### ISSUE TITLE
Suggest a wallet: walletOS

### ISSUE THREAD

**Issue by lukestreckenbach** [ethereum/ethereum-org-website#10004]
### Wallet name

walletOS

### Wallet description

Pine Street Labs’ walletOS is a single API to make blockchain engineering easy. Use a defined set of endpoints for all of your blockchain interactions across 18+ networks. Developers can access a common API interface that abstracts away chain-specific complexities, allowing developers to devote more resources to their core product. 

### Wallet logo

![PSL_Logo_Iconography](https://user-images.githubusercontent.com/70074605/233216485-b0b11158-2c49-4b72-8c6e-b4743025d226.svg)

### Background color for brand logo

#0E1525

### URL to the project

https://www.pinestreetlabs.com

### When did the wallet go live to users?

April 10th, 2023

### Does the wallet have an active development team?

Yes, the Pine Street Labs team actively works on the wallet. You can find our GitHub here: https://github.com/PineStreetLabs, but note that our code is not open source.

### Is the wallet globally accessible?

Yes, the wallet is globally accessible. There are no KYC requirements or geographic limitations.

### Is the wallet available in multiple languages?

walletOS is currently only available in English

### What social links are there for the project?

https://twitter.com/pinestreetlabs
https://www.linkedin.com/company/pine-street-labs/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

No

### What license is the wallet software released under?

N/A

### Who holds the private keys?

walletOS is a non-custodial wallet management tool; users always retain control of their private keys. Users would be able to access their funds even if Pine Street Labs disappeared.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We have undergone an external audit, audit reports are available upon request.

### Has the wallet's smart contract code or security modules been audited?

walletOS is not a smart contract wallet, so we have no smart contract code. Our source code has been audited and audit reports can be delivered upon request.

### Does the wallet have an internal security team?

We rely on external security teams to perform our audits.

### Any other security testing that should be noted?

N/A

### Scam protection?

We don’t have scam protection, but this is less relevant for walletsOS since we only support interaction with certain contracts.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

No, but developers using walletOS can select which RPC endpoints they want to build their application with. walletOS provides interfaces to popular RPC endpoints to make it easy for developers to control their infrastructure 

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

We don't support connecting to any arbitrary application, but we support interaction with specific applications for specific use cases like swapping between assets.

### Does the wallet support staking directly?

Yes, you can refer to our documentation page here: https://docs.pinestreetlabs.com/reference/create_validator

### Does the wallet support swaps directly?

Yes, you can refer to our documentation page here: https://docs.pinestreetlabs.com/reference/swap

### Does the wallet support multi-chain networks?

Yes, you can find the full list of chains we support here: https://docs.pinestreetlabs.com/docs/blockchains

### Does the wallet support Ethereum layer 2 networks?

Yes, we currently support Optimism, Arbitrum, and Polygon. 

### Does the wallet allow the user to customize gas fees?

We currently abstract gas management away so our users do not need to manage it. We plan to support gas fee customization in the near future.

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

We do not allow importing tokens, but users can query for tokens we support.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No, walletOS currently supports creating multi-signature addresses on networks that have native multi-signature support, such as Bitcoin and Cosmos. 

### Does the wallet support social recovery?

No, walletOS does not touch keys and developers can select whatever signing and recovery process they want when building their application with walletOS. 

### Who can the ethereum.org team can contact regarding the wallet in future?

Twitter: @pinestreetlabs
Or
Twitter: @luke_streck
Telegram: @lukestreckenbach

### Does the wallet have a dedicated support team?

Users that are having issues can reach out to Support@pinestreetlabs.com
Support is very fast, users can typically expect a response within 24 hours.

### What educational resources/documentation do you provide to users?

[Documentation](https://docs.pinestreetlabs.com/docs)
[API Reference](https://docs.pinestreetlabs.com/reference/add_signature)
[Guides](https://docs.pinestreetlabs.com/docs/transfer-from-a-bitcoin-multi-signature-wallet)

### Does the wallet have any integrated tools not mentioned above?

Support for decoding transactions
Support for batching transactions
Support for signing a transaction and saving it to be broadcast at a later date
Address validation
Fetching transaction data

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @lukestreckenbach 

I would like to see an audit report here where we asked. Although you state its available upon request, this is the request in that question.

Closing this at this time is the wallet went live ~2 months ago. We do state we expect a wallet to be live for 6 months before consideration: https://ethereum.org/en/contributing/adding-wallets/
