### ISSUE TITLE
Button - Add multi-line support

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10020]
## Description

Add styles on the [button theme configuration](https://github.com/ethereum/ethereum-org-website/blob/dev/src/%40chakra-ui/gatsby-plugin/components/Button.ts) to support multi-lines:
![image](https://user-images.githubusercontent.com/468158/233500824-87b8d2f4-2edf-410a-bc82-354460ac6ae6.png)

## Resources

- [Design System](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=2283-45220&t=4nHkPc8yig1kcYoz-0)

**Comment by pettinarip** [comment]
Hi @sumitshinde-84! thanks for the help but this feature is already under development by @corwintines

**Comment by sumitshinde-84** [comment]
If you have any issues related to frontend, please feel free to let me know. I would be happy to assist you with any problems you may be experiencing

**Comment by TylerAPfledderer** [comment]
@pettinarip @corwintines note that PR #10131 is created to introduce the `Inter` font to prod. Might not make a difference here, but when I checked the visual diff in Chromatic with the "demo" stories, it was showing a significant difference in character width from the font that was previously applied.

**Comment by TylerAPfledderer** [comment]
@pettinarip @corwintines following up on this.

Working on updating the theming for `Button`, and wondering what has been done to resolve this feature?
