### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by CocoUniPass** [ethereum/ethereum-org-website#10047]
### Wallet name

UniPass

### Wallet description

UniPass is a non-custodial smart contract wallet that provides a seedless and gasless user experience. It allows you to have a crypto wallet without the need to remember recovery phrases.

### Wallet logo

UniPass logo：https://lay2.notion.site/UniPass-Media-Kit-5137eb851dba4e798874b256274cf81c

### Background color for brand logo

white

### URL to the project

https://wallet.unipass.id/

### When did the wallet go live to users?

It's now live to users.

### Does the wallet have an active development team?

Yes. Here is the link: https://github.com/UniPassID/

### Is the wallet globally accessible?

Yes, it is. No need to KYC.

### Is the wallet available in multiple languages?

Yes. Now it supports English and Chinese.

### What social links are there for the project?

Twitter: https://twitter.com/UniPassID
Medium: https://medium.com/@unipass
Discord: https://discord.com/invite/XaRMFW85Pg
Landing page: https://unipass.id/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No, it's a web wallet.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No, it's a web wallet.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No, it's a web wallet.

### Is it a hardware wallet?

No, it isn't.

### Is the source code for the wallet fully open-source?

Yes, it is. Here is the link: https://github.com/UniPassID/Unipass-Wallet-Contract

### Who holds the private keys?

UniPass is a non-custodial wallet, so users can access their fund whenever they want. 

UniPass wallet doesn't have the concept of private key. Master key is the execution key of an UniPass account. It is a 2-2 MPC(TSS) key and the 2 slices are generated independently on the client side and server side.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Audit report: https://docs.wallet.unipass.id/audits/overview

### Has the wallet's smart contract code or security modules been audited?

Yes, it has. Here is the Audit report: https://docs.wallet.unipass.id/audits/overview

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, it does.

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No, it isn't. We will support it in the future.

### Does the wallet support multi-chain networks?

Yes. https://docs.wallet.unipass.id/introduction/multi-chain-support

### Does the wallet support Ethereum layer 2 networks?

Yes, it does. https://docs.wallet.unipass.id/introduction/multi-chain-support

### Does the wallet allow the user to customize gas fees?

Yes, it does. https://docs.wallet.unipass.id/introduction/gasless-support

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, it does. https://medium.com/@unipass/fiat-on-off-ramp-feature-now-live-on-unipass-3291185418fc

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

We use 2-2 MCP solution. Here is our technical insights: https://lay2.notion.site/Process-Insight-and-Security-Model-of-UniPass-Wallet-aed04150e8c645399a35ab13d9e98c83

### Does the wallet support social recovery?

Yes, it does.

### Who can the ethereum.org team can contact regarding the wallet in future?

TG: @COCOLin997

### Does the wallet have a dedicated support team?

If users have issues, they can join our discord to ask for help.

### What educational resources/documentation do you provide to users?

https://docs.wallet.unipass.id/intro

### Does the wallet have any integrated tools not mentioned above?

UniPass will soon support transaction batching.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
@CocoUniPass we don't think adding UniPass is appropriate at this time. Some of the concerns we shared as a team were:
- Social media presence is lacking (<300 followers). At least on the Twitter page that the wallet links out to. I see this Twitter profile we land on tells you to go to another profile, but this flow seems weird from the get go and something similar to a broken experience with the wallet
- We have concerns about the guardian structure. There is no password requirements (password1 was accepted, this is very insecure). Adding guardians or removing them was very confusing and hard to do.
- Still share security concerns with the guardian flow, password, and being tied to specific vendors for email addresses. While you could register with a custom email, your guardian email had to be a specific vendor which is concerning. 

For now, going to reject this. If some of the above is addressed, or if you can share more information feel free to reopen.
