### ISSUE TITLE
Feature request: Add `reorg-intl` script to commit hook

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#10055]
### Is your feature request related to a problem? Please describe.

Currently, when English strings are removed from the project, their translated counterparts are left in. At the moment we have a script (`reorg-intl`) which catches and removes them. The issue that comes up is during importing/updating translated content, we run this script at the end and a bunch of files are added from other languages to the import. Ideally, when running that script on a translation import this would only affect the new files imported as the rest are up to date. 

### Describe the solution you'd like

Add the reorg-intl script to git commits so that when an English string is removed from the codebase, the translated strings are also removed.

### Describe alternatives you've considered

Run this script before imports and get someone to merge. Not ideal though as this would be quite manual and easy to forget.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
@corwintines Is this still an issue that needs fixing?

**Comment by wackerow** [comment]
Looks like this is no longer an issue... will close out for now and can re-open if needed.
