### ISSUE TITLE
Several typos on glossary page

### ISSUE THREAD

**Issue by jgeffrard** [ethereum/ethereum-org-website#10079]
### Describe the bug

Just a couple of typos I noticed (these were the most obvious--there were other ones but those were arguable and my intention is not to nitpick so I left it alone).

I can work on this issue.

### To reproduce

1. Go to 'https://ethereum.org/en/glossary/'
2. See typos as per screenshots.

### Expected behavior

No typos

### Screenshots

Should be "...unit of information that includes an..."

![includes not include](https://user-images.githubusercontent.com/51290481/234642186-43bcff70-75a1-42f8-a43c-a6107d1113f9.PNG)

Should be "(e.g. billions of years)" instead of "(eg. billions of years)" as e.g. is the format used across the entire Ethereum glossary.

![e g  not eg](https://user-images.githubusercontent.com/51290481/234642858-f4967981-bc12-4af7-b9e0-bc521f2cc1f4.PNG)

Should be "total blockchain that subsets of validators can be..."

![that subsets of validators](https://user-images.githubusercontent.com/51290481/234643349-879f17f0-2828-4931-a0a9-b0def95d268c.PNG)

Should be "...(12 seconds) in which new blocks can be"

![in which new blocks](https://user-images.githubusercontent.com/51290481/234661997-6395de88-8ba5-4cee-8aaa-f4d5537b8158.PNG)

### Desktop (please complete the following information)

n/a

### Smartphone (please complete the following information)

n/a

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
All of these make sense, ill assign to you @jgeffrard since you marked you were interested :) Let me know if you need anything.
