### ISSUE TITLE
outdated ethereum PoW reference

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#10092]
### Describe the bug

outdated PoW reference

### To reproduce

1. Go to https://ethereum.org/en/roadmap/vision/
2. read the text

### Expected behavior

> And the underlying proof-of-work consensus algorithm that keeps Ethereum secure and decentralized has a big environmental impact.

text on the [vision page](https://ethereum.org/en/roadmap/vision/) references PoW. should be replaced with another challenge we want to address? or at least removed

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by jayanth-kumar-morem** [comment]
Hey @tvanepps,

I would like to take this one up. Can you please assign me to this ?

CC: @chuyeow @matthieu @shazow @jpanachida
