### ISSUE TITLE
VfSE Lottery - All For One

### ISSUE THREAD

**Issue by GitHubPete** [ethereum/ethereum-org-website#10099]
### Name

VfSE Lottery - All For One

### Description

Game of chance that helps to found scientific research. Guaranteed win in each round with 100% of the prize pool. Winner gets 90% of ETH collected in a single round + 10% of the corresponding amount in VfSE tokens.

### Logo

![all-for-one-club-logo](https://user-images.githubusercontent.com/35796092/235356095-3bc4b725-2f5c-44a1-8258-5e04f736fa37.png)

### Brand color

#6239bd

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://etherscan.io/address/0x4b675B8429224134c05d1D519Eb07b4448fEBbE9

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

https://etherscan.io/address/0x4b675B8429224134c05d1D519Eb07b4448fEBbE9#code

### Can a user access the dapp without creating an account?

Yes.

### Are dapp funds non-custodial?

Yes.

### Do you offer community support?

Yes.

### Describe any geographical restrictions on usage of your dapp

No restrictions. 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
I don't think a lottery app is appropriate for listing on ethereum.org. Going to close this out.

**Comment by GitHubPete** [comment]
OK. Thanks anyway.
