### ISSUE TITLE
FlashFlow Protocol For Leveraged trading on Ethereum

### ISSUE THREAD

**Issue by punkuni** [ethereum/ethereum-org-website#10102]
### Name

FlashFlow Protocol
[](https://flashflow.org)

### Description

FlashFlow is an ETH-based protocol for on-chain trading with leverage, utilizing the liquidity of available lending protocols and flash loans. FlashFlow was designed for traders, allowing them to enjoy permissionless trading using self-custody wallets, $10B DeFi market liquidity, and the convenience of CEX-like UI.

**How does it work?**

The general principle of FlashFlow can be succinctly summarized in six steps (commissions will be omitted for simplicity):

1. The user selects the collateral for the trade, the desired leverage, and the asset they wish to long/short. For example, a user may opt to open a long position on wBTC, using 1,000 USDT of their own funds and a 10x leverage. Given the 10x leverage, the total order size amounts to 10,000 USDT. 
2. The protocol then borrows a flash loan for the outstanding 9,000 USDT. 
3. The 10,000 USDT is converted into wBTC at the most favorable rate available across various DeFi liquidity pools (Uniswap, 1inch, Paraswap, etc.). 
4. The wBTC is subsequently deposited as collateral into a lending protocol, such as AAVE or Compound. 
5. With wBTC as collateral, the protocol borrows 9,000 USDT. 
6. Using borrowed 9,000 USDT the protocol repays the flash loan.

### Logo

![ff-logo-full](https://user-images.githubusercontent.com/127932651/235436924-87c6086a-65f1-46c1-9132-f20dfd359ef0.png)

![ff-logo-full](https://user-images.githubusercontent.com/127932651/235436938-8f53d4d6-976f-4063-9759-0b1df8d4be6c.svg)

### Brand color

#6c47ff

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/Flash-Flow

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

There is no formal audit so far. As the project is in the active stage of development, there isn't much point in waiting for a formal audit. It can last several months and completely freeze the development process. We've obtained an informal audit from employees of a world-famous smart contract auditing company to ensure the security of our smart contracts. The major part of the protocol is based on other widely used protocols, such as 1inch, AAVE, Compound, Balancer, and others, which undergo regular audits and have been used for years. The team stakes its reputation on the security of this project. The team has solid experience building such WEB3 projects as Tornado Cash Nova and NFT Multisender.

### Can a user access the dapp without creating an account?

Yes

### Are dapp funds non-custodial?

Self-custodian

### Do you offer community support?

Yes.
Telegram: https://t.me/flashfloworg
Discord invite link: https://discord.com/invite/uUaaMFmPQx
Help: https://flashflow.gitbook.io/

### Describe any geographical restrictions on usage of your dapp

N/A at the moment

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @punkuni! Sorry for delay here. Checking this out, [the repo you've provided](https://github.com/Flash-Flow) gives me a 404. I didn't see a URL, but I think this is it: https://flashflow.org/ Is that correct?

Were you looking to list this on the [/dapps](https://ethereum.org/en/dapps) page?

I've assigned for a product review in the meantime

**Comment by konopkja** [comment]
Hello there,

sorry for delay and here are my thoughts:

1.  link to GH provides 404
2. twitter acc inactive since mid 2023
3. dapp doesnt support L2s
4. no proposal how this should be incorporated to ethereum.org

for those reasons I think this listing should be closed. Maybe a new issue with updated info and clearer vision how and where this is beneficial to the readers of ethereum.org can be proposed.
