### ISSUE TITLE
Flashflow Protocol

### ISSUE THREAD

**Issue by ads-media-helper** [ethereum/ethereum-org-website#10103]
### Name

Flashflow Protocol

### Description

As of today, there are several decentralized trading platforms available for margin trading, but they all come with certain disadvantages. Our team has identified these shortcomings as follows:

1. Projects operating exclusively on Layer-2, typically on one or two blockchains
2. Trading platforms that claim to be DEX but in reality some of the important aspects of these platforms are centralized
3. Projects with proprietary liquidity pools, which are susceptible to centralization and manipulation
4. Lack of liquidity and assets for trading
5. Confusing and bad quality user-interfaces

We have developed [FlashFlow](https://flashflow.org/) to fix these issues and provide the best possible experience for secure, convenient, and genuinely decentralized margin trading.

**So, what exactly is the FlashFlow Protocol?**
Top DeFi lending protocols, such as AAVE and Compound, have a combined total value locked (TVL) of approximately $10 billion, and this is only on the Ethereum blockchain. However, it has not been possible to use these platforms for margin trading — until now.

**FlashFlow unlocks and combines liquidity from top lending protocols for margin trading, representing the next step in the evolution of the DeFi market. We are building on top of existing protocols, utilizing their liquidity and features, and adding up to 10x leverage for trading.**

### Logo

![FF-Logo-fullsize](https://user-images.githubusercontent.com/70171433/235452154-c339b342-c3fc-48e4-b4fb-41c512f4958f.svg)

### Brand color

Purple

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/Flash-Flow/core-contracts

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

There is no formal audit so far. As the project is in the active stage of development, there isn't much point in waiting for a formal audit. It can last several months and completely freeze the development process. **We've obtained an informal audit from employees of a world-famous smart contract auditing company to ensure the security of our smart contracts**. 

The major part of the protocol is based on other widely used protocols, such as 1inch, AAVE, Compound, Balancer, and others, which undergo regular audits and have been used for years. The team stakes its reputation on the security of this project

### Can a user access the dapp without creating an account?

Yes. A user has to connect his wallet to start using the product.

### Are dapp funds non-custodial?

Yes. The flashflow protocol doesn't have an access to the clients funds.

### Do you offer community support?

Yes, we support our users:
1. Telegram chat - https://t.me/flashfloworg
2. Twitter - https://twitter.com/flashfloworg
3. Discord - https://discord.gg/nPCKHB8UqD

### Describe any geographical restrictions on usage of your dapp

We don't support users from several countries such as The North Korea, Iran, Afghanistan, Syria and so on.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Hey, thanks for opening this issue.

Unfortunately, flashflow/zrex does not meet our current listing criteria due to a lack of provable security for users. Please feel free to open a new issue when this changes.
