### ISSUE TITLE
Update energy consumption page to include University of Cambridge research

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#10109]
### Is your feature request related to a problem? Please describe.

Discovered some new data on Etheruem's energy consumption in [a New Scientist article](https://www.newscientist.com/article/2369304-cryptocurrency-ethereum-has-slashed-its-energy-use-by-99-99-per-cent/). At a glance, the research seems pretty rigorous and might be a useful addition or replacement for some of the existing resources to our energy consumption page:

- New Scientist article: https://www.newscientist.com/article/2369304-cryptocurrency-ethereum-has-slashed-its-energy-use-by-99-99-per-cent/
- University of Cambridge / Cambridge Centre for Alternative Finance's research: https://ccaf.io/cbnsi/ethereum/comparisons

### Describe the solution you'd like

Incorporate [the CCFAC's energy consumption comparison figures](https://ccaf.io/cbnsi/ethereum/comparisons) onto [the energy consumption page](https://ethereum.org/en/energy-consumption/).

Specifically, we should use the following figures:

Gold mining @ 131 TWh
Bitcoin @ 131 TWh
Data centres @ 200 TWh
Data Networks @ 250 TWh
Netflix @ 0.451 TWh
AirBnB @ 0.02 TWh

### Describe alternatives you've considered

Measure everything using the classic British kettle ratio 🤭:

![Screenshot 2023-05-02 at 10 50 07](https://user-images.githubusercontent.com/62268199/235635182-29da3456-46cc-499c-9d2b-c30a7640a647.png)

**Comment by thisissamridh** [comment]
Hey @minimalsm 
Can i be assigned to this issue

**Comment by minimalsm** [comment]
Hey @thisissamridh, looks like @jmcook1186 already opened a PR here.

Sorry for missing this, feel free to help review #10120 ❤️

**Comment by corwintines** [comment]
Going to close this out with the above PR merged
