### ISSUE TITLE
Migrate Ethereum Whitepaper

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1011]
**Is your feature request related to a problem? Please describe.**
Whitepaper is currently hosted at https://github.com/ethereum/wiki/wiki/White-Paper - a wiki that is largely outdated (& is currently in the process of being migrated).

There is significant search volume for the Ethereum Whitepaper (~1K – 10K per month):
![Image 2020-05-07 at 1 01 32 PM](https://user-images.githubusercontent.com/8097623/81339445-0fd4fc80-9063-11ea-94aa-a0ca1d24ec75.png)

The Whitepaper is one of the most searched-for terms on our site search & currently we do not provide much reference to it.

**Describe the solution you'd like**

- [x] Migrate the Whitepaper from the [old wiki](https://github.com/ethereum/wiki/wiki/White-Paper) to ethereum.org/whitepaper
- [x] Add some additional context at the top of the page, e.g. some pretext that explains this is a historical paper, Ethereum has evolved since, where to learn more or see latest status / updates
- [x] Add link to the footer (under developers section)
- [ ] Update the wiki Whitepaper to link to ethereum.org/whitepaper (GH 301 redirects are not possible)

**Describe alternatives you've considered**

Leave as is.

**Additional context**

None.

**Comment by ChrisChinchilla** [comment]
@samajammin I'm a bit late here, but I also wondered if we should as a separate task now update the whitepaper at all? There have been a couple of small issues logged over the years. Or is it best left as is in perpetuity?

**Comment by samajammin** [comment]
@ChrisChinchilla I'm not opposed to that, thought we'll have to think through the best way to show we've made edits. Let's open those as separate issues though.
