### ISSUE TITLE
Add Origin Dollar dapp

### ISSUE THREAD

**Issue by sumpg41** [ethereum/ethereum-org-website#10128]
### Name

Origin Dollar

### Description

The Origin Dollar [dapp](https://app.ousd.com/) is the gateway to obtaining [Origin Dollar](https://ousd.com/) (OUSD), the first stablecoin that earns yield while sitting in your wallet. The current OUSD collateral, yield, and yield strategies are always available in real time via the OUSD [analytics page](https://www.ousd.com/analytics). 

### Logo

![ousd](https://user-images.githubusercontent.com/80375331/236335225-2ff7590c-942f-419b-8b3c-8d060fe95992.svg)

### Brand color

0074F0

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/OriginProtocol/

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Origin currently has a continuous auditing agreement with [OpenZeppelin](https://openzeppelin.com/) to constantly review 100% of our smart contract changes. OpenZeppelin has audited Coinbase, Ethereum, Aave, Compound, and other leading projects. They are one of the most trusted auditing firms in the industry and we are thrilled to count them as part of our extended team.

OUSD has also been thoroughly audited by multiple other top security firms including [Trail of Bits](https://www.trailofbits.com/), [Solidified](https://solidified.io/), and [Certora](https://www.certora.com/). Their findings are available via the [OUSD docs](https://docs.ousd.com/security-and-risks/audits).

### Can a user access the dapp without creating an account?

A user can simply connect their Web3 wallet to the Origin Dollar dapp to utilize the technology. No account required! 

### Are dapp funds non-custodial?

Funds obtained via the Origin Dollar dapp are completely non-custodial. Users retain their keys the entire time. 

### Do you offer community support?

Support on any Origin Protocol product is available 24/7 via the official Origin [Discord](https://discord.com/invite/ogn). Alternatively, you may email support@originprotocol.com with your issue. 

### Describe any geographical restrictions on usage of your dapp

Usage of the Origin Dollar and the Origin Dollar dapp is globally accessible, there are no restrictions. Origin's vision is to onboard the next 100M users to crypto.

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by sumpg41** [comment]
peter from Origin Protocol here! Also available to clear up any questions via peter@originprotocol.com

**Comment by sumpg41** [comment]
Hey @wackerow, would it be possible to have the OUSD dapp added? It is 95% of the same code as [OETH](https://github.com/ethereum/ethereum-org-website/pull/10426)!

**Comment by corwintines** [comment]
Hey @sumpg41 

When looking into Origin Dollar, I noticed liquidity/TVL is quite low: https://defillama.com/protocol/origin-dollar

I don't think this amount of liquidity is enough to feel confident listing Origin Dollar. Going to close this out, but if I have missed something on how TVL works here please let me know.

**Comment by sumpg41** [comment]
> Hey @sumpg41
> 
> When looking into Origin Dollar, I noticed liquidity/TVL is quite low: https://defillama.com/protocol/origin-dollar
> 
> I don't think this amount of liquidity is enough to feel confident listing Origin Dollar. Going to close this out, but if I have missed something on how TVL works here please let me know.

Hi @corwintines, we actually received some feedback on this from @wackerow a little while back and decided to submit listing Origin Protocol as a whole (combines [OUSD](https://etherscan.io/address/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86) + [OETH](https://etherscan.io/address/0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3)) instead of listing Origin Dollar and Origin Ether independently. The combined [TVL is $79m](https://defillama.com/protocol/origin-defi) which is about double some of the other protocols listed on the Ethereum.org dapps page. We submitted a PR for this here if you could please take a look: https://github.com/ethereum/ethereum-org-website/pull/10953
