### ISSUE TITLE
Add LearnWeb3 to learn by codnig section

### ISSUE THREAD

**Issue by haardikk21** [ethereum/ethereum-org-website#10138]
### Dev tool name

LearnWeb3

### Dev tool description

LearnWeb3 is a free, high quality education platform to go from zero to hero in web3 development. 

### When did the dev tool go live?

January 2022

### Where do you think this page should be shown?

https://ethereum.org/en/developers/learning-tools/

### Is the product open source?

Yes

### GitHub URL

https://github.com/LearnWeb3DAO

### Documentation URL

 https://www.learnweb3.io/

### Additional context

Logo: https://learnweb3.io/logo.png

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by veera6513** [comment]
can you pls assign this issue to me?i am interested to work on this

**Comment by kapoorsaumitra** [comment]
Hi there! I'm eager to get involved and contribute to the project. Could you please assign me this task to work on? Thanks!

**Comment by wackerow** [comment]
@haardikk21 Apologies for delay... I see https://github.com/LearnWeb3DAO linked to from the website, is this the correct location? Curious if you have any rough usage numbers for this so far? Hadn't see it yet, looks pretty cool

@veera6513 You were first to offer to help, would you still be interested in putting a PR up for this? Will assign for now, but can re-assign if you're busy

**Comment by haardikk21** [comment]
> @haardikk21 Apologies for delay... I see https://github.com/LearnWeb3DAO linked to from the website, is this the correct location? Curious if you have any rough usage numbers for this so far? Hadn't see it yet, looks pretty cool
> 
> @veera6513 You were first to offer to help, would you still be interested in putting a PR up for this? Will assign for now, but can re-assign if you're busy

Hey! 

The GitHub is correct, yes - most of the content is on the website directly though - we moved away from content editing on GitHub and instead are able to edit content directly on the website now. 

It's grown a lot since the time of creating this issue. We've served 200k+ students going through us over the last ~2ish years, and about ~750k badges issued (with >75% of them minted on-chain).

**Comment by corwintines** [comment]
This seems good to me. I see @wackerow has this open as a good first issue. Would you like to add it @haardikk21 or would you like to leave it open for someone else?

**Comment by Shiva-Sai-ssb** [comment]
@corwintines
I can work on this. Can you please assign this issue to me?

**Comment by minimalsm** [comment]
Hey @Shiva-Sai-ssb, sorry for the delay. Thanks for offering to help, I've assigned you :)
