### ISSUE TITLE
EVM

### ISSUE THREAD

**Issue by Chatchawa-is** [ethereum/ethereum-org-website#10153]
### Tutorial title

EVM

### Tutorial description

Learning EVM

### Tutorial tags

EVMd

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by qbzzt** [comment]
@Chatchawa-is , what exactly do you want to teach about the EVM?

**Comment by Chatchawa-is** [comment]
@qbzzt Hi, Guy; I would like to teach EVM to make the smart contract and develop the DApp.

**Comment by qbzzt** [comment]
Do you mean to write a tutorial about how to write a program that runs on the EVM, similar to https://ethereum.org/en/developers/tutorials/hello-world-smart-contract-fullstack/? What's going to be different about your tutorial? Are you going to write it in a language that is closer to the EVM such as [Huff](https://docs.huff.sh/tutorial/overview/) or [Yul](https://coinsbench.com/beginners-guide-to-yul-12a0a18095ef)?

**Comment by wackerow** [comment]
@Chatchawa-is Will echo @qbzzt comments; The tutorials section is already quite overwhelming so ideally any additions have a differentiating factor and aren't just repeating what is already there. Let us know if you have specific thoughts on this, else I'll go ahead and close this next time I circle through.

**Comment by corwintines** [comment]
Going to close this out. If you have more of an idea for what this content would be @Chatchawa-is please do open again.
