### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by Alston333** [ethereum/ethereum-org-website#10155]
### Wallet name

ECHOOO

### Wallet description

Echooo is a hybrid wallet that supports both EOA and AA accounts, making it the safest decentralized wallet on the market.

### Wallet logo

![IP_正面_透明底](https://github.com/ethereum/ethereum-org-website/assets/121208805/e66e2821-6479-40a4-819a-51604e58fa6a)

### Background color for brand logo

1763FF

### URL to the project

www.echooo.xyz

### When did the wallet go live to users?

03.31.2023

### Does the wallet have an active development team?

https://github.com/HEchooo

### Is the wallet globally accessible?

The service is available worldwide except for mainland China

### Is the wallet available in multiple languages?

English and Traditional Chinese，more to come in future

### What social links are there for the project?

Twitter:https://twitter.com/echooo_wallet
Telegram group:https://t.me/Echooowallet
Discord:https://discord.gg/XnhHJn9r

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Both IOS and Android
IOS:https://apps.apple.com/us/app/echooo-wallet/id6446883725
Android:https://play.google.com/store/search?q=echooo+wallet&c=apps

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Not ready now, It will release on June.2023

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Not ready now, It will release on June.2023

### Is it a hardware wallet?

NO

### Is the source code for the wallet fully open-source?

NO

### Who holds the private keys?

Echooo is non-custodial wallet ,users own their assets forever, only users can access to their private keys, we use MPC TSS to protect their Key, If the company were to disappear, users still be able to access their funds

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

[Smart_Contract_Audit_-_Echooo_Wallet_-_2nd_Audit_-_v221229 (2).pdf](https://github.com/ethereum/ethereum-org-website/files/11430221/Smart_Contract_Audit_-_Echooo_Wallet_-_2nd_Audit_-_v221229.2.pdf)

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

LIDO

### Does the wallet support swaps directly?

Uniswap/Paraswap

### Does the wallet support multi-chain networks?

ETH/BSC/POLYGON https://www.echooo.xyz/TechGuide

### Does the wallet support Ethereum layer 2 networks?

ZkSync/Arbitrum

### Does the wallet allow the user to customize gas fees?

YES

### Does the wallet support withdrawals to fiat?

NO

### Is the wallet a multi-signature wallet?

YES，https://www.echooo.xyz/TechGuide

### Does the wallet support social recovery?

YES，https://www.echooo.xyz/TechGuide

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram@linnannan
Mail:lnn@echooo.co

### Does the wallet have a dedicated support team?

Telegram group:https://t.me/Echooowallet
Discord:https://discord.gg/XnhHJn9r
24X7/as soon as possible

### What educational resources/documentation do you provide to users?

https://www.echooo.xyz/Support

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Alston333** [comment]
Anyone to help?

**Comment by corwintines** [comment]
Hey @Alston333 

We currently don't list projects less than 6 months old: https://ethereum.org/en/contributing/adding-wallets/

Feel free to open this up in the future for consideration :)

**Comment by Alston333** [comment]
Hi Corwin
We have already been online for 6 month
And I submitted a new link:https://github.com/ethereum/ethereum-org-website/issues/11034
Please check it
Best Regards 
Alston-Head of Business Development
ECHOOO WALLET 
***@***.*** 
***@***.***
UTC+8 
[image]
