### ISSUE TITLE
Legacy link on the footer needs to change the label to "Learning hub"

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#10156]
### Describe the bug

With the recent update on the learning page to be the "learning hub" the link in the footer to the https://ethereum.org/en/learn/ still has the label:
"[Community guides and resources](https://ethereum.org/en/learn/)"

needs to change to "Learn hub"
 "[Learn hub](https://ethereum.org/en/learn/)"

### To reproduce

1. Go to 'footer'
2. Click on 'Community guides and resources'
3. opens  to the learn hub
4. 

### Expected behavior

1. Go to 'footer'
2. Click on 'Learn hub'
3. opens  to the learn hub
4. 

### Screenshots

![Screen Shot 2023-05-09 11 10 29 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/f6880552-9a55-4545-b27a-c49da9722fe8)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by SimardeepSingh1450** [comment]
@nloureiro I'd like to work on this issue please assign to me.

**Comment by SimardeepSingh1450** [comment]
@nloureiro thanx for the assignment, will raise a pr soon.

**Comment by SimardeepSingh1450** [comment]
@nloureiro I have fixed it and opened a pr, please review and merge at #10167 .
