### ISSUE TITLE
fix japanese typo

### ISSUE THREAD

**Issue by adust09** [ethereum/ethereum-org-website#10157]
### Describe the bug

There is a typo on the Japanese page.
This is a kanji conversion error.

### To reproduce

1. Go to 'https://ethereum.org/ja/community/grants/#broad-ethereum-ecosystem'
2. There is a typo in the bottom sentence.

### Expected behavior

❌女性(woman)
⭕️助成（grant)

### Screenshots

<img width="795" alt="スクリーンショット 2023-05-09 20 47 03" src="https://github.com/ethereum/ethereum-org-website/assets/47593288/3f0b2999-8b7f-4a11-80c8-4c8585ff9bd6">

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by nhsz** [comment]
Fixed by #10168
