### ISSUE TITLE
Suggest a developer tool for ethereum-website : Gitpod

### ISSUE THREAD

**Issue by SimardeepSingh1450** [ethereum/ethereum-org-website#10166]
### Dev tool name

Gitpod

### Dev tool description

Gitpod is an online platform used for easy development of open-source projects by selecting the repo on the go. Instead of setting up code locally contributors can start contributing fast without having issues setting-up project in local dev environment.

### When did the dev tool go live?

Around April,2019

### Where do you think this page should be shown?

I want to add this tool's **direct open new workspace link** or **gitpod.yml config file** in the setup documentation under the **Set up your local environment** part for users to start using development on gitpod.

### Is the product open source?

Yes

### GitHub URL

https://github.com/gitpod-io/gitpod

### Documentation URL

https://github.com/gitpod-io

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by SimardeepSingh1450** [comment]
Possible problems people face :
1.Javascript heap out of memory (Due to low end devices)
2.Unable to properly setup or install packages
3.Have problem raising pr

**Comment by corwintines** [comment]
Thanks @SimardeepSingh1450 

Looking at Gitpod, I am noticing this is a web based IDE. However, there are no templates here for major languages used in Ethereum (ex: Solidity, Vyper, Yul), and no workflows for deployment of smart contracts. This doesn't really show developer tools for an Ethereum developer in this case, which is the purpose of this page.

I would put this in the same bucket as a JetBrains or a VSCode, which we wouldn't list for the same reason. Remix is also an IDE, but is focused around tooling for smart contracts and deployment processes for those smart contracts to blockchain networks. I am not seeing something that would make this more like Remix than the other IDE's, so going to close this out and reject it.
