### ISSUE TITLE
Feature request : Regarding the footer links order in Learn Section

### ISSUE THREAD

**Issue by SimardeepSingh1450** [ethereum/ethereum-org-website#10171]
### Is your feature request related to a problem? Please describe.

Continuing the discussion from the previous closed pr @nloureiro @nhsz  :
![conversation-for-footer-links-change](https://github.com/ethereum/ethereum-org-website/assets/92221517/e9f823f5-c2b7-488b-b04b-1ac846956eb4)

### Describe the solution you'd like

Changing the links in footer section in **Learn** part according to order in which the links are present in header section.

### Describe alternatives you've considered

No alternative.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by nhsz** [comment]
cc @minimalsm @konopkja

**Comment by minimalsm** [comment]
Yeah makes sense to me. Thanks for raising @SimardeepSingh1450. I've assigned you, let us know if you need any help 🤘

**Comment by SimardeepSingh1450** [comment]
will raise a pr soon, thnx for the assignment @minimalsm

**Comment by SimardeepSingh1450** [comment]
I have ordered the links and raisd the pr at #10175 @minimalsm @nhsz @nloureiro

**Comment by nhsz** [comment]
Fixed by #10175
