### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by yash251** [ethereum/ethereum-org-website#10184]
### Describe the bug

Found a deadlink for Verifying the source code of Ethereum smart contracts

### To reproduce

1. Go to 'https://ethereum.org/en/developers/docs/smart-contracts/verifying/#further-reading'
2. Click on '[How to verify the source code of Ethereum smart contract(opens in a new tab)↗](https://developpaper.com/how-to-verify-the-source-code-of-ethereum-smart-contract/)'
3. See error

### Expected behavior

It should point to new valid resource

### Screenshots

<img width="1440" alt="Screenshot 2023-05-11 at 6 13 06 PM" src="https://github.com/ethereum/ethereum-org-website/assets/47234407/588ce2f3-5bc3-46d2-8294-4ca7113ad7b6">

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by yash251** [comment]
assign me this issue

**Comment by wackerow** [comment]
Hey @yash251, I'm not sure this is an issue at this point. 

```markdown
## Further reading {#further-reading}

- [Verifying contract source code](https://programtheblockchain.com/posts/2018/01/16/verifying-contract-source-code/)
```

This is the only link I see which leads to a functional link. Going to close this out, but please feel free to reopen and clarify if I've missed something, thanks!
