### ISSUE TITLE
Add/modify button variants to match the DS

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10186]
## Description

Update current variants to match the variants in the DS.
- Solid
- Outline
- Ghost
- Link

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/6ae64a80-d626-434b-b678-59808d0e80a3)

## Resources

- [Design System](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=545-16075&t=LQh1cuCNIFQwZyIg-0)

**Comment by SimardeepSingh1450** [comment]
I'd like to work in this issue please assign me.

**Comment by TylerAPfledderer** [comment]
Commenting for assignment. 💪🏼
