### ISSUE TITLE
Bug report: missing `Smart Contracts` link in footer `Learn` section

### ISSUE THREAD

**Issue by nhsz** [ethereum/ethereum-org-website#10201]
### Describe the bug

Links from `Learn` section in the footer (bottom screenshot below) follow the same links and same order from `Learn` menu (top screenshot below), but `Smart Contracts` link is missing in footer list.

### To reproduce

1. Go to any [ethereum.org](https://ethereum.org) page
2. Check `Learn` menu links and see `Smart Contracts` link after `What is Web3?`
3. Scroll down to the footer and check `Smart Contracts` link is missing

### Expected behavior

Add `Smart Contracts` link to `/smart-contracts/` page in the footer `Learn` section, after `What is Web3?`

### Screenshots

<img width="639" alt="Screen Shot 2023-05-12 at 13 50 15" src="https://github.com/ethereum/ethereum-org-website/assets/948922/e98d8e5f-4afd-434d-8462-9ad8c26cdad1">

<img width="302" alt="Screen Shot 2023-05-12 at 13 50 30" src="https://github.com/ethereum/ethereum-org-website/assets/948922/6b94097c-ca82-44c5-8c25-2184f5c64a50">

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by HassanTanveer** [comment]
Hey, please assign this issue to me
