### ISSUE TITLE
Suggest a developer tool - Listing an Oracle

### ISSUE THREAD

**Issue by ed-umb** [ethereum/ethereum-org-website#10202]
### Dev tool name

Umbrella Network

### Dev tool description

Umbrella Oracle is a decentralized oracle which leverages a network of validators to perform off-chain computation while securing data on-chain.
https://umb.network/

### When did the dev tool go live?

Sep 2020

### Where do you think this page should be shown?

In src/content/developers/docs/oracles/index.md under the _Use blockchain oracles {#use-blockchain-oracles} section.

### Is the product open source?

Yes

### GitHub URL

https://github.com/umbrella-network

### Documentation URL

https://umbrella-network.readme.io/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Hey @ed-umb

Would you like to open a PR for adding this link?

**Comment by corwintines** [comment]
This seems to be abandoned. Feel free to reopen if you would like to add this information @ed-umb
