### ISSUE TITLE
Bug report: Discord link at Get in Touch section on how to translate tutorial is broken

### ISSUE THREAD

**Issue by megatheikal** [ethereum/ethereum-org-website#10205]
### Describe the bug

The link of discord at Get In Touch section on https://ethereum.org/en/contributing/translation-program/how-to-translate/ is missing.

### To reproduce

1. Go to 'https://ethereum.org/en/contributing/translation-program/how-to-translate/'
2. Scroll down to 'Get in Touch' section
3. Click on anchor link 'ethereum.org Discord server'
5. See error

### Expected behavior

When user clicks the anchor link, it should navigate user to Ethereum Organisation Discord server. Currently, the anchor link will navigate https://ethereum.org/en/discord/

### Screenshots

<img width="875" alt="Screenshot 2023-05-13 at 1 56 09 PM" src="https://github.com/ethereum/ethereum-org-website/assets/64621442/7e89240e-b838-4b81-8aa9-221d59c52bf7">

<img width="1440" alt="Screenshot 2023-05-13 at 1 57 41 PM" src="https://github.com/ethereum/ethereum-org-website/assets/64621442/01044b3f-e22f-4f33-af15-0abc0f12d3e8">

### Desktop (please complete the following information)

- OS: MacOs 13.3.1
- Browser: Safari
- Version:  16.4

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by megatheikal** [comment]
I would like to work on this issue

**Comment by wackerow** [comment]
Hey @megatheikal! Just commented on the above PR... appreciate you reporting this, and I apologize I didn't see your request to work on this until now. Hopefully we can find something else for you to dive into if you're interested!
