### ISSUE TITLE
section Ethereum in numbers is broken in mobile

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#10217]
### Describe the bug

https://ethereum.org/en/what-is-ethereum/

this page has a section  Ethereum in numbers that has a inline padding to make room in bigger screens

this padding is breaking the layout in xs screens.

![Screen Shot 2023-05-15 02 18 17 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/4b55f6f3-f6ca-4ef8-a32f-fc60d280ae93)
![Screen Shot 2023-05-15 02 18 01 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/e88064c3-1116-468e-942f-27839cbd6cba)

### To reproduce

1. Go to [https://ethereum.org/en/what-is-ethereum/](https://ethereum.org/en/what-is-ethereum/) on a smaller than 400px screen
2. Scroll down to Ethereum in numbers
4. See error the layout not centred

### Expected behavior

all should be on centered

### Screenshots

![Screen Shot 2023-05-15 02 20 59 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/73f87996-72ca-4e7b-b4eb-14dd3d8269e6)
![Screen Shot 2023-05-15 02 20 41 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/4bb455af-7b4f-4cef-ad7a-45af2722c9be)

### Desktop (please complete the following information)

![Screen Shot 2023-05-15 02 18 17 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/ffbfc013-113b-4399-8c56-83599dd84e91)
![Screen Shot 2023-05-15 02 18 01 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/1c3946cc-72bf-498a-99b7-47e60bf70049)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by HassanTanveer** [comment]
Hey, can you assign this issue to me?
