### ISSUE TITLE
Suggestion to list Everstake Institutional ETH Staking on ethereum.org under a staking product or service category

### ISSUE THREAD

**Issue by irina-everstake** [ethereum/ethereum-org-website#10220]
### Project name

Everstake Institutional ETH Staking

### Product type

Staking as a service

### Logo

Please see in the attachment:
![Everstake-Logo-Reversed](https://github.com/ethereum/ethereum-org-website/assets/129885952/ef6d68ec-7cde-4cd8-873c-914e00e11d15)
![Everstake-Logo](https://github.com/ethereum/ethereum-org-website/assets/129885952/b852d9b1-4f55-43d0-8a69-6cf2d199b983)
![Everstake-Logo-Reversed](https://github.com/ethereum/ethereum-org-website/assets/129885952/fd5da9ec-2f21-4a4d-a01c-da40027b2402)
![Everstake-Logo](https://github.com/ethereum/ethereum-org-website/assets/129885952/0f0536c5-d681-4e96-bd1d-93ae1047f822)

### Description

Everstake allows institutions to take advantage of the lowest-risk yield opportunity in Web3, delivering the safest possible ETH staking experience.

Unlock network-leading APR in 1-click, from the #1 performing provider across PoS assets.

### Website

https://eth.everstake.one/

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

In production lifecycle

### What wallets support the product or service?

MetaMask, WalletConnect supported wallets

### If a service, what are the fees associated with using the service?

Our standard commission for Institutional ETH Staking is 10% of rewards-generated.

We offer significant reductions on this standard commission for higher stake amounts. Please contact us for an introductory conversation at [https://calendly.com/ryan-lukas/everstake-meeting](https://calendly.com/ryan-lukas/everstake-meeting) and we would be happy to provide you with a customized proposal.

### What date did the project or service go live?

March 31, 2023. Please find the public announcement on our official Twitter account: https://twitter.com/everstake_pool/status/1641824584096792577

### Has the project undergone an external security audit?

Yes, Everstake Institutional ETH Staking solution was put to the test by the renowned Web3 ecosystem security provider, [Blaize.Security](https://blaize.tech/security/). 

Everstake successfully passed the audit, received 10 out of 10 and earned a “Highly Secure” rating on overall security. You can find a summary of the audit and a detailed audit report here – [https://blaize.tech/clients/smart-contract-security-audit-for-everstake/](https://blaize.tech/clients/smart-contract-security-audit-for-everstake/).

### Has the project undergone any security bug bounties?

No

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Everstake solution is free of trusted/human intermediaries.

### If listing a staking-as-a-service, are users required to sign-up for an account?

No, KYC isn’t required for Everstake Institutional ETH Staking since staker's assets do not go to Everstake validator's account and are delegated directly to the Ethereum network.

### If listing as staking-as-a-service, who has access to the signing keys?

A user has access to signing keys to funds and rewards. Everstake gains access only to ETH2 validators signing keys.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

Yes, a user makes a deposit with pre-setuped 0x01 type credentials.

In order to empower better security functionalities, Everstake uses 2-of-3 Multisig as withdrawal address. Therefore, withdrawal rights will be controlled by 3 participants: _Everstake + Delegator + Backup Delegator’s key_.

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

Currently we use Prysm and Geth only.

### What platforms are supported?

All: Linux, macOS, Windows, iOS, Android

### What user interfaces are supported?

Browser app

### Social media links

Twitter - [https://twitter.com/everstake_pool](https://twitter.com/everstake_pool) 
Discord - [https://discord.gg/PqrbhKNpA5](https://discord.gg/PqrbhKNpA5) 
Medium - [https://medium.com/everstake](https://medium.com/everstake) 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by irina-everstake** [comment]
@wackerow, hello! Could you please review this request? Thanks in advance!

**Comment by wackerow** [comment]
Hey @irina-everstake, thanks for the bump... my apologies as I had typed out a full reply on this but apparently it never sent 😕

Had a few questions here...

---

> Everstake solution is free of trusted/human intermediaries.
> Yes, a user makes a deposit with pre-setuped 0x01 type credentials.
> In order to empower better security functionalities, Everstake uses 2-of-3 Multisig as withdrawal address. Therefore, withdrawal rights will be controlled by 3 participants: Everstake + Delegator + Backup Delegator’s key.

So the 0x01 address is set during setup, correct? And is the user required to point to this 2-of-3 multisig? Is the backup delegator decided by the user?

---

> No, KYC isn’t required for Everstake Institutional ETH Staking since staker's assets do not go to Everstake validator's account and are delegated directly to the Ethereum network.

Just clarifying, does this mean the funds don't go to the _users account with Everstake_, but instead go straight to the deposit contract? So to use this service, a user does not need to create an account with you folks? On your website I can't seem to find a way to sign up without booking a call.

How is the 10% fee taken... is that handled through the multi-sig withdrawal contract (the 0x01 address)?

---

For the SaaS product indicators, from the above I would see these as:
- isFoss: false
- hasBugBounty: false
- pctMajorityClient: 100
- isTrustless: Would say `true`, but sounds like the withdrawal credentials are shared through a multisig? Just looking for some clarification here.
- isSelfCustody: true
- isPermissionless: false, given that an appointment/permission seems to be needed to get started

Lemme know thoughts on above!

**Comment by irina-everstake** [comment]
@wackerow, no worries! I expected you are super busy, that's why try to remind about us. 
Please see all responses below:

> So the 0x01 address is set during setup, correct? And is the user required to point to this 2-of-3 multisig? Is the backup delegator decided by the user?

Yes, setuped for validators before deposit. No, a user give us addresses for Multisig wallet and we create it for him. Yes, Delegator and Backup Delegator’s key owned by customer.


> Just clarifying, does this mean the funds don't go to the users account with Everstake, but instead go straight to the deposit contract? So to use this service, a user does not need to create an account with you folks? On your website I can't seem to find a way to sign up without booking a call.

Correct. The user don’t need to fund any Everstake accounts. Only create request for setup and than deposit straight to the Beacon Chain deposit contract.


> How is the 10% fee taken... is that handled through the multi-sig withdrawal contract (the 0x01 address)?

Yes, fee will be charged from multi-sig account. The user can setup Allowance limit and we’ll charge fees automatically monthly. Or manually approve each charge.

And yes, you indicated all SaaS product indicators correctly. Regarding your comments:

- isTrustless: `true` (user fully control multisig)
- isPermissionless: `false` (need presetup to start)

Thank you :pray:

**Comment by wackerow** [comment]
Hey @irina-everstake, thanks for the update. Looks like we're checking the technical boxes.

Wanted to note some concerns though, when looking at the web interface, related to inaccurate or outdated information. ie:

> Since withdrawals from the beacon chain are not yet enabled,

> However, the output of these awards is not yet available as of January 2023 – we are waiting for updates from the platform.

Noticed a handful of statements around this... with staking being the core of the entire service, outdated information like this adds a lot of confusion for users.

For the sake of users who arrive here, I'd like to just request we tidy up the content on the site to make sure info is up-to-date and as accurate as possible before being listed on ethereum.org. Would anyone be able to address this?

**Comment by irina-everstake** [comment]
Hello, @wackerow! Thanks so much for flagging this. 
We will fix everything and I will let you once ready.

Kind regards,
Irina

**Comment by irina-everstake** [comment]
Hello! We are working on the fixes mentioned above.
I will circle back with the updates soon.

**Comment by irina-everstake** [comment]
Hello! We are working on the fixes mentioned above.

**Comment by wackerow** [comment]
@irina-everstake or @omykhailovskyi, is there a proper landing page for users who would like to stake 32 ETH in a dedicated validator account? The above link (https://eth.everstake.one/) yields this:

<img width="1486" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/4780740b-3a56-4fe2-9268-aae1ca34c9f4">

The label "Withdraw multisig" and the warnings make me feel like this isn't the right place, and there is still mention of a "pool fee". I clicked "ETH STAKING" at the top and it brought me to three options:

<img width="1357" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/65f68855-3cd7-4a0e-9942-116c5d0580b7">

Clicking on the middle option I end up on https://everstake.one/institutional-staking which has no mention of Ethereum. Looks like the only way to set this up is to contact you folks directly, is that correct?

**Comment by omykhailovskyi** [comment]
Hey, @wackerow 
Sure.
Basically we configure specific pools for our Institutional clients based on their volumes.
Here is an example pool that we configured for one of our clients: https://eth.everstake.one/0x995FC235f0051cDe7Cc53B6858D3688B96c3D915/dashboard

**Comment by wackerow** [comment]
@omykhailovskyi Okay, few clarifying question if I may... 
- Can users set this up on their own or do they need to contact you folks to get started?
- Are the withdrawal credentials set to the users address?
- Can the user trigger an exit on their own? (ie. with a pre-signed exit message, or by holding the keys to generate one?

**Comment by omykhailovskyi** [comment]
Answering questions:
1. Users should contact Everstake team
2. Yes
3. Yes

Let me describe you the current flow:
1. Everstake discusses with customer the amount of stake customer wants to stake
4. User creates a Safe Wallet for further staking (we recommend use multisig wallet such as Safe)
5. Everstake prepares all infrastructure for agreed number of validator keys
6. Everstake sets Customer's Safe address as a Withdraw Authority for all customer's validators during setup and informs customer when all is ready
7. Customer stakes multiples of 32 ETH
8. When all validators becomes active, after 256 epochs, Everstake prepares exit messages so customer will be able to stop validators from Everstake's UI
9. Everstake provides an alternative way to stop customer's validators using offline exit tool and send exit messages for all customers validators in encrypted way, so customer will be able to exit his validators even without Everstake's UI

**Comment by omykhailovskyi** [comment]
Hey, @wackerow 
Feel free to reach me if you have any additional questions.
Thank you in advance!

**Comment by omykhailovskyi** [comment]
Hey, @wackerow 
Hope you are doing well.
I would really appreciate it if you can provide an update here.
Happy to answer any open questions if you have such.

**Comment by omykhailovskyi** [comment]
Hey, @wackerow 
Thanks for reply.
All is fine, just one change:
Need to replace Discord link to next one: "https://discord.gg/NvcW47V3Xb"

`    {
      "name": "Everstake Institutional",
      "imageName": "Everstake",
      "hue": 43,
      "launchDate": "2023-03-31",
      "url": "https://eth.everstake.one/",
      "audits": [
        {
          "name": "Blaize",
          "url": "https://blaize.tech/clients/smart-contract-security-audit-for-everstake/"
        }
      ],
      "minEth": 32,
      "additionalStake": null,
      "additionalStakeUnit": null,
      "monthlyFee": 10,
      "monthlyFeeUnit": "%",
      "isFoss": false,
      "hasBugBounty": false,
      "isTrustless": true, 
      "isPermissionless": false,
      "pctMajorityExecutionClient": 100,
      "pctMajorityConsensusClient": 100,
      "isSelfCustody": true,
      "platforms": ["Browser"],
      "ui": ["GUI"],
      "socials": {
        "discord": "https://discord.gg/NvcW47V3Xb",
        "twitter": "https://twitter.com/everstake_pool",
        "medium": "https://medium.com/everstake"
      },
      "matomo": {
        "eventCategory": "StakingProductCard",
        "eventAction": "Clicked",
        "eventName": "Clicked Everstake Institution go to link"
      }
    },`
    
    Can you also clarify how you define  "isPermissionless": false parameter?

**Comment by wackerow** [comment]
@omykhailovskyi Sure... ["permissionless" here is defined as](https://ethereum.org/en/staking/saas/#what-to-consider) "Users do not require any special permission, account sign up or KYC to participate with the service".

<img width="992" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/c9d860af-0ce3-433f-b49f-f925bf378e68">

From the above, it appears that users need an account, and a meeting is required to set this up, which would not qualify here.

**Comment by omykhailovskyi** [comment]
Hey, @wackerow 
Thank you for clarification.
Correct me if I'm wrong this parameter is represented on Frontend as Permissionless Nodes?
https://ethereum.org/en/staking/pools/

<img width="275" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/134495539/3be14553-4692-4eb5-a438-2c995af628ca">

Would you be able in that case to change it for our 0.1+ ETH Solution
https://github.com/ethereum/ethereum-org-website/issues/11825#top.
As it doesn't require even to sign up, contact us or provide KYC to participate 0.1+ ETH Solution.
Currently it represents "false" value instead of "true"

Thank you in advance!
