### ISSUE TITLE
Suggest an additonal resource for design and UX in Web3 Page

### ISSUE THREAD

**Issue by UXSequence** [ethereum/ethereum-org-website#10225]
Suggested resource addition to this page: https://ethereum.org/en/developers/docs/design-and-ux/ 

[UX/UI Patterns in Web3 Guide](https://avark.agency/learn/article/blockchain-ux-design-guide/) 

The guide covers the following:

- Why UX is especially crucial in the Web3 space
- UX patterns to follow in different Web3 applications/products/ areas (non-custodial wallets, DeFi, NFTs etc)
- Tips for dealing with multi-chain Dapps from a UX perspective 
- Tips for showing on-chain transaction status in the UX process
- Real-world examples from Web3 products

**Comment by konopkja** [comment]
Hello, and thanks for the suggestion. 

I read through the article and have a few issues with it, hence it is rejected for now:

1. Most tips are only high-level described with sometimes weak arguments, therefore not so useful for a designer
2. The writing should be more concise and to the point. (unnecessary parts should be removed)

**Comment by konopkja** [comment]
the one part that i think would be useful was only the Defi part of the article. 

Consider being more specific with exact suggestions how to make better UX, then the article would be very useful to the community.
