### ISSUE TITLE
404 pages should not load assets via relative paths 

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/ethereum-org-website#1024]
**Describe the bug**

If we load an 404 page that has more than one URI segment (e.g: `ethereum.org/segment-1/segment-2`), most assets will fail to load.

Due to the prefetch mechanism for the site content, one 404 page can generate hundreds more 404 requests.

**To Reproduce**
This works: https://ethereum.org/not-found

This doesn't work: https://ethereum.org/page/not-found

**Expected behavior**

**Screenshots**
Expected: 
![image](https://user-images.githubusercontent.com/47108/82247546-8d76f300-9914-11ea-99e3-86aedbc060dc.png)

Result:
![image](https://user-images.githubusercontent.com/47108/82247514-805a0400-9914-11ea-918f-f91aa9f32a02.png)

**Comment by samajammin** [comment]
Ah, thanks for surfacing @evertonfraga!

I suspect this was created when we added IPFS support in #896 - we installed `[vuepress-plugin-ipfs](https://www.npmjs.com/package/vuepress-plugin-ipfs)` which uses `[all-relative](https://www.npmjs.com/package/all-relative)`as a dependency.

@cwaring I'm curious - how have you folks dealt with this issue? Do you know if there's a way we can prevent using relative paths for a certain component (NotFound.vue)? Thanks in advance!

**Comment by samajammin** [comment]
@all-contributors please add @evertonfraga for bugs

**Comment by cwaring** [comment]
@samajammin hi, I think in this case adding a [baseurl](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) to the 404 page should fix it. If not let me know and I'll see if I can cut a new release to handle dynamic pages better.

**Comment by samajammin** [comment]
@cwaring that did the trick! Thanks.

Closing this out - solved in #1033.

**Comment by samajammin** [comment]
@all-contributors please add @cwaring for ideas
