### ISSUE TITLE
[Tag] Update close button styles

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10266]
Update the styles for the close button inside the Tags.

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/cfefc7cf-c5d9-4fb9-95b3-4b4ccb576bd0)

https://github.com/ethereum/ethereum-org-website/assets/1120748/0474f8e4-8127-46a0-8983-b2239d259ab4

DS: https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=1600-34738&t=thqLEloXh2D9Dd4H-0

**Comment by TylerAPfledderer** [comment]
Commenting for assignment 😄

**Comment by wackerow** [comment]
Hey @TylerAPfledderer! Just circling through... Any update? Happy to open this back up for another contributor

**Comment by TylerAPfledderer** [comment]
@wackerow Hmm this is quite old. Don't know why this was missed!

Keep me on the. I believe I ran into an issue where I needed a consult from @pettinarip and @nloureiro, but not sure what it was here.

Thank you for the follow-up!
