### ISSUE TITLE
[Tag] Fix multi-line height

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10265]
The multi-line tag is not growing in height as in the design:
![image](https://github.com/ethereum/ethereum-org-website/assets/468158/1d0ca99d-a067-4db9-92e7-a3cf7904fd73)

DS:
![image](https://github.com/ethereum/ethereum-org-website/assets/468158/3c4a4e9c-5af4-45db-a832-c8c737f30733)

**Comment by TylerAPfledderer** [comment]
Commenting for assignment! 😄
