### ISSUE TITLE
Fix typo on JavaScript API Libraries page

### ISSUE THREAD

**Issue by johnnygee19** [ethereum/ethereum-org-website#10269]
There's a hyphen missing. Spelling should be consistent across the entire the web page which is "JSON-RPC". 

![eth1](https://github.com/ethereum/ethereum-org-website/assets/132227312/d942b21c-ee0b-4b81-8b76-1d2b37e36dfe)

https://ethereum.org/en/developers/docs/apis/javascript/

I can work on this.

**Comment by Re1da** [comment]
#9608

**Comment by wackerow** [comment]
<img width="519" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/2092ff1f-905a-4c4e-9100-a7abec05b461">

Looks good! Agree, we should standardize around "JSON-RPC"... I see 11 instances of "JSON RPC" in 7 English files when doing a quick search... open for someone to patch these up!
