### ISSUE TITLE
Suggest a staking product or service

### ISSUE THREAD

**Issue by DavideDna** [ethereum/ethereum-org-website#10281]
### Project name

ChainLabo

### Product type

Staking as a service

### Logo

![cl_logo_color](https://github.com/ethereum/ethereum-org-website/assets/132011732/29019feb-6025-48c1-aeae-6af97e7960b2)

### Description

Using Ethereum.org Launchpad, our customers can create a Non Custodial Solo Staking server with their 32 ETH, and keeping the rewards. ChainLabo manages the updates of the staking nodes which run on dedicated servers hosted in Switzerland

### Website

https://www.chainlabo.com/

### If software is involved, is everything open source?

N/A, no custom software is involved

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

N/A

### What wallets support the product or service?

All ethereum wallet

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

No, minimum 32 ETH and multiples
0% ETH FEES

### If a service, what are the fees associated with using the service?

0% ETH FEES
Startup fee in FIAT (CHF, USD, EUR)
Monthly fee in FIAT (CHF, USD, EUR)

### If the product or service involved a liquidity token, what are the tokens involved?

N/A

### What date did the project or service go live?

01/04/2023

### Has the project undergone an external security audit?

No

### Has the project undergone any security bug bounties?

No

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

During a video call, the customer is guided, without screen sharing, through all the steps for the generation of the keys and the smart contract on the Ethereum.org Launchpad signing. It is customer's responsibility to hold and securely store the keys. ChainLabo only receives the keystore and its corresponding password from the customer.

### If a pooled staking service, can users participate as a node operator without permission?

N/A

### If listing a staking-as-a-service, are users required to sign-up for an account?

NO

### If listing as staking-as-a-service, who has access to the signing keys?

The user and ChainLabo maintain the access to keystore key and password.

Only the user maintain access to 24 words that generate the keystore key

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

Only the user holds  the withdrawal keys.
Withdrawal credentials utilize 0x01 type credentials.
Only the user choose this account

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

100% Geth

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

Nimbus

### What platforms are supported?

Linux

### What user interfaces are supported?

N/A

### Social media links

https://twitter.com/ChainLabo
https://web.telegram.org/a/#-1919442359
https://discord.gg/3xmHwXxk
https://github.com/ChainLabo

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @DavideDna! Appreciate you dropping the request... few questions here:

> If software is involved, is everything open source?
> N/A, no custom software is involved

Do users know what they're signing in the first step? I couldn't find a way to check it out without scheduling an appointment.

> Is the product or service free of trusted/human intermediaries?
> During a video call, the customer is guided, without screen sharing, through all the steps for the generation of the keys and the smart contract on the Ethereum.org Launchpad signing. It is customer's responsibility to hold and securely store the keys. ChainLabo only receives the keystore and its corresponding password from the customer.

This sounds great... just making sure I understand correctly: ChainLabo helps the user through the Staking Launchpad, and key generation... user sets the withdrawal credentials to whatever they'd like, correct? Then they make their deposit with the deposit-data file they created, and send a copy of the password-protected keystores to ChainLabo... is that also correct?

> If listing a staking-as-a-service, are users required to sign-up for an account?
> NO

I'm a little confused here... You get on a call, and users make the deposit themselves, and set their own withdrawal address. You then run the node for them, charging a setup fee, and a monthly fee for maintenance, but there is no account involved? How do you charge a monthly fiat fee without an account?

If user doesn't need help with the key/deposit steps, is there any way for them to use the service without a meeting or an account (without any permission or approval)?

> Is the product out of beta development?
> N/A

Please confirm we're out of beta development.

> What date did the project or service go live?
> 01/04/2023

To remove ambiguity, is this Jan 4, or April 1?

Thanks!

**Comment by DavideDna** [comment]
> Hey @DavideDna! Appreciate you dropping the request... few questions here:
> 
> > If software is involved, is everything open source?
> > N/A, no custom software is involved
> 
> Do users know what they're signing in the first step? I couldn't find a way to check it out without scheduling an appointment.
> 

Our website does not have a self-registration or sign-in feature. Customers who are interested in our services can contact us to request more information. We will then provide them with the service contract that needs to be digitally signed before scheduling the setup video call.  

> > Is the product or service free of trusted/human intermediaries?
> > During a video call, the customer is guided, without screen sharing, through all the steps for the generation of the keys and the smart contract on the Ethereum.org Launchpad signing. It is customer's responsibility to hold and securely store the keys. ChainLabo only receives the keystore and its corresponding password from the customer.
> 
> This sounds great... just making sure I understand correctly: ChainLabo helps the user through the Staking Launchpad, and key generation... user sets the withdrawal credentials to whatever they'd like, correct? Then they make their deposit with the deposit-data file they created, and send a copy of the password-protected keystores to ChainLabo... is that also correct?
> 

Yes, this is correct. We will deploy the validator keys on a customer dedicated physical hardware. Currently we don't have any shared or virtual service.

> > If listing a staking-as-a-service, are users required to sign-up for an account?
> > NO
> 
> I'm a little confused here... You get on a call, and users make the deposit themselves, and set their own withdrawal address. You then run the node for them, charging a setup fee, and a monthly fee for maintenance, but there is no account involved? How do you charge a monthly fiat fee without an account?
> 

We don't have a customer area on the website, so no account setup is needed. Customers make fiat payments using Stripe or direct bank transfer when they receive the invoice. Invoices are sent out on a monthly or yearly basis.

> If user doesn't need help with the key/deposit steps, is there any way for them to use the service without a meeting or an account (without any permission or approval)?
> 

To proceed, the user must sign the Chainlabo contract. If they don't require any technical support, they may send us the keys directly. We'll discuss and agree on the preferred method beforehand.



> > Is the product out of beta development?
> > N/A
> 
> Please confirm we're out of beta development.
> 

Yes, we are out of beta

> > What date did the project or service go live?
> > 01/04/2023
> 
> To remove ambiguity, is this Jan 4, or April 1?
> 

April 1st

> Thanks!

No prob, 
Thanks

**Comment by wackerow** [comment]
Hey @DavideDna! Sorry for delay...  just took another look through, and this overall looks good to move forward... from above I would fill in the data for ChainLabo as follows:

minEth: 32
monthlyFee: ? (Please provide)
monthlyFeeUnit: USD
isFoss: false
hasBugBounty: false
isTrustless: true // From the above, it appears the user retains access to their mnemonic, and thus their signing keys and withdrawal credentials.
isPermissionless: false
pctMajorityExecutionClient: 100,
pctMajorityConsensusClient: 0,
isSelfCustody: true

If you'd like to post a PR yourself let me know, otherwise will try to get something up by next week.

**Comment by DavideDna** [comment]
> Hey @DavideDna! Sorry for delay... just took another look through, and this overall looks good to move forward... from above I would fill in the data for ChainLabo as follows:
> 
> minEth: 32 monthlyFee: ? (Please provide) monthlyFeeUnit: USD isFoss: false hasBugBounty: false isTrustless: true // From the above, it appears the user retains access to their mnemonic, and thus their signing keys and withdrawal credentials. isPermissionless: false pctMajorityExecutionClient: 100, pctMajorityConsensusClient: 0, isSelfCustody: true
> 
> If you'd like to post a PR yourself let me know, otherwise will try to get something up by next week.

Hi Paul,
thanks a lot for your support. 
Our monthly fees are 200CHF or 250CHF, they depend on the choosen service level.
Do you mind also chainging the `monthlyFeeUnit` to CHF?
Best,
Davide

**Comment by natpicone** [comment]
@wackerow I prepared https://github.com/ethereum/ethereum-org-website/pull/10998 
Can you please review?
