### ISSUE TITLE
FeedbackWidget hover bug: overflow scroll

### ISSUE THREAD

**Issue by parmishh** [ethereum/ethereum-org-website#10285]
### Describe the bug

a unnecessary left-right scroll bar appears while hovering on was it helpful button.
Here is a video of issue:

https://github.com/ethereum/ethereum-org-website/assets/91942072/0bfbac3d-6112-4c9e-953b-c419ffa3b041

### To reproduce

1. Hover over is this page helpful button

### Expected behavior

The scroll bar is unnecessary as page always fits 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by parmishh** [comment]
please assign it to me if this issue needs to be addressed.

**Comment by corwintines** [comment]
Thanks @parmishh!

I can't reproduce this at the moment, so not sure if this was fixed since this issue was opened. If you still notice it, could you reopen with a bit more information like OS and browser like @wackerow suggested. Thanks!
