### ISSUE TITLE
Add the Blotic community website to the online community page.

### ISSUE THREAD

**Issue by PavanTamrakar** [ethereum/ethereum-org-website#10280]
This PR adds an invite link to the Blotic community website to the online community page.

Blotic focuses on Ethereum and Polygon Development by providing workshops and bounties.
Blotic is now in 15+ universities in India, teaching students how Ethereum and blockchain can change the world in a good way.

We have received grants from PolygonDAO, UNISwap, StarkNet, and, Aave.

https://blotic.org/
https://discord.gg/cAGZfSD6XN

**Comment by PavanTamrakar** [comment]
@corwintines ser give it a look

**Comment by corwintines** [comment]
Hey @PavanTamrakar 

Wondering where you see this fitting under the online community section?

**Comment by corwintines** [comment]
Its not very clear where this would fit on that page. Feel free to reopen with a suggestion, but going to close this out for now.
