### ISSUE TITLE
Add Origin Ether dapp

### ISSUE THREAD

**Issue by sumpg41** [ethereum/ethereum-org-website#10293]
### Project name

Origin Ether

### Product type

Staking pool

### Logo

![OETH](https://github.com/ethereum/ethereum-org-website/assets/80375331/da1baf5f-f84d-4c00-95d5-fd7f0dc8f013)

### Description

Origin Ether (OETH) is a ETH LSD aggregator that combines the yield-generating functions of Lido, Rocket Pool, and Frax into one single, diversified token.

### Website

https://oeth.com/

### If software is involved, is everything open source?

Yes, everything is open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

Yes, OETH is a fork of OUSD

### Is the product out of beta development?

The Origin Ether dapp repo can be found via https://github.com/originprotocol.

Origin Ether is a fork of Origin Dollar: https://ousd.com/ 

### What wallets support the product or service?

Any wallet that supports ERC20 tokens can support OETH.

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

There is no minimum ETH required to use OETH.

### If a service, what are the fees associated with using the service?

There is a 20% performance fee on the yield generated when using OETH. There is also a 0.0025% exit fee when exiting OETH through the dapp, which is avoidable when exiting through any supported DEX.

### If the product or service involved a liquidity token, what are the tokens involved?

OETH is backed by WETH and the following liquid staking derivates:

Lido stETH: 0xae7ab96520de3a18e5e111b5eaab095312d7fe84
Rocketpool rETH: 0xae78736cd615f374d3085123a210448e74fc6393
Frax frxETH: 0xae78736cd615f374d3085123a210448e74fc6393
wETH: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

### What date did the project or service go live?

Origin Ether launched on May 16th 2023.

### Has the project undergone an external security audit?

Origin Ether has undergone multiple audits, all of which can be seen on the [Audits Page ](https://docs.oeth.com/security-and-risks/audits)of the OETH docs.

### Has the project undergone any security bug bounties?

There is an open bug bounty for up to $250k USD on [Immunefi](https://immunefi.com/bounty/origindollarousd/).

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

The OETH contracts are fully owned by the Timelock, which is controlled by OGV stakers.

### If a pooled staking service, can users participate as a node operator without permission?

Users can participate as a node operator without permission with OETH collateral Rocketpool, but not with OETH itself.

### What platforms are supported?

OETH is available on all platforms.

### What user interfaces are supported?

OETH is available on all interfaces.

### Social media links

OP Core Twitter https://twitter.com/OriginProtocol
OP Defi Twitter https://twitter.com/OriginDeFi
Telegram	https://t.me/originprotocol
Discord https://discord.com/invite/ogn
Medium https://blog.originprotocol.com/
Github https://github.com/originprotocol
Facebook https://www.facebook.com/originprotocol/
Youtube https://www.youtube.com/c/originprotocol
Reddit https://www.reddit.com/r/originprotocol/
LinkedIn https://www.linkedin.com/company/originprotocol/
Tik Tok https://www.tiktok.com/@origin_protocol
Instagram https://instagram.com/originprotocol

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by wackerow** [comment]
Hey @sumpg41! Thanks for posting this... Overall this looks good to me! Nice job on active bug bounties and ongoing audits. I like the breakdown of yield sources on the homepage too.

Couple questions...

---

> Is the product or service free of trusted/human intermediaries?
> The OETH contracts are fully owned by the Timelock, which is controlled by OGV stakers.

Can you help me understand Timelock, and how the OGV stakers have control here? This is related to the "Trustless" indicator on the site, currently defined as "Service does not require trusting any humans to custody your keys or distribute rewards"... Are there any potential restrictions on token holders being able to redeem for the underlying asset (ie. exit, not just sell the ERC-20)?

If not, then I'd mark this field `true`

---

> If a pooled staking service, can users participate as a node operator without permission?
> Users can participate as a node operator without permission with OETH collateral Rocketpool, but not with OETH itself.

Being an aggregator, it sounds like this field applies slightly less than pools that focus on running their own. I would say given the support for other pools that have permissionless node operation, ie. Rocket Pool, this should probably qualify, but open to hear if others disagree. 

---

Lastly, you marked yes that you'd like to work on this... a PR is welcome, I'll go ahead and assign you to the issue

**Comment by sumpg41** [comment]
> > Is the product or service free of trusted/human intermediaries?
> > The OETH contracts are fully owned by the Timelock, which is controlled by OGV stakers.
> 
> Can you help me understand Timelock, and how the OGV stakers have control here? This is related to the "Trustless" indicator on the site, currently defined as "Service does not require trusting any humans to custody your keys or distribute rewards"... Are there any potential restrictions on token holders being able to redeem for the underlying asset (ie. exit, not just sell the ERC-20)?
> 
> If not, then I'd mark this field `true`

There are no lockups or restrictions with exiting OETH. Users can go in and out as they please, at the speed of the Ethereum blockchain, for any of the collateral assets, or a basket of the mix. 

More information on the timelock can be found on the [Timelock page](https://docs.oeth.com/smart-contracts/api/timelock) of the OUSD docs. 

We can go ahead and mark this field `true` :)

> > If a pooled staking service, can users participate as a node operator without permission?
> > Users can participate as a node operator without permission with OETH collateral Rocketpool, but not with OETH itself.
> 
> Being an aggregator, it sounds like this field applies slightly less than pools that focus on running their own. I would say given the support for other pools that have permissionless node operation, ie. Rocket Pool, this should probably qualify, but open to hear if others disagree.

Agreed on this! Origin may one day had permissionless node operation for OETH, turning OETH into a hybrid LST aggregator/node operator, but that is a long ways away

> 
> Lastly, you marked yes that you'd like to work on this... a PR is welcome, I'll go ahead and assign you to the issue

ahh that may have been a mistake, as I'm not a technical person. I'd prefer to hand this off to someone with a bit more experience handling/submitting PRs if that's alright
