### ISSUE TITLE
List Consensys under staking as a service

### ISSUE THREAD

**Issue by beetrootkid** [ethereum/ethereum-org-website#10316]
### Project name

Consensys

### Product type

Staking as a service

### Logo

![Staking Logo](https://github.com/ethereum/ethereum-org-website/assets/34025634/fcddac6b-144c-4891-9459-9e38721a95ae)

### Description

Consensys Staking is a self-custodial staking service for Ethereum that offers enterprise-grade staking for ETH holders. The service focuses on security and resilience and has SOC2 Types I and II certification. It is multi-cloud, multi-client and multi-region to give customers a distributed staking operation.

Consensys’ expertise and engagement in the ecosystem that include leading products like Teku, Metamask, Infura and Besu as well as protocol-level research and development.  Consensys Staking is able to leverage the expertise of these teams to deliver the best possible service to its customers.

### Website

https://consensys.net/staking/?utm_source=Ethereum%20Foundation&utm_medium=Website&utm_campaign=Partner

### If software is involved, is everything open source?

Portions of code are open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes. We have been in production and mainnet since genesis of the Beacon Chain on December 1, 2020.

### What wallets support the product or service?

Metamask, MMI and Wallet Connect

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

32 ETH is the minimum

### If a service, what are the fees associated with using the service?

We take a custom percentage of fees based on the expected volume of staking.

### If the product or service involved a liquidity token, what are the tokens involved?

No tokens are involved.

### What date did the project or service go live?

December 1, 2020

### Has the project undergone an external security audit?

We undergo security audits every year.

### Has the project undergone any security bug bounties?

Hackerone - https://hackerone.com/consensys?type=team

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

There is no part of the user journey involving the trust of funds to Consensys or a smart contract by Consensys.

### If a pooled staking service, can users participate as a node operator without permission?

No pooling in this service.

### If listing a staking-as-a-service, are users required to sign-up for an account?

Yes. The user has to agree to our terms and conditions to be given an account.

### If listing as staking-as-a-service, who has access to the signing keys?

Signer Keys are generated and injected directly into cloud-based HSMs. Access to these is restricted to the remote signer software.

The user must maintain access to their withdrawal key(s). Consensys Staking never has access to any withdrawal key.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

User holds their withdrawal key(s).

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

We run 50% Lighthouse and 50% Teku at time of writing. We currently run majority Geth execution layer but are looking to diversify over the next quarter.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

We run Lighthouse and Teku.

### What platforms are supported?

Linux, macOS and Windows

### What user interfaces are supported?

browser app and graphiql and api

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by MatSainto** [comment]
Hello @wackerow ,
Could you help us getting Consensys added to the ETH SaaS page? Thanks!

**Comment by wackerow** [comment]
Hey @MatSainto, sorry for delay and thanks for the ping! @beetrootkid you checked "Yes" to wanting to work on this, I've gone ahead and assigned you.

Overall looks good... Was curious if you had any latest numbers on use of Prysm and Geth? I see 50% Lighthouse mentioned, but is the other 50% Prysm? And we're also trying to help improve execution client diversity, hence looking for Geth usage.

Also, if you could please drop links to the public audits, thanks!

Summary I see from above information (for the `staking-products.json` file):
```json
"launchDate": "2020-12-01",
"url": "https://consensys.net/staking/",
"audits": [], (Pending)
"minEth": 32,
"monthlyFee": 8,
"monthlyFeeUnit": "%",
"tokens": [],
"isFoss": false,
"hasBugBounty": true,
"isTrustless": false,
"isPermissionless": false,
"pctMajorityExecutionClient": null, (Pending)
"pctMajorityConsensusClient": null, (Pending)
"isSelfCustody": false,
```

@beetrootkid Let us know if you're still interested in working on this, if not I'm happy to help get it over the line.

**Comment by beetrootkid** [comment]
Sure - will take a look!

**Comment by beetrootkid** [comment]
So.. I updated the comment section to address the points raised but I'm afraid I'm not sure what the next step is @wackerow  - apologies; I'm relatively new to the whole Github issue/pr submit processes 🙏

**Comment by wackerow** [comment]
@beetrootkid Hey! Just touching base, anything we can do to help here?

**Comment by beetrootkid** [comment]
@wackerow - thanks so much for following up. I created a fork (https://github.com/beetrootkid/ethereum-org-website) and added the relevant tile (I think). But I'm not familiar with this design kit and so don't know how / where to place the required image etc or test it. Do you think you could help me out? 🙏

**Comment by wackerow** [comment]
@beetrootkid Absolutely!

To list a new staking product, the core file you're going to be working with will be `/src/data/staking-products.json`. This is a JSON file with the top level items being the breakdown of different staking products... for this one, you would look for the `saas` section... within you'll find existing saas products that you can use as examples/templates to bring in the information needed from above.

The only challenge beyond that is the logo, which takes a few extra steps (and we'd be happy to help if you run into trouble)... The pattern used in this site takes advantage of Chakra's `createIcon` component, which lets us build out SVGs as Chakra components.

You can see an examples inside `/src/components/icons/staking/`... Any file ending in `GlyphIcon.tsx` is used for the staking products. You could replicate one of the other files for the loose structure, and would likely name it `ConsensysStakingGlyphIcon.tsx`. Then you'd basically have to migrate the source of the SVG into that file, and clean it up a little for React, then export it from `/src/components/icons/staking/index.ts` to make it available. 

Again, this part is a bit trickier, so just ping if you're having issues and we can jump in (if possible, when submitting a PR make sure the box to allow others to contribute to the PR is checked)

**Comment by beetrootkid** [comment]
Thank you @wackerow - let me have a go. Thank you again for your patience.
