### ISSUE TITLE
Card Values Not Updating in "Ethereum Today" Section when Changing Filters

### ISSUE THREAD

**Issue by nisharmultani** [ethereum/ethereum-org-website#10330]
### Describe the bug

Description:
I noticed a bug in the "Ethereum Today" section on the home page where the card labeled "ETH PRICE (USD)" and all other card values do not update when changing the filter, such as from 30 days to 90 days. Only the graph seems to reflect the filter change.

Steps to Reproduce:

Go to the home page.
Locate the "Ethereum Today" section.
Observe the card labeled "ETH PRICE (USD)" and other relevant cards.
Change the filter from 30 days to 90 days.
Notice that the values in the cards do not update accordingly, while the graph does reflect the filter change.

### To reproduce

1 ) go the Ethereum home page
2) scroll down "Ethereum Today" section
3) inside this section change filter from 30d to 90d to 

### Expected behavior

When changing the filter in the "Ethereum Today" section, the values in the cards, including "ETH PRICE (USD)," should update accordingly to reflect the selected time range.

### Screenshots

![Screenshot from 2023-05-25 22-13-30](https://github.com/ethereum/ethereum-org-website/assets/52249398/d896af5d-7ebf-40bb-92a3-fd3c6395d591)
![Screenshot from 2023-05-25 22-13-09](https://github.com/ethereum/ethereum-org-website/assets/52249398/4014bc8a-2313-468e-a1d9-997754d53313)

### Desktop (please complete the following information)

linux
chromeLinux

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @nisharmultani! Thanks for posting... So this is the intended functionality here. The single value that is being displayed represents the "now" state (not a 30-day nor 90-day value of some kind... what would this be?). The 30/90-day toggle is intended only for the line chart.

Will cc the designers on this one (cc: @konopkja @nloureiro) for potential future design iteration, but going to close this one out in the meantime. Thanks again!
