### ISSUE TITLE
Hero in `use-cases` template image displaying behind content

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#10333]
### Describe the bug

The Hero for the use-cases template is not very responsive, and causes the hero image to be covered by the TitleCard.

### To reproduce

1. Go to https://ethereum.org/en/desci
2. Use developer tools to play around with responsive view
3. Notice the Hero image being overlapped by the TitleCard

### Expected behavior

Image and TitleCard should share the Hero, and the TitleCard should not interfere with the image

### Screenshots

![Screen Shot 2023-05-25 at 12 20 09 PM](https://github.com/ethereum/ethereum-org-website/assets/15589226/d5783abe-ca64-48fb-934b-4e7e5c76e044)

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by SimardeepSingh1450** [comment]
Commenting for assignment @corwintines

**Comment by MahendraBishnoi29** [comment]
Then what do you think it should look like? @corwintines 🤔

**Comment by corwintines** [comment]
Im going to close this out as the new hero is being implemented in the design system
