### ISSUE TITLE
Suggest a dapp - Raiden Network

### ISSUE THREAD

**Issue by anton-schwarz** [ethereum/ethereum-org-website#10336]
### Name

Raiden Network

### Description

Raiden Network is an off-chain scaling solution, enabling near-instant, low-fee and scalable payments using state channel technology. It’s complementary to the Ethereum blockchain & Arbitrum and works with any ERC20 compatible token.

### Logo

![Raiden_logo_symbol](https://github.com/ethereum/ethereum-org-website/assets/70583747/2b274c00-c189-49ea-99bf-8d16e37e2675)

Please use a solid white (#FFFFFF) background.

### Brand color

Black (#000000) and White (#FFFFFF)

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/raiden-network/raiden/

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

The whole project is open source with the code being publicly available on GitHub (https://github.com/raiden-network/raiden/). 

There is also extensive documentation on how to use Raiden Network (https://raiden-network.readthedocs.io/en/latest/index.html). 

Raiden Network has not been audited externally, however, is has been subject to internal audits (brainbot technologies AG, which developed Raiden Network, also offers smart contract code audits and thus possesses sufficient skills and experience to ensure a high level of security).

Lastly, as Raiden Network is fairly decentralised (last steps like founding a DAO are currently in the making) and there is no pooling of funds, there is little to no incentive for attackers to attack the network or individual smart contracts.

We're happy to elaborate further if needed, feel free to reach out to anton@brainbot.com.

### Can a user access the dapp without creating an account?

Yes, usage is possible with just an Ethereum address.

### Are dapp funds non-custodial?

Yes. To use payment channels, users have to lock up an initial amount of funds, however, as Raiden Network is fully decentralized, they are the only ones who can unlock and withdraw these funds again.

### Do you offer community support?

There is a public Discord channel for community governance & support.

Use this invite link to join: https://discord.com/invite/nSQDQBq5FC

### Describe any geographical restrictions on usage of your dapp

No geographical restrictions.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Looks great @anton-schwarz... Curious how active Raiden has been lately? Any usage numbers you could forward along for my own curiosity? Assigning you for listing, ping for any help!

**Comment by minimalsm** [comment]
This issue has gone stale and Raiden Network doesn't really look active to me. Feel free to reopen addressing @wackerow's questions if you disagree and still want to list here @anton-schwarz 

Thanks!
