### ISSUE TITLE
Fix possible negative connotation of 'bank run' in code example on homepage

### ISSUE THREAD

**Issue by neodaoist** [ethereum/ethereum-org-website#10369]
### Describe the bug

The words 'bank run' appear on the homepage. Even though of form noun-verb, it could be misinterpreted as noun-noun with the negative connotations of a [bank run](https://en.wikipedia.org/wiki/Bank_run).

(Not necessarily a bug, but this issue type seemed most fitting.)

### To reproduce

1. Go to 'Homepage'
2. Scroll down to 'A new frontier for development' code examples
3. See phrase 'You can build a bank run by logic you've programmed.'

### Expected behavior

Replacing 'run' with a synonym would avoid the possible negative connotations of a bank run.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Closed by #10370 , thanks again @neodaoist
