### ISSUE TITLE
Update energy consumption estimates

### ISSUE THREAD

**Issue by dmatsuoka** [ethereum/ethereum-org-website#10371]
### Is your feature request related to a problem? Please describe.

Proposed changes to https://ethereum.org/en/energy-consumption/ :

We would like to propose the following changes to the page titled “Ethereum's energy expenditure”. This PR will build off the recent work of @jmcook1186, so we would appreciate his review here. Most of these updates are minor clean-up items, with a few additions and added clarifications. The proposed changes are itemized below.

### Describe the solution you'd like

1. The estimate used for “Global data centers” is 200 TWh. However, in the cited [source](https://www.iea.org/commentaries/data-centres-and-energy-from-global-headlines-to-local-headaches) the estimate for 2021 (the latest reported year) is actually 191 TWh. We propose using the 191 TWh number to be more precise.

2. The estimate used for “Bitcoin” is 131 TWh. The cited [source](https://ccaf.io/cbnsi/cbeci/comparisons) updates every 24 hours, and the ethereum.org page already makes it clear that these values were accessed in May 2023. Nevertheless, we propose using the current 138 TWh number to be as up-to-date as possible.

3. The estimate used for “PoW Ethereum” is 78 TWh. This comes from the cited [source](https://digiconomist.net/ethereum-energy-consumption) of Digiconomist. However, we propose switching the [source](https://ccaf.io/cbnsi/ethereum/1) to the University of Cambridge Blockchain Network Sustainability Index — which is the citation used for other estimates, such as gold mining and bitcoin. In addition to being more consistent, Cambridge’s estimates are also more closely aligned with other [independent](https://kylemcdonald.github.io/ethereum-emissions/) [sources](https://carbon-ratings.com/). The new number would be 21 TWh.

4. The estimate used for “Youtube (direct only)” is 12 TWh, taken from a 2020 environmental [report](https://www.gstatic.com/gumdrop/sustainability/google-2020-environmental-report.pdf) from Google. However, the number represents the energy consumption for all of Google, not just Youtube products. Moreover, a more recent report from 2022 can be used. As a result, we propose changing the label to “Google” as well as updating the [source](https://www.gstatic.com/gumdrop/sustainability/google-2022-environmental-report.pdf) to reflect the latest report. The new number used will be 19 TWh.

5. The estimate used for “Gaming in USA” is 34 TWh. While the estimate comes from a reputable [source](https://www.researchgate.net/publication/336909520_Toward_Greener_Gaming_Estimating_National_Energy_Use_and_Energy_Efficiency_Potential), one important piece of context when making comparisons is that this number includes the energy consumed by end user devices (PCs, laptops, gaming consoles, etc.). The other calculations, including Google, Netflix, and Ethereum, do not account for end user devices. Therefore, we propose adding an asterisk: “Gaming in the USA*”, plus a footnote, “*Includes end user devices”, to make this clear.

6. The estimate used for “Netflix” is 0.451 TWh. However, this is not the number that is reported in the cited [source](https://assets.ctfassets.net/4cd45et68cgf/7B2bKCqkXDfHLadrjrNWD8/e44583e5b288bdf61e8bf3d7f8562884/2021_US_EN_Netflix_EnvironmentalSocialGovernanceReport-2021_Final.pdf). The cited source includes the following items:
- Hardware Infrastructure, i.e. Netflix-operated Open Connect Appliances in colocation data centers = 33,407 MWh
- A footnote stating that Hardware Infrastructure represents approximately 1/10th of Scope 2 and 3 data center electricity use (all Open Connect and AWS combined).
- Other Scope 2 energy consumption, which includes electricity use in corporate offices, production studios, and billboards, in addition to colocation data center infrastructure = 123,148 MWh.

Based on this data, an appropriate calculation of total energy consumption would be:
> [ 33,407 MWh x 10 + 123,148 MWh = 457,218 MWh = 0.457 TWh ]

Thus, we propose changing the number to 0.457 TWh.

7. The estimate used for “PayPal” is 0.26 TWh. This number is correct, however the linked [source](https://app.impaakt.com/) does not lead to the correct report. We propose updating the [source](https://s202.q4cdn.com/805890769/files/doc_downloads/global-impact/CDP_Climate_Change_PayPal-(1).pdf) to the right report.

8. There is some [research](https://docsend.com/view/adwmdeeyfvqwecj2) from Galaxy Digital around the energy consumption of the banking system – which consumes an estimated 239 TWh per year when you account for banking data centers, bank branches, ATMs, and card network data centers. Note that this is a conservative estimate (it doesn’t account for things like banking employee commutes, cash in transit, issuance of bank notes/coins, etc.) and the individual category estimates reasonably align with those from [other sources](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4125499). We propose adding this number to the table and chart with the label of “Traditional banking system”, along with a link to the source.

9. In addition to the financial comparison proposed above, it might be good to also add a non-financial comparison. One thought: an alternative to creators selling NFTs to their fans might be manufacturing and selling T-shirts, so including a stat from the fashion industry is relevant. According to an LVMH environmental [report](https://r.lvmh-static.com/uploads/2022/01/2021_environmental_indicators.pdf), the fashion giant consumes an estimated 1.367 TWh per year. We propose adding this number to the table and chart with the label of “LVMH'', along with a link to the source.

10. We will also be editing some of the supporting text to ensure it aligns with the proposed changes listed above, with the appropriate context provided.

### Describe alternatives you've considered

We're open to feedback on any of the proposed changes listed above. I would be happy to submit the PR if this issue is assigned to me.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by jmcook1186** [comment]
Hi - these seem like good changes to me - would personally appreciate a PR. Pinging @minimalsm too.

**Comment by minimalsm** [comment]
Hey @dmatsuoka 😀 thanks for raising this. At a glance, I think these are good changes overall. 

Re: 9—Not sure about using the LVMH figures as a direct comparison to the fashion world, as it looks like LVMH holds a bunch of subsidiaries unrelated to fashion (Moet, Tiffany, Hennessy, etc.). Even if it were 100% fashion, it also would be hard to communicate the scale of LVMH to readers of this page (it's a HUGE chunk of the luxury fashion world), so it might feel a little disingenuous to add this.
