### ISSUE TITLE
> Suggestion 1: <32 ETH staking

### ISSUE THREAD

**Issue by Swipdaggoe** [ethereum/ethereum-org-website#10372]
> Suggestion 1: <32 ETH staking

Seems like we're forming consensus.

- Update to "Home staking"
- Add section about <32 ETH options
- Continue to emphasize node operation from home

- Add indicator to products that support liquid staking options

> Suggestion 2: LSD
> Yeah so this one is interesting because whilst RPL is a liquid staking protocol, it is not liquid staking for the node operators (i.e. they cannot mint rETH as their capital is purely used as collateral). 

Forgive my ignorance, do Rocket Pool node operators who deposit 16 ETH not get rETH in return?

In either case, sounds like with the above changes, we could add an indicator that signals which projects enable minting a token representative of the ETH staked.

> Suggestion 3: "Why stake solo?"

I think given the above discussion, would consider looking at this one from the lens of an updated "Why stake from home?" section. I see this as a section that should be about the direct benefits of home/solo staking. I'm not sure I'm sold that "the ability to liquid stake" is a direct reason why someone should run a home setup... you can also liquid stake without operating any hardware.

> Suggestion 6: Suggest solo for LSDs on pools page
> In hindsight, I think this could stay as is.

I think if we switch to "Home staking", we could potentially tweak the wording on the `/pools` "Why" copy to just suggest that this is possible from home as well.

> Suggestion 8: Testnet tool listing

@konopkja Would be curious your input. Overall given the challenges in maintaining these product listings, and the overall direction so far to avoid beta/pre-production products, I'm not sure a page like this would be the most appropriate for these tools. I think personally I'd be more in favor of waiting until products are in production / on Mainnet.

But as always, welcome thoughts from others. Should we try to provide space for people to learn about what is coming, and to be directed to ways to test things out?

> Suggestion 4, 5, 7: 💯

_Originally posted by @wackerow in https://github.com/ethereum/ethereum-org-website/issues/9277#issuecomment-1491071019_

**Comment by Dukdig2325** [comment]
>               > Suggestion 1: <32 ETH staking
> 
> Seems like we're forming consensus.
> 
> - Update to "Home staking"
> - Add section about <32 ETH options
> - Continue to emphasize node operation from home
> 
> - Add indicator to products that support liquid staking options
> 
> > Suggestion 2: LSD
> > Yeah so this one is interesting because whilst RPL is a liquid staking protocol, it is not liquid staking for the node operators (i.e. they cannot mint rETH as their capital is purely used as collateral). 
> 
> Forgive my ignorance, do Rocket Pool node operators who deposit 16 ETH not get rETH in return?
> 
> In either case, sounds like with the above changes, we could add an indicator that signals which projects enable minting a token representative of the ETH staked.
> 
> > Suggestion 3: "Why stake solo?"
> 
> I think given the above discussion, would consider looking at this one from the lens of an updated "Why stake from home?" section. I see this as a section that should be about the direct benefits of home/solo staking. I'm not sure I'm sold that "the ability to liquid stake" is a direct reason why someone should run a home setup... you can also liquid stake without operating any hardware.
> 
> > Suggestion 6: Suggest solo for LSDs on pools page
> > In hindsight, I think this could stay as is.
> 
> I think if we switch to "Home staking", we could potentially tweak the wording on the `/pools` "Why" copy to just suggest that this is possible from home as well.
> 
> > Suggestion 8: Testnet tool listing
> 
> @konopkja Would be curious your input. Overall given the challenges in maintaining these product listings, and the overall direction so far to avoid beta/pre-production products, I'm not sure a page like this would be the most appropriate for these tools. I think personally I'd be more in favor of waiting until products are in production / on Mainnet.
> 
> But as always, welcome thoughts from others. Should we try to provide space for people to learn about what is coming, and to be directed to ways to test things out?
> 
> > Suggestion 4, 5, 7: 💯
> 
> _Originally posted by @wackerow in https://github.com/ethereum/ethereum-org-website/issues/9277#issuecomment-1491071019_
>
