### ISSUE TITLE
Add stakefish to the list of service providers on ethereum.org

### ISSUE THREAD

**Issue by jeremyanichols** [ethereum/ethereum-org-website#10385]
### Project name

stakefish

### Product type

Staking as a service

### Logo

![main-color](https://github.com/ethereum/ethereum-org-website/assets/23364151/5781f86f-7c8f-4a7c-988f-9ee67c7916db)

### Description

stakefish is a leading validator for Proof of Stake blockchains. With support for 20+ networks, our mission is to secure and contribute to this exciting new ecosystem while enabling our users to stake confidently.

### Website

stake.fish/ethereum

### If software is involved, is everything open source?

Yes, everything is open source: provide link(s) to project repo(s)

https://github.com/orgs/stakefish/repositories

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Founded in 2018, stakefish has provided Ethereum staking services since the genesis of the Beaconchain. 

### What wallets support the product or service?

Metamask, WalletConnect (Zerion, Bitkeep, Ledger, Infinity Wallet, SecuX, Ambire, AT.Wallet, Exodus, PREMA, Marble, ApolloX, Sequence, OneKey, Vision, Venly, RICE Wallet, UniPass, nufinetes, NOW Wallet, Broearn, SafeMoon, Fireblocks, bobablocks, Wallet3, Bitski, Paper, pier, Crossmint, Verso, KryptoGO), Safe Multisig.

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

stakefish does not enable staking with less than 32 ETH. 

### If a service, what are the fees associated with using the service?

0% protocol fees and 25% of priority fee/mev.

### If the product or service involved a liquidity token, what are the tokens involved?

No tokens.

### What date did the project or service go live?

December 1, 2020.

### Has the project undergone an external security audit?

Yes.

**NFT Staking:**
All audits are here: https://github.com/stakefish/eth2-nft-validator-contract/tree/main/audits

**Classic Staking:**
 https://github.com/crytic/slither

**SOC 2 Type II:**
https://blog.stake.fish/stakefish-completes-soc-2-type-ii-certification-for-non-custodial-blockchain-staking-services/

### Has the project undergone any security bug bounties?

No.

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Yes.

### If a pooled staking service, can users participate as a node operator without permission?

N/A

### If listing a staking-as-a-service, are users required to sign-up for an account?

No. User only needs to connect the wallet with which they want to stake. 

### If listing as staking-as-a-service, who has access to the signing keys?

User has access to withdrawal keys. stakefish has access to validator keys. stakefish provides a pre-signed exit message so that stakers do not need to depend on stakefish to sign the exit message. This process decouples stakers from needing to access the stakefish dashboard to access their staked Ethereum. With the message in the staker's possession, stakers can broadcast directly to the Beacon chain themselves. 

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

Withdrawal credentials utilize 0x01 type credentials. The account is chosen by the user. Users hold their withdrawal keys. 

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

Client distribution:

Lighthouse: 72.6%
Teku: 26.9%

via [Rated](https://www.rated.network/o/Stakefish?network=mainnet&timeWindow=all&viewBy=aggregate)

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

Lighthouse
Teku
Nimbus

### What platforms are supported?

Linux, macOS, Windows, iOS, Android

### What user interfaces are supported?

browser app, CLI app

### Social media links

Twitter: [@stakefish](https://twitter.com/stakefish)
YouTube: https://www.youtube.com/channel/UCZvT8cGpFjnZUB9V-WzxPHg/
Telegram: https://t.me/stakefish

### Would you like to work on this issue?

- [X] Yes
- [] No

**Comment by jeremyanichols** [comment]
Hey, following up on this item. @wackerow are you able to assist?

**Comment by wackerow** [comment]
Hey @jeremyanichols! Thanks for the ping... I see we're already listing stakefish under the pooling options, and the info you provided overall looks good. Don't see a reason to hold this up... I see you checked "Yes" to wanting to help... will assign you and a PR is welcome 🙂 Just let me know if you need a hand with anything

**Comment by jeremyanichols** [comment]
Thanks @wackerow! Appreciate the help 🙂

**Comment by jeremyanichols** [comment]
Hey @wackerow @minimalsm !

This item fell off my plate - circling back on it. Admittedly, it is outside of my ability. 😔 Would you be able to help make the updates?

Can we also remove stakefish from the pooling options list?

Thank you!

**Comment by wackerow** [comment]
Closed with #10966
