### ISSUE TITLE
Listing of WhiteBIT on ethereum.org

### ISSUE THREAD

**Issue by viktoriia-lomakina** [ethereum/ethereum-org-website#10382]
### Exchange name

WhiteBIT

### Exchange description

WhiteBIT is one of the biggest European crypto exchanges, founded back in 2018 in Ukraine. We prioritize safety, transparency, and constant development. Hence, over 4 million users choose us and stay with us. Blockchain is the future of technology, and we make this future available to everyone.

### What geographical restrictions apply to this exchange?

Сurrently WhiteBIT does not accept identity verification from citizens or residents of the following countries and territories: Afghanistan, American Samoa, the U.S. Virgin Islands, Guam, Iran, Yemen, Libya, Palestine, Puerto Rico, Somalia, North Korea, the Northern Mariana Islands, the USA, Syria, Sudan, South Sudan, Transnistria, the temporarily occupied territories of Georgia, Nagorno-Karabakh, Northern Cyprus, Western Sahara, Ambazonia, Kosovo, Republic of Belarus, Russian Federation and the temporarily occupied territories of Ukraine.

### Which currencies are accepted by this exchange?

https://whitebit.com/markets
ETH can be bought for BTC, USDT, EUR, USD, KZT, TRY, GBP, PLN, UAH, USDC, TUSD.

### Do you have any proof that they're a legitimate company?

https://whitebit.com/about-us

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by minimalsm** [comment]
Hey @viktoriia-lomakina! Thanks for creating this issue. Noticed that the WhiteBIT website doesn't have a dedicated page detailing the up-to-date geographical restrictions. We have this as a requirement on our exchange listing policy, as these restrictions often change over time, it's important that we have a page we can reference if these were to change in the future. 

If WhiteBIT can create that page, (or that page already exists), we'd be happy to list WhiteBIT.

Please reopen this issue or a new issue when this is done, and we can get you folks listed :) 

Thanks again!
