### ISSUE TITLE
Bug: Links broken on Short ABI Tutorial

### ISSUE THREAD

**Issue by hoanglamcoin** [ethereum/ethereum-org-website#10383]
https://ethereum.org/en/developers/tutorials/short-abi/#example-2

Links to the etherscan and links on the functions are no working.

[Deployment of OrisUselessToken-2](https://kovan-optimistic.etherscan.io/tx/1475397) at address [0xb47c1f550d8af70b339970c673bbdb2594011696](https://kovan-optimistic.etherscan.io/address/0xb47c1f550d8af70b339970c673bbdb2594011696).
[Deployment of CalldataInterpreter](https://kovan-optimistic.etherscan.io/tx/1475400) at address [0x0dccfd03e3aaba2f8c4ea4008487fd0380815892](https://kovan-optimistic.etherscan.io/address/0x0dccfd03e3aaba2f8c4ea4008487fd0380815892).
[Call to setProxy()](https://kovan-optimistic.etherscan.io/tx/1475402).
[Call to faucet()](https://kovan-optimistic.etherscan.io/tx/1475409).
[Call to transferProxy()](https://kovan-optimistic.etherscan.io/tx/1475416).
[Call to approveProxy()](https://kovan-optimistic.etherscan.io/tx/1475419).
[Call to transferFromProxy()](https://kovan-optimistic.etherscan.io/tx/1475421). Note that this call comes from a different address than the other ones, poorSigner instead of signer.

_Originally posted by @nitantchhajed in https://github.com/ethereum/ethereum-org-website/issues/9541_

_Originally posted by @hoanglamcoin in https://github.com/ethereum/ethereum-org-website/issues/9544_

**Comment by wackerow** [comment]
Thanks @hoanglamcoin! Looks like this is still an issue. Opened up to the community if anyone would like to help patch this.

These links all reach out to a deprecated Kovan explorer...

<img width="962" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/ea0e4fda-e71b-4643-9853-9a5b7b273eeb">

I would just ax this entire "Example" section

**Comment by Shiva-Sai-ssb** [comment]
Submitted PR for this. @wackerow
