### ISSUE TITLE
Bug report - Broken link on goerli launchpad website

### ISSUE THREAD

**Issue by Spacesider** [ethereum/ethereum-org-website#10390]
### Describe the bug

Hi all,

On this page https://goerli.launchpad.ethereum.org/en/teku there is a link to the Teku website

It links to https://docs.teku.pegasys.tech/en/latest/HowTo/Get-Started/Build-From-Source/

However the Teku website is now located at https://docs.teku.consensys.net/get-started/install/build-from-source

I guess it was moved at some point and now the link is broken.

EDIT - Actually it looks like all the links on that page to pegasys.tech are broken so yes definitely moved across to consensys.net

### To reproduce

As described above

### Expected behavior

As described above

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by Raghul18** [comment]
This is issue related to a different repo of ethereum. Please raise the bug in this repo - https://github.com/ethereum/staking-launchpad

**Comment by sammyfilly** [comment]
sure its a pleasure

**Comment by Astronaut828** [comment]
I would also like to work on this Bug report.
