### ISSUE TITLE
Assistance in getting started with the project

### ISSUE THREAD

**Issue by rohan9024** [ethereum/ethereum-org-website#10391]
![image](https://github.com/ethereum/ethereum-org-website/assets/64919642/f0205e13-3965-4500-9ecc-b39f27645485)

I have been encountering the following error persistently after executing the command "yarn start" for quite some time. I have already installed nvm and I am exclusively utilizing node v18. Furthermore, I have attempted to resolve the issue by deleting the node modules and reinstalling all dependencies, but unfortunately, the problem persists.

### Desktop 

I am currently using windows 10

**Comment by sscornelius** [comment]
ABI

**Comment by rohan9024** [comment]
> ABI

sorry?

**Comment by amit-ksh** [comment]
Hey @rohan9024, I recreate this error by removing the `.env` file, so try creating the `.env` file and setting the necessary variables' values. You can copy the below text and paste it into your  `.env` file which would probably fix the issue.

```env
# rename this file to .env and supply the values listed below
# also make sure they are available to the build tool (e.g. Netlify)
# warning: variables prefixed with GATSBY_ will be made available to client-side code
# be careful not to expose sensitive data (e.g. your Algolia admin key)
ALGOLIA_ADMIN_KEY=insertValue
ETHERSCAN_API_KEY=insertValue
GATSBY_ALGOLIA_APP_ID=insertValue
GATSBY_ALGOLIA_SEARCH_KEY=insertValue
GATSBY_GITHUB_TOKEN_READ_ONLY=insertValue
GATSBY_FUNCTIONS_PATH=insertValue

# Build pages only for the specified langs. Leave it empty to build all the langs
# e.g. `en,fr` will only build english and french pages
# Note: always include `en` as it is the default lang of the site
GATSBY_BUILD_LANGS=en

# Folders or files to ignore from the `src/content` folder
IGNORE_CONTENT=**/tutorials

# Used to avoid loading Matomo in our preview deploys
IS_PREVIEW_DEPLOY=false
```

**Comment by rohan9024** [comment]
@amit-ksh where can find the keys or is it predefined somewhere?

**Comment by rohan9024** [comment]
@corwintines can you please help me with this?

**Comment by amit-ksh** [comment]
@rohan9024, leave the first  6 variables as it is, it you don't need key for these variables.

**Comment by rohan9024** [comment]
@amit-ksh I'm still facing the same issue

**Comment by amit-ksh** [comment]
If possible, Can you share your `.env`.

**Comment by rohan9024** [comment]
I have pasted the same code which you gave me-->

```
# rename this file to .env and supply the values listed below
# also make sure they are available to the build tool (e.g. Netlify)
# warning: variables prefixed with GATSBY_ will be made available to client-side code
# be careful not to expose sensitive data (e.g. your Algolia admin key)
# you don't to change these 
ALGOLIA_ADMIN_KEY=insertValue
ETHERSCAN_API_KEY=insertValue
GATSBY_ALGOLIA_APP_ID=insertValue
GATSBY_ALGOLIA_SEARCH_KEY=insertValue
GATSBY_GITHUB_TOKEN_READ_ONLY=insertValue
GATSBY_FUNCTIONS_PATH=insertValue

# Build pages only for the specified langs. Leave it empty to build all the langs
# e.g. `en,fr` will only build english and french pages
# Note: always include `en` as it is the default lang of the site
GATSBY_BUILD_LANGS=en

# Folders or files to ignore from the `src/content` folder
IGNORE_CONTENT=**/tutorials

# Used to avoid loading Matomo in our preview deploys
IS_PREVIEW_DEPLOY=false
```

**Comment by amit-ksh** [comment]
You have to create a new called `.env` file and paste this inside the `.env` file. Not in the `.env.example`

**Comment by rohan9024** [comment]
Thank you so much bhai😭😭😭

**Comment by rohan9024** [comment]
@amit-ksh another error -->

![image](https://github.com/ethereum/ethereum-org-website/assets/64919642/3606a82c-1b94-48bf-b9b7-1ca63c9202d2)

**Comment by amit-ksh** [comment]
I recommend to read 
[this article](https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file) to more about **.env** file.

**Comment by rohan9024** [comment]
@amit-ksh is the new error related to env?

**Comment by amit-ksh** [comment]
What do you mean?

**Comment by rohan9024** [comment]
@amit-ksh this is the new error -->

![image](https://github.com/ethereum/ethereum-org-website/assets/64919642/157ff282-be8a-4c34-89e8-76f4c6356f07)

**Comment by amit-ksh** [comment]
I never get this error, run `yarn start` one more time and see it show again.

**Comment by rohan9024** [comment]
@amit-ksh it;s finallyyyy runninggggggg..........😭😭

Thank you so muchhhhhhhhhh Amit!! You're a saviour just by fixing by .env😂

Well I need to update the docs now
