### ISSUE TITLE
Volatility and taxation on cryptocurrency.

### ISSUE THREAD

**Issue by Asuzor11** [ethereum/ethereum-org-website#10393]
### Is your feature request related to a problem? Please describe.

Should government impose tax on cryptocurrency?

### Describe the solution you'd like

If the government wants to impose taxes on web3 firms or cryptocurrency industries, they must be prepared to indemnify the risks involved in the industry. 

### Describe alternatives you've considered

The writer recommends that if the government wants to tax crypto companies, they should provide emergency insurance funding to secure against potential asset loss due to the volatility of the crypto industry. Crypto industries can sign an agreement with the federal ministry of finance for deposit insurance levies every year, and the government in turn acts as an insurance firm to cover all range of possible asset loss for crypto holders in that registered crypto company. The government can act as a warranty provider. 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by sscornelius** [comment]
digitalstarWorld . . . .
