### ISSUE TITLE
Gas and Fees page: outdated content around mining

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#10430]
### Describe the bug

Since the transition to PoS we do not have "miners". This content needs to be updated. 
<img width="778" alt="Screenshot 2023-06-09 at 18 40 14" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/cf0e8d7d-ed78-4dd6-b021-631b7023655b">

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/gas/

### Expected behavior

provide current system description

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by mesquitaoliveira** [comment]
Hey @konopkja, the updated version would be like this, but it needs some tweaking to fit the context:

> In the current Ethereum landscape, the consensus mechanism known as Proof of Stake (PoS) has taken over from the previous Proof of Work (PoW) system. Validators now contribute their ETH holdings to a smart contract and actively engage in network operations. So, to become a validator, one must deposit 32 ETH. The transition to PoS has brought several advantages, including improved energy efficiency, lower barriers to entry, and a reduced risk of centralization.

**Comment by konopkja** [comment]
@jmcook1186 @minimalsm

**Comment by konopkja** [comment]
ping @minimalsm @jmcook1186
