### ISSUE TITLE
Eth2.0 Page

### ISSUE THREAD

**Issue by edsonayllon** [ethereum/ethereum-org-website#1046]
**Is your feature request related to a problem? Please describe.**

Information on Eth2.0 is dispersed across several resources. It might be useful to have a canonical source of what the regular user can expect in a clear, simple to understand way. For example, the regular user may want to know that ETH can't be transferred in Phase 0. 

**Describe the solution you'd like**

A page on the website, maybe ethereum.org/eth2. The page can describe clearly what Phase 0 is and isn't, as well as links to resources on how to participate or more information for those who want something more technical. Then a short snippet on what the next phases are and what to expect. As the release of Phase 0 approaches, maybe have the page link or a feature on the homepage a few weeks before the release, and removed from the homepage 4 months after the release. 

**Describe alternatives you've considered**

The website already has Eth2.0 resources. We could just continue with that section.

**Additional context**

No additional information.

**Comment by samajammin** [comment]
Thanks for suggesting this @edsonayllon! Completely agree this should exist. I'm going to close this out in favor of an existing issue (#878) - please feel free to weigh in there.

**Comment by samajammin** [comment]
@all-contributors please add @edsonayllon for ideas.
