### ISSUE TITLE
Redesigning the homepage 

### ISSUE THREAD

**Issue by rohan9024** [ethereum/ethereum-org-website#10478]
### Is your feature request related to a problem? Please describe.

The feature is not related to any problem yet we can make the homepage look much better by adding animations.

### Describe the solution you'd like

We can add animations, add 3d models using three js and tailwind css for styling.

### Describe alternatives you've considered

-Animations using framer motion
-Rendering 3d models using three js
-Tailwind css for styling

Tailwind css--> https://tailwindcss.com/

### Additional context

Please assign me this issue. If the design team has already made some 3d models or designs, I would love to collaborate with them.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by rohan9024** [comment]
@corwintines can you please guide me on this?

**Comment by konopkja** [comment]
Hello @rohan9024, Im excited to see a community member start looking into animations. Thank you for taking the initiative. 

The core team has considered adding animations to the site few times too. They could be a great UX enhancer. While it is exciting, we would like to explore this on a smaller scale at fist to see the performance. 

My suggestion that would have buy-in is to:

1. animate menu icons: globe and sun/halfmoon using framer
2. inspiration for what we are thinking: https://m2.material.io/design/iconography/animated-icons.html

After that maybe we can move forward and explore other parts of the website that could be enhanced with animations. 

Would you be up to take this on?

**Comment by rohan9024** [comment]
@konopkja Yeah sure.... I would love to.... Can I add tailwind css?

**Comment by konopkja** [comment]
> @konopkja Yeah sure.... I would love to.... Can I add tailwind css?

@pettinarip fyi

**Comment by bod0bod** [comment]
> @konopkja should I proceed with it?

Certainly

**Comment by pettinarip** [comment]
Hi @rohan9024 exciting idea! thanks for sharing and offering your coder hands for it :)

We are not using Tailwind, lets not add it.

Our current css stack is Chakra UI + framer motion. We should be able to create the animations with those tools. You can see [here](https://chakra-ui.com/getting-started/with-framer) how to use it.

**Comment by konopkja** [comment]
@rohan9024 do you still want to work on this? if so let us know and i will assign you the issue to start the work :)

**Comment by rohan9024** [comment]
@konopkja yeah definitely! I would love to.
But I need some assistance since I'm new to gatsby and chakra ui.

**Comment by pettinarip** [comment]
@rohan9024 the error stack indicates that you have something related to tailwind installed and that is generating the conflict. I'd recommend cleaning your node_modules and reinstalling everything again. To make sure that you don't have any tailwind related code in the deps.

**Comment by rohan9024** [comment]
> @rohan9024 the error stack indicates that you have something related to tailwind installed and that is generating the conflict. I'd recommend cleaning your node_modules and reinstalling everything again. To make sure that you don't have any tailwind related code in the deps.

I have done that but still says the same

**Comment by rohan9024** [comment]
> Hey @rohan9024
> 
> Just wanted to check the scope of this so we can update the issue. Are you going to be starting with the animation of the light/dark mode icons?
> 
> As @pettinarip mentioned, I don't think we should be adding any new libraries for this. Tailwind will be unnecessary for our project, and three.js is quite heavy and I would push back on adding this too. But, we do use framer already, so feel free to use that!

Hey @corwintines 

I'll be animating the icons but I'm some errors, can you please help me out?

The error is listed above in the conversation ⬆️

**Comment by corwintines** [comment]
I cant really help with that information you have. But like Pablo mentioned, the errors mention tailwind so im guessing something is happening there. One option could just be starting fresh with a new with a fresh clone and doing the yarn install there. Make sure you are using Node version 18.

**Comment by rohan9024** [comment]
yeah sure I'll try it out.

**Comment by rohan9024** [comment]
hey @corwintines @pettinarip 
Can you please guide me on where are these icons located and where are they stored? So that I can make changes accordingly.

![image](https://github.com/ethereum/ethereum-org-website/assets/64919642/643ceed5-5207-4f5f-bd73-22e4a9004078)


Also, I would like to ask like.... I'm new to gatsby and chakra ui. Are there any recommended videos I should watch?

**Comment by wackerow** [comment]
Going to mark this closed with #10811; please feel free to open a new issue to discuss further animations. Do note that the homepage is currently being redesigned, so [Discord](https://ethereum.org/discord) would probably be the best place to chat about this.
