### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by seidenbergerscott** [ethereum/ethereum-org-website#10479]
### Describe the bug

There's a simple typo in the Execution vs Consensus client on the Staking pools page.

### To reproduce

1. Go to (https://ethereum.org/en/staking/pools/)
2. Click on Execution Diversity and Consensus Diversity

### Expected behavior

Consensus diversity
Service should not run more than 50% of their aggregate validators with a majority **consensus** client.

Execution diversity
Service should not run more than 50% of their aggregate validators with a majority **execution** client.

### Desktop (please complete the following information)

- OS. Mac OS
- Browser: Chrome

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by KaranKaira** [comment]
Hi @seidenbergerscott I can take this up.. Pls assign this to me

**Comment by seidenbergerscott** [comment]
Resolved via PR, merged to dev.
