### ISSUE TITLE
Suggest a tutorial: Building a user interface for your contract

### ISSUE THREAD

**Issue by qbzzt** [ethereum/ethereum-org-website#10489]
### Tutorial title

Building a user interface for your contract

### Tutorial description

You found a feature we need in the Ethereum ecosystem. You wrote the smart contracts to implement it, and maybe even some related code that runs offchain. This is great! Unfortunately, without a user interface you aren't going to have any users, and the last time you wrote a web site people used dial-up modems and JavaScript was new. 

This tutorial is for you. Using modern components such as TypeScript, React, Vite, and Wagmi, we will go over a modern, but minimal, user interface and learn how to implement these functions:

- Connect a wallet to the user interface, specifying which blockchains are supposed by your application.
- Call a smart contract to read information.
- Send a transaction to a smart contract.
- Monitor events from a smart contract to identify changes.

### Tutorial tags

frontend, wagmi, react, vite, 

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

1. Introduction: Why do this?
    1.1. Why pretty matters - the next billion people
2. How does React work?
    2.1. Components
    2.2. Hooks
3. Wagmi - what it is and why it matters
   3.1. Scaffolding
4. Connect to the user's wallet
    4.1. Specify which chains are supported by your app
5. Read from a contract
6. Send a prepared transaction
7. Monitor events
8. Conclusion, why it's time to focus on user experience

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by qbzzt** [comment]
@corwintines and @wackerow, are you interested in this topic, "UI building for smart contract devs"?

**Comment by corwintines** [comment]
This seems interesting to me. @wackerow what do you think?

**Comment by minimalsm** [comment]
Sounds cool @qbzzt!

For the sake of education, would it be better to use a more conventional package manager like npm or yarn? I've not had the chance to work with Vite yet, but sticking to a more 'out of the box' setup might help learners concentrate more on grasping the core concepts of building a UI around a smart contract.

**Comment by minimalsm** [comment]
> 8. Conclusion, why it's time to focus on user experience

What does this mean?

**Comment by qbzzt** [comment]
> For the sake of education, would it be better to use a more conventional package manager like npm or yarn? I've not had the chance to work with Vite yet, but sticking to a more 'out of the box' setup might help learners concentrate more on grasping the core concepts of building a UI around a smart contract.

The point of vite isn't to be a package manager, but a web server [(see here)](https://vitejs.dev/guide/why.html).

**Comment by qbzzt** [comment]
> > 8. Conclusion, why it's time to focus on user experience
> 
> What does this mean?

Just a reiteration of why this matters. Next billion and all that.

**Comment by shrirajpawar4** [comment]
@minimalsm 
I have written a tutorial to build interface and integrate with contract. Will this count as contribution?
https://shrirajpawar04.hashnode.dev/building-an-on-chain-to-do-list
