### ISSUE TITLE
Bug report: Remove Origin Ether from staking pool services

### ISSUE THREAD

**Issue by hanniabu** [ethereum/ethereum-org-website#10495]
### Describe the bug

1. It's actually not an LST at all and just a defi yield protocol that deposits your funds into other projects like Convex, Rocket Pool, Lido, and something called Morpho. This exposes uninformed users to additional risk that they're likely unaware of, and would love to ignore with the site advertising 9.36% APY.
2. There's only 223 holders so it's an extremely new/risky protocol on top of that: https://etherscan.io/token/0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3
3. It has a green checkmark for execution diversity, yet both Rocket Pool and Lido have a question mark. How can that be?

### To reproduce

1. Go to https://ethereum.org/en/staking/pools/#explore-staking-pools
2. See Origin Ether listed

### Expected behavior

1. Go to https://ethereum.org/en/staking/pools/#explore-staking-pools
2. Not see Origin Ether listed

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by hanniabu** [comment]
Pull request https://github.com/ethereum/ethereum-org-website/pull/10496

**Comment by zymox** [comment]
I agree with this. This is not an LST. Seeing some DeFi protocol most never heard of on the top of the "staking pools" page with "all lights green" seems like a weird mistake that should be corrected.

**Comment by domothyb** [comment]
Also agree for all the reasons mentioned, ethereum dot org is the last place that should confuse "staking" with yield aggregating ERC20s

**Comment by Valdorff** [comment]
This is silly. 

I think they were quite clear here:
> since we are not running any validators, it is not possible for 50% of the OETH aggregate validators to be with a majority consensus client

There is no staking happening here.

**Comment by hanniabu** [comment]
@corwintines I've already made a PR: https://github.com/ethereum/ethereum-org-website/pull/10496
