### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by wrexgem** [ethereum/ethereum-org-website#10543]
### Wallet name

Gem Wallet

### Wallet description

Gem Wallet is Multicurrency wallet for iOS and Android that supports Ethereum, Layer 2s, DeFi, NFTs and soon staking and swapping, all from its mobile app. Gem Wallet is an open source wallet, anyone can look and audit its code on Github. 

### Wallet logo

![Gem Wallet Logo](https://github.com/ethereum/ethereum-org-website/assets/134736543/8a5f1f72-62dd-467b-ad92-205b706443df)

### Background color for brand logo

24262a

### URL to the project

gemwallet.com

### When did the wallet go live to users?

01.04.2023

### Does the wallet have an active development team?

https://github.com/gemwalletcom

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English, Russian, German, Chinese (Simple)

### What social links are there for the project?

Twitter: https://twitter.com/GemWalletApp
Telegram: https://t.me/gemwallet_en
Discord: https://discord.gg/9GMTjD8RhF

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS, Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

https://github.com/orgs/gemwalletcom/repositories

### What license is the wallet software released under?

GPL

### Who holds the private keys?

Only the user has access to his/her private keys

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

Yes

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Soon

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

https://t.me/magicwrex

### Does the wallet have a dedicated support team?

Best to join our Telegram for support: https://t.me/gemwallet_en

### What educational resources/documentation do you provide to users?

https://gemwallet.com/blog/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Hey @wrexgem 👋, thanks for raising this issue.

Unfortunately, this wallet does meet our current wallet criteria of being a security-tested product. Feel free to create a new issue in the future if that changes.

Thanks again 😀
