### ISSUE TITLE
Change button style to our default main button

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#10553]
### Describe the bug

On https://ethereum.org/en/run-a-node/ there are custom style buttons that were supposed to match the branding of dappnode and avado, but since then both brandings changed and I think its better to keep there our button style instead anyway.

### To reproduce

1. Go to https://ethereum.org/en/run-a-node/
2. scroll down to choose your adventure

### Expected behavior

consistent button style usage with our main CTA style
<img width="619" alt="Screenshot 2023-06-27 at 19 06 11" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/b07757e6-4f6f-4078-95a5-005f37e290c9">

### Screenshots

![Screenshot 2023-06-27 at 17 49 49](https://github.com/ethereum/ethereum-org-website/assets/100724231/8750e1cb-14d5-498e-80ff-e30c30645c8d)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by hashnj** [comment]
hello, i would like to contribute to resolve this issue ,i am new to open source and git hub
please also guide me a bit

**Comment by ItIsOHM** [comment]
Hello @konopkja, can I work on this issue too if there are any pending tasks other than the ones assigned to @hashnj?

**Comment by M-A-Sattar** [comment]
Hi, I'm currently learning blockchain development, and would like to try and fix this issue, I'm very new to open source, can I participate?
