### ISSUE TITLE
Wallets - BlockWallet changes

### ISSUE THREAD

**Issue by julianariel** [ethereum/ethereum-org-website#10561]
Hey team,

Last year we submitted the suggestion to list our wallet on the website: https://github.com/ethereum/ethereum-org-website/issues/8002

Since then, we've integrated the feature to buy crypto within the wallet and would like to reflect that on the wallet's list, along with other changes:

![image](https://github.com/ethereum/ethereum-org-website/assets/11839151/a32b0801-5d54-4790-8eb2-0e374ee3d15d)

- New logo: we've rebranded our company and changed the logo. I'm attaching the new one
- <img src="https://github.com/ethereum/ethereum-org-website/assets/11839151/a1760372-0b47-4af4-8f93-05de25275530" width=24 height=24/>

- Buy Crypto: we've integrated OnRamper. More info can be found here: https://blockwallet.io/blog/mastering-crypto-purchases-with-block-wallet
- Discord link: updated our Discord server invite link to https://discord.gg/blockwallet

Please let me know if you need anything else to perform these updates or if this the correct way to request them,

Thanks!!

**Comment by corwintines** [comment]
Thanks @julianariel. Is this something you would like to work on?

**Comment by julianariel** [comment]
@corwintines sure! I can work on it; how do you think I should proceed?
