### ISSUE TITLE
remove gatsby emotion plugin

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10562]
After we finish the UI migration of all the components and pages, remove this plugin that is not needed anymore.

**Comment by TylerAPfledderer** [comment]
@pettinarip what's left at this point?

**Comment by pettinarip** [comment]
@TylerAPfledderer for the UI migration, just this and cleaning up some stuff like not using the `SharedStyledComponents` anymore, double check that we are not using `styled` anymore, removing deprecated components like `Icon` and `OldEmoji`. I'll do that today and close this epic.

The only component left to migrate is the `react-select` component that you already covered in this PR #10542. But that one is also doing the DS implementation. I'll try to get that one merged soon but I'll not consider it as necessary to close this epic.

After that, we could make tons of refactors but we will not include them in the scope of this epic. We can do them more organically as we implement the new components from the DS.

**Comment by corwintines** [comment]
@pettinarip I merged the above PR, I think this can be closed out now, but wanted to double check first.

**Comment by pettinarip** [comment]
Awesome, yes. Thanks!
