### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by trial123Zel** [ethereum/ethereum-org-website#10579]
### Wallet name

Zelcore Wallet

### Wallet description

Multi-asset wallet for desktop and mobile devices with quickswaps, fiat ramps, and WalletConnect built-in. Hold assets on 70 different blockchains including NFTs, digital gift cards, and 1M+ other tokens securely in one app.

### Wallet logo

![Zelcore - SM LOGO](https://github.com/ethereum/ethereum-org-website/assets/38964930/eaf986b6-de41-4b06-976b-88c0b974baae)
![Zelcore - SM LOGO_Round](https://github.com/ethereum/ethereum-org-website/assets/38964930/d38454d9-9fb2-4c9e-a165-1f8166a0b610)

### Background color for brand logo

#DA4DFF

### URL to the project

https://zelcore.io

### When did the wallet go live to users?

May 31, 2018

### Does the wallet have an active development team?

https://github.com/ZelCore-io/

### Is the wallet globally accessible?

Yes.

### Is the wallet available in multiple languages?

Czech, German, Danish, Greek, English, Spanish, Finnish, French, Italian, Norwegian, Polish, Portuguese, Croatian, Russian, Swedish, Turkish, Ukrainian, Chinese

### What social links are there for the project?

Twitter - https://twitter.com/zelcore_io
Medium - https://medium.zelcore.io/
Facebook - https://www.facebook.com/zelcore.io/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS - https://apps.apple.com/us/app/zelcore/id1436296839
Android - https://play.google.com/store/apps/details?id=com.zelcash.zelcore

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Windows, MacOS, Linux (.deb, .appimage) - https://zelcore.io/downloads/

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

No, partially open-source: https://github.com/ZelCore-io/

### Who holds the private keys?

Zelcore is completely non-custodial. Users have sole ownership of their public/private keypairs for every address  and they are not stored nor transmitted off-device.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Zelcore utilizes SHA256 with proprietary salts and user-supplied entropy to create key-pairs.

### Has the wallet's smart contract code or security modules been audited?

No smart contracts

### Does the wallet have an internal security team?

The lead developers have app security backgrounds.

### Any other security testing that should be noted?

No

### Scam protection?

No

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, WalletConnect

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

https://docs.zelcore.io/guides/quickswap/

### Does the wallet support multi-chain networks?

Yes

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

No

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

https://docs.zelcore.io/guides/fiat_on/

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

https://twitter.com/zelcore_io
Discord: trial123
email: parker@zel.network

### Does the wallet have a dedicated support team?

Yes, https://help.zelcore.io/support/home
Turnaround time < 24 hours

### What educational resources/documentation do you provide to users?

https://docs.zelcore.io/

### Does the wallet have any integrated tools not mentioned above?

- Ability to change RPC, API, Explorer, and Node endpoints
- decentralized 2FA stored on-chain
- Masternode management for multiple blockchains

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Hey @trial123Zel 👋, thank you for raising this issue.

Unfortunately, this wallet does not meet our current criteria for being a security-tested product. Feel free to reopen this issue or create a new one if there is any change to this in the future.

Thanks again 😀
