### ISSUE TITLE
Add Presail to dapp overview

### ISSUE THREAD

**Issue by bas-db** [ethereum/ethereum-org-website#10586]
### Name

[Presail](https://presail.com)

### Description

Manage everything from one place: Fundraising, investor management & token vesting.

### Logo

![Logo Vertical Dark 720x720](https://github.com/ethereum/ethereum-org-website/assets/76127152/e99cdf48-a37e-4309-b59a-59baa3e3f8da)

### Brand color

#1c2029

### Is your dapp open source?

No

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Presail provides a UI and the ability to view information from the blockchain easily. That said, most actions a user completes on Presail are either off-chain or entirely DeFi, and we use WalletConnect, and ether.js to perform key events.

When it comes to distributing tokens and performing OTC trades, it is facilitated through the Presail smart contract that can be found here: https://etherscan.io/address/0x97e6567c3b63d2e0ec4ad0b96b356c675da1ab7e

And is validated by Certik: https://skynet.certik.com/projects/presail#audit 

In addition, we are a professional business:
- We have been in existence for two years
- Have raised over $5M from professional VCs such as Kraken Ventures.
- Over 1,200 projects have received investments through Presail, with over $150M+ going through our platform.

### Can a user access the dapp without creating an account?

A user creates an account by logging in with a wallet of their choosing. The most used is Metamask.

### Are dapp funds non-custodial?

Yes.

### Do you offer community support?

Yes, our telegram can be found here: https://t.me/presailcom we also offer live chat support to anyone.

### Describe any geographical restrictions on usage of your dapp

The app is globally accessible, with restrictions put in place on countries that are globally sanctioned:

- Iran
- Myanmar 
- North Korea
- Russia
- Syria 
- Crimea, Donetsk, Luhansk, Zaporizhzhia, and Kherson in Ukraine.

### Would you like to work on this issue?

- [x] Yes
- [x] No

**Comment by jase-b** [comment]
I'd like to work on this issue. ✋

**Comment by ameeetgaikwad** [comment]
Would like to work on it, give me the details!

**Comment by corwintines** [comment]
Thanks @bas-db 

After looking at this, we don't think this is ready to be on ethereum.org. The reasons are:

- When looking into socials for this project, we noticed there is not really much going on in terms of both use by Presail, but also others using it
- There is no way to use this application without needing to talk to a human first
- When going to https://app.presail.com/users/sign_up and signing in, the dashboard does not show anything similar to what is being shown for products on the site

Going to close this out, but good luck!
