### ISSUE TITLE
Apply for the inclusion of imToken Staking introduction on the SaaS page

### ISSUE THREAD

**Issue by 1128Mars** [ethereum/ethereum-org-website#10582]
### Project name

imToken Staking

### Product type

Staking as a service

### Logo

![Symble_Rounded](https://github.com/ethereum/ethereum-org-website/assets/50956550/4e22cce9-ee69-40a2-9d25-c95f4168269a)

### Description

imToken is a decentralized wallet that has deeply integrated the non-custodial ETH staking solution. Over the past two years, imToken has attracted a cumulative total of over 41,120 ETH to participate in non-custodial staking.

### Website

https://token.im/

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes, the non-custodial ETH staking service integrated by imToken has been officially launched for over two years and is running stably.

### What wallets support the product or service?

imToken mobile wallet only.

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

imToken non-custodial staking service does not support staking with <32 ETH.

### If a service, what are the fees associated with using the service?

Currently, the non-custodial ETH staking fee includes a maintenance service fee of (0.2 ETH/year/validator) and a block reward sharing fee.

Maintenance Service Fee

- Fee target: Single validator (32 ETH)
- Pricing: 0.2 ETH/year/validator

Block Reward Sharing Fee

- Fee target: All block rewards generated by the validator group
- Pricing: 20% of the block rewards will be allocated to the non-custodial service provider (the remaining 80% will be evenly distributed among all validators staked through imToken)
- Payment method: Automatically distributed proportionally each time block rewards are generated

### If the product or service involved a liquidity token, what are the tokens involved?

imToken Staking does not involve a liquidity token.

### What date did the project or service go live?

In the 2.9.1 App version released on April 30, 2021, imToken officially launched its non-custodial ETH staking service.  Related article: https://support.token.im/hc/en-us/articles/900007069303-imToken-now-with-native-Eth2-integration-and-staking-as-a-service Version release log: https://mainnet-bizapi.token.im/support/questions/release-v2

### Has the project undergone an external security audit?

[Smart contract security audit report-BatchDeposit.pdf](https://github.com/ethereum/ethereum-org-website/files/11892372/Smart.contract.security.audit.report-BatchDeposit.pdf)

### Has the project undergone any security bug bounties?

The imToken Staking function is part of the imToken Wallet, which accepts the bounty program together with the wallet.

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

The principal and earnings from the consensus layer are trustless.

Users always control the withdrawal credentials, maintain ownership of the funds, and periodically receive consensus layer (CL) rewards that have accumulated in the validator nodes from the Ethereum consensus layer network.

For the additional income generated in the execution layer, users are required to place trust in the service provider and periodically obtain additional income rewards from the service provider within the execution layer.

### If a pooled staking service, can users participate as a node operator without permission?

No, we are not pool staking.

### If listing a staking-as-a-service, are users required to sign-up for an account?

imToken is a decentralized wallet. Users only need to import or generate a wallet to access the non-custodial ETH staking service.

### If listing as staking-as-a-service, who has access to the signing keys?

The node operation service provider has permission of the signing key.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

imToken Staking supports two types of withdrawal credentials. Validators created using version 2.12.1 and below will use the 0x00 type address format as the withdrawal address, while validators created using version 2.12.2 and above will use 0x01. In either case, the user always has control over the keys to the withdrawal credentials.

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

We support multiple clients (Prysm, Lighthouse) simultaneously, and can swiftly switch to other clients when one client encounters a problem.

### What platforms are supported?

iOS, Android

### What user interfaces are supported?

mobile app

### Social media links

Discord: https://discord.com/invite/imToken
Twitter: https://twitter.com/imTokenOfficial
YouTube: https://www.youtube.com/@imtoken_official
LinkedIn: https://www.linkedin.com/company/imtoken/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Question has been left unanswered. Goign to close this out as stale.
