### ISSUE TITLE
Add Starknet Layer 2

### ISSUE THREAD

**Issue by drspacemn** [ethereum/ethereum-org-website#10587]
### Name

Starknet

### Logo

![SN-Symbol-Flat colour](https://github.com/ethereum/ethereum-org-website/assets/16685321/905ca9c3-f524-4104-968a-c499ac6477a3)

### Description

Starknet is a Validity Rollup Layer 2. It provides high throughput, low gas costs, and retains Ethereum Layer 1 levels of security.

### Website

https://www.starknet.io

### Developer documentation

https://docs.starknet.io/documentation

### L2BEAT page

https://l2beat.com/scaling/projects/starknet

### Is the project open source?

- https://github.com/starkware-libs/cairo
- https://github.com/starkware-libs/cairo-lang

### What category of layer 2 is it?

Starknet operates as Validity Rollup L2 network over Ethereum, enabling any dApp to achieve unlimited scale for its computation – without compromising Ethereum’s composability and security, thanks to Starknet’s reliance on the safest and most scalable cryptographic proof system – STARK.

Starknet Contracts and the Starknet OS are written in Cairo – supporting the deployment and scaling of any use case, whatever the business logic.

### Does the layer 2 use Ethereum Mainnet for data availability?

Mainnet Verifier
https://etherscan.io/address/0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60

Mainnet Core Contracts
https://etherscan.io/address/0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4

### Which bridges are used to onboard users?

StarkGate is the Ethereum↔Starknet token bridge developed by StarkWare. Each supported token is associated with an L1 and L2 bridge contract that is communicating via Starknet’s messaging mechanism.

https://starkgate.starknet.io

### Link to dapp ecosystem (if applicable)

https://www.starknet-ecosystem.com

### Token contract list (if applicable)

https://github.com/starknet-io/starknet-addresses/blob/master/bridged_tokens/mainnet.json

### What date did the project go live?

https://etherscan.io/tx/0x4810a17f4fa3460fa20990b786d0b5be1be66a2cdc261e85f8e482e2ea06ba54

### Is this project a fork? If yes, which project was forked?

No

### What wallets support this layer 2?

Argent
Braavos
BitKeep
Dynamic
Cartridge

### How can users and/or developers connect too this layer 2 network?

NaaS:
- https://starknet-mainnet.g.alchemy.com/v2/
- https://starknet-mainnet.infura.io/v3/
- https://www.lavanet.xyz
- https://chainstack.com

Nodes:
- https://github.com/eqlabs/pathfinder
- https://github.com/starkware-libs/papyrus
- https://github.com/NethermindEth/juno

### Has this project undergone an external security audit and/or a bug bounty?
- https://github.com/starkware-libs/starkex-contracts/blob/master/audit/EVM_STARK_Verifier_v4.0_Audit_Report.pdf
- https://immunefi.com/bounty/starknet

### Is there an active team developing the project?

Yes

### Is there a block explorer?

https://starkscan.co
https://voyager.online
https://viewblock.io/starknet

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by drspacemn** [comment]
This issue was marked as stale but was never assigned?

**Comment by corwintines** [comment]
closing with above PR
