### ISSUE TITLE
A high level introduction to Ethereum

### ISSUE THREAD

**Issue by charlesfreeborn** [ethereum/ethereum-org-website#10589]
### Is your feature request related to a problem? Please describe.

Getting to understand Ethereum from a high-level perspective was one of the challenges I had, in understanding what Ethereum is. 

As a technical writer and one who is committed to contributing to the Ethereum ecosystem, I wrote about it - explaining in my own terms what Ethereum is. And I believe that this will also help share more light and understanding on Ethereum.

### Describe the solution you'd like

I am submitting this article I wrote on a high level introduction to Ethereum - which I believe readers will find more insightful into getting to understand Ethereum.

Here's a link to a [high-level introduction to Ethereum](https://medium.com/@charlesfreeborn/a-high-level-introduction-to-ethereum-1a9be56a786c) by [Charles Freeborn](https://twitter.com/charliecodes)high-level

### Describe alternatives you've considered

One of the major alternative I used in understanding Ethereuem is from the Ethereum website on [What is Ethereum](https://ethereum.org/en/what-is-ethereum/)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @charlesfreeborn, so sorry for the long delay here. Appreciate your post and didn't mean for this to fall through the cracks without a reply 🙏. 

The article linked out is nice but does contain a few inaccuracies, and I'm not sure this adds too much beyond what is found on the site right now.

Going to close this out, but cc: @konopkja if you disagree or feel there could be a place for this just re-open and ping.
