### ISSUE TITLE
Add/Update/Delete quiz question

### ISSUE THREAD

**Issue by ivpavici** [ethereum/ethereum-org-website#10591]
### Page URL

https://ethereum.org/en/quizzes/ -> Section "The Merge"

### Question content

Proof-of-work is incorrect answer on the question:

_Ethereum’s consensus layer was formerly known as:_

![image](https://github.com/ethereum/ethereum-org-website/assets/2848732/10108414-c213-4b5b-9832-e2d3b558a7d1)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by 0x0OZ** [comment]
The question and the answer are both correct.
before The merge, Proof-of-Work POW _was_ the used consensus mechanism in Ethereum network.

**Comment by wackerow** [comment]
<img width="533" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/360222d8-b76e-4938-9135-0a238faff421">

The question probably needs larger tuning... Out of the choices, the "consensus layer" was known as "ETH2". "Proof-of-work" was part of the existing consensus _mechanism_ that was embedded in the _execution layer_)

We could leave this as is, but if we change I would advocate for either reworking this entire question or simply removing.

@ivpavici Any thoughts on that?

**Comment by ivpavici** [comment]
@wackerow oh I didn't know about Eth2... I assumed that the explanation part is the correct answer, but doesn't match the answer itself - that was something that confused me...

![image](https://github.com/ethereum/ethereum-org-website/assets/2848732/360300bb-b3e1-44a7-979e-cb37832310a1)

But in any case, feel free to close the issue!
