### ISSUE TITLE
LearnWeb3.io will be the best option for tutorial

### ISSUE THREAD

**Issue by SahityaRoy** [ethereum/ethereum-org-website#10596]
### Tutorial title

LearnWeb3.io

### Tutorial description

LearnWeb3 is the leading educational ecosystem in Web3. We offer a wide range of educational courses, resources, and tools that are designed to help developers learn and grow in the Web3 space.

### Tutorial tags

Solidity

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://learnweb3.io/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
@all-contributors please add @SahityaRoy for ideas
