### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by SahityaRoy** [ethereum/ethereum-org-website#10595]
### Dev tool name

Learnweb3

### Dev tool description

LearnWeb3 is the leading educational ecosystem in Web3. We offer a wide range of educational courses, resources, and tools that are designed to help developers learn and grow in the Web3 space.

How we're different

The world is changing. New technologies like blockchain and AI are revolutionizing the landscape of computing forever. Our goal is to provide you top-tier free education so you can build the bridges that lead us to the future.

### When did the dev tool go live?

It's Live 

### Where do you think this page should be shown?

https://ethereum.org/en/developers/learning-tools/
this section i would like to add this tool.

### Is the product open source?

Yes

### GitHub URL

https://github.com/LearnWeb3DAO

### Documentation URL

 https://www.learnweb3.io/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Closing in lieu of #10138

**Comment by wackerow** [comment]
@SahityaRoy If you're interested in working on this still, please comment on #10138 an I can assign
