### ISSUE TITLE
Suggest a dapp name Dapps.co

### ISSUE THREAD

**Issue by SahityaRoy** [ethereum/ethereum-org-website#10597]
### Name

dapps.co

### Description

dapps is a decentralized app store for web3 apps for seamless adoption, facilitating users use of any web3 application on dapps.
Open
Neutral
Censorship-resistant
Programmable
Decentralized
Chain agnostic

dapps helps in the launch and monetization of new or existing decentralized applications. dapps solve the main issues faced by web3 users like discoverability, and visibility and increase retention by enabling on-chain communication and notifications.

dapps help projects build a community around their product, and give users a seamless experience and unstoppable communication.dapps is interoperable meaning applications from different chains can be listed on the platform and users can interact with different chains.

### Logo

https://dapps.co/guidelines

### Brand color

Hex Code: #30BCC2  Rgb: 48, 188, 194

### Is your dapp open source?

Yes

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

https://dev.dapps.co/
Dapps smart contracts provide the functionality to add new dapps to the [dapps.co](http://dapps.co/) platform. Anyone can register their dapp and other users can subscribe to these dapps to receive notifications. While registering a new dapp, we need to provide an account that will act as the admin of the dapp and will have some extra privileges. We will discuss them later in the documentation. All the notifications will be encrypted using the user's secondary wallet (if it exists, otherwise simply encoded), created during the user onboarding process

### Can a user access the dapp without creating an account?

YES

### Are dapp funds non-custodial?

Yes

### Do you offer community support?

Yes

### Describe any geographical restrictions on usage of your dapp

No 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @SahityaRoy 

I was looking around this, and noticed the following:
- The explore takes you to a beta
- The beta products I am not sure are legit or not, but when you look at the product itself that page is not useable. There isnt any description, the links dont work, etc.
- Lots of broken links in the homepage
- The trusted by section lists a few chains, but when you select view all they are nowhere to be seen and there is a small list of random projects

These were things I noticed with a quick walkthrough of the site, and going to reject as its not a great user experience. The purpose of our dapps page is to give users a good starting point in their journey, and this doesn't fit that purpose.
