### ISSUE TITLE
Dead / invalid link in docs

### ISSUE THREAD

**Issue by yash251** [ethereum/ethereum-org-website#10602]
### Describe the bug

In the `Further Reading` section of Smart contract verification there is an invalid / dead link.

### To reproduce

1. Go to 'https://ethereum.org/en/developers/docs/smart-contracts/verifying/'
2. Scroll down to 'Further reading'
3. Click on 'How to verify the source code of Ethereum smart contract'
4. See error - Site not loading

### Expected behavior

It should be removed

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Assigning to you @yash251 since you indicated being interested in working on this

**Comment by KanishkKhurana** [comment]
hey @corwintines ,
is this issue solved? i would love to pick this up.

**Comment by wackerow** [comment]
I think this is fixed now. Please re-open if I'm mistaken
