### ISSUE TITLE
Add Origin Ether dapp

### ISSUE THREAD

**Issue by sumpg41** [ethereum/ethereum-org-website#10613]
### Name

Origin Ether

### Description

Origin Ether (OETH) is a ETH LSD aggregator that combines the yield-generating functions of Lido, Rocket Pool, and Frax into one single, diversified token. OETH holders receive daily yield in the form of a positive rebase directly into their wallets.

### Logo

https://raw.githubusercontent.com/OriginProtocol/origin-website/master/static/img/coins/oeth-256x256.png

### Brand color

0074F0

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/OriginProtocol/origin-dollar/tree/master/dapp-oeth

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Origin currently has a continuous auditing agreement with [OpenZeppelin](https://openzeppelin.com/) to constantly review 100% of our smart contract changes. OpenZeppelin has audited Coinbase, Ethereum, Aave, Compound, and other leading projects. They are one of the most trusted auditing firms in the industry and we are thrilled to count them as part of our extended team.

All audits can be found here: https://docs.oeth.com/security-and-risks/audits

Origin also maintains an open bug bounty for up to $250k USD on [Immunefi](https://immunefi.com/bounty/origindollarousd/).

### Can a user access the dapp without creating an account?

A user can simply connect their Ethereum wallet to use the OETH dapp.

### Are dapp funds non-custodial?

Dapp funds are completely non-custodial with OETH. Users can go in and out as they please, at the speed of the Ethereum blockchain, for any of the collateral assets, or a basket of the mix.

### Do you offer community support?

OETH support is always available via the [Origin Protocol Discord](https://www.originprotocol.com/discord).

### Describe any geographical restrictions on usage of your dapp

There are no geographical restrictions to use the OETH dapp.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by sumpg41** [comment]
>Stop spamming this github 
>
Appologies, this was never my intention. We love Ethereum and are happy to be building on it. 



> This is not an LSD aggregator, it's a defi yield product. If it was an aggregator the yield wouldn't be 8%, a higher yield than each of those LSDs included.
> 

Ok, you are correct. It is not an LSD aggregator, rather it is a yield aggregator. OETH is fully 100% collateralized by ETH and LSDs. The current breakdown as of now is as follows:

ETH: 9774.14
Frax ETH: 2820.75
Rocket Pool ETH: 2555.35
WETH: 2163.14
Lido Staked ETH: 784.01

What are your thoughts on creating a new category for LSDfi on the dapps page?

**Comment by wackerow** [comment]
Right, so @sumpg41, this was the first request of this type to hit the repo... we had gone ahead and listed it based on loosely fitting in as a potential option for users, but please see #10495, as the response has not been great.

Personally wouldn't really support creating space for this on the dapps page as it's not intended to be a space for individual tokens. Until we have a better plan of action for that category of product, I'm going to close this out. Appreciate the understanding.

**Comment by sumpg41** [comment]
>Right, so @sumpg41, this was the first request of this type to hit the repo... we had gone ahead and listed it based on loosely fitting in as a potential option for users, but please see https://github.com/ethereum/ethereum-org-website/issues/10495, as the response has not been great.


@wackerow Thank you for explaining. 

> Personally wouldn't really support creating space for this on the dapps page as it's not intended to be a space for individual tokens. Until we have a better plan of action for that category of product, I'm going to close this out
>
Origin has multiple rebasing yield aggregators - would it be possible to add Origin Protocol to the dapps page instead of OETH? Origin Protocol is not very different from Index Coop, which I can see on the dapps page.

**Comment by sumpg41** [comment]
> > Personally wouldn't really support creating space for this on the dapps page as it's not intended to be a space for individual tokens. Until we have a better plan of action for that category of product, I'm going to close this out
> 
> Origin has multiple rebasing yield aggregators - would it be possible to add Origin Protocol to the dapps page instead of OETH? Origin Protocol is not very different from Index Coop, which I can see on the dapps page.

Hey @wackerow, just following up on this idea in case you missed it. Would this be possible?
