### ISSUE TITLE
Gray color on the selected result search list is difficult to read

### ISSUE THREAD

**Issue by rafarocha** [ethereum/ethereum-org-website#10615]
### Describe the bug

On the selected result search, the gray color chosen turns difficult to read text. 

### To reproduce

1. Go to ethereum.org
2. Click on the search button
3. Scroll down a selected result
4. See error image

### Expected behavior

If is not possible to change the orange color to the selected result box, maybe could try to change the black color selected text.

### Screenshots

![Screen Shot 2023-07-05 at 11 14 29](https://github.com/ethereum/ethereum-org-website/assets/730268/8e30c7eb-b4bf-4a7a-b972-96b2dfe59213)

### Desktop (please complete the following information)

I tested on chrome 114.0.5735.198 and firefox 114.0.2 (64-bits), macOS 11.4.

### Additional context

I will try to investigate how to help with this, although UI is not my area.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks for opening this @rafarocha. There is a fix going out for this https://github.com/ethereum/ethereum-org-website/pull/10594 in our upcoming release that goes out tomorrow. Going to close this out.

**Comment by rafarocha** [comment]
Nice!
