### ISSUE TITLE
Update to Launchnodes listing (features)

### ISSUE THREAD

**Issue by andreilicious23** [ethereum/ethereum-org-website#10637]
This edit aims to update the features under the Launchnodes listing on https://ethereum.org/en/staking/solo/.

The following changes take it account Paul's (@wackerow) latest comments in [this thread](https://github.com/ethereum/ethereum-org-website/issues/7483#issuecomment-1320829932):

1. Multi client - **Yes**. Launchnodes offers [Prysmatic](https://aws.amazon.com/marketplace/pp/prodview-jdqyf2ovwxyfu?ref_=srh_res_product_title) and [Teku](https://aws.amazon.com/marketplace/pp/prodview-i5mal3omdvayu?sr=0-11&ref_=beagle&applicationId=AWSMPContessa) clients. [Applicable website page](https://www.launchnodes.com/ln_products/ethereum-validator-node-prysmatic-client/)

2. Permissionless - **Yes**. Clients do not need permission from us or Amazon/GCP, they can just opt for any product on public cloud and use our self serve instructions to deploy on their own. We are only needed if the customer is not technical enough and requires assistance with spinning up the node. Otherwise, anyone can self-serve without our input. Instructions are openly available on every applicable product page. (Example: [Teku listing](https://aws.amazon.com/marketplace/pp/prodview-i5mal3omdvayu?sr=0-11&ref_=beagle&applicationId=AWSMPContessa) > Usage Information > View usage instructions)

3. Apart from AWS and Azure we are also on GCP, Tencent Cloud, and bare metal. Paul's (@wackerow) suggestion is to combine all cloud providers under Public Cloud but we feel that it nulls the delta between iops differences. Therefore, in order not to congest the box with all cloud providers Launchnodes' products are listed on, we propose to delete Azure and leave AWS, GCP, Bare Metal. The reason why we are happy to lose Azure is because currently AWS and GCP are far more economical to solo stake on than Azure, even with corporate pricing.

4. Opensource - **Yes**. We are open source as per Teku and Prysm, plus all files GCP and AWS related are on github; instructions are on Gitbook.

https://github.com/yashLN/Beacon_Presync
https://github.com/yashLN/Geth_Presync
https://launchnodes.gitbook.io/node-set-up-instructions/
https://launchnodes.gitbook.io/faqs-about-withdrawals-for-solo-staking/

5. Economical. We are not sure what is considered as economical but the validator node license is $20pcm (Teku) and our Beacon and Geth on GCP are extremely competitive to bare metal. 

Thank you and we are happy to provide any additional information if required. 

Andrei

**Comment by wackerow** [comment]
1. Looks good!
2. My argument would be that any service that uses Amazon (or Google, or Tencent) requires permission... The permission may be a low bar, and granted automatically for most users, but Amazon has the capacity to block the user, and will if demanded by an authority. This is unlike a smart contract interaction where absolutely nobody can stop the user. I would not mark this as permissionless, but certainly open to thoughts from others on this topic as I understand it's a bit nuanced. cc: @minimalsm @jmcook1186 
3. That's fine with me, personally would suggest just trying to keep the total tags to no more than six (which is already getting a bit crowded, cc: @nloureiro @konopkja for design thoughts)
4. Thanks for listing these repos. Assuming no other closed source software involved that I'm unaware of, this sounds fine to mark as open source.
5. Economical: "Users can operate a validator by staking less than 32 ETH, utilizing pooled funds from others". This is not related to any fees, but the ability to operate a staking node without providing the full 32 ETH yourself.

Welcome a PR for 1/3/4, but would prefer to get thoughts from others before moving on 2. Thanks for the update!

**Comment by andreilicious23** [comment]
Hi Paul (@wackerow),

1. Great
2. We also do bare metal if that helps but happy to go with your decision.
3. Looking forward to @konopkja and @nloureiro feedback
4. This is all. No other software is involved
5. Understood. Thank you for clarifying

**Comment by wackerow** [comment]
Forwarding from @andreilicious23 in #11061:
> Hi Paul (@wackerow). Based on the outcomes of #10637
> 
> Proposed changes for Launchnodes associated ticks on page: https://ethereum.org/en/staking/solo/
> 
> 1. Open source - YES
> 2. Permissionless - YES
> 3. Multiclient - YES
> 4. Audited - YES (if AWS audit is accounted for)

**Comment by wackerow** [comment]
@andreilicious23 Per above discussion looks like we settled on 1 (open source) and 3 (multiclient)... Still disagree with 2 and hadn't seen any further discussion. The "audited" note is new... are there publicly available audits for the open source software you're using (from the yashLN repos)?

**Comment by andreilicious23** [comment]
Hey @wackerow

2. Re permissionless - your point taken. We also do bare metal if that counts as permissionless. 
4. Only AWS internal audits. Happy to go with your take. No audits of YashLN's repos
