### ISSUE TITLE
Hindi Translation

### ISSUE THREAD

**Issue by Rohan-San** [ethereum/ethereum-org-website#10659]
Translations need to be added to [the Hindi intl](https://github.com/ethereum/ethereum-org-website/tree/dev/src/intl/hi).

**Comment by wackerow** [comment]
Thanks @Rohan-San! Our translations are all handled through [our Crowdin project](https://crowdin.com/project/ethereum-org). More info on our [translation program here](https://ethereum.org/en/contributing/translation-program/).
