### ISSUE TITLE
Suggest a wallet: Blocto Wallet

### ISSUE THREAD

**Issue by audrey5959** [ethereum/ethereum-org-website#10663]
### Wallet name

Blocto Wallet

### Wallet description

Blocto Wallet is your portal to the Web3 space. Gain access to crypto trading, NFT purchasing, crypto asset managing and even crypto learning all in one dApp.

### Wallet logo

![Blocto brand icon_Color](https://github.com/ethereum/ethereum-org-website/assets/34430992/922602d7-7776-433c-aede-851cfb50dc05)

### Background color for brand logo

#0075FF

### URL to the project

https://www.blocto.io/wallet

### When did the wallet go live to users?

1 November 2019

### Does the wallet have an active development team?

Yes

### Is the wallet globally accessible?

Yes, it is. No need to KYC.

### Is the wallet available in multiple languages?

Yes, it is including en, es, zh-cht, zh-chs, ja, ko, ru, pt.

### What social links are there for the project?

- Website: https://www.blocto.io/
- Discord: https://discord.com/invite/QRZTr6yHmY
- Twitter: https://twitter.com/BloctoApp
- Medium: https://medium.portto.com/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, both Android and iOS.

### Who holds the private keys?

Users can choose to be custodial or non-custodial. For more details about our mix-custodial model, please check out  https://docs.blocto.app/technical-documents/key-management
- For custodial users, the keys are held by Blocto server. 
- For non-custodial users, the keys are held by users.

### Has the wallet's smart contract code or security modules been audited?

Yes, here is the audit report: https://github.com/blocto/4337-contracts/blob/v1.5.0/contracts/v1.5.x/BloctoAccount_Audit_Final_Report_Quantstamp.pdf

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support multi-chain networks?

Yes, it does. https://docs.blocto.app/blocto-environment

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, it does.

### Who can the ethereum.org team can contact regarding the wallet in future?

TG: @jettlintw

### Does the wallet have a dedicated support team?

Users can join our Discord or submit a request through [our help center](https://support.portto.com/hc) to ask for help if they encounter any issues.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by audrey5959** [comment]
Hi @minimalsm @corwintines 👋, I need your assistance. If there's any additional information required, please let me know. Thank you.

**Comment by corwintines** [comment]
Thanks @audrey5959 

Going to reject listing Blotco at this time for following issues:
- When creating an account, you don't have the option to create a self custodial wallet first, without needing to give up personal information
- You need to create an account on Ethereum for each token in this wallet. That would get out of hand expensive very quick for users, especially mainnet Ethereum where each one of these is over 40USD per token account.
- The amount of points you get couldn't even create an account on mainnnet Ethereum from the start

**Comment by Adans14** [comment]
Hello Guys, query, I have the non-custodial blocto wallet, but when I try to log in I get the following message, what should I do?
![Screenshot_287](https://github.com/ethereum/ethereum-org-website/assets/152433155/36ced770-8d7a-4ccc-bcbd-6b822d34cd2c)
