### ISSUE TITLE
Add Tenderly Sandbox to "Code sandboxes" section

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#10672]
### Is your feature request related to a problem? Please describe.

We just added Tenderly Sandbox to the IDEs dev docs page:
https://github.com/ethereum/ethereum-org-website/pull/7930

I could also see it on this page https://ethereum.org/en/developers/learning-tools/ in the "Code sandboxes" section.

### Describe the solution you'd like

Add Tenderly Sandbox to "Code sandboxes" section

Page to edit: https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/developers/learning-tools.tsx

### Additional context

Discord discussion:
https://discord.com/channels/714888181740339261/938069929205329980/1020366950301454416

### Want to contribute?

We love PRs from the community, ping us here if you'd like to work on this issue.

**Comment by altinocoelho** [comment]
hello @minimalsm 

I'd like to work on this issue

**Comment by minimalsm** [comment]
Hey @altinocoelho, thanks for offering to help ⚡ It's all yours 👍

Let me know here if you need any help or you can [join our Discord](https://ethereum.org/discord) for assistance 🖖

**Comment by brandonfrulla** [comment]
I'm also available to assist if needed.
