### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by rodripaella** [ethereum/ethereum-org-website#10685]
### Wallet name

Crossmint

### Wallet description

Wallet infrastructure that makes the blockchain invisible

### Wallet logo

![Dark_Horizontal (2)](https://github.com/ethereum/ethereum-org-website/assets/105089398/7880dfc9-d958-4d46-a0a6-cf86a1ecf6fd)

### Background color for brand logo

#FFFFFF

### URL to the project

https://crossmint.com

### When did the wallet go live to users?

February 2022

### Does the wallet have an active development team?

Yes

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

Yes. Over 20 languages supported

### What social links are there for the project?

https://twitter.com/crossmint
https://discord.gg/crossmint

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

No

### Who holds the private keys?

Wallets are MPC, with key management powered by Fireblocks. Customers can access their public key, but not their private key which is sharded. If the company was to disappear, users would be able to transfer their assets to any wallet, free of charge

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Crossmint leverages Fireblocks' battle-tested MPC infrastructure

### Has the wallet's smart contract code or security modules been audited?

Yes, Crossmint leverages third-party independent security auditors including Latacora and Cossack Labs

### Does the wallet have an internal security team?

Yes, https://www.linkedin.com/in/manishbhattacharya/

### Any other security testing that should be noted?

Crossmint is SOC2 Type 1 compliant.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes. https://docs.crossmint.com/docs/sign-transactions

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

Crossmint supports 10+ chains. https://docs.crossmint.com/docs/wallets-features-overview

### Does the wallet support Ethereum layer 2 networks?

Yes, including Optimism, Arbitrum, Base, and Zora https://docs.crossmint.com/docs/wallets-features-overview

### Does the wallet allow the user to customize gas fees?

No

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, via a complementary Account Abstraction with a provably non-custodial signer

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Crossmint offers the leading NFT checkout in the market, having supported 4,000+ drops for major enterprises and  https://docs.crossmint.com/docs/payments-introduction

### Does the wallet support withdrawals to fiat?

Not yet, but it is on the roadmap

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

Yes

### Who can the ethereum.org team can contact regarding the wallet in future?

@rodrifernandezt (telegram and twitter)

### Does the wallet have a dedicated support team?

Yes. We offer 24/7/365 customer and developer support, with SLAs for enterprises

### What educational resources/documentation do you provide to users?

- Deck: https://docs.google.com/presentation/d/1lxibNtC7ZTBfA3hc1ra7PeBYA-TE-oQKRZ9OKZpFyKI/ (must request access but it's granted ~instantly)
- Docs: https://docs.crossmint.com

### Does the wallet have any integrated tools not mentioned above?

- Auth: Stytch (https://stytch.com/blog/onboarding-the-next-web3-wave-with-crossmint-stytch/), auth0, Firebase
- IRL token-gating: tokenproof, ETHpass
- Unreal Engine 5 & Unity: demo (https://www.youtube.com/watch?v=e-GK4hQhAxs)
- Workflow automation: Zapier (eventbrite, stripe, shopify ,airtable, etc.)
- CRMs: Salesforce

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @rodripaella 

Going to reject this listing for now. This seems very developer-focused, especially in messaging, which is a different user base than the find wallets page. We want to help people file their first wallet and one that works for them, instead of pushing developer tech here.

**Comment by rodripaella** [comment]
Hi Corwin! Would it work if we rewrote it to make more user focused?

Thank you!
Rodri
