### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by chaoticgoodpanda** [ethereum/ethereum-org-website#10692]
### Wallet name

Trust Wallet

### Wallet description

More than 4.5M+ assets supported. Store all your coins and tokens in a single, secure mobile wallet. The app supports 70 blockchains and 9M+ assets

### Wallet logo

![TWT](https://github.com/ethereum/ethereum-org-website/assets/13663360/05286e85-0e03-4854-937e-aad0601c9562)

### Background color for brand logo

#0500FF

### URL to the project

https://trustwallet.com

### When did the wallet go live to users?

October 25, 2017

### Does the wallet have an active development team?

https://github.com/trustwallet/

### Is the wallet globally accessible?

N/A

### Is the wallet available in multiple languages?

English, Arabic, Bangla, Chinese (Simplified), Chinese (Traditional), French, German, Hindi, Indonesian, Italian, Japanese, Korean, Portuguese (Brazil), Russian, Spanish, Trukish, Ukrainian, Vietnamese

### What social links are there for the project?

Twitter: https://twitter.com/TrustWallet

Instagram: https://www.instagram.com/trustwallet

Facebook: https://www.facebook.com/trustwalletapp

Discord: https://discord.gg/trustwallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes. 

iOS: https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp

Android: https://apps.apple.com/us/app/trust-crypto-bitcoin-wallet/id1288339409

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No desktop app.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes. 

Chromium: https://chrome.google.com/webstore/detail/trust-wallet/egjidjbpglichdcondbcbdnbeeppgdph

### Is it a hardware wallet?

Supports both hot wallet and cold (Ledger) hardware wallets.

### Is the source code for the wallet fully open-source?

https://github.com/trustwallet/wallet-core

### What license is the wallet software released under?

Apache 2.0

### Who holds the private keys?

Users have access to their public and private keys.  Wallet is fully non-custodial -- no third party has access to their public and private keys.

If the company/project were to disappear, users would still be able to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://community.trustwallet.com/t/a-complete-overview-of-trust-wallet-security/628739

### Has the wallet's smart contract code or security modules been audited?

https://community.trustwallet.com/t/a-complete-overview-of-trust-wallet-security/628739

### Does the wallet have an internal security team?

https://community.trustwallet.com/t/a-complete-overview-of-trust-wallet-security/628739

### Any other security testing that should be noted?

https://community.trustwallet.com/t/a-complete-overview-of-trust-wallet-security/628739

### Scam protection?

https://community.trustwallet.com/t/a-complete-overview-of-trust-wallet-security/628739#trust-wallet-security-scanner-9

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

https://community.trustwallet.com/t/how-to-add-a-custom-network-on-the-trust-wallet-mobile-app/626781

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

https://community.trustwallet.com/t/how-you-can-use-defi-with-trust-wallet/54132

### Does the wallet support staking directly?

https://community.trustwallet.com/t/how-to-stake-solana-sol-in-trust-wallet/457937

### Does the wallet support swaps directly?

https://community.trustwallet.com/t/trust-wallet-adds-in-app-cross-chain-swaps-functionality-with-thorchain-integration/637967

### Does the wallet support multi-chain networks?

https://trustwallet.com/assets/

### Does the wallet support Ethereum layer 2 networks?

https://community.trustwallet.com/t/trust-wallet-extensions-adds-fiat-to-crypto-purchases-aptos-polygon-zkevm-more/729929, https://blog.trustwallet.com/blog/zksync-era-everything-you-need-to-know-to-get-started

### Does the wallet allow the user to customize gas fees?

https://community.trustwallet.com/t/what-is-an-eth-gas-fee/116

### Does the wallet support sending transactions to ENS addresses?

https://community.trustwallet.com/t/ethereum-name-service-ens-is-now-supported/35764

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

https://community.trustwallet.com/t/how-to-add-a-custom-token/213

### Does the wallet support EIP-1559 (type 2) transactions?

https://community.trustwallet.com/t/what-is-eip-1559/285601

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

https://community.trustwallet.com/t/ramp-network-has-been-integrated-to-trust-wallet/239339

### Does the wallet support withdrawals to fiat?

https://community.trustwallet.com/t/how-to-sell-your-crypto-for-fiat-using-trust-wallet/736773

### Is the wallet a multi-signature wallet?

N/A

### Does the wallet support social recovery?

N/A

### Who can the ethereum.org team can contact regarding the wallet in future?

Twitter: SovCoach

Telegram: @ml_trust

### Does the wallet have a dedicated support team?

Yes.

https://support.trustwallet.com/en/support/tickets/new

Support typically responds within 24 hours.

### What educational resources/documentation do you provide to users?

Developer docs: https://developer.trustwallet.com/developer/

User & community docs: https://community.trustwallet.com/

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by Flaborn954** [comment]
I need to get a withdrawal code to get funds from international global pay or is there a software to use to make the withdrawal of funds possible can someone help

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by Anna-cybers** [comment]
NO I'M NOT A FRAUDULENT PERSON! 
IM A ETHICAL HACKING PROFESSIONAL WHO RENDERS ONLINE (WHITE HAT) HACKING SUCH AS
💙FACEBOOK ACCOUNT RECOVERY
💙FACEBOOK ACCOUNT HACKING 
💙INSTAGRAM ACCOUNT RECOVERY 💜INSTAGRAM ACCOUNT HACKING 
💜SNAPCHAT / TIKTOK UNBAN 
💚INSTA-FB MESSAGE HACK
💙ONLINE MESSAGE HACKING 
💜WEBSITE HACKING 
💛CHEATING IN RELATIONSHIP HACK
💛LOST FUNDS RECOVERY (scammers payback) 

📥ANNA_CYBERWEB 0N INSTAGRAM 🕸️DONALDSONHARRY013@GMAIL.COM

How can I help you? SEND AN INBOX OR EMAIL ME FOR SWIFT RESPONSE 24/7
INSTAGRAM LINK https://www.instagram.com/p/Cxbd-lfNEX4/?igshid=MzRlODBiNWFlZA==

**Comment by Anna-cybers** [comment]
NO I'M NOT A FRAUDULENT PERSON! 
IM A ETHICAL HACKING PROFESSIONAL WHO RENDERS ONLINE (WHITE HAT) HACKING SUCH AS
💙FACEBOOK ACCOUNT RECOVERY
💙FACEBOOK ACCOUNT HACKING 
💙INSTAGRAM ACCOUNT RECOVERY 💜INSTAGRAM ACCOUNT HACKING 
💜SNAPCHAT / TIKTOK UNBAN 
💚INSTA-FB MESSAGE HACK
💙ONLINE MESSAGE HACKING 
💜WEBSITE HACKING 
💛CHEATING IN RELATIONSHIP HACK
💛LOST FUNDS RECOVERY (scammers payback) 

📥ANNA_CYBERWEB 0N INSTAGRAM 🕸️DONALDSONHARRY013@GMAIL.COM

How can I help you? SEND AN INBOX OR EMAIL ME FOR SWIFT RESPONSE 24/7
INSTAGRAM LINK https://www.instagram.com/p/Cxbd-lfNEX4/?igshid=MzRlODBiNWFlZA==

**Comment by Anna-cybers** [comment]
NO I'M NOT A FRAUDULENT PERSON! 
IM A ETHICAL HACKING PROFESSIONAL WHO RENDERS ONLINE (WHITE HAT) HACKING SUCH AS
💙FACEBOOK ACCOUNT RECOVERY
💙FACEBOOK ACCOUNT HACKING 
💙INSTAGRAM ACCOUNT RECOVERY 💜INSTAGRAM ACCOUNT HACKING 
💜SNAPCHAT / TIKTOK UNBAN 
💚INSTA-FB MESSAGE HACK
💙ONLINE MESSAGE HACKING 
💜WEBSITE HACKING 
💛CHEATING IN RELATIONSHIP HACK
💛LOST FUNDS RECOVERY (scammers payback) 

📥ANNA_CYBERWEB 0N INSTAGRAM 🕸️DONALDSONHARRY013@GMAIL.COM

How can I help you? SEND AN INBOX OR EMAIL ME FOR SWIFT RESPONSE 24/7
INSTAGRAM LINK https://www.instagram.com/p/Cxbd-lfNEX4/?igshid=MzRlODBiNWFlZA==

**Comment by Anna-cybers** [comment]
NO I'M NOT A FRAUDULENT PERSON! 
IM A ETHICAL HACKING PROFESSIONAL WHO RENDERS ONLINE (WHITE HAT) HACKING SUCH AS
💙FACEBOOK ACCOUNT RECOVERY
💙FACEBOOK ACCOUNT HACKING 
💙INSTAGRAM ACCOUNT RECOVERY 💜INSTAGRAM ACCOUNT HACKING 
💜SNAPCHAT / TIKTOK UNBAN 
💚INSTA-FB MESSAGE HACK
💙ONLINE MESSAGE HACKING 
💜WEBSITE HACKING 
💛CHEATING IN RELATIONSHIP HACK
💛LOST FUNDS RECOVERY (scammers payback) 

📥ANNA_CYBERWEB 0N INSTAGRAM 🕸️DONALDSONHARRY013@GMAIL.COM

How can I help you? SEND AN INBOX OR EMAIL ME FOR SWIFT RESPONSE 24/7
INSTAGRAM LINK https://www.instagram.com/p/Cxbd-lfNEX4/?igshid=MzRlODBiNWFlZA==

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1

https://instagram.com/spygency.1?igshid=MzRlODBiNWFlZA==

EMAIL 📧 spygency@gmail.com

**Comment by Flaborn954** [comment]
Hey can you get in Gmail?? I got a btc mining account that I'm trying to
get in bout 30k in it I'll split it with you if you can get in it.

**Comment by Flaborn954** [comment]
Can you do sim swaps or point me in the right direction?
