### ISSUE TITLE
Add TUM Blockchain Conference to community-events.json

### ISSUE THREAD

**Issue by tumblockchain** [ethereum/ethereum-org-website#10705]
{
    "title": "TUM Blockchain Conference",
    "to": "https://www.tum-blockchain.com/conference",
    "sponsor": null,
    "location": "Munich, Germany",
    "description": "Join us at Germany's leading student-run conference in order to explore the frontiers of blockchain technology during the Octoberfest!",
    "startDate": "2023-9-22",
    "endDate": "2023-9-23"
  }

**Comment by corwintines** [comment]
Sounds good, would you like to open this PR @tumblockchain?

**Comment by tumblockchain** [comment]
Thanks a lot for the help! Feel free to open the PR on your end in order to get it merged to the website :)
