### ISSUE TITLE
External tutorial: ERC-4907 - The NFT Rental Standard

### ISSUE THREAD

**Issue by chandn0** [ethereum/ethereum-org-website#10712]
### Tutorial title

ERC-4907: The NFT Rental Standard

### Tutorial description

How NFT Rentals works

There are currently two ways by which NFTs can be rented out: collateralized renting and collateral-free renting. In both methods, the owner transfers ownership of the NFT to the user with some collateral or conditions to ensure that the renter will return ownership after the rental period is complete. However, these methods come with potential risks, and when the rental period expires, the owner has to manually reclaim their asset, which can be a complicated and expensive process, especially when renting multiple assets at the same time.

### Tutorial tags

NFT, ERC-4907

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://www.buildbear.io/resources/guides-and-tutorials/ERC-4907_The_NFT_Rental_Standard

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
(Noting ERC link: https://github.com/ethereum/ercs/blob/master/ERCS/erc-4907.md)

@chandn0 Thanks for this, and apologies for the long delays here. Is this something you'd still like to add? As an external tutorial I think this would be reasonable... assigning you if you're still interested, but can also close if not.

**Comment by minimalsm** [comment]
Closing out as stale, but feel free to reopen
