### ISSUE TITLE
Learn and deploy an ERC 1155 smart contract (Most used by web3 Games).

### ISSUE THREAD

**Issue by chandn0** [ethereum/ethereum-org-website#10715]
### Tutorial title

Learn and deploy an ERC 1155 smart contract (Most used by web3 Games).

### Tutorial description

In this tutorial, we will guide you through the step-by-step process of creating an ERC 1155 smart contract.

### Tutorial tags

Solidity, Smart Contract

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://www.buildbear.io/resources/guides-and-tutorials/ERC_1155_Smart_Contract

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
@chandn0 Looks like this tutorial is giving a `500`... I'd still be in favor of adding an 1155 tutorial if you have another link, but in the meantime I'm going to close this one out. Please feel free to re-open a fresh issue if you have a new link! Thanks
