### ISSUE TITLE
Suggest a wallet: Phantom

### ISSUE THREAD

**Issue by bfriel** [ethereum/ethereum-org-website#10733]
### Wallet name

Phantom

### Wallet description

The friendly crypto wallet built for DeFi & NFTs.

### Wallet logo

![Phantom_512x512](https://github.com/ethereum/ethereum-org-website/assets/15083324/b2c0e05a-22f2-4cc9-9bc3-d26c8ebd887a)

### Background color for brand logo

#AB9FF2

### URL to the project

https://phantom.app/

### When did the wallet go live to users?

May 17 2021

### Does the wallet have an active development team?

https://github.com/phantom

### Is the wallet globally accessible?

https://phantom.app/terms

### Is the wallet available in multiple languages?

https://help.phantom.app/hc/en-us/articles/5969997960467-Languages-Phantom-Supports

### What social links are there for the project?

https://twitter.com/phantom
https://www.youtube.com/@phantom-wallet
https://www.reddit.com/r/phantom_app/
https://www.linkedin.com/company/phantomwallet/mycompany/
https://www.instagram.com/phantom/
https://podcast.phantom.app/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS: https://apps.apple.com/us/app/phantom-crypto-wallet/id1598432977
Android: https://play.google.com/store/apps/details?id=app.phantom&hl=en_US&gl=US&pli=1

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Chromium: https://chrome.google.com/webstore/detail/phantom/bfnaelmomeimhlpmgjnjophhpkkoljpa
Firefox: https://addons.mozilla.org/en-US/firefox/addon/phantom-app/

### Is it a hardware wallet?

No. Phantom is a software wallet that offers Ledger hardware wallet support.

### Is the source code for the wallet fully open-source?

No

### What license is the wallet software released under?

N/A

### Who holds the private keys?

Phantom is a non-custodial wallet. Users generate their own seed phrases and are the only ones who have access to their private keys.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://phantom.app/security

### Has the wallet's smart contract code or security modules been audited?

https://kudelskisecurity.com/wp-content/uploads/Phantom-Security-Assessment.pdf

### Does the wallet have an internal security team?

Yes: https://phantom.app/security

### Any other security testing that should be noted?

https://phantom.app/learn/blog/security-at-phantom

### Scam protection?

Yes. Phantom has integrated [Blowfish](https://blowfish.xyz/) to simulate transactions and warn users against potential fraud. In addition, Phantom maintains its own open source [blocklist](https://github.com/phantom/blocklist) to prevent users from interacting with known scams and phishing links. More info: https://phantom.app/learn/blog/security-at-phantom

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Not currently

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

https://help.phantom.app/hc/en-us/articles/15271973619091-How-to-connect-to-EVM-dApps-when-Phantom-isn-t-an-option-

### Does the wallet support staking directly?

https://help.phantom.app/hc/en-us/sections/4406351831571-Staking

### Does the wallet support swaps directly?

https://help.phantom.app/hc/en-us/articles/6048249796243-Phantom-Swapper-FAQ

### Does the wallet support multi-chain networks?

https://help.phantom.app/hc/en-us/articles/4406393831187-How-to-deposit-ETH-MATIC-and-SOL-in-my-Phantom-wallet-

### Does the wallet support Ethereum layer 2 networks?

Not currently

### Does the wallet allow the user to customize gas fees?

https://help.phantom.app/hc/en-us/articles/10342202855059-How-do-I-speed-up-my-transaction-

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Phantom automatically displays all available ERC-20 tokens for the networks it supports

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

https://help.phantom.app/hc/en-us/articles/4406543783571-Where-can-I-buy-Ethereum-ETH-Polygon-MATIC-and-Solana-SOL-

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Brian Friel
Developer Relations Manager, Phantom
Telegram: @brianfriel
Twitter: @bfriel_

### Does the wallet have a dedicated support team?

Yes. Phantom employs a full-time, dedicated support team that offers 24/7 coverage: https://help.phantom.app/hc/en-us

### What educational resources/documentation do you provide to users?

Educational resources: https://phantom.app/learn
Developer docs: https://docs.phantom.app/introduction/readme

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by spygency1** [comment]
NEED URGENT HELP?!!



For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 


INSTAGRAM 📥 spygency.1


https://instagram.com/spygency.1?igshid=MzRlODBiNWFlZA==


EMAIL 📧 spygency@gmail.com
