### ISSUE TITLE
Add Origin Protocol to dapp page

### ISSUE THREAD

**Issue by sumpg41** [ethereum/ethereum-org-website#10743]
### Name

Origin Protocol

### Description

Origin Protocol is a collection of rebasing yield aggregators and NFT marketplaces designed in a set and forget fashion.  

### Logo

https://raw.githubusercontent.com/OriginProtocol/origin-website/master/static/img/coins/ogn-256x256.png

### Brand color

0074F0

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/OriginProtocol/

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Origin currently has a continuous auditing agreement with [OpenZeppelin](https://openzeppelin.com/) to constantly review 100% of our smart contract changes. OpenZeppelin has audited Coinbase, Ethereum, Aave, Compound, and other leading projects. They are one of the most trusted auditing firms in the industry and we are thrilled to count them as part of our extended team.

All audits can be found here: https://docs.oeth.com/security-and-risks/audits

Origin also maintains an open bug bounty for up to $1m USD on [Immunefi](https://immunefi.com/bounty/origindollarousd/).

### Can a user access the dapp without creating an account?

A user can simply connect their Ethereum wallet to use the Origin Protocol dapps.

### Are dapp funds non-custodial?

All dapp funds are non-custodial with Origin Protocol. 

### Do you offer community support?

Support is always available via the [Origin Protocol Discord](https://www.originprotocol.com/discord).

### Describe any geographical restrictions on usage of your dapp

There are no geographical restrictions to use Origin Protocol dapps.

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by sumpg41** [comment]
Origin Protocol is a competitor to Index Coop, which is currently listed on the dapps page
cc @wackerow

**Comment by minimalsm** [comment]
Closing out, per https://github.com/ethereum/ethereum-org-website/pull/10953#issuecomment-1976730335
