### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10747]
Implement the [new designs](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=1069%3A17908) for the [Tooltip component](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Tooltip.tsx).

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/1ab5437a-bb24-446c-af56-e2a62672c197)

**Comment by amit-ksh** [comment]
I'd like to work on this one

**Comment by corwintines** [comment]
I think im going to assign this one to myself. There is a lot of overlap with the GlossaryTooltip that im building at the moment, and think I can combine it there.
