### ISSUE TITLE
Modal - implement DS styles and unify modals

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10749]
The goal is to implement the DS styles for the modal and unify all the instances where we use modals.

TODO:
1. Implement latest styles from [the DS](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=1630%3A32303) to the Modal [theme](https://github.com/ethereum/ethereum-org-website/blob/dev/src/%40chakra-ui/gatsby-plugin/components/Modal.ts) and [component](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Modal.tsx).

2. Remove the all the other existing modal implementations and start using this one for everything.

Other modal implementations we currently have:
- [CodeModal](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/CodeModal.tsx)
- [QuizzesModal](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Quiz/QuizzesModal.tsx)

**Comment by ashiskumar-1999** [comment]
Hi @pettinarip,
I want to work on this issue.

**Comment by pettinarip** [comment]
Hey @ashiskumar-1999 thanks!

Please, take a look at the [Design System implementation docs](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/ds-implementation.md) and let me know if you have any questions.

Assigned to you!
