### ISSUE TITLE
TableOfContents

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10745]
Implement the new `TableOfContents` [styles from the DS](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=2415%3A45636) in the [current `TableOfContents` component](https://github.com/ethereum/ethereum-org-website/tree/dev/src/components/TableOfContents).

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/bbb5320a-8c3c-4631-8fd2-20ed25c7efed)

**Comment by ameeetgaikwad** [comment]
assign me this.

**Comment by F3n4nd0gm** [comment]
![p_total_supply_ranges.png](https://github.com/ethereum/ethereum-org-website/assets/147960298/0b55948c-79d4-4319-826c-099ad951666f)
