### ISSUE TITLE
SocialMediaLinks

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10746]
Implement the Social Media links styles from [the DS](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=5448%3A58946).

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/a4d842a5-3f60-4d89-a26e-45d131ec9e1a)

**Comment by altinocoelho** [comment]
hey @pettinarip, I'd like like to help with this

**Comment by jflets** [comment]
Hey @pettinarip if this is still available to help. I'd like to help

**Comment by pettinarip** [comment]
@altinocoelho @jflets thanks for the help and sorry for the delay here. Assigning it to @altinocoelho for now.

----

@TylerAPfledderer if I recall correctly, we chatted a bit about this and you said that probably we don't need to create a new component. That maybe, we could just wrap these icons with the Link component and override the colors, right?

The tricky part I see in this case is that we need to inherit the colors from the Link component but we need to override the default color to be white or black, depending on the color mode (that is the main difference in these links).

That's why I thought about creating a new component, to wrap that logic in there. Let me know if you think differently.

**Comment by TylerAPfledderer** [comment]
> @altinocoelho @jflets thanks for the help and sorry for the delay here. Assigning it to @altinocoelho for now.
> 
> @TylerAPfledderer if I recall correctly, we chatted a bit about this and you said that probably we don't need to create a new component. That maybe, we could just wrap these icons with the Link component and override the colors, right?
> 
> The tricky part I see in this case is that we need to inherit the colors from the Link component but we need to override the default color to be white or black, depending on the color mode (that is the main difference in these links).
> 
> That's why I thought about creating a new component, to wrap that logic in there. Let me know if you think differently.

I do recall and found the discussion the had.

I would clarify that I think importing Chakra's `Link` component here would suffice, along doing direct translation for `aria-label` and applying `trackCustomEvent`. I don't see these links needing all the other overhead from the custom `Link` component, correct?

As to the color override, I don't see why this would cause any issue. This would be different from our `visited` styling we had to attend to.

Best that the icons be in Chakra's `Icon` component or using `createIcon()`. As long as the icon renders `fill: currentColor` which should automatically happen, then applying a color override to `Link` should be successful. Looks like `body.base` is the semantic token to use here.

**Comment by pettinarip** [comment]
Got it, thanks @TylerAPfledderer.

@altinocoelho hopefully that makes sense.

We should
- keep using the Link component for this
- override the default color with `body.base`
- and stop using the custom hover colors we are using as defined in the DS

**Comment by altinocoelho** [comment]
@pettinarip sure thing, thanks for the input

I'll submit this soon
