### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10748]
Create a new component called `Accordion` with [the DS styles](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=1220%3A19589).

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/9cc9917f-2e3b-498c-934e-257757d1f5d2)

**Comment by amit-ksh** [comment]
Hey @pettinarip, can you assign this to me?

**Comment by justynleung** [comment]
![ezgif com-video-to-gif](https://github.com/ethereum/ethereum-org-website/assets/114822505/676e3596-8b22-461f-b789-fa6b411d37eb)

@pettinarip Does this look good? I made a prototype according to the requirements.

**Comment by pettinarip** [comment]
Hey @justynleung looks good! soon we will review the PR and implementation. Thanks for the help

**Comment by justynleung** [comment]
@pettinarip No worries. I am glad that you like it. Please let me know if any change is needed.
