### ISSUE TITLE
Header mobile - Menu and Dropdowns

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10751]
[Mobile version]

Implement the [new DS styles](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=248%3A507) in the [Menu Mobile](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Nav/Mobile.tsx) component.

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/60563c87-f051-4009-865c-55d58a22d1d1)

**Comment by ameeetgaikwad** [comment]
Can I work on this issue, or someone else is doing this? @pettinarip

**Comment by pettinarip** [comment]
@ameeetgaikwad thanks! assigned to you.

**Comment by wackerow** [comment]
The mobile menu has been updated to use Accordion component, alongside the revamp to the information architecture and the desktop menu. Closing this out.
