### ISSUE TITLE
Header - Menu and Dropdowns

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10750]
Implement the [new DS styles](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=248%3A507) in the [Menu](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Nav/Menu.tsx) component.

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/a1eb9d3f-d5ea-41bb-b9de-b86450568dbe)

Note: consider creating a new Menu component if it makes things easier.

**Comment by ameeetgaikwad** [comment]
would like to help!

**Comment by ameeetgaikwad** [comment]
@pettinarip would like to work on this

**Comment by pettinarip** [comment]
Closing issue as a new menu was designed and developed.
