### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10753]
Create a new component for the new Hero component specified in [the DS](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=2486%3A48375).

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/a7490dd3-3d38-49e1-b7f2-366c7e7ee753)

Depends on #11140

**Comment by TylerAPfledderer** [comment]
Commenting for assignment

**Comment by nloureiro** [comment]
@TylerAPfledderer I know that you've talked with @pettinarip about this, and I wanted to update you on where we are.

We hope to have at least three new illustrations, but by the end of this quarter (hope 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻  ) and this new hero is a significant change that I wanted to have tested beforehand on the browser.

So... my take would be to have this PR ready to review from the design and code sides and get it sitting and waiting for the new illustrations.

One of the pages might be the learning page, we can use it to test the new hero, and we can use the homepage image for testing purposes.
![Screen Shot 2023-08-16 06 21 52 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/ad156545-f403-4a7c-999f-5211bde1f785)

Let me know what you think,  if sound like a good plan :)

Thank you

**Comment by TylerAPfledderer** [comment]
> @TylerAPfledderer I know that you've talked with @pettinarip about this, and I wanted to update you on where we are.
> 
> We hope to have at least three new illustrations, but by the end of this quarter (hope 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻 ) and this new hero is a significant change that I wanted to have tested beforehand on the browser.
> 
> So... my take would be to have this PR ready to review from the design and code sides and get it sitting and waiting for the new illustrations.
> 
> One of the pages might be the learning page, we can use it to test the new hero, and we can use the homepage image for testing purposes. Screen Shot 2023-08-16 06 21 52 PM
> 
> Let me know what you think, if it sound like a good plan :)
> 
> Thank you

All good with me! 

I am also making a fresh set of component files for the Storybook stories. So aside from the homepage, the other heroes do not have to be connected to any page straight away, and just left to be viewed in a story.
