### ISSUE TITLE
[get-eth page] Remove Binance on available exchanges in unsupported countries

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#10764]
### Overview
As of July 17th, 2023, Binance is no longer operating in the The Netherlands ([see announcement here](https://www.binance.com/en/support/announcement/notice-on-changes-of-services-in-the-netherlands-b5a647be31cf469b87fc3337fd461ced)).

Therefore, this information should be updated (removed) on the [/get-eth/#country-picker](https://ethereum.org/en/get-eth/#country-picker) page. 

<img width="906" alt="Screenshot 2023-07-24 at 06 30 38" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/f26491bc-1615-44b2-82bf-f446b6a1467a">

### Note
Issue reported by Edwin B via email on July 22nd, 2023.

**Comment by minimalsm** [comment]
Thanks @isabelladebrito :) 

Binance provides a decent interface for this that we can cross reference: https://www.binance.com/en/country-region-selector

We list other countries that are not supported (e.g. Germany)

**Comment by SurajAnand88** [comment]
@minimalsm I want to work on this issue

**Comment by MwitahJob** [comment]
> Thanks @isabelladebrito :)
> 
> Binance provides a decent interface for this that we can cross reference: https://www.binance.com/en/country-region-selector
> 
> We list other countries that are not supported (e.g. Germany)

Hey @minimalsm , according to the reference link you provided, countries supported are less than 50.

```
Africa - Nigeria & South Africa.
Americas - Canada, Argentina, Brazil, Chile, Colombia, Mexico & Peru.
Asia & Pacific - Afghanistan, Australia, Bangladesh, Cambodia, India, Indonesia, Japan, Kazakhstan, Mongolia, Myanmar, New Zealand, Pakistan, Philippines, Taiwan & Vietnam.
Europe - Bulgaria, Czech Republic, France, Greece, Hungary, Italy, Latvia, Poland, Portugal, Romania, Russia, Slovakia, Slovenia, Spain, Switzerland, Turkey & Ukraine.
Middle East - Egypt, Israel, Saudi Arabia & United Arab Emirates.
```

Are those the only ones that should be included?

**Comment by wackerow** [comment]
To @MwitahJob, yes! Thanks for posting... Binance should only be listed for these countries.

Thank you @SurajAnand88 for offering to help, I've gone ahead and assigned you if you'd like to update this data file with the correct countries and drop a PR: https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/exchanges-by-country.csv

Let us know if you have any more questions

**Comment by MwitahJob** [comment]
> To @MwitahJob, yes! Thanks for posting... Binance should only be listed for these countries.
> 
> Thank you @SurajAnand88 for offering to help, I've gone ahead and assigned you if you'd like to update this data file with the correct countries and drop a PR: https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/exchanges-by-country.csv
> 
> Let us know if you have any more questions

@wackerow I am already working on it could you assign me also.

**Comment by MwitahJob** [comment]
I wanted to ask, there are several states of Australia, France and New Zealand:

```
Australia
 -Norfolk Island

France
 -French Guiana
 -French Polynesia
 -Guadeloupe
 -Martinique
 -New Caledonia
 -Saint Barthelemy
 -Saint Martin
 -Saint Pierre & Miquelon
 -Wallis & Futuna

New Zealand
 -Niue
 -Tokelay
 -Cook Islands
```

Should both be set to true?

**Comment by SurajAnand88** [comment]
@MwitahJob Thanks for mentioning this issue https://github.com/ethereum/ethereum-org-website/issues/10764#issuecomment-1648760223
![Screenshot (62)](https://github.com/ethereum/ethereum-org-website/assets/120190623/d5b10911-b038-4f2d-a3b3-1b8315b9d858)

According to this i've talked to the Binance customer support executive for the confirmation as they mentioned that if a specific country is supported then each state of its supported too.

According to my research above mentioned locations are not the  states of the specific countries; they are, in fact, territories belonging to those countries.

**Comment by corwintines** [comment]
Closing with above PR merged in
