### ISSUE TITLE
Bug report: Truffle not longer being supported in solidity-coverage

### ISSUE THREAD

**Issue by clauBv23** [ethereum/ethereum-org-website#10766]
### Describe the bug

On [SOLIDITY AND TRUFFLE CONTINUOUS INTEGRATION SETUP](https://ethereum.org/en/developers/tutorials/solidity-and-truffle-continuous-integration-setup/) tutorial the usage of `solidity-coverage` is suggested but, it doesn't longer support truffle on its latest versions ([Release 0.8.0](https://github.com/sc-forks/solidity-coverage/releases/tag/v0.8.0)).

### To reproduce

1. Go to https://ethereum.org/en/developers/tutorials/solidity-and-truffle-continuous-integration-setup/#adding-the-solidity-coverage-plugin
2. On step 1 `npm install --save-dev truffle coveralls solidity-coverage` the latest version of `solidity-coverage` will be installed and doesn't support truffle.

### Expected behavior

A compatible plugin should be suggested (not sure which one), or add a note explaining latest versions can't be used and update the installation step properly.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @clauBv23! Thanks for posting and apologies for the long delay here. I'm personally having a tricky time verifying this... Do you know if this is still an issue? Do you have a suggested fix here by chance?

cc: @franzihei Any chance you have input here?

**Comment by franzihei** [comment]
Hey all! [Truffle is being sunset](https://github.com/trufflesuite/truffle). I recommend to either...

- add a warning or banner to all tutorials on ethereum.org that use Truffle
- remove all tutorials that use Truffle
- adjust all tutorials that use Truffle to use another tool

Hope this helps!

**Comment by wackerow** [comment]
Thanks @franzihei!

> remove all tutorials that use Truffle

For the sake of moving forward, I would advocate for this option.

A warning banner will just lead to poor UX (worse over time) where users can't actually _do_ the tutorial they're reading. I'd rather encourage new tutorials with modern/maintained tools.

---

We also have another issue discussing this more broadly. I'm going to close this one out in favor of #11262 which we'll use to address all of the Truffle mentions.
