### ISSUE TITLE
Create a listing policy for events

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#10779]
**Is your feature request related to a problem? Please describe.**

Our listing policies aim to provide transparent criteria on how to suggest products/resources/services to be added ethereum.org & to give insight on how we evaluate proposals. While we already do have a listing policy for "[Ethereum products](https://ethereum.org/en/contributing/adding-products/)", we've learned that dedicated listing policies can add greater clarity on the information we require (e.g. like we have for [adding exchanges](https://ethereum.org/en/contributing/adding-exchanges/)). 

**Describe the solution you'd like**

Create a dedicated listing policy for events, which we display here:
https://ethereum.org/en/community/events/

This policy should outline the criteria we use to list the events. Potential criteria might be:
- Is it related to Ethereum, the underlying technologies Ethereum uses, or to crypto broadly?
- Is the event open to all? Is it free or paid?
- Is the event legitimate\*? Is there risk of attendees being scammed or mislead?
- Are the organizers of the event credible\*?

\* Would be worth thinking about how "legitimacy" and "credibility" could be determined using objective measures. 

**Additional context**
Issue Resurfacing from #5767, stemming from discussion on #5744

@minimalsm Assigning you for now; feel free to update as needed

**Comment by minimalsm** [comment]
Looking at this now, this honestly feels unnecessary. Thoughts on closing this out @wackerow?

**Comment by minimalsm** [comment]
> Looking at this now, this honestly feels unnecessary. Thoughts on closing this out @wackerow?

@isabelladebrito any thoughts?

**Comment by corwintines** [comment]
I think for now this is low priority, so will close out. @wackerow if you disagree lets reopen.
