### ISSUE TITLE
Create a listing policy for online communities

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#10790]
**Is your feature request related to a problem? Please describe.**

Our listing policies aim to provide transparent criteria on how to suggest products/resources/services to be added ethereum.org & to give insight on how we evaluate proposals. While we already do have a listing policy for "[Ethereum products](https://ethereum.org/en/contributing/adding-products/)", we've learned that dedicated listing policies can add greater clarity on the information we require (e.g. like we have for [adding exchanges](https://ethereum.org/en/contributing/adding-exchanges/)). 

**Describe the solution you'd like**

Create a dedicated listing policy for online communities, which we display here:
https://ethereum.org/en/community/online/

This policy should outline the criteria we use to evaluate communities & decide if we will list them. Potential criteria might be:
- Is it related to Ethereum, the underlying technologies Ethereum uses, or to crypto broadly?
- Is the community open to all? Is it free or paid?
- Is the community legitimate\*? Is there risk of new members being scammed or mislead?
- Is the community active? Does the community have consistent moderation?

\* Would be worth thinking about how we can define "legitimacy" objectively

**Additional context**
Issue Resurfacing from #6017, similar idea/initiative to #10779

@minimalsm Assigning you for now; feel free to update as needed

**Comment by wackerow** [comment]
cc: @isabelladebrito resurfacing and assigning to you

**Comment by isabelladebrito** [comment]
Thanks @wackerow! Happy to work on this - will share an update next week!

**Comment by minimalsm** [comment]
hey @isabelladebrito any update here?

**Comment by minimalsm** [comment]
LGTM @isabelladebrito, @wackerow any feedback?

**Comment by Shiva-Sai-ssb** [comment]
I would like to work on this. Can you please assign this issue to me? @wackerow
