### ISSUE TITLE
Feature Request: Update Community Events page

### ISSUE THREAD

**Issue by MaUbatuba** [ethereum/ethereum-org-website#10805]
### Is your feature request related to a problem? Please describe.

Add Not Another Virtual Hackathon to community event page

### Describe the solution you'd like

Title: Not Another Virtual Hackathon (NAVH)
To: https://navhackathon.consensys.io/
sponsor: null 
location: virtual (global)
Description: Consensys' annual virtual global hackathon aimed to scale Ethereum
Start date: July 6th
End date: September 6th

### Describe alternatives you've considered

none

### Additional context

Consensys' annual virtual global hackathon aimed to scale Ethereum. We opened up $115,500 in bounties from MetaMask and Linea for builders. The top 5 teams will also have an opportunity to pitch our leadership and interview for our upcoming Accelerator program, Consensys Fellowship. Projects will be scored by product market fit, scalability, viability, creativity, and clean UX. With our global reach, our mission to is to support, onboard, and upskill the future of Ethereum. With 1,5k registrations and 100+ applications, it's vital that we nurture developers to build for the Ethereum community.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Fixed in #10829... we'll get you another one to work on @MaUbatuba!
