### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by vikas-viki** [ethereum/ethereum-org-website#10809]
### Describe the bug

Hey I've just took two quizzes but loosed at max 3 questions like one was 13/16 (account abstraction) and 9/10 (nft) but both the time it gave this error

![image](https://github.com/ethereum/ethereum-org-website/assets/107193100/4f59c049-1563-48ce-bb2c-4f52e604a4f3)

### To reproduce

1. Go to 'https://lirn.io/'
2. Take a quiz.
3. Complete it and click claim.

### Expected behavior

I should be able to receive nfts.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by 0x0OZ** [comment]
@vikas-viki Why are you reporting this here?

It is not part of ethereum.org website.

**Comment by vikas-viki** [comment]
Ohh sorry
