### ISSUE TITLE
Incorrect font size in color mode and language buttons

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10807]
### Describe the bug

The current font size for the color mode and language buttons is too small.

### To reproduce

1. Go to the home page
2. See error on the color mode & language buttons on the nav bar

### Expected behavior

Font size should be the `md` size (1rem or 16px).

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/adfd196d-9175-4296-bcde-2abefbe34945)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by rohan9024** [comment]
@pettinarip Fixed this issue in my latest PR #10811 :)

**Comment by pettinarip** [comment]
Hi @rohan9024 thanks for doing that but would be nice if we can tackle this bug in a separate PR to merge it faster and avoid mixing different things in one PR. LMK in case you can do that 💪🏼 🙏🏼

**Comment by rohan9024** [comment]
> Hi @rohan9024 thanks for doing that but would be nice if we can tackle this bug in a separate PR to merge it faster and avoid mixing different things in one PR. LMK in case you can do that 💪🏼 🙏🏼 

Tbh, I have removed that "languages" text🗿... I have posted the video as well... Can you please verify if any changes has to be made?
