### ISSUE TITLE
Sidebar not hiding when transitioning from dev docs to tutorials

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10806]
### Describe the bug

The dev docs [Sidebar](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/SideNav.tsx) is not hiding when the user transition from the dev docs page to the tutorials page.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/
2. Click on Tutorials in the secondary nav
3. See error

### Expected behavior

When the user is in the Tutorials page, the sidebar should not be visible

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/d438831c-fd85-4c2c-9a00-39eb17a81b68)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Fixed with #10812
