### ISSUE TITLE
Bug report: Fix marker in the developer docs sidebar of the current active page

### ISSUE THREAD

**Issue by 0x0OZ** [ethereum/ethereum-org-website#10813]
### Is your feature request related to a problem? Please describe.

I am not sure 100% if this was a thing in the past but has been removed later from the website design.

### Describe the solution you'd like

The link of the active page is marked with a different color in the sidebar than other links like when it's being hovered for example, this would give users a better experience for end-users when scrolling through the docs.

expected behavior, something like this:
![image](https://github.com/ethereum/ethereum-org-website/assets/52073989/d67e674b-1ec3-45c8-ad60-f65e0876de23)

### Describe alternatives you've considered

ignore it, users can find out where they are when they look closely.

### Additional context

.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
I don't believe this is an issue anymore; please re-open if I'm misunderstanding!

**Comment by 0x0OZ** [comment]
> I don't believe this is an issue anymore; please re-open if I'm misunderstanding!

I think I now understand what's wrong, it is working but there is a small issue
https://ethereum.org/en/developers/docs/smart-contracts/security/#smart-contract-auditing-services

If you open this website you will not see the current page marked because you opened a title in it, if you click any of the titles from the page itself it will be marked with no issues
https://ethereum.org/en/developers/docs/smart-contracts/security/

**Comment by corwintines** [comment]
Anything you need a hand with here @0x0OZ?

**Comment by 0x0OZ** [comment]
> Anything you need a hand with here @0x0OZ?

Yes please, just a small thing I have explained it in the PR.
