### ISSUE TITLE
Suggest a Layer 2

### ISSUE THREAD

**Issue by brandonfrulla** [ethereum/ethereum-org-website#10822]
### Name

Starknet

### Logo

![Here](https://starkware.co/wp-content/uploads/2021/05/StarkNet-Icon.png)

### Description

Starknet is a Validity Rollup Layer 2. It provides high throughput, low gas costs, and retains Ethereum Layer 1 levels of security.

### Website

https://www.starknet.io/

### Developer documentation

https://docs.starknet.io/documentation/

### L2BEAT page

https://l2beat.com/scaling/projects/starknet

### Is the project open source?

https://github.com/orgs/starkware-libs/repositories

### What category of layer 2 is it?

ZK

### Does the layer 2 use Ethereum Mainnet for data availability?

Yes -- https://docs.starknet.io/documentation/architecture_and_concepts/Data_Availability/on-chain-data/#extract_from_ethereum

### Which bridges are used to onboard users?

1. https://starkgate.starknet.io/terms
2. https://www.orbiter.finance/?source=Polygon&dest=Starknet
3. https://www.layerswap.io/

### Which exchanges offer support for the project?

No token out yet, N/A

### Link to dapp ecosystem (if applicable)

https://www.starknet-ecosystem.com/

### What date did the project go live?

November 29, 2021 (Alpha) [Here](https://l2beat.com/scaling/projects/starknet#milestones)

### Is there an active team developing the project?

None

### Is there a block explorer?

https://starkscan.co/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Closing with above PR
