### ISSUE TITLE
add ETH Canal Meetup to community-meetups.json

### ISSUE THREAD

**Issue by sclarke001** [ethereum/ethereum-org-website#10820]
adding Panama Meetup so that it is listed on https://ethereum.org/en/community/events/

**Comment by kritik-sah** [comment]
Do we have to do it or is it done?  
@sclarke001 can you share more detail about events like the dates etc.
{
    "title": "ETH Canal Meetup",
    "emoji": ":panama:",
    "location": "Panama",
    "link": "https://www.meetup.com/eth-canal/"
  }

**Comment by sclarke001** [comment]
More events will be added to the meetup soon. Please add.

**Comment by corwintines** [comment]
I see that events have been on hold since August 2023. Going to close this out as inactive for now, but if this picks up again please reopen :)
