### ISSUE TITLE
Bug report: quizzes page crashes while loading

### ISSUE THREAD

**Issue by 0x0OZ** [ethereum/ethereum-org-website#10828]
### Describe the bug

The [quizzes](https://ethereum.org/en/quizzes/) page crashes while loading and show a blank screen after everything is loaded

Nothing can describe it more than a video:

https://github.com/ethereum/ethereum-org-website/assets/52073989/1c00f310-09ac-4633-b4ff-8175d3446a7a

the error occurs in `./src/components/Quiz/QuizItem.tsx` line 24 `id` is undefined

### To reproduce

I couldn't reproduce this bug in other browsers including an incognito mode in chrome browser...

The only thing I did on this page was do the quizzes; doing them again didn't reproduce it.

I didn't try to clear the cache to fix it, because I might not be able to reproduce it and figure out what is the cause if possible.
### Expected behavior

/

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/52073989/71b95ce6-4cac-44ae-90aa-0da117f677ff)
![image](https://github.com/ethereum/ethereum-org-website/assets/52073989/babb3a22-1436-4f4b-bd80-5bc4509d27d1)

_No response_

### Desktop (please complete the following information)

- OS: Manjaro Linux , Kernel: `6.1.41-1-MANJARO`
- Affected Browser: Chrome
- Browser version: `Google Chrome 115.0.5790.110`

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MahendraBishnoi29** [comment]
I would love to work on this issue 🚀

**Comment by corwintines** [comment]
Will assign to you @MahendraBishnoi29, thanks!

**Comment by MahendraBishnoi29** [comment]
> Following the discussion from #10845, afaik it's not possible to 'sync' changes when using localStorage if we change the structure of the data we are using to track progress across questions (e.g.: adding new quizzes, changing the order, etc) so this kind of issues are expected for users with progress on a previous version when deploying new quizzes cc @pettinarip @corwintines

how should i proceed and tackle this issue then? @nhsz

**Comment by pettinarip** [comment]
Thanks for the effort @MahendraBishnoi29. We've decided to revert these changes #10873 for now until we have a robust solution which may imply doing a refactor on how we store state on localstorage.
