### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by LeoBraavos** [ethereum/ethereum-org-website#10838]
### Wallet name

Braavos

### Wallet description

Braavos is a smart contract wallet on Starknet. 

It is the only wallet that leverages iPhone’s Secure Enclave or Android Phone’s Titan HSM to protect the account. Braavos provides the same user experience as Apple Pay (using biometric ID) with the security of a Hardware Wallet.

### Wallet logo

![Braavos logo cask](https://github.com/ethereum/ethereum-org-website/assets/129163276/213bc9f1-b36b-4fe1-8beb-f3b0b13626ce)

### Background color for brand logo

35363A

### URL to the project

https://braavos.app/

### When did the wallet go live to users?

Early April 2022 - first release

### Does the wallet have an active development team?

https://github.com/myBraavos

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

Twitter: https://twitter.com/myBraavos
Discord: discord.gg/9Ks7V5DN9z
Telegram: http://t.me/mybraavos
YouTube: https://www.youtube.com/@braavos_wallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes

iOS: https://apps.apple.com/us/app/braavos-wallet/id1636013523
Android: https://play.google.com/store/apps/details?id=app.braavos.wallet&pli=1

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes

Chrome: https://chrome.google.com/webstore/detail/braavos-smart-wallet/jnlgamecbpmbajjfhmmmlhejkemejdma
Firefox: https://addons.mozilla.org/en-US/firefox/addon/braavos-wallet/
Brave: https://chrome.google.com/webstore/detail/braavos-smart-wallet/jnlgamecbpmbajjfhmmmlhejkemejdma
Microsoft Edge: https://microsoftedge.microsoft.com/addons/detail/braavos-smart-wallet/hkkpjehhcnhgefhbdcgfkeegglpjchdc

### Is it a hardware wallet?

Braavos has designed a new technology called the Hardware Signer.

The Hardware Signer utilizes the secure subsystem built-in in users’ devices — iPhone’s Secure Enclave or Android Phone’s Titan HSM – to protect the account. The Secure Enclave / Titan chip is a dedicated and isolated subsystem, totally separated from the application processor, that can generate private keys and sign messages. It generates the keys using an internal True Random Number Generator (TRNG) and signs messages over the NIST-P256 elliptic curve (secp256r1) via its internal Public Key Accelerator (PKA). The private keys never leave the secure system and are unknown and inaccessible to anyone, not even to the user, or to the application itself. This means that even if the device application processor kernel becomes compromised, user keys stay safe!

### Is the source code for the wallet fully open-source?

https://github.com/myBraavos/braavos-account-cairo

### What license is the wallet software released under?

contracts are GNU General Public License v3.0, client is not open source

### Who holds the private keys?

Braavos is 100% non-custodial wallet, the keys are saved on users' devices

### Has the wallet's smart contract code or security modules been audited?

Partially (the swap feature), soon the contracts as well

### Does the wallet have an internal security team?

Yes

### Scam protection?

The Transaction Explainer

### Does the wallet support connecting to a hardware wallet?

We have the Hardware Signer that connects to the mobile’s hardware vault

### Does the wallet support WalletConnect?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, on Starknet

### Does the wallet support staking directly?

Yes, with the Stake+ feature you can stake your ETH on Lido in one click

### Does the wallet support swaps directly?

Yes

### Does the wallet support multi-chain networks?

No, only Starknet for now

### Does the wallet support Ethereum layer 2 networks?

Yes, Starknet

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes, to SNS, Starknet equivalence to ENS.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes through Banxa and Ramp

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

Yes, https://braavos.app/multi-owner-account-elevate-team-collaboration-on-starknet-with-account-abstraction/

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

You can contact us directly on Twitter: @myBraavos
Or on our email address: [marketing@braavos.app](mailto:marketing@braavos.app)

### Does the wallet have a dedicated support team?

Yes

https://discord.com/channels/962985965889142844/964090590407053362

### What educational resources/documentation do you provide to users?

We have a blog: https://braavos.app/blog/

A YouTube channel: https://www.youtube.com/@braavos_wallet

And we do weekly AMAs on Twitter or Discord

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Hey @LeoBraavos,

Sounds like a cool project, but I don't see this being appropriate for our wallets page given this can only be used on Starknet. At the bare minimum, a wallet should support Ethereum Mainnet on our wallets page. Going to close this out since users wouldn't be able to use Ethereum Mainnet with this.
