### ISSUE TITLE
Feature request: Update information about Arbitrum One

### ISSUE THREAD

**Issue by TucksonDev** [ethereum/ethereum-org-website#10830]
### Is your feature request related to a problem? Please describe.

Information about Arbitrum One is not up to date:
- Logo is outdated
- Link to token lists is wrong
- Internal links to developer docs and block explorer are deprecated

### Describe the solution you'd like

Information should be up to date.

### Describe alternatives you've considered

-

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by TucksonDev** [comment]
Hey @corwintines !
Thanks for merging #10831  :)

Regarding the logo change, Arbitrum is using different logos for the ecosystem, the Foundation, and the different chains. The one I added was the logo for Arbitrum One (the chain being referenced in the website). You can see the new Arbitrum One logo on [L2Beat](https://l2beat.com/scaling/projects/arbitrum) or in the [official website](https://arbitrum.io/) (first box in Arbitrum Nitro's section).

Shall I create a new PR for updating the logo?

**Comment by corwintines** [comment]
Ah thanks for the context @TucksonDev 

Feel free to just open a PR and link to this one :)
