### ISSUE TITLE
Bug report: Design regression on staking product listings

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#10834]
### Describe the bug

The alignment for product names is off for the staking products listed on the Solo/SaaS/Pools sub-pages for https://ethereum.org/en/staking/... The logo is correctly centered, but the names are aligning too high or too low depending on the device size.

### To reproduce

1. Go to https://ethereum.org/en/staking/solo/#node-and-client-tools
2. See alignment of product names with their logos

### Expected behavior

Both the logo and the names should be aligned along the central horizontal axis of that container. 

### Screenshots

<img width="1068" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/6a982a5e-2ade-40d8-8505-97cbbb25339f">

### Desktop (please complete the following information)

- macOS Ventura, Brave and Safari both

### Smartphone (please complete the following information)

- iOS, Brave and Safari both

### Additional context

The names appear to be aligned too high on desktop, yet too low on mobile.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MahendraBishnoi29** [comment]
I will take care of this 👍🏻 @wackerow

**Comment by wackerow** [comment]
Looks like this is resolved now.
