### ISSUE TITLE
button padding wrong

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#10847]
### Describe the bug

the button is not aligned with the text

### To reproduce

1. Go to (https://ethereum.org/en/layer-2/)
2. See error in the header

### Expected behavior

buttons aligned with the text

### Screenshots

![Screenshot 2023-08-02 at 16 05 03](https://github.com/ethereum/ethereum-org-website/assets/100724231/ffd82589-f67c-4617-802d-141d07631c87)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by amit-ksh** [comment]
@konopkja I'd like to work on this?
