### ISSUE TITLE
[Proposal] Include Interaction Testing via Storybook

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#10878]
## 🚨 Important
This is for the core team as a way to record feedback on this possible implementation. No further action is to be taken at this time due to other project tasks such as implementing the new DS, Migrating the site to NextJS, etc.

## Description
This is a proposal to add interactive testing within storybook.

Interaction Testing is described as automated mock user interactions with the UI. In relation to the structure of the new DS, this would mean possible testing at the "Molecule" or "Organism" level and above to ensure change of state with components are functioning and styled as expected.

Information regarding setup and usage inside Storybook can be found on their [Interaction Tests DocPage](https://storybook.js.org/docs/react/writing-tests/interaction-testing)

Storybook provides packages which include an addon, SB-charged Jest and SB-charged Testing Library to create Zero-config with interactions set up in stories through the `play` function. 
(Note Storybook's explanation for [Interaction tests versus using a testing library on it's own](https://storybook.js.org/docs/react/writing-tests/interaction-testing#whats-the-difference-between-interaction-tests-and-using-jest--testing-library-alone))

### Current Inquiries

The primary reason for the issue to be feedback only is the question of necessity. I currently have not experienced many red flags with interaction issues that couldn't be solved quickly. However, due to unification goals of the UI in a new Design System along with the scaling of the project, I wonder if the team may already be envisioning a need to have this testing as an additional fail-safe. Especially when including interactive tools like the quizzes.

A secondary reason for this being feedback only is that this implementation will add dev dependencies -- specifically three from Storybook -- that provide their modification of Jest and Testing Library, and an addon to log the interactions in the Storybook control dashboard for the viewed story. I would not expect this to be impactful though to the project if these packages are to not effect build times in deployment.

### Alternatives

A primary alternative would be using Cypress as the platform for specifically interaction testing. However, it would be preferred to utilize Storybook since it already exists in the project.

## Main Question to Pose

What UI, either currently in deployment or to be added, could benefit from this type of testing?

**Comment by wackerow** [comment]
Hey @TylerAPfledderer, now that #12444 is merged, could we call this closed? Or did you see this as an ongoing tracker of some kind?

**Comment by TylerAPfledderer** [comment]
@wackerow oh, this should've been marked to close by that PR. I'll close it as completed. Thank you!
