### ISSUE TITLE
Add KROMA Layer 2

### ISSUE THREAD

**Issue by Kajko25** [ethereum/ethereum-org-website#10871]
### Name

KROMA

### Logo

![KROMA1](https://github.com/ethereum/ethereum-org-website/assets/112957382/e1684633-0532-4093-b1f0-a36d292fb1bb)

### Description

Kroma aims to develop an universal ZK Rollup based on the Optimism Bedrock architecture. Currently, Kroma operates as an Optimistic Rollup with ZK fault proofs, utilizing a zkEVM based on Scroll. The goal of Kroma is to eventually transition to a ZK Rollup once the generation of ZK proofs becomes more cost-efficient and faster. Kroma is deployed on the Sepolia testnet for further testing and optimization.

### Website

https://kroma.network/

### Developer documentation

https://docs.kroma.network/introduction/overview

### L2BEAT page

https://l2beat.com/scaling/projects/kroma

### Is the project open source?

https://github.com/kroma-network

### What category of layer 2 is it?

Kroma is universal ZK Rollup based on the Optimism Bedrock architecture.

### Does the layer 2 use Ethereum Mainnet for data availability?

Ethereum Mainnet

### Which bridges are used to onboard users?

https://kroma.network/bridge

### Which exchanges offer support for the project?

https://swap.sepolia.kroma.network/#/swap

### What date did the project go live?

TESTNET

### Is this project a fork? If yes, which project was forked?

No

### What wallets support this layer 2?

Metamask/EVM

### Is there an active team developing the project?

Yes

### Is there a block explorer?

https://blockscout.sepolia.kroma.network

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
This needs to be listed on L2BEAT before we will consider it. Going to close this out.
