### ISSUE TITLE
Help needed to set up site locally

### ISSUE THREAD

**Issue by checkomkar** [ethereum/ethereum-org-website#10872]
### Describe the bug

I am trying to setup the site locally, but I get bunch of errors in the console. The page loads and then goes blank due to API error. Can someone point to a good tutorial or steps to setup the site locally. I feel contributors guide lack these steps.

I think I am missing some steps.

Here is the video of the error I am facing.

https://github.com/ethereum/ethereum-org-website/assets/8987373/fea683a9-d769-4215-8aa3-b7b11457ddd1

### To reproduce

1. Go to 'localhost:8000'
2. See errors in the console and in network tab

### Expected behavior

The site should load in development environment

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/8987373/be4570f9-40ab-466c-86c7-61c286255288)

### Desktop (please complete the following information)

- OS [Windows 10]
- Browser [Chrome]
- Version 115.0.5790.111 (Official Build) (64-bit)

### Would you like to work on this issue?

- [X] Yes
- [X] No

**Comment by rohan9024** [comment]
Hey @checkomkar . Have you updated your .env? Even after that you're facing the errors then try 
rm -rf node_modules && yarn install && npx gatsby clean

yarn start

**Comment by rohan9024** [comment]
Also @konopkja @corwintines 

I think we need to make a setup tutorial for folks who are willing to contribute and provide fixes for any problems if they face
I can create a tutorial in case....Need your guidance on this

**Comment by checkomkar** [comment]
> Hey @checkomkar . Have you updated your .env? Even after that you're facing the errors then try rm -rf node_modules && yarn install && npx gatsby clean
> 
> yarn start

Thanks for reply @rohan9024, I just copied the .env.example to .env, but I am not sure what values should I put for each key in .env

A step by step tutorial will be super helpful as the current guide is not clear.

**Comment by rohan9024** [comment]
Here is the content for .env -->


```# rename this file to .env and supply the values listed below
# also make sure they are available to the build tool (e.g. Netlify)
# warning: variables prefixed with GATSBY_ will be made available to client-side code
# be careful not to expose sensitive data (e.g. your Algolia admin key)
# you don't to change these 
ALGOLIA_ADMIN_KEY=insertValue
ETHERSCAN_API_KEY=insertValue
GATSBY_ALGOLIA_APP_ID=insertValue
GATSBY_ALGOLIA_SEARCH_KEY=insertValue
GATSBY_GITHUB_TOKEN_READ_ONLY=insertValue
GATSBY_FUNCTIONS_PATH=insertValue

# Build pages only for the specified langs. Leave it empty to build all the langs
# e.g. `en,fr` will only build english and french pages
# Note: always include `en` as it is the default lang of the site
GATSBY_BUILD_LANGS=en

# Folders or files to ignore from the `src/content` folder
IGNORE_CONTENT=**/tutorials

# Used to avoid loading Matomo in our preview deploys
IS_PREVIEW_DEPLOY=false```

I'll have informed the ethereum core team. Let's see ...

**Comment by checkomkar** [comment]
@rohan9024 thank you. It seems there is some issue with one of my browser extension. I tried in another browser and it worked.

**Comment by corwintines** [comment]
@checkomkar wondering if you are blocking scripts or cookies in the browser. Looks similar to this issue: https://github.com/ethereum/ethereum-org-website/issues/8725

**Comment by checkomkar** [comment]
> @checkomkar wondering if you are blocking scripts or cookies in the browser. Looks similar to this issue: #8725

Yeah it seems some extension was blocking cookies, hence the page was blanking out. Anyway I just removed a couple of extensions and it started working.
