### ISSUE TITLE
Warning regarding known ERC-20 problems

### ISSUE THREAD

**Issue by Dexaran** [ethereum/ethereum-org-website#10889]
### Is your feature request related to a problem? Please describe.

ERC-20 standard has [known problems](https://dexaran820.medium.com/known-problems-of-erc20-token-standard-e98887b9532c) i.e. lack of 'transaction handling'. OpenZeppelin [confirmed that the problem is widely known](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4451) and it results in impossibility of handling user errors. As the result tokens can be lost and [$130,000,000 worth of tokens are lost today](https://gist.github.com/Dexaran/0b2df0a6ad9a2092fe0b768813669982) even though it could be easily prevented if transaction handling would be implemented.

- I first have reported this issue in 2017, there were $10,000 lost at that moment: [my initial post](https://www.reddit.com/r/ethereum/comments/60ql37/attention_be_careful_using_ethereum_tokens/)
- Then I had a discussion with Ethereum Foundation members involved, at that time there were $13,000 lost: [discussion thread](https://www.reddit.com/r/ethereum/comments/66gr2a/metropolis_and_erc23_request_for/)
- Then I commented the final ERC-20 PR and explained this issue, there were $16,800 lost at that moment: [my comment on the PR](https://github.com/ethereum/EIPs/pull/610#issuecomment-296711733)
- Then it became $1,000,000 loss in 2018: [source](https://www.reddit.com/r/ethereum/comments/7mea1c/erc20_anniversary_new_ath_reached_1_000_000_lost/)
- Then the creator of ERC-20 said he doesn't want to use it in his new project: [Fabian Vogelsteller's tweet](https://twitter.com/feindura/status/1676623784726470658)
- Today it became $130,000,000 lost: [reddit announcement](https://www.reddit.com/r/ethereum/comments/15hdz96/today_at_least_130m_worth_of_tokens_are_lost/)
- Here is a security statement regarding this problem: [statement link](https://www.reddit.com/r/cybersecurity/comments/15ejbjs/erc20_standard_callisto_security_department/)

### Describe the solution you'd like

As ethereum.org is an informational resource I think it is critically important to highlight that using ERC-20 standard may result in a loss of funds so that developers would be aware of the risks as well as the users.

Probably it needs to be added to the Security tab: "ERC-20 token standard does not implement transaction handling, which means it is impossible to handle user mistakes. As of today (8/7/2023) $130,000,000 worth of tokens were 'permanently frozen' because of this."

### Describe alternatives you've considered

Alternatively it could be described in the EIP, but it is in "final" state and it can't be changed now.

Also, it could help if someone from Ethereum Foundation could release an official statement but they didn't do it so far. The longer the problem remains silenced the more funds will be lost.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by vblackwhale** [comment]
My brother in Christ, are you ever going to get over the fact that devs do not want to use your token standard over ERC-20 ? Or are you here to try and extort the Ethereum Foundation after your attempt with OpenZeppelin failed ?

For reference: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4474

**Comment by Dexaran** [comment]
I'm a security auditor and I'm here to report and solve a security issue that caused Ethereum community to lose [$103,000,000](https://gist.github.com/Dexaran/40213a04ce46b394279ac7daa581ce87) worth of tokens.

It seems I'm the only honest security auditors who dares to report an issue in the most commonly used component of the ecosystem.

**Comment by Dexaran** [comment]
@corwintines @Pandapip1 what about this?

**Comment by Pandapip1** [comment]
I do approve of adding warnings that ERC-20 is succeptible to this. I would also love warnings about the approve double spend attack and using unreasonably large approvals.

While @Dexaran is the author of a competing standard, anything that causes $200 million worth of lost funds at least deserves a mention. Even if/though @Dexaran stands to gain from public awareness, it is an issue and it is arguably underdocumented.

I support adding a warning.

**Comment by Pandapip1** [comment]
Any updates?

**Comment by wackerow** [comment]
#11787 has just been merged, adding a section to the `/erc-20` page about this issue, and also adds a dedicate `/erc-223` page. There are a few follow-up polishes to come, but going to mark this closed in the meantime. Thanks everyone!

**Comment by Dexaran** [comment]
Congrats.

@wackerow @Pandapip1 my team built a "live" losses calculator that (1) provides the info regarding the problem and (2) is able to re-calculate the actual amount of lost tokens by given addresses.

https://dexaran.github.io/erc20-losses/

Any chance it can be integrated?

**Comment by Pandapip1** [comment]
That calculator makes a few assumptions that may not necessarily hold. It should instead do contract introspection and figure out if the contract can call transfer or approve, or detect if a transfer or approval event from that contract has ever been ever done. This will remove the false positives but also find tokens stuck for other reasons.

Also, how are you figuring out the dollar value of all the stuck tokens? DExes shouldn't be used, since anyone can create a token and have full control over its value.

I think if these things can be fixed, then it would be a good resource and would be a worthy thing to upstream.

**Comment by Dexaran** [comment]
>It should instead do contract introspection and figure out if the contract can call transfer or approve, or detect if a transfer or approval event from that contract has ever been ever done.

Good point. We will probably implement it in the next update (approx. mid July).

>Also, how are you figuring out the dollar value of all the stuck tokens?

Currently we are pulling the prices from Coinmarketcap / Coingecko APIs at the moment of the calculation.

**Comment by Dexaran** [comment]
We will add a link to the prices API, it's already in the template

![LOSSES_SCRIPT_prices_api](https://github.com/ethereum/ethereum-org-website/assets/26142412/2131c9e3-3673-4303-8405-3d72f5859258)

https://www.figma.com/design/jcRkikBXNpoidDDaxuolLC/%F0%9F%A7%AE-ERC-20-losses-calculator?node-id=1-2&t=RXVPSNnKMNc2CoTu-1

**Comment by Pandapip1** [comment]
> Currently we are pulling the prices from Coinmarketcap / Coingecko APIs at the moment of the calculation.

Great! Just double checking.

**Comment by corwintines** [comment]
I think if we add this, we should just link out to this resource, and not integrate it specifically on ethereum.org. But open to feedback from others.
