### ISSUE TITLE
Link to the correct page

### ISSUE THREAD

**Issue by AlbionaHoti** [ethereum/ethereum-org-website#10884]
The page for [how-to-register-an-ethereum-account](https://ethereum.org/en/guides/how-to-register-an-ethereum-account/) is not found. It might be lost somewhere in the docs. Seen from this [page](https://ethereum.org/en/guides/how-to-use-a-wallet/).

It might be that the URL changed, and they forgot to update it on different pages, the new URL: https://ethereum.org/en/guides/how-to-create-an-ethereum-account/.

**Comment by rishabhknowss** [comment]
please assign me the issue

**Comment by wackerow** [comment]
Looks like this is resolved now, thanks for noting @AlbionaHoti!
