### ISSUE TITLE
adjust top and bottom margin on in page mobile navigation

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#10896]
### Describe the bug

on the menu to change pages, the <ul> have too much top margin

please see the image to help do the fix

![Screen Shot 2023-08-09 11 07 41 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/5aa622ed-0f32-40d7-83f9-18ce4e51ddc8)

### To reproduce

1. Go to (https://ethereum.org/en/social-networks/) on mobile screens
2. Click on "on this page"

### Expected behavior

the space is

`margin-top: var(--eth-space-20);` and `margin-bottom: var(--eth-space-20);`

should be

`margin-top: var(--eth-space-2);` and `margin-bottom: var(--eth-space-2);`

### Screenshots

![Screen Shot 2023-08-09 10 45 16 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/37e070d7-cbb2-4295-bd36-d31a29a0fb5b)

![Screen Shot 2023-08-09 03 53 02 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/31c0dea8-289b-4d74-a345-a3084df18c32)

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by altinocoelho** [comment]
@nloureiro should the margin-bottom receive similar adjustment? 

Noticed that on some pages, like https://ethereum.org/en/governance/ , the menu is showing but not working.

![image](https://github.com/ethereum/ethereum-org-website/assets/92543849/245e577b-6022-4589-8fec-ece4ba248667)

But I'm not sure which is the expected behavior

**Comment by nloureiro** [comment]
> @nloureiro should the margin-bottom receive similar adjustment?

oh, I forgot to mention that. Thank you for raising it it
yes, of course

both should be the same
![Screen Shot 2023-08-09 03 50 17 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/248f667a-3451-40b2-a686-75c33d799707)

**Comment by altinocoelho** [comment]
sure thing!

 I'll look into it later if it's ok

**Comment by wackerow** [comment]
Closed with #10909
