### ISSUE TITLE
Bug report: Error and success states in quiz component showing white bars in dark mode

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#10905]
### Describe the bug

![Screen Shot 2023-08-09 at 11 29 44 AM](https://github.com/ethereum/ethereum-org-website/assets/15589226/9e80f2aa-c802-4146-ba0d-eb3f0c32b9b7)

Whether answering correct or incorrect in the /quizzes/ page, there is a bug in dark mode where the we see white bars from the modal. 

We fixed this for the neutral state, but need to fix this in all cases: https://github.com/ethereum/ethereum-org-website/pull/10860

### To reproduce

1. Go to https://ethereum.org/en/quizzes
2. Do a quiz
3. Answer a question right or wrong

### Expected behavior

The background of the modal in the success and error states should be the same as the background of the quiz widget

### Screenshots

![Screen Shot 2023-08-09 at 11 29 44 AM](https://github.com/ethereum/ethereum-org-website/assets/15589226/c87bffbd-6410-42f6-b1e4-6bae4fd617cb)

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by pettinarip** [comment]
Issue being fixed in #11423

**Comment by F3n4nd0gm** [comment]
http://192.168.1.254
Passwords>
https://coinmarketcap.com/
