### ISSUE TITLE
"on this page" dropdown is not working, on mobile

### ISSUE THREAD

**Issue by altinocoelho** [ethereum/ethereum-org-website#10900]
### Describe the bug

On mobile, the pages like https://ethereum.org/en/governance/ , the "on this page" dropdown is not working

### To reproduce

1. Go to https://ethereum.org/en/governance/
2. Check "On this page" menu
3. Nothing happens

### Expected behavior

A dropdown menu should appear with the page content

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/92543849/015eb81b-45b6-4cd3-b65c-fd8c710636c4)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by MahendraBishnoi29** [comment]
assign it to me 👍🏻

**Comment by corwintines** [comment]
closing with above PR
