### ISSUE TITLE
Bug report: Why is the Ethereum logo asymmetric?

### ISSUE THREAD

**Issue by junsung-cho** [ethereum/ethereum-org-website#10918]
### Describe the bug

Why is the Ethereum logo asymmetric?

<img width="704" alt="Screenshot 2023-08-12 at 12 44 11 PM" src="https://github.com/ethereum/ethereum-org-website/assets/97071544/101aa04c-7444-4cf8-8cfb-49a1232478f9">

* 1-L: w 539.7 h 895.6
* 1-R: w 539.8 h 895.6
* 2-L: w 539.7 h 564.4
* 2-R: w 539.8 h 564.4
* 3-L: w 539.7 h 760.6
* 3-R: **w 540.1** h 760.6

Other logos also have similar problem

### To reproduce

see https://github.com/ethereum/ethereum-org-website/blob/dev/static/static/eth-diamond-purple.svg

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 1920 1920" viewBox="0 0 1920 1920">
  <path
     d="m959.8 80.7-539.7 895.6 539.7-245.3z"
     fill="#8a92b2" />
  <path
     d="m959.8 731-539.7 245.3 539.7 319.1z"
     fill="#62688f" />
  <path
     d="m1499.6 976.3-539.8-895.6v650.3z"
     fill="#62688f" />
  <path
     d="m959.8 1295.4 539.8-319.1-539.8-245.3z"
     fill="#454a75" />
  <path
     d="m420.1 1078.7 539.7 760.6v-441.7z"
     fill="#8a92b2" />
  <path
     d="m959.8 1397.6v441.7l540.1-760.6z"
     fill="#62688f" />
</svg>
```

### Expected behavior

* 1-L: w 539.7 h 895.6
* 1-R: w 539.8 h 895.6
* 2-L: w 539.7 h 564.4
* 2-R: w 539.8 h 564.4
* 3-L: w 539.7 h 760.6
* 3-R: **w 539.8** h 760.6

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 1920 1920" viewBox="0 0 1920 1920">
  <path
     d="m959.8 80.7-539.7 895.6 539.7-245.3z"
     fill="#8a92b2" />
  <path
     d="m959.8 731-539.7 245.3 539.7 319.1z"
     fill="#62688f" />
  <path
     d="m1499.6 976.3-539.8-895.6v650.3z"
     fill="#62688f" />
  <path
     d="m959.8 1295.4 539.8-319.1-539.8-245.3z"
     fill="#454a75" />
  <path
     d="m420.1 1078.7 539.7 760.6v-441.7z"
     fill="#8a92b2" />
  <path
     d="m 959.8 1397.6v441.7l539.8,-760.6 z"
     fill="#62688f"/>
</svg>
```

### Additional context

```diff
--- eth-diamond-purple.svg	2023-08-12 12:56:35
+++ eth-diamond-purple-fix.svg	2023-08-12 12:56:35
@@ -16,6 +16,6 @@
      d="m420.1 1078.7 539.7 760.6v-441.7z"
      fill="#8a92b2" />
   <path
-     d="m959.8 1397.6v441.7l540.1-760.6z"
-     fill="#62688f" />
+     d="m 959.8 1397.6v441.7l539.8,-760.6 z"
+     fill="#62688f"/>
 </svg>
```

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by vivekjoshi-omni-pay** [comment]
Please assign this issue on my name

**Comment by nnnnnnsssss** [comment]
Recheck

**Comment by wackerow** [comment]
@nloureiro Any opposition?

@vivekjoshi-omni-pay Looks good to me! Sorry for late reply here, but assigning you if you'd like to make this update.

**Comment by wackerow** [comment]
Ah never mind, looks like this has already been updated. Closing out
