### ISSUE TITLE
Bug report: link to guide doesnt work on a wallet page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#10919]
### Describe the bug

how to register account is a deadlink - should link to https://ethereum.org/en/guides/how-to-create-an-ethereum-account/ instead

### To reproduce

1. Go to https://ethereum.org/en/wallets/
3. Click on how to register ethereum account

### Expected behavior

working link

### Screenshots

<img width="897" alt="Screenshot 2023-08-12 at 22 08 37" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/efb632da-0039-4f03-bf2e-2b6868eaeff2">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by sidk524** [comment]
I can do this now.
