### ISSUE TITLE
API.NODE.VALIDATION

### ISSUE THREAD

**Issue by raghchawla131** [ethereum/ethereum-org-website#10917]
After following each and every step described in HOW TO CONTRIBUTE section, i am facing this error when i run the command **yarn start**. I installed nvm because volta wasn't working on windows.
<img width="960" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/112266194/47baef9c-1c60-4bf3-a02a-c27f74214bc9">

**Comment by corwintines** [comment]
You can ignore this error @raghchawla131. It doesn't block running the website, and we are moving away from gatsby this quarter.
