### ISSUE TITLE
improve the left side navigation

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#10924]
### Is your feature request related to a problem? Please describe.

The left-side navigation on content pages raised some UX problems with readability and off-screen content.

These issues might be improved in a re-design that should be done under the Design system changes, but meanwhile we can improve the UX of the page with some quick CSS changes.
![Screen Shot 2023-08-14 02 51 03 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/82d0def4-1b73-476c-ad1b-2f61c639f78c)

### Describe the solution you'd like

![Screen Shot 2023-08-14 02 51 59 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/7e62dea4-2376-4947-a28c-4e2c51a1dd50)

This is a screenshot of this Figma file where you can find the proposed changes.
https://www.figma.com/file/ut0RrfN81MLW28Do4X36kQ/sidebar-ux-quick-fix?type=design&node-id=37%3A235&mode=design&t=4H9l9AD1xYCSrosy-1

this would be the finished outcome
![Screen Shot 2023-08-14 02 53 16 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/a34f459d-8161-4e8b-9f60-111a91083fc3)

These changes are targeted at desktop resolutions. The mobile version should not change.

### Describe alternatives you've considered

I discussed this proposed change with the team, and moving forward is OK.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by corwintines** [comment]
@rohan9024 would you like to work on this?

**Comment by rohan9024** [comment]
@corwintines yeah sure. Can you please assign me ?

**Comment by priyadarshss** [comment]
@minimalsm Would it be possible to merge my PR if I finish it earlier although it has been assigned to someone else? I have already begun working on it, which is why I am asking.

**Comment by rohan9024** [comment]
> @minimalsm Would it be possible to merge my PR if I finish it earlier although it has been assigned to someone else? I have already begun working on it, which is why I am asking.

You can work on other issues which haven't been assigned to anyone yet😊

**Comment by priyadarshss** [comment]
@rohan9024 Works for me :). Thank you! 
I've pretty much fixed this part: 
![image](https://github.com/ethereum/ethereum-org-website/assets/58765597/e1b6232d-d1a6-480b-8a4b-6a01aca56674)
![image](https://github.com/ethereum/ethereum-org-website/assets/58765597/59099cba-ca07-44ed-be05-c644a1c1674a)

So you can do the button on top if that's okay with you.

**Comment by rohan9024** [comment]
> @rohan9024 Works for me :). Thank you! 
> I've pretty much fixed this part: 
> ![image](https://github.com/ethereum/ethereum-org-website/assets/58765597/e1b6232d-d1a6-480b-8a4b-6a01aca56674)
> ![image](https://github.com/ethereum/ethereum-org-website/assets/58765597/59099cba-ca07-44ed-be05-c644a1c1674a)
> 
> So you can do the button on top if that's okay with you.

Can we have a chat on discord ? My id is rohan.tsx 

See you there!

**Comment by rohan9024** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> The left-side navigation on content pages raised some UX problems with readability and off-screen content.
> 
> These issues might be improved in a re-design that should be done under the Design system changes, but meanwhile we can improve the UX of the page with some quick CSS changes.
> ![Screen Shot 2023-08-14 02 51 03 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/82d0def4-1b73-476c-ad1b-2f61c639f78c)
> 
> 
> ### Describe the solution you'd like
> 
> ![Screen Shot 2023-08-14 02 51 59 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/7e62dea4-2376-4947-a28c-4e2c51a1dd50)
> 
> This is a screenshot of this Figma file where you can find the proposed changes.
> https://www.figma.com/file/ut0RrfN81MLW28Do4X36kQ/sidebar-ux-quick-fix?type=design&node-id=37%3A235&mode=design&t=4H9l9AD1xYCSrosy-1
> 
> 
> this would be the finished outcome
> ![Screen Shot 2023-08-14 02 53 16 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/a34f459d-8161-4e8b-9f60-111a91083fc3)
> 
> These changes are targeted at desktop resolutions. The mobile version should not change.
> 
> 
> 
> 
> 
> ### Describe alternatives you've considered
> 
> I discussed this proposed change with the team, and moving forward is OK.
> 
> ### Additional context
> 
> _No response_
> 
> ### Would you like to work on this issue?
> 
> - [ ] Yes
> - [ ] No

Well, also one additional suggestion @corwintines @nloureiro  . We can make text color as blue to indicate links which looks much cleaner

**Comment by priyadarshss** [comment]
@rohan9024 I do second that suggestion. Also, DMed on discord.
