### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by justynleung** [ethereum/ethereum-org-website#10923]
### Describe the bug

There was a typo on the profile filters.

### To reproduce

1. Go to 'HOME / WALLET / FIND'
2. Scroll down to 'Profile filter'
3. See error "Hodler"

### Expected behavior

The spelling should be holder

### Screenshots

<img width="1000" alt="Screen Shot 2023-08-13 at 23 23 55 PM" src="https://github.com/ethereum/ethereum-org-website/assets/114822505/291a4701-e49e-40df-bcb9-397a68e63ba4">

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by priyadarshss** [comment]
Pretty sure this is intentional XD. FYI: https://www.urbandictionary.com/define.php?term=Hodler

**Comment by corwintines** [comment]
Thanks for bringing this up @justynleung 

As mentioned, this is more of a crypto culture reference and was intentional. I don't think we plan on making this change so going to close this out.

**Comment by justynleung** [comment]
Thank you for the clarification. @priyadarshss
