### ISSUE TITLE
Events Module Title Line Height

### ISSUE THREAD

**Issue by tlcottr** [ethereum/ethereum-org-website#10933]
### Describe the bug

The events module on the homepage of ethereum.org has a line-height of 1.4 applied to the entire div, but the actual event title is feeling a bit crunched at this line height on all device sizes.

### To reproduce

1. Go to 'ethereum.org'
2. Scroll down to 'Events module leading with "NEXT EVENT"'
4. See line height error

### Expected behavior

A title style with more whitespace in the line height

### Screenshots

<img width="324" alt="Screenshot 2023-08-14 at 4 38 25 PM" src="https://github.com/ethereum/ethereum-org-website/assets/32750540/efd6ebb9-4017-4d43-8afe-8adb1175862a">
<img width="386" alt="Screenshot 2023-08-14 at 4 38 14 PM" src="https://github.com/ethereum/ethereum-org-website/assets/32750540/84b58fa9-0737-4f79-b1ac-db95ec44e3ad">
<img width="961" alt="Screenshot 2023-08-14 at 4 37 37 PM" src="https://github.com/ethereum/ethereum-org-website/assets/32750540/b09433e6-f986-480e-8f39-54be7f0c9682">

### Desktop (please complete the following information)

Ventura 13.1 / Chrome / 115.0.5790.114

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by nawed2611** [comment]
Hey, can i work on this?

**Comment by wackerow** [comment]
I'm not sure this is an issue any longer...

<img width="1480" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/2f9a2c8d-5096-4431-ab57-1f71b3afaa30">

Closing out, but feel free to re-open if I've missed anything
