### ISSUE TITLE
translated image on 

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#10948]
### Describe the bug

this image has text outside of the box on the translated version
![image](https://github.com/ethereum/ethereum-org-website/assets/1120748/8ac896e8-c582-4613-a7f6-60fbd7bacfe6)

original image
![image](https://github.com/ethereum/ethereum-org-website/assets/1120748/f8c9d306-b9a9-45cf-b032-4dc45f57c3ad)

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/transactions/#on-gas
2. view the pt-br
3. Scroll down to /#on-gas section

### Expected behavior

should be inside the box

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by mrnadyy** [comment]
Jdm

**Comment by rafarocha** [comment]
Weird. I checked the translation and both have equal `tspan` definitions. It has the same value properties at `dy=21` and different font styles.

Inside a `tspan` I don't know how to fix this. Maybe, changing the script that generates the images. How do I reproduce to process and generate images by language?

```
Externally<tspan x="120.834" dy="21">owned account</tspan>
Conta de <tspan x="120.834" dy="21">propriedade externa</tspan>
```

Text translation
https://crowdin.com/translate/ethereum-org/7769/en-ptbr?filter=basic&value=3

Image english 
https://ethereum.org/static/c3638b26a1210d2c73a7ec2335c57351/302a4/gas-tx.png

Image pt-br
https://ethereum.org/static/7739f5cc6e54a00841b83dc84c8328e1/302a4/gas-tx.png

**Comment by corwintines** [comment]
@nloureiro This still appears to be an issue, but I think this has to be done in figma. Are you the right one to update this image?

**Comment by nloureiro** [comment]
> @nloureiro This still appears to be an issue, but I think this has to be done in figma. Are you the right one to update this image?

I fix the image and created a PR > https://github.com/ethereum/ethereum-org-website/pull/12100
