### ISSUE TITLE
Scroll into view not taking to the right position

### ISSUE THREAD

**Issue by priyadarshss** [ethereum/ethereum-org-website#10959]
### Describe the bug

The right side navigation has links which when clicked takes to the topic heading in that page but due to the headers, the topic heading is covered and we have to scroll up a bit to see the topic heading.

https://github.com/ethereum/ethereum-org-website/assets/58765597/064b77fa-125d-4ce3-89f3-23b25730263a

This problem exists on all the pages that have this side nav.

### To reproduce

One example of it:

1. Go to [this page](https://ethereum.org/en/developers/docs/nodes-and-clients/)
2. Click on any of the link in the side nav on the right
3. It scroll a bit lower than the supposed position

### Expected behavior

The links scrolls to the topic heading where the heading will be seen on screen instead of being under the header of the page.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by TylerAPfledderer** [comment]
Hi @priyadarshss !

I think this is a known issue. 😅

Note that the new DS with the goal of unifying layouts should result in only one sticky top nav with no sub nav like you see in the dev docs, with a consistent responsive size between any type of page. This way, it would be straightforward to add an offset to the scroll position.

What do you have in mind that would also minimize having to undo some of the work once we update the layouts?

**Comment by priyadarshss** [comment]
Hey @TylerAPfledderer ! 

Thanks for pointing out the known issue and the approach to addressing it! 

One suggestion could be to make the offset value for the scroll position dynamically determined, based on the actual height of the sticky top nav. This way, if the size of the nav changes with the new design system, the scroll offset would automatically adapt without requiring a code change. I'll make a PR today and you can have a look at it.

On a related note, do you have any insights into when the new DS is expected to be implemented?

**Comment by TylerAPfledderer** [comment]
The DS has been a work in progress, slowly implementing components as we go. No hard deadlines at this time.

If you are creating a PR, consider making any alterations or additions in the [scrollIntoView](https://github.com/ethereum/ethereum-org-website/blob/dev/src/utils/scrollIntoView.ts) that is used frequently.

**Comment by priyadarshss** [comment]
@TylerAPfledderer Can you take a look at the above commit(either) and let me know if that's feasible for now? Will make a PR if yes.

**Comment by TylerAPfledderer** [comment]
@priyadarshss this should work!

Double-check how this is handled in a `developer/docs` page with the right-side table of contents.

**Comment by wackerow** [comment]
Looks like this has been resolved, thanks folks!
