### ISSUE TITLE
XBANKING

### ISSUE THREAD

**Issue by xbankingorg** [ethereum/ethereum-org-website#10965]
### Name

XBANKING

### Description

Non-custodial staking provider.

### Logo

![400400](https://github.com/ethereum/ethereum-org-website/assets/126655346/3bd3218f-c75a-485c-9625-dc5a3a17d4a0)

### Brand color

000000

### Is your dapp open source?

No

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

The security of our solutions comes first

Check out our software and technology solutions to secure and monitor the entire XBANKING ecosystem

**Cloud Datacenter**
Amazon AWS.
Google Cloud.
Private Datacenter.
Tier III and IV Datacenter.
All levels of redundancy.

**Security**
Front-end Firewall.
Back-end Firewall.
DDoS protection.
Hardening Server Security.
Low latency with High Performance VPN.
AS Carrier/ISP.
Full Layer7 inspection.
IPS/IDS.
No incoming connections.
KMS/HSM hardware.

**Monitoring**
Datacenter, Hardware and Virtual Machine are monitored and alarmed.
Blockchain monitoring systems such as 'out of sync' and missing signatures.
Hourly reports.
Real-time alarms.
24/7 monitoring.

### Can a user access the dapp without creating an account?

yes

### Are dapp funds non-custodial?

yes

### Do you offer community support?

yes

### Describe any geographical restrictions on usage of your dapp

no

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by minimalsm** [comment]
Hi @xbankingorg,

Looks like you want us to list a staking product. [Please fill out this issue](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&projects=&template=suggest_staking_product.yaml&title=Suggest+a+staking+product+or+service), as we need more information related to staking products.

Will close this out in favour of the correct issue template, but feel free to reopen if I've misunderstood.

**Comment by Inatiye33** [comment]
> ### Name
> XBANKING
> 
> ### Description
> Non-custodial staking provider.
> 
> ### Logo
> ![400400](https://user-images.githubusercontent.com/126655346/261632791-3bd3218f-c75a-485c-9625-dc5a3a17d4a0.png)
> 
> ### Brand color
> 000000
> 
> ### Is your dapp open source?
> No
> 
> ### If open source, what is the repo for the dapp?
> _No response_
> 
> ### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible
> The security of our solutions comes first
> 
> Check out our software and technology solutions to secure and monitor the entire XBANKING ecosystem
> 
> **Cloud Datacenter** Amazon AWS. Google Cloud. Private Datacenter. Tier III and IV Datacenter. All levels of redundancy.
> 
> **Security** Front-end Firewall. Back-end Firewall. DDoS protection. Hardening Server Security. Low latency with High Performance VPN. AS Carrier/ISP. Full Layer7 inspection. IPS/IDS. No incoming connections. KMS/HSM hardware.
> 
> **Monitoring** Datacenter, Hardware and Virtual Machine are monitored and alarmed. Blockchain monitoring systems such as 'out of sync' and missing signatures. Hourly reports. Real-time alarms. 24/7 monitoring.
> 
> ### Can a user access the dapp without creating an account?
> yes
> 
> ### Are dapp funds non-custodial?
> yes
> 
> ### Do you offer community support?
> yes
> 
> ### Describe any geographical restrictions on usage of your dapp
> no
> 
> ### Would you like to work on this issue?
> * [ ]  Yes
> * [x]  No

**Comment by Inatiye33** [comment]
Yes
