### ISSUE TITLE
Bug report (Two broken links)

### ISSUE THREAD

**Issue by Omsify** [ethereum/ethereum-org-website#10972]
### Describe the bug

Two links on the [block proposal](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/block-proposal/) are broken. (PREREQUISITES section)

https://github.com/ethereum/ethereum-org-website/blob/4ed6e8faf32cfb2737e1310eda8cf40e339b974e/src/content/developers/docs/consensus-mechanisms/pos/block-proposal/index.md?plain=1#L11

### To reproduce

1. Go to 'block proposal page'
2. Scroll down to 'PREREQUISITES section'
3. Click on 'any of the links in the PREREQUISITES section'

### Expected behavior

A correct page should open

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Omsify** [comment]
Seems that these links forward me to a strange URL: 
`https://ethereum.org/ensrc/content/developers/docs/consensus-mechanisms/pos/`
Notice the **ensrc** not being separated with a slash here.

**Comment by corwintines** [comment]
Apologies for missing this issue when reviewing @Omsify and not assigning it to you. I really appreciate you calling this out and creating this issue. Will try and be more on top of this in the future and assingn to you for the PR.

@all-contributors can you add @Omsify for bug
