### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Eikix** [ethereum/ethereum-org-website#10983]
### Describe the bug

Typo on https://ethereum.org/en/developers/tutorials/yellow-paper-evm/#91-basics (I think the stack should be 1024 items, not bytes)

Written:
```The maximum size of the stack is 1024 bytes```

Correction:
```The maximum size of the stack is 1024 items, each of size 256 bits```

Note:
If Stack is of size 1024 bytes, then it can only store up to 32 items at a time. Which is contrarian to https://www.evm.codes/about#stack :
```
The stack currently has a maximum limit of 1024 values. 
```

### To reproduce

1. Go to https://ethereum.org/en/developers/tutorials/yellow-paper-evm/#91-basics
2. Click on search "1024 bytes"
3. See error

### Expected behavior

I think the stack should be 1024 items, not 1024 bytes

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Momentmagic** [comment]
@Eikix You made a good point and i guess a solution should be provided for this

**Comment by Eikix** [comment]
Opened https://github.com/ethereum/ethereum-org-website/pull/10984 in case
