### ISSUE TITLE
Lambda functions in staging not working

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#10990]
### Describe the bug

Any lambda function getting data in the staging environment is failing to work

### To reproduce

1. Go to https://ethereumorgwebsitestaging.gatsbyjs.io/en/
2. Scroll down to stats grid, or community events and see the error

### Expected behavior

Should be able to do lamda calls in staging

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by im-spiETH** [comment]
> ### Describe the bug
> Any lambda function getting data in the staging environment is failing to work
> 
> ### To reproduce
> 1. Go to https://ethereumorgwebsitestaging.gatsbyjs.io/en/
> 2. Scroll down to stats grid, or community events and see the error
> 
> ### Expected behavior
> Should be able to do lamda calls in staging
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Would you like to work on this issue?
> * [x]  Yes
> * [ ]  No

**Comment by pettinarip** [comment]
Fixed.
