### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by zdeadex** [ethereum/ethereum-org-website#10996]
### Wallet name

XDEFI

### Wallet description

XDEFI is a multichain all in one wallet supporting UTXO's (Bitcoin, Dogecoin, Litecoin...), EVM's (Ethereum, Polygon, Avalanche...), Cosmos (Cosmos Hub, Osmosis, Kava, Crypto org..), Solana, Near and more ecosystems.
Interesting features: NFT's, customs RPC's, swap in wallet from any chains to any tokens, staking...

### Wallet logo

<svg width="100%" height="100%" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M0 6.39161C0 2.86162 2.86162 0 6.39161 0H25.6084C29.1384 0 32 2.86162 32 6.39161V25.6084C32 29.1384 29.1384 32 25.6084 32H6.39161C2.86162 32 0 29.1384 0 25.6084V6.39161Z"
        fill="url(#paint0_linear_5147_39366)"
      />
      <path
        d="M17.9111 17.198C16.4278 18.1222 14.4423 18.5981 12.4314 18.4964C10.7408 18.4133 9.35416 17.8033 8.51574 16.8006C7.77866 15.9042 7.49304 14.7213 7.68652 13.3604C7.7521 12.9082 7.88649 12.4687 8.08501 12.0574L8.11265 11.9996C8.80858 10.6557 9.8414 9.51667 11.1094 8.69468C12.3775 7.87269 13.8371 7.39605 15.3445 7.31166C16.852 7.22728 18.3553 7.53807 19.7067 8.21343C21.0581 8.88879 22.2108 9.90546 23.0515 11.1634C23.8922 12.4213 24.3919 13.8771 24.5013 15.3875C24.6108 16.898 24.3263 18.4109 23.6758 19.7776C23.0253 21.1442 22.0312 22.3174 20.7915 23.1817C19.5517 24.046 18.1089 24.5716 16.6051 24.7068L16.6973 25.7673C18.3856 25.6164 20.0057 25.027 21.3979 24.057C22.79 23.0871 23.9062 21.7701 24.6366 20.2358C25.3669 18.7015 25.6861 17.0028 25.5628 15.3071C25.4395 13.6114 24.8779 11.9771 23.9334 10.5653C22.9888 9.15357 21.6939 8.01297 20.1761 7.25591C18.6584 6.49886 16.9702 6.15146 15.2779 6.24795C13.5856 6.34444 11.9475 6.88149 10.5251 7.80618C9.10267 8.73087 7.94494 10.0113 7.16597 11.5214L7.12911 11.5976C6.88285 12.1081 6.71659 12.6536 6.63619 13.2149C6.40586 14.8737 6.76288 16.3501 7.69574 17.4868C8.71613 18.7298 10.3769 19.4691 12.3693 19.5662C14.7947 19.6886 17.2063 19.0255 18.9177 17.8056L17.9111 17.198Z"
        fill="white"
      />
      <path
        d="M19.9398 18.4041C18.9746 19.245 16.7312 20.7699 13.0089 20.9778C8.84216 21.2089 7.10542 19.8504 7.0893 19.8365L6.75301 20.2524L7.0916 19.8434L6.41211 20.6613C6.48582 20.7237 8.15114 22.073 12.0623 22.073C12.3824 22.073 12.7187 22.073 13.0688 22.0452C17.5673 21.7934 20.0388 19.8249 20.9003 18.984L19.9398 18.4041Z"
        fill="white"
      />
      <path
        d="M21.7454 19.5039C21.1748 20.2563 20.4723 20.8983 19.6724 21.3984C16.8531 23.2236 13.2668 23.4593 10.7561 23.3322L10.7031 24.3973C11.1246 24.4181 11.53 24.4273 11.9239 24.4273C19.0044 24.4273 21.8652 21.1928 22.6645 20.0376L21.7431 19.4946"
        fill="white"
      />
      <path
        d="M21.4768 15.4712C21.9462 15.4712 22.3267 15.0895 22.3267 14.6187C22.3267 14.1479 21.9462 13.7662 21.4768 13.7662C21.0075 13.7662 20.627 14.1479 20.627 14.6187C20.627 15.0895 21.0075 15.4712 21.4768 15.4712Z"
        fill="white"
      />
      <defs>
        <linearGradient
          id="paint0_linear_5147_39366"
          x1="13.7762"
          y1="-3.85649"
          x2="-11.5874"
          y2="19.3182"
          gradientUnits="userSpaceOnUse"
        >
          <stop stop-color="#4476F2" />
          <stop offset="1" stop-color="#2041E0" />
        </linearGradient>
      </defs>
</svg>

![Square](https://github.com/ethereum/ethereum-org-website/assets/51711900/e9297ef2-0276-4387-bf92-eba91f24a745)
![Square](https://github.com/ethereum/ethereum-org-website/assets/51711900/66bb2a2d-474c-4114-9de4-d1624123b525)
![Square](https://github.com/ethereum/ethereum-org-website/assets/51711900/b2936191-8956-4fd1-a289-928c962d2838)

### Background color for brand logo

#2041E0

### URL to the project

https://www.xdefi.io

### When did the wallet go live to users?

12/10/2021

### Does the wallet have an active development team?

https://github.com/XDeFi-tech (but most of the code is atm closed source)

### Is the wallet globally accessible?

globaly accessible

### Is the wallet available in multiple languages?

English German French Russian

### What social links are there for the project?

https://twitter.com/xdefi_wallet
https://discord.gg/xdefiwallet
https://t.me/xdefi_announcements

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Before end of the year (both)

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes
Chrome, Brave, Opera, Edge, Cot Cot

### Is it a hardware wallet?

We support both hot and hardware wallet (Ledger and Trezor support)

### Is the source code for the wallet fully open-source?

No

### What license is the wallet software released under?

standard copyright for now

### Who holds the private keys?

 stocked encrypted at rest, so in user device
Recap:
- Company does not have access to it
- Users can have access and retrieve them

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://docs.xdefi.io/xdefi-wallet-v2-draft/general/security
https://docs.xdefi.io/xdefi-wallet-v2-draft/general/bug-bounty-program

### Has the wallet's smart contract code or security modules been audited?

https://www.xdefi.io/wp-content/uploads/2021/07/XDEFI_Audit_Report_Kudelski.pdf

### Scam protection?

Will be released before EOY

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes, https://www.xdefi.io/article/change-rpc-urls/

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, https://www.xdefi.io/fr/article/connecter-dapps/

### Does the wallet support staking directly?

Before Q4

### Does the wallet support swaps directly?

Yes, https://docs.xdefi.io/xdefi-wallet-v2-draft/key-features/swap-and-bridge & https://docs.xdefi.io/xdefi-wallet-v2-draft/general/routing

### Does the wallet support multi-chain networks?

Yes, https://docs.xdefi.io/xdefi-wallet-v2-draft/general/blockchains

### Does the wallet support Ethereum layer 2 networks?

Yes, in a month: https://twitter.com/xdefi_wallet/status/1694265719792525531

### Does the wallet allow the user to customize gas fees?

Yes, editable and ape mode https://twitter.com/xdefi_wallet/status/1447927332673576969?lang=fr

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes for Ethereum and Polygon

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, we use Onramp

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

@Zdeadex on both Telegram, Discord or Twitter

### Does the wallet have a dedicated support team?

Yes we have people managing support on few channels:
Intercom-Fin widget on website (https://xdefi.io/) + Intercom-Fin widget on web app (https://app.xdefi.io/) + Discord help desk (https://discord.gg/xdefiwallet)
We also have support on our webstore for extension: https://chrome.google.com/webstore/detail/xdefi-wallet/hmeobnfnfcmdkdcmlblgagmfpfboieaf?hl=en&authuser=0

### What educational resources/documentation do you provide to users?

https://www.xdefi.io/support/ for general support and education
https://docs.xdefi.io/xdefi-wallet-v2-draft/technical-docs/extension-integration developers integration

### Would you like to work on this issue?

- [ ] Yes
- [ ] No
```[tasklist]
### Tasks
```

**Comment by kritik-sah** [comment]
is this done?, I would like to take this.

**Comment by zdeadex** [comment]
> is this done?, I would like to take this.

What do you mean by done?

**Comment by zdeadex** [comment]
@kritik-sah you can take it

**Comment by kritik-sah** [comment]
please confirm the details 
```
{
    last_updated: "2023-08-29",
    name: "XDEFI Wallet",
    image_name: "XDEFI",
    brand_color: "#2041E0",
    url: "https://www.xdefi.io",
    wallet_live_date: "2021-10-12",
    active_development_team: true,
    languages_supported: ["en", "fr", "de", "ru"],
    twitter: "https://twitter.com/xdefi_wallet",
    discord: "https://discord.gg/xdefiwallet",
    reddit: "",
    telegram: "https://t.me/xdefi_announcements",
    ios: false,
    android: false,
    linux: false,
    windows: false,
    macOS: false,
    firefox: true,
    chromium: true,
    hardware: false,
    open_source: false,
    repo_url: "",
    non_custodial: true,
    security_audit: ["https://www.xdefi.io/wp-content/uploads/2021/07/XDEFI_Audit_Report_Kudelski.pdf"],
    scam_protection: false,
    hardware_support: true,
    walletconnect: true,
    rpc_importing: true,
    nft_support: true,
    connect_to_dapps: true,
    staking: false,
    swaps: true,
    multichain: true,
    layer_2: false,
    gas_fee_customization: true,
    ens_support: true,
    erc_20_support: true,
    eip_1559_support: true,
    buy_crypto: true,
    withdraw_crypto: false,
    multisig: false,
    social_recovery: false,
    onboard_documentation: "https://www.xdefi.io/support/",
    documentation: "https://docs.xdefi.io/xdefi-wallet-v2-draft/technical-docs/extension-integration",
  },
```

**Comment by zdeadex** [comment]
> please confirm the details
> 
> ```
> {
>     last_updated: "2023-08-29",
>     name: "XDEFI Wallet",
>     image_name: "XDEFI",
>     brand_color: "#2041E0",
>     url: "https://www.xdefi.io",
>     wallet_live_date: "2021-10-12",
>     active_development_team: true,
>     languages_supported: ["en", "fr", "de", "ru"],
>     twitter: "https://twitter.com/xdefi_wallet",
>     discord: "https://discord.gg/xdefiwallet",
>     reddit: "",
>     telegram: "https://t.me/xdefi_announcements",
>     ios: false,
>     android: false,
>     linux: false,
>     windows: false,
>     macOS: false,
>     firefox: true,
>     chromium: true,
>     hardware: false,
>     open_source: false,
>     repo_url: "",
>     non_custodial: true,
>     security_audit: ["https://www.xdefi.io/wp-content/uploads/2021/07/XDEFI_Audit_Report_Kudelski.pdf"],
>     scam_protection: false,
>     hardware_support: true,
>     walletconnect: true,
>     rpc_importing: true,
>     nft_support: true,
>     connect_to_dapps: true,
>     staking: false,
>     swaps: true,
>     multichain: true,
>     layer_2: false,
>     gas_fee_customization: true,
>     ens_support: true,
>     erc_20_support: true,
>     eip_1559_support: true,
>     buy_crypto: true,
>     withdraw_crypto: false,
>     multisig: false,
>     social_recovery: false,
>     onboard_documentation: "https://www.xdefi.io/support/",
>     documentation: "https://docs.xdefi.io/xdefi-wallet-v2-draft/technical-docs/extension-integration",
>   },
> ```

Hi, probably two changes:
    layer_2: true,
    firefox: false,

For layer 2 we already support Arbitrum, Optimism

**Comment by zdeadex** [comment]
Hi @corwintines can we change the discord link associated there? It should be now

` 
discord: "https://discord.gg/xdefi",
`

The other one is compromised unfortunately.
