### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by blazingrome** [ethereum/ethereum-org-website#10992]
### Describe the bug

/developers/docs/networks/ page has a broken link that needs removal: https://faucet.sepolia.dev/

### To reproduce

1. Go to '[...](https://ethereum.org/en/developers/docs/networks/)' (Release candidate v7.19.2)
2. Scroll down to 'Faucets'
3. Click on '[Sepolia faucet(opens in a new tab)](https://faucet.sepolia.dev/)'

### Expected behavior

Faucet should be working.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by blazingrome** [comment]
Created a pull request by direct edit.

**Comment by blazingrome** [comment]
Closing as there's an active PR: https://github.com/ethereum/ethereum-org-website/pull/11012

**Comment by wackerow** [comment]
Closed with #11012, thanks folks!
