### ISSUE TITLE
Suggest a DeSci project

### ISSUE THREAD

**Issue by MohamedFekryyy** [ethereum/ethereum-org-website#11003]
### Name

ScieNFT

### Description

ScieNFT is an open-access preprint server where researchers can share scientific assets on the blockchain, and a digital collectibles marketplace where science enthusiasts can trade these assets using NFT technology.

### Logo

![logo-on-dark](https://github.com/ethereum/ethereum-org-website/assets/36033065/2cb8daac-b719-42b8-95d8-264b8008cda8)
![logo-on-light](https://github.com/ethereum/ethereum-org-website/assets/36033065/bc13af5a-f13c-4579-bcfe-f909a272b9bf)

### Brand color

#FF6B3B

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/ScieNFT/contracts

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

https://scienft.github.io/contracts/metrics/

### Can a user access the dapp without creating an account?

Users must create an account with an email address to accommodate the community of scientists who may not be fully accustomed to blockchain processes.

### Are dapp funds non-custodial?

Yes.

### Do you offer community support?

We use [Telegram](https://t.me/ScieNFT) for community support, as well as intercom 1:1 chat with our team.

### Describe any geographical restrictions on usage of your dapp

ScieNFT is available globally.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Hey @MohamedFekryyy, thanks for opening the issue. Unfortunately, this product is not on Ethereum so we wouldn't list it per [our product listing](https://ethereum.org/en/contributing/adding-desci-projects/).

Please do open another issue if this changes ❤️

**Comment by minimalsm** [comment]
@all-contributors please add @MohamedFekryyy for ideas
