### ISSUE TITLE
Bug report / Issue Problem

### ISSUE THREAD

**Issue by fujiar10** [ethereum/ethereum-org-website#11011]
### Describe the bug

I see the main display on the word Eip-1 is not working 
Error : "Unable to open page due to server unavailability"
Error String: https://eip.ethereum.org/EIPS/eip-1
Fixed : https://eips.ethereum.org/EIPS/eip-1

### To reproduce

1. Go to ' https://ethereum.org/en/community/get-involved/#ethereum-jobs ‘
2. Click on ' Eip-1 ‘
3. See error

### Expected behavior

Expect to Fixed Primary Access on Web Hosting

### Screenshots

![D1F7D1FD-2FCF-4F3C-8845-292D46255014](https://github.com/ethereum/ethereum-org-website/assets/118127172/64eec870-4ae9-43f7-8951-37d48fef1757)

### Desktop (please complete the following information)

Safari

### Smartphone (please complete the following information)

Iphone 7+

### Additional context

“ Possible Writing error in the Eip section on the page “

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by ameeetgaikwad** [comment]
I would like to help!

**Comment by fujiar10** [comment]
> I would like to help!

Thank You

**Comment by Momentmagic** [comment]
@fujiar10 Are you able to fix your issues?

**Comment by fujiar10** [comment]
> @fujiar10 Are you able to fix your issues?

Hi ser already solved
