### ISSUE TITLE
Suggest an exchange - Ramp

### ISSUE THREAD

**Issue by dtojikulov** [ethereum/ethereum-org-website#11018]
### Exchange name

ramp

### Exchange description

Ramp is a global financial technology company building solutions aiming to connect the crypto economy with legacy financial infrastructure.

Since 2018, we’ve been building and improving our core on-ramp and off-ramp products to take web3 mainstream in a secure and compliant way.

With offices in the UK, US, and Poland, Ramp employs more than 160 people from all over the globe.

Leveraging the years of collective fintech experience of our team, we’re working together with a network of market-leading strategic partners, backers, and advocacy organizations to bring about meaningful change.

### What geographical restrictions apply to this exchange?

We do not operate in these countries.

|Country|
|-------|
|Bahrain|
|Egypt  |
|Eritrea|
|Bahamas|
|Benin  |
|Burkina Faso|
|Burundi|
|Gabon  |
|Guyana |
|Haiti  |
|Niger  |
|Tajikistan|
|Cameroon|
|Congo (DRC)|
|Malawi |
|American Samoa|
|French Southern Territories|
|HIMI   |
|British Indian Ocean Territory|
|Anguilla|
|Afghanistan|
|Algeria|
|Armenia|
|Aruba  |
|Azerbaijan|
|Bangladesh|
|Barbados|
|Bolivia|
|Cambodia|
|Central African Republic|
|China  |
|Jamaica|
|Japan  |
|Pakistan|
|Palestine|
|Saudi Arabia|
|Senegal|
|Tanzania|
|Tunisia|
|Western Sahara|
|Montserrat|
|SGSSI  |
|European Union|
|U.S. Minor Outlying Islands|
|Pitcairn|
|Saint Kitts and Nevis|
|Virgin Islands (U.S.)|
|Belarus|
|Cayman Islands|
|Cuba   |
|Curaçao|
|Ecuador|
|Fiji   |
|Guinea-Bissau|
|Indonesia|
|Iran   |
|Iraq   |
|Ivory Coast|
|Jordan |
|Kosovo |
|Kyrgyzstan|
|Lebanon|
|Lesotho|
|Liberia|
|Libya  |
|Macao  |
|Maldives|
|Mali   |
|Mauritius|
|Mongolia|
|Morocco|
|Myanmar|
|Namibia|
|Nepal  |
|Nicaragua|
|North Korea|
|Oman   |
|Palau  |
|Panama |
|Puerto Rico|
|Qatar  |
|Russia |
|Samoa  |
|Seychelles|
|Somalia|
|South Korea|
|South Sudan|
|Sudan  |
|Syria  |
|Taiwan |
|Trinidad and Tobago|
|Uganda |
|Vanuatu|
|Venezuela|
|Vietnam|
|Virgin Islands|
|Yemen  |
|Zimbabwe|

### Which currencies are accepted by this exchange?

All countries which are not listed in restrictions which I provided in the previous input.

### Do you have any proof that they're a legitimate company?
You can find more info [here](https://ramp.network/about)
![image](https://github.com/ethereum/ethereum-org-website/assets/63240495/03bd6019-7761-4165-8c98-0f9b5a460784)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Hey @dtojikulov, thanks for suggesting this.

I'm a little confused at categorising Ramp as a CEX. My understanding is that no funds are held on behalf of users by Ramp and you're an intermediary?

**Comment by wackerow** [comment]
Closing from inactivity
