### ISSUE TITLE
Suggest a wallet: ECHOOO

### ISSUE THREAD

**Issue by Alston333** [ethereum/ethereum-org-website#11034]
### Wallet name

ECHOOO

### Wallet description

The best next generation smart contract wallet powered by ERC-4337, combines MPC & AI technology

### Wallet logo

![LGO1](https://github.com/ethereum/ethereum-org-website/assets/121208805/1ab8c250-ddef-48b4-91da-e27bb89e6517)

### Background color for brand logo

1763FF

### URL to the project

www.echooo.xyz

### When did the wallet go live to users?

03.31.2023

### Does the wallet have an active development team?

https://github.com/HEchooo

### Is the wallet globally accessible?

The service is available worldwide except for mainland China

### Is the wallet available in multiple languages?

English and Traditional Chinese，more to come in future

### What social links are there for the project?

Twitter:https://twitter.com/echooo_wallet
Telegram group:https://t.me/Echooowallet
Discord:https://discord.gg/38REkgXBzR

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

IOS:https://apps.apple.com/us/app/echooo-wallet/id6446883725
Andriod:https://play.google.com/store/apps/details?id=com.smartwallet.app

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Nope

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Chromium:https://chrome.google.com/webstore/detail/echooo-wallet/lcmncloheoekhbmljjlhdlaobkedjbgd

### Is it a hardware wallet?

NO

### Is the source code for the wallet fully open-source?

https://github.com/HEchooo

### What license is the wallet software released under?

 MAS

### Who holds the private keys?

Users keep the private keys themself, Echooo is a fully decentralized wallet. Even if the company ceases to exist, users still have full control of their assets, and no one else can access them

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

[Smart Contract Audit - Echooo Wallet - 2nd Audit - v221229.pdf](https://github.com/ethereum/ethereum-org-website/files/12472334/Smart.Contract.Audit.-.Echooo.Wallet.-.2nd.Audit.-.v221229.pdf)

### Has the wallet's smart contract code or security modules been audited?

Above

### Scam protection?

Our wallet only offers native integration for high-quality DApps. When users access unknown websites or addresses, a warning will be displayed

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

no

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

connect wallet to dapp, in wallet browser

### Does the wallet support staking directly?

LIDO/Compound/AAVE

### Does the wallet support swaps directly?

Uniswap/Paraswap

### Does the wallet support multi-chain networks?

ETH/BSC/BTC

### Does the wallet support Ethereum layer 2 networks?

ZkSync/Arbitrum/POLYGON

### Does the wallet allow the user to customize gas fees?

YES

### Does the wallet support sending transactions to ENS addresses?

NO

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

YES，Users can add token from the mobile APP

### Does the wallet support EIP-1559 (type 2) transactions?

YES，All Supported

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

YES,We integrate Fatpay/Moonpay

### Does the wallet support withdrawals to fiat?

NO

### Is the wallet a multi-signature wallet?

YES，https://www.echooo.xyz/TechGuide

### Does the wallet support social recovery?

YES，https://www.echooo.xyz/TechGuide

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram:@linnannan
Mail:lnn@echooo.co

### Does the wallet have a dedicated support team?

https://linktr.ee/echooowallet?utm_source=linktree_admin_share
time:24X7 usually support in one day
mail:business@echooo.xyz

### What educational resources/documentation do you provide to users?

https://www.echooo.xyz/TechGuide

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Alston333** [comment]
@corwintines Sir plz check it

**Comment by wackerow** [comment]
Hey @Alston333! Apologies for delays here as we've been making some large changes over the past 9 months! Didn't intend to let this fall through the cracks.

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation!
