### ISSUE TITLE
Add Nepali language in language support

### ISSUE THREAD

**Issue by vivekjoshi-omni-pay** [ethereum/ethereum-org-website#11053]
### Is your feature request related to a problem? Please describe.

The absence of support for the Nepali language on the Ethereum website should not deter individuals from exploring the world of Web3 or Ethereum for the first time. While language barriers can be a challenge, it's important to emphasize that the Web3 and blockchain communities are global and inclusive, welcoming participants from diverse linguistic backgrounds. Developers may temporarily rely on third-party translator extensions to access essential information, but it is advisable for the Ethereum community to consider expanding language support to ensure accessibility and inclusivity for a wider audience, fostering greater participation and innovation within the ecosystem.

### Describe the solution you'd like

We can add "Nepali" as one of the many languages we support currently.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
https://ethereum.org/ne-np 🎉 

Further translation contributions can be made through Crowdin at https://crowdin.com/project/ethereum-org

Thanks!

**Comment by wackerow** [comment]
See here as well for more info on our Translation Program: https://ethereum.org/en/contributing/translation-program/
