### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by vbaranov** [ethereum/ethereum-org-website#11063]
### Dev tool name

Blockscout

### Dev tool description

Blockscout is the first fully-featured open-source blockchain explorer available for use by any Ethereum Virtual Machine (EVM) chain. Utilized by 200+ networks across the blockchain continuum, Blockscout gives everyone access to essential on-chain data, the ability to interact with smart contracts, and the tools to view and verify transactions quickly and easily.

### When did the dev tool go live?

2018

### Where do you think this page should be shown?

Blockscout links should be added to Mainnet, Goerli, Sepolia resources.

### Is the product open source?

Yes

### GitHub URL

https://github.com/blockscout

### Documentation URL

https://docs.blockscout.com/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by nkumawat34** [comment]
hey can i fix this issue....

**Comment by wackerow** [comment]
Closed with #11064
