### ISSUE TITLE
Update to Launchnodes listing (features)

### ISSUE THREAD

**Issue by andreilicious23** [ethereum/ethereum-org-website#11061]
Hi Paul (@wackerow). Based on the outcomes of https://github.com/ethereum/ethereum-org-website/issues/10637

Proposed changes for Launchnodes associated ticks on page: https://ethereum.org/en/staking/solo/

1. Open source - YES
2. Permissionless - YES
3. Multiclient - YES
4. Audited - YES (if AWS audit is accounted for)

**Comment by wackerow** [comment]
Hey @andreilicious23, this looks like a continuation of the issue you noted, #10637... let's keep the conversation over there if we could... going to close this and quote your comment from above
