### ISSUE TITLE
Update FoxWallet

### ISSUE THREAD

**Issue by Nuts444** [ethereum/ethereum-org-website#11071]
### Wallet name

FoxWallet

### Wallet description

 FoxWallet is a safe and easy-to-use decentralized multi-chain wallet, dedicated to creating an entrance and connection to the Web3 world.

### Wallet logo

![Head Portraits](https://github.com/ethereum/ethereum-org-website/assets/102349584/f759c9a1-5e80-40eb-b118-8adb08cdc7b8)

### Background color for brand logo

#000000

### URL to the project

https://foxwallet.com/en

### When did the wallet go live to users?

November 15, 2021

### Does the wallet have an active development team?

https://github.com/madfoxoO/FoxWallet#foxwallet

### Is the wallet globally accessible?

It is accessible everywhere, excluding China Mainland

### Is the wallet available in multiple languages?

English, Ukrainian, Russian, Spanish, Indonesian, Hindi, Turkish, UrduVietnamese, Chinese 

### What social links are there for the project?

[Website: https://foxwallet.com/en](Website: https://foxwallet.com/en)
[Twitter: https://twitter.com/FoxWallet](url)
[Telegram: https://t.me/FoxWallet_EN](url)
[Youtube: https://www.youtube.com/channel/UCt9O4HUkuNutXvFoN6NZh-w](url)
[Discord: https://discord.com/invite/JVjVbe3Zth](url)
[Medium: https://medium.com/@FoxWallet](url)
[Linkedin: https://www.linkedin.com/company/foxwallet/](url)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS: [https://apps.apple.com/app/foxwallet-crypto-web3/id1590983231](url)
Android: [https://foxwallet.com/download#:~:text=App%20Store-,Android,-Google%20Play](url)
Google Play:  [https://play.google.com/store/apps/details?id=com.foxwallet.play&pli=1](url)

### Who holds the private keys?

FoxWallet is a non-custodial wallet, hence, only users have access to their private keys. We do not store any mnemonics or private keys. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

FoxWallet collects blacklist addresses from multiple sources of information and issues a warning when users interact with addresses in the blacklist. At the same time, FoxWallet developers have other strategies to intelligently identify fraudulent types of tokens.

FoxWallet recognizes fraudulent behavior when signing transactions and issues a warning to users. At the same time, FoxWallet has an Approval management gadget where users can view which addresses they have authorized and can easily withdraw the authorization.

FoxWallet also has a special warning for the so-called 'blind signatures' caused by hackers trying to make users sell their NFTs for extremely low prices.

Further, FoxWallet has also cooperated with well-known security agencies in the industry to protect users from visiting phishing sites. Audit report: [https://play.google.com/store/apps/details?id=com.foxwallet.play&pli=1](https://www.certik.com/projects/fox-wallet)

Moreover, users can refer to our Security Tips via the following link: https://hc.foxwallet.com/docs/security-tips

### Has the wallet's smart contract code or security modules been audited?

https://www.certik.com/projects/fox-wallet

### Does the wallet have an internal security team?

Yes, FoxWallet indeed has a security team. Apart from the technicians fully-devoted to FoxWallet, we are also backed by a mining company. Hence, FoxWallet has the mining company's security team enhancing the work as well. 

### Scam protection?

FoxWallet collects blacklist addresses from multiple sources of information and issues a warning when users interact with addresses in the blacklist. At the same time, FoxWallet developers have other strategies to intelligently identify fraudulent types of tokens.

FoxWallet recognizes fraudulent behavior when signing transactions and issues a warning to users. At the same time, FoxWallet has an Approval management gadget where users can view which addresses they have authorized and can easily withdraw the authorization.

FoxWallet also has a special warning for the so-called 'blind signatures' caused by hackers trying to make users sell their NFTs for extremely low prices.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

https://hc.foxwallet.com/docs/ethereum-advance/

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

https://hc.foxwallet.com/docs/ethereum-advance/add-custom-rpc

### Does the wallet support swaps directly?

Yes

### Does the wallet support multi-chain networks?

FoxWallet has supported over 45 different chains and networks. Here is documentation on some of them: https://hc.foxwallet.com/docs/ethereum-advance/. 

### Does the wallet support Ethereum layer 2 networks?

https://hc.foxwallet.com/docs/dapp/zksync-v2-testnet; https://hc.foxwallet.com/docs/ethereum-advance/arbitrum; https://hc.foxwallet.com/docs/ethereum-advance/boba; https://hc.foxwallet.com/docs/ethereum-advance/optimism

### Does the wallet allow the user to customize gas fees?

https://hc.foxwallet.com/docs/speed-up-or-cancel-tx

### Does the wallet support sending transactions to ENS addresses?

https://hc.foxwallet.com/docs/manage-funds

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

https://hc.foxwallet.com/docs/erc20-usage

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, FoxWallet supports both types.  EIP1559 consists of gasLimit, baseFee and priorityFee, in which baseFee + priorityFee is equivalent to previous gasPrice. But baseFee * gasLimit will be destroyed and only priorityFee * gasLimit will be owned by the miners, which makes it a preferable choice for the users, hence, for FoxWallet too. 

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes. Currently, FoxWallet has integrated Moonpay, Banxa, Topper and Onramp. 

### Who can the ethereum.org team can contact regarding the wallet in future?

Natalie, CBO 
Telegram: @natalie_yev 
Email: nataliey@foxwallet.com

### Does the wallet have a dedicated support team?

There's a support channel on our Discord: https://discord.com/invite/JVjVbe3Zth. Also, users can always send a message though our Twitter https://twitter.com/FoxWallet where we always make sure to attend to any issues. 

### What educational resources/documentation do you provide to users?

[https://hc.foxwallet.com/docs/](url)

### Does the wallet have any integrated tools not mentioned above?

Invite Feature [https://hc.foxwallet.com/docs/fox-credit](url)
Fox Credit Feature [https://hc.foxwallet.com/docs/fox-credit](url)
Bookmarks [https://hc.foxwallet.com/docs/basic/bookmark](url)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @Nuts444! Sincere apologies for the delays here as we've been working through a backlog.

Trying to figure out the best way to go about this since we're just updating information here... We have a recently updated template for the wallet information we're requiring on any listing going forward and have begun reaching out to existing listings to request updated information.

Out [latest wallet issue form](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) has some changes, so I'll highlight the differences here:

- Wallet accounts: Externally owned accounts, account abstraction, or smart contract?
- What are the fees users may be paying for using your wallet product? eg) 1% service fee for swapping, bridging functionality, flat fee for all transactions
- Does the wallet support bridging directly? Please provide documentation on bridging.
- Does the wallet have any recovery options? Please provide any information on any recovery options for your wallet
- Does the wallet support bundled transactions? Please provide any documentation on bundled transactions

I see you checked "Yes" to wanting to work on this... Would you mind providing answers to the above required questions, then we can move forward with a PR. Are you still interested in working on this?

**Comment by corwintines** [comment]
Going to close this out for now with the new issue template for wallet listings. 

@Nuts444 as mentioned, apologies for the delay on this and the inconvenience of the new template. It is largely the same, but with a few new questions we require. Will keep an eye out for a new submission to review :)
