### ISSUE TITLE
Suggest ETH Riyadh 2023

### ISSUE THREAD

**Issue by wufengtao1** [ethereum/ethereum-org-website#11072]
Dear [Ethereum.org](http://ethereum.org/),

My name is Cavin, and I serve as the Ecosystem Manager for [ChainIDE](https://twitter.com/ChainIDE), a cloud-based multichain IDE that has been listed on official [Ethereum developer tools](https://ethereum.org/en/developers/learning-tools/).

ChainIDE is teaming up with other committees (such as Tharawat Technology, Mask Network, etc.) to hold ETH Riyadh 2023, which has been submitted in our latest PR on Github: https://github.com/ethereum/ethereum-org-website/pull/10963. 

I am reaching out to kindly request your support in listing ETH Riyadh 2023 on Ethereum Events https://ethereum.org/en/community/events/ 

ETH Riyadh will unite developers and builders from Saudi Arabia and the other Middle East regions, nurturing their roles and connections in the Ethereum ecosystem. 

We have obtained the support of the Saudi Arabian Ministry of Communication and Info Telecom, and the Minister of Communications will also be attending the event conference.

We believe that listing ETH Riyadh 2023 on the Ethereum website would greatly benefit the Ethereum community, providing a valuable resource for enthusiasts and professionals seeking to stay updated on the latest developments and events in the space.

The event will be held from September 18 to October 12, 2023, featuring three parts: 
Online Bootcamp & Competition, Sept. 18 - 29, 2023
In-Person Reception & Conference, Oct. 10 - 11, 2023
Online Closing Mixer, Oct. 12, 2023
For more details, please check: https://ethriyadh.com/

Please do not hesitate to reach out to us for any additional information or clarification.

Thank you for your time and consideration. 

Best Regards,
Cavin
Ecosystem Manager
ChainIDE

**Comment by corwintines** [comment]
Closing this out as PR has been merged

**Comment by wufengtao1** [comment]
@corwintines 
Thank you very much. There might be another unrelated PR that we would appreciate your review on. ChainIDE is a free, multi-chain cloud-powered development platform, and we have recently launched Code Sage. Could you please review this PR as well? We believe that ChainIDE can help more developers get involved with Ethereum.  https://github.com/ethereum/ethereum-org-website/pull/10962
