### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by kalpitf1** [ethereum/ethereum-org-website#11088]
### Describe the bug

Typo on https://ethereum.org/en/developers/docs/nodes-and-clients/#full-node

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/nodes-and-clients/#full-node
2. See typo under subtitle Full node, first paragraph, second sentence.

### Expected behavior

The sentence currently is:
`There are different classes of full node - some start from the genesis block and verify every single block in the entie history of the blockchain.`

Suggested fix:
`There are different classes of full node - some start from the genesis block and verify every single block in the entire history of the blockchain.`

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by HiroyukiNaito** [comment]
It is fixed right now. Please close the issue.
