### ISSUE TITLE
Request to list article and video reference

### ISSUE THREAD

**Issue by PaigeDAO** [ethereum/ethereum-org-website#11091]
### Is your feature request related to a problem? Please describe.

Add to further DeSci Reading - highlighting the entire ecosystem of builders including female founders of DeSci DAOs (I am the first with the founding of FrontierDAO) 

I'd like to add this explanation of DeSci to the further reading section of the DeSci page. It is written for general audiences rather than specialized blockchain-literate or science audiences. As DeSci (and Open Science) gain traction, I feel it's important to be inclusive in our language and messaging, too.

### Describe the solution you'd like

This  is primarily an audio piece. The accompanying article is just a brief summary of DeSci and the contents of the audio. The piece focuses on blockchain tooling for scientific publishing.  When this was published, over a year ago, my protocol build, Frontier Registry, was the first of its kind in scientific publishing. Today there are several very similar projects released by billionaires and ivy Leagues.  
Frontier Registry remains the first IP NFT minted on-chain.  Other orgs (like Molecule) take credit for being the first to create an IP NFT but to date they cannot demonstrate that distinction by producing an artifact earlier than my IP NFT of Frontier Registry minted HERE: 
https://opensea.io/collection/frontier-registry-desci

Describe the solution you'd like
Please add this link to Further Reading Section on DeSci:
[​https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/](https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/) by Paige Donner

And this entry, too, please. 
https://www.youtube.com/watch?v=nC-2QWQ-lgw&t=17s

Describe alternatives you've considered
I suppose the alternative is to continue to leave out this more inclusive messaging about DeSci. It is a shame to call ourselves decentralized but mimic the past transgressions of leaving out worthy voices and contributions from underrepresented groups.

### Describe alternatives you've considered

Describe the solution you'd like

I would like to see more inclusion and recognition of our entire DeSci ecosystem in these pages.  There is a huge diversity of participants who have pioneered this movement, including myself who happens to be a woman.  I really don't see how we can call ourselves 'decentralized' if the same people and the same names keep being highlighted for recognition and credit for things that, in many cases, other people have done first.  In my understanding decentralized means the opposite of centralized. Please correct me if I'm mistaken in this definition? 

Please add this link to Further Reading Section on DeSci:

https://opensea.io/collection/frontier-registry-desci

[​https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/](https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/) by Paige Donner

### Additional context

Paige Donner is the first female founder of a science focused DAO, FrontierDAO. 
She was a featured speaker at ETHCC (6) where she presented on [Tooling Open Science with Web3 and Blockchain](https://www.youtube.com/watch?v=nC-2QWQ-lgw&t=17s). 

She is active with NGOs such as UNESCO in Open Science initiatives as well as with government agencies such as NASA TOPS . 
Find more here:
youtube.com/@frontierdao 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by PaigeDAO** [comment]
Hello @corwintines   I re-opened the issue with additional context.  Thank you

**Comment by wackerow** [comment]
>Please add this link to Further Reading Section on DeSci:
[​https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/](https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/) by Paige Donner

>And this entry, too, please.
https://www.youtube.com/watch?v=nC-2QWQ-lgw&t=17s

Hey @PaigeDAO! Apologies for the delays here. Welcome a PR here if you'd still like to add these.

**Comment by PaigeDAO** [comment]
Hi @wackerow Thank you for surfacing these.

**Comment by PaigeDAO** [comment]
![2024-06-14](https://github.com/ethereum/ethereum-org-website/assets/102079668/aad54e3f-2578-4072-a1aa-e7a46cad0475)
Hello @wackerow  I just tried to do this PR but was blocked as 'not a collaborator' 
Would you please specify the branch etc?   Thanks Kindly -

**Comment by wackerow** [comment]
@PaigeDAO You'll need to make your own fork first. Looks like you're trying to merge our `master` branch into `dev` which is not what we want... as a contributor, you can't write directly to the `ethereum/ethereum-org-website` repo branches; you'll need your own fork/branch and then target the `dev` branch of this repo.

https://github.com/ethereum/ethereum-org-website/ Go here first and click "Fork" at the top first. This makes a copy of the entire repo under ownership of your account... then you can make your changes (recommend you make a new branch from `dev` first, but not strictly required) and commit them. Then you'll make a pull request for that branch (under your ownership/repo) and target the canonical `dev` branch (`ethereum/ethereum-org-website` repo).

**Comment by wackerow** [comment]
Hey @PaigeDAO! I'm putting up a PR to address this now. I'm not sure the OpenSea link is appropriate for here, but please feel free to provide some more info if you disagree. Will put up a change to add the article and youtube links!

**Comment by PaigeDAO** [comment]
Thank you kindly!
