### ISSUE TITLE
Content request: Optimium

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#11105]
### Is your feature request related to a problem? Please describe.

We have a page written for [validums](https://ethereum.org/en/developers/docs/scaling/validium/) which are blockchain networks that post state changes to Ethereum, but data availability is handled off chain in regards to Ethereum. These use validity proofs like zero knowledge rollups, but key difference being the data availability aspect. 

Optimium (name taken from L2BEAT), is the equivalent to optimistic rollups as validiums are to zk-rollups. Their state changes are posted to Ethereum, but data availability is handled elsewhere in regards to Ethereum.

We currently have a page on Validiums, but don't have a page going into Optimium's. 

### Describe the solution you'd like

Context is above, but would like a page similar to the [validium](https://ethereum.org/en/developers/docs/scaling/validium/) page on Optimium

### Describe alternatives you've considered

Don't have this information

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by F3n4nd0gm** [comment]
![IMG_20231014_163218_313.jpg](https://github.com/ethereum/ethereum-org-website/assets/147960298/1f679ff9-cf89-4846-9a06-5e629b3cb48d)

**Comment by F3n4nd0gm** [comment]
Robaron mis cuentas y mi github y cabiaron las contraseñas de las cuentas y borraron internet-star.net

**Comment by emmanuel-awosika** [comment]
@corwintines: You can this issue to me on GitHub so it's easy to track progress.

**Comment by corwintines** [comment]
Closing in favor of Emmanuels issue that is open.
