### ISSUE TITLE
Add DApp World to /developers/learning-tools

### ISSUE THREAD

**Issue by DApp-World** [ethereum/ethereum-org-website#11102]
I would like to propose the inclusion of the DApp World platform in Ethereum's list of LEARN BY DOING developer resources. DApp World is a dynamic platform backed by Ah! Ventures dedicated to empowering blockchain developers with practical tools and resources.

Key Sections of DApp World:

1. **Solidity Problems**:
 DApp World offers a unique Solidity problem-solving section, akin to platforms like LeetCode and CodeChef. Developers can test and enhance their smart contract development skills by solving a range of challenging problems.
Example Problem: [DAO Membership](https://dapp-world.com/problem/dao-membership-hard/problem)

3. **Contests**:
In this section, Ethereum developers can participate in contests that provide invaluable opportunities. They can collaborate with top blockchain industry mentors and even secure job/internship offers from leading blockchain companies by solving real-world Solidity challenges and competing against their peers.
Example Contest: [Super Mentors 2.0](https://dapp-world.com/contests/contest-4)

4. **Blockchain Courses**:
DApp World offers practical blockchain courses where developers learn by doing. These courses provide hands-on experience, allowing developers to grasp concepts and apply them immediately.
Each course module includes interactive problem statements that developers can solve using the platform's built-in code editor.
Example Course: [Introduction to solidity](https://dapp-world.com/course/introduction-to-solidity-Ynws)

5. Soul:
DApp World utilizes the Ethereum blockchain to maintain transparent and trustable developer profiles. Every interaction on the platform is recorded in a developer's Soul Bound Token (SBT) on the Ethereum network.
Developers earn medals and achievements as they progress, making learning an engaging and rewarding experience.
Example Soul: [@bepossible](https://dapp-world.com/soul/bepossible)

I believe that DApp World's commitment to practical blockchain education aligns well with Ethereum's mission. By including DApp World in your resources list, Ethereum can further support developers in gaining expertise and contributing to the blockchain ecosystem.

You can explore [DApp World](https://dapp-world.com).

Thank you for considering this request, and I look forward to your response.

**Comment by wackerow** [comment]
Thanks @DApp-World! Apologies for delays getting back to you. This looks cool... welcome a PR to add this to the `/developers/learning-tools` page.. Were you thinking under "Code sandboxes" or "Developer bootcamps"?

Will open this up to the community for anyone who'd like to work on it, fcfs.

**Comment by tomasgrusz** [comment]
Happy to pick this up!

**Comment by DApp-World** [comment]
Thanks @wackerow and no worries! Adding DAppWorld under "Code sandboxes" seems good. 
Let me know if anything else is needed, happy to help!

**Comment by wackerow** [comment]
Thanks folks! @tomasgrusz Have assigned you 🙏
