### ISSUE TITLE
Suggest a wallet: BitBox02

### ISSUE THREAD

**Issue by jadzeidan** [ethereum/ethereum-org-website#11103]
### Wallet name

BitBox02

### Wallet description

The BitBox02 hardware wallet equips individuals to easily store, protect, and transact cryptocurrencies. Simple and secure, it is a great solution for beginners: the companion BitBoxApp guides new users through every step and setting up the BitBox02 takes less than two minutes, backup to the microSD card included.

### Wallet logo

![BitBox_icon](https://github.com/ethereum/ethereum-org-website/assets/42831937/b0450231-dcfd-49e7-8cac-186ed698a0e2)

### Background color for brand logo

#F5F5F5

### URL to the project

https://bitbox.swiss/

### When did the wallet go live to users?

2019

### Does the wallet have an active development team?

https://github.com/digitalbitbox

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English, German, French, Arabic, Hebrew, Hindi, Italian, Japanese, Malay, Persian, Portuguese, Russian, Slovenian, Spanish, Turkish, Bulgarian and Chinese.

### What social links are there for the project?

https://twitter.com/BitBoxSwiss
https://www.instagram.com/bitboxswiss/
https://www.facebook.com/BitBoxSwiss
https://www.linkedin.com/company/bitbox-swiss

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Android:
https://play.google.com/store/apps/details?id=ch.shiftcrypto.bitboxapp&utm_source=website&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Windows, macOS and Linux:
https://bitbox.swiss/download/

### Is it a hardware wallet?

Yes, USB

### Is the source code for the wallet fully open-source?

https://github.com/digitalbitbox

### What license is the wallet software released under?

Apache License

### Who holds the private keys?

The user has complete control over their private keys. No one else has access. This is fully self custody.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Open source firmware:
https://github.com/digitalbitbox/bitbox02-firmware

Firmware is reproducible, 3rd party audited:
https://walletscrutiny.com/hardware/bitBox2/

Bug bounty program:
https://bitbox.swiss/bug-bounty-program/

Signatures from the community asserting the correctness of our releases:
https://github.com/digitalbitbox/bitbox02-firmware/tree/master/releases#contribute-your-signature

Explanation of Dual chip architecture security architecture:
https://bitbox.swiss/blog/best-of-both-worlds-using-a-secure-chip-with-open-source-firmware/

Overview of security features:
https://bitbox.swiss/bitbox02/security-features/

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

https://shiftcrypto.support/help/en-us/36-rabby-metamask-fork/177-how-to-use-your-bitbox02-with-rabby

### Does the wallet support Ethereum layer 2 networks?

Wallet supports EVM networks: https://bitbox.swiss/ethereum/

### Does the wallet allow the user to customize gas fees?

Yes: https://shiftcrypto.support/help/en-us/12-transactions/111-how-can-i-change-the-transaction-fee

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

https://bitbox.swiss/app/buy/

### Who can the ethereum.org team can contact regarding the wallet in future?

support@bitbox.swiss

### Does the wallet have a dedicated support team?

Yes, usually answers within 1 business day.
support@bitbox.swiss

### What educational resources/documentation do you provide to users?

We provide a lot of educational material and documentation through our blog and support guides respectively:

https://bitbox.swiss/blog/

https://bitbox.swiss/support/#knowledgebase

### Does the wallet have any integrated tools not mentioned above?

- Connect your own Bitcoin full node
- coin control for UTXO management and better privacy
- encrypted USB communication
- Attestation check: The BitBoxApp checks if the connected BitBox02 hardware wallet is genuine
- Miniscript support in the firmware

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by jadzeidan** [comment]
Would it be possible to make progress here? 🙂

**Comment by nnnnnnsssss** [comment]
Recheck

**Comment by wackerow** [comment]
Hey @jadzeidan! Apologies for delays here as the team has been making some large changes over the past 9 months, never intended to let this fall through the cracks.

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation!
