### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by mantasciuksys** [ethereum/ethereum-org-website#11135]
### Dev tool name

Sepolia Faucet from Tatum

### Dev tool description

Hi everyone, 

We know how hard it can be to get testnet eth. I'm recommending to add the [Tatum Sepolia faucet](https://faucets.tatum.io/sepolia) to the "[Networks](https://ethereum.org/en/developers/docs/networks/)" Foundation page. 

Key difference from other faucets, there's no sign up needed. 

 

### When did the dev tool go live?

September 2023

### Where do you think this page should be shown?

https://ethereum.org/en/developers/docs/networks/

### Is the product open source?

Yes

### GitHub URL

https://github.com/tatumio/tatum-js

### Documentation URL

docs.tatum.io

### Additional context

While the faucet itself isn't open sourced - our core product is, and it's essentially our mission to develop Web3 tools that are open source. 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
<img width="950" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/3034ff5e-4cc5-4322-881c-f7960671df6b">

<img width="944" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/c13d2567-c75a-422b-a63d-915cf3a5c33f">

Seven faucets already listed for Sepolia, and getting handshake failures with the provided link. Appreciate the post but going to close this one out.
