### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#11140]
Create a new component for the new Stats component specified in [the DS](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=1069%3A17855).

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/8d71e7a6-59cf-4a91-8f3f-42029984261a)

**Comment by pettinarip** [comment]
cc @TylerAPfledderer

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting for assignment.

Also noting that this is dependent on the completion of #10974, correct?

**Comment by pettinarip** [comment]
Not a hard dependency since we can still use the current Tooltip. I'm planning on doing a new task to transition from the old tooltip to the new one (once it gets merged).
