### ISSUE TITLE
Incorrect Link for Dai Info

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#11141]
### Describe the bug

The link for "Learn about Dai" which directs to https://kb.oasis.app/help/what-is-dai gives page not found error 404

### To reproduce

1. Go to https://ethereum.org/en/stablecoins/
2. Scroll down to 'Dai under Editors' choices'
3. Click on 'Learn about Dai'

### Expected behavior

The web link should give info about Dai

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by rafarocha** [comment]
There is a problem with the site app or we need to check the correct link.
