### ISSUE TITLE
find-wallet: broken table on phone

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#11145]
### Describe the bug

The table view is not optimized for mobile view, i dont see full dropdown and i also dont see the checkmark / x value by default

i have to scroll to the right to see any valuable info

Device:
Samsung Galaxy Note 9

Google Chrome briwser

### To reproduce

1. use phone
2. https://ethereum.org/en/wallets/find-wallet/

### Expected behavior

see the featured dropdown fully and the value for that column

### Screenshots

![Screenshot 2023-09-13 at 22 15 31](https://github.com/ethereum/ethereum-org-website/assets/100724231/1ec982d5-7189-4a07-af0a-3392754a414c)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by konopkja** [comment]
same issue on iphone 8, Safari
![IMG_69D65D6507E1-1](https://github.com/ethereum/ethereum-org-website/assets/100724231/231bbfcb-b09b-41ff-8ecc-a4ddda076608)

**Comment by corwintines** [comment]
Closed with the above PR
