### ISSUE TITLE
Add Veramo framework to developer tools

### ISSUE THREAD

**Issue by emmanuellar** [ethereum/ethereum-org-website#11157]
### Dev tool name

Veramo

### Dev tool description

Veramo is an open source, modular and agnostic framework that makes it easy for decentralized application developers to build decentralized identities and verifiable credentials into their applications.

### When did the dev tool go live?

2021

### Where do you think this page should be shown?

Development Frameworks - https://ethereum.org/en/developers/docs/frameworks/

### Is the product open source?

Yes

### GitHub URL

https://github.com/uport-project/veramo

### Documentation URL

https://veramo.io/docs/basics/introduction

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @emmanuellar. Sorry for delay here, but looks good. PR welcome to make the addition, have assigned you. Can re-assign if needed.

**Comment by corwintines** [comment]
Just wanted to circle back here @emmanuellar and see if this was something you were looking at. Otherwise I will unassign and let someone else take this on.

**Comment by wackerow** [comment]
Circling back through; @emmanuellar let us know if you're still interested in working on this. Opening back up in the meantime.

**Comment by sumitvekariya** [comment]
Please assign this to me @wackerow

**Comment by wackerow** [comment]
Fixed with #13741

**Comment by wackerow** [comment]
@all-contributors please add @emmanuellar for idea
