### ISSUE TITLE
remove scroll bar on find-wallet page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#11156]
### Describe the bug

The scrollbar for list of wallets has too many UX issues on both desktop and mobile phone. 

This has been verified with the community through user testing a year ago as well as in recent simulator testing where 2 users also struggled with it.

Furthermore, we received the same comments recently in the feedback survey.

The issue is that often times the inpage scrollbar is unexpected behavior and results in weird positions that cuts the list view. Then the view is hard to change because suddenly the are that controls the scrollbar unexpectedly changed.

See some examples in screenshots

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/..'
2. Try scrolling

### Expected behavior

No extra scrollbar

### Screenshots

![Screenshot 2023-09-15 at 15 57 17](https://github.com/ethereum/ethereum-org-website/assets/100724231/68e38b10-0c95-475d-ada0-bb7066cbdd11)

This issue is also on mobile - it is difficult to control and expect which area of phone will result in different types of scroll behavior.

In this example i unexpectedly stopped scrolling full page and the inned list started scrolling instead, resulting in a situation where i barely see any product, but cannot change the view from where i was clicking. I must instead start clicking on a different part of the website to control the scroll. This behavior is very unexpected and causes friction. 
![image](https://github.com/ethereum/ethereum-org-website/assets/100724231/62a3e2e2-7bc9-4fff-8b92-1d1909b189b1)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by nloureiro** [comment]
The quick fix should be something like this.

Remove all the heights and overflows.

https://github.com/ethereum/ethereum-org-website/assets/1120748/ae16b381-8608-402c-bbc2-5b4ec05294ff



The downside is the context; you lose the table head and the context of the filters unless the devs find an easier way to fix the table head to the top of the browser. I think we've tried to do this and had some technical issues.

**Comment by konopkja** [comment]
> The quick fix should be something like this.
> 
> Remove all the heights and overflows.
> 
>  Screen.Recording.2023-09-15.at.13.55.44.mov 
> The downside is the context; you lose the table head and the context of the filters unless the devs find an easier way to fix the table head to the top of the browser. I think we've tried to do this and had some technical issues.

yes this is what i am suggesting
