### ISSUE TITLE
Figment addition to Staking as a Service Ethereum Website (https://ethereum.org/en/staking/saas/)

### ISSUE THREAD

**Issue by ivanszeftel** [ethereum/ethereum-org-website#11160]
### Project name

Figment

### Product type

Staking as a service

### Logo

![Figment Logomark - yellow](https://github.com/ethereum/ethereum-org-website/assets/142626003/ae2c9fc9-a1f1-4edf-a537-d37ccc8bcf27)

### Description

Figment is the leading provider of staking infrastructure and provides the most comprehensive staking solution for over 250 institutional clients, including asset managers, exchanges, wallets, foundations, custodians, and large token holders, to earn rewards on their digital assets. On Ethereum, Figment is the largest non-custodial staking provider with nearly 5% of staked ETH on Figment validators. Figment’s institutional staking service offers seamless point-and-click staking dashboard, portfolio reward tracking, API integrations, audited infrastructure, and slashing protection. This all leads Figment’s mission to support the adoption, growth, and long-term success of the digital asset ecosystem.

### Website

https://figment.io/

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes

### What wallets support the product or service?

Metamask, Ledger, BitGo, Fireblocks, Copper, Anchorage, Wallet-Connect compatible wallets

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

N/A. The minimum ETH required to stake is 32. 

### If a service, what are the fees associated with using the service?

~10% staking fee (0% of Consensus Layer rewards, and 30% of Execution Layer rewards)

### If the product or service involved a liquidity token, what are the tokens involved?

No liquidity token involved

### What date did the project or service go live?

2018

### Has the project undergone an external security audit?

Yes, [SOC 2 Type 2 Audit Report](https://trustpage.figment.io/), [ISO 27001 Certificate](https://figment.docsend.com/view/terpqdzfbjafcpy), and [Halborn Smart Contract Security Audit](https://figment.docsend.com/view/3b2w63bye3gfzxc)

### Has the project undergone any security bug bounties?

Yes, we have a private vulnerability disclosure program that is managed through [Bugcrowd](https://www.bugcrowd.com/).

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Yes, Figment’s staking is non-custodial and no point in the journey requires trusting humans with keys, funds, or distribution of rewards.

### If a pooled staking service, can users participate as a node operator without permission?

N/A

### If listing a staking-as-a-service, are users required to sign-up for an account?

Yes.

### If listing as staking-as-a-service, who has access to the signing keys?

For safety reasons, the access to the validator private keys (signing keys) is strictly limited to the service.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

To ensure that the service is non-custodial, the access to the withdrawal credentials is limited to the customer.

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

Figment is not running on a fixed allocation between client stacks and has the ability to rapidly migrate between clients. Today, Figment runs both geth and Lighthouse, with the optionality to seamlessly and swiftly transition between clients to ensure optimization performance and safety.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

Lighthouse and Teku

### What platforms are supported?

The browser app is supported on every platform including Linux, macOS, Windows, iOS and Android.

### What user interfaces are supported?

Browser app

### Social media links

Twitter: https://twitter.com/Figment_io
Linkedin: https://www.linkedin.com/company/figment-io

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @ivanszeftel! Thanks for dropping... 

Could you clarify when the Ethereum staking service went live? Was it along with the Beacon Chain or later?

Is this bug bounty publicly accessible?

> Today, Figment runs both geth and Lighthouse, with the optionality to seamlessly and swiftly transition between clients to ensure optimization performance and safety.

Can you clarify what percent is Geth at the moment, and/or how often you switch between clients... the point of this indicator is to help with network client diversity and currently a deterrent from supporting Geth.

Lemme know and I think we can move this along

**Comment by ivanszeftel** [comment]
Hello and thanks for the quick reply @wackerow! Find the answers below:

- Ethereum staking service went live mid-2021, along the Beacon Chain correct. 
- The bug bounty it’s a private program, but we do have public details on how to responsibly disclose bugs here: https://figment.io/responsible-disclosure/
- we are currently running 85% geth and 15% erigon. we have the ability to adjust this distribution dynamically and are always considering the best distribution for us depending on performance, ease of maintenance, and other factors.

**Comment by wackerow** [comment]
Ok thanks for the updates...

@ivanszeftel Tried looking at the audits but they appear to be behind a permission wall... are there public links available directly to the audits?

> Essential code has undergone formal auditing with results published and available publicly

**Comment by ivanszeftel** [comment]
Hello @wackerow,

Audits have to be requested directly through our [trustpage](https://trustpage.figment.io/). 

Are you looking for any audit report in particular? We can send them over to you.

**Comment by wackerow** [comment]
Okay... it's less about me and what is certain to be available to the public.

I can put this up as a PR... a few items are close (ie audits and bug bounty), but if they aren't publicly available they'd be marked as absent. 

I'll reference this issue and tag you @ivanszeftel when I post the PR.
