### ISSUE TITLE
Ethereum for Ruby developers

### ISSUE THREAD

**Issue by becaz** [ethereum/ethereum-org-website#1116]
Don't we have a page for Ruby developers?

**Comment by samajammin** [comment]
Hey @becaz - thanks for creating this issue.

If I understand you correctly, I assume you're envisioning a dedicated page for Ruby developers, similar to our [current resources for specific programming languages](https://ethereum.org/developers/#language-specific-resources).

Is that correct? Feel free to expand on your thinking.

**Comment by samajammin** [comment]
@all-contributors please add @becaz for ideas.

**Comment by fade2black** [comment]
Hi @samajammin, yeah exactly. It'd be great if there'd be a separate page dedicated to Ruby developers.

**Comment by samajammin** [comment]
@fade2black awesome! Contributions welcome, whether that's a draft document you want to link to from this issue or a full-fledged PR. If it helps, feel free to follow the general structure of those existing pages (e.g. here's the [raw Golang page](https://raw.githubusercontent.com/ethereum/ethereum-org-website/dev/docs/golang/index.md)).
