### ISSUE TITLE
Bug report: Broken link

### ISSUE THREAD

**Issue by 0xMimir** [ethereum/ethereum-org-website#11162]
### Describe the bug

On [https://ethereum.org/sw/developers/docs/bridges/](https://ethereum.org/sw/developers/docs/bridges/) there is link for types of bridges [types of bridge designs](https://blog.li.fi/what-are-blockchain-bridges-and-how-can-we-classify-them-560dc6ec05fa) that is broken.

### To reproduce

1. Go to 'https://ethereum.org/sw/developers/docs/bridges/'
2. Scroll down to 'HOW DO BRIDGES WORK?'
3. Click on `types of bridge designs`
4. Get `This page isn’t working` error with message `blog.li.fi redirected you too many times.`

### Expected behavior

To open [https://li.fi/knowledge-hub/blockchain-bridges-and-classification/](https://li.fi/knowledge-hub/blockchain-bridges-and-classification/)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
@all-contributors can you add @0xMimir for content

**Comment by 0xMimir** [comment]
Fixed by #11164
