### ISSUE TITLE
Bug report - Invalid Link

### ISSUE THREAD

**Issue by srn08** [ethereum/ethereum-org-website#11244]
### Describe the bug

Link for "An Introduction to Smart Contracts with Parity Ethereum Client" no longer exits.

### To reproduce

1. Go to [Rust Docs for Ethereum](https://ethereum.org/en/developers/docs/programming-languages/rust/)
2. Scroll down to [Beginner Articles](https://ethereum.org/en/developers/docs/programming-languages/rust/#beginner-articles)
3. Click on "An Introduction to Smart Contracts with Parity Ethereum Client"

### Expected behavior

Update link with new and relevant article or delete it.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @srn08, I see a PR was opened for this so going to close this issue!

**Comment by corwintines** [comment]
@all-contributors can you add @srn08 for bug
