### ISSUE TITLE
Refactor codebase to use Gatsby

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1126]
**Is your feature request related to a problem? Please describe.**

After research by the team, we've revealed that Gatsby has a number of advantages over the current app (Vuepress). Here's the TL;DR:
- Greater features (e.g. flexible data sources, support for MDX, TypeScript, Framer Motion)
- Greater documentation & community resources
- Long term sustainability (22 FTEs working on open-source code and documentation)
- Team productivity (we're most productive in React & are admittedly biased towards it)
- Larger React vs. Vue talent pool (e.g. for bounties of future hires)
- Shared learnings / patterns / architecture across EF properties

**Describe the solution you'd like**

Refactor codebase from Vuepress to Gatsby.

**Describe alternatives you've considered**

See [this research document](https://www.notion.so/efdn/Spec-out-tech-stack-considerations-a8df100655144e78aa3a43dfd2c70090) for more context.

**Additional context**

See [this research document](https://www.notion.so/efdn/Spec-out-tech-stack-considerations-a8df100655144e78aa3a43dfd2c70090) for more context.

**Comment by cwaring** [comment]
Interesting to see this switch. I agree with most of the advantages however I'm yet to find a solid way to enable IPFS support to the same level as we could with VuePress, mostly related to the issues [outlined in this thread](https://github.com/gatsbyjs/gatsby/issues/14161). Did you find a viable solution to this?

**Comment by samajammin** [comment]
@cwaring bummer. Just read through that issue thread. I regret to say that I overlooked the potential for IPFS to be an issue. I made the unfortunate assumption that given it's popularity, Gatsby must have a good solution to relative URLs 😞

**Comment by samajammin** [comment]
@cwaring I'm closing out this issue (solved in #1134) but I created an issue for IPFS (#1171) that I encourage you to weigh in on. I appreciate you keeping tabs on us!
