### ISSUE TITLE
Remove Truffle Suite references as it's being discontinued

### ISSUE THREAD

**Issue by nhsz** [ethereum/ethereum-org-website#11262]
### Describe the bug

Truffle/Truffle Suite will be discontinued by the ~end of December 2023 ([more context here](https://twitter.com/trufflesuite/status/1704946902393860589)). We should remove links and references from the content, docs, tutorials, etc. In some cases, besides removing we'll need to rewrite some sentences, so some evaluation could be needed.

<img width="603" alt="Screen Shot 2023-09-26 at 15 24 15" src="https://github.com/ethereum/ethereum-org-website/assets/948922/b4583b98-325f-445e-ada7-1a3465c436fb">

### To reproduce

See https://twitter.com/trufflesuite/status/1704946902393860589

### Expected behavior

Remove Truffle/Truffle Suite mentions, links and references from the site to avoid dead links in the future.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by Poojan-20** [comment]
hey i would like to work on this issue.

**Comment by corwintines** [comment]
@Poojan-20 will assign to you

**Comment by Poojan-20** [comment]
I can remove truffle/truffle suite mentions but there are a lot of tutorials that have truffle suite mentions. Additionally there are no such alternatives mentioned for such tutorials. If you want to explain me alternative sources for this we can also get on a call and do this. :)

**Comment by wackerow** [comment]
Hey @Poojan-20, circling back on this. Are you still interested in making these updates?

Regarding tutorials, we have a relative abundance of tutorials which could use some pruning. If they require Truffle to complete, we should remove these (wouldn't worry about replacing for now)

**Comment by wackerow** [comment]
Just clarifying here:
- If there is a tutorial that simply mentions, or links out to Truffle, then I would suggest just removing that specific mention.
- If the whole tutorial hinges on using Truffle and would require re-writing it for the tutorial to work, then we should just deprecate and remove that entire tutorial.

**Comment by wackerow** [comment]
(#10766 Specifically called out [this tutorial](https://ethereum.org/en/developers/tutorials/solidity-and-truffle-continuous-integration-setup/#adding-the-solidity-coverage-plugin), closed that issue to track here)

---

I'd like to open this to a community contributor with the following scope:

- [ ] Find all mentions of Truffle being used in our tutorials.
- [ ] If there is a tutorial that simply mentions, or links out to Truffle, then remove that specific mention
- [ ] Any tutorials that hinge entirely on using Truffle should be removed entirely

Can keep to English only.

**Comment by sumitvekariya** [comment]
Please assign this to me

**Comment by wackerow** [comment]
Fixed with #13738
