### ISSUE TITLE
Create "Ethereum resources for PHP developers" page

### ISSUE THREAD

**Issue by ksqbly** [ethereum/ethereum-org-website#1129]
Hope for ethereum resources for PHP developers

**Comment by samajammin** [comment]
Hey @ksqbly - thanks for creating this issue.

A you envisioning a dedicated page of resources for PHP developers, similar to our current [resources for specific programming languages](https://ethereum.org/en/developers/#language-specific-resources)?

Feel free to expand on the issue & solution you're looking for.

**Comment by samajammin** [comment]
One library to include: https://github.com/sc0Vu/web3.php

Looks to be the most popular PHP Ethereum API, though not extremely active (most development came in early 2018).
