### ISSUE TITLE
Bug report: use case pages sidebar dropdown hidden

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#11304]
### Describe the bug

when opening the dropdown, it has wrong z-index

### To reproduce

1. Go to https://ethereum.org/en/decentralized-identity/
2. Click on ethereum use cases
3. See error

### Expected behavior

dropdown should be overlaying the summary box 

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/100724231/8471b175-e91a-42a7-b406-38813a752b77)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MahendraBishnoi29** [comment]
assign it to me @konopkja
