### ISSUE TITLE
Mistiterane

### ISSUE THREAD

**Issue by Mistiterane** [ethereum/ethereum-org-website#11313]
### Name

1inch.wallet 

### Description

[README (1).md](https://github.com/ethereum/ethereum-org-website/files/12756030/README.1.md)

### Logo

https://ethereum
[The_GitHub_guide_to_empowering_developers.pdf](https://github.com/ethereum/ethereum-org-website/files/12756043/The_GitHub_guide_to_empowering_developers.pdf)
.com/@babayevaterane20/list/reading-list

### Brand color

grey

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

1inch.wallet.open adreses

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

[gh_2.32.0_linux_amd64.tar.gz](https://github.com/ethereum/ethereum-org-website/files/12756046/gh_2.32.0_linux_amd64.tar.gz)

### Can a user access the dapp without creating an account?

[anahtar kelime.txt](https://github.com/ethereum/ethereum-org-website/files/12756051/anahtar.kelime.txt)

### Are dapp funds non-custodial?

1inch wallet adresess 

### Do you offer community support?

ethereum

### Describe any geographical restrictions on usage of your dapp

1inch.wallet open adresess 

### Would you like to work on this issue?

- [X] Yes
- [X] No

**Comment by VaibhavAPatil** [comment]
What the issue??
