### ISSUE TITLE
Add banner: Ethereum.org Writers Cohort (2nd edition)

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#11316]
### Is your feature request related to a problem? Please describe.

Add banner on ethereum.org's website in order to promote the 2nd edition of [Ethereum.org Writers Cohort](https://ethereumwriterscohort.carrd.co/).

### Describe the solution you'd like

- Banner copy:

`🎉 Join the 2nd edition of ethereum.org's Writers Cohort, starting October 20th. [Sign up here!](https://ethereumwriterscohort.carrd.co/)`

### Describe alternatives you've considered

n/a

### Additional context

- A similar request has been made ~5 months ago: https://github.com/ethereum/ethereum-org-website/pull/10078

- Last banner preview: 

![image](https://github.com/ethereum/ethereum-org-website/assets/119775909/6b174ec7-da59-466b-b97a-c2f6b14ae408)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by clairecharles** [comment]
Hi @isabelladebrito can I work on this?
