### ISSUE TITLE
Incorrect intl number formatting

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#11335]
### Describe the bug

Dates on event cards are not being formatted using intl locale.

### To reproduce

1. Go to https://ethereum.org/zh/community/events/
2. Notice date format in event cards compared to date at the top of the page.

### Expected behavior

Despite the contents of these cards not being translated into other languages, I would expect these dates to be rendered according to the locale.

The [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) should be used by passing the current locale and the date to render accordingly.

### Screenshots

<img width="866" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/7462d64f-361f-415b-9892-8e4b1a784ae7">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by akashvana** [comment]
Hi, is this issue still up for grabs? If so, can you assign this to me?

**Comment by shivam200446** [comment]
Hey, I want to work on it assign me!

**Comment by ameeetgaikwad** [comment]
@wackerow can this issue be labeled under Hactoberfest?

**Comment by Nash0509** [comment]
Github marked it as stale. Assign it to me, I will be happy make my first contribution @wackerow

**Comment by ameeetgaikwad** [comment]
@Nash0509 i've already raised a pr. #11443 

If you got a better fix, you can go ahead. Just don't want you to waste your time doing the same work.

**Comment by wackerow** [comment]
Hey folks! Sorry I missed the requests to be assigned here... @ameeetgaikwad I saw your PR and just left a review... as mentioned in there, we're in the midst of migrating the repo to Next.js which will affect this slightly... we should be ready for a patch here within 1-2 weeks.

Will assign you for now given you've already started work on it, but just let us know if you'd prefer one of the other volunteers to take a stab at it!

**Comment by ameeetgaikwad** [comment]
@wackerow would like to continue working on this.

Thank you.

**Comment by ameeetgaikwad** [comment]
@wackerow On it.
