### ISSUE TITLE
Suggest a wallet: Kresus SuperApp

### ISSUE THREAD

**Issue by FrancescoBini** [ethereum/ethereum-org-website#11345]
### Wallet name

Kresus SuperApp

### Wallet description

Kresus is a consumer-friendly, mobile, high security, non-custodial digital wallet app for holding and managing crypto including NFTs and digital tokens. 

### Wallet logo

![Kresus-App-Logo-160x160](https://github.com/ethereum/ethereum-org-website/assets/83545917/2ca704b9-8d74-4a31-b553-6f0662b64488)

### Background color for brand logo

#020a75

### URL to the project

https://www.kresus.com/

### When did the wallet go live to users?

May 11th 2023

### Does the wallet have an active development team?

Yes. We do have a team of developers who continue to work actively on new features and maintenance of the wallet. We are using GitLab and the repositories are private as of now. We can provide access on a need basis.

### Is the wallet globally accessible?

The wallet is accessible in 46 countries worldwide, including all 50 U.S. states. While we don't require any KYC for wallet usage, users may encounter KYC requirements when utilizing in-app partner portals.

### Is the wallet available in multiple languages?

The wallet is currently available only in English

### What social links are there for the project?

Twitter: https://x.com/Kresusofficial
Discord: https://discord.gg/dWYC6nK5

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

The wallet is mobile-first, and is both on iOS and on Android.

iOS: https://apps.apple.com/us/app/kresus-crypto-nft-superapp/id6444355152
Android: https://play.google.com/store/apps/details?id=com.kresus.superapp

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No, the wallet currently doesn't have a desktop app 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No, the wallet doesn't have a browser extension 

### Is it a hardware wallet?

No, the wallet is not a hardware wallet 

### Is the source code for the wallet fully open-source?

No, the source code is currently not open source. 

### What license is the wallet software released under?

Kresus Wallet is a proprietary software. It is free for the consumers to download and use after agreeing to Our Terms and Conditions. The code is not available to the public and falls under a commercial license only available to specific partners.

### Who holds the private keys?

Ours is an HSM based non-custodial wallet where users are able to manage their own keys if needed.
There is a risk factor if the users lose access to their email or phone number, the user would have to go through a different workflow for recovery should they lose access to their wallet.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Audit reports:
- Wallet Security Testing - We conduct internal penetration testing every quarter and the reports are private.
- Vault Smart Contract Audit Report - [Hacken Audit Report](https://hacken.io/audits/kresus-labs/) (Launching November 2023) 

We do not have any public bug bounty programs.
We have a dedicated security team monitoring for cyber threats using various security technologies like EDR, Secure web gateway, Private Access, WAF & SIEM solutions.

### Has the wallet's smart contract code or security modules been audited?

Answer will be the same as to the previous question. 

### Does the wallet have an internal security team?

Yes, we have a dedicated security team equipped with the above-mentioned technologies & 24/7 SOC room for round-the-clock monitoring of threats.

### Any other security testing that should be noted?

As part of our development program, we are presently implementing static & dynamic security testing as part of the CI/CD pipeline.
Application has been pentested periodically & identified critical issues have been fixed.

### Scam protection?

Yes, the wallet has built-in safety features to protect users from potential scams. We have an NFT and Token scam folder that flags and hides suspicious NFTs and Token contracts. Additionally, we offer a transaction simulation feature that allows users to preview the outcome of a transaction, providing an extra layer of security.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, the wallet supports connecting to Ethereum-based applications. Users can connect in two ways:  Through WalletConnect or KresusConnect for partners that have integrated our proprietary SDK.

### Does the wallet support staking directly?

Yes, Kresus does support in-app staking through our partnership with Lido Finance. Users can easily stake their assets without leaving the Kresus app. We currently support Ethereum  and Solana staking. 

### Does the wallet support swaps directly?

Yes, our wallet supports direct swaps through an in-app integration with Changelly. Users can easily swap, also cross-chain, between different cryptocurrencies without leaving the Kresus app.

### Does the wallet support multi-chain networks?

No, the wallet doesn't support multi-chain networks. However, we are a multichain wallet supporting 4 different chains: Ethereum, Bitcoin, Solana and Polygon.

### Does the wallet support Ethereum layer 2 networks?

We don’t currently support any Ethereum layer 2 network

### Does the wallet allow the user to customize gas fees?

Yes, the wallet allows users to customize gas fees for transactions. In the 'Me' section of the app, there's a page called 'Default Send Speed.' Here, users can choose between two options: 'Regular,' which offers a good balance of speed and cost, and 'Expedited,' for those willing to pay a bit extra for faster transactions.

### Does the wallet support sending transactions to ENS addresses?

No, the wallet doesn’t currently support sending transactions to ENS addresses

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

No, the wallet doesn't have this functionality at the moment. However, we do support a wide range of ERC-20 and SPL tokens. Users can browse and add these tokens to their main currency page for easy access.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Kresus offers a variety of in-app fiat on-ramping options, accessible via the "Buy" button in the currency section of the app. We've teamed up with Stripe for credit card, debit card, and ACH transactions, making us one of the few wallets that support on-ramping in New York. For those looking for instant ACH transfers, we've partnered with Sardine. For our international audience, Ramp is available as a credit card on-ramping solution. These strategic partnerships give our users a diverse range of convenient methods to purchase crypto.

### Does the wallet support withdrawals to fiat?

Yes, Kresus enables users to cash out their crypto assets directly to their bank accounts, thanks to our partnership with CoinFlow Labs. The off-ramp feature is easily accessible within the app in the currency page.

### Is the wallet a multi-signature wallet?

No, the wallet is not multi-signature.

### Does the wallet support social recovery?

No, but we have support for recovery through a mobile number once set.

### Who can the ethereum.org team can contact regarding the wallet in future?

Best way to reach out would be via email at francesco.b@kresus.com.
Alternatively, 
Twitter: https://x.com/Kresusofficial
Discord handle: chiccob#8007

### Does the wallet have a dedicated support team?

Yes, Kresus boasts a dedicated 24/7 support team that's readily available to assist users with any issues. For urgent matters, phone support is also an option. Users can easily reach out to our support team directly within the app: there's a chat button on the top-right corner of the landing page, and a "Have some feedback?" button at the bottom of the same page. Additionally, tickets can be raised also from our website.

### What educational resources/documentation do you provide to users?

We offer a variety of educational resources to guide users through their crypto journey. 

- Our blog ([link](https://www.kresus.com/blog/)) covers a wide range of topics, from beginner guides to advanced integration topics. 
- We also host a podcast ([Apple Podcast link](https://podcasts.apple.com/us/podcast/set-in-stone/id1703669161)) ([Spotify link](https://open.spotify.com/show/6uHr2Db4lApJn7a4fMkkj5?si=db22d0271b1a440a)) that delves into various aspects of the crypto world. 
- Within the app itself, we have educational resources designed to make the experience as user-friendly as possible. The app is "goofproof," meaning we hand-hold users until they feel comfortable navigating on their own. Additionally, the landing page can be customized to feature educational resources whenever we deem it necessary.

### Does the wallet have any integrated tools not mentioned above?

Kresus has several additional features that set it apart:
- At sign-up, we provide each user with a free Unstoppable Domain .kresus web3 domain, eliminating the need for complicated hexadecimal addresses. Everything gets sent to the same domain and we sort the right address on the backend. 
- We've removed the traditional seed phrase
- App access is granted through a PIN or biometric authentication.
- We offer the ability to mint NFTs on the Polygon chain for free, and we even provide up to five free copies that can be gifted to friends and family. 
- Users can easily add contacts either from their phone or via their .kresus domain. 
- Human-readable notifications for all transactions within the app can be set.
- NFTs can be sent out of the wallet
- Users can add their social handles for a more seamless sharing experience.
- Users can add a profile picture and a bio to their account.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by FrancescoBini** [comment]
Just following up on this ticket. Any updates or timeline on when this will be addressed? 
Thank you!

**Comment by wackerow** [comment]
Hey @FrancescoBini! My apologies for the delays here as our team has finishing working through some large changes over the past 9 months, didn't mean to let this fall through the cracks. 

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation!
