### ISSUE TITLE
Improve copywriting: rename guides hub and change wallet simulator CTA

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#11362]
### Is your feature request related to a problem? Please describe.

in data we see that only few people click on certain elements:

1. Guides hub
2. Interactive tutorial

the working hypothesis is that this low click rate is due to bad copywriting which users dont relate to. If we change how the items are named, perhaps there will be an improvement in user interest.

### Describe the solution you'd like

1. Rename menu item "Guides hub" -> "How-to guides"
![Screenshot 2023-10-04 at 17 18 05](https://github.com/ethereum/ethereum-org-website/assets/100724231/90338e02-8594-4a3e-8cd0-a66df8af26f9)

2. Rename button "Interactive tutorial" -> "How to use wallets" on https://ethereum.org/en/wallets/
![Screenshot 2023-10-04 at 17 20 32](https://github.com/ethereum/ethereum-org-website/assets/100724231/fb172cd9-2509-4a7e-b184-0b8266f52edb)

### Describe alternatives you've considered

NA

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by minimalsm** [comment]
1. LGTM 👍
2. Fine w/change, but do worry about the length of the copy in some non-English languages.

**Comment by konopkja** [comment]
cc @corwintines

**Comment by fgm5858** [comment]
Nin![SECURITY.md](https://github.com/ethereum/ethereum-org-website/files/12824945/SECURITY.md)

**Comment by fgm5858** [comment]
None

**Comment by fgm5858** [comment]
![ethereum-hero-light.gif](https://github.com/ethereum/ethereum-org-website/assets/146592193/d385e22a-b005-4e8f-bed2-3cfd3c102e2c)

**Comment by minimalsm** [comment]
Maybe "How to use a wallet" ?
