### ISSUE TITLE
Wrong paddings on What is ethereum page (mobile)

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#11361]
### Describe the bug

wrong aligment:

 too much white space in cards (https://ethereum.org/en/what-is-ethereum/)
![Screenshot 2023-10-03 at 22 03 25](https://github.com/ethereum/ethereum-org-website/assets/100724231/6c3f5288-b370-43be-909b-baad8c85f59a)

expected design: (see https://ethereum.org/en/get-eth/)
![Screenshot 2023-10-04 at 16 46 53](https://github.com/ethereum/ethereum-org-website/assets/100724231/a15fb2de-bb9d-4cae-8905-e849e331096c)

### To reproduce

1. use mobile device
2.  Go to https://ethereum.org/en/what-is-ethereum/

### Expected behavior

see other comments

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by shivam200446** [comment]
Hey, I want to work on it assign me!

**Comment by konopkja** [comment]
hello @shivam200446  i think somebody has already jumped ahead without asking to be assigned and created a PR https://github.com/ethereum/ethereum-org-website/pull/11364 for this one, sorry and lets see how that goes

**Comment by fgm5858** [comment]
![20230925_200211.jpg](https://github.com/ethereum/ethereum-org-website/assets/146592193/77bc8096-8def-406d-a0ba-ddb372cf86e7)

**Comment by fgm5858** [comment]
![account-abstraction-hero-mobile.jpeg](https://github.com/ethereum/ethereum-org-website/assets/146592193/08698879-30c3-45e0-bb0c-2bba8362b15e)

**Comment by fgm5858** [comment]
![1IPs-main.zip](https://github.com/ethereum/ethereum-org-website/files/12824884/1IPs-main.zip)

![1inch(1).png](https://github.com/ethereum/ethereum-org-website/assets/146592193/ff40f7e3-6485-4ee2-bf8f-78f4b03cb449)

![1inch(2).png](https://github.com/ethereum/ethereum-org-website/assets/146592193/dd3e1294-5f83-4508-8f74-6364e0f2b193)

https://github.com/ethereum/ethereum-org-website/assets/146592193/64a229b7-34f6-474f-ae69-bb90dedc3fcb

**Comment by fgm5858** [comment]
![eth-gif-sun(1).png](https://github.com/ethereum/ethereum-org-website/assets/146592193/57d622e4-29b9-45be-a19c-be76b7e5dee9)

**Comment by fgm5858** [comment]
![Cargando footer-background-mobile.png …]()

**Comment by fgm5858** [comment]
Súper peso

**Comment by fgm5858** [comment]
Robaron mi cueta de gmail y robaron mi proyecto de 

www.internet-start.net

Www.Start page.com

**Comment by fgm5858** [comment]
Start https://
Start https://start
Start https://start.net
Start https://internet-start.net
Start https://www.internet-start.net
Start https://www.startpage.com

**Comment by suhani1804** [comment]
can i work on this issue?

**Comment by konopkja** [comment]
yes @suhani1804

**Comment by fuzheng1998** [comment]
I think it is not a "padding problem", it is just because misuse of component.

**Comment by fuzheng1998** [comment]
@[corwintines](https://github.com/corwintines) would you like to review it?

**Comment by konopkja** [comment]
> @konopkja would you like to review my PR?

https://github.com/ethereum/ethereum-org-website/pull/11687

cc
@corwintines @pabloped
