### ISSUE TITLE
Icons alignment issue on /wallets/#sim page

### ISSUE THREAD

**Issue by nhsz** [ethereum/ethereum-org-website#11370]
### Describe the bug

Icons used in some lists inside `/wallets/#sim` page are not aligned properly with text

### To reproduce

1. Go to https://ethereum.org/en/wallets/#sim
2. Scroll down to **Types of wallets** and **How to stay safe** sections
3. See icons not aligned properly

### Expected behavior

Icons aligned properly with text

### Screenshots

<img width="684" alt="Screen Shot 2023-10-04 at 13 20 08" src="https://github.com/ethereum/ethereum-org-website/assets/948922/fe08bd3e-b2be-4320-9ea7-262e9b6ca801">

<img width="711" alt="Screen Shot 2023-10-04 at 13 20 41" src="https://github.com/ethereum/ethereum-org-website/assets/948922/31bdff1e-56c1-49db-8503-5c4c3c5bfa09">

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by MahendraBishnoi29** [comment]
assign it to me @nhsz

**Comment by MahendraBishnoi29** [comment]
should i align them in center?
![image](https://github.com/ethereum/ethereum-org-website/assets/74294202/352d14c5-b180-4522-b75b-f26a7ef2ba0c)
just like this 👇🏻
![image](https://github.com/ethereum/ethereum-org-website/assets/74294202/3cb07d6a-cbcd-48dc-b62f-946c84085e1f)
