### ISSUE TITLE
Energy consumption chart missing labels

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#11372]
### Describe the bug

The Energy consumption chart found on [the energy consumption page](https://ethereum.org/en/energy-consumption/) and the [what is Ethereum page](https://ethereum.org/en/what-is-ethereum/) is missing does not have any labels, making it effectively useless.

### To reproduce

1. Go to 'https://ethereum.org/en/what-is-ethereum/'
2. Scroll down to the 'What about Ethereum's energy consumption?' section
3. See error

### Screenshots

<img width="1526" alt="Screenshot 2023-10-04 at 17 42 50" src="https://github.com/ethereum/ethereum-org-website/assets/62268199/6d0f0913-d5e7-4aeb-8509-0c5949472a12">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by corwintines** [comment]
Closing with above PR
