### ISSUE TITLE
Improve 'How to create an Ethereum account' screenshot

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#11374]
### Is your feature request related to a problem? Please describe.

On [the how to create an Ethereum account guide](https://ethereum.org/en/guides/how-to-create-an-ethereum-account/), the first screenshot looks hastily taken (scroll bar visible, white background visible) with poor attention to how it displays on dark mode.

<img width="933" alt="Screenshot 2023-10-04 at 17 52 13" src="https://github.com/ethereum/ethereum-org-website/assets/62268199/b3f313b9-2e90-4315-9bec-c9ce90675ca6">

### Describe the solution you'd like

Take a screenshot that shows the component without a background/scrollbar visible

### Describe alternatives you've considered

This screenshot will always be in English, but we already translate these strings in many languages. Wondering if there is a good solution here without a bunch of duplicative work - @lukassim 

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by shivam200446** [comment]
Hey, I want to work on it assign me!

**Comment by fgm5858** [comment]
![20230924_223314.jpg](https://github.com/ethereum/ethereum-org-website/assets/146592193/99d73f4f-c09c-4811-82ee-2de4e41abe1d)

**Comment by ameeetgaikwad** [comment]
@minimalsm can this issue be labeled under Hactoberfest?
