### ISSUE TITLE
Staking template dropdown links English only

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#11388]
### Describe the bug

The `dropdownLinks` inside the `staking` template are not yet set up for translation, while the rest of the pages are.

### To reproduce

1. Go to https://ethereum.org/es/staking/solo/
2. Click on "Staking Options" (<-- which is in English)
3. See other options in English, while rest of page is in Spanish

### Expected behavior

Menu should be translatd.

### Screenshots

Production Spanish solo staking page:
<img width="1236" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/d55970eb-5c81-4705-8f05-3ea64656d9f0">

English only in the code:
<img width="690" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/0216a286-1160-4fbb-a0d3-c0e6319f9768">

Vs one set up for translation, like `use-cases.tsx`:
<img width="620" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/b89a92d7-4a87-4b21-9594-3c4672a74cd0">

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by amankaushik481** [comment]
I would like to work on this, please assign it to me.

**Comment by MrJithil** [comment]
No progress from the dev. So, I am taking this issue.
