### ISSUE TITLE
Example requests and responses are too dummy on JSON-RPC SPEC page

### ISSUE THREAD

**Issue by Amit0617** [ethereum/ethereum-org-website#11384]
### Describe the bug

There are various kinds of requests and responses on [json-rpc spec](https://ethereum.org/en/developers/docs/apis/json-rpc) page. I understand they are for the purpose of giving structure of request and responses but it would be a good idea that responses are of mentioned request. 
Mainly there should be such requests which can give desired kind of responses.

### To reproduce

Try [eth_getBalance](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getbalance) and you would find following response
```console
{"jsonrpc":"2.0","id":1,"result":"0x0"}                                             
```

### Expected behavior

Mentioned response is expected i.e.,
```js
{
  "id":1,
  "jsonrpc": "2.0",
  "result": "0x0234c8a3397aab58" // 158972490234375000
}
```

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @Amit0617! Thanks for posting, and sorry for delays getting back to you.

Looks like you're referring to the `// Result` being shown in the example and how it doesn't match the actual RPC call (`0x0234c8a3397aab58` vs `0x0`)? These values are currently hard-coded in the markdown files as just examples, so they wouldn't match an actual RPC call.

Any thoughts on how you'd like to see this fixed?

**Comment by Amit0617** [comment]
Yes, my main concern was they are just completely dummy values. While that is not a big issue for someone who is just reviewing and learning about this first time. However, people who will be reading specs and build tooling around it will try to use those parameters as an example to test their tooling. They will also try to match corresponding responses with it. So, I was mainly suggesting using examples which will have some real responses. Instead of using random 32 characters, random hex, an original block hash should be used.

**Comment by Amit0617** [comment]
I recently saw, there is a new section added `JSON-RPC API playground` which already accomplishes what was expected through this issue. Maybe now, we don't need to care about it any more.

**Comment by corwintines** [comment]
@Amit0617 open to these changes if you would like to take this on. I would just er on the side of standardized values kind of like you said (vitalik.eth is used all over the place with other projects I notice for example).
