### ISSUE TITLE
Bug report : Prices are not showing correctly on `/layer2`

### ISSUE THREAD

**Issue by 0xumarkhatab** [ethereum/ethereum-org-website#11385]
### Describe the bug

When accessing the website by `https://ethereum.org/en/layer-2/`, the prices section contains three fields.
Two of them are not showing up correctly.
Those are `TVL locked in layer 2 (USD)` and `Layer 2 TVL change (30 days)`.

Instead of showing the price details it shows `Error, please refresh`

See the picture below!

### To reproduce

1. Go to 'https://ethereum.org/en/layer-2/'
3. Scroll down a bit

### Expected behavior

Show the correct TVL

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/71306738/00cd0d67-b697-4106-8351-4194168b7e51)

### Desktop (please complete the following information)

- Windows 10
- Google Chrome

### Additional context

There seems to be an issue with `src/pages/layer2.tsx` in fetching the price details.

Kindly make sure it's functioning well

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by TylerAPfledderer** [comment]
@pettinarip The api being used is throwing an error:
`DOMException: The quota has been exceeded.`

(At line 222 of `layer-2.tsx`)

**Comment by wackerow** [comment]
This page has been redesigned, closing out.
