### ISSUE TITLE
Renew Matomo plugin license

### ISSUE THREAD

**Issue by wtf** [ethereum/ethereum-org-website#1139]
The "Search Engine Keywords Performance" Matomo plugin is about to expire - we should renew it before it expires, causing anomalies in the data. In addition to renewing it, we need to upgrade it to the "unlimited users" license, since we have exceeded the number of users currently allowed. It might be worth enabling auto-renewal, if it's possible to do so.

The other plugin which is about expire, i.e. "Multi Channel Conversion Attribution", does not need to be renewed since it is not used and was given for free when we first purchased "Search Engine Keywords Performance".

@samajammin has confirmed that we need the first plugin but not the second one.

Edit:
Expires Jul 31. Can be renewed by going to https://matomo.ethereum.org/index.php?module=Marketplace&action=subscriptionOverview and clicking on "Search Engine Keywords Performance"

**Comment by samajammin** [comment]
> we need to upgrade it to the "unlimited users" license, since we have exceeded the number of users currently allowed

@wtf how many users do we have? Perhaps we can avoid an upgrade fee by pruning old users?

**Comment by wtf** [comment]
The license allows up to 15 users, while we're currently at 27. For up to 15 users, the renewal will cost us $290/year, while the next plan (with unlimited users) costs $440/year.

**Comment by samajammin** [comment]
Hmmm, another $150 annually doesn't feel like a large expense but I wonder if we actually need even 15 users.

Perhaps @jjmstark can weigh in here. I'm not aware of who currently has access.

**Comment by samajammin** [comment]
Solved in https://github.com/ethereum/devops/issues/450
