### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Maxservais** [ethereum/ethereum-org-website#11403]
### Is your feature request related to a problem? Please describe.

 I noticed that at the end of the article titled [Optimistic Rollups](https://ethereum.org/en/developers/docs/scaling/optimistic-rollups/), under the "Further reading on optimistic rollups" section, there is one link that appears to be broken.

Broken Link: [Everything you need to know about Optimistic Rollup](https://research.paradigm.xyz/rollups)

### Describe the solution you'd like

Apart from fixing or removing the broken link, I'd like to suggest an additional link for the "Further reading" section: [What is a Blockchain Rollup? A Technical Introduction.](https://www.ethereum-ecosystem.com/blog/what-is-a-blockchain-rollup-a-technical-introduction). This is a comprehensive article that provide valuable insights on what rollups, targeted at beginners.

### Describe alternatives you've considered

Another alternative solution I considered was simply removing the broken link without adding any new ones. Additionally, rather than suggesting the specific link I've mentioned, we could link to other high-quality resources on the topic.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by ameeetgaikwad** [comment]
Would like to work on this.

**Comment by Maxservais** [comment]
Any update on this? I can get started right away :)

**Comment by Maxservais** [comment]
Any update on this?

**Comment by Maxservais** [comment]
Hi @corwintines Could I kindly get your thoughts on this PR https://github.com/ethereum/ethereum-org-website/pull/12095 ?

I am trying to increase awareness for [Ethereum Ecosystem](https://www.ethereum-ecosystem.com/), an unofficial Ecosystem page for Ethereum and its Layer 2s featuring 900+ dApps and tools across Optimism, Base, Starknet and more.
