### ISSUE TITLE
Bug report: No top to up button on Readme file

### ISSUE THREAD

**Issue by Durgesh4993** [ethereum/ethereum-org-website#11418]
### Describe the bug

There are no top to up button on Readme file, when some one go to the last of readme file they take to much scroll or take time to get back on index (ToC) section.

### To reproduce

On Readme.md File

### Expected behavior

Sir can i add top to up button in Readme file

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Durgesh4993** [comment]
@nhsz please assign this task to me

**Comment by wackerow** [comment]
Sounds good to me, sorry for delays here. Have assigned @Durgesh4993 if you'd like to put up a PR for this.

**Comment by corwintines** [comment]
Just bumping on this @Durgesh4993, is this still something you would like to add here?

If not, will close this out on my next loop through.
