### ISSUE TITLE
Solid World

### ISSUE THREAD

**Issue by johngvibes** [ethereum/ethereum-org-website#11425]
### Name

Solid World

### Description

Solid World is the financial infrastructure for funding climate and energy assets. We unlock liquid trading for environmental assets that were previously constrained by a lack of available capital.

### Logo

![Solid-World_Logo_Black](https://github.com/ethereum/ethereum-org-website/assets/113725931/51c2175b-c89b-434c-894e-45fbd481e25a)

### Brand color

#0abc8a

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/solid-world

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

we've developed our smart contracts with security in mind and all our contracts are audited by Dedaub

### Can a user access the dapp without creating an account?

Yes

### Are dapp funds non-custodial?

Yes

### Do you offer community support?

https://discord.com/invite/kPHxcYE7yC

### Describe any geographical restrictions on usage of your dapp

Users from the US are required to do KYC, and we do not allow interactions from sanctioned addresses or countries. 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @johngvibes 

This project is on Polygon, not Ethereum, so going to close this.
