### ISSUE TITLE
[Proposal] Improve Project TypeScript Conventions

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#11421]
This proposal is to update conventions provided in the [typescript.md](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/typescript.md) to help follow best practices using TypeScript in React.

Note: the thoughts outlined below come are based on the [React-TypeScript Cheatsheet](https://react-typescript-cheatsheet.netlify.app) as a primary source, along with how the Chakra team approaches certain conventions.

### 1. Prefer `const Component = (props: ComponentProps) => {}` over `const Component: React.FC<ComponentProps> = (props) => {}`

This suggestions is pretty nuanced and sometimes considered negligible. `React.FC` in the React repo is not recommended and was removed from the `create-react-app` starter template. This type implies the `children` prop is to be used. This goes against components that should not accept the `children` prop, so it will pass the typescript compiler if a contributor tries to add a child in the given component's render.

Using `React.FC` also prevents using [Generic Component](https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase#generic-components) that accept props with variable types, or a component that is using type guarding. For an example of a component like this currently being used in this project, see the [UpgradeTableOfContents component](https://github.com/ethereum/ethereum-org-website/blob/bc518af6c6f383e8216977caaaf198eb54e3faba/src/components/UpgradeTableOfContents.tsx#L90-L1009) that is using type guarding via function overload. This would not work with `React.FC`.

There isn't much readability saved in it's written usage, and could be awkward to use for things like typing a namespace component (i.e. `<Menu.Item />`

See the PR description for [removing React.FC from create-react-app template](https://github.com/facebook/create-react-app/pull/8177)

### 2. Prefer explicit component prop type naming
Most component throughout the project have a prop type named `IProps`, with some of these types exported for use in other components or page components. This is adding steps for contributors to have to declare import aliases for these types to ensure there is no confusion in usage for code readability.

A better convention would simply using naming that matches the component, such as `QuizSummaryProps` for the `QuizSummary` component. 

Secondly, it is fine to prefix the type name with `I`, such as `IButtonProps` to identify it as an interface. However, more times than not this probably not necessary (another negligible matter of preference). 

Thirdly, preference for the component props type should be a `type` and not an `interface` (with specific exceptions) as noted in the [React-Typescript cheatsheet](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/basic_type_example#types-or-interfaces). Because this project is not a 3rd-party API with components, prefer `type` for the added constraint because we are not trying to do something like [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces).

> 🚨 Important: I'm going to take a big L on this one because I've been doing `interfaces` out of habit from working in the Chakra library 😅 

### 3. Remove the `noImplicitAny` option from tsconfig
Now that the TypeScript epic has been complete, this option really should be removed to go back to the default of `true`. The `any` type for the most part should really be avoided to keep from throwing away restrictions. If you are not sure what type of value is being sent to a function or component prop use the [unknown type to allow for type checking or assertions](https://dmitripavlutin.com/typescript-unknown-vs-any/). 

Also, see this [example reading JSON from local storage](https://mariusschulz.com/blog/the-unknown-type-in-typescript#example-reading-json-from-localstorage)

### 4. Remove any notice of ongoing migration
Because the migration is considered complete

## Additional considerations
I would add either [Husky](https://typicode.github.io/husky/) to auto-run the `type-check` script on commit, or adding a github action for PRs to run the script. Based on current DX preferences, the latter makes more sense. This is to help ensure type errors are not forgotten before changes go to prod.

**Comment by wackerow** [comment]
Hey @TylerAPfledderer! Thank you so much for aggregating these proposal points 🎉 Overall I'm in agreement with all of this. 

1. This sounds good, and I did indeed encounter that issue with `UpgradeTableOfContents` over in the Next.js migration repo utilizing `React.FC`
2. Agree with using `ComponentNameProps` and ditching `I`, and I too am used to using interfaces, but should be a simple switch
3. 💯 Agree with this... A note here, the forked repo being worked on for the Next.js migration may be a good place to try this out.

Thinking on your last note about `type-check`... The Next.js repo is enforcing type checking at build time preventing type failures from going to prod, but we don't have anything like a pre-commit hook yet. I'm a little on the fence with pre-commit hooks myself... @pettinarip Any thoughts or preferences here?

**Comment by TylerAPfledderer** [comment]
@pettinarip should this issue be considered closed?

**Comment by pettinarip** [comment]
@TylerAPfledderer correct! thanks for the PR
