### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by TABASCOatw** [ethereum/ethereum-org-website#11430]
### Wallet name

Particle Network

### Wallet description

Particle Network is the Intent-Centric, Modular Access Layer of Web3. With Particle's Wallet-as-a-Service, developers can curate targeted user experience through modular and customizable EOA/AA embedded wallet components. By utilizing MPC-TSS for key management, Particle can streamline onboarding via familiar Web2 accounts—such as Google accounts, email addresses, and phone numbers.

### Wallet logo

https://i.imgur.com/Qm7yQOn.png

### Background color for brand logo

#bc39db

### URL to the project

https://particle.network

### When did the wallet go live to users?

May 5th, 2022

### Does the wallet have an active development team?

Yes, Particle currently has a team of 30+ full-time members. https://twitter.com/ParticleNtwrk https://github.com/Particle-Network

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English, Chinese, Korean, and Japanese

### What social links are there for the project?

https://twitter.com/ParticleNtwrk
https://discord.gg/e69JmS2CsS
https://blog.particle.network/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS: https://apps.apple.com/us/app/particle-crypto-wallet/id1632425771
Android: https://play.google.com/store/apps/details?id=network.particle.auth

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Embedded web application, supports all systems.

Example at https://wallet.particle.network / https://web-demo.particle.network

### Is the source code for the wallet fully open-source?

No

### Who holds the private keys?

Particle Network leverages secure multiparty computation (MPC) for the protection and management of cryptographic keys and secrets, providing industry-grade MPC-based solutions for key management and protection.

Particle Network provides the security benefits of having no single point of compromise and shared responsibility (like Multi-Sig) but with a single signature and without any dependency on the ledger. 

Regarding private key access, we employ a secure mechanism called TSS (Threshold Signature Scheme) with a 2-2 setup. This means that private key access is divided into two shards, each stored in different locations:

2. User's Local Hardware Device: One shard of the private key is stored on the end user's local hardware device. This ensures that the user maintains control over a portion of their private key, enhancing security and decentralization.
3. TEE (Trusted Execution Environment) Environment: The other shard of the private key is securely stored within our TEE environment. The TEE provides a trusted and isolated environment that protects the private key shard from unauthorized access. By distributing the private key across these two locations, we ensure a robust security model that mitigates the risk of single points of failure and enhances the overall protection of the user's private key.

At the moment, we don't allow for private key exports due to the nature of our MPC-TSS architecture, all key management happens through the above described process.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

To begin, some added context to the previous question- regarding out key management mechanism:
1. Sensitive keys and secrets are split into two random shares. The two shares are stored on separate, segregated parties. Each share reveals nothing about the key material.
2. All cryptographic operations performed throughout the key lifecycle are performed without ever combining these two shares together. This includes signing, derivation, and even generation. There is no complete key material or secret in the memory, ever. It is proven mathematically that obtaining the key material requires access to both key shares, and therefore requires compromising both parties. A single party, even if completely compromised and controlled by an attacker, reveals nothing about the key material—simply because the key material never resides in any single party.
3. Key shares refresh. Key shares are continuously modified without modifying the key itself. It is computationally efficient and can be performed very frequently, thus forcing the attacker to compromise both parties at virtually the same time in order to obtain key material.

In addition to our core key security mechanism, we also employ rigorous security standards across the board, and regularly receive codebase audits from:
Certik - https://skynet.certik.com/projects/particle-network
Salus

### Has the wallet's smart contract code or security modules been audited?

https://skynet.certik.com/projects/particle-network includes MPC report PDF

### Scam protection?

Yes, Particle leverages a variety of partners to actively analyze transactions being facilitated by Particle- if a transaction is flagged as potentially malicious (a scam), the user is informed and asked if they're sure about conducting said transaction.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

No, due to being an embedded WaaS provider

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes- if an application has natively integrated Particle as a connection option, users can connect through the specific implementation outlined by the developer. Additionally, our mobile app contains an in-wallet dApp browser as another mechanism of connection.

### Does the wallet support staking directly?

Not in-app, but it can facilitate stake transactions as most wallets can.

### Does the wallet support swaps directly?

Yes, Particle has built-in swap functionality powered by 1inch, Izumi, and LI.FI- https://docs.particle.network/developers/node-service/evm-chains-api/enhanced-rpc/swap (API reference, the in-app functionality is in-part built upon this)

### Does the wallet support multi-chain networks?

Yes, https://docs.particle.network/overview/available-networks

### Does the wallet support Ethereum layer 2 networks?

Yes, https://docs.particle.network/overview/available-networks

### Does the wallet allow the user to customize gas fees?

Yes, when sending an EOA transaction, users can either choose between Slow, Standard, Fastest, or manually alter gas limit and priority fee. For AA transactions, users can choose between gasless/token/native.

### Does the wallet support sending transactions to ENS addresses?

Yes, you can send directly to ENS addresses as they're automatically resolved.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, both. The wallet will query your token balance and display tokens it assumes to be non-spam. You can also import ERC-20 tokens directly.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, Particle Wallet supports EIP-1559, even including RPC endpoints for corresponding gas fee retrieval.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, Particle aggregates various onramp providers (Mercuryo, Transak, AlchemyPay, FatPay) and offers a native widget ("Buy") for facilitating onramp through these different providers directly to your Particle account.

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

N/A

### Does the wallet support social recovery?

Not natively yet, although Particle can act as the signer for various different smart account implementations (along with it's own native implementation, which doesn't yet support built-in social recovery).

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram: tabascodev
Twitter: TABASCOweb3

### Does the wallet have a dedicated support team?

We have a number of support-adjacent team members, who can primarily be contacted through our Discord (https://discord.gg/e69JmS2CsS).

We're a somewhat small team so it isn't the fastest, although pressing inquiries will be answered.

### What educational resources/documentation do you provide to users?

https://docs.particle.network/

https://web-demo.particle.network/

https://www.youtube.com/@ParticleNtwrk

### Does the wallet have any integrated tools not mentioned above?

Particle is set to release V2 in the next few months, which will introduce:
- Authentication privacy via. Confidential Auth (shifting from WaaS to zkWaaS)
- Transaction privacy via. Confidential Transactions (also a result of the shift from WaaS to zkWaaS)
- Intent Fusion Protocol, powering intent-centric interaction through Particle zkWaaS

And all of this, even today, is facilitated primarily through social logins with MPC-TSS for key management.

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @TABASCOatw, apologies for delay here as we work through the backlog but I've assigned for review; will leave #11775 in the meantime.

**Comment by corwintines** [comment]
@TABASCOatw I was looking at this. From what I can gather looking at https://particle.network, I don't see a wallet a user can use here, but a developer toolkit. Am I missing something? If there is a wallet, I think I would want to see this much more accessible from the website we would be linking out to than is already there.

**Comment by TABASCOatw** [comment]
> @TABASCOatw I was looking at this. From what I can gather looking at https://particle.network, I don't see a wallet a user can use here, but a developer toolkit. Am I missing something? If there is a wallet, I think I would want to see this much more accessible from the website we would be linking out to than is already there.

Since opening this, we've changed the model a bit away from the exclusive wallet focus; the core product still here stands though, that being Wallet-as-a-Service (an embedded wallet interface for developers to use and implement and users to leverage, driving wallet creation through social accounts).

Although our branding deviates from this a bit now and may not fit super well with the current list of wallets on the site; can close this issue and associated PR.

**Comment by corwintines** [comment]
Sounds good. I hope the wallet-as-a-service works out!
