### ISSUE TITLE
Bug report: Broken links

### ISSUE THREAD

**Issue by 0xMimir** [ethereum/ethereum-org-website#11444]
### Describe the bug

On page [https://ethereum.org/en/developers/docs/scaling/optimistic-rollups/](https://ethereum.org/en/developers/docs/scaling/optimistic-rollups/) on further reading there is link for [How does Optimism's Rollup really work?](https://research.paradigm.xyz/optimism) for [https://research.paradigm.xyz/optimism](https://research.paradigm.xyz/optimism) that doesn't work

### To reproduce

1. Go to 'https://ethereum.org/en/developers/docs/scaling/optimistic-rollups/'
2. Scroll down to 'Further reading on optimistic rollups'
3. Click on 'How does Optimism's Rollup really work?'

### Expected behavior

To go to https://www.paradigm.xyz/2021/01/how-does-optimisms-rollup-really-work

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by byhow** [comment]
I can take a look at this one if it has not been worked on yet, thanks!
