### ISSUE TITLE
[Feature request]:- Adding Code of conduct to repo. 

### ISSUE THREAD

**Issue by mohitd404** [ethereum/ethereum-org-website#11458]
### Is your feature request related to a problem? Please describe.

We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

### Describe the solution you'd like

This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

### Describe alternatives you've considered

none !

### Additional context

i would love to work on this repository kindly assign me this issue ! Thank you! 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @mohitd404! Sorry for delays here... Were you looking for something like our [Code of Conduct](https://ethereum.org/en/community/code-of-conduct/) page? Or did you want to expand upon a page like this?

We were just discussing potentially adding a [`CODE_OF_CONDUCT.md`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) file. This would be more on the GitHub side, but it could be worth a discussion if we should potentially require users to agree to a code of conduct before being able to post (if that's possible, would have to double check). 

@isabelladebrito Assigning you to help guide this. If we're content with status quo we can always close this out.

**Comment by wackerow** [comment]
`CODE_OF_CONDUCT.md` brought up specifically in #11504, will move discussion about the GitHub side to their.

The Code of Conduct page hosted on ethereum.org was put up around the time of this post, so going to call this one resolved and close it out.
