### ISSUE TITLE
Spacing on token list in wallet simulator

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#11465]
### Describe the bug

In the `Create account` and `Send/receive tokens` flows of the wallet simulator, the spacing of the tokens list (UNI token in this case) is quite close to the border. Without scrolling for more tokens in this list, the spacing looks a bit awkward. 

### To reproduce

1. Go to https://ethereum.org/en/wallets/#sim
2. Select either the `Create account` or `Send/receive tokens` tutorials
3. When you get to a screen with a token list, you can see the UNI token spacing looks a bit awkward without any scrolling

![image](https://github.com/ethereum/ethereum-org-website/assets/15589226/c65c29e9-8f8c-42f9-995f-3f1bac206746)

### Expected behavior

Little more padding on the token list

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/15589226/fd9c90bc-d43a-402b-ae98-b446e2fe88f4)

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by corwintines** [comment]
@wackerow @konopkja @nloureiro would be curious your thoughts on this

**Comment by konopkja** [comment]
we can lower text to 14 or 12 px to get some more space for the token amount row (dollar value keep 16, token value decrease)

**Comment by MahendraBishnoi29** [comment]
how about if increase the size of the box a little bit? it was `600px` and I tried `610px`

![image](https://github.com/ethereum/ethereum-org-website/assets/74294202/b9ab614c-50f0-4486-8fe6-0c6151d32864)

**Comment by MahendraBishnoi29** [comment]
we can do this also. this way we can reduce the box size from `600px` to `570px`. @konopkja @corwintines 

![image](https://github.com/ethereum/ethereum-org-website/assets/74294202/97dac688-b354-4fef-8c2c-4af2e2d035ea)

**Comment by konopkja** [comment]
> we can do this also. this way we can reduce the box size from `600px` to `570px`. @konopkja @corwintines
> 
> ![image](https://user-images.githubusercontent.com/74294202/276830557-97dac688-b354-4fef-8c2c-4af2e2d035ea.png)

this solution will not work well once we show some amount of tokens there which we do later in another walkthrough

increasing box siZes is possible, iam however afraid to do so because we know users on smaller devices will have hidden content but if its at the bottom and it is this particular information it can be ok. 

still would like to see option to reduce font size too

**Comment by MahendraBishnoi29** [comment]
> > we can do this also. this way we can reduce the box size from `600px` to `570px`. @konopkja @corwintines
> > ![image](https://user-images.githubusercontent.com/74294202/276830557-97dac688-b354-4fef-8c2c-4af2e2d035ea.png)
> 
> this solution will not work well once we show some amount of tokens there which we do later in another walkthrough
> 
> increasing box siZes is possible, iam however afraid to do so because we know users on smaller devices will have hidden content but if its at the bottom and it is this particular information it can be ok.
> 
> still would like to see option to reduce font size too

this is when I decrease the font size:

![image](https://github.com/ethereum/ethereum-org-website/assets/74294202/722e804c-5ec8-4dac-8b25-fbf6f7ffd078)

**Comment by wackerow** [comment]
> @wackerow @konopkja @nloureiro would be curious your thoughts on this

I think the original design here was intended to give the appearance of a list of tokens that would continue below the screen, hence the bottom margin was not needed.

We're dealing with sizing constraints here, so personally would err on the side of not messing with it, but not against it if we form consensus around a decent alternative.

**Comment by wackerow** [comment]
@konopkja @nloureiro @MahendraBishnoi29 Do we know what next steps are here?

**Comment by nloureiro** [comment]
Not a strong take here; maybe the reduced font size proposed by @MahendraBishnoi29  can be a good way to go

**Comment by MahendraBishnoi29** [comment]
> Not a strong take here; maybe the reduced font size proposed by @MahendraBishnoi29 can be a good way to go

alright then, i'll submit a PR soon with my solution @wackerow
