### ISSUE TITLE
Update layout spacing on home/hub pages

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#11464]
Per discussions in #11132 regarding spacing presented from a new hub hero with content below (learn hub page was the example), need to pull a new PR to address the other pages that will have the new heroes.

- With the home page, we are looking to have the hero image span the entire viewport regardless of screen size. The page layout needs a mini revamp to allow for this.
- For the remaining hub pages that are not immediately implementing the new hero, update the spacing (especially for mobile) to prep for the future additions.

This PR would also address updating spacing patterns for these pages (i.e. allow a parent component or wrapper control spacing between children)

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting for assignment since this has been previously discussed.

Any other thoughts you have here?

**Comment by F3n4nd0gm** [comment]
Español por favor

**Comment by F3n4nd0gm** [comment]
Soy de México

**Comment by wackerow** [comment]
Thanks @TylerAPfledderer!... Sorry for delay here, want to double check if this is still necessary at this point? If so I've assigned you, but if not feel free to just close out.

**Comment by TylerAPfledderer** [comment]
@wackerow going to close out as it is outdated and not necessary at this point.
