### ISSUE TITLE
Scroll to view on use-case template pages

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#11466]
### Is your feature request related to a problem? Please describe.

Currently, we have this scroll to view component on the use-case template under the header which is supposed to scroll to the top of the #content container when clicked. This only appears in large screens, and our hero is small enough that you can see the content already so it seems like a redundant component. It also doesn't work on every page (example: https://ethereum.org/en/social-networks), so it doesn't serve much of a purpose. 

![Screen Shot 2023-10-18 at 10 21 17 AM](https://github.com/ethereum/ethereum-org-website/assets/15589226/dfd1957e-c5de-4240-bb77-f29ff29d08c2)

### Describe the solution you'd like

I think we can just remove this component, it doesn't really serve a purpose. At one point the headers were larger, but this seems like an anti-pattern that we can get rid of. 

### Describe alternatives you've considered

Fixing the scroll bug for pages where this isn't working.

### Additional context

Lines 443-457 in /src/templates/use-cases.tsx

```
<Show above={lgBp}>
  <Flex
    as={BaseLink}
    to="#content"
    bg="ednBackground"
    justifyContent="center"
    p={4}
    width="full"
    _hover={{
      bg: "background.base",
    }}
  >
    <Icon as={MdExpandMore} fontSize="2xl" color="secondary" />
  </Flex>
</Show>
```

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by ATREAY** [comment]
hey @corwintines, can I work on this issue if you are not already working on it?

**Comment by ATREAY** [comment]
hey @wackerow, can work on this issue?

**Comment by wackerow** [comment]
I'm fine with this, any opposition @nloureiro @konopkja?
