### ISSUE TITLE
Feature request: Image wrapper widget for full screen on click

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#11473]
### Is your feature request related to a problem? Please describe.

Throughout the site, there are various images for content where they are clickable to show full screen in a separate tab. However, because they are being marked as external links, the external link icon is being shown with the image.

![image](https://github.com/ethereum/ethereum-org-website/assets/65234762/5284189c-ef51-4ec3-9be9-1ce3e2e873a9)

### Describe the solution you'd like

Have a wrapper component that displays a full-screen icon to give the user a better indication that they have the option to see it at fullscreen, and not be left wondering if it might lead them to something else.

A mock example:
![image](https://github.com/ethereum/ethereum-org-website/assets/65234762/516ab21d-4d63-4f10-8626-f94f09e7e053)
**That second "hover" should actually be "focus"**

This would be rendered with the `LinkOverlay component` and provide a better indication with screen readers that it "opens a new window as a fullscreen image" or something similar. Can use the `ButtonLink` component with the `ghost` variant for the icon to maintain DS consistency.

For a11y, this can allow for appropriate hidden text to provide clarity that selecting the image opens a new tab with a full-screen version of it. Or simply hide this from focus via `aria-hidden` (for screen readers only).

### Describe alternatives you've considered

No other alternatives considered.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

cc @nloureiro @pettinarip

**Comment by F3n4nd0gm** [comment]
![logo.png](https://github.com/ethereum/ethereum-org-website/assets/147960298/a1dbf40a-8dbc-4cdb-9043-730adc4c2d58)

**Comment by F3n4nd0gm** [comment]
![Cargando bitcoin.png …]()

**Comment by F3n4nd0gm** [comment]
![bitcoin64.png](https://github.com/ethereum/ethereum-org-website/assets/147960298/220b949d-f207-45b0-8626-5dad7a653f4b)

**Comment by F3n4nd0gm** [comment]
Yes

**Comment by wackerow** [comment]
Looks like this has resolved. Closing out but please re-open if I've missed anything.
