### ISSUE TITLE
Suggest a dapp: FBBank

### ISSUE THREAD

**Issue by cubeforex** [ethereum/ethereum-org-website#11506]
### Name

FBBank

### Description

FBBank is the Web3 world's first decentralized crypto fund. It uses the DAO organization form of the blockchain to build an investment system, which is an unprecedented new financial organization.

### Logo

![FBLogo1200](https://github.com/ethereum/ethereum-org-website/assets/97790533/ffe66df5-e735-4a74-92d7-cd159d640ec6)

### Brand color

#28dd8a

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/cubeforex/FBBank

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

We have passed the strict review of BSC chain and passed the review and have been running for more than 1 year.
https://dappbay.bnbchain.org/detail/fbbank

![F8RlrjHbMAATB82](https://github.com/ethereum/ethereum-org-website/assets/97790533/0b366bc1-8087-4a17-b036-7e8568081562)

### Can a user access the dapp without creating an account?

Yes

### Are dapp funds non-custodial?

Yes

### Do you offer community support?

Telegram English: https://t.me/FBBank_official
Telegram Chinese: http://t.me/FBBank_chinese
Discord: https://discord.gg/3z2nE5DeTA

### Describe any geographical restrictions on usage of your dapp

No limit.

### Would you like to work on this issue?

- [x] Yes
- [ ] No
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [x] Telegram: @fbbank_fly
```

**Comment by wackerow** [comment]
Thanks @cubeforex! Sorry for delays here. I've assigned for a product review and we'll take it from there.

cc: @konopkja

**Comment by konopkja** [comment]
Hello i struggled understanding the website, seems like the focus is only on airdrop and FBpay which seems to be a fiat to crypto on ramp tool, but the app didnt work for me in any browser nor incognito. On top of this all it seems to be a BNB project, not Ethereum based.

With this information I am closing this issue.

If I missed anything important, feel free to resubmit with more detail information on how this works and what it does.
