### ISSUE TITLE
Feature request Add CODE_OF_CONDUCT file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [ethereum/ethereum-org-website#11504]
### Is your feature request related to a problem? Please describe.

It's not related to a problem.

### Describe the solution you'd like

I want to add a CODE_OF_CONDUCT file to the repository to be followed by the contributors while contributing to the repository.

### Describe alternatives you've considered

NA

### Additional context

Kindly assign me this issue.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Just wanted to bump on this @isabelladebrito. Will bring this up in grooming next week.

**Comment by minimalsm** [comment]
@isabelladebrito bump

**Comment by isabelladebrito** [comment]
gm folks! Thanks for raising this issue, and sorry for the delay. 

The [ethereum.org's Code of Conduct](https://ethereum.org/en/community/code-of-conduct/) should be applicable for all platforms including this Github repo - that said, the 'CODE_OF_CONDUCT file' to be added should contain the same content as the page I shared above.

In any case, if you feel there should be included more specific recommendations/guidelines for Github contributors, we can definitely work on adding these to the Code of Conduct - just let me know!

**Comment by corwintines** [comment]
Thanks @singodiyashubham87 

I think alright to make this CODE_OF_CONDUCT file, but as @isabelladebrito mentioned we do have this page made already. Ideally we don't want to maintain two versions of this, so we should have a script that copies the code of conduct pages content into this file. Probably a github workflow.
