### ISSUE TITLE
Duplicate items in DeSci example projects

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#11519]
### Describe the bug

There are duplicate items in DeSci example projects.

### To reproduce

1. Go to https://ethereum.org/en/desci/#get-involved
2. Scroll down to items
3. See some of them are listed more than once

### Expected behavior

Each item should be listed once. 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by erfanHosseinPanahi** [comment]
yes what is detail of this issue

**Comment by aslikaya** [comment]
You can see the description

**Comment by amit-ksh** [comment]
These are links are shown twice.

![duplicate-links](https://github.com/ethereum/ethereum-org-website/assets/91947037/5dd7316b-4269-4070-acc6-228b68696491)

**Comment by erfanHosseinPanahi** [comment]
thanks a lot

**Comment by isabelladebrito** [comment]
gm @aslikaya, thanks for reporting this! I've just "refreshed" this issue as I created another issue related to this page (https://github.com/ethereum/ethereum-org-website/issues/12081), so I hope someone will pick this up soon :)

Related to this issue, and for better visualisation, I have added some screenshots on links that are duplicated on the "get involved" section:
<img width="894" alt="Screenshot 2024-01-31 at 22 50 16" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/e398a533-0df6-4ff4-93de-cd6724ab5c77">
<img width="844" alt="Screenshot 2024-01-31 at 22 50 44" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/f2ea25e8-b2ae-43d6-bcee-e15c2457640f">
<img width="840" alt="Screenshot 2024-01-31 at 22 51 14" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/b35363f3-a646-4d02-be78-d55832d3666e">
<img width="864" alt="Screenshot 2024-01-31 at 22 52 09" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/eab078b8-90dd-4f0d-a3fe-b3a0e29fee5b">

**Comment by aslikaya** [comment]
@isabelladebrito Thanks, screenshots make it easier to see the issue. I actually solved it and made a commit when I created this issue

**Comment by kaksv** [comment]
Can I work on this issue ?
