### ISSUE TITLE
Suggest a wallet: Sock

### ISSUE THREAD

**Issue by bryclev** [ethereum/ethereum-org-website#11523]
### Wallet name

Sock 

### Wallet description

Sock is a mobile investing app that helps casual crypto investors build wealth with crypto safely. Sock’s disruptive product approach and perspective help investors protect themselves from market volatility, speculation, and scams so that they can build wealth without worrying about ever losing access to their money. Sock combines the simplicity of centralized exchanges with the safety and security of self-custody. Sock is breaking new ground by offering self-custodial versions of essential investment services like automated stop-loss, limit orders, and risk assessments while ultimately giving users more control over their assets.

### Wallet logo

![Group 316128462](https://github.com/ethereum/ethereum-org-website/assets/3696370/f5771ce1-6aec-43b8-83c2-0b72a1f314ad)

### Background color for brand logo

FFFAF7

### URL to the project

https://sock.app

### When did the wallet go live to users?

October 21, 2023

### Does the wallet have an active development team?

Yes. Our repo is not public, but you can see

### Is the wallet globally accessible?

No, US only at the moment. 

### Is the wallet available in multiple languages?

No

### What social links are there for the project?

Twitter: https://twitter.com/sockfinance

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

It is mobile-only on iOS and Android.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No. 

### Is it a hardware wallet?

No. 

### Is the source code for the wallet fully open-source?

No. 

### What license is the wallet software released under?

N/A

### Who holds the private keys?

The user holds the private and public keys. We are fully self-custodial. If we were to disappear, the user would still have access to all of their funds. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We have undergone a full audit by Hacken, as you can see here: https://hacken.io/audits/sock/

### Has the wallet's smart contract code or security modules been audited?

Yes: https://hacken.io/audits/sock/

### Does the wallet have an internal security team?

No

### Any other security testing that should be noted?

No

### Scam protection?

No

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

No

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

Yes

### Does the wallet support multi-chain networks?

Arbitrum, Ethereum

### Does the wallet support Ethereum layer 2 networks?

Yes, Arbitrum

### Does the wallet allow the user to customize gas fees?

No

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

No

### Does the wallet support EIP-1559 (type 2) transactions?

No

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, through Moonpay, Coinbase, or receiving funds from another address. 

### Does the wallet support withdrawals to fiat?

Yes, through Moonpay and Coinbase

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Bryan Levine, co-founder and Head of Product. 

Twitter: @bryclev
Telegram: @bryclev

### Does the wallet have a dedicated support team?

Yes, we respond within 48 hours via email at support@sock.app

### What educational resources/documentation do you provide to users?

All education resources are here: help.sock.app

### Does the wallet have any integrated tools not mentioned above?

We provide an ERC-4337 smart account that enables automated orders like stop loss and limit orders will allowing the user to maintain self-custody. 

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Hey @bryclev! Apologies for delays here as the team has been working through a backlog over the past 9 months, didn't intend to neglect. 

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation! 🙏
