### ISSUE TITLE
Update the Ethereum website's footer, replace the Twitter logo with the new X logo.

### ISSUE THREAD

**Issue by shubhusion** [ethereum/ethereum-org-website#11567]
### Description

This issue addresses the need to replace the existing Twitter logo with the new X logo in the footer of the Ethereum website. The update is essential for maintaining a consistent and up-to-date brand identity on the website. The current Twitter logo should be replaced with the approved X logo in the designated footer section. This change not only ensures brand consistency but also provides a refreshed look for the website, aligning it with the latest branding guidelines.

**Comment by darigovresearch** [comment]
Thanks for raising this @shubhusion! 

Happy to make a pull request to solve this if given the icon library that's being used for the footer

**Comment by shubhusion** [comment]
Can I make a PR for this ? since I only raised the issue. Waiting for a maintainer to assign this to me.

**Comment by darigovresearch** [comment]
@shubhusion you can make a pull request without it being assigned, ideally use the same icon library and make the pull request so it can ideally be "one click" merged

Then link to the issue in the PR so any maintainers know about the issue or link the PR in this issue when you're done

See contributing for more details on what they expect - https://github.com/ethereum/ethereum-org-website#how-to-contribute

**Comment by shubhusion** [comment]
@darigovresearch Can you provide me the path of the directory containing footer source code?

**Comment by corwintines** [comment]
Going to close this out, more info in PR above
