### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by kooroot** [ethereum/ethereum-org-website#11560]
### Describe the bug

typo error ?

### To reproduce

1. Go to 'https://ethereum.org/en/layer-2/'
2. Scroll down to 'Rollups'
3. See error 
2nd paragraph : 1st 
Rollup transactions get executed off layer 1 but the transaction data is submitted to layer 1.

### Expected behavior

In that sentence, isn't it running on layer 2 and submitted transaction data to layer 1, not running on layer 1 ?
Rollup transactions get executed off layer 2 but the transaction data is submitted to layer 1.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @kooroot, thanks for the note! This appears correct but agree the wording is a little confusing.

> Rollup transactions get executed off layer 1

meaning "not on layer 1", opposite of "on layer 1"

> but the transaction data is submitted to layer 1.

Having "layer 1...but...layer 1" feels off to me, maybe we could just update to something like this:

> Transaction data from rollups is submitted to layer 1, while the execution is performed separately.

**Comment by kooroot** [comment]
Hi @wackerow, thanks for your reply. 
I think your opinion is right. 

I understand that Optimism submit transaction batches and state batches to L1, while Arbitrum sends batches collectively to L1. 

> The transaction data in the rollup is submitted to Layer 1, but the execution is done separately. 

I think the following sentence is good.

**Comment by corwintines** [comment]
I think that sentence is good. Other suggestion I have for one would be to keep the order of steps (transaction is executed on layer 2, then it is submitted to the layer 2)

Something like 
> Transactions are executed by the rollup and then transaction data is submitted to Ethereum (layer 1).

**Comment by corwintines** [comment]
Fixed in the above PR, so going to close this out

**Comment by kooroot** [comment]
Thanks
