### ISSUE TITLE
Add another bounty section for the bug bounty page

### ISSUE THREAD

**Issue by fredriksvantes** [ethereum/ethereum-org-website#11570]
### Is your feature request related to a problem? Please describe.

We're missing a section for things that doesn't fit in the other bug bounty sections.

### Describe the solution you'd like

Below the "Solidity bugs" "Deposit Contract bugs", I'd like to have another section called "Dependency bugs". I believe it would look nice visually if this section span across the page (so it's the same width as solidity bugs and deposit contract bugs together).
Inside this section, it could say:

Certain dependencies are crucial for the Ethereum Network to function, and some of these have been added to the bug bounty program. Currently, the list of dependencies included in the bug bounty program are c-kzg-4844 and go-kzg-4844.

Helpful links:
https://github.com/ethereum/c-kzg-4844
https://github.com/crate-crypto/go-kzg-4844

As for the emoji, I don't have any preference.

### Describe alternatives you've considered

Adding it to the text sections of existing sections, but it doesn't feel very nice.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
@fredriksvantes Hey apologies for letting this fall through. Are you still interested in this, and is it still accurate? I can implement if you can confirm it's still desired.

**Comment by fredriksvantes** [comment]
I saw the PR you made @wackerow , looks very good! Let's run with that :)
