### ISSUE TITLE
[BUG] Issue verifying on discord

### ISSUE THREAD

**Issue by darigovresearch** [ethereum/ethereum-org-website#11578]
### Describe the bug

Unable to verify using discord bot

### To reproduce

1. Go to the home page
2. click on the discord link in the footer
3. Try to verify 

### Expected behavior

When clicking it should allow me to join

### Screenshots

![Ethereum org discord error](https://github.com/ethereum/ethereum-org-website/assets/30328618/0e1f55d7-2b69-4ae1-8858-2dd528c235b4)

### Additional context

Happy to help resolve this

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @darigovresearch, were you able to get past this? Haven't heard this from any other users... I'm going to close this out for now, but please feel free to re-open and clarify, thanks!

**Comment by darigovresearch** [comment]
Hey @wackerow, can confirm managed to get access today. Thanks for looking into it!
