### ISSUE TITLE
[FEATURE REQUEST] Add license page to site

### ISSUE THREAD

**Issue by darigovresearch** [ethereum/ethereum-org-website#11586]
### Is your feature request related to a problem? Please describe.

It's hard to know what license the website is under when in the "app". 

### Describe the solution you'd like

Add a page in the website UI to let people know what the license of the website is.

Is the code under MIT but the content under CC-BY etc?

### Describe alternatives you've considered

Mozilla does this quite well https://www.mozilla.org/en-GB/?v=2

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Oh, I like the [Mozilla link you shared](https://www.mozilla.org/en-GB/?v=2)... I don't feel like we have a page that quite correlates to what is done there, other than maybe our [`/about/`](https://ethereum.org/en/about/) page. 

cc: @minimalsm @konopkja @nloureiro What do you think about a page like this, or at the least updating the /about page?

@darigovresearch Would you still be interested in working on something like this?

**Comment by darigovresearch** [comment]
Yes would be happy to put in a pull request for the about page as a placeholder and can iterate from there

**Comment by darigovresearch** [comment]
Pull request https://github.com/ethereum/ethereum-org-website/pull/13179 should resolve this issue from the MIT license perspective.

Still not sure what license the content of the website is under
