### ISSUE TITLE
Suggest a wallet: Ape Wallet

### ISSUE THREAD

**Issue by 0x0077** [ethereum/ethereum-org-website#11589]
### Wallet name

Ape Wallet

### Wallet description

A pioneer on the zkSync Era, Ape Wallet is the first of its kind to offer account abstraction and an ERC6551 wallet. It redefines the user experience by combining ease of use with advanced security features, setting a new standard for digital wallets in the blockchain space.

### Wallet logo

![wallet-logo](https://github.com/ethereum/ethereum-org-website/assets/42128352/33620363-d9db-46e3-8761-d6ec48ca9fd5)

### Background color for brand logo

#FCD435

### URL to the project

https://zkape.io

### When did the wallet go live to users?

Sep 21th, 2023

### Does the wallet have an active development team?

Yes, Ape Wallet currently has a team of 10+ full-time members. https://github.com/zkapeio/ape-wallet

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

No. Only English

### What social links are there for the project?

https://twitter.com/zk_apes
https://zkape.medium.com
http://discord.gg/zkape

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS: https://apps.apple.com/us/app/ape-layer2-wallet/id6450944029

### Is it a hardware wallet?

No. Ape Wallet is account abstraction and an ERC6551 wallet.

### Is the source code for the wallet fully open-source?

Yes. https://github.com/zkapeio/ape-wallet

### Who holds the private keys?

Ape Wallet is account abstraction and an ERC6551 wallet.
**Users Hold Private Keys:** Ape Wallet employs a mechanism known as the "Guardian" where users do not need to directly handle private keys. The user's private keys are held in custody by smart contracts, but the user has control and can execute certain security functions, such as approving new transactions or recovering access, via guardians (which can be another device, a friend or family member, or even Ape Wallet service).

**Others Holding Private Keys:** In Ape Wallet model, no third party has access to or control over your private keys. Guardians only have limited permissions, such as helping to recover accounts, and cannot directly access your funds.

**If the Company/Project Disappears:** Since Ape Wallet infrastructure is built on the zkSync Era, users should still be able to interact directly with their smart contract wallet through the zkSync network, thereby accessing and controlling their funds, even if the Ape Wallet company ceases operations.

Ape Wallet users do not directly hold their private keys but have full control and access to their funds. Even if Ape Wallet as a company were to disappear, users would still be able to maintain access to and control over their funds through the zkSync Era.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Ape Wallet takes several measures to ensure the security of its wallets:

Smart Contract-Based Security: Ape Wallet  wallets are built on zkSync smart contracts, allowing for advanced security features such as 'Guardians' for wallet recovery, locking, and approving large transactions.

Guardians: Instead of a traditional private key that can be lost or stolen, Ape Wallet  allows users to set up Guardians - trusted devices or individuals - to help recover or secure their wallets without having the power to withdraw funds.

No Seed Phrase: Ape Wallet  eliminates the traditional seed phrase, a common vulnerability where users can lose access to their assets if the seed phrase is lost or stolen.

Locking and Unlocking: Users can lock their wallet instantly if they suspect a threat. A Guardian can then help them to safely unlock it.

Two-Factor Authentication: For key operations like adding a new Guardian, Ape Wallet  uses email verification.

Regular Security Audits: Ape Wallet  smart contracts and security model have been subjected to rigorous audits by leading security research firms.

Open Source: Some components of Ape Wallet  wallet are open source, allowing for community review and contributions to the codebase.

### Scam protection?

Yes, Ape Wallet leverages a variety of partners to actively analyze transactions being facilitated by ape wallet- if a transaction is flagged as potentially malicious (a scam), the user is informed and asked if they're sure about conducting said transaction.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes. We use WalletConnect to enable users to connect with all dApps.

### Does the wallet support staking directly?

Yes.

### Does the wallet support swaps directly?

Yes.

### Does the wallet support Ethereum layer 2 networks?

Yes.

### Does the wallet allow the user to customize gas fees?

Yes.

### Does the wallet support sending transactions to ENS addresses?

Yes.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes.

### Does the wallet support social recovery?

Yes. Ape wallet is smart contract wallet.

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram: zkape_willump

### Does the wallet have a dedicated support team?

We have a number of support-adjacent team members, who can primarily be contacted through our Discord (https://discord.gg/zkape).

We're a somewhat small team so it isn't the fastest, although pressing inquiries will be answered.

### What educational resources/documentation do you provide to users?

https://docs.zkape.io
https://developer.zkape.io
https://help.zkape.io

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by wackerow** [comment]
Hey @0x0077! Apologies for the delays here as the team has been implementing some large changes over the past nine months. Didn't mean to neglect your request.

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation! 🙏
