### ISSUE TITLE
Bug: ToC border moving to incorrect location at some view sizes

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#11592]
### Describe the bug

Noticing the border for the Table of Contents is producing strange behavior at a specific range of viewport widths. The border line should separate the ToC from the content, but at widths from 
`992px` to `1024px` the border moves to the top, removing the border from between ToC and content.

### To reproduce

1. Go to https://ethereum.org/en/about/ on desktop
2. Change window width to anywhere from `992px` to `1024px`, and notice the border line move to the top of the Table of Contents

### Expected behavior

Line should not jump, and should always act as a divider between ToC and content.

### Screenshots

<img width="986" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/8d040774-b872-426a-a3c9-3ccd28734cbc">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by ATREAY** [comment]
Hey @wackerow, can I work on this issue if it's not already claimed by someone else?

**Comment by wackerow** [comment]
This has been resolved.
