### ISSUE TITLE
Bug: Roadmap/Staking menu not set up for translations

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#11618]
### Describe the bug

The roadmap pages dropdown menu (template/roadmap.tsx) is not currently set up for translations, while the remaining content is being translated as markdown content.

### To reproduce

1. Go to https://ethereum.org/es/roadmap (or https://deploy-preview-11297--ethereumorg.netlify.app/es/roadmap before latest deploy has been completed)
2. See and click on "Roadmap Options" dropdown menu
3. See menu labels all in English

### Expected behavior

Menu should also be translated

### Screenshots

Example:

<img width="1283" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/d6daa27d-89ba-415e-881f-1ec1273b1474">

These need to be converted to translation keys, with key/value pairs added to the i18n .json files:

<img width="638" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/08130353-e162-4fc3-989c-4cab875fa07e">

### Additional context

We should probably create a new file at `src/intl/en/page-roadmap.json` for the strings from this page. This namespace will need to be added to the `roadmap.tsx` template:
<img width="517" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/1323c207-b321-4a15-aaa6-e05750b717f4">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Update: Noticing this on the `staking` template as well. `use-cases` template appears to be correct.

**Comment by wackerow** [comment]
More specifically, the Staking home (`pages/staking/index.tsx`, https://ethereum.org/es/staking/) is correct, but the subpages (`template/staking.tsx`) is not.

**Comment by MukulKolpe** [comment]
Hey @wackerow, can I work on this issue?

**Comment by wackerow** [comment]
Fixed with #12951
