### ISSUE TITLE
Add Base as an Optimistic rollup

### ISSUE THREAD

**Issue by Maxservais** [ethereum/ethereum-org-website#11698]
### Name

Base

### Logo

![Base_Network_Logo](https://github.com/ethereum/ethereum-org-website/assets/43566493/8f5259bd-e34f-49c1-b67a-008996d8911e)

### Description

Base is a secure, low-cost, developer-friendly Ethereum L2 built to bring the next billion users to web3. It is a new Ethereum L2, incubated by Coinbase and built on the open-source OP Stack.

### Website

https://base.org/

### Developer documentation

https://docs.base.org/

### L2BEAT page

https://l2beat.com/scaling/projects/base

### Is the project open source?

https://github.com/base-org

### What category of layer 2 is it?

Base is an Optimistic Rollup that has been developed on the Ethereum network, utilizing OP Stack technology.

### Does the layer 2 use Ethereum Mainnet for data availability?

All of the data needed for proof construction is published on chain. Fraud proofs are in development.

### Which bridges are used to onboard users?

[Official base bridge](https://bridge.base.org/deposit)
[List of unofficial Base bridges](https://www.ethereum-ecosystem.com/blockchains/base/web3-tools/cross-chain-bridges)

### Which exchanges offer support for the project?

[Coinbase](https://www.coinbase.com/fr/)
[Binance](https://www.binance.com/en)

### Link to dapp ecosystem (if applicable)

https://www.ethereum-ecosystem.com/blockchains/base

### Token contract list (if applicable)

https://docs.base.org/contracts

### What date did the project go live?

Testnet went live on February 23rd 2023: https://www.coinbase.com/blog/introducing-base

### Is this project a fork? If yes, which project was forked?

OP Stack

### What wallets support this layer 2?

All EVM wallets are compatible and support Base. To name a few:
- Coinbase Wallet
- Rainbow Wallet
- Zerion
- Metamask
- ...

### How can users and/or developers connect too this layer 2 network?

**Network Name**: Base Mainnet
**RPC Endpoint**: https://mainnet.base.org/ (Rate limited and not for production systems.)
**Chain ID**: 8453
**Currency Symbol**: ETH
**Block Explorer**: https://basescan.org/

[Source](https://docs.base.org/network-information)

### Has this project undergone an external security audit and/or a bug bounty?

https://hackerone.com/coinbase?type=team

### Has the project sustained its users over time?

On 20th November 2023:

- Total Value Locked: $282,49m
- New Addresses (24h): 8 335
- Transactions (24h): 370 168

[Source](https://defillama.com/chain/Base)

### Is there an active team developing the project?

Yes

### Is there a block explorer?

https://basescan.org/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Maxservais** [comment]
Any update on this?

**Comment by wackerow** [comment]
Hey @Maxservais, I think listing Base is quite appropriate at this point. Assigning you! As usual, if you'd prefer not to work on this just drop a note to let us know (or un-assign yourself if it lets you). Thanks!

**Comment by konopkja** [comment]
Hey @wackerow  or @corwintines, this needs your eyes to review.

**Comment by konopkja** [comment]
should also include metadata for this section
<img width="1407" alt="Screenshot 2024-02-12 at 23 19 30" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/9d29ca19-a9f8-4c7e-98a1-110dec647364">
