### ISSUE TITLE
Suggest additional resource to be linked

### ISSUE THREAD

**Issue by Maxservais** [ethereum/ethereum-org-website#11699]
### Is your feature request related to a problem? Please describe.

This [page](https://ethereum.org/en/nft/#further-reading) informs readers about NFTs and links to further readings. I suggest adding another reading that gives an overview of many NFT dApps people can use today on Ethereum.

### Describe the solution you'd like

I'd like to suggest an additional link for the "Further reading" section. It lists many popular NFT dApps and tools available on Ethereum: https://www.ethereum-ecosystem.com/blockchains/ethereum/nfts

### Describe alternatives you've considered

Rather than suggesting the specific link I've mentioned, we could link to other high-quality resources on the topic.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Maxservais** [comment]
Any update on this?

**Comment by Maxservais** [comment]
@konopkja WDYT about my PR: https://github.com/ethereum/ethereum-org-website/pull/12094? Cheers :)

**Comment by konopkja** [comment]
Sure i think this can be useful

**Comment by konopkja** [comment]
@Maxservais I think we should be moving away from dapp terminology as it just creates unnecessary jargon and another term a regular person needs to understand.

I would suggest simply calling "Ethereum apps" or "apps"
