### ISSUE TITLE
Adding Cropty Wallet to Ethereum.org

### ISSUE THREAD

**Issue by croptywallet** [ethereum/ethereum-org-website#11706]
### Wallet name

Cropty Wallet

### Wallet description

Cropty - easy to use and secure cryptocurrency wallet for beginners and experts.

 It supports a wide range of tokens, including those running on ERC20, BEP20 and TRC20 networks. 

Cropty offers unique opportunities to make money from your assets. With our crypto loans and deposits, users can earn interest from cryptocurrencies, earning income that far exceeds traditional bank rates.

Our support team is available 24/7/365 and ready to help our users anytime. We pride ourselves on offering high quality support to our users.

### Wallet logo

![glyph](https://github.com/ethereum/ethereum-org-website/assets/151154152/329737b1-f793-47cf-ab8c-417e039f3093)
![glyph](https://github.com/ethereum/ethereum-org-website/assets/151154152/eab00a49-f1e6-4d72-88f9-b96aa052b00b)

### Background color for brand logo

#33FF66

### URL to the project

https://www.cropty.io

### When did the wallet go live to users?

04.07.2022

### Does the wallet have an active development team?

The mobile app was last updated 1 month ago, version history can also be viewed here:https://apps.apple.com/us/app/crypto-wallet-bitcoin-usdt/id1624901793. We also respond to every user feedback.

### Is the wallet globally accessible?

Wallet is available globally, but in some countries where app stores require a license (like China or the UK) it is not available in the app stores. In all of these countries, the online version can be used.

### Is the wallet available in multiple languages?

English, Indonesian, Dansk, Deutsch, Español, Français, Italiano, Norwegian, Polski, Português, Română, Русский, Slovenčina, Svenska, Tiếng Việt, Türkçe, Українська, हिन्दी, ไทย

### What social links are there for the project?

Telegram - https://t.me/croptyfi
YouTube - [www.youtube.com/@croptytv](http://www.youtube.com/@croptytv)
Twitter - https://x.com/cropty_app

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

App Store (iOS) - https://apps.apple.com/us/app/crypto-wallet-bitcoin-usdt/id1624901793
Google Play (Android) - https://play.google.com/store/apps/details?id=com.cropty.droid&pcampaignid=web_share

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Right now we are testing the desktop version of the wallet. It's not ready yet.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Google Chrome extension - https://chromewebstore.google.com/detail/cropty/hdkobeeifhdplocklknbnejdelgagbao

### Is it a hardware wallet?

Cropty is a custodial wallet

### Is the source code for the wallet fully open-source?

No, source code is closed

### What license is the wallet software released under?

https://www.cropty.io/terms-of-services

### Who holds the private keys?

We keep the private keys with us. In case of unforeseen circumstances or closure, we will alert users and ask them to withdraw money from their account.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Cropty bug bounty program - https://www.cropty.io/bug-bounty-program 

### Scam protection?

Cropty uses two-factor authentication, two-factor confirmation of transactions, and double-check of all data entered by the user.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

No

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

Yes, BTC, BNB, ETH, MATIC and TRX for now

### Does the wallet support Ethereum layer 2 networks?

No

### Does the wallet allow the user to customize gas fees?

No, we determine our own fee

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No, Cropty is a custodial wallet

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram - https://t.me/CroptySupportBot
Email - support@cropty.io
Twitter - https://x.com/cropty_app

### What educational resources/documentation do you provide to users?

Terms of service - https://cropty.app/terms-of-services
Privacy policy - https://cropty.app/privacy-policy

### Does the wallet have any integrated tools not mentioned above?

Cropty allows users to earn by lending to other wallet users and receive cryptocurrency backed loans accordingly. 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Bashirkuje-code** [comment]
https://github.com/jlord/sheetsee.js/issues/26

**Comment by wackerow** [comment]
Hey @croptywallet, apologies for the delays here while the team has been working through some large site changes over the past several months. Did not intend to neglect this request.

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation! 🙏
