### ISSUE TITLE
Adding 2 Russian language resources

### ISSUE THREAD

**Issue by UNOFFICIALbgd** [ethereum/ethereum-org-website#11701]
### Is your feature request related to a problem? Please describe.

Russian language resources (https://ethereum.org/en/community/language-resources/) have only one resource, so I want to suggest two more.

### Describe the solution you'd like

- [Forklog](https://forklog.com) - news and educational articles about crypto in general, existing technologies and future upgrades of different blockchains
- [BeInCrypto](https://ru.beincrypto.com) - news, crypto price analysis and non-technical articles with simple explanations about everything in crypto

### Describe alternatives you've considered

Description of the suggested resources can be edited

### Additional context

links for the educational articles:
https://ru.beincrypto.com/learn/
https://forklog.com/cryptorium

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
@UNOFFICIALbgd Sorry for delay here. PR welcome! Assigning you for this

**Comment by wackerow** [comment]
Ah! See you already posted one, but it has been deleted. @UNOFFICIALbgd Mind re-posting the PR you made before with these two new links?

**Comment by wackerow** [comment]
Closed with @13171
