### ISSUE TITLE
Add links to unofficial ecosystem pages

### ISSUE THREAD

**Issue by Maxservais** [ethereum/ethereum-org-website#11700]
### Is your feature request related to a problem? Please describe.

This [page](https://ethereum.org/en/layer-2/) gives an overview of some Generalized layer 2s like Arbitrum, Optimism and Starknet. For each, it links to useful resources (e.g. ecosystem portal).

For Arbitrum, Optimism and Starknet, I suggest adding an additional link to their unofficial ecosystem portal:
- https://www.ethereum-ecosystem.com/blockchains/arbitrum-one
- https://www.ethereum-ecosystem.com/blockchains/optimism
- https://www.ethereum-ecosystem.com/blockchains/starknet

### Describe the solution you'd like

I'd like to suggest additional links for Arbitrum, Optimism and Starknet section.

- [Arbitrum unofficial ecosystem portal](https://www.ethereum-ecosystem.com/blockchains/arbitrum-one)
- [Optimism unofficial ecosystem portal](https://www.ethereum-ecosystem.com/blockchains/optimism)
- [Starknet unofficial ecosystem portal](https://www.ethereum-ecosystem.com/blockchains/starknet)

I believe these links would be a beneficial addition and help people find useful apps and tools built atop those L2s.

### Describe alternatives you've considered

Rather than suggesting the specific links I've mentioned, we could link to other high-quality resources on the topic.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Maxservais** [comment]
Any update on this?

**Comment by wackerow** [comment]
Hey @Maxservais! Thanks for the suggestion here... I had not seen that site before but it looks well put together, clean, and potentially very helpful. Can look into it more, but I'd be okay with this being pursued...
I see you marked "Yes" for contributing to this... I'll go ahead and assign you, just let us know if you change your mind and would like someone else to pick this up

**Comment by Maxservais** [comment]
Hey @wackerow, thanks for your positive feedback on the suggestion! Just submitted a PR: https://github.com/ethereum/ethereum-org-website/pull/12093

Just to give some context, Ethereum-Ecosystem has been in development for over a year. It's received notable support from the Optimism DAO during both Season 4 of grants and RetroPGF3. Also, the official Starknet website directly links to it here: https://www.starknet.io/en/ecosystem/dapps

**Comment by konopkja** [comment]
Hello, I to think this is a good repository for users to find apps, however I think having two links listed there to perform the same function will be confusing UX. The names in the PR look also the same which would not be a good solution.

<img width="1414" alt="Screenshot 2024-02-12 at 23 05 40" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/e402eeb1-6712-49cb-811a-aa3c72ea36eb">

I would suggest instead to include this project in the section "Tools to be effective on layer 2" for now while we think how to maybe restructure this page more in future, where we could give this project a bit of a different prominence. 

<img width="753" alt="Screenshot 2024-02-12 at 23 13 08" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/2a982634-7f2d-4e03-bf5e-911228ad3dac">

@Maxservais would you be up to redoing this  change?

**Comment by konopkja** [comment]
Hi, commented on PR as well. I agree this website looks like a good source, but suggested a different solution linking to the project from "Tools to be effective on layer 2" section instead.

**Comment by Maxservais** [comment]
Hey @konopkja, that makes sense! I'll push a new PR with your suggestion :)

**Comment by Maxservais** [comment]
Hey @konopkja, just submitted a PR: https://github.com/ethereum/ethereum-org-website/pull/12181 Is this what you had in mind?

**Comment by konopkja** [comment]
> Hey @konopkja, just submitted a PR: #12181 Is this what you had in mind?

looks good to me!
