### ISSUE TITLE
Sort out IPFS support

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1171]
**Is your feature request related to a problem? Please describe.**

It appears Gatsby has no solid way to enable IPFS support. See https://github.com/gatsbyjs/gatsby/issues/14161

**Describe the solution you'd like**

Find a way to re-add IPFS support for the site.

Ideally the solution we land on should be integrated within our CI/CD pipeline.
- For now, we've just updated the ethereum.eth ENS content hash to point to https://gateway.pinata.cloud/ipfs/QmVmmSbZVmcWBaDGu93nB2dDPHCCxLmJG1tjeDvrdLggmo/
- This was an effective v1 but in order to keep the ethereum.eth site up to date, we'll want to continually deploy updated versions to IPFS

**Describe alternatives you've considered**

Looks like Fleek provides Gatsby support?
https://docs.fleek.co/Hosting/BuildConfigurations
May be a reasonable fallback if we can't identify a solution ourselves.

In terms of CI, an alternative could be following what the IPFS team uses for their site:
- Circle CI job: https://github.com/ipfs/ipfs-docs-v2/blob/master/.circleci/config.yml
- Docker image: https://github.com/ipfs-shipyard/ipfs-dns-deploy

**Additional context**
We previously added support for VuePress (https://github.com/ethereum/ethereum-org-website/pull/896) but the migration to Gatsby (#1134) creates new challenges here.

**Comment by Blockchainbrett** [comment]
Hey there!

Fleek definitely supports Gatsby sites! [Here's](https://blog.fleek.co/posts/Gatsby-Fleek) a getting started blog post for gatsby sites on Fleek. We also support DNSLink and ENS domains super easily.

**Comment by wackerow** [comment]
Would love to see this re-opened... adding the IPFS plugin is what Gatsby recommends, and the [Fleek docs](https://docs.fleek.co/hosting/domain-management/#ens-domains) seem to indicate they could automatically update the ethereum.eth ENS to point to the latest IPFS hash. 

Ran `yarn add gatsby-plugin-ipfs` on a local branch and added the needed config lines, but not quite sure how to test this.
