### ISSUE TITLE
Bitso Web3 Wallet

### ISSUE THREAD

**Issue by caioflores** [ethereum/ethereum-org-website#11713]
### Wallet name

Bitso Web3 Wallet

### Wallet description

Bitso is launching a new Web3 wallet that will allow users to interact with DeFi. It's an MPC wallet that supports Ethereum main net, Polygon and Arbitrum, 

### Wallet logo

![logo](https://github.com/ethereum/ethereum-org-website/assets/4183877/72d9ebae-c4ff-4edf-9c94-85991076a0e8)

### Background color for brand logo

#FFFFFF

### URL to the project

https://bitso.com/

### When did the wallet go live to users?

It's already live in beta for 4 months and we're make it 100% available in January

### Does the wallet have an active development team?

Yes

### Is the wallet globally accessible?

It's only available in Mexico, Brazil, Colombia and Argetina

### Is the wallet available in multiple languages?

Yes, in English, Spanish and Portuguese

### What social links are there for the project?

Website: https://bitso.com/web3-wallet
Twitter: https://twitter.com/Bitso

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, it'll be accessible through Bitso app on Android and iOS.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No.

### Is it a hardware wallet?

No.

### Is the source code for the wallet fully open-source?

No.

### What license is the wallet software released under?

It's a private product.

### Who holds the private keys?

It's an MPC wallet, so it's self-custody. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We've testing it with 25k users for the last 4 months, if you need more information plz let me know. 

### Has the wallet's smart contract code or security modules been audited?

No.

### Does the wallet have an internal security team?

Yes.

### Scam protection?

Yes, we have firewalls to protect users from accessing suspicious addresses, smart contracts, tokens and dApps.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No.

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, with WalletConnect.

### Does the wallet support staking directly?

No. 

### Does the wallet support swaps directly?

Yes. 

### Does the wallet support multi-chain networks?

No.

### Does the wallet support Ethereum layer 2 networks?

Yes, Polygon, Arbitrum and soon Optimism

### Does the wallet allow the user to customize gas fees?

No.

### Does the wallet support sending transactions to ENS addresses?

No.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, automatically.

### Does the wallet support EIP-1559 (type 2) transactions?

No.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No.

### Does the wallet support withdrawals to fiat?

No.

### Is the wallet a multi-signature wallet?

Yes, users will need to create the wallet and we store a sign key in their devices. To recover the wallet, they need to back it up in Google Drive or iCloud.

### Does the wallet support social recovery?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

You can reach caio.flores@bitso.com.

### Does the wallet have a dedicated support team?

Yes. 

### What educational resources/documentation do you provide to users?

We'll have it soon.

### Does the wallet have any integrated tools not mentioned above?

No.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Hey @caioflores, apologies for the delay here. Team has been working through some large site changes over the past several months and didn't mean to let this fall through.

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation! 🙏
