### ISSUE TITLE
Quiz Result Display Issue on Smaller Screens (e.g., iPhone SE)

### ISSUE THREAD

**Issue by piyushbarve98** [ethereum/ethereum-org-website#11729]
### Describe the bug

Currently experienced a display issue in the quiz result section when accessed on smaller screens. The problem arises as some parts of the image content spill over the question, and we are not able to read it, leading to a compromised user experience, which can be seen in the screenshot I have shared.

### To reproduce

1. Go to 'what is ethereum page'
2. Open it in a screen which is 375 x 667 (Iphone SE) or smaller / do inspect element on you pc.
3. Scroll down to last and see the test you ethereum knowledge section 
4. Take the quiz and give right answers
5. After all the questions are completed it will show results 
6. The question will not be clearly seen as some part of image is overlapping over it.

### Expected behavior

The quiz result screen should be appropriately formatted and displayed without any content overlapping or spilling over the question shown at last. Users should have a seamless experience regardless of their device screen size.

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/69067476/d22e5214-ca52-45e5-96db-13bf82900858)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by TylerAPfledderer** [comment]
This is reproducible. It is a layering context issue as the confetti and the trophy icon are absolute-positioned above all the other content. 

@pettinarip with common screen sizes currently not going below 360px wide (do not see the overlap), this may be an edge case with users possibly still using a device like an iphone 5 that has a 320px wide viewport (can see the overlap). Would you still allow a quick fix here? Based on the current structure of the widget applying padding or margin above the text context at the smallest breakpoint should suffice. What do you think?

**Comment by snowden-fu** [comment]
does my screenshot show problem clearly? My understanding is part of confetti covering part of text.
@TylerAPfledderer @pettinarip @piyushbarve98 

![Screenshot 2023-12-10 at 09 58 03](https://github.com/ethereum/ethereum-org-website/assets/24203166/efed6411-f31c-4005-9f5f-a402fe4e090b)

**Comment by pettinarip** [comment]
Thanks for reporting this issue @piyushbarve98 & @snowden-fu for sharing the screenshot!

@TylerAPfledderer yes, that would be a quick win. I think that with a `2rem` margin we would be fine.

**Comment by piyushbarve98** [comment]
Hii @pettinarip can you assign the issue to me. I'll be glad to fix this.

**Comment by pettinarip** [comment]
Sure! @piyushbarve98 thanks for helping!

**Comment by minimalsm** [comment]
Hey @piyushbarve98, is this still something you're working on?

**Comment by TylerAPfledderer** [comment]
@piyushbarve98 following up to see if you are still looking to resolve this?

At this point, could tie this into #13408

cc @pettinarip I can take this if there are no other takers, and get myself assigned to the other mentioned issue as well
