### ISSUE TITLE
 Adding Chorus One Opus (staking as a service) to Ethereum.org 

### ISSUE THREAD

**Issue by mksh** [ethereum/ethereum-org-website#11724]
### Project name

Chorus One Opus

### Product type

Staking as a service

### Logo

![chorus_logo](https://github.com/ethereum/ethereum-org-website/assets/1139113/83d149c6-a9db-471c-9cf5-31f121ddb33e)

### Description

Staking is one of the easiest and least risky ways to earn rewards on your cryptoassets. However, tracking rewards across multiple networks can be a cumbersome process.

To combat this, OPUS features an intuitive, user-friendly interface that enables users to track real-time rewards data for multiple assets on a single dashboard. Additionally, OPUS offers the highest staking rewards, which include network emissions, transaction fees, and MEV (maximal extractable value).

With just a few clicks, users can earn rewards and download detailed reports on their staking rewards at any time, while retaining unparalleled transparency and control over their assets.

### Website

https://opus.chorus.one

### If software is involved, is everything open source?

Portions of code are open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

The product is out of beta development, fully live and already has multiple users staking millions of dollars in ETH.

### What wallets support the product or service?

All the walletconnect compatible wallets with web access

### If a service, what are the fees associated with using the service?

We currently charge 5% commissions on the rewards earned for the stake.  This commission rates goes down to 4% if a customer stakes more than $5M worth of ETH

### What date did the project or service go live?

May 2023: https://chorus.one/articles/opus-api-what-is-it-and-why-did-we-build-it

### Has the project undergone an external security audit?

We conduct annual security audits and so far we conducted two conducted in the last year

### Has the project undergone any security bug bounties?

No

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

The website dashboard/API are fully non-custodial and OPUS/Chorus One doesn’t take custody of funds ever. The user is free to stake/unstake at any time of their liking.

### If listing a staking-as-a-service, are users required to sign-up for an account?

The users are currently required to sign up to start using OPUS. We’ll be making it permissionless in a few weeks.

### If listing as staking-as-a-service, who has access to the signing keys?

The signing keys are held by Chorus One stored in permissioned Hashicorp Vault storage in a strongly isolated and redundant cloud environment.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

Withdrawal keys in form of 0x01 credentials that point to execution layer address are held exclusively by the customers of the service.

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

Currently, we automatically distribute 50% of customer stake to Lighthouse/Geth clients and 50% to Teku/Neterhmind. There are plans to add support more client pairs and allow customer for choosing client distribution when staking.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

Currently we support Lighthouse and Teku, and distribute validators of the customers evenly among these two clients. We plan to add support for more clients in future, and create a feature that grants ability for customers to choose allocation of their staked ETH to a particular client.

### What platforms are supported?

Any platform with web browser that support walletconnect compatible wallets

### What user interfaces are supported?

All popular web browsers and walletconnect compatible wallets are supported.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
I have one concern/question to ask. I was trying to check out the service by registering on https://opus.chorus.one/portal/login, and I am met with this page

<img width="1116" alt="Screenshot 2024-06-13 at 9 49 33 PM" src="https://github.com/ethereum/ethereum-org-website/assets/15589226/2adae807-2244-440f-ad9e-5e91103eb48d">

Is there something not working at the moment?

**Comment by wackerow** [comment]
I am getting the same issue. This form request was for a service (saas) listing, which seems to be dependent on this form workflow. Going to close this out for now, but @mksh please feel free to @ me or re-open with an update when functional.
