### ISSUE TITLE
Setup Ethereum in numbers for translation on /what-is-ethereum

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#11726]
### Is your feature request related to a problem? Please describe.

Currently the `Ethereum in numbers` section on [/what-is-ethereum](https://ethereum.org/en/what-is-ethereum) isn't setup for translation. This should get set up for translation

![image](https://github.com/ethereum/ethereum-org-website/assets/15589226/ae2970ee-5d8d-4dfb-a15c-e67fa0889aba)

### Describe the solution you'd like

Setup this section for translation

### Describe alternatives you've considered

None, this should be translated

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by fragtex-eth** [comment]
I am interested in working on this issue. Could you please assign it to me?

**Comment by minimalsm** [comment]
Sure, thanks @fragtex-eth 🙏

**Comment by reetbatra** [comment]
@fragtex-eth do you need a hand with this

**Comment by fragtex-eth** [comment]
@reetbatra Thanks, but I am already finished and have opened a Pull Request that just needs to be merged
