### ISSUE TITLE
Adding 01node (staking pool) to Ethereum.org

### ISSUE THREAD

**Issue by Braidlet** [ethereum/ethereum-org-website#11759]
### Project name

01node

### Product type

Staking pool

### If other product type, please describe

DVT STAKING POOL

### Logo

![01node Logo Black](https://github.com/ethereum/ethereum-org-website/assets/90639558/0ec779f6-0c28-43b0-86cf-785083ccd094)

### Description

Dive into the future with our DVT Ethereum staking pool—Enjoy zero commission fees and simplify your staking journey with one-click functionality. Elevate your Ethereum experience today.

### Website

Staking.01node.com

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes, We have successfully completed its beta development phase. This milestone wouldn't have been possible without our incredible community's invaluable feedback and support.

Throughout the beta period, we diligently worked on refining features, addressing user feedback, and ensuring a seamless experience. Your input has been instrumental in shaping our pool into a robust and user-friendly solution.
Here's more details: https://01node.com/01node-ethereum-staking-pool-powered-by-dvt-is-live-on-mainnet/

### What wallets support the product or service?

Rainbow, MetaMask, Wallet connect, Coinbase wallet

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

0.1ETH

### If a service, what are the fees associated with using the service?

Zero commission fees

### If the product or service involved a liquidity token, what are the tokens involved?

The liquid token is nodeETH

### What date did the project or service go live?

14TH NOVEMBER

### Has the project undergone an external security audit?

Yes, we're proud to say that our project has undergone a thorough external security audit by Blaize Security. We've received an exceptional score of 9.7 out of 10. You can review the detailed audit report on the Blaize Security: (https://blaize.tech/clients/smart-contract-security-audit-for-01node/]. This audit underscores our commitment to ensuring the highest standards of security for our project.

### Has the project undergone any security bug bounties?

No, the project has not undergone any security bug bounties. While we continuously prioritize the security and integrity of our project, we are open to feedback and encourage our community to report any potential vulnerabilities directly to our security team.

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

The pool functions in a fully automated way. There are no approvals necessary before any user can stake their tokens. The funds are deposited in the SC of the pool and withdrawal is possible only by the staker.

### If a pooled staking service, can users participate as a node operator without permission?

It is not permission less, it is controlled by the 01node company.

### If listing a staking-as-a-service, are users required to sign-up for an account?

We are a staking pool.

### If listing as staking-as-a-service, who has access to the signing keys?

The pool is permissionless - they only use their wallets to stake funds in the pool. Due to the logic behind it, the service does not gain access to any keys from the user - the keys are generated when depositing a new validator and only the key shards are distributed in the SSV cluster.  The pool SC keeps only the pre signed exit messages for the validators (to be used when users unstake their funds).

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

The withdrawal credentials are to a pre-determined smart contract. From there, the funds are sent to the staker's wallet

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

We do not believe the combination of consensus and execution client presents a dangerous super majority, due to the nature of the DVT being in use.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

No client tooling is required/listed. Supported platforms for clients are the same platforms that support the wallets listed above.

### What platforms are supported?

Linux, macOS, Windows, iOS, Android,

### What user interfaces are supported?

Desktop app, Mobile app

### Social media links

Twitter- https://twitter.com/01node
Telegram- https://t.me/node01
Website- www.01node.com
Linkedin-https://www.linkedin.com/company/01node/
Youtube-https://youtube.com/@01nodestakingvalidator5?si=BL0imZ6bcXKlZRTH

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @Braidlet, appreciate you dropping this request.. Apologies for the delays here; team is still churning through a backlog from Q4 last year.

<img width="1311" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/8dbc610c-e31e-4813-9e0b-2dc15887607b">

I think we need to let this product grow a bit before pushing this to ethereum.org users. Checking the https://staking.01node.com/ site I'm seeing 2 total validators (65 ETH) which limits the reputation that can be elicited here. Would encourage trying to grow this before listing for users on ethereum.org. If/when the product is able to gain some traction please don't hesitate to re-open, thanks!
