### ISSUE TITLE
Request for Updating Exodus Wallet Features on Ethereum.org

### ISSUE THREAD

**Issue by kananrmaze** [ethereum/ethereum-org-website#11785]
Dear Ethereum.org Team,

I hope this email finds you well. My name is Kanan, and I am writing on behalf of Exodus, a leading provider in the cryptocurrency wallet space. We greatly appreciate having our wallets listed on your esteemed platform, Ethereum.org, as one of the supported wallets for Ethereum. This recognition is not only an honor but also a testament to the hard work and dedication our team has put into developing a robust and user-friendly wallet.

However, I would like to bring to your attention that the current listing of Exodus Wallet features on your website appears to be based on older information. We have recently made significant advancements in our wallet's capabilities, which are not yet reflected on Ethereum.org. These updates include support for all Layer 2 solutions, and fiat off-ramp options (allowing users to sell for fiat), and we are excited to announce that we are in the final stages of introducing Ethereum staking, which will be available very soon.

We believe that updating this information on your website will not only provide your users with the most current and accurate data but will also showcase the continuous efforts we make at Exodus to stay at the forefront of technological advancements in the cryptocurrency wallet space.

We understand that such updates require verification and we are more than willing to provide any necessary information or assistance to facilitate this process. Our team is readily available to answer any queries or provide detailed insights into our new features.

Thank you very much for your attention to this matter. We are looking forward to continuing our fruitful collaboration with Ethereum.org and contributing to the Ethereum community. Please feel free to reach out to us at kanan@exodus.com for any further information or clarification.

Best regards,

Kanan Babayev
Exodus Wallet Marketing Team

**Comment by corwintines** [comment]
Thanks @kananrmaze 

Can you fill your current wallet state using the issue for wallets: https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet
