### ISSUE TITLE
Add/Update/Delete quiz question

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#11798]
### Page URL

https://ethereum.org/en/nft/

### Question content

i want a question about bored apes

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by bhargavkakadiya** [comment]
Sure here is one

Question:
What feature is unique to the Bored Ape Yacht Club NFTs?
Options:
A) They can be used as currency.
B) They offer 3D printing of the apes.
C) Ownership grants access to an exclusive social club.
D) They are the only NFTs that can be displayed in virtual reality.

**Comment by WebSculptor** [comment]
Hi I would love to work on this
