### ISSUE TITLE
Suggestion to list Everstake 0.1+ ETH staking on ethereum.org under a staking pool category

### ISSUE THREAD

**Issue by irina-everstake** [ethereum/ethereum-org-website#11825]
### Project name

Everstake 0.1+ ETH staking

### Product type

Staking pool

### Logo

In attachment:
![Everstake-Logo-Reversed](https://github.com/ethereum/ethereum-org-website/assets/129885952/3ae4889e-fbb0-42b5-a362-0c7afb014fb7)
![Everstake-Logo-Reversed](https://github.com/ethereum/ethereum-org-website/assets/129885952/c6623263-27db-421a-b1b8-16639f4c1cfe)
![Everstake-Logo](https://github.com/ethereum/ethereum-org-website/assets/129885952/778221de-e8b8-4f74-bd5f-06f1632420ee)
![Everstake-Logo](https://github.com/ethereum/ethereum-org-website/assets/129885952/6650b10a-899c-4119-b255-526de8d7699e)

### Description

Easy and safe, Everstake ETH staking solution allows everyone to stake Ethereum with as little as 0.1 ETH. 

Unlock network-leading APR in 1-click, from the #1 performing provider across PoS assets.

### Website

https://stake.everstake.one/ethereum/

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

In production lifecycle

### What wallets support the product or service?

MetaMask, WalletConnect supported wallets, Exodus

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

Minimum stake – 0.1 ETH

### If a service, what are the fees associated with using the service?

Our commission for 0.1+ ETH staking is 10% of rewards-generated.

### What date did the project or service go live?

September 14, 2023. Please find the public announcement on our official Twitter account: https://twitter.com/everstake_pool/status/1702349102795686237 

### Has the project undergone an external security audit?

Yes. Our 0.1+ ETH staking solution has been audited by ChainSecurity, ensuring it meets industry standards for safety and reliability. This adds an extra layer of confidence for our users. Link to report: https://chainsecurity.com/security-audit/everstake-eth-b2c-staking/ 

Our staking platform also passed an audit by Ackee, affirming its security and operational excellence. This further boosts the security of Everstake's staking experience. Report could be found here: https://ackeeblockchain.com/blog/everstake-ethereum-staking-protocol-audit-summary/ 

### Has the project undergone any security bug bounties?

No

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Everstake's solution is free of trusted/human intermediaries.

### If a pooled staking service, can users participate as a node operator without permission?

There is no option to run an operator within the pool by some user. The only node operator is Everstake, which is responsible for running all validators for staked ETH.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

Within our ETH staking solution rewards from all validators goes to a predefined address in the smart contract. We solely use Withdraw Authority / execution address, known as “type 1” withdrawal credentials.

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

We run 60% of Geth and 40% of Nethermind on the EL. As for CL, we prefer using Prysm client: https://www.rated.network/o/Everstake?network=mainnet&timeWindow=1d&idType=nodeOperator#:~:text=0-,Client%20distribution,-0 

### What platforms are supported?

All

### What user interfaces are supported?

Our own web app; browser extensions; mobile, desktop and web apps that integrated with our solution

### Social media links

Twitter - https://twitter.com/everstake_pool 
Discord - https://discord.gg/PqrbhKNpA5 
Medium - https://medium.com/everstake 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by irina-everstake** [comment]
@wackerow, Paul, hello! Can you please take a look at these request?

**Comment by irina-everstake** [comment]
This request is live. Response from Jakub Konopka:

"Hello, I know this is frustrating situation. It is indeed taking a long time. Please be patient with us, we are well aware of this request, but there are still other issues and work that needs to be reviewed first. We will get to this eventually."

**Comment by wackerow** [comment]
@irina-everstake Apologies for delays, this looks good. Am a little curious to learn more about the up to 10% APR claims—do you happen to have evidence behind this claim?

I see you marked "yes" to wanting to work on this... a PR is welcome for the next step, I went ahead and assigned you... To help out, I've parsed the above into the format we use for the saas products:

```json
    {
      "name": "Everstake",
      "imageName": "Everstake",
      "hue": 43,
      "launchDate": "2023-09-14",
      "url": "https://stake.everstake.one/ethereum/",
      "audits": [
        {
          "name": "ChainSecurity 2023",
          "url": "https://chainsecurity.com/security-audit/everstake-eth-b2c-staking/",
        },
        {
          "name": "Ackee 2023",
          "url": "https://ackeeblockchain.com/blog/everstake-ethereum-staking-protocol-audit-summary/"
        }
      ],
      "minEth": 0.1,
      "additionalStake": null,
      "additionalStakeUnit": null,
      "monthlyFee": 10,
      "monthlyFeeUnit": "% rewards",
      "isFoss": false,
      "hasBugBounty": false,
      "isTrustless": true,
      "isPermissionless": true,
      "pctMajorityExecutionClient": 60,
      "pctMajorityConsensusClient": 100,
      "isSelfCustody": true,
      "platforms": ["Browser"],
      "ui": ["GUI"],
      "socials": {
        "discord": "https://discord.gg/PqrbhKNpA5",
        "twitter": "https://twitter.com/everstake_pool",
        "medium": "https://medium.com/everstake"
      },
      "matomo": {
        "eventCategory": "StakingProductCard",
        "eventAction": "Clicked",
        "eventName": "Clicked Everstake go to link"
      }
    },
```

Feel free to adjust if you see anything wrong, but in either case this would need to go into the `saas:` section of `src/data/staking-products.json`... Would also need an icon, which can be a little tricky how we have it set up, but it would need to go into `src/components/icons/staking/EverstakeGlyphIcon.tsx`. This will be rendered next to the product name, so I would recommend only using the actual logo, minus the text portion.

Let us know if you have issues or need a hand with any of this!

**Comment by irina-everstake** [comment]
@wackerow, hello! I appreciate your help and support here.  
Sharing with you the link to the contract, as you requested in Discord - https://etherscan.io/address/0xd523794c879d9ec028960a231f866758e405be34

Regarding APR - we even covered this in our article: https://everstake.one/blog/13-apr-on-ethereum-luck-or-the-result-of-partnering-with-a-reliable-validator including links. Hope this helps!

As of checking our card, my colleague will step in and help, providing a slightly updated version for pctMajorityExecutionClient (currently we have 50% Geth, here is the proof: https://twitter.com/everstake_pool/status/1759955444716408863) and platforms, as well as the icon.

Thanks one more time!

**Comment by omykhailovskyi** [comment]
Hey, @wackerow 

Sending you links to our logos if necessary, please choose the most appropriate:

img
https://everstake.one/img/Everstake-logo.svg
https://everstake.one/img/Everstake-256.png
https://everstake.one/img/Everstake-1024.png
logo
https://everstake.one/logo/logo-big-black.svg
https://everstake.one/logo/logo-big-white.svg
https://everstake.one/logo/logo-small-white.svg
https://everstake.one/logo/logo-small-black.svg


Adding few changes here:
1. Changed Discord link - https://discord.gg/NvcW47V3Xb
2. Changed Platforms - added Wallet (as we have an integrations with several wallets, like Exodus and others)
3. Changed the value for Execution Clients Majority to 50


    {
      "name": "Everstake",
      "imageName": "Everstake",
      "hue": 43,
      "launchDate": "2023-09-14",
      "url": "https://stake.everstake.one/ethereum/",
      "audits": [
        {
          "name": "ChainSecurity 2023",
          "url": "https://chainsecurity.com/security-audit/everstake-eth-b2c-staking/",
        },
        {
          "name": "Ackee 2023",
          "url": "https://ackeeblockchain.com/blog/everstake-ethereum-staking-protocol-audit-summary/"
        }
      ],
      "minEth": 0.1,
      "additionalStake": null,
      "additionalStakeUnit": null,
      "monthlyFee": 10,
      "monthlyFeeUnit": "% rewards",
      "isFoss": false,
      "hasBugBounty": false,
      "isTrustless": true,
      "isPermissionless": true,
      "pctMajorityExecutionClient": 50,
      "pctMajorityConsensusClient": 100,
      "isSelfCustody": true,
      "platforms": ["Browser", "Wallet"],
      "ui": ["GUI"],
      "socials": {
        "discord": "https://discord.gg/NvcW47V3Xb",
        "twitter": "https://twitter.com/everstake_pool",
        "medium": "https://medium.com/everstake"
      },
      "matomo": {
        "eventCategory": "StakingProductCard",
        "eventAction": "Clicked",
        "eventName": "Clicked Everstake go to link"
      }
    },



Would it be possible to list us in both "Staking as a service" and "Pooled staking sections"?
Thank you in advance!

**Comment by wackerow** [comment]
@omykhailovskyi  could you help clarify, can users deposit 32 ETH to have their own dedicated validators account? Or do the funds pool together with proportionally shared rewards?

**Comment by omykhailovskyi** [comment]
Yes, we provide such service for our Institutional clients as per request.

**Comment by wackerow** [comment]
Okay, my apologies, I see that now... This PR is for pools, and #10220 is for SaaS.

Don't see why that would be an issue. Thanks for the info @omykhailovskyi; I can get a PR up for these to help move things along.

**Comment by omykhailovskyi** [comment]
Thank you in advance!, @wackerow

**Comment by felipesocha** [comment]
My ETH staking is pending for over 60 days.
Transaction hash: 0x6ed9642baeada690db3388243dfec0ebdd7d771a22cc72d757e1630041b0b9ae

Why is it still not active?
Is it stuck in contract or batching process?

**Comment by felipesocha** [comment]
> My ETH staking is pending for over 60 days. Transaction hash: 0x6ed9642baeada690db3388243dfec0ebdd7d771a22cc72d757e1630041b0b9ae
> 
> Why is it still not active? Is it stuck in contract or batching process?

My staking transaction has already been deposited into the Beacon Chain (32 ETH validator created).

However, after 60 days, my stake is still shown as "pending" and I am receiving no rewards.

Please clarify:
- Which validator is associated with my deposit?
- Why is it not active in my account?
- When will rewards start being distributed?

TX: https://etherscan.io/tx/0x6ed9642baeada690db3388243dfec0ebdd7d771a22cc72d757e1630041b0b9ae

**Comment by omykhailovskyi** [comment]
Hey, @felipesocha 
Your stake should be activated in 1 days and 8 hours
You can track the validator on beaconcha.in
https://beaconcha.in/validator/0xb5ecc3fbd0b8259a9b956f86ea0cb6933a268336168ce2d455c50371ab4c0c62d619565a6628faa36c21c3239301bd24#deposits
Feel free to reach us if you have any additional questions: https://everstake.one/contact-us

**Comment by felipesocha** [comment]
My ETH staking is pending.
Transaction hash: 
0xed37ca11f51fcde21b9045b49c03b6eda602a9162dd93d09f02c833da71bd4e0

Please clarify:
Which validator is associated with my deposit?
Why is it not active in my account?
When will rewards start being distributed?
