### ISSUE TITLE
ADD: Asgardex to find a wallet 

### ISSUE THREAD

**Issue by Thorian1te** [ethereum/ethereum-org-website#11827]
### Wallet name

Asgardex

### Wallet description

Wallet & Exchange client for Thorchain
- https://github.com/asgardex/asgardex-desktop

### Wallet logo

![1024x1024](https://github.com/ethereum/ethereum-org-website/assets/100335276/c32caa2e-1043-4f13-9bcd-f9c6e291dca3)

### Background color for brand logo

#000000

### URL to the project

https://github.com/asgardex/asgardex-desktop

### When did the wallet go live to users?

2019

### Does the wallet have an active development team?

yes

### Is the wallet globally accessible?

yes

### Is the wallet available in multiple languages?

yes

### What social links are there for the project?

@Asgardex - twitter 

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

no

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

yes - supports windows | Mac | linux

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

no

### Is it a hardware wallet?

no

### Is the source code for the wallet fully open-source?

https://github.com/asgardex/asgardex-desktop

### Who holds the private keys?

Users 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Its OSS

### Has the wallet's smart contract code or security modules been audited?

No smart contracts in this wallet 

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

no

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

no

### Does the wallet support staking directly?

Only with Thorchain Savers

### Does the wallet support swaps directly?

Swaps via thorchain

### Does the wallet support multi-chain networks?

yes

### Does the wallet support Ethereum layer 2 networks?

no

### Does the wallet allow the user to customize gas fees?

no

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

no

### Does the wallet support withdrawals to fiat?

no

### Is the wallet a multi-signature wallet?

no

### Does the wallet support social recovery?

no

### Who can the ethereum.org team can contact regarding the wallet in future?

@Asgardex

### Does the wallet have a dedicated support team?

issue board at https://github.com/asgardex/asgardex-desktop

### What educational resources/documentation do you provide to users?

https://youtu.be/hlox7PCZLKo

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Hey @Thorian1te, apologies for the delays here. The team has been working through some large changes to the site over the past several months; didn't mean to let this fall through the cracks.

Appreciate your wallet suggestion, but a few things have been update lately. 

The ethereum.org [wallet listing policy](https://ethereum.org/en/contributing/adding-wallets/) has recently been updated, along with our GitHub issue template used for requesting a wallet.

We kindly request that you [use this updated template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&projects=&template=suggest_wallet.yaml&title=Suggest+a+wallet) to re-file your request with all the latest required fields, and the request will be enqueued for review. (This can also be found by going to the repo "Issues" on GitHub, choosing "New Issue" and selecting "Suggest a wallet".)

Thank you for your understanding and cooperation! 🙏
