### ISSUE TITLE
Site Translation: Add Portuguese (v1.0)

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1182]
**Is your feature request related to a problem? Please describe.**
Portuguese translations have completed review & are ready to be added to the website!

**Describe the solution you'd like**

Portuguese translations have completed review & are ready to be added to the website!

1. Download the [files from CrowdIn](https://crowdin.com/project/ethereumfoundation/pt-PT#) for this version of the content (`Contents v.1.0`) - here's a [screenshot showing how](https://share.getcloudapp.com/ApujZjyn). You may need to sign up for Crowdin & join our project in order to download the files - here's the [invite link](https://crowdin.com/project/ethereumfoundation/invite).
2. Create new directory: /src/content/translations/pt/
3. Copy in the v1.0 Crowdin files
- Copy the markdown files into the new /src/content/translations/pt/ directory, keeping the same directory structure as in Crowdin (i.e. the subdirectories & index.md filenames)
- Rename the /beginners/ directory to /what-is-ethereum/ (i.e. /src/content/translations/pt/what-is-ethereum/)
- Delete the root index.md file (i.e. /src/content/translations/pt/index.md)
- Copy the strings.json file (from Crowdin Contents v1.1) into the /src/intl/ directory & rename as pt.json (i.e. /src/intl/pt.json)
4. Within the frontmatter of each newly added markdown file...
  - Update the `lang` property (it should be `pt`)
	- Remove any `og:title` or `og:description` properties - replace with just `title` & `description`
  - Set all `sidebar` fields to `true` (vs. `auto`)
	- Increase all `sidebarDepth` fields by 1 (e.g. 0 --> 1, 1 --> 2)
5. Update all relative links of the new markdown files to include the language path by running our [script](https://github.com/ethereum/ethereum-org-website/blob/dev/scripts/updateInternalLinks.js), i.e. run `yarn update-internal-links ml` from the root of the project 
6. Add an object to the languageMetadata object within /src/translations/utils/:
```
pt: {
    version: 1.0,
    language: "Português",
    "language-english": "Portuguese",
  },
```

**Describe alternatives you've considered**

**Additional context**

**Comment by developerfred** [comment]
@samajammin I would love to do this implementation assign on this task
