### ISSUE TITLE
Add "Road to Devcon Grants" resource on /community/events 

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#11838]
### Description
Add Road to Devcon Grants [website](https://esp.ethereum.foundation/devcon-grants) to the [Community Events page](https://ethereum.org/en/community/events/) on ethereum.org.

### Potential ideas/implementations

~~**a.** Below the "[Ethereum meetups](https://ethereum.org/en/community/events/#meetups)" table~~
~~- Include the following text (suggestion, feel free to change) below the "_Interested in starting your own meetup? Check out the (...)_" paragraph:~~

~~`Are you based in or close to Southeast Asia? Then check it out the [Road to Devcon Grants](https://esp.ethereum.foundation/devcon-grants) and support Ethereum education initiatives prior to Devcon 7.
`~~

**b.** Create a banner on the Community Events page
- Banner inspo: https://github.com/ethereum/ethereum-org-website/issues/11316
- Suggested banner copy (feel free to edit):

`The Road to Devcon Grants support Ethereum education initiatives in and close to Southeast Asia  🌏🦄  Learn more [here](https://esp.ethereum.foundation/devcon-grants). `

### More info
This request has been originally suggested by EF's Devcon team

### Would you like to work on this issue?

- [ ]  Yes
- [x]  No

**Comment by wackerow** [comment]
+1 for banner
