### ISSUE TITLE
What is Ethereum redesign

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1183]
This page is part of an overhaul of the `Individuals` section of etheruem.org. This overhaul aims to improve the reading experience of the content and make it more engaging. Part of this is to increase the amount of native content on the site that answers user questions rather than linking them off to other sites. 

The `What is Ethereum?` page needs to work seamlessly with other pages in the section to create a holistic "introduction to Ethereum and its concepts" experience.

**Design goals**

1. Explain Ethereum clearly with minimal jargon and introduce the required concepts with jumping off points for more information
2. Help a user understand why they should care about Ethereum by explaining its benefits
3. Give a clear next step whether that's an action (to download a wallet) or more information (read about dapps)
4. Help users try Ethereum  
5. Provide clear paths for technical users to get more technical information: do we need a how-ethereum-works sub-page?
6. Make the page more visually exciting than a "readme"

**Additional context**

WIP design:
![image](https://user-images.githubusercontent.com/40891631/86897384-3ebd2c80-c0ff-11ea-92b2-0dc5f15c4d39.png)

https://www.figma.com/file/u38N56UmJeNi5qamwouYOS/Ethereum?node-id=213%3A0

**Comment by samajammin** [comment]
Solved in #1181
