### ISSUE TITLE
Add a quizz about DAOs

### ISSUE THREAD

**Issue by JanetMo** [ethereum/ethereum-org-website#11836]
### Page URL

https://ethereum.org/en/quizzes/

### Question content

I want to suggest adding a learning quiz about DAOs.

Here's the draft of the questions: https://docs.google.com/document/d/1gQf-u3T_zf9oD2Tm-4I_9IPcdzB046Tu0OAxKA5Pq4Q/edit?usp=sharing

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by aboutmydreams** [comment]
LGTM
