### ISSUE TITLE
ADD: 3SWallet to find a wallet

### ISSUE THREAD

**Issue by Thinhnguyen185** [ethereum/ethereum-org-website#11863]
### Wallet name

3S Wallet: Crypto DeFi Wallet

### Wallet description

3S Wallet is a multi-chain crypto wallet researched and developed by BHO Network based on 3 criteria Simple - Secure - Safe, aiming to be a comprehensive product in terms of technology, security and user experience.

### Wallet logo

[![image](https://github.com/ethereum/ethereum-org-website/assets/97153290/08308b1f-45a9-4a87-9fc5-8946ae387b1e)
](https://3swallet.com/assets/icons/logo.svg)

### Background color for brand logo

rgba(209,12,120,1)

### URL to the project

https://3swallet.com

### When did the wallet go live to users?

08/06/2022

### Does the wallet have an active development team?

yes

### Is the wallet globally accessible?

no kyc

### Is the wallet available in multiple languages?

vietnamese, english, chinese

### What social links are there for the project?

[Facebook](https://www.facebook.com/3SWallet)
[Telegram](https://t.me/EN_3SWallet)
[TwitterX](https://mobile.twitter.com/3S_Wallet)

## App ready on store
[Play Store](https://play.google.com/store/apps/details?id=network.bho.wallet&pli=1)
[App Store](https://apps.apple.com/us/app/3s-wallet-crypto-defi-wallet/id1622316272)

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

3SWallet don't support desktop 

### Is the source code for the wallet fully open-source?

No, Private source

### What license is the wallet software released under?

MIT

### Who holds the private keys?

User hold your key

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No, App support multi rpc listed

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

no

### Does the wallet support withdrawals to fiat?

no

### Is the wallet a multi-signature wallet?

No, EOA Wallet

### Does the wallet support social recovery?

No

## App ready on store
[Play Store](https://play.google.com/store/apps/details?id=network.bho.wallet&pli=1)
[App Store](https://apps.apple.com/us/app/3s-wallet-crypto-defi-wallet/id1622316272)

### Does the wallet have a dedicated support team?

NO

### Does the wallet have any integrated tools not mentioned above?

No

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Thinhnguyen185** [comment]
Just following up on this ticket. Any updates or timeline on when this will be addressed?
Thank you!

**Comment by corwintines** [comment]
This is largely unfilled. Leaving this closed.
