### ISSUE TITLE
Fix errors on 'Active areas of research' page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#11875]
### Describe the bug

There are two errors on the _Active areas of Ethereum research_ page:
- 'Verkle' is misspelled as 'Verkel'
- There is a missing comma in the Community, education and outreach section

### To reproduce

Verkle typo
1. Go to https://ethereum.org/en/community/research/#recent-research-1
2. Check the 4th item on the list
3. See error

Missing comma
1. Go to https://ethereum.org/en/community/research/#community-education-and-outreach
2. Read the first paragraph
3. See error

### Expected behavior

- 'Verkel' should be changed to 'Verkle'
- A comma should be added (**...memes, teaching resources, events...**) in the following sentence:
_This might include blog posts and articles, books, podcasts, memes, teaching resources events and anything else that builds communities, welcomes new starters and educates people about Ethereum._

### Screenshots

<img width="763" alt="Screenshot 2024-01-05 at 15 27 56" src="https://github.com/ethereum/ethereum-org-website/assets/37338979/7c61faa7-4c20-4a0a-9017-f167c2e876ca">
<img width="346" alt="Screenshot 2024-01-05 at 15 28 17" src="https://github.com/ethereum/ethereum-org-website/assets/37338979/de510327-e495-4b37-9dfb-a52540151ed3">

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by MukulKolpe** [comment]
Hey @lukassim, can I work on this issue?

**Comment by GDGouravDey** [comment]
This is an easy issue and I am confident I can solve this. You can assign me this.

**Comment by corwintines** [comment]
Closed in above PR
