### ISSUE TITLE
Add EOA address char count with an example

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#11877]
It is stated for the [contract accounts](https://ethereum.org/en/developers/docs/accounts/#contract-accounts) but not for [EOAs](https://ethereum.org/en/developers/docs/accounts/#account-creation). It is implicit for EOAs - that require additional knowledge for byte conversion. Adding it would make it clear and an example would make it easier to understand.

**Comment by wackerow** [comment]
I like this suggestion! Opening up for a contributor with the following scope:

- [ ] Edit https://ethereum.org/en/developers/docs/accounts/ within `#account-creation` adding a section for externally owned accounts (EOAs) have a 42-character address, adding a neutral example
- [ ] Optionally fix "42 character" -> "42-character"
- [ ] Optionally expand on this to clarify it's a 20-byte segment, which is 40 hexadecimal characters, or 42 total characters with the `0x`

**Comment by Shiva-Sai-ssb** [comment]
Submitted PR for this. @wackerow 
Please review it and let me know if any changes required.
