### ISSUE TITLE
Ethereum meetups open in same tab

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#11902]
### Describe the bug

On the [meetups section of the events page](https://ethereum.org/en/community/events/#meetups) when you select a meetup, the external link opens in the same tab

### To reproduce

1. Go to https://ethereum.org/en/community/events/#meetups
2. Click on a meetup
3. Redirects in same tab to meetup page

### Expected behavior

When clicking on a meetup, it should open that page in a new tab since its an external link. Only internal links should open in the same tab. 

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by lucas-amberg** [comment]
If this is something that needs to be done I can work on it 👍

**Comment by kamuik16** [comment]
> ### Describe the bug
> On the [meetups section of the events page](https://ethereum.org/en/community/events/#meetups) when you select a meetup, the external link opens in the same tab
> 
> ### To reproduce
> 1. Go to https://ethereum.org/en/community/events/#meetups
> 2. Click on a meetup
> 3. Redirects in same tab to meetup page
> 
> ### Expected behavior
> When clicking on a meetup, it should open that page in a new tab since its an external link. Only internal links should open in the same tab.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Would you like to work on this issue?
> * [ ]  Yes
> * [x]  No

Hey, I have opened a PR fixing this issue. 
PR: https://github.com/ethereum/ethereum-org-website/pull/11908
