### ISSUE TITLE
Investigate & upgrade `next-mdx-remote` to v4

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#11938]
**Important:** we can't upgrade to v4 with the current code as it is. See ethereum/ethereum-org-fork#18 for more details about why we downgraded to v3.

Investigate how to fix the issues we have with `next-mdx-remote` v4 and upgrade it https://github.com/hashicorp/next-mdx-remote

We could potentially replace `gray-matter` since the new version can parse frontmatter as well and simplify a bit the code.

```ts
const mdxSource = await serialize(source, { parseFrontmatter: true })
```

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting for assignment, per private discussion, and I will attempt to use my suggestion above to see what effect it has at this point.

**Comment by pettinarip** [comment]
@TylerAPfledderer assigned, thanks!

**Comment by wackerow** [comment]
Closing via this comment: https://github.com/ethereum/ethereum-org-website/pull/12055#issuecomment-2142046046
