### ISSUE TITLE
Various sync strategies are listed but not explained

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#12003]
In [the Nodes and Clients section of Developer Documents](https://ethereum.org/developers/docs/nodes-and-clients) There is a table comparing different execution clients under [Execution Clients](https://ethereum.org/developers/docs/nodes-and-clients#execution-clients). Until that point, the only part mentioned about sync strategies is "There are also options of different sync strategies which enable faster synchronization time. Synchronization refers to how quickly it can get the most up-to-date information on Ethereum's state." in [the Node Types](https://ethereum.org/developers/docs/nodes-and-clients#node-types)
In the table mentioned, there is a column for Sync Strategies, and these types are listed: Snap, Snap (without serving), Fast, Full. 
It would be helpful to define what those types mean

**Comment by wackerow** [comment]
Agree, thanks @aslikaya! Opening up for community contribution with the following scope:

- [ ] Section added to [Nodes and Clients](https://ethereum.org/en/developers/docs/nodes-and-clients/) page about sync types, with brief explainer for each.
- [ ] Optionally add external resources where the reader can learn more.

**Comment by m4sterbunny** [comment]
https://github.com/ethereum/ethereum-org-website/pull/13201
