### ISSUE TITLE
Add social sharing images to page metadata

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1202]
**Is your feature request related to a problem? Please describe.**

When I share a page on social media or in things like discord chats, an image should be rendered alongside the page title and description.

![image](https://user-images.githubusercontent.com/40891631/87319927-2d6e8880-c522-11ea-9c23-dec801c25140.png)

**Comment by samajammin** [comment]
Ya good call, looks like this broke w/ the Gatsby migration (#1134)

For one, the default site image is broken:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/PageMetadata.js#L94
Which we set here:
https://github.com/ethereum/ethereum-org-website/blob/dev/gatsby-config.js#L16

I think the ideal solution we want is mentioned in this issue: https://github.com/gatsbyjs/gatsby/issues/13359
Where depending on the given page's hero/featured image, we pass that to the `<PageMetadata/>` component. That way we can customize depending on the page vs. showing that same default site image for every page like we did previously.
