### ISSUE TITLE
Upgrade to Next v14

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#12024]
During the NextJS migration we had to downgrade to v13 because [we had an issue at build time](https://github.com/ethereum/ethereum-org-fork/pull/218) when using `revalidate` with v14.

The error seems to be related to the [`next-runtime` Netlify plugin](https://github.com/netlify/next-runtime/issues) (`@netlify/plugin-nextjs`) that currently has [many issues](https://github.com/netlify/next-runtime/issues) with v14. We are using `@netlify/plugin-nextjs@4.41.3` atm.

We might need to keep track of the [releases](https://github.com/netlify/next-runtime/releases) and try to bump the Next version once they get it fixed or have a more stable version with v14.

**Comment by TylerAPfledderer** [comment]
Noting here https://github.com/ethereum/ethereum-org-website/pull/12266 showing current deployment issues when attempting to upgrade

**Comment by pettinarip** [comment]
Done in #12266
