### ISSUE TITLE
Consolidate `FileContributors` logic

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#12021]
GitHub and Crowdin file contributors components have been updated, but logic is duplicated in the Docs and Tutorials files. 

Ideally we have one component that is placed in each of these files that we feed the necessary information to, and then inside that it determines exactly which data to display, *rather than* having conditional logic that decides whether to render [`GitHubContributors`](https://github.com/ethereum/ethereum-org-website/blob/quiz-types/src/components/GitHubContributors.tsx) or [`CrowdinContributors`](https://github.com/ethereum/ethereum-org-website/blob/quiz-types/src/components/CrowdinContributors.tsx), and having each of these consume the styling component [`FileContributors`](https://github.com/ethereum/ethereum-org-website/blob/quiz-types/src/components/FileContributors.tsx).

cc @wackerow

**Comment by wackerow** [comment]
Closed with #12969 and #12942
