### ISSUE TITLE
Bug report: Region-specific browser language preferences are being ignored

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12027]
### Describe the bug

The `next/router` plugin automatically checks the preferred language/region for the users browser when going to ethereum.org, and forwards the user to the matching locale if available.

In cases where this browser preference contains region-specificity (ie. `pt-BR` for _Brazilian_ Portuguese) users _should_ be redirected to this region (if available, ie. `/pt-br`), but is instead being directed to the root language `/pt` instead.

### To reproduce

1. Set your browser language to Portuguese Brazilian (pt-br), or Chinese Traditional (zh-tw) (use a new browser profile if needed, or clear cache / use a private browser window)
2. Go to https://ethereum.org (without any language in the path)
3. Notice the page forwards to https://ethereum.org/pt (or https://ethereum.org/zh if Chinese Traditional was used)

### Expected behavior

If browser preference contains a region that is in our list of supported locales, the user should be forwarded to the region-specific path (ie. Brazilian Portuguese should direct ethereum.org to ethereum.org/pr-bt, not ethereum.org/pt).

### Desktop (please complete the following information)

- macOS Sonom 14.2.1
- Brave 1.62.153

### Additional context

This may be related to the `next-i18next.config.js` settings, potentially a side-effect of the `cleanCode`, `load` or `lowerCaseLng` properties but haven't investigated much further yet. 

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by HiroyukiNaito** [comment]
I could reproduce the bug in WIndows

- Microsoft Windows 11 Home v10.0.22621 N/A ビルド 22621
- Release Notes v1.62.153 (Jan 25, 2024)

**Comment by HiroyukiNaito** [comment]
I would pick this issue.

**Comment by HiroyukiNaito** [comment]
It could suppress the issue by the JSON order  pt-br -> pt -> zh-tw -> zh (Prioritizing hyphen language order)
