### ISSUE TITLE
Feedback Widget Causes Horizontal Scrolling

### ISSUE THREAD

**Issue by ArianHamdi** [ethereum/ethereum-org-website#12035]
### Describe the bug

Hovering over the feedback widget element results in an unsightly horizontal scrollbar. This only occurs when the window size is smaller than the max-width of the body.

### To reproduce

1. Visit https://ethereum.com/.
2. Hover over the feedback widget element.
3. Notice the jump due to the horizontal scrollbar.

### Expected behavior

The widget should not create a horizontal scrollbar, and hovering over it should be a smooth experience.

### Screenshots

https://github.com/ethereum/ethereum-org-website/assets/59548833/3a948529-7010-4e6d-bfad-d7d4bb1f6cf7

### Desktop (please complete the following information)

- OS : macOS 14.3
- Browser : Edge 120

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by ArianHamdi** [comment]
Hi @pettinarip,

Thank you for taking the time to check this issue.

I agree with you, and I think resolving the root problem is better.

I tried your idea for fixing this, but it didn't work the way I expected. When applying the transform to children instead of sticky parent, it still causes a scrollbar.

This was a bit tricky, and I found two solutions for this bug.

**Solution 1:**
Move the widget to the left side of the area and bring it back to the right side using the left property. In this scenario, hovering over it won't cause a scrollbar to appear.

You can see the changes here: [solution 1](https://github.com/ArianHamdi/ethereum-org-website/pull/2/files).

**Solution 2:**
Apply `transform-origin: right bottom`. In this scenario, when hover occurs, the widget element gets scaled up from the left and the upper side and doesn't cause a scrollbar. In this solution, the hovering animation is a bit different.

You can see the changes here: [solution 2](https://github.com/ArianHamdi/ethereum-org-website/pull/1/files).

Whichever solution you think is more acceptable, I can create a PR with that implementation.

**Comment by pettinarip** [comment]
@ArianHamdi awesome! thanks for sharing this. Both solutions work great, I think the 1st solution works well while keeping the same animation. So, I'd go with that approach.

**Comment by ArianHamdi** [comment]
> @ArianHamdi awesome! thanks for sharing this. Both solutions work great, I think the 1st solution works well while keeping the same animation. So, I'd go with that approach.

@pettinarip Thanks!
I opened a PR with first solution implementation: #12052
