### ISSUE TITLE
Change formatting of the table header

### ISSUE THREAD

**Issue by Satglow** [ethereum/ethereum-org-website#12045]
### Is your feature request related to a problem? Please describe.

The table heading appears with capital letter for translated pages too, however this is an English rule. In other language this could mean acronyms or specific expressions instead of common words. Can you change this formatting so that the translators decide how to write them in their own lang? Currently this is not visible during translation, moreover it makes the suffixes also in capital letter that is meaningless.

For example on the NFT page https://ethereum.org/en/nft

![Table heading](https://github.com/ethereum/ethereum-org-website/assets/151942349/152db371-e369-442e-830d-7a23b8c35518)

### Describe the solution you'd like

The heading appear as it is translated.

### Describe alternatives you've considered

None.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by corwintines** [comment]
Thanks @Satglow!

Threw up a PR to fix this
