### ISSUE TITLE
Setup texts for translation

### ISSUE THREAD

**Issue by Satglow** [ethereum/ethereum-org-website#12044]
### Is your feature request related to a problem? Please describe.

Some items are not available for translation.

Mainpage https://ethereum.org/
-	Ethereum today table: the 30d/90d tags and the quantity next to the figure (like M, B, k etc.)

![Ethereum today - main page](https://github.com/ethereum/ethereum-org-website/assets/151942349/6c94b208-62ea-4ec9-ad7d-966f23f69d74)

L2 page https://ethereum.org/layer-2
-	Use layer 2 section contains tags like universal, payments, exchange etc.
-	Tools to be effective on layer 2 headers (Information, Wallet managers)

![User layer 2 - L2 page](https://github.com/ethereum/ethereum-org-website/assets/151942349/ee37af54-b59a-48e8-89fc-c4cb66a59f87)

![Tools to be effective - L2 page](https://github.com/ethereum/ethereum-org-website/assets/151942349/3fd8387e-6e8e-4b33-944a-179a477400c5)

Stablecoins page https://ethereum.org/stablecoins
-	Top stablecoins by market capitalisation table, the first half of the button (’Go to’)

![Top stablecoins by market cap - Stablecoins page](https://github.com/ethereum/ethereum-org-website/assets/151942349/8b69d6d2-bdde-4dff-9236-ea5581843186)

Stake ETH https://ethereum.org/staking
-	the staking expression appears in several places in english within the translated text

![staking](https://github.com/ethereum/ethereum-org-website/assets/151942349/c62a8e39-305f-4c88-9243-89cd5c609850)

![staking2](https://github.com/ethereum/ethereum-org-website/assets/151942349/f6a6b1c6-2eb9-4252-9771-f06a408ff94f)

### Describe the solution you'd like

Set up the texts for translation.

### Describe alternatives you've considered

None, these should be translated.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Thank for reporting @Satglow! Sorry for delays, but most of these still appear to be an issue... In summary:

- [x] Mainpage https://ethereum.org/ Amount units (Intl library used now)
- [ ] Mainpage https://ethereum.org/ (`30d`/`90d`... questionable how worth it this one is with homepage redesigns in the work... this could be high effort low impact imo)
- [ ] L2 page https://ethereum.org/layer-2
- [ ] Stablecoins page https://ethereum.org/stablecoins "Go to"
- [x] Stake ETH https://ethereum.org/staking

It would be great if anyone would like to help with the L2 PAge and Stablecoins page to fix this up!

**Comment by corwintines** [comment]
Im going to check the homepage 30d/90d off given the redesign we have
