### ISSUE TITLE
Content and formatting on Nodes as a service page

### ISSUE THREAD

**Issue by Satglow** [ethereum/ethereum-org-website#12046]
### Describe the bug

The listed information about the node providers are a bit unbalanced. For some there are lot of features, even very specific ones, but others has only some generic items. E.g. Infura - less detailed than the others.

The bulletpointing and the indentation is missing for Zeeve and Tokenview.
The ABC order is not working for Chainbase, Zeeve and Tokenview.
Bold formatting is missing for DRPC.

Can you please also correct the following sentences:
RPC endpoints offer authenticated access to **API’s**, hassle free management with intuitive dashboard and analytics. (APIs instead of API's)
Both **rpc** and **wss** endpoints are open to use (with capital letters)

### To reproduce

https://ethereum.org/developers/docs/nodes-and-clients/nodes-as-a-service

### Expected behavior

Aligned content and formatting.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Thanks again for noting these @Satglow! Appreciate the reports, sorry for delays.

Opening this up for the community with the following scope:

- [ ] Fix bulletpointing and the indentation for Zeeve and Tokenview
- [ ] Fix ABC order for entire list
- [ ] Add bold formatting for DRPC name
- [ ] Fix "API’s" -> "APIs"
- [ ] Fix "Both rpc and wss endpoints are open to use" to capitalize RPC and WSS

**Comment by Shiva-Sai-ssb** [comment]
Submitted PR for this. @wackerow 
Please review it and let me know if any changes are needed.

**Comment by wackerow** [comment]
Thanks @Shiva-Sai-ssb! Will take a look
