### ISSUE TITLE
TradeCoinVN Cộng Đồng Crypto

### ISSUE THREAD

**Issue by okiedao-tcvn** [ethereum/ethereum-org-website#12053]
### Event/Meetup Name

https://tradecoinvn.com/danh-muc/ethereum

### Website

https://tradecoinvn.com/

### Location (City/Country, or Remote)

Vietnam

### Description

Website platform with subpages for Ethereum ecosystem, dapps, defi and education.

### Start date: (yyyy-mm-dd)

01/01/2024

### End date: (yyyy-mm-dd)

01/01/2025

### Would you like to work on this issue?

- [ ] Yes

**Comment by isabelladebrito** [comment]
Hi @okiedao-tcvn! The website shared seems to belong to a media project, not to an event specifically to be added on the [ethereum.org website](https://ethereum.org/en/community/events). 

I'll close this request for now but if there's anything else I can help with, don't hesitate to reach out :) thanks!
