### ISSUE TITLE
New Wallets page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1205]
**Is your feature request related to a problem? Please describe.**

A new page that provides a more detailed overview of Ethereum wallets.

Design goals:
1. Explain wallet clearly with minimal jargon and introduce the required concepts with jumping off points for more information (when available)
2. Help a user choose a wallet suited to what they want to do with it
3. Provide a clear next step for when a user has a wallet: dapps/eth
4. Allow users to suggest new wallets based on criteria (_will be considered in the find a wallet page_)
5. Help a user set up and interact with a wallet safely
    - Explain why this is necessary
6. Make the page more visually exciting than a "readme"

**Additional context**

Current page: 
https://ethereum.org/en/dapps/

Design:
https://www.figma.com/file/VYUlXIF1DSORx9xpwIx3eB/Wallets?node-id=81%3A2

**Comment by samajammin** [comment]
Solved in #1206
