### ISSUE TITLE
Missing Images in README.md File

### ISSUE THREAD

**Issue by hiroyukikumazawa** [ethereum/ethereum-org-website#12068]
### Describe the bug

In the `README.md` file of the `ethereum-org-website` repository on the `dev` branch, there are two images that are resulting in a 404 Not Found error. These images are supposed to be part of the documentation but are either missing or have incorrect paths.

### To reproduce

1. Go to the `README.md` file at `https://github.com/ethereum/ethereum-org-website/blob/dev/README.md`.
2. Click on the links attached to the screenshot:
   - [POAP Logo](https://github.com/ethereum/ethereum-org-website/blob/dev/src/assets/poap-logo.svg)
   - [Gatsby Cloud deploy preview](https://github.com/ethereum/ethereum-org-website/blob/dev/GC-preview-deploy.png)
3. Notice that clicking these links leads to a 404 Not Found page, indicating the images are not accessible.

### Expected behavior

The links in the `README.md` file should lead to the respective images, displaying them as intended in the documentation. If the images have been moved or renamed, the links should be updated accordingly to reflect the new paths. If the images are no longer needed, their references should be removed from the README to avoid confusion.

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/142436034/b95553dc-92cf-4e81-8af6-050ff01580cc)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by vedantabanerjee** [comment]
I have found and fixed this issue and issued a pull-request. The details to the fix is in the PR
