### ISSUE TITLE
Charts on the homepage in mobile break on some languages

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#12063]
### Describe the bug

Charts on the homepage in mobile break on some languages when the numbers are defined on a different format

### To reproduce

1. Go to 'homepage in french on a small device'

3. Scroll down to the charts

### Expected behavior

 same line.

### Screenshots

![IMG_7967](https://github.com/ethereum/ethereum-org-website/assets/1120748/30324a85-9926-42be-bc01-320414b6daa4)

### Desktop (please complete the following information)

iOS + safari

### Smartphone (please complete the following information)

Iphone 11

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by diarm0d** [comment]
@nloureiro I would be happy to work in this.

**Comment by nloureiro** [comment]
> @nloureiro I would be happy to work in this.

awesome, thank you!

To help you with the solution, this would be the way to go for mobile.

-reduce the size of the font for the price to 38px
- change the flex-direction and alignment to have the 30D | 90D on a different line
- remove the height constraints for the box.

![Screen Shot 2024-01-31 08 56 52 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/a0f9eed1-0455-468e-94a4-33ac52403e60)

What do you think? Do you have another idea?

**Comment by minimalsm** [comment]
Hey @diarm0d are you still working on this?

**Comment by nloureiro** [comment]
@wackerow, the bug persists, and I would advise doing a quick fix if we have one.

The homepage experiment in mobile for some languages is bad; try Italian.
![Screen Shot 2024-06-14 08 55 52 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/45d81be1-5e90-4a51-ae56-c0066a05b285)

**Comment by wackerow** [comment]
Okay sounds good... Open for contribution if anyone is interested.

**Comment by wackerow** [comment]
Homepage officially revamped, and charts are officially gone. Closing out!
