### ISSUE TITLE
Contradiction between smart contract accounts and wallets

### ISSUE THREAD

**Issue by shoenseiwaso** [ethereum/ethereum-org-website#12061]
In the following section, it describes both "contract accounts", and then goes on to say, "An account is the keypair for a user-owned Ethereum account." So therefore a contract account is not an account?

Happy to suggest a revision through a PR!

https://github.com/ethereum/ethereum-org-website/blob/9c48ba8c9305a351c815aa494974923f9dbb0b97/public/content/developers/docs/accounts/index.md?plain=1#L94-L112

**Comment by wackerow** [comment]
Hey @shoenseiwaso, I see what you're saying. We should be clearer that there are two types of accounts: smart contracts (controlled by their deployment code), and EOAs (controlled by private keys)... the former is not a keypair, but will still have an address (same format, 0x{40}).

Welcome a patch for this

**Comment by shoenseiwaso** [comment]
> Hey @shoenseiwaso, I see what you're saying. We should be clearer that there are two types of accounts: smart contracts (controlled by their deployment code), and EOAs (controlled by private keys)... the former is not a keypair, but will still have an address (same format, 0x{40}).
> 
> Welcome a patch for this

Ok great! Created PR #13109.
