### ISSUE TITLE
resource language

### ISSUE THREAD

**Issue by chrisumanah** [ethereum/ethereum-org-website#1207]
**Is your feature request related to a problem? Please describe.**

Ethereum does not have good php resource support preferable frameworks like laravel 
please something should be done on these.

**Comment by developerfred** [comment]
Library Web3js
- [PHP](https://github.com/sc0Vu/web3.php)
- [Javascript](https://web3js.readthedocs.io/en/v1.2.9/)

**Comment by samajammin** [comment]
Hey folks, this looks to be a duplicate of #1129 - closing this out in favor of that issue. Please feel free to weigh in there!
