### ISSUE TITLE
Update USDC link on stablecoin.tsx

### ISSUE THREAD

**Issue by barskhianfannie** [ethereum/ethereum-org-website#12077]
### Describe the bug

On the `stablecoins.tsx` page, there is a link which should lead users to the [Native USDC Token Page on Matcha](https://matcha.xyz/tokens/ethereum/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48). This link is incorrect and routing users to a 404 page on matcha. 

The link which is [defined here ](https://github.com/ethereum/ethereum-org-website/blob/a33e21691ee96bc24cbeb7112cb8ebe71394dba7/src/pages/stablecoins.tsx#L566)should be updated to - https://matcha.xyz/tokens/ethereum/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

### To reproduce

1. Go to [Stablecoins page on ethereum.org](https://ethereum.org/stablecoins)
2. Click on '`Swap Eth for USDC` as shown in the screenshot below. 
3. Notice this routes you to a 404 page. 
![Screen Shot 2024-01-31 at 11 33 50 AM](https://github.com/ethereum/ethereum-org-website/assets/42990794/fb94e85c-5fe8-40f6-b13b-69529d5e4d69)

### Expected behavior

This link should instead be updated to the appropriate Native USDC Token Page on Matcha. 

Code Line to be updated - https://github.com/ethereum/ethereum-org-website/blob/a33e21691ee96bc24cbeb7112cb8ebe71394dba7/src/pages/stablecoins.tsx#L566

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Agree with getting this link updated. No strong feelings of if its matcha, or uniswap. Something with a large sized dex.

**Comment by rachana-uniyal** [comment]
Hi, can I work on this issue?

**Comment by a-hagi613** [comment]
is this issue resolved? if not i can take it

**Comment by Nagu40** [comment]
<ButtonLink
  mb={4}
  me={4}
  to="https://matcha.xyz/tokens/ethereum/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
>
  {t("page-stablecoins-usdc-banner-swap-button")}
</ButtonLink>

**Comment by minimalsm** [comment]
Closed by #12112
