### ISSUE TITLE
Replace, rename and remove unavailable URLs on ethereum.org's DeSci page

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#12081]
### Describe the bug

Replace, rename and remove unavailable URLs on ethereum.org's [DeSci page](https://ethereum.org/en/desci)

### To reproduce

1. Go to [https://ethereum.org/en/desci#get-involved](https://ethereum.org/en/desci#get-involved)
2. Replace URLs in the following resources:
a. "[Molecule: Fund and get funded for your research projects](https://discover.molecule.to/)" to https://www.molecule.xyz/
b. [Fleming Protocol: open-source data economy that fuels collaborative biomedical discovery](https://medium.com/@FlemingProtocol/a-data-economy-for-patient-driven-biomedical-innovation-9d56bf63d3dd) to http://flemingprotocol.io/
c. [OceanDAO: DAO governed funding for data-related science](https://oceanprotocol.com/dao) into https://oceanprotocol.com/
d. [Molecule’s Biopharma IP-NFTs - A Technical Description](https://molecule.to/blog/molecules-biopharma-ip-nfts-a-technical-description) to https://www.molecule.xyz/blog/molecules-biopharma-ip-nfts-a-technical-description

3. Rename the following resource:
a. [Active Inference Lab](https://www.activeinference.org/) to [Active Inference Institute](https://www.activeinference.org/)

4. Remove
a. [The Emergence of Biotech DAOs](https://molecule.to/blog/the-emergence-of-biotech-daos) (I cannot find the article on [Molecule's new blog](https://www.molecule.xyz/blog))

### Expected behavior

Four URLs replaced, one resource renamed, and one unavailable resource removed from the [DeSci page](https://ethereum.org/en/desci)

### Additional context

- If you want to work on this issue, I'd also encourage to have a look at https://github.com/ethereum/ethereum-org-website/issues/11519 as there are some duplicated links on the same page.

- Thanks to _Zenos T._ for reporting some of these links via email! ⭐ 

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Pushkarmondal** [comment]
can I work on this issue?

**Comment by kaksv** [comment]
Is this issue still open so i can work on it?

**Comment by mabsattar** [comment]
Hi, I would like to tackle this. can you please assign me.
