### ISSUE TITLE
Add EthCC 2024 to events

### ISSUE THREAD

**Issue by nsexer** [ethereum/ethereum-org-website#12085]
### Event/Meetup Name

EthCC

### Website

https://ethcc.io/

### Location (City/Country, or Remote)

Brussels

### Description

The Ethereum Community Conference (EthCC) is the largest annual European Ethereum event focused on technology and community. Four intense days of conferences, networking and learning.

### Start date: (yyyy-mm-dd)

2024-07-08

### End date: (yyyy-mm-dd)

2024-07-11

### Additional context

Also https://www.ethccweek.fr/

### Would you like to work on this issue?

- [ ] Yes

**Comment by corwintines** [comment]
Agree with this being added. @nsexer was this something you wanted to work on, or should somebody else pick this up?

**Comment by oceans404** [comment]
I can add this to the website

**Comment by kaksv** [comment]
Hello, I would like to work on this issue. Any way i can work on it?

**Comment by lukassim** [comment]
Thanks @nsexer, closing this issue out as it was completed by PR #12087
