### ISSUE TITLE
Setup texts for translation (2)

### ISSUE THREAD

**Issue by Satglow** [ethereum/ethereum-org-website#12097]
### Is your feature request related to a problem? Please describe.

These items are not available for translation in Crowdin, this also means that it can not be corrected if it shows a strange text.

Menu: Learn: Gas fees

![Gas fees](https://github.com/ethereum/ethereum-org-website/assets/151942349/527ba5a8-b8bd-429a-9267-fa8f7e293a8c)

https://ethereum.org/what-is-ethereum
criminal activity: the title of the linked resources are not translatable

![criminal activity - reports](https://github.com/ethereum/ethereum-org-website/assets/151942349/1387eb1e-cf7f-4563-a84f-6a78393d98af)

https://ethereum.org/hu/eth
Popular types of token: Stablecoins (this show a strange translation, but not in Crowdin)

![What is ether - stablecoin string](https://github.com/ethereum/ethereum-org-website/assets/151942349/6449d886-84dd-43ac-86d7-0f48a4b443c4)

https://ethereum.org/hu/developers
title is not translatable (DEVELOPERS)

![Developers main page - title](https://github.com/ethereum/ethereum-org-website/assets/151942349/ee9b0a52-b05d-4999-bd5d-be15a5b39a27)

https://ethereum.org/hu/developers/learning-tools
https://ethereum.org/hu/developers/local-environment
The first part of the button ’Open’ is not translatable.

![Learn by coding - button](https://github.com/ethereum/ethereum-org-website/assets/151942349/0f9bb103-1731-420f-9661-863878d80b68)

https://ethereum.org/hu/roadmap/beacon-chain
title is missing for translated page, it says: page-upgrades-beacon-date, instead of ’Shipped!’

![Beacon chain - title](https://github.com/ethereum/ethereum-org-website/assets/151942349/051494d2-4091-4647-b8de-fd2922b056a3)

https://ethereum.org/hu/staking/saas
https://ethereum.org/hu/staking/solo
https://ethereum.org/hu/staking/pools

Same type of issues on all the 3 pages:
- Why stake solo? /  Why stake with a service? / Why stake with a pool? - there are buckets which text is not available for translation
- Comparison with other options – this title is not available for translation; under this subtitles also stay in English: Staking as a service (SaaS), Pooled staking
- Explore node and client setup tools / Explore staking pools/ Explore staking service providers – there is a text like ’from 10,4 ETH’ or ’any amount’ – this could be translatable too

![Solo staking page - bukets](https://github.com/ethereum/ethereum-org-website/assets/151942349/01824b90-6695-467b-95c4-0026b2f4bd96)

![Pooled staking - tools text](https://github.com/ethereum/ethereum-org-website/assets/151942349/542370a3-74d2-4448-89dd-970d28116244)

For solo staking page: 
- Considerations before staking solo – ’Maintenance’ is not available for translation
- Get started on the Staking Launchpad – the list of networks should be translatable (Goerli testnet, Mainnet)

(note: issue #12044 contains related issues for https://ethereum.org/staking - some of the issues can have the same root cause)

### Describe the solution you'd like

See above details.

### Describe alternatives you've considered

None

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
> Menu: Learn: Gas fees

> Popular types of token: Stablecoins (this show a strange translation, but not in Crowdin)

> title is missing for translated page, it says: page-upgrades-beacon-date, instead of ’Shipped!’

I believe these are resolved now.

> criminal activity: the title of the linked resources are not translatable

We typically do not translate these article names, especially if that article is only available in English to begin with. 

> title is not translatable (DEVELOPERS)

Just put up a patch for this: #13167 

---

Open for contributors with the following scope:

- [ ] Fix hard-coded "Open" string inside `ProductCard` component
- [ ] Fix hard-coded "Comparison with other options" from `StakingComparison` component
- [ ] Fix hard-coded "From" and "Any amount" from `StakingProductsCard` component (see line 197)
- [ ] Fix hard-coded "testnet" next to "Goerli" in `StakingLaunchpadWidget` component
