### ISSUE TITLE
Sybil attack as a glossary item

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#12096]
### Checklist

- [X] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [X] This term/definition is not a product advertisement or contain other promotional content
- [X] This term/definition is directly relevant to Ethereum

### Term name

Sybil attacks

### Term definition

Individual humans trick a system into thinking they are multiple people to increase their influence.

### Sources, if any (please do not submit copywrited content without appropriate approval)

https://ethereum.org/decentralized-identity#sybil-protection

### Ethereum.org links

https://ethereum.org/developers/docs/consensus-mechanisms#sybil-chain

### Additional context

This term is mentioned in multiple places on the website - it would be nice to make it a glossary term and link it. https://ethereum.org/developers/docs/consensus-mechanisms here mentioned at the beginning of the document, later in the document explained what it is. It would be nice to know what it is when first encountered. 

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by corwintines** [comment]
Agree with this being added. @aslikaya are you still interested in working on this?

**Comment by aslikaya** [comment]
yes @corwintines
