### ISSUE TITLE
Adding ValleyDAO to the Desci page's Get Involved List

### ISSUE THREAD

**Issue by SeaBlue22** [ethereum/ethereum-org-website#12105]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Hello! 
Just opening an issue to request adding ValleyDAO to the [Ethereum Desci ](https://ethereum.org/en/desci) page. 
We're a DAO founded in 2022 that funds and supports synthetic biology research. 

Site URL and tagline:
[ValleyDAO: an open, global community offering funding and translational support for synthetic biology research]( https://www.valleydao.bio/)

### Describe alternatives you've considered

N/A 

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by lucas-amberg** [comment]
I can work on this if necessary

**Comment by lucas-amberg** [comment]
> I can work on this if necessary

In case y'all need it I opened PR #12114 👍

**Comment by isabelladebrito** [comment]
gm @SeaBlue22, thanks for creating the issue! @lucas-amberg I'll get the team to review your PR :)
