### ISSUE TITLE
Bug: missing space in history entries

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12101]
### Describe the bug

We're missing a space before the block/epoch/slot values for each entry on the `/history` page. 

### To reproduce

1. Go to https://ethereum.org/history
2. See any upgrade entry where it displays either "Epoch number", "Slot number" and/or "Block number"; notice the lack of a space between this label and the value being shown.

### Expected behavior

Should have a single space rendered between the label and value.

### Screenshots

<img width="1087" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/4e02bf0a-def2-4cd8-a93c-8b306e92303f">

### Additional context

Culprit is likely inside the `NetworkUpgradeSummary` component (`/src/components/History/NetworkUpgradeSummary.tsx`), [in the `blockTypeTranslation` function](https://github.com/ethereum/ethereum-org-website/blob/fec8acdf700b31a802494f612b72565b89356b64/src/components/History/NetworkUpgradeSummary.tsx#L53).

There does seem to be a `{" "}` in there, and an up-close screenshot of the text selected...

<img width="1059" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/e51a21cb-1796-4efa-ba23-a56c16596000">

...reveals that the space appears to be present, but for some reason it's collapsing so it doesn't actually take up space.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by yash251** [comment]
hello ser, please assign me this issue

**Comment by a-hagi613** [comment]
has this been resolved?

**Comment by mabsattar** [comment]
Hi, I would like to work on this, can you assign me.

**Comment by kaksv** [comment]
I have ended up reading the entire history. Its so interesting. 🥳

**Comment by kaksv** [comment]
When I check the document in markdown format, I realize that the data we are meant to edit initally is a component and I am requesting to know the exact location of the <NetworkUpgradeSummary name="shanghai" /> component.

**Comment by Nagu40** [comment]
const blockTypeTranslation = (translationKey, explorerUrl, number) => {
  return (
    <Flex>
      <Emoji fontSize="sm" me={2} text=":bricks:" />
      {t(translationKey)}: {" "} {/* Added space here */}
      <InlineLink to={`${explorerUrl}${number}`}>
        {new Intl.NumberFormat(localeForStatsBoxNumbers).format(number)}
      </InlineLink>
    </Flex>
  )
}
