### ISSUE TITLE
[typo link] - roadmap ethereum magician link is redirected from a figma link

### ISSUE THREAD

**Issue by kabaluyot** [ethereum/ethereum-org-website#12108]
### Describe the bug

In https://ethereum.org/roadmap, the Ethereum Magicians forum link (https://www.figma.com/exit?url=https%3A%2F%2Fethereum-magicians.org%2F) is redirected from a figma url.

### To reproduce

In https://ethereum.org/roadmap, the Ethereum Magicians forum link (https://www.figma.com/exit?url=https%3A%2F%2Fethereum-magicians.org%2F) is redirected from a figma url.

### Expected behavior

Should direct redirect to https://ethereum-magicians.org/

### Screenshots

<img width="750" alt="Screen Shot 2024-02-03 at 9 57 21 AM" src="https://github.com/ethereum/ethereum-org-website/assets/38805756/6d601c8c-46f7-47c9-8872-8b159aa3e32a">

<img width="596" alt="Screen Shot 2024-02-03 at 9 55 19 AM" src="https://github.com/ethereum/ethereum-org-website/assets/38805756/4c326f96-f49b-4999-9b00-4617001af1e9">

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by a-hagi613** [comment]
i can work on this

**Comment by isabelladebrito** [comment]
gm @kabaluyot, thanks for point this out! 

I agree with the change you proposed, and I'd add another thing: to fix the hyperlink name from "Ethereum magicians" to "Ethereum Magicians" (with a capitalised 'M').

@a-hagi613 you're more than welcome to work on this issue, just send a PR :)

**Comment by mabsattar** [comment]
Hi, has this been resolved?

**Comment by isabelladebrito** [comment]
Hi @mabsattar! It seems there hasn't been any PR submitted to fix this issue so this is still up for grab :)

**Comment by nhsz** [comment]
> #12137

This was fixed by https://github.com/ethereum/ethereum-org-website/pull/12137 PR, closing this issue

**Comment by nhsz** [comment]
> Hi, has this been resolved?

This was fixed by https://github.com/ethereum/ethereum-org-website/pull/12137 PR, closing this issue
