### ISSUE TITLE
The table is too large for small screens

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#12119]
### Describe the bug

in this page

https://ethereum.org/en/energy-consumption

The table is overflowing the content and breaks the layout on small screens 

### To reproduce

1. Go to https://ethereum.org/en/energy-consumption
2. on screen smaller than 450px
3. See error

### Expected behavior

It should have horizontal scroll

### Screenshots

![Screen Shot 2024-02-06 09 31 01 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/77ff711b-d1e6-4b88-8718-9c11c65c2b74)

### Desktop (please complete the following information)

iOs safari and chrome 

### Smartphone (please complete the following information)

Iphone

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by TylerAPfledderer** [comment]
@nloureiro I can triage this. 👍🏼

**Comment by TylerAPfledderer** [comment]
@nloureiro @pettinarip this looks to be coming from a container 2 levels up that is a direct child of a flex-box. Supposedly this is part of the flexbox behavior and not a bug. (See [Static.tsx line 109](https://github.com/ethereum/ethereum-org-website/blob/ca582ccac4e46b93bd8e57f2c8cdfc9a21d10bd8/src/layouts/Static.tsx#L109), though this quirk might exist in other layouts)

It seems that the solution is to [apply 'min-width: 0px' to the container in question](https://dfmcphee.com/flex-items-and-min-width-0/) to force it's children to shrink. This will enable the overflow in the table.
