### ISSUE TITLE
[Feature request]: Add BlockSec's Phalcon Block Explorer to the Services List

### ISSUE THREAD

**Issue by eminmtas** [ethereum/ethereum-org-website#12123]
### Is your feature request related to a problem? Please describe.

I sometimes use [Phalcon](https://phalcon.blocksec.com/explorer) to simulate Ethereum transactions when I use [MetaSleuth](https://metasleuth.io/). So, I thought it would be cool if other people see this explorer on the website too.

### Describe the solution you'd like

I want Phalcon to be added the `index.md` file located in `/public/content/developers/docs/data-and-analytics/block-explorers/`.

### Describe alternatives you've considered

-

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by eminmtas** [comment]
Still waiting for it to be reviewed🙌

**Comment by wackerow** [comment]
Hey @eminmtas, sorry for delay... marked this for review and assigned myself.

In the meantime, I do see the attached PR.. Could you provide some information about this block explorer and how it may differentiate itself from the list that is already present on that page? 

Is it open source? Does it keep logs? Does it have ads? Does it have verified token lists? Does it have open API plans? etc =) That would help, thanks!

**Comment by wackerow** [comment]
Hey @eminmtas! Haven't heard back; going to close this out for now. Please feel free to re-open as-needed, thanks!
