### ISSUE TITLE
Rename hyperlink text on website footer

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#12138]
### Describe the bug
Replace text on hyperlink located on ethereum.org website footer.

### To reproduce
a. Go to https://ethereum.org and scroll down up to the website footer
b. On the "About ethereum.org" category, look for `Contact`
<img width="959" alt="Screenshot 2024-02-08 at 22 46 59" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/4d52c05d-5564-4215-8922-36279c15d12d">
c. The 'mailto' linked to `Contact` is pointing to an email address for press enquiries, which should be kept in the footer - as ethereum.org's 'general contact' email is already available in other pages.
d. Instead of `Contact`, it should be renamed as `Press Contact`

### Expected behavior
Rename `Contact` into `Press Contact`, keeping the current mailto [press@ethereum.org].

### Would you like to work on this issue?

- [ ]  Yes
- [x]  No

**Comment by yash251** [comment]
on it

**Comment by yash251** [comment]
@isabelladebrito please check
