### ISSUE TITLE
A Typo

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#12147]
### Describe the bug

"received" is used instead of "receives"

### To reproduce

1. Go to https://ethereum.org/developers/docs/consensus-mechanisms/pos/rewards-and-penalties#rewards
2. Scroll down to 'If the attestation arrives in the next slot, the attestor received base_reward * 1/2 and so on.'
3. See error

### Expected behavior

instead of "received" - it should be "receives"

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by isabelladebrito** [comment]
well spotted, @aslikaya! I can see you have already submitted a PR for this issue (https://github.com/ethereum/ethereum-org-website/pull/12148), so our team will have a look soon :) thanks!
