### ISSUE TITLE
Hard to see the writings on a diagram

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#12150]
### Describe the bug

When in the dark mode, reading the writings on a diagram is very hard.

### To reproduce

1. Go to https://ethereum.org/developers/docs/consensus-mechanisms/pos/attack-and-defense#reorgs
2. Scroll down to the [diagram](https://ethereum.org/content/developers/docs/consensus-mechanisms/pos/attack-and-defense/reorg-schematic.png)
3. See error

### Expected behavior

It should be easily readable

### Screenshots

<img width="636" alt="Screenshot 2024-02-12 at 13 26 57" src="https://github.com/ethereum/ethereum-org-website/assets/9151261/59afa163-ded8-459b-b602-2e1d8108271c">

### Desktop (please complete the following information)

MacOS, Chrome

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by iepn** [comment]
> ### 描述错误
> 在黑暗模式下，阅读图表上的文字非常困难。
> 
> ### 重现
> 1. 转到https://ethereum.org/developers/docs/consensus-mechanisms/pos/attack-and-defense#reorgs
> 2. 向下滚动到[图表](https://ethereum.org/content/developers/docs/consensus-mechanisms/pos/attack-and-defense/reorg-schematic.png)
> 3. 查看错误
> 
> ### 预期行为
> 它应该易于阅读
> 
> ### 截图
> <img alt="截图 2024-02-12 13 26 57" width="636" src="https://private-user-images.githubusercontent.com/9151261/304052321-59afa163-ded8-459b-b602-2e1d8108271c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MDkxNTgsIm5iZiI6MTcwOTUwODg1OCwicGF0aCI6Ii85MTUxMjYxLzMwNDA1MjMyMS01OWFmYTE2My1kZWQ4LTQ1OWItYjYwMi0yZTFkODEwODI3MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMjMzNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzAxYTMyMzQ0N2RmODYzNmQ0ZTM5NzI1Njk0NzFiMjAzYzc2MmQ2ODIyMDYyMTQ2MjdkOTMwMDNmN2UxYjVmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H4yRxX1kB_QhhxZ3dYIE1qlPszBVr891VPrOdxU8_SU">
> ### 桌面（请填写以下信息）
> macOS、Chrome
> 
> ### 智能手机（请填写以下信息）
> _没有反应_
> 
> ### 额外的背景信息
> _没有反应_
> 
> ### 您想解决这个问题吗？
> * [ ] 是的
> * [ ] 不



> ### Describe the bug
> When in the dark mode, reading the writings on a diagram is very hard.
> 
> ### To reproduce
> 1. Go to https://ethereum.org/developers/docs/consensus-mechanisms/pos/attack-and-defense#reorgs
> 2. Scroll down to the [diagram](https://ethereum.org/content/developers/docs/consensus-mechanisms/pos/attack-and-defense/reorg-schematic.png)
> 3. See error
> 
> ### Expected behavior
> It should be easily readable
> 
> ### Screenshots
> <img alt="Screenshot 2024-02-12 at 13 26 57" width="636" src="https://private-user-images.githubusercontent.com/9151261/304052321-59afa163-ded8-459b-b602-2e1d8108271c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MDkyNjgsIm5iZiI6MTcwOTUwODk2OCwicGF0aCI6Ii85MTUxMjYxLzMwNDA1MjMyMS01OWFmYTE2My1kZWQ4LTQ1OWItYjYwMi0yZTFkODEwODI3MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMjMzNjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDcwMzc0MDNhMDIxNTUxM2I4M2JiMWRjY2U1Y2UxZWE5NDMyMmQ4NzliYWVjYzk1NTVmNDFhOTkxNTI3YjBiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Eed7AieUQEcFTcvufRC2TgYSUW-gP7uYZQCsd_udapI">
> ### Desktop (please complete the following information)
> MacOS, Chrome
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Would you like to work on this issue?
> * [ ]  Yes
> * [ ]  No

Hey! This issue is due to your being in dark mode. You can click on the "sun" icon in the top right corner to switch to the day mode, and then you'll be able to see clearly.

**Comment by iepn** [comment]
#12344

**Comment by nhsz** [comment]
@nloureiro

**Comment by nloureiro** [comment]
@aslikaya Thank you for raising it, we are in the process of changing all diagram to a new design cohesive and system based approach.

you can see the first batch [here](https://github.com/ethereum/ethereum-org-website/pull/12233), and ready to me merged to production

I will add this one to the priority.
Thank you.

**Comment by nloureiro** [comment]
@aslikaya I just review all the new diagrams and this one in already done

you can see here > https://deploy-preview-12233--ethereumorg.netlify.app/developers/docs/consensus-mechanisms/pos/attack-and-defense

**Comment by aslikaya** [comment]
Thanks! @nloureiro  Looks good! 

A few minor suggestions: 
- there are extra spaces in these two blocks between "N" and the "+" sign  
<img width="455" alt="Screenshot 2024-03-05 at 13 56 00" src="https://github.com/ethereum/ethereum-org-website/assets/9151261/0d7e0728-bae1-4942-9ceb-be4b22a6984b">

- since slots denote time maybe showing them at the bottom might make it clearer
