### ISSUE TITLE
Missing title, text and button on Gas page

### ISSUE THREAD

**Issue by Satglow** [ethereum/ethereum-org-website#12151]
### Describe the bug

There is an empty section (about dapp explore) with only technical references appearing as title, text and on the button too.

https://ethereum.org/gas

![Gas page - Dapp explore section](https://github.com/ethereum/ethereum-org-website/assets/151942349/0a982cd4-d96b-4c9a-b428-505a5acee4bc)

### To reproduce

1. Go to https://ethereum.org/gas
2. Scroll down to the bottom.
4. See error next to the 'Use layer 2' section

### Expected behavior

Title, text part and button has relevant text.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by corwintines** [comment]
Thanks @Satglow 

This was fixed in https://github.com/ethereum/ethereum-org-website/pull/12122. Will be out in this weeks release!
