### ISSUE TITLE
Bug report: missing whitespace

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12173]
### Describe the bug

Missing space between emoji and text on design page

### To reproduce

1. Go to https://ethereum.org/en/contributing/design
2. Scroll down and notice list using emoji's for number
3. Notice lack of space between emoji and heading text

### Expected behavior

We should have some spacing between the emoji and the text. Commonly we'll use 0.5rem (chakra token `"2"`) for marginEnd (Chakra property `me`).

### Screenshots

<img width="901" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/62bd353b-731c-47dc-b786-b36a21292093">

### Additional context

Inside `public/content/contributing/design/index.md` we should add `me="2"` to each Emoji (a margin _end_ of half a rem; do not use marginRight to ensure responsiveness for RTL languages)

This should be done for this page in all languages (`/public/content/translations/{lang}/community/online/index.md`)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by RabihJabr29** [comment]
Hello, Can i work on this issue?

**Comment by MohitKambli** [comment]
Hello,
Can I work on this issue?

**Comment by ameyer12** [comment]
Hi,
Can I work on this issue?

**Comment by RabihJabr29** [comment]
Hello again @wackerow , I have provided a potential fix.
Please let me know of any comments.

**Comment by corwintines** [comment]
Thanks @RabihJabr29, will review your PR

Thanks @MohitKambli and @ameyer12 for offering as well. See @RabihJabr29 offered first and has an open PR so going to assign to them.
