### ISSUE TITLE
Feedback widget overflowing on Mobile

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#12184]
### Describe the bug

When using the FeedbackWidget on mobile, the thank you screen overflows off the screen on the left

### To reproduce

1. Go to https://deploy-preview-12182--ethereumorg.netlify.app/developers/docs on mobile
2. Go through feedback widget
3. 
![Screenshot 2024-02-14 at 11 04 02 AM](https://github.com/ethereum/ethereum-org-website/assets/15589226/79e2d7b0-5342-4d16-926e-ba4053248cce)

### Expected behavior

Should be centered instead of overflowing over

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by RasstCrypt** [comment]
Need To Restructure With Chakra UI More Better

**Comment by AkimBW** [comment]
corwintines, can I take this issue?

**Comment by cypherspeare** [comment]
would be happy to work on this issue

**Comment by TylerAPfledderer** [comment]
This is already being addressed via #10997
