### ISSUE TITLE
Add disclaimer to stablecoins page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12196]
_Re-surfaced from #6370, as that issue had discussion with decisions and then went stale_

---

> Re-posted from #6370

## Problem

[After the collapse of UST](https://www.coindesk.com/markets/2022/05/15/the-collapse-of-terra-was-devastating-but-there-is-still-hope-for-crypto/), the general sentiment I'm seeing in the wild is that algorithmic stablecoins are fundamentally flawed from a design perspective (E.g.: [1](https://twitter.com/TrungTPhan/status/1526572065276383232), [2](https://twitter.com/StellarOrg/status/1524794601462288385), [3](https://www.youtube.com/watch?v=lHxVRuUHJoA)). This issue aims to open up the discussion publicly about whether ethereum.org should list algorithmic stablecoins on [our stablecoins page](https://ethereum.org/en/stablecoins/) or not.

Currently, we list the top eight stablecoins based on market capitalisation. In the top eight, there are presently two algorithmic stablecoins being listed (Magic Internet Money and Frax).

---

## Task

Four options were proposed in that issue thread with consensus forming around one of them:

Keep algorithmic stablecoins in the 'stablecoins list' but add a disclaimer to 'types of stablecoins' explaining that algorithmic stablecoins are experimental and not well battle-tested.

**Comment by gabrieltemtsen** [comment]
can i have this assigned to me ?

**Comment by minimalsm** [comment]
Hey @gabrieltemtsen, thanks for offering to help!

I've assigned you to the issue, let us know if you need any help ☺️

**Comment by zahratt82** [comment]
good great

**Comment by gabrieltemtsen** [comment]
> assigned

https://github.com/ethereum/ethereum-org-website/pull/12229

**Comment by corwintines** [comment]
Closed with the above PR
