### ISSUE TITLE
Deprecate `/deprecated-software` page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12193]
## Issue
The [`/deprecated-software`](https://ethereum.org/deprecated-software) gets very little traffic and is not maintained. There are challenges associated with maintaining this type of page, as it requires resources to constantly be scanning for potential new software that is considered "deprecated" without any mechanism to automate. Impact vs effort on this page is strongly towards the high effort /low impact side. As such, we should deprecate this page.

## Task
- Remove this page for all languages
- Remove associated image assets that are not used anywhere else (if any)

**Comment by FaybianB** [comment]
Hey @wackerow, may I be assigned this issue?

**Comment by wackerow** [comment]
@FaybianB Assigned! Let us know if you have any questions or issues =)
