### ISSUE TITLE
bug: staking page breaks when adding the /en prefix 

### ISSUE THREAD

**Issue by nhsz** [ethereum/ethereum-org-website#12207]
### Describe the bug

If we use the `/en` prefix, the page `https://ethereum.org/en/staking` throws a 404. Seems to be working ok with the rest of the languages

### To reproduce

1. Go to `https://ethereum.org/en/staking`
2. Page shoudl throw a 404

### Expected behavior

`https://ethereum.org/en/staking` working ok

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
This appears to be solved in PR #12134 ([Deploy preview /en/staking](https://deploy-preview-12134--ethereumorg.netlify.app/en/staking)). 

Given currently the path [_without_ `/en/`](https://ethereum.org/staking) is still working, I'd suggest we try to finish up that PR and confirm that fixes this issue, without rushing any temporary patches here.

**Comment by Himanshunashtech** [comment]
there is no need of english  language path because the site default language is english.
