### ISSUE TITLE
Add info about Opcodes in compiling smart contracts.

### ISSUE THREAD

**Issue by allwin199** [ethereum/ethereum-org-website#12216]
In [compiling smart contracts](https://ethereum.org/en/developers/docs/smart-contracts/compiling) page an example of how smart contract is converted to opcodes is provided. But there is missing info about opcodes. 

Adding info about what are opcodes and how it is related to EVM will be helpful.

**Comment by wackerow** [comment]
Thank @allwin199! Reviewing your PR now
