### ISSUE TITLE
Bug report: social button sizing

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12213]
### Describe the bug

The bottom of every page contains social links/icons in the Footer. Tabbing over these shows a strange shape for the outline of the buttons as a result of mixed sizing between the anchor link and contained SVG.

### To reproduce

1. Go to https://ethereum.org or any subpage
2. Scroll to bottom and find GitHub/Twitter/Discord icons
3. Click just before the set of icons to move keyboard focus, then hit "Tab" to highlight one of the icons

(Or, use keyboard to tab all the way down to these elements from the top)

### Expected behavior

Outline shown for the button should simply be square-shaped (with rounded corners)

### Screenshots

<img width="365" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/3f11248e-9d74-4ae0-a293-aa726659be8e">

### Additional context

We seem to be using `BaseLink` for these, but given there is no text, I think a more appropriate component would probably be our `IconButton` component. These should remain proper _anchor links_, but stylistically feel like buttons. Aria-label must be maintained.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by AjayiMike** [comment]
Hey @wackerow, may I be assigned this issue?
