### ISSUE TITLE
Learn Opcodes

### ISSUE THREAD

**Issue by veridelisi** [ethereum/ethereum-org-website#12250]
### Tutorial title

Learn Opcodes

### [Learn EVM Opcodes Series Overview ](https://veridelisi.medium.com/learn-opcodes-7bd28d5f0d1b)
Welcome to the comprehensive series on understanding Ethereum Virtual Machine (EVM) Opcodes! This series is designed for individuals aiming to deepen their knowledge of the Solidity programming language, focusing on security aspects and low-level operations. Through this journey, you will gain insights into how smart contracts operate at the bytecode level, enhancing your ability to write secure and efficient code, audit smart contracts, and understand the intricacies of EVM execution.
![image](https://github.com/ethereum/ethereum-org-website/assets/72710290/2130a3be-a3fe-4547-9b0f-c5575a93490d)

### [I. Introduction to Bytecode and Opcodes ](https://veridelisi.medium.com/evm-opcodes-i-67d4b03dd674)
Objective: Introduce the concepts of bytecode and opcodes within the context of EVM.
Key Topics:
Definition of Bytecode and Opcodes
Importance in Solidity security
Overview of EVM architecture

### [II. Understanding Basic Opcodes](https://veridelisi.medium.com/learn-evm-opcodes-ii-e866cbb46dc1)
Objective: Learn the fundamental opcodes for arithmetic and stack manipulation.
Key Topics:
ADD, SUB, MUL, DIV, and POP opcodes
Code snippets and visual illustrations

### [III. Manipulating the Largest Number in EVM](https://veridelisi.medium.com/learn-evm-opcodes-iii-f7e61780912e)
Objective: Explore EVM's handling of large numbers through practical opcode manipulation.
Key Topics:
Understanding EVM's numerical limits
Practical exercises with arithmetic opcodes

You can see the other lessons from this [link](https://veridelisi.medium.com/learn-opcodes-7bd28d5f0d1b)

This series aims to equip you with a robust understanding of EVM opcodes, paving the way for advanced Solidity development and security auditing. Whether you're a developer seeking to refine your smart contract skills or an enthusiast curious about the inner workings of Ethereum, this journey through EVM opcodes will provide valuable insights and practical knowledge.
Engin YILMAZ (@veridelisi)

### Tutorial tags

opcodes

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://veridelisi.medium.com/learn-opcodes-7bd28d5f0d1b

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @veridelisi, thanks for the suggestion! Tutorials related to opcodes would be nice to have... I'm a bit reluctant on adding 11 tutorials in bulk though all on this topic. Were you looking to list all 11 of these individually, or just the [landing page](https://veridelisi.medium.com/learn-opcodes-7bd28d5f0d1b) that lists them all?

I would suggest either listing the landing page that links to the other 11, or maybe listing the first 2 or 3. If we go with the first couple, would there be a way to update those to link back to the landing page? (Or maybe they already do and I missed it)

Assigning you! Let us know if you have questions or hit issues

**Comment by wackerow** [comment]
@veridelisi Looks good to me! You'll want to target this file: https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/externalTutorials.json

**Comment by veridelisi** [comment]
@wackerow Thanks. I sent pull request https://github.com/ethereum/ethereum-org-website/pull/12516
