### ISSUE TITLE
Layer 2 inaccurracies

### ISSUE THREAD

**Issue by PabloRuizCuevas** [ethereum/ethereum-org-website#12288]
### Describe the bug

https://ethereum.org/layer-2
States: 

>  A layer 2 is a separate blockchain that extends Ethereum.

But if you go to some of the L2 listed solutions, they don´t have a separate blockchain at all, for instance (but not the only one) Loopring relies in a single centralized relayer, 

Also the code of the relayer as far as I know is close source (I may be wrong, but at least it was), but if you look at the conditions for a L2 addition in the page at  https://ethereum.org/contributing/adding-layer-2s

> Open source
> 
>     Your code must be accessible and you should accept PRs from the wider community.
> 

If part of the code is not open source I think it doesn´t match that criteria.

Said that, I have nothing against Loopring or other alternatives that relay in centralized nodes, probably the are great alternatives to 100% CEX, but at the same time I don´t think they are fully DEX solutions as they advertise themselves, and I think the information on the ethereum website is not 100% accurate.

### To reproduce

1. Go to [eth](https://ethereum.org/layer-2)
2. Read

### Would you like to work on this issue?

- [ ] Yes
- [x ] No

**Comment by wackerow** [comment]
Thanks @PabloRuizCuevas! Sounds like there are two issues here, one being that Loopring may not meet our listing criteria, and another about the "blockchain" terminology.

I'm not sure I see the "blockchain" term as a problem in regards to having a centralized sequencer... Being a blockchain data-structure is independent from how many people control it, but if this structure isn't being used we could consider updating the term.

For Loopring, would need to research or get some input myself. I see a repo for them, but not sure it's everything needed.

**Comment by wackerow** [comment]
@PabloRuizCuevas Okay... I'm not sure I fully understand... Taking Loopring as the example, was just looking at https://explorer.loopring.io/ which appears to have evidence that this L2 specifically does use a blockchain structure (blocks, in a canonical order, containing transactions, in a canonical order)... Even if this is controlled by a single sequencer, it's still its own blockchain.

Would you suggest something different for this? Saying it's "a separate blockchain" I find a little confusing as it may imply that the _security_ underpinning this chain is completely isolated from Ethereum (when that's not quite the case for proper rollups, who post data back to Mainnet)... but I don't see the fact that there is a centralized provider as a reason to not use the term "blockchain" here. I may be misunderstanding your point though, so please feel free to qualify.

**Comment by wackerow** [comment]
Closing this out for now, please @ me or re-open as-needed.
