### ISSUE TITLE
Replace one image for a component on the L2 page

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#12304]
### Is your feature request related to a problem? Please describe.

To improve the comprehension on the L2 page, I propose to change one image with an existing component used on the vision page.

from here > [https://ethereum.org/roadmap/vision](https://ethereum.org/roadmap/vision )to here [https://ethereum.org/layer-2](https://ethereum.org/layer-2)

### Describe the solution you'd like

In the section "Why do we need layer 2?" we describe what and mention scalability and a link to the "blockchain trilemma."

We have an excellent visual reference on the vision page that helps us understand this and can be helpful on the layer page.

The only difference would be to remove some text and make it vertical.

![Screen Shot 2024-02-27 12 05 18 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/f4626e89-87f9-44d4-83fc-efa0481a5a85)

Here are the changes/ports from this component.
![Screen Shot 2024-02-27 12 06 29 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/d9717f60-a920-48fe-8d4e-8bfdda1a1e12)

### Describe alternatives you've considered

not alternatives at this point, but open to ideas

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by minimalsm** [comment]
Like the idea @nloureiro.

This component has fairly unique behaviour on mobile. Do you propose keeping it the same?

**Comment by nloureiro** [comment]
> Like the idea @nloureiro.
> 
> This component has fairly unique behaviour on mobile. Do you propose keeping it the same?

yes,  I would say that it's working well as it is we should keep it, and I assume it's easier to port to this page.

**Comment by altinocoelho** [comment]
@nloureiro I would like to help with this one

**Comment by wackerow** [comment]
@nloureiro Are you proposing we _move_ the component (remove from `/vision`)? Or duplicate it's use (both pages)? Just expressing caution against reusing the exact same copy which can hurt SEO scoring

**Comment by nloureiro** [comment]
> @nloureiro Are you proposing we _move_ the component (remove from `/vision`)? Or duplicate it's use (both pages)? Just expressing caution against reusing the exact same copy which can hurt SEO scoring

My take was to use it on both pages. I think it's relevant to both content structures.
Do you have any idea how to do it without messing with the SEO?

**Comment by reetbatra** [comment]
If this is still pending, may I please take this up?

**Comment by nloureiro** [comment]
> If this is still pending, may I please take this up?

Yes. I guess...

 @altinocoelho, do you have any updates? Can we pass it over to @reetbatra ?
 
 The timing is great. @TylerAPfledderer 🤘just [updated the original component](https://github.com/ethereum/ethereum-org-website/pull/10490#issuecomment-2021182281), and we merged it yesterday with dev.
 
 Thank you for reaching out

**Comment by altinocoelho** [comment]
Sorry for the delay.

If @reetbatra is still interested, she can take it.

Otherwise, I'll look into it in the next few days.

**Comment by corwintines** [comment]
Removing the stale tag here. @nloureiro is this still something you are interested in seeing?

**Comment by nloureiro** [comment]
> Removing the stale tag here. @nloureiro is this still something you are interested in seeing?

In light of the new L2 epic we can close this issue. no longer worth the change.
calling out @konopkja to see if this idea can be used on the new pages.
