### ISSUE TITLE
Translation leaderboard is outdated

### ISSUE THREAD

**Issue by Satglow** [ethereum/ethereum-org-website#12335]
### Describe the bug

The data on this page seems to be outdated. Is there a way to automatically update it, or the monthly job failed for some reason?

https://ethereum.org/en/contributing/translation-program/acknowledgements/

For example:
![leaderboard](https://github.com/ethereum/ethereum-org-website/assets/151942349/dcd8015a-fdf7-4db4-ad6f-c9e9eb899bc5)
![Crowdin top numbers](https://github.com/ethereum/ethereum-org-website/assets/151942349/f04516e4-ca27-439a-91cb-71688110c4b3)

The description about the figure is a bit misleading: "Translators are placed on the leaderboards based on their number of ''winning'' words (number of translated words that are approved during the review)." These figures most probably reflect the translated words, not the approved, so maybe the text can be corrected too.

### To reproduce

1. Go to https://ethereum.org/en/contributing/translation-program/acknowledgements/
2. Go to https://crowdin.com/project/ethereum-org/reports/top-members
3. Compare the 2 sources

### Expected behavior

Monthly update mentioned in the text.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Thanks for reporting @Satglow, just assigned myself and can look into this

**Comment by wackerow** [comment]
Looks like Crowdin has updated the data schema for the translation costs report that we used to generate this... Added a label for grooming to chat more about how we want to approach this. 

In the meantime this data will be out of date... we could consider pausing it in the meantime, but I would advocate we just leave until we can debug the API fetch
