### ISSUE TITLE
Navigating directly to the scaling docs enters a redirect loop

### ISSUE THREAD

**Issue by Stebalien** [ethereum/ethereum-org-website#12330]
### Describe the bug

Directly visiting https://ethereum.org/en/developers/docs/scaling/ enters a redirect loop and fails to load. Navigating to this page from another page via the sidebar works just fine.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/scaling/

### Expected behavior

The page loads.

### Desktop (please complete the following information)

- Browser: Chrome, Firefox

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by cypherspeare** [comment]
can you assign me to this? happy to take a look at this
