### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by mmsaki** [ethereum/ethereum-org-website#12342]
### Dev tool name

- Wake
- Tools for Solidity (Wake) –⁠ VS Code Extension

### Dev tool description

Wake is a Python-based development and testing framework for Solidity with built-in vulnerability detectors and cross-chain fuzzing

### When did the dev tool go live?

Sep 17, 2022

### Where do you think this page should be shown?

- [Python projects and tools](https://ethereum.org/en/developers/docs/programming-languages/python/#python-projects-and-tools)
- [Unit testing for smart contracts](https://ethereum.org/en/developers/docs/smart-contracts/testing/#unit-testing-for-smart-contracts)
- [Integration testing for smart contracts](https://ethereum.org/en/developers/docs/smart-contracts/testing/#integration-testing-for-smart-contracts)
- [Static analysis](https://ethereum.org/en/developers/docs/smart-contracts/testing/#static-analysis)
- [Dynamic analysis](https://ethereum.org/en/developers/docs/smart-contracts/testing/#dynamic-analysis)
- [Testing tools and libraries](https://ethereum.org/en/developers/docs/smart-contracts/testing/#testing-tools-and-libraries)
- [Dynamic Analysis tools](https://ethereum.org/en/developers/docs/smart-contracts/testing/#dynamic-analysis-tools)
- [Development frameworks](https://ethereum.org/en/developers/docs/frameworks/)

### Is the product open source?

Yes

### GitHub URL

https://github.com/Ackee-Blockchain/wake

### Documentation URL

https://ackeeblockchain.com/wake/docs/latest/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @mmsaki, thanks for posting... If you had to prioritize the pages you listed which locations would you emphasize the most here?

**Comment by wackerow** [comment]
@corwintines Assigning you for product review but let me know if you don't have time

**Comment by mmsaki** [comment]
@wackerow The first link of "Python project and tools" is probably the page we would like to prioritize.

**Comment by wackerow** [comment]
@mmsaki Okay, thanks! I'm not saying it can only be listed in one place, but eight pages is a bit more than the usual request... Feel free to argue the case for different pages if you feel they'd bring benefit to users, especially if there is a value add compared to products already listed.

**Comment by michprev** [comment]
Hello, Wake core developer here.

After a review we would like to see Wake listed in 5 subsections (3 different pages). I've prepared a pull request (https://github.com/ethereum/ethereum-org-website/pull/12564) describing Wake more in detail and highlighting its benefits compared to other tools.

**Comment by jaczkal** [comment]
I would also love to see it listed somewhere. As far as I know, there are currently only two major Python frameworks and it is Ape and Wake

**Comment by wackerow** [comment]
Closed with #12564
