### ISSUE TITLE
Bug report: string typo

### ISSUE THREAD

**Issue by adeolu98** [ethereum/ethereum-org-website#12346]
### Describe the bug

A typo error that spells 'reveling' instead of 'revealing' as seen here https://github.com/ethereum/ethereum-org-website/blob/9d4bc8e1ed5dafe393838e657dac03409097272a/src/intl/en/common.json#L260 

### To reproduce

1. Go to 'https://ethereum.org/en/'
2. In the nav-bar click on  learn -> advanced -> zero knowledge-proofs
4. See error in description of 'zero knowledge-proofs'

### Expected behavior

https://github.com/ethereum/ethereum-org-website/blob/9d4bc8e1ed5dafe393838e657dac03409097272a/src/intl/en/common.json#L260 

**"nav-zkp-description"** should be **"A way to prove the validity of a statement without revealing the statement itself"**

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/39372980/b620c91a-9deb-4bf4-bd67-1ae2cd71b61e)

### Desktop (please complete the following information)

all desktops and desktop browsers

### Smartphone (please complete the following information)

all smartphone and mobile browsers 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Nice catch, thanks @adeolu98! Just assigned you, PR welcome =)

@all-contributors please add @adeolu98 for bug report
