### ISSUE TITLE
Event listing

### ISSUE THREAD

**Issue by TheCryptoPope** [ethereum/ethereum-org-website#12367]
### Event/Meetup Name

ETH Rio

### Website

ethereumbrasil.com

### Location (City/Country, or Remote)

Rio de Janeiro

### Description

3rd Edition of ETH Rio. ETH Rio 2024 will bring regulators, builders and businesses to discuss the future of the Brazilian Tokenized Economy based on EVM.

### Start date: (yyyy-mm-dd)

2024-05-13

### End date: (yyyy-mm-dd)

2024-05-155

### Would you like to work on this issue?

- [ ] Yes

**Comment by isabelladebrito** [comment]
gm @TheCryptoPope! The event you have requested to add has been cancelled - see announcement [here](https://www.ethereumbrasil.com/blog/postponement-of-ethereum-rio-2024). 

I'm gonna close your issue for now but feel free to continue [contributing](https://ethereum.org/en/contributing/) to ethereum.org! Thanks 🙌

**Comment by nloureiro** [comment]
@isabelladebrito re-opening the issue because these are new dates, to May.
@TheCryptoPope, can you open a PR with this?
