### ISSUE TITLE
Update glossary terms

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12365]
Update these terms to our new glossary JSON structure  from old PR, ignore others as they have been updated in a different ticket. 

ABI
block validation
bootnode
bytecode
committee
consensus client
finality
fork
fork-choice algorithm
fraud proof
Merkle Patricia trie
ommer (uncle) block
proof-of-work
reward
Recursive Length Prefix (RLP)
shard / shard chain
terminal total difficulty (TTD)

from this old PR: https://github.com/ethereum/ethereum-org-website/pull/10975

**Comment by tomasgrusz** [comment]
Happy to help with this issue, just need a quick explanation to the requested changes.

**Comment by wackerow** [comment]
Hey @konopkja, could you help clarify what needs to be done here? Just a quick spot check, I see `"terminal-total-difficulty-definition"` in both `glossary.json` and `glossary-tooltip.json`, but they are the same... is the goal here to write new tooltip definitions for these?

**Comment by konopkja** [comment]
> Hey @konopkja, could you help clarify what needs to be done here? Just a quick spot check, I see `"terminal-total-difficulty-definition"` in both `glossary.json` and `glossary-tooltip.json`, but they are the same... is the goal here to write new tooltip definitions for these?

We reviewed and closed old PR https://github.com/ethereum/ethereum-org-website/issues/12365#:~:text=this%20old%20PR%3A-,%2310975,-Add%20tasklist instead of merging it, but some of the edits in that PR were good and this issue lists the terms from the original PR that should be added to production. 

In the original PR joseph edited some of the terms. So to my knowledge most of them should be already existing, its just that joseph improved the description.

**Comment by tomasgrusz** [comment]
I understand now, thanks @konopkja. Happy to work on it then.

**Comment by konopkja** [comment]
> I understand now, thanks @konopkja. Happy to work on it then.

thats great! thank you. I will assign it to you
