### ISSUE TITLE
Bug report: GH workflow

### ISSUE THREAD

**Issue by sourabupadhya123** [ethereum/ethereum-org-website#12363]
### Describe the bug

Eliminated the use of '<<<' in the 'gh auth login' command within the 'Create Pull Request' step to ensure authentication integrity

https://github.com/ethereum/ethereum-org-website/blob/dev/.github/workflows/get-translation-progress.yml

### To reproduce

1. Go to 'https://github.com/ethereum/ethereum-org-website/blob/dev/.github/workflows/get-translation-progress.yml'
2. Click on 'github/workflows/get-translation-progress.yml'
3. Scroll down to '63 line'

### Expected behavior

By removing the '<<<' syntax from the 'gh auth login' command within the "Create Pull Request" step, authentication integrity is maintained when interacting with GitHub through the command-line interface.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Hey @sourabupadhya123, I'm not sure I understand the issue here. Could you elaborate?

**Comment by sourabupadhya123** [comment]
hey please check it here https://github.com/ethereum/ethereum-org-website/pull/12364

**Comment by minimalsm** [comment]
Thanks @sourabupadhya123,

I seen the PR, and read the docs a little bit. I just don't understand why not using `<<<` is better? Is it a security thing?

**Comment by sourabupadhya123** [comment]
The <<< operator in the gh auth login command poses a security risk because it directly embeds your personal access token within the workflow code

**Comment by wackerow** [comment]
Thanks for noting this @sourabupadhya123 ... we use the same pattern in the `get-crowdin-contributors.yml` workflow (which `get-translation-progress.yml` was templated from). Looking at it, the shell command without `<<<` should work just fine, not quite sure why this was placed here to begin with. 

Looks good to me, and if it breaks anything it won't be critical and we can just revert.

**Comment by sourabupadhya123** [comment]
That's great! to i've removed `<<<` from both `get-crowdin-contributors.yml` & `get-translation-progress.yml` files

**Comment by wackerow** [comment]
Fixed with #12364, thanks @sourabupadhya123!
