### ISSUE TITLE
Refactor Social Icons 

### ISSUE THREAD

**Issue by Gautam-Hegde** [ethereum/ethereum-org-website#12379]
#### We currently utilize older versions of social icons within our application. To ensure consistency and maintain a modern look, it's imperative to update them to the latest icons provided by `react-icons/fa6`

For example, the X (formerly Twitter) from `react-icons/fa6`

![faX](https://github.com/ethereum/ethereum-org-website/assets/85569489/8d53682d-43b6-4b03-ab8a-94cb6151a74f)

If approved, I would like to take this enhancement

**Comment by iepn** [comment]
Thank you for your suggestion. Does option #12382 meet your requirements?

**Comment by kingdayx** [comment]
Is this open?

**Comment by sidharth-05** [comment]
Hi @wackerow! Can I take on this issue.

**Comment by bhappy-buidl** [comment]
@bhappy-buidl pr plz

**Comment by corwintines** [comment]
@nloureiro just wanting your sign off on this change, then we can go through with updating this probably.

**Comment by nloureiro** [comment]
> @nloureiro just wanting your sign off on this change, then we can go through with updating this probably.

yes, go for it.

at this point the blue bird is dead

**Comment by wackerow** [comment]
@sidharth-05 Still interested in handling this? Assigning in the meantime

**Comment by Shiva-Sai-ssb** [comment]
If this is still open, can I work on this issue? 
If possible, please assign this to me. Thank you.
