### ISSUE TITLE
/community-events.json is no longer available + replace URL on /community/events/

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#12371]
### Describe the bug

/community-events.json is no longer available + replace URL on ethereum.org/community/events/

### To reproduce

1. Go to [ethereum.org/en/community/events/](https://ethereum.org/en/community/events/)
2. Scroll down to check the text `This is a non-exhaustive list maintained by our community. Know of an upcoming Ethereum event to add to this list? Please add it!`
3. Click on the hyperlink mentioned in the text: https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.json
4. See 404 error
<img width="1130" alt="Screenshot 2024-03-05 at 14 07 00" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/44bb4bad-2a27-42f2-8207-e3fffdded248">

### Expected behavior

- /community-events.json should be working
- fixed hyperlink on ethereum.org/community/events 

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Gautam-Hegde** [comment]
redirect here instead?
https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.ts

**Comment by minimalsm** [comment]
@Gautam-Hegde yes, this is the correct file :) want to put up a PR?

**Comment by Gautam-Hegde** [comment]
Sure!
