### ISSUE TITLE
Change the footer navigation

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#12376]
### Is your feature request related to a problem? Please describe.

With the new Header Navigation in production, we want to explore the change on the footer.
It does not need to have the same information architecture, but it should be updated.

### Describe the solution you'd like

A new navigation on the footer

### Describe alternatives you've considered

as many as possible

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by Satglow** [comment]
![ethereum org footer proposal](https://github.com/ethereum/ethereum-org-website/assets/151942349/ee6ee01f-5ea2-4978-bbb5-3090f677d81d)


- I have followed the header menu, including the lowest level of the hierarchy where it is useful to the user to see it (e.g. Emerging use cases), but including the middle hierarchy element if the summary expression is enough to navigate (e.g. staking) or the lowest level is too detailed (e.g. how to guide examples). 
- Called the overview item as home (Documentation home), or kept as hub if it was already in the list with this expression (Learn Hub), we can use one of them for all place.
- Regarding the Enterpise under Build, I thought it is more meaningful if using both hierarchy levels (Enterprise - Mainnet Ethereum) instead of listing Mainnet Ethereum and Private Ethereum without much context.
- I kept the already added items like EF, EF blog, ESP etc. I am not aware of any more relevant for this topic.
- Added a "General" tab, including Brand assets from Ecosystem, Glossary from Learn, Code of conduct as new potential and relevant item, and kept the rest from About ethereum.org list.

**Comment by nloureiro** [comment]
Thank you.

I created a Figma file to test it on top of the Footer we have for the design system > feel free to edit and comment
https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=1%3A48&mode=design&t=T8aolwB1Rvv4mbHi-1
![Screen Shot 2024-03-06 10 42 55 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/a84e0c8a-448b-4eb0-82f3-7a0bcb5aa95b)

My first reaction is that it can be too many columns. I tried to remove one, but even so... might be too much

![Screen Shot 2024-03-06 10 43 02 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/bff2a446-bc42-413c-b968-46e76e6fe0e7)

maybe add a dipper level like the header? accordion like the mobile menu? or curate some of the links and make the list smaller

**Comment by Satglow** [comment]
Thanks, this is a great visualization. I didn't know that the previous version was not good, so I shouldn't simulate that with new content. I have curated the list to try with a shorter version. 

![ethereum org footer proposal v2](https://github.com/ethereum/ethereum-org-website/assets/151942349/ba907e80-6e16-4cf2-ad75-51ff87f071e3)


If it is workable, for example we can call Learn hub based on the main content that we find there = What is Ethereum, ETH & web3? Maybe a bit long, but 1 row instead of 4. (What is Ethereum & ETH? also a good version) Same for Community hub = Online communities & events

We could maybe merge the columns like Learn & Use, Build & Research, Participate (also with the items from General). One option is 3 columns with long list, or again a shorter curated list like below.

![ethereum org footer proposal v3](https://github.com/ethereum/ethereum-org-website/assets/151942349/ee5ad98d-c427-4047-b6f2-7ef356eeb48a)

**Comment by iepn** [comment]
> Thank you.
> 
> I created a Figma file to test it on top of the Footer we have for the design system > feel free to edit and comment https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=1%3A48&mode=design&t=T8aolwB1Rvv4mbHi-1 ![Screen Shot 2024-03-06 10 42 55 AM](https://private-user-images.githubusercontent.com/1120748/310465638-a84e0c8a-448b-4eb0-82f3-7a0bcb5aa95b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc1NTUsIm5iZiI6MTcwOTc5NzI1NSwicGF0aCI6Ii8xMTIwNzQ4LzMxMDQ2NTYzOC1hODRlMGM4YS00NDhiLTRlYjAtODJmMy03YTBiY2I1YWE5NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDc0MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlhNTE4YTU0NDA2ZDUyMDM1MjM5NWIxOGJjYTJiNjIyYjRjNWQzZmJlZDhkYTQyYjBlODM5NTU2NWFhZjNhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z8LOiF00xAiq1MVTACIccN7boJEliu_DVUJg9a3W-uI)
> 
> My first reaction is that it can be too many columns. I tried to remove one, but even so... might be too much
> 
> ![Screen Shot 2024-03-06 10 43 02 AM](https://private-user-images.githubusercontent.com/1120748/310465659-bff2a446-bc42-413c-b968-46e76e6fe0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc1NTUsIm5iZiI6MTcwOTc5NzI1NSwicGF0aCI6Ii8xMTIwNzQ4LzMxMDQ2NTY1OS1iZmYyYTQ0Ni1iYzQyLTQxM2MtYjk2OC00NmU3NmU2ZmUwZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDc0MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDdjNDZkNDBkMjYzMmI0YWY4ZjFkMTdkZGJkMDYxNjBkNGFmYzEwNTU2OTFiZDNhYmJkOTJkODBlYTM2NjJiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FhVda0DZOgC7IbcZNI3vaB8bKjlI0ZOCPNG_f3oaHO0)
> 
> maybe add a dipper level like the header? accordion like the mobile menu? or curate some of the links and make the list smaller

![CleanShot 2024-03-07 at 15 41 12](https://github.com/ethereum/ethereum-org-website/assets/57232813/052300c6-3870-4b8f-9620-5deb3fc8beaa)

Hey! I noticed there is a YouTube icon in your prototype, so I added a YouTube link and a new Twitter icon in pull request #12382. If you or the team do not plan to update the Twitter icon, I can remove it, leaving only the YouTube icon.

**Comment by nloureiro** [comment]
> ![CleanShot 2024-03-07 at 15 41 12](https://private-user-images.githubusercontent.com/57232813/310788339-052300c6-3870-4b8f-9620-5deb3fc8beaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDgwMTAsIm5iZiI6MTcwOTgwNzcxMCwicGF0aCI6Ii81NzIzMjgxMy8zMTA3ODgzMzktMDUyMzAwYzYtMzg3MC00YjhmLTk2MjAtNWRlYjNmYzhiZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEwMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTFlYTc4Y2Y5OTQ4NjY3NDk0YThlY2YwYTgwMDQyZDI0MzZhZjFiMzUwMTQ0ZjZkYzAxOWRkMDk4MzY4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gynzUONmatoYnKTo7b9_RFugETro1PiFl0bbkeK2MMs)
> 
> Hey! I noticed there is a YouTube icon in your prototype, so I added a YouTube link and a new Twitter icon in pull request #12382. If you or the team do not plan to update the Twitter icon, I can remove it, leaving only the YouTube icon.
> 
> > Thank you.
> > I created a Figma file to test it on top of the Footer we have for the design system > feel free to edit and comment https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=1%3A48&mode=design&t=T8aolwB1Rvv4mbHi-1 ![Screen Shot 2024-03-06 10 42 55 AM](https://private-user-images.githubusercontent.com/1120748/310465638-a84e0c8a-448b-4eb0-82f3-7a0bcb5aa95b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc1NTUsIm5iZiI6MTcwOTc5NzI1NSwicGF0aCI6Ii8xMTIwNzQ4LzMxMDQ2NTYzOC1hODRlMGM4YS00NDhiLTRlYjAtODJmMy03YTBiY2I1YWE5NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDc0MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlhNTE4YTU0NDA2ZDUyMDM1MjM5NWIxOGJjYTJiNjIyYjRjNWQzZmJlZDhkYTQyYjBlODM5NTU2NWFhZjNhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z8LOiF00xAiq1MVTACIccN7boJEliu_DVUJg9a3W-uI)
> > My first reaction is that it can be too many columns. I tried to remove one, but even so... might be too much
> > ![Screen Shot 2024-03-06 10 43 02 AM](https://private-user-images.githubusercontent.com/1120748/310465659-bff2a446-bc42-413c-b968-46e76e6fe0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc1NTUsIm5iZiI6MTcwOTc5NzI1NSwicGF0aCI6Ii8xMTIwNzQ4LzMxMDQ2NTY1OS1iZmYyYTQ0Ni1iYzQyLTQxM2MtYjk2OC00NmU3NmU2ZmUwZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDc0MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDdjNDZkNDBkMjYzMmI0YWY4ZjFkMTdkZGJkMDYxNjBkNGFmYzEwNTU2OTFiZDNhYmJkOTJkODBlYTM2NjJiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FhVda0DZOgC7IbcZNI3vaB8bKjlI0ZOCPNG_f3oaHO0)
> > maybe add a dipper level like the header? accordion like the mobile menu? or curate some of the links and make the list smaller


Oh, you just found a bug on the design system, the YouTube icon was removed last year, and I did not update the Figma file, my bad, sorry about this (was this PR https://github.com/ethereum/ethereum-org-website/pull/10775)
Can you roll back on your PR? I will change on the DS, too, and add the X icon.

**Comment by iepn** [comment]
> > ![CleanShot 2024-03-07 at 15 41 12](https://private-user-images.githubusercontent.com/57232813/310788339-052300c6-3870-4b8f-9620-5deb3fc8beaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDgwMTAsIm5iZiI6MTcwOTgwNzcxMCwicGF0aCI6Ii81NzIzMjgxMy8zMTA3ODgzMzktMDUyMzAwYzYtMzg3MC00YjhmLTk2MjAtNWRlYjNmYzhiZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEwMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTFlYTc4Y2Y5OTQ4NjY3NDk0YThlY2YwYTgwMDQyZDI0MzZhZjFiMzUwMTQ0ZjZkYzAxOWRkMDk4MzY4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gynzUONmatoYnKTo7b9_RFugETro1PiFl0bbkeK2MMs)
> > Hey! I noticed there is a YouTube icon in your prototype, so I added a YouTube link and a new Twitter icon in pull request #12382. If you or the team do not plan to update the Twitter icon, I can remove it, leaving only the YouTube icon.
> > > Thank you.
> > > I created a Figma file to test it on top of the Footer we have for the design system > feel free to edit and comment https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=1%3A48&mode=design&t=T8aolwB1Rvv4mbHi-1 ![Screen Shot 2024-03-06 10 42 55 AM](https://private-user-images.githubusercontent.com/1120748/310465638-a84e0c8a-448b-4eb0-82f3-7a0bcb5aa95b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc1NTUsIm5iZiI6MTcwOTc5NzI1NSwicGF0aCI6Ii8xMTIwNzQ4LzMxMDQ2NTYzOC1hODRlMGM4YS00NDhiLTRlYjAtODJmMy03YTBiY2I1YWE5NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDc0MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlhNTE4YTU0NDA2ZDUyMDM1MjM5NWIxOGJjYTJiNjIyYjRjNWQzZmJlZDhkYTQyYjBlODM5NTU2NWFhZjNhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z8LOiF00xAiq1MVTACIccN7boJEliu_DVUJg9a3W-uI)
> > > My first reaction is that it can be too many columns. I tried to remove one, but even so... might be too much
> > > ![Screen Shot 2024-03-06 10 43 02 AM](https://private-user-images.githubusercontent.com/1120748/310465659-bff2a446-bc42-413c-b968-46e76e6fe0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc1NTUsIm5iZiI6MTcwOTc5NzI1NSwicGF0aCI6Ii8xMTIwNzQ4LzMxMDQ2NTY1OS1iZmYyYTQ0Ni1iYzQyLTQxM2MtYjk2OC00NmU3NmU2ZmUwZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDc0MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDdjNDZkNDBkMjYzMmI0YWY4ZjFkMTdkZGJkMDYxNjBkNGFmYzEwNTU2OTFiZDNhYmJkOTJkODBlYTM2NjJiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FhVda0DZOgC7IbcZNI3vaB8bKjlI0ZOCPNG_f3oaHO0)
> > > maybe add a dipper level like the header? accordion like the mobile menu? or curate some of the links and make the list smaller
> 
> Oh, you just found a bug on the design system, the YouTube icon was removed last year, and I did not update the Figma file, my bad, sorry about this (was this PR #10775) Can you roll back on your PR? I will change on the DS, too, and add the X icon.

I'm really sorry. I can directly modify and remove the YouTube icon in the pull request, leaving only a Twitter x icon. You can check it in #12379.

**Comment by nloureiro** [comment]
> Thanks, this is a great visualization. I didn't know that the previous version was not good, so I shouldn't simulate that with new content. I have curated the list to try with a shorter version.
> 
> ![ethereum org footer proposal v2](https://private-user-images.githubusercontent.com/151942349/310530394-ba907e80-6e16-4cf2-ad75-51ff87f071e3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDgwMTAsIm5iZiI6MTcwOTgwNzcxMCwicGF0aCI6Ii8xNTE5NDIzNDkvMzEwNTMwMzk0LWJhOTA3ZTgwLTZlMTYtNGNmMi1hZDc1LTUxZmY4N2YwNzFlMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMDM1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjJlNzUyYWNkYzljYmVhZDc2ZmI5ODUxMTk0NWQ0ZjE1ZThjMDQ4OTA2MWVkNTVkM2U4ZjRiMzY4ODBhZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CHXw3BJzRYJgFu5my3rgytCNTnTxws9Q6VHFkEJmVb4)
> 
> If it is workable, for example we can call Learn hub based on the main content that we find there = What is Ethereum, ETH & web3? Maybe a bit long, but 1 row instead of 4. (What is Ethereum & ETH? also a good version) Same for Community hub = Online communities & events
> 
> We could maybe merge the columns like Learn & Use, Build & Research, Participate (also with the items from General). One option is 3 columns with long list, or again a shorter curated list like below.
> 
> ![ethereum org footer proposal v3](https://private-user-images.githubusercontent.com/151942349/310533574-ee5ad98d-c427-4047-b6f2-7ef356eeb48a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDgwMTAsIm5iZiI6MTcwOTgwNzcxMCwicGF0aCI6Ii8xNTE5NDIzNDkvMzEwNTMzNTc0LWVlNWFkOThkLWM0MjctNDA0Ny1iNmYyLTdlZjM1NmVlYjQ4YS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMDM1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTA1MTg4NzI4ZmJmZTE0ZmQ3YzVhOGM2MmQyZmMyOTI4OTc5ZGM5Y2I1ZWVlZTU4YjU1MTMyMGYzMmU4YjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dYdayXJH5apQmJboiYe5MZzT9kDoIX4mqS8tVHNTJV0)



Thank you for the second version, but I think it makes harder to understand

I did some explorations on figma, but I got to a point that the quick win here is your first proposal with minor design adjustments.

 - change some spacing 
 - different braskdown for smaller screens
 - add a footer to the footer for the links that ar enot on the top menu and can be consider secundary

@Satglow let me know what do think on figma > https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=4%3A43546&mode=design&t=rReoPKKv7zMDOBfh-1


@wackerow what do think, is it fast to build a PR with is to test on the browser?

**Comment by Satglow** [comment]
Thanks a lot, I am okey with that! The shorter list still can work without merging the items, if you are looking for less item. Like this:

![ethereum org footer proposal v4](https://github.com/ethereum/ethereum-org-website/assets/151942349/3f244f52-dbda-456d-8a23-5317c1531de6)

I think the 'secondary' is great as footer of footer, just we should not leave out, because this is not available elsewhere - i think this is one of the main purpose of the footer part.
