### ISSUE TITLE
Missing auto-linked headers on glossary page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12393]
### Describe the bug

The glossary page was previously entirely markdown, which had custom header IDs for each glossary entry header, ie `### Account {#account}`. This has been converted to using a custom component for each term entry, ie `<GlossaryDefinition term="account" />`.

This component renders a header that _does_ contain an **id** (ie. `<h3 ... id="account">`), but does _not_ include the auto-linking (link to self) like the section headers do.

### To reproduce

1. Go to https://ethereum.org/en/glossary/
2. Hover over "A", and notice the link icon that appears, which contains a link to itself
3. Hover over a glossary term such as "Account", and notice this _does not_ contain a link to itself

### Expected behavior

All headers on this page should have an auto-link to the ID of that section, including a hover effect to quickly access this link.

### Screenshots

<img width="987" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/66ab8ec9-bab9-498c-983d-d6d0d8985926">

When hovering over "A"... but this does not occur when hovering over "Account"

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by korbinschulz** [comment]
I'd like to take this issue. Went through the repo and found how the glossary sections have their links set up and viewed the GlossaryDefinition component, so I believe I'd just essentially do the same thing there.

**Comment by resourcefulmind** [comment]
Hi there chief! 

I've noticed the missing auto-link headers on the glossary page, and I'd like to jump in and help fix that. I'm familiar with React and front-end development, so I think I could tackle this issue. 
Could you point me to the component or area of the codebase where this needs to be addressed? 

Excited to contribute to improving the site's UX!

**Comment by wackerow** [comment]
Thanks @korbinschulz and @resourcefulmind for offering to help! Sorry for delay, looks like @checkomkar has a PR up that could solve this already, so going to assign to avoid redundant work. Feel free to check out that solution and add to the discussion

**Comment by wackerow** [comment]
Hm, actually I can't seem to assign @checkomkar, but the PR is linked... can come back after that is reviewed if more help needed.
