### ISSUE TITLE
Add `ethers-kt` to developer tooling docs

### ISSUE THREAD

**Issue by ArtificialPB** [ethereum/ethereum-org-website#12409]
### Dev tool name

ethers-kt

### Dev tool description

Async, high-performance Kotlin library for interacting with EVM-based blockchains. Targeting JVM and Android platforms. 

## Features:

- **High Performance**: Optimized types and code to minimize the number of allocations and copying.

- **Clean Abstractions**: Intuitive, extensible, and easy to use.

- **Async**: RPC requests are async by default, with helper functions for awaiting results.

- **Safe**: RPC calls return an error object in case of failure, instead of throwing an exception.

- **Smart contract bindings**:
    - Generate type-safe smart contract bindings from JSON-ABI files.
    - Complete support: events (anonymous), custom errors, structs, receive and fallback functions.
    - Custom errors can be resolved from any source (e.g. generated bindings, 4byte directory, etc...).
    - Payable and non-payable functions/constructors.
- **Batch RPC calls**: RPC calls can be batched together in a single call, reducing the number of round trips to the
  server.
- **Multicalls**: Fully typed multicalls from any smart contract binding

##
We are currently also preparing roadmap for supporting [Kotlin Multiplatform](https://kotlinlang.org/docs/multiplatform.html), which will make it possible to use this library for developing Android, iOS, Desktop, and Web apps using a single codebase. This will allow teams to ship faster on multiple platforms. The roadmap will go public in a week or two.

### When did the dev tool go live?

October 2023

### Where do you think this page should be shown?

The tools should be added to the following pages:
- java tooling (https://ethereum.org/en/developers/docs/programming-languages/java/#working-with-ethereum-clients)
- backend libraries (https://ethereum.org/en/developers/docs/apis/backend/#available-libraries)
- Dapp development frameworks (https://ethereum.org/en/developers/docs/frameworks/#available-frameworks)

### Is the product open source?

Yes

### GitHub URL

https://github.com/Kr1ptal/ethers-kt

### Documentation URL

https://github.com/Kr1ptal/ethers-kt

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @ArtificialPB, thanks for the suggestion!

Overall this looks good to me, with a couple notes... 

> java tooling (https://ethereum.org/en/developers/docs/programming-languages/java/#working-with-ethereum-clients)
> backend libraries (https://ethereum.org/en/developers/docs/apis/backend/#available-libraries)
> Dapp development frameworks (https://ethereum.org/en/developers/docs/frameworks/#available-frameworks)

- Location 1: Java page sounds good to me, but I don't personally work with Kotlin so will just float the question if you think this is most appropriate, or if a separate page for Kotlin would make sense?
- Locations 2 and 3: These pages already have a pretty long list of options for users. We're always cautious of making these lists too long as they can start to inhibit user experience and overwhelm users. @konopkja Wouldn't mind hearing your thoughts here... any suggestions for these pages from a design perspective? These are deep in the dev docs, so I'm personally more comfortable having longer lists of resources here, but wanted to offer the chance for input.

Assigning you in the meantime @ArtificialPB! Let us know if you have issues/questions

**Comment by konopkja** [comment]
> * https://ethereum.org/en/developers/docs/frameworks/#available-frameworks

yeah i think its okay if each tool has some different usage description for guidance or if there are different lists, we like in some of there examples we could have them inside collapsed component for easier overview of all different lists, because right now some of them are indeed growing a lot

**Comment by wackerow** [comment]
Okay...  perhaps we go ahead with this being listed in the traditional manner, and we could discuss separately a way to clean up these listings.

**Comment by ArtificialPB** [comment]
Hey @wackerow , thanks for the feedback. I suggest only the Java page for now as that's currently the supported target of the library. It will make sense to add a separate Kotlin section once we start implementing the Kotlin Multiplatform support. In any case, as long as the library targets Java it should also be on the Java page.

I have a PR ready with these changes, would love to get some feedback when you have time: https://github.com/ethereum/ethereum-org-website/pull/12126

**Comment by ArtificialPB** [comment]
Task has been completed with last release, closing. Thanks
