### ISSUE TITLE
Add NapulETH Open Village to events

### ISSUE THREAD

**Issue by startapple** [ethereum/ethereum-org-website#12427]
### Event/Meetup Name

NapulETH Open Village

### Website

napul.eth.limo

### Location (City/Country, or Remote)

Naples/Italy

### Description

The Biggest ETH Event in Southern Italy

### Start date: (yyyy-mm-dd)

2024-09-12

### End date: (yyyy-mm-dd)

2024-09-14

### Additional context

NapulETH envisions a future where the next billion users are part of the Ethereum blockchain. We aspire to break the current echo chamber within Web3 conferences, which tend to be attended by the same insiders, and to reach out to those who are yet to engage with the Web3 space. The community believes in creating inclusive, open formats for events that allow people from all walks of life to participate, learn, and contribute to the Ethereum ecosystem. 
NapulETH aims to:
1. Engage a broader audience with Ethereum, including students, professionals, and local residents who may not typically attend a Web3 conference.
2. Educate newcomers about the Ethereum blockchain through tailored experiences aimed at varying levels of familiarity with the technology.
3. Create a sustainable and replicable model for their Open Village initiative to periodically introduce new individuals to Ethereum and Web3.

### Would you like to work on this issue?

- [ ] Yes

**Comment by wackerow** [comment]
Thanks @startapple! PR up to add this
