### ISSUE TITLE
README: Incorrect Reference to Translations File

### ISSUE THREAD

**Issue by ymqy** [ethereum/ethereum-org-website#12429]
### Describe the bug

The README incorrectly refers to a non-existent 'data/translations.json' file. In the repository, 'i18n.config.json' lists all supported languages, while 'data/translationProgress.json' includes both supported and unsupported languages along with translation progress. script relies on the list of supported languages from 'i18n.config.json'.

### To reproduce

https://github.com/ethereum/ethereum-org-website?tab=readme-ov-file#4-make-awesome-changes

### Expected behavior

the reference to 'data/translations.json' should be updated to 'i18n.config.json' 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by nhsz** [comment]
@ymqy as the PR was already open and fixing the issue, I approved and merge it. [I also mentioned to the PR author to wait next time](https://github.com/ethereum/ethereum-org-website/pull/12441#pullrequestreview-1935234409) for the PR to be assigned. The [assignment process](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/github-issue-triage-process.md#assignment-process) gives priority if no one is already working on it.

**Comment by ymqy** [comment]
@nhsz Thank you for pointing this out. I chose not to directly submit a pull request (PR) and instead waited to be assigned to the issue after reviewing the assignment process. I believe the description of the assignment process needs to be updated to clarify that if the person who reported the issue is interested in resolving it, they should feel encouraged to submit a PR directly.
