### ISSUE TITLE
List ETHBratislava event

### ISSUE THREAD

**Issue by SFabisik** [ethereum/ethereum-org-website#12448]
### Event/Meetup Name

ETHBratislava

### Website

www.ethbratislava.com

### Location (City/Country, or Remote)

Bratislava, Slovakia

### Description

With this pioneering event in Slovakia we are finally uniting a passionate community engaged in the Ethereum ecosystem's economics, governance, and technology.

### Start date: (yyyy-mm-dd)

2024-05-10

### End date: (yyyy-mm-dd)

2024-05-11

### Would you like to work on this issue?

- [ ] Yes

**Comment by wackerow** [comment]
Thanks @SFabisik! Just put up a PR to add this
