### ISSUE TITLE
Add "use bridges" section to the bridge page 

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#12450]
### Is your feature request related to a problem? Please describe.

We have a page on bridges:
https://ethereum.org/en/bridges/

Currently it describes bridges but doesn't explain how or where to use any.

### Describe the solution you'd like

Add a "use bridges" section to the page.

Simple solution might be to just link to some resources that list out bridges, e.g.
- Risk analysis: https://l2beat.com/bridges/risk
- Bridge assets: https://transferto.xyz/swap

### Describe alternatives you've considered

We could build our own widget similar to https://transferto.xyz/swap but I suspect that might be more effort than it's worth to build & maintain.

### Additional context

Somewhat related improvement to the page, I think L2BEAT has useful definitions on the types of bridges:
- token bridges
- liquidity networks

I suspect that will be more helpful vs. what we have:
- trusted bridges
- trustless bridges

Or perhaps those types we could add in addition to "trusted" & "trustless".

Here's a Devcon talk with more info on the different bridge types:
https://www.youtube.com/watch?v=10welw1d_Bc

**Comment by reetbatra** [comment]
shall I take this one next? please feel free to assign any high-priority issues, just in case.

**Comment by wackerow** [comment]
Thanks @reetbatra! Just assigned you to this task 🙏

**Comment by minimalsm** [comment]
Hey @reetbatra, thanks for offering to help here :) let us know if you need anything.

**Comment by sidharth-05** [comment]
Hi @wackerow I'd love to take on this issue since it's been stale for 30 days!

**Comment by corwintines** [comment]
@sidharth-05 are you still interested in this?

**Comment by SeanXLChen** [comment]
@corwintines I would like to take this one if @sidharth-05 and @reetbatra been stale

**Comment by SeanXLChen** [comment]
@corwintines  Let me know

**Comment by corwintines** [comment]
Assigned to you @SeanXLChen :) I think for this mostly just building out resources for now would be good.

**Comment by SeanXLChen** [comment]
> Assigned to you @SeanXLChen :) I think for this mostly just building out resources for now would be good.

Sounds good to me.
