### ISSUE TITLE
ZkSync zkPorter Broken Link in Validium Article

### ISSUE THREAD

**Issue by doutv** [ethereum/ethereum-org-website#12462]
### Describe the bug

At the end of this article https://ethereum.org/en/developers/docs/scaling/validium/
The link to zkPorter documentation is broken.

`[Documentation](https://docs.zksync.io/zkevm/#what-is-zkporter)`

### To reproduce

https://github.com/ethereum/ethereum-org-website/blob/dev/public/content/developers/docs/scaling/validium/index.md#use-validiumvolitions-use-validium-and-volitions

![image](https://github.com/ethereum/ethereum-org-website/assets/20609724/fc841f9e-65a8-4efa-85d2-7a2b70bb8554)

### Expected behavior

https://blog.matter-labs.io/zkporter-a-breakthrough-in-l2-scaling-ed5e48842fbf

I think this one should be used. It is zkSync's Medium post, and this link is referenced in their latest official docs. 

https://docs.zksync.io/zk-stack/concepts/hyperchains-hyperscaling.html#how-hyperbridges-work
![image](https://github.com/ethereum/ethereum-org-website/assets/20609724/e827fb51-5395-4370-b990-79ed334ad56c)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Looks good! Thanks for reporting @doutv...

My only suggestion would be to just list both of these links. Not a lot of content on this stuff already, so we could add a link to "Blog post" (or something similar, using the blog.matterlabs.io link), and update "Documentation" to the docs.zksync.io link.

Assigning you! Small request, if you could please update the same link on the non-English versions of the page. If you search the repo for `https://docs.zksync.io/zkevm/#what-is-zkporter` you'll find where these are, and just replace with `https://docs.zksync.io/zk-stack/concepts/hyperchains-hyperscaling.html#how-hyperbridges-work`... for these, just leave the existing translated "Documentation" label untouched, and don't add the blog post link... this will get added through the translation process separately.

Let us know if you have issues

@all-contributors please add @doutv for bug report
