### ISSUE TITLE
Disappearing and overlapping words at Russian version of "Pooled staking"

### ISSUE THREAD

**Issue by UNOFFICIALbgd** [ethereum/ethereum-org-website#12473]
### Describe the bug

Some words overlaps and one word disappers. For more detailes see screenshots

### To reproduce

1. Go to 'https://ethereum.org/ru/staking/pools/#why-stake-with-a-pool'
2. Choose Russian language
3. Scroll down to 'Исследуйте стейкинг-пулы'(Explore staking pools) and look at the block right above
4. Сhoose consistently "Проверено", "Вознаграждения за найденные ошибки" and "Испытано в реальных условиях"

### Expected behavior

Words shouldn't disappear and overlap

### Screenshots

First screenshot - everything is okay
![image_2024-03-15_23-20-10](https://github.com/ethereum/ethereum-org-website/assets/71248977/560f1180-02b3-4ef5-9374-97b58d50d4ab)
Second screenshot - word "ошибки" disappears
![image_2024-03-15_23-21-08](https://github.com/ethereum/ethereum-org-website/assets/71248977/aaea5c28-6a72-473b-ad0a-a597565b9c47)
Third screenshot - overlapping words
![image_2024-03-15_23-22-23](https://github.com/ethereum/ethereum-org-website/assets/71248977/7e2dd920-5a2b-4c2d-80b0-07ccc2b89fb3)

### Desktop (please complete the following information)

Windows OS, chrome - latest version

### Additional context

This bug may also appear in other languages, but not necessarily with "Bug bounty" string

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Hey @UNOFFICIALbgd, thanks for reporting this! cc: @nloureiro Could use some design eyes on this component, looks like we need to improve text overflow handling at the very least.

**Comment by wackerow** [comment]
@all-contributors please add @UNOFFICIALbgd for bug report

**Comment by nloureiro** [comment]
I was checking and the quick way to fix is to ellipsis the text

![Screen Shot 2024-03-19 11 13 15 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/f48d63bb-3556-42d8-90b5-bc7d1bd31f9a)


we might need to change the code later, to accommodate 2(or more) lines of text here

**Comment by wackerow** [comment]
Okay, yeah I agree that seems like the easiest/simplest fix for now.

Will open up to community, if anyone would like to fix this up by preventing the text wrap and using a `textOverflow="ellipsis"` 🙏

**Comment by iepn** [comment]
> Okay, yeah I agree that seems like the easiest/simplest fix for now.
> 
> Will open up to community, if anyone would like to fix this up by preventing the text wrap and using a `textOverflow="ellipsis"` 🙏

 Perhaps we can try  `display: table;` ?

![CleanShot 2024-03-21 at 09 24 19](https://github.com/ethereum/ethereum-org-website/assets/57232813/8a98eb48-e6b7-4049-b3df-ecec74314f16)

**Comment by nloureiro** [comment]
ok, this takes a bit more than a quick fix but can be a better fix

- remove the arrow
- remove the primary background and add the same one form the right
- remove the gap
- add a bit of padding up and down
- remove the fix height

![Screen Shot 2024-03-21 11 17 40 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/b4008592-dbf0-4d0d-943f-3ee363341c33)

@iepn @wackerow what do you think?

**Comment by wackerow** [comment]
Looks good to me! Only tiny suggestion, add some padding to the end of the item... ie. in the above screenshot, "as" is awkwardly close to the gray box on the right. Use `pe` for this (`pe="2"` would probably be enough; 8px or 0.5rem), which is short for `padding-inline-end` (direction agnostic for RTL langs... don't use `pr` or `padding-right`)

<img width="1082" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/04bc821a-5c04-4991-8415-8466226d7295">

(Just a general note/reminder to keep RTL locales like `fa` or `ar` in mind when testing this... should work in both directions: https://ethereum.org/fa/staking/solo/#node-tool-considerations)

**Comment by wackerow** [comment]
And on that note, if anyone is interested in working on this just comment and we can assign you.

**Comment by iepn** [comment]
> And on that note, if anyone is interested in working on this just comment and we can assign you.

I can try.
