### ISSUE TITLE
Fix typo on the Testing smart contracts page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#12508]
### Describe the bug

There is a typo in the _Testing vs audits and bug bounties_ section of the _Testing smart contracts_ page
Specifically, the 4th paragraph of this chapter includes a duplicate word 'involves'

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/smart-contracts/testing/#testing-vs-audits-bug-bounties
2. Read the first sentence of the 4th paragraph in this section
3. See error

### Expected behavior

One instance of the word 'involves' should be removed

### Screenshots

<img width="642" alt="Screenshot 2024-03-19 at 22 41 47" src="https://github.com/ethereum/ethereum-org-website/assets/37338979/82506c82-ccf3-4569-8e61-dad0ec6932e9">

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by jennyg0** [comment]
working on this!

**Comment by reetbatra** [comment]
Was trying to fix other issues and noticed this along the way so raised a PR to fix this: https://github.com/ethereum/ethereum-org-website/pull/12517

Please review and close this issue.

**Comment by wackerow** [comment]
@reetbatra Closing!

<img width="315" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/d67cf524-794c-4bfc-a8f9-70d38b71d59a">

Btw, small pro tip, if you use the syntax `Closes #12508` in your PR (or `Fixes #12508`, it will automatically link the PR to the issue, and the issue will automatically be closed when the PR is merged. I usually add this under `## Related issue` and use a bullet list, which GitHub will then parse the issue hash number into a nice looking link with the issue title shown:

<img width="222" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/63e8b147-fe84-4a68-aff3-93378e6a1257">

...renders as...

<img width="822" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/6ab2fa06-b29b-42a5-abd4-40aa5c9addff">


(Example: #12469)

All good here, but in the future just insert whatever the issue number is that your PR is addressing, and the rest will be automatic. Thanks again!
