### ISSUE TITLE
ether-first-app

### ISSUE THREAD

**Issue by gitgoroda** [ethereum/ethereum-org-website#12537]
### Tutorial title

for beginner

### Tutorial description

If you are the first beginner at Ethereum, this document is so great.

### Tutorial tags

aaa

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials hosted elsewhere: URL to tutorial

github.com

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @gitgoroda, not sure I understand the request here... Going to close this out, but if you have a tutorial topic you'd like to see you can update with details and re-open. Thanks!
