### ISSUE TITLE
Organize "available libraries" list on /apis/backend/

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12545]
### Is your feature request related to a problem? Please describe.

https://ethereum.org/en/developers/docs/apis/backend/#available-libraries

The list of available libraries on this page has grown to a point where the guidance for users has degraded. With PR #10365, their are now 26 products listed now, seemingly in no particular order, not even alphabetical.

### Describe the solution you'd like

Look through these products and try to categorize them into a few groups, based on what different users may be looking for. Using h3's (`###`) to make the different category types easier to see and access, and potentially even add a short description sentence to each one before listing the products inside.

Sorting of products in each group should follow a consistent pattern (would recommend alphabetical for simplicity)

### Describe alternatives you've considered

- Leave these as-is, close issue
- Prune list based on listing policy

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Pedrojok01** [comment]
Hey @wackerow, I have reorganized and updated the backend API libraries as suggested. Here is the PR:
https://github.com/ethereum/ethereum-org-website/pull/12605

Let me know what you think.

**Comment by wackerow** [comment]
Closed with #12605
