### ISSUE TITLE
Bug report: Broken Link and Content Update

### ISSUE THREAD

**Issue by HemaDeviU** [ethereum/ethereum-org-website#12540]
### Describe the bug

1) The link to claim POAP (Proof of Attendance Protocol) from Discord is invalid.
2) The channel to claim POAP has changed. The correct channel is #🥇 | proof-of-contribution.

### To reproduce

1. Go to https://ethereum.org/en/contributing/translation-program/acknowledgements/#poap
2. Scroll down to POAPs > How to Claim
3. Click on 'Discord server'.
4. Scroll down to read the next line.

### Expected behavior

How to claim
1) Join our [Discord server](https://discord.com/invite/ethereum-org)
2) Paste a link to your Crowdin account in the #🥇 |proof-of-contribution channel.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Good catch, thanks for reporting @HemaDeviU! The correct link is https://ethereum.org/discord... I see you marked "Yes" to wanting to help so I've gone ahead and assigned you if you wouldn't mind updating that link.

If possible, could you please update this same broken link everywhere in the repo? I see 9 places in 6 files:

```
9 results - 6 files

public/content/translations/de/community/online/index.md:
  28: <SocialListItem socialIcon="discord"><Link to="https://discord.gg/CetY6Y4">Ethereum.org Website-Team</Link> - Kommen Sie vorbei and schreiben Sie mit dem Team und anderen aus der Gemeinschaft über Ethereum.org Web-Entwicklung und Design</SocialListItem>

public/content/translations/es/about/index.md:
   97: **¿Quiere involucrarse? ** [Entérese de las maneras en las que puede contribuir](/contributing/), [envié un mensjae en Twitter](https://twitter.com/ethdotorg), o únase a las discusiones de la comunidad en [nuestro servidor de Discord](https://discord.gg/CetY6Y4).

  121: Publicaremos aquí las ofertas de empleo. Si no ve aquí una función que se adapte a su perfil, diríjase a [nuestro servidor de Discord](https://discord.gg/CetY6Y4)¡y díganos cómo le gustaría trabajar con nosotros!

public/content/translations/es/contributing/index.md:
  36: _¿Tiene alguna pregunta?_ 🤔 Póngase en contacto con nuestro [servidor de Discord](https://discord.gg/CetY6Y4)

  47: - Colgar un mensaje en nuestro [servidor de Discord](https://discord.gg/CetY6Y4)

  62: - [Servidor Discord](https://discord.gg/CetY6Y4)

public/content/translations/es/contributing/design-principles/index.md:
  93: Comparta su opinión sobre el [servidor de Discord](https://discord.gg/CetY6Y4) o [creando una incidencia](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=Type%3A+Feature&template=feature_request.md&title=).

public/content/translations/tr/community/online/index.md:
  28: <SocialListItem socialIcon="discord"><Link to="https://discord.gg/CetY6Y4">Ethereum.org web sitesi ekibi</Link> - uğrayın ve ethereum.org web geliştirme ve tasarımı ekibi ile ve topluluktan insanlarla sohbet edin</SocialListItem>

src/pages/contributing/translation-program/acknowledgements.tsx:
  286:             <InlineLink href="https://discord.gg/CetY6Y4">
```

Let us know if you need help with how to do this, thanks!

**Comment by wackerow** [comment]
Similar, if you could update from the old to the new channel name (in all non-English versions of that page as well) that would be great! Thanks again

**Comment by HemaDeviU** [comment]
Sure, I'll work on it!

**Comment by HemaDeviU** [comment]
Created a pull request here #12551 . Please review. @wackerow
