### ISSUE TITLE
Bug report: Links rendering incorrectly in bug bounty page

### ISSUE THREAD

**Issue by darigovresearch** [ethereum/ethereum-org-website#12599]
### Describe the bug

Two links in the in scope section are not rendering correctly

### To reproduce

1. Go to https://ethereum.org/en/bug-bounty/
2. Scroll down to 'In scope'
3. See error

### Expected behavior

Link to the relevant locations

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/30328618/f714a75a-45f1-49cf-9607-1a0ad3ddac7f)

### Desktop (please complete the following information)

Any device/browser

### Smartphone (please complete the following information)

Any device/browser

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by rileyannon** [comment]
I'm pretty sure this is an issue with React trying to prevent XSS attacks. This could probably be bypassed with [dangerouslySetInnerHTML](https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html).

**Comment by bhargavkakadiya** [comment]
@wackerow it's a small fix and open for a while now, can I submit a PR for this?

**Comment by wackerow** [comment]
@darigovresearch You were the original poster, and marked yes to wanting to work on this so I assigned you and would like to give you the chance to patch this.

It'd be nice to get this patched by the next deploy, so we still have til at least Tuesday... would you be able to do that? 

@bhargavkakadiya I'd ask you to hold for the moment, and @darigovresearch just let us know if you'd like to knock this out or let @bhargavkakadiya handle it. Can circle back on this in a couple days.

**Comment by darigovresearch** [comment]
@wackerow thanks for the guidance, have now put in a pull request (https://github.com/ethereum/ethereum-org-website/pull/12671)

Have checked that the netlify preview on the page no longer renders the links - https://deploy-preview-12671--ethereumorg.netlify.app/en/bug-bounty/#rules

When searching for `href` in the search bar of the netlify preview there still appears to show the bug bounty page with hrefs in the page. Assume this is because the index of the search is not based on the contents of the pull request but some other API index. Can you confirm?

Otherwise happy to raise an another issue and with some guidance and get this particular pull request merged for the next deployment on Tuesday.
