### ISSUE TITLE
GlossaryTooltip not working on mobile

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#12592]
### Describe the bug

When I try to use the GlossaryTooltip on mobile it is not popping up

### To reproduce

1. go to https://deploy-preview-12586--ethereumorg.netlify.app/en/nft/
2. Try to use the GlossaryTooltip on a term
3. See that its not popping up

### Expected behavior

The GlossaryTooltip should function on mobile

### Screenshots

https://github.com/ethereum/ethereum-org-website/assets/15589226/817c7311-a6b8-446a-be43-def6b8fe3dbd

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
This appears to be fixed with #12594
