### ISSUE TITLE
Bug report: outline on mobile glossary tooltip

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12597]
### Describe the bug

GlossaryTooltip component displaying an outline when used on mobile; not present on desktop

### To reproduce

0. Use a phone
1. Go to https://ethereum.org/en/nft
2. Click on dotted-underlined "blockchain" at the end of the second paragraph
3. Notice colored outline to the tooltip box

### Expected behavior

No outline; should appear same as on desktop

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/54227730/0b7df322-2835-43db-b20f-2d7b6734d687)

### Smartphone (please complete the following information)

iPhone, Brave or Safari

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by rileyannon** [comment]
Is this claimed yet?
I was taking a look through some of the docs and I found that this may be linked to ChakraUI as shown in this issue: https://github.com/chakra-ui/chakra-ui/issues/708

I'd like to take a stab at it - not yet sure how I could run this locally on mobile (I'm a n00b) but I'm interested!

**Comment by SeanXLChen** [comment]
Hi, I could take this one.
