### ISSUE TITLE
Exploring strategic partnership

### ISSUE THREAD

**Issue by Johnrichard111** [ethereum/ethereum-org-website#12591]
### Is your feature request related to a problem? Please describe.

Hello ETH group,

Our client contacted us and has reiterated his desire to get in touch with you.
As indicated the focus is on the fintech aspect, a profitable agreement for both parties.

Please do not underestimate the value of the investment desired by our client. This endeavor is intended for the long term and the additional value it could provide would be highly profitable.

We are very interested in setting up and developing a lasting partnership with Ethereum foundation. I would be delighted to furthering this exchange with the head of Business Development.

Looking forward to hear from you.

Best regards,
John

### Describe the solution you'd like

Get in touch with the head of business development.

### Describe alternatives you've considered

e-mail : j.richard@zogar-management.lu
t.me : Winter11j

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
This isnt related to the development of ethereum.org, so closed out.

**Comment by Johnrichard111** [comment]
Alright, sorry for the inconvenience. Are you able to redirect me to the BD team with an email please? Thank you.
