### ISSUE TITLE
Release blocking - Find wallet on Safari not working when clicking a wallet or more information

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#12590]
### Describe the bug

When I use the find wallet page on Safari, I go to get more information on a wallet and the site crashes. 

### To reproduce

1. Go to https://deploy-preview-12586--ethereumorg.netlify.app/en/wallets/find-wallet/ in Safari
2. Scroll down and click on Rainbow wallet
3. See the crash

https://github.com/ethereum/ethereum-org-website/assets/15589226/c1e50fd5-a32b-4c0b-a00e-f6a394a61240

### Expected behavior

I should be able to get more info on all wallets in Safari

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by wackerow** [comment]
Closed with #12593
