### ISSUE TITLE
Docs - Run a node - updating clients announcements subscription link problem

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#12627]
### Describe the bug

When I click to "subscribe to these announcements" it directs to a google group which seems to be unavailable. 

### To reproduce

1. Go to [Updating Clients](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#updating-clients)
2. Click on [subscribe to these announcements](https://groups.google.com/a/ethereum.org/g/announcements)
3. See error

### Expected behavior

Subscription to protocol announcements can be done [here (at the bottom of the page)](https://blog.ethereum.org/) I am not sure if it can be linked directly or just stating this could be enough, the announcements blog link is given previously. 

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks for surfacing @aslikaya! Yes, I would use this link:

https://blog.ethereum.org/category/protocol#subscribe

This will go to the protocol category, and directly to the subscribe widget.

**Comment by wackerow** [comment]
I see you checked yes for wanting to work on it so I went ahead and assigned you @aslikaya
