### ISSUE TITLE
Deprecate use of postMergeBannerTranslation

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12637]
## Issue
The "post merge banner" and logic/strings surrounding it are no longer needed.

Currently the `postMergeBannerTranslation` front matter property is only being used on one page (in all languages), `public/content/governance/index.md` (`/governance/` path). This file uses the `Static` layout, which does not actually handle this variable.

Meanwhile, we do handle it in the Tutorial layout, but no tutorials have this property anymore.

```[tasklist]
### Scope
- [ ] Remove all `postMergeBannerTranslation` properties from the front matter of the governance pages
- [ ] Remove logic surrounding use of `postMergeBannerTranslationString` in the `Tutorial.tsx` layout, and remove use of `PostMergeBanner` component
- [ ] Deprecate/remove `Banners/PostMergeBanner.tsx` component
- [ ] Remove the `"page-upgrades-post-merge-banner-governance-ood"` string from `page-upgrades.json` for all languages
```

**Comment by colmck** [comment]
I'd like to take this on if that's alright!

**Comment by wackerow** [comment]
Great, thanks @colmck, assigned you
