### ISSUE TITLE
Missing find wallet tracking: main CTA buttons, mobile filter tab open

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12642]
### Is your feature request related to a problem? Please describe.

There are two instances of missing tracking. 
1. Main button to visit wallet website is currently not being tracked resulting in the team not knowing how many people are being redirected to wallet providers.
2. Sticky "filters" link is not tracked

### Describe the solution you'd like

1. MAIN WALLET CTA 

Event Category:  WalletExternalLinkList

event action: Tap main button

event name: {wallet name}

![Screenshot 2024-04-03 at 20 06 09](https://github.com/ethereum/ethereum-org-website/assets/100724231/2449c43d-5556-4627-ae9b-3f509a3cb01a)

- historically we used to track the position in the list as well, do not implement that as it scattered data too much, include just wallet name 

3. STICKY FILTERS LINK (Mobile only)

Event Category:  MobileFilterToggle

event action: Tap MobileFilterToggle - sticky

event name: show mobile filters true

<img width="291" alt="Screenshot 2024-04-03 at 11 51 03" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/b320dce3-2ce4-417c-bf8e-ba18fed97236">

### Describe alternatives you've considered

NA

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by nhsz** [comment]
@wackerow PR https://github.com/ethereum/ethereum-org-website/pull/12713
