### ISSUE TITLE
Bug report: changing website language does not update order of wallets

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12640]
### Describe the bug

When i change language the list of wallets is supposed to reorder to start with the wallets supporting the language of the website.

eg if i switch to czech, czech wallets should be listed first

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on languages in the MENU
3. Switch website language to any other, for exmaple Czech (https://ethereum.org/cs/wallets/find-wallet/)
4. See error - list of wallets is not reordered
5. hard refresh
6. list of wallets after refresh is suddenly reordered

### Expected behavior

should reorder without the need of user to refresh

### Screenshots

<img width="1493" alt="Screenshot 2024-04-03 at 10 33 33" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/157b59b4-2038-4b63-8a19-d71f35a14641">
<img width="1494" alt="Screenshot 2024-04-03 at 10 33 49" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/f5dcda95-8765-4ed1-8606-7d0b5c07f8a6">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Dharmik79** [comment]
@konopkja I would like to work on this issue.

**Comment by konopkja** [comment]
Hello @Dharmik79  again! thank you very much and assigning you the issue. Pinging @wackerow for visibility and potential guidance.

**Comment by wackerow** [comment]
Sure, assigning you @Dharmik79 

I would suspect this has to do with how route changes are handled with Next.js... In this case, having a `useEffect` that triggers when `locale` changes may be enough to just force the filter state to update

**Comment by Dharmik79** [comment]
@konopkja I have tried to use useEffect and update the state, but I did not get the result, so I am trying new methods to complete the task.

**Comment by konopkja** [comment]
> @konopkja I have tried to use useEffect and update the state, but I did not get the result, so I am trying new methods to complete the task.

ok thank you for the update! :) let us know if you need help with this one! cc @wackerow  @pabloped

**Comment by Dharmik79** [comment]
@konopkja Pull request has been created.
