### ISSUE TITLE
Bug report: find wallet - clicking "Visit website" unintended behavior

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12644]
### Describe the bug

clicking on main "visit website" button in wallet listings unintentionally also opens wallet detail which triggers additional event and distorts our usage reports.

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on "visit website" of any wallet
3. wallet detail opens (should not)

### Expected behavior

wallet detail does not open, this is unintended behavior and is namely problematic because it also triggers "More info wallet" event which distorts the data.

In event reports it now looks that clicking on wallet detail is more popular than in reality it is because of this dynamic

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Dharmik79** [comment]
I would like to work in this issue

**Comment by konopkja** [comment]
Hi @Dharmik79, assigned you the issue. Thanks again!
