### ISSUE TITLE
Bug report: poor tooltip position - find wallet 

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12643]
### Describe the bug

in some instances the tooltip is too far from the text
<img width="1127" alt="Screenshot 2024-04-03 at 11 55 09" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/e96b7b04-279d-4912-bf7e-be0b8e7bdf57">

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on wallet detail

### Expected behavior

the tooltip should be right after the text without blank gap

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Dharmik79** [comment]
@konopkja I would like to work on this issue

**Comment by konopkja** [comment]
@Dharmik79  thank you so much for offering your help! I will assign you the task :) assigned you the issue. @pabloped since we had some issues handling this internally adding you here for review.

**Comment by wackerow** [comment]
I can't find my original comment at the moment, but yeah just noting this is a little tricky because when the text wraps from being too long, the browser doesn't collapse the container width to the now-wrapped text, it just fills the full width (which is what pushes that (i) all the way to the right edge when the text wraps)...

We could make this `display: inline;` with the text, but then the (i) would be like this:

```
Some really long example
name here (i)
```

...which is not what @konopkja is requesting here. Not sure the best way to keep the (i) right next to the text block when it's multiple lines tbh.

**Comment by konopkja** [comment]
Hello @Dharmik79 what is the status on this task?

**Comment by Dharmik79** [comment]
@konopkja The issue is with the css property, and using `display:inline` it does not fix the issue. We need to use another method for that.

**Comment by konopkja** [comment]
cc @pettinarip @wackerow

**Comment by pettinarip** [comment]
Hmm I don't have atm a better solution than the one @wackerow mentioned. I think moving the `(i)` icon inside the paragraph would make it follow the width of the text. Is not exactly what was requested but I think it will look good and consistent as well.

**Comment by Dharmik79** [comment]
@pettinarip @wackerow Can we remove the (i) icon and make the tooltip hover from the text itself?

**Comment by konopkja** [comment]
> @pettinarip @wackerow Can we remove the (i) icon and set the tooltip from the text itself?

its good idea to consider different solutions, this one though would probably not be good for mobile devices apart from also being less clear. Id advise against it.

**Comment by wackerow** [comment]
One approach that I mentioned elsewhere is slightly messier, but it seems to work:

Inside `src/components/FindWallet/WalletTable/WalletMoreInfoCategory.tsx`, before `if (feature.category === sectionName)` on line 61, insert:

```tsx
const lastWord = feature.label.split(" ").pop()
```

Then rearrange the tooltip below as follows:

```tsx
                <Text px={1} lineHeight={1}>
                  {feature.label}

                  <Text as="span" whiteSpace="nowrap">
                    {lastWord}
                    <Tooltip
                      content={
                        <Text color="body.base !important">
                          {t(walletFilterData[feature.filterKey].description)}
                        </Text>
                      }
                    >
                      <Box as="span" ms="2">
                        <Icon as={MdInfoOutline} color={featureColor} />
                      </Box>
                    </Tooltip>
                  </Text>
                </Text>
```

1. Pulls the Tooltip into the `feature.label` span, so it lays inline with the text
2. Adds a margin-start of half a rem (`ms="2"`) to icon box
3. Breaks off the last word and wraps it in a `nowrap` span with the icon, so the icon never lays on it's own line alone

Probably a cleaner way to do it, but this is the result:
ltr:
<img width="1136" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/0dc12d70-7574-4604-89b5-c9be60059912">

rtl:
<img width="1177" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/e01e2828-0ca2-4a43-a331-2c52fea7f858">

May need to just clean up the vertical alignment a little with the above, but it seems to be a solution to the posted problem.m

**Comment by Dharmik79** [comment]
@wackerow This solution looks pretty good, I will implement this and will create the pull request for the same.
