### ISSUE TITLE
Feature request: multiple personas clickable on list of wallets

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12645]
### Is your feature request related to a problem? Please describe.

With rising popularity of personas, during user testing several users requested having the option to select multiple personas to filter down list of wallets to a narrower list that tailors to their needs.

https://ethereum.org/en/wallets/find-wallet/

<img width="1466" alt="Screenshot 2024-04-03 at 12 03 04" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/7f816586-5aa3-4d09-93af-46953b008e3a">

### Describe the solution you'd like

Switch logic to "AND" and allow users to select multiple personas.

Change radio buttons to checkboxes in UI

### Describe alternatives you've considered

 NA

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by bhargavkakadiya** [comment]
I would like to contribute to this

**Comment by konopkja** [comment]
Hi @bhargavkakadiya, thank you for your interest in this task! I will assign it to you and pinging @pabloped and @nhsz to provide guidance on implementation if needed.

**Comment by konopkja** [comment]
Hi @bhargavkakadiya, are you still interested working on this issue?

**Comment by bhargavkakadiya** [comment]
@konopkja Yes I am interested
I have made progress with multi select UI,  please give me until this week to try fixing display of wallets based on the select options

**Comment by konopkja** [comment]
> @konopkja Yes I am interested I have made progress with multi select UI, please give me until this week to try fixing display of wallets based on the select options

Of course! Thank you for working on this! I was just curious about status update and seeing whether you need any help guidance to finish this. If so please let us know and we will gladly help :)

I think this might be a more complex feature that it seems on first sight.

**Comment by bhargavkakadiya** [comment]
@konopkja yes, it's a slightly tough given the filtering structure used right is supported for single select options
Thanks for offering the help, I can of course post questions here but I was wondering if you also discuss issues on discord?
