### ISSUE TITLE
Bug report: color accessibility with tags

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12647]
### Describe the bug

Some users have expressed difficulty reading tags on https://ethereum.org/en/wallets/find-wallet/ 

This is an issue both on light mode as well as dark mode. The problem is that color contrast between the tag background and tag text is too low. Even though it follows accessibility standards (>4.5) the perceived readability is low and we should increase the contrast ratio.

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. See error in wallet listing (tags)

![Screenshot 2024-04-03 at 12 13 44](https://github.com/ethereum/ethereum-org-website/assets/100724231/b0fe9e29-583a-420f-9f4d-8a54e57b1377)

![Screenshot 2024-04-03 at 12 13 40](https://github.com/ethereum/ethereum-org-website/assets/100724231/d6335bd3-d554-4ce6-ac34-793383b911fe)

### Expected behavior

increase contrast by changing background color or text color (or both)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Dharmik79** [comment]
@konopkja  I would like to work on this issue.

**Comment by nloureiro** [comment]
I've made changes on the Design system level to help here.
The problem is not the color contrast but the font weight. It is too light for that font size, which makes it hard to read on some screens with less resolution.

I propose to create a new design token just for tags that can fix this (I hope)
These are differences from the xs design token.
```
font-weight: 500;
line-height: 120%; /* 0.9rem */
text-transform: uppercase;
```
Let me know what you think.
![Screen Shot 2024-04-03 11 38 23 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/17765d28-0973-4dcf-985d-4883d3f98378)

**Comment by Dharmik79** [comment]
@nloureiro  I believe relying solely on font weight may not fully address the issue. Combining both font weight and the background color of the label could significantly enhance its clarity.
![image](https://github.com/ethereum/ethereum-org-website/assets/61613931/6bb2fa63-188b-45b7-ba1f-238164c5213d)

**Comment by nloureiro** [comment]
> @nloureiro I believe relying solely on font weight may not fully address the issue. Combining both font weight and the background color of the label could significantly enhance its clarity. ![image](https://private-user-images.githubusercontent.com/61613931/319475180-6bb2fa63-188b-45b7-ba1f-238164c5213d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTkzMDQsIm5iZiI6MTcxMjIxOTAwNCwicGF0aCI6Ii82MTYxMzkzMS8zMTk0NzUxODAtNmJiMmZhNjMtMTg4Yi00NWI3LWJhMWYtMjM4MTY0YzUyMTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA4MjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlY2U5Zjc1ODNmMDRiZDJmZTlmODRiZmE2NmVkMjljMzE1ZmFjYmU2OWU5MmY2MzliMWYzYWI4Y2VmNzg5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MsT3YpYnNYM5yHRIrnDw7fW8Gw5QyXF8pwSXieT4i6I)

Yes, and @konopkja further discussed this on Figma.

I will add a new tag variation called "highProfile" to address this and leave the "subtle" as is
in addition to this let's keep the new font style just for tags

Can you do all this in this issue? Meaning, change the tags components?

**Comment by Dharmik79** [comment]
@nloureiro For changing the tags component, do I need to change all the tags component or adding a new "highProfile" tag component only.

**Comment by nloureiro** [comment]
> @nloureiro For changing the tags component, do I need to change all the tags component or adding a new "highProfile" tag component only?

hey, can you hold on to this for a couple of days?
we are talking with @TylerAPfledderer to consider a better solution for this.

**Comment by minimalsm** [comment]
@nloureiro any update here?

**Comment by nloureiro** [comment]
yes, let's go with the High Contrast version.

![Screen Shot 2024-04-16 09 40 41 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/1290b157-bee0-4a5d-9673-a29045817aff)

@Dharmik79 can you please check the [Figma file](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=2460%3A45844&mode=design&t=bVsOm1Xg3xcsCfEK-1) and add the hight variation variation
