### ISSUE TITLE
Bug report: update the table styles based on design system /stablecoins page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#12648]
### Describe the bug

There is a text contrast issue on https://ethereum.org/en/stablecoins/ when using dark mode.

In a table on this page when user mouse overs a stablecoin in the table, the text becomes greyed out and hard to read.

### To reproduce

1. Go to https://ethereum.org/en/stablecoins/
2. Scroll down to "Top stablecoins by market capitalisation" section and see table
3. Use dark mode
4. Mouse over item in the table
5. See error

### Expected behavior

- on mouse over keep the text white instead of greyed out (only background changes)
- The problem is it is not following the DS because it inherited properties from the page that overrides the DS ones

Design system: https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=1961%3A33521&mode=design&t=cm7YrGNCoOVawgRV-1

### Screenshots

<img width="1474" alt="Screenshot 2024-04-03 at 12 43 13" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/c9493a0e-9e90-487b-879f-d477d6e97167">

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by iepn** [comment]
@konopkja  I would like to work on this issue.

**Comment by konopkja** [comment]
> @konopkja I would like to work on this issue.

awesome! i am assigning you the issue. Pinging @nloureiro  for visibility as DS owner

**Comment by iepn** [comment]
> > @konopkja I would like to work on this issue.
> 
> awesome, thank you! i am assigning you the issue. Pinging @nloureiro for visibility as DS owner

Thank you, and wish you a wonderful day!

#12666

**Comment by iepn** [comment]
@konopkja Hello, I think this PR can be closed now since it's already merged. https://github.com/ethereum/ethereum-org-website/pull/12666
