### ISSUE TITLE
Add MEV diagrams to the diagrams page

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#12691]
The content is hard to understand, and by adding diagrams to this page will help understand 

https://ethereum.org/en/developers/docs/mev/

**Comment by sogobanwo** [comment]
@nloureiro i would love to work on this

**Comment by nloureiro** [comment]
> @nloureiro i would love to work on this

Awesome. Any ideas for the diagram?

**Comment by sogobanwo** [comment]
Yes, I am looking to add 2 diagrams.
i. one that shows what MEV is after the definition
ii. another that visualizes the example of arbitrage  (how flashloan of 1000ETH was collected on AAVE and used to get 1045ETH.)

**Comment by sogobanwo** [comment]
![Screenshot from 2024-04-24 00-30-49](https://github.com/ethereum/ethereum-org-website/assets/99739569/c19c5432-c1b0-4e68-b464-122978c91814)
This is the proposed diagram I intend to upload on the page to explain the order of transactions due to gas fees by validators in order to get the max value from a block.

**Comment by nloureiro** [comment]
ok, thank you! That is a great starting point.
 I wanted to have more eyes on this base diagram to be sure that we ar not forgetting anything.
 @wackerow @corwintines can you help here?
 
 @sogobanwo Another thing, how are your Figma skills? Are you okay with doing the diagrams using your style guide?
 https://www.figma.com/file/Hj8Hnc6TYBs8GDxfdcCtqW/Diagrams-and-schematics?type=design&node-id=122%3A27&mode=design&t=QMcbsYJvpmuUYojp-1
 
 If not, it's okay; no worries. We can have another contributor just to do the final design; you are already helping a lot.

**Comment by sogobanwo** [comment]
Hi @nloureiro i'm not too good with figma but with the style guide i should be able to draw  the diagram with figma.

**Comment by aslikaya** [comment]
Hi! Yes @sogobanwo  the specific example with a diagram would be nice to see too. For just the MEV part, I am not sure if ordering according to gas fees explains it correctly, MEV is pretty complex. 

The part that was confusing to me was many actors involved in the process of mev-boost (users, searchers, builders, relays, validators) and each responsible for different things. I checked a few other resources, and see some diagrams about it from Flashbots website. Here they are:

<img width="869" alt="Screenshot 2024-04-25 at 13 06 06" src="https://github.com/ethereum/ethereum-org-website/assets/9151261/cadcca30-3836-4344-94e2-dacf44ba6cbd">


<img width="1068" alt="Screenshot 2024-04-25 at 13 09 35" src="https://github.com/ethereum/ethereum-org-website/assets/9151261/d9646da2-40f5-47e5-a878-8f83cd4b5b81">

![block-proposal](https://github.com/ethereum/ethereum-org-website/assets/9151261/e6d480e5-3d23-4a5a-90ae-cf00b36d7928)

I did one too, but I kind of combined the first two and some readings I guess. They got densed. I used google drawings, I don't have design experience. 
![mev-boost](https://github.com/ethereum/ethereum-org-website/assets/9151261/b6028146-2d20-4856-9166-bce5f6f6e71f)

The relationship between relay, mev-boost and validator could be another diagram

**Comment by wackerow** [comment]
Thank you @sogobanwo and @aslikaya, appreciate these contributions... I do tend to agree that the first drawing seems to overly simplify MEV. Simply ordering txs by highest fee is pretty standard, and I suppose could be a form of MEV, but as the other diagrams demonstrate, MEV can get quick complex. 

Seeing as these changes are targeting the dev docs, I would probably lean towards the more complex explanations, though maybe there's room for both. At a glance these all look pretty decent but will have to come back to look through them in more depth.

**Comment by nloureiro** [comment]
> Hi @nloureiro i'm not too good with figma but with the style guide i should be able to draw the diagram with figma.

ok. no worries if you don't it on Figma, we can open an issue for someone else to do it.  All good

**Comment by nloureiro** [comment]
@aslikaya @wackerow, would something like this make sense? maybe too many images to this page
![Screen Shot 2024-04-30 03 35 07 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/4fc0c40d-88c5-49b7-8f17-a7faa7a8bce8)

I'm trying to understand how to push this forward.

did on this Figma to be easy to have an overview of the page, please add comments there if it is easy 
https://www.figma.com/file/ZEhZXwNPF6t5MrVKBpvyYt/MEV-diagrams?type=design&node-id=0%3A1&mode=design&t=DTJtEuo9Wg3ug0bL-1

**Comment by aslikaya** [comment]
Btw these two resources helped me understand mevboost:
1- [Talk by Alex Stokes](https://www.youtube.com/watch?v=PS9SlHGJlrU ) (then I realized a more recent, longer version exist: https://youtu.be/-xY1EEzcp0s)
2- [Architectural overview on block proposal](https://docs.flashbots.net/flashbots-mev-boost/architecture-overview/block-proposal)

**Comment by nloureiro** [comment]
> Btw these two resources helped me understand mevboost: 1- [Talk by Alex Stokes](https://www.youtube.com/watch?v=PS9SlHGJlrU) (then I realized a more recent, longer version exist: https://youtu.be/-xY1EEzcp0s) 2- [Architectural overview on block proposal](https://docs.flashbots.net/flashbots-mev-boost/architecture-overview/block-proposal)

I only have a high level of knowledge of MEV; I feel a bit out when discussing this level of detail.
Let's try to get a proposal out and then get more eyes on it to validate it.

thank you for your help!

**Comment by aslikaya** [comment]
As I mentioned, here is another diagram to explain the relationship between validator-mevboost-relays-builders in more detail

![validator-mevboost-relays](https://github.com/ethereum/ethereum-org-website/assets/9151261/b6b78be8-6413-41aa-baff-49ed02cfd42e)

this page helped: [Architectural overview on block proposal](https://docs.flashbots.net/flashbots-mev-boost/architecture-overview/block-proposal)

I skipped the validator registration part here and focused on the more complicated part: when a validator is selected to propose a block

**Comment by LauraSinisterra** [comment]
Hi @nloureiro, would love to help designing the diagrams on Figma.

**Comment by nloureiro** [comment]
> Hi @nloureiro, would love to help designing the diagrams on Figma.

Hi. Great!

At this point I'm working with @aslikaya and @wackerow on the main one

you can follow here https://www.figma.com/design/ZEhZXwNPF6t5MrVKBpvyYt/MEV-diagrams?node-id=254%3A594&t=vrIuMBRfrrt8W9Zh-1
this is where we are... almost ready for the data to finish the design 
![Screen Shot 2024-05-24 01 11 25 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/31dddcc5-93cb-4a29-a59b-ea2f5f00abb2)



But I was wondering if we should have a simpler one at the top of the page based on @sogobanwo's proposal.

@aslikaya what do you think? Do we need a simplified version on the top of the page? (if yes, for sure... @LauraSinisterra, you can help... Thank you for reaching out)
![Screen Shot 2024-05-24 01 13 49 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/b9a7246e-5f81-49e5-b802-dd4b8eac8bdf)

**Comment by aslikaya** [comment]
I think it could be nice to show other parts of the process like searchers and public-private mempools without going into much detail, like an overview. The one we are working on now is pretty detailed. Maybe under MEV Extraction - where searchers are mentioned, yet mev-boost, builders and relays are not mentioned there, only towards the bottom of the page

**Comment by almesh** [comment]
https://t.me/+i7MQ2LQujC0wM2U0

**Comment by corwintines** [comment]
Just wanted to check in on an update here. @nloureiro seems like we were pretty close with designs in the figma, are we ready to create a PR with those?

**Comment by nloureiro** [comment]
> Just wanted to check in on an update here. @nloureiro seems like we were pretty close with designs in the figma, are we ready to create a PR with those?

Almost!!! it's on me to finish the diagram design and open the PR

**Comment by LauraSinisterra** [comment]
Hi @nloureiro ! Happy to help polishing the diagram design, I'm already working on a version using the current figma file.

**Comment by nloureiro** [comment]
> Hi @nloureiro ! Happy to help polishing the diagram design, I'm already working on a version using the current figma file.

hey, awesome. I can´t let you edit this Figma file, but can you duplicate and edit on your side?

https://www.figma.com/design/ZEhZXwNPF6t5MrVKBpvyYt/MEV-diagrams?node-id=287-32&t=KMwokFIM7RS888KO-1


I've also created this guides to help follow the style. not a hard set of rules, we can bend them a little bit but I think we souls follow a similar style.
 https://www.figma.com/design/Hj8Hnc6TYBs8GDxfdcCtqW/Diagrams-and-schematics?node-id=603-3&t=v1gWYEzpe4vcJ5Zn-1
 
 
 Thank you for reaching out!

**Comment by LauraSinisterra** [comment]
Perfect! Thanks, I'll make sure to follow the style.

**Comment by nloureiro** [comment]
> Perfect! Thanks, I'll make sure to follow the style.

Let me know if you have any questions. Thank you!

**Comment by corwintines** [comment]
Thanks @LauraSinisterra! Assigned this to you for now while you work on the diagram :)

**Comment by LauraSinisterra** [comment]
Hey @nloureiro @corwintines ! Here's a first draft for the diagram. I'm using some shapes/color/spacing from the diagrams and schematics Figma file, and took some liberties with the circle shapes and the end of the arrows. 

Let me know what you think, happy to make any adjustments in size/color/anything else.

![image](https://github.com/ethereum/ethereum-org-website/assets/66342887/f5e3697d-ec18-49c8-9e24-4a5c6912218d)

**Comment by nloureiro** [comment]
> Hey @nloureiro @corwintines ! Here's a first draft for the diagram. I'm using some shapes/color/spacing from the diagrams and schematics Figma file, and took some liberties with the circle shapes and the end of the arrows.
> 
> Let me know what you think, happy to make any adjustments in size/color/anything else.
> 
> ![image](https://private-user-images.githubusercontent.com/66342887/347043231-f5e3697d-ec18-49c8-9e24-4a5c6912218d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTQ0NjcsIm5iZiI6MTcyMzE5NDE2NywicGF0aCI6Ii82NjM0Mjg4Ny8zNDcwNDMyMzEtZjVlMzY5N2QtZWMxOC00OWM4LTllMjQtNGE1YzY5MTIyMThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA5MDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYTZkNDc3Yzg1NzU3MjVmZGM0NGE4NmZiY2RlMTM3NzlkYTlhNGE4ODZhOGMwZjFjYTQ1ZmMwNWFjMmY1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2mVGYnqtq6GWiw1j2O21lslFWGtOaVi9ru4rtSWA0LE)

Oh, I missed this! I'm so... sorry @LauraSinisterra 

Look awesome! Thank you so much

Can you export a transparent version to test it on the browser? We use the same image on light and dark themes, and that's the biggest challenge with these diagrams, which is why I usually use stronger colors. The visual impact is kinda the same on both themes. But I want to try as is now.

**Comment by nloureiro** [comment]
@LauraSinisterra Thank you!

This brings me back to our discussion of using the same PNG to have a similar visual impact on both themes.

You've made some improvents on the arrows and ither details that I realt like and makes me wonder if we should change this to be the new diagram system 😅

this is what I have onde last year
![Screen Shot 2024-08-14 12 30 48 AM](https://github.com/user-attachments/assets/2c68be25-d3eb-4a27-8e71-ec9e249b1f1c)
(https://www.figma.com/design/Hj8Hnc6TYBs8GDxfdcCtqW/Diagrams-and-schematics?node-id=603-3&t=iDdC6cZnN9v91oYx-1)





Meanwhile, we have a few comments on Figma about the content. Would you like to check them out?
https://www.figma.com/design/ZEhZXwNPF6t5MrVKBpvyYt?node-id=395-40#906251495

**Comment by LauraSinisterra** [comment]
Glad you like it! Happy to contribute to the new diagram system if you decide you want it.

Just checked the comments, here's the updated version. 
![MEV_diagram](https://github.com/user-attachments/assets/d998f990-90b0-45e0-bcd4-77cb2b6a0729)

**Comment by nloureiro** [comment]
> Glad you like it! Happy to contribute to the new diagram system if you decide you want it. @nloureiro
> 
> Just checked the comments, here's the updated version. ![MEV_diagram](https://private-user-images.githubusercontent.com/66342887/360523040-d998f990-90b0-45e0-bcd4-77cb2b6a0729.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjA4NzYsIm5iZiI6MTcyNDM2MDU3NiwicGF0aCI6Ii82NjM0Mjg4Ny8zNjA1MjMwNDAtZDk5OGY5OTAtOTBiMC00NWUwLWJjZDQtNzdjYjJiNmEwNzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIxMDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNjM3ZTY4ZDgxZmQwMWVkOGU5ZDEzODQyNGNiZDZkMzk2MzZjNzFkZDdjZjE4NTIxMGQ3OGM5NGI2ZGNmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.flpK4vUWKTWCRzsUHaKklZ6Wy9WwM0Bdm5XZHl05_8c)

Thank you! Great work!

It has been added to Figma for a quick review. Then, we can move on to the code phase and open a PR with it.
https://www.figma.com/design/ZEhZXwNPF6t5MrVKBpvyYt/MEV-diagrams?node-id=426-41&t=9LvQSQU9YUviL8Pz-1

**Comment by wackerow** [comment]
Thanks for the help @LauraSinisterra! Going to close this issue out now that the new diagram has been merged. 

As our theming has been updated there will certainly be more that needs to be done in the future to update and iterate on our diagrams if you have any interest! Let us know and can be in touch, cc: @nloureiro

**Comment by nloureiro** [comment]
> Great! Yes, I'm interested in continue collaborating on this, in particular would love to work on the diagram systems or any other diagram iterations. Let me know! @nloureiro @wackerow

Oh, that would be great!!!

Do you think we can improve the diagrams that we have now? Or create new ones?

**Comment by LauraSinisterra** [comment]
We can improve on the existing diagrams but if there is a new theme maybe this is a good opportunity to create a new diagram system.

**Comment by nloureiro** [comment]
> We can improve on the existing diagrams but if there is a new theme maybe this is a good opportunity to create a new diagram system.

I agree that we should update the diagram system.
Would you be up to it? It's quite a lot of work.

**Comment by LauraSinisterra** [comment]
Yes, it is a lot of work. I'm up for it as long as there isn't a set deadline, I can work bit by bit.

**Comment by nloureiro** [comment]
> Yes, it is a lot of work. I'm up for it as long as there isn't a set deadline, I can work bit by bit.

for sure, I think we can work with that and I can help too.
how do see us moving forward?

**Comment by LauraSinisterra** [comment]
It would be great to have a closer collaboration for this, what are you thinking?

**Comment by nloureiro** [comment]
> It would be great to have a closer collaboration for this, what are you thinking?

I will open a new issue on github to track the task and create a new Figma file that we can both edit.

Form there, I will let you lead the file at your own pace. How does it sound?

**Comment by LauraSinisterra** [comment]
Sure! Sounds great.

**Comment by nloureiro** [comment]
> Sure! Sounds great.

Let's go!!! 
https://github.com/ethereum/ethereum-org-website/issues/14154

let me know on the issue if this makes sense or you have any other ideas
