### ISSUE TITLE
Remove Gitcoin bounties from get involved page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#12725]
## Description

Our get involved page suggests working on a bounty on Gitcoin as an option for getting involved in Ethereum.

As far as I know, the Gitcoin bounty program has been discontinued. We should either remove or replace this if there is a suitable alternative.

**Comment by cairoeth** [comment]
[gitcoin.co/issue](https://gitcoin.co/issue) and [gitcoin.co/hackathon](https://gitcoin.co/hackathon) now redirect to [buidlbox](https://app.buidlbox.io/). if this is a suitable alternative, happy to open a PR

**Comment by minimalsm** [comment]
@cairoeth I don't think that's suitable. Buidlbox is a platform for hackathons, and I don't think it really has the concept of bounties.

**Comment by JeffreyJoel** [comment]
Hi @minimalsm can I work on this

**Comment by minimalsm** [comment]
Hey @JeffreyJoel, thanks for offering to help. I've assigned you! :) 

cc: @isabelladebrito i know you were looking at this page

**Comment by JeffreyJoel** [comment]
can open a PR adding `https://learnweb3.io/bounties` instead?

**Comment by minimalsm** [comment]
> can open a PR redirecting to `https://learnweb3.io/bounties` instead?

@JeffreyJoel I don't feel great about that... the learnweb3.io bounties' board doesn't look to be very well maintained. lots of the open bounties are over six months old and expired (based on the date for submission) but are still showing as open to be worked on [(example)](https://learnweb3.io/bounties/use-account-abstraction-to-make-ethereum-quantum-proof/).

**Comment by JeffreyJoel** [comment]
@minimalsm Okay, I'll remove all instances of the gitcoin bounty

**Comment by wackerow** [comment]
Closed with #12745
