### ISSUE TITLE
Update content (add year + call-out) on Translatathon page

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#12756]
## Context
ethereum.org organised a Translatathon (https://ethereum.org/en/contributing/translation-program/translatathon/) in 2023, however, the event timeline doesn't mention the year it took place, which can be misleading given the `Page last updated:` information at the top of the page.

### 1. Add `2023` next to event dates, e.g.

> Application period: August 1st - August 15th, 2023
Translation period: August 16th - August 23rd, 2023
Evaluation & QA period: August 23rd - August 30th, 2023
Results announcement: August 31st, 2023

> The application period will be open from August 1st to August 15th, 2023

### 2. Add a callout in the page mentioned this event have passed
 
a. Example of call-out design:
<img width="530" alt="Screenshot 2024-04-17 at 14 40 07" src="https://github.com/ethereum/ethereum-org-website/assets/119775909/3899f74b-16cc-4a16-b472-18ce694532ef">

(you can find similar call-outs [here](https://ethereum.org/en/eth/) and [here](https://ethereum.org/en/staking/solo/))

b. Text to be added
`This event has passed. Stay tuned for the next events [here](https://twitter.com/ethdotorg). `

c. Note: Make sure to replace the 🎉  emoji to 🗓️  in the call-out

**Comment by tomasgrusz** [comment]
Happy to work on this issue.

**Comment by isabelladebrito** [comment]
@tomasgrusz assigned to you! let me know if you have any questions 😃

**Comment by MartiPresa** [comment]
Can i work on this issue? Thankss

**Comment by kaksv** [comment]
Is this issue worked on fully?

**Comment by wackerow** [comment]
All completed... we'll try to find another one for you @MartiPresa and @kaksv! Thanks for expressing interest

**Comment by kaksv** [comment]
You are most welcome

**Comment by MartiPresa** [comment]
You are welcome!
