### ISSUE TITLE
Adding references to exchanges for the UAE

### ISSUE THREAD

**Issue by RockmanR** [ethereum/ethereum-org-website#1283]
**Is your feature request related to a problem? Please describe.**
No. its just adding an information.

Adding exchange references under "[Where to buy ETH?](https://ethereum.org/en/get-eth/#country-picker)", 

**Describe the solution you'd like**
Could you please add the following exchanges that are available for the United Arab Emirates: [BitOasis](https://bitoasis.net/) & [Rain](https://www.rain.bh/)
They are reputed places and safe to deal with. 

**Describe alternatives you've considered**
N/A

**Additional context**

if you need anymore information. please let me know.

**Comment by developerfred** [comment]
@RockmanR Can these exchanges be used in the United States?

**Comment by RockmanR** [comment]
I'm not sure, but I don't think so.

**Comment by developerfred** [comment]
ok @RockmanR, Thanks!

**Comment by ryancreatescopy** [comment]
Hi there @RockmanR we'll need a bit of time to refine our policy for listing exchanges. We just want to let you know we've seen this and it's on our radar to discuss and decide very soon! Thanks for suggesting.

**Comment by RockmanR** [comment]
Good to hear that there is/will be due diligence for listing an exchange. Thanks for the update.

**Comment by ryancreatescopy** [comment]
For us to list any exchange, we need the following information. Please supply and we'll be able to consider your suggestion:

```
**What geographical restrictions apply to this exchange?** 

<!-- If you don't know, please get in touch with the exchange. They'll likey have a list of restricted countries and jurisdictions. -->

**Which currencies are accepted by this exchange?**

<!-- If you don't know, please get in touch with the exchange. They'll likey have a list of accepted currencies -->

**Do you have any proof that they're a legitimate company**

<!-- This is a safeguard against listing any malicious sites. You could provide a link to an "About" page from the exchange that provides more information about their legal entity, or a link to an official company registration -->

**Do you have any extra information?**

<!-- Add any more info that may make a stronger case for listing this exchange. Consider years of operation, size of company, financial backing etc. -->
```

**Comment by RockmanR** [comment]
I've sent an email the the exchanges. If they are interested, then they'll reply back to me or to this open issue directly.

**Comment by champbronc2** [comment]
@RockmanR we'd be interested here at https://rain.bh

**What geographical restrictions apply to this exchange?** 

Rain currently serves the MENA region, specifically the GCC.

For more information please visit the link below:
https://support.rain.bh/en/articles/2301225-list-of-supported-countries


**Which currencies are accepted by this exchange?**

Rain supports the following fiat currencies: 
Saudi Riyal (SAR)
Bahraini Dinar (BHD)
Emirati Dirham (AED)
Kuwaiti Dinar (KWD)
Omani Rial (OMR)
US Dollar (USD)
EUR (coming in 2021)

As for the cryptocurrencies offered, we currently support four main cryptocurrencies: 
bitcoin (BTC)
ethereum (ETH)
litecoin (LTC) 
ripple (XRP) 

For more information please visit the link below: 
https://support.rain.bh/en/articles/1782632-rain-currency-pairs-list

**Do you have any proof that they're a legitimate company**

Rain has acquired the Crypto-Asset Module (CRA) license from the Central Bank of Bahrain (CBB). This permits us to serve customers for the purpose of buying, selling, and storing Crypto-Assets in a safe and supervised way, while applying the highest standards of security online and offline.

For more information please visit the link below:
https://support.rain.bh/en/articles/3332099-rain-s-regulatory-license


**Do you have any extra information?**

Rain is a cryptocurrency trading platform in the Middle East, headquartered in Manama, Kingdom of Bahrain. Founded in 2016 by four entrepreneurs Yehia Badawy, Abdullah Almoaiqel, AJ Nelson and Joseph Dallago, Rain enables users to buy, sell and store Bitcoin, Ethereum, Litecoin, and Ripple. 

Rain also has raised funds from notable investors, including Bitmex https://www.coindesk.com/what-its-really-like-to-live-on-bitcoin-in-the-middle-east

Customers can open a personal account or an institutional account by using the website or mobile application that is compatible with iOS and Android. 

For more information about Rain please visit the website:
https://www.rain.bh/en

**Comment by samajammin** [comment]
Thanks for info @champbronc2! @ryancreatescopy please review when able.

**Comment by ryancreatescopy** [comment]
@GeorgeTrotter one to add to the list, if you haven't seen it already!
