### ISSUE TITLE
Unnecessary backslash

### ISSUE THREAD

**Issue by Amit0617** [ethereum/ethereum-org-website#12838]
### Describe the bug

![2024-04-25-22-59-50](https://github.com/ethereum/ethereum-org-website/assets/71893015/5f8832fd-0be0-4c7c-bf56-964dca218c18)
 It took me a few seconds to digest what exactly that was, and then I realised they are just backslashes, which make it appear horrendous.

### To reproduce

1. Go to '[Unformatted data](https://ethereum.org/en/developers/docs/apis/json-rpc/#unformatted-data-encoding)'
2. See backslashes before zeros.

### Expected behavior

0x004200 (size 3, "0B0")

### Additional context

I was thinking of creating PR directly but doubted if it is intentional by any chance.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Nice catch, yeah I suppose that should render as `"0A0"`? Assigned you; PR welcome =)

**Comment by Amit0617** [comment]
No it should be "0B0". It's 42 in hex.
