### ISSUE TITLE
Suggest a tutorial Dspyt- into CodeVerse

### ISSUE THREAD

**Issue by BadmWe** [ethereum/ethereum-org-website#12855]
### Tutorial title

Exploring Ethereum Network: A Guide to Etherscan, Ethplorer, and BlockScout

### Tutorial description

Learn how to explore the Ethereum network using popular tools like Etherscan and BlockScout. By following this tutorial, you'll understand how to
- Navigate and search for contracts using Etherscan and BlockScout.
- Retrieve detailed information about contracts, including code, transactions, and analytics.
- Interact with Etherscan and BlockScout APIs using JavaScript and TypeScript.
- Analyze Ethereum network performance and contract behavior using advanced analytics features provided by these tools.

### Tutorial tags

JAVASCRIPT, SMART CONTRACTS, BLOCK EXPLORER, ETHERS.JS, WEB3.JS

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://dspyt.com/exploring-ethereum

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @BadmWe!

After reading this, I am not sure this is the most helpful tutorial for someone looking at exploring contract information. The content here only goes into an API call for each block explorer, and doesn't expand past that for anything useful. There isn't even an example of the response object being explained. For now I am going to reject this, but if you do an edit to expand on this content into something you can do with the API calls for a contract feel free to resubmit.
