### ISSUE TITLE
Add Modular Crypto as an educational resource in Brazilian Portuguese

### ISSUE THREAD

**Issue by ModularCrypto** [ethereum/ethereum-org-website#12894]
Hey, we would like to be included as an educational resource in Portuguese. We are a organization that creates content, educational material and brings information about Ethereum and web3 as a whole to Portuguese speakers.

We have a weekly newsletter, daily news roundup, weekly Ethereum podcast ("The State of Ethereum") and much more, check it out our website for more information: https://modularcrypto.xyz/

**Comment by corwintines** [comment]
Closing with the above PR
