### ISSUE TITLE
Add Epirus Platform to relevant parts of the docs

### ISSUE THREAD

**Issue by conor10** [ethereum/ethereum-org-website#1294]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

To see the Epirus Platform listed in the developer tool and enterprise sections of the docs.

**Describe alternatives you've considered**

N/A

**Additional context**

Epirus is our platform that builds on top of Web3j simplifying the developer experience for users developing on the JVM and Android platforms.

**Comment by samajammin** [comment]
Solved in #1295
