### ISSUE TITLE
Update Wallet Listing Information - Ambire Wallet

### ISSUE THREAD

**Issue by steboi** [ethereum/ethereum-org-website#12946]
### Is your feature request related to a problem? Please describe.

Ambire Wallet's listing on the [Find Wallet](https://ethereum.org/en/wallets/find-wallet/) needs updating. The information is not accurate, and one of the links is broken. 

### Describe the solution you'd like

The **Discord** link should be https://discord.com/invite/ambire. _[Source](https://www.ambire.com/)_

The Feature list should include **ENS support**. [_Source_](https://blog.ambire.com/make-the-most-out-of-ambire-wallet/)

**Sell for fiat** should be marked as available. The wallet has built-in on/off-ramps. _[Source](https://help.ambire.com/hc/en-us/articles/4410238661522-What-deposit-methods-and-off-ramp-options-are-available)_

### Describe alternatives you've considered

N/A

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by aryankeluskar** [comment]
Hey! I have made the changes as required and opening a PR shortly.
