### ISSUE TITLE
Bug report - overlapping elements

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#12965]
### Describe the bug

The LanguagePicker component has a keyboard shortcut `[\]` available, which is noted inside the text input to filter languages once the menu is open. In left-to-right (LTR) languages this works well, but with right-to-left (RTL) languages (`fa`, `he`, `ar`, `ur`) this keyboard shortcut indicator is not adjusting to the left side of the input, causing it to overlap with the placeholder/input text.

### To reproduce

1. Go to https://ethereum.org/he/
2. Click on HE (language menu top left) 
<img width="153" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/fa31af6d-4f81-43fb-8680-1ccbeb8d249d">
3. See overlapping elements

### Expected behavior

Keyboard shortcut indicator `[\]` should be on the left for RTL languages, and should also not overlap the clearing X once user starts typing.

### Screenshots

<img width="612" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/0037659c-6f82-4ad1-9573-a495079ff842">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MukulKolpe** [comment]
Hey @wackerow, can I work on this one?

**Comment by MartiPresa** [comment]
Hi, is this issue still available?

**Comment by wackerow** [comment]
Thanks @MukulKolpe! Went ahead and assigned you
