### ISSUE TITLE
change Ethereum Uruguay dates

### ISSUE THREAD

**Issue by dariogitcoin** [ethereum/ethereum-org-website#12963]
### Event/Meetup Name

Ethereum Uruguay

### Website

ethereumuruguay.org

### Location (City/Country, or Remote)

Montevideo, Uruguay

### Description

Building together for a decentralized future.

### Start date: (yyyy-mm-dd)

2024-08-15

### End date: (yyyy-mm-dd)

2024-08-17

### Would you like to work on this issue?

- [ ] Yes

**Comment by wackerow** [comment]
Hey @dariogitcoin! Checked out ethereumuruguay.org and I didn't see any dates here... Is there a site that shows these dates or how users could attend?

**Comment by dariogitcoin** [comment]
Hey Paul, thank you so much for checking this out. This is our announcement
in Twitter https://x.com/EthereumUruguay/status/1798456022086136009, this
is the registration to the hackathon
https://taikai.network/en/ethuruguay/hackathons/buildathon-2024/projects
and we will update our website soon with the info to get the tickets.

If you need any further info please let me know. Thank you! Dario.

**Comment by corwintines** [comment]
Thanks @dariogitcoin 

I see the website looks like its been updated with more event information and can probably be added now. Is this something you would like to work on?

**Comment by dariogitcoin** [comment]
Thank you very much Corwin, Im sorry I was checking this today and
accidentally unassigned me.

It would be great if the info can be added, as we are approaching the event
and we already have the registration links and tickets.

How should we proceed?

Thank you!
