### ISSUE TITLE
Replace "add a community event" URL .ts on /community/events/

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#12961]
### Describe the bug

Replace community URL mentioned on [/community/events](https://ethereum.org/en/community/events/).

### To reproduce

1. On [/community/events](https://ethereum.org/en/community/events/), at the end of the "Upcoming events" section, you can read: 
`This is a non-exhaustive list maintained by our community. Know of an upcoming Ethereum event to add to this list? [Please add it](https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.ts)!`

2. "Please add it" is an hyperlink leading to a 404 page: https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.ts

3. This URL should be replaced to https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.json

### Expected behavior

Community events URL: https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.json

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MukulKolpe** [comment]
Hey @isabelladebrito, can I work on this issue?

**Comment by wackerow** [comment]
@MukulKolpe Thanks! Sure can... assigned you
