### ISSUE TITLE
ShapeShift Mobile

### ISSUE THREAD

**Issue by firebomb1** [ethereum/ethereum-org-website#12964]
### Wallet name

ShapeShift

### What type of wallet?

EOA

### Wallet description

Trade, track, buy, and earn with your favorite crypto assets with ShapeShift’s community-owned, private, non-custodial, and multichain platform. Enables cross-chain trades between Ethereum, Bitcoin, Dogecoin, Litecoin and many more.

### Wallet logo

![shapeshift](https://github.com/ethereum/ethereum-org-website/assets/88804546/f20c06e5-d381-42e1-bea2-b1e7077e8fce)

### Background color for brand logo

#386FF9

### URL to the project

https://shapeshift.com/

### When did the wallet go live to users?

2020-07-01

### What are the fees users may be paying for using your wallet product?

Wallet send/receive: Free outside of network fees
Trading/Bridging: Free for transactions under $1000 (outside of DEX provider/network fees). 48bps fee (0.48%) for trades/bridging above $1000, can be reduced by owning ShapeShift FOX tokens (down to free service based on holdings).

### Does the wallet have an active development team?

https://github.com/shapeshift/hdwallet (Wallet Abstraction) https://github.com/shapeshift/web (UI)

### Is the wallet globally accessible?

No KYC, except for on/off fiat ramp services.

### Is the wallet available in multiple languages?

Yes. English, Spanish, Portuguese, French, German, Japanese, Chinese, Turkish, Ukrainian and Russian

### What social links are there for the project?

Twitter: https://twitter.com/shapeshift
Discord: https://discord.gg/shapeshift
Telegram: https://t.me/shapeshiftofficial

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes.
iOS: https://apps.apple.com/us/app/shapeshift-crypto-platform/id996569075
Android: https://play.google.com/store/apps/details?id=com.shapeshift.droid_shapeshift&hl=en_US&gl=US

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No.

It is accessible through Web browser, but the on-boarding experience specifically for Web does not give enough focus on the ShapeShift wallet (as it is possible to connect with different wallets too in a Web browser) and this lead to the wallet getting de-listed earlier this year. This suggestion though is for a listing as a Mobile app only, the mobile experience is focused on ShapeShift wallet only, after discussing with "asbe" on Discord they suggested to make the suggestion this way after a short/informal review of the mobile app.

### Is it a hardware wallet?

No.

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

MIT license

### Who holds the private keys?

Users hold their private keys. Fully non-custodial wallet.
If the ShapeShift DAO disappears, the user can use their private keys (seed) to restore their wallet in any wallet supporting BIP39 seeds. The derivation path is standard/available in the open-source code.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Audit by DeFiSafety https://www.defisafety.com/app/pqrs/108
Responsible Disclosure Program: https://hackenproof.com/shape-shift/shapeshift

### Has the wallet's smart contract code or security modules been audited?

https://www.defisafety.com/app/pqrs/108

### Does the wallet have an internal security team?

Engineering Workstream of the ShapeShift DAO

### Any other security testing that should be noted?

No.

### Scam protection?

No. It includes filters for scam NFTs.

### Does the wallet support connecting to Ethereum applications?

Yes through WalletConnect v2: https://docs.shapeshift.com/faq/protocols/wallet-connect

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

Yes. https://docs.shapeshift.com/faq/protocols/earning-opportunities

### Does the wallet support swaps directly?

Yes. https://docs.shapeshift.com/faq/protocols/earning-opportunities

### Does the wallet support bridging directly?

Yes. https://docs.shapeshift.com/faq/protocols/trading-and-bridging

### Does the wallet support multi-chain networks?

Yes. 13 chains are supported. https://docs.shapeshift.com/faq/faq/blockchains

### Does the wallet support Ethereum layer 2 networks?

https://docs.shapeshift.com/faq/faq/blockchains

### Does the wallet allow the user to customize gas fees?

When prompted to sign a transaction with fees the user is provided with 3 options (Low, Normal, High) for the priority of the transaction with various level of fees. Currently no option to manually specify custom fees.

### Does the wallet support sending transactions to ENS addresses?

Yes. ENS addresses can be used to send and receive. Unstoppable Domains are also supported.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

List of supported token is based on Coingecko full list and updated twice weekly. Currently no way to import custom tokens (limits scams a lot).

### Does the wallet support EIP-1559 (type 2) transactions?

Yes. All the type of transactions supported can be viewed in the source code of the wallet abstraction: https://github.com/shapeshift/hdwallet/tree/master/packages/hdwallet-native/src

### Does the wallet have any recovery options?

During wallet creation the user is prompted to backup their 12-words seed and a short test is done to verify that they have done it.
After the wallet creation they can backup the words manually too from the UI.
And there is a documentation on how to import/restore a seed: https://docs.shapeshift.com/faq/faq/how-to-import-a-seed-phrase

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes. https://docs.shapeshift.com/faq/faq/supported-on-off-ramps

### Does the wallet support withdrawals to fiat?

Yes. https://docs.shapeshift.com/faq/faq/supported-on-off-ramps

### Is the wallet a multi-signature wallet?

No.

### Does the wallet support social recovery?

No.

### Does the wallet support bundled transactions?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

On Discord: https://discord.gg/shapeshift
Contact the Operations, Marketing, or Product Workstream.

### Does the wallet have a dedicated support team?

User support is provided on the official website (Support/Chat button bottom right) and in the app. ("Feedback / Support" button in left drawer menu) though a Live Chat which can be used to leave a message outside of the opening hours below.
Support team is available Monday-Friday between 3:00PM UTC and 11:00PM UTC, response time is usually within couple of days max.

### What educational resources/documentation do you provide to users?

https://docs.shapeshift.com/

### Does the wallet have any integrated tools not mentioned above?

Staking: ThorChain Saver Vaults which a form of unilateral staking for assets supported on ThorChain (ETH, BTC, DOGE, etc.), FOX staking (Uniswap), Cosmos/ATOM staking.
Lending: ThorChain Lending to borrow crypto using your assets (ETH and BTC) as collateral.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @firebomb1! Have assigned for product review

**Comment by wackerow** [comment]
Thanks @konopkja! @firebomb1 I see you checked "Yes" to wanting to work on this so I've gone ahead and assigned you. Let us know if you have issues!

**Comment by firebomb1** [comment]
Thanks, I'm making a PR now. I've just removed a link to Zendesk from the original submission as I've learned after filling the issue that we're depreciating our former Zendesk links. Hopefully the other documentation link is sufficient.
