### ISSUE TITLE
Updated URL scheme produces broken links

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/ethereum-org-website#1297]
**Describe the bug**
Hey team :wave:. In our (web3.py) documentation, we include a link to the python resources, formally located at `ethereum.org/python`, which now throws a 404. Manual navigation makes clear that this route has updated to `ethereum.org/en/python`. Was the intention to remove a "default" English route?

**Expected behavior**
By making this update, I have to imagine that very many Ethereum.org links around the web are now broken. My expectation would be for English to be the default. If not a working URL, at least a redirect to the `/en/` namespace would be preferable. 

:beers:

**Comment by samajammin** [comment]
Yikes! Thanks for the report @marcgarreau! [I added redirects from the old pages](https://github.com/ethereum/ethereum-org-website/blob/dev/netlify.toml#L120) but looks like I missed those language pages. Fixing now.

**Comment by samajammin** [comment]
@all-contributors please add @marcgarreau for bugs
