### ISSUE TITLE
Suggest a wallet (add back): Coin Wallet

### ISSUE THREAD

**Issue by mahnunchik** [ethereum/ethereum-org-website#12970]
### Wallet name

Coin Wallet

### What type of wallet?

EOA

### Wallet description

Coin Wallet is a non-custodial multicurrency wallet for multiple platforms.

### Wallet logo

![yRDhG3sqmo-228](https://github.com/ethereum/ethereum-org-website/assets/780935/28717cee-c133-442e-86bb-e06d45346ace)

### Background color for brand logo

#68c481

### URL to the project

https://coin.space/

### When did the wallet go live to users?

2015

### What are the fees users may be paying for using your wallet product?

Network fee for Ethereum

### Does the wallet have an active development team?

yes https://github.com/CoinSpace/CoinSpace

### Is the wallet globally accessible?

no KYC, no limitation

### Is the wallet available in multiple languages?

```
languages_supported: [
      "id",
      "bs",
      "cs",
      "de",
      "en",
      "es",
      "fil",
      "fr",
      "hr",
      "it",
      "hu",
      "nl",
      "nb",
      "pl",
      "pt-br",
      "ro",
      "sr",
      "sv",
      "vi",
      "tr",
      "ru",
      "uk",
      "th",
      "km",
      "ko",
      "ja",
      "zh-cn"
    ],
```

### What social links are there for the project?

* https://twitter.com/CoinAppWallet
* https://www.facebook.com/coinappwallet/
* https://www.linkedin.com/company/coin-space/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

https://apps.apple.com/app/apple-store/id980719434
https://play.google.com/store/apps/details?id=com.coinspace.app

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes, Windows, Mac, Linux

https://www.microsoft.com/store/apps/9NBLGGH5PXJQ
https://apps.apple.com/app/coin-wallet-bitcoin-crypto/id980719434?platform=mac
https://snapcraft.io/coin

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No browser extension, just a full featured web app https://coin.space/wallet/

### Is it a hardware wallet?

No

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

https://github.com/CoinSpace/CoinSpace/blob/master/LICENSE

### Who holds the private keys?

User, because it is non-custodial wallet

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Because it is live and open source from 2015 https://github.com/CoinSpace/CoinSpace

### Has the wallet's smart contract code or security modules been audited?

-

### Does the wallet have an internal security team?

yes

### Any other security testing that should be noted?

Wallet supports 2FA using any FIDO-certified security key.

https://hackerone.com/coinspace

### Scam protection?

Wallet uses audited crypto list https://github.com/CoinSpace/crypto-db

### Does the wallet support connecting to Ethereum applications?

Not yet, but planned

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support importing Ethereum RPC endpoints?

no

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support staking directly?

no

### Does the wallet support swaps directly?

yes

### Does the wallet support bridging directly?

no

### Does the wallet support multi-chain networks?

yes

### Does the wallet support Ethereum layer 2 networks?

yes

### Does the wallet allow the user to customize gas fees?

yes

### Does the wallet support sending transactions to ENS addresses?

yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

yes

### Does the wallet support EIP-1559 (type 2) transactions?

yes

### Does the wallet have any recovery options?

Your Keys, Your Crypto!

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

yes https://coin.space/buy-ethereum/

### Does the wallet support withdrawals to fiat?

yes

### Is the wallet a multi-signature wallet?

no

### Does the wallet support social recovery?

no, Your Keys, Your Crypto!

### Does the wallet support bundled transactions?

no

### Who can the ethereum.org team can contact regarding the wallet in future?

support@coin.space and https://t.me/nverkhovin

### Does the wallet have a dedicated support team?

Yes, we have support agents. 1 business day.
https://support.coin.space/hc/en-us
[support@coin.space](mailto:support@coin.space)

### What educational resources/documentation do you provide to users?

Help Center https://support.coin.space/hc/en-us

### Does the wallet have any integrated tools not mentioned above?

Coin Wallet supports second factor (2FA) using FIDO-certified security key (hardware) to complete any sensitive actions.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @mahnunchik, have assigned for review!

**Comment by konopkja** [comment]
hi @mahnunchik whats the wallet business model if there are no fees for user?

**Comment by konopkja** [comment]
"Does the wallet support Ethereum layer 2 networks?
yes"

which L2s are supported?

**Comment by mahnunchik** [comment]
@konopkja @wackerow 

* Wallet takes fee from some crypto https://coin.space/all-about-fees/
* Optimism L2 network is supported for now

WalletConnect will be added in next (or next next) release.

**Comment by konopkja** [comment]
Thank you for the clarifications, so there are no additional fees for swaps? (except for network fee)

**Comment by mahnunchik** [comment]
@konopkja No additional fees from the Wallet for any Ethereum transactions.

**Comment by konopkja** [comment]
@corwintines  lgtm

**Comment by wackerow** [comment]
Thanks @konopkja... @mahnunchik have assigned to you for PR

**Comment by wackerow** [comment]
Ah hah, never mind, reviewing #12948 now @mahnunchik
