### ISSUE TITLE
Feature Request: Infrastructure Deep Dive

### ISSUE THREAD

**Issue by stanislavkozlovski** [ethereum/ethereum-org-website#13029]
### Is your feature request related to a problem? Please describe.

Hey! I am interested in writing more about Ethereum - technical deep dives that are written simply.

In particular - I am interested in the infrastructure - how the protocol works.

I was trying to find this information on the website but for some reason couldn't - is it not there?

### Describe the solution you'd like

A page with architecture diagrams that explains how the blockchain protocol works

### Describe alternatives you've considered

.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by corwintines** [comment]
Just wanted to bump this @stanislavkozlovski, do you have a proposal for this?

**Comment by corwintines** [comment]
Going to close this out for now. @stanislavkozlovski feel free to open with more of a proposal.
