### ISSUE TITLE
Suggest a dapp : Meeds

### ISSUE THREAD

**Issue by plamarque** [ethereum/ethereum-org-website#13021]
### Name

Meeds

### Description

Fair and transparent rewards for Web3 contributors

### Logo

![meeds-256x256](https://github.com/ethereum/ethereum-org-website/assets/227828/58a87dd4-fe88-471d-a527-120b8c1fa281)

### Brand color

#D26561

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/Meeds-io/

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

- [Smart contracts code](https://github.com/Meeds-io/deeds-dapp/tree/develop/deeds-dapp-contract/src/main/resources) uses standards and [OpenZeppelin libraries](https://www.openzeppelin.com/contracts)
- self-audited with [MythX](https://consensys.io/mythx/about)
- informal reviews by [Black Paper](https://www.black-paper.xyz/) auditors : 

### Can a user access the dapp without creating an account?

No. Users can use Metamask  to create an account on a Meeds Hub using their Ethereum address

### Are dapp funds non-custodial?

Yes. 
Rewards target wallets can use Metamask (recommended), or if a user does not have Metamask installed, they are offered to generate a non-custodial Meeds wallet and back up their private key.User wallets can be self-custodial using Metamask (recommended), or if a user does not have Metamask installed, they are offered to generate a non-custodial Meeds wallet and back up their private key.

### Do you offer community support?

Yes, through Discord: https://discord.gg/8bfU2NuFb9

### Describe any geographical restrictions on usage of your dapp

global. Access through https://meeds.io

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @plamarque, have assigned to myself for review!

**Comment by plamarque** [comment]
> Looks good @plamarque! Assigned you, PR welcome

Thanks @wackerow I sent PR #13241 . 

Note : I placed it into Finance/Payment because it's closest category I could find, but I usually describe Meeds as a social/community-building tool

I didn't dare add a new Community category to Social, but I can if you agree. What do you think?

**Comment by wackerow** [comment]
@plamarque If it's more a social and community building tool, then sure, I think it's probably better to put it under the Social section and we can place it in a Community section. I'm not sure I see anything else that fills that role yet, so I'd say go for it! 

Do you feel comfortable making that addition in your referenced PR? If not let us know
