### ISSUE TITLE
Tomiborges9 

### ISSUE THREAD

**Issue by Tomiborges** [ethereum/ethereum-org-website#13028]
tomiborges9@gmail.com

**Comment by almesh** [comment]
> tomiborges9@gmail.com

**Comment by Brovmos** [comment]
> tomiborges9@gmail.com

Hello what's the issue?

**Comment by Tomiborges** [comment]
Não fui eu

Em sex., 24 de mai. de 2024 11:11, Brovmos ***@***.***>
escreveu:
