### ISSUE TITLE
Add CryoDAO to DeSci project list

### ISSUE THREAD

**Issue by KaiMicahMills** [ethereum/ethereum-org-website#13034]
### Is your feature request related to a problem? Please describe.

N/a

### Describe the solution you'd like

This issue aims to add CryoDAO to the https://ethereum.org/en/desci/ page.

CryoDAO is a DAO in the Molecule/bio.xyz ecosystem, similar to VitaDAO and ValleyDAO which are already listed here, but with the goal of funding high-impact research in cryopreservation (https://www.cryodao.org).

CryoDAO has raised $3M+ to date to fund and advance cryopreservation research with a global community on Ethereum.

Tagline: _CryoDAO: funding moonshot research in the field of cryopreservation_

### Describe alternatives you've considered

N/a

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Closed with #13035
