### ISSUE TITLE
Suggest a tutorial (WORLD3)

### ISSUE THREAD

**Issue by wufengtao1** [ethereum/ethereum-org-website#13039]
### Tutorial title

WORLD3 Ethereum Social Room

### Tutorial description

Explore the Ethereum Exhibition Hall in WORLD3, an autonomous world offering browser-based, immersive 3D multiplayer experiences.

### Tutorial tags

NFT, METAVERSE

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

Instance Spaces
Instance Spaces are domains in our 3D interactive social hub where WORLD3 users and partners can create curated experiences for all to enjoy! While you can access these Instance Spaces through the elevator, you can also do so directly by entering the permalinks into your browser.

Ethereum Exhibition Hall

This was developed during our previous collaboration with Ethereum.

The Ethereum 3D Social Exhibition Hall was Matrix World’s first multi-chain pavilion project and located in an Instance Room in the Matrix Universe Building, and users will use an elevator to enter. It aims to provide users with an immersive virtual space to learn about the ETH ecosystem and culture. This space allows users to learn what ETH is, how to create an ETH wallet, how to stake and buy ETH, the history of ETH, the ETH community, ongoing events, and more! Our AI ETH guides will guide users through the entire exhibition hall and answer their questions.

How to get there? Press the interactive key ‘F’ in front of the elevator in WORLD3 Headquarters lobby and select 2F to enter the square of ETH Social Pavilion. The interior of the pavilion can be reached by the beam elevator in the central area.

How to Interact? Users can approach the smart screen in the venue and press the interaction key ‘F’ to interact, including using the ETH wallet to sign in, jump to the specified URL, chat with the AI robot, etc.

How to Leave? Take the beam elevator back to the Pavilion square, then press the interactive key ‘F’ near the portal to select another floor and leave.

### For tutorials hosted elsewhere: URL to tutorial

https://medium.com/@WORLD3_AI/an-instructional-guide-to-world3-and-matrix-world-7d522953c678

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wufengtao1** [comment]
https://github.com/ethereum/ethereum-org-website/pull/13038

**Comment by wackerow** [comment]
Thanks @wufengtao1! I see your PR; have assigned for product review first

**Comment by wufengtao1** [comment]
> Thanks @wufengtao1! I see the linked PR; have assigned for product review first

Hi, we have already replied in the PR. Could you please take a look?

**Comment by wufengtao1** [comment]
@wackerow Hi, I have provided an analysis regarding the issue you raised. Please review it.

**Comment by corwintines** [comment]
Given this tutorial suggestion is very specific to a single application, I don't believe this is the right platform for this. Going to close this out for now.
