### ISSUE TITLE
Create story for DismissableBanner component

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#13044]
# Create story tests for DismissableBanner component

## Prerequisite

To get yourself up to speed on how we use storybook on ethereum.org, learn more [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/applying-storybook.md)

## What to do

- [ ] Move `/src/components/Banners/DismissableBanner.tsx` to `/src/components/Banners/DismissableBanner/index.tsx`
- [ ] Fix any filepath changes to imports for the DismissableBanner component
- [ ] Create story file `/src/components/Banners/DismissableBanner/DismissableBanner.stories.tsx`
- [ ] Write story testing render of the DismissableBanner component in context of use.

**Comment by wackerow** [comment]
@tutizaraz Again appreciate your enthusiasm to help! Please make sure to comment on an issue to get assigned before starting work on it (it's a frequent cause of duplicating work)

**Comment by wackerow** [comment]
Please note that we can only assign someone to an issue after they've commented on it, so I cannot yet assign you here. This also helps us just stay organized so we can visually see who's assigned to different tasks. Thanks!

**Comment by corwintines** [comment]
As mentioned @tutizaraz, in the future please comment in the issue and get assigned in the future, but appreciate you jumping on this. 

I have updated the information on implementation details for this issue. If you don't mind making those changes to fit this criteria in your PR that would be great.

**Comment by corwintines** [comment]
Trying to assign you and having issues finding you when using your username to assign. Will try assigning again tomorrow, not sure if this is a GitHub thing.

**Comment by TylerAPfledderer** [comment]
@tutizaraz following up here. 😄  It looks like there isn't a comment made by you under this issue. Please provide some kind of comment like "Commenting for assignment" here so @wackerow or @corwintines can properly assign you. I don't think tagging a PR to this issue will work.

By the way, even though your PR is blocked to run checks and tests, I'll still take a moment to review it before a core member can unblock it.

**Comment by TylerAPfledderer** [comment]
> @TylerAPfledderer i couldn't quite understand. @corwintines wasn't able to assign me this task for some reason. he said he'd try again later
> 
> And I didn't quite understand what exactly is blocking my pull request.
> 
> upd; Commenting for assignment

All good! 

I think Corwin's comment about not being able to assign you still had to do with you not yet commenting here. 😅 The assignment should work now!

You are a first-time contributor to this project, so the PR needs approval from a member to approve running the Github CI checks. My apologies for the lack of clarity.

**Comment by tutizaraz** [comment]
@TylerAPfledderer oke, thank you for the clarification

**Comment by wackerow** [comment]
> I think Corwin's comment about not being able to assign you still had to do with you not yet commenting here.

Yep! Sorry for confusion @tutizaraz, but we cannot assign someone to an issue if they haven't commented on it yet (even if a PR has been posted for it). Now I was able to 😄
