### ISSUE TITLE
Create story for Logo component

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#13067]
# Create story tests for Logo component

## Prerequisite

To get yourself up to speed on how we use storybook on ethereum.org, learn more [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/applying-storybook.md)

## What to do

- [ ] Move `/src/components/Logo.tsx` to `/src/components/Logo/index.tsx`
- [ ] Fix any filepath changes to imports for the Logo component
- [ ] Create story file `/src/components/Logo/Logo.stories.tsx`
- [ ] Write story testing renter of the Logo component in context of use

**Comment by corwintines** [comment]
@TommWolf im going to assign you to this issue

**Comment by corwintines** [comment]
If you comment on this issue @TommWolf I can assign you :)

**Comment by TommWolf** [comment]
I am redy for this issue.

**Comment by wackerow** [comment]
Thanks @TommWolf! Have assigned

**Comment by TommWolf** [comment]
So this is application programming task? I am really willing to help. I am not programator. Do you think that even though it is possible for me?

**Comment by TommWolf** [comment]
I have found the Logo.tsx component.

**Comment by corwintines** [comment]
@TommWolf the plan here is to implement a story for testing. I have updated the description of this issue to have more information on what needs to be done here. Let me know if you have any questions.

**Comment by corwintines** [comment]
@TommWolf any update?

I have unassigned for now, but let me know if you are still looking at this.

**Comment by corwintines** [comment]
@tomasgrusz would you be interested in taking on this story?

**Comment by tomasgrusz** [comment]
happy to pick this up @corwintines

**Comment by corwintines** [comment]
CLosing this out with merged PR
