### ISSUE TITLE
icons alignment is not centered

### ISSUE THREAD

**Issue by MahendraBishnoi29** [ethereum/ethereum-org-website#13078]
### Describe the bug
in the [wallets page](https://ethereum.org/en/wallets/#sim) the icons are not perfectly center aligned

### To reproduce

1. Go to  [wallets page](https://ethereum.org/en/wallets/#sim)
2. Scroll down to 'How to Stay Safe heading section'
4. See alignment bug in the steps

### Expected behavior

Icons should be center aligned.

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/167435856/b89a5ec1-6fb6-4524-b04d-a7ba38fffe07)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Looks good, thanks for reporting @MahendraBishnoi29! Have assigned you for a fix, let us know if you have issues or too busy, thanks!

**Comment by Agrim-Sharma174** [comment]
> > Looks good, thanks for reporting @MahendraBishnoi29! Have assigned you for a fix, let us know if you have issues or too busy, thanks!
> 
> nope, i don't have any issues, will raise a PR soon 🙌

hey, if you are not able to work on it right now, i can take this one

**Comment by hacanand** [comment]
assign it to me

**Comment by Uki7991** [comment]
aligning parent container by baseline fixes this issue

**Comment by siddharthbaleja7** [comment]
Is this issue still open?

**Comment by MahendraBishnoi29** [comment]
> Is this issue still open?

no, it's fixed. @siddharthbaleja7
