### ISSUE TITLE
Update "How do optimistic rollup fees work?" on Optimistic rollups 

### ISSUE THREAD

**Issue by iankressin** [ethereum/ethereum-org-website#13104]
### Describe the bug

With the inclusion of EIP-4844, I believe the section [How do optimistic rollup fees work?](https://github.com/ethereum/ethereum-org-website/blob/dev/public/content/developers/docs/scaling/optimistic-rollups/index.md#how-do-optimistic-rollup-fees-work-how-do-optimistic-rollup-fees-work) on Optimistic rollups need to be  updated to match the new fee dynamics created by Proto-Danksharding

This is more an update than a bug, but as I couldn't find a template for refactors, I used this one. Hope it's ok

### To reproduce

Visit =>  [How do optimistic rollup fees work?](https://github.com/ethereum/ethereum-org-website/blob/dev/public/content/developers/docs/scaling/optimistic-rollups/index.md#how-do-optimistic-rollup-fees-work-how-do-optimistic-rollup-fees-work)

### Expected behavior

Explain the new fee dynamics for rollups after EIP-4844

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @iankressin! Have assigned you

**Comment by corwintines** [comment]
Thanks @iankressin, seems like a good addition. Just wondering how things are going and if there something you need a hand with here.

**Comment by iankressin** [comment]
@corwintines I'm working on a draft, should have something next week. Is this timeline okay for you?

**Comment by iankressin** [comment]
@corwintines just opened the PR. I'd appreciate any feedback on the content! :heart:
