### ISSUE TITLE
Change Twitter Logo to X Logo

### ISSUE THREAD

**Issue by aj-ats** [ethereum/ethereum-org-website#13103]
### Is your feature request related to a problem? Please describe.

There is no Problem related  with the twitter logo 

### Describe the solution you'd like

Change twitter logo to X logo using the provided toolkit  https://about.x.com/en/who-we-are/brand-toolkit 
- ensure formatted properly across mobile/desktop devices 

### Describe alternatives you've considered

no  alternative solutions 

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by aj-ats** [comment]
@bhappy-buidl

**Comment by wackerow** [comment]
Duplicate of #12379, cc: @nloureiro
