### ISSUE TITLE
Proposal for Including Book reference in the Learning Resources Section learn/#books-and-podcasts

### ISSUE THREAD

**Issue by ferreiramarcelo** [ethereum/ethereum-org-website#13107]
### Is your feature request related to a problem? Please describe.

I’m reaching out to kindly request the inclusion of the book “**Blockchain in Practice: Your Step-by-Step Guide to Mastering the Digital Future**” in the list of suggested reading materials (book) on learning page. My book, released in November 2023 (available on Amazon - https://amzn.to/3X94t7H - English and Portuguese editions), offers valuable insights and comprehensive knowledge that would greatly benefit beginners and those seeking enterprise use of Ethereum.

_Highlighted Chapters_: 

- **Introduction to Blockchain**: Dive into its history, understand public and private keys, and discover how blockchain works.
- **Blockchain Beyond Cryptocurrencies**: Understand digital transformation and tokenization. 
- **Understanding Ethereum**: Discover what sets Ethereum apart from Bitcoin and navigate the world of Etherscan. 
- **Programming in Solidity**: Learn the language behind smart contracts. 
- **Tokens and NFTs on Ethereum**: Explore the world of tokens and learn how to create your own. 
- **Governance in Blockchain**: Delve into blockchain governance models and case studies. 
- **Cryptocurrency Exchanges**: Understand the differences between centralized and decentralized exchanges. 
- **Tools and Best Practices**: Master essential tools for blockchain development. 
- **Web3**: Navigate the future of digital assets and interconnectivity. 
- **Blockchain in the Corporate World**: Discover how this technology is revolutionizing business. 
- **The Present Future**: Explore the intersection of Blockchain, Artificial Intelligence, CyberSecurity, and CBDCs.

As one of the Learning Facilitators at MITPE's Blockchain program, where Ethereum serves as the primary blockchain for our program, I believe my book aligns perfectly with the educational goals of your page learn/#books-and-podcasts. I would be thrilled to see this book featured among the recommended resources, aiding learners in their journey to understanding and mastering Ethereum.

![livro](https://github.com/ethereum/ethereum-org-website/assets/11818521/36d39b92-9411-4224-b84b-269001ceb458)

### Describe the solution you'd like

Inclusion of the book “**[Blockchain in Practice: Your Step-by-Step Guide to Mastering the Digital Future](https://amzn.to/3X94t7H)  – November 25, 2023 –  Marcelo Ferreira**” in the list of suggested reading materials (book) on  Learning Resources Section learn/#books-and-podcasts

### Describe alternatives you've considered

N/A

### Additional context

Preview of the book on Amazon:

https://www.amazon.com/Blockchain-Practice-Step-Step-Mastering-ebook/dp/B0CNZHXD58/ref=tmm_kin_swatch_0?_encoding=UTF8&sr=8-1&asin=B0CNZT6YJR&revisionId=&format=4&depth=4

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @ferreiramarcelo! Have assigned for review first

**Comment by corwintines** [comment]
Hey @ferreiramarcelo,

Just wanted to check if there was a goodreads link for this book to follow the pattern we have on that page.

**Comment by ferreiramarcelo** [comment]
Hi @corwintines,

Yes, there is a Goodreads link. I'm not an expert on Goodreads, so I initially provided the direct Amazon link. 
However, here is the Goodreads link for the book: [https://www.goodreads.com/book/show/202678437-blockchain-in-practice](https://www.goodreads.com/book/show/202678437-blockchain-in-practice)

Thanks @corwintines

**Comment by minimalsm** [comment]
@all-contributors please add @ferreiramarcelo for ideas
