### ISSUE TITLE
Remove BloxStaking card from Staking as a Service provider page

### ISSUE THREAD

**Issue by ddannehh** [ethereum/ethereum-org-website#13116]
### Describe the bug

As per their own website: 
> BloxStaking has sunset.
> Blox has shut down. Node Operations are now ceased.

Blogpost: https://www.bloxstaking.com/blog/product-updates/bloxstaking-moving-to-new-horizons/

### To reproduce

1. Go to https://ethereum.org/en/staking/saas/#saas-providers
2. Scroll down to BloxStaking Card
3. Click "Get started"

### Expected behavior

Only list SaaS providers that are providing this service

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Thanks @ddannehh! 

<img width="1262" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/c439ee56-04bd-48d3-a949-c8321c38fcec">

Looks like it's time; have labeled as good first issue, open for contributors

**Comment by Khemmie-Ray** [comment]
Hello, can I be assigned this issue?

**Comment by wackerow** [comment]
Thanks @Khemmie-Ray! Just assigned

**Comment by Khemmie-Ray** [comment]
Alright

**Comment by RV12R** [comment]
Is it Open?
