### ISSUE TITLE
delist duplicate listing: MyEtherWallet

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13110]
### Describe the bug

https://ethereum.org/en/wallets/find-wallet/  has 2x MEW wallet listed

once as MEW wallet, second time as MyEtherWallet

**DELIST**
"MyEtherWallet"

(the one without "new to crypto" metadata)

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/ 
2. see error

### Expected behavior

delete duplicate listing

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by 0x0OZ** [comment]
MEW Wallet seems to be only an android/IOS wallet while my ether wallet is the desktop version, both have different repos and websites.

----
MewWallet:
https://github.com/mewwallet
https://www.mewwallet.com/
MyEtherWallet:
https://www.myetherwallet.com/
https://github.com/MyEtherWallet/MyEtherWallet

---

**Comment by konopkja** [comment]
> MEW Wallet seems to be only an android/IOS wallet while my ether wallet is the desktop version, both have different repos and websites.
> 
> MewWallet: https://github.com/mewwallet https://www.mewwallet.com/ MyEtherWallet: https://www.myetherwallet.com/ https://github.com/MyEtherWallet/MyEtherWallet

Do you see those two products to be significantly different from end user perspective? Or is it just one product on different platforms? From my view:

1. On both websites i see links redirecting users to the other product
2. the branding and logos are the same with minor alterations

Other wallets in our list also have multiple platforms, but are listed together as one wallet. I dont see enough arguments here to justify split to two products. Is there anything im missing?

**Comment by wackerow** [comment]
I see PR #13114 which removed "MyEtherWallet" (the desktop browser app)... These do have slight differences such as "hardware support" and "languages support", so this approach would effectively be removing the desktop/browser version, which to my knowledge only acts as a front-end, and not as a key-storage solution (you connect with another wallet).

I'm in favor of removing MyEtherWallet in this case, just wanted to note.

**Comment by wackerow** [comment]
@konopkja Does that sound good to you? Just approached that PR, we can merge if you're in agreement.

**Comment by konopkja** [comment]
> @konopkja Does that sound good to you? Just approached that PR, we can merge if you're in agreement.

lgtm
