### ISSUE TITLE
New design for Staking cards

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#13115]
### Is your feature request related to a problem? Please describe.

On [exploring](https://github.com/ethereum/ethereum-org-website/issues/12966) a new color scheme for the Design system, @ddannehh ended up designing a better version of the Stake cards.

We should isolate this design and implement it under the current design system.

this is the base proposal that should be worked to be implemented under the existing design system
![Screen Shot 2024-06-07 09 21 39 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/6c1d0d3c-edf5-4b99-a311-1104ae59e05e)

Link to the figma file
https://www.figma.com/design/wdBEEuqbT2t94jp92DTITy/New-Staking-cards?node-id=1-3&t=fJe1FAqkufXGCf9H-1

**Comment by ddannehh** [comment]
Done: https://www.figma.com/design/wdBEEuqbT2t94jp92DTITy/New-Staking-cards?node-id=1-416&t=vnKr7pv1chG3XhNX-1

<img width="1084" alt="Staking Cards" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/66e3d083-4342-41dc-92d3-45c3dc5765fc">

**Comment by ddannehh** [comment]
PS: Content issue, BloxStaking has been shutdown :)

**Comment by nloureiro** [comment]
> PS: Content issue, BloxStaking has been shutdown :)

can you open a new issue with this? it's easier to have a contributor to remove it
Thank you

**Comment by nloureiro** [comment]
@wackerow, long story short, we have new cards for staking :) 

what do you think?

**Comment by wackerow** [comment]
Agreed. I think this looks nice, though it's obviously a minimal change from the existing design... same layout, same structure and same information. We have a bit more data collected in the data JSON that we're not really displaying, ie socials, or fees... we could also consider ways to include these values.

**Comment by wackerow** [comment]
I like the switch to colored logos... the monochromatic look was challenging to maintain and arguably not worth it.

**Comment by nloureiro** [comment]
> Agreed. I think this looks nice, though it's obviously a minimal change from the existing design... same layout, same structure and same information. We have a bit more data collected in the data JSON that we're not really displaying, ie socials, or fees... we could also consider ways to include these values.

on nice!!!

can you add that extra data on Figma?

**Comment by ddannehh** [comment]
Included fees in the sub-header text and added social icons at the bottom.

<img width="1084" alt="Saas Providers" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/a1c6b029-7674-4aaf-a4a7-514249621a65">

Probably worth noting as well, the Key generators below the Saas Providers have a slightly different layout since they don't require a minimum ETH stake and have no fees

<img width="1084" alt="Key Generators" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/449c6f89-2dba-4dfe-b43d-aa9e878a29a2">

**Comment by wackerow** [comment]
Yeah this looks great... like the simple addition with the socials and the fees

**Comment by wackerow** [comment]
If I'm correct looks like it may pull away from DS a bit? @nloureiro checking in if this change was something you were interested in planning for or not.

**Comment by nloureiro** [comment]
> If I'm correct looks like it may pull away from DS a bit? @nloureiro checking in if this change was something you were interested in planning for or not.

Actually, @ddannehh made all the adjustments to make it a DS component.

From my side, it's ready to be coded unless you see some adjustments needed.

He also made a variation on the tabs that I like; it might be a different issue, but it goes a long with these cards really well.
![Screen Shot 2024-06-20 09 37 31 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/5b6aef93-fb7e-4719-ac1e-6463fa5018d1)

**Comment by wackerow** [comment]
Happy to implement this when bandwidth allows, but this could be a great task for someone looking to contribute.

Anyone interested in this for hacktoberfest? =) Ping a team member to be assigned, thanks!

**Comment by pettinarip** [comment]
FYI I've removed this component from the shadcn migration for now.

**Comment by rafagomes** [comment]
Hey guys, contributor wanna be here! Would love to this, to start getting my hands dirty and understanding the architecture... start small <3

**Comment by konopkja** [comment]
> @wackerow Hey guys, contributor wanna be here! Would love work on this one, to start getting my hands dirty and understanding the architecture... start small <3
> 
> If I understood correctly, the task is to update the style of the component of this page. http://localhost:3000/en/staking/saas/
> 
> I have already started to play with the component StakingProductCard
> 
> This is what I have today: ![image](https://private-user-images.githubusercontent.com/565337/373419326-e6f2d4f5-3570-4b99-8ae3-a06c6be7a03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMDU2NTYsIm5iZiI6MTcyOTEwNTM1NiwicGF0aCI6Ii81NjUzMzcvMzczNDE5MzI2LWU2ZjJkNGY1LTM1NzAtNGI5OS04YWUzLWEwNmM2YmU3YTAzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxOTAyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzhlZTA3OTY3ODg0NzhiZmY5YWQ5ZDhiZDg1OTY4MDE0NjcwODUzNTgyYTRjNTMwZGRiMGYxMGE4ZmY3NzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.czjHjwsNnt2GoGY1du5q1DwHRgWKP8-0Oh_mVIB2mX0)
> 
> My questions are:
> 
> * For social icons. The component is `<SocialListItem>`. As I understood, doesn't support black icons. I added optional parameters to change the size and color of the component, leaving the default to the existent number to avoid conflicts.
> * For the Image/svg of the brand, how can I make it original/colorful? Only accepts the colors we have...so I added base as temporary for you too understand.
> 
> I'm creating the PR to see the implementation so far. Ignore the commits, will squash upon we have all questions solved.

i think this would be for all staking pages, maybe all cards in general - question for @nloureiro

**Comment by wackerow** [comment]
@all-contributors please add @ddannehh for design

**Comment by wackerow** [comment]
We should open a separate task to ensure
- Addition of **fee information**
- Color brand logos

These were not included in #14047
