### ISSUE TITLE
Listing our web application: Request Finance (https://www.request.finance/)

### ISSUE THREAD

**Issue by Sunil525** [ethereum/ethereum-org-website#13112]
### Name

Request Finance

### Description

A suite of financial tools to make your life easier - crypto organizations & freelancers use Request for invoices, expenses, payroll and accounting. Trusted by 2300+ businesses including AAVE, The Graph, Sandbox to process over $700m in crypto invoices, payroll, expenses, grants and more.

### Logo

![62bb2644a84a2f9d5e650b77_Logo_full-blue (1)](https://github.com/ethereum/ethereum-org-website/assets/171324787/d41c9094-e478-4053-b323-9878c64eeb3f)

### Brand color

#2b6ff4

### Is your dapp open source?

No

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

[2022.06 Sayfer Penetration Testing Certification For Request Finance.pdf](https://github.com/user-attachments/files/15604122/2022.06.Sayfer.Penetration.Testing.Certification.For.Request.Finance.pdf)

This security test was done in 2022, and we have another security test scheduled to happen this year.

### Can a user access the dapp without creating an account?

A user cannot access the app only with their wallet, but it can be done using their email. Once inside, we help the user create invoices, receive payments and more, using every prominent wallet out there. (We have integrations with Walletconnect too).

As part of the onboarding, only their name and email is asked, or they can sign-up using Google as well. We also help businesses pay in crypto while their employees receive in fiat, with very affordable pricing options

### Are dapp funds non-custodial?

We only help process payments, and we're completely non-custodial. We help companies, DAOs, and professionals to easily manage crypto invoices, salaries, and expenses in a fast and non-custodial way.

### Do you offer community support?

We offer support through our chatbot (Intercom), and we have an extensive product guide/ help center to help any new users.

### Describe any geographical restrictions on usage of your dapp

Residents of North Korea, Iran and Myanmar are prevented from using the web application. All other countries are free to use our platform.

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by wackerow** [comment]
Thanks @Sunil525! Have assigned for initial review

**Comment by corwintines** [comment]
Thanks @Sunil525!

This seems good for me on my end. Wondering where you would see this, and if you were wanting to work on adding it.

**Comment by corwintines** [comment]
Ive assigned you for now @Sunil525 since you marked yes in the issue for working on it :)

**Comment by Sunil525** [comment]
Hello @corwintines!

Can we get Request Finance shown here: https://ethereum.org/en/dapps/

We offer a completely self custodial platform for payments, payroll, accounting and more. We're also SOC 2 compliant, and will be offering insurance for payments soon :)

**Comment by corwintines** [comment]
Yes @Sunil525, I have assigned you to make the PR.

**Comment by Sunil525** [comment]
@corwintines, I'm not a developer, but is it okay if I invite a dev from my team who can work on this?

**Comment by Sunil525** [comment]
@corwintines, I think it would be best if you can help us make the necessary changes. I've changed my answer for this question (Would you like to work on this issue?).

Apologies for the confusion!

**Comment by corwintines** [comment]
@Sunil525 feel free to have a dev from your team comment here and I will assign. Otherwise, I will open it up for the community to take.

**Comment by Sunil525** [comment]
@corwintines, can you please open it up for the community? Thanks a lot!

**Comment by Sunil525** [comment]
@corwintines, is it possible to get a timeline on when we'll be shown on https://ethereum.org/en/dapps/

Thank you :)

**Comment by Vedant-asati** [comment]
@corwintines i have created a pr, let me know if anything needs to be changed.

**Comment by Sunil525** [comment]
Thank you so much guys!!
