### ISSUE TITLE
Typo on Staking as a Service page

### ISSUE THREAD

**Issue by ddannehh** [ethereum/ethereum-org-website#13117]
### Describe the bug

Typo on page (ENG): https://ethereum.org/en/staking/saas/#saas-providers
Check first line below the "Explore staking service providers" title
Below are some available SaaS provider.
Should be
Below are some available SaaS provider**s**.

### To reproduce

1. Go to https://ethereum.org/en/staking/saas/#saas-providers
2. Check first line below the "Explore staking service providers" title

### Expected behavior

Fix typo

### Screenshots

![Screenshot 2024-06-07 at 13 05 43](https://github.com/ethereum/ethereum-org-website/assets/109203827/64931b15-6ae6-4c45-b7f7-bf0578ba3473)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Looks like we just need an "s" on here, thanks for reporting @ddannehh! Have opened up for contributors

**Comment by Khemmie-Ray** [comment]
Hello, can I work on this task?

**Comment by kyndrawynne** [comment]
Mind if I take this one?
