### ISSUE TITLE
Update solo staking section

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#13134]
## Description
From discussion on #9277:

- [ ] Update terminology to use "home staking" instead of "solo staking"
- [ ] Add informational section about <32 ETH options for home staking
- [ ] Emphasize importance of staking from home; add _brief_ note that liquid staking options are available even for home stakers (need for LST should not stop a user from considering home staking)
- [ ] Add indicator to products that support liquid staking options

These are the key points I've pulled from discussion on the above thread. This will require some help with content writing, and will require design input (potentially with a little design work).

cc: @Jstar101

**Comment by MukulKolpe** [comment]
Hey @wackerow, can I work on this issue?

**Comment by Jstar101** [comment]
Hey guys - I've drafted some thoughts on a Google Doc - would be good to get your opinions on my suggestions. It essentially tweaks the current format/content to better highlight that solo/home staking and liquid staking are not mutually exclusive, plus shifts the narrative from solo staking to home staking. The design remains the same to reduce the scope of work

[Google Doc](https://docs.google.com/document/d/1ALDmRTkd3nO8wgLVTByo6Z8v8cu6M0GWTBhLRRKabHA/edit?usp=sharing)
 
 (also @wackerow , check your TG ;) )

**Comment by wackerow** [comment]
@Jstar101 Thanks! Made comments on that document. I would suggest taking that to PR form at this point and the rest could be iterated on in there where we can see how it looks on the site as well.

@MukulKolpe I've assigned @Jstar101 since he's been involved in this ongoing discussion for a while now, but I'll defer to him if he'd prefer someone else to implement this. 

As for design research, the proposed changes in the doc probably don't require too much in terms of design consideration ahead of time, but will need design eyes once the PR is ready.

**Comment by Jstar101** [comment]
Thanks for your comments on the Google Doc @wackerow, I have made updates based on your suggestions.

Regarding the PR, I will need assistance here (I rarely use GitHub). I'm happy to transfer the suggested changes from the Google Doc into the PR, but can someone get the PR started? @MukulKolpe

**Comment by MukulKolpe** [comment]
@Jstar101, I'd be happy to. I'll get the PR started and let you know when it's ready.

**Comment by MukulKolpe** [comment]
Hi @Jstar101, @wackerow. I would love to hear your thoughts on #13357. Please let me know if any changes are needed.

**Comment by Jstar101** [comment]
Thanks for creating the PR @MukulKolpe ! It looks great. I added only 1 comment on Line 38: I think this would read better if it was "Considerations before home staking", rather than "staking home"

**Comment by MukulKolpe** [comment]
Yes, I agree. "Considerations before home staking" reads better than "staking home." Thanks for the suggestion @Jstar101! I’ve updated it.
