### ISSUE TITLE
1inch Wallet

### ISSUE THREAD

**Issue by khkseniaa** [ethereum/ethereum-org-website#13159]
### Wallet name

1inch Wallet

### What type of wallet?

EOA

### Wallet description

The 1inch Wallet is a fast, secure, and user-friendly non-custodial DeFi crypto wallet supporting multiple networks and hundreds of tokens. It offers advanced features like biometric authentication, secure backup, scam protection with transactions simulation and validation, AML, and the ability to manage transactions with ease, making it a versatile and highly secure choice for crypto enthusiasts.

### Wallet logo

![Product=1inch Network, Dark Mode=off, colors=on, type=vertical](https://github.com/ethereum/ethereum-org-website/assets/33128415/4cc21797-ea54-48fa-8783-65b5d645e36d)

### Background color for brand logo

2F8AF5

### URL to the project

https://wallet.1inch.io

### When did the wallet go live to users?

01.04.2021

### What are the fees users may be paying for using your wallet product?

No additional charges, just the standard network gas fees

### Does the wallet have an active development team?

https://github.com/1inch

### Is the wallet globally accessible?

Accessible worldwide with no KYC requirements

### Is the wallet available in multiple languages?

English, Spanish, French, Hindi, Portuguese, Russian, Japanese, Korean, German, Turkish, Vietnamese, Indonesian, Chinese (Simplified)

### What social links are there for the project?

https://x.com/1inchwallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

[iOS](https://apps.apple.com/us/app/1inch-defi-wallet/id1546049391)
[Android](https://play.google.com/store/apps/details?id=io.oneinch.android)

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No desktop app

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

[Mobile Safari browser extension](https://apps.apple.com/us/app/1inch-defi-wallet/id1546049391)

### Is it a hardware wallet?

No hardware wallet

### What is the availability of your source code?

Closed source

### What license is the wallet software released under?

Released under a proprietary license, ensuring the code remains closed source and protected.

### Who holds the private keys?

1inch Wallet is EOA wallet, where users have full access to their public and private keys. No one else, including the company, has access to these keys

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://blog.1inch.io/the-1inch-wallet-security-explained/

### Has the wallet's smart contract code or security modules been audited?

https://blog.1inch.io/the-1inch-wallet-security-explained/

### Does the wallet have an internal security team?

Yes

### Any other security testing that should be noted?

1inch Wallet has undergone comprehensive security testing, including penetration testing, vulnerability assessments, and regular code reviews to ensure its robustness and reliability

### Scam protection?

1inch Wallet ensures multiple layers of security for users. Any time a user connects their wallet to sign a transaction, 1inch Wallet provides clear information about what will actually happen when the transaction is executed. It simulates any transaction involving a wallet, dApp, or smart contract across multiple blockchains.

### Does the wallet support connecting to Ethereum applications?

WalletConnect, Web3 Browser, Safari Extension

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

Yes

### Does the wallet support bridging directly?

No

### Does the wallet support multi-chain networks?

Yes, it supports 12 networks

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes, with Unstoppable Domains and LENS support

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, it supports all types of transactions

### Does the wallet have any recovery options?

1inch Wallet offers recovery options including iCloud, Google Drive, and file backup support. Users can securely back up their wallet data, ensuring easy recovery in case of device loss or damage. Additionally, users can create a local file backup, which can be stored safely and used to restore the wallet on any compatible device.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

Yes

### Does the wallet support bundled transactions?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

wallet@1inch.io
https://x.com/1inchwallet

### Does the wallet have a dedicated support team?

Yes, 1inch Wallet has live support chat

### What educational resources/documentation do you provide to users?

https://help.1inch.io/en/collections/2897068-1inch-wallet
https://blog.1inch.io

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Looks good, I see we already list 1inch Wallet... Assuming this is updated information @khkseniaa? I've gone ahead and assigned you, PR welcome for any differences to what is already live. Can close out if no changes.

**Comment by konopkja** [comment]
> Looks good, I see we already list 1inch Wallet... Assuming this is updated information @khkseniaa? I've gone ahead and assigned you, PR welcome for any differences to what is already live. Can close out if no changes.

yes this was upon request for update, @wackerow  since we are collecting new information i think we will have to add new metadata to our file where we store info

**Comment by corwintines** [comment]
Thanks @khkseniaa 

I just have one clarifying question, which 12 networks does the 1inch wallet support? We are looking at getting this information more explicitly as we expand our content.

**Comment by wackerow** [comment]
Following up, @khkseniaa are you still interested in updating this? Assigned right now... If so, please include the networks per above request, else we can open up for someone else to jump in.

**Comment by khkseniaa** [comment]
@corwintines @wackerow Sorry, I missed your previous question. Regarding networks we support the following: Ethereum, BNB chain, Polygon, Optimism, Arbitrum, Gnosis chain, Avalanche, Fantom, Klaytn, Aurora, zkSync Era, Base.

Regarding the newly provided information, yes we would like to have it updated in our profile.

**Comment by MukulKolpe** [comment]
Hi @konopkja, @wackerow. If it's alright, I’d like to work on this. Could you please assign it to me?
