### ISSUE TITLE
Suggest a tutorial: Server components for web3 apps

### ISSUE THREAD

**Issue by qbzzt** [ethereum/ethereum-org-website#13158]
### Tutorial title

Server components for web3 apps

### Tutorial description

After this tutorial, you will be able to write TypeScript servers that listen to events on a blockchain and respond accordingly with their own transactions. This will enable you to write applications that are centralized (because the server is a point of failure), but can interact with web3 entities.

### Tutorial tags

server, offchain, centralized

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

- Introduction: Why a Centralized Server?
- Getting started: Node, TypeScript, and Viem
- Listening to Events
- Responding with Transactions
- Conclusion, when is this an appropriate solution?

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
@qbzzt Interesting... so would these "server components" be like front end components? Or more of an API that is listening to events and capable of responding with actions?

cc: @minimalsm

**Comment by qbzzt** [comment]
They can be either. I'm thinking of a use case that requires listening to events, but it can be triggered by any other input too.

**Comment by wackerow** [comment]
Gotcha, I see what you're getting at here. Sounds good from my end!

**Comment by qbzzt** [comment]
Written (#13228). Next, I'll submit a proposal for a sequel that teaches how to use zero-knowledge proofs for a centralized component that holds a secret state and can be trusted. Do you think it's better to use [Zokrates](https://zokrates.github.io/toolbox/zokrates_js.html) or [Cairo](https://docs.cairo-lang.org/)?

**Comment by wackerow** [comment]
> Written (#13228). Next, I'll submit a proposal for a sequel that teaches how to use zero-knowledge proofs for a centralized component that holds a secret state and can be trusted (#13234). Do you think it's better to use [Zokrates](https://zokrates.github.io/toolbox/zokrates_js.html) or [Cairo](https://docs.cairo-lang.org/)?

@qbzzt Not sure personally as these aren't tools I have familiarity with; feel like I've heard more about Zokrates lately though, but I'll let you be the judge.
