### ISSUE TITLE
Solo staking page: Goerli has been deprecated; use Holesky

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#13168]
### Describe the bug

The [`/staking/solo`](https://ethereum.org/en/staking/solo/#get-started-on-the-staking-launchpad) page has a widget for users to get started with staking, but it is still pointing to the Goerli Launchpad. This should be updated to use the [Holesky testnet Launchpad](https://holesky.launchpad.ethereum.org/en/) instead.

### To reproduce

1. Go to https://ethereum.org/en/staking/solo/#get-started-on-the-staking-launchpad
2. Click on the dropdown for "Choose a network"
3. See use of Goerli testnet, which has been deprecated.

### Expected behavior

References to Goerli should be removed and replaced with the Holesky testnet where users can practice staking before going to Mainnet.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by SnehalSrivastava27** [comment]
I would like to take this issue
Can I go ahead?

**Comment by wackerow** [comment]
> @wackerow I have made all the required content and translation changes please check it out

Did you push them to #13184? Not seeing them

**Comment by SnehalSrivastava27** [comment]
@wackerow i made a new pull request

**Comment by wackerow** [comment]
Oh, apologies, getting confused with different authors. @SnehalSrivastava27 you were the first to request to work on the issue and would like to honor this. @tutizaraz appreciate the enthusiasm, but please make sure to comment on an issue an await being assigned before jumping straight to posting PRs to avoid conflict.

**Comment by tutizaraz** [comment]
Sure @wackerow ! Good job @SnehalSrivastava27
