### ISSUE TITLE
Replace ethereum.org's Galxe URL on /contributing/#oat

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#13180]
### Describe the bug

Replace ethereum.org's Galxe URL on /contributing/#oat

### To reproduce

1. Go to https://ethereum.org/en/contributing/#oat
2. On `you will have a change to claim a special badge on [Galxe](https://galxe.com/ethereumorg/)`, replace URL to https://app.galxe.com/quest/ethereumorg

### Expected behavior

n/a

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by jacobjelen** [comment]
I'll fix this

**Comment by isabelladebrito** [comment]
thanks @jacobjelen! 🙌
