### ISSUE TITLE
Website should be compatible with Dark Mode extensions

### ISSUE THREAD

**Issue by jjmstark** [ethereum/ethereum-org-website#132]
Some people use extensions like [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) when browsing the web. Currently, ethereum.org produces weird graphical errors when viewed through that extension, as documented [here](https://twitter.com/zigguratt/status/1149057024036151296). 

We should make ethereum.org compatible with such extensions, by either detecting them and flipping the website automatically to the existing dark-mode setting, or simply fixing the issues that cause the strange formatting issues.

**Comment by Z3N0** [comment]
maybe this: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by samajammin** [comment]
This is definitely something we should address but it's not a top priority. Will spike on a solution (and label as a `wip` when I begin), but in the meantime, contributions welcome!

**Comment by samajammin** [comment]
Looks like this was solved in https://github.com/ethereum/ethereum-org-website/pull/115

Feel free to re-open if you're still seeing issues!
