### ISSUE TITLE
Unaccessible link on the "Intro to Ethereum" page

### ISSUE THREAD

**Issue by AlexanderLukin** [ethereum/ethereum-org-website#13209]
### Describe the bug

The link [How does Ethereum work, anyway?](https://www.preethikasireddy.com/post/how-does-ethereum-work-anyway) in the [FURTHER READING](https://ethereum.org/en/developers/docs/intro-to-ethereum/#further-reading) section of the "Intro to Ethereum" page is no longer accessible. It should probably be removed from this section or replaced with its up-to-date version.

### To reproduce

Go to this page
https://ethereum.org/en/developers/docs/intro-to-ethereum/#further-reading
The second link in the section is no longer accessible.

### Expected behavior

All links on the site should be correct.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks for surfacing @AlexanderLukin! PR welcome to remove this link.

**Comment by AlexanderLukin** [comment]
Great! Here it is https://github.com/ethereum/ethereum-org-website/pull/13219

I decided to update the link instead of removing it, because the article is excellent.

**Comment by AlexanderLukin** [comment]
Looks like the domain is fixed, so, we may not change the original link. I'm closing the issue together with my PR, as the existing link is working fine.
