### ISSUE TITLE
Add Chronicle to Oracles page

### ISSUE THREAD

**Issue by biancabuzea200** [ethereum/ethereum-org-website#13220]
### Dev tool name

Chronicle Protocol

### Dev tool description

[Chronicle](https://chroniclelabs.org/) - Chronicle overcomes the current limitations of transferring data on-chain by developing truly scalable, cost-efficient, decentralized, and verifiable Oracles.

### When did the dev tool go live?

2017, used to be part of Maker's Oracle Unit

### Where do you think this page should be shown?

https://ethereum.org/en/developers/docs/oracles/

### Is the product open source?

Yes

### GitHub URL

https://github.com/chronicleprotocol

### Documentation URL

https://docs.chroniclelabs.org/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @biancabuzea200 

This seems ok for me, going to assign to you to add :)

**Comment by wackerow** [comment]
Fixed with #13424
