### ISSUE TITLE
Create story for MergeInfoGraphic

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#13242]
# Create story tests for MergeInfoGraphic component

## Prerequisite

To get yourself up to speed on how we use storybook on ethereum.org, learn more [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/applying-storybook.md)

## What to do

- [ ] Create story file `/src/components/MergeInfoGraphic/MergeInfoGraphic.stories.tsx`
- [ ] Write story testing render of the MergeInfoGraphic component in context of use

The MergeInfoGraphic is used on the [/roadmap/merge page](https://ethereum.org/en/roadmap/merge). You can find the file its used in for context [here](https://github.com/ethereum/ethereum-org-website/blob/4d9f0b6ef53f46f399c8e57faa4a20f232c1c22a/public/content/roadmap/merge/index.md#L22).

**Comment by corwintines** [comment]
@baystef I have created this issue for the MergeInfoGraphic. If you don't mind commenting in here, I can assign to you :)

**Comment by Baystef** [comment]
Hi @corwintines , I'll love to be assigned this. Thanks 🙂

**Comment by corwintines** [comment]
Great, assigned to you @baystef!
