### ISSUE TITLE
Chinese content bug

### ISSUE THREAD

**Issue by zzzzzshPig** [ethereum/ethereum-org-website#13271]
### Describe the bug

https://ethereum.org/zh/zero-knowledge-proofs/

There are translation errors present

### To reproduce

open website https://ethereum.org/zh/zero-knowledge-proofs/

search "零知识简洁非交互式知识论证是零知识简洁非交互式知识论证的缩写"

### Expected behavior

It should be translated as "ZK-SNARK是零知识简洁非交互式知识论证的缩写"

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/26410989/6463b599-698a-47c6-a45b-27e9e38d3871)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey thanks for reporting @zzzzzshPig... Are you familiar with [our Crowdin project](https://crowdin.com/project/ethereum-org) by chance? This is where we handle all of our non-English content updates...

We can patch this here in GitHub, but to prevent this from being overwritten when translations are imported (1st of each month) I'll address this on Crowdin as well. Assigning you for a PR in the meantime, thanks!
