### ISSUE TITLE
Update Developer Bootcamps List

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [ethereum/ethereum-org-website#13294]
## Description

Hey,

I noticed that on the [Ethereum.org Developer Learning Tools page](https://ethereum.org/en/developers/learning-tools/), both Chainshot and Alchemy University are listed separately. Since Chainshot was acquired by Alchemy and is now rebranded as Alchemy University, it would make sense to remove Chainshot from the list. This will help avoid confusion and keep the resources up to date.

The Chainshot URL now redirects to Alchemy University following its acquisition and rebranding.

Chainshot URL: [https://www.chainshot.com/](https://www.chainshot.com/) (redirects to Alchemy University)  
Alchemy University URL: [https://university.alchemy.com/](https://university.alchemy.com/)

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by testgithubsonika** [comment]
[Shiva-Sai-ssb](https://github.com/Shiva-Sai-ssb)
 hey, I can solve this issue. if you want , you can assign this to me.i can make those url commmon.

**Comment by wackerow** [comment]
Great! Thanks for reporting @Shiva-Sai-ssb! Appreciate you offering to help @testgithubsonika, assigning you

**Comment by Shiva-Sai-ssb** [comment]
> [Shiva-Sai-ssb](https://github.com/Shiva-Sai-ssb) hey, I can solve this issue. if you want , you can assign this to me.i can make those url commmon.

Hey, you need to remove ChainShot from the list of developer bootcamps because ChainShot and Alchemy University are now a single entity.

**Comment by rohitt-gupta** [comment]
@wackerow please review the above PR

**Comment by rohitt-gupta** [comment]
@konopkja Hey can you please reqiew and merge this pr if it fits the criteria
