### ISSUE TITLE
Inappropriate padding in code blocks

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#13299]
### Describe the bug

The `Codeblock` component is used to render various types of code snippets from the triple-backtick markdown syntax (\`\`\`). These blocks currently do not have appropriate padding applied to them.

### To reproduce

1. Go to https://ethereum.org/en/developers/tutorials/all-you-can-cache (or any page with code snippets)
2. Scroll down to some code snippets
3. Notice the lack of padding on the bottom of the code blocks

### Expected behavior

Codeblocks should have 1.5rem padding-bottom applied to improve readability

### Screenshots

<img width="937" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/dd6853ef-6b02-4b98-b820-8eb1268db518">

### Additional context

Note that some codeblocks have a "copy" button added to it which alters the top padding; this should remain unchanged. The codeblocks _without_ the copy button use `24px` (`1.5rem`, **size token `6`**) for the top padding; I would recommend we use the same for the bottom.

Similarly, some code blocks are longer than others... there is a max-height applied initially, with a "Show all" button for longer blocks. In those cases, we do _not_ need padding if there is more code to scroll to, but once we're at the bottom there _should_ be padding.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Baystef** [comment]
> ### Describe the bug
> The `Codeblock` component is used to render various types of code snippets from the triple-backtick markdown syntax (```). These blocks currently do not have appropriate padding applied to them.
> 
> ### To reproduce
> 1. Go to https://ethereum.org/en/developers/tutorials/all-you-can-cache
> 2. Scroll down to some code snippets
> 3. Notice the lack of padding on the bottom of the code blocks
> 
> ### Expected behavior
> Codeblocks should have 1.5rem padding-bottom applied to improve readability
> 
> ### Screenshots
> <img alt="image" width="937" src="https://private-user-images.githubusercontent.com/54227730/344677757-dd6853ef-6b02-4b98-b820-8eb1268db518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDQ1MDIsIm5iZiI6MTcxOTg0NDIwMiwicGF0aCI6Ii81NDIyNzczMC8zNDQ2Nzc3NTctZGQ2ODUzZWYtNmIwMi00Yjk4LWI4MjAtOGViMTI2OGRiNTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE0MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjMxMDUxYTcwNDkzZjlhZmYyMmIzMjZkMzg2OTczMmJkNDVjNjBmZjk5OGE3YzE3MTdiZjhmMmU4ZDU5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6MC2umVMwtYPco0rZTUCip5LSZa3158rEeDiI-8V9Zw">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional context
> Note that some codeblocks have a "copy" button added to it which alters the top padding; this should remain unchanged. The codeblocks _without_ the copy button use `24px` (`1.5rem`, **size token `6`**) for the top padding; I would recommend we use the same for the bottom.
> 
> Similarly, some code blocks are longer than others... there is a max-height applied initially, with a "Show all" button for longer blocks. In those cases, we do _not_ need padding if there is more code to scroll to, but once we're at the bottom there _should_ be padding.
> 
> ### Would you like to work on this issue?
> * [x]  Yes
> * []  No

**Comment by wackerow** [comment]
Hey @Baystef hah are you trying to say "Yes" you'd like to work on this?

**Comment by Baystef** [comment]
> Hey @Baystef hah are you trying to say "Yes" you'd like to work on this?

Yes, please @wackerow

**Comment by wackerow** [comment]
Great, thanks! Assigning =)

**Comment by sandeepV2** [comment]
@wackerow @Baystef I see this behaviour across all the tutorial pages.  Sorry but, Couldn't resist to solve it.

**Comment by wackerow** [comment]
Looping back, appreciate the patch @sandeepV2... @Baystef apologies for the override, mind if we re-assign and find another one for ya? Would check out the [unassigned "good first issues"](https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee) if you're interested!

**Comment by Baystef** [comment]
> Looping back, appreciate the patch @sandeepV2... @Baystef apologies for the override, mind if we re-assign and find another one for ya? Would check out the [unassigned "good first issues"](https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee) if you're interested!

Sure, I'll look through and tag you to it
