### ISSUE TITLE
Incorrect Image Paths in README.md

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [ethereum/ethereum-org-website#13308]
### Describe the bug

The README.md file contains broken image links due to changes in file paths.

### To reproduce

1. Go to the README.md file on the main repository page.
2. Locate the Ethereum logo, Netlify preview image, and POAP logo.
3. Observe that these images are not displaying correctly.

### Expected behavior

All images in the README.md file should display correctly with the updated file paths.

### Screenshots

1. 
![Pic-1](https://github.com/ethereum/ethereum-org-website/assets/112751524/babd7989-1b3f-41a2-901c-055c9afb8cb6)

2. 
![Pic-2](https://github.com/ethereum/ethereum-org-website/assets/112751524/de5c7454-2748-453f-b96b-607626980393)

3. 
![Pic-3](https://github.com/ethereum/ethereum-org-website/assets/112751524/e2d853bf-3410-4426-9057-c7e3f9b78f07)

### Additional context

1. The Ethereum logo path should be changed from `./public/assets/eth-transparent.png` to `./public/images/assets/eth-transparent.png`.

2. The Netlify preview image path should be changed from `public/preview-deploy.png` to `public/images/preview-deploy.png`.
3. The POAP logo path should be changed from `public/poap-logo.svg` to `public/images/poap-logo.svg`.

Moreover, only GitPOAP is given to contributors upon making their first pull request on merging it into the repo, while OATs are given to contributors for making significant contributions to the repo, including translations. I think it would be beneficial to replace the section specifically mentioning POAP with a section describing OATs instead.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment]
Thanks for raising @Shiva-Sai-ssb! I've put up a patch for this

**Comment by wackerow** [comment]
@all-contributors please add @Shiva-Sai-ssb for bug report
