### ISSUE TITLE
I wanna bild my Coin from Zero 

### ISSUE THREAD

**Issue by Caesar-001** [ethereum/ethereum-org-website#13304]
### Tutorial title

How to do it 

### Tutorial description

Bild the coin from Zero 

### Tutorial tags

10 Days

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by aj-ats** [comment]
this kind of tutorial is already on etherum.org here
 https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/

**Comment by wackerow** [comment]
Thanks for posting @Caesar-001... Curious if you feel the link @aj-ats posted satisfies what you're looking for here, or if you were looking for something with more detailed steps for exactly how to deploy a token with the ERC-20 standard?

**Comment by corwintines** [comment]
Going to close this out.
