### ISSUE TITLE
Updating a file in src/intl directory

### ISSUE THREAD

**Issue by jyoo** [ethereum/ethereum-org-website#1330]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I see that some JSON files in `ethereum-org-website/src/intl` are not updated yet compared to `en.json`. I can update `ko.json` as I speak Korean, but I am not sure if it is okay to follow the structure of `en.json` (i.e, key and value sets in the file)

**Describe alternatives you've considered**
Update `ko.json`

**Additional context**
Not applicable

**Comment by samajammin** [comment]
Awesome @jyoo! Thank you for offering to help out!

We ask that you please translate in Crowdin (the platform we use) vs. editing the `ko.json` file directly. That's the easiest way for us to edit, review & track translations. 

You can find the Korean translations here (it looks like we could use help with the `Contents v1.1` translations):
https://crowdin.com/project/ethereumfoundation/ko#

You can find instructions on how to get up & running as a translator here:
https://ethereum.org/en/languages/#ethereum-org-translation-program

Thanks again!

**Comment by jyoo** [comment]
No worries! I am happy to help. I will close this for now.
