### ISSUE TITLE
Add Node Guardians to Interactive game tutorials list

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [ethereum/ethereum-org-website#13325]
## Description

* Add [Node Guardians](https://nodeguardians.io/) to the list of Interactive game tutorials on [Learning tools](https://ethereum.org/en/developers/learning-tools/). 

* Node Guardians is a gamified educational platform aimed at web3 developers. It offers an immersive journey through Solidity, Cairo, Noir, Huff, and more, providing an entertaining way to enhance and practice development skills.

### Would you like to work on this issue?
- [ ] Yes
- [x] No

**Comment by wackerow** [comment]
Looks good! Down to see Node Guardians listed... will open up for contributor.

**Comment by codingmickey** [comment]
Hey, I can do this :D

should I directly raise a PR?
