### ISSUE TITLE
Outdated Reference to 0Chain

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [ethereum/ethereum-org-website#13324]
### Describe the bug

On the page https://ethereum.org/en/developers/docs/storage/, there is outdated information regarding the storage solution previously known as 0Chain. The current page still refers to it as 0Chain and provides a link to https://0chain.net/. However, 0Chain has rebranded to Züs, and the correct name and updated link should reflect this change.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/storage/
2. Look for the sections mentioning 0Chain.
3. Note that it still refers to 0Chain and links to https://0chain.net/

### Expected behavior

The page should accurately reflect the current name and link of the storage solution, which is now known as Züs, with the correct URL https://zus.network/

### Additional context

* The correct updated information should be:

    * Name : Züs
    * Link : https://zus.network/
* Reference to CoinMarketCap : [Zus on CoinMarketCap](https://coinmarketcap.com/currencies/0chain/)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @Shiva-Sai-ssb! Looks good, PR welcome, have assigned
