### ISSUE TITLE
Bug: ethereum-hero-light.mp4 path at `What is ETH?` page

### ISSUE THREAD

**Issue by saurabhburade** [ethereum/ethereum-org-website#13349]
### Describe the bug

At https://ethereum.org/en/eth/ page, there is a video above the heading `ETH fuels and secures Ethereum`. It has an inappropriate path to load that causes the not found error
`Failed to load resource: the server responded with a status of 404 ()`

It needs to be fixed by replacing paths
1.`images/ethereum-hero-light.mp4` to `/images/ethereum-hero-light.mp4`
2.`images/ethereum-hero-dark.mp4` to `/images/ethereum-hero-dark.mp4`

### To reproduce

1. Got to https://ethereum.org/en/eth/
2. Open the console and see the error `Failed to load resource: the server responded with a status of 404 ()`
3. We can see void space as a fallback above the heading `ETH fuels and secures Ethereum`

### Expected behavior

https://github.com/ethereum/ethereum-org-website/assets/39492927/53809a37-a0c7-4199-9839-ca2a19fd2276

### Screenshots

<img width="1509" alt="Screenshot 2024-07-07 at 6 38 56 PM" src="https://github.com/ethereum/ethereum-org-website/assets/39492927/35727acd-45ba-47cd-9047-12fd69c2be66">

### Desktop (please complete the following information)

- OS : MacOS 14.5
- Browser : Brave 1.66.115

### Additional context

This issue is mostly related to the unresolved public path for assets

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @saurabhburade. Assigned to you since you marked interested in working on this :)

**Comment by saurabhburade** [comment]
Hey @corwintines, thank you for assigning the issue. Please check the PR

**Comment by wackerow** [comment]
Closed with #13356

**Comment by Romansharar** [comment]
please help me with ethereum 100
