### ISSUE TITLE
Getting Ethereum Mastodon Listed

### ISSUE THREAD

**Issue by behradkhodayar** [ethereum/ethereum-org-website#1334]
As a non-profit project, I started Ethereum Mastodon(microblogging platform) under [Ethereum.blog.](https://ethereum.blog/)

Its newborn & it requires being noticed by new users. So it would be of great help to be listed under Ethereum's main website.

Any thoughts & plans on managing/directing it is also appreciated.

**Comment by samajammin** [comment]
Hey @behradkhodayar - thanks for your interest & for creating this issue.

Would you mind explaining the goals & value prop of Ethereum Mastodon? What are you trying to accomplish with this project? What unique value do you believe this will provide to the Ethereum community?

You can find the criteria we use to assess additions to the site here:
- https://ethereum.org/en/contributing/adding-products/
- https://ethereum.org/en/contributing/adding-articles/
At first glance, Ethereum Mastodon appears to be a mix of a product & article content, so I'm including both.

Cheers.

**Comment by behradkhodayar** [comment]
Hey Sam,

As you know I've been trying to translate the project last years, but left translation as I thought others may do it better & I can get involved in stuff that I may be better in doing that(maybe the code). This is one of those things: launching services around Ethereum.

weeks ago I found that there is a Mastodon for Bitcoin (Bitcoinhackers.org) & users joining in coz of some bad news & centralized attitude of Twitter. So I though it may be helpful to create a similar place for Ethereum community as well as funding it on my own as far as I can (& then community grant or so). Once users start joining it, we will end up having a network around everything Ethereum (that cannot be discussed in a Social Network manner at places such as Ethresear.ch).

In addition, I thinks its well adjusted to the "Groups and events" under "Education & community" at [Ethereum Ecosystem Wishlist](https://esp.ethereum.foundation/en/wishlist/).

I know moderation & content feeding would be tough & I'm not going to do it on my own, leaving it to the community. as it is a Non-profit from community for community.

Just wanted to share this w/ you before reading the links you (kindly) shared. I'll get back to you once assessed this service based on guidelines provided there.

**Comment by behradkhodayar** [comment]
@samajammin just reviewed the pages.

When considering Ethereum.blog a:

- **product**: Its neither a Wallet nor Dapp & of course not an Ethereum client. But based on common criterion, it is:
    - somehow inspirational: no other dedicated social network for Ethereum users
    -  not a good story
    - credible: from my POV & when I consider my intention!
    - easy to use
    - inoperable with other products: as a part of mastodon project
    - secure: OSS
    - not meeting longevity yet: its new born
    - an audited product: OSS
    - has been live for over 6 months: Its a Mastodon
    - Worked on by an active team: Sure it is
    - Easy onboarding
    - Open source
    - has an active community behind
    - uses on of the recommended hosting services by the Mastodon itself: Masto.host

- **article**:
    - Is the content up to date: sure it will be as its a microblogging platform by nature.
    - Is the information accurate? Is it factual or opinion-based?: B/C of being a social network, it will be opinion based but non-accurate ideas should be ignored by the community itself.
    - Is the author credible? Do they reference their sources?: It is a social network
    - Does this content add distinct value that existing resources/links don't cover?: It should definitely act like that.
    - Does this content serve one of our user personas: it will definitely serve the most (specially individuals).

I tried to be as specific as I can, but my point is that as a service that has never been before in Ethereum ecosystem, maybe its not the best way to assess it according to terms/factors listed on above links.

Anyway, thank you for time evaluating this case & I hope this can add value to the community.

**Comment by samajammin** [comment]
@ryancreatescopy please review when able. Thanks!

**Comment by behradkhodayar** [comment]
Thank you @samajammin

**Comment by ryancreatescopy** [comment]
Hi @behradkhodayar it doesn't look like there's any content right now.

![image](https://user-images.githubusercontent.com/40891631/90516600-24de2300-e15c-11ea-96f0-23683fa3b875.png)

I'm not sure the value prop is clear when you enter the site either, which I worry might confuse users. I think this is something we could be interested in listing once you've picked up some frequent users. We only want to list active products for our users – we're not an advertising platform to help you get users unfortunately. 

Let me know if I've misunderstood, but if not, please let us know once the product is fully up and running and we'll happily reconsider.

**Comment by behradkhodayar** [comment]
@ryancreatescopy sure, I see.
Thanks for your time & comment.

So, I'm gonna close the issue & reopen it once/if Ethereum users get interested in the product. Again, as it is a kinda non-profit project, I'm not sure if I can devote enough time marketing it, but I'll do my best.

cheers.
