### ISSUE TITLE
Update Aave logo

### ISSUE THREAD

**Issue by omahs** [ethereum/ethereum-org-website#13341]
### Describe the bug

Update Aave logo

### To reproduce

The Aave logo and branding have recently been updated, and our files should be revised in a few places, including this [page](https://ethereum.org/en/stablecoins/).

The new branding materials are available [here](https://github.com/aave-dao/aave-brand-kit/tree/main).

<img width="1455" alt="aave-logo" src="https://github.com/ethereum/ethereum-org-website/assets/73983677/93786a34-4f0a-4f01-a4dc-0f263b307c72">

### Expected behavior

The Aave logo and branding have recently been updated.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @omahs! Sounds good, PR welcome, have assigned
