### ISSUE TITLE
Bug report: inappropriate anchor links on GlossaryTooltip terms

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#13340]
### Describe the bug

Recently we updated the `/glossary` page where entries use the `GlossaryDefinition` component. With that we lost the anchor links for each glossary entry on `/glossary` and a patch was placed to fix this (#12455), _but_ now we're getting this on our glossary tooltips where hovering the term presents the hash link.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/data-and-analytics/ (or any page with a glossary tooltip term)
2. Hover over term
3. See tooltip popup, then hover over the term _within the tooltip_
4. Notice this is a hash link which does not work correct when clicked

### Expected behavior

When a term/definition is being displayed inside a `GlossaryTooltip` the term should not have a hash link.

### Screenshots

<img width="1345" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/c433850c-5c57-4262-86c8-fa9fdff235d0">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by arujjval** [comment]
@wackerow Just to be clear, are we expecting that instead of a hash link, the term inside the `GlossaryTooltip` should also have a tooltip pop-up?

**Comment by Dozie2001** [comment]
Please assign me to this

**Comment by wackerow** [comment]
Hm, oops! Appreciate the interest in helping out folks... realizing this bug seems to already be patched, but hasn't made it to production yet. I had only looked on production when filing.

https://dev--ethereumorg.netlify.app/en/developers/docs/data-and-analytics/ <- This is the same link as above but pointing to the `dev` build:

<img width="1535" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/f05c3fcc-0ee7-443a-8f8b-ff10e1357b79">

Can see here that this is no longer a link; going to close this issue out and can always reopen if we notice this resurface on `dev`.
