### ISSUE TITLE
The title of the table hardly seen in dark mode

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#13360]
### Describe the bug

Under [this section in portal networks](https://ethereum.org/en/developers/docs/networking-layer/portal-network/#how-does-portal-network-work), the title of the table at the bottom can hardly be seen in dark mode. In light mode or when clicked works fine. 

### To reproduce

1. Go to [How does portal network work](https://ethereum.org/en/developers/docs/networking-layer/portal-network/#how-does-portal-network-work)
2. Scroll down to the table at the bottom of the section
3. See error in dark mode

### Expected behavior

the title easily be seen in dark mode too

### Screenshots

![Screenshot 2024-07-09 at 08 46 33](https://github.com/ethereum/ethereum-org-website/assets/9151261/1ed3e070-e8b6-47ff-a5b5-10cfd11728c7)

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by Dipti0704** [comment]
i am interested to work on this issue kindly assign me this issue  @aslikaya

**Comment by Dipti0704** [comment]
i am interested to work on this issue kindly assign me this issue @wackerow

**Comment by wackerow** [comment]
Thanks @Dipti0704, assumed you

**Comment by Mrkhatana786** [comment]
i am interested to work on this issue kindly assign me this issue

**Comment by Dipti0704** [comment]
i will soon raise a pr @wackerow thanks

**Comment by minimalsm** [comment]
Hey @Dipti0704, any update here or should we open this up for other contributors?

**Comment by corwintines** [comment]
Ignore the energy consumption label, linked here by accident
