### ISSUE TITLE
Some abbreviations are lowercase

### ISSUE THREAD

**Issue by aslikaya** [ethereum/ethereum-org-website#13362]
### Describe the bug

Under [this section](https://ethereum.org/en/developers/docs/networking-layer/portal-network/#how-does-portal-network-work) some abbreviations like RAM and MB are written lowercase

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/networking-layer/portal-network/#how-does-portal-network-work
2. Scroll down to 'The benefits of this network design are:
3. See error "Accessible to resource-constrained devices (<1GB ram, <100mB disk, 1CPU)"

### Expected behavior

both RAM and MB should be capitalized

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @aslikaya, agree! PR welcome, assigning =)

**Comment by Dipti0704** [comment]
I am interested to work on this issue , kindly assign me this issue

**Comment by wackerow** [comment]
Appreciate the interest @Dipti0704... Giving @aslikaya preference as the original poster who requested to work on this. Still a young issue, so can always re-assign if needed down the line.
