### ISSUE TITLE
Bug report: find wallet language filter doesnt work

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13385]
### Describe the bug

the filter doesnt filter, fix bug.

When user clicks on the language filter, list isnt updated

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on any language filter
3. See error (wallets dont get filtered based on language)

<img width="346" alt="Screenshot 2024-07-12 at 22 12 54" src="https://github.com/user-attachments/assets/15624ff1-2edb-44de-90b3-14b93c66e70c">

### Expected behavior

wallets filtered

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MukulKolpe** [comment]
Hey @wackerow @konopkja, can I work on this issue?

**Comment by wackerow** [comment]
Thanks @MukulKolpe have assigned

**Comment by konopkja** [comment]
Hello, since this is our most popular page that gets hundreds of thousands of views daily, id urge to fix this this week. @MukulKolpe do you think you can manage?
