### ISSUE TITLE
Bug report: link styling on /stablecoins

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#13400]
### Describe the bug

The styling of titles within cards is incorrectly being displayed as a regular inline link. 

### To reproduce

1. Go to https://ethereum.org/en/stablecoins/
2. Scroll down to the product cards, ie Aave
3. See the styling of the titles inside the cards

### Expected behavior

Card styling handles the link; title styling should not be blue or underlined (regular styling should apply)

### Screenshots

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/2825e382-a347-4a3b-9b8d-cfe19058e826">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by krishchvn** [comment]
Hey. Can you assign the issue to me?

**Comment by HarshS1611** [comment]
Hey, I can work on this issue. Can you assign me?

**Comment by Shiva-Sai-ssb** [comment]
@wackerow
Looks like this issue has already been fixed. You can mark it as completed.

**Comment by wackerow** [comment]
Thanks for the interest folks. Resolved now, closing out
