### ISSUE TITLE
Replace ethereum.org's product roadmap URL on /about page

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#13401]
### Description

Replace current ethereum.org's product roadmap URL on [/about/#roadmap page](https://ethereum.org/en/about/#roadmap) to [Q3 2024 ethereum.org product roadmap](https://github.com/ethereum/ethereum-org-website/issues/13399). 

### To reproduce

1. Go to https://ethereum.org/en/about/#roadmap
2. Replace URL and copy: '[View our 2024 Q1 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/12005)' URL to ['View our 2024 Q3 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/13399)'

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Ekam-Bitt** [comment]
I would like to work on this issue

**Comment by krishchvn** [comment]
Hey. Can you assign the issue to me?

**Comment by isabelladebrito** [comment]
Thanks for the PR, @krishchvn! 

@Apocalypse96 this issue has been assigned already, but there are other good-first-issues available on https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 😃

**Comment by krishchvn** [comment]
Hi @isabelladebrito, I can see there is another issue that mentioned the same thing and it has been merged. Can you still merge this pr or abandon it?
