### ISSUE TITLE
Cypherock X1

### ISSUE THREAD

**Issue by JSKAkhil** [ethereum/ethereum-org-website#13412]
### Wallet name

Cypherock X1

### What type of wallet?

EOA

### Wallet description

Cypherock X1 is an audited cold wallet to store crypto and NFTs. Cypherock X1 currently supports 9000+ tokens across multiple networks. It can also be used as a wallet backup and portfolio aggregator for users' existing BIP39 compatible wallets.

### Wallet logo

![White_C_Text](https://github.com/user-attachments/assets/843fc01f-c5ff-4d97-a1e2-da07f83693b4)

### Background color for brand logo

#e3c675

### URL to the project

https://www.cypherock.com/

### When did the wallet go live to users?

2022

### What are the fees users may be paying for using your wallet product?

No fee for receiving and sending crypto as of now. Swapping, Bridging functionalities aren't available currently.

### Does the wallet have an active development team?

Yes. - https://github.com/orgs/Cypherock/repositories

### Is the wallet globally accessible?

Yes.

### Is the wallet available in multiple languages?

English, German, Chinese, Indonesian, Arabic

### What social links are there for the project?

Twitter (X) - https://x.com/CypherockWallet
LinkedIn - https://www.linkedin.com/company/cypherockwallet/
Telegram - https://t.me/cypherock

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Not yet.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes. The app name is "cySync".
OS supported by the app -
- Windows
- Linux
- Mac

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No.

### Is it a hardware wallet?

Yes. 
It broadcasts signed transactions through USB.

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

N/A

### Who holds the private keys?

Cypherock X1 is a non-custodial hardware wallet. Users generate their own seed phrases and they're are the only ones who have access to their private keys.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://docs.cypherock.com/security-overview/introduction

### Has the wallet's smart contract code or security modules been audited?

https://docs.cypherock.com/security-overview/keylabs-third-party-security-audit

### Does the wallet have an internal security team?

https://www.cypherock.com/about

### Any other security testing that should be noted?

https://docs.cypherock.com/design-decisions/cypherock-x1-hardware-architecture

### Scam protection?

As a first step towards making wallets more trustless and secure over time, Cypherock X1 cards have been designed to be unupgradable while ensuring that your Cypherock X1 is able to support new coins and features over time. It is important to recall that the Crypto private keys of the wallet are never stored in a singular place with Cypherock X1. The keys are cryptographically split into 5 Cryptographic parts and stored physically on the X1 Vault and the 4 X1 Cards. This ensures that hypothetically even if there is a malicious developer inside Cypherock, they will never be able to compromise the X1 cards remotely giving users a much stronger security model for their Crypto assets. - https://docs.cypherock.com/design-decisions/cypherock-x1-hardware-architecture/why-the-x1-cards-are-not-upgradeable
As an extra layer of security (to avoid scams), users must authenticate X1 cards and the vault device during setup - https://www.youtube.com/watch?v=4AE--wk3XT4&t=106s

### Does the wallet support connecting to Ethereum applications?

Users can connect to Ethereum applications and dApps using WalletConnect - https://www.youtube.com/watch?v=R0g35dKjRtI

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Not yet

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

Not currently.

### Does the wallet support swaps directly?

Not currently.

### Does the wallet support bridging directly?

Not currently.

### Does the wallet support multi-chain networks?

Yes - https://www.cypherock.com/coin-support

### Does the wallet support Ethereum layer 2 networks?

Yes. - https://www.cypherock.com/coin-support

### Does the wallet allow the user to customize gas fees?

No bridging and swapping functionalities currently.

### Does the wallet support sending transactions to ENS addresses?

Not yet

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes.

### Does the wallet have any recovery options?

PIN recovery - Cypherock Cover offers a hardware-based service designed for PIN loss and inheritance of digital assets. Built upon the Cypherock X1 hardware wallet and Shamir’s Secret Sharing, it ensures enhanced security. For PIN recovery, encrypted reminders via email enable access even if forgotten. Inheritance features allow designated nominees to receive encrypted instructions in case of user inactivity, using Cypherock X1 cards and encrypted PIN for secure asset retrieval. You can read how it works [here](https://www.cypherock.com/blogs/cypherock-cover).

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Not currently.

### Does the wallet support withdrawals to fiat?

Not currently.

### Is the wallet a multi-signature wallet?

No, it's Shamir Secret Sharing based wallet. 

### Does the wallet support social recovery?

Not yet. Non custodial inheritance feature "Cypherock Cover" has been announced. It will be released in Q3 2024 - https://www.cypherock.com/blogs/cypherock-cover

### Does the wallet support bundled transactions?

Not yet for ETH. Yes - For BTC.

### Who can the ethereum.org team can contact regarding the wallet in future?

Rohan Agarwal - Telegram - @rohanagarwal7
Email ID - support@cypherock.com

### Does the wallet have a dedicated support team?

Yes. Users can email support@cypherock.com. They will receive a response in 24 business hours. 

### What educational resources/documentation do you provide to users?

User documentation - https://docs.cypherock.com/
Educational resources - https://www.cypherock.com/blogs, https://www.youtube.com/@CypherockWallet/playlists. 
Developer documentation - https://github.com/Cypherock

### Does the wallet have any integrated tools not mentioned above?

- Four hardware wallets in one wallet.
Unlike other hardware wallets where you get one wallet account per hardware, you can create 4 different wallet accounts in a single Cypherock X1. Use one wallet account for storing NFTs and maybe use another one for storing just ETH etc. 

- Use it as vault to secure other seed phrases.
No more insecure wallet backup solutions like a paper or metal plate. Cypherock X1 can also function as a Seed Phrase backup for your other Crypto wallets.

- No more losing crypto in case something happens to you. Introducing Cypherock Cover - Non custodial inheritance feature. 
You have to safeguard your Crypto while you are alive and only transfer them after you are dead which is impossible if you are the only one knowing your keys. Cypherock eliminates fear around loss of Crypto in case you die. With our beneficiary feature, the assets can be transferred without Cypherock or any other party ever knowing the amount you HODL in the X1 Vault (Go Privacy!) or controlling the assets.

- Manage all of your crypto portfolio in a single place.
Do you have your Crypto assets scattered over in different wallets and find it difficult to track everything? Manage them today all in CySync desktop app by storing the seed phrases into the Cypherock X1.

- Stress-free wallet updates. Other wallets can steal your funds. Cypherock can't.
Your X1 Cards which stores your Crypto are never upgradable and remains cold at all times. Hence your keys are always safe even if you add a new coin on your X1 Vault device.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @JSKAkhil! Have self assigned for review; bear with us in the meantime 🙏

**Comment by konopkja** [comment]
hello @JSKAkhil  can you share with us which Ethereum rollup networks does the wallet natively support in the UI?

**Comment by JSKAkhil** [comment]
hey @konopkja - Rollup networks on Ethereum - Arbitrum, Optimism, Starknet (in progress). Cypherock also supports other EVM chains like Polygon, Fantom Opera, Avalanche C-Chain, Optimism, Arbitrum One, BSC (EVM compatible).

**Comment by JSKAkhil** [comment]
hello @konopkja Is there anything else I can help you with?

**Comment by konopkja** [comment]
lgtm cc @corwintines  @wackerow

**Comment by JSKAkhil** [comment]
Hello @konopkja @chuyeow @wackerow any updates on this please? When can we expect this to go live? Thanks for your time.

**Comment by konopkja** [comment]
> Hello @konopkja @chuyeow @wackerow any updates on this please? When can we expect this to go live? Thanks for your time.

Hi @JSKAkhil I see in the issue you signalled that you are willing to work on this - that means you can submit a Pull request with modifications to include this wallet on our website.  

Do you want to do that yourself? If so you can proceed.

**Comment by JSKAkhil** [comment]
@irshadjsr21 pls look into this.

**Comment by JSKAkhil** [comment]
@irshadjsr21 , pls look into this.

**Comment by JSKAkhil** [comment]
> > Hello @konopkja @chuyeow @wackerow any updates on this please? When can we expect this to go live? Thanks for your time.
> 
> Hi @JSKAkhil I see in the issue you signalled that you are willing to work on this - that means you can submit a Pull request with modifications to include this wallet on our website.
> 
> Do you want to do that yourself? If so you can proceed.

We have raised the PR. Thanks @konopkja

**Comment by JSKAkhil** [comment]
> > Hello @konopkja @chuyeow @wackerow any updates on this please? When can we expect this to go live? Thanks for your time.
> 
> Hi @JSKAkhil I see in the issue you signalled that you are willing to work on this - that means you can submit a Pull request with modifications to include this wallet on our website.
> 
> Do you want to do that yourself? If so you can proceed.

PR raised and issues fixed. Please let me know if there is anything else required from our end.

**Comment by konopkja** [comment]
fees:
€149.00 to buy the device

L2s supported:
Optimism, Arbitrum,
