### ISSUE TITLE
fix event tracking: wallet page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13420]
### Is your feature request related to a problem? Please describe.

currently there is missing event tracking on one button and also other tracking should be changed on https://ethereum.org/en/wallets/

### Describe the solution you'd like

![Screenshot 2024-07-18 at 16 44 31](https://github.com/user-attachments/assets/f3dfb1e7-95c2-4710-a96e-5f11ca9dce86)

the two buttons on the image above (in the header of the page) are missing event tracking.

Event Category
Header buttons

Event Action 
click

Event Name
Find_wallet
How_to_use_wallet

![Screenshot 2024-07-18 at 16 46 35](https://github.com/user-attachments/assets/48848862-e3b8-40e0-bbcf-f7ac1ae329f6)

these two buttons tracking should be changed not to use "value"

**Original**
Event Category 
Link

Event Action
Clicked
Event Name

Clicked on internal link
Event Value 
/guides/how-to-create-an-ethereum-account/

**Change to**
Event Category 
Link

Event Action
Clicked

Event Name
Create_eth_acc
How_to_use_wallet

![Screenshot 2024-07-18 at 16 49 23](https://github.com/user-attachments/assets/e26bd0c5-12e3-4551-8023-a298153a09a8)

**Same issue here and the existing tracking should be changed**

**Change to**
Event Category 
Link

Event Action
Clicked_external

Event Name
protecting_yourself
the_keys_to_keeping_crypto_safe

### Describe alternatives you've considered

NA

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MahendraBishnoi29** [comment]
assign it to me @wackerow

**Comment by rohitt-gupta** [comment]
@konopkja @corwintines  Created a PR for the same,
Please check/review and merge it.
Let me know if you need any help regarding this PR

**Comment by MahendraBishnoi29** [comment]
> @konopkja @corwintines Created a PR for the same, Please check/review and merge it. Let me know if you need any help regarding this PR

@rohitt-gupta I'm already working on this issue, please check that if someone has been assigned for the issue or not before contributing :)

@wackerow @corwintines

**Comment by corwintines** [comment]
@rohitt-gupta as mentioned, if someone is assigned please don't snipe it from them

I will review it for now since its the only open PR. @MahendraBishnoi29 not sure your progress here and if you are close, I will favor yours.
