### ISSUE TITLE
Bug report: UI on find-wallet

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13421]
### Describe the bug

Based on UXR we have noticed that people might not be aware that there are multiple personas to select from on mobile device.

The issue is because visually it looks like there are only two options.

### To reproduce

1. use mobile device
2. Go to https://ethereum.org/en/wallets/find-wallet/
3. Scroll down to persona selection

### Expected behavior

Currently there is **empty space from right side of persona**  which misleads users thinking there are only two options
![IMG_107FF554C0C5-1](https://github.com/user-attachments/assets/918f14b9-57d7-417c-9846-84948e803a7a)

![IMG_107FF554C0C5-1](https://github.com/user-attachments/assets/63e4d436-a077-417b-9ca1-f7a0e03fbbf3)

Expected behavior
1. overflow the wrapper till the end of the screen like this and have no empty space on the right side
![Screenshot 2024-07-18 at 17 25 53](https://github.com/user-attachments/assets/07abe2bb-1205-421a-9c33-1ef137ae6e97)

2. Show scrollbar at the bottom of the component by default
<img width="455" alt="Screenshot 2024-07-18 at 17 28 18" src="https://github.com/user-attachments/assets/82a9889f-5191-4840-b7cc-a5707a388ae9">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by nipunh** [comment]
@konopkja Can you please assign this issue to me?

**Comment by konopkja** [comment]
> @konopkja Can you please assign this issue to me?

Assigned you the issue! Thank you :)
