### ISSUE TITLE
Refactor Link component: cleanup deprecated `to` prop

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#13423]
## Description

The `to` prop in the Link component [is marked as deprecated](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Link.tsx#L23).

TODO:
- Replace all the instances where we are using `to` with `href`.
- Remove the `to` prop from the Link component.

**Comment by jackabald** [comment]
Hey!

I want to take a stab at this issue. Is anyone working on this?

**Comment by pettinarip** [comment]
@jackabald assigned to you, thanks!

**Comment by jackabald** [comment]
@pettinarip Do you want all references to the 'to' prop to be removed? I'm finding instances of 'to' being used for <DocLink> and <ButtonLink>. Should it be replaced here as well?

Thanks!
