### ISSUE TITLE
Maximum Extractable Value (MEV)

### ISSUE THREAD

**Issue by JoshDavisLight** [ethereum/ethereum-org-website#13431]
### Checklist

- [X] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [X] This term/definition is not a product advertisement or contain other promotional content
- [X] This term/definition is directly relevant to Ethereum

### Term name

Maximum Extractable Value (MEV)

### Term definition

Maximal extractable value (MEV) refers to the maximum value that can be extracted from block production in excess of the standard block reward and gas fees by including, excluding, and changing the order of transactions in a block.

### Sources, if any (please do not submit copyrighted content without appropriate approval)

https://ethereum.org/en/developers/docs/mev/

### Ethereum.org links

https://ethereum.org/en/developers/docs/mev/

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
Looks good @JoshDavisLight, would you be interested in being assigned for a PR?
