### ISSUE TITLE
ETH Shenzhen Event listing

### ISSUE THREAD

**Issue by jueduizone** [ethereum/ethereum-org-website#13446]
### Event/Meetup Name

ETH Shenzhen

### Website

https://ethshenzhen.org

### Location (City/Country, or Remote)

Shenzhen

### Description

The Shenzhen Ethereum Developer Conference and Hackathon is a premier event designed to connect, inspire, and educate developers from the Guangdong-Hong Kong-Macao Greater Bay Area and beyond.

### Start date: (yyyy-mm-dd)

2024-08-16

### End date: (yyyy-mm-dd)

2024-08-18

### Additional context

Twitter Announcement: https://x.com/OpenBuildxyz/status/1813596587844927883

### Would you like to work on this issue?

- [X] Yes

**Comment by wackerow** [comment]
Thanks @jueduizone, assigned!
