### ISSUE TITLE
Make the process of adding exchanges clearer

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1346]
**Is your feature request related to a problem? Please describe.**

We need to improve the process of users suggesting new exchanges so that we have the required information to list them accurately on our site. 

**Describe the solution you'd like**

- [x] Create GitHub issue template for adding exchanges
- [x] Link users to GitHub issue template from /get-eth page
- [x] Add exchange policy to contributing section

**Comment by samajammin** [comment]
Solved in #1345
