### ISSUE TITLE
Suggest a wallet: Ctrl Wallet (fka XDEFI Wallet)

### ISSUE THREAD

**Issue by sean-mc-grath** [ethereum/ethereum-org-website#13467]
### Wallet name

Ctrl Wallet

### What type of wallet?

EOA

### Wallet description

One wallet for all your assets. Multichain wallet that displays all assets and NFTs on 200+ networks. 

### Wallet logo

![App Icon Black](https://github.com/user-attachments/assets/d3e0733c-6ce6-45ea-a70c-ad393e75ee83)

### Background color for brand logo

#FFFFFF

### URL to the project

https://ctrl.xyz/

### When did the wallet go live to users?

XDEFI has been live since 2020, Ctrl rebrand will be live in September 2024

### What are the fees users may be paying for using your wallet product?

No fees on general usage or transactions. 
0.3% fee on in-app swaps & bridges, with discounts for token holders.

### Does the wallet have an active development team?

Yes. https://github.com/XDeFi-tech/ctrl-extension/

### Is the wallet globally accessible?

Globally accessible everywhere crypto is legal.

### Is the wallet available in multiple languages?

Currently available in English with more languages coming soon.

### What social links are there for the project?

https://discord.gg/ctrlwallet
https://x.com/ctrl_wallet
https://t.me/ctrl_wallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, iOS & Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

N/A

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, Chromium

### Is it a hardware wallet?

No

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

This project is licensed under the Apache-2.0 License.

### Who holds the private keys?

Ctrl is a self-custody wallet, we never have access to users private keys. Users have full control over their keys.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Security audit by FYEO currently underway.
Previously [audited by Kudelski Security](https://www.xdefi.io/wp-content/uploads/2021/07/XDEFI_Audit_Report_Kudelski.pdf).

### Has the wallet's smart contract code or security modules been audited?

https://www.xdefi.io/wp-content/uploads/2021/07/XDEFI_Audit_Report_Kudelski.pdf

### Does the wallet have an internal security team?

No

### Any other security testing that should be noted?

N/A

### Scam protection?

Yes, integrations with a number of third party security providers, covering:
- Malicious domain detection and warning
- Malicious address scanning
- Transaction simulation
- Transaction and message signing risk analysis

### Does the wallet support connecting to Ethereum applications?

Extension: connect wallet to dapp directly, Mobile: WalletConnect

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

Yes: https://docs.xdefi.io/docs/general/routing

### Does the wallet support bridging directly?

Yes: https://docs.xdefi.io/docs/general/routing

### Does the wallet support multi-chain networks?

Yes. 36 chains natively + hundreds more possible to add by the user. https://docs.xdefi.io/docs

### Does the wallet support Ethereum layer 2 networks?

Yes: https://docs.xdefi.io/docs

### Does the wallet allow the user to customize gas fees?

Yes: 

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have any recovery options?

Recovery via:
- Recovery Phrase
- Private Key
- Hardware Wallet import
- Social Log Ins (web3auth)
- JSON back up

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

Yes

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

Yes: web3auth integrated

### Does the wallet support bundled transactions?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

https://discord.gg/ctrlwallet
https://x.com/ctrl_wallet
https://t.me/ctrl_wallet

### Does the wallet have a dedicated support team?

Yes, support available via discord or intercom on the website.
Dedicated support team available almost 24/7 with very fast response (less than 30 mins)

### What educational resources/documentation do you provide to users?

User support: https://intercom.help/ctrlwallet/en/
Developer support: https://docs.xdefi.io/docs

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by konopkja** [comment]
Does the wallet support Ethereum layer 2 networks?
Arbitrum
Ethereum
Optimism
Custom EVM

**Comment by konopkja** [comment]
whoever makes the PR, please also update last time updated metadata

**Comment by sean-mc-grath** [comment]
@konopkja yes Ctrl supports Arbitrum & Optimism natively, and all EVMs are possible to be added as custom networks.

**Comment by wackerow** [comment]
@konopkja Have you been able to review this yet? If so just go ahead and update labels  (remove "needs product review", add "awaiting PR, help wanted, good first issue") and remove yourself from assignment. Thanks!

@sean-mc-grath Was this something you wanted to implement if/when ready for a PR?

**Comment by sean-mc-grath** [comment]
Hey @wackerow , sorry not sure what the question is, let me know if there's any other actions I need to take to get the listing approved and live?

**Comment by wackerow** [comment]
@sean-mc-grath No action now, I'm just checking with @konopkja to see if he's finished with any reviews of Ctrl Wallet since this is a new listing...

Once approved, we'll just need someone to implement the updates. Is this something you'd like to be assigned to handle when the time comes, or would you prefer someone else to make the actual code adjustments?

**Comment by sean-mc-grath** [comment]
Thanks @wackerow , if possible would be great to have somebody on your side make the code adjustments, I'm not a dev so better to leave it to somebody with the expertise

**Comment by wackerow** [comment]
Sounds good @sean-mc-grath! Thanks for letting us know, will handle it

**Comment by 0xshikhar** [comment]
Hey @konopkja , would like to work on this task. Could you clarify the remaining tasks for this issue? Any additional context would be appreciated. Thanks!

**Comment by konopkja** [comment]
> Hey @konopkja , would like to work on this task. Could you clarify the remaining tasks for this issue? Any additional context would be appreciated. Thanks!

create PR with changed metadata for this particular wallet here https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/wallets/wallet-data.ts 

want to do that?

**Comment by konopkja** [comment]
<img width="1148" alt="Screenshot 2024-10-30 at 10 09 40" src="https://github.com/user-attachments/assets/3acabd8f-8684-4b8c-b6c5-d1a8be20866b">

hi @sean-mc-grath  - can you please elaborate on why the extension has not been renamed and why there is a warning for users? when is this going to be updated?

**Comment by konopkja** [comment]
furthermore, @sean-mc-grath  i see you indicated that the app has android and ios versions, but i see the links on the website for those disabled

**Comment by konopkja** [comment]
this link https://github.com/XDeFi-tech/ctrl-extension/ shows 404

**Comment by sean-mc-grath** [comment]
Hey @konopkja , the migration from XDEFI to Ctrl is currently in progress - the XDEFI extension is still live for now, and the warning is as it is not updated to MV3 per Google guidelines. The Ctrl extension is MV3 compatible, and will migrate fully in production for all users by mid-November. You can find more details here: https://ctrl.xyz/xdefi-wallet-rebranding-to-ctrl/ & https://ctrl.xyz/news/manifest-v3/

Both Ctrl extension and mobile apps are available for beta testing, if helpful please let me know your email (associated with chrome for extension) and I can add you to beta group to download and review

**Comment by konopkja** [comment]
> Hey @konopkja , the migration from XDEFI to Ctrl is currently in progress - the XDEFI extension is still live for now, and the warning is as it is not updated to MV3 per Google guidelines. The Ctrl extension is MV3 compatible, and will migrate fully in production for all users by mid-November. You can find more details here: https://ctrl.xyz/xdefi-wallet-rebranding-to-ctrl/ & https://ctrl.xyz/news/manifest-v3/
> 
> Both Ctrl extension and mobile apps are available for beta testing, if helpful please let me know your email (associated with chrome for extension) and I can add you to beta group to download and review

ok so should we rebrand already on https://ethereum.org/en/wallets/find-wallet/ your listing or wait till december?

**Comment by sean-mc-grath** [comment]
We are happy for it to be rebranded now already yes so it is ready in advance, thanks
