### ISSUE TITLE
Update: Ambire Wallet

### ISSUE THREAD

**Issue by dmngdsm** [ethereum/ethereum-org-website#13470]
### Wallet name

Ambire Wallet

### What type of wallet?

Account Abstraction

### Wallet description

Ambire Wallet is a Web3 wallet that makes self-custody easy and secure for everyone.
Ambire provides secure smart accounts (based on account abstraction & ERC-4337) that can be authenticated via hardware wallets or in-browser keys and optional email recovery.
It's available as browser extension (Chromium and Firefox), mobile apps (iOS and Android) and as a web platform.

### Wallet logo

https://github.com/AmbireTech/ambire-brand/blob/main/Media%20Kit/Logo/logo-hor-mono-white.png

### Background color for brand logo

#6000FF

### URL to the project

www.ambire.com

### When did the wallet go live to users?

Dec 16, 2021

### What are the fees users may be paying for using your wallet product?

0.5% on internal swaps

### Does the wallet have an active development team?

https://github.com/AmbireTech

### Is the wallet globally accessible?

No limitations

### Is the wallet available in multiple languages?

The interface is currently in English only

### What social links are there for the project?

- https://x.com/AmbireWallet
- https://discord.com/invite/ambire
- https://t.me/AmbireOfficial
- https://t.me/AmbireWalletAnnouncements

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Ambire Wallet is officially available on both iOS and Android since Jul 27, 2023:
https://play.google.com/store/apps/details?id=com.ambire.wallet&hl=en&gl=US
https://apps.apple.com/us/app/ambire-smart-crypto-wallet/id6444863857

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Ambire doesn't have a dedicated desktop app, but its Web version makes it available on various devices and operating systems.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

The browser extension version is currently in its final stage of development and is already available for closed-group beta testing via invite code.
Ambire Extension supports Chromium-based browsers and Firefox.

### Is it a hardware wallet?

No

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

GNU General Public License Version 3, 29 June 2007  

### Who holds the private keys?

Users

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

With Ambire Wallet, users can rest assured that their digital assets are safeguarded by a robust security model built on careful development practices, transparency, advanced security through account abstraction, rigorous auditing, and proactive bug bounty initiatives.
https://help.ambire.com/hc/en-us/articles/4411180546834

### Has the wallet's smart contract code or security modules been audited?

Both currently used and previously used contracts are audited. Information for the audits for the current contracts: https://github.com/AmbireTech/ambire-common/tree/v2/audits Information for the previous: https://github.com/AmbireTech/ambire-wallet/blob/main/contracts/audits/Certik.pdf and https://github.com/AmbireTech/adex-protocol-eth/blob/master/audits/Ambire%20Contest%20%E2%80%94%20Code%20423n4.pdf

### Does the wallet have an internal security team?

No

### Any other security testing that should be noted?

All listed 

### Scam protection?

Ambire Wallet relies on multiple levels for scam protection:
1) dApp catalog—a list of pre-selected, popular dApps that ensures the user connects with the real, not a fake one. The user can customize its dApp catalog by adding or removing dApps.
2) Humanized transactions. On all of its platforms, Ambire Wallet "translates" the interaction with the network and informs the user of what he is about to sign.
3) On-chain transaction simulation—A transaction (or batch of transactions) is simulated before it is signed, so the user can see in advance how it will affect his assets.

### Does the wallet support connecting to Ethereum applications?

Yes, via Injected Wallets (for extension and mobile apps), plus WalletConnect 2.0 and Gnosis Safe App SDK (for Web platform)

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

The upcoming Ambire extension supports changing of the RPC endpoints.

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

On the Web platform, via integration of AAVE

### Does the wallet support swaps directly?

Yes, via integration of Uniswap

### Does the wallet support bridging directly?

 Yes, integrated cross-chain swaps provided by Socket

### Does the wallet support multi-chain networks?

By default, the Ambire extension supports 7 EVM networks, but users can add any other EVM network.  Web and mobile platforms support 11+ EVM networks

### Does the wallet support Ethereum layer 2 networks?

The web and mobile wallets currently support: 
Optimism, Base, Arbitrum, Metis, Scroll

### Does the wallet allow the user to customize gas fees?

Users can speed up transactions

### Does the wallet support sending transactions to ENS addresses?

Yes. Ambire Wallet supports sending transactions to ENS, Unstoppable domains, and locally stored address books.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

 Yes. By default, Ambire Wallet supports any token listed in CoinGrecko. If users deposit a token that is not supported by default, they can manually add its contract address, and make it available in the dashboard.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have any recovery options?

Yes.
Email/password accounts on the Web and mobile platforms can be recovered in case one of the keys is lost, as they are 2-out-of-2 signer accounts.
Other types of accounts on those platforms allow users to add back-up signers (web or hardware wallets).
The upcoming extension will use a new model for recovery, which can be activated for one or a group of accounts - via email recovery or email vault (Authentication via DKIM), for which the team won a grant from the Ethereum Foundation.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Fiat on-ramps (deposits) are available via third parties, integrated in the wallet - Guardarian, MoonPay, RAMP, PayTrie.

### Does the wallet support withdrawals to fiat?

Withdrawals to fiat from Ambire Wallet are available via third parties, integrated in the wallet - Guardarian, MoonPay, or swappin.gifts

### Is the wallet a multi-signature wallet?

Only email/password type of accounts uses 2-out-of-2 signers. Users can add and replace signers, but they are not working as multi-signature. Each signer can be invalidated at any time if you're authorized with one of the other ones, and a new signer can be added at any time.

### Does the wallet support social recovery?

 No, but such a type of recovery can be added in the future.

### Does the wallet support bundled transactions?

Yes. It has supported bundled (batched) transactions since its official release.

### Who can the ethereum.org team can contact regarding the wallet in future?

ivan@ambire.com
Twitter: @vanzooeth
Telegram: @vanzooeth

### Does the wallet have a dedicated support team?

Yes, Support team can be reached at https://help.ambire.com/hc/en-us. Tickets are replied within a few hours usually.

### What educational resources/documentation do you provide to users?

Editorial team of Ambire Wallet provides various articles, from product updates, tutorials dedicated to Ambire Wallet to general educational articles.
Educational blog articles: https://blog.ambire.com/tag/learn/
Product updates: https://blog.ambire.com/tag/product-updates/
Help center: https://help.ambire.com/hc/en-us
Whitepaper: https://ambire.notion.site/Ambire-Wallet-Whitepaper-d502e54caf584fe7a67f9b0a018cd10f

### Does the wallet have any integrated tools not mentioned above?

Gas Tank - Feature that enables Ambire Wallet users to pre-pay for gas fees with native and stablecoins, which can be used across all the networks, supported by Ambire Wallet. For example DAI deposited on Polygon to be used to pay gas fees on BASE, Scroll networks, or any other of the supported networks.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by konopkja** [comment]
This is submission upon request for updated info. Whoever makes the PR, please update the wallet update date metadata as well

**Comment by dmngdsm** [comment]
> Which L2 rollups are natively supported in ambire?

Updated the issue with currently natively supported networks

**Comment by minimalsm** [comment]
@dmngdsm would you be able to open a PR to update?

thanks :)!

**Comment by dmngdsm** [comment]
> @dmngdsm would you be able to open a PR to update?
> 
> thanks :)!

Can you help with this one? Not sure where this information is supposed to go, hence the PR

**Comment by konopkja** [comment]
> > @dmngdsm would you be able to open a PR to update?
> > thanks :)!
> 
> Can you help with this one? Not sure where this information is supposed to go, hence the PR

https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/wallets/wallet-data.ts
