### ISSUE TITLE
Wallet Info Update: OneKey

### ISSUE THREAD

**Issue by PatrickChoo** [ethereum/ethereum-org-website#13488]
### Wallet name

OneKey

### What type of wallet?

EOA

### Wallet description

Open source app and hardware wallet. Backed by Coinbase Ventures, Dragonfly Capital and Ribbit Capital.

### Wallet logo

![OneKey](https://github.com/user-attachments/assets/234f5b30-54cd-415f-860d-c0c191270d0d)

### Background color for brand logo

#fff

### URL to the project

https://onekey.so

### When did the wallet go live to users?

2019

### What are the fees users may be paying for using your wallet product?

0.3% fee for swap, bridge transactions

### Does the wallet have an active development team?

https://github.com/OneKeyHQ/app-monorepo

### Is the wallet globally accessible?

YES

### Is the wallet available in multiple languages?

- English
- Bengali
- Chinese Simplified
- Chinese Traditional (Taiwan)
- Chinese Traditional (Hong Kong)
- French
- German
- Hindi
- Indonesian
- Italian
- Japanese
- Korean
- Portuguese
- Portuguese (Brazil)
- Russian
- Spanish
- Thai
- Ukrainian
- Vietnamese

### What social links are there for the project?

Twitter
https://x.com/onekeyhq

Bitly LinkPage
https://bit.ly/m/onekey

Instagram
https://www.instagram.com/onekeyhq/

Youtube
https://www.youtube.com/@onekeyhq

Github
https://github.com/onekeyhq

Discord
https://discord.gg/onekey

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

- iOS
- Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

- Windows
- Mac
- Linux

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Chromium
- Chrome
- Edge
- Brave

### Is it a hardware wallet?

OneKey App can directly create a hot wallet and can also be used with the OneKey hardware wallet. Different models have different connection methods.

- OneKey Mini - USB
- OneKey Classic - USB, Bluetooth
- OneKey Classic 1S - USB, Bluetooth
- OneKey Touch - USB, Bluetooth
- OneKey Touch - USB, Bluetooth, QR Code

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

https://github.com/OneKeyHQ/app-monorepo/blob/x/LICENSE.md

### Who holds the private keys?

• Recovery phrase and private keys are generated locally and users are reminded to back them up. These are retained by the users, and if kept securely, no one else can access the recovery phrase or private keys.
• Using the BIP44 standard, even if this project or company shuts down, users can still access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Collaboration with Slowmist for code auditing.

Bug bounties have been announced on Bugrap:
https://bugrap.io/bounties/OneKey

### Has the wallet's smart contract code or security modules been audited?

Yes. The app and hardware wallet code audit report will be released soon.

### Does the wallet have an internal security team?

Yes. We have dedicated security engineers.

### Any other security testing that should be noted?

We engage professional security firms to perform annual security audits of our codebase. All external dependencies are version-locked and will only be updated when absolutely necessary. Each time an update to external dependencies is made, our Security Engineers thoroughly review the changes to ensure there is no malicious code.

### Scam protection?

- Risk detection for websites, addresses, tokens, transactions
- Check if the user's account has ever made a transfer to the counterpart address

### Does the wallet support connecting to Ethereum applications?

Yes, you can use WalletConnect to connect dApps on desktop or mobile, or connect to dApps directly in the desktop browser, as well as connect to dApps on the Extension.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

https://help.onekey.so/hc/articles/9280841182479

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

https://help.onekey.so/hc/articles/6493962872207

### Does the wallet support swaps directly?

https://help.onekey.so/hc/articles/10125064370319

### Does the wallet support bridging directly?

https://help.onekey.so/hc/articles/10125064370319

### Does the wallet support multi-chain networks?

https://onekey.so/cryptos/

### Does the wallet support Ethereum layer 2 networks?

https://onekey.so/cryptos/

### Does the wallet allow the user to customize gas fees?

https://help.onekey.so/hc/articles/9379019495823

### Does the wallet support sending transactions to ENS addresses?

https://help.onekey.so/hc/articles/9159188814863

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

https://help.onekey.so/hc/articles/8455836685967

### Does the wallet support EIP-1559 (type 2) transactions?

https://onekey.so/eips/

### Does the wallet have any recovery options?

In OneKey, you can use a 12, 15, 18, 21, or 24-word recovery phrase for wallet restoration, supporting BIP44 and Ledger Live account recovery. 

It also supports OneKey recovery phrase backup kit products, including OneKey KeyTag and OneKey Lite, for wallet recovery.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

https://help.onekey.so/hc/articles/10303614485135

### Does the wallet support withdrawals to fiat?

https://help.onekey.so/hc/articles/10303614485135

### Is the wallet a multi-signature wallet?

No.

### Does the wallet support social recovery?

No.

### Does the wallet support bundled transactions?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

Twitter: onekeyhq
Email: patrick@onekey.so

### Does the wallet have a dedicated support team?

Yes. For any question please submit a ticket: hi@onekey.so
We will reply your ticket 

### What educational resources/documentation do you provide to users?

OneKey - Help Center
https://help.onekey.so

Submit a ticket
hi@onekey.so

### Does the wallet have any integrated tools not mentioned above?

- Token Bulk transfer
- Exchange to other L1 chains like Bitcoin, Solana, Aptos and more

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by konopkja** [comment]
L2 rollups supported based on the website:
Arbitrum
Optimism
ZKsync era
Base
Linea
blast

**Comment by konopkja** [comment]
Thank you @PatrickChoo  for submission!  lgtm!
