### ISSUE TITLE
Bug report: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by HiroyukiNaito** [ethereum/ethereum-org-website#13482]
### Describe the bug

NEXT button in https://ethereum.org/en/developers/docs/smart-contracts/ page causes "ERR_TOO_MANY_REDIRECTS" error.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/smart-contracts/
2. Click on NEXT button
3. See error ERR_TOO_MANY_REDIRECTS

### Expected behavior

Go to NEXT page "Smat contract languages"

### Screenshots

![image](https://github.com/user-attachments/assets/6ad92ba6-1722-43c4-b6a2-f29439931127)

### Desktop (please complete the following information)

- Chrome Version 126.0.6478.183 (Official Build) (64-bit)
- Firefox 128.0.2 (64 bit)
- Edge Version 126.0.2592.113 (Official build) (64-bit)

### Additional context

No relevant to the environment.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by kohantikanath** [comment]
Hi @HiroyukiNaito ,
 I would love to work on this, can you assign me this issue?

**Comment by HiroyukiNaito** [comment]
@kohantikanath I'm afraid I don't have the permission to assign.
@wackerow  Please assign this issue to @kohantikanath .

**Comment by HiroyukiNaito** [comment]
Related issue   https://github.com/ethereum/ethereum-org-website/pull/12686/files

**Comment by kohantikanath** [comment]
Thanks @HiroyukiNaito. @wackerow , I'm ready to work on this if you can assign it to me. I'll review the related PR in the meantime. Let me know if you need any info from me.

**Comment by wackerow** [comment]
Hey, thanks for reporting.. this is a known issue with the `languages` paths (the Next button in the example goes to a path ending in `/languages`)

- #13192

@corwintines currently assigned, with PR #13193 pending. Going to close this one out as a duplicate.
