### ISSUE TITLE
UI Bug report: missing padding around button

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13498]
### Describe the bug

https://ethereum.org/en/get-eth/ missing padding

### To reproduce

1. Go to https://ethereum.org/en/get-eth/
2. Scroll down to "What are DEXs?"
3. See error

### Expected behavior

add 32px padding

### Screenshots

![Screenshot 2024-07-26 at 12 17 46](https://github.com/user-attachments/assets/2d834ab5-94d8-4a2c-b68b-288d7f89a43d)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by sanjanaynvsdl** [comment]
Hey, @konopkja I would like to work on this issue can you please assign this to me!

**Comment by konopkja** [comment]
Hi, assigned - thank you!

**Comment by sanjanaynvsdl** [comment]
Hey @konopkja , 
I have created a  [PR](https://github.com/ethereum/ethereum-org-website/pull/13509) to address this issue. Please review it at your convenience.

**Comment by wackerow** [comment]
Fixed with #13509
