### ISSUE TITLE
Quizzes: change "scaling" quiz metadata from "Intermediate" -> "Advanced"

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13500]
Go to https://ethereum.org/en/quizzes/
Scroll to Using Ethereum
See "Scaling"

This quiz uses advanced terminology and discusses very advanced topics, users who might click on this quiz might be expecting much easier content then there in reality is.

As a result they might feel a bit demotivated seeing all this jargon. 

**Solution**
- change the label to "advanced"

![Screenshot 2024-07-26 at 12 33 35](https://github.com/user-attachments/assets/3d552af2-b599-42f4-bf58-050db94ef61d)

**Comment by Shiva-Sai-ssb** [comment]
@konopkja, Can you please assign this issue to me?

**Comment by konopkja** [comment]
> @konopkja, Can you please assign this issue to me?

assigned, thank you!

**Comment by Priyanshi1908** [comment]
@konopkja Can I kindly work on this issue?

**Comment by konopkja** [comment]
> @konopkja Can I kindly work on this issue?

hello, this has been already assigned to a different contributor. Lets wait for @Shiva-Sai-ssb.

**Comment by Shiva-Sai-ssb** [comment]
Hey @Priyanshi1908, sorry, but I have just submitted a pull request for this. Could you please check out the other issues? 
There are many open issues.
