### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by panditdhamdhere** [ethereum/ethereum-org-website#13521]
### Describe the bug

In [Developers Learning tools](https://ethereum.org/en/developers/learning-tools/) and Developer bootcamps section when we open [Pointer](https://pointer.gg/) **Learn web3 dev skills with fun interactive tutorials. Earn crypto rewards along the way** the link shows 404 deployment not found.

### To reproduce

1. Go to 'https://ethereum.org/en/developers/learning-tools/'
2. Scroll down to 'Developer bootcamps'
3. Click on Pointer

### Expected behavior

When we go to [Developers Learning tools](https://ethereum.org/en/developers/learning-tools/) and scroll down to Developer bootcamps inside that section we have various platforms including[ Pointer](https://pointer.gg/) 
![image](https://github.com/user-attachments/assets/234d665f-1989-4a80-b306-f310f5bfd222)
but when we click on the link of Pointer it shows 404. Kindly it'd be corrected with it's original link. 

### Screenshots

![image](https://github.com/user-attachments/assets/307c73fa-d26f-43f7-b90c-00013c0db386)
![ss](https://github.com/user-attachments/assets/158ac56d-fcde-44dd-ab22-980cda3b4042)

### Desktop (please complete the following information)

- OS: [windows 11]
- Browser: [Chrome]

### Smartphone (please complete the following information)

- Device [techno pova]
- OS [android 10]
- Browser: [Chrome]

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by sanjanaynvsdl** [comment]
Hey @panditdhamdhere , @chuyeow I would like to work on this issue please assign this to me!

**Comment by jay-691** [comment]
I would like to work on this issue

**Comment by wackerow** [comment]
Thanks for noting @panditdhamdhere, assigning to you as original poster.

**Comment by wackerow** [comment]
Would go ahead and remove this card from the listings
