### ISSUE TITLE
Suggest a wallet: SubWallet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [ethereum/ethereum-org-website#13542]
### Wallet name

SubWallet

### What type of wallet?

EOA

### Wallet description

SubWallet is the comprehensive non-custodial wallet solution for Polkadot & Ethereum ecosystems. We envision a Web3 multiverse gateway through which users can enjoy multichain services with utmost ease and absolute security.

### Wallet logo

- PNG File:
![Style=Gradient](https://github.com/user-attachments/assets/061a3268-02f1-4940-9ce0-ab707bea59fd)
- SVG File:
![Style=Gradient](https://github.com/user-attachments/assets/b3f66213-1505-4537-a025-d4a958d316aa)

### Background color for brand logo

#004BFF

### URL to the project

https://subwallet.app/

### When did the wallet go live to users?

2022

### What are the fees users may be paying for using your wallet product?

Users don't have to pay any wallet fees to SubWallet. They only need to pay the network and/or protocol fees depending on the transaction.

### Does the wallet have an active development team?

Yes, GitHub: https://github.com/Koniverse

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English, Vietnamese, Japanese, Chinese, Russian

### What social links are there for the project?

X (Twitter): https://x.com/subwalletapp
Telegram: https://t.me/subwallet
Discord: https://discord.com/invite/PvjV5mu6Gq
Youtube: https://www.youtube.com/channel/UC5XYLzQ1G077kUb7guZEMdA

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, SubWallet Mobile is available for both iOS and Android:
- iOS: https://apps.apple.com/us/app/subwallet-polkadot-wallet/id1633050285
- Android: https://play.google.com/store/apps/details?id=app.subwallet.mobile

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes, SubWallet Web Dashboard works with Windows, Mac, Linux:
- Web Dashboard: https://web.subwallet.app/

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, SubWallet Browser Extension is available on Chrome, Firefox:
- Chrome: https://chrome.google.com/webstore/detail/subwallet-polkadot-extens/onhogfjeacnfoofkfgppdlbmlmnplgbn
- Firefox: https://addons.mozilla.org/en-US/firefox/addon/subwallet/

### Is it a hardware wallet?

No

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

Apache-2.0 license; more details here: https://github.com/Koniverse/SubWallet-Extension?tab=Apache-2.0-1-ov-file#readme

### Who holds the private keys?

SubWallet is non-custodial. Users have full access to their public and private keys. If the project disappears, users can import their private keys into other crypto wallets to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

SubWallet has had two security audits, is open-source, and has integrated some phishing preventions. All security information is listed at: https://www.subwallet.app/security.html

### Has the wallet's smart contract code or security modules been audited?

Yes, https://verichains.io/?search=subwallet

### Does the wallet have an internal security team?

Not really but we do have a QA/QC team to help ensure that the user experience using SubWallet is as secured as possible.

### Any other security testing that should be noted?

All security information is listed at: https://www.subwallet.app/security.html

### Scam protection?

Yes, SubWallet has integrated phishing lists from Polkadot {.js} and ChainPatrol to protect users from scams. So when users access a flagged site, they will see a notification. 
All security information is listed at: https://www.subwallet.app/security.html

### Does the wallet support connecting to Ethereum applications?

Yes; Here are the documents about WalletConnect (https://docs.subwallet.app/main/extension-user-guide/connect-dapps-and-manage-website-access/connect-dapp-with-walletconnect), about connecting SubWallet directly (https://docs.subwallet.app/main/extension-user-guide/connect-dapps-and-manage-website-access), and in-wallet browser (https://docs.subwallet.app/main/mobile-app-user-guide/dapp-browser-and-manage-website-access)

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes, https://docs.subwallet.app/main/extension-user-guide/customize-your-networks#import-networks

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

Yes, but only for networks based on the Polkadot-SDK at the moment. Documentation: https://docs.subwallet.app/main/extension-user-guide/manage-staking

### Does the wallet support swaps directly?

Yes, here is a quick walk-through for SubWallet's swap feature: https://www.youtube.com/watch?v=GNrDEHiiPiY 

### Does the wallet support bridging directly?

Yes, SubWallet supports bridging various tokens between various chains. Here is our user guide: https://docs.subwallet.app/main/extension-user-guide/receive-and-transfer-assets/transfer-tokens/cross-chain-transfer; and here is a tutorial specifically for bridging WETH between Ethereum <> Polkadot: https://x.com/subwalletapp/status/1805601650318700771

### Does the wallet support multi-chain networks?

Yes, https://docs.subwallet.app/main/integration/supported-network

### Which Ethereum Layer 2 networks does the wallet support?

Arbitrum, Polygon, Optimism, Boba Network, Base

### Does the wallet allow the user to customize gas fees?

No

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, https://docs.subwallet.app/main/extension-user-guide/import-and-manage-customized-assets/import-and-manage-customized-tokens

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, SubWallet supports type 2 (EIP-1559) and type 0 (legacy) transactions.

### Does the wallet have any recovery options?

Users can export and backup accounts on SubWallet: https://docs.subwallet.app/main/extension-user-guide/account-management/export-and-backup-accounts

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, https://docs.subwallet.app/main/extension-user-guide/buy-crypto-from-fiat-money

### Does the wallet support withdrawals to fiat?

Not yet

### Does the wallet support bundled transactions?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Mabel - BD at SubWallet
- Telegram: https://t.me/MabelNguyen
- Discord: @mabelnguyen
- Twitter: https://x.com/MabelNguyen_

### Does the wallet have a dedicated support team?

Yes, SubWallet's community support is available via email, telegram, and discord:
- Email: agent@subwallet.app
- Telegram: https://t.me/subwallet
- Discord: https://discord.com/invite/PvjV5mu6Gq

### What educational resources/documentation do you provide to users?

Our comprehensive guideline is available at https://docs.subwallet.app/
We also post some detailed tutorials on Youtube at https://www.youtube.com/channel/UC5XYLzQ1G077kUb7guZEMdA

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @Mabel-Nguyen! Assigned to @konopkja for product review to start

**Comment by Mabel-Nguyen** [comment]
Thank you! @konopkja please let me know if you need any further information

**Comment by konopkja** [comment]
Hello @Mabel-Nguyen, after a careful review of both browser app and mobile app I concluded that this wallet is primarily focusing on Polkadot ecosystem, while Ethereum support in the UI is secondary or even hidden. 

This would result in a lot of confusion and friction for our Ethereum users who's goals are to use Ethereum networks and expect to use wallets that are primarily tailored for Ethereum and its ecosystem. 

The default setting, accounts, tokens and dapps are tailored for Polkadot ecosystem instead.

For these reasons I suggest against listing SubWallet.

**Comment by Mabel-Nguyen** [comment]
Hi @konopkja, I understand your concern! Our team will continue improving SubWallet further so the user experience is simple and easy for Ethereum's ecosystem as well. Thank you so much for your feedback!
