### ISSUE TITLE
Suggest a wallet: FoxWallet

### ISSUE THREAD

**Issue by Nuts444** [ethereum/ethereum-org-website#13540]
### Wallet name

FoxWallet

### What type of wallet?

EOA

### Wallet description

FoxWallet, a secure and user-friendly decentralized self-custody wallet, aims to serve as a gateway and connector within the Web3 ecosystem, seamlessly integrating with major blockchain networks such as Ethereum, Bitcoin, Solana, Ton, TRON, and Cosmos.

### Wallet logo

![svg-image-1 (1)](https://github.com/user-attachments/assets/96b2baa8-a1da-421b-976d-327027a28015)
![svg-image-1 (2)](https://github.com/user-attachments/assets/f4070768-df17-4d92-8a1d-eb47a29c5538)
![svg-image-1](https://github.com/user-attachments/assets/167714df-a109-41f5-bab2-12c2d2ebb815)

### Background color for brand logo

#000000

### URL to the project

https://foxwallet.com/en

### When did the wallet go live to users?

November 15, 2021

### What are the fees users may be paying for using your wallet product?

0.5% service fee for cross-chain swaps
0.2% service fee for same-chain swaps

### Does the wallet have an active development team?

https://github.com/foxwallet

### Is the wallet globally accessible?

Yes, FoxWallet is available globally, except Mainland China. The staking function requires KYC. 

### Is the wallet available in multiple languages?

English 
Chinese 
Japanese
Hindi 
Ukrainian 
Spanish
Indonesian (Bahasa Indonesia)
Vietnamese
Turkish
Arabic
Bengali
Russian
Thai

### What social links are there for the project?

Twitter: https://twitter.com/FoxWallet
Telegram: https://t.me/FoxWallet_EN
Discord: https://discord.com/invite/JVjVbe3Zth
Youtube: https://www.youtube.com/channel/UCt9O4HUkuNutXvFoN6NZh-w
Medium: https://medium.com/@FoxWallet
Linkedin: https://www.linkedin.com/company/foxwallet/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

IOS, Android, Google Play 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

N/a

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Chrome

### Is it a hardware wallet?

No 

### What is the availability of your source code?

Source available

### What license is the wallet software released under?

MIT for browser extension. For the app there is none as it is closed source

### Who holds the private keys?

Users hold their own private keys. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

FoxWallet has been audited by Certik as well as partially reviewed by Slowmist. 
Also, FoxWallet has integrated GoPlus API to ensure better wallet security: https://x.com/FoxWallet/status/1806538155660829149

### Has the wallet's smart contract code or security modules been audited?

https://github.com/foxwallet/security-audit-certification

### Does the wallet have an internal security team?

Yes, FoxWallet has a security team. Apart from the technicians fully-devoted to FoxWallet, we are also backed by a mining company. Hence, FoxWallet has the mining company's security team enhancing the work as well. 

### Any other security testing that should be noted?

N/a
https://hc.foxwallet.com/docs/security-tips

### Scam protection?

FoxWallet blacklists potentially fraudulent addresses and websites as well as send a warning to the users about it. Also, FoxWallet sends a notice every time users jump to a third-party website to make sure users are well-aware of the risks of using third-party websites and double-check any links they click. 
https://hc.foxwallet.com/docs/security-tips

### Does the wallet support connecting to Ethereum applications?

WalletConnect, connect to dapp directly and an in-wallet browser called "Discovery Page"

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

https://hc.foxwallet.com/docs/ethereum-advance/

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

Yes, staking ETH is supported: https://hc.foxwallet.com/docs/basic/hashquark-staking

### Does the wallet support swaps directly?

Yes, powered by 1inch

### Does the wallet support bridging directly?

Yes, powered by Li.fi

### Does the wallet support multi-chain networks?

FoxWallet has supported over 80 different chains and networks. Here is documentation on some of them: https://hc.foxwallet.com/docs/ethereum/, https://hc.foxwallet.com/docs/aleo/, https://hc.foxwallet.com/docs/spacemesh/, https://hc.foxwallet.com/docs/cosmos/injective, https://hc.foxwallet.com/docs/bitcoin/, 

### Which Ethereum Layer 2 networks does the wallet support?

Yes, https://hc.foxwallet.com/docs/ethereum/

### Does the wallet allow the user to customize gas fees?

Yes, https://hc.foxwallet.com/docs/basic/speed-up-or-cancel-tx

### Does the wallet support sending transactions to ENS addresses?

Yes, https://hc.foxwallet.com/docs/manage-funds

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

https://hc.foxwallet.com/docs/basic/erc20-usage

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, FoxWallet supports both types. EIP1559 consists of gasLimit, baseFee and priorityFee, in which baseFee + priorityFee is equivalent to previous gasPrice. But baseFee * gasLimit will be destroyed and only priorityFee * gasLimit will be owned by the miners, which makes it a preferable choice for the users, hence, for FoxWallet too. 

### Does the wallet have any recovery options?

N/a

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes. Currently, FoxWallet has integrated Moonpay, Banxa, Topper and Onramp.money, Ramp, 

### Does the wallet support withdrawals to fiat?

Yes. Powered by Onramp.money

### Does the wallet support bundled transactions?

Yes

### Who can the ethereum.org team can contact regarding the wallet in future?

Email: nataliey@foxwallet.com
Telegram: nataliey@foxwallet.com

### Does the wallet have a dedicated support team?

https://hc.foxwallet.com/
Telegram: https://t.me/FoxWallet_EN
Discord: https://discord.com/invite/JVjVbe3Zth
The support team is available 24/7

### What educational resources/documentation do you provide to users?

https://hc.foxwallet.com/docs/

### Does the wallet have any integrated tools not mentioned above?

Batch inscriptions 
Additional privacy features for Aleo and Ironfish 
Cross-chain swaps 
One Seed Derives Multiple accounts
Importing/Exporting Private Keys generated in other wallets

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @Nuts444! Have self assigned for product review to start

**Comment by konopkja** [comment]
lgtm, supported L2s:
- Arbitrum
- Optimism
- Linea
- Scroll
- zkSync Era


@Nuts444  I see you checked you are willing to work on this issue, are you able to make PR with metadata changes for your listing?

**Comment by Nuts444** [comment]
Hi Jacub,

Actually, it’s fine, I won’t need to work on this issue.

Best regards,
Natalie Y.

Natalie Yevtushyna

*Business Development & Partnerships*

*FoxWallet*
[image: emailAddress] ***@***.***
[image: website] https://foxwallet.com

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
