### ISSUE TITLE
Wallet Info Update: Infinity Wallet

### ISSUE THREAD

**Issue by InfinityWallet** [ethereum/ethereum-org-website#13564]
### Wallet name

Infinity Wallet

### What type of wallet?

EOA

### Wallet description

Infinity Wallet is a decentralized all-in-one non-custodial multi-chain wallet ecosystem and first of its kind web3 browser, that provides a one-stop solution for all a user's decentralized needs on desktop with mobile coming soon.

### Wallet logo

SVG
![app-icon](https://github.com/user-attachments/assets/028d1579-fc88-48b5-8a95-008be4361c49)

PNG
![app-icon](https://github.com/user-attachments/assets/765178eb-307a-484d-a522-4d0867b80bee)

### Background color for brand logo

#ffffff

### URL to the project

https://infinitywallet.io/

### When did the wallet go live to users?

November 2019

### What are the fees users may be paying for using your wallet product?

No fees, we are 100% free to use. The only fees a user pays are the network fees.

### Does the wallet have an active development team?

Yes, we release a Desktop wallet update every 1-2 months and will soon be launching our highly anticipated mobile version. https://infinitywallet.io/versions

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

- English
- Spanish

### What social links are there for the project?

https://x.com/InfinityWallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No, but coming soon

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

The desktop app can be downloaded here https://infinitywallet.io/download, or via the custom Ethereum page here https://infinitywallet.io/asset/ethereum 

We support:
- Windows;
- Mac;
- Linux;

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### What is the availability of your source code?

Closed source

### What license is the wallet software released under?

n/a

### Who holds the private keys?

**Do users have access to their public and private keys?** Yes, users own and are the only ones that have access to their seed phrase and private keys.

**Does anyone else?** No, only the user their self has their seed phrase which can also be generated offline since its generated and encrypted locally.

**If the company/project were to disappear, would users still be able to access their funds?** Yes, we follow the standards allowing users to recover their wallet with us or from us to another wallet.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We are not a static wallet and are constantly evolving with new features, this makes external audits unfeasible. We do however have our own in-house audit and QA team that internally audit/review and test every release, and have an ongoing bug bounty program. The wallet has been in live use for over 4 years with over 2,500,000 wallets created without ever an issue and we operate live support to ensure our users' experience is flawless.

### Has the wallet's smart contract code or security modules been audited?

Not a smart contract wallet

### Does the wallet have an internal security team?

Yes

### Any other security testing that should be noted?

n/a

### Scam protection?

Yes, with our Web3 Browser we have employed blacklisting of scam/phishing projects/contracts in attempts to further secure interactions with Web3.

### Does the wallet support connecting to Ethereum applications?

Yes, we support connecting to Ethereum application two ways. Either via our Web3 Browser (not a browser extension but a native desktop browser for web3) or via WalletConnect.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support importing Ethereum RPC endpoints?

We provide our own infrastructure and RPCs, as such there is no need for users to import an RPC

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

No, coming soon

### Does the wallet support swaps directly?

Yes. https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

### Does the wallet support bridging directly?

Yes. https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

### Does the wallet support multi-chain networks?

Yes, a full list of supported chains can be found here https://infinitywallet.io/assets?type=chains

### Which Ethereum Layer 2 networks does the wallet support?

Arbitrum, Optimism and Base. We will also continue to expand support for further L2s.

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, Legacy (type 0) and Eip-1559 (type 2)

### Does the wallet have any recovery options?

Yes, users can always recover their wallet with their 12 or 24 word seed phrase.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes. https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

### Does the wallet support withdrawals to fiat?

Yes. https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No, but we are working on social and passkey wallet creation and recovery.

### Does the wallet support bundled transactions?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

You can get in contact with a partner team at [partner@infinitywallet.io](mailto:partner@infinitywallet.io)

### Does the wallet have a dedicated support team?

Yes

**Where should we send users that are having issues?**
Our live support team can be contacted 7 days a week via the website [infinitywallet.io](https://infinitywallet.io/)

**How fast is the support?**
Usually within 2-10 minutes if via live support chat and 24-48 hours via email.

### What educational resources/documentation do you provide to users?

Users can visit our Knowledge Base - https://infinitywallet.io/support

We also recently released our Glossary that is in the process of expanding terms https://infinitywallet.io/glossary 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @InfinityWallet! Assigned. cc: @konopkja

**Comment by konopkja** [comment]
lgtm @InfinityWallet 

1. is there any processing fee atop of the network fee for in-app swapping & bridging? if not what is the business model?
2. I see you checked that you are willing to work on this issue, that means you are willing to create a pull request with metadata update for your listing, will you do that?

**Comment by InfinityWallet** [comment]
> lgtm @InfinityWallet
> 
> 1. is there any processing fee atop of the network fee for in-app swapping & bridging? if not what is the business model?
> 2. I see you checked that you are willing to work on this issue, that means you are willing to create a pull request with metadata update for your listing, will you do that?

Hi @konopkja,

1. Fees would depend on the exchange used for the particular swap. The wallet aggregates exchanges for the best rate, and the estimated amount to receive would already have any fees deducted.
2.  In regards to point 2, I am not quite sure what you mean?

**Comment by konopkja** [comment]
> > lgtm @InfinityWallet
> > 
> > 1. is there any processing fee atop of the network fee for in-app swapping & bridging? if not what is the business model?
> > 2. I see you checked that you are willing to work on this issue, that means you are willing to create a pull request with metadata update for your listing, will you do that?
> 
> Hi @konopkja,
> 
> 1. Fees would depend on the exchange used for the particular swap. The wallet aggregates exchanges for the best rate, and the estimated amount to receive would already have any fees deducted by an exchange if they have a fee.
> 2. In regards to point 2, I am not quite sure what you mean?

<img width="338" alt="Screenshot 2024-08-16 at 9 38 12" src="https://github.com/user-attachments/assets/d280bab0-dcf6-4d1d-9a50-56be32e24836">

This in the original post. If not dont worry though, our dev team or contributors will take care of the update. It will just likely take some time before we can get to it.

**Comment by InfinityWallet** [comment]
> > > lgtm @InfinityWallet
> > > 
> > > 1. is there any processing fee atop of the network fee for in-app swapping & bridging? if not what is the business model?
> > > 2. I see you checked that you are willing to work on this issue, that means you are willing to create a pull request with metadata update for your listing, will you do that?
> > 
> > 
> > Hi @konopkja,
> > 
> > 1. Fees would depend on the exchange used for the particular swap. The wallet aggregates exchanges for the best rate, and the estimated amount to receive would already have any fees deducted by an exchange if they have a fee.
> > 2. In regards to point 2, I am not quite sure what you mean?
> 
> <img alt="Screenshot 2024-08-16 at 9 38 12" width="338" src="https://private-user-images.githubusercontent.com/100724231/358507392-d280bab0-dcf6-4d1d-9a50-56be32e24836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTczNzIsIm5iZiI6MTcyMzc5NzA3MiwicGF0aCI6Ii8xMDA3MjQyMzEvMzU4NTA3MzkyLWQyODBiYWIwLWRjZjYtNGQxZC05YTUwLTU2YmUzMmUyNDgzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwODMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTQ3NDliY2Q4MmQ0MTMwOWE2MGYyY2VlMDdkMDJhNWNhNzhlMDIwNjk1YjViM2UwZDlhYTM1MDFjNzNlM2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BL177QSHKNTKM2KDwGz6r6PDCHm8pJ62_ZTi3wTyajY">
> This in the original post. If not dont worry though, our dev team or contributors will take care of the update. It will just likely take some time before we can get to it so hang in there.
> 
> Once done, this issue will be closed.

@konopkja we have made a pull request with the update data. https://github.com/ethereum/ethereum-org-website/pull/13665
