### ISSUE TITLE
BUG: Search functionality is not working.

### ISSUE THREAD

**Issue by Tanishk05** [ethereum/ethereum-org-website#13603]
### Describe the bug

When I click on the search field it does not any suggestion for the text neither it shows error page.

## It says no result found.

When I click on search by **algolia** it gives 400: BAD_REQUEST.

### To reproduce

1. Go to 'https://ethereum.org/en/'
2. Click on 'search bar'
3. See error

### Expected behavior

Search bar had to show the results for the matching query. It is showing no result found.

### Screenshots

![Screenshot from 2024-08-08 00-42-39](https://github.com/user-attachments/assets/7234d973-166c-4cb4-b033-e7546c935dd9)

![Screenshot from 2024-08-08 00-42-52](https://github.com/user-attachments/assets/d0bcab47-c799-48fb-b71d-b0e94fd87700)

![Screenshot from 2024-08-08 00-43-23](https://github.com/user-attachments/assets/4516d6c7-965d-4810-a34e-4c101232b80e)

![Screenshot from 2024-08-08 00-50-32](https://github.com/user-attachments/assets/8f511fb4-baf7-4399-b95d-a66258eef7c0)

### Desktop (please complete the following information)

- OS: Fedora 40
- Browser: Firefox
- Version: 128.0.3 (64-bit)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by pettinarip** [comment]
Thanks for reporting @Tanishk05
