### ISSUE TITLE
New issue templates not appearing

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1360]
**Describe the bug**

There are 4 GitHub issue templates in the repo, but only 2 appear when you go to create an issue via the GitHub website. All four templates should be included on the template selection screen.

![image](https://user-images.githubusercontent.com/40891631/90886751-eab69080-e3aa-11ea-87b4-768f09e2ff98.png)
![image](https://user-images.githubusercontent.com/40891631/90886780-f99d4300-e3aa-11ea-9069-f631c0fa42f9.png)

**Comment by samajammin** [comment]
Hmmm thanks for surfacing... I must have screwed something up... 👀
