### ISSUE TITLE
Suggest an exchange

### ISSUE THREAD

**Issue by must479** [ethereum/ethereum-org-website#13624]
### Exchange name

Uniswap 

### Exchange description

Ugp

### What geographical restrictions apply to this exchange?

Tesnet user

### Which currencies are accepted by this exchange?

Bounty layer2

### Do you have any proof that they're a legitimate company?

Yes

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Uniswap is already listed on https://ethereum.org/en/dapps/
