### ISSUE TITLE
Feature request: Add Updraft to learning tools page

### ISSUE THREAD

**Issue by panditdhamdhere** [ethereum/ethereum-org-website#13638]
[Updraft](https://updraft.cyfrin.io/) is a great resource for learning **Smart contract development, Security, EVM**, and overall what one needs to start building on **Ethereum.**  This Resource teaches the next generation of smart contract developers and helps them learn about Ethereum.  It needs to be listed on our [Learning Tools](https://ethereum.org/en/developers/learning-tools/) page along with other resources and bootcamps.

**Comment by Khemmie-Ray** [comment]
Can I be assigned to this when it's open?

**Comment by wackerow** [comment]
Looks great, thanks for posting @panditdhamdhere! @Khemmie-Ray, appreciate you volunteering, have gone ahead and assigned you; a PR is welcome =). Let us know if you hit issuees

**Comment by Khemmie-Ray** [comment]
On it, thank you
