### ISSUE TITLE
Add quiz for stablecoins

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13649]
### Page URL

https://ethereum.org/en/stablecoins/

### Question content

This is a call to action for someone to create a fun beginner friendly quiz questions and explanations for our Stablecoins page. The quiz will be accessible from Stablecoins page as well as from the [quiz page](https://ethereum.org/en/quizzes/)

**Format**:
Create 5 questions, each consisting of:

Question prompt
1 correct answer with an explanation for why it is correct
3 incorrect answers, each with a unique explanation for why they are incorrect

Be mindful and use concise beginner friendly language. All questions should be only related to the content that is present on the https://ethereum.org/en/stablecoins/

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by emolikememo** [comment]
Would love to take this on!

**Comment by konopkja** [comment]
> Would love to take this on!

perfect! assigning you the issue

**Comment by emolikememo** [comment]
This is my first time contributing, unsure if you want me to open a new issue or just write directly in here. Let me know if opening a new issue is cleaner or if this is chill

Q1: What are Stablecoins?
- Cryptocurrencies with low volatility, meaning their value is steady and similar to traditional currencies
    - Correct! Stablecoins are designed to address the volatility issue common in many cryptocurrencies.
- Digital representations of gold
    - This is incorrect. While some stablecoins might be backed by precious metals, they can also be backed by fiat currency or other cryptocurrencies.
- A new type of credit card
    - This is incorrect. Stablecoins are a type of cryptocurrency, not a credit card.
- A replacement for Ether
    - This is incorrect. Stablecoins are not designed to replace Ether. They are another token on the Ethereum network and are designed to have the opposite characteristic of Ether, notably its volatility, but don't function as a replacement.

Q2: Which of the following is a stablecoin?
- US Dollar
    - This is incorrect. While stablecoins can represent the US dollar, a US dollar is not a cryptocurrency and thus is not considered a stablecoin.
- Aave token
    - This is incorrect. Aave token is a cryptocurrency, but it's price is not intended to be stable.
- Dai
    - Correct! Dai is probably the most famous decentralized stablecoin and its value is roughly 1 US Dollar.
- Ether
    - This is incorrect. Ether is the native currency of the Ethereum network, but is not intended to be stable.

Q3: What can stablecoins be used for?
- To reduce exposure to cryptocurrencies with volatile changes in price
    - Not quite. This answer is partially correct, but it's only one of the many things stablecoins can be used for.
- To buy things on the internet anywhere in the world 
    - Not quite. This answer is partially correct, but it's only one of the many things stablecoins can be used for.
- To earn money by lending to others
    - Not quite. This answer is partially correct, but it's only one of the many things stablecoins can be used for.
- All of the above
    - Correct! Stablecoins can be used to hold cryptocurrency with less volatility, transact globally on the internet, and earn interest when you lend them out.

Q4: What makes a stablecoin unique?
- It is a token that is tied to an asset in the real world
    - This is incorrect. While this is often the case, it is not unique to stablecoins.
- It is a token specifically designed to keep its value steady
    - Correct! Stablecoins are unique in that they are tokens designed to keep their value equal to the asset they are pegged to (most commonly traditional currencies e.g., 1 USDC = 1 US dollar)
- It is capable of being sent over the internet
    - This is incorrect. While this is a capability, it is not unique to stablecoins.
- It can be used on the Ethereum network.
    - This is incorrect. Many other cryptocurrency tokens can be used on the Ethereum network.

Q5: What is NOT a way to get stablecoins?
- Swap for them with your existing cryptocurrencies
    - Incorrect, this is a way to get stablecoins. One of the most common ways people acquire stablecoins is by swapping their existing cryptocurrencies for stablecoins.
- Earn them in exchange for work
    - Incorrect, this is a way to get stablecoins. You can earn stablecoins by working on projects in the Ethereum ecosystem.
- Borrow them
    - Incorrect, this is a way to get stablecoins. You can borrow some stablecoins by using your existing cryptcurrencies, such as Ether, as collateral. You will need to pay the borrowed stablecoins back at some point.
- Buy them from an exchange
    - Incorrect, this is a viable way to get stablecoins. Many exchanges and wallets let you buy stablecoins directly, though geographical restrictions may apply.
- Mine them
    - Correct! Unlike Bitcoin, you are unable to mine stablecoins.

**Comment by konopkja** [comment]
perfect, I will do minor adjustments but lgtm! next step will be request help from the community to create PR and add this quiz. Thank you @emolikememo !

**Comment by konopkja** [comment]
**Final version**

**Q1: What are Stablecoins?**

A. Cryptocurrencies with low price volatility, their value is steady and similar to traditional currencies
- Correct! Stablecoins are designed to address the volatility issue common in many cryptocurrencies.
B. Digital representations of gold
- This is incorrect. While some stablecoins might be backed by precious metals, they can also be backed by fiat currency or other cryptocurrencies.
C. A new type of credit card
- This is incorrect. Stablecoins are a type of cryptocurrency, not a credit card.
D. A replacement for Ether
- This is incorrect. Stablecoins are not designed to replace Ether. They are another token on the Ethereum network and are designed to have the opposite characteristic of Ether, notably its volatility.

**Q2: Which of the following is a stablecoin?**

A. US Dollar
- This is incorrect. While stablecoins can represent the US dollar, a US dollar is not a cryptocurrency.
B. Aave token
- This is incorrect. Aave token is a cryptocurrency, but it's price is not intended to be stable.
C. Dai
- Correct! Dai is probably the most famous decentralized stablecoin and its value is roughly 1 US Dollar.
D. Ether
- This is incorrect. Ether is the native currency of the Ethereum network, but is not intended to be stable.

**Q3: What can stablecoins be used for?**

A. To shield its users from volatile changes in price
- Not quite. This answer is partially correct, but it's only one of the many things stablecoins can be used for.
B. To buy things on the internet anywhere in the world
- Not quite. This answer is partially correct, but it's only one of the many things stablecoins can be used for.
C. To earn money by lending to others
- Not quite. This answer is partially correct, but it's only one of the many things stablecoins can be used for.
D. All of the above
- Correct! Stablecoins can be used to hold cryptocurrency with less volatility, transact globally on the internet, and earn interest when you lend them out.

**Q4: What makes stablecoins unique?**

A. It is a token that is tied to an asset in the real world
- This is incorrect. While this is often the case, it is not unique to stablecoins.
B. It is a cryptocurrency token specifically designed to keep its value steady
- Correct! Stablecoins are unique in that they are tokens designed to keep their value equal to the asset they are pegged to (most commonly traditional currencies e.g., 1 USDC = 1 US dollar)
C. It is capable of being sent over the internet
- This is incorrect. While this is a capability, it is not unique to stablecoins.
D. It can be used on the Ethereum network.
- This is incorrect. Many other cryptocurrency tokens can be used on the Ethereum network.

**Q5: What is NOT a way to get stablecoins?**

A. Swap them with other token
- Incorrect, this is a way to get stablecoins. One of the most common ways people acquire stablecoins is by swapping their existing cryptocurrencies for stablecoins.
B. Borrow them
- Incorrect, this is a way to get stablecoins. You can borrow some stablecoins by using your existing cryptcurrencies, such as Ether, as collateral. You will need to pay the borrowed stablecoins back at some point.
C. Buy them from an exchange
- Incorrect, this is a way to get stablecoins. Many exchanges and wallets let you buy stablecoins directly, though geographical restrictions may apply.
D. Mine them
Correct! Unlike Bitcoin, you are unable to mine stablecoins.

**Comment by konopkja** [comment]
for https://ethereum.org/en/quizzes/

quiz difficulty: beginner
section: Using Ethereum

**Comment by Shiva-Sai-ssb** [comment]
I would like to work on this. Please assign it to me, @konopkja.

**Comment by Oyase-shinobi** [comment]
Hello @konopkja 
I would love to engage in your team

**Comment by konopkja** [comment]
> Hello @konopkja I would love to engage in your team

not sure what you mean, but specificissues arent the right place to discuss unrelated topics. If yo uwish to contribute, you can check the open issues in our repo or reach out on discord.

**Comment by Oyase-shinobi** [comment]
Ok, Thanks
