### ISSUE TITLE
Delete /enterprise/private-ethereum/ and the menu link to it

### ISSUE THREAD

**Issue by tasdienes** [ethereum/ethereum-org-website#13640]
### Is your feature request related to a problem? Please describe.

In the early years, "Enterprise Ethereum" generally meant private chains. Since then the landscape has evolved, and private chains have mostly become irrelevant while the enterprise focus is now mainly on Mainnet and L2s. 

Though I split up the public and private chain sections of ethereum.org/enterprise into separate pages about 5 years ago, I now believe it is time to retire the private chains related content entirely. I have given up on maintaining https://ethereum.org/en/enterprise/private-ethereum and it has become increasingly obsolete and irrelevant. I recently removed references to it from the /enterprise page.

### Describe the solution you'd like

Please retire /enterprise/private-ethereum, and remove the menu item Build > Enterprise > Private Ethereum that links to it.

Build > Enterprise can link directly to /enterprise

I would have created a PR for this, but mucking with menus is a bit over my head :)

### Describe alternatives you've considered

NA

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by Signor1** [comment]
Hi @tasdienes, can I work on this ?

**Comment by tasdienes** [comment]
> Hi @tasdienes, can I work on this ?

Certainly!  No objections from me!  Though I don't know if the site maintainers prefer to manage the menus directly?

**Comment by Signor1** [comment]
> > Hi @tasdienes, can I work on this ?
> 
> Certainly! No objections from me! Though I don't know if the site maintainers prefer to manage the menus directly?

Alright. Let me get their attention.

**Comment by Signor1** [comment]
Hello @wackerow, can I quickly on work this ?

**Comment by tasdienes** [comment]
Bump @wackerow

**Comment by isabelladebrito** [comment]
@Signor1 sorry for our delay! let me know if you'd still up to work on this issue

**Comment by Signor1** [comment]
> @Signor1 sorry for our delay! let me know if you'd still up to work on this issue

Yes, I can work on it.

**Comment by Signor1** [comment]
Hey @isabelladebrito, I just created a PR #14062 . You can check it out

**Comment by wackerow** [comment]
Fixed with #14062
