### ISSUE TITLE
Bug report: remove date from whitepaper page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13645]
### Describe the bug

We have a date component that showcases when was a page last edited, however on whitepaper page this may be confusing to users leading them to believe the whitepaper has been updated with new information.

THerefore we should remove the component from this page.

### To reproduce

1. Go to https://ethereum.org/en/whitepaper/
2. See date on top of the page

### Expected behavior

remove date (OR instead hard code static date of when the whitepaper has been published.)

### Screenshots

<img width="1101" alt="Screenshot 2024-08-15 at 11 19 45" src="https://github.com/user-attachments/assets/7c48d12f-6646-4ae1-af5b-5f92c008284f">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by gks2022004** [comment]
I solve it, assign it to me please

**Comment by konopkja** [comment]
> I solve it, assign it to me please

assigned, thank you!

**Comment by gks2022004** [comment]
I could not find the 'whitepaper' page, to remove the date, need help😅

**Comment by konopkja** [comment]
> I could not find the 'whitepaper' page, to remove the date, need help😅

https://ethereum.org/en/whitepaper/

**Comment by gks2022004** [comment]
no, in the main repository, where I have to fix the issue, from the repo I get the idea of working, but the whitepaper is fetched on the hero section of WhitePaper.

**Comment by konopkja** [comment]
cc @wackerow  @pettinarip for help

**Comment by corwintines** [comment]
Hey @gks2022004 

The area where this is rendered can be found here https://github.com/ethereum/ethereum-org-website/blob/0e37f74304808aa6612d3e6b8c8a9f0bd186ebb8/src/layouts/Static.tsx#L125

I think all that needs to be done is conditionally render this where if the slug is /whitepaper it isnt rendered, otherwise render.

**Comment by gks2022004** [comment]
Thanks, for the help

**Comment by gks2022004** [comment]
@corwintines @wackerow @konopkja 
I have created the PR
https://github.com/ethereum/ethereum-org-website/pull/13687

**Comment by gks2022004** [comment]
@wackerow @konopkja 
I have created the [PR](https://github.com/ethereum/ethereum-org-website/pull/13710)
