### ISSUE TITLE
Content request: What is cryptocurrency and blockchain?

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13652]
This is a content request for anyone to write a beginner friendly article explaining what is blockchain and cryptocurrency.

Whoever wants to write the article, please first comment on this issue and we will assign it to you.

Use this style guide and best practices to format the article appropriately for our audience: https://ethereum.org/en/contributing/style-guide/

**Describe the solution you'd like**
A beginner friendly article explaining what are blockchains and what are cryptocurrencies. 

- Should not be too long or technical
- What are the benefits
- Comparison with Fiat currencies

**Comment by Code-Hacker26** [comment]
@konopkja  I want to try this issue,plz assign it to me

**Comment by konopkja** [comment]
> @konopkja I want to try this issue,plz assign it to me

thats great to hear! assigning you the ticket, we can have discussion here if you need to bounce back ideas for the article.

**Comment by Code-Hacker26** [comment]
@konopkja  Shall i make a new file, in content folder in public , for the given article?

**Comment by konopkja** [comment]
> @konopkja Shall i make a new file, in content folder in public , for the given article?

yes, it will be probably in a url such as https://ethereum.org/en/blockchain/

**Comment by konopkja** [comment]
closing this issue due to lack of contribution, perhaps we can recreate new issue in the future.
