### ISSUE TITLE
Add Linea to displayed layer 2s

### ISSUE THREAD

**Issue by jlwllmr** [ethereum/ethereum-org-website#13657]
### Name

Linea

### Logo

![Wordmark Black](https://github.com/user-attachments/assets/7da65fbe-dc57-47bc-9e25-bafa3aa54ffd)

### Description

An EVM-equivalent network, scaling the Ethereum experience. Secured with a zero-knowledge rollup to Ethereum, built on lattice-based cryptography, and powered by Consensys.

### Website

https://linea.build/

### Developer documentation

https://docs.linea.build/

### L2BEAT page

https://l2beat.com/scaling/projects/linea

### Is the project open source?

Yes: https://github.com/Consensys/linea-monorepo

### What category of layer 2 is it?

Zero knowledge

### Does the layer 2 use Ethereum Mainnet for data availability?

Yes. An example transaction submitting a blob to L1: https://etherscan.io/tx/0x3927bca514d6f2661d5f7a09f1988a00855b09c7d43fec7789f21cacace02d5b

### Which bridges are used to onboard users?

Linea has a bridge portal available here: https://bridge.linea.build/

It includes:
- Linea's native bridge
- A link to MetaMask Portfolio, which has a bridge aggregator
- Our ecosystem portal, [filtered to display bridges](https://linea.build/apps?types=bridge)

### Which exchanges offer support for the project?

Available CEXs: https://linea.build/apps?types=cex

There are also many DEXs available in the DeFi category: https://linea.build/apps?types=defi

### Link to dapp ecosystem (if applicable)

https://linea.build/apps

### Token contract list (if applicable)

https://github.com/Consensys/linea-token-list/blob/main/json/linea-mainnet-token-shortlist.json

### What date did the project go live?

July 11, 2023: https://linea.mirror.xyz/7l9gKzYzKVOxEOnReavov467Ss_fsrkGzABvbRISPMY

### Is this project a fork? If yes, which project was forked?

n/a

### What wallets support this layer 2?

https://linea.build/apps?types=wallet 

- AlphaWallet
- Arcana Network
- Bitget
- BlockWallet
- Desig
- Echooo
- Fluvi
- FoxWallet
- Gate
- Holdstation
- ImToken
- Krystal
- **MetaMask**
- Nabox
- OKX
- OneKey
- Particle Network
- Patch Wallet
- SafePal
- Scuba Protocol
- Timeless X
- TokenPocket
- UXUY
- Web3Auth
- Wigwam
- Yellow Wallet

### How can users and/or developers connect too this layer 2 network?

RPC URL: https://rpc.linea.build
Chain ID: 59144
Symbol: ETH
Block explorer: https://lineascan.build/ 

Alternative public RPC URLs available [here](https://docs.linea.build/developers/tooling/node-providers#public-rpc-endpoints). 

[Source](https://docs.linea.build/developers/quickstart/info-contracts#network-information)

### Diligence:

- Plonk Verifier: https://consensys.io/diligence/audits/2023/06/linea-plonk-verifier/
- Message Service & Rollup: https://consensys.io/diligence/audits/2023/06/linea-message-service/
- Canonical Token Bridge: https://consensys.io/diligence/audits/2023/06/linea-canonical-token-bridge/

### Open Zeppelin:

- Linea Bridge Audit: https://blog.openzeppelin.com/linea-bridge-audit-1
- Linea Verifier Audit: https://blog.openzeppelin.com/linea-verifier-audit-1

### Diligence:

- Proof aggregation, data compression and message service updates audit: https://consensys.io/diligence/audits/2024/01/linea-contracts-update/

### Open Zeppelin:

Proof aggregation, data compression and message service updates audit: https://blog.openzeppelin.com/linea-v2-audit

### Open Zeppelin

Blob submission audit: https://blog.openzeppelin.com/linea-blob-submission-audit

### Open Zeppelin

Gas optimization and token bridge update audit: https://blog.openzeppelin.com/linea-gas-optimizations-audit

### Cyfrin

Full codebase audit including recent gas optimizations and TokenBridge updates: https://github.com/Cyfrin/cyfrin-audit-reports/blob/main/reports/2024-05-24-cyfrin-linea-v2.0.pdf

([Source](https://immunefi.com/bug-bounty/linea/information/))

### Has the project sustained its users over time?

YTD charts sourced from [L2beat](https://l2beat.com/scaling/projects/linea): 

TVL:
<img width="869" alt="image" src="https://github.com/user-attachments/assets/07580a56-e847-40ce-90aa-26a203bdb694">

Activity:
<img width="869" alt="image" src="https://github.com/user-attachments/assets/47a591f0-c022-47cf-a0b9-6eacd6e27aed">

### Is there an active team developing the project?

Yes

### Is there a block explorer?

[Multiple available](https://l2beat.com/scaling/projects/linea). 

- Lineascan: https://lineascan.build/ 
- L2scan: https://linea.l2scan.co/
- Blockscout: https://explorer.linea.build/
- OKLink: https://www.oklink.com/linea

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by konopkja** [comment]
Hi @jlwllmr, thanks for the submission! We are currently revamping our L2 content (see https://github.com/ethereum/ethereum-org-website/issues/13062). Which is a blocker for this. But rest assured, we are familiar with Linea and will be listing it on our new pages (to be published in this quarter).

I will close this issue for now as we are already in the proces of including Linea. However thank you for useful links and additional info we could consider.

**Comment by jlwllmr** [comment]
@konopkja Many thanks! Feel free to get in touch if you need any more details.
