### ISSUE TITLE
Content request: Ethereum payments as a use case

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13653]
This is a content request for anyone to write a beginner friendly article explaining why payments on Ethereum have become a strong use case for the technology.

Whoever wants to write the article, please first comment on this issue and we will assign it to you.

Use this style guide and best practices to format the article appropriately for our audience: https://ethereum.org/en/contributing/style-guide/

**Describe the solution you'd like**

A beginner friendly article explaining different contexts when payments on Ethereum make the most sense.

- What are the benefits
- Comparison with Fiat currencies
- include real world examples and data

**1. Donations and relief funds**
- The crypto community quickly came together to globally collect funding for relief efforts. Different donation campaigns were launched by [Refik Anadol](https://twitter.com/refikanadol/status/1622623521104089090), [Anka Relief DAO](https://ankarelief.org/), [Bankless DAO & Giveth](https://twitter.com/Givethio/status/1623493672149843969), and [Pak](https://cause.quest/). Vitalik Buterin also donated to [different campaigns](https://cointelegraph.com/news/vitalik-buterin-donates-227k-to-help-earthquake-victims-in-turkey-syria). Although [crypto is not allowed as a payment](https://www.reuters.com/technology/no-more-kebabs-bitcoins-turkeys-crypto-payment-ban-looms-2021-04-28/) in Turkey, [an okay was given](https://twitter.com/haluklevent/status/1622913175409623041) for some organizations to collect donations. At least 6M $ was collected per [this Dune dashboard](https://dune.com/davy42/turkiye-earthquake-donations) following some of the addresses.

More info can be found here: https://turkiyereliefdao.org/

Recalling the similar campaigns for [Ukraine](https://www.elliptic.co/blog/live-updates-millions-in-crypto-crowdfunded-for-the-ukrainian-military) and [India](https://cryptorelief.in/), I think this highlights an important use case for Ethereum: To be able to quickly raise donations against emergencies globally, which otherwise would require converting foreign currencies, sending them through SWIFT (if your bank supports it) which takes days to reach, and potentially paying really high transactions fees.

Also Money disbursement programs can benefit from easy audibility of the blockchain

**2. Remittances**
- Cheap global payment network

**3. Payments for goods and services**
- provide examples of projects accepting ETH or stablecoins, which countries are farthest in adoption.

**4. Salary payments**
- provide examples

**5. Access to foreign currencies to fight local hyperinflations**

There are probably many other topics related to payments that the author of the article could research and write about.  We can use this issue to coordinate and discuss ideas.

**Comment by BoluwatifeInferno** [comment]
Gm @konopkja I would love to contribute to this task. May it be assigned to me?

**Comment by konopkja** [comment]
HI @BoluwatifeInferno, this is great to hear! Assigning you the issue. Please comment here whenever you need feedback or ask questions. 

Be sure to read properly our style guides linked above - every article is heavily reviewed before submitting to the website and usually takes a lot of edits.

**Comment by BoluwatifeInferno** [comment]
Thank you, I will make sure to read and incorporate the style guides linked above properly. I will also make comments when I have questions or need feedback.

**Comment by BoluwatifeInferno** [comment]
Gm @konopkja I have read the style guide and I found it extremely helpful. I would like to write about payments for goods and services as a use case. But I would also love to write about how Ethereun has helped impact donations of relief funds. Is it possible I do both or does this issue only require one submission?

**Comment by BoluwatifeInferno** [comment]
Oh alright, that is not a problem. I initially thought to write on all, but I was considering the word count. Putting in mind that the style guide doesn't advise that I go over 1500 words. 

The first draft will be ready soon.

**Comment by konopkja** [comment]
hi @BoluwatifeInferno, how is it going with this article? Need any help? Still working on this one as well or working on other issue currently?

**Comment by BoluwatifeInferno** [comment]
gm @konopkja I am actually working on both. Just had an issue with bandwidth lately. 

Anyways, here is the first draft for this issue without the graphics https://docs.google.com/document/d/12PgrcdglATbsy0uLRjpXEnnC8x8GJPp8yzqJ4cNu0ec/edit?usp=sharing

I would love comments and feedback before proceeding.

**Comment by konopkja** [comment]
hi @BoluwatifeInferno, the team reviewed the article and was very impressed! Great job! We will be happy to add this to the website.

Added few comments in the doc for minor edits.

**Comment by BoluwatifeInferno** [comment]
Thank you @konopkja would incoporate the edits into the article now.

**Comment by konopkja** [comment]
the article is ready to be turned into PR! thank you so much  @BoluwatifeInferno!!! (we also gave you shoutout for this contribution on our last community call).

Do you have experience coding or shall we find a different dev person to prepare the code part for the new article to be published?

**Comment by BoluwatifeInferno** [comment]
Thank you so much @konopkja, oh I don't have experience coding, I would appreciate if there is a different dev person to prepare the code part of the article. 

Thank you for the shoutout ❤️ . Oh also is there a recording of the community call, I would love to listen to it, there were some updates I missed that I would really love to also check out.

**Comment by konopkja** [comment]
> Thank you so much @konopkja, oh I don't have experience coding, I would appreciate if there is a different dev person to prepare the code part of the article.
> 
> Thank you for the shoutout ❤️ . Oh also is there a recording of the community call, I would love to listen to it, there were some updates I missed that I would really love to also check out.

Hi, unfortunately not recorded this time. 

Unassigning you the issue so that a dev can pick it up.

For implementation:

- create new page /payments

**Comment by konopkja** [comment]
I will create new issue for the development, once again thank you @BoluwatifeInferno  for the work on this. I will close this issue as completed

**Comment by BoluwatifeInferno** [comment]
I thank you @konopkja and the community for all the help given to me during the entire process. Thank you!

**Comment by konopkja** [comment]
to track development of the page: https://github.com/ethereum/ethereum-org-website/issues/14217

**Comment by konopkja** [comment]
Adding just an update here: the page will go live in few days! TY everyone who participated and please claim your poaps on discord / https://app.galxe.com/quest/ethereumorg
