### ISSUE TITLE
Add PayTrie as a fiat on/off ramp to ethereum.org/get-eth

### ISSUE THREAD

**Issue by kevinzhangTO** [ethereum/ethereum-org-website#1365]
**What geographical restrictions apply to this exchange?**

Canada

**Which currencies are accepted by this exchange?**

Canadian dollars, ERC-20 based stablecoins (DAI, USDC, USDT, BUSD, PAX, TUSD), ETH

**Do you have any proof that they're a legitimate company**

https://www10.fintrac-canafe.gc.ca/msb-esm/public/detailed-information/msb-details/7b226d73624f72674e756d626572223a3135393938382c227072696d617279536561726368223a7b226f72674e616d65223a2270617974726965222c2273656172636854797065223a317d7d/

**Do you have any extra information?**

PayTrie is a fiat on/off ramp for Canadians. PayTrie has been around since 2019, with backing from ConsenSys. Due to our fast, low-cost, and noncustodial service, PayTrie has been the go-to fiat on/off ramp for Canadians wishing to interact with DeFi applications, acquiring ETH and other ERC-20 stablecoins. PayTrie makes it extremely easy to onboard into your first piece of cryptocurrency using a stablecoin.

**Comment by ryancreatescopy** [comment]
@kevinzhangTO does this mean you're only able to use PayTrie if you live in Canada?

**Comment by GeorgeTrotter** [comment]
Hey @kevinzhangTO! Confirming some last details for your request. Our [policy](https://ethereum.org/en/contributing/adding-products/) for adding products asks for products to be audited, live for six months, and maintained by an active team.

- Where can we confirm the results of your last audit?

- When did PayTrie go live?

- Is PayTrie maintained by an active team (I assume so, but just checking!)

Thanks!
