### ISSUE TITLE
Suggest a wallet: MEW Portfolio

### ISSUE THREAD

**Issue by gamalielhere** [ethereum/ethereum-org-website#13660]
### Wallet name

MEW Portfolio

### What type of wallet?

EOA

### Wallet description

MEW Portfolio (MyEtherWallet) is a dashboard that allows users to view and manage any self-custody wallet, and access features like multichain sending, swapping, and staking, as well as direct interaction with Ethereum contracts. MEW Portfolio also offers an offline interface for the secure generation of software Ethereum wallets.

### Wallet logo
![MyEtherWallet](https://github.com/user-attachments/assets/07ef82d1-6718-41f9-941a-763522cd0006)
![logo-dark b47b5639 (1)](https://github.com/user-attachments/assets/0960bd84-decf-40f5-bf66-c8ad23581abc)

### Background color for brand logo

#ffffff

### URL to the project

https://www.myetherwallet.com/

### When did the wallet go live to users?

August 2015

### What are the fees users may be paying for using your wallet product?

The wallet is free to use. Users only pay network fees for sending transactions. Swaps incur fees set by our integrated providers, and vary depending on provider, ranging 0.875 - 1%. All fees are shown in the transaction preview before the user confirms the transaction

### Does the wallet have an active development team?

Yes, code can be found at https://github.com/MyEtherWallet/MyEtherWallet.

### Is the wallet globally accessible?

Yes. MEW Portfolio does not collect personal data, has no KYC requirements, and no geographic limitations.

### Is the wallet available in multiple languages?

No.

### What social links are there for the project?

X (Twitter) https://x.com/myetherwallet
Instagram https://www.instagram.com/myetherwallet/
Facebook https://www.facebook.com/MyEtherWallet
Reddit https://www.reddit.com/r/MyEtherWallet/
Youtube https://www.youtube.com/channel/UCQU5QbObwmaHNEMsuX3uQKA
Github https://github.com/mewwallet
Telegram https://t.me/myetherwallet
Medium https://medium.com/myetherwallet
Warpcast https://warpcast.com/myetherwallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

MEW Portfolio is an application that can be accessed in the browser at https://www.myetherwallet.com/, and can also be downloaded to use offline or as a PWA from https://github.com/MyEtherWallet/MyEtherWallet/releases, on MAC, Windows, or Linux.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No.

### Is it a hardware wallet?

No.

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

MIT

### Who holds the private keys?

Users hold their own private keys. MEW does not have any access to user keys or wallets. Users receive their keystore file or mnemonic phrase when generating a software wallet offline, and can use that information to import the wallet into any other Ethereum interface of their choice.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

All MEW Portfolio developers are required to be part of our organization and have 2FA enabled. MEW is partnered with HackenProof for penetration testing, and is using latest industry standards for hosting our services to ensure high up-time. https://hackenproof.com/programs/myetherwallet

### Has the wallet's smart contract code or security modules been audited?

MEW Portfolio is not audited, however, it does not use its own smart contract, and it’s client-side and non-custodial. MEW doesn't collect or hold personal user information, and doesn't have custody of user assets.

### Does the wallet have an internal security team?

No. MEW works with PhishFort to monitor and take down phishing websites, apps, and communications (like emails and socials accounts) that pretend to be MEW with similar names and visual assets.

### Any other security testing that should be noted?

No.

### Scam protection?

In addition to working with Phishfort to block and take down any fake websites and phishing communications with our users, we provide extensive educational materials about recognizing and avoiding crypto scams. For example: https://help.myetherwallet.com/en/articles/5377928-pro-tips-how-to-avoid-phishing-scams, https://www.myetherwallet.com/blog/avoid-these-common-crypto-scams-easy-money/

### Does the wallet support connecting to Ethereum applications?

Yes, several integrated applications are available including staking with Staked, ETH staking powered by Coinbase, ENS manager, and Aave.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No.

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

Yes, MEW Portfolio offers integrated Ethereum staking options for full validators with Staked and partial ETH staking powered by Coinbase.

### Does the wallet support swaps directly?

Yes, MEW Portfolio features swaps supported by integrated providers 1inch, 0x, Paraswap, Changelly.

### Does the wallet support bridging directly?

No.

### Does the wallet support multi-chain networks?

Yes, MEW Portfolio supports over a dozen EVM-compatible networks, including BNB Smart Chain, Polygon, Arthera, Gnosis, Ethereum Classic, and others. 

### Which Ethereum Layer 2 networks does the wallet support?

Arbitrum One, Optimism.

### Does the wallet allow the user to customize gas fees?

Users who connect with non-web3 wallets can choose from several gas settings.

### Does the wallet support sending transactions to ENS addresses?

Yes.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

MEW Portfolio supports all ERC-20 tokens automatically. Users can also add custom tokens using the token contract.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes.

### Does the wallet have any recovery options?

Yes, when using offline wallet generation, users receive their keystore file or recovery (mnemonic) phrase and can use them to restore their wallet in any other interface that supports those recovery methods. Users can also use MEW Offline to recover crypto wallets generated elsewhere, using private key, keystore file, or recovery phrase.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, MEW Portfolio users are able to buy crypto with a credit/debit card via integrated providers Simplex, MoonPay, and Topper.

### Does the wallet support withdrawals to fiat?

Yes, users can sell crypto and have fiat deposited into a bank account via integrated partner MoonPay.

### Is the wallet a multi-signature wallet?

No.

### Does the wallet support social recovery?

No.

### Does the wallet support bundled transactions?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

X (Twitter) DMs: https://x.com/myetherwallet
Telegram Vince Major: https://t.me/VinceM009
Github: https://github.com/myetherwallet/myetherwallet

### Does the wallet have a dedicated support team?

Yes, users can write to [support@myetherwallet.com](mailto:support@myetherwallet.com) for assistance, or go to the Help Center here https://help.myetherwallet.com/en/ and use the chat feature.

### What educational resources/documentation do you provide to users?

Help Center (documentation, guides): https://help.myetherwallet.com/en/
Blog (educational resources, guides): https://www.myetherwallet.com/blog

### Does the wallet have any integrated tools not mentioned above?

Users can add custom tokens, sign and verify messages, interact directly with smart contracts, deploy contracts.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @gamalielhere! I see #13659 as well, and just looking at the [MEW website](https://www.myetherwallet.com/) real quick trying to make sure I understand the different products.

- "MEW **Mobile** App" -- [we list this](https://ethereum.org/en/wallets/find-wallet/) as "MEW Wallet"
- "Enkrypt **Browser** Wallet" -- [we list this](https://ethereum.org/en/wallets/find-wallet/) as "Enkrypt", and I see #13659 which appears to be updating the information for that wallet

And this PR is now to list the "MEW **Portfolio Manager**", which IIRC, we used to have listed on ethereum.org as well, but had been removed at some point. I believe it was because this falls into a slightly different category of "portfolio manager", and doesn't actually handle generating/handling it's own keys.. effectively bring-your-own-keys, correct?

<img width="396" alt="image" src="https://github.com/user-attachments/assets/b4f3b18f-a752-4c7a-b799-5a108aeca80d">

<img width="695" alt="image" src="https://github.com/user-attachments/assets/151c6910-3477-483f-b3fd-e501b609ca31">

@konopkja @corwintines Any thoughts on this? If I'm correct, it's akin to the desktop Ledger Live app in many ways, or Zerion, MEW just isn't selling their own hardware wallet. This ultimately feels like it falls into the "dapp" category more than the "wallet" category.

On https://ethereum.org/en/dapps/ :

<img width="853" alt="image" src="https://github.com/user-attachments/assets/c1c3138b-55b3-490f-b53d-4451dd49396f">

**Comment by konopkja** [comment]
if its not a wallet that is able to generate ethereum account, it should not be on the find wallets page

**Comment by gamalielhere** [comment]
> Thanks @gamalielhere! I see #13659 as well, and just looking at the [MEW website](https://www.myetherwallet.com/) real quick trying to make sure I understand the different products.
> 
> * "MEW **Mobile** App" -- [we list this](https://ethereum.org/en/wallets/find-wallet/) as "MEW Wallet"
> * "Enkrypt **Browser** Wallet" -- [we list this](https://ethereum.org/en/wallets/find-wallet/) as "Enkrypt", and I see [Suggest a wallet #13659](https://github.com/ethereum/ethereum-org-website/issues/13659) which appears to be updating the information for that wallet
> 
> And this PR is now to list the "MEW **Portfolio Manager**", which IIRC, we used to have listed on ethereum.org as well, but had been removed at some point. I believe it was because this falls into a slightly different category of "portfolio manager", and doesn't actually handle generating/handling it's own keys.. effectively bring-your-own-keys, correct?
> 
> <img alt="image" width="396" src="https://private-user-images.githubusercontent.com/54227730/358694412-b4f3b18f-a752-4c7a-b799-5a108aeca80d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTAyMTMsIm5iZiI6MTcyNDA4OTkxMywicGF0aCI6Ii81NDIyNzczMC8zNTg2OTQ0MTItYjRmM2IxOGYtYTc1Mi00YzdhLWI3OTktNWExMDhhZWNhODBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE3NTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YmE0OTc2MGE4NjQwNDA0Yjc4MjJmOGEyN2M5NTA5ODQxOGFjMDYzZGRlNThlOGM2MTA5NmExMjNmYmQ0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ET7OSRWRafwcvUoxoySFc2GaynimO4fKGv31plP06bY"> <img alt="image" width="695" src="https://private-user-images.githubusercontent.com/54227730/358694323-151c6910-3477-483f-b3fd-e501b609ca31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTAyMTMsIm5iZiI6MTcyNDA4OTkxMywicGF0aCI6Ii81NDIyNzczMC8zNTg2OTQzMjMtMTUxYzY5MTAtMzQ3Ny00ODNmLWIzZmQtZTUwMWI2MDljYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE3NTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3N2NiNmUxNDU0ZGUwNzdmMzg1N2NiZDZhOWY3YTk0YTk3ZGYxY2I0ZWMwM2FjN2NjMjg2ZTI5ZDhhNWQ3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-tUtByol7WQpe_24Xu-pN9uGj7aHPvxl7poSJJsUdc">
> @konopkja @corwintines Any thoughts on this? If I'm correct, it's akin to the desktop Ledger Live app in many ways, or Zerion, MEW just isn't selling their own hardware wallet. This ultimately feels like it falls into the "dapp" category more than the "wallet" category.
> 
> On https://ethereum.org/en/dapps/ :
> 
> <img alt="image" width="853" src="https://private-user-images.githubusercontent.com/54227730/358726793-c1c3138b-55b3-490f-b53d-4451dd49396f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTAyMTMsIm5iZiI6MTcyNDA4OTkxMywicGF0aCI6Ii81NDIyNzczMC8zNTg3MjY3OTMtYzFjMzEzOGItNTViMy00OTBmLWI1M2QtNDQ1MWRkNDkzOTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE3NTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZjM4MmZhNWFmOGViYWJkOWU0N2Q5ZTBiZjIxYWM4NjkyNDQ1YmRmMGM5YWY3MmE5YThhOTE5YTA3ZTk5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AXgkhBjSiu89VSCnjdoxV8dtA3UVui5bzTMYS7Zx2Ow">

Correct, MEW Mobile is our newer way of branding the mobile app which was submitted as "MEW Wallet" last time.

Enkrypt is our browser extension, submitted as Enkrypt last time and as Enkrypt (for wallet name) again this time.

The MEW Portfolio manager does work as a dapp that allows users to 'bring their own wallet' and then manage assets, use integrated dapps, etc. However, it is also possible to create a software wallet on MEW Portfolio, both online and offline. We have multiple warnings for users about choosing the offline method if they are creating a software wallet. See following guides for info:
https://help.myetherwallet.com/en/articles/5979837-how-to-create-an-ethereum-wallet-with-mew#h_738dbb025a
https://help.myetherwallet.com/en/articles/6512619-using-mew-offline

**Comment by gamalielhere** [comment]
> if its not a wallet that is able to generate ethereum account, it should not be on the find wallets page

It is able to generate mnemonic phrase and keystore files still. Do we still submit it as a wallet or as a Dapp?

**Comment by konopkja** [comment]
> > if its not a wallet that is able to generate ethereum account, it should not be on the find wallets page
> 
> It is able to generate mnemonic phrase and keystore files still. Do we still submit it as a wallet or as a Dapp?

seeing this as primarily dashboard it be leaning more towards a dapp

**Comment by konopkja** [comment]
closing this issue and please open a new one for a dapp listing
