### ISSUE TITLE
RAISON wallet 

### ISSUE THREAD

**Issue by ElenaRaison** [ethereum/ethereum-org-website#1369]
I want to suggest RAISON app for listing. RAISON lets users get smart contracts for pre-IPO investment products from €100, operate and store ETH, BTC, USDC. It's a non-custodial wallet. Remote onboarding takes about 6 minutes and is provided by Snapswap. Using Ethereum blockchain technology, we have created a first fully compliant legal structure for the tokenization of large-cap private companies' shares (SpaceX, Airbnb, Robinhood) and offer accessible pre-IPO investments via digital units.

RAISON was founded in 2017, operates under the following licenses:
- Virtual currency wallet service, FRK000449
- Exchange services between virtual currencies and fiat currencies, FVR000536
In the USA, it's registered by Financial Crimes Enforcement Network (FinCEN) as Money Service Business (MSB),
Registration: №: 31000139013650

Website – https://raison.ai/
Email – e.milosheska@raison.ai

**Comment by samajammin** [comment]
Hey @ElenaRaison - sorry for the delay here. We recently published [our listing policy](https://www.ethereum.org/en/contributing/adding-products/) for wallets. Could you please 1) confirm it meets our requirements (& close the issue if not) and 2) answer the questions below? Thanks!

***

Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does, complete the following information which we need to accurately list the wallet.

**Does the wallet have fiat on-ramps?**

Does the wallet subsidise transaction fees for all or some wallet activity? 

**Does the wallet allow users to explore dapps?**

Is the wallet integrated with WalletConnect? Does it have a dapp browser? Or can users connect to a dapp using the wallet?  

**Does the wallet have integrated defi/financial tools?**

Can users borrow/earn/lend assets directly from a screen in the wallet?  

**Can a user withdraw to their card?**

Can a user cash out their crypto assets directly to a card or bank account? 

**Does the wallet offer limits protection?**

Can a user set a limit for transfers to protect their assets? 

**Does the wallet allow high-volume purchases?**

Can a user buy more than $2000 worth of crypto in one go? 

**Does the wallet have an integrated token swap?**

Can a user swap ETH for other tokens from within a screen in the wallet? 

**Is the wallet a multi-signature wallet?**

Can a user opt to require multiple signatures to authorise transactions? 

**Wallet title**

Please provide the official name of the wallet 

**Wallet description**

Please provide a short 1-2 sentence description of the wallet 

**Wallet logo**

Please provide a hi-res SVG or transparent PNG 

**Brand color**

Please provide a hex code for the brand color. This will be added to the background of the wallet card.

**Comment by ElenaRaison** [comment]
I confirm that the wallet meets the requirements in your listing policy.  

**Does the wallet have fiat on-ramps?** 

Yes, EURO

**Does the wallet subsidise transaction fees for all or some wallet activity?** 

Yes, subside for fiat-to-ETH purchase by paying the blockchain fee for the incoming ETH transaction

**Does the wallet allow users to explore dapps?** 

No

**Is the wallet integrated with WalletConnect? Does it have a dapp browser? Or can users connect to a dapp using the wallet?** 

No

**Does the wallet have integrated defi/financial tools?** 

Yes, an ERC-20 tokenized assets of private equity companies

**Can users borrow/earn/lend assets directly from a screen in the wallet?**

No

**Can a user withdraw to their card?** 

Only to bank accounts

**Can a user cash out their crypto assets directly to a card or bank account?** 

Users can withdraw to bank account in EUR or in RUB

**Does the wallet offer limits protection?** 

No

**Can a user set a limit for transfers to protect their assets?** 

No

**Does the wallet allow high-volume purchases?**

Yes, no limits for fiat top-up via SEPA transfer, 15K EUR daily card payments limits

**Can a user buy more than $2000 worth of crypto in one go?**

Yes, no limits for purchase

**Does the wallet have an integrated token swap?** 

Currently no

**Can a user swap ETH for other tokens from within a screen in the wallet?** 

No

**Is the wallet a multi-signature wallet?** 

No

**Can a user opt to require multiple signatures to authorise transactions?** 

No

**Wallet title**

RAISON

Wallet description

**Please provide a short 1-2 sentence description of the wallet**

RAISON lets users get pre-IPO investment products from €100 and operate ETH, BTC, USDC and EUR currencies.

**Wallet logo**

https://drive.google.com/file/d/1LZZREceCchOrElpkwlGCTptgJn0ltbmV/view

**Brand color**

15b0db

**Comment by samajammin** [comment]
Thanks @ElenaRaison! @ryancreatescopy please review when able.

**Comment by ElenaRaison** [comment]
Hello! Just wanted to know, are there any updates on the decision?

**Comment by GeorgeTrotter** [comment]
Hey @ElenaRaison! Thanks for the follow up. We recently updated our listing policy [here](https://ethereum.org/en/contributing/adding-products/) to include global accessibility and non-custodial access. Last questions:

- Are there geographic limitations or KYC requirements that exclude certain people from accessing your service?

- Is Raison's wallet custodial or non-custodial?

Thanks!

**Comment by ElenaRaison** [comment]
Hello @GeorgeTrotter ! 
- Raison wallet is non-custodial
- Yes, we have limitations for certain countries. Our full terms of services can be found on our website. Last year, the Estonian government passed a law tightening the rules for obtaining licenses to work with virtual currencies. Only 140 companies out of more than 3000 primarily regulated ones were able to go through the new regulation procedure. And we successfully updated our licenses under the new laws!

**Here is the list of our geographical restrictions** 

If the Client is from or the seat of a Client being a legal person is located in a third country, which is included in the list of risk countries given in internal rules of procedure for prevention of money laundering and terrorist financing, and compliance with international sanctions the Provider of Service in it’s sole discretion decides if the Client is eligible for Raison Service according to due diligence measures taken.
Notwithstanding the above mentioned loading and withdrawal of fiat funds are totally prohibited for the following countries and territories: Turkey, United Arab Emirates, Bahrain, American Samoa, Antarctica, French Southern Territories, Antigua and Barbuda, Burundi, Benin, Bonaire Sint Eustatius and Saba, Burkina Faso, Bangladesh, Bahamas, Belize, Bermuda, Barbados, Brunei Darussalam, Bhutan, Bouvet Island, Botswana, Cocos Keeling Islands, Congo The Democratic Republic of, Cook Islands, Comoros, Cape Verde, Curacao, Christmas Island, Djibouti, Dominica, Algeria, Ecuador, Egypt, Western Sahara, Ethiopia, Fiji, Falkland Islands Malvinas, Micronesia Federated States of, Gabon, Gibraltar, Guinea, Guadeloupe, Gambia, Guinea Bissau, Equatorial Guinea, Grenada, Greenland, Guatemala, French Guiana, Guam, Guyana, Heard Island and McDonald Islands, Honduras, Haiti, Indonesia, British Indian Ocean Territory, Iran Islamic Republic of, Iraq, Jersey, Jordan, Kenya, Kyrgyzstan, Cambodia, Kuwait, Lao Peoples Democratic Republic of, Lebanon, Liberia, Libyan Arab Jamahiriya, Saint Lucia, Sri Lanka, Lesotho, Saint Martin, Morocco, Madagascar, Marshall Islands, Mali, Myanmar, Mongolia, Mozambique, Mauritania, Montserrat, Martinique, Mauritius, Malawi, Malaysia, Mayotte, Namibia, New Caledonia, Niger, Norfolk Island, Nigeria, Niue, Nepal, Oman, Pakistan, Panama, Pitcairn, Philippines, Palau, Papua New Guinea, Puerto Rico, Paraguay, Palestinian Occupied Territory, French Polynesia, Qatar, Reunion, Rwanda, Saudi Arabia, Sudan, Senegal, South Georgia and the South Sandwich Islands, Saint Helena Ascension and Tristan da Cunha, Sierra Leone, El Salvador, Saint Pierre and Miquelon, South Sudan, Sao Tome and Principe, Suriname, Swaziland, Sint Maartin, Syrian Arab Republic, Turks and Caicos Islands, Chad, Togo, Tajikistan, Tokelau, Timor Leste, Tonga, Trinidad and Tobago, Tunisia, Taiwan, Tanzania United Republic of, Uganda, United States Minor Outlying Islands, Holy See Vatican City State, Saint Vincent and the Grenadines, Virgin Islands US, Vanuatu, Wallis and Futuna, Yemen, Zambia, Aruba, Afghanistan, Angola, Aland Islands, North Korea, Crimea, Somalia.

**Comment by ElenaRaison** [comment]
@GeorgeTrotter Hey! Just wanted to ask, are there any updates? Thank you in advance!

**Comment by GeorgeTrotter** [comment]
Hey Elena! My sincere apologies for the delay here. We recently updated our [listing policy](https://ethereum.org/en/contributing/adding-products/) to include a focus for wallets and dapps which are globally accessible, in that they don't have geographic limitations or KYC requirements that exclude certain people from accessing your service. From a user experience perspective we can only list so many wallets, and unfortunately given the geographical restrictions you've outlined we won't be able to list Raison. Again, my apologies for not getting back to you last week 

If there are changes in Raison's geographical restrictions in the future please let us know and we'd be happy to review this again!
