### ISSUE TITLE
Remove Truffle references from ethereum.org as Truffle has been sunset

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#13703]
### Describe the bug

With the sunset of Truffle, we need to remove references to Truffle from ethereum.org to avoid any confusion or outdated information. We should also ensure that unnecessary intl strings related to Truffle are also removed.

### To reproduce

1. Go to 'https://ethereum.org/en/developers/local-environment/'
2. Scroll to 'Frameworks and pre-made stacks'
3. See error

### Additional context

I've highlighted one example on [our local environment page](https://ethereum.org/en/developers/local-environment/), but I'm sure there are at least a few more across our developer docs 

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by omega000133** [comment]
Hello @minimalsm 
I am interested with this work.
I will fix this issue asap.
Thank you.

**Comment by minimalsm** [comment]
Thanks @omega000133, I've assigned you :)

**Comment by omega000133** [comment]
Nice. thanks

**Comment by Shiva-Sai-ssb** [comment]
Similar as issue #11262

**Comment by minimalsm** [comment]
Hey @omega000133, any update here? 

Sorry for the quick ping, but looking to get this out soon :)

**Comment by omega000133** [comment]
sorry for late reply.
suddenly i have a busy project.
i will actively participate in future contributions.
thank you for your understanding

**Comment by sumitvekariya** [comment]
I have started working on this task,

Following questions:

- What to do with the articles https://github.com/ethereum/ethereum-org-website/blob/fb601b2a10dd0590e6ed1b7c85b26d979ff175f1/public/content/developers/tutorials/create-and-deploy-a-defi-app/index.md#L1 like this, which mentions truffle & ganache?

@minimalsm

**Comment by minimalsm** [comment]
Mmm thanks for calling out @sumitvekariya. Could you maybe just add some text at the beginning saying Truffle is deprecated?

We can work on this separately (perhaps migrating the tutorial to a different tool), but obviously that's beyond the scope of this issue.

**Comment by sumitvekariya** [comment]
Thanks, one more question, when I remove the word `truffle` & its references, should I remove it from all the translations `content/translation/[language]`? 

because there are too many & some translations might become inaccurate

**Comment by wackerow** [comment]
Fixed with #13738
