### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by cryptofriend** [ethereum/ethereum-org-website#13709]
### Wallet name

Zerion

### What type of wallet?

EOA

### Wallet description

A crypto wallet for everything onchain - from tokens and NFTs to staked assets and the best of DeFi.

### Wallet logo

![zerion-icon_square-rounded](https://github.com/user-attachments/assets/e81dcf6c-2d71-4309-b98f-b8ccbd61424c)
![zerion-lockup_main](https://github.com/user-attachments/assets/ca1e4363-773c-43fb-81a7-5a0a57d1a85b)

### Background color for brand logo

#3232DC

### URL to the project

https://zerion.io/download

### When did the wallet go live to users?

May 2022

### What are the fees users may be paying for using your wallet product?

Swap fee - 0.8%
Onramp fee - 1%

### Does the wallet have an active development team?

https://github.com/zeriontech

### Is the wallet globally accessible?

It's globally accessible, not required KYC

### Is the wallet available in multiple languages?

Mobile: English, Russian, Chinese simplified and soon French and Spanish
Web Extension: English

### What social links are there for the project?

https://x.com/zerion
https://zerion.io/discord
https://warpcast.com/zerion.eth

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Mobile: iOS, Android, 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Desktop: macOS

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Web: Chromium

### Is it a hardware wallet?

no

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

The core (cryptography and key management) are open sourced on extension and mobile apps

### Who holds the private keys?

self custodial, user holds private keys

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We did the security audit for all the parts that are about seed phrase / private key handling

### Has the wallet's smart contract code or security modules been audited?

Yes, we haven't published security audit docs, but can provide due request. 

### Does the wallet have an internal security team?

No, it's outsourced 

### Any other security testing that should be noted?

For UX we use such defense approaches:
- phishing checks in dapp browsers and Extension
- security transaction checks with Blockaid 
- transaction simulation 

### Scam protection?

Yes, powered by Blockaid

### Does the wallet support connecting to Ethereum applications?

WC, Dapp browser, Regular browser (Extension), Coinbase link 

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

Yes

### Does the wallet support swaps directly?

Yes

### Does the wallet support bridging directly?

Yes

### Does the wallet support multi-chain networks?

Yes

### Which Ethereum Layer 2 networks does the wallet support?

https://developers.zerion.io/reference/supported-blockchains

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, it happens automatically. No need to import manually

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, we support it across all networks where chain support this standard

### Does the wallet have any recovery options?

Use can back up the key with icloud 

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Via onramps (Moonpay, Ramp, Onramper, Mercuryo). It's integrated in UI across all platforms

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Does the wallet support bundled transactions?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Email: boogaav@zerion.io
Telegram: @boogaav 
X & other socials: @boogaav

### Does the wallet have a dedicated support team?

Yes. Users can chat with our team at the support page
https://help.zerion.io/en/

Or drop a request in Discord https://discord.com/invite/BDtsbCunWF

### What educational resources/documentation do you provide to users?

https://help.zerion.io/en/collections/5525626-zerion-wallet
https://zerion.io/blog/tag/learn/ 

### Watchlist
1. We have a search feature; you can search for any wallet and see its aggregated portfolio along all supported chains
2. Also, you can follow a particular wallet and get notified when this wallet processes a transaction.### Human readable TX history 

### Others 
1. Zerion has one of the most advanced TX histories, which is aggregated along all supported chains.
2. PNL feature 
3. Export TXs 
4. Aggregated portfolio along all your wallets
5. Automated token discovery
6. Tracking protocols positions 

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by konopkja** [comment]
L2s: Arbitrum, Base, Blast, Linea, Optimism, Scroll, zkSync

**Comment by konopkja** [comment]
ok LGTM, needs PR

**Comment by konopkja** [comment]
> what needs to be done here? from dev perspective? do you want me to add your wallet details here for additional discovery if i am not wrong? https://ethereum.org/en/wallets/find-wallet/ please assign me this issue

the wallet is already listed on that URL, what needs to be done is to update metadata for the wallet based on this issue

**Comment by KatrixReloaded** [comment]
Hey @konopkja , could you please assign this task to me?

**Comment by KatrixReloaded** [comment]
Hey, I've made the changes to the metadata but I don't see any fields for some details mentioned in the issue like the EIP-1559 type 2 txs, backing up the key with icloud, the on-ramps and the contact info for ethereum.org to use. Am I supposed to add those details anywhere?

**Comment by konopkja** [comment]
> Hey, I've made the changes to the metadata but I don't see any fields for some details mentioned in the issue like the EIP-1559 type 2 txs, backing up the key with icloud, the on-ramps and the contact info for ethereum.org to use. Am I supposed to add those details anywhere?

some details are enough to be kept here in the issue, not all is in metadata
