### ISSUE TITLE
Broken Link for Azure Blockchain Workbench

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [ethereum/ethereum-org-website#13712]
### Describe the bug

 The Azure Blockchain Workbench link is currently broken on the [Ethereum.org developers page](https://ethereum.org/en/developers/docs/ides) under the "Desktop IDEs" section. This link either needs to be updated with a new, working URL or removed from the page if no replacement is available.

### To reproduce

1. Go to the [Ethereum.org developers page for IDEs](https://ethereum.org/en/developers/docs/ides).
2. Scroll down to the "Desktop IDEs" section.
3. Click on the "Azure Blockchain Workbench" link.
4. Observe that the link is broken and does not lead to the intended destination.

### Expected behavior

The link should either be updated to direct users to a valid page related to Azure Blockchain Workbench or removed if no valid link is available.

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by UNOFFICIALbgd** [comment]
On September 10, 2021, Azure Blockchain was retired.
And (probably) On October 31, 2022 Azure Blockchain Workbench was retired.
https://learn.microsoft.com/en-us/answers/questions/929378/deploy-blockchain-workbench


So we should just remove this link

**Comment by Code-Hacker26** [comment]
@UNOFFICIALbgd  is this issue still open with the given link needed to be removed and if yes then can i work on this ?

**Comment by UNOFFICIALbgd** [comment]
@Code-Hacker26 Hi! I already deleted this link yesterday. I said about it in my previous comment right above

**Comment by Code-Hacker26** [comment]
@UNOFFICIALbgd  i had the same idea but as i saw the issue still open so i asked by

**Comment by corwintines** [comment]
Merged in your PR @UNOFFICIALbgd! Thank you.
