### ISSUE TITLE
Breadcrumbs should wrap

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1373]
**Describe the bug**

When breadcrumbs reach the edge of the screen, it should wrap onto a new line from the beginning of the component. A crumb should not wrap independently. 

We could also look into truncating a page (replacing a level with `...` if the breadcrumb gets too long. 

![image](https://user-images.githubusercontent.com/40891631/91329369-feedf980-e7bf-11ea-8694-f47acd7ad261.png)

**Comment by samajammin** [comment]
Nice spot @ryancreatescopy. Could you clarify what you mean by "it should wrap onto a new line from the beginning of the component". What should wrap in this instance? Just the "ADDING ARTICLES" text? Or what specifically?

**Comment by ryancreatescopy** [comment]
@samajammin 
![image](https://user-images.githubusercontent.com/40891631/91711287-95823800-eb7d-11ea-9c97-a21c495b1f5e.png)

**Comment by samajammin** [comment]
Solved in #1388
