### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by Lahannin** [ethereum/ethereum-org-website#13736]
### Wallet name

Trezor

### What type of wallet?

EOA

### Wallet description

Trezor is a highly secure, open-source hardware wallet designed for managing, trading, and staking crypto with ease. Use it with our easy-to-use Trezor Suite app or pair it with your favorite software wallet, such as MetaMask, Rabby, Backpack, or Rainbow, to securely interact with dApps and the Web3 ecosystem.

### Wallet logo

![trezor-main-logo-black-rgb](https://github.com/user-attachments/assets/a1ac92d1-ef93-4e33-99f9-714f8f41eb61)

### Background color for brand logo

#ffffff

### URL to the project

www.trezor.io

### When did the wallet go live to users?

2013

### What are the fees users may be paying for using your wallet product?

just the gas fee when sending

### Does the wallet have an active development team?

https://github.com/trezor/trezor-firmware

### Is the wallet globally accessible?

Yes, globally accessible.

### Is the wallet available in multiple languages?

English, Spanish, Czech, German, French 

### What social links are there for the project?

https://x.com/Trezor

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

- iOS: https://apps.apple.com/us/app/trezor-suite-lite/id1631884497
- Android: https://play.google.com/store/apps/details?id=io.trezor.suite

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Windows, mac & Linux: https://trezor.io/trezor-suite 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No, but we have a web version: https://trezor.io/trezor-suite 

### Is it a hardware wallet?

USB

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

GPLv3 https://github.com/trezor/trezor-firmware/blob/main/LICENSE.md

### Who holds the private keys?

Yes, users have access to their public and private keys. No one else has access to them. USers can access their funds even if Trezor were to disappear. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://github.com/orgs/trezor/discussions
https://trezor.io/support/a/how-to-report-a-security-issue

### Has the wallet's smart contract code or security modules been audited?

https://chainsecurity.com/security-audit/everstake-eth-b2c-staking/ https://ackeeblockchain.com/blog/everstake-ethereum-staking-protocol-audit-summary/

### Does the wallet have an internal security team?

Yes, we have a security team

### Any other security testing that should be noted?

Bug Bounty program. https://trezor.io/support/a/how-to-report-a-security-issue

### Scam protection?

 ERC20 scam airdrops are obfuscated.

### Does the wallet support connecting to Ethereum applications?

Yes, e.g. MetaMask, Rabby support Trezor.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support staking directly?

Yes. https://content.trezor.io/eth-staking

### Does the wallet support swaps directly?

Yes.  https://trezor.io/learn/a/exchange-crypto-in-trezor-suite

### Does the wallet support bridging directly?

yes.  https://trezor.io/learn/a/exchange-crypto-in-trezor-suite

### Does the wallet support multi-chain networks?

n/a

### Which Ethereum Layer 2 networks does the wallet support?

~Polygon PoS~ (not L2, edit from core team)

### Does the wallet allow the user to customize gas fees?

Yes, via custom gas setting

### Does the wallet support sending transactions to ENS addresses?

no

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

The firmware supports EIP-1559 (type 2) transactions. Trezor Suite support in H2 2024

### Does the wallet have any recovery options?

12 & 24w BIP-39, single-share & multi-share SLIP-39

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

https://trezor.io/learn/a/buy-crypto-in-trezor-suite

### Does the wallet support withdrawals to fiat?

no

### Is the wallet a multi-signature wallet?

https://trezor.io/learn/a/what-is-multisig

### Does the wallet support social recovery?

no

### Does the wallet support bundled transactions?

no

### Who can the ethereum.org team can contact regarding the wallet in future?

https://x.com/trezor https://trezor.io/support

### Does the wallet have a dedicated support team?

Yes, dedicated support team. First response in 1-2 days. https://trezor.io/support

### What educational resources/documentation do you provide to users?

https://trezor.io/learn

### Does the wallet have any integrated tools not mentioned above?

Tor for privacy

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by konopkja** [comment]
hi @Lahannin  thank you for the submission! LGTM

Do you want to make PR yourself with updated metadata or shall we give it to the community / core team?

**Comment by Lahannin** [comment]
Hi,

I am just a poor marketing person who was asked to update this info so
please, if you could give it to the community / core team, that would be
great!

Thank you!

-Lauri Hanninen

ke 28. elok. 2024 klo 14.35 Jakub ***@***.***) kirjoitti:

**Comment by p1kalys** [comment]
Hey @konopkja, Does this issue solved? If not, can you please explain what's the expected behavior ? I would like to work on it.

**Comment by konopkja** [comment]
> Hey @konopkja, Does this issue solved? If not, can you please explain what's the expected behavior ? I would like to work on it.

we need a PR to update metadata for this wallet listed https://ethereum.org/en/wallets/find-wallet/

**Comment by konopkja** [comment]
https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/wallets/wallet-data.ts

**Comment by p1kalys** [comment]
Just checked it, Trezor already exists in the wallet.

**Comment by konopkja** [comment]
yes this is a metadata update on exisiting product, some metadata may be different and the date of last update needs to be changed as well
