### ISSUE TITLE
Add fallback redirects for requests that don't include a language path

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1374]
**Is your feature request related to a problem? Please describe.**

Requests to pages without a language path (e.g. https://ethereum.org/eth2) currently 404.

I imagine it's easy to forget the language path when linking to pages. I myself just did this (& I build the darn site):

**Describe the solution you'd like**
- Come up with a way to automatically redirect pages to English equivalent if the requested page doesn't exist
- Ideally this accomplished using a redirect rule in [our netlify.toml](https://github.com/ethereum/ethereum-org-website/blob/dev/netlify.toml) ([docs here](https://docs.netlify.com/configure-builds/file-based-configuration/#redirects))

**Describe alternatives you've considered**
- Manually add a redirect from every base page (e.g. https://ethereum.org/eth2 --> https://ethereum.org/en/eth2) 👎 
- Add additional info on [our 404 page](https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/404.js) (e.g. mention something like "is your URL missing a language path?")

**Additional context**
I tried the automatic route using our intl plugin but it lead to this issue: https://github.com/ethereum/ethereum-org-website/issues/1347
**Note: this approach may become a valid solution again once we roll out every page for every language!**

Docs on redirects using netlify.toml: https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

**Comment by samajammin** [comment]
@ryancreatescopy curious to hear your thoughts on this - is site search an adequate solution? Or would some additional copy be helpful here?

**Comment by ryancreatescopy** [comment]
I think content is a bit of a band-aid to this problem but it couldn't hurt to add a suggestion here to check the language path (providing we think the user knows what their language path is). Ideally, I'd like us to pursue the automatic redirect or even better redirect to a language based on something else like browser language or something else that could help us make a best guess about what language the user might want (fallback being English with a toast(?) that explains the page isn't available in their desired language)

**Comment by samajammin** [comment]
This is still an issue.

**Comment by samajammin** [comment]
Once we roll out every page for every language (#2072), we'll be able to solve this via the `redirect` config option in our intl plugin: https://github.com/wiziple/gatsby-plugin-intl
