### ISSUE TITLE
Ethereum for swift Developers 

### ISSUE THREAD

**Issue by Veeit** [ethereum/ethereum-org-website#1375]
Hey people out there in the Internet, 

I saw that the [developer page](https://ethereum.org/en/developers/) don't show language support for Swift. Is there any ?

**Comment by samajammin** [comment]
Hey @Veeit - thanks for raising this issue! You're correct, we don't currently list any Swift resources. We can add a TODO to create a page under our language-specific resources: https://ethereum.org/en/developers/#language-specific-resources

In the meantime, I found these 2 projects after a quick Google.
- https://github.com/argentlabs/web3.swift
- https://github.com/Boilertalk/Web3.swift

I haven't vetted these projects (I've never written Swift code) but at first glance, the Argent Labs project looks like it's more actively maintained.

Hope that helps!

For anyone who is interested in contributing a page for Swift Ethereum resources, we welcome PRs!

**Comment by samajammin** [comment]
@all-contributors please add @Veeit for ideas
