### ISSUE TITLE
Add Rollspace PVP Games

### ISSUE THREAD

**Issue by Buzzspace** [ethereum/ethereum-org-website#13775]
### Name

Rollspace

### Dapp URL

www.rollspace.com

### Description

Rollspace is crypto gamefi project built on Blast L2, where you can Play and Earn Ethereum (ETH) with crypto PVP games. Connect your crypto wallet and start playing multiplayer crypto games and earn your opponents ETH.

### Logo

![logo-bg_blue-512](https://github.com/user-attachments/assets/a01fb465-0680-4274-a256-4d565dc93a99)
![logo-bg_blue-512@2x](https://github.com/user-attachments/assets/c37fd315-bc1e-445c-a4f7-76ee8ecc308d)

### Brand color

#5162FF

### Is your dapp open source?

No

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Our dapp is running for more than a year without any issues, can be checked in archives or how long we run our twitter accounts or socials. 

### Can a user access the dapp without creating an account?

Yes, only crypto wallet is required to connect to the dapp, we also offer wallet connect option to scan qr code to connect.

### Are dapp funds non-custodial?

Yes, users can still withdraw funds via smart contract even if the frontend is not available.

### Do you offer community support?

Discord: https://discord.gg/7v7VKMxxQT
Telegram: https://t.me/rollspacecom

### Describe any geographical restrictions on usage of your dapp

N/A

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by konopkja** [comment]
<img width="877" alt="Screenshot 2024-09-15 at 21 37 38" src="https://github.com/user-attachments/assets/d5e14f07-7d90-4940-9be5-7a6ad091d38c">

issue with metamask

**Comment by konopkja** [comment]
still not working, tried on coinbase wallet and also not working. Do not reopen until properly fixed

**Comment by konopkja** [comment]
> Hey @konopkja hope we can give it another test?


https://github.com/user-attachments/assets/48fec14a-20fd-4713-bccd-4532398cd048
