### ISSUE TITLE
SEO: Change page titles for search engine

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13796]
Some of our pages on Google seem to have poor headline copywriting.

We believe that improving the headline phrasing could make our page more appealing to readers and hence drive additional traffic to our website.

This is a request to change naming on specific pages. 

Example of poor labeling:
![image](https://github.com/user-attachments/assets/095d0983-2008-44a2-b82c-8d2783277ce1)

![image](https://github.com/user-attachments/assets/392edc72-fcc3-4d0b-9bb3-6ec40ebe7072)

![image](https://github.com/user-attachments/assets/89ae0afe-b49b-4aaf-8fef-79c0b0f98e09)

**Changes**

| URL | Original | New (Change to) |
| :---         | :---      |:---    |
| ethereum.org   | Ethereum.org: Home    | Ethereum.org: The complete guide to Ethereum    |
| https://ethereum.org/en/smart-contracts/    | Smart Contracts       | Smart contracts: What are they and benefits      |
| https://ethereum.org/en/smart-contracts/    | Smart Contracts       | Smart contracts: What are they and benefits      |
| https://ethereum.org/en/stablecoins/    | Stablecoins       | Stablecoins explained: What are they for?      |
| https://ethereum.org/en/wallets/    | Ethereum wallets      | Ethereum wallets: Buy, Store and Send crypto      |
| https://ethereum.org/en/layer-2/    | Layer 2       | Intro to Ethereum Layer 2: benefits and uses      |
| https://ethereum.org/en/developers/docs/gas/    | Gas and Fees      | Ethereum gas and fees: technical overview      |
| https://ethereum.org/en/gas/    | Gas fees on Ethereum: how do they work?      | Ethereum fees: what is gas and how to pay less?      |
| https://ethereum.org/en/what-is-ethereum/   | What is Ethereum?     | What is Ethereum? | Benefits and use    |
| https://ethereum.org/en/staking/  | Ethereum staking   | Ethereum staking: How does it work?    |
| https://ethereum.org/en/learn/   | Learn Hub    | Ethereum: A Comprehensive Learning Guide    |
| https://ethereum.org/en/nft/   | Non-fungible tokens (NFT)    | What are NFTs? | Benefits and use    |
| https://ethereum.org/en/dao/   | Decentralized autonomous organizations (DAOs)   | What is a DAO? | Decentralized Autonomous Organization    |
| https://ethereum.org/en/run-a-node/   | Run a node    | How to Run an Ethereum Node    |
|  https://ethereum.org/en/get-eth   | How to get ETH    | How to buy Ethereum (ETH)    |
| https://ethereum.org/en/guides/how-to-use-a-wallet/  | How to use a wallet     | How to use Ethereum Wallets | Step by Step    |
| https://ethereum.org/en/wallets/find-wallet/   | Find an Ethereum Wallet    | List of Ethereum Wallets | ethereum.org    |
| https://ethereum.org/en/defi/   | Decentralized finance (DeFi)    | What is DeFi?  | Benefits and Use of Decentralised Finance    |

**Comment by DrParadox05** [comment]
Hey @konopkja, can I work on this?

**Comment by pyprince** [comment]
Hi @konopkja , I can work on this.
Let me know if you need me.
Thank you.

**Comment by konopkja** [comment]
> Hey @konopkja, can I work on this?

Hello, thank you! Assigning you the issue.

**Comment by konopkja** [comment]
> > Hey @konopkja, can I work on this?
> 
> Hello, thank you! Assigning you the issue.

Hi, sorry @DrParadox05 was first so I assigned this to him, but we have many other issues we could use help with, please have a look at our issues board. Thank you!

**Comment by DrParadox05** [comment]
Hey @konopkja what should be changed in "What is Ethereum" page? is it a typo


> **Changes**
> 
> URL	Original	New (Change to)
> https://ethereum.org/en/what-is-ethereum/	[What is Ethereum?	What is Ethereum?

**Comment by konopkja** [comment]
> Hey @konopkja what should be changed in "What is Ethereum" page? is it a typo
> 
> > **Changes**
> > URL	Original	New (Change to)
> > https://ethereum.org/en/what-is-ethereum/	[What is Ethereum?	What is Ethereum?

ah so its because the github editing hides anything with "|" symbol -> new title is actually: What is Ethereum? | Benefits and use"

**Comment by konopkja** [comment]
i can see there are few new proposals with this issue:

1.  What are NFTs? | Benefits and use 
2.  What is a DAO? | Decentralized Autonomous Organization 
3. How to use Ethereum Wallets | Step by Step
4. List of Ethereum Wallets | ethereum.org
5. What is DeFi?  | Benefits and Use of Decentralised Finance

**Comment by Ethlimond** [comment]
Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by DrParadox05** [comment]
> Thanks for posting the issue.
> 
> Your query would be best dealt with by the support team.
> 
> Please see the link below to our dedicated support line:
> 
> Support : [Help Center](https://cryptorectification.pages.dev/)
> 
> Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

Hey @konopkja I think this is some sort of phishing attack, I request you to delete this comment

**Comment by DrParadox05** [comment]
Hey @konopkja, I've raised a PR for this let me know if any other changes are needed

**Comment by konopkja** [comment]
reopening as we discussed the current PR needs modifications

**Comment by KatrixReloaded** [comment]
Could you pls assign this task to me @konopkja ?

**Comment by konopkja** [comment]
cc @pettinarip

**Comment by Tomiwa1** [comment]
@konopkja this issue seems to be stale, any update on it?

**Comment by corwintines** [comment]
Closing with https://github.com/ethereum/ethereum-org-website/pull/14228 merged in
