### ISSUE TITLE
AlienFlowSpace DAO (DeFi, DeSci, GameFi, ReFi, RWA)

### ISSUE THREAD

**Issue by AitorAilen** [ethereum/ethereum-org-website#13818]
Please, need help for redo the Dapp web 3 of AlienFlowSpace DAO (DeFi, DeSci, GameFi, ReFi, RWA) Thanks

**Comment by konopkja** [comment]
provide links and explanation why this would be to the benefit of the user. This is poorly written issue, closing

**Comment by AitorAilen** [comment]
A qué te refieres? Tengo que rehacer la DAPP web de AlienFlowSpace DAO
(DeFi, DeSci, GameFi, ReFi, RWA) Gracias
