### ISSUE TITLE
Minor English grammatical issue

### ISSUE THREAD

**Issue by jcamilli** [ethereum/ethereum-org-website#1381]
**Describe the bug**

The [What is Ethereum](https://ethereum.org/en/what-is-ethereum/) page says the following:

> ![image](https://user-images.githubusercontent.com/1952742/91626058-d3167380-e979-11ea-9292-f0bb1a23fb67.png)

The phrase "...anyone to stop you receiving payments" should changed to "...anyone to stop you **from** receiving payments"

The code can be found here:
https://github.com/ethereum/ethereum-org-website/blob/0ad8cca82dfdb61b20a9302dc6d6df16de77e910/src/pages-conditional/what-is-ethereum.js#L239

References:
https://sentence.yourdictionary.com/receiving
https://ell.stackexchange.com/questions/258630/should-the-word-from-be-between-you-and-receiving

**Comment by samajammin** [comment]
Solved in #1382
