### ISSUE TITLE
Update Everstake Pooled Staking Solution info

### ISSUE THREAD

**Issue by omykhailovskyi** [ethereum/ethereum-org-website#13846]
### Project name

Everstake 0.1+ ETH staking

### Product type

Staking pool

### Logo

img
https://everstake.one/img/Everstake-logo.svg
https://everstake.one/img/Everstake-256.png
https://everstake.one/img/Everstake-1024.png
logo
https://everstake.one/logo/logo-big-black.svg
https://everstake.one/logo/logo-big-white.svg
https://everstake.one/logo/logo-small-white.svg
https://everstake.one/logo/logo-small-black.svg

### Description

Change values to next one
Battle Tested = True Live > 1 year, 14 September will be 1 year live
     "pctMajorityExecutionClient": 50, - Diversified 
      "pctMajorityConsensusClient": 50 - Diversified 

### Website

https://stake.everstake.one/ethereum/

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes, live > 1 year, 14 September will be 1 year live

### What wallets support the product or service?

Trezor, Exodus, ZenGo

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

0.1 ETH

### If a service, what are the fees associated with using the service?

10%

### What date did the project or service go live?

14.09.2023

### Has the project undergone an external security audit?

Yes.
Chainsecurity and Ackee
https://www.chainsecurity.com/security-audit/everstake-eth-b2c-staking
https://ackee.xyz/blog/everstake-ethereum-staking-protocol-audit-summary/

### Has the project undergone any security bug bounties?

No

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Everstake's solution is free of trusted/human intermediaries.

### If a pooled staking service, can users participate as a node operator without permission?

There is no option to run an operator within the pool by some user. The only node operator is Everstake, which is responsible for running all validators for staked ETH.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

Within our ETH staking solution rewards from all validators goes to a predefined address in the smart contract. We solely use Withdraw Authority / execution address, known as “type 1” withdrawal credentials.

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

We run 25% Geth Nimbus, 25% Geth Prysm, and 25% Nethermind Teku, 25% Nethermind Lighthouse on the EL. 
As for CL, we prefer using Ligthouse 50%, Nimbus ~ 45% and Teku ~5%

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

All of them - Lighthouse, Teku, Nimbus, Prysm

### What user interfaces are supported?

Our own web app; browser extensions; mobile, desktop and web apps that integrated with our solution

### Social media links

"discord": "https://discord.gg/NvcW47V3Xb",
"twitter": "https://twitter.com/everstake_pool",
"medium": "https://medium.com/everstake"

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
> We run 25% Geth Nimbus, 25% Geth Prysm, and 25% Nethermind Teku, 25% Nethermind Lighthouse on the EL.

These are EL<>CL pairs (Geth/Nethermind are EL, but Nimbus/Prysm/Teku/Lighthouse are CL).. Should we interpret this as 50% Geth, 50% Nethermind?

**Comment by wackerow** [comment]
If that's the case, looks like we need to update `pctMajorityExecutionClient` and `pctMajorityConsensusClient` values to `50`.

The "Battle Tested" indicator is based on the existing launch date, and this has already updated to a green check in production.

@omykhailovskyi I see you marked "Yes" yo wanting to work on this. I'll go ahead and assign.. if you wouldn't mind just clarifying the above question, then a PR is welcome! Thanks

**Comment by omykhailovskyi** [comment]
Hey, @wackerow 
Thanks.
So basically need to adjust value for pctMajorityConsensusClient, as we now meet the requirement - Service should not run more than 50% of their aggregate validators with a majority consensus client

**Comment by wackerow** [comment]
I see you've unassigned yourself, I'll assign myself to handle

**Comment by irina-everstake** [comment]
@wackerow, really appreciate your help 🙏
