### ISSUE TITLE
Fix Issue with table formatting

### ISSUE THREAD

**Issue by gconnect** [ethereum/ethereum-org-website#13869]
### Is your feature request related to a problem? Please describe.

<img width="928" alt="Screenshot 2024-09-15 at 2 18 40 AM" src="https://github.com/user-attachments/assets/e1112125-83b4-4c89-9bc4-f608c1a53e21">

Currently the Consensus client section of this doc https://ethereum.org/en/developers/docs/nodes-and-clients/ is not properly formatted as shown in the above scrrenshot.

### Describe the solution you'd like

I want to format the table properly.

### Describe alternatives you've considered

Proper formatting

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Code-Hacker26** [comment]
@gconnect  can i work on this issue ?

**Comment by gconnect** [comment]
@isabelladebrito thanks for assigning it to me. Here is a link to the PR https://github.com/ethereum/ethereum-org-website/pull/13870
