### ISSUE TITLE
Bug report: event text too long - introduce character limit

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13914]
### Describe the bug

The event description has no text limitation and can become too long.  At some point it can break design + looks messy with other events combined with less text next to it.

**We need to introduce a character limit for event description:**

**Max characters:** 230

Then cut and show three dots
... 

### To reproduce

Go to https://ethereum.org/en/community/events/

### Expected behavior

character limit of 230 characters

### Screenshots

<img width="851" alt="Screenshot 2024-09-20 at 10 55 16" src="https://github.com/user-attachments/assets/04650ff9-296d-44f9-a8f2-f2c530e0729a">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by sumitvekariya** [comment]
@konopkja Please assign this to me

**Comment by konopkja** [comment]
> @konopkja Please assign this to me

assigned, thank you!

**Comment by konopkja** [comment]
thank you for the fix @sumitvekariya
