### ISSUE TITLE
add the link to specific queries on the source links

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#13916]
### Describe the bug

when ever is possible we should link to the specific pages/queries on the big numbers on the homepage

example: the link for dune analytics should go to a dashboard and not the homepage

![Screen Shot 2024-09-20 10 02 01 AM](https://github.com/user-attachments/assets/a676b1c0-31cc-45fe-9804-d766b6fbd44d)

### To reproduce

1. Go to homepage
2. scroll to big numbers section
3. open the tooltip
4. click on the source link on the tooltip

### Expected behavior

change the source links

### Would you like to work on this issue?

- [ ] Yes
- [x] No

**Comment by Code-Hacker26** [comment]
Hi @nloureiro,
I'm interested in working on this issue but need a bit more clarity to ensure I'm addressing it correctly 
Specifically the link for dune analytics should go to a dashboard and not the homepage

**Comment by nloureiro** [comment]
> Hi @nloureiro, I'm interested in working on this issue but need a bit more clarity to ensure I'm addressing it correctly Specifically the link for dune analytics should go to a dashboard and not the homepage

Yes, that's correct. The idea is to give users the ability to verify the numbers on the most easy form possible

**Comment by wackerow** [comment]
Hey @Code-Hacker26! Thanks for the help.

Let me try to help outline this... we have four (4) homepage metrics:

**Value locked in DeFi**
_DeFi Llama_:
- Endpoint: https://api.llama.fi/charts/Ethereum
- Fetch logic: `src/lib/api/fetchTotalValueLocked.ts`
Most recent `totalLiquidityUSD ` value used

**Value protecting Ethereum**

_Dune Analytics_:
- Used to fetch the "total ETH staked" (in ETH)
- Endpoint: https://api.llama.fi/charts/Ethereum
- Fetch logic: `src/lib/api/fetchTotalValueLocked.ts`

_CoinGecko_:
- Used to fetch the "current ETH price" (in $/ETH)
- Endpoint: https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd
- Fetch logic: `src/lib/api/fetchEthPrice.ts`

We then multiply those together to get the total $ securing the network.

**Average transaction cost** AND **Transactions in the last 24h**
_GrowThePie_:
- Endpoint: https://api.growthepie.xyz/v1/fundamentals_full.json
- Fetch logic: `src/lib/api/fetchGrowThePie.ts`

```tsx
    const mostRecentDate = data.reduce((latest, item) => {
      const itemDate = new Date(item.date)
      return itemDate > new Date(latest) ? item.date : latest
    }, data[0].date)
```
^ Finds the `date` of the most recent available data, assigns to `mostRecentDate`

```tsx
    const mostRecentData = data.filter(
      (item) =>
        item.date === mostRecentDate &&
        [TXCOSTS_MEDIAN_USD, TXCOUNT].includes(item.metric_key)
    )
```
^ Grabs most recent data for transaction costs and counts, assigns to `mostRecentData`

```tsx
    let totalTxCount = 0
    let weightedSum = 0

    mostRecentData.forEach((item) => {
      if (item.metric_key !== TXCOSTS_MEDIAN_USD) return

      const txCountItem = mostRecentData.find(
        (txItem) =>
          txItem.metric_key === TXCOUNT && txItem.origin_key === item.origin_key
      )
      if (!txCountItem) return

      totalTxCount += txCountItem.value
      weightedSum += item.value * txCountItem.value
    })

    // The weighted average of txcosts_median_usd, by txcount on each network (origin_key)
    const weightedAverage = totalTxCount ? weightedSum / totalTxCount : 0
```

- `totalTxCount += txCountItem.value` is tallying up the cumulative tx counts for Mainnet + all Ethereum layer 2 networks
- `weightedSum += item.value * txCountItem.value` is tallying up the cumulative transaction-weighted median costs for each transactions on each network
- `weightedAverage` is then calculated by dividing the weight cost total by the total transaction count: `weightedSum / totalTxCount`

This produces the "Average transaction cost" metrics, spanning the L2's available from that endpoint.

---

Hope this helps summarize how/where the metrics come from. Any help organizing this info to present to users (cc: @nloureiro) would be most appreciated! Assigning you =)

**Comment by Code-Hacker26** [comment]
Hi @wackerow,
Thank you for assigning this to me! I’ll work on it and submit the PR as soon as possible.

Best regards,

**Comment by Code-Hacker26** [comment]
@nloureiro @wackerow, I've submitted the PR with updates to the four links in the homepage metrics section. Please review it and let me know if you have any suggestions or changes.

Thank you!
