### ISSUE TITLE
Add the ethereum.org repo on GitHub to goodfirstissue.dev

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#13923]
### Summary
ethereum.org is gearing up to take part of Hacktoberfest 2024 - in order to make our project visible to participants, I'd like to include our repo to [goodfirstissue.dev](https://goodfirstissue.dev/) (one of the resources listed on [Hacktoberfest's website](https://hacktoberfest.com/participation/))

### Task
1. Go to [goodfirstissue.dev](https://goodfirstissue.dev/)
2. Click at '[Add Your Project](https://github.com/DeepSourceCorp/good-first-issue#adding-a-new-project)'
3. Follow the instructions to add ethereum.org

**Comment by varun-doshi** [comment]
I can take this up

**Comment by varun-doshi** [comment]
https://github.com/DeepSourceCorp/good-first-issue/pull/787

**Comment by corwintines** [comment]
Thanks @varun-doshi!

Going to close this issue out as complete as we have the PR up now, but we are not in control of the process for DeepSourceCorp repo.
