### ISSUE TITLE
Bug in "Merkle patricia trie" page on mobile

### ISSUE THREAD

**Issue by UNOFFICIALbgd** [ethereum/ethereum-org-website#13930]
### Describe the bug

adresses are too long and go beyond the page

### To reproduce

1. Go to 'https://ethereum.org/en/developers/docs/data-structures-and-encoding/patricia-merkle-trie/'
2. See error

### Expected behavior

.

### Screenshots

bug
![image](https://github.com/user-attachments/assets/bd21d5ea-49a9-45c7-848e-23b937d91cd8)

reason of this behavior: 
![image](https://github.com/user-attachments/assets/61c5efd3-9701-4ad0-9633-8f9d81394660)

### Smartphone (please complete the following information)

Browser - chrome, android 

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by jorgezerpa** [comment]
hi! I would like to work on this one @corwintines @isabelladebrito

**Comment by isabelladebrito** [comment]
Thanks @MukulKolpe - assigned it to you!

@jorgezerpa thanks for your offer to help! You can find more good-first-issues here: https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 😃

**Comment by jorgezerpa** [comment]
@isabelladebrito Thanks! I'll check them👾
