### ISSUE TITLE
4pump.fun – Secure and simple token generation

### ISSUE THREAD

**Issue by 4pumpdotfun** [ethereum/ethereum-org-website#13935]
### Name

4pump.fun

### Dapp URL

4pump.fun

### Description

4pump.fun is a secure, rug-proof coin generation platform built on the Base blockchain, empowering creators and businesses to easily launch their own tokens with confidence and scalability.

### Logo

![logo](https://github.com/user-attachments/assets/f0cfcae3-108c-4b71-b41d-e3bf0ca1ed15)

### Brand color

#12c412

### Is your dapp open source?

No

### If open source, what is the repo for the dapp?

there is no referential

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

The code is verified

### Can a user access the dapp without creating an account?

Yes, he just needs to connect his wallet when the site opens.

### Are dapp funds non-custodial?

Yes, they will still be able to access everything.

### Do you offer community support?

t.me/fourpumpdotfun

### Describe any geographical restrictions on usage of your dapp

no restriction

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @4pumpdotfun 

Going to reject this as it is not a well used product, and there is no access to seeing how these tokens are created as well. This seems very closed source, and has me worried that is a scam. Thanks for understanding.
