### ISSUE TITLE
Bug report: delist augur from dapps page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13941]
### Describe the bug

dead link

### To reproduce

1. Go to https://ethereum.org/en/dapps/?category=finance
2. Scroll down to Prediction markets
3. Augur

### Expected behavior

remove this project 

### Screenshots

<img width="722" alt="Screenshot 2024-09-23 at 23 45 22" src="https://github.com/user-attachments/assets/29adb226-7c51-4bd8-a9d3-7d9af2cce880">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Shiva-Sai-ssb** [comment]
@konopkja, Can you please assign this issue to me?

**Comment by konopkja** [comment]
assigned, thank you!
