### ISSUE TITLE
Bug report ...... PAGE NOT FOUND broken link

### ISSUE THREAD

**Issue by Xcertik-Realist** [ethereum/ethereum-org-website#13992]
### Describe the bug

When visiting the SUMBIT tutorials page via the button located here >>> https://ethereum.org/en/developers/tutorials/ you are presented with pop up that asks if you would like to make a PR but when clicking on the YES button inside the pop up this in fact just redirects you to a broken Github link !!! 

### To reproduce

1. Go to 'https://ethereum.org/en/developers/tutorials/'
2. Click on 'SUBMIT A TUTORIAL' button
3. You are presented with a Pop up containing a button named 'Create a Pull Request'
4. When clicking upon this you are forwarded to https://github.com/ethereum/ethereum-org-website/new/dev/src/content/developers/tutorials
5. SEE ERROR =  Seem theres a broken link displaying default github 404 error page 

### Expected behavior

The page displayed in the browser should be https://github.com/ethereum/ethereum-org-website/pulls thus allowing you to submit a pull request

### Screenshots

![Screenshot_28-9-2024_145857_ethereum org](https://github.com/user-attachments/assets/60f6688f-8dfb-493c-8f40-0ef42462832d)
![Screenshot_28-9-2024_145612_github com](https://github.com/user-attachments/assets/80b676be-8c35-4970-8c96-6400a26ddbc2)

### Desktop (please complete the following information)

OS =WIN 10 Home 
Browser = MS EDGE Version 128.0.2739.79 (Official build) (64-bit)

### Smartphone (please complete the following information)

OS = Google Pixel 9 
Browser = Chrome 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @Xcertik-Realist, would you like to work on this?

I have tagged this for hacktoberfest which starts tomorrow in case you are participating as well.

**Comment by Rhythm-08** [comment]
Hi @isabelladebrito , I would like to attempt this issue, can you assign it to me

**Comment by UNOFFICIALbgd** [comment]
Hi @corwintines , this issue is the same as https://github.com/ethereum/ethereum-org-website/issues/13761 , we should close one of them

**Comment by jorgezerpa** [comment]
Hi! @corwintines @isabelladebrito I would like to try this one

**Comment by Xcertik-Realist** [comment]
Yes id love to work on it

**Comment by corwintines** [comment]
@Xcertik-Realist assigning to you given you marked as wanting to work on this

**Comment by corwintines** [comment]
Thanks @UNOFFICIALbgd, closed that other one out

**Comment by Xcertik-Realist** [comment]
thanks ill get it pushed over the weekend
