### ISSUE TITLE
Deprecated eth_coinbase 

### ISSUE THREAD

**Issue by MaryNfs** [ethereum/ethereum-org-website#13996]
### Describe the bug

As per [ethereum/go-ethereum#29747](https://github.com/ethereum/go-ethereum/issues/29747), `eth_coinbase` no longer returns an address in v1.14.0+.
Since this RPC method is deprecated, we should remove it from JSON-RPC API [list](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_coinbase).

### To reproduce

We can see `eth_coinbase` in the RPC list.
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_coinbase

### Expected behavior

We should not list the unsupported RPC APIs.

### Additional context

In Deploying a contract [example](https://ethereum.org/en/developers/docs/apis/json-rpc/#deploying-contract), its been mentioned `eth_coinbase` for getting the coinbase address, instead we can call it as developer account and use eth_accounts to retrieve it.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Jagadeeshftw** [comment]
Hi, I would like to work on this issue, can anyone assign it to me?

**Comment by MaryNfs** [comment]
> Hi, I would like to work on this issue, can anyone assign it to me?

Hi @Jagadeeshftw I have created the pr already, you can find it [here](https://github.com/ethereum/ethereum-org-website/pull/13997).
