### ISSUE TITLE
Translating ethereum.org content into Bengali

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#14005]
You can participate in [Hacktoberfest](https://hacktoberfest.com/) by contributing to the ethereum.org Translation program!

Are you a native speaker of **Bengali**?

We are looking for contributors to increase the amount of **Bengali** content we have available on the website.

### ethereum.org Translation Program

You can learn more about the Translation program [here](https://ethereum.org/en/contributing/translation-program/).

### How to contribute

The quick guide to contributing to ethereum.org as a translator:

1. [Sign up for Crowdin](https://accounts.crowdin.com/register) (translation management platform)
2. Comment on this issue with your Crowdin username, so we can verify your contribution
3. Join our [translation project in Crowdin](https://crowdin.com/project/ethereum-org)  
4. Navigate to your language and find the first untranslated file (translation progress <100%)
5. Start translating on Crowdin

More details on how to navigate and use Crowdin, including a step-by-step video guide, are available here: [ethereum.org/en/contributing/translation-program/how-to-translate](https://ethereum.org/en/contributing/translation-program/how-to-translate/)

Thank you for helping us make ethereum.org more accessible!

**Comment by 1-SubhamSingh** [comment]
Hey there,
I am a native Bengali Speaker from West Bengal, India.
I can help building this feature.
Can you assign me this task.

**Comment by isabelladebrito** [comment]
Thanks

> Hey there, I am a native Bengali Speaker from West Bengal, India. I can help building this feature. Can you assign me this task. Thanks in advance :)

thanks @1-SubhamSingh! Translations should be done via our project in [Crowdin](https://crowdin.com/project/ethereum-org) - could you please provide your Crowdin username?

**Comment by 1-SubhamSingh** [comment]
Sure , here it is : Subham_Singh_1

**Comment by lukassim** [comment]
Closing this out as Hacktoberfest is coming to an end
The ethereum.org Translation program is always open for contributors though, so feel free to join the project in Crowdin to contribute: https://crowdin.com/project/ethereum-org
