### ISSUE TITLE
Translating ethereum.org content into Arabic

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#14008]
You can participate in [Hacktoberfest](https://hacktoberfest.com/) by contributing to the ethereum.org Translation program!

Are you a native speaker of **Arabic**?

We are looking for contributors to increase the amount of **Arabic** content we have available on the website.

### ethereum.org Translation Program

You can learn more about the Translation program [here](https://ethereum.org/en/contributing/translation-program/).

### How to contribute

The quick guide to contributing to ethereum.org as a translator:

1. [Sign up for Crowdin](https://accounts.crowdin.com/register) (translation management platform)
2. Comment on this issue with your Crowdin username, so we can verify your contribution
3. Join our [translation project in Crowdin](https://crowdin.com/project/ethereum-org)  
4. Navigate to your language and find the first untranslated file (translation progress <100%)
5. Start translating on Crowdin

More details on how to navigate and use Crowdin, including a step-by-step video guide, are available here: [ethereum.org/en/contributing/translation-program/how-to-translate](https://ethereum.org/en/contributing/translation-program/how-to-translate/)

Thank you for helping us make ethereum.org more accessible!

**Comment by minimalsm** [comment]
Closing these out as hacktoberfest is coming to an end :)
