### ISSUE TITLE
overflow on a dev doc is breaking on small screens

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#14013]
### Describe the bug

on small screens, this page is broken because of an overflow fail

[https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/](https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/)

![Screen Shot 2024-10-01 11 22 43 AM](https://github.com/user-attachments/assets/d74e468e-1274-488c-ad84-3d057d7f38a9)

### To reproduce

1. Go to [en/developers/docs/consensus-mechanisms/pow/#finality](https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/)
2. resize the window to a smaller than 500px

3. See the page with horizontal scroll

### Expected behavior

should not have horizontal scroll  

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by 0xRPL** [comment]
![overflow_issue](https://github.com/user-attachments/assets/22a32a12-ddfe-473b-8017-0edc93fc0fc7)

**Comment by jorgezerpa** [comment]
Hi! Can I be assigned to this one? 🤠

**Comment by nloureiro** [comment]
> Hi! Can I be assigned to this one? 🤠

It's yours, thank you!

**Comment by nloureiro** [comment]
> hello! @nloureiro
> 
> the idea is to break the word into more lines (like image below) or let an scroll on the list element as sugested [here](https://github.com/ethereum/ethereum-org-website/issues/14013#issuecomment-2387528941) ?
> 
> ![image](https://private-user-images.githubusercontent.com/90111873/372895838-a2ec990f-9260-4224-ac92-4452cd657a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODExMDEsIm5iZiI6MTcyNzg4MDgwMSwicGF0aCI6Ii85MDExMTg3My8zNzI4OTU4MzgtYTJlYzk5MGYtOTI2MC00MjI0LWFjOTItNDQ1MmNkNjU3YTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE0NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YjFiYjMwYmNmYjUzNjBlODMyYjIyNDUyMzlhOGFmNDY0MDMwYWQ3NGMwM2RiMmRlZWRlOGI2OTMyZmRjOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j8ir1gmbHuJF_JS4jqwRvMfGLuWLWaqDXk961HMAzfY)

yes, I think breaking into multiple lines makes sense here; it's not a code snippet.

The screenshot looks great to me.

**Comment by jorgezerpa** [comment]
@nloureiro Nice! I think this is ready to make a PR
but before, should I implement this changes into the translations pages too?

![image](https://github.com/user-attachments/assets/6a25a628-47e2-4e81-af02-c7ae56f12a05)

**Comment by jorgezerpa** [comment]
@nloureiro I checked other languages pages and found the same issue, So I fix on those files to. 

PR opened, I'm attentive for corrections if its needed🤠

**Comment by corwintines** [comment]
Thanks @jorgezerpa 

There was a more global solution that was merged with https://github.com/ethereum/ethereum-org-website/pull/14050, so going to close this out as complete. Feel free to take a look at what was brought in :)
