### ISSUE TITLE
Confirm/update Brownie repo URL

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1404]
**Is your feature request related to a problem? Please describe.**
Related to fix in #1402, we're looking to confirm which is the canonical Brownie repo to link out to.

**Describe the solution you'd like**
Get confirmation from @iamdefinitelyahuman - which URL should we link to:
- https://github.com/eth-brownie/brownie
- https://github.com/iamdefinitelyahuman/brownie-v2

**Comment by samajammin** [comment]
Hey @iamdefinitelyahuman - could you please confirm which URL we should use?

I see the docs link to both, e.g. [on this page](https://eth-brownie.readthedocs.io/en/latest/install.html), the "Edit on Github" links to the `iamdefinitelyahuman` repo but the "github repository" link & clone instructions reference the `eth-brownie` repo.

Thanks in advance!

**Comment by iamdefinitelyahuman** [comment]
Oooh that's a mistake in the docs that i need to update! Thanks for pointing it out :pray:

* [`eth-brownie/brownie`](https://github.com/eth-brownie/brownie) is the current repo and the correct location to link to
* [`iamdefinitelyahuman/brownie-v2`](https://github.com/iamdefinitelyahuman/brownie-v2) is a fork where I'm making breaking changes as i work toward a new major release

**Comment by samajammin** [comment]
Ok great, thanks for the quick reply.
