### ISSUE TITLE
Wrong shisui (portal network client) address

### ISSUE THREAD

**Issue by r4f4ss** [ethereum/ethereum-org-website#14048]
In this [page](https://ethereum.org/en/developers/docs/networking-layer/portal-network/#client-diversity-as-default) the current address linked to Shisui portal network client(https://github.com/GrapeBaBa/shisui) is the address of the fork of user @GrapeBaBa. Although this user is part of the team, the main repo is at https://github.com/optimism-java/shisui. The Portal Network official [site](https://ethportal.net/clients/shisui) points correctly to this address.

**Comment by r4f4ss** [comment]
PR: #14049

**Comment by corwintines** [comment]
Nice catch, thanks @r4f4ss
