### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by 18121A05L2** [ethereum/ethereum-org-website#14041]
### Describe the bug

This is just a UI Bug

### To reproduce

1) Go to - https://ethereum.org/en/developers/docs/networking-layer/network-addresses/
2) Scroll down to ENODE - https://ethereum.org/en/developers/docs/networking-layer/network-addresses/#enode

### Expected behavior

need to add it to the next line instead of breaking the page

### Screenshots

<img width="1440" alt="Screenshot 2024-10-03 at 3 46 10 PM" src="https://github.com/user-attachments/assets/8924acc4-b099-48f6-8fe8-32692a686552">

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @18121A05L2 

This looks like it got resolved with https://github.com/ethereum/ethereum-org-website/pull/14050 so going to close the issue as resolved.
