### ISSUE TITLE
Deprecate _buildspace 

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#14064]
### Describe the bug

_buildspace learning platform has been deprecated

### To reproduce

1. Go to https://ethereum.org/en/developers/learning-tools/
2. Scroll down to **_buildspace**
3. Click link to https://buildspace.so/
4. See loving deprecation note

### Expected behavior

Remove listing from `/learning-tools/`

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by aslikaya** [comment]
I can work on this

**Comment by Lukman-01** [comment]
I will like to work on this.

**Comment by Rex739** [comment]
I'm interested in this. Hook me up

**Comment by manvirsingh1716** [comment]
Sir/Mam i would love to work on this.(i'm also currently learning blockchain)

**Comment by Piyush-Tilokani** [comment]
Made a PR to resolve this issue please review and accept

**Comment by corwintines** [comment]
Since we have a PR here, I will review it. But @Piyush-Tilokani please don't jump the line in the future.

**Comment by Piyush-Tilokani** [comment]
@corwintines I am sorry. I did not see any assignees and no PR made so I thought that making the necessary changes was the right thing to do
