### ISSUE TITLE
Add ETHCluj to community-meetups.json

### ISSUE THREAD

**Issue by dappcoder** [ethereum/ethereum-org-website#14079]
Add the details related to ETHCluj meetup group.

```
"title": "ETHCluj Meetup",
"emoji": ":romania:",
"location": "Cluj-Napoca",
"link": "https://www.meetup.com/ethcluj"
```

**Comment by corwintines** [comment]
I see this meetup hasn't had an event since May, and does not have any upcoming events. Is this group still active?

**Comment by corwintines** [comment]
Going to close this out since the community doesn't have anything coming up. If this changes feel free to reopen

**Comment by dappcoder** [comment]
Hi @corwintines. ETHCluj community is active. Though the recent events were scheduled on [lu.ma:](https://lu.ma/calendar/cal-t3VVZHOgrPOYFdQ) , the meetup.com page is still the main place for listing community meetups.
