### ISSUE TITLE
Event listing: ETHCluj conference

### ISSUE THREAD

**Issue by dappcoder** [ethereum/ethereum-org-website#14080]
### Event/Meetup Name

ETHCluj

### Website

https://www.ethcluj.org

### Location (City/Country, or Remote)

Cluj-Napoca, Romania

### Description

ETHCluj is the conference dedicated to on-boarding local companies, builders and enthusiasts to the Ethereum ecosystem.

### Start date: (yyyy-mm-dd)

2025-06-19

### End date: (yyyy-mm-dd)

2025-06-21

### Additional context

We’re a community on a mission to bring Ethereum into a city filled with tech talent. 
Here, in Cluj Napoca - Romania’s main IT hub, and throughout the Transylvania region, blockchain is just starting to gain serious traction, but we know what this place is capable of. Our city is sitting on untapped potential that can make waves in the global Ethereum community.

This event isn’t just about talk and theory—it’s about inspiring real-world building and empowering developers to create something that matters, without asking for permission. We’ve got some of the most skilled professionals around and it’s time for them to put those talents to work. 

This event is also a space for enthusiasts and curious minds, where anyone interested in Ethereum can come, learn, and get inspired. Whether you’re a seasoned developer, an entrepreneur, or simply intrigued by web3, you’re welcome here.

We believe in the power of a fair and open internet, where users can control their own data and assets without gatekeepers. Ethereum is already more than a blockchain. It is an ecosystem; with its uncompromised focus on decentralization and security, it’s a way to reshape the digital world. Let’s unlock this city’s potential and make it part of that change!

### Would you like to work on this issue?

- [X] Yes

**Comment by corwintines** [comment]
I cant access information on this without a password, so I don't think this event is ready to be listed. Thanks @dappcoder

**Comment by dappcoder** [comment]
@corwintines the password was removed. Please check again. The website is still in early stage, but we need to put this on the calendar because event planning and preparations are depending on that. Thanks.
