### ISSUE TITLE
Bug report: Address overflow at REVERSE ENGINEERING A CONTRACT

### ISSUE THREAD

**Issue by saurabhburade** [ethereum/ethereum-org-website#14092]
### Describe the bug

- Address overflow

### To reproduce

1. Go to https://ethereum.org/en/developers/tutorials/reverse-engineering-a-contract/#0x81e580d3
2. Mobile device view

### Expected behavior

Wrap words/address

### Screenshots

<img width="403" alt="Screenshot 2024-10-09 at 1 14 41 PM" src="https://github.com/user-attachments/assets/83f45756-1f7b-44a6-b126-3a10552af46e">

### Smartphone (please complete the following information)

- iPhone SE

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by corwintines** [comment]
Thanks @saurabhburade 

I think this will have a similar solution to the docs overflow that was done in https://github.com/ethereum/ethereum-org-website/pull/14050/files for whoever picks this up

**Comment by Signor1** [comment]
@corwintines can I work on this ?

**Comment by corwintines** [comment]
For sure, assigned to you @Signor1!

**Comment by corwintines** [comment]
@Signor1 just checking in to see if theres anything you need?

**Comment by Signor1** [comment]
Hi @corwintines, I'm working on it. I got delayed in cloning the repo due to the size

**Comment by Signor1** [comment]
Hi @corwintines, I just created a PR #14254

**Comment by saurabhburade** [comment]
Hey @Signor1, Great! 
Few suggestions here
- Use tailwind classes instead of using custom CSS
- Follow https://github.com/ethereum/ethereum-org-website#how-to-contribute guide
- I'd recommend to only modify `src/layouts/Tutorial.tsx`, unless there's dependency.

**Comment by Signor1** [comment]
Thank you @saurabhburade for the guidance. 
I've made the corrections and then created a PR #14256
