### ISSUE TITLE
Issue with "Find a wallet" on ethereum.org

### ISSUE THREAD

**Issue by michael60634** [ethereum/ethereum-org-website#1412]
**Describe the bug**

Argent no longer subsidizes transfer fees, but the ethereum.org website still shows Argent as having gas subsidization.

**To Reproduce**

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on "No transaction fees"
3. Click on "Search chosen features"

**Expected behavior**

Argent should not show up when "No transaction fees" is selected.

**Comment by samajammin** [comment]
Thanks for reporting @michael60634! @ryancreatescopy could you please confirm?

**Comment by ryancreatescopy** [comment]
Thanks for flagging. Have chased up the wallet providers that we have for "no transaction fees" to get more information. Will act when we know more.
