### ISSUE TITLE
Outdated README info about POAPs for contributions

### ISSUE THREAD

**Issue by UNOFFICIALbgd** [ethereum/ethereum-org-website#14169]
### Describe the bug

1. There are currently galxe OATs (onchain achievement tokens) for github and translation contributions. Only GitPOAP still exist.
2. "A member of our team will verify the request and DM you with a personalized link to claim your own freshly minted POAP collectible!" - no one from the team will DM you with a link. Instead, you will receive links from the team in your post for claiming your OATs.
3. As long, as there are POAPs and OATs for contributions I think we should add info about "what is OAT?".

### To reproduce

1. Go to 'README'
2. Scroll down to 'Claim your POAP'
3. See outdated information

### Expected behavior

1. Should be 2024 year in all sentences, not 2022 year
2. Info about OATs

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Signor1** [comment]
@UNOFFICIALbgd are you working on this ?

**Comment by konopkja** [comment]
@corwintines  @isabelladebrito

**Comment by isabelladebrito** [comment]
Thanks @UNOFFICIALbgd - indeed, the [POAP section](https://github.com/ethereum/ethereum-org-website/blob/dev/README.md#claim-your-poap) on README is really outdated!

I suggest you to use the text from the /contributing page:
- https://ethereum.org/en/contributing/#oat
- https://ethereum.org/en/contributing/#claim-gitpoap

**Comment by UNOFFICIALbgd** [comment]
@Signor1 yes, I am

**Comment by UNOFFICIALbgd** [comment]
@isabelladebrito Thanks for the tip! I'll do my best
