### ISSUE TITLE
Implement new page for payments use case

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#14217]
The task is to implement a brand new page to our website!

Content worked on here: https://github.com/ethereum/ethereum-org-website/issues/13653

**Instructions**
URL for the page should be:  /payments

Design and content of the page:
https://www.figma.com/design/PlJHPXisq7b5ual2DjrR9F/payments?node-id=12940-869&t=J998WMcKEFD6c0jn-1

this design follows the same template as for example: https://ethereum.org/en/defi/ or https://ethereum.org/en/nft/

if you have any questions feel free to comment in figma or in this issue!

**Comment by MukulKolpe** [comment]
Hey @konopkja, can I work on this?

**Comment by konopkja** [comment]
> Hey @konopkja, can I work on this?

perfect! let me know if you need any clarifications! assigned you the issue

**Comment by rahulsingh3526** [comment]
Hey could you assign me this issue I would like to work on this

**Comment by konopkja** [comment]
hi @rahulsingh3526  this issue is already assigned to @MukulKolpe who i believe is working on it, lets give him few days

**Comment by rahulsingh3526** [comment]
ok sounds great.

**Comment by konopkja** [comment]
hi @MukulKolpe , how is it going? Do you need any help? Is this in progress?

**Comment by MukulKolpe** [comment]
Hey @konopkja, yes! sorry for the delay. I’ll have the PR ready ASAP.

**Comment by rahulsingh3526** [comment]
Hey let me know if this is available to work on.

**Comment by konopkja** [comment]
hello @rahulsingh3526  it seems @MukulKolpe is unavailable, do you still want to build this out?
