### ISSUE TITLE
Status Wallet

### ISSUE THREAD

**Issue by Simona-Pop** [ethereum/ethereum-org-website#1425]
Status is your gateway to Ethereum.

The wallet does not have a fiat onramp.

Status does not subsidise transaction fees for wallet activity.

The Status Dapp browser is one of the most straightforward mobile browsing capabilities in web3. It also curates trusted dapps - voted for by the community - in its dap.ps listing.

Users can easily connect to any dapp using the wallet and integration with Wallet Connect is being worked on. The lengthier duration for the integration is due to Status' decentralized first mission which makes any centralized aspect a hurdle in partnerships.

Status enables defi usage through the dapp browser where users borrow/earn/lend assets directly from a screen in the wallet.

Cashing out crypto assets directly to a card or bank account is not possible.  the wallet does not offer limits protection or setting a limit for transfers to protect assets. Tokens cannot be swapped within wallet.

**Status**

**Wallet description**

The Gateway to Ethereum
Combining decentralized messenger, wallet and app browser.

**Wallet logo**

https://statusnetwork.com/press-kit/status/

**Brand color**

#4360DF
RGB: 67, 96, 223
Pantone 2726 C

**Comment by samajammin** [comment]
Thanks @Simona-Pop! @ryancreatescopy please review when you have a chance.
