### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by adomassapalas** [ethereum/ethereum-org-website#14270]
### Wallet name

BlockWallet

### What type of wallet?

EOA

### Wallet description

BlockWallet is a self-custodial crypto wallet for EVM networks, built with a focus on user-friendly features and strong security. It offers users a reliable, easy way to manage digital assets while keeping full control over their crypto

### Wallet logo

![BlockWallet Transparent](https://github.com/user-attachments/assets/e99fd8aa-0ed7-48aa-b663-d2b7799541f7)

### Background color for brand logo

#08090A

### URL to the project

https://blockwallet.io

### When did the wallet go live to users?

February 28, 2022 

### What are the fees users may be paying for using your wallet product?

A 0.5% fee applies to both swapping and bridging functionalities.

### Does the wallet have an active development team?

Yes. 

### Is the wallet globally accessible?

Yes, the wallet is globally accessible, no KYC Required. 

### Is the wallet available in multiple languages?

The wallet is currently available in English only.

### What social links are there for the project?

Twitter: https://x.com/GetBlockWallet

Discord: https://discord.gg/blockwallet

Telegram: https://t.me/blockwallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No it does not. 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No it does not. 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

The wallet is available as a browser extension for both Chrome-based browsers and Firefox:

Chrome:https://chromewebstore.google.com/detail/blockwallet/bopcbmipnjdcdfflfgjdgdjejmgpoaab?hl=en

Firefox:https://addons.mozilla.org/en-US/firefox/addon/blockwallet/

### Is it a hardware wallet?

No it is not a hardware wallet.

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

https://github.com/block-wallet/extension?tab=License-1-ov-file#readme

### Who holds the private keys?

Only user have access to private keys. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We have bug bounty program up and running from the day one of the wallet: https://immunefi.com/bug-bounty/blockwallet/information/

We always do security audits and here is the most recent one: https://raw.githubusercontent.com/block-wallet/block-wallet/main/audits/BLW-01-report.v4.pdf

### Has the wallet's smart contract code or security modules been audited?

https://raw.githubusercontent.com/block-wallet/block-wallet/main/audits/BLW-01-report.v4.pdf

### Does the wallet have an internal security team?

No, we use external auditing/security services. 

### Any other security testing that should be noted?

Not at the moment. 

### Scam protection?

Token allowances revoke: https://blockwallet.io/features/allowances-revoke

Phishing protection: https://blockwallet.io/features/phishing-protection

### Does the wallet support connecting to Ethereum applications?

Yes, it does. Supported browsers recognize BlockWallet, allowing users to set it as their default wallet and connect directly to most dApps.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

https://blockwallet.io/docs/add-a-network-or-custom-rpc

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

No. 

### Does the wallet support swaps directly?

Yes. https://blockwallet.io/docs/swap-tokens-using-block-wallet

### Does the wallet support bridging directly?

Yes: https://blockwallet.io/docs/bridge-tokens-using-block-wallet

### Does the wallet support multi-chain networks?

No. 

### Which Ethereum Layer 2 networks does the wallet support?

The wallet support every EVM-compatible chain. 

### Does the wallet allow the user to customize gas fees?

Yes: https://blockwallet.io/docs/set-your-default-gas-setting

### Does the wallet support sending transactions to ENS addresses?

Yes. 

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Both. https://blockwallet.io/docs/add-custom-tokens

### Does the wallet support EIP-1559 (type 2) transactions?

yes. 

### Does the wallet have any recovery options?

Only through private keys accessible exclusively to the user.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes. https://blockwallet.io/docs/buy-crypto-with-block-wallet

### Does the wallet support withdrawals to fiat?

no. 

### Is the wallet a multi-signature wallet?

no. 

### Does the wallet support social recovery?

no. 

### Does the wallet support bundled transactions?

no. 

### Who can the ethereum.org team can contact regarding the wallet in future?

Email: hello@blockwallet.io

### Does the wallet have a dedicated support team?

Both to our Discord and Telegram. Our support team is available 24/7

### What educational resources/documentation do you provide to users?

We have our docs section with guides though all the wallet features: https://blockwallet.io/docs

Our academy section: https://blockwallet.io/academy

### Does the wallet have any integrated tools not mentioned above?

-

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by konopkja** [comment]
lgtm, thanks for the update
