### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by chendatony31** [ethereum/ethereum-org-website#14320]
### Wallet name

TokenPocket

### What type of wallet?

EOA

### Wallet description

Your secure crypto wallet to explore blockchain. Easy and safe to buy, store, send, swap tokens and collect NFTs. Trusted by 25+ millions users from 200+ countries and regions.

### Wallet logo

![TokenPocket_App__white](https://github.com/user-attachments/assets/6f5a14f1-8b2a-4b52-b9c0-a6f287382255)

### Background color for brand logo

#2980FE

### URL to the project

https://tokenpocket.pro/

### When did the wallet go live to users?

04-20-2018

### What are the fees users may be paying for using your wallet product?

0.2%-0.3% service fee for swapping and bridging.

### Does the wallet have an active development team?

https://github.com/tp-Lab, https://github.com/tokenbankteam

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English
简体中文
繁体中文
हिन्दी
Indonesia
Türkçe
한국어
日本語
عربي
اردو
فارسی
বাংলা
Pусский
Español
Português
Filipino
Bahasa Melayu
Deutsch
Tiếng Việt
ไทย
Français
Dansk
Magyar

### What social links are there for the project?

https://twitter.com/TokenPocket_TP
https://discord.com/invite/NKPM8TXFQk

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS and Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, Chromium.

### Is it a hardware wallet?

Yes, Bluetooth.

### What is the availability of your source code?

Source available

### What license is the wallet software released under?

MIT

### Who holds the private keys?

Only Users themselves can access the private keys.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We have bug bounties here: https://bugrap.io/bounties/TokenPocket
We use users' passwords combined with PBKDF2 to encrypt private keys, which are stored exclusively on users' devices.

### Has the wallet's smart contract code or security modules been audited?

No

### Does the wallet have an internal security team?

Yes, We have our internal security team coming from several large Internet companies.

### Any other security testing that should be noted?

No

### Scam protection?

Yes, we have collaborated with and integrated several security APIs, such as GoPlus and ScamSniffer, to guard against potential scams. Additionally, we maintain our own database of suspicious accounts, contracts, and URLs.

### Does the wallet support connecting to Ethereum applications?

Yes, we support nearly all popular methods for connecting applications. Users can connect with our wallet using various third-party libraries, such as Web3Modal, Web3-Onboard, RainbowKit, and WalletConnect. We are also one of the earliest wallets to support EIP-6963.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes. https://help.tokenpocket.pro/en/wallet-operation/how-to-create-a-wallet/core-1#how-to-add-core-blockchain-on-tokenpocket-extension-wallet

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

Yes, https://help.tokenpocket.pro/en/wallet-faq-en/eth-wallet/node-staking#id-2.-self-custodial-staking

### Does the wallet support swaps directly?

Yes, https://help.tokenpocket.pro/en/wallet-operation/how-to-trade-on-dex/base

### Does the wallet support bridging directly?

Yes, https://help.tokenpocket.pro/en/wallet-operation/how-to-trade-on-dex/base

### Does the wallet support multi-chain networks?

Yes, https://help.tokenpocket.pro/en/wallet-operation/custom-network-token/how-to-add-custom-network

### Which Ethereum Layer 2 networks does the wallet support?

We have support ARB,OP,Base,Mantle,Blast,Scroll,Linea,Zksync era,Taiko,Polygon zkEvm, etc. We can support all evm compatible chains though custom network: https://help.tokenpocket.pro/en/wallet-operation/custom-network-token/how-to-add-custom-network

### Does the wallet allow the user to customize gas fees?

Yes, But we don't have any documentation on this.

### Does the wallet support sending transactions to ENS addresses?

YES,  https://help.tokenpocket.pro/en/announcement/update/version-update-july-11

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, https://help.tokenpocket.pro/en/wallet-operation/custom-network-token/about-custom-token

### Does the wallet support EIP-1559 (type 2) transactions?

Yes,  https://help.tokenpocket.pro/en/announcement/update/version-update-log-august-5-2021-support-eip-1559-miner-fee-mode-more-detailed-optimization

### Does the wallet have any recovery options?

No.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, https://help.tokenpocket.pro/en/wallet-management/token-management/transit-buy

### Does the wallet support withdrawals to fiat?

Yes, same service different tab: https://help.tokenpocket.pro/en/wallet-management/token-management/transit-buy

### Is the wallet a multi-signature wallet?

Yes, we support create and import safe wallet: https://help.tokenpocket.pro/en/wallet-faq-en/multisig-wallet/create#what-is-a-multisig-wallet

### Does the wallet support social recovery?

No.

### Does the wallet support bundled transactions?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

https://x.com/chendatony31
https://t.me/chendatony31
or email: chenda@tokenpocket.pro

### Does the wallet have a dedicated support team?

Yes. 
You can find our support team on telegram: [@tokenPocket_en](https://t.me/tokenPocket_en). 
And also using email:  service@tokenpocket.pro 
Feedback is almost real-time.

### What educational resources/documentation do you provide to users?

Our help center: https://help.tokenpocket.pro/en  

### Does the wallet have any integrated tools not mentioned above?

We also support smart contract wallets(AA) as well. But mostly our users are using our EOA wallets.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by konopkja** [comment]
perfect, lgtm! @chendatony31 can you also make PR with metadata changes for the wallet?

**Comment by chendatony31** [comment]
Thanks for the PR. @konopkja, the `last_updated` field in the PR should be 2024 not 2022.  https://github.com/ethereum/ethereum-org-website/pull/14324/files#diff-c90c3a78b4eeebdb12b8c93266ce09959ee81616ec0a4ddfb2f5ec41817c5f7eL973

**Comment by chendatony31** [comment]
Thanks, @konopkja. I've submitted a PR with some modifications. Please take a look: https://github.com/ethereum/ethereum-org-website/pull/14331
