### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by ru513** [ethereum/ethereum-org-website#14322]
### Wallet name

Safe(prev. Gnosis Safe)

### What type of wallet?

Smart contract

### Wallet description

Safe is the most trusted decentralized custody protocol and collective asset management platform, with over $30B in assets stored across Ethereum and multiple other networks.

At the most basic, Safe is a multi-signature account standard that allows users to define a list of owner/signer accounts and a quorum of signers required to confirm a transaction. The Safe Protocol also serves as a foundation for a growing ecosystem of Dapps.

### Wallet logo

![212338977-5968eae5-bb1b-4e71-8f82-af5282564c66](https://github.com/user-attachments/assets/cc4c885f-2110-4691-bd5f-d39c9d5d7e8d)

### Background color for brand logo

#12ff80

### URL to the project

https://safe.global/

### When did the wallet go live to users?

2017

### What are the fees users may be paying for using your wallet product?

https://help.safe.global/en/articles/222615-safe-staking - 20% fee 
https://help.safe.global/en/articles/233902-safe-wallet-native-swaps - 0.35 % fee

### Does the wallet have an active development team?

Yes: https://github.com/5afe

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

Twitter: https://twitter.com/safe
Discord: https://chat.safe.global/
Mirror: https://safe.mirror.xyz/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS
https://apps.apple.com/us/app/safe-wallet/id1515759131
Android
https://play.google.com/store/apps/details?id=io.gnosis.safe&pli=1

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

N/A

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

N/A

### Is it a hardware wallet?

N/A

### What is the availability of your source code?

Open source

### What license is the wallet software released under?

Various (https://github.com/5afe)

### Who holds the private keys?

Non-custodial

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://docs.safe.global/advanced/smart-account-audits

### Has the wallet's smart contract code or security modules been audited?

https://docs.safe.global/advanced/smart-account-audits

### Does the wallet have an internal security team?

Yes

### Any other security testing that should be noted?

N/A

### Scam protection?

Safe{Wallet} security features, integration with Blockaid

### Does the wallet support connecting to Ethereum applications?

WalletConnect, Safe Apps(https://help.safe.global/en/articles/40860-what-are-safe-apps)

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

N/A

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

https://help.safe.global/en/articles/222615-safe-staking

### Does the wallet support swaps directly?

https://help.safe.global/en/articles/233902-safe-wallet-native-swaps

### Does the wallet support bridging directly?

N/A

### Does the wallet support multi-chain networks?

https://help.safe.global/en/articles/40795-supported-networks

### Which Ethereum Layer 2 networks does the wallet support?

https://help.safe.global/en/articles/40795-supported-networks

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have any recovery options?

https://help.safe.global/en/articles/110656-account-recovery-with-safe-recoveryhub

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

via External Safe application

### Does the wallet support withdrawals to fiat?

N/A

### Is the wallet a multi-signature wallet?

Yes

### Does the wallet support social recovery?

https://help.safe.global/en/articles/110656-account-recovery-with-safe-recoveryhub

### Does the wallet support bundled transactions?

https://help.safe.global/en/articles/234052-transaction-builder

### Who can the ethereum.org team can contact regarding the wallet in future?

Discord : @rudyd_1

### Does the wallet have a dedicated support team?

[help.safe](https://help.safe.global/en/) via Live Chat

Response time will be a matter of minutes

### What educational resources/documentation do you provide to users?

https://docs.safe.global
https://help.safe.global

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by konopkja** [comment]
lgtm

**Comment by konopkja** [comment]
@ru513 can you also make PR updating the wallet metadata?
