### ISSUE TITLE
A gaming system that supports ethereum

### ISSUE THREAD

**Issue by kinghgreat** [ethereum/ethereum-org-website#14329]
### Is your feature request related to a problem? Please describe.

Related to a general problem in the crypto system. it's high time gamers are given the chance to pay or access some in-game features using crypto as a means of payment. it has come to be that many gamers are also crypto enthusiasts or traders earning in crypto. Top games such as Call of Duty, Free Fire, GTA, and some other top games. i will be happy to have Ethereum as the first crypto to be used as means of payment in games like Call of Duty, etc.

### Describe the solution you'd like

I want Ethereum as an eco system to be used as a payment means in games; instead of having to convert to USDT, you pay directly with Ethereum as an option. In general terms, it will also help to grow and boast the eco system and give more value to Ethereum.

### Describe alternatives you've considered

Imagine BTC being used to purchase Tesla products or having to use Ethereum to purchase iPhone products. It will stand as an instant boast to the system as a whole.

### Additional context

It might just skyrocket Ethereum from its normal price way above ten thousand dollars in the near future.

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by konopkja** [comment]
I am not sure how is this relevant to the website ethereum.org, seems like a comment to ethereum ecosystem rather then something relevant to the website.

This repo is only about ethereum.org website and how to improve that, if you have any specific suggestion to the website, please create new issue with more clarity on what to do about this on ethereum.org
