### ISSUE TITLE
Update monolith to include fiat on-ramp

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1432]
**Is your feature request related to a problem? Please describe.**

Monolith now supports fiat on-ramp.

- [x] Add feature to monolith in wallet compare component
- [ ] Add to get-eth

**Comment by ryancreatescopy** [comment]
Awaiting response from Monolith on on-ramp provider so we can add to get-eth page (we need to know geographical restrictions). Email sent: September 11 2020. Chased on October 2 2020

**Comment by samajammin** [comment]
Solved in #1747
