### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by BitgetWalletTeam** [ethereum/ethereum-org-website#14337]
### Wallet name

Bitget Wallet

### What type of wallet?

EOA

### Wallet description

Bitget Wallet, with over 40 million users, provides comprehensive on-chain services including asset management, instant swaps, rewards, staking, trading tools, live market data, a DApp browser, and an NFT marketplace. Supporting various wallet options such as mnemonic, MPC keyless, AA, and Telegram wallets, Bitget Wallet connects to over 100 blockchains, 20,000+ DApps, and 500,000+ tokens. It enables seamless multi-chain trading across hundreds of DEXs and cross-chain bridges, backed by a $300 million protection fund.

### Wallet logo

![Bitget Wallet](https://github.com/user-attachments/assets/a979c2c7-4c2d-4ac4-8992-c283e3a73e10)

### Background color for brand logo

#00F0FF

### URL to the project

https://web3.bitget.com/

### When did the wallet go live to users?

2018 May

### What are the fees users may be paying for using your wallet product?

Gas fee customization

### Does the wallet have an active development team?

https://github.com/bitgetwallet

### Is the wallet globally accessible?

No

### Is the wallet available in multiple languages?

https://web3.bitget.com/en/academy/how-to-switch-between-different-languages

### What social links are there for the project?

- Twitter: https://twitter.com/BitgetWallet
- Telegram:
  - http://t.me/Bitget_Wallet_Announcement
  - https://t.me/BitgetWalletLite_Announcement (Bitget Wallet Lite News)
- Discord: https://discord.gg/bitget-wallet
- YouTube: https://www.youtube.com/@BitgetWallet
- Instagram: https://www.instagram.com/bitgetwallet_global/
- LinkedIn: https://www.linkedin.com/company/bitgetwallet
- TikTok: https://www.tiktok.com/@bitget.wallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

- iOS
- Android
- Telegram Mini APP

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

- No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

- Chrome Extension

### Is it a hardware wallet?

No

### What is the availability of your source code?

Closed source

### What license is the wallet software released under?

None

### Who holds the private keys?

- Only users have access to their public and private keys.
- Users will always be able to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

- **Bug bounties**: https://bugrap.io/bounties/Bitget%20Wallet%20(Formerly%20BitKeep)
- **Security Audit and Code Audit Process Explanation:**

  During the product iteration process, we strictly implement the Security Development Lifecycle (SDL) to ensure security at every stage:

  - **Requirements Stage:** Conduct security assessments, threat modeling, and risk identification to proactively identify and mitigate potential security risks.
  - **Technical Design Stage:** Perform architectural security assessments to ensure that the design solutions are robustly secure.
  - **Testing Stage:** Execute comprehensive security testing, covering the entire lifecycle management of vulnerabilities, to promptly identify and fix potential issues.
  - **Code Changes:** Conduct automated security scans to ensure ongoing security during code updates.
  - **Special Security Audits:** Perform targeted security code audits on key functional modules to thoroughly investigate possible security vulnerabilities.
  - **Security Development Standards:** Adhere to strict security development standards to ensure that the development process aligns with best practices.

  Our SDL process runs throughout the entire product development cycle, providing users with a high level of security assurance.

### Has the wallet's smart contract code or security modules been audited?

- Bitget Wallet Swap V2 https://github.com/bitgetwallet/bkswapv2/blob/main/audit
- Bitget Wallet Solana Swap https://github.com/bitgetwallet/solana-swap/blob/main/audit
- Bitget Wallet Bridge https://github.com/bitgetwallet/bkbridge/tree/main/audit
- Bitget Wallet NFT Exchange https://github.com/bitgetwallet/bkexchange/tree/main/audit
- Bitget Wallet Staker 
    - https://github.com/bitgetwallet/bwb-staking-solana/tree/main/audit
    - https://github.com/bitgetwallet/bwb-claim/tree/main/cosigner-distributor/audit

### Does the wallet have an internal security team?

Our wallet's security team is composed of over 50 experienced security experts, providing comprehensive security assurance from applications to infrastructure.

- **Application Security Team:** Focuses on security assessments, security testing, and the establishment of the Security Development Lifecycle (SDL) process during the product iteration, as well as ensuring the security of the service architecture. This team ensures the security of the entire product development lifecycle and the robustness of the product architecture.

- **Blockchain Security Team:** Dedicated to ensuring the security of on-chain transactions and auditing smart contracts, providing industry-leading blockchain security solutions to safeguard the trustworthiness of every on-chain transaction.

- **Data Security Team:** Responsible for building the data security framework and establishing strict data storage standards to ensure the safety and compliance of user data throughout its lifecycle.

- **Infrastructure Security Team:** Ensures the security of hosts and endpoints by employing state-of-the-art Web Application Firewall (WAF) protection technologies, advanced cloud security solutions, and a zero-trust architecture. Additionally, this team handles around-the-clock alert monitoring and emergency response to ensure immediate action against potential threats.

Through a multi-layered and multi-dimensional security protection system, we comprehensively safeguard the security of our users and platform, ensuring the stability and sustainable development of our business.

### Any other security testing that should be noted?

- https://web3.bitget.com/zh-CN/about/security-technology

### Scam protection?

- We will alert users if they visit a scam or high-risk website/DApp.
- ![img_v3_02gf_09d8513a-9c7b-4aa5-9c7f-ad15b3967e7h](https://github.com/user-attachments/assets/5e5f7628-7619-4a86-b6e4-a60560422755)

### Does the wallet support connecting to Ethereum applications?

https://web3.bitget.com/en/docs/dapp/web-dapp.html

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

- https://web3.bitget.com/en/docs/dapp/network-token.html#Adding%20a%20Mainnet

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

- https://web3.bitget.com/en/academy/liquid-staking

### Does the wallet support swaps directly?

- https://web3.bitget.com/en/academy/how-to-trade-tokens

### Does the wallet support bridging directly?

- https://web3.bitget.com/en/dapp/All/Bridge

### Does the wallet support multi-chain networks?

- https://web3.bitget.com/en/docs/wallet/supported-chains.html

### Which Ethereum Layer 2 networks does the wallet support?

- https://web3.bitget.com/en/docs/wallet/supported-chains.html#Supported%20on%20Ethereum%20Mainnet

### Does the wallet allow the user to customize gas fees?

- https://web3.bitget.com/en/academy/how-to-set-gas-fee

### Does the wallet support sending transactions to ENS addresses?

- No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

- https://web3.bitget.com/en/academy/how-to-add-tokens-nfts

### Does the wallet support EIP-1559 (type 2) transactions?

- https://web3.bitget.com/en/docs/provider-api/eth.html

### Does the wallet have any recovery options?

 - Bitget Wallet is a decentralized wallet that only supports user-initiated wallet import and export.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

- https://web3.bitget.com/en/blog/articles/new-otc-services-available-on-bitkeep

### Does the wallet support withdrawals to fiat?

- https://web3.bitget.com/en/blog/articles/new-otc-services-available-on-bitkeep

### Is the wallet a multi-signature wallet?

- No

### Does the wallet support social recovery?

- No

### Does the wallet support bundled transactions?

- No

### Who can the ethereum.org team can contact regarding the wallet in future?

- [support.web3@bitget.com](mailto:support.web3@bitget.com)

### Does the wallet have a dedicated support team?

- Yes
- 24 hours

### What educational resources/documentation do you provide to users?

- https://web3.bitget.com/en/academy

### Does the wallet have any integrated tools not mentioned above?

1. https://web3.bitget.com/en/academy/how-to-transfer-tokens-in-bulk

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by konopkja** [comment]
hi @BitgetWalletTeam thank you for the application - for the languages supported in the wallet, can you please specify specifically? there is some screenshot in provided link but that could be outdated and/or not the full list. 

Please provide the full list of languages here instead.

**Comment by konopkja** [comment]
What are the fees users may be paying for using your wallet product?
Gas fee customization - are there any in app briding or staking services that users pay fee for?

**Comment by konopkja** [comment]
arbitrum, optimism, blast,  supported l2s
