### ISSUE TITLE
Update "No transaction fees" on wallets page 

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1437]
**Is your feature request related to a problem? Please describe.**

Currently, due to network congestion and unprecedented gas fees, most wallets that were offering gas subsidisation have either stopped or introduced pretty high minimum transfer value stipulations. 

**Describe the solution you'd like**

Option A: Remove no transaction fees as an option / replace it with a different feature (perhaps private messaging)
Option B: Introduce some content that explains that transaction fee subsidisation can't be guaranteed as wallets will base this on network conditions.

**Describe alternatives you've considered**

**Comment by samajammin** [comment]
My two cents - If we decide on option A, I think a filter on hardware wallets / hot vs. cold storage is a worthy feature filter.

**Comment by samajammin** [comment]
Solved in #1607 - we removed the "No transaction fees" feature filter.
