### ISSUE TITLE
Help needed: Mining page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1438]
As part of an initiative to expand content resources for developers, we need domain experts who can help write these resources!

This page is an "entry-level" overview of mining and proof-of-work, and how that is relevant to the world of dapp development. 

- Here is a [loose template to follow](https://www.notion.so/efdn/Writer-template-4b40d196cde7422ca6a2091de33550bd)
- Here is the page as it exists today: https://ethereum.org/en/developers/docs/mining/

**Acceptance criteria**
- There are clear prerequisites as per the template
- No knowledge is assumed, so concepts are explained or linked out to explanations
- Mining and proof-of-work are explained and examples are provided when necessary
- Content is clearly separated into manageable sections with clear headers (h2s and h3s)
- There are links to further reading for those that want to learn more
- There are links to related topics within the ethereum.org developers section
- As a new dapp buidler I understand how mining and proof-of-work impacts my dapp design or decision making process

**How to contribute**
- Update `index.md` files in`src > content > docs > mining`
- Submit PRs to the `dev` branch
- [More on the contribution process](https://github.com/ethereum/ethereum-org-website#the-contribution-process)

**Comment by samajammin** [comment]
The more I think on this, I think more I think it makes sense to have this as a subpage of "consensus mechanisms".

So the content & goal of this page wouldn't necessarily change but we'd build out the following structure:
- /developers/docs/
  - /consensus-mechanisms/
    - /pow/
      - /mining/
    - /pos/

I think this would give a better structure to provide broader context on the topic of mining as well as add more topics within PoW & PoS.
