### ISSUE TITLE
Help needed: Nodes as a service page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1439]
As part of an initiative to expand content resources for developers, we need domain experts who can help write these resources!

This page is an "entry-level" overview of nodes as a service, e.g. Infura – and how that is relevant to the world of dapp development. This page should be as agnostic as possible when it comes to the languages & tools used (showing examples of multiple approaches is always a great solution to this).

- Here is a [loose template to follow](https://www.notion.so/efdn/Writer-template-4b40d196cde7422ca6a2091de33550bd)
- Here is the page on nodes for inspiration and reference: https://ethereum.org/en/developers/docs/nodes-and-clients/

**Acceptance criteria**
- There are clear prerequisites as per the template
- No knowledge is assumed, so concepts are explained or linked out to explanations
- Nodes as a service / APIs are explained and examples are provided when necessary
- Relevant tools / resources are explained and examples are provided when necessary
- Content is clearly separated into manageable sections with clear headers (h2s and h3s)
- There are links to further reading for those that want to learn more
- There are links to related topics within the ethereum.org developers section
- As a new dapp buidler I understand how nodes-as-a-service impact my dapp design or decision making process

**Bonus points**
- Link to this page from wherever relevant across the site! e.g. are there tutorials or other documentation pages that reference this topic? Add a link!

**How to contribute**
- Create an `index.md` files in`src > content > docs > nodes-and-clients > nodes-as-a-service`
- Submit PRs to the `dev` branch
- [More on the contribution process](https://github.com/ethereum/ethereum-org-website#the-contribution-process)

**Comment by elanh** [comment]
@samajammin Just saw your message--happy to take ownership of this issue!

**Comment by elanh** [comment]
Feel free to re-open the issue and assign it to me, I'll get started right away :)

**Comment by fulldecent** [comment]
Bibliography:

- A very simple server-side part of a blockchain product that uses Infura and queries information from the blockchain https://github.com/su-squares/update-script

**Comment by samajammin** [comment]
Solved in #1923
