### ISSUE TITLE
Help needed: testing smart contracts page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1440]
As part of an initiative to expand content resources for developers, we need domain experts who can help write these resources!

This page is an "entry-level" overview of testing smart contracts – and how that is relevant to building a dapp. This page should be as agnostic as possible when it comes to the languages & tools used (showing examples of multiple approaches is always a great solution to this).

- Here is a [loose template to follow](https://www.notion.so/efdn/Writer-template-4b40d196cde7422ca6a2091de33550bd)
- Here is the overview page on smart contracts for inspiration and reference: https://ethereum.org/en/developers/docs/smart-contracts/
- Here is the page as it exists today: https://ethereum.org/en/developers/docs/smart-contracts/testing/

**Acceptance criteria**
- There are clear prerequisites as per the template
- No knowledge is assumed, so concepts are explained or linked out to explanations
- The importance of testing and the tools you need are explained and examples are provided when necessary
- Content is clearly separated into manageable sections with clear headers (h2s and h3s)
- There are links to further reading for those that want to learn more
- There are links to related topics within the ethereum.org developers section
- As a new dapp buidler I understand how to test my smart contacts when developing my dapp

**Bonus points**
- Pros & cons of testing in e.g. Solidity vs. testing in JavaScript
- Include a section on how to mock smart contracts for testing
- Link to this page from wherever relevant across the site! e.g. are there tutorials or other documentation pages that reference this topic? Add a link!

**How to contribute**
- Update `index.md` in`src > content > docs > smart-contracts > testing`
- Submit PRs to the `dev` branch
- [More on the contribution process](https://github.com/ethereum/ethereum-org-website#the-contribution-process)

**Comment by fulldecent** [comment]
Bibliography:

- https://fulldecent.blogspot.com/2019/04/testing-deployed-ethereum-contracts.html
