### ISSUE TITLE
### <span aria-hidden="true">✅</span> Deploy Preview for *ethereumorg* ready!

### ISSUE THREAD

**Issue by byearthinc-com** [ethereum/ethereum-org-website#14456]
### <span aria-hidden="true">✅</span> Deploy Preview for *ethereumorg* ready!

|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 6424a740faa696ef6286275bcd569ffeea5c3ab1 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/ethereumorg/deploys/67508a199a7ed60008847902 |
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-14455--ethereumorg.netlify.app](https://deploy-preview-14455--ethereumorg.netlify.app) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />![QR Code](https://app.netlify.com/qr-code/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJodHRwczovL2RlcGxveS1wcmV2aWV3LTE0NDU1LS1ldGhlcmV1bW9yZy5uZXRsaWZ5LmFwcCJ9.eXKdQ_QCJtKw0GHT8NEKFbZ8QqSKg9G7sDRelKBp8iA)<br /><br />_Use your smartphone camera to open QR code link._</details> |
|<span aria-hidden="true">![Lighthouse](https://app.netlify.com/public/external-usage/git-comments/lighthouse-sm.png)</span><br />Lighthouse | 7 paths audited<br />**Performance**: 46 (🔴 down 14 from production)<br />**Accessibility**: 92 (no change from production)<br />**Best Practices**: 89 (🔴 down 9 from production)<br />**SEO**: 99 (no change from production)<br />**PWA**: -<br />[View the detailed breakdown and full score reports](https://app.netlify.com/sites/ethereumorg/deploys/67508a199a7ed60008847902) |
---

_To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/ethereumorg/configuration/notifications#deploy-webhooks)._

_Originally posted by @netlify in https://github.com/ethereum/ethereum-org-website/pull/14455#issuecomment-2518026098_

This appeared ongoing issues interface with login using github on netlify 

Authentication Error
Authenticating failed due to the following error: bad_verification_code: The code passed is incorrect or expired. error=bad_verification_code&error_description=The+code+passed+is+incorrect+or+expired.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-oauth-app-access-token-request-errors%2F%23bad-verification-code

**Comment by konopkja** [comment]
dont see any changes nor related issue, closing this as it looks like opened by mistake
