### ISSUE TITLE
Broken Link on Decentralized finance (DeFi)

### ISSUE THREAD

**Issue by timbalabuch** [ethereum/ethereum-org-website#14481]
### Describe the bug

The link to 'More on flash loans' on the Ethereum website leads to a 404 error page instead of the intended Aave documentation. This broken link prevents users from accessing detailed information about flash loans.

### To reproduce

1. Go to 'https://ethereum.org/en/defi/'
2. Click on 'More on flash loans'
3. See error: 404 This page could not be found.

### Expected behavior

Link should open new Aave docs on flash loans: https://aave.com/docs/concepts/flash-loans

### Screenshots

![Screenshot 2024-12-10 at 16 49 33](https://github.com/user-attachments/assets/37aba92b-eef6-4418-9d1a-375c76d89458)

### Desktop (please complete the following information)

MacOS - Chrome Browser

### Smartphone (please complete the following information)

iOS - Chrome Browser

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by Tomiwa1** [comment]
Hi @timbalabuch, assign this to me please

**Comment by timbalabuch** [comment]
PR has been merged
