### ISSUE TITLE
Event listing: Update details on ETHCluj conference

### ISSUE THREAD

**Issue by dappcoder** [ethereum/ethereum-org-website#14484]
### Event/Meetup Name

ETHCluj

### Website

https://www.ethcluj.org

### Location (City/Country, or Remote)

Cluj-Napoca, Romania

### Description

ETHCluj is the conference dedicated to on-boarding local companies, builders and enthusiasts to the Ethereum ecosystem.

### Start date: (yyyy-mm-dd)

2025-06-26

### End date: (yyyy-mm-dd)

2025-06-28

### Additional context

This is re-opening #14080 
Since then, the website became public. Note that the date has shifted by one week since #14080 was closed.
The event is also listed on the [official EF spreadsheet](https://docs.google.com/spreadsheets/d/1NEu_FCc1hnGAuRgPmbXXpf0h2lCrCOlMKbbFEqgkVDQ/edit?gid=572241033#gid=572241033).

### Would you like to work on this issue?

- [x] Yes

**Comment by corwintines** [comment]
Closing with above PR
