### ISSUE TITLE
Add ETHCluj to community-meetups.json

### ISSUE THREAD

**Issue by dappcoder** [ethereum/ethereum-org-website#14483]
This issue is re-opening #14079 

Add the details related to ETHCluj meetup group.

```
"title": "ETHCluj Meetup",
"emoji": ":romania:",
"location": "Cluj-Napoca",
"link": "https://www.meetup.com/ethcluj"
```

As mentioned in #14079 , ETHCluj community is active. Though some of the events were scheduled on [lu.ma](https://lu.ma/calendar/cal-t3VVZHOgrPOYFdQ) , the meetup.com page is still the main place for listing community meetups. You can also see a new event scheduled on December 12 here [https://www.meetup.com/ethcluj/events/304875610](https://www.meetup.com/ethcluj/events/304875610)

**Comment by corwintines** [comment]
Closing above PR
