### ISSUE TITLE
Missing explanation text on 'Run a node' quiz

### ISSUE THREAD

**Issue by isabelladebrito** [ethereum/ethereum-org-website#14490]
### Describe the bug

Missing explanation text on '[Run a node](https://ethereum.org/en/quizzes/)' quiz.

### To reproduce

1. On [ethereum.org/quizzes](https://ethereum.org/en/quizzes/) page, start the 'Run a node' quiz 
2. In the question 'Running a node earns network rewards', choose the answer 'False' and then, 'Check answer'
3. The explanation of the question is missing (see screenshot below):
<img width="565" alt="Screenshot 2024-12-11 at 22 22 18" src="https://github.com/user-attachments/assets/0a479b2c-5a18-40ce-a218-27d102dd7ec6" />

### Expected behavior

Add the following text on the 'explanation' section:

`Running a client node alone does not earn you rewards; to earn rewards, you must also be actively staking.`

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by minimalsm** [comment]
Thanks @isabelladebrito! I'll note this issue could be wider in scope than this quiz question. 

The bug was introduced in #14208 and [I've explained the issue here](https://github.com/ethereum/ethereum-org-website/pull/14208/files#r1881114318)

**Comment by isabelladebrito** [comment]
> Thanks @isabelladebrito! I'll note this issue could be wider in scope than this quiz question.
> 
> The bug was introduced in #14208 and [I've explained the issue here](https://github.com/ethereum/ethereum-org-website/pull/14208/files#r1881114318)

Oh I see, thanks for the context @minimalsm! Feel free to close this issue then 💪

**Comment by wackerow** [comment]
> Oh I see, thanks for the context @minimalsm! Feel free to close this issue then 💪

All good, can keep open... fix is up =)
