### ISSUE TITLE
Broken Link on What is Ethereum page

### ISSUE THREAD

**Issue by timbalabuch** [ethereum/ethereum-org-website#14493]
### Describe the bug

The link to "Kernel Ethereum's Dream" on the "What is Ethereum" page leads to a 404 error. This indicates that the target page does not exist or the link is broken.

### To reproduce

1. Go to 'https://ethereum.org/en/what-is-ethereum/'
2. Click on 'Kernel Ethereum's Dream'
3. See error 404 - This page could not be found.

### Expected behavior

Opens Kernel community page

### Screenshots

![Screenshot 2024-12-12 at 10 16 15](https://github.com/user-attachments/assets/88ef75a6-2fcd-4a47-bcf2-95266098a4d4)

### Desktop (please complete the following information)

MacOS - Chrome Browser

### Smartphone (please complete the following information)

iOS - Chrome Browser

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by konopkja** [comment]
we have a duplicate here https://github.com/ethereum/ethereum-org-website/issues/14457

**Comment by timbalabuch** [comment]
Oh! thanks for the catch. I'll close this one.

**Comment by timbalabuch** [comment]
Oh! thanks for the catch. I'll close this one.
