### ISSUE TITLE
Add licensing info to Assets page

### ISSUE THREAD

**Issue by slipperybeluga** [ethereum/ethereum-org-website#1461]
The "Ethereum Brand Assets" page (https://ethereum.org/en/assets/) currently has the various Ethereum logos and website art available for viewing and download. It includes links to the artists where applicable, but **the page is incomplete without licensing information.** 

Suggested improvement:

- If all images are under the same license, a small blurb stating that license at the top of the page would be helpful. 

- If individual images are subject to different licenses, that info should follow the individual images. 

blah blah blah: 

As it stands, it is unclear to me what license the Ethereum logo is subject to. The ethereum.org website (along with all assets including images) is available here on github subject to MIT license, but the svg of the logo is available elsewhere under CC v3 (on wikimedia, etc). A look on archive.org at the ethereum.org/assets page only compounds the confusion in numerous ways with talk of plans to update the use guidelines, references to trademarks, links to branding pages that don't exist anymore, and visual identity guide documents, etc. 

Please consider updating the assets page to include licensing to eliminate all confusion.

**Comment by samajammin** [comment]
Thanks for the suggestion @slipperybeluga! Definitely agree that this should be more straightforward.

@ryancreatescopy - assigning to you.

**Comment by samajammin** [comment]
@all-contributors please add @slipperybeluga for ideas.

**Comment by ryancreatescopy** [comment]
@jjmstark do you know the name of the licence that the illustrations are subject to? I will speak to EF legal to see what licence the EF assets are under.

**Comment by samajammin** [comment]
Re-opening, this is still an issue.

**Comment by minimalsm** [comment]
@samajammin should we close this out for now?

**Comment by samajammin** [comment]
Still an issue. I've been following up with EF internally but still don't have resolution.

**Comment by minimalsm** [comment]
Still waiting for clarity on this.

**Comment by corwintines** [comment]
Should have clarity soon to push this across finish line

**Comment by slipperybeluga** [comment]
It's been more than 2 years, I certainly don't care anymore.

**Comment by q9f** [comment]
But maybe someone else cares?

**Comment by corwintines** [comment]
Going to reopen, we still plan on adding this.

**Comment by rotate-eth** [comment]
To add to the discussion:

Someone in Spain has just been granted a trademark for the Ethereum logo: http://consultas2.oepm.es/ceo/jsp/busqueda/consultaExterna.xhtml?numExp=M4135936
The same person tried to apply for the Bitcoin logo too, which was rejected, so I assume he doesn't represent the Ethereum Foundation.

Furthermore, a Google search of "ethereum logo licence" gives this Reddit post as the top result for me: https://www.reddit.com/r/ethereum/comments/9w6abe/can_i_use_the_ethereum_logo_on_my_website_the/
This argues that it was originally published under CC Attribution 3 which is a non-revocable licence, and therefore can still be used under the licence whatever the EF website says now.

Not a lawyer and don't know myself, but seems clear that clarity is needed.

**Comment by MicahZoltu** [comment]
Would love to see the brand assets CC0 (or other no-attribution-required license) so they can freely be used.  Requiring attribution adds a *lot* of complication when someone wants to integrate them into a webpage or create derivative works as you now need a mechanism for giving attribution to the original author.  Usually brand assets are incredibly permissive in licensing to encourage use, but at the moment the lack of license and the suggestion they might be MIT or CC3 makes them hard to use.  😢

**Comment by minimalsm** [comment]
Closing this out for now, we won't have a robust solution for this issue any time soon due to complexities outwith our current control.
