### ISSUE TITLE
Typo in docs/transactions signature description

### ISSUE THREAD

**Issue by DrMad92** [ethereum/ethereum-org-website#1463]
**Describe the bug**

On https://ethereum.org/en/developers/docs/transactions/ page, the description of `signature` states: `This is generated when the sender's public key signs the transaction and confirms the sender has authorised this transaction`

**Expected behavior**

Shouldn't it be `private key`?

**Screenshots**

<img width="685" alt="Screenshot 2020-09-21 at 12 36 59" src="https://user-images.githubusercontent.com/28419987/93752388-43c25000-fc07-11ea-932a-1ae9b717cf84.png">

**Comment by samajammin** [comment]
Thanks for catching @DrMad92! This sounds right to me, let me get confirmation 🤔

**Comment by samajammin** [comment]
This article seems to confirm your point: https://medium.com/@codetractio/inside-an-ethereum-transaction-fa94ffca912f

LMK if you know of any other references 😄

**Comment by samajammin** [comment]
Solved in #1615

**Comment by samajammin** [comment]
@all-contributors please add @DrMad92 for bug reports.
