### ISSUE TITLE
Bitbuy - Exchange listing request

### ISSUE THREAD

**Issue by Adam-Koza** [ethereum/ethereum-org-website#1465]
Before suggesting an exchange, make sure you've read [our exchange listing policy](https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**

Services Canada only.

**Which currencies are accepted by this exchange?**

- CAD (Canadian Dollar)
- ETH (Ethereum)
- BTC (Bitcoin)
- LTC (Litecoin)
- BCH (Bitcoin Cash ABC)
- XLM (Stellar)
- XRP (Ripple)
- EOS (EOSIO)

**Do you have any proof that they're a legitimate company?**

About us page:   https://bitbuy.ca/en/about-us

FINTRAC Registration:   https://www10.fintrac-canafe.gc.ca/msb-esm/public/detailed-information/msb-details/7b226d73624f72674e756d626572223a3136303239322c227072696d617279536561726368223a7b226f72674e616d65223a22626974627579222c2273656172636854797065223a317d7d/

**Do you have any extra information?**

Been fully operational since 2016 with roots back to 2013 (InstaBT), 25 employees, 5MM+ in funding. Located in Toronto Ontario, Canada.

In the news: 

https://www.forbes.com/sites/colinharper/2020/05/27/bitcoin-exchange-bitbuy-partners-with-knox-security-to-offer-full-deposit-insurance/#895d8e65b7d5

https://www.globenewswire.com/news-release/2020/07/13/2061264/0/en/BIGG-Digital-Assets-Inc-Subsidiary-Blockchain-Intelligence-Group-provides-ExDD-Report-Exchange-Due-Diligence-Report-and-Proof-of-Reserve-for-BitBuy-Technologies.html

https://bitcoinmagazine.com/articles/bitbuy-knox-team-to-offer-insured-custody-for-bitcoin-on-exchange

**Comment by GeorgeTrotter** [comment]
@samajammin we're good to go on this one, waiting on you!
