### ISSUE TITLE
Site translation: (Add) Serbian

### ISSUE THREAD

**Issue by mvelebit** [ethereum/ethereum-org-website#1482]
**Is your feature request related to a problem? Please describe.**

Serbian language's missing from the [Crowdin list](https://crowdin.com/project/ethereumfoundation). 

**Describe the solution you'd like**

Serbian language should be added to the list so that I could begin work on the translation.

**Comment by samajammin** [comment]
Thanks for the request @mvelebit!

@sorumfactory could you please add Serbian as a language to Crowdin?

**Comment by sorumfactory** [comment]
Hello @mvelebit !
Thank you for the request :)
The Serbian language is available on Crowdin. You can check out the link below:https://crowdin.com/project/ethereumfoundation/sr-CS#

Although Wikipedia said that the Latin alphabets are commonly used in online and website script, I wanted to lean on your decision and ended up adding both Latin and Cyrillic to Crowdin. Please feel free to choose the one you think it's best to support Serbian community members. Later, I will remove the one which isn't used :)

Thank you!

**Comment by samajammin** [comment]
Thanks @sorumfactory & @mvelebit! I'll close this issue out - we can track translation progress in CrowdIn directly.
