### ISSUE TITLE
Add Infinity Wallet to Ethereum Wallets 

### ISSUE THREAD

**Issue by InfinityWallet** [ethereum/ethereum-org-website#1483]
**Does the wallet allow users to explore dapps?**
The Infinity Wallet is one of the first desktop platforms to allow desktop to desktop connecting without an browser extension and supports every ethereum defi and dapp platform. We make connecting to defi and dapps more easier than ever and much more secure, along with our easy connect and scan technology.  
https://i.gyazo.com/cb9aebfb77c948c624cfda3533f08c6f.png

**Does the wallet have integrated defi/financial tools?**
The Infinity Wallet supports direct p2p connecting with defi and dapps within the desktop with our new technology and further support with the development of our mobile wallet to be released within early 2021.

**Can a user withdraw to their card?**
We currently do not support crypto-fiat, however this is something we are looking at integrating in the future to allow more easier retail adoption. However we find many providers very limiting and costly to the user and are looking at our own possible solution.

**Does the wallet offer limits protection?**
The Infinity Wallet is fully decentralized for maximum security and does not limit or block users as a fully decentralized wallet, with easy onboarding for mass adoption and the most professional and easy to use UI with new innovative features.

**Does the wallet allow high-volume purchases?**
Users can trade in large volumes with no limits applied for crypto-crypto.

**Does the wallet have an integrated token swap?**
Yes, we have created one of the easiest interfaces for any users no matter their knowledge of trading or swapping. Users can simply in one click trade, changing the entire crypto experience and making adoption easier than ever before.

**Is the wallet a multi-signature wallet?**
The Infinity Wallet currently supports 12 or 24 seed word and in the near future we are looking at providing multi-sig for more advanced users as well as additional options for retail users to understand and still maintain maximum security. Our goal is ease of use while keeping security for easier onboarding and adoption of cryptocurrency providing the best user experience and user interface.

**Wallet title**
Infinity Wallet

**Wallet description**
Infinity Wallet is the ultimate gateway to decentralized finance in a user friendly, multi-coin and secure cryptocurrency wallet for all a user crypto needs, with easy instant dapp and defi connecting.

**Wallet logo**
http://infinitywallet.io/images/Infinity_official_logo_icon.svg

**Brand color**
#1c223e

**Website Link**
https://infinitywallet.io/

**Comment by samajammin** [comment]
Thanks for the suggestion @InfinityWallet!

@GeorgeTrotter please review when able.

**Comment by GeorgeTrotter** [comment]
Hey @InfinityWallet! This info looks great. A few last details we need to iron out. Per our content [policy](https://ethereum.org/en/contributing/adding-products/), wallets need to have been audited, live for six months, and maintained by an active team:

- Where can we confirm your wallet's last audit?

- When did your wallet go live?

- Is your team active? (I assume so, but just checking!)

This last note isn't necessary but info we collect. Does InfinityWallet offer fiat currency on-ramps for users?

Once we've got those details we'll get InfinityWallet up!

**Comment by InfinityWallet** [comment]
> Hey @InfinityWallet! This info looks great. A few last details we need to iron out. Per our content [policy](https://ethereum.org/en/contributing/adding-products/), wallets need to have been audited, live for six months, and maintained by an active team:
> 
> * Where can we confirm your wallet's last audit?
> * When did your wallet go live?
> * Is your team active? (I assume so, but just checking!)
> 
> This last note isn't necessary but info we collect. Does InfinityWallet offer fiat currency on-ramps for users?
> 
> Once we've got those details we'll get InfinityWallet up!


The wallet has been live for nearly just over a year and the team is active with constant new developments. We are actually surprised we are still not added to the Ethereum Wallet list.

**Comment by InfinityWallet** [comment]
Hello, any update? Thanks

**Comment by EYEFOUREYE** [comment]
Start loafing installing

**Comment by minimalsm** [comment]
Hey @InfinityWallet. Sorry for the delay on this.

Thank you for providing the additional information on the timeframe/active development. Last thing we need to iron out is the wallet security as per the product [criteria for inclusion](https://ethereum.org/en/contributing/adding-products/) to be listed on the site.

> A security-tested product – whether through audit, an internal security team or some other method, your product's security must be reliably tested. This reduces the risk to our users and shows us that you take security seriously.

I had a look on https://infinitywallet.io/ but I couldn't find anything specific. If we can resolve this point we will get InfinityWallet live ASAP. Thanks again for your patience on this issue.

**Comment by minimalsm** [comment]
@InfinityWallet any update on this?

**Comment by minimalsm** [comment]
Hey @InfinityWallet I'm closing this for now due to inactivity. Feel free to re-open with the relevant information 😀 thanks!
