### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by BlueVelvetSackOfGoldPotatoes** [ethereum/ethereum-org-website#1491]
At https://ethereum.org/en/developers/docs/#development-modules

DEVELOPMENT MODULES
If this is your first attempt at Ethereum development, we recommend starting at the beginning and working **you** way through like a book.

**you** should be **your**

**Comment by samajammin** [comment]
Thanks for catching! Fix coming shortly...

**Comment by samajammin** [comment]
@all-contributors please add @BlueVelvetSackOfGoldPotatoes for bug reports.

**Comment by mspaansen** [comment]
😀
