### ISSUE TITLE
Help needed: Running your own node page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1516]
As part of an initiative to expand content resources for developers, we need domain experts who can help write these resources!

This page is an "entry-level" overview how to run your own node and how that is relevant to the world of dapp development. This page should be as agnostic as possible when it comes to the languages & tools used (showing examples of multiple approaches is always a great solution to this).

- Here is a [loose template to follow](https://www.notion.so/efdn/Writer-template-4b40d196cde7422ca6a2091de33550bd)
- Here is the page on nodes for inspiration and reference: https://ethereum.org/en/developers/docs/nodes-and-clients/
- Here is the existing content around "running your own node": https://ethereum.org/en/developers/docs/nodes-and-clients/#running-your-own-node - the goal here is to break out this section into a subpage with more detailed information

**Acceptance criteria**
- There are clear prerequisites as per the template
- No knowledge is assumed, so concepts are explained or linked out to explanations
- A walkthrough on how to run a node is covered and example code is provided when necessary
- Relevant tools / resources are explained and examples are provided when necessary
- Content is clearly separated into manageable sections with clear headers (h2s and h3s)
- There are links to further reading for those that want to learn more
- There are links to related topics within the ethereum.org developers section
- As a new dapp buidler I understand how running my own node impacts my dapp design or decision making process

**Bonus points**
- Link to this page from wherever relevant across the site! e.g. are there tutorials or other documentation pages that reference this topic? Add a link!

**How to contribute**
- Create an `index.md` files in`src > content > docs > nodes-and-clients > running-your-own-node`
- Submit PRs to the `dev` branch
- [More on the contribution process](https://github.com/ethereum/ethereum-org-website#the-contribution-process)

**Comment by ryancreatescopy** [comment]
fixed in #2182

**Comment by samajammin** [comment]
Closing this out. As @ryancreatescopy mentioned, this was solved in #2182
