### ISSUE TITLE
Friction in installation steps in tutorial `A Python developer's introduction to Ethereum, part 1`

### ISSUE THREAD

**Issue by daviroo** [ethereum/ethereum-org-website#1526]
The installation steps for the tutorial `A Python developer's introduction to Ethereum, part 1` includes the following step:

```bash
$ pip install web3[tester]
```

The above command won't work in .zsh as .zsh [uses square brackets for globbing](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity).  With macOS Catalina [using .zsh as the default shell](https://support.apple.com/en-us/HT208050) there will likely be more people hitting this bit of friction.  Adding quote marks around the package fixes it in .zsh and also works in bash (those are the only shells I have tested).

**To Reproduce**

1. Open a shell with .zsh
2. `$ pip install web3[tester]`
3. See error

**Expected behavior**

The package should be installed.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser N/A
- Version Catalina

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

**Additional context**

N/A

**Comment by daviroo** [comment]
I'm happy to submit a PR to fix this by adding the quotation marks around the package name.  I've tested it and it fixes the issue in .zsh and continues to work in bash.

**Comment by ryancreatescopy** [comment]
Thanks for raising an issue. @marcgarreau this might interest you...

**Comment by marcgarreau** [comment]
Thanks for reporting @daviroo. I'm still using bash locally, so wasn't on my radar. The PR would be welcome.
