### ISSUE TITLE
@all-contributors please add @alancwoo for code & design

### ISSUE THREAD

**Issue by truongnhi08** [ethereum/ethereum-org-website#1527]
@all-contributors please add @alancwoo for code & design

_Originally posted by @samajammin in https://github.com/ethereum/ethereum-org-website/issues/407#issuecomment-552231004_

**Comment by samajammin** [comment]
@alancwoo has already been added: https://github.com/ethereum/ethereum-org-website/blob/dev/.all-contributorsrc#L688
