### ISSUE TITLE
ola!

### ISSUE THREAD

**Issue by truongnhi08** [ethereum/ethereum-org-website#1528]
ola!
gotaria de ajudar a traduzir para o pt-BR

_Originally posted by @JefteCosta in https://github.com/ethereum/ethereum-org-website/issues/610#issuecomment-573344078_

**Comment by samajammin** [comment]
Hey @truongnhi08! Thanks for volunteering to help.

I believe pt-BR translations have been completed:
https://crowdin.com/project/ethereumfoundation/pt-BR#
We're just waiting on review from our professional translation service. Once that's complete, we'll update the website.

We'll also be launching new content for our volunteers to translate in the coming weeks. Go ahead & sign up to our Crowdin project - you can find instructions here: https://ethereum.org/en/contributing/translation-program/
That way, we can alert you when new translations are needed 👍 

I'm closing this issue out but feel free to re-open & tag @sorumfactory if you have any more questions.
