### ISSUE TITLE
Trust Wallet 

### ISSUE THREAD

**Issue by MiladHassani73** [ethereum/ethereum-org-website#1531]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samajammin** [comment]
Hey @MiladHassani73 - not sure what this is issue is requesting. I'm going to close this out but feel free to re-open with more details.

Trust Wallet can already be found on this page: https://ethereum.org/en/wallets/find-wallet/
