### ISSUE TITLE
Confirm deposit address page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1553]
**Is your feature request related to a problem? Please describe.**

A page that allows users to double check they have the correct staking contract address – to support the journey created by the launchpad. 

**Describe the solution you'd like**

- Clear warnings to users that this is to confirm an address from a trusted source
- Clear links to the launchpad for users who have yet to go through the process
- Enough friction to make users check the address properly

**Comment by samajammin** [comment]
Solved in #1554 #1691 - page is live at https://ethereum.org/en/eth2/deposit-contract/
