### ISSUE TITLE
Help needed: "Indexing and querying" developer resource page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1564]
We could use a developer resource around the topic of indexing & querying Ethereum blockchain data. As part of an initiative to expand content resources for developers, we need domain experts who can help write these resources!

**Why?**
As discussed in https://github.com/ethereum/ethereum-org-website/pull/1529#discussion_r498351878 ...
1) This is a common challenge for dapp developers. Smart contract view functions & [client APIs](https://ethereum.org/en/developers/docs/apis/javascript/) can only do so much.
2) There are projects (like The Graph mentioned in that PR) that help developers solve these problems but don't really fit the definition of a "framework" & don't really belong on [our framework page](https://ethereum.org/en/developers/docs/frameworks/).

**What?**

This page is an "entry-level" overview of indexing and querying blockchain data – why it's useful, how it's accomplished and how it's relevant to building a dapp. This page should be as agnostic as possible when it comes to the languages & tools used (showing examples of multiple approaches is always a great solution to this).

Here is a [loose template to follow](https://www.notion.so/efdn/Writer-template-4b40d196cde7422ca6a2091de33550bd).

Not sure "indexing and querying" is the best name for this topic - I welcome input & ideas on this!

**Acceptance criteria**
- There are clear prerequisites as per the template
- No knowledge is assumed, so concepts are explained or linked out to explanations
- Relevant tools / resources are explained and examples are provided when necessary
- Content is clearly separated into manageable sections with clear headers (h2s and h3s)
- There are links to further reading for those that want to learn more
- There are links to related topics within the ethereum.org developers section
- As a new dapp buidler, I understand how to use upgradeable smart contracts when developing my dapp after reading this

**Bonus points**
- Link to this page from wherever relevant across the site! e.g. are there tutorials or other documentation pages that reference this topic? Add a link!

**How to contribute**
- Create an `index.md` files in`src > content > docs > indexing-and-querying`
- Add the page under the ["Data and analytics" section](https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/developer-docs-links.yaml#L59) of our docs links
- Submit PRs to the `dev` branch
- [More on the contribution process](https://github.com/ethereum/ethereum-org-website#the-contribution-process)

**Useful references/resources**
- https://thegraph.com/
- https://amberdata.io/
- https://aleth.io/
- We welcome others!

**Comment by fulldecent** [comment]
I see this issue has been open for a while. If it is important, the core salaried team is not available, and cash bounties are being offered then please add a note.

**Comment by cj-technical** [comment]
> src > content > docs > indexing-and-querying

@samajammin  Is that path still correct? "docs" doesn't appear to be under the "content" folder any more.

https://github.com/ethereum/ethereum-org-website/tree/dev/src/content

**Comment by samajammin** [comment]
@cj-technical content > developers > docs

**Comment by minimalsm** [comment]
Has this issue been closed by @cj-technical's PR? (#2439)

**Comment by sasicodes** [comment]
@minimalsm Is this issue still open or closed by (#2439) ?

**Comment by minimalsm** [comment]
I'd say closed. Thanks @sasicodes

**Comment by samajammin** [comment]
I'd propose re-opening this issue. The description perhaps needs updating but I still see value in a dedicated page on indexing & querying solutions. Most dapp developer building frontends will eventually run into this issue - it's nearly impossible to rely on a convenience library like ethers.js to query all your contract data, particularly if you rely on events & need to enumerate through many blocks, creating expensive JSON RPC queries.

**Comment by samajammin** [comment]
@emmanuel-awosika not sure if you'd have any interest in this? 😄

**Comment by meera** [comment]
I will be happy to contribute!

**Comment by AnmolSirola** [comment]
@corwintines @samajammin I want to contribute to this issue, can you explain what needs to be done now, like there is already a pr #2439 for this issue which is targeting content document for Data and Analytics in the developer section. Do we need to make a dedicated page on indexing & querying solutions only?

**Comment by wackerow** [comment]
Closing this and resurfacing on #11564
