### ISSUE TITLE
Help needed: "Development network" page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1582]
As part of an initiative to expand content resources for developers, we need domain experts who can help write these resources!

This page is an "entry-level" overview of "development networks" within the "Ethereum stack" section of docs. This should explain the why & how of setting up a local blockchain network like Ganache or Buidler EVM that are geared specifically towards development & how they fit into the world of dapp development. This page should be as agnostic as possible when it comes to the languages & tools used (showing examples of multiple approaches is always a great solution to this).

**Why?**

Based on questions we've received, there appears to be confusion that in order to test a dapp, a developer must set up a full node. We should add a section in our Nodes & Clients page that explains this is not the case & link to this new page.

The main thought behind naming this category of tooling a "development network" is that it's more specific than "local network/blockchain" since these tools pack development features that aren't present in real clients - they’re tailored for development (e.g. the quirky behavior of 0 block times & 1 transaction per block). A local blockchain, on the other hand, could be an instance of Geth running locally. This page should explain the differences between a "development network" & a standard Ethereum client & provide context on why these differences exist.

**How**

- Here is a [loose template to follow](https://www.notion.so/efdn/Writer-template-4b40d196cde7422ca6a2091de33550bd)
- Here is the page on nodes for reference: https://ethereum.org/en/developers/docs/nodes-and-clients/

**Acceptance criteria**
- There are clear prerequisites as per the template
- No knowledge is assumed, so concepts are explained or linked out to explanations
- A walkthrough on how to set up a development network is covered and example code is provided when necessary
- Relevant tools / resources are explained and examples are provided when necessary
- Content is clearly separated into manageable sections with clear headers (h2s and h3s)
- There are links to further reading for those that want to learn more
- There are links to related topics within the ethereum.org developers section
- As a new dapp buidler I understand how to set up a development network to test & deploy my smart contracts

**Bonus points**
- Link to this page from wherever relevant across the site! e.g. are there tutorials or other documentation pages that reference this topic? Add a link!

**How to contribute**
- Create an `index.md` files in`src > content > docs > development-networks`
- Submit PRs to the `dev` branch
- [More on the contribution process](https://github.com/ethereum/ethereum-org-website#the-contribution-process)

**Comment by davidmurdoch** [comment]
Commenting to follow along. 😁

**Comment by samajammin** [comment]
Solved in #1613 but we'd welcome further edits/contributions!
