### ISSUE TITLE
Clicking the "Start building" button on the "What is Ethereum" page returns Resource Not Found

### ISSUE THREAD

**Issue by voska** [ethereum/ethereum-org-website#1585]
**Describe the bug**

Clicking the `Start building` button at the bottom of the ["What is Ethereum" page](https://ethereum.org/en/what-is-ethereum/) returns `Resource Not Found` (See Screenshot). The `Start building` button links to `https://ethereum.org/en/build/` which should redirect to `https://ethereum.org/en/developers/learning-tools/` but the redirect isn't working.

**To Reproduce**

1. Go to ["What is Ethereum" page](https://ethereum.org/en/what-is-ethereum/)
2. Click on `Start building` at the bottom of the page under "Make something with Ethereum"

**Expected behavior**

`Start building` should link directly to `https://ethereum.org/en/developers/learning-tools/` or should properly redirect from `https://ethereum.org/en/build/`

**Screenshots**

<img width="626" alt="Screen Shot 2020-10-06 at 11 00 24" src="https://user-images.githubusercontent.com/3444419/95181115-2672b180-07c3-11eb-8e21-8756329d2cd5.png">

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.6 (19G2021)
- Browser: chrome
- Version: 85.0.4183.121 (Official Build) (64-bit)

**Comment by samajammin** [comment]
Thanks for catching & reporting this @voska! The redirect only work for new network requests vs. internal links. I'll update the internal links to fix this.

**Comment by samajammin** [comment]
@all-contributors please add @voska for bug reports.
