### ISSUE TITLE
Listing on Ethereum website

### ISSUE THREAD

**Issue by triterras** [ethereum/ethereum-org-website#1618]
We developed and operate Kratos - one of the world's largest commodity trading and trade finance platforms that connects and enables commodity traders to trade and source capital from lenders directly online. 

We are using Ethereum smart contract function heavily and wanted to find out if we could be included on your website like other companies mentioned here -  https://ethereum.org/en/enterprise/#why-enterprise-ethereum

Please let me know if this would be possible and what the next steps would be.

**Comment by samajammin** [comment]
Thanks for raising this issue @triterras - is this the platform you're referring to?
https://triterras.com/kratos

@tasdienes could you please review this platform & determine if it's a good fit for the Enterprise page?

@triterras in the meantime, any additional information you could provide related to our [product listing criteria](https://ethereum.org/en/contributing/adding-products/) would help us reach a decision faster.

Thanks!

**Comment by tasdienes** [comment]
Added in #1629
