### ISSUE TITLE
Mobile menu nav links tappable region not extending width of menu

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#1621]
**Describe the bug**
On the mobile menu, the tappable portion of each item listed currently extends the entire width of the container, however, only the text portion of each line will correctly navigate to that link, despite visual styling feedback that extends beyond that region when tapped.

**To Reproduce**

1. Go to home page on mobile device, or mobile sized browser screen
2. Tap/click on hamburger menu button in upper right
3. Tap/click to the right of the text from any section item. 
4. As you tap/click, you'll notice styling of the menu text changes to give feedback that the line has been pressed, followed instantly by the menu closing, but no navigation triggered.

**Expected behavior**
On step 4 above, would expect that despite clicking to the right of the text, by tapping on a given row in this menu I would expect to be navigated to the appropriate link, especially when there is visual styling feedback suggesting I tapped that line correctly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/95779690-4ef52280-0c7f-11eb-8baf-26bc3edfd448.png)
This shows the limitations of the actual `NavLink`

**Desktop:**
- OS: macOS Big Sur public beta
- Browsers: Brave (Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64)), Chrome 85.0.4183.121, Safari 14.0.1

**Smartphone:**

- Device: iPhone XS Max
- OS: iOS 14.0.1
- Browser: Brave

**Additional context**
Suggestion: Changing this block...
https://github.com/ethereum/ethereum-org-website/blob/3858a397beba5ecd43965d25dbfe7d0978598989/src/components/Nav/Mobile.js#L265
...to...
```
return (
  <NavLink
    to={item.to}
    isPartiallyActive={item.isPartiallyActive}
    key={idx}
  >
    <SectionItem onClick={toggleMenu}>
      <Translation id={item.text} />
    </SectionItem>
  </NavLink>
)
```
...seems to correct this issue.

Happy to send PR with this if there is agreement.

**Comment by samajammin** [comment]
@wackerow thanks for surfacing this! We'd welcome a PR fix 😄

**Comment by samajammin** [comment]
@all-contributors please add @wackerow for bug reports.
