### ISSUE TITLE
Add "Previous" & "Next" links to Developer Docs pages

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1650]
**Is your feature request related to a problem? Please describe.**

Currently all documentation pages are "dead ends" unless we manually add links at the end of the markdown files.

**Describe the solution you'd like**

Add a component to the [docs.js template](https://github.com/ethereum/ethereum-org-website/blob/dev/src/templates/docs.js) that automatically generates "Previous" & "Next" links at the bottom of every page.

Design screenshot:
![Image 2020-10-19 at 2 17 52 PM](https://user-images.githubusercontent.com/8097623/96512811-e6291f80-1215-11eb-978a-9f9aa5b2ca4f.png)
(on mobile, these buttons should stack)

Figma design file:
https://www.figma.com/file/dclyxiMIYeAGUSgJoV3xdc/Sketches?node-id=34%3A1934

The logic for how the links should be generated should follow the sequential structure of [/data/developer-docs-links.yaml](https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/developer-docs-links.yaml). Specifically:
- If current page is the first item of a section (e.g. /developers/docs/intro-to-ethereum/), hide "Previous" link
- If current page is within a section, link "Previous" and "Next" to its siblings
   - e.g. if the page is /developers/docs/smart-contracts/anatomy/
      - "Previous" should be /developers/docs/smart-contracts/languages/
      - "Next" should be /developers/docs/smart-contracts/libraries/
  - e.g if the page is /developers/docs/smart-contracts/
      - "Previous" should be /developers/docs/ethereum-stack/
      - "Next" should be /developers/docs/development-networks/ (since it's the next sibling, even though this page has children pages)
- If current page is the last item of a section, link "Next" to first item of next section
   - e.g. /developers/docs/mining/ should link "Next" to "/developers/docs/ethereum-stack/"
- If current page is the last item of last section (i.e. /developers/docs/layer-2-scaling/), hide "Next" link

Ideally the implemented solution doesn't hardcode any paths into the logic (e.g. don't check if location.pathname === "/developers/docs/layer-2-scaling/" in order to hide the "Next" link, instead can you find a solution to traverse the tree & identify if it's the last node?)

**Describe alternatives you've considered**
- Manually set next & previous of each page 👎 

**Additional context**
When implementing your new component, use our `<Link />` component to perform the linking.

**Comment by wackerow** [comment]
Taking a look at this now if you want to assign me!
