### ISSUE TITLE
Replace <Icon> component with FontAwesome

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1651]
**Is your feature request related to a problem? Please describe.**

Our current [`<Icon />` component](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Icon.js) is fairly inflexible - we must add SVG code every time we want to add a new icon.

**Describe the solution you'd like**

Let's use [Font Awesome](https://github.com/FortAwesome/react-fontawesome) or some other free / open source alternative.

**Describe alternatives you've considered**
Keep as is

**Additional context**
See [ESP site](https://github.com/ethereum/esp-website) as example of Gatsby project using Font Awesome.

**Comment by howdyAnkit** [comment]
Maybe You can use REACT-ICONS and "IconContext" for this. It comes with simple NPM installations and supports various other Icons under one package.

REACT-ICONS comes with various icon support and it's really flexible you can check this link for reference 
(https://react-icons.github.io/react-icons/icons?name=bi)

**Comment by samajammin** [comment]
@howdyAnkit thanks for the suggestion, that sounds good to me! Let's use Font Awesome icons via `react-icons`.

**Comment by howdyAnkit** [comment]
Hey, @samajammin Can you please assign this to me? if it's not claimed

**Comment by samajammin** [comment]
@howdyAnkit thanks for offering to take this on! 💪

**Comment by howdyAnkit** [comment]
Thank you so much Sam this means a lot to me @samajammin

**Comment by samajammin** [comment]
Solved in #1674 & #1701
