### ISSUE TITLE
Imgbot -- Feature Request

### ISSUE THREAD

**Issue by howdyAnkit** [ethereum/ethereum-org-website#1658]
**Is your feature request related to a problem? Please describe.**

lazy loading feature
I have seen few images on the homepages taking an ample amount of time to load maybe due to the Image size being heavy

**Describe the solution you'd like**

Imgbot can be really helpful to solve this problem. it's free for open-source and it'll be very useful for ethereum main-page website

**Describe alternatives you've considered**

Other I am not aware of but would love to hear any other suggestions on this topic/alternatives present similar or better than Imgbot

**Additional context**

You can check Imgbot here
Imgbot:- https://imgbot.net/

**Comment by wackerow** [comment]
Curious the experience you're having and if it has anything to do with the fade-in animation effect the images have. 

I have personally thought there were issues with the images loading until I realized this transition was coded in. It will cause images to be blurred when they first appear on screen and then sharpen up. 

So, not sure if that applies to what you're experiencing or not, but at the very least figured it was worth noting my experience with that effect. It gives me the _feeling_ of a slow loading website to be honest.

**Comment by wackerow** [comment]
Hm.. I apologize... now that I'm looking at this again, I think I am mistaken with that comment and was getting it confused with a different transition effect I noticed. Got me curious though, gonna take a peek at imgbot... I'll let ya know if I think I can help

**Comment by howdyAnkit** [comment]
Thankyou @wackerow for the mention if you're still facing any confusion you can check my PR of the forked version link below

Link:- https://github.com/howdyAnkit/ethereum-org-website/pull/1/files

**Comment by samajammin** [comment]
@wackerow interesting to hear your experience! Thanks for weighing in. There is indeed an intentional "blur-up" effect. You can learn more about how we've implemented image processing & rendering here: https://www.gatsbyjs.com/plugins/gatsby-image/

**Comment by wackerow** [comment]
@samajammin I thought so! I swore I saw something like that, but then I couldn't recall the exact wording (still new to Gatsby) and couldn't find it when I looked again..
Noticed ```The gatsby-image component automatically sets up the “blur-up” effect as well as lazy loading of images further down the screen.``` on their page, guess I'm curious how this option compares to the the imgbot you suggested @howdyAnkit... constantly learning hah

**Comment by samajammin** [comment]
I believe they could work together. From my understanding, Imgbot performs lossless compression on the image files themselves to reduce the size of the source image. Gatsby Image optimizes the loading & rendering of the images.

**Comment by howdyAnkit** [comment]
Commenting for removing stale and 
awaiting this issue to get merge https://github.com/ethereum/ethereum-org-website/pull/1905

**Comment by samajammin** [comment]
Solved in #1905
