### ISSUE TITLE
Morpher component not cycling back to start after last word

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#1661]
**Describe the bug 🐞**
Currently `Morpher.js` component will iterate through an array of words to "morph" through, but upon reaching the last word the counter does not properly reset and the last word in the list persists.

**To Reproduce**

1. Go to 'www.ethereum.org' on desktop-sized screen
2. Slightly shift your gaze just below the home banner on the right side
3. Wait patiently for it to cycle through all 18 translations available
4. Gets stuck on last word

**Expected behavior**
Expect each name be displayed once at a time, in order, then cycle back to the first item after the last.

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/96752730-bb5cd980-1383-11eb-8c47-76c8af175ae4.png)
..Just to make it clear which component we're talking about, but it's more of a dynamic thing (I'll spare the video or looping gif)

**Desktop 🖥:**
- OS: macOS Big Sur
- Browser: Brave
- Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64)

**Smartphone 📱:**
- Device: iPad Pro
- OS: iPad OS 14
- Browser: Brave

**Additional context**
Will take a look at this myself.

_(While I'm looking at this, any thoughts on making this component a link to `/languages/`?)_

**Comment by samajammin** [comment]
Thanks for reporting @wackerow. I think having this link to `/en/languages/` is a great idea!

**Comment by wackerow** [comment]
Patching now!
