### ISSUE TITLE
Warning: React does not recognize the `marginLeft` prop on a DOM element

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#1667]
**Describe the bug**
```
index.js:2177 Warning: React does not recognize the `marginLeft` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `marginleft` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in span (created by Emoji)
    in Emoji (created by Twemoji)
    in Twemoji (created by Emoji__StyledEmoji)
    in Emoji__StyledEmoji (at Emoji.js:14)
    in Emoji (at Mobile.js:317)
    in div (created by Mobile__BlankSearchState)
    in Mobile__BlankSearchState (at Mobile.js:316)
    in div (created by ForwardRef(MotionComponent))
    ...
```

Getting this error since Twemoji implemented. There are four console errors, one for each `prop` being passed to `<StyledEmoji />` component (`marginLeft`, `marginTop`, `marginRight`, `marginBottom`), and it essentially tells you how to fix it in the error.

**To Reproduce**

1. Run project locally
2. Go to http://localhost:8888/en/
3. View console error

**Expected behavior**
Properly display Twemojis without console errors, passing margin props appropriately.

**Desktop:**
- OS: macOS Big Sur
- Browser: Brave (Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64))

**Smartphone:** _not tested_

**Additional context**
Looks pretty straight forward... will put into PR fixing prop names

**Comment by khokho1986** [comment]
`3AhLfoVCK1UcA8VjCDu6r1ZQTLEdVq3LPc`
