### ISSUE TITLE
ESLintError: React Hook useEffect has missing dependencies

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#1672]
**Describe the bug**
```warning  React Hook useEffect has missing dependencies: 'morphTimeout', 'morpher', 'state.text', and 'state.words'. Either include them or remove the dependency array```

Getting this since my `Morpher.js` update where I included an empty array to the `useEffect` dependencies argument.

**To Reproduce**
1. Run project locally with `yarn start`
2. See console warnings

**Expected behavior**
Morpher works properly without producing a linter warning. 

**Desktop:**
- macOS Big Sur

**Additional context**
Wanted to make note of this, will fix with PR shortly

**Comment by wackerow** [comment]
Hm.. scratching my head a little on this one. Removing the `[]` from `useEffect(() => {...}, [])` totally screws up the text rendered, as it's getting interrupted somewhere during the text transition... and adding `[morphTimeout, morpher, state.text, state.words]` does the same thing.
This was why I placed it in there to begin with, since all the looping logic is handled within one single run of `useEffect`, so I wanted the list of dependencies to be forced to nothing, so it executes once on mounting, but never again. 

@samajammin Thoughts on how to address this?

**Comment by mnewlin** [comment]
setState({ ...state, text: string.join("") }) is causing useEffect to be triggered which then calls clearTimeout(morphTimeout) and stops the update function from getting called again before it finishes the transition.

**Comment by mnewlin** [comment]
Moving clearTimeout(morphTimeout) to be right before calling new setTimeout each time.
