### ISSUE TITLE
Pillar

### ISSUE THREAD

**Issue by jacabass** [ethereum/ethereum-org-website#1686]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

Yes, except those countries on the global sanctions list.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial smart wallet - users have access to their private keys to recover their key-based wallets and can set up Recovery Devices to access their smart contract-based wallets in the event of losing their phone, private key, or the service stoppage.

**Please provide information on your latest security audit**

We have an ongoing bug bounty program with HackerOne: https://hackerone.com/pillarproject

**Does the wallet have fiat on-ramps?**

Provides on-ramps for US users through the native integration of [Wyre](https://www.sendwyre.com/) and for EU/UK users thanks to in-app services from [Ramp.Network](https://Ramp.Network) and [Altalix](https://altalix.com/).

Transaction fees are subsidised on a special occasion i.e. the new service's launch or the release of a new feature.

**Does the wallet allow users to explore dapps?**

It allows for it through the WalletConnect integration - users can connect to dapps using their Pillar Wallets. We made a conscious choice of not implementing a dapp browser to bring a better experience through native integrations. 

**Does the wallet have integrated defi/financial tools?**

Currently, Aave, PoolTogether, Sablier, 1inch, and Uniswap services are integrated into the app and users can use those products directly in the app's UI. TokenSets, Rari.Capital and Synthetix integrations are in the production pipeline.

**Can a user withdraw to their card?**

No fiat off-ramp option as of now - planned in the future though.

**Does the wallet offer limits protection?**

Not available currently, but on our roadmap.

**Does the wallet allow high-volume purchases?**

It does.

**Does the wallet have an integrated token swap?**

It does, offers are sourced from Uniswap and 1inch at the moment - can be expanded to other services in the future.

**Is the wallet a multi-signature wallet?**

It's not. 

**Wallet title**

Pillar

**Wallet description**

Non-custodial, community-owned wallet with its own L2 Payment Network.

**Wallet logo**

Please use the "Full Black" logotype: https://zeroheight.com/035a8f23d/p/77c5dd-brand-logo

**Brand color**

#00FF24 as in our Media Kit: https://zeroheight.com/035a8f23d/p/581e1b-colors

**Comment by GeorgeTrotter** [comment]
Hey @jacabass - just letting you know we finished processing this and Pillar is up on the website!

**Comment by jacabass** [comment]
Thanks so much, George! Can I just ask to change it from *Pillar Project* to
just *Pillar *- this is a part of actual's wallet branding.

Cheers!

**Comment by samajammin** [comment]
@jacabass updated in https://github.com/ethereum/ethereum-org-website/pull/1855
