### ISSUE TITLE
Bug in blog.ethereum.org -- wrong LinkedIn link

### ISSUE THREAD

**Issue by bmann** [ethereum/ethereum-org-website#17]
The footer of https://blog.ethereum.org has a LinkedIn icon that links to https://linkedin.com/in/ethereum -- this is a person, not an

I couldn't find the source of this blog, otherwise I would have made a pull request to help fix it.

If we're going to link to LinkedIn at all, people probably meant to link to https://www.linkedin.com/company/ethereum/ -- which should be labelled as Ethereum Foundation.

Filed in [ECH 35](https://github.com/ethereum-cat-herders/PM/issues/35)

**Comment by alancwoo** [comment]
@Souptacular do you have access to the blog codebase?

Indeed this link doesn't work

![image](https://user-images.githubusercontent.com/1481890/57053260-2d6fc900-6c8d-11e9-819d-0b55b40591d7.png)
