### ISSUE TITLE
Ethereum.org not forcing https

### ISSUE THREAD

**Issue by tayvano** [ethereum/ethereum-org-website#170]
If my assumption that Ethereum.org utilizes aws cloudfront, enforcing https (aka redirecting all http traffic to https) is as simple as checking a checkbox in AWS:

To configure CloudFront to require HTTPS between viewers and CloudFront

1. Sign in to the AWS Management Console and open the CloudFront console at https://console.aws.amazon.com/cloudfront/.

2. In the top pane of the CloudFront console, choose the ID for the distribution that you want to update.

3. On the Behaviors tab, choose the cache behavior that you want to update, and then choose Edit.

4. Specify the following values for Viewer Protocol Policy: Redirect HTTP to HTTPS

Reference: https://twitter.com/_prestwich/status/1161420491652866049?s=19

**Comment by jjmstark** [comment]
thanks @tayvano! Devops is aware of the issue and working on it.

**Comment by jjmstark** [comment]
This has been fixed. FYI, this was intentional - forcing redirect to HTTPS can sometimes cause issues for users visiting ethereum.org from China. But we've switched to forcing for now, and will continue to evaluate if this is still an issue.
