### ISSUE TITLE
Ethereum Studio is using a **very** outdated version of Solidity

### ISSUE THREAD

**Issue by franzihei** [ethereum/ethereum-org-website#1704]
Hey guys, 

Sorry for not using any of the issue templates, but none of them seemed to fit for my matter: 

## The Problem

"Ethereum Studio" is promoted quite prominently in the developer sections of ethereum.org. It looks like a great and clean web-based IDE, however, it is using a **very outdated** version of Solidity. It seems to be using v0.5.10 (even though I could not find a proper information about that anywhere in the interface, except for by looking at the sol contract directly). Solidity 0.5.10 was released on 25 Jun 2019. Just to give some perspective: We aim at releasing v.0.8 until the end of the year. So it is a couple of breaking releases behind.

**Why is this problematic?**
- Solidity as a language is still evolving rapidly. We do non-breaking releases every 2-3 weeks, aiming for a breaking release approx. every half year. Why so many releases? Mainly for fixing bugs, adding features and making changes to the language design itself. 
- It is **highly encouraged** to always use the latest version of Solidity to ensure that you use the safest and most up to date version. Every learning tool and even more importantly IDE needs to encourage using the latest version! By "getting started" with an outdated version like 0.5 and using an IDE where it does not seem possible to use a more up-to-date version of the compiler this is certainly not ensured.
- It is anyways super hard to get devs to update their code and to always use the newest versions of Solidity, so we should try to avoid promoting tools that use an outdated version.

## Solution Ideas

I'm not really an expert in Ethereum Studio: 
- Is there a way to make it use the latest version of the compiler (for now that would mean a 0.7.x release, or soon a 0.8.x release)?
- If there is no way to update it, we should consider removing Ethereum Studio from the website, or at least not placing it so prominently. 

Looking forward to hearing your thoughts about this!

**Comment by samajammin** [comment]
Hey @franzihei - thanks for raising this issue! I completely agree it's suboptimal. We simply haven't had the bandwidth to update it. This is one of the reasons we've taken steps to de-emphasize Ethereum Studio (to see, compare the [current English page](https://ethereum.org/en/developers/learning-tools/) to an outdated [translation page](https://ethereum.org/de/build/) - we've removed it from the primary site navigation & significantly de-emphasize it compared to other web tools).

The Ethereum Studio repo can be found here:
https://github.com/SuperblocksHQ/ethereum-studio

There's an open issue on this here, which I encourage you to weigh in on:
https://github.com/SuperblocksHQ/ethereum-studio/issues/244

I'm going to close this issue out but feel free to re-open if there's further changes you believe we should make specifically to ethereum.org vs. Ethereum Studio.
