### ISSUE TITLE
Add mobile TableOfContents to static page templates

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1705]
**Is your feature request related to a problem? Please describe.**

Currently the `<TableOfContents />` component in the static template is hidden on mobile. As a result, mobile users have no way to navigate the page other than scrolling.

**Describe the solution you'd like**

Refactor the [static template](https://github.com/ethereum/ethereum-org-website/blob/dev/src/templates/static.js) to function like the [docs template](https://github.com/ethereum/ethereum-org-website/blob/dev/src/templates/docs.js#L205), which included 2 TableOfContents - 1 for desktop (which is hidden on mobile) & 1 for mobile (which is hidden on desktop).

**Describe alternatives you've considered**
Keep as is

**Additional context**
In order to render the mobile version, [pass `isMobile={true}` to the TableOfContents component](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/TableOfContents.js#L309).

**Comment by wackerow** [comment]
Will take a look at this 👍
