### ISSUE TITLE
Add more entries to ethereum.org glossary

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1718]
As the first iteration of the ethereum.org glossary is based on Mastering Ethereum there are plenty more terms that have entered the Ethereum lexicon since it was published. This PR is open to anyone who wants to add terms to the glossary. Some examples, I can think of straight away:

- ZK snarks
- ZK rollups
- Optimistic rollups
- Layer 2
- Sidechains
- Rollups
- Shard chains
- Staking
- defi
- stablecoin

This list is not exhaustive, there are plenty more, so feel free to open a PR with any terms you feel are important.

### Acceptance criteria
- [ ] Descriptions include anchor links to other glossary terms if mentioned
- [ ] Where there are specific ethereum.org pages that cover the term, include a link so the user can get more information
- [ ] The term is added under the correct letter
- [ ] The term title includes a `{#term-title}` so that it can be access via the table of contents and anchor links.
- [ ] The term isn't a product advertisement

**Comment by samajammin** [comment]
Another glossary source: https://ethdocs.org/en/latest/glossary.html

License is also CC: https://github.com/ethereum/homestead-guide/blob/master/LICENSE-CC-BY-SA-4-POINT-0

**Comment by samajammin** [comment]
Solved in #2015 #1728 #1725
