### ISSUE TITLE
Inconsistent capitalization of "Ethereum"

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#1727]
**Describe the bug**
Noticed this first on `/en/community` page where there are multiple uses of lowercased "ethereum" when referring to the name of the network. Throughout this repo this term is consistently capitalized (in over 4200 places when searching), but in a handful of places this convention is not followed.

**To Reproduce**

1. Go to https://ethereum.org/en/community/
2. ie: `r/ethereum - all things ethereum`

**Expected behavior**
Would expect all used of Ethereum the network to be capitalized. This of course does not apply to variable names, references to ethereum.org or other similarly appropriate uses of lower cased 'ethereum.'

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/97928738-82761a80-1d1c-11eb-856e-145d7e10a80d.png)

**Additional context**
_I will defer on any alteration to the non-English pages at the moment..._
Please assign me if you're okay with an update to the English pages and I will put up a PR.

**Comment by ryancreatescopy** [comment]
great find. Ethereum, the noun, should always be capitalised unless referring to `ethereum.org` in which case we leave it lower case.
