### ISSUE TITLE
UI/UX Glossary linking enhancement

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#1737]
**Is your feature request related to a problem? Please describe.**
Suggested by @ryancreatescopy -- This is a continuation of #1724 with goal to improve the UI/UX of the links on the glossary page by adding styling to further differentiate between different types of links beneath definitions (internal anchor links, vs links to external pages).

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/40891631/97992150-34275100-1dda-11eb-9150-f44180609a03.png)
(pulling in the page title and meta description to populate the content)

**Describe alternatives you've considered**
- Leave internal anchor links with default anchor styling (colored, underlined) and 👉 emoji (as implemented in #1724)
- Leave internal anchor links with default anchor styling (colored, underlined) without emoji indicator

**Additional context**
May wait til other PRs get merged to avoid confusion/conflicts, but will take a look at this.

**Comment by wackerow** [comment]
@ryancreatescopy Have a component started to address this, but I may need your help with writing the query to pull in the `title` and `description` from the document being linked to. 

My thought was to have a component called something like `<DocLink>` with all the templating and styling. Import into the `static.js` and `MDXProvider`. In the glossary `.md` file, this could then be used in the form of `<DocLink to="/en/developers/docs/accounts" />`...

..but I'm not quite sure how to then query using that path to get the correct `.md` document, and parse out the `title` and `description`. Using static data I've got a working version, but would obviously prefer to make it dynamically pull in what's needed with a query for many reasons. 

Lemme know what you think!

**Comment by samajammin** [comment]
We might just have to bite the bullet & hardcode the title & description. Gatsby's GraphQL doesn't support dynamic queries (queries with variables) since it runs them on build: https://www.gatsbyjs.com/docs/static-vs-normal-queries/

**Comment by samajammin** [comment]
(There also may be a clever way of accomplishing this that I just haven't thought of)

**Comment by wackerow** [comment]
Okay, well I guess it wasn't just me then hah... I'll parse these out today

**Comment by wackerow** [comment]
Closed with #1753
