### ISSUE TITLE
Add TokenPocket wallet

### ISSUE THREAD

**Issue by chendatony31** [ethereum/ethereum-org-website#1749]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

YES

**Is your wallet custodial, non-custodial, or a hardware wallet?**

non-custodial

**Please provide information on your latest security audit**

No security audit, but open-sourced part of the code. check here:  https://github.com/TP-Lab/tp-android

As a Decentralization wallet, we have been running stably for 3 years without any wallet security incident. The cumulative number of TokenPocket wallet users worldwide has exceeded 5 million, and our community users cover more than 100 countries and regions around the world.

**Does the wallet have fiat on-ramps?**

YES.We provide some third-party fiat currency trading platforms for users to choose, such as https://localbitcoins.com/, https://www.luno.com/wallet/

At present, we do not provide users with GAS fee subsidies, but we provide GAS gas stations, transaction acceleration and other functions to help users transfer faster and smoother.

**Does the wallet allow users to explore dapps?**

Yes, we have developed an ETH browser to allow users to directly use the wallet to experience the rich dapp on ETH.

We have integrated with WalletConnect and a dapp browser fully compatible with metamask. In addition, we also support iOS/Android native SDK for APP to log in, auth and send TXs, check:  https://github.com/TP-Lab/Mobile-SDK

**Does the wallet have integrated defi/financial tools?**

Yes, we have included most of the DEFI and financial tools on Ethereum, and developed the DEFI market function to facilitate users to view the UNISWAP trading currency market.

YES

**Can a user withdraw to their card?**

No. Currently, the wallet does not provide this service, users can use the third-party application on the wallet platform to achieve this purpose.

**Does the wallet offer limits protection?**

NO

**Does the wallet allow high-volume purchases?**

NO

**Does the wallet have an integrated token swap?**

Yes

**Is the wallet a multi-signature wallet?**

NO

**Wallet title**

TokenPocket

**Wallet description**

TokenPocket：A secure and convenient world-leading digital currency wallet and a portal to DApps, with Multi-chain supported. 

**Wallet logo**

![TokenPocket Logo]( https://tp-lab.tokenpocket.pro/tokenpocket-logo.svg) 

**Brand color**

#2761e7

**Comment by chendatony31** [comment]
Hi, @GeorgeTrotter, If you have any questions, you can ask me.

**Comment by samajammin** [comment]
Nudge @GeorgeTrotter

**Comment by GeorgeTrotter** [comment]
Hey @chendatony31, thanks for following up! Everything looks good here, TokenPocket should go live onto the site the next time we updated our wallets, which (I think!) will be this week! We'll update this issue when it goes live.

**Comment by samajammin** [comment]
Solved in #1956
