### ISSUE TITLE
UI/UX Community upgrade

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#1762]
**Is your feature request related to a problem? Please describe.**
PR #1738 re-structures the navigation sections (pulling **Community** to it's own section). This "section" currently is a single markdown page.

**Describe the solution you'd like**
- Re-design `/community/` section into a `community.js` page-conditional, instead of using `/content/community/index.md`
- Include some new graphics and potentially give this a theme inline with new Eth2 section changes
- UX that makes buttons to places like GitHub, Reddit, Discord, Meetups far more obvious, prominent and enticing/inviting
- Potentially include improved way for users to add events, and automatically remove expired events
- Potentially include social media widgets
- Most importantly, wanted to open the discussion for more ideas here

**Describe alternatives you've considered**
Keeping/expanding current markdown file

**Additional context**
(**Draft** PR to follow to start a collaborative approach to this and get the conversation going)

**Comment by samajammin** [comment]
@wackerow thanks for raising this issue!

Overall I like this idea, I just think we should outline pros/cons of this approach so that we're mindful of any potential downsides.

Seems like the main "pro" or goal of this would be to improve UX? By changing this from a Markdown page to a component page, we can add more features, like automatically hiding historical events. Anything else?

To me a potential "con" to consider is: does this increase the barrier to contribute? Now, to add an event to the site, someone needs to understand JavaScript vs. just Markdown. Anything other potential issues that this change might create?

**Comment by wackerow** [comment]
@samajammin Yeah, in general I see that as the main advantage of markdown (simplicity), but of course there is the trade off between simplicity and flexibility

So this stemmed from two things... one was the decision to pull `Community` into it's own category, and the other was my previous experience with that page where I had visited multiple times and didn't feel very enticed to read through all of it. I have since discovered some things (while playing around with the source code) I hadn't even noticed before because it blended in to the all-text format... Some of those things I had previously been passively looking for, like the reddit/discord communities, but missed because I didn't read for it. I guess after playing with some of these changes I found some simple graphics can really draw your eye to these communities.

My argument for JS would be the ability to more flexibly enhance the page with enticing graphics, card layouts, better tables, and things like event filtering. 
**Note**: With current structure the `jobs`, `daos`, `forums`, and `events` data are each stored in arrays, and this could be pulled out to maybe a `yaml` file where adding new events would be cake.

**Comment by wackerow** [comment]
Gonna revisit this soon and I'll mull over ways to keep this as a markdown while still sprucing it up with some components, with easy-to-edit data. I'll let ya know what I come up with and if I still think it's worth converting to js.

**Comment by samajammin** [comment]
Assigning to @ryancreatescopy recognizing this may not be a priority soon 😬 😄

**Comment by wackerow** [comment]
(PR #1763 still open for this)

**Comment by wackerow** [comment]
Closing for now, can always revisit.
