### ISSUE TITLE
Eth2 Banner bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1768]
**Describe the bug**

Occasionally the eth2 banner doesn't render correctly. I've had this error on both mobile and desktop, pre and pose v2.10.0 deploy. 

**To Reproduce**

1. Go to an /eth2 page
2. Look at banner 

**Expected behavior**

Banner should have a primary colour background and text should be centered.

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/98730314-00c56300-2394-11eb-9e1e-f990bdc739ab.jpeg)

**Comment by tvanepps** [comment]
![image](https://user-images.githubusercontent.com/27454964/98748155-1b450f80-2387-11eb-8865-b2857efa7b2e.png)

yup, seeing the same issue on desktop

**Comment by wackerow** [comment]
Fixed =)

**Comment by samajammin** [comment]
This appears to still be an issue:
![Image 2020-11-13 at 3 11 40 PM](https://user-images.githubusercontent.com/8097623/99129471-8d556880-25c2-11eb-87c5-e36de2e07987.png)
