### ISSUE TITLE
Ethereum Foundation donations wallet

### ISSUE THREAD

**Issue by sneg55** [ethereum/ethereum-org-website#177]
I was wondering what's happened with EF donation wallet from the old site? 
https://etherscan.io/address/0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359 

http://web.archive.org/web/20190330174149/https://www.ethereum.org/donate

**Comment by jamesconnolly93** [comment]
Tangentially related to this issue, any thoughts on making ethereum.org a verified BAT publisher? There are probably a lot of people in the community who are using Brave and earning BAT would would be interested in tipping the EF.

**Comment by jjmstark** [comment]
hey @sneg55 - since the website re-launch, ethereum.org is no longer considered "the website for the Ethereum Foundation", but rather a general resource about Ethereum. When a new separate site for the EF launches, it will host things like links to the donation wallet.
