### ISSUE TITLE
Warning messages on upgrade pages cut off

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1772]
**Describe the bug**

On the Eth2 upgrade pages, the warning message about scammers does not have sufficient top padding/margin on mobile. So appears cut off by the Eth2 staking banner. 

**To Reproduce**

1. Go to `/eth2/beacon-chain/` `/eth2/shard-chains/` or `/eth2/docking/`
2. See banner

**Expected behavior**

There should be greater padding so you can see the whole banner. As a nice-to-have you should be able to dismiss the banner and we remember this preference in local storage.

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/98796713-99df9280-2403-11eb-88c4-1233933e8856.png)

**Comment by ryancreatescopy** [comment]
This issue was not fixed in the latest deploy

**Comment by wackerow** [comment]
![image](https://user-images.githubusercontent.com/54227730/99141702-c8778c00-2602-11eb-96b1-19b6fc6a4414.png)
(Brave on left, Safari on right)

I'm gettin strange results when reproducing this. Brave on desktop displays it fine, even if you shrink the size to mobile. Brave on iOS renders incorrectly, as does Safari on both iOS and desktop. 

![image](https://user-images.githubusercontent.com/54227730/99141657-543ce880-2602-11eb-9864-472865f1127e.png)
(Brave on left, Safari on right)

The dev tools in Safari show that the margin is correct on <MainContainer>, but the content does not seem to be obeying this. Not sure why this is, but thought I'd share what I noticed so far.
