### ISSUE TITLE
Mobile nav should include search

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1774]
**Is your feature request related to a problem? Please describe.**

At the moment the interaction for searching on mobile is not obvious and a little cumbersome. Using a top right icon, followed by a bottom-left icon isn't comfortable and it's not clear where to find search.

**Describe the solution you'd like**

I believe search should be always available on mobile from the header. Navigation is already more difficult on mobile due to a lack of an omnipresent header. Search in a tap from any page would be a nice UX improvement for moving around the site.

**Describe alternatives you've considered**

Alternatively, we could move search to sit at the top of the mobile menu, but I think this is also suboptimal as it doesn't improve the discoverability of the feature.

**Additional context**

**Comment by samajammin** [comment]
Solved in #1775
