### ISSUE TITLE
Expand/collapse codeboxes

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1776]
**Is your feature request related to a problem? Please describe.**

Our codebox component can make our docs pages a little cumbersome, especially when we show an entire contract or a lot of code. We should introduce the ability to expand/collapse the codebox. 

**Describe the solution you'd like**

The codebox should be collapsed by default. But the collapsed state should show a few lines of the code. 

While adding the button to show/hide code, we should revisit the button design. The primary purple color can be a little harsh on the codebox background.

See problem below

<img width="1525" alt="Screenshot 2020-11-11 at 12 15 05" src="https://user-images.githubusercontent.com/40891631/98810765-96560680-2417-11eb-8f2a-07f325e20d37.png">

![image](https://user-images.githubusercontent.com/40891631/98810819-acfc5d80-2417-11eb-9e0d-643ba88cfda3.png)

**Comment by wackerow** [comment]
Working on this now
