### ISSUE TITLE
Is this page useful? component

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1779]
**Is your feature request related to a problem? Please describe.**

To help us better prioritise content improvements, we should add a "Is this page useful?" component to our .js templates. 

**Describe the solution you'd like**

Add a 1-5 scale at the bottom of a template. A user can select one of the options and we'll get quantitative data of page ratings. 

**Describe alternatives you've considered**

We could do a binary "Is this page useful? Yes/No" – however it's felt that this may not be as useful for prioritisation.

**Comment by wackerow** [comment]
Curious, were you thinking about having any type of sybil resistance (user identifier / authentication)? Or keeping it simple and anonymous? In either case, how would we store the vote data using gatsby (or would you not)?

(And 👍 for Yes/No from a user standpoint... can only speak for myself but I click a lot more Up/Down arrows than I do 1-5 star ratings)

**Comment by ryancreatescopy** [comment]
I think we would leave this as anonymous. We're not interested in who's reviewed it so much as the general consensus on the content.

In terms of storage, I'm sure @samajammin might have some ideas on that front. 

And I hear you on the yea/no vs 1-5... perhaps if it's easier we stick to yes/no and see if it helps us and we can iterate on it later to add scales of usefulness.

**Comment by yakkomajuri** [comment]
Wondering where you'd want to have this data? 

I feel like one way with little overhead would be to send it as a custom event to Matomo since that's already integrated here?

Haven't used Matomo myself, but I assume I could pass an event name like `page_review` with a prop determining if it was helpful or not (e.g. boolean), and then a pathname (could be from `window.location.pathname`)

**Comment by wackerow** [comment]
@yakkomajuri Thanks for jumping in on this!... yes, Matomo sounds like the best approach here. @ryancreatescopy Any design ideas in mind on this one? I think simplicity is our friend, some binary type of vote.

**Comment by ryancreatescopy** [comment]
I agree, if we can ship something simple, hooked up to matomo:

```
Was this page helpful? Yes/No
```

and then we can go from there once we see usage...

**Comment by minimalsm** [comment]
I think this issue was closed by #2745

<img width="702" alt="Screenshot 2021-04-16 at 12 46 18" src="https://user-images.githubusercontent.com/62268199/115019942-c36c8080-9eb1-11eb-99d9-c711f0d86e9b.png">

**Comment by wackerow** [comment]
Indeed it was... thanks for the help brainstorming everyone!
