### ISSUE TITLE
XL screen layout for docs.js

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1780]
**Is your feature request related to a problem? Please describe.**

Our docs.js template doesn't render well on XL screens. 

**Describe the solution you'd like**

Ideally the content should remain central but background color and borders should respond to the size of the screen.

![image](https://user-images.githubusercontent.com/40891631/98813566-43cb1900-241c-11eb-8973-a4cd5a111426.png)

**Comment by wackerow** [comment]
Not sure _exactly_ what you're looking for here.... something like this?
![image](https://user-images.githubusercontent.com/54227730/98875132-754ddf80-2430-11eb-881e-b0a7ee845be1.png)

**Comment by ryancreatescopy** [comment]
@wackerow yep, that's it. I wonder if the left side nav might need a border-left too so it doesn't look too massive.

**Comment by minimalsm** [comment]
See comment [here](https://github.com/ethereum/ethereum-org-website/pull/2671#issuecomment-917183413) from @Scott1Up for a proposed design solution to this problem 😀

**Comment by wackerow** [comment]
Closing and resurfacing with new issue #4026
