### ISSUE TITLE
Add Github stars to developer products we list

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1782]
**Is your feature request related to a problem? Please describe.**

Throughout the developer section, we list developer products but we don't make it easy for users to pick one at a glance. For example: https://ethereum.org/en/developers/local-environment/

A bit of a vanity metric, but it would be useful for some users to see GitHub stars on these cards to help them make decisions quicker about which products to check out first. 

**Describe the solution you'd like**

These cards should show the number of github stars the projects have. For any project that isn't open source, we should reconsider listing them.

**Comment by wackerow** [comment]
Similar to #1783, could use a `get` request to `https://api.github.com/repos/{/user}/{/repo}`
ie: https://api.github.com/repos/ethereum/ethereum-org-website
In the return JSON there is a `stargazers_count` that can be used.

(You can assign me to this, I'll work on it simultaneous to #1783... again, design suggestions/guidance always welcome)
