### ISSUE TITLE
Add programming language labels to developer products we list

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1783]
**Is your feature request related to a problem? Please describe.**

Throughout the developer section, we list developer products but we don't make it easy for users to pick one at a glance. For example: https://ethereum.org/en/developers/local-environment/

It would be useful to include a tag or label that identifies the language the product uses, where relevant, to help users choose.

**Describe the solution you'd like**

These cards should show a language label relevant to the product. For any project that isn't open source, we should reconsider listing them.

**Comment by wackerow** [comment]
Language... meaning _programming_ language I assume? At first glance I thought you meant written language, ie. english. This appears to be contained in JSON object returned from a `get` request to `https://api.github.com/repos/{/user}/{/repo}/languages`
ie: https://api.github.com/repos/ethereum/ethereum-org-website/languages

(You can assign me to this and I'll take a stab at it... design suggestions/guidance always welcome)

**Comment by samajammin** [comment]
@wackerow yes - primary programming language. Thanks!

**Comment by wackerow** [comment]
Okay, _just_ the primary language? Or a list of pills for each?
