### ISSUE TITLE
Implement structure and categorisation for local environment page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1784]
**Is your feature request related to a problem? Please describe.**

At the moment, https://ethereum.org/en/developers/local-environment/ just lists a bunch of frameworks that a dev might find useful. However, we don't categorise these in any way. And it's unclear as to what part of the stack each framework/product covers.

We should improve this page by creating sections for different parts of the stack, e.g.:

- local blockchain
- smart contract frameworks (could even split between languages, libraries, etc.)
- front-end
- testing

Each part of the stack should have links to relevant docs to help tell the story. 

**Bonus points**

Your stack options will change dependent on whether you're writing your own smart contract vs using an existing one. We should reflect this in the page design. Perhaps a qualifying question that starts the experience: "Writing your own smart contract?" or a toggle. However the same is true that some frameworks/products won't be relevant if you're only writing a smart contract and have no frontend.

Can we show these things as sequential? Is there a sensible order?

Rather than just link to the products, should we include quick installation instructions for users that don't want to check out the product's site/repo, e.g. why insist a user visits the repo for create-eth-app when we can display the installation instructions in ethereum.org e.g. 

```
yarn create eth-app my-eth-app
cd my-eth-app
yarn react-app:start
```

Other ideas we've discussed:
- Treating the stack options like shopping items. You can add items to a page basket and then we display a convenient way for you to explore all the different product repos, websites, etc.
- Showing famous buidlers' stacks. Would it be useful for new users to see Vitalik's stack or Austin Griffith's stack? Or for community members to upload a stack they find works! How can we enable this kind of content on the page?

**A very rough, unfinished sketch**
![image](https://user-images.githubusercontent.com/40891631/98816295-59424200-2420-11eb-99ed-6b381ab5ebea.png)

**Comment by yakkomajuri** [comment]
There's an entire commented out section that essentially provides the main foundation for this - what (except the "bonus points" section) would the desired solution for this look like now? @ryancreatescopy
