### ISSUE TITLE
Content prototype: smart contract annotations/walkthrough

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1785]
**Is your feature request related to a problem? Please describe.**

User testing has indicated that it might be useful for new devs to have a walkthrough of popular smart contracts.

Walk through an end to end flow of a popular dapp, e.g. Aave and explain how it all works so users can understand how devs create liquidity pools or interest-generating tokens etc. 

Probably best to start w/ most basic flow of that machine. And we can add secondary journeys, if relevant, over time.

**Describe the solution you'd like**

Pick a popular dapp and write a walkthrough of the contract. The content should include prose descriptions of what is happening + code snippet examples.

Where this content would live is currently undecided.

**Comment by qbzzt** [comment]
Do you want more code walk throughs? If so, how about `Ownable` (https://docs.openzeppelin.com/contracts/3.x/access-control)?

**Comment by ryancreatescopy** [comment]
We're always interested in code walkthroughs. 

From a personal perspective I think it'd be really interesting to get walkthroughs of contracts of popular dapps that folks may have used like Uniswap ("Understand an automated market maker contract")... @samajammin @wackerow what do you think?

If you have the time @qbzzt maybe we as a team can figure out what walkthroughs we think would be useful and we can get back to you with some potentials and how we might structure this collaboration moving forward?

**Comment by wackerow** [comment]
I think `Ownable` is a smaller decent topic that users starting out with basic smart contract security should know about.

A walkthrough of an AMM contract would be really interesting in my opinion, but definitely more advanced. Depends how lengthy you were thinking @ryancreatescopy

**Comment by qbzzt** [comment]
Now that we are about to have a Solidity code walk-through, I think it would provide the most value if we add a Vyper one. Is Vyper stable enough for this to add value? If so, shall I take one of the contracts from https://github.com/vyperhub-io/vyper-smart-contracts and explain it?

**Comment by samajammin** [comment]
I love the idea of walking through the Uniswap contracts. The question is which version? v1 was in Vyper & is definitely the simplest. Perhaps it makes sense to start there?

**Comment by qbzzt** [comment]
The contract source code for Uniswap 1 (https://github.com/Uniswap/uniswap-v1/tree/master/contracts) is about 550 lines of Vyper

The contract source code for Uniswap 2 core (https://github.com/Uniswap/uniswap-v2-core/tree/master/contracts) is about 350 lines of Solidity, and the periphery (https://github.com/Uniswap/uniswap-v2-periphery/tree/master/contracts) is about 800 lines. 

So I agree, it would be easier to understand version 1.

**Comment by qbzzt** [comment]
@wackerow , does the reopening mean that we need more of these walkthroughs? If so, any ideas?

**Comment by wackerow** [comment]
@qbzzt hah I'd say more because we still haven't caught up on the last one 😬

**Comment by minimalsm** [comment]
Calling this solved by: https://ethereum.org/en/developers/tutorials/uniswap-v2-annotated-code/ and https://ethereum.org/en/developers/tutorials/erc-721-vyper-annotated-code/ :)
