### ISSUE TITLE
Get a user from 0 experience to a deployed thing as quickly as possible (minimum viable content)

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1787]
**Is your feature request related to a problem? Please describe.**

Minimum viable content for introducing a new dev to the world of Etheruem.

I think we can assume some level of coding experience in web2 technologies, but assume no knowledge when it comes to blockchain/ethereum. 

This content should aim to limit the amount of explanation and just get a user to build something on a local Ethereum chain or testnet **as quickly as possible**. The idea being that if a user is impressed enough by the tech, they'll go on to read the docs and level up their knowledge about etheruem/blockchain later.

The philosophy for this ticket is to make docs a support rather than a pre-requisite.

Feel free to be opinionated about products and paths. We understand there are plenty available to a new user, but what do you think is easiest?

**Inspiration**
https://hardhat.org/tutorial/
https://consensys.net/developers/onboarding-step-1/

**Comment by wackerow** [comment]
Just a thought: One thing I found fun that gained my interest was deploying an OpenZeppelin ERC-20 standard token to a testnet using Remix. Using the OZ libraries, this is really just a few lines of code, and using remix and metamask you can hop onto a testnet (with a quick stop to a faucet) and deploy within minutes. I suggest this given your comments about a minimalistic approach to perk interest, as you could hold off on explaining every detail here, as there is already a lot of abstraction done for you, and they'd be left with a custom (testnet) token in their wallet.

**Comment by qbzzt** [comment]
Do you want to use this? https://github.com/qbzzt/etherdocs/tree/master/startingout

**Comment by wackerow** [comment]
@qbzzt Thanks for posting this! @ryancreatescopy What do you think of something like this for what you're trying to accomplish here? This seems to involve some testing as well, which I agree is important, but for minimum viable content may be more than needed.

**Comment by qbzzt** [comment]
> @qbzzt Thanks for posting this! @ryancreatescopy What do you think of something like this for what you're trying to accomplish here? This seems to involve some testing as well, which I agree is important, but for minimum viable content may be more than needed.

I think testing is essential, because otherwise you're just writing code and hoping it runs correctly. It's a lot more comfortable when you can write a small piece, test it, and then add incrementally.

Do you want me to submit this in the tutorials area?

**Comment by ryancreatescopy** [comment]
Sorry for the delayed response my end. I think this would be cool to add as a tutorial for now.

My end goal with this issue is to create a "wizard-style" experience where we walk through the process and offer different steps based on different preferences (e.g. I want to build a defi app) users have or different OS's (e.g. I'm using Mac) etc...  

I think for now it's well worth having it on the site but I'd like to use this content later on to form this more "develop-along" experience. I also think it's worth us eventually being able to properly show off whole repos like this where the repo itself is as much a tutorial as the content. 

However I don't think that should block us adding this as a tutorial right now, so feel free to create a PR @qbzzt. 

From a technical perspective, does this tutorial take into account all the most recent tooling available? Or is it more foundational than that? I'm not a developer so it's hard for me to tell, but from what I understand tools like HardHat should be recommended for efficiency, right? Perhaps that's just personal preference but just want to make sure we're making this as easy as possible... @samajammin @wackerow

**Comment by PatrickAlphaC** [comment]
https://ethereum.org/en/developers/tutorials/deploying-your-first-smart-contract/ 

Does this already fit this request?

**Comment by qbzzt** [comment]
> https://ethereum.org/en/developers/tutorials/deploying-your-first-smart-contract/
> 
> Does this already fit this request?

I think so, for Remix. But I agree with @ryancreatescopy that we should have multiple tutorials for different environment, probably with a page that gives the developer enough information decide which would be best for them.

**Comment by PatrickAlphaC** [comment]
So like a "getting started" for hardhat/truffle/brownie/web3.py/ethersjs/web3js as well?

**Comment by wackerow** [comment]
I'm in favor of a Hardhat intro tutorial to get people going. Taking advantage of these tools should be encouraged imo. They help integrate the latest best security practices too.

**Comment by qbzzt** [comment]
> I'm in favor of a Hardhat intro tutorial to get people going. Taking advantage of these tools should be encouraged imo. They help integrate the latest best security practices too.

Hardhat has a pretty good tutorial at https://hardhat.org/tutorial/ . Maybe we should like to it?

**Comment by wackerow** [comment]
@ryancreatescopy  thoughts on this? This tutorial from Hardhat looks kinda like the wizard setup you were mentioning

**Comment by PatrickAlphaC** [comment]
I wanted to write a blog on getting setup with hardhat... but I feel like their docs really do the most justice it's weird to want to try to reproduce.

**Comment by qbzzt** [comment]
> My end goal with this issue is to create a "wizard-style" experience where we walk through the process and offer different steps based on different preferences (e.g. I want to build a defi app) users have or different OS's (e.g. I'm using Mac) etc...

For a wizard, how about:

1. Are you joining an existing project? **yes** -> show the list and tell them to use the tooling the project uses now, **no** continues down the list.
2. Are you developing a smart contract, or a user interface for an existing smart contract ? **user interface** -> https://ethereum.org/en/developers/docs/programming-languages/.  **smart contract** -> continue
3. Do you prefer C/C++/Java/Javascript style, or Python style? **Python** -> Vyper, **C/C++.../" -> Solidity
4. Do you prefer to develop with an IDE, or command line? **IDE** -> link to a remix tutorial, **command line** link to hardhat and truffle tutorials.

**Comment by spalladino** [comment]
> One thing I found fun that gained my interest was deploying an OpenZeppelin ERC-20 standard token to a testnet using Remix. Using the OZ libraries, this is really just a few lines of code, and using remix and metamask you can hop onto a testnet (with a quick stop to a faucet) and deploy within minutes. 

Just stumbled upon this issue. FWIW, we have created a Contracts Wizard where the user can customize their token (ERC20, 721, or 1155), export it to Remix, and deploy it on the spot by using Metamask. Sharing here in case it helps!

http://zpl.in/wizard

**Comment by minimalsm** [comment]
In its current state, this isn't something that we think a contributor could pick up (it is more of an epic than issue itself and requires far more context for someone to pick this up). We've captured this internally and will relist it when it becomes a priority again.
