### ISSUE TITLE
Small typo in ETH2 website

### ISSUE THREAD

**Issue by wendydv1989** [ethereum/ethereum-org-website#1790]
**Describe the bug**

https://github.com/ethereum/ethereum-org-website/blob/76ab215e3c644d86ed0b7bfc071e646a10be0ba7/src/pages/eth2/index.js#L669

Etheruem instead of Ethereum 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wackerow** [comment]
@wendydv1989 Thanks for mentioning this! Just put up a PR to fix.

**Comment by samajammin** [comment]
@all-contributors please add @wendydv1989 for bug reports.
