### ISSUE TITLE
Clicking on a markdown image leads to a 404

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1807]
**Describe the bug**

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/nodes-and-clients/
2. Click on one of the images
3. See 404 "not found" error

**Expected behavior**

- Should we prevent this images from being clickable?
- Should we expand / zoom in on the image?
- I *don't* think clicking on the image should navigate to a standalone page of the image - that doesn't seem useful

**Screenshots**

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

**Comment by wackerow** [comment]
My thoughts are, first priority find the bug (that link) and disable it from being clickable.

After that, a nice feature would be the images expanding (modal with dimmer background, maybe full width on mobile, with some margins on desktop, tap/left-click anywhere to toggle back). I agree that linking to another page for each image is a bad idea. 
That being said, with how relatively easy it is these days to zoom in on things manually if needed (and the fact these images are already pretty easy to see), I think the simplest option of just disabling these from being clickable should be considered.
