### ISSUE TITLE
Eth2 upgrades pages: banner overlaps PSA on mobile

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1817]
**Describe the bug**

On all Eth2 upgrades pages the staking banner overlaps PSA on mobile.

**To Reproduce**

1. Go to https://ethereum.org/en/eth2/beacon-chain/
2. See error

**Expected behavior**

No overlap!

**Screenshots**

![image](https://user-images.githubusercontent.com/8097623/99103246-2751ec80-2594-11eb-83b2-d085967a22a6.png)

**Desktop (please complete the following information):**

None

**Smartphone (please complete the following information):**

- Device: iPhoneX

**Comment by ryancreatescopy** [comment]
This is a duplicate of #1772

**Comment by samajammin** [comment]
Ah, thanks @ryancreatescopy!

Closing this in favor of #1772.
