### ISSUE TITLE
Set up Eth2 component pages for translations

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1826]
**Is your feature request related to a problem? Please describe.**
We recently updated most of our Eth2 pages from markdown files to fully featured React components:
https://github.com/ethereum/ethereum-org-website/tree/dev/src/pages/eth2

We need to set this content up for translation. 

**Describe the solution you'd like**
For each of these components:
1.  Move the English copy into [/intl/en.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en.json) - see [our homepage](https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/index.js) for an example of how this is done.
2. Replace the English copy with our `<Translation/>` component and/or the `intl.formatMessage()` function (again, see the homepage for an example of how this is done)

**Describe alternatives you've considered**
None

**Additional context**
- We the use [`gastby-plugin-intl`](https://github.com/wiziple/gatsby-plugin-intl) for our internationalization. That plugin's documentation may provide more context for how it works.

**Comment by ph5500** [comment]
I have experience setting up these translations with gatsby-plugin-intl. Would be happy to complete the steps above.
