### ISSUE TITLE
Tutorial template h2s/h3s

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1843]
**Describe the bug**

If you put a link or a `code`  in a h2/h3 title it doesn't display properly.

**To Reproduce**

1. Create a new tutorial in your local
2. Add `## Example h2 with [a link](https://google.com)` or `## Example h2 with `code` `
3. Preview in your local 

**Expected behavior**

Links should work/display in titles.
Code should inherit font size from header.

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/99181225-01a81d00-2725-11eb-99f0-e14e3af586c0.png)
![image](https://user-images.githubusercontent.com/40891631/99181273-62375a00-2725-11eb-8652-57d1060cdc68.png)

**Comment by wackerow** [comment]
@ryancreatescopy As for the link suggestion: Will this be valid HTML? The Header itself is parsed as a link, and this seems like it would cause nested anchor tags.
