### ISSUE TITLE
Markdown templates don't support GIFs

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1845]
**Describe the bug**

Gifs don't appear when added to markdown files.

**To Reproduce**

1. Add a gif to a markdown pagee
2. It won't display.

**Expected behavior**

Gifs should be supported.

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/99181789-c0b20780-2728-11eb-9fec-3cf4292ea3c5.png)

**Comment by wackerow** [comment]
`gatsby-config` seems to use `gatsby-remark-images` for md/mdx parsing which according to their docs:
![image](https://user-images.githubusercontent.com/54227730/99193662-505ab480-272f-11eb-8fc0-2188fdf67c65.png)

Looks like this would need to use `gatsby-remark-copy-linked-files` plugin. I can take a look at this.
