### ISSUE TITLE
Global-COM Group LLC (Advanced Digital Finance Advisors/Specialist)

### ISSUE THREAD

**Issue by BManess910** [ethereum/ethereum-org-website#1846]
GlobalBiT™ (Eth.NETWORK CRPT Token) © idea in place for crypto world. GlobalCOMGroupLLC@Github along with Global-SEC.NET(Network Blockchain Data Security Forces TEAM) aka Global Security Network GSN1 also have other projects/ideas/Plans for future platforms via Crypto World (All Aspects CRPT) Contact info: globalcomgroup.worldwide.network@gmail.com please contact TEAM for more information and questions about our special entities that coincide with all network partnerships and programs.Thank you, -GBManess (Founder)

**Comment by ryancreatescopy** [comment]
Closing this as it appears to be an advert not an issue. Open a new issue if you have a feature request or a bug to report. Thanks.
