### ISSUE TITLE
Docs incomplete mobile banner bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1848]
**Describe the bug**

The incomplete banner displays underneath the mobile table of contents for the docs 

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/layer-2-scaling/ on mobile 
2. See banner 

**Expected behavior**

You should see the full banner sitting underneath the table of contents.

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/99191944-f3c7bb80-2767-11eb-8cf9-2209f11f2630.png)

**Comment by wackerow** [comment]
Having a really hard time replicating this in dev locally. When I load up upstream/dev locally, this bug does not occur. Tried brave/chrome/safari/firefox on desktop and used `ngrok` to port over to my phone, which also displays correctly from the local branch, yet all of these continue to display incorrectly from `ethereum.org` or from a netlify build. 

Anyone have any ideas what could be going on here? There have been a few of these types of bugs lately I feel, where things render fine locally during dev, but glitch out when serving live. Figuring this out may help a couple issues we've been having.
