### ISSUE TITLE
Dapps page feedback

### ISSUE THREAD

**Issue by michael60634** [ethereum/ethereum-org-website#1856]
https://ethereum.org/en/dapps/

- Dharma no longer allows users to earn interest on Dai though Compound, so the description should be updated. The app does now have a major focus on an in-app integration with Uniswap, so maybe the description for Dharma should reflect this. Alternatively, Dharma could be removed from the dapps page.

- Uniswap should be added to the dapp page, as it is a very important dapp in the Ethereum ecosystem.

**Comment by ryancreatescopy** [comment]
Thanks @michael60634 — we're actually working on this page right now: #1810

We're likely removing dharma from the dApps page as they're listed on the wallets page. Uniswap will be added!

Appreciate the issue. We'll close this out when we ship that page. Feel free to drop any feedback in that PR.

**Comment by samajammin** [comment]
@all-contributors please add @michael60634 for ideas.

**Comment by ryancreatescopy** [comment]
Closed via #1810 #1903
