### ISSUE TITLE
Plate "Read about this artwork" hovers content

### ISSUE THREAD

**Issue by rumkin** [ethereum/ethereum-org-website#186]
Plate hovers the page content. For example a sidebar.

<img width="312" alt="Screen Shot 2019-08-22 at 01 29 10" src="https://user-images.githubusercontent.com/609373/63473094-f102eb80-c47c-11e9-99c6-582db40d5dbc.png">

**Comment by samajammin** [comment]
Thank you for raising this! We should only display the artwork callout on the homepage, which will resolve this issue. I'll label this as a `wip` once I hop on this. In the meantime, tagging this as a good issue for contributors to hop on!
