### ISSUE TITLE
Extra sidebar element on page load

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1866]
**Describe the bug**

If I open up a docs page from a link (e.g. https://ethereum.org/en/developers/docs/layer-2-scaling/), I'm seeing a strange extra `Layout__MainContent` element.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/layer-2-scaling/
2. See strange white element

**Expected behavior**

**Screenshots**

![Image 2020-11-16 at 4 58 51 PM](https://user-images.githubusercontent.com/8097623/99326627-461ee000-282d-11eb-81b1-a0658aa9efb8.png)

![Image 2020-11-16 at 4 58 44 PM](https://user-images.githubusercontent.com/8097623/99326584-4323ef80-282d-11eb-852e-1e6dd5ee32a9.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave

**Comment by wackerow** [comment]
(PR #1973 may fix this as well when it's ready... looking at it closer now)

**Comment by wackerow** [comment]
Reiterating a tl;dr form of the PR #1973 thread comments that relate to this issue:
- Cached versions of sites seem to be affecting certain DOM elements in strange ways
- (The above white space is an improperly styled "SideNavMobile" component)
- Clearing browser cache seems to fix this, but remains an issue for the end user who should not have to do that

(this was _not fixed_ by PR #1973, as suggested in my last comment)

**Comment by samajammin** [comment]
Thanks @wackerow, so are you still seeing this issue / have you been able to replicate it?

**Comment by wackerow** [comment]
@samajammin No, not after clearing cache, everything has been looking good... just makes me wonder if any end users are experiencing anything similar, but not sure there is much more to add to this for now.

**Comment by samajammin** [comment]
Seems like these might have something to do with toggling from light to dark mode 🤔 :
https://share.getcloudapp.com/Jruq6R8E

**Comment by wackerow** [comment]
Hm.. I had toggling dark mode fix the issue once. Not able to replicate this at the moment.
