### ISSUE TITLE
Layout margin issue when loading directly on a developers page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1867]
**Describe the bug**

When I land directly on a developer page (or hard refresh on the page), e.g. https://ethereum.org/en/developers/learning-tools/ our top margin is not set correctly.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/learning-tools/
2. See margin-top issue above h1

**Expected behavior**

`Layout__MainContainer` element margin-top should be 134px (`props.theme.variables.navSubNavHeightDesktop`), not 4.75rem (`props.theme.variables.navHeight`)
https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Layout.js#L37

**Screenshots**

Landing on homepage, then navigating to dev page (looks good):
![Image 2020-11-16 at 5 02 08 PM](https://user-images.githubusercontent.com/8097623/99326891-96963d80-282d-11eb-90c8-96b37d365e1e.png)

Landing directly on dev page (margin looks off):
![Image 2020-11-16 at 5 01 54 PM](https://user-images.githubusercontent.com/8097623/99326909-a746b380-282d-11eb-99bd-9e0a4f42a718.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave

**Additional context**

I suspect this has to do how we conditionally set margin-top in our Layout.js component:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Layout.js#L37
My hunch is that on initial page load, that prop is not getting properly set.

**Comment by wackerow** [comment]
I see this when I use ethereum.org or a netlify build but can't seem to reproduce locally, maybe that's a clue to what's going on.  When it hard-refreshes to one of those pages, you can actually see the content render before the developers nav bar even loads, and then when it does the content doesn't adjust. Will think about this and let you know if I figure anything out, but if you find a way to reproduce locally let me know.

**Comment by wackerow** [comment]
(#1973 addresses this)
