### ISSUE TITLE
Inconsistent capitalization of "Mainnet"

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1882]
**Describe the bug**

Similar to #1727, we use a mix of `mainnet` & `Mainnet` when describing the primary Ethereum network.

e.g.
- https://ethereum.org/en/enterprise/
- https://ethereum.org/en/glossary/#mainnet
- https://ethereum.org/en/developers/docs/networks/#mainnet

**Expected behavior**

We should come to an agreement on a canonical way to reference this term & update our content accordingly.

**Comment by wackerow** [comment]
I would say, in any use case if you theoretically replaced it with the word "network"... would you capitalize it? And in most cases, no, but if it's attached to the name of something, like Ethereum Network, or Matic Network, then it seems more appropriate to capitalize (as a formal name, or if it's contained within a title where every word is capitalized).
Curious what others have experienced with this elsewhere.

**Comment by samajammin** [comment]
@tasdienes any thoughts on this? How does EEA typically reference it? Looking at this press release, it seems to be _mostly_ lowercase `mainnet` ( though there's some inconsistencies there as well):
https://entethalliance.org/eea-mainnet-working-group-forms-task-force-eminent-ethereum-mainnet-integration-for-enterprises/

**Comment by tasdienes** [comment]
So historically it has been mainnet, but there is a movement (started in the EEA) to make it Mainnet, like the Internet.  As in there is only one Mainnet that businesses should be using, and the Mainnet is the Internet of value.  I don't have really strong feelings either way, but I have tended to use Mainnet.

**Comment by wackerow** [comment]
FWIW: Searched through the ethstaker discord logs for "mainnet", where they are very active utilizing the term (especially recently, about 1000+ results), and by _far_ lowercase "mainnet" is the most common (probably around 96-99% of usage). There is the occasional "MainNet" which I would definitely argue against. Then some rare mentions of "ETH2 Mainnet", which seem to be embedded in the Prysm client console logs.... but those logs also refer to lowercase "mainnet" elsewhere. 

Just throwing that out there... seems like "mainnet" is historically most inline with peoples usage of the term, but _if there is a formal movement to change that_ to more of an official name (ie. _the_ Mainnet, and _the_ Internet) then this would be the place to implement that change to help set the standard.

**Comment by ryancreatescopy** [comment]
I would advocate for mainnet. Even if we do want it to have the gravitas of Internet, common usage of that would more likely be internet.

**Comment by samajammin** [comment]
Solved in #1909
