### ISSUE TITLE
Sha256 checksum does not match for Eth1 image

### ISSUE THREAD

**Issue by zupino** [ethereum/ethereum-org-website#1901]
**Describe the bug**

The page [here](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/tutorials/run-node-raspberry-pi/index.md) shows 2 link to download a Raspberry image file, one configured for Eth1 and the other for Eth2. 

The Eth1 image's checksum does not match with the one showed below the link.

**To Reproduce**

1. Download the Eth1 image file as per link at this [page](https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/#image-download-and-installation)
2. Check the SHA256 checksum of the image (in my case on Mac I used `shasum -a 256 ./ubuntu-20...img.zip`
3. Compare the obtained value with the value indicated in the same download page

**Expected behavior**

SHA256 checksum should be matching the one published on the webpage

**Screenshots**

<img width="956" alt="Screen Shot 2020-11-20 at 5 29 43 PM" src="https://user-images.githubusercontent.com/4855290/99832451-d710f680-2b60-11eb-959d-5d987533afca.png">

**Desktop (please complete the following information):**

**Additional information**

The same checksum verification steps give a correct value for the Eth2 image file.

**Comment by wackerow** [comment]
![image](https://user-images.githubusercontent.com/54227730/99866919-20b20f00-2b6a-11eb-8448-6e8a92ac4016.png)
Also getting 7fa9370d13857dd6abcc8fde637c7a9a7e3a66b307d5c28b0c0d29a09c73c55c

@samajammin I can update this, but should we be concerned that this does not match?
