### ISSUE TITLE
studio.ethereum.org should stop using window.web3

### ISSUE THREAD

**Issue by rekmarks** [ethereum/ethereum-org-website#1904]
This is not a bug yet, but the MetaMask team has noticed that studio.ethereum.org makes use of our injected `window.web3` object. As described in https://github.com/MetaMask/metamask-extension/issues/8077, we are going to stop injecting this object in the immediate future. If the website relies on this object to function, it will break for MetaMask users unless it migrates per our [migration guide](https://docs.metamask.io/guide/provider-migration.html).

Specifically, we've detected usage of `web3.eth.accounts`. This could simply be replaced with `await ethereum.request({ method: 'eth_accounts' })`.

Of course, any script running on the website could be responsible for the accesses, but I recommend taking a look on your end.

**Comment by samajammin** [comment]
Thanks @rekmarks! I've opened an issue in the Ethereum Studio repo to track this - https://github.com/SuperblocksHQ/ethereum-studio/issues/275

Closing this out in favor of that new issue.
