### ISSUE TITLE
Social images

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1910]
**Is your feature request related to a problem? Please describe.**

When links to our site are shared on Twitter, images don't appear making links look less trustworthy or official. 

**Describe the solution you'd like**

Add social Twitter images to pages at an individual or section level.

![image](https://user-images.githubusercontent.com/40891631/99884532-d8a4f200-2c26-11eb-84b8-4710cce56da3.png)

**Comment by samajammin** [comment]
Hmmm good catch. This should help: https://cards-dev.twitter.com/validator

**Comment by samajammin** [comment]
Confirm it's now working cc @ryancreatescopy :
<img width="999" alt="Image 2020-12-03 at 1 00 39 PM" src="https://user-images.githubusercontent.com/8097623/101069137-7618f380-354e-11eb-949d-cfc910da0771.png">
