### ISSUE TITLE
Prevent glossary link wrapping

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1921]
**Describe the bug**

The new glossary link with icon shouldn't wrap onto two lines. The icon should be treated as part of the last word, so instead of only the icon wrapping onto a new line "network" should wrap too (or the entire link if easier).

![image](https://user-images.githubusercontent.com/40891631/99969678-b8924180-2d92-11eb-82d0-d8cd3280cd5b.png)

**Comment by samajammin** [comment]
I suspect this is the same issue as #980 - we solved by changing from `display: inline-block;` to `display: inline;` (see https://github.com/ethereum/ethereum-org-website/pull/1229/files) but unfortunately this may remove the hover effect 😕

**Comment by santdeleon** [comment]
I think i've got a fix for this. Should have a PR shortly 👍
