### ISSUE TITLE
Update eth2 copy that mentions dependency on reaching staking threshold

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1927]
**Is your feature request related to a problem? Please describe.**

Some copy in the Eth2 section explains that the beacon chain will launch if the deposit contract got enough deposits.

We reached the threshold so this is no longer an "if"!

**Describe the solution you'd like**

Update the copy based on the new status.

**Comment by samajammin** [comment]
Solved in #1931
