### ISSUE TITLE
Card misalignment mobile

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1928]
**Describe the bug**

Stacked cards on mobile have margin that should only be on desktop. This is causing some dodgy misalignment. 

This may be present elsewhere but I noticed it on the beacon chain page. 

**Expected behavior**

Cards should align and have the same margin on mobile. 

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/100063013-6996eb80-2e28-11eb-98e9-a6aaf2c2614c.png)

**Comment by samajammin** [comment]
Solved in #1931
