### ISSUE TITLE
Add information about where to "earn ETH" on "get-eth" page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1929]
**Is your feature request related to a problem? Please describe.**

A question in our Discord made me realise that there are ways to get ETH without fiat-onramps... earning it. We should link to eco-system projects that reward people in ETH or tokens for tasks/work, e.g. Gitcoin Bounties and Community.makerdao.com.

**Describe the solution you'd like**

Add a section to `/get-eth` that discusses the options for earning ETH. This might give us cause to separate the "Keeping your ETH safe" into its own page, which we link to from `/get-eth` and other relevant page.

**Describe alternatives you've considered**

A new page `/earn-eth`... however I think that's unnecessary and may cause a bad UX for users who want to explore all the options for getting eth in one place.

**Comment by samajammin** [comment]
Agreed! I've also received this question.

**Comment by wackerow** [comment]
Definitely agree... arguably the best way to obtain ETH is to earn it.. I try to make this my first recommendation when people ask where to "get it" because it shifts the normal to "it's currency... you don't have to buy USD do you? you just earn it"

**Comment by wackerow** [comment]
Still think this is worth developing

**Comment by samajammin** [comment]
@wackerow agreed, re-opening.

**Comment by darkwater4213** [comment]
Possibly add a mining program downloadable from the `\get-eth` page? (Or am I confusing this with Bitcoin? I'm still not sure how PoS works...) I'll start looking into finding some ways to earn ETH, though.

**Comment by wackerow** [comment]
@darkwater4213 Hey, thanks for chiming in! So mining _is_ a part of the eth1 mainnet which uses PoW for consensus, however, there is an active upgrade in progress to transition to PoS which does not involved any mining. This is live now on the beacon chain, and is ultimately the future of Ethereum consensus. Given the high cost of entry to "earn ETH" via mining, and its impending discontinuation, I think others here would agree mining probably wasn't what was in mind here. 

I was thinking more along the lines of highlighting projects like [Gitcoin.co](gitcoin.co), for example, that allow developers to be paid directly for their skills in ETH or ERC-20 tokens (and more). 

Perhaps if anyone knows of services that help payroll departments automatically convert portions of an employees pay into a chosen digital asset?

Or suggestions for retailers, entrepreneurs, or anyone who sells anything, to start accepting cryptocurrency. Benefits could be listed (including guaranteed irreversible payments like cash applied to e-commerce) and tips could be shared to get started and answer common questions about things like taxes or accounting.

**Comment by darkwater4213** [comment]
> @darkwater4213 Hey, thanks for chiming in! So mining _is_ a part of the eth1 mainnet which uses PoW for consensus, however, there is an active upgrade in progress to transition to PoS which does not involved any mining. This is live now on the beacon chain, and is ultimately the future of Ethereum consensus. Given the high cost of entry to "earn ETH" via mining, and its impending discontinuation, I think others here would agree mining probably wasn't what was in mind here.  
Okay, that makes more sense. But ETH _currently_ uses PoW right now, right? So I could mine ETH right now, even if it is discontinued later? Also, I'm still a bit confused as to how PoS works... Can I get some clarification, and can someone who is relatively broke viably earn ETH off of it?

**Comment by wackerow** [comment]
@darkwater4213 Correct. The "eth1" blockchain is currently still processing 100% of mainnet transactions and currently operates using PoW consensus (mining). We are working to consolidate more resources into the ethereum.org page to help with everyones understanding, but in the meantime I'd recommend checking out a couple of these resources:

- Beaconchain Knowledge Base: https://kb.beaconcha.in/
- Ethereum Study Master: https://ethereumstudymaster.com/
- ethos.dev: https://ethos.dev/beacon-chain/

Also you could check out the EthStaker [reddit](https://www.reddit.com/r/ethstaker/), or [discord](https://discord.gg/3vbwcCYu35)... super friendly and enthusiastic group who will gladly help you more with this stuff.

**Comment by minimalsm** [comment]
If anyone knows any good ways to **earn** ETH we'd like to hear them.

An obvious one is working for a crypto company that pays in ETH. You can find a list of job boards listing jobs in cryptocurrency here - https://ethereum.org/en/community/#ethereum-jobs

You can also earn crypto by completing GitCoin bounties: http://gitcoin.co/

Don't know if I'd consider mining or staking 'earning' ETH but those are options. RocketPool (decentralised staking pool platform) will be on Mainnet very soon.

https://www.rocketpool.net/

Also you could earn altcoins from something like Coinbase Learn and then swap tokens from ETH.

> Popular cryptocurrency exchange Coinbase offers incentives for using the platform’s Learn hub. In order to get the free change, you’ll need to watch Coinbase’s videos, take quizzes, and then Coinbase will deposit a small amount of crypto into your wallet. The content is typically focused on a specific altcoin (like GRT and BOND) and, as a result, these are the coins you’ll earn for going through the lessons.
>
> Because altcoins generally aren’t recommended for long-term investing, you can convert these lesser-known coins into Bitcoin or Ethereum once you earn them.

**Comment by corwintines** [comment]
Going to close and refresh this issue in https://github.com/ethereum/ethereum-org-website/issues/9274
