### ISSUE TITLE
Add trilemma to mobile

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1932]
**Is your feature request related to a problem? Please describe.**

On the Eth2 vision page we have an interactive trilemma, so folks can explore the challenges of decentralized scaling: https://ethereum.org/en/eth2/vision/

Currently this isn't styled for mobile, so doesn't show on phones. We'd like to create a mobile implementation of this trilemma.

**Describe the solution you'd like**

I think modals might be the best way to go as per this quick prototype: https://www.figma.com/proto/UP36ufDF6PaVPwi7Eqzzge/Mobile-trilemma?node-id=1%3A13&viewport=428%2C400%2C0.6768559217453003&scaling=min-zoom

On mobile having the information in a separate card above or below the SVG is a poor experience as the user must continuously scroll up and down to interact with the trilemma and read the info. It's also not clear that interactions do anything. Hence, wondering whether a modal would be a better bet. 

- Text should still be legible with a 16px minimum font size

**Screenshot**
Desktop implementation: 

![image](https://user-images.githubusercontent.com/40891631/100089918-57c64000-2e4a-11eb-98f8-7b325c891695.png)

**Comment by wackerow** [comment]
I'll take a look at this if you want to assign me
