### ISSUE TITLE
New wallet: Multis

### ISSUE THREAD

**Issue by gjeanmart** [ethereum/ethereum-org-website#1935]
# Wallet suggestion: [Multis](https://multis.co)

Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

Yes, there are no geographic limitations nor KYC requirements (except a few exceptions when using our fiat on-ramp integration).

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Our wallet is **non-custodial**, it is a multi-signature smart-contract. Each key to access the contract is owned and managed by the owners of the multisig (only) through browser wallets (Metamask, Portis)

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Our wallet is based on the battle-tested and thoroughly audited [Gnosis Multisig](https://github.com/gnosis/MultiSigWallet) holding funds since 2017. We have been audited for a few minor changes made in order to allow meta-transaction with [GSN](https://opengsn.org) (links to the [audit report](https://certificate.quantstamp.com/full/multis) | [GitHub](https://github.com/multis/MULTISig)).

**Does the wallet have fiat on-ramps?**

Yes, Multis integrates [MoonPay](https://www.moonpay.io) and [ramp.network](https://ramp.network) to allow users to purchase crypto using cards and fiat currencies.

We put subsidizing transaction fees on pause due to recent gas price volatility but our smart-contract is [GSN](https://opengsn.org) enabled meaning users can send transactions through meta-transaction.

**Does the wallet allow users to explore dapps?**

No

**Does the wallet have integrated defi/financial tools?**

Yes, Multis integrates the following DeFi protocols:

- [Kyber](https://kyber.network) for token swaps
- [Compound](https://compound.finance) for earning interests
- [TokenSet](https://www.tokensets.com) for investment strategy
- [RequestNetwork](http://request.network) to generate request for payment

**Can a user withdraw to their card?**

No

**Does the wallet offer limits protection?**

Yes the wallet offers two types of limits protection:

- daily limit for ETH
- ability to set team spending allowances on ERC20 tokens

**Does the wallet allow high-volume purchases?**

Yes but it will depend on the KYC review by our fiat on-ramp partners (MoonPay and ramp.network)

**Does the wallet have an integrated token swap?**

Yes, we have integrated [Kyber](https://kyber.network) for token swap.

**Is the wallet a multi-signature wallet?**

Yes, we are a multi-signature smart-contract wallet based on Gnosis Multisig.

**Wallet title**

[Multis](https://multis.co)

**Wallet description**

Multis is a cryptocurrency account designed for businesses. With Multis, companies can store with access controls, earn interest on their savings, and streamline payments and accounting.

**Wallet logo**

![](https://imgur.com/LGncJra.png)

**Brand color**

#166efc

---

Please check our website https://multis.co for more details and feel free to contact us (twitter: @gjeanmart | email: greg[at]multis.co)

**Comment by samajammin** [comment]
Thanks for the suggestion @gjeanmart - @GeorgeTrotter please review when able.

**Comment by samajammin** [comment]
Solved in #1956
