### ISSUE TITLE
Update deploy process

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#195]
- It's out of date: https://github.com/ethereum/ethereum-org-website#deployment
- Remove deploy.sh

**Comment by samajammin** [comment]
We're 2 weeks into the updated process. It feels improved but I think we could refine it further.

I propose we scrap the `dev` branch & set `master` as the "default branch", which would make it the default branch on which all PRs are created against. As a result, all PRs that are merged would be immediately deployed to the production site at ethereum.org via our Netlify integration.

Why? Our [current development lifecycle](https://github.com/ethereum/ethereum-org-website#deployment-lifecycle) has an extra step, which means more manual work to deploy changes & more noise in the form of additional PRs & merge commits between `dev` & `master`. Given that we create Netlify previews for all PRs, that should give us sufficient ability to QA changes. We also have the `staging` branch which auto-deploys to staging.ethereum.org if needed.

The default branch can be set here:
https://github.com/ethereum/ethereum-org-website/settings/branches

@jjmstark or others - any thoughts on this?

**Comment by wtf** [comment]
I kinda agree that the deployment process can be simplified. However, there are arguments against pulling PRs directly into `master`:

- There might be PRs which change the same file and thus conflict with each other. While deployment previews for each PR would work correctly, accepting both would break the site
-

**Comment by samajammin** [comment]
Thanks for the feedback! Good points regarding the preview deploys. I didn't realize they don't update when the base branch changes - they only change when the PR branch changes.

I'll plan to scrap `staging` & update Netlify to have staging.ethereum.org point to `dev`. Once that's complete I'll close this issue out.

**Comment by samajammin** [comment]
I've created an issue in the devops repo to update the DNS record for staging.ethereum.org to point to our `dev` branch deploy in Netlify: https://github.com/ethereum/devops/issues/363
