### ISSUE TITLE
Questions about a tutorial

### ISSUE THREAD

**Issue by mickaelandrieu** [ethereum/ethereum-org-website#1971]
Hi, I'm following this [tutorial](https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/)
and I have 2 questions to check if I'm doing good so far !

1 /  I have access to the logs but how I can ensure my port 13000 is opened, do we have some commands to type on linux to check everything is good ?

2 / I don't have access to grafana

I got my  raspberry pi 4 ip using "hostname -I" then on my laptop (which is using the same network) i took this IP in my browser followed by the port 3000.

I have the following error from my browser: 

> This is is unreachable 192.168.68.112 doesnt allow the connexion.

Do I need to wait that the eth blockchain is synced on my raspberry Pi 4 before get access to the monitoring tools ?

Thanks for your help (awesome tutorial :+1: )

**Comment by mickaelandrieu** [comment]
Hi there,

investing deeper today, looks like I don't have any grafana there 

```
sudo systemctl status grafana-server
Unit grafana-server.service could not be found.
```

I'm really sorry to ping you @wackerow, but do you have any idea why I don't have access to the monitoring tools ?

I'm also worried about the logs 

```
Nov 29 14:45:05 ethnode-2fc3a3766 geth[12464]: CRIT [11-29|14:45:05.282] Failed to write block data to ancient store err="the append operation is out-order"
Nov 29 14:45:05 ethnode-2fc3a3766 systemd[1]: geth.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 14:45:05 ethnode-2fc3a3766 systemd[1]: geth.service: Failed with result 'exit-code'.
Nov 29 14:45:06 ethnode-2fc3a3766 systemd[1]: geth.service: Scheduled restart job, restart counter is at 488.
Nov 29 14:45:06 ethnode-2fc3a3766 systemd[1]: Stopped Ethereum geth client daemon by The Ethereum Foundation.
Nov 29 14:45:06 ethnode-2fc3a3766 systemd[1]: Started Ethereum geth client daemon by The Ethereum Foundation.
Nov 29 14:45:06 ethnode-2fc3a3766 geth[12484]: INFO [11-29|14:45:06.104] Bumping default cache on mainnet         provided=1024 updated=4096
Nov 29 14:45:06 ethnode-2fc3a3766 geth[12484]: WARN [11-29|14:45:06.104] Sanitizing cache to Go's GC limits       provided=4096 updated=2603
Nov 29 14:45:06 ethnode-2fc3a3766 geth[12484]: INFO [11-29|14:45:06.110] Maximum peer count                       ETH=103 LES=25 total=128
Nov 29 14:45:06 ethnode-2fc3a3766 geth[12484]: INFO [11-29|14:45:06.110] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Nov 29 14:45:06 ethnode-2fc3a3766 geth[12484]: INFO [11-29|14:45:06.114] Starting peer-to-peer node               instance=Geth/v1.9.5-stable-a1c09b93/linux-arm64/go1.13
Nov 29 14:45:06 ethnode-2fc3a3766 geth[12484]: INFO [11-29|14:45:06.114] Allocated trie memory caches             clean=650.00MiB dirty=650.00MiB
Nov 29 14:45:06 ethnode-2fc3a3766 geth[12484]: INFO [11-29|14:45:06.115] Allocated cache and file handles         database=/home/ethereum/.ethereum/geth/chaindata cache=1.27GiB handles=262144
```

I can read "geth.service: Scheduled restart job, restart counter is at 488.", is it "normal" ?

**Comment by ryancreatescopy** [comment]
Hi @mickaelandrieu I recommend reaching out to the tutorial author: https://twitter.com/EthereumOnARM

We'd appreciate you letting us know anything that helps you debug so that we may improve the tutorial in the future.
