### ISSUE TITLE
Suggested Dapp: Async Art

### ISSUE THREAD

**Issue by conlan** [ethereum/ethereum-org-website#1974]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

**Is your dapp open source?**

Yes! Our contract is open source: https://github.com/asyncart/async-contracts.

**Can a user access the dapp without creating an account?**

Yup! Anyone can build on top of the smart contract at: https://etherscan.io/address/0xb6dae651468e9593e4581705a09c10a76ac1e0c8

**Are dapp funds non-custodial?**

Absolutely. See above.

**Do you offer community support?**

Yup! Come talk to us at: https://async.art/discord.

**Describe any geographical restrictions on usage of your dapp**

No restrictions.

**Dapp title**

Async Art

**Dapp description**

Create, collect, and trade #ProgrammableArt - digital paintings split into "Layers" which you can use to affect the overall image. Each Master and Layer is an ERC721 token.

**Dapp logo**

https://p124.p4.n0.cdn.getcloudapp.com/items/bLu0rnQy/Async_onBlack.png?v=8d42dce16ac63882735f471ed9044a11

**Brand color**

#000000

**Comment by conlan** [comment]
"Programmable Art Designed to Evolve on Ethereum? Meet the Async Art Project"
- https://blockonomi.com/programmable-art-async-art-project/

"Async Art – Paving the Way for Programmable, Dynamically Changing Art on the Blockchain."
- https://opensea.io/blog/digital-art/async-art-paving-the-way-for-programmable-dynamically-changing-art-on-the-blockchain/

"How MLB player-turned-artist Micah Johnson is celebrating Black boyhood"
- https://www.nbcnews.com/news/nbcblk/how-mlb-player-turned-artist-micah-johnson-celebrating-black-boyhood-n1248068

"NFT Painting of Buterin in Harlequin Garb Sets Record in Weekend Crypto Art Sale"
- https://www.coindesk.com/nft-painting-of-buterin-in-harlequin-garb-sets-record-in-weekend-crypto-art-sale

**Comment by wackerow** [comment]
@samajammin @ryancreatescopy someone else can approve, but I'll put this in a PR in the event it is.

**Comment by conlan** [comment]
Thanks @wackerow!
