### ISSUE TITLE
Propose the listing of Crypto.com on get ETH exchange list

### ISSUE THREAD

**Issue by jack-cryptocom** [ethereum/ethereum-org-website#1975]
Before suggesting an exchange, make sure you've read [our exchange listing policy](https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**

People's Republic of China

**Which currencies are accepted by this exchange?**

USD,GBP,EUR,SGD,CAD,AUD,NZD,HKD,TWD,NOK,SEK,DKK,CHF,PLN,ZAR,KES,RUB,BGN,RON,ILS,SAR,AED,HUF,CZK

**Do you have any proof that they're a legitimate company?**

Crypto.com receive in-principle approvals for a Financial Institution License and a Class 3 Virtual Financial Assets (VFA) License from the Malta Financial Services Authority : https://blog.crypto.com/crypto-com-receives-in-principle-approvals-for-a-financial-institution-license-and-a-class-3-vfa-license/

Crypto.com Joins the International Digital Asset Exchange Association : https://blog.crypto.com/crypto-com-joins-the-international-digital-asset-exchange-association/

**Do you have any extra information?**

Crypto.com was found in 2016 with 500+ staffs worldwide and 5M users on its platform. 
Crypto.com services are provided across both CeFi and Defi aspect via our Crypto.com App, Crypto.com Exchange, Crypto.com DeFi Wallet and Crypto.com DeFi Swap (Dexs)

**Comment by ryancreatescopy** [comment]
Thanks, we'll take a look at this and get back to you.

**Comment by GeorgeTrotter** [comment]
Hey @jack-cryptocom - just want to make sure, the exchange is accessible everywhere **but** PRC, or only in PRC?

**Comment by jack-cryptocom** [comment]
accessible everywhere but PRC, thanks

**Comment by jack-cryptocom** [comment]
@samajammin Hi Team thanks for listing Crypto.com on https://ethereum.org/en/get-eth/, could you help to change the current hyperlink from https://crypto.com/exchange/ to https://crypto.com/ which is our offical homepage and just like other brands over there, a million thanks ahead and apology if any inconvenience caused
