### ISSUE TITLE
Broken link on Staking Community Grants page

### ISSUE THREAD

**Issue by catsnackattack** [ethereum/ethereum-org-website#1996]
[Staking Community Grants](https://ethereum.org/en/eth2/get-involved/staking-community-grants/) -> FAQ -> How can I learn more about Eth2?

Link destination for Superphiz 'Intro to Eth2 & Staking for Beginners' is incorrect: https://ethereum.org/en/eth2/get-involved/staking-community-grants/%5Bhttps://www.youtube.com/watch?v=tpkpW031RCI%5D(https://www.youtube.com/watch?v=tpkpW031RCI)

AFAICT destination should be: https://www.youtube.com/watch?v=tpkpW031RCI

**Comment by wackerow** [comment]
@catsnackattack Thanks for spotting this! Will put up PR to fix in a moment.
