### ISSUE TITLE
"proof-of-stake" should be changed to "proof-of-work"

### ISSUE THREAD

**Issue by oscarguindzberg** [ethereum/ethereum-org-website#1999]
On https://ethereum.org/en/eth2/vision/

"This isn't possible in proof-of-stake , where the best a protocol..." 

Should be changed to "This isn't possible in proof-of-work , where the best a protocol..."

**Comment by wackerow** [comment]
@oscarguindzberg Good catch, will toss up a fix in a moment!

**Comment by oscarguindzberg** [comment]
This is the line with the bug https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/eth2/vision.js#L321

**Comment by wackerow** [comment]
Yeah, there was another place where this was being used as well.. the above PR should take care of it 👍
