### ISSUE TITLE
Inconsistency in point/USD prizes on eth2 bug bounty site

### ISSUE THREAD

**Issue by lsankar4033** [ethereum/ethereum-org-website#2005]
**Describe the bug**

Eth2 bug bounty site has inconsistency between point and dollar values.

**To Reproduce**

1. Go to 'https://ethereum.org/en/eth2/get-involved/bug-bounty/'
2. Scroll down to 'Submit a bug' section
3. See that 'high risk' category awards 'up to 10,000 points' and 'up to 25,000 DAI' (instead of 20,000)

**Expected behavior**

25,000 -> 20,000

**Screenshots**

![Screen Shot 2020-11-30 at 4 41 48 PM](https://user-images.githubusercontent.com/451947/100682462-f8c16900-332a-11eb-96ee-1a540cc9de14.png)

**Comment by wackerow** [comment]
@samajammin @ryancreatescopy do we know what the accurate breakdown is here?
On https://bounty.ethereum.org/ it states:
![image](https://user-images.githubusercontent.com/54227730/100685037-6328d800-3330-11eb-864c-a252d5840b5e.png)
Both `Medium` and `High` categories on our eth2 page currently do not match with this
![image](https://user-images.githubusercontent.com/54227730/100685154-b4d16280-3330-11eb-8478-06a8b46d62fa.png)
Happy to fix this if we can confirm what the most accurate information is.

**Comment by lsankar4033** [comment]
The intention with the initial version of the eth2 bounty site was 10k points on high (https://github.com/ethereum/eth2.0-bounty/blob/master/_includes/bounty-rules.markdown#rules--rewards), understanding that there's a slight divergence from the eth1 system b/c 'Note' and 'Low' are combined
