### ISSUE TITLE
Set up remaining components & pages for translations

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2006]
**Is your feature request related to a problem? Please describe.**

Catch-all issue to set up remaining components & pages for translations. Feel free to knock any/each component in individual PRs!

**Describe the solution you'd like**

Refactor components:
- [ ] AssetDownload
- [ ] BugBountyPoints
- [ ] CallToContribute
- [ ] Codeblock
- [ ] DocsNav
- [ ] EthExchanges
- [ ] FileContributors
- [ ] ProductList
- [ ] SectionNav
- [ ] TranslationsInProgress
- [ ] TutorialMetadata

Refactor page components:
- [ ] languages.js

Refactor template components:
- [ ] docs.js

For each component:
1.  Move the English copy into [/intl/en.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en.json)
2. Replace the English copy with our `<Translation/>` component and/or the `translateMessageId` function

**Describe alternatives you've considered**

**Additional context**

Similar work to #1937 & #1936 - see associated PRs for solution.

**Comment by samajammin** [comment]
@ryancreatescopy @wackerow @ph5500 could definitely use your help with these if you have any capacity over the next few days 😄 - we're trying to finish these & upload our new content files for translations by the end of this week 😅 

Feel free to ping me here / message me in Discord if you have any questions! Happy to hop on a call & walk through how to do this.

**Comment by wackerow** [comment]
I will start working on these from the bottom of the list upward

**Comment by samajammin** [comment]
@ryancreatescopy I'm curious to hear your thoughts re: the TableOfContent.js component & docs.js template.

Given the current translation process (English copy --> Crowdin translations --> Github files), we only show the "Edit this page" button link to Github for English pages. I suppose we should do the same for the "This page is incomplete" banner (i.e. hide it unless it's an English page)? Or should we reconsider this flow?

**Comment by ph5500** [comment]
I can start working from the top of the list down if that works.

**Comment by wackerow** [comment]
@ph5500 Not sure where you're at, if you're working on this now, but the bottom ones didn't take terribly long and I'm currently on `EthExchanges` which is slightly more involved, so I'll stop after this one.

**Comment by samajammin** [comment]
Amazing work @wackerow @ph5500 💪 - love the quick turnaround! Our global visitors will soon thank you 😄
