### ISSUE TITLE
Improve whitepaper images for dark mode

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2013]
**Is your feature request related to a problem? Please describe.**

At the moment, the images in the whitepaper have a white background. This isn't great for dark mode.

**Describe the solution you'd like**

Redesign the diagrams so that they can be placed on a transparent background and visible on dark mode and light mode.

This is an example of a diagram I redesigned for the accounts page (to work on dark mode and light mode)

![image](https://user-images.githubusercontent.com/40891631/100730527-142b8300-33c2-11eb-9d59-3d1252bdac4d.png)

All diagrams should have alt descriptions.

**Comment by wackerow** [comment]
I'll fire up windows paint haha.. go ahead and assign me, I would love to see this fixed

**Comment by ryancreatescopy** [comment]
> I'll fire up windows paint haha.. go ahead and assign me, I would love to see this fixed

I'd recommend Figma ;)
