### ISSUE TITLE
Tutorial tags shouldn't duplicate (even with different casing)

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2020]
**Is your feature request related to a problem? Please describe.**

If I add a tutorial and I tag it "JavaScript" it shouldn't generate a new tag alongside "javascript". Instead our logic should recognise that they are the same and group it under the one tag which displays on the frontend as `JAVASCRIPT` anyway.

**Additional context**

This is mainly for the tutorials in the developers section.

**Comment by ryancreatescopy** [comment]
cc @samajammin please add more technical detail if necessary

**Comment by samajammin** [comment]
Thanks for creating this!

**Comment by wackerow** [comment]
Happy to take a look at this 👍
