### ISSUE TITLE
Belgacoin.com

### ISSUE THREAD

**Issue by OliverPetrovic** [ethereum/ethereum-org-website#2026]
**What geographical restrictions apply to this exchange?**

It's an European exchange (european countries are accepted), they don't accept orders from the US (because of US laws and restrictions).

**Which currencies are accepted by this exchange?**

EUR

**Do you have any proof that they're a legitimate company?**

I've done multiple successful transactions, feel free to check their page for info about them:
https://www.belgacoin.com/

**Do you have any extra information?**

This exchange is a bit special, it doesn't require KYC (So if you aren't old enough for KYC you can still place an order).
You can buy / sell / convert crypto and you have to provide only email.
The transactions aren't instant because they are processed manually.

**Comment by GeorgeTrotter** [comment]
Hey @OliverPetrovic, can you be more specific about the geographical restrictions? When you say European countries, is that every EU country? Are there other European countries that receive service?

**Comment by OliverPetrovic** [comment]
I mean every EU country.
According to their website.

Thanks :)

**Comment by GeorgeTrotter** [comment]
Hey @OliverPetrovic - we are going to close this issue without adding Belgacoin to the website. We made this decision in view of ethereum.org's design principles:

Inspirational: anything on ethereum.org should offer something new to users
A good story: what's listed should provide an "aha" moment
Credible: everything should be legitimate businesses/projects to minimise risk to users

In the world where space on the site is limited and not every exchange can be listed, we felt Belgacoin didn't give the kind of inspirational moment we want our users to have, relative to the other exchanges we could be listing.

Please don't hesitate to open issues around Belgacoin in the future as the exchange evolves! We're always happy to look at it again, given time.
