### ISSUE TITLE
Refactor codebase to use `translateMessageId`

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2029]
**Is your feature request related to a problem? Please describe.**

Related to #2006, as we set up the codebase for further translations let's clean up the code to use our new translation function (`translateMessageId`):
https://github.com/ethereum/ethereum-org-website/blob/dev/src/utils/translations.js#L56
This function simplifies our logic by removing the need for a `defaultMessage` - it always falls back to the English translation.

**Describe the solution you'd like**
Search through the codebase & replace all uses of `intl.formatMessage` with `translateMessageId`.

**Additional context**
See this commit as an example of a page refactor:
https://github.com/ethereum/ethereum-org-website/pull/2028/commits/c9548102d20a0e5dca6d00a582dceef0aa628487

**Comment by wackerow** [comment]
Happy to work on this if you want to assign
