### ISSUE TITLE
Establish consistent font hierarchy

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#203]
- Homepage section titles should be headers (`<h2>`?), not `<li>`
- Every page should have an `<h1>` - all header titles should be `<h1>` not `<h2>`
- Headers & HTML elements should have consistent size
    - e.g. `<h1>` on /developers has custom styling to display like an `<h2>`!?

**Comment by samajammin** [comment]
Adhering to the point of "Every page should have an `<h1>`", which is generally beneficial for SEO, a suggestion in https://github.com/ethereum/ethereum-org-website/issues/76 was to break up the headline text into a title & a subtitle (thanks @rossbulat):
- Current
  - Headline: "Ethereum is a global, open-source platform for decentralized applications. On Ethereum, you can write code that controls digital value, runs exactly as programmed, and is accessible anywhere in the world"
- Proposed
  - Title (h1): "Ethereum is a global, open-source platform for decentralized applications."
  - Subtitle (h2?): "On Ethereum, you can write code that controls digital value, runs exactly as programmed, and is accessible anywhere in the world."

No copy changes, just formatting with HTML elements. Thoughts? @jjmstark?

**Comment by jjmstark** [comment]
No opposition from me, unless doing so is going to radically change the way it looks currently.

**Comment by texture** [comment]
Hey Sam. Do you have a design background or are you purely technical?

**Comment by samajammin** [comment]
@jjmstark here's what that proposed breakout of the headline could look like. LMK if anyone has thoughts.

### Current
<img width="1045" alt="Image 2019-09-18 at 5 08 01 PM" src="https://user-images.githubusercontent.com/8097623/65197936-48be5380-da37-11e9-85f9-4dd8c39d6702.png">

### Updated
<img width="918" alt="Image 2019-09-18 at 5 07 47 PM" src="https://user-images.githubusercontent.com/8097623/65197890-42c87280-da37-11e9-805f-330e7bd79055.png">

Again, this issue is primarily focused on the HTML element hierarchy vs the design.

**Comment by samajammin** [comment]
Hey @texture - I primarily identify as an (opinionated) frontend developer vs. a designer but I've been lucky enough to work alongside web designers for most of my career who were generous with their time 😄.

**Comment by jjmstark** [comment]
@samajammin preference if possible to keep that paragraph a consistent style for both sentences. Thought son making them both  `<h1>`?

**Comment by samajammin** [comment]
Hmm, not strongly opposed but in my view a core purpose of breaking out the headline into a title & subtitle is to have different UI presentation for each. We could make that entire headline an `<h1>`, although that would be quite lengthy (204 chars vs. a typically recommended 20-70 chars).

**Comment by jjmstark** [comment]
kk - then I defer to the conventional wisdom here, let's break them out as you suggest above.

Post user-persona restructuring, we can work to improve the way these two sentences are displayed.
