### ISSUE TITLE
Predict user's country on Get ETH page to provide default results

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2033]
**Is your feature request related to a problem? Please describe.**

One of the most common flow for visitors to the Get ETH page is to select their country. If they don't select any country, we don't provide any results. I think it'd be a nice feature to provide a default result using their geolocation.

**Describe the solution you'd like**

We could use the Geolocation API:
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

This would prompt a user for their location when they land on the page:
<img width="337" alt="Image 2020-12-02 at 5 26 25 PM" src="https://user-images.githubusercontent.com/8097623/100938995-6fd13b80-34aa-11eb-9456-dd6857bf93be.png">

If the user accepts, we could use that result to predict their country & match it with one of our input options.

**Describe alternatives you've considered**
- We could could guess based on the user's IP address
- We could use some API service to predict the user's location

**Comment by samajammin** [comment]
Curious to hear your thoughts on this @ryancreatescopy. There's certainly potential downside, e.g. if visitors find the request annoying or intrusive.

**Comment by ryancreatescopy** [comment]
Personally, I'm always wary when a website asks me for this and invariably say no... of course that's just me. We should chat about ways we might validate that this is a useful feature for our users.

**Comment by samajammin** [comment]
I'm going to close this out for now as it's not a priority.
