### ISSUE TITLE
HyperWallet 

### ISSUE THREAD

**Issue by MacOMNI** [ethereum/ethereum-org-website#2035]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

Yes, there are no geographic limitations nor KYC requirements
**Is your wallet custodial, non-custodial, or a hardware wallet?**

 HyperPay is non-custodial and support hardware wallet

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

HyperPay app is auditted by [hyperpay](https://hyperpay.me/?lang=zh-cn).
As a non-custodial wallet, HyperPay has launched more than 3 years and been used by more than 1 million users worldwide without security incidents 

**Does the wallet have fiat on-ramps?**

Yes, HyperPay does not provide subsidise transaction fees function, but it allows user to adjust gas price and recommends the best gas price for smooth transaction.

**Does the wallet allow users to explore dapps?**
 Yes, HyperPay integrated with WalletConnect.
Yes, HyperPay developed an dapp browser to allow users to directly use the wallet to experience the dapp on ETH.

**Does the wallet have integrated defi/financial tools?**

Yes, HyerPay integrated Aave/MakerDAO/Compound/dYdX and other defi tools in the Assets - Financial tab. User can view/borrow/lend their assets all in one place.
**Can a user withdraw to their card?**
 No. Currently, the wallet does not provide this service, users can use the third-party application on the wallet platform to achieve this purpose.

**Does the wallet offer limits protection?**

 NO 

**Does the wallet allow high-volume purchases?**

 NO 

**Does the wallet have an integrated token swap?**

YES

**Is the wallet a multi-signature wallet?**

YES 

**Wallet title**

HyperPay 

**Wallet description**

HyperPay is a multi-platform  universal crypto wallet that supports 50+ blockchains and 2000+ dApps.

**Wallet logo**

![HyperPay](https://user-images.githubusercontent.com/6373598/100970843-b6896900-3570-11eb-9eed-b465121bf4fe.png)

**Brand color**

#161823

Please check our website [https://hyperpay.tech](https://hyperpay.tech) for more details and feel free to contact us (email: mackunmt@gmail.com)

**Comment by samajammin** [comment]
Solved in #2171
