### ISSUE TITLE
Ethereum launchpad deposit upload doesn't work on windows

### ISSUE THREAD

**Issue by mocolicious** [ethereum/ethereum-org-website#2060]
**Describe the bug**

If you're using Windows it the "Upload deposit file" validation always says "That is not a valid deposit_data json file".  This was tried on 2 different Windows computers in Brave, Chrome and Edge.  Then on Linux and it worked fine in chrome.

**To Reproduce**

1. Run the Deposit CLI or take any already generated file. 
2. Click through the wizard on ETH launchpad
3. Upload deposit file on screen

**Screenshots**

![image](https://user-images.githubusercontent.com/6373607/101206247-7ee3f500-3634-11eb-82d2-debee8e40cdf.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome, Edge, Brave
- Version: latest

**Comment by wackerow** [comment]
@mocolicious Hey! Thanks for bringing this up! Wanted to let you know that the Launchpad is actually managed separately from the main ethereum.org page over at [ethereum/eth2.0-deposit](https://github.com/ethereum/eth2.0-deposit). I'm sure they would welcome this issue over there and could help ya out 👍

**Comment by samajammin** [comment]
@mocolicious I've created your issue over at the Launchpad repo: https://github.com/ethereum/eth2.0-deposit/issues/286

Closing this out in favor of that issue. Let us know if you have any questions.

**Comment by mocolicious** [comment]
> @mocolicious I've created your issue over at the Launchpad repo: [ethereum/eth2.0-deposit#286](https://github.com/ethereum/eth2.0-deposit/issues/286)
> 
> Closing this out in favor of that issue. Let us know if you have any questions.

Thanks for the help @samajammin!
