### ISSUE TITLE
Unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by Kristiyan96** [ethereum/ethereum-org-website#2065]
**Describe the bug**

An unnecessary horizontal scrollbar showing up on all major browsers (Safari/Chrome/Firefox). 

**To Reproduce**

1. Go to www.ethereum.org
2. Check if you can scroll horizontally

**Expected behavior**

The page should not scroll horizontally. The max-width should be the width of the screen.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: **Mac**
- OS: **Catalina**
- Browser **Safari/Chrome/Firefox**

Tested on Mac Catalina, the specified browsers, and emulated a phone screen using Chrome Emulator. 

[EDIT]
Screenshot on Chrome: _(Can't be a plugin as I have none installed on Firefox and Safari.)_
<img width="1440" alt="Screenshot 2020-12-07 at 15 21 58" src="https://user-images.githubusercontent.com/15987117/101356078-392b6480-38a0-11eb-8dcf-0314aaa9909d.png">

**Comment by ryancreatescopy** [comment]
Hmmm I can't seem to replicate. @samajammin what about you?

**Comment by Kristiyan96** [comment]
Yeah, just checked. The navbar's width is set to 100vh which also includes the vertical scrollbar.
 
.Nav__NavContainer
  ~~width: 100vw~~
  top: -1px

You don't need the width property because the parent container is `display: flex; flex-flow: column` which by default gives all children `align-self: auto;` and makes them stretch the whole width.

The navbar also needs to be pushed up so that you can't see in between it and the top of the screen like here:
<img width="1440" alt="Screenshot 2020-12-07 at 15 46 01" src="https://user-images.githubusercontent.com/15987117/101358288-51e94980-38a3-11eb-8062-5382f09aee79.png">
, but that's probably for a separate issue

**Comment by samajammin** [comment]
Thanks for reporting this @Kristiyan96, thought I'm also unable to replicate this issue 🤔

**Comment by wackerow** [comment]
Hm... I am also unable to replicate the scrollbar or the topnav not aligning. This reminds me of the cache related issues we've been having though... layout related, difficult to replicate. @Kristiyan96 Out of curiosity, if you clear the website cache does it still produce this?

**Comment by Kristiyan96** [comment]
@wackerow Yeah, disabling cache from dev tools fixed it...
