### ISSUE TITLE
Update Languages page to use current style guide components

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2076]
**Is your feature request related to a problem? Please describe.**

https://ethereum.org/en/languages/

Current page displays outdated card styles:
<img width="1126" alt="Image 2020-12-07 at 8 13 44 PM" src="https://user-images.githubusercontent.com/8097623/101424244-95e24b80-38af-11eb-8cdb-1c9dc240fe87.png">

**Describe the solution you'd like**

Something using our current card components, perhaps GhostCard?

**Describe alternatives you've considered**

**Additional context**

**Comment by samajammin** [comment]
@ph5500 this might be one you'd interested in.

**Comment by ryancreatescopy** [comment]
```
const LangItem = styled(GatsbyLink)`
  text-decoration: none;
  margin: 1rem 1rem 1rem 0;
  padding: 1rem;
  flex: 0 1 260px;
  list-style: none;
  border-radius: 2px;
  width: 100%;
  border: 1px solid ${(props) => props.theme.colors.lightBorder};
  box-shadow: ${(props) => props.theme.colors.tableBoxShadow};
  transition: all 0.5s cubic-bezier(0.25, 0.8, 0.25, 1);
  color: ${(props) => props.theme.colors.text};

  &:hover {
    box-shadow: ${(props) => props.theme.colors.cardBoxShadow};
    border: 1px solid ${(props) => props.theme.colors.black300};
  }
`
```

This creates quite an interesting style

**Comment by samajammin** [comment]
@ryancreatescopy I dig that! I wonder, should we roll that out across some of our card components?
