### ISSUE TITLE
Changing the Finnish language name in the Language Support page

### ISSUE THREAD

**Issue by sorumfactory** [ethereum/ethereum-org-website#2079]
**Describe the bug**

Changing the Finnish language name from "Suomalainen" to "suomi" in the Language Support page: https://ethereum.org/en/languages/.

Reason for change: "Suomalainen" means "Finnish" as in Finnish national, Finnish delicacy. "Suomi" means the language Finnish.

In English, both are "Finnish" but in Finnish this is context dependent. So here, when referring to languages, it should be "Finnish" = "Suomi"

**Comment by samajammin** [comment]
Thanks for reporting @sorumfactory!

**Comment by samajammin** [comment]
Solved in #2080
