### ISSUE TITLE
Add filters to URL params

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2087]
**Is your feature request related to a problem? Please describe.**

Situations like this it'd be nice to be able to link directly to the wallets that have the given feature:

![image](https://user-images.githubusercontent.com/8097623/101557247-757ac580-3971-11eb-9d06-74c23c19bbf4.png)

**Describe the solution you'd like**

Investigate solutions to support URL, e.g. React router's useParam hook.

**Describe alternatives you've considered**

**Additional context**

Hat tip to @ph5500 for the suggestion.

**Comment by ryancreatescopy** [comment]
Yes, absolutely. I designed this content with that in mind and then realised later on it wouldn't be possible. Would love to have this worked on. @wackerow if you're looking for next issues ;)

**Comment by wackerow** [comment]
Can definitely take a look at this!
