### ISSUE TITLE
Prettier pre-commit hook adds backslash before dollar signs in markdown files

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2090]
**Describe the bug**

Essentially this: https://github.com/mdx-js/mdx/issues/606

It appears our Prettier pre-commit hook is attempting to escape `$` characters, changing them to `\$`, which leads to the slashes actually rendering in the HTML, e.g.

<img width="263" alt="Image 2020-12-09 at 8 31 20 AM" src="https://user-images.githubusercontent.com/8097623/101636179-c923f800-39df-11eb-9642-51db3860c172.png">

**To Reproduce**

1. Go to https://ethereum.org/en/community/
2. See error:

<img width="713" alt="Image 2020-12-09 at 8 32 21 AM" src="https://user-images.githubusercontent.com/8097623/101636274-f07ac500-39df-11eb-8fc3-867b919ecea7.png">

**Expected behavior**

I believe we should prevent Prettier from attempting to escape the dollar sign (`$`) character.

**Comment by samajammin** [comment]
Looks like this was fixed in Prettier: https://github.com/prettier/prettier/issues/6213

**Comment by sebastienbarre** [comment]
Is there any plan on fixing this for `*` as well?

For example, in a MDX file:
```
MDX also supports JavaScript expressions inside curly braces, i.e.: {Math.PI * 2}
```
Prettier automatically changes it to:
```
MDX also supports JavaScript expressions inside curly braces, i.e.: {Math.PI \* 2}
```
Which breaks MDX parsers -- this is no longer a valid Javascript/JSX expression.

Thanks
