### ISSUE TITLE
Add D'CENT wallet

### ISSUE THREAD

**Issue by paromix** [ethereum/ethereum-org-website#2091]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

YES

**Is your wallet custodial, non-custodial, or a hardware wallet?**

non-custodial
D'CENT wallet supports 2 types of  hardware wallet: D'CENT biometric wallet, D'CENT card type wallet
and also supports software wallet for users to use wallet without hardware wallet

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

D'CENT biometric wallet is audited by [Coinspect](https://coinspect.com/).
Announcement about the audit is below.
https://medium.com/dcentwallet/coinspect-audit-of-the-dcent-wallet-b8a6cf50cfa4

D'CENT hardware wallet (both of biometric wallet and card type wallet) uses Secure Element to protect sensitive information like private key.
For more information: https://medium.com/dcentwallet/secure-element-technology-65c8ce896981

**Does the wallet have fiat on-ramps?**

YES. D'CENT wallet integrates [MoonPay](https://www.moonpay.com/) to allow users to purchase cryptocurrency with fiat currency.
D'CENT wallet does not provide subsidise transaction fees function, but it allows user to adjust gas price and recommends the best gas price for smooth transaction.

**Does the wallet allow users to explore dapps?**

YES. D'CENT wallet has a dapp browser. WalletConnect integrated version will be released soon.

**Does the wallet have integrated defi/financial tools?**

Not directly integrated. But users can use DeFi tools like UniSwap, Compound etc. via dapp browser.

**Can a user withdraw to their card?**

NO.

**Does the wallet offer limits protection?**

NO.

**Does the wallet allow high-volume purchases?**

YES. Users can buy more than $2000 worth of crypto via MoonPay service.

**Does the wallet have an integrated token swap?**

Not directly integrated. But users can swap the tokens by using swap tools like UniSwap, 1inch etc. via dapp browser.

**Is the wallet a multi-signature wallet?**

NO.

**Wallet title**

D'CENT Wallet

**Wallet description**

D'CENT Wallet is the über convenient multi-cryptocurrency wallet with built-in DApp browser for easy access to DeFi, NFT, and variety of services.

**Wallet logo**

![dcent icon](https://user-images.githubusercontent.com/20573044/101635671-a17b7100-3a6d-11eb-95a4-c0fa209c172e.png)

**Brand color**

ffffff

**Comment by samajammin** [comment]
Solved in #2171
