### ISSUE TITLE
Listing Bitpie wallet

### ISSUE THREAD

**Issue by kelvinbitpie** [ethereum/ethereum-org-website#2095]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**
Yes. Available on APP store and Play store

KYC: ID card
Geographic limitation: high risk or crypto limitation country

**Is your wallet custodial, non-custodial, or a hardware wallet?**
Non-custodial 

Yes, they can access their public and private key
**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
We will update our APP once a week and we have a team to do QA

**Does the wallet have fiat on-ramps?**
Yes

Yes

**Does the wallet have integrated defi/financial tools?**
Yes

Yes

**Can a user withdraw to their card?**
Yes

Yes

**Does the wallet offer limits protection?**
No

They can free to transfer

**Does the wallet allow high-volume purchases?**
Yes

Yes

**Does the wallet have an integrated token swap?**
Yes

Yes
**Is the wallet a multi-signature wallet?**
Yes

Yes
**Wallet title**
Bitpie

Bitpie
**Wallet description**

A multichain wallet which can support multi-signature, DApp, Earn, ETH2.0, Exchange and Lending etc
**Wallet logo**

![47C8FF44-C64C-4322-ABFE-E45EB66ADDBF](https://user-images.githubusercontent.com/75765731/101712860-6d399c00-3ad1-11eb-8e51-97c3cee15546.png)

**Brand color**

 #3750DE   To #1E3DA0

**Comment by GeorgeTrotter** [comment]
Hey @kelvinbitpie, we're closing this issue without adding Bitpie to the website. Ethereum.org is focused on listing wallets without geographical restrictions or KYC requirements, as described in our [listing policy](https://ethereum.org/en/contributing/adding-products/). As Bitpie evolves, please don't hesitate to open issues here around it down the road, if it matches our policy more closely!

**Comment by kelvinbitpie** [comment]
Sorry, I'm new to the team, and I haven't got a lot of things figured out. I will close my issues and let my colleague open another detailed one. [Here is the new one.](https://github.com/ethereum/ethereum-org-website/issues/2338)
