### ISSUE TITLE
Code snippets not light/dark mode responsive

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#2096]
**Describe the bug**
Recent change 087df98f4513de38bba3350dc3149397f226de44 adjusted styling for `tt` which also had a `code` css selector attached to it causing all inline code snippets to render with deep purple theme even on light mode.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/
2. Go to light mode
3. Scroll down through code snippets noticing how they are now themed.

**Expected behavior**
- [x] Inline code snippets to render as they were previously with dark/light mode responsive coloring
- [x] Would also expect larger code blocks to render using a light mode theme

**Screenshots**
Previously:
![image](https://user-images.githubusercontent.com/54227730/101724983-98d26d00-3a64-11eb-9f98-a54f7dfaa6b6.png)
Currently:
![image](https://user-images.githubusercontent.com/54227730/101725011-a5ef5c00-3a64-11eb-9b94-816f545a9942.png)

## Additional context
The PR I have addressing this (still working out a few bugs, but will post it shortly):
![image](https://user-images.githubusercontent.com/54227730/101728141-b0145900-3a6a-11eb-830c-e371bac7cad6.png)

**Comment by samajammin** [comment]
Solved in #2098

**Comment by samajammin** [comment]
FYI @wackerow - a good habit to get into is mentioning issues in your commit message in order to automatically close issues. More info here:
https://github.com/ethereum/ethereum-org-website#submit-your-pr
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by wackerow** [comment]
@samajammin  Oh definitely, I try to do this every time, looks like I accidentally put the PR number in instead of the issue number, my bad
