### ISSUE TITLE
Ethereum casino

### ISSUE THREAD

**Issue by starr80** [ethereum/ethereum-org-website#2097]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

**Is your dapp open source?**

**Can a user access the dapp without creating an account?**

**Are dapp funds non-custodial?**

**Do you offer community support?**

**Describe any geographical restrictions on usage of your dapp**

**Dapp title**

**Dapp description**

**Dapp logo**

**Brand color**

**Comment by ryancreatescopy** [comment]
If you'd like this product listed please fill in the requested info. Thanks!

**Comment by mozeart** [comment]
wow...wouldn't allowing something like this make eth vulnerable to jurisdiction?

**Comment by ryancreatescopy** [comment]
Closing out. Feel free to reopen with more information.
