### ISSUE TITLE
Local builds not merging translations automatically

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#2120]
**Describe the bug**
- With recent translation efforts the new `merge-translations.js` script pulls sub-divided translation jsons into one usable language json, but this is not being run automatically on local builds. 
- Without running `yarn merge-translations` (which is included in `yarn build`) changed translation id's were not not being shown in `en.json` and causing local runtime problems (see screenshot below)
- In my case, running this locally on my `dev` branch leaves me with uncommitted changes that are not already committed here

**To Reproduce**
Not sure for everyone, but for me
1. `yarn start` or `yarn start:static`
2. See build console errors
3. Go to `localhost:8000/en/eth2` or `localhost:9000/en/eth2`
4. Scroll down to region in screenshot below
5. See browser console errors

**Expected behavior**
Merged updates to language text should automatically update and work appropriately without having to run separate build commands.

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/102162933-fa1c8680-3e3e-11eb-887a-e9b215ba46c0.png)

**Desktop (please complete the following information):**
- OS: macOS BigSur / Brave

**Additional context**
Perhaps this should just be added to the `start` scripts?... ie: `"start": "yarn merge-translations && gatsby develop"` since it's extremely fast and should help keep everyone in sync when running `yarn start` or `yarn start:static`
Also, eventually if everything if pulled out and broken into sub-divisions for each language, perhaps the language files (ie: `en.json`) should be in the `.gitignore` so only the others are edited, and the compiled version is created on starting the local build.

**Comment by samajammin** [comment]
Thanks for catching this @wackerow.

I'm thinking the same solution here - for now I'll just keep it simple & add it to the `start` script. I'm open to ideas on how to improve this though.

As for the `en.json` file, I've added it to `.gitignore`:
https://github.com/ethereum/ethereum-org-website/blob/dev/.gitignore#L78
