### ISSUE TITLE
Sort out how to manage CODEOWNERS across branches

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2123]
**Is your feature request related to a problem? Please describe.**

We've started using a [CODEOWNERS file](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) to help manage our review & deploy process.

Currently the file is the same for `dev` & `master` but ideally they should be different.

**Describe the solution you'd like**

Figure out how to have different CODEOWNERS files for `dev` & `master`

`dev`:
```
# This file defines the code owners of the repository
# Code owners are automatically requested for review when someone opens a PR that modifies code that they own
# Each line is a file pattern followed by one or more owners. Learn more here:
# https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
*       @samajammin @ryancreatescopy

# Owners of specific files
/src/data/eth2-bounty-hunters.csv @lsankar4033 @djrtwo

```

`master`:
```
# This file defines the code owners of the repository
# Code owners are automatically requested for review when someone opens a PR that modifies code that they own
# Each line is a file pattern followed by one or more owners. Learn more here:
# https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
*       @samajammin @ryancreatescopy @jjmstark @GeorgeTrotter

# Owners of specific files
/src/data/eth2-bounty-hunters.csv @lsankar4033 @djrtwo
```

**Describe alternatives you've considered**
- Add CODEOWNERS to `.gitignore` (but this isn't ideal, we want this file in version control)
- Keep as is (but any updates to `dev` CODEOWNERS are merged into `master` when we deploy)

**Additional context**

This thread may help provide context/solutions:
https://github.community/t/codeowners-per-branch/406/22

**Comment by pettinarip** [comment]
I couldn't find a proper solution for this. It seems that there is no elegant and easy solution for this right now in GH.

I would lean towards closing this until we hear something new from the GH team in the thread you shared.

**Comment by corwintines** [comment]
Based on @pettinarip comment going to abandon / close out.
