### ISSUE TITLE
TouchSwap

### ISSUE THREAD

**Issue by steniwp** [ethereum/ethereum-org-website#2138]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

**Is your dapp open source?**

**Can a user access the dapp without creating an account?**

**Are dapp funds non-custodial?**

**Do you offer community support?**

**Describe any geographical restrictions on usage of your dapp**

**Dapp title**TouchSwap

touch
![Screenshot_20201215-121430_BRImo](https://user-images.githubusercontent.com/35838192/102610291-497cf280-4170-11eb-8734-6e4f24d573fe.png)

**Dapp description**

**Dapp logo**

**Brand color**

#112

**Comment by samajammin** [comment]
Hey @steniwp - if you'd like to suggest a dapp, please fill out the question prompts in the issue description.
