### ISSUE TITLE
> 0x487623715a2E2A48306EE4a34b08302Ea2E36c07

### ISSUE THREAD

**Issue by 0848551558** [ethereum/ethereum-org-website#2140]
> 0x487623715a2E2A48306EE4a34b08302Ea2E36c07

_Originally posted by @0848551558 in https://github.com/ethereum/ethereum-org-website/issues/2128#issuecomment-745475430_

**Comment by samajammin** [comment]
Hey @0848551558 - what's this about? I'm closing this issue out. Please provide more context, otherwise I'll block you if you keep creating incoherent issues on this repo. Thanks in advance 😄

**Comment by 0848551558** [comment]
Sorry bro
