### ISSUE TITLE
Site Translation: Dutch

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#217]
Volunteers needed to complete this translation!
https://crowdin.com/project/ethereumfoundation/nl#

We've been managing our efforts throught CrowdIn. Here's an invite to get started:
https://crowdin.com/project/ethereumfoundation/invite

Soon we'll have a public guide directly on the website (https://github.com/ethereum/ethereum-org-website/issues/318) but in the meantime, please leave a comment if you begin translating & we'll connect you with our Translation Program team lead to answer any questions you have about the process.

**Comment by pjgeutjens** [comment]
I just did some work on this on crowdin. Will try to do some more in the coming days. I did make the assumption you do not want to translate titles of hyperlinks referencing external content, articles that are in English?

**Comment by samajammin** [comment]
Awesome - thanks @pjgeutjens! That is correct. Please submit this form & our translations team can help walk you through any other questions that come up: https://docs.google.com/forms/d/e/1FAIpQLSfsV1sG7OEPRzO6zDdj0BsYo9DR1L3nSSmCvYktftLjhQ4CoA/viewform

**Comment by samajammin** [comment]
Translations have been completed, reviewed & are ready to add to the site! Closing this in favor of https://github.com/ethereum/ethereum-org-website/issues/358

Thanks again for your work @pjgeutjens!
