### ISSUE TITLE
Can not find the three Accounts?

### ISSUE THREAD

**Issue by jley81** [ethereum/ethereum-org-website#2170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samajammin** [comment]
Hey @jley81! Please provide more information. What do you mean "the three Accounts"?

**Comment by jley81** [comment]
I had built a master file that could be the all 3  for eth.  Now i can to find it ianywhere

**Comment by ryancreatescopy** [comment]
@jley81 I'm not sure I'm following. Please fill out the bug report template.
