### ISSUE TITLE
PageHero cuts off hero image

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2184]
**Describe the bug**

Recent refactor to use a `PageHero` component across pages created a bug. See screenshots.

**Expected behavior**

Images should resize based on screen size. They should never be cropped off.

**Screenshots**

<img width="1042" alt="Image 2020-12-25 at 11 31 57 AM" src="https://user-images.githubusercontent.com/8097623/103138901-c554ce80-468b-11eb-96e8-6914cfaa18ea.png">

<img width="1035" alt="Image 2020-12-25 at 11 31 43 AM" src="https://user-images.githubusercontent.com/8097623/103138903-c8e85580-468b-11eb-991a-0436e05bf42b.png">

**Comment by jadijadi** [comment]
For me both works fine.
Chrome 87 / Mac book BigSur

**Comment by ryancreatescopy** [comment]
I also can't reproduce.

**Comment by wackerow** [comment]
Same, can't reproduce... you still getting this @samajammin? Looks like possibly another cache related issue.

**Comment by wackerow** [comment]
Closing for now, can reopen if needed
