### ISSUE TITLE
Site Translation: Indonesian

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#219]
Volunteers needed to complete this translation!
https://crowdin.com/project/ethereumfoundation/id#

We've been managing our efforts throught CrowdIn. Here's an invite to get started:
https://crowdin.com/project/ethereumfoundation/invite

Soon we'll have a public guide directly on the website (https://github.com/ethereum/ethereum-org-website/issues/318) but in the meantime, please leave a comment if you begin translating & we'll connect you with our Translation Program team lead to answer any questions you have about the process.

**Comment by Izzur** [comment]
I'm interested to help with this translation

**Comment by amusfq** [comment]
Can i accept this translation request?

**Comment by samajammin** [comment]
Thanks @amusfq! Please submit this form to get started: https://docs.google.com/forms/d/e/1FAIpQLSfsV1sG7OEPRzO6zDdj0BsYo9DR1L3nSSmCvYktftLjhQ4CoA/viewform

**Comment by samajammin** [comment]
This is complete! Thank you everyone who contribute! Closing this out in favor of #652

**Comment by samajammin** [comment]
For anyone who did contribute & would like recognition, please post a comment in #407
