### ISSUE TITLE
Site Translation: Persian

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#220]
Volunteers needed to complete this translation!
https://crowdin.com/project/ethereumfoundation/fa#

**Comment by shayanb** [comment]
I'm working on the full translation on a [fork](https://github.com/shiryakhat/ethereum-org-website), it should be done by the end of the week or so. 
The team at [Coiniran](http://coiniran.com) and [Shir Ya Khat](https://shiryakhat.net/) is working on the professional translation.

**Comment by samajammin** [comment]
Amazing! Thank you @shayanb! Would be great to deploy this before Devcon next week :)

**Comment by shayanb** [comment]
Yes, that'd be perfect. 💯 

See you at Devcon :)
