### ISSUE TITLE
List Omen as a Dapp under "Trading and prediction markets" on ethereum.org/dapps

### ISSUE THREAD

**Issue by ontologymachine** [ethereum/ethereum-org-website#2207]
**Is your feature request related to a problem? Please describe.**

Omen, the decentralized prediction market platform developed by the DXdao and powered using Gnosis' conditional tokens framework, is missing from the list of Trading and prediction market apps and it would be great if it could be added!

**Describe the solution you'd like**

I would like to list Omen ([omen.eth.link](url)) prediction market platform, powered by Gnosis' Conditional Tokens Framework, as a Dapp under "Trading and prediction markets" on [ethereum.org/en/dapps](url)

**Describe alternatives you've considered**

There can be no alternative - this is the only way ;)

**Additional context**

I am making this request based on the directions here: https://ethereum.org/en/contributing/adding-products/ so I hope it came to the right place.

For more information on Omen, please read [](https://blog.gnosis.pm/omen-and-the-next-generation-of-prediction-markets-2e7a2dd604e) and check it out for yourself at [omen.eth.link](url)!

For further questions please feel free to message me on Telegram at @ontologymachine or email beth.mccarthy@gnosis.io.

**Comment by ryancreatescopy** [comment]
Hi @ontologymachine thanks for this. Could you please provide the information asked for in the dapp issue template and we'll look into adding your product! https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=Type%3A+Feature%2C+Type%3A+Content&template=suggest_dapp.md&title=

**Comment by GeorgeTrotter** [comment]
Hey @ontologymachine - following up on this! Can you provide the information requested below so we can have a look at listing your dapp? Thank you!

Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**



**Is your dapp open source?**



**Can a user access the dapp without creating an account?**



**Are dapp funds non-custodial?**



**Do you offer community support?**



**Describe any geographical restrictions on usage of your dapp**



**Dapp title**



**Dapp description**



**Dapp logo**



**Brand color**

**Comment by GeorgeTrotter** [comment]
Hi @ontologymachine - we're closing this issue for now. Please feel free to reopen with the above info any time you like!
