### ISSUE TITLE
Contributor List Overflow

### ISSUE THREAD

**Issue by siddhantkharode** [ethereum/ethereum-org-website#2224]
**Describe the bug**

The contributor list of respective pages show 5 latest contributors on desktop but the contributor names and avatars overflow the container while accessing on mobile.

**To Reproduce**

1) Go to https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/
2) Click on 'See Contributors' button

**Expected behavior**

The container should either show the latest 5 contributors or should show all the contributors while accessing the website on all devices.

**Screenshots**

![Screenshot (81)](https://user-images.githubusercontent.com/50978880/103855783-63f41d00-50d9-11eb-8195-7b8e2b0283af.png)

![Screenshot_20210107-105411~2](https://user-images.githubusercontent.com/50978880/103855824-7a9a7400-50d9-11eb-95b9-1115171da12f.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version 84.0.1

**Smartphone (please complete the following information):**

- Device: Moto G5+
- OS: Android 8.1.0
- Browser Chrome

**Additional context**

**Comment by samajammin** [comment]
Thanks for reporting!

@all-contributors please add @siddhantkharode for bug reports.
