### ISSUE TITLE
Add Unstoppable Wallet

### ISSUE THREAD

**Issue by Dadybayo** [ethereum/ethereum-org-website#2229]
Unstoppable Wallet is an open-source, non-custodial storage solution known for its intuitive design and frictionless user experience. Moreover the wallet natively integrates decentralized trading/exchange capabilities by integrating protocols such as Uniswap on Ethereum.

- source code Android: https://github.com/horizontalsystems/unstoppable-wallet-android
- source code iOS: https://github.com/horizontalsystems/unstoppable-wallet-ios

The wallet is non-custodial, meaning that the wallet itself never "holds custody" of the assets:

- It is a one wallet app for all your cryptocurrencies.

- It is a non-custodial wallet without third party risk.

- The private keys, with which you control the cryptocurrency, are stored in secure storage mechanisms provide by OS.

- You can monitor crypto balances, transaction history & other details in real time.

- You can see the current price of assets in your preferred base currency.

- You can set alerts for price changes and price trend reversals.

- You can use FaceID, Touch ID, or conventional lock codes to lock your wallet.

- It is possible to add any Ethereum ERC20 token to your wallet.

- It is possible to add any Binance BEP2 token to your wallet.

- The wallet has WalletConnect Support.

- You have a real-time transaction fee estimator for Bitcoin and Ethereum.

- You have ability to set custom transaction fees.

- There is functionality for easily migrating to Unstoppable from other wallets (*e.g.*, Metamask) and vice versa.

- You can backup and restore existing wallets using a standard 12-word BIP39 recovery phrases.

- *Bitcoin Enhancements*: SPV wallet / Segwit support / No address reuse.

- *Bitcoin Advanced*: Ability to send Bitcoins that can’t be spent until certain date.

### Active Users

Our Android/iOS apps was first launched on 18th December 2018 and currently has more than 5000 downloads. Number of daily active users nearly quadrupled over last 4/5 months. Going from about 1.5 to about 4.5 thousand daily active users. These are the people that user the wallet app daily.

### Partnerships

Unstoppable worked with Zcash team to be the first wallet to support fully shielded/private Zcash transactions. That partnership turned out fairly well and we continue working with them on various features.

- https://electriccoin.co/blog/zcash-is-unstoppable-privacy-focused-wallet-first-to-integrate-ecc-wallet-sdks/
- https://forum.zcashcommunity.com/t/zcash-is-unstoppable-ama/37782/15

We are working on other partnerships with players in the cryptocurrency ecosystem as well which, will be announced in the coming weeks.

### Security Audit

Few weeks back we have completed our first security audit by Certik, https://certik.foundation. The audit was specifically focused on private key generation and key storage security. The audit hasn't revealed any serious issues and about to be published on their website.

The audit did make a couple of minor suggestions related to some non-critical elements all of which are being implemented in the release version 0.19 scheduled for mid January.

All that said, we still remain one of the few wallets out there with verifiably open source code as listed on WalletScrutiny.com.

### User Help / Assistance

We monitor feedback on crypto forums, subreddits, app stores, social channels and Google in general.

The wallet also got an extensive FAQ section for troubleshooting as well as Academy section for learning cryptocurrency and Ethereum in particular. Moreover, the users can easily reach us on Twitter, Reddit and via email.

### Press Kit

- https://github.com/horizontalsystems/HS-Design/blob/master/README.md

I invite you to check out the wallet website https://unstoppable.money

_Looking forward to for your feedback!_

**Comment by Dadybayo** [comment]
Dear friends, please consider our wallet
@GeorgeTrotter @ryancreatescopy

**Comment by ryancreatescopy** [comment]
@GeorgeTrotter nudge on this

**Comment by GeorgeTrotter** [comment]
Hey @Dadybayo - my sincere apologies for the long delay on this. I've had a look at the material you've provided and everything looks great. I have a few clarifying questions for you and then we can move forward quickly:

**Is the wallet a multi-signature wallet?**

I don't think so - is that correct? 

**Wallet description**

"Unstoppable Wallet is an open-source, non-custodial storage solution known for its intuitive design and frictionless user experience."

- We'll use this as a description of your wallet on the site. Does that work for you? 

**Brand color**



- What color should we use? I don't think I saw a code in your press kit - let me know if I'm mistaken!

Thank you!

**Comment by Dadybayo** [comment]
Hey @GeorgeTrotter - Thank you for your reply.

Yes, you are right, Unstoppable is not a multi-signature wallet, but it is **multi-currency**. 

**Wallet description** 

I suggest replacing it with this text 

"Unstoppable Wallet is an open-source, non-custodial, and easy-to-use multi-crypto wallet with extensive market analytics tools and the ability to swap crypto via decentralized exchanges in a frictionless manner."

**Brand Color** 

Brand Color - #FFBE43

**Comment by wackerow** [comment]
@Dadybayo Any chance you could link to the logo asset you want to use?

**Comment by Dadybayo** [comment]
https://github.com/horizontalsystems/HS-Design/blob/master/PressKit/UW-Logo-on-light.svg

**Comment by Dadybayo** [comment]
@samajammin When Ethereum.org site will update its list of wallets?

**Comment by samajammin** [comment]
@all-contributors please add @Dadybayo for content.

**Comment by samajammin** [comment]
> @samajammin When Ethereum.org site will update its list of wallets?

We'll update the site this week. You can keep an eye on our releases here: 
https://github.com/ethereum/ethereum-org-website/releases

**Comment by Dadybayo** [comment]
Wonderful, thank you. Have a productive week!
