### ISSUE TITLE
Headings on Eth 2.0 pages obstruct content on scroll

### ISSUE THREAD

**Issue by sweetpea22** [ethereum/ethereum-org-website#2231]
**Describe the bug**
Headings on pages about Beacon Chain and Sharding have a fixed position and obstruct content on tablet. Screen resolution at 1536px wide. It seems on Chrome devtools the emulator is showing this happening on iPad at 768px wide too.

**To Reproduce**

1. Go to https://ethereum.org/en/eth2/beacon-chain/
2. Use google inspector on setting "iPad 768px" or visit the same site on a tablet if you own one.
3. Scroll the page.

**Expected behavior**
For the heading to stay put when scrolling the page on tablet, like it does on mobile.

**Screenshots**
![IMG_1147](https://user-images.githubusercontent.com/47398578/104106397-845fdb00-5283-11eb-81fa-e46b343c47c0.PNG)
![IMG_1145](https://user-images.githubusercontent.com/47398578/104106399-86299e80-5283-11eb-9d68-a15d71db901d.PNG)

**Tablet (please complete the following information):**

- Device: iPad Pro 9.7"
- OS: iPadOS 14.3
- Browser: Brave 1.18.78 and Safari 14.0.2
**Additional context**

**Comment by wackerow** [comment]
@sweetpea22  Thanks for bringing this up! I am unable to replicate this issue on Brave/Safari on macOS/iPad OS (anyone else?). Could you possibly try clearing your browser cache and seeing if this still occurs?

**Comment by sweetpea22** [comment]
Hi, yeah it's still there after clearing my cache, and also still seeing it in the inspector too on screen res of 768px.

**Comment by samajammin** [comment]
@ryancreatescopy were you able to replicate? I'm not able to either.
