### ISSUE TITLE
Reorder Developer Frameworks

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/ethereum-org-website#2235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Developer Framework ordering seems to be outdated, and we are not putting our best foot forward with developer frameworks. 

**Additional context**

See [here for a writeup of the current frameworks.](https://github.com/PatrickAlphaC/smart-contract-frameworks)

**Comment by ryancreatescopy** [comment]
Fixed by #2236

**Comment by samajammin** [comment]
Closing this out - solved in #2236
