### ISSUE TITLE
Programming-Language Specific Pages: Javascript

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#224]
Let's add resource pages that cater to specific user groups to "meet people where they're at", making Ethereum more approachable to a broader range of people.

The /java page is a great template to work off:
https://ethereum.org/java/
https://github.com/ethereum/ethereum-org-website/blob/dev/docs/java/index.md

**Comment by faraggi** [comment]
@samajammin  I can _**try**_ do make this before devcon, but js really isn't my field, so any help and pointers in the right direction would be great.

**Comment by faraggi** [comment]
Open call for help can be found here:
https://twitter.com/felipefaraggi/status/1177495069156229121

**Comment by samajammin** [comment]
Thanks! I'm happy to take a swing at it. If no one has jumped on it yet by next week, I'll open up a PR where you & other folks can comment to add input.

**Comment by samajammin** [comment]
@faraggi I've created a WIP PR - https://github.com/ethereum/ethereum-org-website/pull/268

Contributions welcome!

**Comment by samajammin** [comment]
Merged & deployed - it's pretty bare bones, contributions still welcome!
https://ethereum.org/javascript/
