### ISSUE TITLE
Decentralize

### ISSUE THREAD

**Issue by SirAlcan** [ethereum/ethereum-org-website#2250]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

**Is your dapp open source?**

**Can a user access the dapp without creating an account?**

**Are dapp funds non-custodial?**

**Do you offer community support?**

**Describe any geographical restrictions on usage of your dapp**

**Dapp title**

**Dapp description**

**Dapp logo**

**Brand color**

**Comment by samajammin** [comment]
Hey @SirAlcan - if you'd like to suggest dapp, please address the questions in the issue template.

Closing this out. Feel free to re-open once you've answered those questions. Thanks!
