### ISSUE TITLE
Translation progress card style update

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2251]
**Is your feature request related to a problem? Please describe.**

These card styles are outdated:
https://ethereum.org/en/contributing/translation-program/#in-progress

**Describe the solution you'd like**

Similar to #2076 & #2195 - let's update these card styles to match the one on the Languages page:
https://ethereum.org/en/languages/

Given that these card styles are now in 3 separate components, let's see if we can consolidate these into a single shared component in SharedStyledComponents.js 

**Describe alternatives you've considered**

**Additional context**

We should wait until #2227 is merged before moving on this.

**Comment by samajammin** [comment]
@wackerow mind knocking this out (once #2227 is merged)?

**Comment by Anuragtech02** [comment]
Hey @samajammin  I'd like to work on this! Could you please assign this to me ?

**Comment by wackerow** [comment]
@Anuragtech02 Thanks for offering to help on this!! Don't hesitate to drop questions/more comments here, or hop onto our [Discord](https://discord.gg/CetY6Y4) to say hi. If you end up not having the time for it just let us know and we can un-assign you. 🙂
