### ISSUE TITLE
Unify card transition/hover states

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2253]
**Is your feature request related to a problem? Please describe.**

At the moment, we lack consistency in our card hover states. See the cards on [What is Ethereum?](https://ethereum.org/en/what-is-ethereum/) vs [Languages](https://ethereum.org/en/languages/) as an example.

**Describe the solution you'd like**

One consistent, accessible approach that fits our site's aesthetic and is changed on all cards with a hover state (where the whole card is clickable.)

For more context see #2227 & #2251

**Comment by samajammin** [comment]
Thanks for kicking off this conversation @ryancreatescopy! This relates to #2251 as well, will update the issue.

**Comment by samajammin** [comment]
My current stance (loosely held): generally I support rolling out consistent styles but I don't necessarily think ALL cards that are links MUST have the same hover & transition states, e.g. I'm fine with different treatment for ActionCard components that contain images (like the cards on [What is Ethereum](https://ethereum.org/en/what-is-ethereum/)) given they have different background colors that a hover shadow/transition may look weird on.

From a personal opinion on aesthetic, I tend to favor the box shadow / border animations (i.e. on [Languages page](https://ethereum.org/en/languages/) vs. the zoom/scale effect of ActionCards (i.e. on [What is Ethereum page](https://ethereum.org/en/what-is-ethereum/)). Having the text grow & shift throws me off slightly. Not a super strong preference though.

**Comment by ryancreatescopy** [comment]
Ok, let's ignore the style changes in #2227 and revert back to the transition/ border style we had before.
