### ISSUE TITLE
Add brownie tutorial for python engineers

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/ethereum-org-website#2257]
We'll consider [our article policy](https://ethereum.org/en/contributing/adding-articles/) when reviewing the tutorial, so please take a look there first.

**Tag your tutorial**
https://codeburst.io/deploy-a-smart-contract-using-python-how-to-b62de0124b?source=friends_link&sk=518545da7400ba3061f29185b479a417

- Brownie 
- Python
- Ethereum

**Tutorial title**
Deploy a Smart Contract using Python and Brownie: How-to

**Tutorial description**

Python has numerous tools including brownie and web3.py that allow users to become a blockchain engineer. This goes over the basics of brownie, and also a little bit of web3.py

**Publication**

Medium - codeburst

**Skill level**

Intermediate

**Paste in your tutorial below**

https://codeburst.io/deploy-a-smart-contract-using-python-how-to-b62de0124b?source=friends_link&sk=518545da7400ba3061f29185b479a417

**Comment by wackerow** [comment]
Closed with #2258
