### ISSUE TITLE
Add "run a node" page to developer docs

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2270]
**Is your feature request related to a problem? Please describe.**

We have an excellent new resource from #2182 (thanks @taxmeifyoucan!) but we don't currently link to it anywhere.

**Describe the solution you'd like**

- [x] Add page to /developers/docs/ navigation
- [x] Add links to this page from relevant pages (https://ethereum.org/en/developers/docs/nodes-and-clients/ being the obvious one, though there's probably many others)

**Describe alternatives you've considered**

@ryancreatescopy think this should page should live under /developers/docs/nodes-and-clients/? e.g. /developers/docs/nodes-and-clients/run-a-node/? Makes sense to me from a hierarchical perspective. Also "run" has more search volume vs. "spin up".

**Additional context**
Page added in #2182

**Comment by samajammin** [comment]
@wackerow mind knocking this out?

**Comment by wackerow** [comment]
No problem... I agree, `nodes-and-clients/run-a-node/` seems fitting, it's where I would look

**Comment by wackerow** [comment]
![image](https://user-images.githubusercontent.com/54227730/104992689-69edd600-59d6-11eb-9a7d-d7762692609f.png)
Btw, this is currently linked, but only buried within the `nodes-and-clients` page. Will fix
