### ISSUE TITLE
Integrate kb.beaconcha.in content

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2277]
**Is your feature request related to a problem? Please describe.**

The folks at beaconcha.in have built out some incredible technical resources on Eth2:
https://kb.beaconcha.in/

The content is open source & free to use:
https://github.com/gobitfly/eth2-knowledge-base/blob/master/LICENSE

Chatted with @Buttaa & confirmed that we're welcome to add their resources on the site. As always, we should link out to them w/ credit as the original source.

**Describe the solution you'd like**

We should discuss & decide the best place for this content. 2 main options

1. Within the Eth2 section: https://ethereum.org/en/eth2/
2. Within the developer docs section: https://ethereum.org/en/developers/docs/

Curious to hear what folks think. My take: given their technical focus & that eventually, "Eth2" resources will eventually become just "Ethereum" dev resources, I learn toward putting them within the developer docs. On the side navigation we currently have an "Advanced" section. We could store them there or create a new "Eth2" section.

**Describe alternatives you've considered**
Just link out to kb.beaconcha.in pages where appropriate

**Context**

Part of this epic: #7075

**Comment by samajammin** [comment]
Some thoughts on specific pages:
- https://kb.beaconcha.in/glossary : add individual terms to https://ethereum.org/en/glossary/ (if they don't yet exist) with the preface that it's related to Eth2 & link to https://ethereum.org/en/eth2/
- https://kb.beaconcha.in/ethereum-2.0-blocks : add terms to Eth2 block explorer (if they don't yet exist) https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/#eth2-data
- Port over pages for new Eth2 dev docs section:
   - https://kb.beaconcha.in/staking-and-hardware
   - https://kb.beaconcha.in/ethereum-2-keys
   - https://kb.beaconcha.in/ethereum-2.0-depositing
   - https://kb.beaconcha.in/attestation

Pages I'm not sure about:
- https://kb.beaconcha.in/the-genesis-event (is this important anymore? Perhaps useful knowledge to understand?)
- https://kb.beaconcha.in/depositing-to-ethereum-2.0 (should we just refer folks to https://launchpad.ethereum.org/)
- https://kb.beaconcha.in/rewards-and-penalties (great topic but needs content)

**Comment by Buttaa** [comment]
Hi @samajammin , 

here are additional ideas which I did not have time for yet

- How rewards work
- improving inclusion delays
- explain port forwarding + practical example 
- key managment
- how to handle extreme scenarios (electricity/internet outage)

**Comment by ryancreatescopy** [comment]
> My take: given their technical focus & that eventually, "Eth2" resources will eventually become just "Ethereum" dev resources, I learn toward putting them within the developer docs. On the side navigation we currently have an "Advanced" section. We could store them there or create a new "Eth2" section.

For this very reason, I think we should integrate these as much as possible into existing sections. Make sure we have clear ETH2 sections within pages where relevant. I don't think we should create an ETH2 bucket, instead integrate into existing sections wherever possible.

**Comment by minimalsm** [comment]
Re-up this?

**Comment by samajammin** [comment]
Latest thinking on this - maybe we should create a staking "docs" section under the main staking page:
https://ethereum.org/en/staking/

We could use the same docs.js markdown template we use for the developer docs:
https://ethereum.org/en/developers/docs/

Reasoning is that these resources should probably be kept separate from the developer docs… we don’t want to intimidate folks by making them feel they need to be a developer in order to be technical enough to stake.

**Comment by samajammin** [comment]
@jmcook1186 assigning to you as well 😄 - feel free to update this issue/description as needed.

**Comment by wackerow** [comment]
Calling this complete with the merging of our post-merge content. 🎉
