### ISSUE TITLE
Site Translation: Spanish

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#229]
Volunteers needed to complete this translation!
https://crowdin.com/project/ethereumfoundation/es-EM#

**Comment by faraggi** [comment]
@samajammin  I'm new to crowdin.com and crowd translations, so I might be wrong, but I believe the translation linked above is at 100%.

Whats missing for this to go live?

**Comment by samajammin** [comment]
@faraggi thanks for pointing this out! You're correct, it does appear to be complete on CrowdIn. I'll double-check with the translation team on this. We've been using a professional service to audit the volunteer's translation so we may be waiting on them. If not, I'll get this going ASAP!

**Comment by faraggi** [comment]
Let me know if there's anything I can do.
I specifically noticed none (?) of the current translations have the new landing pages in them, like enterprise or python.

**Comment by samajammin** [comment]
@faraggi that would be awesome! Let me get in touch with the folks leading our translation effort. The initial push has been to get the core landing pages translated for [these languages](https://crowdin.com/project/ethereumfoundation), with the understanding that other languages will lag behind the other English content for the time being. We're in the midst of hashing out a maintenance process for keeping translations up to date.

Question for you - if you're interested in translating Spanish content for the site, what platform would you prefer? CrowdIn? Github? Something else? I've noticed other communities (like [Vue](https://github.com/vuejs) & [React](https://github.com/reactjs)) manage translations via Github project forks. I haven't dug in too much yet but I like the concept of distributing the workload & empowering volunteer maintainers with repo ownership.
