### ISSUE TITLE
Add ethscan.org eth2 explorer with a free public API

### ISSUE THREAD

**Issue by nobd** [ethereum/ethereum-org-website#2292]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

https://ethscan.org/

**Product description:**

Open-source eth2 beacon chain explorer based on the original eth2 explorer by bitfly, offering a free public API.
Maintained by [Redot.com](https://redot.com/)

**How long has it been around?**

Since December 2020.

**Where do you think it should go?**

https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/#eth2-block-explorers

**GitHub URL**

https://github.com/nobd/ethscan-org

**Docs URL**

https://github.com/nobd/ethscan-org/tree/master/docs

**Is the product open source?**

Yes

**Additional context**

Our motivation to host this explorer as a completely free public service with long-term commitment boils down to 3 key points:

1. If bitfly's beaconcha.in goes down for whatever reason there is just 1 explorer left in the world for eth2 which is closed source (beaconscan.com). We are not comfortable knowing this as eth2 validators and staking service operators.

2. bitfly's beaconcha.in offers paid APIs (https://beaconcha.in/pricing) you have to purchase not to hit essential rate limits which we believe is something hindering the eth2 ecosystem development - we got rid of paid APIs and any kind of rate limits in our explorer instance, i.e. APIs are available for free without limitations.

3. We have noticed sporadic delays in beaconcha.in explorer syncing to the latest slot, which we tried to address with HPC dedicated hardware running in DCs in 2 regions (EU and Asia). Additionally, we are working to improve the explorer backend logic to make our BE instance more stable & performant.

**Comment by Buttaa** [comment]
https://github.com/prysmaticlabs/documentation/pull/302#issuecomment-764748273

**Comment by nobd** [comment]
Hi @Buttaa, we've amended our beaconcha.in mirrors to retain branding as suggested by @rauljordan, please see my comment here https://github.com/prysmaticlabs/documentation/pull/308#issuecomment-766623280

**Comment by Buttaa** [comment]
Please look into the official license on our repository. There are still a lot of things missing to fulfill the requirements.

**Comment by nobd** [comment]
@Buttaa thanks for pointing, we're on it.

**Comment by nobd** [comment]
I believe we have addressed all the requirements of GPL-3 as per https://choosealicense.com/licenses/gpl-3.0

Copyright and license notices are preserved, source code is disclosed (https://github.com/nobd/ethscan-org).
