### ISSUE TITLE
Add BitKeep Wallet to Wallet list

### ISSUE THREAD

**Issue by sam17889** [ethereum/ethereum-org-website#2299]
Product name:

BitKeep Wallet

https://bitkeep.org

Product Description:

BitKeep is the world's leading decentralized multi-chain non-custodial digital wallet, dedicated to providing secure and simple one-stop digital asset management services to users worldwide. With complete DEFI suit and DAPP store.

How long has it been around?

Since 2018.

Where do you think it should go?

https://ethereum.org/en/wallets/

GitHub URL

https://github.com/bitkeepcom

Is the product open source?

Yes

**Comment by GeorgeTrotter** [comment]
Hey @sam17889 - thanks for your submission and sorry for the wait! I've got some questions about the wallet's features we need to know about before listing. 

- I couldn't find any information on BitKeep's audits or other security measures. Do you know what steps BitKeep has taken for security?

- Does BitKeep have limits protection for high volume transactions, to protect user funds?

- Does BitKeep support multisig?

- What hex code colour should we use for BitKeep?

Let me know!

**Comment by GeorgeTrotter** [comment]
Hey @sam17889 following up about the questions above!

**Comment by GeorgeTrotter** [comment]
Hey @sam17889 we are closing this issue for now. Feel free to reopen with the above info included!
