### ISSUE TITLE
Site Translation: Russian

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#230]
Volunteers needed to complete this translation!
https://crowdin.com/project/ethereumfoundation/ru#

**Comment by sneg55** [comment]
noticed that not all EN strings from  `/docs/use/index.md ` listed  as a source  https://crowdin.com/translate/ethereumfoundation/384/en-ru 
eg. 

![image](https://user-images.githubusercontent.com/7769371/65301466-881a9c00-db2c-11e9-9d24-8c1a5b4973d0.png)
![image](https://user-images.githubusercontent.com/7769371/65301479-95378b00-db2c-11e9-89ed-e4ce19cc482e.png)

@samajammin

**Comment by samajammin** [comment]
Thanks for the comment @sneg55 but I'm not sure I follow. Could you clarify the issue you see? Is it that the "Ethereum Dapps" article title is not translated in the Russian file?

**Comment by sneg55** [comment]
I'm talking about the difference between files at repo and files at crowdin.

**Comment by samajammin** [comment]
Ah, ok, thanks for catching this & clarifying. This is because the source files that were uploaded when the Russian translation project began are now outdated (i.e. some content & links have since been added to the English pages).

For now, we're anticipating that updates to translated pages will lag a bit behind the English counterparts. Our team is working on a process to minimize this lag time (to start, making it easier to identify differences) but we welcome any suggestions you might have!
