### ISSUE TITLE
Repeat sidenav on docs page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2301]
**Describe the bug**

Kinda hard to replicate this. I think it's a return of the caching issue as it seems to sometimes appear and other times not. Refreshing can sometimes cause it.

First discovered on: https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/105507375-03f99b00-5cc3-11eb-9571-12f684ed6ea1.png)

![image](https://user-images.githubusercontent.com/40891631/105507392-08be4f00-5cc3-11eb-91cd-68d7f78976ca.png)

random arrow halfway down the page

![image](https://user-images.githubusercontent.com/40891631/105507417-11af2080-5cc3-11eb-868e-632856ab037e.png)

![image](https://user-images.githubusercontent.com/40891631/105507432-170c6b00-5cc3-11eb-84e6-7d7bb09f2f6b.png)

**Comment by mikejpoole** [comment]
The "random arrow" @ryancreatescopy is referring to is an SVG with the classes `.Icon__StyledIcon-sc-1o8zi5s-0` and `.idUHpq` which is used in the mobile side navigation.

I would be happy to fix this if you would like to assign it.

**Comment by ryancreatescopy** [comment]
Thanks @mikejpoole!

**Comment by mikejpoole** [comment]
Hi @ryancreatescopy I set aside some time this afternoon to fix this but was unable to replicate the problem. I understand that it was intermittent but do you know if it is still happening for you?

**Comment by okdonga** [comment]
@ryancreatescopy @mikejpoole  I am able to reproduce this issue on my pc. It's actually happening on all ```/docs``` sites on light mode. I can have a go at fixing this issue if that's okay.

**Comment by mikejpoole** [comment]
Thanks @okdonga it's all yours :)
