### ISSUE TITLE
Update translation program page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2316]
Add basic guideline & instructions on the Translation Program page.

- [x]  Screenshot function - Where to get more context on the ambiguous strings?
- [x]  Comment tab - How to raise an issue for typo or broken hyperlink?
- [x]  Glossary - What's the definition of the word? What's the official translation into your language?
- [x]  Terminology Translation policy -  for names (Brand, company, a person) & new tech term (Eth2, beacon chain, etc)

@sorumfactory to draft
@ryancreatescopy to create PR

**Comment by sorumfactory** [comment]
Hello all, 
the draft of the Translation Program Guideline is ready: https://www.notion.so/efdn/Updating-the-Translation-Program-page-Guideline-b82099bf90ea4f2d9926250e66255e90

- I'm expecting to add it to the end of the Translation Program page.
- The screenshot images will be replaced with better ones once it is finalized. (I know they're ugly.🤦‍♀️)
- Especially, I would like to hear your opinions on the last part "Q6. Terminology Translation Policy" which is the most controversial.
- Feel free to leave comments or directly tweak if necessary.
