### ISSUE TITLE
Migrate/add JSON-RPC docs to ethereum.org

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2322]
## Description

- [ ]  Make space for JSON RPC docs on ethereum.org
- [ ]  Can the UX/readability of specs be improved?
- [ ]  Publish specs
- [ ]  Set up redirects

## Context

https://github.com/ethereum/eth-wiki/issues/55

**Comment by samajammin** [comment]
Opened up an issue on ethereum-oasis/eth1.x-JSON-RPC-API-standard#8 for input on this.

**Comment by samajammin** [comment]
A couple ideas...

1) I watched a [great presentation](https://www.youtube.com/watch?v=MZxqRs_tLNs) from @pipermerriam recently where he categorized the core JSON-RPC endpoints:
![image](https://user-images.githubusercontent.com/8097623/106047648-b69d7500-6098-11eb-8fda-ba6e4f7f259e.png)
I wonder if we should organize endpoints / allow filtering of endpoints in a similar manner?

2) @djrtwo shared that the Eth2 folks built an [API browser](https://ethereum.github.io/eth2.0-APIs/) (from [this repo](https://github.com/ethereum/eth2.0-APIs)). Looks like this was built using [Swagger](https://swagger.io/solutions/api-documentation/). I believe Swagger only support REST APIs (vs. JSON-RPC) but finding/creating a similar solution might be an alternative here vs. building the documentation into our Gatsby app. It would be nice to provide the ability to execute requests directly in the web UI & inspect response payload, which tools like Swagger provide out of the box.
