### ISSUE TITLE
Audit eth.wiki content

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2324]
Similar to [ethdoc.org](http://ethdoc.org) audit, let's create a spreadsheet to track & vet all pages

Note: I wasn't able to crawl this site like [ethdocs.org](http://ethdocs.org) **sigh* * so we may need to click through the site & add 1 by 1

Audit spreadsheet:
https://docs.google.com/spreadsheets/d/1yJL7hi5Q620BMH58Uv-H0NntzcdckNHtMOKyosnSExo/edit#gid=1639751855

Dependency: #2323

**Comment by minimalsm** [comment]
Closed by #5690 (the audit has been done, migration in progress)
