### ISSUE TITLE
Add an exchange - itez.com

### ISSUE THREAD

**Issue by mikehd2** [ethereum/ethereum-org-website#2330]
Before suggesting an exchange, make sure you've read [our exchange listing policy](https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**

Afghanistan, Algeria, The Bahamas, Botswana, Bangladesh, Bolivia, Cambodia, Ghana, China, Cuba, Ecuador, Egypt, Iceland, Mongolia, Pakistan, Syria, Trinidad and Tobago, Yemen, Zimbabwe, Guam, Libya, Nigeria, Samoa, Somalia, Lebanon, Guinea Bissau, Libya, Venezuela, Haiti, the Democratic Republic Congo, Sudan, Iran, North Korea, USA, Japan, Indonesia, Iraq, Kyrgyzstan, Morocco, Nepal, Vietnam.

**Which currencies are accepted by this exchange?**

US Dollar USD
EURO EUR
Russian Ruble RUB
Ukrainian Hryvnia UAH
Korean Won KRW
Indian Rupee INR
Turkish Lira TRY
Brazilian Real BRL
Pound Sterling GBP
Australian Dollar AUD
Hong Kong Dollar HKD
Taiwan New Dollars TWD
Belarusian Ruble BYN
Armenian Dram AMD
Kazakhstani Tenge KZT
Polish złoty PLN
Singapore Dollar SGD
Vietnamese dong VND
Swedish krona SEK
Moldovan leu MDL

**Do you have any proof that they're a legitimate company?**

https://itez.com/terms
https://mtr.mkm.ee/juriidiline_isik/240857
https://www10.fintrac-canafe.gc.ca/msb-esm/public/detailed-information/msb-details/7b226d73624f72674e756d626572223a3136333238382c227072696d617279536561726368223a7b226f72674e616d65223a2264617461627269646765222c2273656172636854797065223a317d7d/

**Do you have any extra information?**

itez.com - simple and fast non custodial service to buy Ethereum with Visa and Mastercard.

**Comment by GeorgeTrotter** [comment]
Hey @mikehd2, thanks for submitting this issue! Clarifying the geographical restrictions you've included - these are countries in which itez.com does not provide services, correct? 

Does itez.com service the US? If so, are there state-by-state restrictions or can US residents use itez.com wherever? 

Let us know!

**Comment by mikehd2** [comment]
Hi! @GeorgeTrotter
Thanks for your feedbaсk!

> Clarifying the geographical restrictions you've included - these are countries in which itez.com does not provide services, correct?

Yes, we dont provide our service in this locations.

> Does itez.com service the US? If so, are there state-by-state restrictions or can US residents use itez.com wherever?


No. For this moment we are unable to serve USA customers.

**Comment by GeorgeTrotter** [comment]
@wackerow good to go
