### ISSUE TITLE
Text color issue in dev

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2336]
**Describe the bug**

It appears that in our dev branch a change has made it in which causes text to display the same in light mode and dark mode. This means copy is basically unreadable in dark mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/106150021-cee1c280-6172-11eb-995e-392e4112c3ad.png)

![image](https://user-images.githubusercontent.com/40891631/106150173-f6388f80-6172-11eb-8142-e31d099a1b82.png)

**Comment by ryancreatescopy** [comment]
This can be fixed by removing `color: hsla(0, 0%, 0%, 0.8);` from `layout.css`

However, I'm not sure why this would suddenly be causing this as we haven't edited that line of code in ~8 months. @wackerow @samajammin any ideas?

**Comment by samajammin** [comment]
Hmmmm... @ryancreatescopy I'm not able to reproduce this. Just pulled latest `dev`:
![Image 2021-01-28 at 7 05 55 PM](https://user-images.githubusercontent.com/8097623/106226447-13ce1f00-619c-11eb-905b-cf5b256f7ede.jpg)

These variables should be set from theme.js:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/theme.js#L177
https://github.com/ethereum/ethereum-org-website/blob/dev/src/theme.js#L254

LMK if this is still an issue on your end.

**Comment by ryancreatescopy** [comment]
Weird... I guess it's a caching issue on my end again!

**Comment by ryancreatescopy** [comment]
Closing as it appears to be a caching issue my end.
