### ISSUE TITLE
Add Bitpie Wallet

### ISSUE THREAD

**Issue by songchenwen** [ethereum/ethereum-org-website#2338]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

Yes. 

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial. Users and only users have access to their private keys. They can recover their funds in any other compitable wallets.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Bitpie is developed by a crypto wallet team with a long history. We have 3 wallet products.

Bither, since May, 2014, is our first open sourced Bitcoin wallet, which is recommanded by bitcoin.org with a good reputation among the early Bitcoin users.

Bitpie, since Oct, 2016, is a mobile wallet (iOS/Android) for multiple Blockchain assets. Bitpie is not open sourced and we have not done any third party security audit yet. Bitpie relies on Android and iOS's security method to store user's private keys and ask for a pin code wherever a private key is used.

BitHD, since Dec, 2017, is an open sourced hardware wallet based on Trezor's firmware. We have added many useful functions such as easily used multisig function for BTC/ETH/
USDT and so on. [Here is the repo.](https://github.com/bithd) BitHD is deeply integrated with Bitpie. We recommand users use BitHD to store large amount of crypto assets.

As a wallet developing team with more than 7 years history, we've built a very large user base around many countries, especially in China. And a good reputation is kept all the way along.

**Does the wallet have fiat on-ramps?**

No fiat on-ramps. But we have a method for users to use their tokens as their transaction fees when they don't have any ETH.

**Does the wallet allow users to explore dapps?**

Yes. WalletConnect is integrated and Dapp Browser is built in.

**Does the wallet have integrated defi/financial tools?**

Yes.

**Can a user withdraw to their card?**

No.

**Does the wallet offer limits protection?**

No.

**Does the wallet allow high-volume purchases?**

No.

**Does the wallet have an integrated token swap?**

Yes.

**Is the wallet a multi-signature wallet?**

We do not support multisig function in Bitpie. But we have multisig supported in BitHD hardware wallet.

**Wallet title**

Bitpie

**Wallet description**

Bitpie is an multi-blockchain (BTC/ETH/LTC/ETC etc.) wallet. We are devoted to providing safe assets management and DApps for users worldwide.

**Wallet logo**

![logo_bitpie@3x](https://user-images.githubusercontent.com/6240753/106226782-f1331900-6222-11eb-9542-99f943d4da55.png)

**Brand color**

 FFFFFF

**Comment by GeorgeTrotter** [comment]
Hey @songchenwen  - we are closing this issue without listing Bitpie Wallet. In reference to our [listing policy](https://ethereum.org/en/contributing/adding-products/), we look to list wallets that have clearer security documentation and/or are open source so that their security can be verified. In addition, we look for products that fit our design principles: 

Inspirational: anything on ethereum.org should offer something new to users
A good story: what's listed should provide an "aha" moment
Credible: everything should be legitimate businesses/projects to minimise risk to users

Let us know if you have any questions, and please reopen an issue down the road if there are any big changes to Bitpie!
