### ISSUE TITLE
Systematize text styles

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2342]
**Is your feature request related to a problem? Please describe.**

Our text (particularly header) styles are getting a bit messy (shocker - CSS getting unruly!?).

Currently we have a variety of ways we've been setting header styles.

1) in SharedStyledComponents.js:

```
export const H1 = styled.h1`
  ${Mixins.textLevel1}
`
export const H2 = styled.h2`
  ${Mixins.textLevel2}
  @media (max-width: ${(props) => props.theme.breakpoints.m}) {
    font-size: 1.5rem;
  }
`
export const H3 = styled.h3`
  ${Mixins.textLevel3}
`
export const H4 = styled.h4`
  ${Mixins.textLevel4}
`
export const H5 = styled.h5`
  ${Mixins.textLevel5}
`
```

... which imports from

2) in theme.js where we create mixins:

```
export const Mixins = {
  textLevel1: `
    font-size: 3rem;
    line-height: 1.4;
    margin: 2rem 0;
    font-weight: 400;
  `,
  textLevel2: `
    font-size: 2rem;
    line-height: 1.4;
    margin: 2rem 0;
    font-weight: 600;
  `,
  textLevel3: `
    font-size: 1.5rem;
    line-height: 1.4;
    margin: 1.5rem 0 2rem;
    font-weight: 600;
  `,
  textLevel4: `
    font-size: 1.25rem;
    line-height: 1.4;
    font-weight: 400;
    margin-top: 2rem;
  `,
  textLevel5: `
    font-size: 1rem;
    line-height: 1.6;
    font-weight: 400;
    margin-top: 2rem;
  `,
  textLevel6: `
    font-size: .875rem;
    line-height: 1.6;
    font-weight: 400;
    letter-spacing: 0.04em;
    margin: 1.14em 0;
    text-transform uppercase
  `,
  textLevel7: `
    font-size: 1rem;
    line-height: 1.6;
    font-weight: 400;
    margin: 2rem 0 1rem;
  `,
  textLevel8: `
    font-size: .875rem;
    line-height:1.6;
    margin: 1.14em 0;
    font-weight: 400;
  `,
}
```

3. in individual page components, e.g. src/pages/index.js:

```
const H1 = styled.h1`
  font-size: 40px;
  font-weight: 700;
  margin-bottom: 0rem;
  text-align: center;
  @media (max-width: ${(props) => props.theme.breakpoints.s}) {
    font-size: 32px;
  }
`
```

**Describe the solution you'd like**

I suspect this can be simplified.

For one, we don't use the `Mixins` from theme.js much. Should we ditch those?

Instead, perhaps we:
- roll out defaults for all text elements (h1-h6, p, body, etc.) in `GlobalStyle` of theme.js.
- delete the H1-H6 in SharedStyledComponents.js (since those are now the defaults)
- extend the defaults in individual page components when necessary (as we do currently)

**Describe alternatives you've considered**

I welcome your thoughts & ideas @ryancreatescopy @wackerow 

**Additional context**

Surfaced in homepage work: #2124

**Comment by wackerow** [comment]
@samajammin Yeah this seems like a good idea, and a good starting point. I can take a look at this and get back to you
