### ISSUE TITLE
Create Assets page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#235]
## Expected Behavior

Create a page at ethereum.org/assets, which contains a variety of assets organized into two sections:

- [ ]  Section 1: "Previous landing page artwork"
    - The purpose of this section is to display previous HERO images, credit the artists for their work, and let people find and use this art themselves.
    - link to blog post on the initiative
    - Initially, this section will include only two images:
        - the current artwork, with the same credit information found on the main page
        - The previous artwork from launch (still available in our repo), with credit information to be provided by @jjmstark 

- [x]  Section 2: General Ethereum Graphic Assets
    - The purpose of this section is to display a variety of generic Ethereum graphic assets (logos, desktop backgrounds, etc)
        - Display image once, include text links to various file formats
    - Initially, we will use the same assets that were on the previous website
        - Dropbox folder with core assets: [https://www.dropbox.com/s/to15tj4hiid5mxe/Logos-20190613T055158Z-001.zip?dl=0](https://www.dropbox.com/s/to15tj4hiid5mxe/Logos-20190613T055158Z-001.zip?dl=0)*
            - No ef or devcon logos, just eth
    - Over time, people can add other art to this
    - This should also include the ethereum "font"

## Current Behavior

Page doesn't exist.

**Comment by tabathap** [comment]
👌

**Comment by richmanrich** [comment]
Lets complaint it

**Comment by samajammin** [comment]
Shipped the /assets page & broke out the "previous artwork" section into a separate issue: https://github.com/ethereum/ethereum-org-website/issues/332
