### ISSUE TITLE
Update homepage smart contracts to Solidity 0.8.x

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2357]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Good spot from @franzihei
> It would be nice if you could use a version from the current Solidity series with is 0.8.x. It is super hard to motivate the ecosystem to use the latest versions (while that is super important for secturity reasons!) hence we do not want to encourage using outdated versions by putting them on the ethereum.org website. : )

**Describe alternatives you've considered**

**Additional context**

**Comment by MonarthS** [comment]
We can change it to `^0.8.1`.
