### ISSUE TITLE
Languages page - "Learn more" link only works in /en

### ISSUE THREAD

**Issue by catsnackattack** [ethereum/ethereum-org-website#2359]
If you navigate to the Language Support page (https://ethereum.org/en/languages/) when reading the site in a language other than English, the "Learn more..." link doesn't work. The English url (https://ethereum.org/en/contributing/translation-program/) works fine but any other language pathway e.g. https://ethereum.org/bn/contributing/translation-program/ returns a 404.

**Comment by MonarthS** [comment]
It is happening because there is no translated data available for other languages.

**Comment by MonarthS** [comment]
@sorumfactory is the translation of [this](https://ethereum.org/en/contributing/translation-program/) page still remaining?

**Comment by wackerow** [comment]
@catsnackattack Hey! Thanks for bringing this up... @MonarthS is correct that this page does not have translated versions yet. 
@samajammin What do you think? I would assume this should redirect to the `/en/` english path automatically, but that also takes a user out of their chosen language. Alternatively we render a copy of the english version for all languages so they can read it and not be diverted back into all english pages.

**Comment by catsnackattack** [comment]
From what I can tell other pages are rendered in English if translations aren't available - this seems like a particularly ironic exception :D

**Comment by ryancreatescopy** [comment]
@all-contributors please add @catsnackattack for bug report.
