### ISSUE TITLE
Add GetBlock to Popular Nodes Services

### ISSUE THREAD

**Issue by wetryingtodorock** [ethereum/ethereum-org-website#2373]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

GetBlock

**Product description:**

[GetBlock](https://getblock.io) is a service that provides a fast and easy API connection to full nodes from many leading blockchain platforms, including Ethereum (ETH). It allows you to request on-chain information from a node without the need to set up one manually with JSON-RPC, REST, and WebSockets.

**How long has it been around?**

Since 2019

**Where do you think it should go?**

https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/#popular-node-services

**GitHub URL**

https://github.com/Getblock

**Docs URL**

https://getblock.io/docs/get-started/authentication-with-api-key/

**Is the product open source?**

No

**Additional context**

Features: 
* Access to 40+ blockchain nodes
* 40K free daily requests
* Unlimited number of API keys
* High connection speed at 1GB/sec
* Trace+Archive
* Advanced analytics
* Automated updates
* Technical support

**Comment by wetryingtodorock** [comment]
Hello! Can you take a look at this issue, please?

**Comment by wackerow** [comment]
@wetryingtodorock Hey! Sorry for the delay on this while we play catch up. Putting this into a PR now.
(Just curious, you listed this as open source but the GitHub account provided doesn't have any public repos... not a deal breaker for this specific page, just curious if the source code was available anywhere.. thanks!)

**Comment by wetryingtodorock** [comment]
> @wetryingtodorock Hey! Sorry for the delay on this while we play catch up. Putting this into a PR now.
> (Just curious, you listed this as open source but the GitHub account provided doesn't have any public repos... not a deal breaker for this specific page, just curious if the source code was available anywhere.. thanks!)

Hello! Thank you!
Sorry, that was my bad, the product is not open source, I've edited the answer to 'No'.

**Comment by wetryingtodorock** [comment]
Hello! I've seen you added info, it's all here: https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

Can you tell me, please, when it should appear on the website, because I can't find it there?

**Comment by ryancreatescopy** [comment]
@wetryingtodorock we deploy the site when there's enough new stuff. We'll probably deploy within the next day or so which should make these changes go live. Check here for updates: https://github.com/ethereum/ethereum-org-website/releases

**Comment by wetryingtodorock** [comment]
> @wetryingtodorock we deploy the site when there's enough new stuff. We'll probably deploy within the next day or so which should make these changes go live. Check here for updates: https://github.com/ethereum/ethereum-org-website/releases

Thank you so much for the reply!
