### ISSUE TITLE
Add New Language 'Urdu: Pakistan' on https://crowdin.com/project/ethereumfoundation

### ISSUE THREAD

**Issue by tahiralvi** [ethereum/ethereum-org-website#2376]
**Need to add a new language in https://crowdin.com/project/ethereumfoundation which is Urdu : Pakistan with Arabic script**

**Comment by okdonga** [comment]
Hi @tahiralvi  
I think this is the link to the Urdu translation page: 
https://crowdin.com/project/ethereumfoundation/ur-IN  
<img width="1210" alt="Screen Shot 2021-02-15 at 10 20 55 AM" src="https://user-images.githubusercontent.com/12257412/107895889-27d59700-6f78-11eb-95b7-6f028834249e.png">

**Comment by tahiralvi** [comment]
@okdonga The language has multiple variations. The said one is not recognized as Urdu (Pakistan).

**Comment by okdonga** [comment]
Ah I see, sorry about misunderstanding. I think you can reach out to Taeyeon Kim via the [Discussions](https://crowdin.com/project/ethereumfoundation/discussions) tab on the crowdin page.  It seems like she is in charge of adding new languages. 



<img width="1049" alt="Screen Shot 2021-02-17 at 3 43 28 PM" src="https://user-images.githubusercontent.com/12257412/108166025-e7704780-7136-11eb-85bd-8481ea2e1448.png">

**Comment by sorumfactory** [comment]
Hello @tahiralvi, thank you for your suggestion to add Urdu(Pakistan) language to ethereum.org! 
It's now available in Crowdin: [](https://crowdin.com/project/ethereumfoundation/ur-PK)
Feel free to reach out if you have any further requests or questions along the way :)

@okdonga Thank you very much for your support on this!

**Comment by samajammin** [comment]
Thank you @tahiralvi for the suggestion & thank you @sorumfactory for adding!

Closing this issue out but feel free to re-open if there's any further questions/issues.

**Comment by samajammin** [comment]
@all-contributors please add @tahiralvi for ideas.
