### ISSUE TITLE
throwing default message error in console

### ISSUE THREAD

**Issue by MonarthS** [ethereum/ethereum-org-website#2390]
**To Reproduce**

1. Open homepage of any language other than english
ex: https://ethereum.org/zh-tw/

**Screenshots**

![image](https://user-images.githubusercontent.com/40236229/106996290-b3943a00-67a6-11eb-996d-8729a1ba5a7f.png)

**Comment by yakkomajuri** [comment]
Seems like errors are being thrown deliberately:

https://github.com/ethereum/ethereum-org-website/blob/816b2de5cfd1e0c6e4c3353ab4da2d0f15dd7189/src/utils/translations.js

**Comment by yakkomajuri** [comment]
@samajammin what's the reason for throwing errors in prod?

**Comment by samajammin** [comment]
Thanks for reporting this @MonarthS!

> @samajammin what's the reason for throwing errors in prod?

Great point @yakkomajuri, we should only throw these errors in development. One solution might be to access an ENV variable: https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#accessing-environment-variables-in-javascript

**Comment by samajammin** [comment]
Solved in #2410 - thanks @yakkomajuri!
