### ISSUE TITLE
Add Guarda Wallet

### ISSUE THREAD

**Issue by bchrvl** [ethereum/ethereum-org-website#2404]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**
Yes

**Is your wallet custodial, non-custodial, or a hardware wallet?**
Non-custodial and supports integration with Ledger Nano S.
Users have full access to their public and private keys.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
Guarda is a non-custodial service that's been around since 2017 and users' security has been a number one priority since the very beginning. We do not store any of the users' data.
 Guarda uses AES encryption for generating backups. Also, MarkMonitor is used as a domain management solution. 

**Does the wallet have fiat on-ramps?**
Yes. It can be purchased with credit or debit through integrated partner service - Simplex or with SEPA through Guardarian.

**Does the wallet allow users to explore dapps?**
Yes. WalletConnect is integrated on iOS and Android apps. Also, we have our own browser extension that allows using dapps.

**Does the wallet have integrated defi/financial tools?**
Yes. Staking is available. We run the staking pool for Ethereum as well. Lending is coming soon.

**Can a user withdraw to their card?**
No.

No
**Does the wallet offer limits protection?**
No. But we have multisignature functionality to add extra security for transfers.

**Does the wallet allow high-volume purchases?**
Yes. Up to $20,000.

**Does the wallet have an integrated token swap?**
Yes. Via integrated services of ChangeNOW.

**Is the wallet a multi-signature wallet?**
Yes.

**Wallet title**
Guarda Wallet

**Wallet description**
Secure, feature-packed, non-custodial crypto wallet with support for over 50 blockchains. Easy stakings, exchange and purchase of crypto assets.

**Wallet logo**
https://guarda.com/assets/images/guarda-shield-logo.svg

**Brand color**
#798ce5

**Comment by wackerow** [comment]
@bchrvl Thanks for submitting, sorry for any delays! PR to add this going up now 👍
