### ISSUE TITLE
Explanation: Why Layout renders twice

### ISSUE THREAD

**Issue by yakkomajuri** [ethereum/ethereum-org-website#2406]
Not actually a bug but just thought I'd chip in given I was looking at the codebase.

The answer to this was probably already found but the answer to this comment:

```
// TODO `Layout` renders twice on page load - why?
```

Is the `useEffect` hook in `Layout`. In fact, it only renders twice if the theme changes, which is always if the person has a dark mode default.

Essentially, this is the same thing that causes dark mode users to experience "jumpiness". Since the browser APIs aren't available on the server and Gatsby does server-side rendering, it's impossible to know when the page is first rendered that the user prefers dark mode. What then happens is the user receives a page in light mode, and then the `useEffect` hook updates to their preference accordingly. 

There is indeed a way around this, but it would require a massive refactor of the codebase. You can see [this PR](https://github.com/PostHog/posthog.com/pull/551) for context.

So, effectively, as long as a `useEffect` hook updates the state and the state is dependent on browser APIs (like `window`, `localStorage`, `document`), some users will have a double render, and hence probably some "jumpiness".

Keep up the awesome work! ❤️

**Comment by ryancreatescopy** [comment]
Thanks for much for looking into this and providing the explanation. Head on over to our discord to get yourself a POAP if you want. Instructions here: https://ethereum.org/en/contributing/#poap
