### ISSUE TITLE
Simplify random sorting w/ Lodash's shuffle method 

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2407]
**Is your feature request related to a problem? Please describe.**

In a handful of components we've implemented logic to randomize the order of lists, e.g.
- https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Contributors.js#L37
- https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/WalletCompare.js#L299
- https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/developers/local-environment.js#L346

**Describe the solution you'd like**

Let's use the Lodash `shuffle` method:
https://lodash.com/docs/4.17.15#shuffle

I suspect in order to use this we'll need to [remove `collections` from our disabled Lodash features](https://github.com/ethereum/ethereum-org-website/blob/dev/gatsby-config.js#L81).

Let's see if this allows us to randomize during build time vs. requiring us to use in `useEffect`.

**Comment by Vishal19111999** [comment]
@samajammin I would like to work on this as my first issue!

**Comment by cj-technical** [comment]
@samajammin Would you want this abstracted away in a utility function or class? As in, if you wanted to swap out LoDash at some point in the future, it wouldn't create any breaking changes.

If so, where would those be housed in the overall solution?

**Comment by ryancreatescopy** [comment]
@Vishal19111999 sorry for the delay! We'd love for you to hop in to the code and help out with this. Thanks!
