### ISSUE TITLE
Add the steps to stop a node under the Stopping and Restarting a Node part of the Geth Light Client Tutorial

### ISSUE THREAD

**Issue by finleyexp** [ethereum/ethereum-org-website#2408]
To Stop the Node use : 
CTRL+C 

To Restart the Node use:
geth --ropsten --syncmode "light"

Replace "ropsten" with the testnet you want to use. Or, use "mainnet"

**Comment by wackerow** [comment]
@finleyexp Sorry for the delay, thanks for posting this! Looked at this a bit more and realized `--testnet` was being used in a few places in this tutorial, which is now a deprecated flag. Just put up a PR fixing this... Thanks for surfacing =)

**Comment by samajammin** [comment]
@all-contributors please add @finleyexp for ideas.
