### ISSUE TITLE
Link of community pointing at Enterprise 

### ISSUE THREAD

**Issue by comeToThinkOfEth** [ethereum/ethereum-org-website#2413]
https://github.com/ethereum/ethereum-org-website/blob/bde851b1dd6073d701b3482f350af50f879e7fb0/src/pages/index.js#L471

**Comment by wackerow** [comment]
@comeToThinkOfEth Thanks for spotting this! Will patch this now, good catch

**Comment by samajammin** [comment]
@all-contributors please add @comeToThinkOfEth for bug reports.

**Comment by samajammin** [comment]
Thanks @comeToThinkOfEth! Great handle name BTW 😄
