### ISSUE TITLE
Add Fortmatic Wallet

### ISSUE THREAD

**Issue by hcote** [ethereum/ethereum-org-website#2423]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

Yes.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Users have access to their private keys through our non-custodial [Delegated Key Management](https://medium.com/fortmatic/security-infrastructure-at-fortmatic-4a95c3688997).

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

[Delegated Key Management Explained](https://medium.com/fortmatic/security-infrastructure-at-fortmatic-4a95c3688997)

**Does the wallet have fiat on-ramps?**

Yes, through Moonpay.

**Does the wallet allow users to explore dapps?**

Yes, on any dapps that Fortmatic is a wallet option. Fortmatic is not integrated with WalletConnect, and also doesn't have a dapp browser.

**Does the wallet have integrated defi/financial tools?**

 Fortmatic is integrated in defi protocols such as Uniswap, Aave, Zerion, Tokensets, 1inch.

**Can a user withdraw to their card?**

No. 

**Does the wallet offer limits protection?**

No.

**Does the wallet allow high-volume purchases?**

Depending on a users level of KYC, they can purchase up to $50k worth of crypto per day.

**Does the wallet have an integrated token swap?**

No.

**Is the wallet a multi-signature wallet?**

No.

**Wallet title**

Fortmatic

**Wallet description**

Access Ethereum apps from anywhere with just an email or phone number. No more browser extensions and seed phrases.

**Wallet logo**

<img width="529" alt="fortmatic-vertical-black" src="https://user-images.githubusercontent.com/34493689/107701978-dc20a600-6c76-11eb-8a26-5490fd50f068.png">

**Brand color**

#6851ff

**Comment by samajammin** [comment]
@wackerow mind knocking this out? Thanks!

**Comment by wackerow** [comment]
@hcote Thanks for posting! Just put up a PR to add Fortmatic Wallet =)
