### ISSUE TITLE
dTV

### ISSUE THREAD

**Issue by altinojoao** [ethereum/ethereum-org-website#2424]
Descentralized TV platform.
With channels from all the world.

**Comment by ryancreatescopy** [comment]
Hi @altinojoao this is the repo for the ethereum.org website. Although this sounds like a cool idea, it's not something we can help with. Maybe share it with a hackathon team and work on bringing it to life. Check back here regularly for upcoming hackathons: https://ethereum.org/en/community/#upcoming-events 

Closing this issue out
