### ISSUE TITLE
transaction canceled, commission charged

### ISSUE THREAD

**Issue by Yoker26** [ethereum/ethereum-org-website#2427]
**Describe the bug**
when making a purchase through a balancer, the transaction was canceled, but the commission was written off

https://etherscan.io/tx/0x5dffc6afbb9883f6cc033785d502f3ad87575a177b2e19d5f98042f0100da6bf
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ryancreatescopy** [comment]
Hi @Yoker26 this is the repo for the ethereum.org website. We can't help you. I think you'll want to raise an issue with the balancer team here: https://github.com/balancer-labs

Closing this issue out.
