### ISSUE TITLE
Requerimento de uma transação sem conversao, debitada da carteira tt, mais não não adicionada na carteira ethereum

### ISSUE THREAD

**Issue by WelliGodoi** [ethereum/ethereum-org-website#2429]
Requerimento, de um envio errado de thundercore tt, para ethereum, por favor gostaria que revessem a situação e devolvencem as minhas 400tt enviadas erradas sem conversao da moeda, 
![Screenshot_20210211-004723](https://user-images.githubusercontent.com/78008277/107771194-2b1f1780-6d19-11eb-9d91-2b1db9e29259.png)
![Screenshot_20210210-234741](https://user-images.githubusercontent.com/78008277/107771222-33775280-6d19-11eb-9628-e74101dfb045.png)
Como posso recorrer a isso, por favor me ajudem email de cadastro e para contato
wellingtons2angela@gmail.com
Desde já agradeco

**Comment by ryancreatescopy** [comment]
Hi @WelliGodoi this is the repo for the website: ethereum.org, an educational website about Ethereum. I'm afraid we can't help. I suggest you speak to the company behind the site/wallet you used to send the transaction. Closing this comment as we're unable to help further...
