### ISSUE TITLE
Javascript/other Wallet...?

### ISSUE THREAD

**Issue by darkwater4213** [ethereum/ethereum-org-website#2433]
Hey, I've been looking through the repositories at [Ethereum's "profile"](https://github.com/ethereum) and can't find any Eth1 (PoW) wallets built in Javascript or other more... universal languages. Can someone please reply with a complete list of all _official_ Eth1 wallets (preferably that also function as full nodes, or is that different software)? Thank you!

**Comment by ryancreatescopy** [comment]
Hey, thanks for your question.

There are no "official" wallets in the same way that there is no official implementation of Ethereum – no single repo of source code. Ethereum is deliberately language agnostic in this respect. 

To find an Ethereum web-based wallet, we suggest looking here: https://ethereum.org/en/wallets/

Wallet software is largely decoupled from client software at this stage. You can get more info on the clients here: https://ethereum.org/en/developers/docs/nodes-and-clients/

And if you want to explore Ethereum through a javascript lens more specifically, check out: 
- The ethereum javascript team's discord: https://discord.gg/4E7T8cgquk
- The ethereum.org page on javascript: https://ethereum.org/en/developers/docs/programming-languages/javascript/ – you might like to dig into EthereumJS (linked to from that page)

Hope that helps. Closing this issue out but feel free to reopen if you have any more questions! ✊

**Comment by darkwater4213** [comment]
Okay, cool. Thanks! One last question, though: are there any full-node/mining applications running the Eth1 protocol (the one that's still PoW) that also function as a full (preferably non-CLI) client, and/or vice versa? I'm kind of clueless in this regard...

**Comment by darkwater4213** [comment]
I suppose I should say why I want it... I'm making my own blockchain, very much like Ethereum, but with a slightly different (for lack of a better term) flavor to it. The idea behind the node/wallet combination is that you can simply leave the wallet application running (it would still auto-lock after twenty minutes, for obvious reasons) and it would automatically be PoW mining for the last address to successfully sign in on that instance of the wallet application. Make sense?
