### ISSUE TITLE
The explanation of codeHash could use some improvement

### ISSUE THREAD

**Issue by seishun** [ethereum/ethereum-org-website#2443]
https://ethereum.org/en/developers/docs/accounts/

> codeHash – All such code fragments are contained in the state database under their corresponding hashes for later retrieval. For contract accounts, this is the code that gets hashed and stored as the codeHash. For externally owned accounts, the codeHash field is the hash of the empty string.

What code fragments?

**Additional context**

It seems this paragraph was accidentally (?) decimated in https://github.com/ethereum/ethereum-org-website/commit/afaa877625aecfd84f696d8f2c2cc0b63f61242d.

**Comment by wackerow** [comment]
@seishun Thanks for dropping this feedback! Can take a look at this eventually, but in the meantime please feel free to open a PR if you have a suggestion on how to improve this, would be happy to consider any improvements =)
