### ISSUE TITLE
Clarify the status and planned future Proof of Stake change in the website documentation.

### ISSUE THREAD

**Issue by stuz5000** [ethereum/ethereum-org-website#2458]
As a noob, the documentation leaves me confused as to the status of the move to Proof of Stake.
Could the documentation be improved to clarify:
 - is proof of stake used in use in Etherenum?
 - has it/will it completely replace proof of work?
 - what's the difference between, ETH, ETH 2, ETH Classic? 
 - what are the timelines for the switch to PoS, deprecation of PoW.

---
There's a summary of consensus mechanisms here:

https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/#:~:text=Ethereum%20is%20moving%20to%20a,Ethereum%20via%20the%20Eth2%20upgrades.
https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/consensus-mechanisms/pos/index.md

"Ethereum **is moving to** a consensus mechanism called proof-of-stake (PoS) from proof-of-work (PoW)."
... is a little vague. As is:    https://ethereum.org/en/eth2/
I'm left confused about the status of Proof of Stake.

A lot of sources point to a Dec 2020 launch date. Again ... it begs the question, "will move", "is moving", "has moved?" to proof of stake.
https://www.techradar.com/news/ethereum-20-goes-live-next-month-heres-why-thats-a-huge-deal

**Comment by samajammin** [comment]
Great questions!

**Comment by samajammin** [comment]
@all-contributors please add @stuz5000 for ideas.
