### ISSUE TITLE
Adding Linen App wallet

### ISSUE THREAD

**Issue by frostiq** [ethereum/ethereum-org-website#2459]
### **Is your wallet globally accessible?**

Yes. iOS version has full functionality, Android version - limited functionality at the moment.

### **Is your wallet custodial, non-custodial, or a hardware wallet?**

Linen Wallet is a non-custodial smart-contract wallet and users have access to 2 of 3 private keys.

If our infrastructure is not operational, users will be able to access their funds with 2 of 3 private keys that they possess.

More details about Linen Wallet and private key scheme can be found here: [Linen Wallet Premier](https://linen.app/articles/crypto-assets-self-custody-linen-wallet-primer)

### **Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Linen Wallet is based on Gnosis Safe multisig smart contracts: [https://gnosis-safe.io](https://gnosis-safe.io/)

Security audit: [https://gnosis-safe.io/security](https://gnosis-safe.io/security)

The mobile app undergoes a continuous security audit by our team.

### **Does the wallet have fiat on-ramps?**

Fiat on-ramps are available for U.S. residents in most states by [Wyre](https://www.sendwyre.com). Deposit and withdrawal fees are partially subsidized.

### **Does the wallet allow users to explore dapps?**

Not for now. WalletConnect will be available in future versions.

### **Does the wallet have integrated defi/financial tools?**

The wallet is built for DeFi. Users can earn interest on [Compound](https://compound.finance). More DeFi integrations and use cases are coming.

### **Can a user withdraw to their card?**

Withdrawal to debit cards is not available.

### **Does the wallet offer limits protection?**

Not now, but is planned in future releases.

### **Does the wallet allow high-volume purchases?**

Yes, a user can purchase up to $5000 worth of certain crypto assets per week.

### **Does the wallet have an integrated token swap?**

Not now, but is planned in future releases.

### **Is the wallet a multi-signature wallet?**

Yes, Linen Wallet requires 2 of 3 signatures to initiate a transaction. Both signatures are done by a single person - wallet owner.

### **Wallet title**

Linen App

### **Wallet description**

Mobile smart contract wallet: earn yield, buy crypto, and participate in DeFi. Earn rewards and governance tokens. 

### **Wallet logo**

![Linen Logo](https://cdn.linen.app/img/linen-logo-simple.svg)

### **Brand color**

#08CDC7

Feel free to check out Linen App on [AppStore](https://apps.apple.com/app/apple-store/id1480509067) and [Google Play](https://play.google.com/store/apps/details?id=com.linenapp.android)
Please reach out to us for more details: hello@linen.app

**Comment by wackerow** [comment]
@GeorgeTrotter ping

**Comment by GeorgeTrotter** [comment]
@wackerow all set here!
