### ISSUE TITLE
Pre-filter and anchor links

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2465]
As a content creator I want to link users to a pre-filtered section that exists halfway down a page so that I can link users to the exact content I want them to see.

For example, on a page that discusses NFTs I should be able to link users to the `/#explore` section of the dapps page with the collectibles option pre-filtered. This way users can see the NFT dapps immediately upon navigating. 

Current behaviour pre-filters the page but gives the user no context as to what is pre-filtered.

**Comment by samajammin** [comment]
E.g. URL: https://ethereum.org/en/dapps/?category=collectibles/#explore

The category URL param shouldn't break the anchor link
