### ISSUE TITLE
To add TradeTrust to the list of application in the enterprise page

### ISSUE THREAD

**Issue by cavacado** [ethereum/ethereum-org-website#2473]
**Is your feature request related to a problem? Please describe.**

Request to add [TradeTrust](https://www.tradetrust.io/) to the list of applications in [this](https://ethereum.org/en/enterprise/) page under the supply chain section

**Describe the solution you'd like**

assign the issue to me to make the edit, or add this particular line to the supply chain [section](https://ethereum.org/en/enterprise/#supply-chain) in the enterprise page:
- [TradeTrust](https://www.tradetrust.io/) _is a digital utility that comprises a set of globally-accepted standards and frameworks that connects governments and businesses to a public blockchain to enable trusted interoperability and exchanges of electronic trade documents across digital platforms._ 

**Describe alternatives you've considered**

NA

**Additional context**

Since our team has an entry in the list (OpenCerts) in this [section](https://ethereum.org/en/enterprise/#supply-chain), would like to put our other product on this list as well.

**Comment by samajammin** [comment]
Hey @cavacado - thanks for the suggestion!

@tasdienes could you please take a look at this when able?

**Comment by tasdienes** [comment]
Makes sense to include TradeTrust.  But I think we need a simpler, clearer, and more concrete explanation of what it does with respect to Ethereum.  Is this accurate?

"TradeTrust creates attestations about electronic trade documents, and tokenizes transferrable trade records on Ethereum."

Also, curious if you guys are working on putting this on L2?

**Comment by cavacado** [comment]
Hey @tasdienes, let me get back to you on the proposed summarised description, i'll need to check with my team's communications channel to make the decision.

For your second question on whether we are working on putting this on L2, we currently have no plans now, but it might be a direction to explore in the near future.

**Comment by cavacado** [comment]
Hey @tasdienes , my team's communications channel does not think that the summary adequately captures what our product is actually doing, so they prefer to stick to the first description provided.

I hope that you would understand.

**Comment by tasdienes** [comment]
Hi @cavacado, 

I re-read the marketing description, and to be honest, I find it vague and unclear.  I really don't have any understanding of exactly, practically what the product does after reading it, and how it interacts with Ethereum.  I have tried to keep the content on this page very factual and concrete, without any marketing jargon. More like Wikipedia, and less like an advertisement.  

My suggested text was based on what I read on your web site.  If it doesn't fully capture the product, please feel free to improve it. But please try to keep the style consistent with what we are aiming for on this page.

**Comment by samajammin** [comment]
I agree with @tasdienes. The description you provided is quite a mouthful & full of jargon.

@cavacado assigning this to you - feel free to create a PR but please try to simplify the language.

**Comment by cavacado** [comment]
hey @tasdienes @samajammin ,

nope I fully understand your concerns. I'll push to get the more concise description through to my other stakeholders, but if I don't achieve it, I'll probably close the issue without doing anything.

Once again, thank you for taking the time to look at this request.

**Comment by jley81** [comment]
I don't know what to do

**Comment by jley81** [comment]
Great. Then I approve Trade Trust.

**Comment by ryancreatescopy** [comment]
Closing this out while pruning the backlog. @cavacado feel free to reopen if your stakeholders get on board with a more concise description.
