### ISSUE TITLE
Remove redundant returns

### ISSUE THREAD

**Issue by Kristiyan96** [ethereum/ethereum-org-website#2477]
**Is your feature request related to a problem? Please describe.**
In response to:

_Agreed, these are scattered throughout the codebase and could be cleaned up in batch in a separate issue. I'll push the syntax fix here though while we're looking at it._

_Originally posted by @wackerow in https://github.com/ethereum/ethereum-org-website/pull/2389#discussion_r574854548_

**Describe the bug**

There are several places in the code where the following simplifications can be done:

1. Remove unnecessary return in map
`      {crumbs.map((crumb, idx) => {
          return (
              <>...</>
          )
        }
`
becomes 
`      {crumbs.map((crumb, idx) => (<>...</>)}
`
2. Remove unnecessary return when rendering a component
`
const BugBountyCards = () => {
  return (
    <CardRow> </CardRow>
  )
}
`
becomes
`
const BugBountyCards = () => (<CardRow> </CardRow>);
`

The benefits are:

- Fewer words used
- Saves indentation spaces and improves readability
- Less vertical space while maintaining readability

**Comment by wackerow** [comment]
@Kristiyan96 Hey thanks for creating an issue for this =) Obviously agree that cleaning up the syntax in these cases is preferred, and to help keep things consistent and up to date. 

If you'd like to be assigned just reply back, would welcome a PR addressing this =) Otherwise no worries, I can take care of this on a lower priority basis.

**Comment by howdyAnkit** [comment]
Can I try this? @wackerow. Please assign me if  it's free.

**Comment by Kristiyan96** [comment]
@wackerow thanks! I have already started on it in [this branch](https://github.com/Kristiyan96/ethereum-org-website/tree/remove_redundant_returns)
