### ISSUE TITLE
Create "Ethereum grants" page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2479]
**Is your feature request related to a problem? Please describe.**

There's various EF & community grant programs throughout the ecosystem but they're not always easy to find.

**Describe the solution you'd like**

Let's create a subpage of the [Community page](https://ethereum.org/en/community/) (e.g. https://ethereum.org/en/community/grants/) to list active grant programs.

**Describe alternatives you've considered**

Add this as a section within the Community page?

**Additional context**

Potential grant programs to list:
- https://esp.ethereum.foundation/en/grants/
- https://consensys.net/grants/
- https://www.metacartel.org/grants
- https://gitcoin.co/grants/

**Comment by samajammin** [comment]
A larger list (thanks @catsnackattack):

- EF Ecosystem Support Program: https://esp.ethereum.foundation
- Consensys grants: https://consensys.net/grants/
- Gitcoin grants: https://gitcoin.co/grants
- MetaCartel: https://www.metacartel.org/
- clr.fund: https://clr.fund/
- Moloch DAO: https://www.molochdao.com/
- KERNEL (teams): https://gitcoin.typeform.com/to/wgZn4U
- KERNEL (individuals): https://gitcoin.typeform.com/to/xBx2lL
- Uniswap https://airtable.com/shrEXXxXB1humz7VS
- TheGraph: https://airtable.com/shreX09LazIhsg0bU
- Open Grants: https://opengrants.com/explore
- UNICEF CryptoFund: https://cryptofund.unicef.io/about
- Maker Grants: https://grants.makerdao.com/

**Comment by ipapandinas** [comment]
Hi @samajammin 👋
I would be happy to help on this feature. If you would like, you can assign it to me.

**Comment by samajammin** [comment]
Solved in #2510 - thanks again @ipapandinas!

**Comment by samajammin** [comment]
@all-contributors please add @ipapandinas for content.
