### ISSUE TITLE
Issue with Discord Group Invite

### ISSUE THREAD

**Issue by YussufElarif** [ethereum/ethereum-org-website#2485]
**Describe the bug**
I'm following a tutorial and there is a discord invite. I click to join and it mentions that the invite is invalid.

**To Reproduce**
Link to tutorial: https://ethereum.org/en/developers/tutorials/sending-transactions-using-web3-and-alchemy/#what-is-the-web3-library

**Expected behavior**
Being able to join the discord group

**Screenshots**
![image](https://user-images.githubusercontent.com/9627828/109112697-f8bae480-7732-11eb-9e5b-3b68ca791f60.png)

**Comment by ryancreatescopy** [comment]
@elanh any chance you could confirm the correct discord link?

**Comment by elanh** [comment]
Sorry about that -- try this one https://discord.gg/gWuC7zB

**Comment by vemuez** [comment]
Thanks, that invite works. You can edit the server link expiration time to "never". Not sure how long that invite lasts for but I got in :)!

**Comment by samajammin** [comment]
Thanks @elanh! Is that link set to never expire? If so, we can make that update in the tutorial & close this out.

**Comment by samajammin** [comment]
@all-contributors please add @vemuez for bug reports.

**Comment by elanh** [comment]
Yup! @samajammin that link should be set to never expir!
