### ISSUE TITLE
Audit ETH exchanges list

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2487]
**Describe the bug**

Was looking into solving a user question receive by email and it appears that we don't correctly list exchanges for the USA. For example, Gemini isn't listed when it has one of the best coverages for US users. On closer inspection it's even down as false in the data file. This makes me concerned that the CSV was copy/pasted badly. We should double check the information we are providing is correct.

**Comment by samajammin** [comment]
Hmmm yes a bit concerning.

What makes you think it was a copy/paste issue? Looking at the [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1B1H5y6b3DOYfY3M_JgLX6hltnwEQre3PYcbC73QUCFE/edit#gid=1076953224), it also lists Gemini as `FALSE` for USA.

I'd definitely support an audit of the data to ensure this is correct & up to date!

In the meantime I'll update Gemini.

**Comment by samajammin** [comment]
@ryancreatescopy I added Gemini in #2488. Re-opening this issue in case we want to explore how to audit entire dataset.

**Comment by MrBrain295** [comment]
This looks like it’s part of #3908

**Comment by minimalsm** [comment]
@MrBrain295 hey :) with this issue, we're looking to audit the exchanges (like Coinbase or Binance) that we list on ethereum.org to ensure they cover the countries and regions that we claim on ethereum.org. Bit of a tricky one that we're trying to scope out.

**Comment by minimalsm** [comment]
We are going to close this issue for now to either

- Find a way to enable contributors to  meaningfully contribute to this
- Prioritize it for an ethereum.org team member as a task
