### ISSUE TITLE
Support language versioning on a page-by-page basis

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2490]
**Is your feature request related to a problem? Please describe.**

Currently our content versioning of translations is applied at the language level:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/translations.json
i.e. our logic treats all pages of a given language as the same version

**Describe the solution you'd like**

We want to get to a world where we can assign content versions at the page level. This would allow us to add updated files to the codebase as soon as they are translated (vs. waiting for the entire content version to be translated in Crowdin).

As an example, the [Spanish Developers page](https://ethereum.org/es/developers/) might be on v2.0 while the [Spanish homepage](https://ethereum.org/es/) might be on v2.4.

Not yet sure how we want to implement this. I suspect in gatsby-node.js we'll want to add some logic that assigns a content version property to every page we create.

**Comment by minimalsm** [comment]
Does this need to be an issue anymore? 

My understanding is that with the content bucket refactor the codebase now supports page by page translations and we just don't have correct processes in place to do page by page properly.

**Comment by minimalsm** [comment]
Solved in #4441
