### ISSUE TITLE
Add Coinomi

### ISSUE THREAD

**Issue by moodmosaic** [ethereum/ethereum-org-website#2539]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

yes

**Is your wallet custodial, non-custodial, or a hardware wallet?**

non-custodial

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Strong AES-256 encryption, biometric locks, private keys are always stored inside Trusted Execution Environment (TEE) or Secure Element (SE) and never exposed out of it, the encryption key authentication is always enforced by TEE or SE. Coinomi has been around for more than 7 years and no wallet has ever been hacked.

**Does the wallet have fiat on-ramps?**

yes, also for ETH

**Does the wallet allow users to explore dapps?**

yes, unlimited dapp access

**Does the wallet have integrated defi/financial tools?**

yes

**Can a user withdraw to their card?**

no

**Does the wallet offer limits protection?**

no

**Does the wallet allow high-volume purchases?**

yes

**Does the wallet have an integrated token swap?**

yes

**Is the wallet a multi-signature wallet?**

no

**Wallet title**

Coinomi 

**Wallet description**

Coinomi is the oldest multi-chain, defi-ready, cross-platform wallet for bitcoin, altcoins & tokens - never hacked, with millions of users.

**Wallet logo**

https://www.coinomi.com/svg/coinomi-logo-color.svg

**Brand color**

#11b8ef

**Comment by GeorgeTrotter** [comment]
@wackerow this too!
