### ISSUE TITLE
NFT page width on mobile

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2553]
**Describe the bug**

Width of the page overflows on mobile. 

Safari on iPhone X
![image](https://user-images.githubusercontent.com/8097623/110225450-8b2d5780-7e9a-11eb-97a0-00f54fd8ceba.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NilsKaden** [comment]
The same issue also occurs on the following pages:
https://ethereum.org/en/defi/
https://ethereum.org/en/dao/

Please assign this issue to me :)
