### ISSUE TITLE
Unhelpful token standards documentation titles

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2556]
**Describe the bug**

Token standards documentation titles should explain the type of token rather than the technical name. People new to the space don't know their erc-20 from their erc-721. But something like currency and unique assets might be clearer. 

This is also the case on the token standards page where we link to the individual standards. We don't provide explanations and expect users to know what the different standards are already.

![image](https://user-images.githubusercontent.com/40891631/110247782-d2344f00-7f65-11eb-929c-d04e7f0c59ad.png)
![image](https://user-images.githubusercontent.com/40891631/110247851-348d4f80-7f66-11eb-97bc-2ab4549a2721.png)

**Comment by samajammin** [comment]
Potential menu titles
- `ERC-20: Fungible Tokens`
- `ERC-732: NFTs`
