### ISSUE TITLE
Like this picture 

### ISSUE THREAD

**Issue by KunKaxx** [ethereum/ethereum-org-website#2568]
![1D640CEA-5040-43BA-B5E2-FCD0A5ED14BB](https://user-images.githubusercontent.com/61171961/110356740-2413cc80-806d-11eb-8150-79737e59aab2.jpeg)
![7F44B95C-97ED-4149-B9D6-7D6229EEEC1A](https://user-images.githubusercontent.com/61171961/110356760-2a09ad80-806d-11eb-9303-fdf9051018a6.jpeg)
![6B7B354E-806B-466D-A951-D66F3A25FAB2](https://user-images.githubusercontent.com/61171961/110356765-2b3ada80-806d-11eb-91d7-5d01f970d3ff.jpeg)

Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

**Is your wallet custodial, non-custodial, or a hardware wallet?**

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

**Does the wallet have fiat on-ramps?**

**Does the wallet allow users to explore dapps?**

**Does the wallet have integrated defi/financial tools?**

**Can a user withdraw to their card?**

**Does the wallet offer limits protection?**

**Does the wallet allow high-volume purchases?**

**Does the wallet have an integrated token swap?**

**Is the wallet a multi-signature wallet?**

**Wallet title**

**Wallet description**

**Wallet logo**

**Brand color**

*Importante*i don’t have money^^

**Comment by samajammin** [comment]
?
