### ISSUE TITLE
Retire / update staking banner?

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2569]
**Is your feature request related to a problem? Please describe.**

Now that staking has been live for a few months, perhaps it's time to rethink our banner across Eth2 pages:

![Image 2021-03-08 at 11 42 18 AM](https://user-images.githubusercontent.com/8097623/110372823-a071c580-8003-11eb-8a33-f7c11972813d.jpg)

> Staking has arrived! If you're looking to stake your ETH, confirm the deposit contract address.

**Describe the solution you'd like**

Remove the banner.

**Describe alternatives you've considered**

We could update the banner text, e.g. to learn more about staking by linking to the Staking page if user is not on it. I don't think checking the deposit contract address should be the primary action at this point given how well established it is.

**Comment by samajammin** [comment]
@ryancreatescopy @wackerow curious for your thoughts on this.

**Comment by wackerow** [comment]
Yeah may be time to refactor this. A link to staking page sounds like a better idea at this point. Having the contract address available is nice, but agreed it doesn't need to be a primary action at this point.

**Comment by ryancreatescopy** [comment]
I think we can remove. We shouldn't use this type of banner for just linking to the staking page IMO. There for timely notifications, e.g. "staking is now live" or "this page needs some edits". We can use the hero area or dedicated areas on the page to link to the staking stuff in my opinion...
