### ISSUE TITLE
Vertical height bug – use-case and eth2 template 

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2583]
**Describe the bug**

On certain screen sizes, the left-hand column with the table of contents isn't scrollable. If a list goes beyond the view port it's impossible to navigate to the sections below the viewport until the main content has scrolled to the footer. 

**Expected behavior**

If the table of contents doesn't fit due to vertical height, it should be scrollable so that users can select all items in the table of contents.

**Screenshots**

https://user-images.githubusercontent.com/40891631/110489524-5f52e180-80e7-11eb-91ca-7459453a38e5.mov

**Comment by NilsKaden** [comment]
@wackerow did you start working on this already? I can have a look at this if you like :)

**Comment by wackerow** [comment]
@NilsKaden Thanks for offering to help on this! Please don't hesitate to ask us any questions along the way 🙂 Assigning you (just let us know if you change your mind in the future)
