### ISSUE TITLE
Absolute reference for both Intl and English MDX images

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2585]
**Describe the bug**

We recently added our first translations of tutorials (#2531) 🎉  but we are not properly referencing assets.

**To Reproduce**

1. Go to https://ethereum.org/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/
2. See 404s in console from failed image fetches

**Expected behavior**

Images should work!

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**

A couple approaches I see here, neither which I like
- A) Copy over the images from English tutorial directories into translations
- B) Update the relative path of image files in translation tutorials to point to English images
- C) Refactor our file structure to have all markdown in the same directory

I think a better solution might be to 
- D) Find a plugin / configure a way to have all relative image references in markdown files start from the same absolute reference, e.g. so anywhere in the project we could use
```
![Some image alt text](./some-image.png)
``` 
Then our project would know that actually references `/src/assets/some-image.png`. I'm not sure how to accomplish that yet but that would save us time from manually copying files / updating relative image references.

More context on C) approach here:
https://github.com/gatsbyjs/gatsby/discussions/30244#discussioncomment-482912

**Comment by samajammin** [comment]
Offline discussion: approach C) seems to be our best bet here.

**Comment by minimalsm** [comment]
@samajammin 

Until this is solved I believe we're blocked on the CrowdIn to Github automation?

**Comment by samajammin** [comment]
Depends on the implementation but I don't think this should impact the GH <> Crowdin integration at all. Particularly if we can implement option D.

**Comment by samajammin** [comment]
For the record we are currently go with approach B (manually updated image paths of translated files) to solve this (which is NOT ideal).

**Comment by pettinarip** [comment]
Might be worth to look at https://www.gatsbyjs.com/plugins/gatsby-plugin-module-resolver/ where we could start by the basic resolution of `src`:

```ts
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-module-resolver',
      options: {
        root: './src',
      }
    }
  ]
}
```

Note: I don't know if this is going to work from inside the md files, this is something to test.

**Comment by corwintines** [comment]
While we dont do absolute paths, we have a script made to resolve these issues
