### ISSUE TITLE
Support currency filter on Get ETH page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2587]
**Is your feature request related to a problem? Please describe.**

Currently users can filter exchanges / wallets by country where they can onboard fiat to get ETH but there's no ability to filter by fiat currency support. For instance, I can't view exchanges that support British pounds / Mexican pesos.

**Describe the solution you'd like**

Provide an additional data source similar to our country CSV:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/exchanges-by-country.csv

Add UI feature to allow filtering by currency (TODO need to define which currencies we support).

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by IliadisVictor** [comment]
Hello , ! i think i could tackle this  , could you please assign me when you have the time ? @samajammin
