### ISSUE TITLE
ETH2 updates

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2629]
With the merge potentially happening sooner than expected, we should update our eth2 resources to reflect the new reality...

https://github.com/ethereum/eth2.0-specs/pull/2229

- [x] confirm that the merge will happen before sharding (cc @djrtwo )
- [x] fix order of eth2 action cards
- [x] fix order in eth2 template drop down 
- [x] scour content for anywhere we discuss order (I'm not sure we do but we should check. Shards aren't a prerequisite for the merge clearly!)
- [x] update language from "docking" to "the merge"
- [ ] update roadmap diagram to reflect new reality
- [ ] add latest articles from Danny and Ben
- [ ] add banner that explains that info has changed!

**Comment by ryancreatescopy** [comment]
We should also consider adding more support for stakers, now that the system and community is larger. There are lots of answers on launchpad so maybe it's a case of developing the content there and making sure we have proper links to it from ethereum.org.

**Comment by wackerow** [comment]
If anyone in the community has some design skills and any ideas for how to graphically demonstrate the new rollup-centric roadmap (with the merge occurring before sharding, and layer 2 rollups going live separately as we speak), would encourage you to jump into [our discord server](https://discord.gg/CetY6Y4) to discuss some ideas.

**Comment by samajammin** [comment]
@minimalsm @wackerow - closing this out. It's not very specific what further actions are needed. There's more Eth2 updates needed for sure but I think we can create better scoped issues as needed in the coming weeks.
