### ISSUE TITLE
h2s on homepage have inconsistent font

### ISSUE THREAD

**Issue by jordanoverbye** [ethereum/ethereum-org-website#2636]
**Describe the bug**

The `h2` elements on the homepage have a font applied `"serif"` which is not used anywhere else on the site.

<img width="571" alt="Screen Shot 2021-03-15 at 8 12 34 pm" src="https://user-images.githubusercontent.com/6265154/111137702-d64a1780-85ca-11eb-8c72-51fc38ee70ce.png">

**To Reproduce**

1. Go to `https://ethereum.org/`
2. Scroll down to first content section

**Comment by samajammin** [comment]
Thanks for the issues (& PR) @jordanoverbye! I believe this styling was intentional - @ryancreatescopy can you please confirm?

Even if so, good to collect feedback on it, so thanks again for raising this.

**Comment by jordanoverbye** [comment]
@samajammin thanks for your comment. If it was intentional, maybe we could add it other parts of the website?

**Comment by wackerow** [comment]
@ryancreatescopy Not sure if you had intent to use this styling elsewhere at this point. If so sounds like we could create a separate issue and assign @jordanoverbye ... in the meantime will close this issue, but can always reopen if needed =)
