### ISSUE TITLE
ToiletCoin 

### ISSUE THREAD

**Issue by Hunters284** [ethereum/ethereum-org-website#2644]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible** The dapps security is taken with the Ethereum network.

 https://toiletcoin2.godaddysites.com/

**Is your dapp open source?** Yes

 Yes.

**Can a user access the dapp without creating an account?** Yes.

 Yes.

**Are dapp funds non-custodial?** Yes.

 Yes, users can access their funds anytime.

**Do you offer community support?** Yes, we do.

 Unfortunately, we don't have a Discord server.

**Describe any geographical restrictions on usage of your dapp** We don't restrict users as long as they follow our guidelines.

 Yes, it is globally accessible.

**Dapp title** ToiletCoin 

 ToiletCoin Official 

**Dapp description** ToiletCoin is an Ethereum token that aims to create a unique connection between all cryptocurrencies. You can also visit the ToiletCoin 
website and purchase TLT to earn rewards.

 ToiletCoin is a token that's goal is to reach out to other cryptocurrencies and help build onto them.

**Dapp logo** 

 https://pngimg.com/image/17753

**Brand color** Gold

 #FFD700

**Comment by ryancreatescopy** [comment]
This link doesn't work. We can't assess this and I'm a little skeptical considering the name 🤔 . Closing out for now, but re-open if there's a link that works.
