### ISSUE TITLE
improve keyboard accessibility (a11y)

### ISSUE THREAD

**Issue by jordanoverbye** [ethereum/ethereum-org-website#2648]
**Describe the bug**

I have noticed a few issues when trying to navigate this website using only a keyboard. 

<s>1. A few interactive elements (such as the theme toggle button) are either not focusable or do not have any focus styles applied</s> Fixed in #2649

2. The mobile navigation doesn't have `display: none` applied and therefor is rendered in the accessibility tree. This means a keyboard user has to tab through all of these hidden nav items before reaching any content.

**To Reproduce**

1. Go to `https://ethereum.org/en/`
2. Try navigating the site with just using a keyboard

**Expected behavior**

- Each interactive element on the page should have a clear focus state.
- The mobile menu should not appear in the accessibility tree when on desktop, and the desktop menu shouldn't be in the accessibility tree on mobile.

**Comment by wackerow** [comment]
@jordanoverbye Were there any other key places you were planning on working on, or where you noticed could use work?

**Comment by jordanoverbye** [comment]
I haven't noticed anything else, so this could issue could probably be closed.

**Comment by wackerow** [comment]
@jordanoverbye Sounds good, feel free to surface anything else you find in another issue 👍

**Comment by samajammin** [comment]
Thanks @jordanlyall! Appreciate the report & PRs 💪

**Comment by samajammin** [comment]
@all-contributors please add @jordanoverbye for bug reports & code.
