### ISSUE TITLE
Kazakh Translation 

### ISSUE THREAD

**Issue by AIKO7772011** [ethereum/ethereum-org-website#2674]
Dear All,

I'd like to suggest you to translate into Kazakh language all Ethereum technical documents. Can you please open issue about Kazakh translation. 

Thank you,
Best regards,
A.

**Comment by AIKO7772011** [comment]
And can you please provide a little bit step by step instruction how to do it or where to start it to do translate the tech docs.

thank you

**Comment by AIKO7772011** [comment]
If I did anything wrong just show me right steps

thank you in advance

**Comment by AIKO7772011** [comment]
Добрый день Всем!

Хочу предложить открыть тикет для перевода техдокументацию на Казахский язык. Поэтому прошу открыть ссылку или раздел на Казахском языке. (https://ethereum.org/en/contributing/translation-program/)

**Comment by sorumfactory** [comment]
@AIKO7772011 Hey there, thank you for suggesting adding the Kazakh language to Ethereum.org. Sorry for my late response to your request! Kazakh is now available on Crowdin:[]( https://crowdin.com/project/ethereumfoundation/kk#)
Please feel free to explore and let me know if you face any challenges along the way! 
Again, we appreciate your sincere interest in supporting Kazakh speaking community.

**Comment by sorumfactory** [comment]
> If I did anything wrong just show me right steps
> 
> thank you in advance

As for your

**Comment by sorumfactory** [comment]
> And can you please provide a little bit step by step instruction how to do it or where to start it to do translate the tech docs.
> 
> thank you
As for the instructions, you can refer to the links below that will explain how to start participating in the program and some basic FAQs for using Crowdin.

- [https://ethereum.org/en/contributing/translation-program/](https://ethereum.org/en/contributing/translation-program/)

- [https://ethereum.org/en/contributing/translation-program/translation-guide/
](https://ethereum.org/en/contributing/translation-program/translation-guide/
)
 If you have more questions, feel free to join our Discord group and ask at the _Translations_channel where you can get direct support from us! 

- [https://discord.gg/CwCt9rPV](https://discord.gg/CwCt9rPV)
