### ISSUE TITLE
Infinite request made to CoinGecko API endpoints

### ISSUE THREAD

**Issue by tmlee** [ethereum/ethereum-org-website#2676]
**Describe the bug**
Co-founder at CoinGecko here, it is great to see Ethereum.org using the CoinGecko API to power pricing pages
But I am also noticing a bug that it is making infinite requests to the API which is in a way of waste of bandwidth on our end for the free API that we are providing. I don't supposed that is intended.

**To Reproduce**
1. I dont know if any other pages are impacted, but visit https://ethereum.org/en/stablecoins/
2. Open network inspector 
3. You will see an infinite requests is being made to the API

**Expected behavior**
API should be made once or only sufficient to display the value rather than calling it in a loop

**Screenshots**

https://user-images.githubusercontent.com/110264/111655179-63e46c00-8844-11eb-9abe-a17ba0d945da.mov

**Desktop (please complete the following information):**
Tested on
- OS: Mac
- Chrome
- 89.0.4389.82

but should be applicable across browsers

**Comment by wackerow** [comment]
@tmlee Thank you so much for reporting this (and of course for providing this service to begin with!). Definitely not intended, and will work to address this right away.

**Comment by samajammin** [comment]
Yes thanks for the report @tmlee! We've fixed the issue (thanks @wackerow) & added caching to help reduce the load. Will deploy the fix shortly.

**Comment by samajammin** [comment]
BTW @tmlee - any timeline to support `stablecoins` as a market category in your API 😄 ? Would be great to have.
https://twitter.com/samonchain/status/1335999786865070081?s=20

Appreciate your free API in the meantime! Thanks for all you do for the community.

**Comment by samajammin** [comment]
@all-contributors please add @tmlee for bug reports.

**Comment by tmlee** [comment]
> Yes thanks for the report @tmlee! We've fixed the issue (thanks @wackerow) & added caching to help reduce the load. Will deploy the fix shortly.

Thanks for the quick turnaround @samajammin @wackerow really appreciate that! 

> BTW @tmlee - any timeline to support `stablecoins` as a market category in your API 😄 ? Would be great to have.
> https://twitter.com/samonchain/status/1335999786865070081?s=20
> 
> Appreciate your free API in the meantime! Thanks for all you do for the community.

That's a good feedback, I will see how we can have that supported soon. Will let you know here when it is up and running.
Feel free to let me know if there is anything else that you all need.

**Comment by tmlee** [comment]
> BTW @tmlee - any timeline to support `stablecoins` as a market category in your API 😄 ? Would be great to have.
> https://twitter.com/samonchain/status/1335999786865070081?s=20
> 
> Appreciate your free API in the meantime! Thanks for all you do for the community.

Hi @samajammin , just a quick update that you can do this now with the following endpoint https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&category=stablecoins&order=market_cap_desc&per_page=100&page=1&sparkline=false

Let me know what you think!
