### ISSUE TITLE
Broken link on Ethereum for Rust Developers page

### ISSUE THREAD

**Issue by rabbitXIII** [ethereum/ethereum-org-website#2682]
**Describe the bug**

The link on the Ethereum for Rust Developers page - "Sending Transaction to Ethereum Using Rust" 
url: https://kauri.io/article/97c85229c66445759bb0ce642224d364/sending-ethereum-transactions-with-rust
directs the user to a 404.

**To Reproduce**
1. Go to https://ethereum.org/en/developers/docs/programming-languages/rust/
2. Click on "Sending Transaction to Ethereum Using Rust"

**Expected behavior**

Navigate to the correct article

**Screenshots**

![image](https://user-images.githubusercontent.com/1820619/111685967-c22e3200-87e5-11eb-8f62-9e0c8fbc640c.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Browser: Firefox
- Version: 86.0.1 (64-bit)

**Additional context**

https://github.com/kauri-io/archive/

**Comment by rabbitXIII** [comment]
I found a new link for the same article hosted by kauri. I can send a PR with the fixed line

https://kauri.io/#collections/A%20Hackathon%20Survival%20Guide/sending-ethereum-transactions-with-rust/

**Comment by wackerow** [comment]
@rabbitXIII Please do =) Just assigned you, thanks for helping!

**Comment by wackerow** [comment]
@all-contributors please add @rabbitXIII for bug report

**Comment by wackerow** [comment]
(Closed in #2729)
