### ISSUE TITLE
JSON RPC API client list is outdated

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2687]
**Describe the bug**

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/apis/json-rpc/#json-rpc-support
2. See client list

**Expected behavior**

Update the client list to match https://ethereum.org/en/developers/docs/nodes-and-clients/#clients

**Context**

Reported here: https://discord.com/channels/595666850260713488/804019759934078987/821863439822487583

**Comment by ZackDeRose** [comment]
Is this still an issue? Looks like there is now a link to the `CLIENTS` section referrenced in the *Expected Behavior* section.

![Screen Shot 2021-04-26 at 10 37 59 PM](https://user-images.githubusercontent.com/3788405/116190912-49719e00-a6e0-11eb-9587-349e99b3e09b.png)
