### ISSUE TITLE
Ethereum State Transition Graphical Explanation - Whitepaper

### ISSUE THREAD

**Issue by SatoshiMiracle** [ethereum/ethereum-org-website#2691]
On the Ethereum website, in the whitepaper, there is a section with a graphical explanation about the State Transition Function, I think there is a small typo there.

In the middle section, titled Transaction, the sender happens to be address "14c5f88a", while in State and State' there is no such account, but there is another account with a similar address, "14c5f8ba", who was the one debited for the transaction.

It is a small typo, but for quality purposes it should be fixed. The attached PNG shows how it should be, not sure if it's compatible with the website's dark mode though.
![Untitled design_2x](https://user-images.githubusercontent.com/72975337/111845526-b3db3580-890d-11eb-8949-4e622747ad62.png)

**Comment by wackerow** [comment]
@SatoshiMiracle Good eye! hah, I suppose that would've been my typo when re-creating those PNGs, and I shall fix =)

**Comment by wackerow** [comment]
@all-contributors please add @SatoshiMiracle for bug reports
