### ISSUE TITLE
Add info on reducing gas costs

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2699]
**Is your feature request related to a problem? Please describe.**

We get lots of questions in our Discord about gas fees, why they're high & how to avoid them.

**Describe the solution you'd like**

We should add sections to https://ethereum.org/en/developers/docs/gas/
- Explain why gas fees get high (i.e. high demand for the network)
- Explain initiatives in progress (e.g. Eth2, L2) that are working to reduce gas costs
- Explain strategies users can use to reduce gas costs (e.g. tools to monitor gas prices)
- Explain approaches as a dapp developer you can do to reduce gas usage of smart contracts (e.g. assembly code optimization)

...or at least link to resources that explain these

**Comment by wackerow** [comment]
https://www.youtube.com/watch?v=Yh8cHUB-KoU
(Suggestion)

**Comment by DevAranCarter** [comment]
Hey guys I took a crack at wring the description! It can be found here: [https://github.com/ethereum/ethereum-org-website/pull/2903](url)

**Comment by wackerow** [comment]
Closed with #2903
