### ISSUE TITLE
Add a 'good-first-issue' tag for new contributors

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2704]
**Is your feature request related to a problem? Please describe.**

Github adds a nice callout on [our issues page](https://github.com/ethereum/ethereum-org-website/issues):
![Image 2021-03-22 at 1 20 17 PM](https://user-images.githubusercontent.com/8097623/112053283-64655700-8b11-11eb-9057-c4737442631d.jpg)

**Describe the solution you'd like**
We should add & use this tag to surface good first issues for potential contributors.

**Comment by wackerow** [comment]
@samajammin I did make this tag, but after reviewing the existing issues it doesn't seem to apply to any of them. Keeping an eye on this going forward, and will try to apply.

**Comment by samajammin** [comment]
Thanks @wackerow!

I went through & tagged 10 I think are good first issues. LMK if you disagree with any:
https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Counting this as solved!
