### ISSUE TITLE
Add rotki, the only opensource portfolio tracking and accounting tool that protects user privacy.

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/ethereum-org-website#2711]
**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

Rotki is a local application. We are a portfolio tracking and accounting tool. Security-wise we keep all user data locally in the user's system so there is no possibility of data leaking. Additionally, at the point of writing, we do not handle any user keys.

**Is your dapp open source?**

Oh most definitely yes: https://github.com/rotki/rotki

**Can a user access the dapp without creating an account?**

They create a local account in their system. It's like creating an ethereum address. It's essentially a password protected and encrypted sqlcipher database. We also want to allow encrypting it with an ethereum address, but then we get into the field of managing user keys which we would like to avoid unless absolutely necessary.

**Are dapp funds non-custodial?**

We do not manage user funds. Rotki is a portfolio tracker and accounting tool. All user data are non-custodial and local to the user's system encrypted by a password of their choice.

**Do you offer community support?**

Yes: https://discord.gg/aGCxHG7

**Describe any geographical restrictions on usage of your dapp**

None

**Dapp title**

rotki

**Dapp description**

Rotki is an open source portfolio tracking, analytics, accounting and tax reporting tool that respects your privacy. The mission of Rotki is to bring transparency into the crypto and financial sectors through the use of open source. Most importantly unlike virtually every other competing service which consists of closed source SaaS onto which you are forced to hand over all your financial data, with Rotki your data is stored encrypted locally in your computer. It enables you to take ownership of your financial data!

**Dapp logo**

https://raw.githubusercontent.com/rotkehlchenio/rotkehlchen/develop/frontend/app/src/assets/images/rotkehlchen_no_text.png

**Brand color**

Oh that's ... ehm ... what is a brand color? :sweat_smile:

**Comment by wackerow** [comment]
@LefterisJP Thanks for submitting! We'll take a look and get back to you... no worries about the brand color =), your logo is enough

**Comment by GeorgeTrotter** [comment]
Hey @LefterisJP! Thanks for this inquiry. Rotki looks really interesting. Can you help me understand it a bit better? Which parts of the service occur on chain?

**Comment by LefterisJP** [comment]
Hello @GeorgeTrotter .
It's a portfolio tracker. So it's a monitoring tool that monitors the chain for your accounts. It does not handle any user keys.

**Comment by ryancreatescopy** [comment]
@GeorgeTrotter what's the status on this?

**Comment by GeorgeTrotter** [comment]
@wackerow good to go on this!

**Comment by LefterisJP** [comment]
Thank you guys :bow:
