### ISSUE TITLE
Improve wallet filtering

### ISSUE THREAD

**Issue by ligi** [ethereum/ethereum-org-website#2715]
Currently the wallet filter looks like this:

![Selection_060](https://user-images.githubusercontent.com/111600/112101718-68dc4f00-8ba7-11eb-8073-81cb8b59155d.png)

I see room for improvement here. First of all the IMHO most important criteria is missing "The Wallet is fully libre software / open source"
Also I am really missing a filters like

 * a filter for which chains are supported (especially important in the upcoming L2 world)
 * which platform is supported (Android, Linux, iOS, mcOS, windows, browser)
 * hardware wallet support
 * supports WalletConnect
 * supports Sourcify

And I see that from a UX perspective there should not be too many filters - but I also see a lot of filters that IMHO can be dropped as these things are IMHO things that should happen on the dApp level - not on the Wallet level. It is even a security benefit if you reduce the stuff that the wallet is doing to things that are core of a wallet.
IMHO what can be dropped:
 * decentralized token swaps (should be on L2 like on uniswap and just communicate with the wallet via WalletConnect)
 * Buy crypto with credit card
 * Access to financial tools
 * Withdraw to a bank
 * High volume purchase

What should stay for sure is:
 * Multi-signature accounts
 * Limits protection
 * maybe Explore dapps

I know this is a big change (especially the non-binary filters like supported platforms/chains) - maybe it is best to start small and for now just add the new filter "Fully libre software" that is IMHO really missing here.

**Comment by jzaki** [comment]
I feel filters like "Buy crypto with credit card" are useful for on-boarding new users.

I'm in support of the filters you list, but see them as "Advanced" filters (or some other division). E.g. knowing the licensing, networks supported, hw wallet... even broad categories of these seem too technical for new users. Or at least less actionable by users looking to try a wallet.

There is probably a meaningful divide of filters somewhere: new user capabilities, vs software capabilities.
And agree it would be good to surface "Fully libre software" somehow.

**Comment by ligi** [comment]
Thanks for joining the conversation!

TBH I am not really sure if they should be hidden behind "Advanced"
especially the networks - IMHO it is really important to know for the users which networks are supported. Also the platform should not be hidden behind "advanced". Especially in the L2 aera we are about to enter.
About the license and HW-Wallets we can talk. But IMHO the availability of the source-code is *really* important. I even think if you use a closed-source wallet you are practically using a custodial one - because you do not know if it sends the keys home. Would even go so far to say the foundation should not list such wallets - but I am being pragmatic here for the time being as the list of wallets would be *very* small then ;-)
But yea the actual license might be hidden under "Advanced" (really hope Richard Stallman does not read his though :)
Maybe another option could also be (to not have too many complex filters that lead to bad UX) to have warnings like "Source code not available" or "not libre software" next to the wallets.

**Comment by jzaki** [comment]
Looking back at the path to get to that filter screen (`find-wallet`), it's a screen beyond `/wallets` already, so I take back the need for yet another layer (`/wallets/find-wallet/advanced` not needed).

I really like the idea of a top-level signal of the benefit of the source openness (or not): eg "Openly maintainable", "(No) Tech Lock-in", "Anti-fragile fallback"/"Single point of failure", ... Or simply the signal: "Open(/Closed) App", "Proprietary"...

Can imagine this as an icon next to each wallet with hover-over text.

**Comment by samajammin** [comment]
Thanks for the input @ligi @jzaki - lots of good ideas here.

It's certainly a balance between serving new & more advanced users but I agree, ultimately we should make the relevant information available for the folks who are looking for it.

Our team will be mapping out Q2 goals shortly & wallet page improvements are likely on that list. Together they make ~20% of site pageviews. In the meantime, I welcome input on content / design from anyone. One major area we could certainly use help with is the data collection for the wallets! You can find the source file here:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/wallets.csv

**Comment by ligi** [comment]
@samajammin thanks for the reply and great to hear you are open to changes here and might add it to the roadmap!

regarding the WalletData I opened #2730

would also like to add things here (e.g. my favorite wallet: http://walleth.org :) - but I think it makes sense to change the format first to reduce the amount of work afterwards

**Comment by ligi** [comment]
commenting so the bot is not closing it - I think the issue is still very relevant. @samajammin seems this issue did not make it to the Q2 goals - maybe Q3? I think it is quite important.

**Comment by ligi** [comment]
In the context of EIP-1559 it would also be nice to have a filter if the wallet supports it. So users will know if they overpay and it is an incentive for the wallet to support it. Some wallets like TREZOR need some convincing to support 1559.

**Comment by timbeiko** [comment]
@ligi I like that idea. This is also true for EIP-2930 transactions.

**Comment by ligi** [comment]
Do you know a wallet that has 2930 support implemented or on the agenda?

**Comment by timbeiko** [comment]
No idea - I haven't really looked into it.

**Comment by ryancreatescopy** [comment]
I personally disagree with introducing filters that reference specific EIPs like 1559... this is a step further down the rabbit hole than I'm comfortable with. This page is intended to support new Ethereum users getting started in the space. I see 1559, at this stage, being a choice for more advanced users. However, if we re-label 1559 as something the user might understand intuitively it could work: what's the benefit of 1559 to end users?

Ultimately we probably need to refresh the filters soon but these should all reflect tangible user benefits and not require existing knowledge of anything Ethereum-based, ideally. 

cc @wackerow @samajammin

**Comment by wackerow** [comment]
@ryancreatescopy I do agree that we should be careful how technical we get with this page. 

> "what's the benefit of 1559 to end users?"

That being said, EIP-1559 is supposed to be a UX improvement for users. The short-term volatility in gas fees is what this addresses, and users are going to want to benefit from it. 

>"However, if we re-label 1559 as something the user might understand intuitively it could work"

100%

Could use some marketing/branding.

**Comment by jzaki** [comment]
I think a top-level signal of EIP-1559 explained simply (eg "Transaction fee stability") would be good.

Akin to open-source as, say, "Development transparency".

**Comment by ligi** [comment]
@jzaki  I agree - we need a better name/branding for EIP-1559 when it hits end-users. Not yet sure about "Transaction fee stability" though as the fees are still moving and are not stable - that could message a wrong message to the users. E.g. when they see their transfer costs 1$ today and 2$ tomorrow - then they wonder "is this stable fee feature broken"? I would throw "simple fees" into the ring for a new term.

I can get behind "Development transparency" and cannot yet imagine a better term. Although there might be one out there that captures more properties that arise like user freedom (e.g. to modify the code) or also product transparency and security improvements coming from that aspect.

**Comment by AFDudley** [comment]
> I think a top-level signal of EIP-1559 explained simply (eg "Transaction fee stability") would be good.
> 
> Akin to open-source as, say, "Development transparency".

In this context I prefer "fee optimization" and a reference to the fork, not the EIP.

**Comment by timbeiko** [comment]
Perhaps another option is "Excess Fee Refund" or something similar. One of the nice things about 1559 is that you get a refund for the difference between your `maxFee` and what was paid in the `baseFee` + `priorityFee`. I really like "fee optimization" too, but you could argue that a non-1559 wallet could provide good estimations.

**Comment by wackerow** [comment]
"Smart fees"

?

**Comment by timbeiko** [comment]
In the spirit of not letting this go stale and "shipped is better than perfect", does anyone oppose @AFDudley's "Fee Optimization"?

**Comment by wackerow** [comment]
Not against that at all... do we have any idea which wallets are updated to fully support EIP-1559 yet?

**Comment by FrederikBolding** [comment]
https://app.mycrypto.com/ will support EIP 1559 at launch

Trackable here: https://github.com/MyCryptoHQ/MyCrypto/pull/4045

**Comment by carlfairclough** [comment]
To echo @ryancreatescopy's comment, I'm not sure whether referencing specific EIPs is useful to end users. Questions that matter for **new users** regarding transactions (especially when viewed as an **onboarding resource**) might be:
 - are fees low?
 - do transactions get processed?
 
Information about fee variability and steps taken to mitigate that belongs elsewhere, unless this page is to become a wallet-feature-matrix.

I'm also anti-"Fee Optimization" is very generic, as grandfathered transactions can still be tightly optimised.

Regardless, https://status.im will be supporting 1559 and is trackable across multiple branches:
https://github.com/status-im/status-react/tree/wallet/eip1559-ui
https://github.com/status-im/status-desktop/tree/feat/eip1559
https://github.com/status-im/status-go/tree/feature/suggest-fees

**Comment by timbeiko** [comment]
@carlfairclough what do you think about "Excess Fee Refund"? It really is what 1559 provides, but I'm concerned it is just too weird of a label. Any other suggestions?

**Comment by carlfairclough** [comment]
@timbeiko  I'm much more for saying exactly what it does like your suggestion. It's possibly worth noting that there is an existing 1559 explainer page too, which this could connect to: #3104

**Comment by ligi** [comment]
I think the talk by vitalik buterin at ethCC ["Things that matter outside of defi"](https://www.youtube.com/watch?v=oLsb7clrXMQ) is also very much relevant in this context and plays to the point I initially wanted to make here.
Currently the filtering is very much DeFi centric - 5/8 filters are around DeFi - but Ethereum is about so much more than DeFi and IMHO the ethereum.org website should reflect that!

**Comment by samajammin** [comment]
> I personally disagree with introducing filters that reference specific EIPs like 1559... this is a step further down the rabbit hole than I'm comfortable with. This page is intended to support new Ethereum users getting started in the space. 

I tend to agree with @ryancreatescopy on this. A filter for EIPs seems like unnecessary complexity to be pushing onto users who are new to Ethereum.

One alternative route may be to add EIPs to our listing policy:
https://ethereum.org/en/contributing/adding-products/
This might be an extreme stance but we _could_ just make EIP 1559 support (& any other EIPs) a requirement for wallets in order to get listed on the site. We could simply remove wallets that don't support it. What do folks think about that as an approach?

**Comment by timbeiko** [comment]
I'd be in favor of simply not listing non-1559 supporting wallets if that's easier, but you probably want to wait ~6 months before you do that to give everyone the chance to add support.

**Comment by ligi** [comment]
I would also be fine with just removing wallets that do not support EIP1559 - would even make a shorter period like 3 months
My main intention behind this issue are removing these DeFI centric filters in favor to the other ones I mentioned initially anyway ..-)

**Comment by samajammin** [comment]
Hey folks - following up here - we made the tough decision as a team to not prioritize this issue this quarter (you can find our priorities in our roadmap here: https://github.com/ethereum/ethereum-org-website/issues/3446). This will for sure be something we (particularly @minimalsm) dedicate time towards before the end of the year.

Thank you for your patience on this! Please feel free to share ideas & weigh in on what you think the best approach forward is.

**Comment by ligi** [comment]
Great! Happy to chat

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by corwintines** [comment]
I would say we addressed this issue with the revamp. @ligi I'm going to close this issue now that https://github.com/ethereum/ethereum-org-website/issues/6274 has been finished. Please reopen another issue if you disagree :) Thanks again for this suggestion, it helped shape a lot in the redesign.
