### ISSUE TITLE
NFT InfoBanner broken

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2718]
**Describe the bug**

On the NFT page, one of the InfoBanners doesn't work. The button isn't clickable. I believe the h4 below is the culprit. The button should be clickable.

https://ethereum.org/en/nft/#nfts-for-creators

**Screenshots**

![image](https://user-images.githubusercontent.com/40891631/112163434-ef635180-8be4-11eb-91c1-3a0cd3a9cfd4.png)

**Desktop (please complete the following information):**

- Chrome

**Comment by wackerow** [comment]
Definitely from the headers... the `:before` pseudo-element used for the links are getting in the way. This happens in other places on the site too unfortunately, like the glossary.

Will take a look and try to find a solution for the whole site.
