### ISSUE TITLE
Want to add my Article to ethereum.org

### ISSUE THREAD

**Issue by Uttam-Singhh** [ethereum/ethereum-org-website#2726]
I want to add my article to ethereum.org.
My article is based on how ethereum is going to change the internet.
Please have a look - https://uttamkhanduja.medium.com/how-the-internet-is-going-to-change-c0006ad8672f

**Comment by Uttam-Singhh** [comment]
@ryancreatescopy Please have a look!

**Comment by ryancreatescopy** [comment]
hi @Uttam-Singhh thanks for raising the issue. Although a nice read, we don't currently host user articles on ethereum.org. Our content doesn't tend to be in article-format, it's designed to support user needs. If you think there's a need we're not yet satisfying and think your content can help solve that, please do let us know. And If you'd like to add anything to our existing content, we'd welcome a PR/issue. Thanks again!

**Comment by Uttam-Singhh** [comment]
Okay, sure! @ryancreatescopy I will create a new issue.
