### ISSUE TITLE
Add "JetBrains IDEs" to ides/index.md

### ISSUE THREAD

**Issue by jhhb** [ethereum/ethereum-org-website#2743]
**Is your feature request related to a problem? Please describe.**

There's no problem -- just an enhancement request. As a user of JetBrains IDEs, which officially support a Solidity plugin, it would be handy to have "JetBrains IDEs" as as section in `ides/index.md`

**Describe the solution you'd like**

- add section under "DESKTOP IDES" (see screenshot); new section in red.
- In order, the links point to the JetBrains home page, the JetBrains github, and the github repo for the official JetBrains Solidity plugin.

<img width="1189" alt="Screen Shot 2021-03-28 at 2 44 56 PM" src="https://user-images.githubusercontent.com/12632889/112764056-f15a5580-8fd4-11eb-89c3-d370d2a3f602.png">

**Describe alternatives you've considered**
- A link to the solidity plugin could go under "PLUGINS AND EXTENSIONS" as an alternative to adding a section for JetBrains, but I think it makes sense to give JetBrains the same treatment as the other IDEs even though the extent of integration is just one plugin so far.

**Additional context**
- I'm happy to make this change

Thanks for all of the excellent docs and work on this project, especially the contribution and local dev guidelines.

**Comment by samajammin** [comment]
Thanks for the suggestion @jhhb. We'd welcome a PR 😄
