### ISSUE TITLE
https://ethereumbillboard.com

### ISSUE THREAD

**Issue by eakdogan** [ethereum/ethereum-org-website#2754]
**Is your dapp open source?**
Yes, anyone can access the contract methods. 
https://github.com/eakdogan/ethereumbillboard/tree/main

Yes

**Can a user access the dapp without creating an account?**
Yes

Yes

**Are dapp funds non-custodial?**
Yes

Yes

**Do you offer community support?**
Yes

cognitiveapps@gmail.com

**Describe any geographical restrictions on usage of your dapp**
None

Globally accessible

**Dapp title**
Ethereum Billboard

Ethereum Billboard

**Dapp description**
Post eternal messages on Ethereum.

Users can advertise brand, NFT, share a message, support a cause by posting on billboard. 

**Dapp logo**

<img width="512" alt="1024-1024 Ethereum Billboard Logo" src="https://user-images.githubusercontent.com/24481672/112917916-4aa3b100-90c9-11eb-94cc-2ada99b6a9ea.png">

**Brand color**

White

**Comment by GeorgeTrotter** [comment]
Hey @eakdogan! Thanks for opening this. I had a look at your github repo, is there anywhere else I can find information about ethereumbillboard?

Thanks!

**Comment by eakdogan** [comment]
Hi Georg,

Thank you for looking into it! Here’s an article about it: https://link.medium.com/Q2ufCICcpfb

**Comment by ryancreatescopy** [comment]
@GeorgeTrotter what's the status on this?

**Comment by GeorgeTrotter** [comment]
Hi @eakdogan, we're closing this issue without adding to the site. While ethereumbillboard looks like a cool project, it doesn't look in line with our [design principles](https://ethereum.org/en/contributing/design-principles/#contributing-to-ethereumorg-), in that it doesn't look to be very active currently. Please feel free to reopen this issue in the future if that changes!
