### ISSUE TITLE
Translation component pages that are still in English do not display TranslationBanner

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2757]
**Describe the bug**

Some translation component pages that are still in English do not display the TranslationBanner.

It looks to be an issue with components in the /src/pages/ directory. The /src/pages-conditional/ are working as expected.

**To Reproduce**

1. Go to https://ethereum.org/bn/get-eth/
2. TranslationBanner component does not display

**Expected behavior**
TranslationBanner component should display (translated) "You’re viewing this page in English because we haven’t translated it yet. Help us translate this content."

It's working correctly for markdown pages, e.g. https://ethereum.org/bn/dapps/

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
The ultimate solution here might be to scrape the `gatsby-plugin-intl` plugin. That's what is automatically creating translation pages for all /src/pages/ components under the hood:
https://github.com/wiziple/gatsby-plugin-intl/blob/master/src/gatsby-node.js#L41

**Comment by samajammin** [comment]
Actually we might be able to fix this in the `onCreatePage` hook... if content version is <2, for most pages (I think anything other than /developers/index.js we should set `page.context.isContentEnglish` to `true`.

**Comment by mic0des** [comment]
Hey @samajammin this looks like an interesting problem to tackle since I'm thinking about contributing to some language translations! If it hasn't already been taken, mind assigning it to me?
