### ISSUE TITLE
Layer 2 clean up

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2760]
**Is your feature request related to a problem? Please describe.**

I've seen a few mentions over Discord/Twitter that our [layer 2 docs](https://ethereum.org/en/developers/docs/layer-2-scaling/) may be misleading/incorrect.

The argument is: sidechains / validium are not technically layer 2 because they don't use layer 1 as the security layer. 

So although they are ways to "scale" your dapp, they are not actually layer 2. 

I think this stems from the fact that we, at one point, transitioned the title from "scaling" to "Layer 2 scaling". Bear in mind it is just "scaling" in the menu. 

**Describe the solution you'd like**

1. Confirm that it's incorrect to label contentious solutions as layer 2
2. If yes, split section into multiple pages, e.g.

```
|_scaling
     |_ rollups
          |_ zk
          |_optimistic
     |_ sidechains
     |_ etc
```

"Scaling" can either be a directory style page or can just exist as a folder. I think my preference is that it intros each metho of scaling and describes what they're good for.

**Comment by minimalsm** [comment]
I would like to tackle this issue if it is agreed upon.

Looking at the current structure of other sidebar items a directory style page makes sense to me. 👍

**Comment by jjmstark** [comment]
One other option to consider would be to use "off-chain scaling" to refer to L2 + Sidechains/Validium, and only use "Layer 2 scaling" to refer to things that are properly L2. 

Since we also talk elsewhere on the site about "scaling" in a much more general sense, for instance in relation to the Eth2 upgrades, it might be useful to have terminology that makes that distinction.

**Comment by samajammin** [comment]
I agree the page (https://ethereum.org/en/developers/docs/layer-2-scaling/) could use a re-work. Thanks for suggesting 👍 

Adding my take, mostly from an SEO perspective.

I agree with @ryancreatescopy - I think it makes sense to have a top level page on general scaling (i.e. https://ethereum.org/en/developers/docs/scaling/) that explains what it means to "scale" a blockchain & provides a brief intro into the various approaches (including Eth2 work like sharding, which can reference [our page on sharding](https://ethereum.org/en/eth2/shard-chains/)).

While what defines "layer 2" might be up for debate (or is it?), I also think it makes sense to keep a page targeting "layer 2" given how widespread the L1/L2 terminology has become. If you look at the search terms driving volume to the current page, the impressions for "layer 2" terms far exceed "rollup" related terms. Take a look at this export of search volume around these terms over the past 3 months:
https://docs.google.com/spreadsheets/d/1l20_lWQXd2yB3SVP5tfdBxXZQ759dnyxFaBatEwLIjo/edit#gid=1009804214

If it's cleaner from a definition standpoint to go with the hierarchy @ryancreatescopy suggested (i.e. if we prefer https://ethereum.org/en/developers/docs/scaling/rollups/ vs. https://ethereum.org/en/developers/docs/scaling/layer-2/), I recommend we title it something along the lines of `Layer 2 scaling: rollups` to ensure we continue to capture that search traffic.

**Comment by samajammin** [comment]
> I would like to tackle this issue if it is agreed upon.

Thanks for volunteering @minimalsm! I'd say go for it! Perhaps start with the top level "Ethereum scaling" page? That would give us some time to finalize the information architecture of this section.

Appreciate any input from folks on this!

**Comment by samajammin** [comment]
Perhaps another use case distinction worth calling out - payment based L2s vs full EVM generalized computing L2s.

**Comment by minimalsm** [comment]
> explains what it means to "scale" a blockchain & provides a brief intro into the various approaches (including Eth2 work like sharding, which can reference [our page on sharding](https://ethereum.org/en/eth2/shard-chains/)).

To include sharding would it make sense to break it down as follows?

- Scaling Overview

- On-chain scaling
  - Sharding

- Off-chain scaling
   - Roll ups 
   - Sidechains
   - Etc

- Further Reading

**Comment by minimalsm** [comment]
@samajammin I have created a draft PR whilst waiting on the finalisation of the architecture of this section 🙂

**Comment by lamart1** [comment]
What if on page is "LAYER 2 SCALING + SIDECHAINS" ? 
And then explanation that sidechains are blockchains with different security than Etheruem, but they are bridged to Ethereum and you can hop to them easily and decentralized way.

**Comment by wackerow** [comment]
(I believe #2785 should cover this... closing for now, feel free to re-open if I missed anything)
