### ISSUE TITLE
A page for explaining that ETH transactions cannot be reversed

### ISSUE THREAD

**Issue by GeorgeTrotter** [ethereum/ethereum-org-website#2767]
**Is your feature request related to a problem? Please describe.**

Many new members of the Ethereum community are familiar with the experience of having sent ETH to an address and then wanting to reverse the payment. Standard material that explains 1. that payments are irreversible 2. why it's desirable for a blockchain to not be able to reverse payments 3. softening potential hard feelings could be a high leverage resource.

**Describe the solution you'd like**

Something like a page called "what happens if I send my ETH to the wrong address?" or "can I get my ETH back?" or "who can I ask for help getting my ETH back?" that explains that ETH transactions cannot be reversed, and why that is.

**Describe alternatives you've considered**

**Additional context**

**Comment by ryancreatescopy** [comment]
I'm not certain it's as easy as just adding a page. For example, I'm not sure where it would currently live. We could think about expanding out "live help" to include support pages with common queries like this... 

I think in the short term we can make this clear on our what is eth, what is ethereum and wallet pages. 

![image](https://user-images.githubusercontent.com/40891631/113257699-e1878d80-92c2-11eb-85b6-b25335a0f5ae.png)

But ultimately, products bear some of the responsibility here in educating their users to double check addresses.

**Comment by wackerow** [comment]
@ryancreatescopy The Live Help experiment is coming to a close for now... should we consider a "Help" section in its place?

**Comment by qbzzt** [comment]
It looks like this belongs in the page requested in #2077 .

**Comment by ryancreatescopy** [comment]
I think building out a help section would be very worthwhile. Definitely something we could start small with (e.g. stuck transaction) and build out. A fully fledged help center would be a big job but maybe we could just drop a few pages that we’ve identified a need for under a help drop down for now!

**Comment by minimalsm** [comment]
#2077
#3448

**Comment by wackerow** [comment]
Going to close this with #3872, can expand on the new page with new issues if needed
