### ISSUE TITLE
Security page that demonstrates good security habits

### ISSUE THREAD

**Issue by GeorgeTrotter** [ethereum/ethereum-org-website#2768]
**Is your feature request related to a problem? Please describe.**

Good security habits are an essential part of working in the Ethereum ecosystem, but aren't always written down well anywhere

**Describe the solution you'd like**

a Security page where we could help demonstrate good security habits, like always confirming the address you’re sending to (and how to do that)

**Describe alternatives you've considered**

**Additional context**

**Comment by qbzzt** [comment]
Do you want me to try and tackle this over the weekend?

**Comment by samajammin** [comment]
Some solid resources for inspiration:
- https://metamask.zendesk.com/hc/en-us/articles/360015489591-Basic-Safety-and-Security-Tips-for-Metamask
- https://support.mycrypto.com/staying-safe/protecting-yourself-and-your-funds
- https://support.mycrypto.com/staying-safe

**Comment by samajammin** [comment]
> Do you want me to try and tackle this over the weekend?

Thanks for offering @qbzzt! I'm open to it - do you think that's the best use of your time? My hesitation is that I don't see this page being nearly as technical as the developer resources/tutorials you've worked on in the past.

**Comment by ryancreatescopy** [comment]
#2077

**Comment by minimalsm** [comment]
We've got a few security threads now. Reopening this with the goal of consolidating them to provide the best context to tackle this (hopefully soon!)

**Comment by wackerow** [comment]
Going to close this with #3872, can expand on the new page with new issues if needed
