### ISSUE TITLE
Improve accessibility of icon links

### ISSUE THREAD

**Issue by Robiquet** [ethereum/ethereum-org-website#2770]
**Is your feature request related to a problem? Please describe.**

The social icons (Youtube, Twitter, etc ) at the bottom of the home page don't contain any text. This makes it hard for people that use screen readers to figure out what they do.

**Describe the solution you'd like**

The simplest solution I can think of would be to add an ariaLabel property to the Link component to allow a link to have an aria-label attribute. Though, maybe a better solution would be to add an accessibleText property to the Icon component that would display the text to screen readers and hide the icon using aria-hidden. Would be good to get a second opinion!

**Describe alternatives you've considered**

**Additional context**

**Comment by minimalsm** [comment]
An aria-label does the job. Would there be any added benefit to the second approach?

The area where this lives has quite a few abstractions so I don't know if there is a 'correct' way to implement it even if it is only adding an aria-label.

One thought I had was would the aria label need to be translated? I done a quick poll and the consensus was that these are Brand names and would be understood universally but I'd love to hear any thoughts either way.

**Comment by Robiquet** [comment]
No huge benefit, in general I think it's best if things make sense semantically but in this case it might be more pain than it's worth. So happy to go with the simple aria-label! 

Think we'll be ok to go without translations for the reason you mentioned. I was thinking that they might be needed for languages that use different characters but this text is intended to be read by a screen reader so it should be ok.

**Comment by Robiquet** [comment]
If someone on the team thinks this is worth doing could you assign it to me and I'll get started on it

**Comment by ryancreatescopy** [comment]
Thanks @Robiquet — assigned.
