### ISSUE TITLE
Developer docs page that explains ETH & tokens

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2776]
**Is your feature request related to a problem? Please describe.**

I've seen multiple questions on Discord of people looking for the "Ether token address"

> Hey there guys, how come its so hard to find the Ether token address as opposed to dAI? I want to use that in a dApp

> What is the eth smart contract address?? Why is it so hard to locate as opposed to DAI on etherscan?

**Describe the solution you'd like**

We have a page on ETH: https://ethereum.org/en/eth/

But we don't get into the nitty gritty of how ether compares to other tokens (which have a dedicated smart contract)

Perhaps within our "Foundational topics" developer docs, we should explain ETH & tokens, e.g. https://ethereum.org/en/developers/docs/tokens/

**Describe alternatives you've considered**
- Add this information to the [accounts page](https://ethereum.org/en/developers/docs/accounts/), that an ETH balance is directly embedded in an account vs. token balances are merely storage variables on a smart contract?
- Create a more general "Tokens" page that explain ETH vs. tokens in more laymen's terms?

**Additional context**

Potential content for the page...

There is no ETH smart contract address. ETH the asset is built into the protocol. It's held as a balance on accounts.
More on accounts here: https://ethereum.org/en/developers/docs/accounts/
DAI is an ERC-20, which IS a smart contract https://ethereum.org/en/developers/docs/standards/tokens/erc-20/

So ETH is the native currency of the Ethereum blockchain. When you send a transaction with value you are sending ETH.
(As opposed to sending and ERC20 token on Ethereum)
What's interesting is there is a WETH token that is "wrapped ether"
So you can send ETH as an ERC20 by wrapping it :slight_smile:

**Comment by mic0des** [comment]
Hi @samajammin would you guys mind if I tried taking a stab at a draft for this information? Getting back into the Ethereum ecosystem this year and as also a copywriter/technical writer, I wouldn't mind contributing to some of these docs if at the very least to solidify my own understanding by attempting to explain things in a clear manner for others. 😊

**Comment by samajammin** [comment]
That'd be great, thanks for volunteering @mic0des!
