### ISSUE TITLE
Migrate off "gatsby-plugin-intl"

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2777]
**Is your feature request related to a problem? Please describe.**

During migration to Gatsby v3 (#2528) we've hit warnings that the `gatsby-plugin-intl` is not compatible with Gatsby v3.

There's an open issue & PR to address this:
https://github.com/wiziple/gatsby-plugin-intl/issues/172

But it appears the project is no longer maintained:
https://github.com/wiziple/gatsby-plugin-intl/issues/168

**Describe the solution you'd like**

Given all the custom functionality we've already implemented around internationalization (e.g. [see our gatsby-node.js file](https://github.com/ethereum/ethereum-org-website/blob/dev/gatsby-node.js)), I think we could remove the plugin entirely & roll our own solution.

I'm keen to explore a solution similar to what we built for the Eth2 launchpad just using `react-intl`:
https://github.com/ethereum/eth2.0-deposit/pull/308
Main win here would be to auto-generate string ids so we could keep the English content right in components for easier readability & DX. One thing we'd need to confirm is if Gatsby can be configured to use the `defaultMessage` approach to auto-generate those string ids. CRA didn't support this out of the box (see https://github.com/formatjs/formatjs/issues/2151).

**Describe alternatives you've considered**

Looks like there's a fork of `gatsby-plugin-intl` with Gatsby v3 support:
https://github.com/theowenyoung/gatsby-plugin-intl

**Comment by minimalsm** [comment]
Codebase would definitely be a lot less intimidating and easier to navigate for newer contributors if there is something we could do here.

**Comment by minimalsm** [comment]
Solved
