### ISSUE TITLE
Migrate to "gatsby-plugin-image"

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2778]
**Is your feature request related to a problem? Please describe.**

After migrating to Gatsby v3 (https://github.com/ethereum/ethereum-org-website/issues/2528) we get this warning on build:

```
warn [gatsby-transformer-sharp] The "fixed" and "fluid" resolvers are now deprecated. Switch to "gatsby-plugin-image" for better performance and a simpler
API. See https://gatsby.dev/migrate-images to learn how.
```

**Describe the solution you'd like**
https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide/

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by minimalsm** [comment]
Had a play around with this. Going to have dig into the config for it, by default the quality of the images after migrating seems significantly worse.. probably far more noticeable as the site is using illustrations.

## Before (Gatsby-Image)
![Screenshot 2021-05-29 at 21 38 52](https://user-images.githubusercontent.com/62268199/120084206-4b0af900-c0c6-11eb-929b-64ad48b60a91.png)

## After (Gatsby-plugin-image)
![Screenshot 2021-05-29 at 21 38 30](https://user-images.githubusercontent.com/62268199/120084211-51997080-c0c6-11eb-95d4-0a2cc8491f95.png)

**Comment by samajammin** [comment]
FYI current work on #4271 will solve this.

**Comment by samajammin** [comment]
@minimalsm do you still notice this issue on the recent Gatsby v4 preview deploys (e.g. #4324)?

**Comment by samajammin** [comment]
I actually do notice the quality being worse... 🧐 

e.g. look at the hero on https://build-67666ca9-da4b-4126-841f-d7bf9bf4842b.gtsb.io/en/what-is-ethereum/ vs https://ethereum.org/en/what-is-ethereum/

Might just be a matter of configuring the new plugin? cc @wackerow @pettinarip

**Comment by wackerow** [comment]
@samajammin Yeah, there is a `quality: 100` parameter that we can add on the image queries. I added this to all images marked as "hero" but not every single image on the site. I didn't do this by default everywhere, but maybe it's worth it. Can push a patch to max out the gatsby image quality.

**Comment by minimalsm** [comment]
Closed with our move to Gatsby V4.
