### ISSUE TITLE
Пожалуйста ссылку на кошелёк!

### ISSUE THREAD

**Issue by serega198331** [ethereum/ethereum-org-website#2781]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

**Is your wallet custodial, non-custodial, or a hardware wallet?**

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

**Does the wallet have fiat on-ramps?**

**Does the wallet allow users to explore dapps?**

**Does the wallet have integrated defi/financial tools?**

**Can a user withdraw to their card?**

**Does the wallet offer limits protection?**

**Does the wallet allow high-volume purchases?**

**Does the wallet have an integrated token swap?**

**Is the wallet a multi-signature wallet?**

**Wallet title**

**Wallet description**

**Wallet logo**

**Background colour for brand logo**

**Comment by serega198331** [comment]
хочу все!

**Comment by serega198331** [comment]
Кошелёк локальный, название не важно, можно переводить на карту , можно обменивать на другие монеты,

**Comment by wackerow** [comment]
(For reference, the above translates to: "Please link to the wallet! I want everything! The wallet is local, the name is not important, can be transferred to a card, can be exchanged for other coins" according to Google)

@serega198331 
- Please fill out the requested information for us in English please, utilizing online translation tools as needed if you are having any issues. Further repeat posts without clarity will result in reporting.
- Пожалуйста, заполните запрашиваемую информацию на английском языке, используя инструменты онлайн-перевода, если у вас возникнут какие-либо проблемы. Дальнейшие повторные публикации без ясности приведут к отчету.
