### ISSUE TITLE
YouTube embeds not displaying

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2787]
**Describe the bug**

Seems to only be a case on: https://ethereum.org/en/developers/docs/accounts/

Console error:
```
[Error] Refused to display 'https://ethereum.org/en/developers/docs/accounts/youtube.com/embed/QJ010l-pBpE' in a frame because it set 'X-Frame-Options' to 'DENY'.
```

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/accounts/
2. Scroll down to bottom videos

**Expected behavior**

Embeds should work! These appear to be the only broken ones...

**Screenshots**

![Image 2021-04-05 at 4 56 12 PM](https://user-images.githubusercontent.com/8097623/113640407-34997180-9630-11eb-9fe9-4e12efef7631.jpg)

**Desktop (please complete the following information):**

Reproduced in Brave & Safari on MacOS

**Comment by mic0des** [comment]
Hello! Iframe URL needs to be absolute https path otherwise it is looking for the YouTube resource in the site directory path instead. Can fix this in a jiffy if assigned.

**Comment by samajammin** [comment]
Thanks for offering @mic0des! I fixed before I saw your comment 😅
