### ISSUE TITLE
"Front-end web developer" role points to a broken job application link

### ISSUE THREAD

**Issue by JayWelsh** [ethereum/ethereum-org-website#2804]
**Describe the bug**

The current "Front-end web developer" role points to a broken link when trying to apply

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://ethereum.org/en/about/web-developer/
2. Click on "Apply for job"
3. See error

**Expected behaviour**

A functional job application

**Screenshots**

<img width="1440" alt="Screenshot 2021-04-08 at 13 40 13" src="https://user-images.githubusercontent.com/14224459/114020556-03a77f80-9870-11eb-998c-9059ba8def84.png">

**Comment by JayWelsh** [comment]
Additional context for anyone that finds this:

<img width="876" alt="Screenshot 2021-04-08 at 16 58 06" src="https://user-images.githubusercontent.com/14224459/114049325-a6212c00-988b-11eb-99c9-546b8db69a8d.png">

**Comment by samajammin** [comment]
This has been fixed 🎉

**Comment by samajammin** [comment]
@all-contributors please add @JayWelsh for bug reports.
