### ISSUE TITLE
No loading state for FileContributors components

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2809]
**Describe the bug**

As a result of #2713, the FileContributors component creates a jumpy interaction on page load.

**To Reproduce**

1. Go to a documentation / tutorial page
2. View jump in layout when component data loads

e.g. screencast:

https://user-images.githubusercontent.com/8097623/114082565-c12b7600-9862-11eb-81dc-3f0d3cd2e6f7.mp4

**Expected behavior**

We should add a loading state, e.g. with a dummy avatar or at least keeping the component height consistent during loading state so the page layout doesn't jump. Will need to account for different screen sizes.

**Screenshots**

See above

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

I believe we can also remove `gatsby-source-graphql` now that we're fetching Github data client-side?
https://github.com/ethereum/ethereum-org-website/blob/dev/gatsby-config.js#L223

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by hueyhe** [comment]
Hi, I'm new to the project and interested in contributing. I think we can solve this problem by adding a placeholder avatar with a fixed height. Can I work on this issue?

**Comment by ryancreatescopy** [comment]
Go for it! Assigned to you @hueyhe

**Comment by hueyhe** [comment]
@ryancreatescopy I've submitted a PR. Please comment if there's any problem.
