### ISSUE TITLE
Sorting the Ethereum client list by GitHub stars.

### ISSUE THREAD

**Issue by Danielrachi** [ethereum/ethereum-org-website#2813]
**Is your feature request related to a problem? Please describe.**

I find odd that the list of beacon chain clients (https://ethereum.org/en/eth2/get-involved/) and the list of Frameworks and pre-made stacks (https://ethereum.org/en/developers/local-environment/) show the different alternatives in no particular order.

**Describe the solution you'd like**

Sort the alternatives in a way that the user can see which ones are more popular.

**Describe alternatives you've considered**

Sort those kind of lists by the amount of GitHub stars that each alternative have.

**Additional context**

![Frameworks](https://user-images.githubusercontent.com/67139425/114118443-72a3c900-98ae-11eb-9a42-5bcae4fae1d3.png)
![Beacon Chain Clients](https://user-images.githubusercontent.com/67139425/114118447-746d8c80-98ae-11eb-9108-e4fa9132c5c2.png)

**Comment by minimalsm** [comment]
Personally I don't think GitHub stars is a particularly good metric in such a young eco-system. It might even promotes the status-quo? Being early to the game doesn't mean you've got the best tools. Samajammin touched on this [on discord](https://discord.com/channels/714888181740339261/720699996227502180/826600459065229352) last week.

 Just something to think about 😀.

**Comment by minimalsm** [comment]
If sorted the alignment you get of placeholder images is a bit.. ugly. Don't see any way around that as I double checked and none of them have logos.

<img width="1527" alt="Screenshot 2021-04-09 at 21 05 03" src="https://user-images.githubusercontent.com/62268199/114234915-528c0c80-9977-11eb-9c42-138014268988.png">

**Comment by ryancreatescopy** [comment]
We intentionally randomise these lists for the reasons stated above. Often github stars probably means it's been around the longest not that it's necessarily the best. We also want to make sure we support decentralization of tools/frameworks wherever possible. We welcome ideas for any other way we can help users make their decisions about these tools – are there other data points you'd find useful when comparing/choosing?
