### ISSUE TITLE
Package upgrades pending

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#2817]
The following are showing up as outdated:

- [x] `"netlify-lambda": "^1.6.3"` -> `"netlify-lambda": "^2.0.3"`
- [x] `"polished": "^3.6.5"` -> `"polished": "^4.1.1"`
- [x] `"react": "17.0.0"` -> `"react": "17.0.2"`
- [x] `"react-dom": "17.0.0"` -> `"react-dom": "17.0.2"`
- [x] `"react-select": "^3.1.0"` -> `"react-select": "^4.3.0"`
- [x] `"babel-preset-gatsby": "^0.8.0"` -> `"babel-preset-gatsby": "^1.2.0"`
- [ ] `"husky": "^4.2.5"` -> `"husky": "^6.0.0"`

_Originally posted by @wackerow in https://github.com/ethereum/ethereum-org-website/issues/2814#issuecomment-816375078_

**Comment by ryancreatescopy** [comment]
@wackerow can this be closed out?

**Comment by wackerow** [comment]
Yeah, Husky is low priority, can close for now
