### ISSUE TITLE
Scaling Ethereum Hackathon

### ISSUE THREAD

**Issue by xBalbinus** [ethereum/ethereum-org-website#2823]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

Scaling Ethereum Hackathon - ETHGlobal

**Product description:**

Building with an entire ecosystem at your back. Giving people support of a huge community of experts, mentors, sponsors, developer advocates, and other community members who want to help you build something awesome.

**How long has it been around?**

5+ years.

**Where do you think it should go?**

ethereum.org events page.

**URL**

https://scaling.ethglobal.co/#:~:text=Scaling%20Ethereum%20is%20a%204,%2C%20zero%20knowledge%2C%20and%20more!

**Comment by wackerow** [comment]
@xBalbinus https://ethereum.org/en/community/#upcoming-events I see a link to scaling.ethglobal.co. already listed on the [Community events page](https://ethereum.org/en/community/#upcoming-events) for this event. Was there anything else you were thinking for this?

**Comment by xBalbinus** [comment]
Hi, if the event is already on, then that's my bad. I was just thinking of
advertising the event because I work on the team - I did not know that the
event was already on there.

**Comment by wackerow** [comment]
@xBalbinus No worries! Good luck with it!
