### ISSUE TITLE
NFT content improvement

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2839]
From Twitter:
![image](https://user-images.githubusercontent.com/40891631/114545968-848dbf00-9c54-11eb-9919-067ae0b25da5.png)

**Comment by svaddadhi** [comment]
Hello, I would love to tackle this issue. Let me know if this is possible!

**Comment by ryancreatescopy** [comment]
@svaddadhi go for it. feel free to raise a PR

**Comment by jley81** [comment]
I do not know how they work. I dont even know how any of thos works. I'm new to everything about how this works.

**Comment by nassersaazi** [comment]
has this been worked on or can I take it up?

**Comment by cassyblaise** [comment]
Hey, @ryancreatescopy has anyone work on this? I'll like to work on it.
