### ISSUE TITLE
Mining Recourses/Mining Pool

### ISSUE THREAD

**Issue by Finn-Developments** [ethereum/ethereum-org-website#2843]
**Is your feature request related to a problem? Please describe.**

This is not as much of a problem as it is just a suggestion but when you want to get into crypto currency you probably start by just looking up ethereum or bitcoin and generally ethereum.org or bitcoin.com come up and then if you want to get into mining on bitcoin.com it does have a mining pool where as this is not the case on ethereum.org.

**Describe the solution you'd like**

I have no idea what this would entail, but I do understand that it is a big thing to make a mining pool.

**Describe alternatives you've considered**

I think this would be a lot smaller in comparison but I think it might be just as helpful if there was page that went more into depth about mining and also link to good programs to use for mining that someone might want/need to start mining.

**Additional context**

http://console.pool.bitcoin.com

**Want to contribute?**

Again I have none of the expertise needed for this but I would help however I could help.

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Hey there! Thanks for raising this issue :)

A solution here might be to add a section to our page on mining:
https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/mining/
We could link to resources that explain how to mine and/or how to join a mining pool.

In general, with the upcoming transition to proof-of-stake I don't think it makes much sense to invest too much of our resources into building out native content. Information & resources on staking can be found here:
https://ethereum.org/en/eth2/staking/

**Comment by Finn-Developments** [comment]
I have added some stuff to the website but I need to go back and add more information about software.
