### ISSUE TITLE
Adding the dapp Sorare to Ethereum.org

### ISSUE THREAD

**Issue by brohagan** [ethereum/ethereum-org-website#2859]
**Is your feature request related to a problem? Please describe.**

We would like to start the process of adding https://sorare.com on ethereum.org/dapps

Sorare is one of the NFT Dapp with the most transaction over the past year (as per Etherscan) and the Ethereum NFT dapp with the most users and volume in the past month. We've been working on Ethereum since day 1 and we intend to keep it that way and scale on Ethereum. 

**Describe the solution you'd like**

We'd like to have https://sorare.com referenced on ethereum.org/dapps as an example of a dapp that is built on Ethereum but whereby you barely feel that it's on blockchain (we try to abstract as much as possible) while keeping all the benefits of it.

**Comment by samajammin** [comment]
Hey @brohagan - thanks for the suggestion!

We have a listing policy for adding dapps:
https://ethereum.org/en/contributing/adding-products/

Could you please provide the info from the [dapp issue template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=Type%3A+Feature%2C+Type%3A+Content&template=suggest_dapp.md&title=)?

I've pasted it below:

Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**



**Is your dapp open source?**



**Can a user access the dapp without creating an account?**



**Are dapp funds non-custodial?**



**Do you offer community support?**



**Describe any geographical restrictions on usage of your dapp**



**Dapp title**



**Dapp description**



**Dapp logo**



**Brand color**

**Comment by wackerow** [comment]
@brohagan Hey, just touching base... any updates on this?

**Comment by minimalsm** [comment]
Leaving this closed for now. @brohagan feel feel to reopen with the requested info above ✌️
