### ISSUE TITLE
Please advise on how to proceed my Wallet

### ISSUE THREAD

**Issue by JODIN1727** [ethereum/ethereum-org-website#2864]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
?

**Comment by samajammin** [comment]
@JODIN1727 please feel free to clarify what you're looking to do.

**Comment by JODIN1727** [comment]
My Thailand based company need funds to fix for Renovations and Tax that shall lead to grow up my account here in the Philippines.. Please advise
