### ISSUE TITLE
Contents update

### ISSUE THREAD

**Issue by ozora-ogino** [ethereum/ethereum-org-website#2865]
In [/src/content/developers/docs/consensus-mechanisum/pos/index.md](https://github.com/ozora-ogino/ethereum-org-website/blob/dev/src/content/developers/docs/consensus-mechanisms/pos/index.md) line 26, add a page reference to "Shard" page.

**Comment by samajammin** [comment]
Solved in #2866

**Comment by mspaansen** [comment]
😀
