### ISSUE TITLE
0xdda869b5d56e101cdffb3e18b3f8bbeed1921a08

### ISSUE THREAD

**Issue by somchai992** [ethereum/ethereum-org-website#2868]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by chewy917** [comment]
@underdeveloped
