### ISSUE TITLE
Make it obvious that Serenity is Eth2

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#2872]
Currently it isn't obvious that Eth2 and Serenity are the same thing. 

Suggesting:
- [x] Update the glossary to reference this more explicity
- [ ]  Add reference on /eth2/ page

#### Current

<img width="870" alt="Screenshot 2021-04-16 at 22 10 22" src="https://user-images.githubusercontent.com/62268199/115084285-909da900-9f00-11eb-80af-4aaf523da6c0.png">

#### Proposed Change

<img width="816" alt="Screenshot 2021-04-16 at 22 21 29" src="https://user-images.githubusercontent.com/62268199/115085283-2a198a80-9f02-11eb-9e65-1dbde87c933b.png">

### Eth2 Page

Currently the [/eth2](https://ethereum.org/eth2) page has no mention of Serenity at all. Is it worth adding something on this page?

**Comment by wackerow** [comment]
@minimalsm I don't think it's worth spreading that term into the Eth2 pages, as it was initially more of a dev code name... even "Eth2" is something that is eventually likely to fade away in favor of just "Ethereum" again.
I'm cool with the above change though to help clarify 👍 thanks!

**Comment by wackerow** [comment]
@samajammin @ryancreatescopy Please feel free to open this back up and disagree if you would like to expand the Serenity term, otherwise I'm going to mark as closed by #2873

**Comment by samajammin** [comment]
Thanks for raising @minimalsm! I agree, I think this is worth mentioning, at the very least on the glossary. There's a fair amount of "serenity" related search volume so it would be helpful for the folks looking for that to understand they're the same thing.

**Comment by wackerow** [comment]
Cool, @ryancreatescopy any thoughts on how to slip this in? 

Perhaps in the "What is Eth2?" block?
![image](https://user-images.githubusercontent.com/54227730/115801804-806b4b00-a392-11eb-8abf-58aa5603a765.png)

**Comment by ryancreatescopy** [comment]
I’m with Paul on this one. I think we already mention it on the vision page that it’s been in the works for many years. Not sure we need to talk about it on the main Eth2 page.

**Comment by ryancreatescopy** [comment]
Closing this out for now. The glossary has been updated to reflect this. Not convinced it's needed on the Eth2 page. Feel free to reopen if anyone feels strongly about this.
