### ISSUE TITLE
Suggest a Samsung Blockchain Wallet. 

### ISSUE THREAD

**Issue by Jongkeun-Choi** [ethereum/ethereum-org-website#2886]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

-> Firstly, No KYC requirement. And there are geographic/device limitations of our wallet. 

* device limitations
For now, Samsung Galaxy S10,S20,and S21 series, Galaxy Note 10 and Note 20 series,    Galaxy Fold series,  Galaxy Z Flip, Galaxy A90 5G and some of Galaxy A series support the Samsung Blockchain Wallet. 

* geographic limitations 
Samsung Blockchain Wallet is currently available in United State of America, Canada, Republic of Korea, United Kingdom, Germany, Switzerland, Spain, Portugal, Austria, Sweden, Finland, Denmark, Norway, Iceland, Australia, Singapore, Philippines, Romania, and Brazil. The service region will be expanded to more countries and territories worldwide. 

**Is your wallet custodial, non-custodial, or a hardware wallet?**

-> non-custodial

We allow users to get 12-word recovery phrase. 
Regardless of company/project's EOS, user can access their funds with the recovery phrase.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

-> Your private key used to make transactions or payments in Samsung Blockchain Wallet is stored in a secure area of your device, accessible only by your PIN or recovery phrase. Screens that you enter recovery phrase, PIN, and fingerprint works on a secure OS isolated from Android OS, so they are safe from hacks from outside and data leakage.

**Does the wallet have fiat on-ramps?**

-> SBW don't subsidise any transaction fees.

**Does the wallet allow users to explore dapps?**

-> SBW allow users to browse and explore dapps. Also, Any collectibles user recieve are stored securely within the app. In our wallet, discover about 4-50 dapps, which are web-based and app-based integrated with our Samsung Blockchain SDKs. 

For more informations : https://developer.samsung.com/blockchain

**Does the wallet have integrated defi/financial tools?**

-> We don't provide that tools directly. 

However, our wallet is integrated with exchange(Gemini), so If user are using from one of the supported countries(USA, CANADA), the exchange link feature will be availabe. Coin/tokens can be purchased from an exchange and be transferred to Samsung Blockchain Wallet. 

**Can a user withdraw to their card?**

-> No.

**Does the wallet offer limits protection?**

-> No.

**Does the wallet allow high-volume purchases?**

-> No.

**Does the wallet have an integrated token swap?**

-> No.

**Is the wallet a multi-signature wallet?**

-> No.

**Wallet title**

-> Samsung Blockchain Wallet

**Wallet description**

-> Keep your valuables safe and secure with Samsung Blockchain. 

**Wallet logo**

-> Please find the attached. 

![wallet_app_ic_72x72](https://user-images.githubusercontent.com/82481973/115205315-659b9b00-a134-11eb-8805-8e847bdbef87.png)
![wallet_app_ic_144x144](https://user-images.githubusercontent.com/82481973/115205322-67655e80-a134-11eb-9eef-089126e8a620.png)

**Background colour for brand logo**

-> Please white. 

====================

Also, Please refer to below link : 
https://www.samsung.com/global/galaxy/apps/samsung-blockchain/

**Comment by wackerow** [comment]
@Jongkeun-Choi Thanks for submitting! We'll check it out and get back to you

**Comment by GeorgeTrotter** [comment]
Hey @Jongkeun-Choi - in terms of security measures for this wallet, has the code been audited? Is your code open source? Is there a bug bounty or some equivalent? Let us know!

**Comment by Jongkeun-Choi** [comment]
Hi, George

It's not open source. Plus, there isn't any bug bounty.
Firstly, Samsung Galaxy Mobile has a 'Samsung Knox'(security mobile platform), which store and mange some datas
on Secure OS isolated with Android OS.

Also, There is a Samsung Blockchain Keystore(type of preloaded app on Samsung Galaxy Mobile)that has to use and work with this security mobile platform. By using this platform, Keystore allows private keys to be created, stored, and managed securely in secure area.

The point is that our wallet is integrated with this Keystore, and working on.
If you get more info, i want you to refer below link. you can check how wallet is working with Keystore.

Link : 
https://us.community.samsung.com/t5/Samsung-Apps-and-Services/OFFICIAL-Samsung-Blockchain-Keystore-amp-Wallet-Tutorial/td-p/1561814

**Comment by Jongkeun-Choi** [comment]
Hi, team. 
Could you share the status of progress?, If there's any problem to proceed, please tell us. :)

**Comment by GeorgeTrotter** [comment]
Hey @Jongkeun-Choi! We'll go ahead with adding this wallet. @wackerow will help with a PR!

**Comment by Jongkeun-Choi** [comment]
Thank you for your support!, Feel free to ask us if you guys have any inquiry to prepare a PR.

**Comment by wackerow** [comment]
@Jongkeun-Choi Thanks for bearing with us, just put up a PR to list SBW, will merge in momentarily

**Comment by Jongkeun-Choi** [comment]
Hi, @wackerow, Thank you for your help. 
And seems there's a issue while merging. could find 'Merging is blocked' in that merge. could you check it once?

**Comment by wackerow** [comment]
@Jongkeun-Choi Hey, following up on this, small bug needs patching on the PR before merging. It will be addressed and merged before the next site deployment.

**Comment by Jongkeun-Choi** [comment]
Thanks for sharing!
