### ISSUE TITLE
Add Crust Network to decentralized storage docs page

### ISSUE THREAD

**Issue by yyd106** [ethereum/ethereum-org-website#2887]
**Product name:**
[Crust Network](https://crust.network)

**Product description:**
Crust Network (https://crust.network/) is a decentralized storage network based on IPFS and Substrate, and it basically provides decentralized IPFS service.

Recently, [**Uniswap**](https://app.uniswap.org), has enabled decentralized deployment of websites by integrating [Crust Network](https://crust.network) into [Uniswap's release workflow](https://github.com/Uniswap/uniswap-interface/blob/main/.github/workflows/release.yaml). More details of this integration is in [Decentralized Uniswap Interface Hosting on IPFS](https://medium.com/crustnetwork/decentralized-uniswap-interface-hosting-on-ipfs-18a78d1209ac).
The same integration was later realized by [**Polkadot**](https://polkadot.network/), the [PolkaApps](https://dotapps.io/) is now hosted on Crust Network decentralized. 

**How long has it been around?**
The development of Crust Network kicked off in early 2019.

**Where do you think it should go?**
https://ethereum.org/en/developers/docs/storage/#contract-based

**GitHub URL**
https://github.com/crustio/crust

**Docs URL**
https://wiki.crust.network/en

**Is the product open source?**
Crust is open source 100%

**Additional context**
Now Crust is running preview network Maxwell and got 1000+ nodes joined in to provide IPFS storage (https://telemetry.polkadot.io/#list/Crust%20Maxwell).

**Comment by yyd106** [comment]
@GeorgeTrotter Thanks for the self-assignment, please let me know if you need any further information

**Comment by ryancreatescopy** [comment]
@GeorgeTrotter have you looked into this?

**Comment by GeorgeTrotter** [comment]
Hey @yyd106, we are closing this issue without adding to the site. As far as I can tell, Crust Network has launched only recently, and I believe according to [the site ](https://crust.network/), isn't live on mainnet. Please feel free to reopen this issue down the road after Crust has been live on mainnet for ~six months!

**Comment by yyd106** [comment]
@GeorgeTrotter Thanks for the info, we will reopen this after six months of the mainnet launch.
