### ISSUE TITLE
Grammar issue: page-dapps-features-6-description

### ISSUE THREAD

**Issue by ZackDeRose** [ethereum/ethereum-org-website#2892]
**Describe the bug**

**To Reproduce**

1. Go to '/en/dapps'
2. Scroll down to "Magic behind dapps" grid
3. Click on "Backed by cryptography"
4. Text in second sentence seems off gramatically

**Expected behavior**

Current: "Your authorise dapp actions with your Ethereum account, usually via your wallet, so keep your credentials safe."

Proposed: "You authorize dapp actions with your Ethereum account - usually via your wallet - so that your credentials stay safe."

**Screenshots**

![Screen Shot 2021-04-19 at 11 33 34 PM](https://user-images.githubusercontent.com/3788405/115349660-f68c6980-a168-11eb-9e4e-7164728fe4f9.png)

**Additional context**

Source: `src/intl/en/page-dapps.json`
Key: `"page-dapps-features-6-description"`

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ZackDeRose** [comment]
👋 Hi all - happy to submit the PR to fix.

**Comment by wackerow** [comment]
@ZackDeRose Agree with proposed changes 👍🏻  Thanks for dropping the issue, I've assigned you =)
