### ISSUE TITLE
Add Hermez Network to developers/docs/layer-2-scaling/zk-rollups docs page

### ISSUE THREAD

**Issue by krlosMata** [ethereum/ethereum-org-website#2893]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**
[Hermez network](https://hermez.io/)

**Product description:**
Hermez is an open-source ZK-Rollup optimised for secure, low-cost and usable token transfers on the wings of Ethereum

**How long has it been around?**
Mainnet release was done on 24th of March 2021, further details could be found [here](https://blog.hermez.io/hermez-network-mainnet-launch/) 
Testnet  release was done on 1st of March, further details could be found [here](https://blog.hermez.io/hermez-testnet-is-now-public/)

**Where do you think it should go?**
https://ethereum.org/en/developers/docs/layer-2-scaling/#use-zk-rollups

**GitHub URL**
https://github.com/hermeznetwork

**Docs URL**
https://docs.hermez.io/#/

**Is the product open source?**
Yes, [hermez network](https://hermez.io/) is open source 100%

**Additional context**

**Comment by krlosMata** [comment]
I'm willing to add content regarding this issue

**Comment by wackerow** [comment]
@krlosMata Thanks for submitting this =) We'll take a look at it and try to get back to you within a week or two.

**Comment by GeorgeTrotter** [comment]
@wackerow @krlosMata this is ready for a PR!
