### ISSUE TITLE
The latest full node get GasPrice question

### ISSUE THREAD

**Issue by msak222** [ethereum/ethereum-org-website#2894]
The gasPrice of the main network is more than 300 Gwei, 
but web3j.getGasPrice is obtained from our latest version of the full node and occasionally returns 6 or 2. 
What is the problem?

**Comment by jley81** [comment]
Duck of I know

**Comment by wackerow** [comment]
@msak222 Not sure =) This repo focuses on the development of the ethereum.org website though, not the web3js library... Maybe check out https://github.com/ChainSafe/web3.js/issues Good luck, stay safe!
