### ISSUE TITLE
Eth2 bug bounty wrong text

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ethereum-org-website#2895]
This should say "High impact, high likelihood" :)

https://ethereum.org/en/eth2/get-involved/bug-bounty/
<img width="368" alt="Screenshot 2021-04-20 at 11 48 11" src="https://user-images.githubusercontent.com/731743/115383958-5832ef00-a1ce-11eb-8836-cfbe05d15f4e.png">

**Comment by JustinDrake** [comment]
The "High" severity is now incorrectly changed to "High impact, high likelihood". Does this make sense @wackerow?

<img width="712" alt="Screenshot 2021-04-23 at 14 42 19" src="https://user-images.githubusercontent.com/731743/115879948-1ca05b00-a442-11eb-8c53-b1366d46918b.png">

**Comment by wackerow** [comment]
@JustinDrake Yeah, hadn't realized the string was shared 😕 will get a patch up
