### ISSUE TITLE
New cryptocurrency 

### ISSUE THREAD

**Issue by chemeconomy** [ethereum/ethereum-org-website#2901]
Dear All 
Thank you for your support 

I am very interested to create new cryptocurrency using ethereum blockchain 
Our project is very promising to establish 

please let me know how to start ?

thank you

**Comment by johnmlussier** [comment]
You can learn how to start developing using Ethereum here: https://ethereum.org/en/developers/

**Comment by chemeconomy** [comment]
Dear Ethereum/Ethereum-Org-Website

I am interested to create new cryptocurrency with promising project so how
can I start ?

Thanks
Eng. Ammar

**Comment by wackerow** [comment]
@chemeconomy Echoing the above referral =) Feel free to join us on Discord too to further the discussion.

**Comment by chemeconomy** [comment]
Dear All
Thank you for your email

Is there any way to start discussion to issue new cryptocurrency?
Thanks
Eng. Ammar
