### ISSUE TITLE
Create new "Ethereum History" page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2919]
**Is your feature request related to a problem? Please describe.**

As part of #2918 we'll refactor the existing ["Ethereum History" page](https://ethereum.org/en/history/) in an "Ethereum Network Upgrades" page.

Separately, it would be valuable to create a less technical, less protocol-based "History of Ethereum" page.

**Describe the solution you'd like**

Create a "History of Ethereum" page that provides a narrative on how Ethereum came to be, e.g.
- Inspiration from Bitcoin & limitations that it aimed to solve
- Narrative on the major events of Ethereum: whitepaper, founding members, creation of Ethereum Foundation, 1st smart contract deployed, beacon chain launch, etc.

**Describe alternatives you've considered**

- Keep history & network upgrades on same page

**Additional context**

See #2918

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Patil2099** [comment]
I would love to help with this issue. Can you guide me a little more?

**Comment by svaddadhi** [comment]
Hey I would love to help with this issue, could I possibly get it assigned so I can go ahead and get started? @samajammin

**Comment by Haleymiranda79** [comment]
I would like to help. I cannot seem to find any supporting documents that tell the "softer" side of the Ethereum story. Everything I can find is technical. I am not a developer. I want to be one possibly. I'm sure others like me, would be more likely to get involved if we knew all these good things about it and how it helps the community. Guidance on resources would be great and I would help.

**Comment by cassyblaise** [comment]
hey, @samajammin please can I work on this, it seems no want had worked on it. Thanks

**Comment by minimalsm** [comment]
Closing this out while we try to scope this a little better ☺️😬!
