### ISSUE TITLE
Add Link to Storj DCS Documentation

### ISSUE THREAD

**Issue by keleffew** [ethereum/ethereum-org-website#2929]
**Is your feature request related to a problem? Please describe.**

Storj documentation is not currently linked to in storage section

**Describe the solution you'd like**

Add Storj DCS documentation link alongside Filecoin, Arweave, Sia etc.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ryancreatescopy** [comment]
Hi @keleffew we have a template for suggesting a developer tool: [here](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=Type%3A+Feature%2C+Type%3A+Content&template=suggest_dev_tool.md&title=)

Please provide all the required information in this format please.

**Comment by wackerow** [comment]
(closed in #2930)
