### ISSUE TITLE
Eth2 upgrades banner layout

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2940]
**Describe the bug**

Should be center aligned, icon should not be stacked:
![Image 2021-04-26 at 8 36 08 PM](https://user-images.githubusercontent.com/8097623/116183178-4b346500-a6d2-11eb-9a8b-81ba5edf45be.jpg)

Like Eth2 homepage:
![Image 2021-04-26 at 9 00 04 PM](https://user-images.githubusercontent.com/8097623/116183259-6dc67e00-a6d2-11eb-8def-59718bea9bc0.jpg) 

**To Reproduce**

1. Go to https://ethereum.org/en/eth2/beacon-chain/

**Comment by wackerow** [comment]
@samajammin I'm not able to reproduce...

firefox:
![image](https://user-images.githubusercontent.com/54227730/116190582-c3edee00-a6df-11eb-81f4-d8e7ffad6ccd.png)
brave:
![image](https://user-images.githubusercontent.com/54227730/116190524-aae53d00-a6df-11eb-9557-36fefa0a0d8b.png)

Cache related?

**Comment by samajammin** [comment]
It happens to me when I navigate from one page to another - @wackerow can you see if that reproduces it for you?

https://user-images.githubusercontent.com/8097623/116938389-8f1df180-ac1f-11eb-93a9-f008f3c7d50a.mp4

If I refresh a page, it looks fine.

**Comment by wackerow** [comment]
Yeah actually, getting this specifically if I navigate to `/en/eth2/` then click to navigate to the Beacon Chain page
