### ISSUE TITLE
Eth2 Bug bounty does not list Nimbus

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#2943]
https://ethereum.org/en/eth2/get-involved/bug-bounty/ Nimbus is missing in the second section

**Comment by wackerow** [comment]
@tvanepps Thanks for raising this. Assuming you're talking about this section:
![image](https://user-images.githubusercontent.com/54227730/117740539-8005e900-b1b5-11eb-84c6-b707a19333ab.png)
Posting a patch for this now
