### ISSUE TITLE
Private key address problem

### ISSUE THREAD

**Issue by 805477481** [ethereum/ethereum-org-website#2963]
I have a 51 bit Ethereum private key address before the ETH fork a few years ago. Now the wallets on the market only support 64 bit private key addresses. Now I can only check the quantity in the wallet, but I can't trade. How can I transfer money? Thank you

**Comment by ryancreatescopy** [comment]
Hi @805477481 this is the repo for the ethereum.org website. Unfortunately we can't help you. Maybe try one of the ethereum sub reddits?
