### ISSUE TITLE
Missing margins on feedback widget

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#2974]
**Describe the bug**
No space between _contributor callout_ and _feedback widget_ on desktop size screen in the developer docs.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/gas/ on desktop
1. Scroll to bottom
1. Note lack of margins

**Expected behavior**
Margin giving space between contributor callout and the feedback widget

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/117063203-56dae980-acd9-11eb-8e32-044512b4e59d.png)

**Desktop (please complete the following information):**
Using macOS, Firefox and Brave (latest)

**Comment by DevAranCarter** [comment]
Hi wackerow,

Where would I go about finding this? I looked on the dit page for gas docs but it doesn't display. Tried looking for it through the other code but couldn't seem to find it?

Thanks,
D

**Comment by wackerow** [comment]
@DevAranCarter So all the "docs" pages use a react template, found in the repo at `/src/templates/docs.js`... in there you will see the `FeedbackCard` that was adjusted in the PR posted above. Obviously this one is fixed up now, but thanks for asking and looking into it! Sorry for the delay on getting back to you, hope this helps in the future.
