### ISSUE TITLE
CoinSpot Exchange Added to Page: https://ethereum.org/en/get-eth/

### ISSUE THREAD

**Issue by drcreamy** [ethereum/ethereum-org-website#2984]
Before suggesting an exchange, make sure you've read [our exchange listing policy](https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**
Only Australia for verified accounts.

**Which currencies are accepted by this exchange?**
Fiat: AUD
Cryptocurrencies: Over 300. Full list here: https://www.coinspot.com.au/tradecoins 

**Do you have any proof that they're a legitimate company?**
Blockchain Australia Certified Exchange: https://blockchainaustralia.org/member/member-profile-coinspot/
AML/CTF/KYC Compliant (This is required to operate in Australia: https://www.coinspot.com.au/aml 
AUSTRAC Regulated: https://www.austrac.gov.au/business/industry-specific-guidance/digital-currency-exchange-providers

**Do you have any extra information?**

CoinSpot has been operating since 2013 and has over one million Australian users, it is the largest exchange in Australia.
It also has the highest level of security based on it's external audits and ISO 27001 Certification: https://www.coinspot.com.au/security

Operating since 2013.
Largest exchange in Australia with over one million users.
Fully regulated.

**Comment by wackerow** [comment]
@drcreamy Thanks for posting this! We'll take a closer look and try to get back to you within a week or two. 👍🏻

**Comment by wackerow** [comment]
@drcreamy Just merged a PR listing CoinSpot 👍🏻 Thanks for requesting this and for bearing with us!
