### ISSUE TITLE
Article to tutorial about minting/selling on OpenSea

### ISSUE THREAD

**Issue by PeterRusznak** [ethereum/ethereum-org-website#2985]
Tutorial about minting your own ERC-721 Token and selling it on OpenSea

**Comment by PeterRusznak** [comment]
https://fullstackwithpr.hashnode.dev/scribble-on-canvas-and-sell-it-as-nft-react-truffle-ipfs-opensea

**Comment by wackerow** [comment]
@PeterRusznak Thanks for posting this! Were you thinking having this listed on the [community guides and resources](https://ethereum.org/en/learn/) page?

**Comment by wackerow** [comment]
@PeterRusznak Sorry for delays on this, circling back. I guess within that page, was there somewhere you had in mind? I'm looking through and it doesn't quiet seem to fit. This is a single tutorial for a specific platform, while the /learn page is primarily larger resources, or articles covering broader Ethereum topics. 

@samajammin Curious your thoughts on a potential home for this article.

**Comment by wackerow** [comment]
@minimalsm Circling back to this, any thoughts on a potential appropriate home for this one?

**Comment by minimalsm** [comment]
@wackerow I'll add this as an external tutorial once the functionality is implemented.

**Comment by minimalsm** [comment]
Circling back on this. Given our coverage of NFT tutorials on ethereum.org I don't think adding this tutorial makes sense anymore, as it doesn't have anything we don't already cover except listing on OpenSea, which isn't something I believe needs explained.
