### ISSUE TITLE
Make ethereum.org available on IPFS at ethereum.eth

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#300]
## Expected Behavior
Make ethereum.org available on IPFS at ethereum.eth

## Current Behavior
Does not exist

## Possible Solution
- Add it to IPFS!
- Questions
   - how to set up automation to continuously deploy updates?
   - set canonical to ethereum.org to avoid duplicate content?

## Context
Nice way to showcase this technology

**Comment by chopin2712** [comment]
Yes totally agree!

**Comment by bretware12** [comment]
When does this go live

**Comment by samajammin** [comment]
@bretware12 it's already live: https://twitter.com/vitalikbuterin/status/1244940021272064000?lang=en
