### ISSUE TITLE
Adding Kannada Language Support for Ethereum Website

### ISSUE THREAD

**Issue by manojmsrit** [ethereum/ethereum-org-website#3005]
Hello,

I can see that ethereum.org is available in multiple language including Indian languages such as Hindi, Malayalam. But I would like to request to add the Kannada language also. I can help in transalating. Kannada is one of the most spoken language in India with speakers volume up to 70-80 million. It is also one of the oldest Indian language. Most of the people in silicon valley of India (Bangalore) will speak Kannada. Thank you for understanding.Hope my request will be answered soon.

Thanks,
Manoj

**Comment by samajammin** [comment]
Thanks for this suggestion @manojmsrit! I've added Kannada to [our Crowdin project](https://crowdin.com/project/ethereumfoundation):
https://crowdin.com/project/ethereumfoundation/kn

Feel free to hop in & contribute 😄  - here's some information on how to get involved:
https://ethereum.org/en/contributing/translation-program/

Closing this issue out - let us know if you have any questions.

**Comment by samajammin** [comment]
@all-contributors please add @manojmsrit for ideas.

**Comment by manojmsrit** [comment]
Thank you :) Much appreciated.
