### ISSUE TITLE
Learn page: Ethereum energy consumption

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3020]
**Is your feature request related to a problem? Please describe.**

It's a well known critique on Ethereum/NFTs/blockchains generally.

**Describe the solution you'd like**

An open explanation of energy consumption. Why there's a trade-off for decentralization and why this won't be an issue with Eth2 moving to PoS.

**Describe alternatives you've considered**

Flesh out / optimize content on https://ethereum.org/en/eth2/vision/

**Additional context**

- Bankless folks offered to co-publish if we can find a writer: https://twitter.com/samonchain/status/1383120909624483841?s=20
- Great thread on Ethereum’s current state & roadmap https://twitter.com/smpalladino/status/1391901504752300033?s=21-Could be a good outline for “ethereum energy consumption” page

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Solid article by @CarlBeek that could serve as the foundation for this!
https://blog.ethereum.org/2021/05/18/country-power-no-more/

**Comment by heypran** [comment]
We can add a new list item in the `Learn` dropdown, linking to a separate page where we can showcase all the relevant energy consumption-related articles/resources. 

<img width="500" alt="Screenshot 2021-06-13 at 1 43 10 AM" src="https://user-images.githubusercontent.com/15847009/121789748-973b5a80-cbe9-11eb-9746-6d719db89793.png">

We can me the page something similar to the history page as below- 
<img width="832" alt="Screenshot 2021-06-13 at 1 47 51 AM" src="https://user-images.githubusercontent.com/15847009/121789812-44ae6e00-cbea-11eb-8aeb-2ddf85e3ca28.png">

**Comment by samajammin** [comment]
https://twitter.com/0xstark/status/1457823831360368640?s=20
