### ISSUE TITLE
Indian exchanges

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#3021]
From an email to website@

Worth checking at some point...

In India, you can also buy ethereum on the following exchanges --

- [x] ~www.wazirx.com~

- [ ] https://www.buyucoin.com/

- [ ] www.zebpay.com

**Comment by corwintines** [comment]
https://github.com/ethereum/ethereum-org-website/pull/5839

Some work has been done on this, but since this issue is quite stale going to close out. There are updated issue templates for this for exchanges to fill out if they want to be listed now.
