### ISSUE TITLE
Prepare for EIP-1559

### ISSUE THREAD

**Issue by carlfairclough** [ethereum/ethereum-org-website#3022]
**Is your feature request related to a problem? Please describe.**

As EIP-1559 is soon to become reality, we should update sources of information for users who dive into the "custom" part of transaction fees in wallets, or want to understand how transactions are included. Having potentially conflicting information fragmented across the knowledge bases of different wallets, using different terminology, could cause problems for users.

**Describe the solution you'd like**

We'd like to describe the new concepts and define wallet language via ethereum.org, which is a definitive source of information for both users, developers and products.

The developer resource should be updated: https://ethereum.org/en/developers/docs/gas/ but I also think there should/could be something user-oriented under the `learn` section.

**Describe alternatives you've considered**

We could publish at status.im, however we don't think that benefits the ecosystem.

**Additional context**

Currently we have `gas price` and `gas limit`. Many wallets have implemented this as `transaction speed`.

EIP-1559 involves replacing  `gas price` with:
- `Base fee (per gas, set by the network)`
- `Tip limit (per gas)`
- `Overall limit (per gas)`
`Gas limit` is retained.

The EIP focuses on `transaction priority` rather than `transaction speed`. This is consistent with how Ethereum functions, and as a part of the updates we should adopt this language across resources, with the expectation that Wallets will do the same.

**Comment by wackerow** [comment]
@carlfairclough I like this suggestion, is this something you were looking to contribute on? I would certainly be in favor of bringing some EIP-1559 related information to the dev docs

**Comment by qbzzt** [comment]
I'd love to take this one.

**Comment by samajammin** [comment]
Thanks for creating this issue @carlfairclough! I believe this has been solved in #3104 & #3509 among others.
