### ISSUE TITLE
Learn page: An intro to smart contracts

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#3023]
**Is your feature request related to a problem? Please describe.**

A newbie / non-technical intro to smart contracts

**Describe the solution you'd like**

A page that lives in our learn section that helps explain the potential and power of smart contracts. They are a fundamental part of Ethereum's USP so we should explain them in a way for users to understand. We currently only reference them in passing on other pages or include them in developer documentation...

Can discuss further when someone registers interest.

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Potential sources of inspiration
- https://github.com/ethereumbook/ethereumbook/blob/develop/07smart-contracts-solidity.asciidoc#what-is-a-smart-contract (CC license)
- https://docs.ethhub.io/ethereum-basics/what-is-ethereum/#what-are-smart-contracts-and-decentralized-applications (CC license)
- https://www.oobit.com/blog/what-are-ethereum-smart-contracts/
- https://www.investopedia.com/terms/s/smart-contracts.asp
- https://www.coindesk.com/learn/ethereum-101/ethereum-smart-contracts-work

**Comment by jkbishbish** [comment]
Hey, I could do a draft of this one too. Here's what I'm thinking of as an outline:

_General stuff_

**What's a smart contract**
- smart contracts are computer programs that run on ethereum (the network, not the coin)
- step-by-step, plain-language example of how a smart contract should work (like an auction or one of the other beginner solidity examples)
- defining smart contracts generally

**But...why?**
- allowing things other than transactions
- they automate things (program acts as intermediary)
- they help put things on the blockchain record

_Technical stuff_

**Computer science concepts**
- computers are systems (users, hardware, software) with levels
- programs are software (usually) written by users to tell hardware (or other software) what to do

**Ethereum's computer system**
- nodes and client software
- consensus rules
- transactions

**Contracts behave the same for everyone**
- define deterministic
- why this matters in a decentralized system like ethereum
- example

**A contract is born**
- how contracts get to the blockchain (bulleted example of a software development process)
- where they live (on their own addresses)
- how people can update them, make them expire, or switch them on and off
- opcodes (overview)

**Who owns a smart contract?**
- nobody basically
- adding the right to modify / send certain opcodes could give power similar to "ownership"

**Not so smart after all**
- they don't act on their own (i.e. they do what you build them to)
- transactions as triggers
- sample transaction

**how do you make your own smart contract?**
- brief look at elements of smart contracts (variables (if applicable), functions, etc.)
- data types
- special functions (constructor, fallback,  ???)

**What can they do?**
- defi
- other dapps
- underline the importance of identifying on/offchain processes (centralized exchanges, "statelessness", etc.)

**Do it now**
- easiest to learn more is by doing
- links to tutorials, remix, zombies, etc

**Further reading**
- nick szabo (nick would be getting pushed down to the footnotes, sorry nick!)
- https://ethervm.io/
- vyper and solidity docs
- smart contract development on other chains

**Comment by minimalsm** [comment]
@jkbishbish Hey! Are you still looking to work on this? If not I'd be happy to carry the torch on this one 🔥

**Comment by jkbishbish** [comment]
@minimalsm Hey! My bad! This kind of got away from me. Continuing the metaphor, I'm still hot to trot 🔥 I'll get a PR up in the next few hours
