### ISSUE TITLE
Learn page: Intro to Layer 2

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#3024]
**Is your feature request related to a problem? Please describe.**

What is this Layer 2 stuff that everyone keeps going on about on crypto twitter?

**Describe the solution you'd like**

A learn page that explains to users what L2 does in a non-technical way: e.g. more speed, cheaper fees. Explain how users still get the security of Ethereum and why we can't just make Ethereum L1 faster/cheaper. This will likely be a base for linking out to different L2 bridges when solutions start shipping to mainnet and users want a trusted place to get L2 funds.

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by leo-cuellar** [comment]
would like to be assigned to this issue
