### ISSUE TITLE
Learn page: what is decentralization?

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#3025]
**Is your feature request related to a problem? Please describe.**

A page that explains some of Ethereum's design principles around decentralization.

**Describe the solution you'd like**

A page that lives in our learn section that digs into what we mean by decentralization and decentralized services. It's not always clear to new users why it matters or what it even means. When you grasp this, the power of Ethereum becomes more apparent. So this could be a very useful way of pushing people further down the rabbit hole. 

Can discuss further when someone registers interest.

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by jkbishbish** [comment]
Hey Ryan, I'm interested in writing about this.  Here's an outline of what I think might work. Just quick brainstorming here so please forgive any typos:

### Main sections
Defining "decentralization"

- Building something where everyone can have input and no single authority can make major decisions
- Going beyond reactive definitions (focus on the fact that Ethereum has a purposeful, fromthegroundup mission to distribute resources and authority)
- Technical explanation of Ethereum network architecture
- Discussion of how the development community works

Other decentralization efforts that support what people do on Ethereum

- Oracle networks
- IPFS
- etc?

Challenges to Ethereum's decentralization

- Virtual machines on Amazon, etc.
- Centralized third parties (exchanges, service providers)

What people can do to help / to get involved

- Running light Ethereum nodes
- Running IPFS nodes
- Learning more about internet architecture
- etc?

### Possible other sections?
Centralization of the web

- How ISPs work
- DNS and similar services
- "Big Tech"
- Government authorities over infrastructure
- Private/semiprivate infrastructure companies that also provide consumer/business services

Decentralization is already here

- Other familiar decentralized tech

Security advantages / disadvantages

- Autonomy of decentralized computing/recordkeeping
- Dependence on participation

How to tell if something is decentralized / the extent of its decentralization

- (for blockchains) looking at what people need to do to participate in running/supporting the network
- (for services) Smart contract basics
- (for all open-source projects) Using github

**Comment by ryancreatescopy** [comment]
Hey @jkbishbish this looks like a great outline! I think comparing to heavily centralized companies is always a really good way to explain the benefits of decentralization, so I'd encourage that line of argument. 

I'd be comfortable if you wanted to do a first draft of this. Take a look at our recent use-case pages (https://ethereum/org/en/defi) to get a sense of our writing style... and remember we're aiming this content at beginners so if you **need** to use any jargon or technical language, make sure it's explained or (there's links to a beginner-friendly explanation).

Let me know if you're happy to get started.

**Comment by jkbishbish** [comment]
Yeah! Sounds great. I forked the depository and I'm using the link you sent as a template, if that works.

**Comment by qbzzt** [comment]
You might find part of this useful to take ideas from: https://github.com/qbzzt/etherdocs/blob/master/what_can_Ethereum_do.md
