### ISSUE TITLE
Add search to languages page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3036]
**Is your feature request related to a problem? Please describe.**

Request from Discord user - add search to the languages page:
https://ethereum.org/en/languages/

**Describe the solution you'd like**

Add a search input on the page that filters language results. Support search by both English & native language titles.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by cth0604** [comment]
Hi, I was looking through the project and I would love to contribute to this awesome project by tackling this issue!

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by ryancreatescopy** [comment]
sorry @himanshu007-creator @cth0604 just beat you to it. Thanks for your interest and hopefully you can find another issue that interests you.

**Comment by himanshu007-creator** [comment]
> sorry @himanshu007-creator @cth0604 just beat you to it. Thanks for your interest and hopefully you can find another issue that interests you.

Best of luck @cth0604 😄
