### ISSUE TITLE
Roadmap "Implemented features" showing spam issues that have been closed

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#3047]
**Describe the bug**
Currently, closed GitHub issues are being displayed on the Roadmap section of the site (as "implemented features"), even if these issues were spam. This potentially allows users to submit issues on this repo with titles that will be displayed on the live website, which poses potential security risks to our users (ie. soliciting funds to a 0x address).

**To Reproduce**

1. Go to https://ethereum.org/en/about/#roadmap
1. Scroll down to "Implemented features"
1. Notice that cards are a mix of closed PRs, and also closed issues. See screenshot below... ATM, there is a spam entry (this one is harmless).

**Expected behavior**

- This section should include PRs that have been merged into `dev` branch
- Whether or not to display issues is in question... At the least, issues that have been marked as spam on GitHub should be filtered out.
- If this isn't possible, I'd argue we don't need to show closed issues at all, and can just display the merged PRs. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/118308271-9acfaa80-b4a0-11eb-95b9-61ba94608107.png)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on this issue if you're interested in helping out with a PR.

**Comment by adi44** [comment]
I am interested

**Comment by adi44** [comment]
Would like working on

**Comment by Uttam-Singhh** [comment]
I would love to work on this issue!
Please assign me this task.

**Comment by wackerow** [comment]
Oh no, my bad.... I missed your reply @adi44... Did you still want to tackle this, or have you done any work on it yet? @Uttam-Singhh Going to reassign to adi44 in the meantime since this was the first response, but if anything changes I'll get you on here.

**Comment by Uttam-Singhh** [comment]
Yes

> Oh no, my bad.... I missed your reply @adi44... Did you still want to tackle this, or have you done any work on it yet? @Uttam-Singhh Going to reassign to adi44 in the meantime since this was the first response, but if anything changes I'll get you on here.

Oh ok! No Problem.
Please reassign this to me if nobody works on this.
Also @wackerow I am new to open source so can you please suggest some good first issues to work on.

**Comment by adi44** [comment]
> Oh no, my bad.... I missed your reply @adi44... Did you still want to tackle this, or have you done any work on it yet? @Uttam-Singhh Going to reassign to adi44 in the meantime since this was the first response, but if anything changes I'll get you on here.

I will be working on it

**Comment by wackerow** [comment]
![image](https://user-images.githubusercontent.com/54227730/120423331-10e86400-c31f-11eb-8bdf-b6ba23b5112f.png)

This is to my comment about the above PR not filtering out spam pull requests. The "Create Yi" PR was closed without merging, and marked as spam, yet it's showing up as an implemented feature. 

The "Implemented features" section should really only be showing PRs that have been merged into `dev` at the very least.

Alternatively, we could perhaps replace this table with the [latest release message](https://github.com/ethereum/ethereum-org-website/releases/latest).
