### ISSUE TITLE
Eth error in withdrawing cash through exchange fuction:underfined undefined! help me !

### ISSUE THREAD

**Issue by SayFireworks** [ethereum/ethereum-org-website#3054]
eth Collection address : 0x020aC1d930deD0B95623F9F399F5631E0b1c84f1
eth txid : 0xa81a01b3bbcab1f803148aa231899c33961f27ce5b18226ba40f6b2f068c916a
eth Sending address : 0xe603e99e96985536c95ab37cb1afa78dd43019be

Make sure there is no error in my Ethernet address. As evidenced by the screenshot, I hope to recover my loss, because I still have other digital currencies in the wallet of imtoken, and I need to pay eth to withdraw. Thank you.!!！！

![IMG_0512](https://user-images.githubusercontent.com/35683906/118354934-0d737f80-b5a0-11eb-80b4-5851a33f867b.PNG)
![IMG_0511](https://user-images.githubusercontent.com/35683906/118354963-36941000-b5a0-11eb-8ad2-b5163b77ca1b.PNG)
![IMG_0510](https://user-images.githubusercontent.com/35683906/118354969-38f66a00-b5a0-11eb-8a82-146dd9f28b86.PNG)

**Comment by wackerow** [comment]
@SayFireworks This wouldn't be something we can help with here. This repo is for development of the ethereum.org homepage and does not handle wallet or transaction issues. I would check out the ConsenLabs GitHub, makers of imToken https://github.com/consenlabs and see if they can help you with the wallet related issues =)
