### ISSUE TITLE
add WallETH

### ISSUE THREAD

**Issue by ligi** [ethereum/ethereum-org-website#3058]
**Is your wallet globally accessible?**

Yes

**Is your wallet custodial, non-custodial, or a hardware wallet?**

non-custodial and supports hardware wallets (TREZOR, KeepKey, KeyCard)

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

 * *Fully* Open Source ( https://github.com/walleth )
 * Dependency locking (https://github.com/walleth/walleth/blob/master/checksum.xml)
 * No JavaScript / npm usage (e.g. drastically reducing the chance to be attacked via malicious dependencies)
 * Hardware Wallet support
 * Device Security information screen (https://walleth.org/assets/img/screenshot-2.png)
 * [DappNode](https://dappnode.io) support
 * [Sourcify](https://sourcify.dev) support
 * Watch only account support
 * Limited attack surface by only being a wallet isolating features that can be outside the wallet to other apps and leverage Androids App-isolation this way (also see comments in sections below)

**Does the wallet have fiat on-ramps?**

no  (does not belong into a Wallet IMHO) - can be done outside the wallet

**Does the wallet allow users to explore dapps?**

Yes you can explore WalletConnect enabled dapps

**Does the wallet have integrated defi/financial tools?**

no (does not belong into a Wallet IMHO) - you can access these tools via WalletConnect

**Can a user withdraw to their card?**

no (does not belong into a Wallet IMHO) 

**Does the wallet offer limits protection?**

not yet

**Does the wallet allow high-volume purchases?**

yes - e.g. via uniswap via WalletConnect

**Does the wallet have an integrated token swap?**

no (does not belong into a Wallet IMHO) - can be done via WalletConnect

**Is the wallet a multi-signature wallet?**

not yet

**Wallet title**

WallETH

**Wallet description**

100% open source (GPLv3) and native Android Ethereum Wallet for your service since 2017. Connect to your favorite Ethereum Applications via WalletConnect and use it directly with hardware wallets like the TREZOR or KeepKey via USB or the KeyCard via NFC.

**Wallet logo**

![walleth_icon](https://user-images.githubusercontent.com/111600/118391593-56c1de80-b635-11eb-9cdd-50c6838f6bba.png)

**Background colour for brand logo**

0xFFFFFF

**Link**

https://walleth.org

**Comment by ryancreatescopy** [comment]
Thanks @ligi – @wackerow let's discuss this and get a PR up when we get some capacity. 

@ligi if you have time feel free to raise a PR as this may be faster at the moment with our current commitments.

**Comment by ligi** [comment]
Thanks for considering. I would see #2730 as a blocker for a PR - can you please reopen the issue? Unfortunately I cannot do this.

**Comment by ryancreatescopy** [comment]
Not sure it's necessarily a blocker but I've reopened nonetheless. As a heads up, I can't promise we'll have time to work on this for a while, however we are expanding our dev team very shortly so fingers crossed we can address this soon.

**Comment by minimalsm** [comment]
@ligi added a PR to add this. Can you confirm what I have below is correct:

{
   "id": "walleth",
   "name": "WallETH",
   "url": "https://walleth.org",
   "brand_color": "#FFF",
   "has_mobile": true,
   "has_desktop": false,
   "has_web": false,
   "has_hardware": false,
   "has_card_deposits": false,
   "has_explore_dapps": true,
   "has_defi_integrations": false,
   "has_bank_withdrawals": false,
   "has_limits_protection": false,
   "has_high_volume_purchases": true,
   "has_multisig": false,
   "has_dex_integrations": false
 }

**Comment by ligi** [comment]
thanks! Looks all good - just change `"has_high_volume_purchases": true,` to `"has_high_volume_purchases": false,` please.

**Comment by minimalsm** [comment]
> thanks! Looks all good - just change `"has_high_volume_purchases": true,` to `"has_high_volume_purchases": false,` please.

Done :]
