### ISSUE TITLE
Pressing enter in the search bar refreshes the page

### ISSUE THREAD

**Issue by Robiquet** [ethereum/ethereum-org-website#3059]
**Describe the bug**

Pressing enter in the search bar refreshes the page

**To Reproduce**

1. On the front page of ethereum.org click the search bar text field
2. Enter some text
3. Press enter

The page is refreshed

**Expected behavior**

I would expect either nothing to happen or to be navigated to the first result

**Desktop (please complete the following information):**

- Browser: Chrome, Firefox

Happy to put in a fix if someone on the team agrees it's a bug

**Comment by DavidPlutus** [comment]
+1 - I can recreate this on Brave

**Comment by minimalsm** [comment]
Fixing this
