### ISSUE TITLE
Link for 'Layer 2 scaling' is broken

### ISSUE THREAD

**Issue by Robiquet** [ethereum/ethereum-org-website#3060]
**Describe the bug**

After searching for 'layer 2' and selecting the top result I am navigated to a 'resource not found' page

**To Reproduce**

1. On the front page of ethereum.org enter 'layer 2' into the search bar
2. Select the first result (Layer 2 scaling)

Resource not found page is displayed

**Expected behavior**

Instead of navigating here: https://ethereum.org/en/developers/docs/layer-2-scaling/#top
I think we should navigate to here: https://ethereum.org/en/developers/docs/layer-2-scaling/

Happy to put in a fix if the team agrees the expected behaviour is correct

**Comment by wackerow** [comment]
Sounds good 👍🏻 Thanks for catching this =)

**Comment by Robiquet** [comment]
@wackerow looks like this is working now, maybe I was running an old cached version

**Comment by wackerow** [comment]
@Robiquet cool, I think you may be right... I had the same issue yesterday, but similarly it went away after a cache clear. Thanks for touching base 👍🏻

**Comment by jley81** [comment]
@Robiquet Agreed  #[](https://ethereum.org/en/developers/docs/layer-2-scaling/[](url))
