### ISSUE TITLE
Add Marathi language (code: mr)  translation to the website

### ISSUE THREAD

**Issue by vj-codes** [ethereum/ethereum-org-website#3066]
**Is your feature request related to a problem? Please describe.**
Marathi is one of the popular spoken language in India and the website doesn't have a translated version of it.

**Describe the solution you'd like**
Add a translated Marathi version 

**Describe alternatives you've considered**
No alternative

**Want to contribute?**
Yes I would like to work on this

**Comment by vj-codes** [comment]
@GeorgeTrotter @samajammin I would like to work on this if approved

**Comment by rukuiza** [comment]
Absolutely it should get translated! It gets done here: https://crowdin.com/project/ethereumfoundation

**Comment by minimalsm** [comment]
For interested in translating into Marathi this has been added to our CrowdIn - https://crowdin.com/project/ethereumfoundation/mr#
