### ISSUE TITLE
Oracle-based recovery of Genesis Ether

### ISSUE THREAD

**Issue by mindey** [ethereum/ethereum-org-website#3069]
**Is your feature request related to a problem? Please describe.**

Hello. I'm one of the contributors to the Ethereum genesis pre-sale (total `3325.11 ETH`), and bought the pre-sale Ethereum on [ethereum.org](https://ethereum.org]) website with Bitcoin twice: [[1]](https://etherscan.io/address/0x992646ac1acaabf5ddaba8f9429aa6a94e7496a7), [[2]](https://etherscan.io/address/0xc4088c025f3e85013f5439fb3440a17301e544fe), via BTC addresses `12bVTNKjRQkZDHmJfarppXMS1vfxr3AwJX` [[tx]](https://www.blockchain.com/btc/tx/953414d753bac42bdedc973dd0e7457a0b413019890589b9402e582106907e82) and `17y1XWUyEo4wrwsML5GetaXznRoADgXBsp` [[tx]](https://www.blockchain.com/btc/tx/e9ceb3c301661a12f9827924f2fd21f01cddcda7bd03e0701509a51e60898a1b) respectively, both associated with my alternate e-mail address `3stdminds@gmail.com`, where I have original purchase confirmation e-mails that came from `confirmation@sale.ethereum.org`, including encrypted wallets that were sent to it. Unfortunately, I have lost part of the password that I used to create the `encseed`, when Ethereum.org was running [pyethtool](https://github.com/tagawa/website/blob/master/pyethtool/pyethtool.py). Encouraged by the words on the sale site, I had made the password really long (I guess approx 64 chars long), and split it into two parts, one part on a paper (that I still have), and another part on computer (that I lost irrecoverably).

**Describe the solution you'd like**

Being an optimist, back in 2016, when I realized that I have a problem, I thought -- since Ether supports smart contracts, we should be able to make a smart contract between my new verified identity (for example, I've recently verified my domain by issuing a token https://etherscan.io/token/0x16e0d4494c6538fa5a461ed086dd44b15d708461), and the Ethereum.org organization, relying on a few oracles, like `Bitcoin` chain as oracle, `Gmail` as an oracle, and any other thing, where information about that had remained. For example, I made the two bitcoin transactions by first transferring my Bitcoin to Cryptsy.com (that exchange doesn't exist anymore), but, if the database of the accounts and associated wallets with transactions still exist, I could prove that it came from the account that I possess, and that it was credited from another bitcoin address, the private key of which I do possess as well.

So, the solution I'd like is the pre-sale Ether recovery based on a smart contract relying on external oracles and facts. It could be a feature of Ethereum.org site, where user comes with a MetaMask, and then provides data for proving facts. The way how this re-assignment of coins could happen, would be up for developer developers and miners to decide, -- it is either re-assigning of the original Ether, or creating new Ether in compensation, connected to the old address.

**Describe alternatives you've considered**

I remember the incident in the early times of Ethereum, when Ethereum was forked for similar reason, when a transaction equivalent to $50 M worth of Ether went to a wrong address. In my case, it's much smaller amount, and the network had progressed to block number... `12453718`. :)

**Additional context**

I'd like is a feature that solves the problem not just for myself, but in general. I think oracles-based smart contract-based asset recovery could be an option on the website.

**Want to contribute?**

// We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

Sure, I'd love to look into what possible smart contract could exist to solve this issue, and then contribute to helping write the necessary details in code. However, at this point I don't have a PR that would just magically solve this issue.

**Comment by wackerow** [comment]
@mindey I'm sorry this happened. I'm not sure this is something we can help you with in this repo though, as this repo is strictly for the development of the ethereum.org homepage. I personally don't see any way these funds can be recovered if the password to the encrypted seed is missing, but you may have more luck asking over at the Eth R&D discord https://discord.gg/mncqtgVSVw ... Some of the issues you're alluding to, such as identity issues, are complex issues being worked on in the community and I'd encourage you to hop into the conversations =)

(Going to close this for now, feel free to re-open if I misunderstood something)

**Comment by mindey** [comment]
@wackerow Thanks, I'll try contacting the Eth R&D discord. The original Ether pre-sale has [happened](https://web.archive.org/web/20140815223959/https://www.ethereum.org/) on the ethereum.org website, and therefore, I believe the best place for recovery options is on ethereum.org site. My suggestion is to realize such option for those who invested into Ethereum, and that is why the issue here.
