### ISSUE TITLE
Include Carl's energy article on NFT page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#3072]
https://blog.ethereum.org/2021/05/18/country-power-no-more/

We should align the calculations if possible and/or just link to it as another resource. 

We can also use this to help form the energy page on ethereum.org

**Comment by samajammin** [comment]
Agreed! Relevant to #3020 as well.

**Comment by minimalsm** [comment]
Closed in #3777 😬
