### ISSUE TITLE
Link on 'Token Standards' Page is broken

### ISSUE THREAD

**Issue by jcpickett1** [ethereum/ethereum-org-website#3073]
**Describe the bug**
On the 'Token Standards' page, a related tutorial link to 'Transfers and approval of ERC20 tokens from a Solidity smart contract' is missing a hyphen and 404s.

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/standards/tokens/#related-tutorials'
2. Click on 'Transfers and approval of ERC20 tokens from a Solidity smart contract'
3. See error

**Expected behavior**

Expectation is to be redirected to the article URL: 'https://ethereum.org/en/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/'

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 88.01

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by jcpickett1** [comment]
I can submit a PR for this issue

**Comment by wackerow** [comment]
@jcpickett1 Thanks for surfacing this.. hah, sorry, went ahead and patched this one but thanks for offering =)
