### ISSUE TITLE
Transfers and Approval Tutorial; Image Discrepancy

### ISSUE THREAD

**Issue by nadroj-olletsoc** [ethereum/ethereum-org-website#3079]
The image within The Sell Function section should be an example of a transaction with a Sold event, not a Bought event. Similarly, the "to" field in the image should refer to DEX.sell(), not DEX.buy().

The image file within The Sell Function appears to be the same image used in The Buy Function (https://ethereum.org/static/0789b512ac67511f04564aed1d2d3378/a13c9/transfer-and-bought-events.png).

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/#the-sell-function
2. Scroll down to the text "If everything works you should see 2 events (a Transfer and Sold)..."
3. Observe image following the paragraph from step 2

**Expected behavior**

Expect image to display transaction data which displays a Sold event.

**Screenshots**

Screenshot of current paragraph and image in the sell function section:

![image](https://user-images.githubusercontent.com/58618826/119022645-e08fe580-b96e-11eb-8022-1ce55bedbd34.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome
- Version: 90

**Comment by adi44** [comment]
@wackerow I would like to work on this

**Comment by wackerow** [comment]
@adi44 Hey, any update on this? If you'd prefer to let someone else work on it just un-assign yourself 👍🏻

**Comment by minimalsm** [comment]
Hey @adi44 :) I'm unassigning you for now. Feel free to give us a shout if you still want to tackle this, otherwise, this is open for anyone to have a shot at.

**Comment by TrevorFrench** [comment]
@minimalsm it looks like @wackerow might have already updated this.
![ethdotorg](https://user-images.githubusercontent.com/42419234/133847669-1731c068-fa10-473f-a3d8-9080d44f88a2.PNG)
![ethdotorg2](https://user-images.githubusercontent.com/42419234/133847808-154c105a-59e6-431a-a321-e2bc77cb5984.PNG)

**Comment by minimalsm** [comment]
@TrevorFrench Indeed it is, thanks 😀!
