### ISSUE TITLE
"Yarn" or "Yarn Install" failing on Windows

### ISSUE THREAD

**Issue by Uttam-Singhh** [ethereum/ethereum-org-website#3080]
I was following the process to clone the repo and install dependencies.
But when I used the command - `yarn` or `yarn install` for installing dependencies.

so After running for sometime it gave Error which was - 
`error An unexpected error occurred: "C:\\Users\\Dell\\AppData\\Local\\Yarn\\Cache\\v6\\npm-p-cancelable-1.1.0-d078d15a3af409220c886f1d9a0ca2e441ab26cc-integrity\\node_modules\\p-cancelable\\.yarn-metadata.json: Unexpected end of JSON input".`

![Screenshot (32)](https://user-images.githubusercontent.com/63050765/119036229-2334da80-b9ce-11eb-84ea-14ef1d3f48fb.png)

I tried to run it again but it gave the same error every time. I don't really know whether this is a BUG or not.

**Comment by minimalsm** [comment]
Potentially corrupt cache.. Could you try 
```yarn cache clean```
then 
```yarn install```

**Comment by Uttam-Singhh** [comment]
> yarn cache clean

Thanks for your help @minimalsm but it's not working.

**Comment by Uttam-Singhh** [comment]
Please let me know what else I can do.

**Comment by wackerow** [comment]
@Uttam-Singhh hm... I'm not positive what's going on there... but I also see stuff about network connection? Are you sure `yarn` is able to connect and fetch the packages? I'm not sure this is a bug with this repo. @samajammin ?

**Comment by samajammin** [comment]
Hmmmm ya not too sure. My first attempt it was @minimalsm recommended, I'd try wiping your /node_modules/ directory & trying again.

@Uttam-Singhh what version of node are you running?

**Comment by Uttam-Singhh** [comment]
Thank you @samajammin and @wackerow. 
I don't how but it's working now maybe `yarn cache clean`  worked.

**Comment by Uttam-Singhh** [comment]
Closing the issue!

**Comment by samajammin** [comment]
Glad to hear!
