### ISSUE TITLE
No Link to Discord in Community Tab - https://ethereum.org/en/community/

### ISSUE THREAD

**Issue by DavidPlutus** [ethereum/ethereum-org-website#3083]
**Is your feature request related to a problem? Please describe.**

There is no link to the ethereum.org Discord on the [Community section ](https://ethereum.org/en/community/) of ethereum.org 

**Describe the solution you'd like**

Add this link (https://discord.gg/CetY6Y4) in the 'Chat Rooms' section of the [Community tab](https://ethereum.org/en/community/) on ethereum.org

**Suggested Implementation**

[Ethereum.org Discord Server](https://ethereum.org/en/community/) - _A place to discuss all things ethereum.org and contribute to the Ethereum educational repository_

Place it above the ETH R&D Discord Channel link for maximum exposure

![image](https://user-images.githubusercontent.com/63456936/119052143-0d1e1e80-b9bc-11eb-872e-1c76879b0285.png)

**Describe alternatives you've considered**

Although the Discord link is clearly displayed in the footer of the website, it'd make sense to include it in the collated chat rooms in the Community tab

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
One argument for not including this is that our discord is primarily concerned with the development of the Ethereum.org website, rather than the Ethereum blockchain itself.

Playing devil's advocate - I'm pretty neutral on it either way.

**Comment by DavidPlutus** [comment]
> One argument for not including this is that our discord is primarily concerned with the development of the Ethereum.org website, rather than the Ethereum blockchain itself.
> 
> Playing devil's advocate - I'm pretty neutral on it either way.

From a user POV I was looking for the .org Discord and that's the first place I headed, had to do some (albeit very little) searching to find it - but I get it, depends what the overarching goal of the **Community** tab is
