### ISSUE TITLE
Assets missing from Asset Page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3110]
After linking a user on discord to the assets page I noticed that quite a few of them aren't included on this page (like the awesome one on the [DeFi page](https://ethereum.org/en/defi/) or the eth2 rhino).

**To Reproduce**

1. Go to https://ethereum.org/en/assets/
2. See missing assets

--------
Edit:

### Assets to be added

- [x] [Eth2 Rhino](https://ethereum.org/static/50d8cb4568b509f5b76f877c89cdee33/f3dec/eth2_rhino.png)
 - actually not sure about the rights for this image, so best we leave it off for now
- [x] [Oldship](https://ethereum.org/static/a2122b00761e964ee0084399f5e2da3c/5707d/oldship.png)
 -  artist: Viktor Hachmang (https://viktorhachmang.nl)
- [x] [Sharding](https://ethereum.org/static/a0f00bb81aaf3743c3d42c8270451781/34ae2/newrings.png)
 - artist: Viktor Hachmang (https://viktorhachmang.nl)
- [x] [The Merge](https://ethereum.org/static/5d3af9eb308978e7a078bf51022d8a5c/f3dec/merge.png)
 - artist: Viktor Hachmang (https://viktorhachmang.nl)
- [x] [Stablecoins](https://ethereum.org/static/21501e8dfa2f42d8260c096e21d8dbb4/aff26/hero.png)
 - a comp I did so not really an official image.
- [x] [Finance](https://ethereum.org/static/0453c88b09ddaa2c7e7552840c650ad2/f3583/finance_transparent.png)
 - artist: William Tempest (https://cargocollective.com/willtempest) I think... will confirm
- [x] [Future](https://ethereum.org/static/754d2f72ce2296fb59d9d974aeda16be/96d01/future_transparent.png)
 - artist: William Tempest (https://cargocollective.com/willtempest) I think... will confirm
- [x] [Infrastructure](https://ethereum.org/static/a44134e541c72364beb121234ab5864e/d7c05/infrastructure_transparent.png)
 - artist: William Tempest (https://cargocollective.com/willtempest) I think... will confirm
- [x] [Impact](https://ethereum.org/static/4d030a46f561e5c754cabfc1a97528ff/8f8aa/impact_transparent.png)
 - artist: William Tempest (https://cargocollective.com/willtempest) I think... will confirm
- [x] [Magicians](https://ethereum.org/static/4148f16065ce432f2390708eef5a0011/2a4de/magicians.png)
 - cut out from landing page image 
- [x] [Beacon Chain](https://ethereum.org/static/33fc191428d18ac5239516b5d37036a5/34ae2/core.png)
 - artist: Viktor Hachmang (https://viktorhachmang.nl)
- [x] [Enterprise](https://ethereum.org/static/26947bda5fcbe2ce830caa46bd5bd02d/7a6cf/enterprise.png)
 - cut out from landing page image 
- [x] [Eth Gif Cat](https://ethereum.org/static/c3104a17c4e8d8c9679e4ad1e5945f93/4ea59/eth-gif-cat.png)
 - intentionally not included for now...
- [x] [DeFi hero](https://ethereum.org/static/9c53e2b9d16ad28a02d9292f0fb6b943/3e8a5/defi.png)
 - artist: Patrick Atkins (https://patrickatkins.co.uk)
- [x] [DAO hero](https://ethereum.org/static/d17b5ecb3655c50d6540e590a93d65e7/3e8a5/dao-2.png)
 - artist: Patrick Atkins (https://patrickatkins.co.uk)

**Comment by ryancreatescopy** [comment]
Hi @minimalsm certainly not intentional, we just haven't got round to adding them. Is this something you want to have a go at?

**Comment by minimalsm** [comment]
> Hi @minimalsm certainly not intentional, we just haven't got round to adding them. Is this something you want to have a go at?

Yeah I'll do it. I'll come back to you later today with what assets I need more information on.

**Comment by minimalsm** [comment]
@ryancreatescopy edited the original issue to include the missing assets.

**Comment by ryancreatescopy** [comment]
@minimalsm hopefully this is all the info you need right now

**Comment by minimalsm** [comment]
Thanks Ryan, will get this done over the weekend.
