### ISSUE TITLE
Update README for latest local dev instructions

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3123]
**Is your feature request related to a problem? Please describe.**

Saw a question in Discord about setting up API keys:

> Hello guys , does anyone know where i could find the API keys for DeFiPulse  and Etherscan , working on some charts atm and i need them to continue , Thanks !

**Describe the solution you'd like**

We should include instructions on how to set up personal API keys:

> Easiest approach is probably to create your own API keys for devlopment purposes, then add those values in your .env
> https://docs.defipulse.com/quick-start-guide
> https://etherscan.io/apis

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Happy to do this if no one else is already working on it.

Am I right in thinking it is only the ```DEFI_PULSE_API_KEY``` and ```ETHERSCAN_API_KEY``` to be added?
