### ISSUE TITLE
Eth2 translated page are now outdated

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3128]
**Is your feature request related to a problem? Please describe.**

Since merge updates #2933 the translation content is now outdated.

**Describe the solution you'd like**

Mark these translated pages as outdated (in gatsby-node.js) so we display the banner that links to the latest English content.

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vj-codes** [comment]
@minimalsm I would like to work on this!

**Comment by SNikhill** [comment]
@samajammin 

Sir, if I understand it correctly, you are saying that due to the changes in content for eth2 pages (Available under: https://ethereum.org/en/eth2),
all the translations are outdated?

**Comment by minimalsm** [comment]
This was solved with our translations refactor
