### ISSUE TITLE
Add hover effect to the Tooltip

### ISSUE THREAD

**Issue by Uttam-Singhh** [ethereum/ethereum-org-website#3139]
Add hover effect to the Tooltip so that the content is visible when hovering over the I button.

Before: 
![IMG_20210526_230715](https://user-images.githubusercontent.com/63050765/119706858-1e61a200-be78-11eb-8d2b-179b9631a64d.jpg)

After:
![IMG_20210526_230736](https://user-images.githubusercontent.com/63050765/119706802-0d189580-be78-11eb-9a91-ff63e2d78213.jpg)

**Comment by wackerow** [comment]
@Uttam-Singhh The above PR is merged, but will keep this open in the meantime per [my comment on that thread](https://github.com/ethereum/ethereum-org-website/pull/3140#issuecomment-856165135). If you feel this issue still needs work, will keep open.
