### ISSUE TITLE
Bulgarian language not supported on ethereum.org

### ISSUE THREAD

**Issue by lachoj** [ethereum/ethereum-org-website#314]
## Your Environment

- Browser name and version:
- Device, operating system and version:

**Comment by sorumfactory** [comment]
Hello @lachoj 	
Thank you for your thoughtful suggestion.
We just added the Bulgarian language on Crowdin!
[](https://crowdin.com/project/ethereumfoundation/bg#)

Please feel free to jump in at any time:)

**Comment by sorumfactory** [comment]
Hello @lachoj
Thank you for your thoughtful suggestion.
We just added the Bulgarian language on Crowdin!
https://crowdin.com/project/ethereumfoundation/bg#
Please feel free to jump in at any time:)

**Comment by samajammin** [comment]
As @sorumfactory mentioned, we manage translations via a platform called CrowdIn. You can join our project here:
https://crowdin.com/project/ethereumfoundation/invite

Once you join, you can begin translating immediately here:
https://crowdin.com/project/ethereumfoundation/bg#

You can learn more about our Translation Program here:
https://ethereum.org/languages/

Let us know if you have any questions! Looking forward to getting your translations on ethereum.org!
