### ISSUE TITLE
Subscribe to blog posts button

### ISSUE THREAD

**Issue by nigelp** [ethereum/ethereum-org-website#3146]
It would be great to be able to subscribe to Ethereum Foundation blog posts on the site. https://blog.ethereum.org/

But there is no way to do that at the moment? 

Thanks.

**Comment by minimalsm** [comment]
Agreed! But, I don't think the blog is operated from within this repo. I've posted the question to the Eth R&D discord asking who we could pass this request along to.

**Comment by samajammin** [comment]
Thanks for raising this issue @nigelp! I'll pass this along to the team who manages the blog.

Closing this out for now.

**Comment by nigelp** [comment]
Thanks. :)

**Comment by samajammin** [comment]
FYI @nigelp there is an RSS feed: https://blog.ethereum.org/feed.xml

Probably the best short term solution is to use your own reader that can consume RSS feeds. That would allow you to get notified of new posts.
