### ISSUE TITLE
Add "no-deception" as must-have criteria to  "The decision framework"

### ISSUE THREAD

**Issue by ligi** [ethereum/ethereum-org-website#3150]
Background: I think trust wallet should be removed as a wallet from ethereum.org as they actively lie to their users by stating they are open-source:

![image](https://user-images.githubusercontent.com/111600/119901880-c47bdd80-bf46-11eb-8a3e-8185f0e8b67a.png)

But in fact their android app is not.
I tried to raise that with them without success: https://twitter.com/mr_ligi/status/1393653155116769282
Not really sure what more to do - but I really think this wallet should not be linked on ethereum.org
But currently I see no actual rule in the decision framework to remove an app on that reason - so starting here.

**Comment by wackerow** [comment]
Hey @ligi, sorry for delays on this. Certainly not everything needs to be 100% open source, but I agree regarding your point about the deception. Will bring this up at our meeting and get back to ya, cc @samajammin @GeorgeTrotter

**Comment by samajammin** [comment]
Yes thanks for raising this @ligi!

I agree we should take steps to investigate this. I've also tried getting in touch with them:
https://twitter.com/samonchain/status/1408097675854028800

It's clear that at least _some_ of their source code is open source:
https://github.com/trustwallet

I'm not clear if their android code is though. This appears to be part of it:
https://github.com/trustwallet/wallet-core

**Comment by ligi** [comment]
thanks for looking into this. But I really think everything needs to be open source. IMHO there is no real value in just open sourcing parts. Because then you can just hide the crimes in the closed part ..

**Comment by wackerow** [comment]
Hey @ligi, sorry for delays on this... just added a PR to add some wording to our `adding-product` guide about falsified information. 

This does not solve the issue with Trust Wallet specifically... Revisited that Tweet thread and looks like nothing came of it. Any update on this from your end? Have we found where the android app source-code is provided, or any hard evidence it's not?
