### ISSUE TITLE
Glossary suggestion: Meme Crypto Currency

### ISSUE THREAD

**Issue by ThePrudentPatriot** [ethereum/ethereum-org-website#3151]
Meme Coins are Crypto currencies that were created as a joke or after a popular Meme. Example of a Meme Coin is Doge Coin. Or Shiba Inu. Both of these coins were created as a joke, but then became popular online. As their popularity grew, so did the value of their currency. Doge reached a price as high as .67 cents. After starting off lower than a penny.

**Comment by ryancreatescopy** [comment]
See response #3152
