### ISSUE TITLE
Glossary suggestion: FUD 

### ISSUE THREAD

**Issue by ThePrudentPatriot** [ethereum/ethereum-org-website#3155]
FUD is the acronym for Fear, Uncertainty, and Doubt. FUD occurs when the media or popular figureheads spread disinformation about something, to drive down the price. This practice has most recently been seen used by Elon Musk. Like when he said that Bitcoin is not friendly to the environment.  The price plummeted.

**Comment by ryancreatescopy** [comment]
I reopened your earlier issue, please consolidate the two definitions and close out the redundant issue, thanks!
