### ISSUE TITLE
Tutorial - CREATE AND DEPLOY A DEFI APP

### ISSUE THREAD

**Issue by sjschweber** [ethereum/ethereum-org-website#3161]
**Describe the bug**

Coding along the "CREATE AND DEPLOY A DEFI APP" tutorial on the Ethereum tutorials page, when I run `truffle compile` I'm getting a solc version error. I've tried specifying the version in my truffle-config.js file, but still getting the same error.

**To Reproduce**

1. Go to the tutorial at this [link](https://ethereum.org/en/developers/tutorials/create-and-deploy-a-defi-app/#install-truffle-and-ganache)
2. Download all the requirements for the tutorial(truffle and ganache)
3. Follow steps in the tutorial and once you reach the part where you are prompted to run `truffle compile` you should see the same error.

**Expected behavior**

Expect the program to compile correctly.

**Screenshots**

<img width="726" alt="Screen Shot 2021-05-29 at 10 24 59 PM" src="https://user-images.githubusercontent.com/32683112/120089924-b5bf3300-c0cc-11eb-919c-6fd36843036c.png">

**Desktop (please complete the following information):**

- OS: [macOS Catalina]
- Browser [Chrome]
- Version 90.0.4430.212 (Official Build) (x86_64)

**Additional context**

I tried downgrading my truffle version, as well as my openzepplin to solidity 0.5, and also changing the config settings to version 0.5.0, but then got another error: 

<img width="728" alt="Screen Shot 2021-05-29 at 10 28 32 PM" src="https://user-images.githubusercontent.com/32683112/120090009-354d0200-c0cd-11eb-85e5-1fc2130b4882.png">

**Comment by jid** [comment]
Tutorial should be updated, but for now you can set compiler version to ^0.8.0 (in truffle_config.js).

The @openzeppelin/contracts/token/ERC20/ERC20.sol requires solidity compiler in version ^0.8.0. This will change in the future releases of ERC20.sol implementation.

**Comment by minimalsm** [comment]
Closed by #4146
