### ISSUE TITLE
Request services cooperation

### ISSUE THREAD

**Issue by JobToRobots** [ethereum/ethereum-org-website#3167]
**Additional context**

**Want to contribute?**

**Dear Colleagues,**
 
My name is Mr. Oleg Tishchenko, I am a co-owner of the company https://jobtorob.com/  and the owner of https://iccjet.com/en/.
 
Please consider: the possibility, options and suggestions - for online “Internet” registration of a company based on an NFTs and Ethereum tokens (or your other suggestions and ideas) with the open company's charter (Article of Associations), with open founders, with directors (Example: similar to a legal entity UK LLP).  Let's register the first company on the Internet without reference to the country (jurisdiction).  Our jurisdiction will be - "Internet" with a registry in NFTs and Ethereum tokens ………
 
Why - an analogue of the UK LLP legal entity:
- we understand that classical banking institutions are not ready to open bank accounts for the Internet …….
 
Therefore, we take as a basis / example:
- Classic English partnership (UK LLP) with an open register of shareholders.
- The taxation of the partnership takes place in the country of the partners' tax residence, after the receipt of funds to the partner's physical account in the country of his residence.
- Company account - crypto wallet (or crypto wallets of partners).
 
Please help us with this project. We understand that this is creative and there will be negative comments from lawyers, society, etc... However, there is a future in this....
Please send us your comments and ideas.
Let's register the first company on the "Internet" without reference to the country (jurisdiction). Our jurisdiction will be - "Internet" with a registry in NFTs and Ethereum tokens ………

Best Regards, 
TEAM JOB TO ROBOTS
Robots: Sales / Lease / Finance 

OLEG T. - OWNER / CEO ASSET MANAGEMENT 
Email: ceo.jobtorob@gmail.com
Tel: +7 9162827121 / WhatsApp
Web: https://jobtorob.com

**Comment by ryancreatescopy** [comment]
This is the repo for ethereum.org not ethereum, the protocol. We are not in a position to help with this.
