### ISSUE TITLE
Include Books/Podcasts in Resources

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3181]
A discussion about Ethereum/Crypto related books on discord made me wonder why we aren't recommending any. I think a lot of value can be added by pointing users to resources that they can consume away from their computer.

**Describe the solution you'd like**

Create a section on https://ethereum.org/en/learn/ for books and/or podcasts.

**Additional Context**
Some potential books to get us started.

Books
- The Infinite Machine
- Out of the Ether
- The Age of Cryptocurrency
- The Truth Machine
- Digital Gold
- Kings of Crypto

Podcasts
- Into the Ether
- Bankless

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by TrevorFrench** [comment]
I'd like to work on this item!

**Comment by samajammin** [comment]
Thanks @TrevorFrench! Feel free to take a swing at this 😃 

A few of my favorite crypto podcasts (in addition to the ones mentioned)...
- Uncommon Core
- Zero Knowledge
- Epicenter
- Unchained

**Comment by corwintines** [comment]
Commented in the PR, but also thinks its worthwhile adding a more developer focused book: https://github.com/ethereumbook/ethereumbook
