### ISSUE TITLE
Day mode on Firefox text

### ISSUE THREAD

**Issue by NukeManDan** [ethereum/ethereum-org-website#32]
Day mode on Firefox - the button text is near illegible. 

![image](https://user-images.githubusercontent.com/35669742/57006032-7c890180-6b9a-11e9-9fba-a40003af8cc0.png)

66.0.3 (64-bit) on Manjaro Linux

**Comment by alancwoo** [comment]
@NukeManDan thanks for the note, would it be possible for you to check the branch `iss-32` and see if it fixes the issue for you? I'm on FF on Ubuntu which doesn't seem to have this problem, but I imagine it just required some forced button styling

**Comment by alancwoo** [comment]
@NukeManDan Just FYI, this branch has been merged and deleted, let us know if you still have issues!
