### ISSUE TITLE
Unescaped Asterisks

### ISSUE THREAD

**Issue by TheBicPen** [ethereum/ethereum-org-website#3202]
**Describe the bug**

Asterisks are not escaped, causing them to be interpreted as italic styling

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/gas/
2. Scroll down to 'Total fee will be:'
3. See 'Total fee will be: Gas units Gas price per unit i.e 21000 200 = 4,200,000 Gwei or 0.0042 ETH'

**Expected behavior**

'Total fee will be: Gas units * Gas price per unit i.e 21000 * 200 = 4,200,000 Gwei or 0.0042 ETH'

**Screenshots**
![image](https://user-images.githubusercontent.com/23622288/120942746-c6306880-c6df-11eb-9add-238a3b7d896c.png)

**Desktop (please complete the following information):**

- Browser: Firefox
- Version: 89

**Additional context**

**Want to contribute?**

Should be a 1-line fix so I think I can take care of it

**Comment by TheBicPen** [comment]
I can fix this issue

**Comment by Aivolt1** [comment]
Sorry everyone I haven’t been able to communicate much, I keep getting  spamed some of the documents they have managed to access. I’m recovering the files, and will be opening a new repository soon. As the white paper and solidly ul diagram has been compromised. So I have been up trying to work on the main frame code.sorry for the inconvenience. I appretiate the work the community is putting into this. 



Sent from App for Gmail


Monday, 7 June 2021, 00:05 +0100 from ***@***.***  ***@***.***>:

**Comment by Aivolt1** [comment]
All systems linked are functioning, a slight relay has occurred causing a malfunction however still seems to be above the 90% range. 



Sent from App for Gmail


Monday, 7 June 2021, 00:05 +0100 from ***@***.***  ***@***.***>:

**Comment by Aivolt1** [comment]
I deployed the contract as an open source you should be able to to set those changees but that might not be the problem. 



Sent from App for Gmail


Monday, 7 June 2021, 00:04 +0100 from ***@***.***  ***@***.***>:

**Comment by ryancreatescopy** [comment]
Fixed by #3203
