### ISSUE TITLE
Add Erigon/Turbogeth to list of Eth1 clients

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3207]
**Is your feature request related to a problem? Please describe.**

We don't currently list Erigon/Turbogeth:
https://ethereum.org/en/developers/docs/nodes-and-clients/#clients

**Describe the solution you'd like**

- [ ] Confirm the client meets listing policy criteria: https://ethereum.org/en/contributing/adding-developer-tools/
- [ ] If it does, add it to the client table on https://ethereum.org/en/developers/docs/nodes-and-clients/#clients

**Describe alternatives you've considered**

None

**Additional context**

See discussion: https://twitter.com/DylanCaponi/status/1401074713858764801?s=20

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
Closed with #3214
