### ISSUE TITLE
eth_sendTransaction missing from the JSON-RPC section

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/ethereum-org-website#3209]
Hi there 👋

One of our team members just mentioned that the JSON-RPC method `eth_sendTransaction` is not present in [this section](https://ethereum.org/en/developers/docs/apis/json-rpc/), so I'm opening this issue to let you know. Maybe other methods are also missing. I didn't check that, tbh.

`eth_sendTransaction` is present in [the wiki](https://eth.wiki/json-rpc/API) and implemented by all the clients.

**Comment by leo-cuellar** [comment]
I checked if any other methods were missing and yeah, here they are:

- eth_sign
- eth_signTransaction
- eth_sendTransaction

If its ok I will submit a PR

**Comment by wackerow** [comment]
@all-contributors please add @alcuadrado for ideas
