### ISSUE TITLE
Translation banner logic is incorrect

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3213]
**Describe the bug**

For certain translations the homepage is displaying the incorrect banner. e.g. https://ethereum.org/zh/ or https://ethereum.org/fr/ :
![Image 2021-06-07 at 2 35 38 PM](https://user-images.githubusercontent.com/8097623/121071201-8079ab80-c784-11eb-9a4e-3c56e241608e.jpg)

The banner content is saying the page is not translated & therefore is showing content in English. This is NOT the case. The banner should explain that the page is translated but outdated & include a link to the equivalent (up to date) English page.

From what I can tell languages with version `1.0` & `1.1` have this bug. Versions `2.0` & above are displaying correctly.

**To Reproduce**

1. Go to https://ethereum.org/zh/
2. See banner content

**Expected behavior**

See above

**Screenshots**

See above

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
Something must be incorrect with the `pageContext.isContentEnglish` we set in gatsby-node.js & pass to the TranslationBanner in Layout.js

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Robiquet** [comment]
I can have a look at this

**Comment by minimalsm** [comment]
@Robiquet Just realised my PR doesn't solve the issue 🤬. Feel free to have a look.

**Comment by Robiquet** [comment]
@minimalsm I think the banner is being displayed because the translations are also outdated. We just need to handle that with a slightly different banner
