### ISSUE TITLE
I use UPHOLD for my crypto currency trading. It recommended me here but now it’s not showing up.

### ISSUE THREAD

**Issue by harharbinks** [ethereum/ethereum-org-website#3215]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

**Is your dapp open source?**

**Can a user access the dapp without creating an account?**

**Are dapp funds non-custodial?**

**Do you offer community support?**

**Describe any geographical restrictions on usage of your dapp**

**Dapp title**

**Dapp description**

**Dapp logo**

**Brand color**

**Comment by ryancreatescopy** [comment]
@harharbinks can you clarify your issue please?

**Comment by minimalsm** [comment]
Hey @harharbinks. 

Closing this out for now due to lack of information. Feel free to edit the issue with the relevant information and reopen.
