### ISSUE TITLE
Typo in ERC-20 tutorial

### ISSUE THREAD

**Issue by sonicsmith** [ethereum/ethereum-org-website#3231]
**Describe the bug**

On page: https://ethereum.org/en/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/
There is a sentence which reads:

> So we know have our DEX

When it should instead read: "So we now have our DEX".

**Comment by ryancreatescopy** [comment]
Fixed by #3234
