### ISSUE TITLE
I've noticed a few typos while studying the following tutorial:

### ISSUE THREAD

**Issue by lopeselio** [ethereum/ethereum-org-website#3233]
**Describe the bug**
The typos have been highlighted in bold:

1. 

> For this tutorial we’ll use the code we wrote in the previous tutorial as a base. Our DEX will instantiate an instance of the contract in **it’s** constructor and **perfom** the operations of:

![image](https://user-images.githubusercontent.com/43913734/121347995-718e2700-c945-11eb-921f-b58184666888.png)
2.
> So we **know** have our DEX and it has all the token reserve available. The contract has two functions

![image](https://user-images.githubusercontent.com/43913734/121348666-3fc99000-c946-11eb-8ca7-24926f929d0f.png)

**To Reproduce**

1. Go to [the dev tutorial](https://ethereum.org/en/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/#the-buy-function)
2. Check the typos highlighted in this issue.

**Expected behavior**
1. 
> For this tutorial we’ll use the code we wrote in the previous tutorial as a base. Our DEX will instantiate an instance of the contract in **its** constructor and **perform** the operations of:
2.

> `So we **now** have our DEX and it has all the token reserve available. The contract has two functions:`

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version: 89.0

**Comment by ryancreatescopy** [comment]
Fixed by #3234
