### ISSUE TITLE
Dynamically update table of contents section highlighting based on active scroll position

### ISSUE THREAD

**Issue by lopeselio** [ethereum/ethereum-org-website#3235]
**Describe the bug**

I was studying the ERC-20 tutorial and noticed that when I scrolled down to **THE SELL FUNCTION** from **THE BUY FUNCTION** header, the scroll was not changing dynamically. 

**To Reproduce**

1. Go to [the dev tutorial](https://ethereum.org/en/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/#the-buy-function)

**Expected behavior**
It should be scrolling up/down dynamically depending on the position of the user inside the view port height and width. It will help in tutorials involving a lot of headers as subtopics, so that the user knows which topic in the tutorial he/she is currently on. and navigate to another subtopic when needed.

**Screenshots**

![image](https://user-images.githubusercontent.com/43913734/121351548-879de680-c949-11eb-8594-728df4005ac5.png)

**Desktop (please complete the following information):**

- OS: Linux 
- BrowserFirefox
- Version 89.0

**Comment by wackerow** [comment]
Thanks for creating the issue @lopeselio! I agree, it'd be nice to have the active section highlighted as the scroll position changes. Happy to accept a PR for this if anyone is interested.

**Comment by samajammin** [comment]
Agreed - this is a pretty standard interaction for documentation, e.g. any Gitbook docs: https://docs.gitbook.com/spaces/space-visibility

**Comment by AkshatJindal1** [comment]
I would like to work on this @wackerow

**Comment by dombovari-balazs** [comment]
Hi,

This is my first time trying to contribute on any open source project. So, I would like to work on this @wackerow 

What I've noticed:
Chrome:
![Screenshot from 2021-06-28 14-50-11](https://user-images.githubusercontent.com/45357979/123639344-603b8a80-d820-11eb-8cea-b8bb649b4e4d.png)

**Comment by wackerow** [comment]
@dombovari-balazs Thanks for your interest! So for this issue @AkshatJindal1 has already been assigned and is working on a fix... I would take a look at some of the other issues that are open with nobody assigned. You could try starting with the ones labeled "good first issue" and drop a comment just like you did here asking to be assigned. If anything changes here and we need a hand I'll ping ya. 🙂

**Comment by il3ven** [comment]
I have made a PR that resolves this issue. #3451
