### ISSUE TITLE
ETHGlobal HackMoney Hackathon

### ISSUE THREAD

**Issue by xBalbinus** [ethereum/ethereum-org-website#3240]
**Is your feature request related to a problem? Please describe.**

The feature is an educational opportunity to onboard thousands of developers to the Ethereum ecosystem.

**Additional context**

We're planning on bringing together 1000+ confirmed hackers at the event to make the biggest DeFi hackathon of the summer. We need as much public exposure as possible for this to happen.
Event details:
🗓️ June 18 - July 9

💎 Over $150k+ in prizes

👩🏼‍⚖️ Access to industry experts and technical mentors

⛰️ Summits and talks on the future of the DeFi

🏅 POAP Tokens to show off to your friends

🔗 https://defi.ethglobal.co/

**Want to contribute?**

Here's the hackathon link: https://hackathon.money. Please let me know if you need any more resources to upload this onto Ethereum.org

**Comment by NhlanhlaHasane** [comment]
I would love to contribute to the HackMoney Hackathon,  though I am still new to the protocol,  I am one of the participants in Core Developers Apprenticeship Program run by Piper I think from R&D
