### ISSUE TITLE
Nftfy - The trustless way of sharing ownership of NFTs

### ISSUE THREAD

**Issue by LeonardoIRC** [ethereum/ethereum-org-website#3241]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

Github - https://github.com/nftfy
Audit 1 - https://omniscia.io/nftfy-erc-721-securitizer/
Docs - https://docs.nftfy.org/
White Paper - https://drive.google.com/file/d/1B4b8jV3QDxGPO-Xg_JAtiKbd2O6y8cV7/view
Deck - https://bit.ly/3tpbhfd

**Is your dapp open source?**

Yes, is a new primitive for the composability of DeFi.

**Can a user access the dapp without creating an account?**

Yes.

**Are dapp funds non-custodial?**

Yes. Non-custodial, decentralized, trustless and permissionles

**Do you offer community support?**

Discord and Telegram
https://discord.gg/tE4xxFH
https://t.me/nftfySec

**Describe any geographical restrictions on usage of your dapp**

**Dapp title**

Nftfy

nftfy.org

**Dapp description**

The trustless way of sharing ownership of NFTs.
Fractionalize NFTs into ERC20 Fungible fractions.

**Dapp logo**

https://photos.app.goo.gl/FQdkT8kTgbXLVfGj6

**Brand color**

#ff7982

**Comment by corwintines** [comment]
@LeonardoIRC im noticing a lot of the products on your page are listed as legacy. Do you mind opening a new issue with more information on what this means to clarify. Thanks!
