### ISSUE TITLE
Can u fix it?

### ISSUE THREAD

**Issue by Oilking777** [ethereum/ethereum-org-website#3248]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Oilking777** [comment]
Bug

**Comment by heypran** [comment]
Can you please provide more info?

**Comment by wackerow** [comment]
@Oilking777 If you're having a problem, please fill out a new issue explaining what you are experiencing. Closing this for now.
