### ISSUE TITLE
Site Translation: Polish

### ISSUE THREAD

**Issue by P1X3L0V4** [ethereum/ethereum-org-website#325]
Polish translation is complete and waiting for review:
[crowdin.com/project/ethereumfoundation/pl#](https://crowdin.com/project/ethereumfoundation/pl#)

Here is a [Polish Worksheet & Guideline](https://docs.google.com/spreadsheets/d/1dq_HS79lATSj_GpkqT_spkZehsmpNay3_D4cLus0-P4/edit#gid=110386278)

I will be grateful for the information about translation verification process

**Comment by samajammin** [comment]
Thanks! 🎉 🇵🇱 

@sorumfactory (who runs our translation program) could speak more in-depth but the short story is that we use a professional translation service to review the CrowdIn translations. The turnaround time depends on the language but I'm hoping we can get this up on the site next week!

**Comment by sorumfactory** [comment]
Thank you for your contribution, Anna.
We're looking forward to adding the Polish version website as soon as our professional proofreading service provider finishes the review process. You can check the progress of the proofreading by checking out the page below. (The blue bars will turn to yellow-green, once it's done :)
Thank you again for your great work!

**Comment by samajammin** [comment]
Translations have been reviewed & are ready to add to the site! Closing this in favor of https://github.com/ethereum/ethereum-org-website/issues/357

Thanks again for your work @P1X3L0V4!

**Comment by P1X3L0V4** [comment]
Do you have CONTRIBUTORS.md file for this project? I searched the  repo and can't find one

**Comment by samajammin** [comment]
@P1X3L0V4 not yet but I love the idea! We've been brainstorming ways to better acknowledge contributors, e.g. via a CONTRIBUTORS.md file or a tool like [All Contributors](https://allcontributors.org/docs/en/overview).

I just created this issue: https://github.com/ethereum/ethereum-org-website/issues/362 - please feel free to add your thoughts!

**Comment by samajammin** [comment]
@all-contributors please add @P1X3L0V4 for translation
