### ISSUE TITLE
code blocks with horizontal overflow have two scrollbars.

### ISSUE THREAD

**Issue by leo-cuellar** [ethereum/ethereum-org-website#3253]
**Describe the bug**

code blocks with horizontal overflow have two scrollbars.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getstorageat
2. In the "returns" section of that method, check the second code block.
3. See the horizontal scrollbars

**Expected behavior**

Only one horizontal scrollbar should exist

**Screenshots**

![image](https://user-images.githubusercontent.com/52687532/121845313-df6e8180-ccaa-11eb-80b4-4f68564c700d.png)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Chrome
- Version 91.0.4472.77

**Comment by leo-cuellar** [comment]
If considered relevant I would like to be assigned this issue.

**Comment by samajammin** [comment]
Thanks for reporting @leo-cuellar! We'd welcome a PR fix. I'll assign you.

**Comment by leo-cuellar** [comment]
Thank you guys. @wackerow Would it be possible to update my collaborator status?  Don't know if this could be marked for bug report or code but I would appreciate that update. Thank you so much

**Comment by wackerow** [comment]
You bet! Thanks for the help, sorry for delay =)

**Comment by wackerow** [comment]
@all-contributors please add @leo-cuellar for bug reports and code
