### ISSUE TITLE
code block tools overlap vertical scrollbar

### ISSUE THREAD

**Issue by leo-cuellar** [ethereum/ethereum-org-website#3254]
**Describe the bug**

code block tools overlap vertical scrollbar

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getstorageat
2. In the "returns" section of that method, check the first code block.
3. See the "show all" button overlapping with the vertical scrollbar.

**Expected behavior**

The button(s) should not overlap 

**Screenshots**

![image](https://user-images.githubusercontent.com/52687532/121845873-b995ac80-ccab-11eb-88e9-eb505a144ad1.png)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Chrome
- Version: 91.0.4472.77

**Comment by leo-cuellar** [comment]
If considered relevant I would like to be assigned this issue.

**Comment by samajammin** [comment]
Solve in https://github.com/ethereum/ethereum-org-website/pull/3263 - thanks @leo-cuellar!

**Comment by samajammin** [comment]
@all-contributors please add @leo-cuellar for code & bug reports.
