### ISSUE TITLE
The MakerDao Grants page has changed and current link is no longer valid

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#3255]
**Describe the bug**

When opening the 'Maker' link on the Community/Grants page, the website cannot be reached.

**To Reproduce**

1. Go to 'https://ethereum.org/en/community/grants/'
2. Scroll down to 'Project Specific'
3. Click on 'Maker'

**Expected behavior**

The grants.makerdao.com page should open.

**Screenshots**

![This site can't be reached](https://user-images.githubusercontent.com/37338979/121891636-fef1c280-cd1b-11eb-9bf4-e809c96b69a8.jpg)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [91.0.4472.101]

**Additional context**

The MakerDao Grants page is currently available at the following address: https://community-development.makerdao.com/en/programs/development-grants/. The link should be updated to reflect this change.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by lukassim** [comment]
I am available to help out with this PR if required.

**Comment by minimalsm** [comment]
@lukassim Nice spot. Is this something you'd like to have a go at fixing?

**Comment by lukassim** [comment]
@minimalsm Thanks for the reply. This is definitely something I can work on, please feel free to assign me. Thanks!
