### ISSUE TITLE
Suggestion to add a Microsoft Language Portal link to the Translation Program page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#3266]
**Is your feature request related to a problem? Please describe.**

I would like to suggest adding a link to the Microsoft Language Portal on the Translation Program page with a short description of it. This would inform the contributors of this tool, since it is not very well known outside of the professional translation industry, and increase its use, in turn helping translators provide significantly better and more accurate translations.
The Microsoft Language Portal is available at https://www.microsoft.com/en-us/language.

**Describe the solution you'd like**

The ideal solution would be to add the link to the Microsoft Language Portal and a short description to the Translation Program page in order to prompt contributors to use it during their translations.

**Describe alternatives you've considered**

There aren't many publicly-available alternatives of this scope and quality, if any.

**Additional context**

The Microsoft Language Portal contains very useful tools for technical translators, however the Microsoft translation memory is by far the most important one for our use-case. The translation memory contains the past and current translations of Microsoft's content by professional translation teams that are working for Microsoft. These translations have been professionally translated by technical translators, confirmed by proofreaders and PM's, as well as ultimately accepted by Microsoft, and are being used by Microsoft in their daily business.

The translation memory is essentially the best audited and supervised database for approved, established and up-to-date technical translations in over 100 languages, localized in accordance with Microsoft's detailed and strict Style Guides. All professional linguists working on localization projects for Microsoft are required to adhere to the translations from the Language Portal, while most other leading tech companies encourage their linguists to use the translation memory for their work as well.

Therefore, I believe that this tool could be very useful to all Ethereum.org translators, as it offers a reliable and easy way to find some of the more advanced or obscure technical terms and concepts, and check their established translations. By adding a link to it to the Translation Program page, we could encourage a lot of contributors to use it and make the localization process slightly easier for them.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Sounds great! Down to take a swing with a PR? Here's the page: https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/contributing/translation-program/index.md

I'm open to the approach. Perhaps we add a new "Resources" section to the page, where we can add tools like this?

**Comment by lukassim** [comment]
Sure, I will add the Resource section and try to think of other resources and tools that could be useful.
