### ISSUE TITLE
Request to enable MetaMask account

### ISSUE THREAD

**Issue by JODIN1727** [ethereum/ethereum-org-website#3268]
**Is your feature request related to a problem? Please describe.**

No Funds in the account 

**Describe the solution you'd like**

please advise what I need to do 

**Describe alternatives you've considered**

please advise 

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
@JODIN1727 If you're having issues with MetaMask I'd encourage you to check out their repo [here](https://github.com/MetaMask/metamask-extension). If you have general questions you're also welcome to stop into our Discord server and ask for help in an appropriate channel. Closing, as this does not pertain to the ethereum.org website.
