### ISSUE TITLE
Added to have Thai language

### ISSUE THREAD

**Issue by filmblackeye** [ethereum/ethereum-org-website#327]

**Comment by sorumfactory** [comment]
Thai language is added to the Crowdin now.
Please go to the link below and feel free to join our translation program :)

https://crowdin.com/project/ethereumfoundation

**Comment by samajammin** [comment]
FYI I believe the invite link is https://crowdin.com/project/ethereumfoundation/invite

**Comment by samajammin** [comment]
Here's the direct link for folks looking to contribute! https://crowdin.com/project/ethereumfoundation/th#
