### ISSUE TITLE
0chain listed as "blockchain based" decentralized storage instead of "contract based"

### ISSUE THREAD

**Issue by zeroservices** [ethereum/ethereum-org-website#3293]
**Describe the bug**
On https://ethereum.org/en/developers/docs/storage/ 0chain is listed as blockchain based storage project.

0chain does not store the actual data within the blockchain itself. Instead the concept of spreading data in allocations (contracts) across multiple 'blobbers' using user-configurable erasure-coding is used.

**Comment by wackerow** [comment]
@zeroservices Thanks for noting this... can take a closer look when time allows, or happy to accept a PR for this =)

**Comment by samajammin** [comment]
Hey @zeroservices!

> 0chain does not store the actual data within the blockchain itself. Instead the concept of spreading data in allocations (contracts) across multiple 'blobbers' using user-configurable erasure-coding is used.

I don't understand. So where is data stored? What is a blobber?

Thanks :)

**Comment by zeroservices** [comment]
> @zeroservices Thanks for noting this... can take a closer look when time allows, or happy to accept a PR for this =)

There already is a PR attached to this case :-) See https://github.com/ethereum/ethereum-org-website/pull/3294
All other stated information was correct from my checking.

**Comment by sculptex** [comment]
> Hey @zeroservices!
> 
> > 0chain does not store the actual data within the blockchain itself. Instead the concept of spreading data in allocations (contracts) across multiple 'blobbers' using user-configurable erasure-coding is used.
> 
> I don't understand. So where is data stored? What is a blobber?
> 
> Thanks :)

Blobbers are the term given to the storage nodes on the 0chain network. These are off-chain, that is separate to the BlockChain itself and referred to via hashes as per other providers mentioned in off-chain section
