### ISSUE TITLE
Takings of the Staked monies for Etherium 2.0 BACK because it is taking FAR TOO LONG!!

### ISSUE THREAD

**Issue by DaveyD233** [ethereum/ethereum-org-website#3295]
Takings of the Staked monies for Etherium 2.0 BACK because it is taking FAR TOO LONG and I Cant have that much money there no more!!!

**Comment by wackerow** [comment]
@DaveyD233 I'm sorry to hear of your frustrations. This repo is specifically for development of the front end of ethereum.org and is not involved in the protocol level of changes, so not going to be able to help much here. I'd encourage you to check out the EthStaker community on reddit or discord if you have general questions about staking, or feel free to hope into the [Eth R&D discord](https://discord.gg/mncqtgVSVw) to follow on a technical basis. Hope this helps provide some guidance. (Closing this issue as it does not pertain to this repository)

**Comment by DaveyD233** [comment]
Thank you for your time!

**Comment by jley81** [comment]
Why doesn't anyone help me

**Comment by wackerow** [comment]
@jley81 I'm sorry did you need help with something? Please feel free to post an issue if it is something related to the ethereum.org website, or you are also welcome to hop into Discord and ask questions.
