### ISSUE TITLE
Little mention of Bitcoin

### ISSUE THREAD

**Issue by alexgausman** [ethereum/ethereum-org-website#33]
The old site had a section dedicated to describing the relationship between ETH and BTC. Many users coming to the new site will likely know of Bitcoin and may hold some too. They will want to know how ETH matches up to BTC and whether they are in direct competition. Personally I am of the opinion that they can both benefit from each other. Having a link/page to a blurb about potential synergies could send a positive message and reduce anxiety of any BTC holders trying to learn more.

Feel free to disagree about this being a good idea.

**Comment by alexgausman** [comment]
Here's an example of what I'm thinking... 
---------------------------
ETH and Bitcoin have a lot in common but they also have a number of differences. 

Bitcoin has been around longer than ETH.
Bitcoin’s protocol is a less complex than ETH’s.
There are more options for buying/selling Bitcoins than ETH.
Bitcoin’s blockchain is less likely to change considerably than ETH’s.
Bitcoin’s price is generally less volatile than ETH.

While it’s easy to see how Bitcoin and ETH could be viewed as competitors, there are actually many cases where they can benefit each other. 

WBTC is a version of Bitcoin, called “Wrapped Bitcoin”, that can be used on the Ethereum blockchain.

WBTC can be traded on decentralized exchanges like Kyberswap.
WBTC can earn interest on lending platforms like NuoNetwork.
WBTC can be auto-balanced against other assets via TokenSets.

Every WBTC is backed 1:1 by Bitcoin, allowing Ethereum users to leverage the power of Bitcoin in a growing permisionless landscape.

**Comment by alexgausman** [comment]
To reiterate, this is just an idea based on some criticism of the new website by BTC holders that I observed. Feel free to close this issue if you don't feel mentioning bitcoin is necessary

**Comment by jjmstark** [comment]
Hey @alexgausman - this is a cool idea. One of the principles of the new ethereum.org is that it should have minimal "native" content, but be a great portal to community-created content. If you were to write a good blog post about this subject, you could submit a PR to add it as a link (maybe somewhere on /Learn?) so that users can find this information if they're looking for it.

**Comment by alexgausman** [comment]
Sounds good @jjmstark I'll mark this issue as closed and see about making a post and submitting it. Thanks for the response
