### ISSUE TITLE
Add Remix desktop IDE

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3307]
**Is your feature request related to a problem? Please describe.**

https://twitter.com/matthewdif/status/1406199850379714560?s=20

**Describe the solution you'd like**

Add to https://ethereum.org/en/developers/docs/ides/#desktop-ides

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Patil2099** [comment]
I would like to take this up.
