### ISSUE TITLE
Last Edit showing 'admin' instead of user

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3313]
**Describe the bug**

The last edit on this (and possibly other?) page/s currently shows 'admin' instead of the actual user.

<img width="668" alt="Screenshot 2021-06-20 at 22 15 17" src="https://user-images.githubusercontent.com/62268199/122688637-552b9d80-d215-11eb-8045-160357cf96ee.png">

<img width="598" alt="Screenshot 2021-06-20 at 22 18 31" src="https://user-images.githubusercontent.com/62268199/122688660-7ee4c480-d215-11eb-8445-196d62be698f.png">

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/ides/'
2. See error

**Expected behavior**
The GitHub handle associated with the last user to make an edit should be shown

**Want to contribute?**
We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
Hm... Looking at #2761 commit 743aae9 it looks like the user assigned to that commit is unavailable (?). Not sure what happened there, but I don't think that's a bug directly with the site.

Maybe it's worth placing a filter on this to remove these?

**Comment by wackerow** [comment]
This appears to have been fixed...  Closing, but feel free to reopen if anyone notices it's still a problem.
