### ISSUE TITLE
README shown as heading in docs sidebar navigation

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3314]
**Describe the bug**
README is currently showing as the sidebar navigation heading for the front page for the developer docs.

<img width="1195" alt="Screenshot 2021-06-20 at 22 19 54" src="https://user-images.githubusercontent.com/62268199/122688745-016d8400-d216-11eb-99bf-d91664ea449f.png">

![image0](https://user-images.githubusercontent.com/62268199/122688781-2e219b80-d216-11eb-8988-0aca524aa6e5.png)

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/'
2. Look at sidebar navigation
3. See error

**Expected behavior**
README should be shown in sidebar. Should this page be in the sidebar navigation at all? I don't see navigating to this page to be a particularly useful action if you're already in the docs.

**Want to contribute?**
We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
Hey @minimalsm! I believe this was the intended result, to have the intro page to the documentation section be essentially a README. I don't know if we'd want to remove the link to this on the sidebar, even if the page may not be one a lot of people navigate back to.
@samajammin Any thoughts on naming / layout of this README link?

**Comment by minimalsm** [comment]
@samajammin any thoughts on this

**Comment by enriavil1** [comment]
> We translate this: https://ethereum.org/ro/developers/docs/
> 
> Don't think we should. Maybe change this to introduction?

I was wondering if I could be assigned this. I was thinking it on naming it 'Development Documentation' or just 'Documentation', even though 'Introduction' sounds more formal I feel like it is a bit confusing specially for people looking for the documentation on how to start specifically.

**Comment by enriavil1** [comment]
<img width="1680" alt="Screenshot 2021-08-28 at 04 11 33" src="https://user-images.githubusercontent.com/19207637/131201485-b94b3ccb-9e39-4cdd-ac11-29e247f8556a.png">
This is how it would look with development documentation

**Comment by enriavil1** [comment]
<img width="1185" alt="Screenshot 2021-08-28 at 04 12 26" src="https://user-images.githubusercontent.com/19207637/131201512-61cc1198-6317-4df1-9c9b-d10914b4dc7d.png">
this is how documentation only would look. I feel like those two labels convey more information and would be quicker to find, even though it is the starting of the page.

**Comment by minimalsm** [comment]
@all-contributors please add @enriavil1 for ideas

**Comment by minimalsm** [comment]
Closing in favour of #3908
