### ISSUE TITLE
YouTube link should be embedded

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3315]
**Describe the bug**
On the Gas and fees page there is a YouTube link that should be an embedded video.

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/gas/'
3. Scroll down to 'WHY CAN GAS FEES GET SO HIGH?' section
3. See bug

**Expected behavior**
An embedded YouTube video should be shown instead of just a link

**Screenshots**
<img width="690" alt="Screenshot 2021-06-20 at 22 29 53" src="https://user-images.githubusercontent.com/62268199/122688913-21ea0e00-d217-11eb-98a2-182d72dc4964.png">

**Want to contribute?**
We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
Thanks @minimalsm!
