### ISSUE TITLE
Mobile nav BottomMenu hidden when Chrome url bar is deployed

### ISSUE THREAD

**Issue by leo-cuellar** [ethereum/ethereum-org-website#3329]
**Describe the bug**

Just tested this on the Chrome app. when the URL bar is deployed, the bottom menu gets hidden. You can see that in the screenshots below.

url bar deployed
![WhatsApp Image 2021-06-22 at 12 49 53 AM (1)](https://user-images.githubusercontent.com/52687532/122871177-45cf5180-d2f4-11eb-8b90-cfe957ffbfe6.jpeg)

url bar not deployed
![WhatsApp Image 2021-06-22 at 12 49 53 AM](https://user-images.githubusercontent.com/52687532/122871193-48ca4200-d2f4-11eb-8834-2becb521d09c.jpeg)

**To Reproduce**

1. Go to ethereum.org from the Chrome app on mobile
2. Open the menu
3. See the bottom menu hidden
4. Scroll down until the URL bar gets hidden
5. See the menu as it should be

**Expected behavior**

The menu should always be visible no matter if the URL bar is deployed or not.

**Screenshots**

See above

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S20+
- Browser: Chrome

**Comment by leo-cuellar** [comment]
I would like this assigned to me if considered relevant.

**Comment by SNikhill** [comment]
I see. I believe that the same is due to the fact that the URL bar takes up the viewport too (often missed while designing using the mobile view of a desktop browser).

So, 100vh in testing will show that our webpage takes the whole viewport height but, actually, around 10 vh may be covered by the URL and shifting the page's content further below.

**Comment by samajammin** [comment]
@leo-cuellar thanks for reporting & offering to tackle this! I've assigned you.

**Comment by minimalsm** [comment]
@leo-cuellar Hey ✌️ any progress on this?

**Comment by aayusharyan** [comment]
Hey,
I came here hoping for the free NFT and found this good first issue.
Posting the evidence of the fix. Need to check a little bit more in the code where to change the CSS exactly to make this work. (Currently did in Chrome dev tools and took the evidence).
I'll make the PR in a couple of days.

Evidence. 👇🏻 
https://kemuri.gyazo.com/08eba5353272cdc60a79d44876686d3b

If that's okay, please let me know and assign it to me.

**Comment by minimalsm** [comment]
@aayusharyan thanks for offering to help here. I've assigned you 😀

**Comment by minimalsm** [comment]
@aayusharyan hey! Any progress on this?

**Comment by aayusharyan** [comment]
Not exactly, I was having trouble setting up local environment. Will be checking more over this weekend.

**Comment by 0xpranay** [comment]
@minimalsm I want to work on this issue. I've have a fix ready and figuring out the PR steps for the repo. Can you assign me?

[Proof of Fix](https://imgur.com/a/ZSOu2MD) 😀

**Comment by minimalsm** [comment]
All yours :-) @0xpranay
