### ISSUE TITLE
Strange text in the Ethereum Whitepaper

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#3338]
Strange bit of text in the middle of the original [whitepaper](https://ethereum.org/en/whitepaper/). was there originally an image here or something?

> Group At launch After 1 year After 5 years

![image](https://user-images.githubusercontent.com/27454964/123356710-38090e80-d536-11eb-9279-6a2983134079.png)

**Comment by wackerow** [comment]
@tvanepps This appears to be a table, just needing some markdown syntax cleanup. Good catch, posting a fix 👍🏻
