### ISSUE TITLE
Cloudinary account to be deleted due to traffic

### ISSUE THREAD

**Issue by alancwoo** [ethereum/ethereum-org-website#335]
@samajammin we're using cloudinary to host the splash video with a free account, unfortunately it's going to be closed on October 26 due to the traffic being generated on the site currently.

I think we need to host the MP4 elsewhere, if even just as part of the netlify bundle since they are fairly small files.

https://res.cloudinary.com/dtqk9d1xc/video/upload/v1565083119/Comp_1_3_yikcia.mp4

**Comment by samajammin** [comment]
Thanks @alancwoo - I notice we also use a file on ucarecdn as well:
```
    videoSrc () {
      if (this.dark) {
        return 'https://res.cloudinary.com/dtqk9d1xc/video/upload/v1565083119/Comp_1_3_yikcia.mp4'
      } else {
        return 'https://ucarecdn.com/b33f5c86-2d0b-4063-99e1-0acfc6d15a00/ethwhiteoptimized2.mp4'
      }
    }
```
Do you have access to that account?

For now I'll add the files to the bundle.

**Comment by alancwoo** [comment]
@samajammin yep, I do also have access to the uploadcare account, but if we find it's loading okay off netlify then perhaps it's fine. They are very optimized videos anyhow, and to be honets we'd probably hit the limit on uploadcare as well before paying for service: https://uploadcare.com/pricing/
