### ISSUE TITLE
Language relating to Trinity and Open Ethereum clients is not accurate

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#3358]
A twitter user recently [tried to sync the Trinity client](https://twitter.com/lopp/status/1409606419851231239?s=20), which failed.  

Many in the Ethereum community are aware that Trinity is not a mainnet client, but this is not called out on the [Nodes and Clients](https://twitter.com/lopp/status/1409606419851231239?s=20) page of the website. There is also a flag above the table which says "All of them are actively worked on."

It might make sense to separate out clients that are 1. continuously maintained 2. are not going to be deprecated.

Related to #2, consider mentioning that OE will be deprecated after London and that users should look into migrating to other clients.

**Comment by pipermerriam** [comment]
Trinity will no longer be developed or maintained.
