### ISSUE TITLE
Add EthCC to the upcoming events

### ISSUE THREAD

**Issue by lorelei1** [ethereum/ethereum-org-website#3362]
& side events happening the same week in Paris!

**Comment by wackerow** [comment]
@lorelei1 Great idea! =) I just added the https://ethcc.io page as well as the https://ethccweek.fr/ page to shine light on both. You, or others, are welcome to add the individual events if you'd like... will keep this issue open in the meantime 👍🏻

**Comment by lorelei1** [comment]
Great! Thank you :) Seems that more and more are listed on ethccweek every day!

**Comment by wackerow** [comment]
Yeah... hm 🤔 that makes me think it's probably best not to try and list all of the events, as they may change, and our site won't update that rapidly. Could leave people with the wrong info, and it's better to have a canonical place where people can get accurate info.
Any thoughts on this?

**Comment by lorelei1** [comment]
I agree that listing ethccweek.fr totally satisfies the need! take advantage of the amazing reality that someone ELSE has coalesced this info 😄

**Comment by wackerow** [comment]
cheers to that! 🎉
