### ISSUE TITLE
Showcase Bitvavo on the /get-eth page

### ISSUE THREAD

**Issue by noahpierau** [ethereum/ethereum-org-website#3368]
Dear ethereum.org team,

This issue was created on behalf of Bitvavo, one of the biggest regulated EUR exchanges in Europe. Bitvavo is proudly based in Amsterdam and has been offering the ETH/EUR trading pair for some time now.

It will be beneficial for you to showcase Bitvavo on your https://ethereum.org/en/get-eth/ page, since it is one of the largest regulated exchanges in Europe and committed to support Ethereum. We also provide a custom asset page: https://bitvavo.com/en/ethereum (you can link to local versions of the website if you replace "EN" with DE, ES, FR, IT or NL).

- **What geographical restrictions apply to this exchange?**
Bitvavo offers its services to residents of the European Economic Area (EEA), including Gibraltar, Switzerland and United Kingdom. Full list of countries: https://support.bitvavo.com/l/en/article/9c62dbg4ws-supported-countries 

- **Which currencies are accepted by this exchange?**
We currently only offer EUR pairs on our platform.

- **Do you have any proof that they're a legitimate company?**
Bitvavo is registered with the Dutch Central Bank and complies with all relevant laws in the Netherlands: https://support.bitvavo.com/l/en/article/1swy7m1kzp-bitvavo-registered-with-the-dutch-central-bank-dnb

- **Do you have any extra information?**
It will be beneficial for you to showcase Bitvavo on your website, since it is one of the largest regulated exchanges in Europe and committed to support Ethereum. You can link to a custom asset page: https://bitvavo.com/en/bitcoin-cash (and simply link to local versions of the website if you replace "EN" with DE, ES, FR, IT or NL).

Bitvavo is launching a new website with a redesigned logo. If you are willing to showcase Bitvavo, kindly send us the required logo dimensions and file format (png, jpg, svg) for your website, so our designers can create this for you.

**Comment by minimalsm** [comment]
Approved! Thanks for raising this @noahpierau.
