### ISSUE TITLE
UNQT

### ISSUE THREAD

**Issue by Shaze24** [ethereum/ethereum-org-website#3374]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Shaze24** [comment]
Unic currency in which currency landscape

**Comment by wackerow** [comment]
@Shaze24 If you have an issue you'd like to discuss please fill out the requested information in a new issue, thank you.
