### ISSUE TITLE
POAP - Proof of Attendance Protocol

### ISSUE THREAD

**Issue by LamboshiNakaghini** [ethereum/ethereum-org-website#3377]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

POAP has not completed an audit, but has been double checked by Scott Bigelow and other developers in the Ethereum space. Users do not need to use any of their own funds to use POAP and the tokens issued by the protocol have no resale value. For this reason an audit has been a low priority. 

https://poap.xyz
https://github.com/poap-xyz 

**Is your dapp open source?**

POAP is fully open source.

PRs for POAP are accepted and deeply appreciated.

**Can a user access the dapp without creating an account?**

Users only need to input their public address to receive a POAP. Other parts of the protocol require users to sign a message to participate. 

**Are dapp funds non-custodial?**

POAP has some control over tokens issued. Because the tokens are non-fungible, free to create, and have no resale value this is not a large concern. 

POAPs are tokens on either the XDAI or Ethereum network. If the POAP interface goes down the tokens can be manually moved and/or an independent interface could be built to move the tokens. 

**Do you offer community support?**

POAP has a github, subreddit, discord server, and twitter account to offer support for users.
https://github.com/poap-xyz
https://twitter.com/poapxyz
https://discord.gg/9s8U8Bn
https://old.reddit.com/r/poap

**Describe any geographical restrictions on usage of your dapp**

POAP has no restrictions on use. 

**Dapp title**

Proof of Attendance Protocol

**Dapp description**

Proof of Attendance Protocol allows users to claim a non-fungible token that proves they were present at an event; either virtual or in person. 
In addition to the token delivery system there are several additional services that leverage users having those tokens. 
-	POAP.fun is a raffle system that allows users to join a raffle if they own a relevant POAP. This makes it easy and Sybil resistant to make a raffle for anyone that went to an event. 
-	POAP.vote allows users who own a relevant POAP to participate in a vote. This can be valuable for governance decisions in different communities. For example EthStaker airdropped a POAP to everyone who made a pre-genesis deposit to the deposit contract. If there were ever a governance issue with the beacon chain POAP.vote could be used to get opinions from users that provably have skin in the game. 
-	POAP.chat lets users create chat rooms for people who have a relevant POAP. This has similar benefits to POAP.vote in governance issues. 
-	POAP.art is a community based drawing application. Over the course of an event, participants can draw on a canvas together, and at the end there is a community generated piece of art.

The low barrier to entry for both event hosts and participants, the fun nature of product, and the useful products built on top of POAP has made POAP very popular in many different communities across the entire Ethereum space.

**Dapp logo**

![POAPlogo](https://user-images.githubusercontent.com/49704490/124407643-75c61e00-dd12-11eb-958c-bb2b47b4f8f9.png)

**Brand color**

#6633ff
#ffcccc

**Comment by wackerow** [comment]
@LamboshiNakaghini Yes! Thank you for posting this... were you thinking of this just being listed on the ethereum.org/en/dapps page? Or did you have somewhere else in mind too?

**Comment by LamboshiNakaghini** [comment]
Hi Paul! Yes, I was thinking it fits nicely in the digital collectibles category.
