### ISSUE TITLE
Please add Atomic Wallet

### ISSUE THREAD

**Issue by ramapom** [ethereum/ethereum-org-website#3395]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

**Is your wallet custodial, non-custodial, or a hardware wallet?**

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

**Does the wallet have fiat on-ramps?**

**Does the wallet allow users to explore dapps?**

**Does the wallet have integrated defi/financial tools?**

**Can a user withdraw to their card?**

**Does the wallet offer limits protection?**

**Does the wallet allow high-volume purchases?**

**Does the wallet have an integrated token swap?**

**Is the wallet a multi-signature wallet?**

**Wallet title**

**Wallet description**

**Wallet logo**

**Background colour for brand logo**

**URL**

**Comment by wackerow** [comment]
⬆️ Hey @ramapom, if you or anyone else could do us a favor and fill out the requested information in your post we'll be able to take a closer look.. thanks!

**Comment by ramapom** [comment]
Sorry, I'm not very computer literate and I still don't know if I'm doing this properly. Basically I just wanted to connect with my Atomic wallet but I've since realized that my SHIB holdings are on the Australian Exchange, CoinSpot so I guess that is the one I need to connect to. Also, originally I heard (one of the Youtubers) that if I staked my SHIB I would not have to lock it in for a fixed period but recently I read somewhere that you have to lock it away for 6 months if you want to stake it, can you please clarify? Thank you so much for your help.

**Comment by wackerow** [comment]
Sorry @ramapom, this is the repo for the ethereum.org website specifically and nothing more. Please contact those exchanges or the wallet maker themselves for further assistance.
