### ISSUE TITLE
Separate out the vuepress theme

### ISSUE THREAD

**Issue by man15h** [ethereum/ethereum-org-website#34]
It would be great if the Vuepress theme is separate out from the project. It'll be easy to maintain code and content another advantage is that the theme can be used or maintained by any other Vuepress developer. Let me know if you agree I'm happy to submit a PR.

**Comment by samajammin** [comment]
@man15h I'm going to close this issue for maintenance purposes. Feel free to re-open if you have a response to my question. Thanks!
