### ISSUE TITLE
Turkish

### ISSUE THREAD

**Issue by ahmeteminkocal** [ethereum/ethereum-org-website#341]
Add Turkish language support please

**Comment by samajammin** [comment]
Thanks for the suggestion @ahmeteminkocal!

We've added Turkish to our translation project in CrowdIn:
https://crowdin.com/project/ethereumfoundation/tr#

Here's the invite link to join our translation program. Feel free to hop in (or send to folks who could help)!
https://crowdin.com/project/ethereumfoundation/invite

@sorumfactory leads our translation program & can help with any questions you have. Let us know!

**Comment by ahmeteminkocal** [comment]
I will be helping! Thank you!

**Comment by samajammin** [comment]
Translations are complete! 🎉

Closing this out in favor of #873

**Comment by samajammin** [comment]
@all-contributors please add @ahmeteminkocal for translations

**Comment by samajammin** [comment]
If anyone else helped out with these translations, please comment here or in #407 so we can acknowledge your contributions 😄. Thanks!
