### ISSUE TITLE
Kannada Language support

### ISSUE THREAD

**Issue by Rashmi-278** [ethereum/ethereum-org-website#3414]
Kannada is one the Indian languages which is native language of Bengaluru, the capital of Karnataka State in India. 
Bengaluru is center of high-tech center. so adding this language support would be helpful to lot of native developers.

**Comment by qbzzt** [comment]
Can you do this translation?

**Comment by samajammin** [comment]
Hey @Rashmi-278 - thanks for creating this issue!

I've added Kannada in Crowdin for translation. We encourage you to get involved if you're able!
https://crowdin.com/project/ethereumfoundation/kn

Here's more info on our translation program:
https://ethereum.org/en/contributing/translation-program/

Closing this issue out but please let @lukassim or I know if you have any questions.
