### ISSUE TITLE
List of Eth2 clients is misleading

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3422]
**Describe the bug**

Currently we list all Eth2 clients here:
https://ethereum.org/en/eth2/get-involved/#clients

We should make it clear which clients are production-ready vs. those that are not.

**Expected behavior**

We should probably break the list out into 2 sections:
1. mainnet-compatible
2. "experimental" (or something along those lines)

Is there clear criteria here on how to delineate between production-ready clients & those that are still experimental/in development? i.e. is there a test sweet that certain clients are passing vs. those that are not?

**Screenshots**

![Image 2021-07-14 at 12 19 16 PM](https://user-images.githubusercontent.com/8097623/125680284-320feed2-3769-4c7c-87f4-61105700e037.jpg)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by timbeiko** [comment]
For a list of "mainnet-compatible" clients, we can probably use the ones which appear on https://launchpad.ethereum.org (Prysm, Nimbus, Teku, Lighthouse). The one that may also be in that category is Lodestar. @dapplion @wemeetagain @mpetrunic any thoughts about how to categorize Lodestar? I didn't think it was mainnet-compatible, but I see a lot of PRs merged that reference Altair. 

For the others, I think they may both actually be deprecated. @sgryphon is Cortex still maintained? @pipermerriam same question for Eth2 Trinity.

**Comment by dapplion** [comment]
Hey! I think "mainnet-compatible" is a bad term. Probably all clients in that list are "compatible" in the sense that they follow the spec and can join the network. A more appropriate term would be "product-ionized", or "mainnet-ready".

Specifically for Lodestar we having good performance on the Prater testnet and may publicly announce that we are "mainnet-ready" after further testing and maybe an audit to some key parts if applicable. I would agree to put Lodestar under an "experimental" category until then.
