### ISSUE TITLE
Text on Eth2 Vision Trilemma Diagram cut off in Brave Browser on Linux

### ISSUE THREAD

**Issue by sharon-wang** [ethereum/ethereum-org-website#3434]
**Describe the bug**

Text in the Trilemma Diagram (`DECENTRALIZATION`, `SCALABILITY`) is getting cut off.

**To Reproduce**

Only observed on Linux machine on Brave Browser (looks fine in Firefox). Did not see this problem on Mac in Brave.

1. Go to https://ethereum.org/en/eth2/vision/
2. Scroll down to 'The challenge of decentralized scaling' section
3. See error: 'DECENTRALIZATION' with 'N' cut off

**Expected behavior**

Text in Trilemma diagram should not get cut off. When the `DECENTRALIZATION` or `SCALABILITY` circles in the diagram are selected, their text gets even more cut off (see screenshots below).

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/25834218/126009132-ee524522-b33e-4ecc-80c4-7a2cbceb3a7d.png)
![Untitled2](https://user-images.githubusercontent.com/25834218/126009158-e143d1df-b883-4e85-828b-1d19a900751e.png)

**Desktop (please complete the following information):**

- OS: Linux Ubuntu
- Browser: Brave
- Version 1.25.68 Chromium: 91.0.4472.77

**Want to contribute?**

I'd like to contribute! I'm thinking to just increase the width of the `viewBox` of the SVG.

**Comment by minimalsm** [comment]
Tried on two different macs and I'm unable to replicate this. 

@pettinarip do you have Brave on your Linux machine? If so, could you see if you get the same issue?

**Comment by enriavil1** [comment]
I tried on my Mac and also couldn't replicate this. Maybe we could increase the div size by a little bit, so they fit better, though we might have to see the chain reaction on other devices.

> Tried on two different macs and I'm unable to replicate this.
> 
> @pettinarip do you have Brave on your Linux machine? If so, could you see if you get the same issue?

**Comment by enriavil1** [comment]
I was thinking maybe by adding some padding it would help by when you click on the text

**Comment by enriavil1** [comment]
I did it in this code. could you please try it on ur device? @sharon-wang

**Comment by samajammin** [comment]
Thanks for reporting this @sharon-wang!

> Tried on two different macs and I'm unable to replicate this.

@minimalsm you could test out a few different OS/devices using BrowserStack to try & replicate. Unfortunately it doesn't look like they have much support for Linux. @pettinarip please also take a look on your machine 😄 

Thanks for looking into this @enriavil1! I see you've made a commit after forking the repo. Can you please open up a pull request into this repo so we can assess your commits? Instructions on how to do that here: https://github.com/ethereum/ethereum-org-website#submit-your-pr

**Comment by enriavil1** [comment]
> Thanks for reporting this @sharon-wang!
> 
> > Tried on two different macs and I'm unable to replicate this.
> 
> @minimalsm you could test out a few different OS/devices using BrowserStack to try & replicate. Unfortunately it doesn't look like they have much support for Linux. @pettinarip please also take a look on your machine 😄
> 
> Thanks for looking into this @enriavil1! I see you've made a commit after forking the repo. Can you please open up a pull request into this repo so we can assess your commits? Instructions on how to do that here: https://github.com/ethereum/ethereum-org-website#submit-your-pr

Sorry, but I cant seem able to replicate the problem.

**Comment by sharon-wang** [comment]
> I did it in this code. could you please try it on ur device? @sharon-wang

Just tried the site preview from your PR (#3434), but the text is still cut off on my machine (Linux):
![image](https://user-images.githubusercontent.com/25834218/131408155-738cd853-0db8-411d-845a-15ddff447081.png)

**Comment by sharon-wang** [comment]
Increasing the width of the Trilemma SVG viewBox fixes the issue on my end -- opened a PR here: https://github.com/ethereum/ethereum-org-website/pull/3761

I'd want to be sure this doesn't make things worse for those using Mac/Windows and other browsers, so I'd appreciate some help with testing!
