### ISSUE TITLE
Add bitFlyer to list of exchanges on /get-eth page

### ISSUE THREAD

**Issue by bitoflai** [ethereum/ethereum-org-website#3443]
Hi there! Would like to add bitFlyer to the list of centralized exchanges on the `/get-eth` page.

**What geographical restrictions apply to this exchange?**

• United States - All states except Nevada and West Virginia.
• Europe - All EEA countries. List here https://bitflyer.com/en-eu/faq/77-10
• Japan

**Which currencies are accepted by this exchange?**

US Dollar, Euro, Japanese Yen. Each currency is available to customers from each respective region (USD for US, JPY for Japanese, and EUR for European customers)

**Do you have any proof that they're a legitimate company?**

bitFlyer is Japan’s largest cryptocurrency exchange and the first exchange to get licensed in Japan, the US, and Europe. It has over 2.5 million customers worldwide and has been operating since 2014 with a track record of being a secure and regulated exchange.

In Japan, they were amongst the first group of exchanges to receive the virtual currency license from the Japanese Financial Services Agency (FSA). They’ve been the largest cryptocurrency exchange by trading volume in Japan for 5 years in a row.

Moreover, in 2017 [they expanded to the US](https://www.cnbc.com/2017/11/28/worlds-largest-bitcoin-exchange-bitflyer-enters-the-us.html), becoming the 1st international company (4th overall) to receive the NY Bitlicense. Today, US residents living in all states except West Virginia and Nevada can buy ETH and other popular cryptocurrencies with USD. They’re also registered with FinCEN as an MSB. You can find their [US licenses here](https://bitflyer.com/en-us/states).

They [launched their services in Europe](https://www.ft.com/content/5bf1462c-ff84-11e7-9650-9c0ad2d7c5b5) in 2018, where they are licensed by the CSSF in Luxembourg as a payments institution. Customers living in all EEA countries can buy ETH with EUR.

Lastly, bitFlyer was recognized as one of the 10 exchanges with real trading volume in [Bitwise’s application](https://www.sec.gov/comments/sr-nysearca-2019-01/srnysearca201901-5164833-183434.pdf) to the SEC for a Bitcoin ETF in the US.

**Do you have any extra information?**

bitFlyer investors include Digital Currency Group and many other leading Japanese corporations including Mizuho, SMBC, SBI, Mitsubishi UFJ Capital, and more.

Lastly, given bitFlyer’s vast reach in Japan as the #1 exchange in the region, last year they collaborated with the Ethereum Foundation in a two-part series ([1](https://blog-jp.bitflyer.com/n/ncea4e1255076) and [2](https://blog-jp.bitflyer.com/n/naf6d0f0ea3c3)) with the goal of educating Japanese residents about what Ethereum is, its roadmap & vision, upcoming developments, and more.

**Comment by bitoflai** [comment]
Thanks a lot, @minimalsm ! 
Confirming that all the non-USA territories in that list are supported. Let me know if you have more questions:)

![Screen Shot 2021-09-30 at 11 05 36 AM](https://user-images.githubusercontent.com/86689107/135507796-1b36babb-c51f-4255-8fc1-50fa8cc2459d.png)

**Comment by corwintines** [comment]
Added in https://github.com/ethereum/ethereum-org-website/pull/5839
