### ISSUE TITLE
Add section informing on the types of common crypto scams

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#3448]
**Is your feature request related to a problem? Please describe.**

There are a lot of common scams that occur in this space. Some we see consistently are DM's through messaging applications, YouTube streams linking to giveaway scams, clipboard malware, etc. 

**Describe the solution you'd like**

I think it would be valuable to the community to have a section informing about common crypto scams. Given the nature of ethereum.org being a resource for education, giving some information about this would be beneficial for the community.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by nassersaazi** [comment]
would love to comtribute to this!

**Comment by samajammin** [comment]
Some designs that @ryancreatescopy put together awhile back when first thinking about this.

Many of these designs revolved around user generated content - allowing users to submit scam reports & a place to list all these reports. I think that's a great idea but I suggest we start with something even simpler: basically an outline of the common scams that occur, what things to be wary/skeptical of & best practices in terms of protecting your funds.

Here's the Figma file: https://www.figma.com/file/ME3DCgxmqmEX1dUwMhmSfT/Scams?node-id=0%3A1

Potential structure I like regarding "best practices" or "how to stay safe" section:
![Image 2021-07-25 at 1 13 16 PM](https://user-images.githubusercontent.com/8097623/126912144-c9304ed7-bfa6-47f5-8b10-40a36aeb642c.jpg)

**Comment by samajammin** [comment]
I'm noticing this thinking overlaps closely with an existing issue: https://github.com/ethereum/ethereum-org-website/issues/2077

Looks like it was closed by the stale bot but should probably be re-opened / incorporated into this work.

**Comment by samajammin** [comment]
Could take some inspiration from this resource: https://bitcoin.org/en/scams

**Comment by samajammin** [comment]
Another great resource: https://support.mycrypto.com/staying-safe

**Comment by wackerow** [comment]
Going to close this with #3872, can expand on the new page with new issues if needed
