### ISSUE TITLE
Colored Ethereum Logo in SVG & High-Res PNG format

### ISSUE THREAD

**Issue by digitalblossom** [ethereum/ethereum-org-website#3452]
This is the logo from the top left of ethereum.org. I made it because I couldn't find a vector version, and was told to submit it here for https://ethereum.org/en/assets/.

[The three files are on Sia Skynet](https://skytransfer.hns.siasky.net/#/ae6be3d1c88a6beaeae7aba220a4323e23f3c332a15f1cb5eed8654cd9fbf294/2b71bd03be275830e7078322fbe3f30c7af3a708e06888b5d8a1e14ebbd0549c293514c991b09b05aac8320664c946d7c48d69bdaf7490f9b0110b817d70a12d) ([mirror](https://siasky.net/HABZ8WPNi60U14D7_NPoK5Z4KJiuiQgpOir-PZcUsaOZeA)), two PNGs (light and dark) and an SVG .

Preview:
![ethereum-colored-dark](https://user-images.githubusercontent.com/80636305/126576577-cb07ba84-a4fe-4d63-b43a-e7832c77483d.png)

**Comment by minimalsm** [comment]
Hey @digitalblossom thanks so much for this 😍 really appreciate it.

Had a quick check with the team (my eyes aren't great for colour!) and they agreed that the colour here seems slightly off to us. In particular the border is definitely more blue than you have it here. For reference here is the exact file we are using for the icon currently: https://github.com/ethereum/ethereum-org-website/blob/dev/src/assets/favicon.png

**Comment by minimalsm** [comment]
Hey @digitalblossom. 

Just checking if you've had the time to look at this ☺️? Keen to incorporate this if you've got the capacity.

**Comment by digitalblossom** [comment]
> Just checking if you've had the time to look at this ☺️? Keen to incorporate this if you've got the capacity.

hi @minimalsm and sorry for the late answer, i overlooked the first reply. I adjusted the outline color and rerendered the images, it now looks like this:

[Files are here](https://skytransfer.hns.siasky.net/#/86d8c2ec52ba88c8aaec2ba9cd9c0d448e55953202e4c3839e4b4d5c88626ae0/c984f76b9f6c899a59d9b3c2058addca4b2f5a048372dc3a290c26b9d76ed741a3f4af688f24d6146366dabee60101c32515897710929f86d031a4c946ff495d)

![ethereum-colored-light](https://user-images.githubusercontent.com/80636305/130060453-875a6633-3ce1-4f19-9a7d-61ce4d286c90.png)

**Comment by minimalsm** [comment]
Thanks 🥰 Looks great to me. Just waiting on another pair of eyes to double-check and then we can get them incorporated into the website 😀❤️

**Comment by MrBrain295** [comment]
@minimalsm I know I’m not a maintainer but it looks good to me.
