### ISSUE TITLE
Contributors modal displays duplicate users

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3468]
**Describe the bug**

The modal appears to list duplicate contributors. I suspect this instance is because it's displaying the user's name vs. their Github handle (not sure why). See screenshot below.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/intro-to-ethereum/
2. Click on "See contributors"
3. Scroll down & see duplicates

**Expected behavior**

**Screenshots**

![Image 2021-07-22 at 4 41 42 PM](https://user-images.githubusercontent.com/8097623/126722132-16bf8369-6e1c-4cb1-a9f9-b143e808671a.jpg)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by NishantChandla** [comment]
@samajammin I would like to work on this issue.

**Comment by samajammin** [comment]
@NishantChandla thanks for volunteering! I've assigned the issue to you.

Note that in order to query contributors from GitHub in the FileContributors component:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/FileContributors.js

I believe you'll need to set up a GitHub token (used in the Apollo client): https://github.com/ethereum/ethereum-org-website/blob/dev/src/apollo.js

More details on setting up a GitHub API token here: https://github.com/ethereum/ethereum-org-website#set-up-your-local-environment-optional

**Comment by NishantChandla** [comment]
Okay, Thanks for the info!
