### ISSUE TITLE
ETHGlobal HackFS 2021

### ISSUE THREAD

**Issue by xBalbinus** [ethereum/ethereum-org-website#3470]
**Is your feature request related to a problem? Please describe.**

Our goal is to onboard thousands of hackers onto the Ethereum ecosystem.

**Describe the solution you'd like**

We want our event to be listed on Ethereum.org so that people can join us and learn how to build.

**Describe alternatives you've considered**

Having this posted on r/Ethereum by the mods would be wonderful too, but I don't have enough reddit karma.

**Additional context**

Together with Protocol Labs, we're bringing folks three-weeks of hacking, summits and talks on the state of decentralized storage. You can integrate IPFS or Filecoin with your favorite NFT, DeFi, DAO, Gaming, and web3 applications. 

🗓️ July 30 - August 20
💎 Over $100k+ in prizes
👩‍⚖️Technical mentors and project feedback sessions
⛰️ High-level summits and talks on current events
🏅 POAP Tokens to show off to your friends
🔗 fs.ethglobal.co

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
@xBalbinus Thanks for posting =) Looks like this was added to the community events in #3437... It's currently in the `dev` branch and should be live within a few days 👍🏻  Closing for now, but feel free to comment/reopen if you notice anything that needs correcting.
