### ISSUE TITLE
Add Atomic Wallet to the wallet's section

### ISSUE THREAD

**Issue by centralizedtransformer** [ethereum/ethereum-org-website#3479]
**Is your wallet globally accessible?**
Yes, Atomic is a decentralized wallet that can be accessed from anywhere with no KYC and verification for basic features.

**Is your wallet custodial, non-custodial, or a hardware wallet?**
Atomic is a non-custodial wallet. It’s simply an interface with private and public keys and to sign transactions. Users’ funds are always accessible on blockchains.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
Atomic Wallet Privacy Policy is stated here. Atomic is also continuously tested by our QA team and senior software engineers to ensure it complies with global security standards. Before the launch of our product, it has to pass a penetration test, security test, and vulnerability test. We've had zero security compromises in our app's history. Moreover, we have a bug bounty campaign and warmly welcome any suggestions and reports from our users.

**Does the wallet have fiat on-ramps?**
Yes, our users can buy top crypto assets with VISA/MC of 18 global fiat currencies. The service is provided by Simplex, 5% fees (min. $10 USD) are included in the price.

**Does the wallet allow users to explore dapps?**
Atomic is integrated with WalletConnect.

**Does the wallet have integrated defi/financial tools?**
No.

**Can a user withdraw to their card?**
Not yet.

**Does the wallet offer limits protection?**
The limit for transfers exists only in the sense of the KYC process. Until a customer buys crypto up to $200, they don’t need to pass the verification.

**Does the wallet allow high-volume purchases?**
Yes, a user can buy $2000+ worth of crypto in one go, passing KYC powered by Simplex.

**Does the wallet have an integrated token swap?**
Yes, Atomic has an exchange service directly in the wallet. Service is provided by ChangeNOW. There are more than 60 crypto pairs available for the swaps.

**Is the wallet a multi-signature wallet?**
No

**Wallet title**
Atomic Wallet

**Wallet description**
Atomic is a decentralized cryptocurrency wallet that supports more than 500 coins and tokens, providing simplicity, safety, and convenience for its users.

**Wallet logo**
https://atomicwallet.io/images/press-kit/atomic_wallet_logo_white_vert_2.png

**Background colour for brand logo**
Dark-Blue Background: 212D4D, Light-Blue Color: Gradient, top – 3EBBF, bottom – 1F8EFA

**URL**
https://atomicwallet.io/

**Comment by minimalsm** [comment]
Hey @centralizedtransformer ! A few details we need to iron out. [Per our content policy](https://ethereum.org/en/contributing/adding-products/), wallets need to have been audited and maintained by an active team:

- Where can we confirm the wallet's last audit?

- Is the Atomic Wallet team active? (I assume so, but just checking!)

Thanks!

**Comment by minimalsm** [comment]
@centralizedtransformer hey! Any update on this 😬?

**Comment by minimalsm** [comment]
@centralizedtransformer closing this out for now. Feel free to reopen with the necessary information ☺️

**Comment by centralizedtransformer** [comment]
@minimalsm Hi Joshua! It's Andrew from the Atomic Wallet team. First of all sorry for not replying to your comments.


We are ready to send you the audit in dm. We have it in pdf format. Please provide us with contacts where we can send it. 

Regarding the team, we constantly updating the app and maintaining our own validators and nodes, so the team is pretty active. You may check out the website and social media as proof: https://twitter.com/atomicwallet
