### ISSUE TITLE
Breadcrumbs shown twice on ETH2 template pages 

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3480]
**Describe the bug**
In a screensharing session with @samajammin the [Beacon Chain Page](https://ethereum.org/en/eth2/beacon-chain/) bugged out causing the breadcrumbs to display twice. The bug persisted across pages using the ETH2 template.

**To Reproduce**
I wasn't able to reproduce this on my machine...

**Expected behavior**
Breadcrumbs should only display once.

**Screenshots**
<img width="974" alt="Screenshot 2021-07-26 at 18 00 14" src="https://user-images.githubusercontent.com/62268199/127063384-e5fee59a-cfed-409d-8deb-43a802045c54.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave
- Version: ??

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Interesting - I'm also unable to reproduce this (at least on mobile).

**Comment by wackerow** [comment]
Yeah, noticed this the other day during our meeting, but was also unable to reproduce. Possibly another caching related page glitch... @samajammin Let me know if you still get this on desktop, otherwise will close out.

**Comment by minimalsm** [comment]
Doesn't seem anyone has been able to reproduce this since it happened so closing this out for now.
