### ISSUE TITLE
Adding Coin98 Wallet to the homepage

### ISSUE THREAD

**Issue by hosyminh95** [ethereum/ethereum-org-website#3484]
Is your wallet globally accessible?
Yes, Coin98 Wallet is a decentralized wallet that can be accessed from anywhere in the world, with no KYC and verification

Is your wallet custodial, non-custodial, or a hardware wallet?
Coin98 is a non-custodial, multi-chain wallet. 

Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible
Coin98 Wallet is being audited by Certik. 

Does the wallet have fiat on-ramps?
No

Does the wallet allow users to explore dapps?
Yes, we have built in DApps Browser. 

Does the wallet have integrated defi/financial tools?
Yes, we have native swap feature and DApps Browser.

Can a user withdraw to their card?
No

Does the wallet offer limits protection?
No

Does the wallet allow high-volume purchases?
Users are free to transfer and swap whichever volume they want. 

Does the wallet have an integrated token swap?
Yes

Is the wallet a multi-signature wallet?
No

Wallet title
Coin98 Wallet

Wallet description
A Non-Custodial, Multi-Chain Wallet & DeFi Gateway

Wallet logo
https://c98.link/Coin98-wallet-logos

URL
https://coin98.com/wallet

**Comment by minimalsm** [comment]
Hey @hosyminh95! Thanks for providing the above. A few details we need to iron out to move forward. [As per our content policy](https://ethereum.org/en/contributing/adding-products/), wallets need to be live for at least 6 months, need to have been audited for security and maintained by an active team:

- How long has Coin98 wallet been live?

- Where can we confirm the wallet's last audit? (If you're currently awaiting an audit when is it due?)

- Is the Coin98 team active? (I assume so, but just checking!)

Thanks!

**Comment by hosyminh95** [comment]
Sorry for the late reply

Coin98 Wallet has been around for over a year now. Please check out our
wallet here: https://coin98.com/wallet
Our audit with Extension Wallet is still ongoing with Certik, but you can
take a look at our token audit here:
https://github.com/coin98/coin98-docs/tree/master/audit . Also another
reference: https://research.binance.com/en/projects/coin98
Yes, Coin98 team is super active. You can check out our communities here:
https://coin98.com/communities

If you have any questions, please let me know. Thank you!

**Comment by minimalsm** [comment]
Hi @hosyminh95 thanks for the additional info. I've approved this and it will be added to the website soon. Thanks!

@all-contributors please add @hosyminh95 for docs

**Comment by hosyminh95** [comment]
Awesome, thank you so much.
