### ISSUE TITLE
Dynamic decentralised democratic voting system - to replace all governments

### ISSUE THREAD

**Issue by zerogravitycity** [ethereum/ethereum-org-website#3488]
We would like to attract good developers that would like to be part of creating this system. 

It can work on local communities as-well as large countries, and can replace politicians. 

It will of-course be open source but will require registration in system to participate. High security and actual person register should be possible with bank-ID or fingerprint.

As a transparent system with possibility to vote anonymously should be achievable through dynamic settings.

Anyone can create a case to be voted on, but it should be well documented to become public case.

While not a system for fund transfer, storage or investment it might work well with other systems in this category (but is mainly focused on agreement on cases and "politics". Accounting numbers for public sector and companies should be available and easy to read. Ideally it should be possible for each person to view & edit where their taxes are spent.

DDDVS - Dynamic Decentralised Democratic Voting System

Who would like to help make this a reality?

**Comment by minimalsm** [comment]
Hey @zerogravitycity 👋. Thanks for this suggestion but this repo is specifically for the Ethereum.org website. 

Some places you could check out if you're looking to find people to build this out:
- [/r/ethdev](https://www.reddit.com/r/ethdev/) on Reddit
- [CryptoDevs](https://discord.gg/5W5tVb3) on discord

And if you're looking for funding to build a project in the Ethereum space
- The [Ethereum Grants](https://ethereum.org/en/community/grants/#ethereum-grants) page in our community section

Be sure to keep us in the loop with any progress, we'd love to hear it ✌️😀
