### ISSUE TITLE
ETHWall description length causing scrolling

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3489]
**Describe the bug**

The character length of the description on the WallEth wallet is causing the card to require scrolling to read the whole description. No other wallets have this issue.

**To Reproduce**

1. Go to 'https://ethereum.org/en/wallets/find-wallet/'
2. Scroll down to WallETH wallet card
3. See bug

**Expected behavior**
Description should fit within the card without scrolling.

**Screenshots**

![Screenshot 2021-07-28 at 14 41 30](https://user-images.githubusercontent.com/62268199/127340534-96e14fe9-dade-4e10-906e-f9055b3c111f.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Brave
- Version 1.24.82

**Alternatives Considered**
Limit description length so we're not redesigning every time the new max description length is exceeded?

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by mannekin** [comment]
Would like to take this on as my first contribution :)

**Comment by minimalsm** [comment]
Closed by #3569
