### ISSUE TITLE
TypeError: Cannot read property 'accounts' of undefined

### ISSUE THREAD

**Issue by abdul745** [ethereum/ethereum-org-website#3493]
**Is your feature request related to a problem? Please describe.**
Yes, My request is related to a probem. 

I am facing a problem in creating an etherium wallet in my own website. When I run the code of creating wallet i.e. 
var myWallet = web3.eth.accounts.wallet;
I get an error:
var myWallet = web3.eth.accounts.wallet;
                        ^
TypeError: Cannot read property 'accounts' of undefined
    at Object.<anonymous> (/home/server/auth/AuthController.js:16:25)

**Describe the solution you'd like**
Anyone please tell me what the issue is here?
I am following the documentation here-> https://web3js.readthedocs.io/en/v1.2.11/web3-eth-accounts.html

I want to create an ethereum wallet and accounts in my own website.

**Describe alternatives you've considered**

I have considered no alternatives. Rather I want help in this issue.
**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey! We already spoke on discord but just to close this out - this repo is for the Ethereum.org website, rather than general Ethereum *things*. Here is the repo for the library you're having trouble with: https://github.com/ChainSafe/web3.js

Hope you get it sorted ✌️
