### ISSUE TITLE
Add Trustee Wallet to the wallet's section

### ISSUE THREAD

**Issue by taki-183** [ethereum/ethereum-org-website#3495]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

YES, Trustee available on iOS and Android markets in 160 countries.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial, open source (https://github.com/trustee-wallet/trusteeWallet)

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Trustee Wallet has a security certificate from Hacken.io. Also the application is open source hosted on GitHub (https://github.com/trustee-wallet/trusteeWallet). The code is updated in the repository before the release of the new version. Therefore, each user can check the application code for vulnerabilities. During the entire operation of the application, no vulnerabilities or data leaks were found.

**Does the wallet have fiat on-ramps?**

Yes, our users can buy top crypto assets with VISA/MC of 40 global fiat currencies and from different payment systems - Perfect Money, ADVCash, Payeer, Capitalist etc. The service is provided by different providers of liquidity (Kuna, MoonPay, Mercuryo and other). User can see all fees in app before purchase.

**Does the wallet allow users to explore dapps?**

WalletConnect - YES
Dapps browser - NO
User can use Dapps by link in WalletConnect

**Does the wallet have integrated defi/financial tools?**

NO

**Can a user withdraw to their card?**

YES. User can sell crypto to bank card in UAH and RUB. 

**Does the wallet offer limits protection?**

For crypto transaction - NO
For fiat-crypto and crypto-fiat transactions - YES. It is limited by exchange services.

**Does the wallet allow high-volume purchases?**

YES. User can buy $2000+ worth of crypto in one go. Max limit $11400 with KYC.

**Does the wallet have an integrated token swap?**

YES. Service is provided by ChangeNOW, Changelly, Swapy and other exchangers.

**Is the wallet a multi-signature wallet?**

NO

**Wallet title**

Trustee Wallet

**Wallet description**

Trustee Wallet is a quick and secure multi-currency crypto wallet to store, exchange and instantly buy cryptocurrencies with Visa/MasterCard and other payment systems. This is the easy and simple way to conduct cryptocurrency transactions via mobile devices. 

**Wallet logo**

![logoDark](https://user-images.githubusercontent.com/54359346/127519318-96836612-516f-402f-aea9-6cd7692433f8.png)

**Background colour for brand logo**

#f7f7f7

**URL**

https://trusteeglobal.com/

**Comment by minimalsm** [comment]
Hey @taki-183 ! Thanks for providing the above. [As per our content policy](https://ethereum.org/en/contributing/adding-products/), wallets need to be live for at least 6 months, need to have been audited for security and maintained by an active team:

- How long has Trustee Wallet wallet been live?

- Where can we confirm the wallet's last security audit? 

- Is the Trustee Wallet team active? (I assume so, but just checking!)

Thanks!

**Comment by taki-183** [comment]
> Hey @taki-183 ! Thanks for providing the above. [As per our content policy](https://ethereum.org/en/contributing/adding-products/), wallets need to be live for at least 6 months, need to have been audited for security and maintained by an active team:
> 
> * How long has Trustee Wallet wallet been live?
> * Where can we confirm the wallet's last security audit?
> * Is the Trustee Wallet team active? (I assume so, but just checking!)
> 
> Thanks!

Hello.

1. Trustee was released 01 may 2019 on AppStore and Play Market. So app working more than 2 years.
2. Trustee it is open source wallet, everybode can check app for security on GitHub
3. Yes, Trustee team active on social networks (you can see core team in our webiste) and GitHub

We will be happy to answer other questions.

**Comment by minimalsm** [comment]
Thanks for your patience and the additional information on this. Unfortunately, at this time we are only accepting wallets that have had an external security audit performed on the code of their wallet. Please do open another issue in the future if you decide to get an external security audit on the codebase. Thanks again!
