### ISSUE TITLE
Small typo: replace miner with minor

### ISSUE THREAD

**Issue by esale** [ethereum/ethereum-org-website#3498]
Hi,

I think there is a typing error in https://ethereum.org/en/eth2/staking/ where it says:

> A miner upgrade will follow to enable withdraw of staked funds.

Maybe it should be MINOR instead of MINER?

I think the issue is [in this line of code](https://github.com/ethereum/ethereum-org-website/blob/451e7198bc027b3139306f8dfb87ee3d055d0b03/src/intl/en/page-eth2-staking.json#L56).

Thanks and regards!

**Comment by wackerow** [comment]
@esale Good catch, thanks for posting =) Just put up a patch to fix this

**Comment by wackerow** [comment]
@all-contributors please add @esale for bug reports
