### ISSUE TITLE
The current logo is closer to the Ethereum Classic logo

### ISSUE THREAD

**Issue by virgil** [ethereum/ethereum-org-website#35]
Specifically, it looks too much like the ETC logo.

I suggest we using the hologram logo from:

https://devcon4.ethereum.org/

But probably anything from Jon Ying would be fine.

**Comment by hrishikeshio** [comment]
Devcon4 website looks better than current ethereum website IMHO.

**Comment by scott-l-e-w-i-s** [comment]
yea, that logo on devcon4 is awesome. possibly the twitter account avatar and website logo should be sync'd up.

**Comment by jjmstark** [comment]
Relevant context from the blog post:

> The dominant feature of the landing page is a large “HERO” style image, and the current one is only temporary. We plan to change it regularly as we receive submissions from the community, rotating the art over time. If you’re interested in submitting a new HERO image design, reach out to us at website@ethereum.org.
