### ISSUE TITLE
Add matomo error tracking

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3518]
**Is your feature request related to a problem? Please describe.**

The Gatsby matomo plugin now supports error tracking: https://github.com/kremalicious/gatsby-plugin-matomo/pull/169

**Describe the solution you'd like**

Update the plugin & add this feature!

**Describe alternatives you've considered**

None

**Additional context**

See PR link above

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
We're closing this out as this isn't something a contributor can contribute to.
