### ISSUE TITLE
Sort out strategy for JSON RPC docs

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3520]
**Is your feature request related to a problem? Please describe.**

A few months ago we created a page for the JSON RPC API:
https://ethereum.org/en/developers/docs/apis/json-rpc/

Why? At the time eth.wiki was the only place actually hosting docs for these endpoints (https://eth.wiki/json-rpc/API) & it was clearly a suboptimal UX. More on that here: https://github.com/ethereum/eth-wiki/issues/55

But now it appears @timbeiko & others are maintaining references here:
https://github.com/ethereum/eth1.0-apis

Which includes a nice playground!
https://playground.open-rpc.org/

Additional context: https://github.com/ethereum/eth-wiki/pull/61

**Describe the solution you'd like**

Let's decide how to approach this going forward. When we added the page, we knew this might just be a temporary fix. Is there any reason for us to continue to maintain the endpoints on ethereum.org as well? 

@timbeiko curious to hear your thoughts / plans on maintaining these moving forward. Seems like the new repo (https://github.com/ethereum/eth1.0-apis) is a solid solution & I'd personally be happy to just reference that from ethereum.org as the source of truth (assuming you have resources to keep it up to date).

**Describe alternatives you've considered**

Continue to maintain https://ethereum.org/en/developers/docs/apis/json-rpc/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by timbeiko** [comment]
@samajammin hey! 

yes, we'll be maintaining that repo as the canonical source. It _may_ change/be merged with another repo post-merge, but likely not. If you want to just point to it, that works. @lightclient is the maintainer if you ever need anything. I also have merge access.

**Comment by lightclient** [comment]
:wave: hello! I'm working on maintaining the OpenRPC spec for the Ethereum APIs. The current spec is still incomplete and buggy, but we'll continue to improve it over time. There is the OpenRPC playground, but I don't the frontend experience to much with it.

It would be really cool to have the playground deployed on some official Ethereum URL. I'd love help getting that setup and integrated into the CI. Probably not an immediate thing since we should try and iron out more of the bugs - however, something to be considering!

**Comment by samajammin** [comment]
Sounds great! Thanks @timbeiko @lightclient. We're definitely happy to collaborate on the frontend piece if that's helpful.

@minimalsm here's a resource on changes to the API for EIP 1559. 
https://hackmd.io/@timbeiko/1559-json-rpc

I think perhaps for now we just update our page on ethereum.org to 1) explain the JSON RPC API at a high level 2) link out to the spec & playground.

**Comment by timbeiko** [comment]
@samajammin that SGTM! It's probably not worth investing tooo much on the eth.org side until things are a bit more settled spec-wise.
