### ISSUE TITLE
London Banner

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#3522]
Countdown/celebration banner for the upcoming London release on Mainnet. Should count down until the release, when its release should say that London is out.

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by il3ven** [comment]
I'll like to work on this. Is this banner supposed to be shown on the home page? I am thinking something like this.
![image](https://user-images.githubusercontent.com/4337699/127775348-44476382-9bc3-4dcd-ad81-70e8557bb19a.png)

**Comment by minimalsm** [comment]
Hey @il3ven! 

Sorry, corwintines was already working on a fix for this when you posted. Love the idea/design though. Implementing something like this is definitely something we could loop back round to discuss with you in the future.

If there are any issues you fancy having a shot at let us know 🙏. Or, if there is anything you want to discuss about contributing or the project generally be sure to stop by the [Ethereum.org discord channel](https://discord.com/invite/bTCfS8C) ✌️
