### ISSUE TITLE
Remove stale bot

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3523]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I feel like the stale GitHub Action bot creates more annoyance than value. I propose we remove it.

**Describe alternatives you've considered**

We could also increase the time before it becomes stale.

**Additional context**

Action lives here: https://github.com/ethereum/ethereum-org-website/blob/dev/.github/workflows/stale.yml

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Possible alternative: we don't let it close issues, simply use it as a reminder to not let issues stagnate?

Not opposed to removing it all together either though.

**Comment by samajammin** [comment]
Solved in #3608
