### ISSUE TITLE
Hello, a newb here

### ISSUE THREAD

**Issue by emejinglilcompany** [ethereum/ethereum-org-website#3527]
hello,

if I may I would like to redo this task please, thanks

**Comment by AayushCurious** [comment]
What are you actually trying to do?

**Comment by mahesh4173** [comment]
I can't intereste mail please stop sending otherwise I use respect less
word ###

**Comment by minimalsm** [comment]
Hi @emejinglilcompany. Could you clarify what you're looking for help on?
