### ISSUE TITLE
Proof of authority

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3528]
**Is your feature request related to a problem? Please describe.**

Worth adding a page under consensus mechanisms on PoA?

**Describe the solution you'd like**

Add a page explaining it & its trade offs.

**Describe alternatives you've considered**

**Additional context**
Good resource? https://github.com/cryptoeconomics-study/website/blob/master/docs/sync/2.4-lecture.md

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ayushgun** [comment]
+1

Though, this may have some overlap with content located in other places of the website. Some cleaning would be nessecary.

**Comment by samajammin** [comment]
Potential content inspiration: https://forum.openzeppelin.com/t/proof-of-authority/3577

**Comment by corwintines** [comment]
Revived in https://github.com/ethereum/ethereum-org-website/issues/10774
