### ISSUE TITLE
Update guide for translators

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#3530]
**Is your feature request related to a problem? Please describe.**

Expand the instructions for joining the Translation Program and using Crowdin, add additional information to the Translation Program page.

**Describe the solution you'd like**

- Add expanded guide for translators
- Add translations@ethereum.org as method of contact
- Add Proz term search and Euro TermBank to tools

**Comment by minimalsm** [comment]
Closed by #3532
