### ISSUE TITLE
Defi API down?

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#3533]
**Describe the bug**

Error when trying to load TVL stats on homepage

**To Reproduce**

1. Go to homepage
2. Scroll to "the network today" section
3. See error

**Expected behavior**

I should see a value of total value locked in Defi protocols.

**Screenshots**

<img width="749" alt="Screenshot 2021-08-02 at 11 51 13" src="https://user-images.githubusercontent.com/40891631/127850651-bc1b248f-27af-4523-be67-fe48c20ac0c8.png">

**Comment by minimalsm** [comment]
Thanks for reporting this Ryan. Working for me now - probably an issue on their end? I've tagged @defipulse on Twitter asking if they experienced downtime this morning.  Do we have a way of checking this kind of thing from the DefiPulse dashboard @samajammin before closing this out?

**Comment by wackerow** [comment]
Hey @ryancreatescopy! Curious if you're still getting this?

Polled the endpoints using our API key and it seems to be working, and the ethereum.org page seems to be loading the correct data for me at this point in time. Not sure if anything changed, but if this is still an issue for anyone please chime in.

**Comment by samajammin** [comment]
Ya seems to be working - hopefully was a temporary issue on their end.

Closing this out for now. If we see this again please re-open this & I can reach out to the DeFiPulse team to investigate.
