### ISSUE TITLE
Remove/comment out ReleaseBanner in Layout after London Release

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#3541]
**Is your feature request related to a problem? Please describe.**
No set time, but at some point we will want to remove or comment out the Release Banner from Layout after London has been out for a bit. The info will be stale at some point, and dont need to waste requests to etherscan either at that point as well.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by jley81** [comment]
Approved
