### ISSUE TITLE
Add ether documentation page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3548]
**Is your feature request related to a problem? Please describe.**

Currently we have a "What is ether?" intro page: https://ethereum.org/en/eth/ but no technical resources on ETH.

**Describe the solution you'd like**

Wondering if we should add a new documentation page covering ether.

In addition to the current intro page, it might be useful to have a technically focused resource, e.g. that includes 
- denominations (https://ethdocs.org/en/latest/ether.html#denominations)
- explanation of how ether is minted during block creation
- ether supply & how it can be calculated
- how ether is sent in transactions (i.e. via `msg.value`), how both EOAs & contracts can send & hold it
- how ether can be queried (e.g. `address.balance`)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Related issue #2776

**Comment by tapstephenson** [comment]
@samajammin @minimalsm Could I volunteer for this? It would be my first issue, but I've read the guidelines [here](https://github.com/ethereum/ethereum-org-website#how-to-contribute). 

Please let me know next steps and I'm happy to submit a PR for review.

**Comment by minimalsm** [comment]
> @samajammin @minimalsm Could I volunteer for this?

For sure! The page would live in our developer docs section. If you haven't already you can check out the [docs pages](https://ethereum.org/en/developers/docs/intro-to-ethereum/) to get an idea of the format and style that these pages take. I think Sam's outline is scoped well enough to get started but if you've got any other questions feel free to ask here or on [discord](https://discord.gg/JRQjPkr7HA) ✌️

**Comment by tapstephenson** [comment]
Hi all! Just made my first PR. I'm sure there's a lot of room for improvement, so please let me know any preferred updates. Thanks
