### ISSUE TITLE
Add Wallet Request

### ISSUE THREAD

**Issue by SafePalWallet** [ethereum/ethereum-org-website#3549]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**
Decentralized wallet

**Is your wallet custodial, non-custodial, or a hardware wallet?**
SafePal Wallet is a Hardware Wallet and Software Wallet

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
https://blog.kraken.com/post/7874/kraken-security-labs-finds-flaws-in-safepal-s1-hardware-wallet/

**Does the wallet have fiat on-ramps?**
YES

**Does the wallet allow users to explore dapps?**
SafePal Wallet is integrated with WalletConnect and Support dapp brower, Of Course users can connect to dapp with the wallet.

**Does the wallet have integrated defi/financial tools?**
YES

**Can a user withdraw to their card?**
NO

**Does the wallet offer limits protection?**
NO

**Does the wallet allow high-volume purchases?**
YES

**Does the wallet have an integrated token swap?**
YES

**Is the wallet a multi-signature wallet?**
NO

**Wallet title**
SafePal

**Wallet description**
SafePal cryptocurrency wallet application is a secure, easy-to-use and free application to manage cryptocurrency at your fingertips. In the SafePal application, you can store, send and receive crypto at ease, and enjoy the smooth and intuitive user experience!

**Wallet logo**
https://github.com/SafePalWallet/ethereum-org-website/blob/dev/src/assets/wallets/safepal.png

**Background colour for brand logo**
#3F37FF

**URL**
https://www.safepal.io/

**Comment by SafePalWallet** [comment]
Hey @minimalsm, Thanks your reply. The specific details are below:

How long has the SafePal wallet been live?
4 year since 2008

Where can we confirm the wallet's last security audit?

**Comment by SafePalWallet** [comment]
Hey @minimalsm, Thanks your reply. The specific details are below:

How long has the SafePal wallet been live?
4 year since 2008

Where can we confirm the wallet's last security audit?
[Kraken Wallet Research_ Safepal Disclosure.pdf](https://github.com/ethereum/ethereum-org-website/files/6952060/Kraken.Wallet.Research_.Safepal.Disclosure.pdf)

**Comment by SafePalWallet** [comment]
Hey @minimalsm, Thanks your reply. The specific details are below:

How long has the SafePal wallet been live?
4 year since 2008

Where can we confirm the wallet's last security audit?
[Kraken Wallet Research_ Safepal Disclosure.pdf](https://github.com/ethereum/ethereum-org-website/files/6952065/Kraken.Wallet.Research_.Safepal.Disclosure.pdf).

**Comment by SafePalWallet** [comment]
Hey, @minimalsm , this is our blog about Kraken Wallet Research, https://blog.safepal.io/our-response-to-the-security-findings-from-kraken-security-labs/.

**Comment by minimalsm** [comment]
Approved and added, thanks! 😀
