### ISSUE TITLE
Learn about translation program link points to wrong page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3564]
**Describe the bug**
The 'Find out how to get involved in the translation program' link [here](https://ethereum.org/en/community/#how-can-i-get-involved) points to the [language support page](https://ethereum.org/en/languages/#ethereum-org-translation-program) instead of the [translation program page](https://ethereum.org/en/contributing/translation-program/).

The code needing changed lives in the markdown file here - https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/community/index.md

**To Reproduce**

1. Go to 'https://ethereum.org/en/community/#how-can-i-get-involved'
2. Scroll down to 'Translate Ethereum content into your native language'
3. Click on 'Find out how to get involved here'

**Expected behavior**
Link should point to translation program page - https://ethereum.org/en/contributing/translation-program/

**Additional context**

<img width="798" alt="Screenshot 2021-08-05 at 16 15 31" src="https://user-images.githubusercontent.com/62268199/128375119-9b35874e-d0ff-4340-96bc-401417ba925b.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by siddharths00** [comment]
I've raised a [PR](https://github.com/siddharths00/ethereum-org-website/commit/bac000f483eb9c77f258e6c3bb63d3f7cdecf9af) for this issue. Please take a look at it and do let me know if there are any faults in it.
