### ISSUE TITLE
Request to please add Easy Crypto to Australia and New Zealand geographical locations

### ISSUE THREAD

**Issue by ButlerBneAU** [ethereum/ethereum-org-website#3572]
Before suggesting an exchange, make sure you've read [our exchange listing policy] - (https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**

Australia and New Zealand

**Which currencies are accepted by this exchange?**

AUD and NZD

**Do you have any proof that they're a legitimate company?**

Our Australian Entity: https://connectonline.asic.gov.au/RegistrySearch/faces/landing/panelSearch.jspx?searchTab=search&searchText=EC+Systems+Pty+Ltd&searchType=OrgAndBusNm&_adf.ctrl-state=11k9tw93yw_32

Our New Zealand Entity (EC Systems and EC Group): https://app.companiesoffice.govt.nz/companies/app/ui/pages/companies/search?mode=standard&type=entities&q=EC+Systems&advancedPanel=true&entityTypes=ALL&entityStatusGroups=ALL

**Do you have any extra information?**

We are the number one fiat to crypto on/off ramp in New Zealand and have supported ETH and ERC-20 ecosystem from day one of our operations, guiding 100,000 + Users into the world of crypto.  We are a non-custodial exchange which encourages users to send to their own wallets or DeFi platform.  We have been trading for over 4 years, have expanded to South Africa and about to launch in Brasil.

Our sites:

easycrypto.com/au
easycrypto.com/nz

**Comment by corwintines** [comment]
Added in https://github.com/ethereum/ethereum-org-website/pull/5839
