### ISSUE TITLE
Show Discord invite if visitor didn't find page helpful

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3581]
**Is your feature request related to a problem? Please describe.**

We currently display a FeedbackCard component at the bottom of our documentation pages, e.g. https://ethereum.org/en/developers/docs/

![Image 2021-08-07 at 2 06 45 PM](https://user-images.githubusercontent.com/8097623/128613868-343bedf8-8cc6-4c5c-96d1-122559355c4f.jpg)

If the user selects "no" we just thank them for their feedback:
![Image 2021-08-07 at 2 08 07 PM](https://user-images.githubusercontent.com/8097623/128613874-0bbda73f-39b8-4e0c-aa25-665698d32fb9.jpg)

**Describe the solution you'd like**

I think we should invite them to our Discord to for additional support. e.g. "Join our public Discord and get the answer you're looking for".

Should we also consider adding this to the bottom of every page / most pages on the website?

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
For reference, we currently receive feedback input on this widget ~100 times per week & ~20% respond "No".

**Comment by ahmedprusevic** [comment]
Hey I can help with this PR

**Comment by minimalsm** [comment]
@ahmedprusevic Great! I've assigned you.
