### ISSUE TITLE
Explicitly point to good first issues label on Contributing page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3587]
**Is your feature request related to a problem? Please describe.**
We probably have lots of users land on the contributing page who like the idea of contributing to Ethereum.org but are intimidated by 1. how well implemented/polished Ethereum.org is and 2. the potential complexity of the codebase. We should explain that we have low-barrier to entry issues specifically designed to be tackled by open-source newbies.

**Describe the solution you'd like**

Explicitly explain we have the 'good first issue' label for new contributors and link to these issues.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by JaredFlomen** [comment]
Would love to help with this issue if it's not being tackled already

**Comment by minimalsm** [comment]
Hey @JaredFlomen. Thanks for the offer! I've assigned you to this issue.

I personally think this should live in the [How to work on ethereum.org section](https://ethereum.org/en/contributing/#how-to-update-content), but if you have other ideas we are open to that too ☺️

Feel free to ping me here or on discord if you need anything else to get going on this.

**Comment by JaredFlomen** [comment]
@minimalsm I'll put it there! Was thinking of it's own header like "New to open source" but I think under that header works.

**Comment by minimalsm** [comment]
@JaredFlomen feel free to do that if you believe that works out better for new contributors! 😀
