### ISSUE TITLE
Add new upcoming events to community page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3603]
**Is your feature request related to a problem? Please describe.**

https://www.ethlisbon.org/
https://online.ethglobal.com/#prizes

**Describe the solution you'd like**

Add these events to https://ethereum.org/en/community/#upcoming-events

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Patil2099** [comment]
I would love to work on this
