### ISSUE TITLE
Add "MEV" page to developer docs

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3610]
**Is your feature request related to a problem? Please describe.**

Lots of questions from the community around MEV & current resources on this are fairly scattered across the web.

**Describe the solution you'd like**

Let's build a new page in our [developer docs](https://ethereum.org/en/developers/docs/) about MEV (within the "Advanced" section). This page should explain what MEV is, why it is unique to blockchains (& specifically to smart contract platforms like Ethereum), the impact of MEV as well as projects (e.g. flashbots) within the community that are working to address it.

Here is a [loose template to follow](https://www.notion.so/efdn/Writer-template-4b40d196cde7422ca6a2091de33550bd)

**Describe alternatives you've considered**

**Acceptance criteria**
- There are clear prerequisites as per the template
- No knowledge is assumed, so concepts are explained or linked out to explanations
- Relevant tools / resources are explained and examples are provided when necessary
- Content is clearly separated into manageable sections with clear headers (h2s and h3s)
- There are links to further reading for those that want to learn more
- There are links to related topics within the ethereum.org developers section (e.g. mining)

**Additional context**

Throwing out some MEV resources:
- [MEV.wtf Virtual Summit](https://hackmd.io/ivUzk3piQEG8ALzCGbxlag)
- https://medium.com/dragonfly-research/we-live-in-a-mempool-backrunning-the-mev-crisis-a4ea0b493b05
- https://dyor-crypto.fandom.com/wiki/Miner_Extractable_Value_(MEV)#:~:text=%22MEV%20stands%20for%20Miner%20Extractable%20Value.&text=This%20is%20what%20we%20call,opportunities%20in%20the%20Ethereum%20mempool.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by nathanhleung** [comment]
👍
