### ISSUE TITLE
EIP-1559(AFTER THE LONDON UPGRADE docs mistake) 

### ISSUE THREAD

**Issue by ricky321u** [ethereum/ethereum-org-website#3611]
Is your feature request related to a problem? Please describe.
After checking out the docs of eip-1559(https://ethereum.org/en/developers/docs/gas/#post-london) , I think the docs of the calculation of the base fee and tip in the docs was wrong. I wonder how would the numbers of burned ETH + Taylor credited ETH + Miner tip was not equal to 1.0023, If that was true, maybe something should be explained more clearly?
Quote
"
When Jordan sends the money, 1.0023 ETH will be deducted from Jordan's account. Taylor will be credited 1.0000 ETH. Miner receives the tip of 0.000195 ETH. Base fee of 0.001953 ETH is burned.
"

Describe the solution you'd like
Add more explanation or the calculation was wrong , and I'm not sure what is it.

Want to contribute?
We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Nice spot! 👀 You're right the calculation is wrong.

Fancy slinging a PR to fix? If not I can do it. 

[This is the page](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/gas/index.md) that needs to be editted.

Correct figures are

```
BaseFee = 0.0021 ETH

Tip = 0.00021 ETH

BaseFee + Tip = TotalFee = 0.0023 ETH

**Comment by ricky321u** [comment]
Ya, I think i can do a pr.
But Also I think the calculations above also have to change to 21,000 * (100 + 10) = 2,310,000 gwei or 0.00231 ETH would be more accurate. 
For now it’s 0.0023, what do you think?

**Comment by minimalsm** [comment]
Yeah... I rounded it down when writing it because I thought the heuristic understanding was more important. Feel free to change or keep it the same - whatever you think works better 😀✌️ @ricky321u

**Comment by minimalsm** [comment]
Hey @ricky321u 

I can see you've done the work here but you've done the PR to your fork instead of to this repo 😀 Could you make the PR to this repo? Here is [a guide on doing that.](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by ricky321u** [comment]
Ya i will do it again, thanks for your reminding

**Comment by minimalsm** [comment]
Merged! Thanks ❤️
