### ISSUE TITLE
Request to add dapptools

### ISSUE THREAD

**Issue by mds1** [ethereum/ethereum-org-website#3613]
**Product name:** Dapptools

**Product description:** Dapptools is a suite of Ethereum focused CLI tools following the Unix design philosophy, favoring composability, configurability and extensibility. There are four tools that are part of the Dapptools suite:

- dapp - All you need Ethereum development tool. Build, test, fuzz, formally verify, debug & deploy solidity contracts.
- seth - Ethereum CLI. Query contracts, send transactions, follow logs, slice & dice data.
- hevm - Testing oriented EVM implementation. Debug, fuzz, or symbolically execute code against local or mainnet state.
- ethsign - Sign Ethereum transactions from a local keystore or hardware wallet.

**How long has it been around?**: Since 2018, maybe even earlier

**Where do you think it should go?**: The "Available Frameworks" and "Local Environments" pages, as seen in this PR for Dapptools: https://github.com/ethereum/ethereum-org-website/pull/3598

**GitHub URL**: https://github.com/dapphub/dapptools

**Docs URL**: https://dapp.tools/

**Is the product open source?**: Yes

**Additional context**: @samajammin [convinced me](https://twitter.com/samonchain/status/1421688283273195521) to open the PR! 😁

**Comment by minimalsm** [comment]
Approved and merged, thanks 😀✌️
