### ISSUE TITLE
Add a way to credit all contributors

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#362]
**Is your feature request related to a problem? Please describe.**

We'd like to find a way to recognize every contribution to ethereum.org, not merely code contributions. We could do a better job to show our love & appreciation, particularly with our [Translation Program](https://github.com/ethereum/ethereum-org-website#translation-program), where translations are typically committed to this repository by someone other than the volunteer(s) who dedicated their time translating content.

**Describe the solution you'd like**

A couple options:
- [All Contributors](https://allcontributors.org/docs/en/overview) adds a convenient bot to add contributors to the README by their contribution category
- The [Proof of Attendance Protocol](https://www.poap.xyz) to issue ERC-721 tokens to contributors

**Describe alternatives you've considered**
Would love to hear input from community members on this!

**Additional context**

Currently [we're tweeting acknowledgements](https://twitter.com/ethdotorg) of our translation contributors & plan to give shout-outs to key contributors in [our Development Updates](https://blog.ethereum.org/2019/09/18/Development-Update-0-Ethereum.org/) but none of these methods have to be mutually exclusive.

**Comment by P1X3L0V4** [comment]
@samajammin I suggest to start with a simple table with all contributors plus their roles in the project. I personally like template that [nerd-fonts repository uses](https://github.com/ryanoasis/nerd-fonts/blob/master/CONTRIBUTORS.md). That way it is not only visually pleasing but also can be informative. Plus all translators that contributed via Crowdin can be aknowledged that way by making a PR themselves. Please let me know what  you think.

**Comment by jjmstark** [comment]
Great idea @samajammin - the `All Contributors` bot to add to the readme.md feels like a great first solution, and we can do more over time like PoAP and other suggestions.
