### ISSUE TITLE
Allow submission of 3rd party tutorials

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3620]
**Is your feature request related to a problem? Please describe.**

I think our developer tutorials section should also display popular tutorials on external sites, like the Hardhat tutorial & scaffold-eth tutorials.

**Describe the solution you'd like**

I think we could add a static file, e.g. /data/tutorials.json with some basic info, e.g. 
```
{
  url: "",
  title: "",
  description: "",
  author: "",
  authorGithub: "",
  tags: "",
  skillLevel: "",
  publishDate: ""
}
```

Then display theme as the same cards on https://ethereum.org/en/developers/tutorials/

![image](https://user-images.githubusercontent.com/8097623/129423255-8776fc38-1f9e-4a40-89e7-5b049e9d22a9.png)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ahmedprusevic** [comment]
I can help with this

**Comment by minimalsm** [comment]
@ahmedprusevic awesome! I've assigned you.

**Comment by ahmedprusevic** [comment]
Hey could you guys provide me with at least one tutorial to put in JSON file . Data structure needed is 
```
{
        "url": "",
        "title": "",
        "description": "",
        "author": "",
        "authorGithub": "",
        "tags": [""],
        "skillLevel": "",
        "timeToRead": "",
        "publishDate": ""
    }
```

**Comment by minimalsm** [comment]
Hey @ahmedprusevic. Here is an example of an external tutorial:

```js
{
  "url": "https://docs.alchemy.com/alchemy/tutorials/how-to-create-an-nft/how-to-mint-a-nft",
  "title": "How to Mint an NFT",
  "description": "This tutorial describes how to mint an NFT on the Ethereum blockchain using Web 3",
  "author": "Alchemy",
  "authorGithub": "https://github.com/alchemyplatform",
  "tags": ["solidity"],
  "skillLevel": "beginner",
  "timeToRead": "10 minutes",
  "publishDate": "08/08/2021"
}
```
