### ISSUE TITLE
AAVE

### ISSUE THREAD

**Issue by jvtamanini20** [ethereum/ethereum-org-website#3622]
We'll consider [our article policy](https://ethereum.org/en/contributing/adding-articles/) when reviewing the tutorial, so please take a look there first.

**Tag your tutorial**

**Tutorial title**

**Tutorial description**

**Publication**

**Skill level**

**Paste in your tutorial below**

**Comment by minimalsm** [comment]
Hey @jvtamanini20

Not sure what this issue is for. Could you clarify, please? Closing this out for now but feel free to reopen with more info.
