### ISSUE TITLE
Argent logo does not display correctly on the Find an Ethereum Wallet page

### ISSUE THREAD

**Issue by michael60634** [ethereum/ethereum-org-website#3623]
**Describe the bug**

**To Reproduce**

1. Go to 'https://ethereum.org/en/wallets/find-wallet/'
2. Scroll down to 'Argent'
3. See error

**Expected behavior**

Logo should be visible.

**Screenshots**

https://mega.nz/file/6gZknBYT#Z_Bb1VYWC1ouAD5rr_Befo07sd7dZoHFJCY6Nxbx06s

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [92.0.4515.131]

**Comment by minimalsm** [comment]
Thanks for reporting. Fixed in #3625
