### ISSUE TITLE
crypto collaborate

### ISSUE THREAD

**Issue by Wangchingold** [ethereum/ethereum-org-website#3624]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

**Product description:**

**How long has it been around?**

**Where do you think it should go?**

**GitHub URL**

**Docs URL**

**Is the product open source?**

**Additional context**

**Comment by minimalsm** [comment]
Hey @Wangchingold 

Not sure what this issue is for. Could you clarify, please? Closing this out for now but feel free to reopen with more info.

**Comment by Wangchingold** [comment]
.....wat up
