### ISSUE TITLE
Automatically pull latest upgrades blog posts

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#3632]
**Is your feature request related to a problem? Please describe.**
Eth2 blog posts by Danny Ryan and Ben Edgington are currently listed at the bottom of https://ethereum.org/en/eth2. These are essentially hard-coded into our repo, and do not update when new blog posts by Danny or Ben are released. 

**Describe the solution you'd like**
Research options for pulling latest Eth2 related blog posts in automatically, and reduce need for hard-coding this information.

**Describe alternatives you've considered**
- API requests (haven't looked into potential endpoints)
- Perhaps a hook/bot that puts up a PR to add any new articles to the list when they're posted
- Continue to manually keep an eye on these and update manually 👎🏻 

**Additional context**
Issue #3627 brought this to my attention, as several months passed before this section way updated.

Perhaps solutions here could be generalized to alternative blog posts beyond Eth2 as well, for other parts of the site. 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
+1

When we get to this we'll want to refactor to only display a set amount (probably 4) of articles. Currently, it'll pull and display an infinite amount.

**Comment by samajammin** [comment]
I believe I remember Ben Edgington mentioning on a podcast that he maintains an RSS feed... 🧐

**Comment by samajammin** [comment]
Here's Ben's RSS feed: https://benjaminion.xyz/newineth2/rss_feed.xml

**Comment by samajammin** [comment]
There's also a feed for the EF blog: https://blog.ethereum.org/feed.xml

We _could_ parse this for Danny's posts. I think a better solution would be to set up a feed specifically for the [R&D category](https://blog.ethereum.org/category/research-and-development/) like there is for the [Devcon category](https://blog.ethereum.org/category/devcon/): https://blog.ethereum.org/feed/category/devcon.xml

Here's a PR showing how to add an RSS feed on the blog: https://github.com/ethereum/blog/pull/619/files

From there we'd still have to do some filtering (e.g. for if <title> contains "finalized") but I think it could get us there.

Once we have our RSS feeds, best approach might be to use a Gatsby source plugin so we can query this data via GraphQL, e.g. https://github.com/mottox2/gatsby-source-rss-feed

**Comment by cdomashn** [comment]
At the moment, I have some bandwidth to research Options for you if you would like.

In the interim, [https://ethereum.org/en/eth2/](url) probably needs to be updated manually. See Edition83 on [https://hackmd.io/@benjaminion/eth2_news/https%3A%2F%2Fhackmd.io%2F%40benjaminion%2Fwnie2_211203](url) ![Ben83](https://user-images.githubusercontent.com/58366873/146685963-caca9aff-ee18-4a8c-9214-18f381e5419b.jpg)
vs Edition82 on [https://ethereum.org/en/eth2/](url):
![Eth2](https://user-images.githubusercontent.com/58366873/146685972-4753f18d-f6d9-4a5c-86f2-03fec70b3e99.jpg)

**Comment by minimalsm** [comment]
Looks like this was accidentally closed in #4865 but this is still an issue.

**Comment by wackerow** [comment]
Closing this out given completion of the PoS upgrade, and discontinuation of these blog entries.
