### ISSUE TITLE
Create a guide/handbook for Ethereum Meetup Organizers

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3646]
**Is your feature request related to a problem? Please describe.**

Wondering if there's valuable resources we could provide for community organizers?

**Describe the solution you'd like**

Create a subpage / series of resources within [the Community section](https://ethereum.org/en/community/) of our site.

We could call out specific opportunities available to community organizers, e.g. 
- https://consensys.net/developers/buidlnetwork/
- https://esp.ethereum.foundation/en/devcon-grants/

**Describe alternatives you've considered**

Merely link out to other resources from our Community page, e.g.
- https://consensys.net/developers/buidlnetwork/
- https://anett.gitbook.io/emsp/

**Additional context**

It appears the Ethereum Meetup Support Program has been discontinued (Annett worked on it for 6 months until September 2020). Wondering if there's unique opportunity for us to pick up the torch here to maintain, expand on & translate these kind of resources.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by anettrolikova** [comment]
I'm Anett (with one n), otherwise it looks great :)

**Comment by corwintines** [comment]
https://ethereum.org/en/community/get-involved/#meetups

It looks like most of this initiative has been covered in this page now. Going to close this out.
