### ISSUE TITLE
Fill

### ISSUE THREAD

**Issue by yokymia** [ethereum/ethereum-org-website#3647]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @yokymia :) Not sure what this issue is for, could you clarify? Closing this out for now but feel free to reopen with more info.
