### ISSUE TITLE
Expand Plasma developer docs

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3655]
**Is your feature request related to a problem? Please describe.**

The [developer docs for Plasma](https://ethereum.org/en/developers/docs/scaling/plasma/) are pretty bare and don't provide a good overview of Plasma.

**Describe the solution you'd like**
- Expand upon the current docs to more thoroughly describe Plasma
- Explain [the mass exit problem](https://www.google.com/search?q=plasma+mass+exit+problem)
- Probably explain that Plasma will (or has) fall out of favour, with the community support gathering around other Layer 2 solutions.

**Additional context**
I've collected some potential resources for the convenience of whoever works on this issue:

- https://blog.matic.network/explaining-plasma-and-rollups-advantages-and-limitations-matic-network/
- https://academy.binance.com/en/articles/what-is-ethereum-plasma
- https://medium.com/dragonfly-research/the-life-and-death-of-plasma-b72c6a59c5ad#
- https://youtu.be/BgCgauWVTs0?t=363
- https://ethresear.ch/t/basic-mass-exits-for-plasma-mvp/3316

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by shadforth** [comment]
I'll take this @minimalsm 🙂 give me a week

**Comment by minimalsm** [comment]
Thanks for offering to help on this @shadforth. I've assigned you 😬 if you need any help or a second pair of eyes feel free to ping here.

**Comment by b17z** [comment]
@minimalsm I can take this on if it's still open and @shadforth is blocked for whatever reason. Happy to collab, too, if they're available.

**Comment by minimalsm** [comment]
Hey @b17z, thanks for offering to help. I've assigned you! :-)

**Comment by corwintines** [comment]
Closing this out as we merged the awesome work done by @emmanuel-awosika!
