### ISSUE TITLE
Add Lambda School to developer bootcamps

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3660]
**Is your feature request related to a problem? Please describe.**

https://lambdaschool.com/learn-blockchain-development

**Describe the solution you'd like**

Add to "Developer bootcamps" section of https://ethereum.org/en/developers/learning-tools/

**Additional context**

I suppose we don't have clear listing criteria for these type of additions but Lambda School is a fairly well known, well funded & highly regarded online web development bootcamp.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MukulKolpe** [comment]
Hey @samajammin, can I work on this issue..

**Comment by samajammin** [comment]
Awesome, thanks! Should be fairly straightforward. Here's where that data is: https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/developers/learning-tools.js#L141

The one tricky piece of Gatsby is using GraphQL for sourcing images, but you should be able to follow the pattern of other items there. More on that here: https://github.com/ethereum/ethereum-org-website#image-loading-and-api-calls-using-graphql

**Comment by samajammin** [comment]
Potential image: https://assets-global.website-files.com/5cd091cfb5499f22bdf72905/5e1230986a42a4d4965e22f6_icon.png
