### ISSUE TITLE
Create ERC-777 developer docs page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3666]
**Is your feature request related to a problem? Please describe.**
We currently have [token standards pages](https://ethereum.org/en/developers/docs/standards/tokens/) for both ERC-20 and ERC-721 but not ERC-1155 or ERC-777.

**Describe the solution you'd like**
Create a page similar to the ERC-20/ERC-721 pages for ERC-777 tokens.

**Additional context**
Some resources that may be useful
- https://docs.openzeppelin.com/contracts/3.x/tokens
- https://docs.openzeppelin.com/contracts/3.x/erc777
- https://eips.ethereum.org/EIPS/eip-777

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by il3ven** [comment]
Hi, I'll like to work on it. I am not an expert about token standards but I'll try to write something up.

**Comment by minimalsm** [comment]
Hey! Thanks for the offer to help ☺️  I've assigned you. The additional resources should provide quite a good starting ground to work on but if you need anything at all to get this over the line just let me know here or ping on the ethereum.org discord 😃
