### ISSUE TITLE
Create ERC-1155 developer docs page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3667]
**Is your feature request related to a problem? Please describe.**
We currently have [token standards pages](https://ethereum.org/en/developers/docs/standards/tokens/) for both ERC-20 and ERC-721 but not ERC-1155 or ERC-777.

**Describe the solution you'd like**
Create a page similar to the ERC-20/ERC-721 pages for ERC-1555 tokens.

**Additional context**
Some resources that may be useful
- https://docs.openzeppelin.com/contracts/3.x/tokens
- https://docs.openzeppelin.com/contracts/3.x/erc1155
- https://academy.binance.com/en/glossary/non-fungible-token-nft

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by nataschaberg** [comment]
Hey :), I would love to contribute here.

**Comment by minimalsm** [comment]
Hey! Thanks for offering to help @nataschaberg 

I've assigned you 😬 if you need any help feel free to ping.

**Comment by minimalsm** [comment]
@nataschaberg just double-checking you've seen I assigned you 😬

**Comment by nomebahi** [comment]
I love to the project```
- > 
```
``@nomebahi

**Comment by minimalsm** [comment]
Opening this back to the community to work on 😀 ping here if you're interested in working on this issue.

**Comment by shryasss** [comment]
I would like to work on this

**Comment by shryasss** [comment]
While doing 'yarn start', I get a bunch of errors regarding Gatsby. I found the index.md files I have to edit though, and have started editing using a readme interpreter.

**Comment by minimalsm** [comment]
The first thing I'd check is - do you have the Gatsby CLI installed? ([docs](https://www.gatsbyjs.com/docs/tutorial/part-0/#gatsby-cli)) 

Other than that, if you can post the error output we can probably work it out from that.

You can also [join the discord](https://discord.gg/CetY6Y4) and post in the #contributing channel and we'll try to debug this for you further 😀
