### ISSUE TITLE
Add link to the Web3Bridge website to the site

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#3670]
**Is your feature request related to a problem? Please describe.**

Web3Bridge is an initiative, focused on identifying, training and supporting Ethereum developers from African countries.
https://www.web3bridge.com/

**Describe the solution you'd like**

Add a link to their website and a quick summary to the site to help raise awareness about the initiative.

**Comment by minimalsm** [comment]
Closed by #3671
