### ISSUE TITLE
Site does not redirect to secure https

### ISSUE THREAD

**Issue by tobiv** [ethereum/ethereum-org-website#368]
**Describe the bug**
I just visited ethereum.org and noticed the browser showed it as Not Secure. I then entered https:// manually which works

**To Reproduce**
1. Go to ethereum.org (don't enter http:// or https://)
2. Site is Not Secure
3. This only works if you haven't visited the https URL before / if your cache/HSTS is clear

**Expected behavior**
The https site should be configured as canonical redirect (by the way, also choose with or without www, currently both work and should redirect to one or the other).

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1
 - Browser: Firefox
 - Version: 70.0

**Additional context**
I would create a pull request, but looked over the code and I don't think the server configuration is in the public repo.

**Comment by samajammin** [comment]
Thank you for reporting this! Brave browser (thankfully) redirects to HTTPS but I was able to reproduce this in Firefox & Chrome. Will dig into this.

**Comment by samajammin** [comment]
This is fixed. Thanks again for raising @tobiv! Please re-open if you see any issues.
