### ISSUE TITLE
Opera Crypto Wallet

### ISSUE THREAD

**Issue by spiolat** [ethereum/ethereum-org-website#3681]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet globally accessible?**

Yes

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Opera crypto wallet is audited by Opera security team.
Opera is NASDAQ listed company and the security team takes care of products (web browser, news, fintech)  for its 400M users globally.

**Does the wallet have fiat on-ramps?**

Yes (may vary depend on location and partner)

**Does the wallet allow users to explore dapps?**

YES, dapp's work, web3 support in browser

**Does the wallet have integrated defi/financial tools?**

Not yet

**Can a user withdraw to their card?**

Soon

**Does the wallet offer limits protection?**

limit of onramp partner only

**Does the wallet allow high-volume purchases?**

limit of onramp partner only

**Does the wallet have an integrated token swap?**

Not yet

**Is the wallet a multi-signature wallet?**

No

**Wallet title**

Opera browser (built-in crypto wallet)

**Wallet description**

Built-in crypto wallet in Opera Touch on iOS and Opera for Android
The first major browser to integrate a crypto wallet, enabling seamless access to the emerging web of tomorrow (Web 3).

**Wallet logo**

https://brand.opera.com/1472-2/opera-logos/

**Background colour for brand logo**

https://brand.opera.com/1472-2/opera-logos/

**URL**

https://www.opera.com/crypto

**Comment by minimalsm** [comment]
Approved! Thanks @spiolat 

@all-contributors please add @spiolat for docs

**Comment by spiolat** [comment]
Thanks gents :)
