### ISSUE TITLE
CoinSwitch Kuber

### ISSUE THREAD

**Issue by iamkabilan** [ethereum/ethereum-org-website#3718]
Before suggesting an exchange, make sure you've read [our exchange listing policy](https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**
    CoinSwitch Kuber is based in India. Currently it operates only in India.

**Which currencies are accepted by this exchange?**
    It accepts INR(Indian Rupee)

**Do you have any proof that they're a legitimate company?**
[About CoinSwitch Kuber](https://coinswitch.co/in/about-us)

**Do you have any extra information?**
  https://coinswitch.co/kuberverse/
  

- Its been working for more than 4 years [[source]](https://coinswitch.co/kuberverse/four-years-of-crypto-revolution-coinswitch-turns-four-2017-2021/)
- CoinSwitch market cap values $500 Million [[source]](https://economictimes.indiatimes.com/tech/funding/coinswitch-kuber-valued-at-500-million-after-raising-25-million-from-tiger/articleshow/82195549.cms)
- It was backed by investors like Tiger capital, Sequoia capital, etc
-
https://pitchbook.com/profiles/company/436520-71

website: https://coinswitch.co/

**Comment by minimalsm** [comment]
@iamkabilan thanks for raising this issue.

Can I check if CoinSwitch Kuber's code has undergone a security audit? If so, could you provide a link to the audit. Thanks 👍

**Comment by minimalsm** [comment]
Hey @iamkabilan, I did some more digging. It seems that they have stopped withdrawals? https://coinswitch.co/kuberverse/crypto-withdrawal-temporarily-disabled/ 

Given CoinSwitch is quite popular in India is this something you've heard about at all?

**Comment by iamkabilan** [comment]
Yeah, I am using CoinSwitch it is popular in India

Withdrawls are temporarily disabled

**Comment by minimalsm** [comment]
@all-contributors please add @iamkabilan for ideas
