### ISSUE TITLE
ethereum.org/en/community/

### ISSUE THREAD

**Issue by Megalo-don** [ethereum/ethereum-org-website#3720]
**Ethereum Jobs**

Guys, I checked it out and apparently **the Blocktribe link is broken**. When accessing, a message that the domain registration is expired, maybe their project has been discontinued.

_"This job board website is either expired or its domain name is invalid. If you are the site owner, click below to login."_

**Comment by MukulKolpe** [comment]
@minimalsm, any updates on this??
Their website is not up yet...(https://blocktribe.com/)

**Comment by minimalsm** [comment]
Yeah... probably best removing the link for now and we can re-add it if/when the site goes live again. Fancy making up a PR for this @MukulKolpe ?

**Comment by MukulKolpe** [comment]
Yes sure!!! can you assign me...

**Comment by minimalsm** [comment]
@MukulKolpe assigned :)
