### ISSUE TITLE
Exodus

### ISSUE THREAD

**Issue by Paulchemouni** [ethereum/ethereum-org-website#3729]
**It's a software wallet, but there is an exodus app for trezor hardware wallets.**
**https://github.com/ExodusMovement**
**Users can use DApps like compound directly in the wallet**
**Users can earn assets directly from the wallet** 
**the wallet has an integrated token swap.**
**Wallet title : Exodus**
**Wallet description : Send, receive & exchange Bitcoin and 100+ cryptocurrencies with ease on the world's leading Desktop, Mobile and Hardware crypto wallets**
![téléchargement](https://user-images.githubusercontent.com/87277848/131026343-b2ae71f2-82d8-4205-98f7-bf419d74f625.png)

**#2200d4**
**URL : exodus.com**

**Comment by enriavil1** [comment]
you want to implement the wallet in the page using their framework ether.js?

**Comment by Paulchemouni** [comment]
Yes, it’s that. Cordialement,Paul Chemouni. De : Enrique Jose Avila AsapcheEnvoyé le :samedi 28 août 2021 12:36:33À : ethereum/ethereum-org-websiteCc : Paul Chemouni; AuthorObjet :Re: [ethereum/ethereum-org-website] Exodus (#3729) you want to implement the wallet in the page using their framework ether.js?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by minimalsm** [comment]
Hey @Paulchemouni. Could you edit or re-submit this to use [the wallet template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=Type%3A+Feature%2C+Type%3A+Content&template=suggest_wallet.md&title=) so the team has all the necessary information to review the wallet. Thanks in advance 😬👍

**Comment by minimalsm** [comment]
Closing pending more information. Feel free to reopen or create an issue with the wallet issue template above.
