### ISSUE TITLE
What determines the criteria for listing a dapp on the site?

### ISSUE THREAD

**Issue by jamesmorgan** [ethereum/ethereum-org-website#3732]
I noticed there is a centralised, custodial NFT exchange/platform listed under dapps and I am wonder why they would be?

`Nifty Gateway` are doing good stuff in attracting new users but it's more that it clashes with some of the points raised below e.g. they required KYC'd login, payments are settles off-chain and not atomically, and generally not inline with the dapp wordings that are listed, so I was just wondering why they are be promoted as a top dapp from the Ethereum foundation? 

There are many other more dapp like NFT platfroms such as ArtBlocks, KnownOrigin, Zora, Mintbase etc and many others. (note I work for KO 😸 )

**Comment by enriavil1** [comment]
Yeah I am pretty sure it's just an error

**Comment by jaysonmald35** [comment]
Help

**Comment by enriavil1** [comment]
What do you need help with? I can collaborate to this.

**Comment by minimalsm** [comment]
Hey @jamesmorgan good question 🤔...

Our Product Listing policy is admittedly vague when it comes to questions like this. I'm going to leave this issue open and unsolved whilst we clarify our position on this. Thanks for raising the point 🙏

**Comment by minimalsm** [comment]
@all-contributors please add @jamesmorgan for ideas

**Comment by minimalsm** [comment]
Closing in favour of #3792
