### ISSUE TITLE
Re-think social footer links

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3746]
**Is your feature request related to a problem? Please describe.**

This is just a hunch that I'm not backing up with any data but I suspect our footer links create confusion for site visitors:
![Home ethereum org 2021-08-29 at 12 47 16 PM](https://user-images.githubusercontent.com/8097623/131263462-d7fc74f4-a229-4313-9828-ba75b265a6d4.jpg)

My hunch is that it's not clear what these icons represent. Are these the "official" Ethereum social links? We seem to give the impression that they are. Anecdotally, many people drop into the ethereum.org Discord server thinking it is the Ethereum Discord & ask questions irrelevant to ethereum.org. This is understandingly confusing for people new to Ethereum. Footer links are a common patterns for projects & organizations to list their official social channels on their website but ethereum.org is not a standard website & Ethereum not a typical project.

Currently we link to:
- ethereum.org Github repo: https://github.com/ethereum/ethereum-org-website
- ethereum.org Twitter: https://twitter.com/ethdotorg
- EF YouTube channel: https://www.youtube.com/channel/UCNOfzGXD_C9YMYmnefmPH0g
- ethereum.org Discord server: https://discord.com/invite/CetY6Y4

This is a somewhat strange mix of ethereum.org & EF social presences - e.g. why do we link to the EF YouTube but not the EF Twitter? Why not add popular community social presences, like r/ethereum?

**Describe the solution you'd like**

I think we should reconsider the goals of these social links - what is the main purpose? What problem are we trying to solve for users? How can we increase awareness that there is no "official" Ethereum social channels?

One option might to be: display a bunch of social icons (e.g. including Reddit & Facebook) that all link to the Community page. Then in the community page we explicitly explain that there is no official social channels - no one controls Ethereum, there is no official Ethereum team or support - but there are many communities within the Ethereum ecosystem. From there, we could link out to a variety of credible options & organize them by categories based on what the visitor might be looking for (e.g. R&D vs. trading vs. building).

Regarding ethereum.org social links, I think these would be most relevant listed on the [About Us page](https://ethereum.org/en/about/) where it's clear we're talking about ethereum.org, not Ethereum more broadly.

**Describe alternatives you've considered**

- Remove the footer social icons entirely
- Add a blurb that explicitly states these are ethereum.org social links, not Ethereum or EF more broadly

**Additional context**

I think this type of change could also feed into ideas we've had on a "Ethereum support" page or section where people can go for common issues they encounter when using Ethereum, as it seems many Discord queries often revolve around these common issues. Related issues: #2767 #2077 #3448

**Comment by vluna** [comment]
I was thinking that maybe if you want to keep the footer social links, a label could be added. Something like "Follow our community" and then link to a page with the detail explanation and more links, while also keeping the main social channels on the footer.

<img width="793" alt="Screen Shot 2021-11-06 at 8 09 56 AM" src="https://user-images.githubusercontent.com/8848639/140609095-faeb6566-601e-4f5c-bd20-59e183d2c19f.png">

This might help to keep the footer social links, explain or give a hint that it is a community, and a link to different community channels users can join.

Just an idea that might work.

**Comment by samajammin** [comment]
My latest thinking on this is still to:
- Update all footer social links to https://ethereum.org/en/community/online/
- Highlight social links specific to ethereum.org on https://ethereum.org/en/about/
- Highlight social links specific to the Ethereum Foundation on https://ethereum.org/en/foundation/

**Comment by corwintines** [comment]
Ive made a pull request to remove the YouTube link from the Footer. I agree this causes some confusion as everything else goes to something related to ethereum.org, and then theres a random Ethereum Foundation link. 

At this point though, I think its safe to keep our other socials there. I think we just have to accept some of the traffic to our discord where we will deal with some spam. 

We also have https://ethereum.org/en/community/online/ which contains a lot of the social links suggested.
