### ISSUE TITLE
Validation Node Burn Alternative proposal

### ISSUE THREAD

**Issue by emerbaum** [ethereum/ethereum-org-website#3755]
Presently if a validator acts in bad faith we are burning the tokens. 
My issue with this is that if an exchange or community staking pool has an issue third party stakers could be burned hard.

What if instead of burning it, they got frozen in a smart contract for a period of time, say N^2 months for each incident?
This way bad actors loose access to the funds and in cases of repeat attempts they get locked further.
third party stakers will see that they are locked and will move there eth out to other nodes as soon as the lockout period is over.

Pools with a track record of good faith will be able to attract the etherium for staking in the long run.

What do yall think?

**Comment by minimalsm** [comment]
Hey @emerbaum 😬 This repo is for the ethereum.org website, not really for posting ideas about Ethereum development generally.

One place that might be worthwhile getting involved in for similar discussions is the [Ethereum Research and Development Discord](https://discord.gg/qGpsxSA). Closing this issue out for now.
