### ISSUE TITLE
Re-add Blocktribe to Jobs Section

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3764]
**Is your feature request related to a problem? Please describe.**
We have removed [Blocktribe.com](https://blocktribe.com/) from the jobs section [in PR #3762](https://github.com/ethereum/ethereum-org-website/pull/3762) as the site has been down for 5 days. 

**Describe the solution you'd like**
We should re-add Blocktribe to the jobs section when the site is live again. 

**Describe alternatives you've considered**
None

**Want to contribute?**

We love contributions from the Ethereum community! If Blocktribe.com goes live again feel free to comment below and create a PR to re-add it to the site.

**Comment by farismecinovic** [comment]
I'd like to help with this one when Blocktribe is live again

**Comment by minimalsm** [comment]
Hey @farismecinovic! Thanks for offering to help. I'm not going to be tracking this myself (who knows if/when it'll go back up) 
so not going to assign this to anyone right now. Feel free to make a PR to re-add it to the site when it does go live again.

**Comment by vj-codes** [comment]
@minimalsm hey I would like to work on this!

**Comment by minimalsm** [comment]
@vj-codes unfortunately this is blocked. Blocktribe website hasn't gone back up 😞  I'd close this issue but they still seem to be active on Twitter oddly...

**Comment by minimalsm** [comment]
Still not up, closing this out :-)
