### ISSUE TITLE
The Ethereum Whitepaper Year Published + Issues around Academic Citation

### ISSUE THREAD

**Issue by agorismlabs** [ethereum/ethereum-org-website#3768]
Hello Ethereans,

I am an academic currently teaching and researching Ethereum and I think there is an issue around how best to cite the whitepaper. 

On Google Scholar you can see that there are many different versions of the paper cited: https://scholar.google.co.kr/citations?user=DLP9gTAAAAAJ&hl=en

The most popular links to a website called Translated Whitepaper: https://scholar.google.co.kr/citations?view_op=view_citation&hl=en&user=DLP9gTAAAAAJ&citation_for_view=DLP9gTAAAAAJ:IjCSPb-OGe4C This seems like it could disappear relatively easily. I believe this is cited over the website because it is PDF form which the website version is not. The year given for this paper is 2014.

The next most popular appears to be a Polish translation: https://scholar.google.co.kr/citations?view_op=view_citation&hl=en&user=DLP9gTAAAAAJ&citation_for_view=DLP9gTAAAAAJ:5nxA0vEk-isC The year given for this paper is 2013.

The whitepaper on the main website is also not very citable. It is not a PDF but a static webpage and has no pagination. This renders it almost unusable by most academic citation software: https://ethereum.org/en/whitepaper/ This refers, but gives no more information, to 2013 as the original date. 

It is also not clear *when* the whitepaper was originally published. Some such as the second most popular translation suggest 2013 and I see this date referred to on the website (with no link). But then the first most popular suggests 2014. This means anyone new to Ethereum has no idea when the whitepaper was actually published. 

As new academic attention comes to Ethereum we need to sort this situation out as it will have recursive effects down the years as the citations become more compounded. I think it looks a bit unprofessional and makes life needlessly difficult for those trying to study us. 

Solution: an official website version of the Ethereum whitepaper with pagination and available as a PDF. 

Separate from the paper - perhaps in a text box just above it - a contextual explanation of when the paper was published, in what context, and where. Perhaps a note on the various iterations of the paper.

**Comment by minimalsm** [comment]
Thanks for raising this concern!

Closing this issue to keep discussion housed in #3794.

@all-contributors please add @agorismlabs for ideas
