### ISSUE TITLE
Missing whitespace

### ISSUE THREAD

**Issue by ndrozd** [ethereum/ethereum-org-website#3775]
**Describe the bug**

**To Reproduce**

1. Go to https://ethereum.org/en/glossary/#crosslink
2. See error of "Beacon Chain**in** the"

**Expected behavior**

"Beacon Chain in the"

![image](https://user-images.githubusercontent.com/6696080/131549412-89af0dac-136b-4ba9-b01c-895e7194111c.png)

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Version Latest

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ndrozd** [comment]
This would be my first contribution, so please advise if there was a better way to make it :) Thanks!

**Comment by minimalsm** [comment]
No this was great! Thanks @ndrozd 🙏
