### ISSUE TITLE
(DEX) Add Exodus Exchange for United States of America

### ISSUE THREAD

**Issue by bmdhodl** [ethereum/ethereum-org-website#3778]
**What geographical restrictions apply to this exchange?**

Exodus exchange API providers do not allow customers in AL, HI, LA, NY, OR, and WA to exchange with their service, which extends to Exodus customers. This is due to prohibitive regulations in these states.

**Which currencies are accepted by this exchange?**

A link to all accepted currencies - https://www.exodus.com/status/#assets

**Do you have any proof that they're a legitimate company?**

https://www.exodus.com/about/

**Do you have any extra information?**

Exodus was founded in 2015 by JP Richardson and Daniel Castagnoli, 6 years in this crypto journey.

https://www.exodus.com/investors/

**Comment by minimalsm** [comment]
Hey @bmdhodl, could you confirm if Exodus's dex product has undergone an external security audit? If so, could you provide a link to the audit? Thanks 😀

**Comment by konopkja** [comment]
exodus has been added to the list of wallets, so closing this issue.
