### ISSUE TITLE
calling all white hats..

### ISSUE THREAD

**Issue by ifstatic** [ethereum/ethereum-org-website#3780]
im fairly new to cryptocurrency.. i think, just over a year in it.. But is there a target i dont see on my back. i have been dealing with hackers constantly.. i literally am ready to walk away.. i have lost10x more then ever made.. reformating my pc always 2 phones destroyed.. becasuse they gety so damn hot.. This might   be the wrong place to ask, and im sorry if it is but.. who do i go to for help..

**Comment by Clashinm** [comment]
you and me both lets get together in say 3 hours and work thru this i have
absolutely no idea but maybe we can put our brains together

**Comment by minimalsm** [comment]
Hey @ifstatic this is the repo for ethereum.org (the website), rather than Ethereum support generally. You can [join the etheruem.org discord](https://discord.gg/CetY6Y4) if you are looking to chat about these issues in a more appropriate place, we can try to help you there ✌️

**Comment by ifstatic** [comment]
How do u get on discard when my  accounts are gone 2FA gone phone number linked to another account.. start my 5 zero email account.. thanks for the response though cheers

**Comment by Clashinm** [comment]
@ifstatic honestly idk what you mean, im new
