### ISSUE TITLE
Add external tutorials

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3786]
**Is your feature request related to a problem? Please describe.**

Now that #3630 is merged we have the ability to add external tutorials 🚀 

**Describe the solution you'd like**

I'm open to what we'd like to add 😄 - no need to add everything at once.

Here's a few tutorials in the space I think are particularly excellent & worth calling attention to:
- https://hardhat.org/tutorial/
- https://dev.to/dabit3/the-complete-guide-to-full-stack-ethereum-development-3j13
- https://github.com/austintgriffith/scaffold-eth/tree/simple-nft-example
- https://github.com/austintgriffith/scaffold-eth/tree/challenge-1-decentralized-staking

**Describe alternatives you've considered**

Wait until folks submit tutorials 😃

**Comment by minimalsm** [comment]
Working on this.

**Comment by PrechyDev** [comment]
There's https://dappuniversity.com/bootcamp

His channel on youtube is full of contents relevant to blockchain development
