### ISSUE TITLE
Update language names for consistency

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#3788]
**Is your feature request related to a problem? Please describe.**

The list of languages on the website includes localized language names. However, there are some inconsistencies between languages, specifically the capitalization.
https://ethereum.org/en/languages/

Most languages are capitalized, apart from 'čeština' and 'norsk'.
Additionally, 'Slovenija' (meaning Slovenia) should be changed to 'Slovenščina' (meaning Slovenian).

**Describe the solution you'd like**

Update the translations.json file to ensure consistency between language names.

**Additional context**

![Languages list](https://user-images.githubusercontent.com/37338979/131751651-a7875819-7a36-48ac-a18d-dbaf734b849f.png)
![Languages list 2](https://user-images.githubusercontent.com/37338979/131751866-5b6a3968-37d9-4651-b207-327d6284c17d.png)

**Comment by minimalsm** [comment]
Closed in #3789. Thanks Luka 👍
