### ISSUE TITLE
Update dapp listing policy

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3792]
**Is your feature request related to a problem? Please describe.**
Currently, our [Adding Products page](https://ethereum.org/en/contributing/adding-products/) does not make a very clear distinction between wallets and dApps. Non-custodial is listed as a **nice-to-have** whereas the team agree that for dApps non-custodial should be **a requirement.**

**Describe the solution you'd like**
We should re-write the listing policy to make clear distinctions between wallets, dApps and other products and, if necessary, create separate sections/pages for different types of products.

**Describe alternatives you've considered**
None

**Additional context**
Initial discussion in #3732

**Comment by corwintines** [comment]
Going to close this issue out for now. As we rethink product listings I think we will either revive this issue, or come up with a more appropriate body of work to address that.
