### ISSUE TITLE
Add new 'Typed Transaction Envelope' to transactions page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3807]
**Is your feature request related to a problem? Please describe.**
[EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) introduced Typed Transaction Envelope. 

**Describe the solution you'd like**
We should add Typed Transaction Envelope to [the transactions page](https://ethereum.org/en/developers/docs/transactions/)

**Additional context**
- https://eips.ethereum.org/EIPS/eip-2718
- https://blog.mycrypto.com/new-transaction-types-on-ethereum/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MukulKolpe** [comment]
Hey @minimalsm can I work on this issue?

**Comment by minimalsm** [comment]
Of course! Assigned you @MukulKolpe
