### ISSUE TITLE
Fix broken translation ID in developer links

### ISSUE THREAD

**Issue by shadforth** [ethereum/ethereum-org-website#3826]
**Describe the bug**

On the `Explore the documentation` section of the [Ethereum Developer Resources](https://ethereum.org/en/developers/) page, there is an incorrect translation ID being used for the `Intro to Ether` description.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/
2. Scroll down to **Explore the documentation**
3. Under `Intro to Ether`, the description says `page-developers-into-ether-desc`

**Expected behavior**

The description should be linked to the correct ID: `page-developers-intro-ether-desc` which converts to `An introduction to cryptocurrency and Ether`.

**Screenshots**

<img width="871" alt="eth-docs" src="https://user-images.githubusercontent.com/16424236/132160322-1a6d1886-0519-454e-a13d-52ede7c50d2e.png">

**Desktop (please complete the following information):**
Not required

**Smartphone (please complete the following information):**
Not required

**Additional context**
None

**Comment by shadforth** [comment]
I'm happy to fix this as my first docs contribution 😄

**Comment by minimalsm** [comment]
@shadforth Thanks for offering to help on this. I've assigned you 😀
