### ISSUE TITLE
Flesh out proof-of-stake developer doc

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3830]
**Is your feature request related to a problem? Please describe.**

The [proof-of-stake developer doc page](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/) is incomplete and pretty bare considering all of the information and excitement around proof-of-stake. It is also one of the most popular developer docs pages.

**Describe the solution you'd like**
- Expand the current proof-of-stake page with more details and resources

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by jley81** [comment]
Flesh out proof-of-stake developer doc

**Comment by jley81** [comment]
Good

**Comment by jmcook1186** [comment]
Hi, 

I'd like to have a stab at this if it's ok?

Cheers

**Comment by minimalsm** [comment]
@jmcook1186 Awesome! Thanks. I've assigned you 😁

**Comment by minimalsm** [comment]
Feel free to ping me here or [on discord](https://discord.gg/CetY6Y4) if you need anything.

**Comment by Longju000** [comment]
Can I work on here too? If it is open

**Comment by Clashinm** [comment]
yes! omg thank you!

**Comment by Longju000** [comment]
> yes! omg thank you!

Will work on it

**Comment by minimalsm** [comment]
This is covered by #3908
