### ISSUE TITLE
Article about an ERC-20 where the original mint is L2

### ISSUE THREAD

**Issue by qbzzt** [ethereum/ethereum-org-website#3839]
**Tag your tutorial**

#ERC-20 #Layer2 #Bridging

**Tutorial title**

ERC-20: Mint on L2, Bridge to L1

**Tutorial description**

In this tutorial the reader learns how L1<->L2 bridging typically works (L1 as the true source of tokens, locking in the bridge, etc.) and how to write an ERC-20 token that works differently, because it is minted on L2 while the tokens can still be bridged to L1 using the standard bridge, and treated just like any L1 ERC-20 token.

The technique explained in this article is *demonstrated* using Optimistic Ethereum, but the technique is not Optimism specific, it can be applied just as easily to Arbitrum or any other rollup or side chain that uses the same type of ERC-20 bridge.

Table of content:

1. Why do this? The advantages of L2, and the importance of still being able to transact on L1.
2. The standard bridge: How ERC-20 bridges work, with the tokens originally minted on L1, and then locked in the bridge when they are used in L2.
3. What do we need to do to originally mint on L2?
   1. On L2, how we handle minting and burning (including source code that works in Optimistic Ethereum, but that should work elsewhere with a simple change of address)
   2. On L1, how we handle the bridge having to have tokens "locked in" before it even knows about them (including source code that works in Optimistic Ethereum, but that should work elsewhere with a simple change of address)
4. Conclusion

**Publication**

It's not even written yet.

**Skill level**

Intermediate to advanced, requires somewhat advanced Solidity programming.

**Comment by minimalsm** [comment]
> It's not even written yet.

Looking forward to it being written 😬

**Comment by qbzzt** [comment]
WIP: https://github.com/qbzzt/ethereum-org-website/blob/l2-mint/src/content/developers/tutorials/minting-erc20-tokens-on-l2/index.md

**Comment by minimalsm** [comment]
@qbzzt looking forward to it 😀  feel free to ping if you want eyes on it before it is finished or else I'll await your PR 😊

**Comment by qbzzt** [comment]
Blocked right now, waiting for the new Optimism SDK to be released (https://github.com/ethereum-optimism/optimism/discussions/1801) which will make this much easier
