### ISSUE TITLE
Node glossary term repeats a link

### ISSUE THREAD

**Issue by colinsteidtmann** [ethereum/ethereum-org-website#3846]
**Describe the bug**

There's two links to the same website on the Node glossary term: https://ethereum.org/en/glossary/#node

**To Reproduce**

1. Go to https://ethereum.org/en/glossary/#node
2. Click two of the same links titled "Nodes and Clients" that link to https://ethereum.org/en/developers/docs/nodes-and-clients/

**Expected behavior**

There should only be one link. 

**Screenshots**
![Screen Shot 2021-09-07 at 12 00 07 PM](https://user-images.githubusercontent.com/34821973/132397127-bac26316-66ad-4dd8-b6c8-5c01898a8058.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome 
- Version 93.0.4577.63 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

Yes, I'm interested in helping out with a PR.

**Comment by minimalsm** [comment]
> Yes, I'm interested in helping out with a PR.

Thanks, I've assigned you 😬🙏
