### ISSUE TITLE
Add BitKeep Wallet request

### ISSUE THREAD

**Issue by bitkeepos** [ethereum/ethereum-org-website#3863]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**

Yes, we have security tested with PeckShield and Amors team, but is not opened.
As the most popular wallet in China, BitKeep have released almost 3 years, there has been no safety incident.

**When did your wallet go live to users?**

At May, 2018

**Does your wallet have an active development team?**

Yes, always

**Is your wallet open-source?**

Not yet. We are preparing to open part of the core code. 

**Is your wallet globally accessible?**

Yes, any time any where.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial, the private key is controlled by the user and stored in the user’s device, like Metamask.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

1 system architecture
    The standard C/S architecture is adopted in the software. Besides interface interaction and data storage, Client also implements transaction signatures for all currencies locally. Server mainly implements data reading and broadcasting on block chains, as well as other basic data services.
    HTTPS protocol is used for all requests of software. Each request has a unique token authenticating mechanic, which avoids user’s operation is being simulated by robot and greatly enhances security.
    Cloud services are deployed in a distributed way, with 12 nodes around the world. They can accommodate at least one million concurrent traffic and have higher dilatancy.

2 DESM double encryption algorithm
    Double Encryption Storage Mechanism (DESM) is a set of algorithms customized by BitKeep wallet to encrypt and store mnemonics or private keys. BitKeep adopts the combination of encrypting method of sha256+aes256+cloud authentication.
    The algorithm of DESM of BitKeep can be understood as follows: 1) the user sets the transaction password: the client stores it in the cloud after sha256 (password + seed), and returns the new seed based on BitKeep’s account and password; 2) calculates the key needed for symmetric encryption through sha256 (password+account Seed+specific rules); 3) calculates the key needed for symmetric encryption through aes256 (mnemonic code or private key+Key) to encrypt; similarly, users also abide by this principle when entering mnemonic words. This principle has fundamentally solved the problem of security, even if hackers or internal staff can not solve it. Only in one case that is possible to crack the user's cell phone data while knowing the user's transaction password and account password, as well as the encryption rules in the BitKeep cloud. But this possibility is extremely rare.

**Does the wallet have fiat on-ramps?**

Not yet.

**Does the wallet allow users to explore dapps?**

Yes, we have Dapps Store to explore dapps. It is a dapp browser, support WalletConnect and other connect method like Metamask.

**Does the wallet have integrated defi/financial tools?**

Not yet.

**Can a user withdraw to their card?**

Not yet.

**Does the wallet offer limits protection?**

Have a max amount limited.

**Does the wallet allow high-volume purchases?**

Not yet

**Does the wallet have an integrated token swap?**

Yes, we have BitSwap, integrate other swap protocols to facilitate users to quickly complete transactions.

**Is the wallet a multi-signature wallet?**

Not yet.

**Wallet title**

BitKeep

**Wallet description**

BitKeep is a most popular digital currency wallet, which supports all mainstream public chains and Layer 2 such as BTC, ETH, BSC, HECO, TRON, OKExChain, Polkadot, Polygon, EOS, etc. It has provided reliable digital currency asset management service for nearly tens of millions of users around the world; 

**Wallet logo**

https://github.com/bitkeepcom/download/blob/main/bitkeep.svg

**Background colour for brand logo**

#FFFFFF

**URL**

https://bitkeep.com

**Comment by minimalsm** [comment]
Closed by #3850
