### ISSUE TITLE
16 hour freecodecamp tutorial 

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/ethereum-org-website#3868]
Hi team! I'm looking for a place where putting this would go best. It goes over **everything** blockchain & solidity. 

Title: Solidity, Blockchain, and Smart Contract Course - Beginner to Expert Tutorial with Python

https://www.youtube.com/watch?v=M576WGiDBdQ

And it has code examples with every section: 
https://github.com/smartcontractkit/full-blockchain-solidity-course-py

**Tag your tutorial**

- Solidity
- Blockchain
- Metamask
- Remix
- EthBrownie
- IPFS
- Chainlink
- Alchemy
- Infura
- Opensea
- Aave
- DeFi

And way more

**Publication**

YouTube

**Skill level**

Beginner -> Advanced 

**Hosted on Ethereum.org or hosted elsewhere?**

Right now it's on youtube, but where would it be most helpful here?

**Comment by samajammin** [comment]
Awesome, thanks for creating this!

I like the idea of adding video tutorials/playlists like this. I think it's clear that different devs prefer different mediums when it comes to learning through tutorials. Personally I find them much quicker to learn from vs. reading articles. 

Among the laundry list we have of ways to improve our tutorial section (😅) I suspect it'd be helpful for visitors to be able to filter for videos or to filter out videos though. Perhaps a quick hack to start would be adding a "video" tag?

**Comment by PatrickAlphaC** [comment]
Ooooo that's a great idea! I'll see if I can get a PR up!
