### ISSUE TITLE
Ethereum for life

### ISSUE THREAD

**Issue by TravelerJo** [ethereum/ethereum-org-website#3880]
**Is your feature request related to a problem? Please describe.**

Ethereum, and Blockchain in general, is exploding with possibilities. It all makes perfect sense to developers and other long term advocates. However it's a confusing landscape to the uninitiated. A clear and practical use case should be created.

**Describe the solution you'd like**

A guide needs to be created that breaks down the technology into simple manageable bites for the end user. The technology has evolved to the point where it offers multiple benefits for the general public. However those benefits are often lost in memes, crashes and other noisy bunny trails. To broaden usage of the technology, it must be presented in a less technical, more digestible manner.

**Describe alternatives you've considered**

Once developed, the content must be delivered in a variety of ways, geared to specific demographics. I would be happy to help in content development.

**Comment by TravelerJo** [comment]
I feel that though the appeal of crypto in general is exponentially expanding and a whole new group of people are becoming interested, but have no way to navigate the language and the intricacies of Ethereum. Obviously part of growing a successful platform is onboarding new users. The tech may be a shining city on a hill but you need to get users there. There is a lot of hype around some of the newer platforms, not so much eth. I'm just looking at ways to expand the user base for quality products before the novice user gets caught up in some of the flashy, eventually non viable stuff. So is there a page that already looks at education for the end user? Can I help in any way? 
Thanks for the response,
Jo
    On Tuesday, September 21, 2021, 10:23:24 AM PDT, Joshua ***@***.***> wrote:  
 
 


@TravelerJo hey! I'm not sure what exactly you're proposing here. Is it a new page dedicated to this topic? If so, feel free to provide an overview of what you'd like such a page to contain and we can discuss options! Thanks 😀
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by minimalsm** [comment]
> So is there a page that already looks at education for the end user? Can I help in any way? 

The whole site is designed to educate new users and we're constantly working on new ways to engage the community. I think it's probably best to think about this and scope it to an implementable idea and open a new issue for it 😀 definitely open to any ideas to improve ethereum.org but they need to be more specific than this is.
