### ISSUE TITLE
ethereum

### ISSUE THREAD

**Issue by anaimal** [ethereum/ethereum-org-website#3883]
We'll consider [our article policy](https://ethereum.org/en/contributing/adding-articles/) when reviewing the tutorial, so please take a look there first.

**Tutorial title**

**Tutorial description**

**Tag your tutorial**

**Publication**

**Skill level**

**Hosted on Ethereum.org or hosted elsewhere?**

**For tutorials to be hosted on Ethereum.org: Tutorial Content**

**For tutorials hosted elsewhere: URL to tutorial**

**Comment by anaimal** [comment]
a fundamental course on etherenm for developer

**Comment by minimalsm** [comment]
Hey @anaimal did you have a tutorial you wanted to post? Nothing has been attached in the issue template 🤷‍♂️
