### ISSUE TITLE
Warning! Error encountered during contract execution [Reverted] 

### ISSUE THREAD

**Issue by jamiufatai** [ethereum/ethereum-org-website#3886]
Warning! Error encountered during contract execution [Reverted] 
![Screenshot_20210912-171119](https://user-images.githubusercontent.com/35002584/132995428-00917876-16dc-41b2-93cc-69b14a6abf0d.png)

  ERC-20 Token Transfer Error (Unable to locate corresponding Transfer Event Logs), Check with Sender.
Here is my erc20 USDT address,. 0x1329410051fc114d8050b007717fc7575a221c71

Being trying to send out a usdt transaction since January but unable to do so, I have done all possible best also increase the transaction gas fees to high priority, still can't send please help me. God bless you

**Comment by jamiufatai** [comment]
My erc20 USDT address block,

0x1329410051Fc114D8050B007717fC7575a221C71

**Comment by minimalsm** [comment]
Hey @jamiufatai this is the repo for ethereum.org (the website). This isn't a place for general Ethereum support queries. I'd recommend contacting support at your wallet provider and they should be able to help. Thanks!
