### ISSUE TITLE
Add zkSync to dApp Page

### ISSUE THREAD

**Issue by astarinmymind** [ethereum/ethereum-org-website#3890]
zkSync fits all criteria listed in the [listing policy](https://ethereum.org/en/contributing/adding-products/).

zkSync is a zkRollup and is the cheapest yet still fully secure way to transfer tokens on Ethereum. 
It is being developed and maintained actively by Matter Labs.

All information and apps can be found at [zksync.io](url).

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

We take security very seriously. 
Bug Bounty: https://zksync.io/dev/bug-bounty.html 
Security Culture of Matter Labs: https://twitter.com/ChrisBlec/status/1435390952261267459?s=20

**Is your dapp open source?**

Yes.

**Can a user access the dapp without creating an account?**

Yes.

**Are dapp funds non-custodial?**

Yes.

**Do you offer community support?**

Yes via discord and telegram.

**Describe any geographical restrictions on usage of your dapp**

No

**Dapp title**

zkSync

**Dapp description**

zkSync is a zkRollup and is the cheapest yet still fully secure way to transfer tokens on Ethereum. 

**Dapp logo**

Dark and Light versions can be found here: https://drive.google.com/drive/folders/1rLlLkj77E-oa2tc5vjwGgwGxPXoTH-V5 

**Brand color**

Light purple: 8c8dfc
Dark purple: 4e529a

**Comment by julian-st** [comment]
To which category would this belong to? I would suggest Token swaps, but there is also the category Payments which sort of fits to zkSyncs.

**Comment by minimalsm** [comment]
Hey @astarinmymind,

This has been added to our zk-rollups page and will be added to our upcoming layer 2 page. I don't believe this also belongs on the dapps page.

Thanks!
