### ISSUE TITLE
URL Fragment Identifier bug on H4 headings

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3892]
**Describe the bug**
When you visit a developer doc and use the section header ID's in the sidebar or visit the the URL directly (i.e. go to /docs/nodes-and-clients/#openethereum) the heading is cut off at the top of the screen by the nav and subnav.

This problem only happens on H4s.

Example - https://ethereum.org/en/developers/docs/nodes-and-clients/#erigon
![Screenshot 2021-09-13 at 13 17 08](https://user-images.githubusercontent.com/62268199/133103282-9e18bd11-23da-4339-bb02-eb61e10be13b.png)

If we inspect the element and delete the navbar and subnav we will see the heading at the top of the page.

![Screenshot 2021-09-13 at 13 16 50](https://user-images.githubusercontent.com/62268199/133103516-b54aa4bd-9641-4c8d-ad78-d3f17214e66f.png)

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/nodes-and-clients/#erigon'
2. See error

**Expected behavior**
The heading should be visible below the subnav.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave Browser
- Version: 1.28.106

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by calvinsomething** [comment]
I'll take this issue if that's okay.

**Comment by calvinsomething** [comment]
Well, I hope it's not a problem I went ahead and did it. 😛 

It was a very minimal change.
