### ISSUE TITLE
Internal links with URL fragment identifier are rendering as External Links

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3893]
**Describe the bug**
On the Ethereum Govnernace page I noticed there was an internal link that was rendered as an external link. This changes the behaviour to 1. open in a new tab and 2. show an external link arrow (↗)

This seems to be caused by the link having a fragment identifier (#) in the URL (i.e the link being: [/docs/nodes-and-clients/**#clients**](https://ethereum.org/en/developers/docs/nodes-and-clients/#clients))

**To Reproduce**

1. Go to 'https://ethereum.org/en/governance/'
3. Scroll down to 'Get Involved section'
4. See error on 'Contribute to Client Development' link

**Expected behavior**
- Internal links with fragment identifiers should not show the external arrow (↗)
- Internal links should not open in a new tab

**Screenshots**
<img width="307" alt="Screenshot 2021-09-10 at 14 39 55" src="https://user-images.githubusercontent.com/62268199/133105558-7b4d6a1e-6a10-4494-947f-f5f5d5b11a9d.png">

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by il3ven** [comment]
Hey, I'll like work on this. Thanks.

**Comment by minimalsm** [comment]
@il3ven all yours 😀

FYI I just had a quick look at this and realised I was being an idiot.  From the [Link](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Link.js) component you can see that any link that has an absolute path will be rendered as an ExternalLink. 

I checked the markdown and we've not passed the link correctly 😅 (i.e. its an absolute path instead of a relative path)

<img width="885" alt="Screenshot 2021-09-14 at 10 28 29" src="https://user-images.githubusercontent.com/62268199/133232876-3afb0cb9-b400-4800-bda6-67d210d9d191.png">

Assigned you ✌️
