### ISSUE TITLE
New wallet: yiToken

### ISSUE THREAD

**Issue by yiToken-frank** [ethereum/ethereum-org-website#3897]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**
yiToken is continuously tested by our QA team and senior software engineers to ensure it complies with global security standards.

**When did your wallet go live to users?**
April 2021

**Does your wallet have an active development team?**
yes

**Is your wallet open-source?**
no

**Is your wallet globally accessible?**
Yes, there are no geographic limitations nor KYC requirements.

**Is your wallet custodial, non-custodial, or a hardware wallet?**
yiToken is a non-custodial wallet.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
As a non-custodial wallet, yiToken has launched more than one year without security incidents.

**Does the wallet have fiat on-ramps?**
no

**Does the wallet allow users to explore dapps?**
Yes, yiToken developed a dapp browser to allow users to directly experience the dapps.

**Does the wallet have integrated defi/financial tools?**
no

**Can a user withdraw to their card?**
no

**Does the wallet offer limits protection?**
no

**Does the wallet allow high-volume purchases?**
no

**Does the wallet have an integrated token swap?**
no

**Is the wallet a multi-signature wallet?**
no

**Wallet title**
yiToken

**Wallet description**
yiToken is a decentralized multi-chain cryptocurrency and NFT wallet which supports chains such as Bitcoin, Ethereum, Polkadot, Polygon, Solana, BSC, Heco, OKExChain.etc.

**Wallet logo**
![yiToken-logo-rounded-288](https://user-images.githubusercontent.com/82084808/133053170-328e27a0-60a3-4bde-bb37-7053bf921842.png)

**Background colour for brand logo**
![yiToken banner](https://user-images.githubusercontent.com/82084808/133051122-0591e94d-e325-4751-a5f7-3ad5d8d76862.jpeg)

**URL**
https://yitoken.im

**Comment by minimalsm** [comment]
Hey @yiToken-frank, thanks creating this issue.

> When did your wallet go live to users?
September 2020

Can you verify yiToken's launch date? Everything I'm finding is pointing to April of this year. Thanks 👍

**Comment by yiToken-frank** [comment]
> Hey @yiToken-frank, thanks creating this issue.
> 
> > When did your wallet go live to users?
> > September 2020
> 
> Can you verify yiToken's launch date? Everything I'm finding is pointing to April of this year. Thanks 👍

Yeah, yiToken wallet went live to our internal users in September 2020 aming to test it, and in Aprial of this year went to the public users, shoud we update it to April of this year?

**Comment by minimalsm** [comment]
Hey @yitokenfrank. Sorry for the delay on this.

Unfortunately, this wallet does not meet our product listing criteria. As part of our wallet section revamp in our [Q1 roadmap](https://github.com/ethereum/ethereum-org-website/issues/5105), we will be updating the product listing criteria. Please feel free to reapply under the new criteria if you feel yiToken meets the necessary criteria.
