### ISSUE TITLE
Create docs page for EVM opcodes

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3900]
**Is your feature request related to a problem? Please describe.**

Feedback from @MariusVanDerWijden:
> Hey, one thing I'm always looking for is a good resource for opcodes, like their gas usage, how many stack arguments they take, etc. There are some horribly outdated spreadsheets floating around that have some info like that, but it would be really cool to have a canonical version on the website that gets updated with each hf

Looking into this, there's a couple existing resources:
- https://www.ethervm.io/ but it's not open source (I had to email them to update with new London upgrade opcodes)
- https://github.com/wolflo/evm-opcodes but it describes itself "it is not particularly rigorous"

**Describe the solution you'd like**

Given https://github.com/wolflo/evm-opcodes is on the MIT licensed, we could largely copy that README & easily create a documentation page from the markdown.

Perhaps this would live as a subpage of EVM? https://ethereum.org/en/developers/docs/evm/

Given the traffic ethereum.org receives & our existing community of contributors, I suspect this resource would be more reliably maintained.

**Describe alternatives you've considered**

Continue to link out to existing resources.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Hey @wolflo! As the primary maintainer of https://github.com/wolflo/evm-opcodes just reaching out & checking that this is something you'd be comfortable with. We'd be happy to provide attribution to your project. Thanks!

**Comment by wolflo** [comment]
I would be glad to see it being used. I'm happy to help set things up, too. I intend to keep the evm-opcodes updated for hardforks, so having an easy way to pull changes from the repo to the hosted version would make things pretty low overhead.

The statement about the rigor of the reference page is a little out of date. The stack arguments and gas costs should all be correct, and it would be a priority to correct them if any discrepancies are found. But, the language used for defining the gas costs is informal, and the semantics of opcodes is almost entirely avoided.

As a small example, the notes on the `JUMP` opcode say that it takes a destination offset and sets the program counter to that offset. But it makes no mention of other important parts of the semantics here, such as the exceptional halt if the destination offset is not a valid `JUMPDEST` (or even what a valid `JUMPDEST` is).

**Comment by corwintines** [comment]
https://docs.soliditylang.org/en/latest/yul.html#evm-dialect

cross positing from discord
