### ISSUE TITLE
Audit Developer Documentation

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3908]
This issue is to be used for the management of an audit of the [developer documentation](https://ethereum.org/en/developers/docs/) on ethereum.org. 

If you have any ideas or want to discuss things to add to remove from the existing content listed here please leave a comment below or [join the ethereum.org discord](https://discord.gg/CetY6Y4). 

---

**Foundational Topics**

- [x] README [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/4095)
- [x] Intro to Ethereum - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/3907)
- [x] Intro to Ether - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/3929)
- [x] Intro to dapps - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/4065)
- [ ] Web2 vs Web3
- [ ] Accounts
- [ ] Transactions
- [ ] Blocks
- [ ] Ethereum virtual machine (EVM)
- [ ] Gas
- [ ] Nodes and clients
- [ ] Run a node
- [ ] Nodes as a service - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/4050) (awaiting more changes)
- [ ] Networks
- [x] Consensus mechanisms - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/3978)
- [x] Proof of work - [Open PR in progress](https://github.com/ethereum/ethereum-org-website/pull/3999)
- [x] Mining - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/4112)
- [ ] Proof of stake

**Ethereum Stack**- 

- [x] Intro to the stack - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/4116)
- [x] Deploying smart contracts - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/4064)
- [x] Storage - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/4081)
- [x] Python - [Merged PR #1](https://github.com/ethereum/ethereum-org-website/pull/4000), [Merged PR #2](https://github.com/ethereum/ethereum-org-website/pull/4015)

**Advanced**
- [ ] Scaling
- [x] Layer 2 rollups - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/3996)
- [x] Oracles - [Merged PR](https://github.com/ethereum/ethereum-org-website/pull/3998)

**Want to contribute?**

We love contributions from the Ethereum community! Reviewing or adding new content to any of these pages will massively help this task ❤️

**Comment by corwintines** [comment]
Going to close this out in favor of the content audit being done by @jmcook1186 this quarter: com/ethereum/ethereum-org-website/issues/10666
