### ISSUE TITLE
Suggested Revisions to improve UX for becoming a staker

### ISSUE THREAD

**Issue by james-prysm** [ethereum/ethereum-org-website#3921]
#### Background

Hi, I'm James from Prysmatic Labs. We have been doing some research into the UX of becoming a validator and have thought about various changes that could improve this experience. I prepared a doc [here ](https://hackmd.io/@prysmaticlabs/validator-ux) for some background.

#### Major Points

- bring network (mainnet/testnet) selection into the forefront of participation 
    - currently the main page forces users to join the mainnet right away which may bring unintended risk and confusion for new users, there should be more information around testnet participation and the corresponding launchpad urls
    - link users to the correct launchpad based on network selection
    - provide information on how to get initial eth based on network
 
- begin migration away from use of Eth2 term and adjusting page (https://ethereum.org/en/eth2/get-involved/) for participation to reflect
- update "get involved" website with proper prysmatic labs [website ](https://docs.prylabs.network/docs/getting-started)
    - currently still using old website
    
**To Reproduce**

1. Go to Ethereum.org
2. Click on Learn
3. Scroll down to Ethereum 2.0 and click
4. Scroll down to get involved and click
5. scroll down to prysm url and click 
6. takes you to old deprecated website prylabs.com when users should be directed to https://docs.prylabs.network/docs/getting-started/

**Expected behavior**
users should be directed to https://docs.prylabs.network/docs/getting-started/

**Comment by minimalsm** [comment]
Hi James! Thanks for all the thoughts and research you've put into this ❤️. Definitely agree with the sentiment here.

> currently the main page forces users to join the mainnet right away which may bring unintended risk and confusion for new users, there should be more information around testnet participation and the corresponding launchpad URLs

Great point, we could definitely do more on promoting testnet staking.

> begin migration away from use of Eth2 term and adjusting page (https://ethereum.org/en/eth2/get-involved/) for participation to reflect

Agreed. This is something we're thinking hard about right now! - [early work has already begun here](https://github.com/ethereum/ethereum-org-website/issues/3864)). 

> update "get involved" website with proper prysmatic labs website

Done in #3922

cc: @samajammin @wackerow

**Comment by minimalsm** [comment]
@all-contributors please add @james-prysm for ideas

**Comment by samajammin** [comment]
This looks great @james-prysm 😍 - appreciate you doing this research & surfacing this issue. I haven't read through your doc yet in depth but I agree with pretty much everything you're proposing. We can certainly queue this work up but not sure at this point when we can get to it (can circle back on this). We'd welcome any PR or draft of copy changes in the meantime.

Regarding transitioning away for Eth2 terminology, I'd welcome your team's thoughts on this: https://www.notion.so/efdn/The-Great-Eth2-Renaming-7d57a700c6ef492e8d031494c605ae46

**Comment by james-prysm** [comment]
@minimalsm Thanks for the quick turnaround on this.

@samajammin I'm glad you're in alignment with our proposals 😄  If possible please do add it to your queue of work in the mean time, if time/priority permits I'll see what I can draft up. I'll also forward the link you mentioned to my team and see what we can comment on. 

I apologize in advance I'm pretty new to the git workflows. with the issue on the url closed and the remaining items added to a queue of work, should I be the one closing this issue?

**Comment by minimalsm** [comment]
> @minimalsm Thanks for the quick turnaround on this.

Very welcome!

> I apologize in advance I'm pretty new to the git workflows. with the issue on the url closed and the remaining items added to a queue of work, should I be the one closing this issue?

We should keep the issue open for now for context although we'll probably break the remaining two items into two separate issues at some point.

**Comment by samajammin** [comment]
Hey @james-prysm - just circling back to let you know this we've queued up this work as part of our Q4 roadmap (#4215). Stay tuned!

In the meantime feel free to add more ideas here 😄

**Comment by james-prysm** [comment]
saw the bot mark this as stale. I think @wackerow has been working on this but not sure if any direction has changed.

**Comment by corwintines** [comment]
@wackerow do you know if this is ready to be closed with the changes over the last few years to launchpad, staking and node content?

**Comment by wackerow** [comment]
> bring network (mainnet/testnet) selection into the forefront of participation

The `staking-launchpad` now has a banner announcing that a user is on the testnet page, and ethereum.org/staking page now directs users to the Goerli launchpad by default. The `/staking/solo` page also emphasizes the testnet version by default:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/54227730/226602058-65301820-8ac2-4f96-ac0d-5e94c761afc7.png">

---

> link users to the correct launchpad based on network selection

See above

---

> provide information on how to get initial eth based on network

This does not appear to be solved

---

> begin migration away from use of Eth2 term and adjusting page (https://ethereum.org/en/eth2/get-involved/) for participation to reflect

Eth2 terminology has been deprecated

---

> update "get involved" website with proper prysmatic labs [website](https://docs.prylabs.network/docs/getting-started)

This link has been updated

---

@james-prysm Please feel free to re-open if you disagree, but going to close this for now. The only item I see that doesn't seem to have been addressed is providing better faucet information. If we want to try and pursue improving that we could open a dedicated issue to track this separately.
