### ISSUE TITLE
NFT

### ISSUE THREAD

**Issue by spicymix** [ethereum/ethereum-org-website#3930]
Hi

I'm an independent artist and I'm requesting help to put CDs, DVDs, Books, Ebooks, Videobooks, Arts, Drawings .. and Collectibles .. for sale through NFT (non-fungible token/non-fungible token) like this how the band Kings of Leon put up for sale a copy of their latest album, a work of art and a gold record, plus the band's recording errors, last March, in the Ethereum cryptocurrency.

Can you help me?

Thanks

**Comment by minimalsm** [comment]
Hey @spicymix this is the repo for ethereum.org the website. Seeing as this isn't related to the website I'm going to close this issue but I'd recommend checking out this page to begin your research into NFTs: https://ethereum.org/en/nft/

Thanks and good luck :)
