### ISSUE TITLE
Dudes gas fees! If you are burning it anyway just make it really cheap.

### ISSUE THREAD

**Issue by bsoldre** [ethereum/ethereum-org-website#3931]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MrBrain295** [comment]
@bsoldre this isn’t related to the Ethereum website.
