### ISSUE TITLE
Consistent Styling/Adding a DAO

### ISSUE THREAD

**Issue by TrevorFrench** [ethereum/ethereum-org-website#3932]
*Two issues here, so let me know if I need to break them out into separate requests.

1. Two of the explanations on this page aren't italic while the rest are. I'd like to fix that.
2. I'd like to append Developer DAO to the list (https://twitter.com/developer_dao).

https://ethereum.org/en/community/#decentralized-autonomous-organizations-daos/community/#decentralized-autonomous-organizations-daos

**Comment by TrevorFrench** [comment]
Comment

**Comment by minimalsm** [comment]
Hey @TrevorFrench! Thanks for spotting the bug and agreed on adding DeveloperDAO.

If there is anything else you think should be added definitely happy to start a discussion around this too, the page is kinda bare ATM.

I've assigned you to this (I think you are volunteering? Let me know if I've got this wrong 😅)

**Comment by TrevorFrench** [comment]
@minimalsm I was volunteering! Sorry that wasn't super clear.

I like the idea @samajammin mentioned in #3746 of pointing social links to this page and building out a more comprehensive directory of social channels but I think that's already scoped out in that issue (happy to work on that one too though).
