### ISSUE TITLE
Health Care

### ISSUE THREAD

**Issue by Daw9000** [ethereum/ethereum-org-website#3936]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MrBrain295** [comment]
?

**Comment by minimalsm** [comment]
@Daw9000 you've accidentally left this issue blank :) did you want to raise a bug or discuss a feature?

**Comment by Daw9000** [comment]
Sorry my error, thanks for closing
