### ISSUE TITLE
Add 1inch wallet

### ISSUE THREAD

**Issue by n0mer** [ethereum/ethereum-org-website#3939]
**URL**

https://1inch.io

**Comment by minimalsm** [comment]
Hey @n0mer. Could fill out [this issue template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=Type%3A+Feature%2C+Type%3A+Content&template=suggest_wallet.md&title=) for adding a new wallet so the team has all the necessary information to review this submission 😬👍 thanks

**Comment by minimalsm** [comment]
Closing this out. Please fill out the issue template as requested if you'd like to see this added 🙏
