### ISSUE TITLE
Add info on smart contract size limit

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3943]
**Is your feature request related to a problem? Please describe.**

Currently we don't provide any info on this limitation.

**Describe the solution you'd like**

I think we should mention this contract size limitation (24KB) somewhere in our docs on smart contracts:
https://ethereum.org/en/developers/docs/smart-contracts/

We could also list approaches to getting around this limitation, e.g. by using proxy contracts or the diamond pattern:
https://dev.to/mudgen/ethereum-s-maximum-contract-size-limit-is-solved-with-the-diamond-standard-2189

**Describe alternatives you've considered**

Not sure where the best place is to put it... could make sense in a few places:
- https://ethereum.org/en/developers/docs/smart-contracts/#limitations
- https://ethereum.org/en/developers/docs/smart-contracts/anatomy/
- https://ethereum.org/en/developers/docs/smart-contracts/compiling/
- https://ethereum.org/en/developers/docs/smart-contracts/deploying/
- https://ethereum.org/en/developers/docs/smart-contracts/libraries/

**Additional context**

More on the diamond pattern: https://eips.ethereum.org/EIPS/eip-2535

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
@mudgen let us know if you have thoughts on this 😄

**Comment by MrBrain295** [comment]
@samajammin I could work on this.

**Comment by mudgen** [comment]
> @mudgen let us know if you have thoughts on this smile

I think it is a great idea to mention EIP-2535 anywhere the diamond pattern could help people.

**Comment by minimalsm** [comment]
@MrBrain295 thanks for offering to help! I've assigned you 😬 you know the drill, any questions ask here or ping me.

**Comment by minimalsm** [comment]
Partially solved in #3957 but leaving this open for now as I still think it's a good idea to add more information about using proxy contracts.

**Comment by MrBrain295** [comment]
I could take another blow at this.

**Comment by ossayed** [comment]
Hi there, I'd love to work on this issue! What information would you specifically like to be added more in depth beyond the change made perviously?

**Comment by corwintines** [comment]
I think we can close this out from the previous PR from @MrBrain295
