### ISSUE TITLE
Add Tutorial: Create, test and interact with a smart contract

### ISSUE THREAD

**Issue by rodrigoherrerai** [ethereum/ethereum-org-website#3947]
We'll consider [our article policy](https://ethereum.org/en/contributing/adding-articles/) when reviewing the tutorial, so please take a look there first.

**Tutorial title**

Create, Test, Deploy and Interact with a Smart Contract from A to Z
**Tutorial description**

By doing this tutorial, you will know how to create a developer environment in Hardhat, how to test your smart contract, deploy it and interact with it through react.
**Tag your tutorial**

React, Smart Contract, Hardhat, Ethers.js
**Publication**

https://medium.com/@rodrigoherrerai/create-test-deploy-and-interact-with-a-smart-contract-from-a-to-z-e494f40ae154
**Skill level**

beginner
**Hosted on Ethereum.org or hosted elsewhere?**

Link to Medium
**For tutorials to be hosted on Ethereum.org: Tutorial Content**

**For tutorials hosted elsewhere: URL to tutorial**

https://medium.com/@rodrigoherrerai/create-test-deploy-and-interact-with-a-smart-contract-from-a-to-z-e494f40ae154

**Comment by minimalsm** [comment]
Thanks @rodrigoherrerai, I'll check this out soon! :)

**Comment by rodrigoherrerai** [comment]
Hi! did you have a chance to check it ?
