### ISSUE TITLE
Need reset my public

### ISSUE THREAD

**Issue by Blockbath-Staking** [ethereum/ethereum-org-website#3948]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @Blockbath-Staking, you've accidentally left this issue blank. Is there a bug or issue you'd like to report :)?
