### ISSUE TITLE
Fix broken links in whitepaper content

### ISSUE THREAD

**Issue by andyGallagher** [ethereum/ethereum-org-website#3949]
**Describe the bug**

There are a few broken/deprecated links in the whitepaper, specifically the links for [UTXO lack of state](https://github.com/ethereum/ethereum-org-website/blame/dev/src/content/whitepaper/index.md#L444) and the [Patricia tree wiki](https://github.com/ethereum/ethereum-org-website/blame/dev/src/content/whitepaper/index.md#L529).

**To Reproduce**

1. Click link describing UTXO [lack of state](https://bitcoin.org/en/glossary/unspent-transaction-output), will direct to a 404 page.
2. Click [Patricia tree documentation](https://github.com/ethereum/wiki/wiki/%5BEnglish%5D-Patricia-Tree), will direct to legacy wiki.

**Expected behavior**

1. Link describing UTXO being spent/unspent should direct to a page about transaction, not a 404 page. 🙃
2. Link to Patricia tree docs should direct past the legacy github wiki straight to the eth.wiki page.

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version: 93.0.4577.63

**Want to contribute?**

I'd love to fix up these links, let me know.
I believe the UTXO link should href [here](https://developer.bitcoin.org/devguide/transactions.html) and the patricia tree should just direct to [the non-legacy page](https://eth.wiki/en/fundamentals/patricia-tree).

**Comment by wackerow** [comment]
@andyGallagher Thanks for posting this issue, and the help is welcomed! Just assigned you =)
