### ISSUE TITLE
Link to Pantheon Gitter will be broken as of 11/14 - Migration to Hyperledger Besu

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#395]
**Describe the bug**
Soon to be broken link, gitter shutting down

**To Reproduce**
1. Go to [Enterprise Developer Community](https://ethereum.org/enterprise/#enterprise-developer-community)
2. Click link to Pantheon

**Expected behavior**
It should take you to the Pantheon Gitter. This chat is closing down 11/14 and moved to the [Hyperledger Rocketchat](https://chat.hyperledger.org), Besu Channel. Link will be deprecated by existing Hyperledger Besu Rocketchat

**Screenshots**

![image](https://user-images.githubusercontent.com/27454964/68428243-c40bce00-0179-11ea-8949-fd8ed3e28fe9.png)

**Comment by samajammin** [comment]
Thanks for the heads up!
