### ISSUE TITLE
Is it a 99.95% or 99.98% energy reduction when switiching from Eth1 to Eth2?

### ISSUE THREAD

**Issue by colinsteidtmann** [ethereum/ethereum-org-website#3950]
**Describe the bug**

**To Reproduce**

1. Go to https://ethereum.org/en/nft/#environmental-impact-nfts
2. Then go to https://ethereum.org/en/nft/#fn-1
4. See different energy reduction numbers (99.95 and 99.98%)

**Expected behavior**

Energy reduction numbers should be consistent

**Screenshots**
![99.98%](https://user-images.githubusercontent.com/34821973/133952369-aed8fd98-383b-46a8-b92e-2be91d45e2b2.png)

![99.95%](https://user-images.githubusercontent.com/34821973/133952374-0b1440e0-6422-433d-bd6e-81b5c71718d0.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 93.0.4577.82 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Want to contribute?**
Of course. I can fix this once someone confirms which number is correct. 

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @colinsteidtmann nice spot.

We're going with 99.95% to bring it in line with Carl Beekhuizen's [blog on energy usage ](https://blog.ethereum.org/2021/05/18/country-power-no-more/).

[This PR](https://github.com/ethereum/ethereum-org-website/pull/3777) made the change from 99.98% to 99.95% but we must have missed one instance 🤪

Would love a PR on it if you're still down! Assigned you.

**Comment by MrBrain295** [comment]
I made a pr

**Comment by samajammin** [comment]
Solved in #4032 - thanks @colinsteidtmann & @MrBrain295!

**Comment by samajammin** [comment]
@all-contributors please add @colinsteidtmann for bug reports.
