### ISSUE TITLE
Docs / Transactions / improve gas fee accounting example

### ISSUE THREAD

**Issue by metalocal** [ethereum/ethereum-org-website#3951]
The gas fee example on the _Transactions_ docs page is not accurate.

Example Scenario:  (190 + 10) * 21000 = 4,200,000 gwei

Current explanation of gas components does not appear correct:

> The base fee will be burned **-0.003735 ETH**
> Miner keeps the tip **+0.000197 ETH**

It should use the following numbers:

> The base fee will be burned **-0.00399 ETH**
> Miner keeps the tip **+0.000210 ETH**

**Comment by metalocal** [comment]
PR #3952 proposes a change.

**Comment by minimalsm** [comment]
Closed by #3952, thanks!
