### ISSUE TITLE
Docs / Gas / inconsistent rounding of base fee values

### ISSUE THREAD

**Issue by metalocal** [ethereum/ethereum-org-website#3964]
Some of the numbers in the table that demonstrates an increasing base fee of 12.5% are not rounded with the usual convention.

It's a minor detail, but rounding to the nearest 0.1 ETH is a subtle bit of polish for the example.

**Comment by metalocal** [comment]
#3965 proposes a small change

**Comment by minimalsm** [comment]
Closed by #3965
