### ISSUE TITLE
Add Loopring Wallet to wallet section

### ISSUE THREAD

**Issue by adam-bro** [ethereum/ethereum-org-website#3970]
**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**
1. Check that each permission is required for App functions and does not violate the privacy policies of the App store and Google play.
2. For wallet mnemonics, transaction passwords, etc., stored in the Android application KeyStore, and iOS application KeyChain.
3. The interface uses the https protocol, using API Key authentication mechanism, data signature, adding time stamp, current limiting mechanism, blacklist mechanism to ensure data security, mainly through Charles tools to assist in checking.
4. Use third-party security testing platforms, such as Tencent Mobile Security Lab (https://m.qq.com/security_lab/scans_online.jsp).

**When did your wallet go live to users?**
Nov 25, 2020.

**Does your wallet have an active development team?**
Yes, we have nine people working on the wallet, 7 engineers and 2 designers.

**Is your wallet open-source?**
No, it is closed sourced.

**Is your wallet globally accessible?**
Our wallet is globally accessible and available on both iOS and Android. There are no geographic limitations or KYC requirements to use the wallet. 

**Is your wallet custodial, non-custodial, or a hardware wallet?**
The Loopring Wallet is a non-custodial mobile smart contract wallet.

There is no private key. Loopring Smart Wallet is a smart contract wallet and uses social recovery and guardians which replaces seed phrases. If our company were to disappear, users can always just interact with the smart wallet contract directly. There's no direct dependencies to Loopring. The wallet is 100% non-custodial.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
The Loopring Wallet smart contracts work in terms of guardians, locks, limits, and security in general. The Loopring Wallet is not a 'normal' Ethereum address (not an EOA), it is a smart contract. As such, it is much more flexible, and it has rules and logic baked in, which makes it much more user-friendly, secure, and extensible in the future. Security is at the core of Loopring Wallet design decisions. You can read more here - https://loopring.io/#/legal/walletdesign

**Does the wallet have fiat on-ramps?**
We do not have fiat on-ramps in the wallet yet. We are expected to go live with this feature in Q1 2022.

**Does the wallet allow users to explore dapps?**
Yes there's a dapp browser page on the wallet. Users are able to interact with UniSwap, SushiSwap, Aave, Balancer, PoolTogether, Compound and more. 

**Does the wallet have integrated defi/financial tools?**
Yes Smart Wallet users can do gas-free layer-2 swaps, trades, transfers and provide liquidity via AMM.

Soon users will be able to lend and borrow from L1 dapps directly on L2 with our upcoming Ethport feature. 

**Can a user withdraw to their card?**
No

**Does the wallet offer limits protection?**
Yes, users are able to add a daily limit quota. 

**Does the wallet allow high-volume purchases?**
Yes.

**Does the wallet have an integrated token swap?**
Yes, our Layer-2 AMM is integrated into the Smart Wallet allowing users to token swap, gas-free

**Is the wallet a multi-signature wallet?**
The Smart Wallet is an advanced multisig, where you can choose people, institutions, and hardware that you trust as the guardians of your wallets but the signer is just you. Users need multiple signers for bigger actions, like recovering a wallet, or sending a tx that is above a previous limit you set.

**Wallet title**
Loopring Wallet

**Wallet description**
The first ever Ethereum smart contract wallet with zkRollup-based trading, transfers, and AMM. Gas-free, secure, and simple. DEXes, DeFi, and payments powered by Loopring Layer-2 allows you to avoid gas fees and network congestion, and deploy assets to earn and invest.

**Wallet logo**
![1024](https://user-images.githubusercontent.com/84410897/134215180-b4938237-8d4c-4813-a1b5-577e063c30fd.png)

**Background colour for brand logo**
Darkest blue background: 1E44FF, Dark Blue Background: 2451FF, Darkish blue background: 2C61FF, Blue background: 316AFF, lightish blue background: 3570FF, light blue background: 3B7FFF, lightest blue background: 4897FF

**URL**
https://loopring.io

**Comment by minimalsm** [comment]
@adam-bro this looks good to me :-) will queue it up to get added to the site.

**Comment by adam-bro** [comment]
Thank you @minimalsm !

**Comment by adam-bro** [comment]
@minimalsm do you know when the Loopring Wallet will be added to the wallet section?

**Comment by adam-bro** [comment]
Hi minimalsm can you please tick off 'buy ETH with card'

Users can now onramp from FIAT to ETH straight to Loopring L2 without having to pay for gas-fees. This has been the easiest and cheapest way for our users to onboard funds onto Loopring. RAMP and Banxa are our FIAT providers

![1IMG_5663](https://user-images.githubusercontent.com/84410897/151210021-2f67ea06-6122-4bab-b4f3-3a376ded84d8.jpeg)

Thanks minimalsm!

**Comment by adam-bro** [comment]
HI @minimalsm can you please tick off 'Connect to dapps' and 'Staking'

Connect to dapps 
 Users can connect to dapps on Ethereum and on Loopring using this mobile wallet. See below, connecting to Uniswap

![1IMG_8244](https://user-images.githubusercontent.com/84410897/210456462-72b6c9cc-7dcb-4db7-a462-c64aeb562eeb.jpeg)
![1IMG_8245](https://user-images.githubusercontent.com/84410897/210456474-579e4144-eab5-41c7-8cbb-bfcd1c1d19ad.jpeg)


Staking
Users can stake Ethereum via Lido or Rocket Pool

![1IMG_8242](https://user-images.githubusercontent.com/84410897/210456543-1eed857b-af87-4d01-b935-ba021f01ac95.jpeg)
![1IMG_8243](https://user-images.githubusercontent.com/84410897/210456545-9f9c99d9-6dc9-4e44-94b0-9f5966a88360.jpeg)

**Comment by f3n4nd0m3** [comment]
https://mail.ru/    tieda de aplicasiones heter
