### ISSUE TITLE
Add deprecated EF-supported projects / software section

### ISSUE THREAD

**Issue by bleesherman** [ethereum/ethereum-org-website#3971]
**Is your feature request related to a problem? Please describe.**

There are several projects and resources that are no longer active or maintained, and it can be unclear to users and new people arriving that this is the case. Once projects are spun off or graduated from the EF, there is no approach for how to consistently communicate the situation to the present and future users.

**Describe the solution you'd like**

The idea is for Ethereum software/projects with subdomains on ethereum.org that are now deprecated, so it could be seen almost like a History of Ethereum Software and other types of resources documentation page. We can use ethereum.org to create an "official" landing page for these with an explanation, links to GitHub repos, and alternative options.

An example of this is the "Studio" deprecation page, this is redirected from https://studio.ethereum.org.
The code of the page is here: https://github.com/ethereum/ethereum-org-website/blob/master/src/pages/studio.js  

**Ideas For Where It Will be Situated**

- Put it in a standalone section, not linked to from the navigation, and for Google bot consumption only
- Create a special page listing all deprecated software, documentation, and information sources. 
- Create a "History of Ethereum Software" page, perhaps linked to from "History of Ethereum". This would feature major software launches as well as deprecations.

**Describe alternatives you've considered**

Create an alternative resource, perhaps a standalone website

**Additional context**

Some examples:
Clearly marked as deprecated:

- Parity
https://github.com/openethereum/parity-ethereum

- Trinity
Repo:
https://github.com/ethereum/trinity
Website (no announcement of deprecation)
https://trinity.ethereum.org/ 
Snake Charmers home page still displays Trinity as active
https://python.ethereum.org/

- Mist and Meteor App Wallet 
https://mist.ethereum.org/
https://wallet.ethereum.org/

- Grid
https://grid.ethereum.org/

- Mix
https://github.com/ethereum/mix 

- "Ethereum Forum"
Marked as an archived web page using Archive-It
https://forum.ethereum.org 

- Dapps and Services
Cover Protocol, SparkPool, The DAO 

Not so clearly deprecated:

- Gitter channels and other comms resources (often there are deprecation messages)
ethereum/AllCoreDevs
ethereum/devp2p
ethereum/ethereumjs
ethereum/go-ethereum
(and many others)

- Wikis
eth.wiki, legacy ethereum/wiki, etc.

We've been working in the following fork of this repo: https://github.com/bleesherman/ethereum-org-website/tree/deprecated-experiment 

**Want to contribute?**

We are currently working on what it should look like, and I'll link to that soon. :)

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by jpitts** [comment]
Proposing a standard set of fields for each entry:

- Date of Deprecation
- Summary of software / service (when it was active)
- Link to archive (archived GH repo, Internet Archive) 
- History / major events
- List of a few alternatives

**Comment by samajammin** [comment]
Awesome, this is looking great. I'd say go ahead & open a PR (even if just as a "draft"), so folks can review & add comments. 

> Are we on the right track with this? Is the scope too wide here?

I like this direction overall. I think this will be super helpful e.g. for people searching "mist" in our site search, which happens quite frequently.

I think you folks have the right idea on implementation here! Using a markdown file for this page makes the most sense to me 👍 https://github.com/bleesherman/ethereum-org-website/blob/deprecated-experiment/src/content/deprecated-software/index.md

> Is this issue labeled "blocked" in order to prevent others from working on it, or is there some other reason?

I _think_ so but @minimalsm should confirm.

> Regarding images: we did an experiment for Parity's SVG but this is hosted elsewhere. Is there a favored approach, or documentation about how to reference and host images?

Good question. Please add the images directly to the codebase. You can see the whitepaper as an example of how to do this in markdown files: https://github.com/ethereum/ethereum-org-website/tree/dev/src/content/whitepaper

@minimalsm I'm noticing we don't have any instructions around this. We explain [how to add images in React components](https://github.com/ethereum/ethereum-org-website#image-loading-and-api-calls-using-graphql) but not for markdown. Could you please add a quick explainer to the README?

> Regarding translation: should we worry about translation at this point? We are not sure if we are developing in the right way to make translation convenient later on.

Nope, what you have (just the English markdown file) is great - we can handle the translations afterwards.

**Comment by minimalsm** [comment]
Closed by #4256
