### ISSUE TITLE
DeFi Pulse TVL endpoint fetching inconsistently

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#3972]
**Describe the bug**
On the homepage, Total Value Locked in defi is pulled from DeFi Pulse, and recently have noticed sporadic periods where this data is failing to load. This issue was previously brought up in #3533 and was closed after it spontaneously resolved. 

**To Reproduce**

1. Go to https://ethereum.org
2. Scroll down to metrics (Price/TVL/Nodes/Txs) near the bottom
3. Occasionally will see an error here (see below screenshots)

Getting console error `Task timed out after 10.01 seconds`

**Expected behavior**
Would expect our API endpoint to be consistent at fetching the desired data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/134230784-93e46d98-b4d8-4edc-afd3-00523b54ef0e.png)
![image](https://user-images.githubusercontent.com/54227730/134231820-289f1833-9543-4aff-aa66-21cc4dee6d7c.png)

**Additional context**
We may need to reach out to the DeFi Pulse team to investigate this endpoint, and confirm our API key isn't being rate limited.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by bford21** [comment]
Hey friends, Brian from DeFi Pulse here. We've upgraded our infrastructure and response times from our endpoints are now consistently in the few hundred millisecond range. Appreciate your patience and for calling this out!

**Comment by ivbhatt** [comment]
This issue still persists. As shown:

![image](https://user-images.githubusercontent.com/20361038/155227842-4378bf72-e566-4519-9f84-5918b4177574.png)

It appears that we are hitting the correct API as per DeFi Pulse's own documentation.
Link to our code: https://github.com/ethereum/ethereum-org-website/blob/dev/src/lambda/defipulse.js#:~:text=%60https%3A//data%2Dapi.defipulse.com/api/v1/defipulse/api/GetHistory%3Fapi%2Dkey%3D%24%7Bprocess.env.DEFI_PULSE_API_KEY%7D%26period%3D3m%26length%3D1%60 

Link to DeFi Pulse documentation:  https://docs.defipulse.com/api-docs-by-provider/defi-pulse-data#:~:text=https%3A//data%2Dapi,Copied!

I tried getting my own key and hitting the API using postman as per documentation but I too get a time-out error. 
This indicates there's a problem on your end @bford21 

Here's the postman screenshot of API req-response:
![Screen Shot 2022-02-22 at 5 13 21 PM](https://user-images.githubusercontent.com/20361038/155228648-90384888-a51a-4717-9371-dea8cdbca683.png)
