### ISSUE TITLE
Old translated dapps pages with missing intl strings

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#3976]
**Describe the bug**
The old dapps page (languages on v1/v1.1) embeds a component, `<RandomAppList />` which uses some translation strings that are not available for the given language. This results in rendering the kebab-cased intl lookup key. 

**To Reproduce**

1. Go to https://ethereum.org/bn/dapps/
1. See kebab-cases keys instead of translated (or english) copy.

**Expected behavior**
Should not show the lookup key. If the strings are not available, should fall back to english. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/134283341-ca62c6b1-7626-481b-b7e2-6bfffbee5caa.png)

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by julian-st** [comment]
Can I work on this?

**Comment by minimalsm** [comment]
Closd by #4124
