### ISSUE TITLE
Translation banner on pages that are not being translated

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3980]
**Describe the bug**

We are currently showing a 'help translate this page' banner on pages that are not queued up for translation. This could be discouraging to translators to suggest a translation is incomplete but not allow them to translate it.

**To Reproduce**

1. Go to 'https://ethereum.org/ro/community/'
1. See error

**Expected behavior**
1. We could remove the "Help us translate this content." section of the message

or 

2. We could explain this page is not being translated for x reasons

**Screenshots**
Romanian community page:

<img width="1998" alt="Screenshot 2021-09-22 at 13 29 17" src="https://user-images.githubusercontent.com/62268199/134344239-e240c850-6c1d-4d42-96f4-19d0c35e1432.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
I think we _should_ show the banner on community pages given that we plan to translate that page.

I agree it's a bug if we're showing the banner on pages we don't plan to translate (e.g. privacy policy, cookie policy, contributing pages).

**Comment by minimalsm** [comment]
Agree @samajammin - I believe we should show a banner but don't think the current banner is the right one as it's a call to action to translate a page that is currently not translateable.

<img width="642" alt="Screenshot 2021-09-22 at 21 13 24" src="https://user-images.githubusercontent.com/62268199/134415109-5fa22a7f-b2f4-4aa9-888d-b69ba60435e6.png">

So if languages the user flow is potentially pretty poor:

<img width="1285" alt="translation-userflow" src="https://user-images.githubusercontent.com/62268199/134417842-0baf35bd-8c07-4b2f-9054-2b4a305fec93.png">
 
As for the foreseeable future, we'll be adding new pages that we will want to translate but that are not yet added to CrowdIn perhaps we could have an additional banner to cover this? i.e:

1. Translated pages (no banner)
2. Translated but outdated (outdated banner)
3. Not translated and on CrowdIn (translate CTA banner)
4. Not translated and not on CrowdIn (additional banner)

It's a very small UX improvement so if this sounds like a ton of work to maintain or implement we can shut it down.

**Comment by corwintines** [comment]
I believe this has been addressed at this point. @minimalsm if there is still an issue here do you mind reviving this issue? Going to close this out.
