### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zoeyteche** [ethereum/ethereum-org-website#3997]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

 zoeyw637@gmail.com

**Is your dapp open source?**

 yes

**Can a user access the dapp without creating an account?**

 must request access 

**Are dapp funds non-custodial?**

 no

**Do you offer community support?**

 zoey077

**Describe any geographical restrictions on usage of your dapp**

 yes

**Dapp title**

 Zoeytech 

**Dapp description**

 blockchain/ token miner 

**Dapp logo**

 z$

**Brand color**

 purple

**Comment by minimalsm** [comment]
Hey @zoeyteche, is this a dapp that is already developed and live? If so could you provide a link and brief description? Thanks 😀
