### ISSUE TITLE
Non-english pages link to English pages in footer navigation

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4001]
**Describe the bug**

When browsing on a non-English version of ethereum.org, clicking on any of the legal pages (terms of use, cookie policy, privacy policy) will take you to the /en/ path and therefore onto the English version of the site. 

This is a poor user experience as it makes users use the browser's back button to return to their desired language.

**To Reproduce**

1. Go to 'www.ethereum.org/sl'
2. Click on 'Cookie Policy'
3. See error

**Expected behavior**

- The user should remain on their current language path
- The navigation components should remain in the user selected language 
- The user should see a banner, in their selected language, explaining that the page is deliberately not being translated.

**Screenshots**

![translationGif](https://user-images.githubusercontent.com/62268199/134581511-763bb776-93a5-4ab0-b634-ca79be638584.gif)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by abritpal** [comment]
Hi!, I would like to work on this issue.

**Comment by minimalsm** [comment]
Hey @abritpal. 

I've assigned you. FYI these pages *should* be in English but they should have the correct language path.

This is being caused by the logic here: https://github.com/ethereum/ethereum-org-website/blob/93845b1c9a7513fc0f39a85e7f159f08afad130d/gatsby-node.js#L138

**Comment by abritpal** [comment]
Thanks for giving me the opportunity to work on this.

**Comment by abritpal** [comment]
For some time I have been trying to work on this but I am really confused.
Even if I comment all the code down there, there is no change. Changing any variables or anything won't change anything. First of all how is Gatsby able to understand, not to direct this to other language URL. Second, how is 
`createPage` working on a whole since pages like etheruem community behave the same way we wan't all these legal pages to work. So where is the it behaving differently for different pages even if I comment or remove the following code.
`
const isLegal =
      slug.includes(/cookie-policy/) ||
      slug.includes(/privacy-policy/) ||
      slug.includes(/terms-of-use/) ||
      slug.includes(/contributing/)
`
(back ticks in the above declation are removed to display as code here)
`
    const language = node.frontmatter.lang
    const relativePath = node.fields.relativePath

    // If markdown file is English, check for corresponding file in each language.
    // e.g. English file: "src/content/community/index.md"
    // e.g. corresponding German file: "src/content/translations/de/community/index.md"
    if (language === defaultLanguage && !isLegal) {
      for (const lang of supportedLanguages) {
        const splitPath = relativePath.split("/")
        splitPath.splice(2, 0, `translations/${lang}`)
        const langPath = splitPath.join("/")
        // If corresponding file doesn't exist, create a page for it.
        if (!fs.existsSync(langPath)) {
          const splitSlug = slug.split("/")
          splitSlug.splice(1, 1, lang)
          const langSlug = splitSlug.join("/")
          createPage({
            path: langSlug,
            component: path.resolve(`./src/templates/${template}.js`),
            context: {
              slug: langSlug,
              isOutdated: false,
              isContentEnglish: true,
              relativePath: relativePath, // Use English path for template MDX query
              // Create `intl` object so `gatsby-plugin-intl` will skip
              // generating language variations for this page
              intl: {
                language: lang,
                defaultLanguage,
                languages: supportedLanguages,
                messages: getMessages("./src/intl/", lang),
                routed: true,
                originalPath: slug.substr(3),
                redirect: false,
              },
            },
          })
        }
      }
    }
` 
![image](https://user-images.githubusercontent.com/26769996/137551131-3218c1ed-cd5e-49d2-8ba5-b3480cbf8e59.png)
