### ISSUE TITLE
Add EthPortland to community page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4002]
**Describe the solution you'd like**

We should add EthPortland to our [upcoming events section](https://ethereum.org/en/community/#upcoming-events) on the community page

https://2021.ethportland.com/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MrBrain295** [comment]
I could work on this.

**Comment by minimalsm** [comment]
@MrBrain295 thanks! Assigned you 😀 Any help needed just give me a ping on discord.
