### ISSUE TITLE
Keyboard shortcut to jump focus to search input

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#4027]
**Is your feature request related to a problem? Please describe.**
Functionality to use the `/` key to jump focus to the search bar on desktop.

**Describe the solution you'd like**
Add a listener for keystroke `/` (or even additionally `ctrl/cmd+K` as used in Discord or Telegram) to automatically move cursor focus to the search bar. An indicator on the search bar with the `/` character to inform user of option. 
![image](https://user-images.githubusercontent.com/54227730/134756972-73095347-463e-42fd-be57-47f0d169c82b.png)

**Describe alternatives you've considered**
Keep requiring the mouse or tabbing through with keyboard 👎

**Additional context**
A few examples of sites that utilize this behavior are https://github.com, https://coingecko.com or https://coinmarketcap.com. Was thinking of keeping this simple and simply place the cursor in this input, but not necessarily building out a new dropdown like used on these sites, at lease for this issue. 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SNikhill** [comment]
@wackerow 

Sir, May I please tackle this issue?

**Comment by SNikhill** [comment]
Linked PR: #4031

**Comment by corwintines** [comment]
Closing as we have merged the PR
