### ISSUE TITLE
English fallback content within `ar` and `fa` rendering right-to-left

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#4028]
**Describe the bug**
For languages that use a right-to-left flow, some pages remain in English resulting in right-aligned English content with buggy bullet points and styling as a result.

**To Reproduce**

1. Go to https://ethereum.org/ar/about/
2. Notice English content within the arabic languages URL path, causing issues with how bullets and link decorators lay out.

**Expected behavior**
Pages using Arabic or Farsi URL paths that are falling back to English content should be conditionally rendered for **left-to-right** reading.

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/134757543-9db22c19-ec88-4532-87d6-b5cc618a3aac.png)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SNikhill** [comment]
@wackerow 

Sir, may I please have this one?

**Comment by minimalsm** [comment]
@wackerow Pretty sure code blocks should always be ltr too?

**Comment by wackerow** [comment]
Closed with #4035, thanks @SNikhill!
