### ISSUE TITLE
Add Translation Program mission and vision section

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#4036]
**Is your feature request related to a problem? Please describe.**

We should add a section to the website to explain the Translation Program's mission and vision.

**Describe the solution you'd like**

Add this section to the Translation Program page.

**Additional context**

Adding a mission and vision would inform readers about what the Translation Program is aiming to achieve and how.

**Comment by minimalsm** [comment]
Closed by #4046
