### ISSUE TITLE
Adding Tokocrypto Indonesia to "Suggest an Exchange" on Ethereum.org 

### ISSUE THREAD

**Issue by asriqul** [ethereum/ethereum-org-website#4037]
Before suggesting an exchange, make sure you've read [our exchange listing policy](https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**

< Indonesia. all countries, have the identity and crypto legality of the country of residence>

**Which currencies are accepted by this exchange?**

< Fiat Currency : Indonesia Rupiah (Rp), and currencies of all countries >

**Do you have any proof that they're a legitimate company?**

< Tokocrypto claims to be the first cryptoasset exchange to be registered (Registration number: 001/BAPPEBTI/CP-AK/11/2019) with the Commodity Futures Trading Regulatory Agency (BAPPEBTI) of Indonesia

https://news.tokocrypto.com/2019/11/26/tokocrypto-siap-tancap-gas-setelah-terdaftar-di-bappebti/ >

**Do you have any extra information?**

<Tokocrypto was ranked first in the "Exchange Spot" of crypto assets in Indonesia and 27th in the world based on a report on the development site for crypto assets Coin Market Cap on Friday (3/9/2021). The rating is given based on several factors, including average liquidity in terms of trading activity and daily trading volume. >

**Comment by minimalsm** [comment]
Hey @asriqul thanks for creating this issue. Just to check am I correct in thinking TokoCrypto is only available in Indonesia?

**Comment by asriqul** [comment]
Thanks for replying me, Tokocrypto available for all users around the world. but the headquarter and Branch in Indonesia

**Comment by minimalsm** [comment]
@asriqul - I tried searching on the site but I couldn't find anything. Are you able to provide a link to documentation detailing exactly the countries that are and aren't supported? 

Thanks

**Comment by minimalsm** [comment]
Hey @asriqul, closing this out. Please feel free to reopen/open a new issue with the information above.
