### ISSUE TITLE
Revisit Nodes as a Service page

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#4053]
**Is your feature request related to a problem? Please describe.**
The content on this page needs a refreshing as it is a bit outdated. There have been projects coming out decentralizing nodes as a service, and currently the information does not reflect this. 

**Describe the solution you'd like**

Looking to refresh the information on https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/ to reflect the current landscape of this area. 

Questions that could use refreshed information:
- HOW DO NODE SERVICES WORK?
- WHAT ARE THE BENEFITS OF USING A NODE SERVICE?
- WHAT ARE THE CONS OF USING A NODE SERVICE?

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by larrybird0x** [comment]
I'm interested in helping out with this issue!

**Comment by minimalsm** [comment]
Hey @larrybird0x thanks for offering to help on this :-) I've assigned you. I know you're in direct contact with @corwintines already but if you need anything on this issue feel free to ping here or on discord.

**Comment by HursitTarcan** [comment]
@minimalsm not sure if this has already been resolved but I'm willing to do this (if it still has to be done).
