### ISSUE TITLE
Reporte de Error

### ISSUE THREAD

**Issue by rodeger** [ethereum/ethereum-org-website#4054]
**Describa el bug**

**To Reproduce**
Pasos realizados que ocasionaron el bug:

1. ir a '...'
2. Click en '....'
3. Deslizar abajo '....'
4. mire el error

**Expected behavior**

**Screenshots**

**Computador (por favor describa la siguiente información:**

- Navegador[e.g. chrome, safari]
- Versión [e.g. 22]

**Smartphone (Por favor complete la siguiente informacion):**

- Equipo: [e.g. iPhone6]
- Navegador [e.g. stock browser, safari]
- Versión [e.g. 22]

**informe adicional**

**Gracias por ayudarnos?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @rodeger you've left the issue blank... anything we can do to help here?

**Comment by wackerow** [comment]
@rodeger Please join our discord if you have questions. Closing this for now, feel free to open a new issue with the requested information.
