### ISSUE TITLE
Acknowledge our project contributors

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#407]
**Is your feature request related to a problem? Please describe.**

Now that we added [All Contributors](https://allcontributors.org/docs/en/overview) to acknowledge contributors [in the project README](https://github.com/ethereum/ethereum-org-website#contributors-), let's give recognition to all the folks who have contributed to ethereum.org!

**Describe the solution you'd like**

- [x] Review past PRs to add all [code contributors](https://github.com/ethereum/ethereum-org-website/graphs/contributors) w/ their relevant contribution types
- [x] Add all language contributors from Github & CrowdIn (if they have a GH handle)

### Are you missing?
If you've contributed to our project & would like to be added, please comment here with a link to your commit or contribution 😄 

### (this issue will be an ongoing thread)

**Comment by samajammin** [comment]
@all-contributors please add @alancwoo for code & design

**Comment by samajammin** [comment]
@all-contributors please add @jjmstark for content, review & project management

**Comment by samajammin** [comment]
@all-contributors please add @think-in-universe for code & content

**Comment by samajammin** [comment]
@all-contributors please add @Jannis for content

**Comment by samajammin** [comment]
@all-contributors please add @easeev for content

**Comment by samajammin** [comment]
@all-contributors please add @virgil for content

**Comment by samajammin** [comment]
@all-contributors please add @ScyDev for code

**Comment by samajammin** [comment]
@all-contributors please add @shayanb for code & translation

**Comment by samajammin** [comment]
@all-contributors please add @Souptacular for content & documentation

**Comment by samajammin** [comment]
@all-contributors please add @CPSTL for content, review & documentation

**Comment by samajammin** [comment]
@all-contributors please add @maurelian for code, review & content

**Comment by samajammin** [comment]
@all-contributors please add @faraggi for content & translation

**Comment by samajammin** [comment]
@all-contributors please add @ethers for content

**Comment by samajammin** [comment]
@all-contributors please add @eswarasai for code

**Comment by samajammin** [comment]
@all-contributuors please add @wtf for code, review & infrastructure

**Comment by samajammin** [comment]
@all-contributors please add @zoek1 for code

**Comment by samajammin** [comment]
@all-contributors please add @wtf for code, review & infrastructure

**Comment by samajammin** [comment]
@all-contributors please add @sneg55 @BogdanHabic for content

**Comment by samajammin** [comment]
@all-contributors please add @BogdanHabic & @zscole for content

**Comment by samajammin** [comment]
@all-contributors please add @zscole for content

**Comment by samajammin** [comment]
@all-contributors please add @s0b0lev for content

**Comment by samajammin** [comment]
@all-contributors please add @realabbas for content

**Comment by samajammin** [comment]
@all-contributors please add @pi0neerpat for content

**Comment by samajammin** [comment]
@all-contributors please add @maheshmurthy for content

**Comment by samajammin** [comment]
@all-contributors please add @lbrendanl for content

**Comment by samajammin** [comment]
@all-contributors please add @kcole16 for content

**Comment by samajammin** [comment]
@all-contributors please add @javier-tarazaga for content

**Comment by samajammin** [comment]
@all-contributors please add @gesquinca for content

**Comment by samajammin** [comment]
@all-contributors please add @econoar for content

**Comment by samajammin** [comment]
@all-contributors please add @carumusan for content

**Comment by samajammin** [comment]
@all-contributors please add @bmann for content

**Comment by samajammin** [comment]
@all-contributors please add @awallendahl for content

**Comment by samajammin** [comment]
@all-contributors please add @Sunghee2 for content

**Comment by samajammin** [comment]
@all-contributors please add @Solexplorer for content

**Comment by samajammin** [comment]
@all-contributors please add @PierrickGT for code

**Comment by samajammin** [comment]
@all-contributors please add @Perseverance for content

**Comment by samajammin** [comment]
@all-contributors please add @ChrisChinchilla for content

**Comment by samajammin** [comment]
@all-contributors please add @Aniket-Engg for content

**Comment by samajammin** [comment]
@all-contributors please add @wilbarnes for content

**Comment by samajammin** [comment]
@all-contributors please add @wanseob for content

**Comment by samajammin** [comment]
@all-contributors please add @vrde for content

**Comment by samajammin** [comment]
@all-contributors please add @timbeiko for content

**Comment by samajammin** [comment]
@all-contributors please add @spalladino for content

**Comment by samajammin** [comment]
@all-contributors please add @shazow for content

**Comment by samajammin** [comment]
@all-contributors please add @shanejonas for content

**Comment by samajammin** [comment]
@all-contributors please add @remiprev for content

**Comment by samajammin** [comment]
@all-contributors please add @phillux for content

**Comment by samajammin** [comment]
@all-contributors please add @pfletcherhill for content

**Comment by samajammin** [comment]
@all-contributors please add @oovg for content

**Comment by samajammin** [comment]
@all-contributors please add @ninabreznik for content

**Comment by samajammin** [comment]
@all-contributors please add @nicksavers for content

**Comment by samajammin** [comment]
@all-contributors please add @nabetse00 for content

**Comment by samajammin** [comment]
@all-contributors please add @mat7ias for content

**Comment by samajammin** [comment]
@all-contributors please add @martintel for content

**Comment by samajammin** [comment]
@all-contributors please add @mariapaulafn for content

**Comment by samajammin** [comment]
@all-contributors please add @joshorig for content

**Comment by samajammin** [comment]
@all-contributors please add @jekrb for content

**Comment by samajammin** [comment]
@all-contributors please add @jamesconnolly93 for content

**Comment by samajammin** [comment]
@all-contributors please add @guylando for content

**Comment by samajammin** [comment]
@all-contributors please add @fzeoli for content

**Comment by samajammin** [comment]
@all-contributors please add @djrtwo for content

**Comment by samajammin** [comment]
@all-contributors please add @damianrusinek for content

**Comment by samajammin** [comment]
@all-contributors please add @craigwilliams84 for content

**Comment by samajammin** [comment]
@all-contributors please add @chriseth for content

**Comment by samajammin** [comment]
@all-contributors please add @chaitanyapotti for content

**Comment by samajammin** [comment]
@all-contributors please add @carver for content

**Comment by samajammin** [comment]
@all-contributors please add @ajsantander for content

**Comment by samajammin** [comment]
@all-contributors please add @RichardMcSorley for content

**Comment by samajammin** [comment]
@all-contributors please add @Lililashka for design

**Comment by samajammin** [comment]
@all-contributors please add @JesseAbram for content

**Comment by samajammin** [comment]
@all-contributors please add @EvanVanNessEth for content

**Comment by samajammin** [comment]
@all-contributors please add @AlexandrouR for content

**Comment by samajammin** [comment]
@all-contributors please add @8bitp for content

**Comment by samajammin** [comment]
@all-contributors please add @sorumfactory for translation & project management

**Comment by samajammin** [comment]
@all-contributors please add @samajammin for code, content, documentation & project management

**Comment by samajammin** [comment]
@all-contributors please add @samajammin for code, content, documentation & project management

**Comment by samajammin** [comment]
@sorumfactory - please contact all translators & tell them if they'd like recognition to please comment on this issue & to include a link to their CrowdIn profile. Thanks!

**Comment by sangphilkim** [comment]
@samajammin 

my CrowdIn profile is https://crowdin.com/profile/philnshoo/
thanks!

**Comment by tstt** [comment]
@samajammin 
My crowdin profile: https://crowdin.com/profile/peijie
thanks

**Comment by Jokyash** [comment]
My crowdin profile is: [](https://crowdin.com/profile/jokyash).

**Comment by samajammin** [comment]
@all-contributors please add @sangphilkim for translation

**Comment by samajammin** [comment]
@all-contributors please add @tstt for translation

**Comment by samajammin** [comment]
@all-contributors please add @Jokyash for translation

**Comment by pedrorivera** [comment]
My crowdin is [pedrorivera](https://crowdin.com/profile/pedrorivera)

**Comment by gabririgo** [comment]
Hey adding my crowdin gabririgo[https://crowdin.com/profile/gabririgo] as indicated by @sorumfactory

**Comment by dTilen** [comment]
Checking in as a translator for the Slovenian content. My crowdin id is [dTilen](http://crowdin.com/profile/dTilen).

**Comment by jJosko1986** [comment]
Me also as a translator of the Slovenian content. My crowdin id is https://crowdin.com/profile/matjaz.verdnik

**Comment by EthereumCommunityNetwork** [comment]
ECN is a Chinese contributor for ethereum.org, Our Crowdin profile link: https://crowdin.com/profile/ethereum.cn

**Comment by damianoazzolini** [comment]
My crowdin profile https://crowdin.com/profile/damianodamiano (italian contributor)

**Comment by matteopey** [comment]
Hello, my crowdin profile is: https://crowdin.com/profile/matteopey

Thanks

**Comment by kilu83** [comment]
Hello, I am Hun Ryu.

My crowdin profile is: https://crowdin.com/profile/hunryu

**Comment by nake13** [comment]
Hi I'm ZhiXiong Pan.

My crowning profile is: https://crowdin.com/profile/nake13

**Comment by alexiskefalas** [comment]
Hi I'm Alexis Kefalas
My crowning profile is: https://crowdin.com/profile/alexiskefalas

**Comment by behradkhodayar** [comment]
Hello & Thank you for putting this motivational plan into action.
I'm Behrad Khodayar & My Crowdin profile is: https://crowdin.com/profile/behradkhodayar

**Comment by Frankaus** [comment]
https://crowdin.com/profile/quantumfranci

Translation

**Comment by hacktar** [comment]
Hi,
my crowning profile is: https://crowdin.com/profile/hacktar
and i made a pull request: https://github.com/ethereum/ethereum-org-website/pull/250

**Comment by DjangoM** [comment]
Hi everyone, 
I did slovak translations..
https://crowdin.com/profile/DjangoM

**Comment by EmanHerawy** [comment]
Hey,please add me :) 
My crowdin profile is: https://crowdin.com/profile/eman.herawy

**Comment by Bellinas** [comment]
Hi, my crowning profile is: 
https://crowdin.com/profile/bellinas90
I helped a bit with Spanish translation.

**Comment by amchercashin** [comment]
https://crowdin.com/profile/amchercashin

**Comment by shayanb** [comment]
https://crowdin.com/profile/shayanbahal

**Comment by samajammin** [comment]
@all-contributors please add @pedrorivera for translation

**Comment by samajammin** [comment]
@all-contributors please add @gabririgo for translation

**Comment by samajammin** [comment]
@all-contributors please add @dTilen for translation

**Comment by samajammin** [comment]
@all-contributors please add @jJosko1986 for translation

**Comment by samajammin** [comment]
@all-contributors please add @EthereumCommunityNetwork for translation

**Comment by samajammin** [comment]
@all-contributors please add @damianoazzolini for translation

**Comment by samajammin** [comment]
@all-contributors please add @matteopey for translation

**Comment by samajammin** [comment]
@all-contributors please add @kilu83 for translation

**Comment by samajammin** [comment]
@all-contributors please add @nake13 for translation

**Comment by samajammin** [comment]
@all-contributors please add @alexiskefalas for translation

**Comment by samajammin** [comment]
@all-contributors please add @behradkhodayar for translation

**Comment by samajammin** [comment]
@all-contributors please add @Frankaus for translation

**Comment by samajammin** [comment]
@all-contributors please add @hacktar for code & translation

**Comment by samajammin** [comment]
@all-contributors please add @DjangoM for translation

**Comment by samajammin** [comment]
@all-contributors please add @DjangoM for translation

**Comment by samajammin** [comment]
@all-contributors please add @EmanHerawy for translation

**Comment by samajammin** [comment]
@all-contributors please add @Bellinas for translation

**Comment by samajammin** [comment]
@all-contributors please add @amchercashin for translation

**Comment by samajammin** [comment]
@all-contributors please add @shayanb for translation & code

**Comment by EnochMbaebie** [comment]
https://crowdin.com/profile/enochmbaebie

**Comment by inlak16** [comment]
https://crowdin.com/profile/inlak16

**Comment by bobjiang** [comment]
Simplified Chinese translation team member - Bob Jiang

https://crowdin.com/profile/bobjiang

**Comment by cobject** [comment]
https://crowdin.com/profile/cobject for Korean translation

**Comment by jzu** [comment]
[https://crowdin.com/profile/filtertron](https://crowdin.com/profile/filtertron) (fr)

**Comment by HachemiH** [comment]
https://crowdin.com/profile/Hachemih (fr)

**Comment by hanzoh1** [comment]
https://crowdin.com/profile/hanzoh (jp)

**Comment by vincentlg** [comment]
https://crowdin.com/profile/vincentlg (fr)

**Comment by samajammin** [comment]
@all-contributors please add @EnochMbaebie for translation

**Comment by samajammin** [comment]
@all-contributors please add @inlak16 for translation

**Comment by samajammin** [comment]
@all-contributors please add @bobjiang for translation

**Comment by samajammin** [comment]
@all-contributors please add @cobject for translation

**Comment by samajammin** [comment]
@all-contributors please add @jzu for translation

**Comment by samajammin** [comment]
@all-contributors please add @HachemiH for translation

**Comment by samajammin** [comment]
@all-contributors please add @hanzoh1 for translation

**Comment by samajammin** [comment]
@all-contributors please add @vincentlg for translation

**Comment by sickmorty** [comment]
Looking for Indonesian contribution haha, it's a bit hard to take th translation alone 😁
https://crowdin.com/profile/udinujang

**Comment by jeedani** [comment]
https://crowdin.com/profile/jeedani (korean translation)

**Comment by wanseob** [comment]
https://crowdin.com/profile/wanseob (ko)

**Comment by akira-19** [comment]
https://crowdin.com/profile/akira-19 (jp)

**Comment by samajammin** [comment]
@all-contributors please add @sickmorty for translation

**Comment by samajammin** [comment]
@all-contributors please add @jeedani for translation

**Comment by samajammin** [comment]
@all-contributors please add @wanseob for translation

**Comment by samajammin** [comment]
@all-contributors please add @akira-19 for translation
