### ISSUE TITLE
Add standardization of header casing to style-guide

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#4075]
**Is your feature request related to a problem? Please describe.**
The capitalization of headers is inconsistent throughout the codebase. If you visit our new [style guide](https://ethereum.org/en/contributing/style-guide/) it nicely lays out many conventions that are being used across the site, but this one is missing, and also demonstrates the inconsistency. 

![image](https://user-images.githubusercontent.com/54227730/135181873-bacbdfd2-784b-42ea-9337-3e59041b1018.png)

Above you'll see "Use Active Voice" in title casing, while "Linking to internal pages" is in sentence casing

**Describe the solution you'd like**
- [x] Decide on which casing is preferred by default (comment below)
- [x] Add note about this to style guide (#4082)
- [x] Cleanup of existing codebase (#4082)

**Describe alternatives you've considered**
- Leave it up to whoever writes it to chose at will 👎🏻 
- Turn all headers into random emojies 🤷🏻 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
@wackerow 
> Turn all headers into random emojies 🤷🏻

👀 👍 👉 💌

**Comment by minimalsm** [comment]
IMO we should use sentence case for headers.
