### ISSUE TITLE
Chinese tutorials showing incorrect reading time

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4083]
**Describe the bug**

The [Chinese simplified tutorials page](https://ethereum.org/zh/developers/tutorials/) is showing the incorrect time to read. Every tutorial is showing 1 or 2 minutes as their read time. 

For tutorials hosted on ethereum.org we get `timeToRead` through [a GraphQL query](https://github.com/ethereum/ethereum-org-website/blob/d129338b4a81bbb88f515ff68682889a8607d582/src/templates/tutorial.js#L232) which, based on the number of words, calculates an estimated reading time.

We use `gatsby-plugin-mdx` to calculate the `timeToRead` and it is a [known issue](https://github.com/gatsbyjs/gatsby/issues/25532) that the plugin doesn't work well with hanzi/kanji (Chinese/Japanese characters).

There is an [open PR in the Gatsby repo](https://github.com/gatsbyjs/gatsby/pull/25533) to fix this issue but there hasn't been any movement on this in a while. 

One solution could be to add `timeToRead` to the frontmatter of all Chinese tutorials with hardcoded values (similar to how we do it [with external tutorials](https://github.com/ethereum/ethereum-org-website/blob/d129338b4a81bbb88f515ff68682889a8607d582/src/data/tutorials.json#L70)).

**To Reproduce**

1. Go to 'https://ethereum.org/zh/developers/tutorials/'
2. See error

**Expected behavior**
The time to read should be accurate and closer to the times found on other languages ([see Romanian](https://ethereum.org/ro/developers/tutorials/))

**Screenshots**
Chinese simplified tutorials
<img width="991" alt="Screenshot 2021-09-29 at 15 45 04" src="https://user-images.githubusercontent.com/62268199/135292354-d1d9bce0-c023-429e-98dc-4f0ef3bdea1c.png">

Romanian tutorials
<img width="985" alt="Screenshot 2021-09-29 at 15 46 12" src="https://user-images.githubusercontent.com/62268199/135292948-bf667b2d-dbfc-4ed6-8fa5-040d9c22f7ca.png">

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SNikhill** [comment]
@minimalsm 

Sir, May I please have this one?

**Comment by minimalsm** [comment]
@SNikhill all yours :-) ❤️

**Comment by SNikhill** [comment]
Thank You. I shall fix the same. I shall refer to other languages for a time estimate and hard code the same.

I do have a question, would it be better for future translations to default to the time estimate for the English version (Assuming English to be the default language)?

**Comment by pettinarip** [comment]
My two cents here. Have we tried this plugin? https://www.gatsbyjs.com/plugins/gatsby-remark-reading-time
I have tested the underlying lib that is been used there (https://github.com/ngryman/reading-time) and seems to be working fine.

Perhaps we can use this lib as a "complete" solution while we wait for the fix in the mdx plugin.

**Comment by SNikhill** [comment]
@pettinarip 

Thank you for the suggestion, sir. From the README (help wanted) section, it does look like that it supports CJK languages. I shall try the same too and let you know. :)

**Comment by SNikhill** [comment]
@minimalsm 

Sir, this issue is now fixed. :)
