### ISSUE TITLE
Refactor tutorials.json to externalTutorials.json

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4084]
**Is your feature request related to a problem? Please describe.**

It isn't clear that the data in [/data/tutorials.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/tutorials.json) is for external tutorials only (i.e. items on the tutorials page which link out to an external site). 

Given we also pull in tutorials from [/developers/tutorials/](https://github.com/ethereum/ethereum-org-website/tree/dev/src/content/developers/tutorials) using GraphQL this could be confusing to someone trying to understand the codebase.

**Describe the solution you'd like**

- Rename tutorials.json to externalTutorials.json
- Fix all imports/references to the file

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Ashwin-exe** [comment]
Hey @minimalsm, can I work on this issue ?

**Comment by minimalsm** [comment]
@Ashwin-exe sure, all yours 😬 If you need anything feel free to ping here or on our [discord](https://discord.gg/CetY6Y4)

**Comment by Ashwin-exe** [comment]
> 
> 
> @Ashwin-exe sure, all yours 😬 If you need anything feel free to ping here or on our [discord](https://discord.gg/CetY6Y4) ✌️

Sure 😊.

**Comment by Ashwin-exe** [comment]
#4084
