### ISSUE TITLE
Add edit page functionality to non-English developer docs 

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4086]
**Is your feature request related to a problem? Please describe.**

On our [English developer docs](https://ethereum.org/en/developers/docs/) we provide users with an 'Edit Page' button linking to the markdown file on GitHub of the current doc page they are viewing. This functionality is not available in any other language and is likely causing obvious bugs in those languages to not be fixed.

We enforce this behaviour with the [`shouldShowEditButton` function](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/TableOfContents.js#L348) by checking if the locale path is English and, if it is, showing the edit button. 

We'll have to do some refactoring to the logic of [how we get the URL for the Edit Button](https://github.com/ethereum/ethereum-org-website/blob/dev/src/templates/docs.js#L195) because the [english markdown files](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/index.md) live in a different directory/path to all of the translated content (see [Chinese developers page for contrast](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/translations/zh/developers/docs/index.md)).

English docs
<img width="1196" alt="Screenshot 2021-09-29 at 16 51 44" src="https://user-images.githubusercontent.com/62268199/135305193-41d79fda-539d-49d0-a005-fcdc146fabd5.png">

Simplified Chinese docs
<img width="1195" alt="Screenshot 2021-09-29 at 16 51 34" src="https://user-images.githubusercontent.com/62268199/135305183-0989bf86-4eb1-48d4-a41d-f424fdd67bd1.png">

**Describe the solution you'd like**

- Add 'Edit page' button on foreign language doc pages which links to the markdown file of the docs in their current language
- Add the term 'Edit page' to translation backlog (if it isn't already)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by PaoloSimonazziit** [comment]
Hello @minimalsm , I'd love to work on this

**Comment by PaoloSimonazziit** [comment]
Hello @minimalsm , just opened PR #4089 that aims at implementing this functionality. As written there, no change to the logic of how we get the URL for the Edit Button was needed. Also edit-button translations are already present.

I also added a suggested change for the mobile view, since for example for pages in Italian the "Contributors" text inside the button goes outside the boundaries of the button itself.
