### ISSUE TITLE
Add NFT school to developer learning tools

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4093]
**Describe the solution you'd like**

Add [NFT school](https://nftschool.dev/) to our [developer learning tools page](https://ethereum.org/en/developers/learning-tools/) under the bootcamp section.

**Describe alternatives you've considered**

We should probably separate bootcamps and courses into their own sections.

**Additional context**

[This is a similar PR](https://github.com/ethereum/ethereum-org-website/pull/3966) to use as a reference

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by pranavvdesai** [comment]
can i work on this? @minimalsm

**Comment by minimalsm** [comment]
@pranavvdesai sure! All yours 😀

**Comment by vj-codes** [comment]
If @pranavvdesai is not working on it, I would like to:)

**Comment by pranavvdesai** [comment]
> If @pranavvdesai is not working on it, I would like to:)

I am

**Comment by shryasss** [comment]
I would like to work on this
