### ISSUE TITLE
Remove deprecated ETH2 client (Trinity)

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4097]
**Describe the bug**

[Trinity](https://github.com/ethereum/trinity) is still listed on [our get-involved page](https://ethereum.org/pl/eth2/get-involved/#clients) as an ETH2 client despite being deprecated.

**To Reproduce**

1. Go to 'https://ethereum.org/en/eth2/get-involved/#clients'
2. Scroll down to 'Experimental Eth2 clients'
3. See error

**Expected behavior**

We shouldn't list clients that are no longer being developed or maintained.

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by abritpal** [comment]
Hi!, can I work on this issue

**Comment by minimalsm** [comment]
Hey @abritpal 😬 assigned you. Let me know if you need anything to get started on this.
