### ISSUE TITLE
Move Lodestar from experimental to production-ready ETH2 client

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4098]
**Describe the bug**

On our [get-involved eth2 page](https://ethereum.org/en/eth2/get-involved/#clients), Lodestar is still being listed as an experimental Eth2 client. 

**To Reproduce**

1. Go to 'https://ethereum.org/en/eth2/get-involved/#clients'
2. Go to 'Experimental Eth2 clients'
3. See error

**Expected behavior**

[Lodestar is now production-ready](https://hackmd.io/@benjaminion/eth2_news/https%3A%2F%2Fhackmd.io%2F%40benjaminion%2Fwnie2_210924#The-Beacon-Chain) and should be moved into the correct category.

**Screenshots**

![Screenshot 2021-09-30 at 20 49 35](https://user-images.githubusercontent.com/62268199/135520973-e736f1a6-a444-472d-b9dd-0057cf86a5ab.png)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by harshmathurx** [comment]
I would like to work on this 
please assign it to me

**Comment by minimalsm** [comment]
Hey @harshmathurx, I've assigned you. Let me know if you need anything to get started on this 😀.

**Comment by harshmathurx** [comment]
I shall, thank you :)
