### ISSUE TITLE
Step 9 is unclear in "how to mint an NFT" tutorial

### ISSUE THREAD

**Issue by under3415** [ethereum/ethereum-org-website#4176]
**Describe the bug**

Step 9 is unclear: https://ethereum.org/en/developers/tutorials/how-to-mint-an-nft/#call-mintnft-fn

How do we call `mintNFT` function?
What is `contract-interact.js`, it's only mentioned in the title?
Can you include the actual call syntax?

I tried below, but it just sits in "starting"
````
npx run scripts/mint-nft.js mintNFT "https://gateway.pinata.cloud/ipfs/[TokenURI]"
````

**To Reproduce**
Call syntax missing from tutorial step 9

**Expected behavior**

Call syntax provided

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Firefox
- Version: [e.g. 22]

**Smartphone (please complete the following information):**

- Browser: [e.g. stock browser, safari]
- Version: [e.g. 22]

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @under3415 thanks for reporting this. I've re-read this and agree that the instructions are unclear.

The instruction _"Get its hashcode from Pinata and pass the following into a call to mintNFT"_ refers to calling the `mintNFT` function. This can be done as follows:

```javascript
mintNFT(
  "https://gateway.pinata.cloud/ipfs/QmYueiuRNmL4MiA2GwtVMm6ZagknXnSpQnB3z2gWbz36hP"
)
```

However you need to pass in your own hashcode: `https://gateway.pinata.cloud/ipfs/[YOUR HASH CODE GOES HERE]`

The example of how this code should look is in Step 9.

<img width="917" alt="Screenshot 2021-10-11 at 11 53 37" src="https://user-images.githubusercontent.com/62268199/136778809-9599afad-bab6-4bd0-809e-2aa528365f5b.png">

I agree the wording isn't fantastic and we should fix this 👍

**Comment by minimalsm** [comment]
@all-contributors please add @under3415 for ideas

**Comment by under3415** [comment]
Should the URI be generic ipfs address instead of pinata?

**Comment by minimalsm** [comment]
Hey @noopta :) any update on this?

**Comment by noopta** [comment]
> Hey @noopta :) any update on this?

Hey, really sorry I've been quite busy lately with balancing school and my internship. I do genuinely want to complete the ticket though, are there any deadlines to be aware of? If there are pressing deadlines, I can pass off the ticket to someone else for now, and look to pick up a ticket when I have more spare time. Let me know what works best.

**Comment by vishvanathan-k** [comment]
I will take it on 😉 , If you don't mind

**Comment by vishvanathan-k** [comment]
This issue is solved... It has to be closed 😄!!
