### ISSUE TITLE
Background is scrollable when navigation modal is open on smaller screen sizes

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4194]
**Describe the bug**
On screens below 1025px wide the background is scrollable when the navigation modal is open.

[View a GIF of the bug](https://i.gyazo.com/650bdaffedef83761429237b7b08386a.gif)

**To Reproduce**

1. Go to [ethereum.org](https://ethereum.org/en/)
2. Reduce screen size below 1025px wide
3. Click on navigation hamburger
4. See scrolling error

**Expected behavior**

Scrolling should be limited to the sidebar modal.

**Additional context**
We are dealing with a similar issue in https://github.com/ethereum/ethereum-org-website/pull/3799

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
Hi @minimalsm, I saw this issue is pretty much with every modal on mobile. I would like to give it a try. I do not have experience with gatsby/react specifically, but I think I might be able to do this one 😃

**Comment by JulienMaurice** [comment]
Hey, maybe I could get my hand on it. I tried something in local, and its seem to work pretty well.
As I don't have much experience, maybe the method isn't suitable.
If you allow me, I could show you what I've done.

**Comment by vluna** [comment]
@JulienMaurice we can work together on this one if you like? My solution, which works in local as well, is just to add `position: fixed` to the `#gatsby-focus-wrapper` when any modal pops up.

**Comment by JulienMaurice** [comment]
@vluna I agree !
My proposition was maybe a bit more abrupt. Tell me what you think

I would have use the `handleMenuToggle()` in Nav component
Using the already existant `isMenuOpen` and `isSearchOpen` state: 

```js
      if (!isMenuOpen) {
        document.body.setAttribute("style", "overflow: hidden; position: fixed;");
      } else {
        document.body.setAttribute("style", "overflow: visible; position: static;");
      }
```
Stopping the body to be scrolled when the Mobile Menu or the Search Menu is open.

**Comment by vluna** [comment]
@JulienMaurice Pretty much what I have, I just have it at the end of the function since it can be part of any modal.

```
const handleMenuToggle = (item) => {
   /*...if else statements*/

  const gatsbyWrapper = document.querySelector("#gatsby-focus-wrapper");
  if(isMenuOpen || isSearchOpen) {
    gatsbyWrapper.style.cssText = '';
  } else {
    gatsbyWrapper.style.cssText = 'position:fixed';
  }
}
```

**Comment by JulienMaurice** [comment]
I'm alright with this.

In the case where the id `#gatsby-focus-wrapper` is used in the futur, maybe we should put something like
`gatsbyWrapper.style.position = "fixed"` & `gatsbyWrapper.style.position = "static"`

Instead of wiping it with `style.cssText`, don't you think ?

**Comment by vluna** [comment]
Yup, that is better for sure!

**Comment by vluna** [comment]
@JulienMaurice I noticed an issue where if we add position fixed/static it will always scroll to the top. We can fix this by adding a global variable and every time we open the modal save the position and scroll to the position Y on close/open.

**Comment by JulienMaurice** [comment]
@vluna 
I just took a look. You are right.

Alright, funny thing: I never used Gatsby or worked on a gatsby project before. It seems that it force the `html` element to `overflow-y: scroll`. And that's why just playing with the `body` element (what should be done, I believe) doesn't work.

We have the option where we could get `scrollY` , keep the position, and set it after with `window.scrollTo()` (with maybe putting `scrollBehavior` to unset before if its smoothing) . But it seems a bit too much for that. 

Instead, we could just set `documentElement` behaviour differently the time that the menu/search is open to minimize the impact and keep it simple.
```js
   if (isMenuOpen || isSearchOpen) {
      document.documentElement.style.overflowY = "scroll"
    } else {
      document.documentElement.style.overflowY = "hidden"
    }

**Comment by vluna** [comment]
> @vluna I just took a look. You are right.
> 
> Alright, funny thing: I never used Gatsby or worked on a gatsby project before. It seems that it force the `html` element to `overflow-y: scroll`. And that's why just playing with the `body` element (what should be done, I believe) doesn't work.
> 
> We have the option where we could get `scrollY` , keep the position, and set it after with `window.scrollTo()` (with maybe putting `scrollBehavior` to unset before if its smoothing) . But it seems a bit too much for that.
> 
> Instead, we could just set `documentElement` behaviour differently the time that the menu/search is open to minimize the impact and keep it simple.
> 
> ```js
>    if (isMenuOpen || isSearchOpen) {
>       document.documentElement.style.overflowY = "scroll"
>     } else {
>       document.documentElement.style.overflowY = "hidden"
>     }
> ```

Nice @JulienMaurice! Thank you for creating the PR 😄
