### ISSUE TITLE
Explicitly add frontmatter props to schema

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#4202]
**Is your feature request related to a problem? Please describe.**

Noticed in #4152 that we're not consistently adding frontmatter props to the schema: https://github.com/ethereum/ethereum-org-website/pull/4152#pullrequestreview-776680917

**Describe the solution you'd like**

We should add all properties we use in frontmatter to the `Frontmatter` type, so it's clear what the potential options are. Would be nice to also document what the properties are used for.

**Describe alternatives you've considered**

Keep as is.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
I think this has been addressed during out typescript migration. But, as we are [migrating to NextJS](https://github.com/ethereum/ethereum-org-website/issues/10666) this quarter this may change. Going to close this out in favor of the migration work that is being done, or has been done. If this is still an issue after the migration we can revive.
