### ISSUE TITLE
webpack.stats.json is disclosed

### ISSUE THREAD

**Issue by Aldekein** [ethereum/ethereum-org-website#4237]
**Describe the bug**
https://ethereum.org/webpack.stats.json has the dependency graph and various other build information. It shouldn't be published because it will allow to easier copy and modify the minified website JS.

**To Reproduce**
Open the URL – https://ethereum.org/webpack.stats.json

**Expected behavior**
404 error.

**Additional context**
The CI should be instructed to not include this file on builds. 
There's also https://archive.devcon.org/webpack.stats.json and https://ethereum.foundation/webpack.stats.json so this may be a common problem in our deployments.

**Comment by Aldekein** [comment]
@minimalsm could we remove that file from Git and add it to `.gitignore`? It should be a quick change.

**Comment by samajammin** [comment]
There's a Gatsby issue on providing an option to remove it from production build - perhaps we can bump there: https://github.com/gatsbyjs/gatsby/issues/23629

**Comment by samajammin** [comment]
@Aldekein thanks for raising this issue!

> https://ethereum.org/webpack.stats.json has the dependency graph and various other build information. It shouldn't be published because it will allow to easier copy and modify the minified website JS.

I don't have a solid understanding of what the stats.json file exposes, but is it any different from our site being open source & available on GitHub? Any malicious actor can already inspect our package.json to view our dependency graph, no?

**Comment by Aldekein** [comment]
Oh, that's a good catch :) I created this issue based on Detectify report without considering the open source nature of the website. `webpack.stats.json` [does not disclose](https://webpack.js.org/api/stats/) any extra information, so should be safe to keep as-is.
