### ISSUE TITLE
Catch missing lang property error before build

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4253]
**Is your feature request related to a problem? Please describe.**

In [this PR](https://github.com/ethereum/ethereum-org-website/pull/4252) we created a check that will throw an error during the build if a markdown page does not have a lang attribute. The problem with this is that the build could run for 30+ minutes before throwing an error.

**Describe the solution you'd like**

We should implement a check to catch this **before** we reach the point of doing a build. This could be something like a pre-commit hook or a test.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by narayand16** [comment]
My approach is to use husky pre-commit hook which will check this lang in the MDX file. Can you assign this to me ?

**Comment by minimalsm** [comment]
Hey, @noopta sure. I have assigned you. I think the suggested approach by @narayand16 is probably sufficient to solve this for now.

Thanks for offering @narayand16; if @noopta ends up not working on this, I'll ping you to see if you're still interested...

**Comment by minimalsm** [comment]
Hey @narayand16 

Sorry for the late reply on this. Do you want to work on this still?

**Comment by narayand16** [comment]
Hi Joshua,

I would like to work on this issue. Can you assign it to me ?

It would be great if you could give a little brief about the issue and what
we are trying to accomplish.

Thanks,
Narayan Deshmukh

**Comment by akht** [comment]
Hi @minimalsm , can I take up this issue?

**Comment by SNikhill** [comment]
@minimalsm 

May I tackle this one?

**Comment by minimalsm** [comment]
Closing this out as this was solved as part of #7088
