### ISSUE TITLE
Suggest Refinable

### ISSUE THREAD

**Issue by maximgeerinck** [ethereum/ethereum-org-website#4261]
We would like to suggest Refinable to be added to the "Digital collectibles" category of ethereum.org

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

We have conducted multiple audits by multiple vendors

- Hacken: https://hacken.io/wp-content/uploads/2021/04/04042021_Refinable_SC_Audit_Report.pdf
- Slowmist: https://drive.google.com/file/d/101TJt-OI9Zy08HCTDKSH_JVa65m4bkWe/view?usp=sharing

**Is your dapp open source?**

The SDK repo is entirely open source: https://github.com/refinableco/refinable-sdk

**Can a user access the dapp without creating an account?**

Yes, the user can simply connect his wallet without the need to create an account.

A user can choose from any of the following wallets:

- Metamask
- TrustWallet
- Binance Wallet

Next to this, the user is also able to connect to any of the 70+ wallets supported by WalletConnect (https://walletconnect.com/registry/wallets) 

**Are dapp funds non-custodial?**

Yes, only the standard NFT protocol is used, making the app fully decentralized. Users can still access and move nfts by using any wallet that supports NFTs (Metamask, TrustWallet, ...)

**Do you offer community support?**

We have multiple support channels where we look at and reply to:

- Discord: https://discord.com/invite/2Ps43kUxy7 
- Twitter: https://twitter.com/refinableapp
- Telegram: https://t.me/refinablenft

Next to this we also offer support through the intercom chat bubble on our website

**Describe any geographical restrictions on usage of your dapp**

The app is globally accessible and optimized for global distribution using a solid CDN network and regional servers.

**Dapp title**

Refinable

**Dapp description**

A decentralized multi-chain NFT marketplace for users to trade items from across the metaverse. Discover, Trade, and Create NFTs from the best and upcoming projects and collections on Ethereum, Solana, Binance Smart Chain, Polygon and More.

**Dapp logo**

https://app.refinable.com/logo.svg

**Brand color**

#000

**Comment by maximgeerinck** [comment]
Any update?

**Comment by minimalsm** [comment]
Hey @maxingeerinck

Sorry for the delay here. Having a look at Refinable, love the UI!

Unfortunately, I don't think adding Refinable offers anything particularly novel to users of ethereum.org that we don't already showcase and we feel listing it would only lead to more confusion for users. 

The real deciding factor is that Refinable is a general NFT marketplace, rather than one focused on Ethereum NFTs. Only ~1% of the NFTs listed are on Mainnet Ethereum (168 ETH vs 13350 total).
