### ISSUE TITLE
Refactor smart contract security page URLs

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4273]
**Is your feature request related to a problem? Please describe.**

We have renamed the title of the smart contract security page from `Security` to `Smart contract security` (see https://github.com/ethereum/ethereum-org-website/pull/4212). We should do the same to the file names (currently just 'security') and URLs.

**Describe the solution you'd like**

- Change filenames of smart contract security files
- Update breaking changes (links/anchor references)
- Upload changes to CrowdIn

**Comment by il3ven** [comment]
I'd like to work on this.

**Comment by minimalsm** [comment]
Thanks @il3ven 😬 assigned!
