### ISSUE TITLE
Refactor isMobile checks into one utility function

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#4297]
**Is your feature request related to a problem? Please describe.**
There are a few checks for isMobile in the application which implement the same functionality in each of them.

**Describe the solution you'd like**
Create a single isMobile utility function to use throughout the application.

**Additional context**
These are getting added in https://github.com/ethereum/ethereum-org-website/pull/4131 and https://github.com/ethereum/ethereum-org-website/pull/4205. After these are merged, the refactor will be best.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ShubhankarKG** [comment]
Now that both the PRs are merged, can we revisit this?

I had a look at what the implementations are, and I found two implementations of `isMobile`

```javascript
let isMobile = false
if (typeof window !== undefined) {
    isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    window.navigator.userAgent
  )
}
```

```javascript
const isMobile = document && document.documentElement.clientWidth < 1024
```

Would like to know your thoughts on which one to prefer, and then maybe I can refactor that out and put it in `/src/utils/isMobile.js`.

**Comment by minimalsm** [comment]
Hey @ShubhankarKG, I've assigned you to this.

The first is more comprehensive but we would need to test it. @corwintines any thoughts on this approach?
