### ISSUE TITLE
Update Hardhat's graphic

### ISSUE THREAD

**Issue by fzeoli** [ethereum/ethereum-org-website#4298]
In here https://ethereum.org/en/developers/local-environment/
![image](https://user-images.githubusercontent.com/232174/138595654-dfa5e581-fb9c-4b63-8d0e-10d4b35bee2a.png)
This is a year-old graphic from when Hardhat was called Buidler.
This is the new version https://user-images.githubusercontent.com/176499/96893278-ebc67580-1460-11eb-9530-d5df3a3d65d0.png

Here's an SVG logo https://hardhat.org/assets/img/Hardhat-logo.652a7049.svg
Let me know if you need us to put together an asset

**Comment by corwintines** [comment]
@fzeoli made a PR to update to the other image as requested :)

**Comment by fzeoli** [comment]
that looks good, except that it's a png that's a bit blurry. Can you use the SVG? https://hardhat.org/assets/img/Hardhat-logo.652a7049.svg

**Comment by corwintines** [comment]
Thanks @fzeoli, changed to the svg.

**Comment by fzeoli** [comment]
Great, thanks
