### ISSUE TITLE
Resolve Todo at `src/components/BugBountyCards.js:111` on `dev` Branch

### ISSUE THREAD

**Issue by Hakeemmidan** [ethereum/ethereum-org-website#4303]
**Is your feature request related to a problem? Please describe.**

Not really a problem. Just some syntax clean-up. 

I'd like to resolve [the todo at `src/components/BugBountyCards.js:111` on the `dev` branch](https://github.com/ethereum/ethereum-org-website/blob/653e3efe500d24796c86536fd9464e878ab86ef8/src/components/BugBountyCards.js#L111):

```JavaScript
// TODO move data into array & loop through
const BugBountyCards = () => (
  <CardRow>
    <Card>
      <LowLabel>
        <Translation id="page-eth2-bug-bountycard-label-1" />
  // ...
```

**Describe the solution you'd like**
Associate an index number (starting from 0) with each card and do string interpolation to change the id during the iteration. E.g.
```JavaScript
{[0,1,2,3].map((i) => {
  <CardRow>
    <Card>
      <LowLabel>
        <Translation id=`page-eth2-bug-bountycard${i}-lowlabel` />
  // ...
})}
```

Nevertheless, that wouldn't work with some IDs that use words instead of numbers, such as `"page-eth2-bug-bountycard-low"`, and each card's link. So I'd need to change those IDs to just use numbers instead of words, and have a simple array of links that has an index that's the same as its parent-card index number.

**Describe alternatives you've considered**
Move _all existing data_ into an array of objects, and iterate through them.

It'd be something like this:
```JavaScript
const bugBountyCardsInfo = [
  {
    lowLabelId: 'page-eth2-bug-bountycard-label-1',
    titleId: 'page-eth2-bug-bountycard-low',
    // ...
  },
  // ...
  {
    lowLabelId: 'page-eth2-bug-bountycard-label-7',
    titleId: 'page-eth2-bug-bountycard-critical',
    // ...
  },
  // ...
];
```
Which seems a little more verbose.

**Additional context**
<img width="1680" alt="Screen Shot 2021-10-24 at 9 56 31 PM" src="https://user-images.githubusercontent.com/27740273/138608761-015cde1b-3ab4-40eb-b653-e1dbc1e5d53d.png">
(page screenshot)

**Comment by minimalsm** [comment]
Hey @Hakeemmidan. Thanks for offering to help on this.

I agree we should refactor this (as per the todo). However because of how the translations work on ethereum.org it would be a lot of overhead to rename the labels. I think moving data into an array of objects and mapping through them is what we were looking for here.

**Comment by ShubhankarKG** [comment]
Hey @Hakeemmidan , still working on this ? If not, can I pick this one up ?

**Comment by Hakeemmidan** [comment]
Hi @ShubhankarKG, thank you for reaching out! = ) 
Yes, I'm still working. (Kind of got busy with another task.) I'll try to get it done this week (by end of day, Sunday, 12/26/2021). If I don't, I'll pass it on to you. Thanks again ( ^__^ )
