### ISSUE TITLE
Add "Oracle" as a glossary term

### ISSUE THREAD

**Issue by jaskoeth** [ethereum/ethereum-org-website#4309]
**Checklist**

- [y] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [y] This term/definition is not a product advertisement or contain other promotional content
- [y] This term/definition is directly relevant to Ethereum

**Term Name: "Oracle"**

**Term Definition: "An oracle is a bridge between the blockchain and the real world. They act as on-chain APIs you can query to get information into your smart contracts. This could be anything from price information to weather reports. Oracles can also be bi-directional, used to "send" data out to the real world."**

**Sources, if any (please do not submit copywrited content without appropriate approval):**

**Ethereum.org links? https://ethereum.org/en/developers/docs/oracles/#top**

**Additional context**

**Comment by vicenzospaghetti** [comment]
I'd also like to work on this one. Are you already working on it. Want some collaboration?

**Comment by MrBrain295** [comment]
> I'd also like to work on this one. Are you already working on it. Want some collaboration?

I was waiting to be assigned but if you would like to make a pull request go ahead.
