### ISSUE TITLE
推荐可以赚以太币的游戏Recommend games that can earn Ether

### ISSUE THREAD

**Issue by chenlie449** [ethereum/ethereum-org-website#4325]
推荐可以赚以太币的游戏
Recommend games that can earn Ether

**Comment by corwintines** [comment]
@chenlie449 we certainly show a few https://ethereum.org/en/dapps/?category=gaming, would be curious what you are thinking to add to this.

**Comment by corwintines** [comment]
Closing as this has been abandoned
