### ISSUE TITLE
Adding SFT term to glossary

### ISSUE THREAD

**Issue by BenOfTheBlockchain** [ethereum/ethereum-org-website#4333]
**Checklist**

- [y] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [y] This term/definition is not a product advertisement or contain other promotional content
- [y] This term/definition is directly relevant to Ethereum

**Term Name:**

Semi-Fungible Token (SFT)

**Term Definition:**

A SFT can be described as a token, considered as both a fungible and non-fungible token (NFT). It runs on Enjin's ERC-1155 standard. A SFT can be traded just like any other fungible token, like a gift voucher with an expiration date. Once a SFT(s) get exchanged or redeemed, they lose their form and get converted into an NFT. 

**Sources, if any (please do not submit copywrited content without appropriate approval):**

[https://kalkinemedia.com/uk/stocks/financial/what-are-semi-fungible-tokens-how-are-they-different-from-nfts](https://kalkinemedia.com/uk/stocks/financial/what-are-semi-fungible-tokens-how-are-they-different-from-nfts)

**Ethereum.org links?**

[https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/#top](https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/#top)

**Additional context**

No other comments.

**Comment by corwintines** [comment]
Hmm, I am unsure if this needs to be included. I have never really heard of this term before, at least in the context of SFT's. Would like to hear what others think though.

**Comment by BenOfTheBlockchain** [comment]
> Hmm, I am unsure if this needs to be included. I have never really heard of this term before, at least in the context of SFT's. Would like to hear what others think though.

Thanks for your consideration.

**Comment by minimalsm** [comment]
@BenOfTheBlockchain hey, I agree with @corwintines. SFT isn't a commonly used acronym and I don't think we should force it into the glossary unless it becomes one. 

Thanks for the contribution either way!

**Comment by minimalsm** [comment]
@all-contributors please add @BenOfTheBlockchain for ideas
