### ISSUE TITLE
Etherem wallet

### ISSUE THREAD

**Issue by aishaidir** [ethereum/ethereum-org-website#4337]
I would like ethereum to have their own wallet instead of using a third party app yo reduce the cost of gas fee when making transactions.

**Comment by markusbug** [comment]
Gas Fees are determined by miners. Most third-party apps don't charge anything for transaction.
The Ethereum foundation cannot create a wallet that reduces gas fees.

**Comment by corwintines** [comment]
@aishaidir all wallets implement using standardized RPC calls to the protocol. Fees are dictated by block space demand. Closing this issue, but here is some more information on how gas fees are derived. I would suggest looking into L2's like Arbitrum and Optimism for reduction is gas fees.

https://ethereum.org/en/developers/docs/gas/#top
