### ISSUE TITLE
'Find a wallet' filters

### ISSUE THREAD

**Issue by taxmeifyoucan** [ethereum/ethereum-org-website#4338]
Find a wallet at https://ethereum.org/en/wallets/find-wallet/ enables various filtering for wallet features. UX is clear but I believe there might be filters for more features which are important like **non-custody, hardware wallet support, enabling own node RPC** and maybe more. 

Options like Withdraw to bank or Buy with card might lead new users to custodial, KYC wallets without understand risks. 

**Describe the solution you'd like**

Add more options to `Find a wallet`, e.g. 'Full control over the funds' for fully non custodial wallets, 'Hardware wallet support', 'Validation' for full node.. More ideas welcomed, I would rather start a discussion about options than dictate how it should look like. 

**Describe alternatives you've considered**

Maybe some other filters might be helpful like desktop/phone, newbie friendly/advanced. Guide shouldn't be overwhelming for a new user, I understand if options should be kept limited.

**Want to contribute?**

I would be glad to help with research about wallets to tag them with specific features.

**Comment by corwintines** [comment]
@taxmeifyoucan happy to collaborate on this a bit!

**Comment by minimalsm** [comment]
Hey @taxmeifyoucan, sorry we haven't followed up on this yet. We've been pulled in a lot different directions 😀

Just wondering if you've made any progress here? (no problem if not)

**Comment by taxmeifyoucan** [comment]
I am going trough current info about wallets, verifying it and putting together this doc https://notes.ethereum.org/@MarioHavel/wallets_overview. It takes time to find all that information on wallets, help is much appreciated. @minimalsm @corwintines

**Comment by corwintines** [comment]
Hey @taxmeifyoucan! We are going to be looking at the wallets pages as part of the Q1 roadmap. Id be interested in chatting a bit about some of your thoughts for the wallets section of ethereum.org if you're interested. Updating the filters and listing criteria is on the list of things to do for this epic, and it seems like you have some ideas on some filters that would be potentially beneficial for users. Thanks for the suggestions!

**Comment by samajammin** [comment]
Is this complete @corwintines? I believe we solved as part of https://github.com/ethereum/ethereum-org-website/issues/6274 but LMK if I'm wrong.

**Comment by corwintines** [comment]
I would say we addressed this issue with the revamp. @taxmeifyoucan I'm going to close this issue now that https://github.com/ethereum/ethereum-org-website/issues/6274 has been finished. Please reopen another issue if you disagree :) Thanks again for this suggestion, it helped shape a lot in the redesign.
