### ISSUE TITLE
crypto.com app will not connect to shibaswap.com 

### ISSUE THREAD

**Issue by OCMM** [ethereum/ethereum-org-website#4346]
**Describe the bug**

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Smartphone (please complete the following information):**

- Browser: [e.g. stock browser, safari]
- Version: [e.g. 22]

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey :) this repo is for the [ethereum.org](https://ethereum.org) website. You'll have to contact the support team at crypto.com to resolve this.
