### ISSUE TITLE
Adding the term "Asset" to the glossary

### ISSUE THREAD

**Issue by BenOfTheBlockchain** [ethereum/ethereum-org-website#4350]
**Checklist**

- [y] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [y] This term/definition is not a product advertisement or contain other promotional content
- [y] This term/definition is directly relevant to Ethereum

**Term Name:**

Asset (Crypto Asset)

**Term Definition:**

An asset refers to any type of decentralized [Token](https://ethereum.org/en/developers/docs/standards/tokens/#top), such as ETH or a NFT.

**Sources, if any (please do not submit copywrited content without appropriate approval):**

[https://www.investopedia.com/terms/c/cryptocurrency.asp#:~:text=A%20cryptocurrency%20is%20a%20form,of%20governments%20and%20central%20authorities.](https://www.investopedia.com/terms/c/cryptocurrency.asp#:~:text=A%20cryptocurrency%20is%20a%20form,of%20governments%20and%20central%20authorities.)

**Ethereum.org links?**

[https://ethereum.org/en/developers/docs/standards/tokens/#top](https://ethereum.org/en/developers/docs/standards/tokens/#top)

**Additional context**

I think that while this is a basic term, it could still have a place in the glossary.

**Comment by MrBrain295** [comment]
I could work on this.

**Comment by BenOfTheBlockchain** [comment]
> I could work on this.

Thank you!

**Comment by minimalsm** [comment]
Checking out our [glossary listing template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2C+content+%3Afountain_pen%3A&template=suggest_glossary_term.md&title=) for criteria and I don't think this is a term we want to add the glossary. 

Specifically I don't think the **term/definition is directly relevant to Ethereum**.

It also quite an abstract concept with different meanings [depending on the context](https://learn.robinhood.com/articles/2J2eZzikqesIXe1K7tPJqo/what-is-an-asset/).
