### ISSUE TITLE
Writing an NFT Collectible Smart Contract

### ISSUE THREAD

**Issue by rounakbanik** [ethereum/ethereum-org-website#4361]
We'll consider [our article policy](https://ethereum.org/en/contributing/adding-articles/) when reviewing the tutorial, so please take a look there first.

**Tutorial title**

Writing an NFT Collectible Smart Contract

**Tutorial description**

Use Solidity, Hardhat, and OpenZeppelin to write and deploy a smart contract that allows people to mint NFTs from a custom collection of generative artwork. 

**Tag your tutorial**

Solidity, Hardhat, Alchemy, ERC-721, NFTs, OpenZeppelin, Smart Contracts, Etherscan

**Publication**

[https://medium.com/scrappy-squirrels/tutorial-writing-an-nft-collectible-smart-contract-9c7e235e96da](https://medium.com/scrappy-squirrels/tutorial-writing-an-nft-collectible-smart-contract-9c7e235e96da)

**Skill level**

Intermediate

**Hosted on Ethereum.org or hosted elsewhere?**

Hosted on [https://medium.com/scrappy-squirrels](https://medium.com/scrappy-squirrels).

**For tutorials hosted elsewhere: URL to tutorial**

[https://medium.com/scrappy-squirrels/tutorial-writing-an-nft-collectible-smart-contract-9c7e235e96da](https://medium.com/scrappy-squirrels/tutorial-writing-an-nft-collectible-smart-contract-9c7e235e96da)

**Comment by shryasss** [comment]
I'll take this up🙋

**Comment by rounakbanik** [comment]
@shryasss Thank you! Not sure how this works but do let me know if you need anything from my side.

**Comment by villarode** [comment]
Hi, I know this has been discussed before but nowhere did I get a definitive answer what exactly should be done with versions 0.8.0 and above(

I am creating a smart contract for my nfts following a rather standard set of documentation:

https://ethereum.org/ru/developers/tutorials/how-to-write-and-deploy-an-nft/

I am getting this message, apparently the _setTokenURI function is gone on pragmas >0.8.0:

$ npx hardhat compile
Compiling 21 files with 0.8.0
DeclarationError: Undeclared identifier.
--> contracts/Villa_Rode_AL_OS721_Ropsten.sol:25:9:
|
25 | _setTokenURI(newItemId, tokenURI);
| ^^^^^^^^^^^^
Error HH600: Compilation failed

What do I replace _setTokenURI with so I get the same output?) Many thanks in advance!)

**Comment by rounakbanik** [comment]
@villarode I don't think this is relevant to this issue. The tutorial that you are referring to was published by Alchemy. I suggest you ask this question on their Discord.

**Comment by minimalsm** [comment]
Hey @rounakbanik 👋 sorry for not being able to review this sooner. At the moment we're swamped trying to keep up on [our Q4 roadmap](https://github.com/ethereum/ethereum-org-website/issues/4215). I'll try to take some time out of hours to review this in the next week. ❤️

**Comment by rounakbanik** [comment]
@minimalsm Thank you so much! Look forward to it. :)

**Comment by villarode** [comment]
Please keep me posted as well lads) Cheers

**Comment by minimalsm** [comment]
Unfortunately, due to the existing wealth of internal resources we have on NFTs already, we don't believe adding this adds anything novel to the tutorials and might just paralyse users with choices or confuse them further, ([as per our listing policy](https://ethereum.org/en/contributing/adding-products/)). Sorry again for the delay in reviewing this.
