### ISSUE TITLE
Proof-of-Stake not used consistently

### ISSUE THREAD

**Issue by lightclient** [ethereum/ethereum-org-website#4374]
`proof-of-stake` in some places, `proof of stake` in others

https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/

**Comment by vluna** [comment]
I can update to `proof-of-stake` where required.

**Comment by lightclient** [comment]
How do y'all make style decisions? It doesn't seem like there is a canonical definition - but I did notice that Wikipedia does `proof of stake` and `proof of work` rather than the hyphenated version.

**Comment by vluna** [comment]
I the decision was made and then standardized in the [style guide](https://ethereum.org/en/contributing/style-guide/#proof-of).

**Comment by lightclient** [comment]
Oh cool! Thanks for that link. I think the EIP repo should adopt it.

**Comment by minimalsm** [comment]
Hey @vluna. I've assigned you to this issue :-)

**Comment by vluna** [comment]
@minimalsm Thanks, will get to it today! Just a couple of things. This seems to be an issue across multiple pages, including translations.
- Would I need to update all of the ones that start with _Proof of [whatever]_ -> _Proof-of-[whatever]_, including translation pages? Or, should I just focus on the English ones?
- There are a few links to resources and articles that are titles, i.e. _Proof of Stake versus Proof of Work_ or _On the Security and Performance of Proof of Work Blockchains_. Should these ones be updated as well?
- Or should I stick to this page for now?

**Comment by corwintines** [comment]
I think in the instance of article titles, we should preserve what they are as we were not the authors. For the main content on the page, we should catch all of those in this PR. Let me know if you have any questions or need a hand @vluna :)

**Comment by minimalsm** [comment]
Closed in #4393
