### ISSUE TITLE
Fix typo on Development documentation page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#4389]
**Describe the bug**

The word 'vulnerabilitie' is missing an 's' at the end.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/#ethereum-stack
2. Scroll down to Security
3. See error

**Expected behavior**

Correct spelling is vulnerabilities.

**Screenshots**

![Typo](https://user-images.githubusercontent.com/37338979/140430712-9a379566-6787-4c4b-993b-d68a41a1f59a.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 95.0.4638.69

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by lidianycs** [comment]
I could work on that!

**Comment by corwintines** [comment]
I think @samajammin caught this in https://github.com/ethereum/ethereum-org-website/pull/4383

**Comment by lidianycs** [comment]
> I think @samajammin caught this in #4383

That's ok

**Comment by lukassim** [comment]
Ok, thanks @corwintines

**Comment by iusamahub** [comment]
Hey I can work on that!
