### ISSUE TITLE
NFT page says merge is happening in 2021

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4392]
**Describe the bug**

The NFT page still says the merge might happen in 2021. This is absolutely not the case. We should update this to state 2022.

**To Reproduce**

1. Go to 'https://ethereum.org/en/nft/'
2. Scroll down to 'Timelines heading'
3. See error

**Screenshots**

<img width="790" alt="Screenshot 2021-11-05 at 09 49 56" src="https://user-images.githubusercontent.com/62268199/140492376-aea3364a-c2dd-4c35-9011-e8fcd7ce19d4.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by sakshamgurbhele** [comment]
Hi @minimalsm, I am interested in this issue. Let me know if I can work.

**Comment by minimalsm** [comment]
@sakshamgurbhele thanks for helping ☺️ assigned.
