### ISSUE TITLE
Duplicate footer link

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#4400]
**Describe the bug**

2 footer links to /developers

**To Reproduce**

1. Scroll down to footer
2. See error

**Expected behavior**

Should only be 1!

**Screenshots**
![image](https://user-images.githubusercontent.com/8097623/140565051-37c93a4e-bd35-4654-b08b-b5943c557ce1.png)

**Additional context**

Thanks Scott_1UP for pointing out! https://discord.com/channels/714888181740339261/727898649006309377/903992268896227378

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
@minimalsm do you know Scott_1UP's GH handle? Please add him for bug reports 🐛

**Comment by minimalsm** [comment]
@all-contributors please add @Scott1UP for bugs
