### ISSUE TITLE
How to pass an NFT linked to a physical product as proof of ownership to somebody that is not on the chain 

### ISSUE THREAD

**Issue by stefanrusen** [ethereum/ethereum-org-website#4412]
**Is your feature request related to a problem? Please describe.**
I have minted an NFT on opensea linked to a physical work of art - painting. As I am selling this painting I want to pass the NFT to the new owner but they are not active on the platform. How do I state that ownership has passed? 

**Describe the solution you'd like**

  the work of art can be sold either in real-world or on NFT marketplace. There should be an agnostic solution to mark that ownership has changed. 

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @stefanrusen this is the repo for ethereum.org the website. We aren't able to provide OpenSea support, please [contact them directly](https://support.opensea.io/hc/en-us).
