### ISSUE TITLE
Iiccoinsss 

### ISSUE THREAD

**Issue by Jaysonmaldx** [ethereum/ethereum-org-website#4415]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Jaysonmaldx** [comment]
Hi

**Comment by minimalsm** [comment]
Hey @Jaysonmaldx not sure if you meant to leave a blank issue here? Feel free to reopen with the correct info.
