### ISSUE TITLE
Add skip navigation link to ethereum.org

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4425]
**Is your feature request related to a problem? Please describe.**

We don't have any way to skip over our navigation links for users using screen readers.

**Describe the solution you'd like**

Add a 'Skip to main content' link 

**Additional context**

- https://webaim.org/techniques/skipnav/
- https://www.youtube.com/watch?v=UnEItq289lU
- Good example of an accessible skiplink - https://www.gov.uk/ (access page, press tab and notice skip link, hit enter to skip to main content)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by il3ven** [comment]
I'd like to work on this. I am assuming we don't have add this link on each page. It makes sense for pages such as documentation. In documentation it will skip to the last edit link.

Inspired by the https://www.gov.uk/ website. I have this design in mind.

![image](https://user-images.githubusercontent.com/4337699/141357864-b58d52bd-9f97-43f7-8621-4a2f5b964cb2.png)

**Comment by minimalsm** [comment]
Hey @il3ven. Thanks for offering to work on this. I've assigned you 💪

No, this would be on every page. The idea of a skip link is so that users of screenreaders don't have to tab through every single item in the navigation to get to the main content of the site. It should skip to the main content (usually an`article` html tag) of the page. This would typically be a H1 though for the developer docs this would likely be the sidebar navigation.
