### ISSUE TITLE
Low contrast date range selector

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4426]
**Describe the bug**

The date selector on our Ethereum today statistics component (StatsBoxGrid) is below the recommended 4.5:1 contrast ratio to be considered accessible to those with low vision.

**To Reproduce**

1. Go to 'https://ethereum.org/en/'
2. Scroll down to 'Ethereum today'
3. See error

**Expected behavior**

Contrast between background color and text should score **at least** 4.5:1 to be pass basic accessibility test - https://webaim.org/resources/contrastchecker/

**Screenshots**

<img width="877" alt="Screenshot 2021-11-08 at 15 42 21" src="https://user-images.githubusercontent.com/62268199/140772770-7a134a6d-a048-46dd-b6a4-7f6700e01629.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by JulienMaurice** [comment]
Hello !

I suggest putting a background-color "greyish"

If you want I can do it.

**Comment by minimalsm** [comment]
Hey @JulienMaurice thanks for offering to help on this. 

I think we want to be mindful of two things here:

1. The existing Ethereum.org design system
2. Contrast

For the first concern I don't think we want to just select a random colour and call it a day. It should feel cohesive with the existing design. Feel free to browse the site and find inspiration that you think might fit.

E.g. this uses the same colours as the current primary button (IMO this don't think it looks great used here but passes accessibility)

<img width="635" alt="Screenshot 2021-11-10 at 16 02 13" src="https://user-images.githubusercontent.com/62268199/141148643-65ef506a-dc33-45da-b42c-7179bcdf551d.png">

As for the second concern: the current text is white. White text on a grey background is definitely going to struggle to adequately meet contrast requirements.

As I said, feel free to play around and make suggestions ☺️ Picking the right colors to use here is 80% of the issue here.

**Comment by JulienMaurice** [comment]
Hey @minimalsm 
I took a look at the differents colors from `theme.js`
I choosed `homeBoxPurple`, to have the option to switch from darkmode to lightmode too.

->_`/src/components/StatsBoxGrid.js`_
```js 
const ButtonToggle = styled(Button)`
  ${({ active, theme }) =>
    active &&
    `
    background-color: ${theme.colors.homeBoxPurple};
    opacity: 1;
  `}
`
```

[![Image from Gyazo](https://i.gyazo.com/e80b5b36f22e9b8a1d1918569529f136.gif)](https://gyazo.com/e80b5b36f22e9b8a1d1918569529f136)
Contrast 10.45 in lightmode
Contrast 14.13 in darkmode

What do you think ?
