### ISSUE TITLE
Add Aleth to deprecated software page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#4432]
**Is your feature request related to a problem? Please describe.**

Similar to Parity (https://ethereum.org/en/deprecated-software/#parity) this client is no longer maintained:
https://github.com/ethereum/aleth

**Describe the solution you'd like**

Add section similar to Parity: https://ethereum.org/en/deprecated-software/#parity

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by karelnagel** [comment]
I can also help with this one 😀

**Comment by sakshamgurbhele** [comment]
@samajammin I am Interested, I would love to take this issue

**Comment by samajammin** [comment]
Closed in #4461 - thanks @cameronfink!

Sorry for missing your comment @sakshamgurbhele - we appreciate you volunteering! Feel free to ping @minimalsm next time around. He's more on top of GitHub notifications than I am 😅.
