### ISSUE TITLE
Add Ethereum Studio to deprecated software page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#4433]
**Is your feature request related to a problem? Please describe.**

https://ethereum.org/en/studio/

**Describe the solution you'd like**

Add content from [this page](https://ethereum.org/en/studio/) to the [deprecated software page](https://ethereum.org/en/deprecated-software/).

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by karelnagel** [comment]
Hi! I can help with this

**Comment by sakshamgurbhele** [comment]
Hi @samajammin, I would like to work on this issue

**Comment by bgillcode** [comment]
This has now been done and merged in. Pull request: https://github.com/ethereum/ethereum-org-website/pull/4448

**Comment by samajammin** [comment]
Solved in #4448 - thanks @bgillcode!

@minimalsm please check to ensure issues get closed out after PRs are merges 😉
