### ISSUE TITLE
Add the original Ethereum philosophy to the website

### ISSUE THREAD

**Issue by rmeissner** [ethereum/ethereum-org-website#4435]
**Is your feature request related to a problem? Please describe.**

With the revert of the Whitepaper to its original version in https://github.com/ethereum/ethereum-org-website/pull/4246 the Philosophy section was removed. 

**Describe the solution you'd like**

Have a new separate section on the website for the Ethereum Philosophy

**Additional context**

I found the philosophy section very inspiring and was surprised that it was removed without any additional notice or update in a release.

**Comment by minimalsm** [comment]
Hey @rmeissner. We reverted the Whitepaper back to its original state at the time of Ether token sale [(see here)](https://github.com/ethereum/wiki/wiki/White-Paper/502e0e01355a42c8e6f5463c49cce496ae423179). Whilst I agree that it was a nice, inspiring addition to the Whitepaper, the philosophy section was not in the Whitepaper at that time.

**Comment by rmeissner** [comment]
Yes, I am aware, therefore I proposed to add it as a separate section to the website (not to the whitepaper)

**Comment by minimalsm** [comment]
@rmeissner Ah, misunderstood you. Anywhere you'd like to see this living in particular?

**Comment by rmeissner** [comment]
For me it would make sense under Community] (or Ethereum Community). 
![image](https://user-images.githubusercontent.com/2896048/141263125-f0aabda6-503e-4f67-af85-9d777ac6b994.png)


On the original website it was on the front page (https://web.archive.org/web/20140208030136/http://www.ethereum.org/) but I wouldn't go that far :D

**Comment by minimalsm** [comment]
I personally don't think having its own page makes sense. Curious to receive other input on this.

We're currently working on the ETH2 rebrand (more on that soon in our Q1 roadmap). Maybe adding this to the general Ethereum vision page we plan on creating makes sense? 

I'd say blocked for now until we at least release V1 of the rebrand but open to alternative ideas.

**Comment by wackerow** [comment]
<img width="1296" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/75d8eb01-ab7e-471f-b1bf-01d9e51cd835">

Hm, circling back, not sure about this one... I agree we should keep the whitepaper as-is. I think this content could maybe fit in the [Vision](https://ethereum.org/en/roadmap/vision) page, which is already similarly themed around the principles that surround Ethereum's roadmap/vision/future/(philosophy).

That's really the only place I can think of that would be fitting for this kind of content... the other question is are these elements still fully relevant to Ethereum in present-day. "Simplicity" may be getting to be a little bit of a stretch as network upgrades have progressed, but wording will be everything.

@rmeissner Would this be something you're interested in working on? Removed the stale tag and will make this attempt to resurface in the meantime... if no interest, we can close this out.

**Comment by konopkja** [comment]
This seems abandoned. I think the idea of communicating guiding principles for ethereum is important and there are several places on the website where these topics are discussed.

There could be more done on this topic, but since community member has step up I am closing the ticket and inviting anyone to create a new with a more refined proposal.
