### ISSUE TITLE
External Link to makerdao.world is broken

### ISSUE THREAD

**Issue by nlarche** [ethereum/ethereum-org-website#4453]
the link to makerdao.world in stablecoins section is broken

**To Reproduce**

1. Go to 'https://ethereum.org/en/stablecoins/#explore'
2. Click on 'Earn'
3. Click on 'MarkeDao community'
4. the link goes to 404 page

**Expected behavior**

- goes to the right page
- or MarkeDao community might  not  exist anymore

**Screenshots**
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/3041222/141540328-014b5738-9d08-4862-ba57-6b19950aeca0.png">

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/3041222/141540365-a1c96f64-a3af-453c-b798-67d9e4e7575d.png">

**Comment by byoriolserra** [comment]
Hello. Should the link go to MakerDAO Community's main page, or to a specific subsection?

**Comment by nlarche** [comment]
I think it's link to this [issue](https://github.com/makerdao/community/issues/1558)

**Comment by cameronfink** [comment]
[Here](https://makerdao.world/en/) is the community home page, not the "get started" page.

If you go back to January 2021 on archive.org and enter the page linked to on ethereum.org, it pulls up a page that is most similar to this page now: https://makerdao.world/en/resources/. I think this is the page it should be linked to.

**Comment by cameronfink** [comment]
> [Here](https://makerdao.world/en/) is the community home page, not the "get started" page.
> 
> If you go back to January 2021 on archive.org and enter the page linked to on ethereum.org, it pulls up a page that is most similar to this page now: https://makerdao.world/en/resources/. I think this is the page it should be linked to.

Compare this page: https://web.archive.org/web/20210122201652/https://community-development.makerdao.com/en/contribute/ to this page: https://makerdao.world/en/resources/

**Comment by byoriolserra** [comment]
@cameronfink thank you for checking the archive, I didn't even think about it. I agree, the resources page looks the most similar to the one linked back in January. Can I take the issue? 😄

**Comment by cameronfink** [comment]
@byoriolserra You take it! I was trying to figure out how to fix it anyway and couldn't, so -

Happy I could help find the link though!

**Comment by minimalsm** [comment]
Thanks for the input on this everyone!

**Comment by minimalsm** [comment]
@all-contributors please add @cameronfink for ideas

**Comment by minimalsm** [comment]
@all-contributors please add @nlarche for bug report
