### ISSUE TITLE
Add Wazirx exchange

### ISSUE THREAD

**Issue by anvats** [ethereum/ethereum-org-website#4459]
Wazirx is one of the biggest exchanges in India. Wazirx also claims that it stores 95% of funds offline to protect them from hacking activities.

**Comment by vj-codes** [comment]
@minimalsm hey being from India and personally using the exchange I think the issue is valid and can I work on it please?

**Comment by minimalsm** [comment]
@vj-codes thanks but unfortunately but we don't have the infrastructure set up to allow contributors to do this yet, there is a required documentation step first that is currently entirely internal.

**Comment by nareshprajapat** [comment]
Great Approach :)
