### ISSUE TITLE
Unwanted overscrolling on mobile navigation

### ISSUE THREAD

**Issue by Longju000** [ethereum/ethereum-org-website#4463]
**Describe the bug**
When you scroll on the menu button.
![IMG_20211115_100023](https://user-images.githubusercontent.com/71775965/141722873-04dda3d5-8137-4315-b20e-867006b357c1.jpg)

**Comment by minimalsm** [comment]
Hey @Longju000! Thanks for reporting ☺️ 

Could you let us know what device and browser you are using so we can try to replicate this 😬?

**Comment by Longju000** [comment]
Browser: Google Chrome
Movbile Device: Xiaomi Redmi

**Comment by vluna** [comment]
@minimalsm I can take a look at it.

**Comment by minimalsm** [comment]
Hey @vluna thanks for offering to help. I've assigned you to this 😬

**Comment by Longju000** [comment]
Should I try too??

**Comment by vluna** [comment]
@Longju000 sure, we can work on it together!

@minimalsm trying to fix this issue but I am struggling a bit. I believe the issue has to do with the address bar on chrome mobile.

Current steps to reproduce:
- Open ethereum.org on mobile
- Open navigation, make sure the address bar is visible
- Scroll all the way to the bottom in the menu, while the address bar is visible.
- Once you are at the bottom, scroll up without taking your finger out of the screen
- At this point you should see that the bottom nav scrolls up and the content behind is visible (see screenshot on issue)

I am assuming that this could cause a glitch where the menu does not move back to the bottom causing this issue. I see this seems to be a theme across the web and some solutions are suggested. I just have not been able to properly make it work. Will keep trying and hopefully I will have it done soon.

**Comment by Longju000** [comment]
@vluna  sure sure will try from my side too

**Comment by vluna** [comment]
@minimalsm found a solution and opened PR #4528. Let me know if that works 🙂

**Comment by Longju000** [comment]
I'm trying from my side but still not able to fix it
Do share the code later on 😁

**Comment by minimalsm** [comment]
@Longju000 this should be fixed now! Not live on the official site yet. It should be deployed later but please feel free to test https://deploy-preview-4528--ethereumorg.netlify.app/en/ and confirm it works for you). 

Thanks @vluna for solving this for us 🎉
