### ISSUE TITLE
Update Oracles Documentation Page

### ISSUE THREAD

**Issue by andrejrakic** [ethereum/ethereum-org-website#4477]
In the Oracle Section of the Documentation Page there is no explanation nor example of using Chainlink Keepers. I would like to open a PR and work on this issue.

**Product name:** 
Chainlink Keepers

**Product description:**
Smart contracts alone can't trigger or initiate their own functions at arbitrary times or under arbitrary conditions. State change will only occur when a transaction is initiated by another account (such as user, oracle, or contract). To resolve this issue, The Chainlink Keeper Network provides options for smart contracts to outsource regular maintenance tasks in a trust minimized & decentralized manner. 

**How long has it been around?**
Open Beta was released in March 2021 and the product itself is live on Mainnet for more than three months, according to [official announcement](https://blog.chain.link/chainlink-keepers-is-now-live-on-mainnet/)

**Where do you think it should go?**
In my opinion, it should be in the [Oracle Section](https://ethereum.org/en/developers/docs/oracles/) of the Documentation Page, with other examples of Chainlink services

**GitHub URL**
https://github.com/smartcontractkit/chainlink

**Docs URL**
https://docs.chain.link/docs/chainlink-keepers/introduction/

**Is the product open source?**
Yes, and it is available at https://keepers.chain.link/

**Comment by minimalsm** [comment]
Hey @andrejrakic thanks for raising this issue 🤝

I'm not familiar with Chainlink keepers but I agree having more information about automating the execution of smart contracts is a great idea! 

Open to input here but I'm not sold that the Oracles developer docs is the best place for this to live. Are keepers technically oracles? Do you think this content living alongside [smart contracts](https://ethereum.org/en/developers/docs/smart-contracts/) makes sense?

**Comment by andrejrakic** [comment]
Yes, I am sure that they are oracles. Technically, oracles either provide external data or do external computation/automation. In my opinion, Keepers are an example of the second one.

Glad you opened this discussion! As I see it, after the Oracles section, the second-best place for Keepers is the Smart Contracts section for sure, but I am curious what the community thinks. Maybe @PatrickAlphaC has something to add as an oracle expert.

**Comment by PatrickAlphaC** [comment]
I echo @andrejrakic's points here! To me this makes a lot of sense!

Perhaps we could point to the keepers page in the smart contracts page too if that is what you'd like, to help users do decentralized event-driven automation.

**Comment by minimalsm** [comment]
Okay, you've convinced me—I think it living in the Oracles developer docs is good. Finding a home for it in the current smart contract pages probably isn't a bad idea either. 

The team are pretty swamped trying to get through our Q4 work and don't have the capacity to take this on yet but feel free to open a PR if you want to expedite this 😊 

@andrejrakic @PatrickAlphaC

**Comment by andrejrakic** [comment]
Deal, I will open a PR then 🤝

**Comment by samajammin** [comment]
Thanks for raising this issue @andrejrakic!

I agree the Oracles page is a solid spot for this, at least for now until the terminology, resources & projects around keepers continues to expand. It may eventually make sense to have a dedicated page for this topic.

One request here would be to also research & add any other keeper projects that exist in the ecosystem, so it's not too Chainlink-centric. I think describing the concept of keepers in a generic way, then listing the available projects that cover this problem space would be a good way to go to keep things credibly neutral. e.g. I know the Keep3r Network is a popular one within the yearn ecosystem: https://docs.keep3r.network/

**Comment by andrejrakic** [comment]
Thanks for the comment @samajammin that makes sense. I will do some extra research but I must say that I've never used Keep3r Network before. Since I am not an Keep3r expert I propose to open a PR with example for usage of Chainlink Keepers and list Keep3r Network as an alternative
