### ISSUE TITLE
Add the ZK Hack to the upcoming events section

### ISSUE THREAD

**Issue by womensrights** [ethereum/ethereum-org-website#4497]
happy to be assigned the issue :)

**Comment by minimalsm** [comment]
@womensrights all yours 😀 

[This example PR](https://github.com/ethereum/ethereum-org-website/pull/4428) of adding an event might be helpful if you need a reference point.  feel free to ping if you need anything ✌️

**Comment by samajammin** [comment]
Solved in #4498 - thanks @womensrights!
