### ISSUE TITLE
Standardise colour format to hex codes

### ISSUE THREAD

**Issue by seekingtau** [ethereum/ethereum-org-website#4504]
Not sure if this has been considered in the past, but just wanted to bring up a discussion over switching to hex codes rather than RGB codes - RGB must be converted to hex before it gets displayed anyway, which can lead to some small issues (that colours may appear inaccurately).

Besides, I do think that hex codes are more standard/easier.

Regardless, it is a bit of a nit-picky dev thing that might ultimately be more trouble than it is worth. Just wanted to bring it up in case anyone had thoughts on it.

**Comment by lemiesz** [comment]
> which can lead to some small issues (that colours may appear inaccurately). 

Do you have example of there this could happen.   

>  Besides, I do think that hex codes are more standard/easier. 

I tend to agree however I will provide one counterpoint. In the case of applying a Alpha channel. 

```
rgba(1, 25, 53, .1)  
```

Writing the alpha channel as a decimal opacity value is a bit more clear than using HEX to represent the opacity. Although this is highly based on my personal opinion. I wonder what others think

**Comment by minimalsm** [comment]
Thanks for the suggestion @cameronfink 

@lemiesz no strong feelings but I prefer explicitly declaring the colours being used instead of using opacity to achieve a colour.  E.g. adding opacity via rgba can cause problems where your design system is WCAG compliant on paper, but in the browser it isn't. 

Curious to hear other thoughts on this @corwintines @wackerow

**Comment by minimalsm** [comment]
Thanks for the suggestion @seekingtau . Discussed with the team and we're happy to use HEX across the codebase.

For consistency's sake we should:

- use uppercase HEX (i.e. use `#FFFFFF`, not `#ffffff`)
- use 8-digit HEX notation when alpha/opacity is required

Is this something you'd be interested in working on @seekingtau?

**Comment by brokenprogrammer** [comment]
@minimalsm I would like to claim this issue. 

I noticed most colors are defined in theme.js but there is also a few in other places such as layout.css and I have not yet investigated any components but I'm guessing we change to hex there as well.

A question for you is if I should change only the `rgb` and `rgba` occurences or if I should worry about others as well such as `hsla` or `mix` ?

**Comment by minimalsm** [comment]
Thanks for offering to help @brokenprogrammer. I've assigned you. 

We'd like to use HEX across the entire codebase for consistency.

**Comment by brokenprogrammer** [comment]
@minimalsm Just for clarification does that include removing the use of the `polished` npm package referenced in: https://github.com/ethereum/ethereum-org-website/blob/dev/src/theme.js#L2 ?

**Comment by AnmolBansalDEV** [comment]
does this issue still need resolution?

**Comment by samajammin** [comment]
I don't have a super strong opinion here. I agree consistency in the codebase is always worth striving for but I'm not sure it's always worth it if it comes at the cost of legibility. e.g. as others have pointed out, when using the alpha channel / opacity it's easier to read & reason about with the `rgba` format (at least for me). Also we do use some packages, like the `mix` utility from the `polished` package as @brokenprogrammer called out, which makes it easy to create a spectrum across brand color palettes - much easier to read vs. HEX in my opinion.

> RGB must be converted to hex before it gets displayed anyway, which can lead to some small issues (that colours may appear inaccurately).

@seekingtau I would be curious if you can cite any examples of this. I think this would be a good case to go with HEX.
