### ISSUE TITLE
Intro to Ethereum developer docs: it is not obvious that ETH === ether

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4509]
**Describe the bug**

The Intro to Ethereum developer docs does not make it obvious that ether and ETH are the same thing. 

The 'what is ether' section does not mention ETH. And, the 'ETH' section makes the assumption that users know that ether is ETH without explicitly stating it anywhere previously.

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/intro-to-ethereum/#what-is-ether'
2. See error

**Expected behavior**

It should be obvious that when we define ether, we are also defining ETH.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by phyBrackets** [comment]
Hey , I'm interested in this . Can you assign it to me ? And can you please explain briefly that what actually need to be done , what i understood it that we need to define ETH with Ether definition right?

**Comment by vishvanathan-k** [comment]
Wups.... wrong mention 😅
