### ISSUE TITLE
Incorrect K value in Tutorials/Uniswap V2

### ISSUE THREAD

**Issue by eulerbeat** [ethereum/ethereum-org-website#4512]
Should this be 256 instead of 1024?

https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/tutorials/uniswap-v2-annotated-code/index.md#mint

![Screen Shot 2021-11-22 at 10 06 50 AM](https://user-images.githubusercontent.com/52531715/142885251-8b434322-81e7-4447-873b-3539eaf67d42.png)

**Comment by qbzzt** [comment]
Oops, thank you for noticing. 

I submitted a PR to fix it: https://github.com/ethereum/ethereum-org-website/pull/4524

**Comment by minimalsm** [comment]
Closed by #4524 

Thanks for reporting @eulerbeat

**Comment by minimalsm** [comment]
@all-contributors please add @eulerbeat for bug report
