### ISSUE TITLE
Add 'Access to Ethereum Layer 2' to the Find a Wallet page

### ISSUE THREAD

**Issue by milvinae** [ethereum/ethereum-org-website#4520]
**Is your feature request related to a problem? Please describe.**

The use of Layer 2 technology is essential to scaling Ethereum and ensuring that users get a better experience with lower gas fees and faster transactions. Identifying which wallets have incorporated Layer 2 technology isn't always straightforward.

**Describe the solution you'd like**

I would like to see 'Layer 2 Integrated' as part of the 'Choose the wallet features you care about' section of ethereum.org.

**Describe alternatives you've considered**

This could be expanded to be solution specific, e.g. zkSync, Loopring, Polygon, Starkware.

**Want to contribute?**

Always happy to help.

**Comment by minimalsm** [comment]
Definitely like this idea (very topical!). I haven't investigated this but I'd assume the list would be quite small at least to begin with?

**Comment by milvinae** [comment]
Yes it would be quite a short list right now but would grow in the future.

These are the wallets I know of with Layer 2 Live or in beta/rumored. I'll have to dig deeper to see if there are more that I missed.

**Live:**

Loopring - Loopring
Rainbow - Optimism
Numio - zkSync
imToken - zkSync & Arbitrum
Trust Wallet - Arbitrum
Coin98 - Arbitrum
Coinbase Wallet - Arbitrum, & Optimism

**Beta:**

Argent - zkSync & Starkware
Rainbow - Arbitrum
Numio - Starkware
MyKey - zkSync

**Comment by taxmeifyoucan** [comment]
This is also part of #4338. I am working on researching wallet features including L2 support, thanks for listing these! @milvinae Here is features overview https://notes.ethereum.org/@MarioHavel/wallets_overview

**Comment by milvinae** [comment]
I'm happy to help with that if you need anything @taxmeifyoucan. I'll head over to #4338 and see what you have going on.

**Comment by lemiesz** [comment]
> This is also part of #4338. I am working on researching wallet features including L2 support, thanks for listing these! @milvinae Here is features overview https://notes.ethereum.org/@MarioHavel/wallets_overview

Awesome wallets_overview matrix. Once this is finalized would it be useful to add it as a extra link somewhere on the main docs?

**Comment by corwintines** [comment]
Hey @milvinae! Thanks for the suggestions. We are working on updating the wallets section of our site in Q1, and having L2 support is high on the list of filters in my mind. Happy to bring this filter in, and thanks for listing some wallets that fit the criteria as well!

**Comment by milvinae** [comment]
Hello @corwintines - thanks for the update

If it is any help I recently launched a zkRollup Directory over at [zkrollups.xyz](https://www.zkrollups.xyz/). It doesn't cover all L2s, just the zkRollups, but you may find it to be a useful data source.

For Arbitrum there is - https://portal.arbitrum.one/

and for Optimism - https://www.optimism.io/apps/wallets

Let me know if I can help in any way.

**Comment by corwintines** [comment]
I would say we addressed this issue with the revamp. @milvinae I'm going to close this issue now that https://github.com/ethereum/ethereum-org-website/issues/6274 has been finished. Please reopen another issue if you disagree :) Thanks again for this suggestion, it helped shape a lot in the redesign.
