### ISSUE TITLE
Update Lambda School

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#4526]
**Is your feature request related to a problem? Please describe.**

Our link to Lambda School:
https://lambdaschool.com/learn-blockchain-development

On this page:
https://ethereum.org/en/developers/learning-tools/

Now directs to:
https://www.bloomtech.com/courses/web3

**Describe the solution you'd like**

Let's update the title & logo on our page.

**Describe alternatives you've considered**

None.

**Additional context**
https://www.bloomtech.com/article/embracing-a-new-identity-as-bloom-institute-of-technology

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Solved in #4499
