### ISSUE TITLE
Add OpenEthereum to deprecated software list

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4530]
**Is your feature request related to a problem? Please describe.**

OpenEthereum [has been deprecated](https://medium.com/openethereum/gnosis-joins-erigon-formerly-turbo-geth-to-release-next-gen-ethereum-client-c6708dd06dd) and is no longer be maintained. We should add this information to our new [deprecated software page](https://ethereum.org/en/deprecated-software/).

**Describe the solution you'd like**

Add OpenEthereum to the [deprecated software page](https://ethereum.org/en/deprecated-software/) and update any references to OpenEthereum accordingly (example from this page: "_The successor project to Parity Ethereum client is Open Ethereum._").

**Additional context**

@taxmeifyoucan added a PR to make this change on the [nodes and clients page](https://ethereum.org/en/developers/docs/nodes-and-clients/) (#4525).

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by joneskj55** [comment]
@minimalsm I'd like to take this if possible.

**Comment by minimalsm** [comment]
All yours! @joneskj55

**Comment by masteraychen** [comment]
why would OpenEthereum be deprecated? Is there any problem that couldn't be solved?
Rust are in many ways better than golang....It's a shame not to have a Rust version of Ethereum...
