### ISSUE TITLE
Incorrect range for uint112 in Tutorials/Uniswap V2

### ISSUE THREAD

**Issue by eulerbeat** [ethereum/ethereum-org-website#4542]
https://ethereum.org/en/developers/tutorials/uniswap-v2-annotated-code/#FixedPoint

Should this be 2^112-1?

![Screen Shot 2021-11-25 at 3 38 09 AM](https://user-images.githubusercontent.com/52531715/143407632-d541df1e-5448-4ec2-8894-f87fb604e163.png)

**Comment by minimalsm** [comment]
Looks like it! @eulerbeat 

Would you like to sling a PR for this 😬?

**Comment by sanket-kogekar** [comment]
I would like to take this! @minimalsm

**Comment by mskalisz** [comment]
Has this issue been addressed? If not, I'd be happy to try to work on it! Thanks!

**Comment by Mocktic** [comment]
@minimalsm  I can work on this if possible. It's an easy fix!!!
