### ISSUE TITLE
More on tokens and their uses does not redirect

### ISSUE THREAD

**Issue by ShubhankarKG** [ethereum/ethereum-org-website#4544]
**Describe the bug**

On the [What is Ether ?](https://ethereum.org/en/eth/) Page, there is a subsection on More on tokens and their uses. All the uses mentioned are just elevated cards, which do nothing when clicked.

**To Reproduce**

1. Go to 'https://ethereum.org/en/eth/'
2. Scroll down to 'More on tokens and their uses'
3. Click on any card.

**Expected behavior**

The cards should be clickable and redirect to their respective URLs.

**Screenshots**

![image](https://user-images.githubusercontent.com/50791000/143453288-89cf223f-727c-4c7b-a83a-1423bceb0b9b.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Brave
- Version: V1.32.106

**Additional context**

There's a subsection just above that does the same.
![image](https://user-images.githubusercontent.com/50791000/143453490-ea0f049c-b56b-4583-9488-c349ab86addc.png)

**Want to contribute?**

Sure, once the issue is finalized, would be happy to help.

**Comment by minimalsm** [comment]
Hey @ShubhankarKG nice catch! 

Yeah, these cards should direct to the corresponding pages on the site. I've assigned you to know, let me know that you're happy to take on this issue and if you need any help. ☺️

At a quick glance, it looks like this issue can be sorted entirely by adding links to the `tokenLinks` array [here](https://github.com/ethereum/ethereum-org-website/blob/42463a54cfdf7218aec15806e19e7de5b5bcdc92/src/pages-conditional/eth.js#L222).

**Comment by minimalsm** [comment]
@all-contributors please add @ShubhankarKG for bug reports

**Comment by ShubhankarKG** [comment]
I'll put up the PR in some time. Thanks!
