### ISSUE TITLE
Headers covered by nav on ETH2 template when using header-ids in the url

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4547]
**Describe the bug**

When using a URL to directly access a header using a header-ID (i.e. `https://ethereum.org/en/eth2/beacon-chain/#beacon-chain-features`) the navigation bar covers the header.

**To Reproduce**

1. Go to 'https://ethereum.org/en/eth2/beacon-chain/'
2. Click on a header-ID chain link or a sidenav link
3. See error

**Expected behavior**

The nav should not cover the heading

**Screenshots**

https://i.gyazo.com/9ff035d5579b47de06a44f701644e8b8.gif

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave Browser
- Version: v1.32

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@minimalsm since this is same issue as #4548, I can also update this one.

**Comment by minimalsm** [comment]
Fixed in #4561
