### ISSUE TITLE
Headers covered by nav on usecases template when using header-ids in the url

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4548]
**Describe the bug**

When using a URL to directly access a header using a header-ID (i.e. `https://ethereum.org/en/defi/#defi-vs-tradfi`) the navigation bar covers the header.

**To Reproduce**

1. Go to 'https://ethereum.org/en/eth2/beacon-chain/'
2. Click on a header-ID chain link or a sidenav link
3. See error

**Expected behavior**

The nav should not cover the heading

**Screenshots**

https://i.gyazo.com/9ff035d5579b47de06a44f701644e8b8.gif

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave Browser
- Version: v1.32

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@minimalsm I can help with this one 🙂

**Comment by vluna** [comment]
@minimalsm you can find the fix here #4561

**Comment by chiholiu10** [comment]
Already solved yet?

**Comment by minimalsm** [comment]
@chiholiu10 hey :-) 

@vluna is working on this currently in #4561
