### ISSUE TITLE
"State Transition System" illustration in ETH Whitepaper doesn't make sense

### ISSUE THREAD

**Issue by nwoodr94** [ethereum/ethereum-org-website#4560]
**Describe the bug**

The graphic illustrating the _state transition system_ idea in the Ethereum whitepaper doesn't make sense.

In the initial state, addresses `14c5f8ba`, `892bb91f`, and `4ad59065` have 0 tokens, where `7b53ab84` has 1 token, and `3ce6f712` has 2 tokens.

In the transaction segment, `7b53ab84` signs a transaction and spends 1 token, and `3ce6f712` signs and spends 2 tokens.
Also, address `bb75a980` is created, and, presumably, is the recipient of these 1, and 2 token transactions. 

In the final state, address `bb75a980` is represented three times, presumably once for each state, having had 0 tokens, then been the recipient of a 1 token, and 2 token transaction. The 0 token addresses `14c5f8ba`, `892bb91f`, and `4ad59065` are also represented in the final state, having been unchanged, but the addresses `7b53ab84` and `3ce6f712`, having been involved in the spending transactions, are not represented.

**It appears that the illustration conflates the system state, and the record of all transactions. The illustration should simply demonstrate that after the creation of, or transaction between addresses, the ledger and final balances should be updated accordingly. However, the final state depiction appears to show only a catalogue of addresses having a net token change >= 0. For example the `7b53ab84` and `3ce6f712` addresses are not represented in the final state depiction, but the `bb75a980` is represented once for each of its token receipts within the transaction period**

**To Reproduce**
The markdown is found [here](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/whitepaper/index.md#bitcoin-as-a-state-transition-system-bitcoin-as-a-state-transition-system)

**Expected behavior**
A **much** clearer illustration of the state transition system is to illustrate an initial state where five participants have a total of 3 bitcoin, and enter into a transaction period, where they send tokens to one another by signing and spending them. The final state should simply show that after the transactions are recorded, the final token balance of each participant in the system has been updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/46133948/143656761-96cd1ded-6a30-4a06-a638-61f71500d753.png)

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by phyBrackets** [comment]
Hey , here is my PR of solving this issue. https://github.com/ethereum/ethereum-org-website/pull/4565

**Comment by lemiesz** [comment]
So I see what you are saying,  and the way you are phrasing this is actually much clearer  as to the result of a transaction. However the whitepaper defines BTC state as 

> The "state" in Bitcoin is the collection of all coins (technically, "unspent transaction outputs" or UTXO) that have been minted and not yet spent, with each UTXO having a denomination and an owner (defined by a 20-byte address which is essentially a cryptographic public keyfn.  

In this case we have 3 transaction outputs 

```
bb7a980: 0 
bb7a980: 1
bb7a980: 2
``` 

So these are represented in the state as per the definition.  

Your interpretation is clearer as to the intent of the state transition, however im not sure if it is correct as to what actually happens in this kind of transaction. Maybe someone with more knowledge of BTC could chime in.

**Comment by minimalsm** [comment]
Hey @nwoodr94  @lemiesz @phyBrackets, thanks for weighing in on this.

We recently decided that we should not be making alterations to the Whitepaper. Instead, we will be maintaining it in its current form as a historical reference. [Please see this comment for more detail.](https://github.com/ethereum/ethereum-org-website/pull/4565#issuecomment-983522713)

**Comment by minimalsm** [comment]
@all-contributors please add @nwoodr94 for ideas

**Comment by nwoodr94** [comment]
Hey all, thanks for your help and feedback on this.

I'll just share my results for those who might appreciate a simpler, or otherwise alternative graphic in the future.

From the Ethereum whitepaper:
> From a technical standpoint, the ledger of a cryptocurrency such as Bitcoin can be thought of as a state transition system, where there is a "state" **_consisting of the ownership status of all existing bitcoins_** and a "state transition function" that takes **_a state and a transaction_** and **_outputs a new state_** which is the result.

I propose the below graphic, which illustrates this system and meets my needs.
![ethereum-state-transition-new](https://user-images.githubusercontent.com/46133948/144734715-87998cd5-21b8-4a0e-974a-ecd611279177.png)

Thanks to @phyBrackets for your earlier work on this and @lemiesz for checking my understanding.
