### ISSUE TITLE
We need to create unique P2P Physical for All Indian Increases of Uses  

### ISSUE THREAD

**Issue by nareshprajapat** [ethereum/ethereum-org-website#4563]
My Idea is - we need to Create a Platform for Everyone Use Eth Coin using A bar code and Scanner . then will be valuable in India.

Like : When One User want Payment , then Second User can easy to pay using Eth scanner . This is very gd way to run in india with general people.

**Comment by lemiesz** [comment]
Many wallets already support QR codes.  

Or are you thinking like traditional IR barcode scanners?

**Comment by minimalsm** [comment]
Hey @nareshprajapat, this repo is for discussion around ethereum.org only. Closing this out.
