### ISSUE TITLE
The website is not responsive on Ultrawide monitors

### ISSUE THREAD

**Issue by version0chiro** [ethereum/ethereum-org-website#4575]
**Describe the bug**
The website when accessed from an ultrawide monitor of ratio 21:9, centres itself to the middle instead of being responsive and expanding as other websites do. This can be seen as in the screenshots, the website is shown in form of a  16:10 and is centred.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Open the website in any ultrawide monitor with a ratio of 21:9

**Expected behaviour**

The expected behaviour should be responsiveness towards all the screen sizes and expanding the horizontal width of the website as per the display being used 

**Screenshots**
![image](https://user-images.githubusercontent.com/56084650/143864249-c9820a1f-c966-4878-bb00-450c524f75c0.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Brave
- Version: 1.32.113

**Want to contribute?**

If possible I would like to take up this issue myself

**Comment by chiholiu10** [comment]
What is the exact problem here?

**Comment by version0chiro** [comment]
The left out space on the sides looks really odd and would be better if the whole div fit into it rather than being at the center of it

**Comment by lemiesz** [comment]
This is not really a bug. Many website used the center rail approach, even on ultrawides, there are certain limits around optimal readability anyway.  

Text content should be max 800px for optimal readability, thought many go lower. This site explains it better than I could https://baymard.com/blog/line-length-readability. 

Some website will split the nav bar to stretch to the end of the screen, however that does not seem like a good experience here either.

**Comment by chiholiu10** [comment]
So what are we going to do here. Fix or ignore this issue?

**Comment by lemiesz** [comment]
Is there anyone that specifically owns he UX designs for the etherum website?  

To me it seems to be working as intended (at least from a utility standpoint). Take for example the Solona website displayed at ultra-wide resolution. 
<img width="3341" alt="image" src="https://user-images.githubusercontent.com/2940410/144143779-70bbc60c-30be-4b12-a764-befe0493a28a.png"> 

Yes indeed it does stretch out to fill the page. However the only content that stretches out is the decorative background elements. And one center breakout div. There main content div is still a center rail of similar size to the ethereum one.  

If we are concerned about the aesthetics of the website. We could consider adding some background accent elements, to fill the empty space a bit better. However I think the clean minimalist style is already working pretty well.

**Comment by ssaslavsky** [comment]
> The left out space on the sides looks really odd and would be better if the whole div fit into it rather than being at the center of it

No different from any other website, isn't it?

This is how I see this page in github:
![image](https://user-images.githubusercontent.com/37705943/144160583-52ba698e-8067-461b-bf74-c6bebc3ee1ba.png)

**Comment by lemiesz** [comment]
I guess GitHub does stretch out the top nav. Although that itself is a questionable choice

**Comment by minimalsm** [comment]
@version0chiro @ssaslavsky @lemiesz @chiholiu10 

Hey folks. This is a duplicate for #4026. Please read that issue for full context of the desired solution to this problem.

For context, we decided that stretching the site content indefinitely ([similar to the Solana website](https://github.com/ethereum/ethereum-org-website/issues/4575#issuecomment-983120088)) was a poor solution and unpleasant to use for those on ultra-wide monitors.

A better solution would be to give the appearance of a full-width page on XL screens whilst keeping the content relatively centred to allow for easy readability and navigability. 

![132911160-a1755683-567a-4f26-be82-a4d5fd5e93b5](https://user-images.githubusercontent.com/62268199/144429102-db5c0187-b7bd-4e47-b8f7-628d2f4788f7.png)

I'll leave this issue open temporarily to allow some further discussion but if anyone is interested in trying to fix this please comment in #4026.
