### ISSUE TITLE
Update nodes-as-a-service page

### ISSUE THREAD

**Issue by ddocs** [ethereum/ethereum-org-website#4592]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

Ankr Protocol 

**Product description:**

Ankr Protocol offers open access to a Public RPC API layer allowing anyone to connect to the Ethereum network.

Ankr Protocol provides reliable, load balanced access to node clusters from anywhere in the world. 

For developers, it is super easy to connect to a chain simply using the URL - https://rpc.ankr.com/<chain-name> without any of the complexity of running a node.

As a provider of node infrastructure, you can send traffic to the fast and reliable RPC network at times of peak demand and scare capacity. You can also allow others to use your idle node infrastructure capacity at times of low demand for you and earn rewards for doing so.

**How long has it been around?**

Ankr has been providing decentralized node services since 2017. 

**Where do you think it should go?**

https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/

**GitHub URL**

https://github.com/Ankr-network

**Docs URL**

https://docs.ankr.com/

**Is the product open source?**

free, open access 

**Additional context**

**Comment by ddocs** [comment]
I have read the listing policy for dev tools.

**Comment by minimalsm** [comment]
Closed by #4606 😀
