### ISSUE TITLE
Stablecoin page layout bug

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#4598]
**Describe the bug**
Horizontal scrolling is occurring at medium screen widths on the stablecoins page. Also noting a bug to the layout of CTA buttons in one of the cards on the same page at similar screen sizes.

**To Reproduce**

1. Go to https://ethereum.org/en/stablecoins/ on desktop
2. Scroll down to "Find a stablecoin" section
3. Reduce window width to around 1025px to 1125px
4. Notice cards start to extend off right side and horizontal scroll bar comes in
5. Also, scroll to "Use your stablecoins" callout, and notice two buttons are stacked and staggered without vertical padding.

**Expected behavior**
Cards should rearrange if too big for the window size. Buttons should rearrange to stacking vertically, with some padding between, and full width once this occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/144150466-deb39d50-a61e-480d-9df1-67b90cfffca5.png)
![image](https://user-images.githubusercontent.com/54227730/144150723-8d1e8804-dcf8-4bdf-b442-5efb57743a50.png)

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- Browser: Brave latest

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@minimalsm I can work on this if possible.

**Comment by minimalsm** [comment]
Feel free to take a crack at this @vluna. Assigned :-) As always, ping if you need any help/a second pair of eyes.

**Comment by vluna** [comment]
@minimalsm PR in here #4626, let me know if there are any changes.

**Comment by vluna** [comment]
@minimalsm My apologies, I completely disregard the second screenshot! I will fix it and open a new PR for it.

**Comment by vluna** [comment]
@minimalsm here is the PR with the fix for the second part #4667. Let me know if there are any issues.
