### ISSUE TITLE
Spelling mistake on the developers page

### ISSUE THREAD

**Issue by m-t-a97** [ethereum/ethereum-org-website#4608]
**Describe the bug**

On the developers page located at the URL `https://ethereum.org/en/developers`, the card with the "Contribute" button has a spelling mistake which is the word "opportunties".

**To Reproduce**

1. Go to [Ethereum Developer Resources](https://ethereum.org/en/developers)
2. Scroll down to the section that's titled "About these developer resources"
3. Look at the card with the "Contribute" button
4. You will see the spelling mistake -> "opportunties"

**Expected behavior**

The word "opportunties" should be corrected to "opportunities".

**Screenshots**

![image](https://user-images.githubusercontent.com/54685928/144326786-0cfeff52-6916-4661-87c6-520e7310af82.png)

**Desktop:**

- OS: Windows 11
- Browser: Brave Browser
- Version: Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by m-t-a97** [comment]
I would like to be assigned this issue. Thank you in advance.

**Comment by minimalsm** [comment]
Hey @m-t-a97,

I've assigned you to this. Feel free to open a PR :-) If you need any help getting set up, feel free to ping me.

**Comment by m-t-a97** [comment]
Thank you for assigning the issue to me. I have created a PR for it now.
