### ISSUE TITLE
Fix typo in Raspberry Pi node tutorial

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#4621]
**Describe the bug**

The ''How to turn your Raspberry Pi 4 into a node'' contains a typo.

**To Reproduce**

1. Go to (https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/#recommended-hardware-and-setup)
2. Scroll down to ''Recommended hardware and setup''
3. In the second line, ''MicroSD Card (16 GB Class 10 minimun)'' contains a typo

**Expected behavior**

''minimun'' should be ''minimum''.

**Screenshots**

![Minimun typo](https://user-images.githubusercontent.com/37338979/144464152-b4a97633-f3f7-4bf7-b73d-093ae070b5f1.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 96.0.4664.45

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by geoffhull03** [comment]
@lukassim Could you please assign me this one? I'm new to open-source contributing, but this one seems very doable 😄

**Comment by lukassim** [comment]
@geoffhull03 Sure, feel free to take a crack at this.
