### ISSUE TITLE
Add headers to all markdown files

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#4622]
**Describe the bug**

With update to how we support language translations (#4441) we now rely on markdown headers to determine if files are up to date or not.

We have some markdown pages that do not have any headers. They should - this is also best practices for SEO.

**To Reproduce**
1. Run `yarn build` on the project.
2. See `regex error` logs 

**Expected behavior**
We should receive any `regex error` logs

**Comment by minimalsm** [comment]
These are the two tutorials causing the regex errors:

- https://ethereum.org/en/developers/tutorials/interact-with-other-contracts-from-solidity/
- https://ethereum.org/en/developers/tutorials/logging-events-smart-contracts/
