### ISSUE TITLE
Redundant translation files (developer docs)

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4633]
**Describe the bug**

Many of our non-English languages have duplicated files that were not removed when we refactored the file structure.

For example:
- [src/content/translations/developers/docs/programming-languages/rust/index.md](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/translations/zh/developers/docs/programming-languages/rust/index.md)
- [src/content/translations/zh/rust/index.md](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/translations/zh/rust/index.md)

**Screenshots** (Example below is in the /translations/zh/ folder)

![Screenshot 2021-12-03 at 12 27 30](https://user-images.githubusercontent.com/62268199/144602613-f36b1d0d-0f2b-4af8-90cd-94ab7e0975ca.png)

**Comment by samajammin** [comment]
I believe this is intended. Let's discuss @minimalsm @corwintines 🙂

**Comment by samajammin** [comment]
Ah no maybe you're right.

**Comment by samajammin** [comment]
If so we should probably just clean this up ourselves. Might be confusing to someone without the context.

**Comment by minimalsm** [comment]
Already partially done in #4638. I believe we can trim a bit more here but wanted to start with the obvious ones.

**Comment by wackerow** [comment]
@minimalsm Is this closed now with #4638?

**Comment by Ningnong369** [comment]
Apakah butuh ditambahkan bahasa daerah

**Comment by minimalsm** [comment]
Closed by #4638
