### ISSUE TITLE
Multiple H1 tags on use-cases template

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4648]
**Describe the bug**

The use-cases template has two H1s. This is bad for the page's accessibility and SEO.

**To Reproduce**

1. Go to 'https://ethereum.org/en/nft/'
1. See error

**Expected behavior**

There should only be one H1 tag on the page. (Aesthetic/design of the page should not change, a different tag can be styled the same as the H1)

**Screenshots**

![Screenshot 2021-12-04 at 23 17 36](https://user-images.githubusercontent.com/62268199/144727571-757ca34e-a2cb-4b98-8473-eba704632070.png)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SNikhill** [comment]
@minimalsm 

Sir, may I please have this issue?

**Comment by minimalsm** [comment]
@SNikhill thanks for offering to help. I've assigned you to this 👌👌

**Comment by aguscruiz** [comment]
@minimalsm I can also work in this issue if you need

**Comment by minimalsm** [comment]
Hey @aguscruiz, thanks for offering. @SNikhill is on this for now but if for any reason he can't complete I'll ping you 😬❤️
