### ISSUE TITLE
Add section on crypto mining pool scams

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4655]
**Is your feature request related to a problem? Please describe.**

Crypto mining pool scams seem to be the newest popular attack vector for scamming people out of their crypto. We should add this to our security page (and try to optimise for ranking for the term @samajammin ?)

**Describe the solution you'd like**

Add a section on crypto mining pool scams here on our [security and scam prevention page](https://ethereum.org/en/security/)

**Additional context**

https://www.indiatimes.com/technology/news/crypto-mining-pool-scam-on-twitter-555251.html
https://www.reddit.com/r/CoinBase/comments/r0qe0e/scam_or_possible_incredible_payout/
https://www.reddit.com/r/CryptoCurrency/comments/r2atqi/im_the_guy_from_a_few_days_ago_that_got_scammed/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by joneskj55** [comment]
@minimalsm I'd like to take this one if possible.

**Comment by samajammin** [comment]
Thanks @minimalsm - I'm not too aware of these scam but trust you take & the sources. 

When you say rank for terms, what terms are you referring to?

**Comment by minimalsm** [comment]
@joneskj55 all yours :-)
