### ISSUE TITLE
Sort meetup list

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#4657]
**Is your feature request related to a problem? Please describe.**

Currently our meetup list is displayed [in the order they are entered into the array](https://github.com/ethereum/ethereum-org-website/blob/16e8705bd3f0c8fe6b3bd90281fdbe53ab9c39f0/src/components/MeetupList.js#L7). This might be giving older events more visibility than newer ones.

**Describe the solution you'd like**

Until we come up with a better solution, I believe we should simply randomize this list.

**Describe alternatives you've considered**

- Leaving as is
- Ordering alphabetically by location

**Additional context**
Issue that flagged this: #4646

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by amm98d** [comment]
Hi, I would like to be assigned to this issue.

**Comment by corwintines** [comment]
I think we should sort by country in my opinion.

**Comment by samajammin** [comment]
> I think we should sort by country in my opinion. Then by city after.

Agreed, I think this makes more sense vs. random sort. As a visitor I want to see meetups in my city grouped together.

**Comment by amm98d** [comment]
Agreed and  understood. I submitted a PR, let me know if I can work on this and I'll push an update to it.

@corwintines 
@samajammin

**Comment by samajammin** [comment]
Thanks @amm98d! Feel free to move forward with an update, we chatted with @minimalsm offline about this.

FYI we do have lodash installed on this project, so you could probably use something like `sortBy` for this: https://lodash.com/docs/4.17.15#sortBy

**Comment by amm98d** [comment]
> Thanks @amm98d! Feel free to move forward with an update, we chatted with @minimalsm offline about this.
> 
> FYI we do have lodash installed on this project, so you could probably use something like `sortBy` for this: https://lodash.com/docs/4.17.15#sortBy

Sounds great! Will push an update soon :)

**Comment by amm98d** [comment]
Hi @minimalsm, update pushed. Kindly check #4662.
