### ISSUE TITLE
Proof of Attendance Protocol (POAP)

### ISSUE THREAD

**Issue by decipherer2** [ethereum/ethereum-org-website#4672]
**Checklist**

- [ ] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [ ] This term/definition is not a product advertisement or contain other promotional content
- [ ] This term/definition is directly relevant to Ethereum

**Term Name:** Proof-of-Attendance-Protocol (POAP)

**Term Definition:**
 
 Alows event organizers to better engage with their audiences by providing a customized experience
 by getting a unique badge with a cryptographic record.

**Sources, if any (please do not submit copywrited content without appropriate approval):**

<[!-- Please list any sources utilized -->
](https://poap.xyz/)

**Ethereum.org links?**

**Additional context**

Users should be on the lookout for QR codes in POAP sponsored events in order to collect badges and participate in different activities

**Comment by samajammin** [comment]
Thanks for the suggestion!

I'm a bit skeptical of this. POAP is certainly a popular term in the space but it's also a dapp/product built on Ethereum. Should we be listing products as glossary terms? Seems like a slippery slope. Should ENS be a glossary term? Should MetaMask?

**Comment by decipherer2** [comment]
Sam,

I just thought it would be a good suggestion but after hearing your
thoughts I think it would be a slippery slope.
I'll look for some more glossary terms related to Ethereum itself. Thanks!

**Comment by minimalsm** [comment]
@decipherer2 I agree with samajammin that it's a slippery slope to add this. Seems like you agree so closing this out :-)

**Comment by minimalsm** [comment]
@all-contributors please add @decipherer2 for ideas
