### ISSUE TITLE
Add and implement the Link component in Markdown files

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#4679]
**Is your feature request related to a problem? Please describe.**
The content created using markdown is using the `<a>` html. We should switch this over to using `<Link>` as we do throughout the project.

**Describe the solution you'd like**
- Add Link to templates used for markdown
- Go through markdown files and replace the `<a>` elements with `<Link>`

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by KarthikSundar2002** [comment]
I am interested in contributing to this PR

**Comment by Sayantan-s** [comment]
Please assign me this task if it's open? @corwintines

**Comment by minimalsm** [comment]
> - Add Link to templates used for markdown

@corwintines I think we already pass the `Link` component to the MDXProvider to replace the default behaviour of an <a> tag. [Is this what you mean?](https://github.com/ethereum/ethereum-org-website/blob/3636982ae2e34cdfcde41a941238b05dd2d1c4a1/src/templates/docs.js#L160)

**Comment by pgupta212** [comment]
Hi corwintines

I would like to contribute to this PR

**Comment by tburnam** [comment]
@corwintines, please let me know if still available!

**Comment by minimalsm** [comment]
> I think we already pass the Link component to the MDXProvider to replace the default behaviour of an <a> tag. Is this what you mean?

Marking as blocked until we clarify the work needing done here @corwintines
