### ISSUE TITLE
Dev docs contributors not fetching

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#4710]
**Describe the bug**
Latest contributor and "See contributors" modal not fetching properly.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/
2. Note the latest contributor is not shown

**Expected behavior**
Should fetch contributors for the file and display them.

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/145517902-bb6db20e-1b90-40ac-ac36-9dcba13a9515.png)
![image](https://user-images.githubusercontent.com/54227730/145517961-9e7eace6-25d5-4b10-854d-44970562bd13.png)

**Additional context**

Noticing since Gatsby Cloud migration. Noted this in the network logs for GitHub graphql POST:

```json
{
  "message":"API rate limit exceeded for <IP address>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Noticed that in GC our `GATSBY_GITHUB_TOKEN_READ_ONLY` was a different value than in Netlify. Just replaced it & triggered a rebuild. We'll see if that fixes it. It's working for me when I run locally with `netlify dev`.

**Comment by samajammin** [comment]
This didn't seem to solve the issue 🤔 

I am noticing this console error while running this locally:
```
react-dom.development.js:67 Warning: Received `true` for a non-boolean attribute `loading`.

If you want to write it to the DOM, pass a string instead: loading="true" or loading={value.toString()}.
```
Looks to be the same issue as here: https://github.com/styled-components/styled-components/issues/1198

I wouldn't expect this to break it but I wonder if that's somehow affecting things in prod build.

**Comment by samajammin** [comment]
A cleaner way to refactor that FileContributors might be to display the "skeleton" placeholder elements if `loading`, else render the actual components. Currently we are passing `loading` to the styled components which appears to be creating this error.
