### ISSUE TITLE
Style events to look like a blockchain

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#4714]
**Is your feature request related to a problem? Please describe.**
Would like to have the events listed on `/community/events` styled to have a connection between them to look like a blockchain. Some inspiration to draw from: https://bitcoin.org/en/events

**Additional context**
- Feel free to reach out to @corwintines about this

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by tburnam** [comment]
I'd love to tackle this!

**Comment by corwintines** [comment]
@tburnam assigning to you :) Let me know if you need anything.

**Comment by minimalsm** [comment]
@tburnam just checking you've seen your assignment to this :-)

**Comment by vluna** [comment]
@minimalsm I would like to help if possible 🙂 Let me know if there is anything I can do.

**Comment by minimalsm** [comment]
@tburnam no just submitting it as a PR is fine. 

Any update on the status of this ❤️?

**Comment by vluna** [comment]
@minimalsm I would like to give it a go if there is no update on this.

**Comment by minimalsm** [comment]
Thanks offering again @vluna 🙏 Hmm yeah feel free to have a swing at this.

**Comment by minimalsm** [comment]
Closed in #5150
