### ISSUE TITLE
Redesign: TableOfContents

### ISSUE THREAD

**Issue by Hakeemmidan** [ethereum/ethereum-org-website#4721]
**Is your feature request related to a problem? Please describe.**

Not really. Just a redesign of `TableOfContents` component contents.

**Describe the solution you'd like**

From
| Inactive      | active |
| ----------- | ----------- |
| <img width="233" alt="Screen Shot 2021-12-10 at 11 07 54 PM" src="https://user-images.githubusercontent.com/27740273/145635782-daa2e0ab-f861-4d07-b3a2-2785c192543f.png">   | <img width="214" alt="Screen Shot 2021-12-10 at 11 11 15 PM" src="https://user-images.githubusercontent.com/27740273/145635769-def23485-3c3d-4409-9a13-48e44389fb23.png">       |

To
| Inactive      | active |
| ----------- | ----------- |
| <img width="230" alt="Screen Shot 2021-12-10 at 11 07 20 PM" src="https://user-images.githubusercontent.com/27740273/145635788-7cea7de3-cdb6-4b0f-aa0f-b971dc424b5d.png">   | <img width="226" alt="Screen Shot 2021-12-10 at 11 07 33 PM" src="https://user-images.githubusercontent.com/27740273/145635786-bb903d3c-d215-4a7a-b2cc-b80a6e5b33fb.png"> | 

Things that changed:
- 'Edit page' button and 'zen mode' toggle are moved to the bottom of the component
  - Why?
    - Because the table of content information should be more prominent than 'zen mode' and 'edit page', as it is the main purpose of the `TabeleOfContents` component
 - Removed text and toggle of zen mode and replaced with a toggleable icon, and lowered its opacity (to make it less distracting).
 - Lowered opacity of the 'edit page' (to make it less distracting).

**Describe alternatives you've considered**
#4168

**Additional context**
- I used the `FaYinYang` react icon for the zen mode toggle. I feel like there might be better fitting icons. Let me know if you know of any that might be a better fit! = )
- Edit: I also unintentionally created the full-redesign/branch needed for the PR while making the mock-up for this issue so I pushed that as well and connected it to this issue (#4722)

**Comment by victorlrz** [comment]
@Hakeemmidan I would love to work on this :)

**Comment by Hakeemmidan** [comment]
@victorlrz 
There's a pull request for this already, unfortunately.
Thank you for the enthusiasm though! = )

PS: [This](https://github.com/ethereum/ethereum-org-website/issues/4026) seems like a similar issue (design/frontend related), and it's marked as 'stale', so it might be a good candidate to check out! ( ^___^ )

**Comment by victorlrz** [comment]
Oh thanks @Hakeemmidan :) I'll have a loook !
