### ISSUE TITLE
"Edit page" points to the wrong URL

### ISSUE THREAD

**Issue by Sl1van** [ethereum/ethereum-org-website#4727]
**Describe the bug**

"Edit page" points to the wrong URL on multiple pages where you can edit the page via github. 2 examples are : 
https://ethereum.org/en/defi/
https://ethereum.org/en/dao/

**To Reproduce**

1. Go to [https://ethereum.org/en/defi/](https://ethereum.org/en/defi/)
2. Click on 'Edit page'
4. Now you should get a 404 because the page no longer exists

**Expected behavior**

The link should link to the correct file in github. In this case I think that would be [this ](https://github.com/ethereum/ethereum-org-website/blob/d0d67be74b09652f5c055001bd17a0b5eb38ab59/src/content/defi/index.md)one.

**Additional context**

The problem seems to be that the URL in [this](https://github.com/ethereum/ethereum-org-website/blob/2ff1c612770a7618864154d6b62faa3c07eaa36d/src/templates/use-cases.js#L379) file on line 379 is set wrong.

**Comment by prakhar1144** [comment]
Please assign this to me.
I would like to work on this issue.

**Comment by ShubhankarKG** [comment]
Hi, I tried reproducing this, but all the links all working properly. Do you mind having a look again ?

**Comment by prakhar1144** [comment]
> Hi, I tried reproducing this, but all the links all working properly. Do you mind having a look again ?

Issue has been resolved.

**Comment by Sl1van** [comment]
I have no idea how i got the 404 last saturday but the problem seems to be solved now. I looked into the releases and can't find a change that addressed the issue.
