### ISSUE TITLE
Feature: Add community links(gitter/matrix) for ethereum-solidity

### ISSUE THREAD

**Issue by muddlebee** [ethereum/ethereum-org-website#4753]
**Is your feature request related to a problem? Please describe.**

Community links for Solidity(https://github.com/ethereum/solidity) to be added here https://ethereum.org/en/community/online/

- Gitter: https://gitter.im/ethereum/solidity
- Matrix: https://matrix.to/#/#ethereum_solidity:gitter.im

Community Links Source: https://forum.soliditylang.org/

**Comment by lingzhong** [comment]
Happy to take a stab at this 😃

**Comment by minimalsm** [comment]
Hey @lingzhong, thanks for offering to help again. It's all yours 🙌. Feel free to give me a ping here or on Discord if you need to be unblocked on anything.

**Comment by ErikBjare** [comment]
Gave this a shot in #5322

**Comment by lingzhong** [comment]
Thanks for taking this over @ErikBjare ! 👍

**Comment by lingzhong** [comment]
Thanks for taking this over @ErikBjare ! 👍
