### ISSUE TITLE
AirGap Wallet

### ISSUE THREAD

**Issue by AndreasGassmann** [ethereum/ethereum-org-website#4755]
**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**

We have done a [security audit by a third party](https://github.com/airgap-it/airgap-coin-lib/tree/master/docs/audits).

**When did your wallet go live to users?**

We released the first version of the wallet about 4 years ago.

**Does your wallet have an active development team?**

Yes, we are actively working on the project and have frequent releases (approx. 1 per month).

**Is your wallet open-source?**

https://github.com/airgap-it/airgap-wallet
https://github.com/airgap-it/airgap-vault

**Is your wallet globally accessible?**

Yes, it is globally accessible.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

The wallet is non-custodial, users have access to their private keys.

If our project would disappear, users could either build the project themselves because it's open source, or they could use any other BIP39 compatible wallet to recover their accounts.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

AirGap is focussed on security. We have split our wallet into 2 apps, [AirGap Wallet](https://github.com/airgap-it/airgap-wallet) and [AirGap Vault](https://github.com/airgap-it/airgap-vault). AirGap Vault holds the private keys and can be installed on an air-gapped device. AirGap Wallet only holds the public keys to be able to check balances and prepare transactions. If the apps are installed on different devices, communication happens over QR codes and the private key never touches a device with internet access.

Both apps can be installed on the same device as well. In that case, communication is done over app-switching. While less secure than the 2 device approach, it is still more secure than having everything in one app because AirGap Vault doesn't have internet access (eg. no internet permissions on Android).

More information: https://support.airgap.it/

**Does the wallet have fiat on-ramps?**

No

**Does the wallet allow users to explore dapps?**

AirGap Wallet has WalletConnect support.

**Does the wallet have integrated defi/financial tools?**

No

**Can a user withdraw to their card?**

No

**Does the wallet offer limits protection?**

No

**Does the wallet allow high-volume purchases?**

No

**Does the wallet have an integrated token swap?**

Yes, we support Changelly and ChangeNow

**Is the wallet a multi-signature wallet?**

No

**Wallet title**

AirGap Wallet

**Wallet description**

With AirGap’s two device approach, you can sign transactions completely offline on a device without any network connectivity using AirGap Vault. Then you can broadcast them with your every-day smartphone with the AirGap Wallet app.

**Wallet logo**

https://user-images.githubusercontent.com/680814/135846462-10e9c1f3-b695-4a94-a7bb-7d344f995ba8.png

**Background colour for brand logo**

#50249F

**Website**

https://airgap.it

**Does the wallet support layer 2 networks?**

No

**Can the wallet be used with arbitrary Ethereum RPC endpoint?**

No

**Comment by Backling** [comment]
thank you so much

**Comment by minimalsm** [comment]
Hey @AndreasGassmann thanks for raising this :-) could you add the two newest questions (below) that we just added to our wallet template and I'll get this reviewed for you?

> **Does the wallet support layer 2 networks?**
> 
> 
> 
> **Can the wallet be used with arbitrary Ethereum RPC endpoint?**
> 
>

**Comment by AndreasGassmann** [comment]
@minimalsm I added the 2 new questions to the post. Let me know if you need anything else.
