### ISSUE TITLE
Site Translation: Bislama (Vanuatu)

### ISSUE THREAD

**Issue by uwantege** [ethereum/ethereum-org-website#480]
**Is your feature request related to a problem? Please describe.**
Would like to add Bislama translation so I and my colleagues can contribute to this project on CrowdIn
**Describe the solution you'd like**
Allow for translation of ethereum website into Bislama, the language of Vanuatu (a country in the Pacific Islands). This language is also accessible to people from Papua New Guinea and the Solomon Islands (neighbouring countries in the Pacific)

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by samajammin** [comment]
Great idea, thank you for creating this & volunteering! @sorumfactory - could you please create this project in CrowdIn?

**Comment by sorumfactory** [comment]
Thank you, Uwantege! 
We've added the Bislama in Crowdin! You can start working on the translation from now on :))

**Comment by samajammin** [comment]
Thanks @sorumfactory! Closing out this issue for maintenance purposes. You can contribute to the translations here: https://crowdin.com/project/ethereumfoundation/bi#

There's also instructions & resources for our Translation Program here:
https://ethereum.org/languages/
