### ISSUE TITLE
Update Ethereum docs to make definition of Wallet and Account clearer

### ISSUE THREAD

**Issue by kennethcassel** [ethereum/ethereum-org-website#4821]
The site has a conflicting definition of Wallets on two pages. 

On https://ethereum.org/en/wallets, the definition is: 
> Ethereum wallets are applications that let you interact with your Ethereum account. 

On https://ethereum.org/en/developers/docs/accounts/#a-note-on-wallets the definition is:
> A wallet is the keypair associated with a user-owned account, which allows a user to make transactions from or manage the account.

I brought this up in a [twitter thread](https://twitter.com/KennethCassel/status/1471854438126137352?s=20) and @samajammin agreed with the following suggested terminology from @wslyvh 

Account : key-pair 
Wallet: application that can interact on behalf of it.

We should update the docs at https://ethereum.org/en/developers/docs/accounts/#a-note-on-wallets to reflect this change in terminology.

**Comment by kennethcassel** [comment]
I'd like to be assigned to this issue :)

**Comment by minimalsm** [comment]
Closed in #4822
