### ISSUE TITLE
BUG: Links in the DAO section not clickable due to overlaying H3 tags from use-cases template

### ISSUE THREAD

**Issue by muddlebee** [ethereum/ethereum-org-website#4825]
**Describe the bug**

 Links in the DAO section not clickable due to overlaying H3 tags from use-cases template

**To Reproduce**

1. Go to https://ethereum.org/en/dao/#join-a-dao
2. Click on all links under the section **Join a DAO** and **Start a DAO**
3. Few links are not clickable

**Expected behavior**
All links should be clickable

**Screenshots**

**Desktop (please complete the following information):**
![Screenshot 2021-12-19 at 2 23 39 PM](https://user-images.githubusercontent.com/8139783/146669437-58401442-acb1-40ea-bb81-b63d5faf7cc7.png)
![Screenshot 2021-12-19 at 2 25 54 PM](https://user-images.githubusercontent.com/8139783/146669440-dcee85ff-fc0a-4f73-a598-abc577376810.png)

**Smartphone (please complete the following information):**

<img src="https://user-images.githubusercontent.com/8139783/146669469-8a1e209f-6bae-4705-a799-3f28ed215eae.jpg" width="260" height="380">

**Comment by minimalsm** [comment]
Hey @muddlebee thanks for raising this. We've already got an open issue in #4793 that covers this, so I'm going to close this one out for now :-) thanks again.
