### ISSUE TITLE
Add ETHGlobal events

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#4859]
**Is your feature request related to a problem? Please describe.**

https://ethglobal.medium.com/announcing-the-ethglobal-2022-season-51a7906bb3a4

**Describe the solution you'd like**

Add to https://ethereum.org/en/community/events/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@samajammin I can work on this 🙂

**Comment by minimalsm** [comment]
Hey @vluna, thanks for offering to help here. I've assigned you ✌️

**Comment by vluna** [comment]
@minimalsm Here is the PR #4889. Let me know if there are any changes that need to be done 🙂
