### ISSUE TITLE
Add 'Get Involved' page to help people find what they can do

### ISSUE THREAD

**Issue by wschwab** [ethereum/ethereum-org-website#489]
(This idea has been discussed by the [Ethereum Cat Herders](https://www.ethereumcatherders.com/) and a member of the EF, which is why I'll be using 'we' instead of 'me'. Just to be clear - I wrote the content and the code, and the ECH is looking it over.)

**Is your feature request related to a problem? Please describe.**

We think it would be good to have a page dedicated to helping people find what they can do to be involved in the ecosystem, coders and non-coders alike.

**Describe the solution you'd like**

We propose adding a new page to the menu on the home page title 'Get Involved' with links and short descriptions of what newcomers can contribute.

**Describe alternatives you've considered**

I'm not sure if this is an alternative, but the ECH is in general trying to ramp up its ability to help people find their place, and while I don't think this is a stated goal of the Magicians, I believe to be well within their purview, too.

I'd like to assign this to myself, as I have the material pretty much ready (as a rough draft for feedback).

**Comment by wschwab** [comment]
I'd add a `wip` label (re the contributing guidelines), but I don't think I have the permissions.

**Comment by samajammin** [comment]
Thanks for raising this @wschwab! I think this is a great idea & I know [our team](https://github.com/ethereum/ethereum-org-website#-how-are-decisions-about-the-site-made) has had conversations with many community members around this as well. 

I feel like this page may be very similar to this "community page" idea in #269 (which I believe is in the works, @jjmstark may be able to help you get involved). Or do you think this is a separate idea that needs a distinct page?

**Comment by wschwab** [comment]
I think this is a separate idea. I'm looking for a good way to describe why, so apologies if this isn't too clear.

The community page idea (which is awesome, btw) focuses on community resources for interaction about the platform - you can ask questions or post answers on Stack, have a conversation on Reddit, go to a meetup, etc. The page we're proposing comes to answer one question: How can I contribute something to the ecosystem? As such the focus is less on where to interact/consume content, but rather what can be done. Examples of resources mentioned are [Ethereum Challenges](https://challenges.ethereum.org) and MolochDAO.

One concrete example of the difference might be that the Community page talks about attending a meetup, whereas the 'Get Involved' page would talk about hosting one.

@samajammin Is that clear? I have a rough draft that I could push if it would make things clearer, but I figured that I shouldn't PR out of the blue.

**Comment by samajammin** [comment]
Interesting! Yes, a rough draft would help clarify this. They do seem closely related but you may have a valid reason to create the distinction. Do you envision this as a "Get involved" for developers? Or is this for anyone who is looking to A) contribute to an existing project or B) start their own Ethereum project?

If this is a separate page, @jjmstark this seems like something the Community page should have a brief section on & a link to.

**Comment by wschwab** [comment]
> Do you envision this as a "Get involved" for developers? Or is this for anyone who is looking to A) contribute to an existing project or B) start their own Ethereum project?

I feel like people coming to Ethereum sense that there is a larger community/ecosystem, and would like to join the family, so to speak. I feel like this is especially true of non-devs, though also true for devs. As such, I hope this page will help give some guidance as to how to get involved in the community, be a part of what's happening. I think it applies less to those with enough guidance and capability to launch their own project, though I included a link to the section about building on Ethereum on the page.

@samajammin Does that answer the question? I've made a rough draft PR; you can take a look [here](https://github.com/ethereum/ethereum-org-website/blob/485340a9a3d383ddaad9e541c4a3a778fb5eb38d/docs/get_involved/index.md) at what I'm proposing.

**Comment by jjmstark** [comment]
Hey @wschwab! Sorry for the long delayed response - we're actually working right now on some draft content for a "community" page that I think captures a lot of what you're going for here. 

What email address can I reach you at, so that I can share that doc with you? Our first take on this is being written up in a Dropbox Paper doc to allow easier commenting/discussion from a larger group.

**Comment by wschwab** [comment]
@jjmstark 
> What email address can I reach you at

I pinged you on Gitter with an address.

**Comment by samajammin** [comment]
Hey folks - closing this out in favor of #269 - please feel free to add input there. Thanks for the thoughtful discussion!
