### ISSUE TITLE
Add Rocketpool to 'Less Than 32 ETH' section of staking page

### ISSUE THREAD

**Issue by MiConnell** [ethereum/ethereum-org-website#4891]
**Describe the solution you'd like**
The current [staking page](https://ethereum.org/en/eth2/staking/#stake) under the `less than 32 eth` section only links out to a [list of pools and staking services](https://beaconcha.in/stakingServices). Now that Rocketpool is live, I think it would be great to feature that project. As they are more than just a pool, users with less than 32 eth can actually run a node. 

Happy to hear your thoughts on this, I have a PR ready to go if this would be something that you'd be open to adding.

**Comment by corwintines** [comment]
@wackerow would be interested in hearing what you think around this.

**Comment by minimalsm** [comment]
Thanks @MiConnell,

Personally I'd be fine with adding this. 

Echoing @corwintines — I'd default to @wackerow on this.

**Comment by minimalsm** [comment]
Marking this as blocked until we merge the ETH2 rebrand stuff in. Though, I still think we should make this change.

**Comment by wackerow** [comment]
Hey @MiConnell  sorry for the delays here... Love that you brought this up, I think adding Rocket Pool is an absolute must. We were planning on assessing and revamping the staking section in the near future and I definitely planned on incorporating Rocket Pool into it as much as possible. 

In the meantime, if you do have a PR, it's hard to saw how it'll all play together in the end with other upcoming changes, but I'd say it's worth us taking a look at if you want to post it. 

Thanks again for surfacing Rocket Pool 💪🏻

**Comment by minimalsm** [comment]
@MiConnell assigned :-)

**Comment by MiConnell** [comment]
I just added PR #5349. This is just a brief description, I wasn't sure if there should be a hero image and everything like there is with the r/ethstaker section below. Also if there's a desire to add a full page dedicated to rocket pool I would be happy to contribute. Looking forward to your feedback.
