### ISSUE TITLE
We ethereum projects is not registered on google summer  of code?

### ISSUE THREAD

**Issue by yehia67** [ethereum/ethereum-org-website#4903]
[Google Summer Of Code](https://summerofcode.withgoogle.com/)    is a great opportunity for developers to contribute in Open-source project and to continue Open-source contribution on their careers. I see ethereum has a lot of projects that has great potential to be accepted in Google summer of code. Which will help a lot of developers to learn more about web3 technologies and open-source organizations will found a lot of new contributors.

**Comment by minimalsm** [comment]
Hey @yehia67 thanks for raising this.

It is actually something that we are considering for ethereum.org although we have not fully investigated/committed to it yet. 

Appreciate the prompt here. Applications for organisations [don't open until Feb 2022](https://summerofcode.withgoogle.com/) so there isn't anything actionable here just yet so I'm going to close this issue out. The ethereum.org team will be sure to announce this if we decide to participate 😬
