### ISSUE TITLE
i m in china how to have a ethereum wallet, fans of metaverse

### ISSUE THREAD

**Issue by PirateRadioY** [ethereum/ethereum-org-website#4914]
**Is your feature request related to a problem? Please describe. Y, i m a  fans of metaverse,lots OF MANAGE problemS NEED to be solved

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Clashinm** [comment]
Basically how can I pull my self up out this down fall If I need to get you
or someone else to take over in other to finalize the website
