### ISSUE TITLE
Added term to glossary: Soft Fork

### ISSUE THREAD

**Issue by nschaferx** [ethereum/ethereum-org-website#4916]
**Checklist**

- [x] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [x] This term/definition is not a product advertisement or contain other promotional content
- [x] This term/definition is directly relevant to Ethereum

**Soft Fork**

**A temporary divergence in a [blockchain](https://ethereum.org/en/glossary/#blockchain) that occurs when the [consensus rules](https://ethereum.org/en/glossary/#consensus-rules) become stricter. Contrary to a [hard fork](https://ethereum.org/en/glossary/#hard-fork), a soft fork is backward compatible; upgraded nodes can validate blocks created by nonupgraded nodes as long as they follow the new consensus rules. However, nonupgraded nodes are ultimately encouraged to download the latest version of the blockchain's software to avoid complications related to transactions.**

**N/A**

**N/A**

**N/A**

**Comment by minimalsm** [comment]
Hey @nschaferx, I agree we should add Soft Fork to the glossary. 

I think we can come up with a cleaner definition. 

Would you like to be assigned to this?

**Comment by nschaferx** [comment]
Sure thing!

**Comment by minimalsm** [comment]
@nschaferx assigned! Be sure to ping here if you need any help getting this over the line.

**Comment by nschaferx** [comment]
I believe omitting the last sentence and changing "become stricter" to "are updated" would simplify the definition.

**Comment by minimalsm** [comment]
Agree! But I wouldn't worry too much about the definition being perfect right now. We can resolve that in the PR itself :-)

**Comment by jumptiger8** [comment]
> 同意！但我不会太担心现在的定义是否完美。我们可以在 PR 本身解决这个问题:-)

Can I participate in the contribution of this word?

**Comment by jumptiger8** [comment]
I see that this word has not been updated for a long time and has not appeared in Ethereum vocabulary.

**Comment by nschaferx** [comment]
Yes you may, I was told by the lead to let contributors edit.

**Comment by corwintines** [comment]
Closing as the above PR addresses this
