### ISSUE TITLE
Improve to "How to Write & Deploy an NFT" tutorial

### ISSUE THREAD

**Issue by Gobljn** [ethereum/ethereum-org-website#4918]
**Reference tutorial**
https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/#write-contract

**Proposed improvement**
I propose to specify that `@openzeppelin/contracts` have to be installed by npm.
And also in the contract code `MyNFT.sol` I suggest removing the accessor `public` from the constructor because hardhat generates a warning during compilation.

Let me know if the proposed improvement makes sense. In case I'm happy to open a PR with these changes.

**Comment by minimalsm** [comment]
Solved, thanks!

**Comment by minimalsm** [comment]
@all-contributors please add @Gobljn for ideas
