### ISSUE TITLE
The URL for "Ethereum community DAOs" is wrong

### ISSUE THREAD

**Issue by Naman-Bhalla** [ethereum/ethereum-org-website#4922]
**Describe the bug**

The URL for "Ethereum community DAOs" on  https://ethereum.org/en/dao/ doesn't work as it points to a page that doesn't exist.

**To Reproduce**

1. Go to https://ethereum.org/en/dao/ 
2. Scroll to the section in screenshot. 
<img width="393" alt="Screenshot 2021-12-30 at 2 49 40 AM" src="https://user-images.githubusercontent.com/6305474/147704188-501eb3f0-5452-4563-b049-3ad267858115.png">

3. Try clicking on "Ethereum community DAOs"
4. You aren't able to click it.

**Expected behavior**

The link should take you to https://ethereum.org/en/community/get-involved/#decentralized-autonomous-organizations-daos

**Comment by minimalsm** [comment]
Solved in #4923
