### ISSUE TITLE
Unable to click links due to a psuedoelement's hinderance

### ISSUE THREAD

**Issue by aryankeluskar** [ethereum/ethereum-org-website#4930]
**Describe the bug**

The last two links in the subheading "Join a DAO" don't work for all of its children.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://ethereum.org/en/dao/
2. Scroll to the section in screenshot.
   
![image](https://user-images.githubusercontent.com/80093392/147852402-55e51b40-4bdc-402b-b594-b94d5772caa5.png)

3. Try clicking on "Ethereum community DAOs" or "DAOHaus's list of DAOs" or  even "Start a colony", ie: last two list items of any list in the subheading of "Join a DAO"
4. You aren't able to click any of them.

**Weird Accomplishments**
When i added additional list items to the list, for debugging, the above mention list items became clickable
![image](https://user-images.githubusercontent.com/80093392/147852517-f7db1883-87e6-48f0-abad-04c6e3606857.png)
 
To reproduce it, open inspect element at the h3 of join a dao, go to the ul and paste:
<li><a class="Link__ExternalLink-sc-e3riao-0 gABYms" href="https://app.daohaus.club/summon" target="_blank" rel="noopener noreferrer">"Dummy Item #1"</a></li>

**Comment by udbhav-s** [comment]
![image](https://user-images.githubusercontent.com/50021387/147852955-8366eaac-93b4-491e-bf94-0f39b39cabd6.png)

The `h3` element following the `ul` containing the two list items under "Join a DAO" has a psudo ::before element (`.gWTLmC::before`) which has a negative margin and height of 120px which covers the list and seems to obstruct the mouse from interacting with the list. Removing it by unticking `content: ""` under `.gWTLmC::before` in the CSS panel makes the list interactable again. Same issue with the last 2 items of the "Start a DAO" list being blocked by the `.gWTLmC::before` element of the "Further Reading" `h2` following it.

**Comment by aryankeluskar** [comment]
I have found the faulty line in code, and working on the fix.
