### ISSUE TITLE
Broken link in CALLING A SMART CONTRACT FROM JAVASCRIPT post

### ISSUE THREAD

**Issue by kamilsadik** [ethereum/ethereum-org-website#4937]
**Describe the bug**

The link at the end of [this paragraph](https://ethereum.org/en/developers/tutorials/calling-a-smart-contract-from-javascript/#call-reading-value-from-a-smart-contract) is broken:
The first example will call a “constant” method and execute its smart contract method in the EVM without sending any transaction. For this we’ll read the ERC20 balance of an address. *Read our article about ERC20 tokens.*

The last sentence should instead link to https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/#gatsby-focus-wrapper

**Screenshots**

**Desktop (please complete the following information):**

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Smartphone (please complete the following information):**

- Browser: [e.g. stock browser, safari]
- Version: [e.g. 22]

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@minimalsm I can take this if possible.

**Comment by minimalsm** [comment]
Thanks for the report @kamilsadik 

@vluna all yours, please don't include `#gatsy-focus-wrapper` in the URL :-)

**Comment by vluna** [comment]
@minimalsm here is the PR #4938

**Comment by minimalsm** [comment]
@all-contributors please add @kamilsadik for bug reports

**Comment by kamilsadik** [comment]
Wow thanks!
