### ISSUE TITLE
error in the code blocks of spanish developer docs

### ISSUE THREAD

**Issue by Factral** [ethereum/ethereum-org-website#4972]
in some sections of Spanish developer docs there are errors in the translation of code blocks.

for example in the [smart contracts](https://ethereum.org/es/developers/docs/smart-contracts/) section in the second block of code, in the 3rd line of code `contract VendingMachine {` is literally translated as `contrato VendingMachine {` ignoring the solidity syntax and making the script not work in practice, this does not only happen in the smart contract section.

also in other sections it seems that during the translation some characters were removed, for example in the [smart contract languages](https://ethereum.org/es/developers/docs/smart-contracts/languages/) section there is one such error.
![image](https://user-images.githubusercontent.com/74687828/148143806-64bae138-4577-4e8a-a5ac-e23eb87301d1.png)
and there are also literal translation errors in lines of code.
![image](https://user-images.githubusercontent.com/74687828/148143981-eb93c38f-f58a-40ff-95c1-e2a08e59802b.png)

I was looking at how the code blocks have been translated into other languages and I found that not all of them follow the same methodology

in the [French translation of smart contracts languages ](https://ethereum.org/fr/developers/docs/smart-contracts/languages/) the code blocks are not translated and are copied from the English version, while on the other hand the [Italian translation](https://ethereum.org/it/developers/docs/smart-contracts/languages/) of the same section translates only the commented lines of the code block.

I am willing to open a PR to fix the problem in the Spanish translation of the code blocks but I would like to know which methodology to follow, I would say that the best one is the one used in the Italian translation, translating only the commented sections. 😀

**Comment by minimalsm** [comment]
Hey @Factral, thanks for flagging this.

Yes, we can open leave the translated comments in and revert the code to English. I've assigned you :-)
