### ISSUE TITLE
Expand article on composability in smart contracts

### ISSUE THREAD

**Issue by chtnnh** [ethereum/ethereum-org-website#4974]
**Describe the bug**

The article on [composability](https://ethereum.org/en/developers/docs/smart-contracts/composability/) in smart contracts is a stub, and can be improved. This should be done as composability is a key component of why DeFi is so diverse on Ethereum.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by chtnnh** [comment]
Would love to help add some links to the article as well as expand it. Have forked and cloned my fork.

**Comment by minimalsm** [comment]
Hey @chtnnh, thanks for offering to help.

Agreed! This needs some work. Did you plan to add any additional content or just link out to external resources? Either way, please feel free to open a PR to improve this page 🙏

**Comment by chtnnh** [comment]
hola @minimalsm! currently researching and trying to find the right words to extend the article. Already added links to the articles I'm reading.

**Comment by minimalsm** [comment]
@chtnnh sure thing! Let me know if you need any help getting started on this.

**Comment by minimalsm** [comment]
@chtnnh hey :-) just checking you've seen that I assigned you on this.

**Comment by chtnnh** [comment]
hey @minimalsm sorry for the delay. 

things have been hectic for a while, finals week. getting back to this by the weekend, hope that's acceptable?

**Comment by corwintines** [comment]
Closing as abandoned
