### ISSUE TITLE
Add term "Base Fee" to glossary

### ISSUE THREAD

**Issue by zainabb12345** [ethereum/ethereum-org-website#4995]
**Checklist**

- [x] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [x] This term/definition is not a product advertisement or contain other promotional content
- [x] This term/definition is directly relevant to Ethereum

**Base Fee:**

**Term Definition: The algorithmically determined network fee proposed in the EIP-1559. It is the minimum fee a user pays to include a transaction on the next block. The base fee is burned, helping to prevent miners from colluding and inflating the network.**

**Sources, if any (please do not submit copywrited content without appropriate approval):**

**Ethereum.org links?**

**[Additional context](https://eips.ethereum.org/EIPS/eip-1559)**

**Comment by minimalsm** [comment]
Hey @zainabb12345, thanks for the suggestion to add this. 

Would love some other opinions on this. My first reaction is that adding properties of a block or transaction might be slippery slope, do we also add priority fee? What about max fee? 

They are explained well and within relevant context in the developer docs already: e.g., on our [gas](https://ethereum.org/en/developers/docs/gas/#base-fee) or [transactions](https://ethereum.org/en/developers/docs/transactions/) pages.

**Comment by zainabb12345** [comment]
Hey @minimalsm,
Thank you for bringing it to my attention that it is there in relevant context and with details.
Closing request.
Again thank you

**Comment by samajammin** [comment]
IMO "base fee" would be a useful word to add. I think it's a common term that users will come across.

**Comment by corwintines** [comment]
I would definitely support this. It's a common term in many wallets users will be interacting with, and having a place to shine a light on what it is seems valuable to me.

**Comment by wackerow** [comment]
Hey @zainabb12345! Agree this would be a nice term to add to the glossary. We want to be careful not to have a slippery slope where we feel we need to add every technical property out there, but I believe this term would certainly provide value.

Would you like to help out with this one? If so drop a reply and we'll assign you =)

**Comment by zainabb12345** [comment]
@wackerow Yes, I would very much like to =)
