### ISSUE TITLE
Cant create development enviroment!

### ISSUE THREAD

**Issue by fiskce** [ethereum/ethereum-org-website#5033]
Im trying to create a development enviroment but i doesnt seem to work

https://pastebin.com/ndqzWRV7

**Comment by minimalsm** [comment]
Hey @fiskce, thanks for raising this issue.

Could you let me know what command you used in your terminal to get this output?

Also, if you use Discord you can [join our server here](https://discord.gg/CetY6Y4) to get help more quickly on this. ☺️

**Comment by minimalsm** [comment]
Discussion in discord, can't troubleshoot this without more information. Closing this out.
