### ISSUE TITLE
Article: Compressing contract deployers for Layer 2

### ISSUE THREAD

**Issue by qbzzt** [ethereum/ethereum-org-website#5038]
# Tag your tutorial

#Layer2 #Optimization #L2

# Tutorial title

Compressing Contract Deployers for Layer 2

# Tutorial description

Rollups change the tradeoffs between providing the blockchain with information (through CALLDATA) and having the information processed on the blockchain. All transactions have to be written, at great expense, to L1 (the Ethereum mainnet). On the other hand, processing is done on L2 (the rollup) at a much lower cost. For example, at writing the the cost of writing a single byte to L1 call data is approximately two thousand gwei. For that cost on Optimism you can spend two million gas doing calculations and writing the results to L2 storage.

In this article you learn how to reduce the cost of deploying contracts to rollups by compressing the code and deploying it through a decompression contract. The technique explained in this article is demonstrated using Optimistic Ethereum, but the technique is not Optimism specific, it can be applied just as easily to Arbitrum or any other optimistic rollup.

# Table of content (tentative, might change during writing):

- Introduction - why and how
   - Rollups - what costs they can reduce and what costs they can't
   - How contracts normally get deployed
   - The completed system - description of what we are building in the article
- Data compression
   - Why is it possible?
   - [Huffman coding](https://en.wikipedia.org/wiki/Huffman_coding) - tradeoff between performance and simplicity
- Building the coding table
   - The similarity between contracts
   - A corpus of EVM bytecode
   - The coding table builder (in JavaScript)
- Encoding contract constructors - the JavaScript program that does it
- Decoding contract constructors - the contract that does it (probably in Yul)
- Tying into a tool chain (probably Hardhat)
- Conclusion

# Publication

It's not even written yet.

# Skill level

Advanced to understand the entire article. Intermediate to just use the technique on a network with an existing decompression contract.

**Comment by wackerow** [comment]
Hey @qbzzt, this outline looks great! Totally on board to have more intermediate/advanced coverage of layer 2s. Looks like you were planning on setting this up as a tutorial?

Would love to potentially incorporate some of this into our upcoming L2 improvements, perhaps pulling pieces to update the developer docs eventually. We'll cross that bridge soon, but in the meantime I think this tutorial would be a great addition.

**Comment by qbzzt** [comment]
Thank you. I spent 15 hours writing it up, and I'm close to done, but for the second time Optimism developnment caught up with me and an article I wished to write got superceded. We're going to start compressing the calldata before writing it to L1, so there's no point compressing the contract prior to deployment. Being an Optimism employee, I'm reluctant to put my name on an article that wouldn't be useful on us, but would be useful on Arbitrum.

**Comment by corwintines** [comment]
@qbzzt let me know what you want us to do with this. Sounds like a great article, but I understand the reluctance as well.

**Comment by qbzzt** [comment]
I think I'd like to wait with this. Once the compression feature is out, I can check if adding this improves the results or not, and then decide - is that OK?

**Comment by qbzzt** [comment]
I checked it - with compression using my article's technique is actually counter productive. So I have to either give up on this, or include in the introduction that it doesn't work with Optimism, but if you have to work with a different rollup that doesn't compress natively it'll be useful. That would sound like an attack on Arbitrum even if it isn't. 

As reluctant as I am to throw away all this work, I think I have to.
