### ISSUE TITLE
Fix typo in 'Sending transactions using Web3' tutorial

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5042]
**Describe the bug**

In the 'Sending transactions using Web3' developer tutorial, we have a note that says ''This guide is for singing your transactions on the backend for your app...''
'Singing' is a typo here.

**To Reproduce**

1. Open the tutorial: https://ethereum.org/en/developers/tutorials/sending-transactions-using-web3-and-alchemy/
2. Scroll down to the first note in the intro.
3. See error

**Expected behavior**

'for singing' should be spelled 'for signing'.

**Screenshots**

![Sending transactions using Web3 typo](https://user-images.githubusercontent.com/37338979/148831198-10ab76c6-7e82-44e8-8cdb-2e93776de52e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: V1.34.80

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by stefan-wuest** [comment]
I would like to do this as my first issue in here
