### ISSUE TITLE
Unwanted text wrap on ExpandableCard component 

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5083]
**Describe the bug**

We have undesirable word-wrapping with the use of our [ExpandableCard](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/ExpandableCard.js) component on some languages where:

- the card's preview text spans two lines
- the translation of the word 'More' is too long 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://ethereum.org/tr/eth2'
2. Scroll down to 'Sıkça sorulan sorular'
3. See error

**Expected behaviour**

- The 'More' link should not wrap.

**Screenshots**

**Japanese:**
<img width="1496" alt="Screenshot 2022-01-13 at 11 10 38" src="https://user-images.githubusercontent.com/62268199/149321147-d96cf869-9c3f-4e69-8b30-50aa081f6c9e.png">

**Turkish:**
<img width="1538" alt="Screenshot 2022-01-13 at 11 09 05" src="https://user-images.githubusercontent.com/62268199/149321251-551a32f4-03d4-448d-ab93-b0351840f1ee.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Nice catch!

**Comment by vluna** [comment]
Hey @minimalsm, I would like to give it a try 🙂

**Comment by minimalsm** [comment]
Hey @vluna, all yours 😬

As a potential area to investigate, in many cases the wrapping actually disappears actually disappeared when the card is expanded 🤔
