### ISSUE TITLE
Trilemma text labels are not visible

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5084]
**Describe the bug**

The text labels for 'Security', 'Decentralisation', and 'Scaling' are not visible on the [Trilemma](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Trilemma.js). However, they are showing up in the DOM.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://ethereum.org/en/eth2/vision/'
3. Scroll down to 'The challenge of decentralized scaling'

**Expected behavior**

The labels should be visible next to the circular buttons.

**Screenshots**

<img width="1503" alt="Screenshot 2022-01-13 at 11 55 01" src="https://user-images.githubusercontent.com/62268199/149325835-6d8fbaaa-d91d-4bb4-abab-5a1c4d733f53.png">

<img width="1112" alt="Screenshot 2022-01-13 at 11 38 10" src="https://user-images.githubusercontent.com/62268199/149326009-12ad77f4-bf0f-4c2c-9b08-c0be927686a3.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SNikhill** [comment]
@minimalsm 

Sir, May I tackle this issue? I shall like to learn more about how these good looking graphics are setup.

**Comment by wackerow** [comment]
This has been fixed in #4915

**Comment by samajammin** [comment]
Yes indeed looks to be solved in #4915 - thanks @wackerow! Closing this out.

https://ethereumorgwebsitedev01-eth2rebrand.gtsb.io/en/upgrades/vision
