### ISSUE TITLE
Glossary header ID does not take you directly to the header

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5085]
**Describe the bug**

When navigating directly to a header-ID or using the table of contents there is additional (unwanted) content between the navigation bar and header. This may be slightly confusing/jarring to users.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://ethereum.org/en/glossary/#byzantium-fork'
2. See error

**Expected behaviour**

The selected header should be at the top of the page, directly beneath the navigation bar.

**Screenshots**

For example: when going directly to #byzantium-fork

<img width="1511" alt="Screenshot 2022-01-13 at 12 02 05" src="https://user-images.githubusercontent.com/62268199/149326767-f6525d68-b43c-44b3-b426-6c33931715a6.png">

**Additional context**

Related: #5003 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
FYI when I clicked on the link I didn't see this issue:
![Image 2022-01-13 at 5 59 48 PM](https://user-images.githubusercontent.com/8097623/149438500-b370fda3-2d23-4393-99ec-6ae4fe335cbd.jpg)

I'm not able to replicate - @minimalsm what browser/device/version are you using?

- OS: [e.g. iOS]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by minimalsm** [comment]
Hmm, it seems to only be visible on my 27inch screen (but somewhat less so than yesterday, which makes no sense...) let me dig into this more later.

OS: macOS Monterey v12.1
Browser: Brave
Version: V1.34.80

**Comment by Himanxu1** [comment]
Have this resolved or I would like to contribute to this issue:
