### ISSUE TITLE
/get-eth/ CallOutBanner not displaying any content

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5086]
**Describe the bug**

The callout banner on the /get-eth/ page is not displaying any content.

**To Reproduce**

1. Go to 'https://ethereum.org/en/get-eth/'
3. Scroll down to bottom of page

**Expected behavior**

The content should display dynamically based on the selected website language

**Screenshots**

<img width="1557" alt="Screenshot 2022-01-13 at 12 11 28" src="https://user-images.githubusercontent.com/62268199/149328346-a4a6d6ee-5b3e-48fc-bc42-4e0d54ff7caf.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by mradziwon** [comment]
Hi Joshua, I can fix it. Problem is related to wrong props passed to component. `CalloutBanner` accepts `title` and `description`, not `titleKey` and `descriptionKey`. I can pass translated `title` and `description` or refactor `CalloutBanner` to accept keys and translate it there, just like in `Callout` component. I think the problem has occurred because of this inconsistency between similar components. `CalloutBanner` is used in pages: `get-eth, learning-tools, find-wallet`.

**Comment by mradziwon** [comment]
@minimalsm should I pass translated texts to [CalloutBanner](https://github.com/ethereum/ethereum-org-website/blob/37ce90359540b3cf0ba6f677ca3e4f30bcfc6e93/src/components/CalloutBanner.js) or refactor it to accept keys like in [Callout](https://github.com/ethereum/ethereum-org-website/blob/37ce90359540b3cf0ba6f677ca3e4f30bcfc6e93/src/components/Callout.js)? What's your opinion?

**Comment by minimalsm** [comment]
Sorry for the lack of clarity. Yes, I believe we want to refactor it to use keys for better translation support if we decide to use this component in a markdown file. @wackerow could you confirm?

**Comment by wackerow** [comment]
We could go either way here. The `CalloutBanner` component specifically seems to only be used on React pages, and we pass it already translated strings (except for this buggy case), which works fine for the non-markdown side of things.

For consistency I say we just refactor this as well, which will make it usable in markdown in the future and keep it consistent with the other Callout component. 

Quick search looks like this `CalloutBanner` component is used in 10 files:
src/pages/get-eth.js
src/pages/index.js
src/pages/stablecoins.js
src/pages/developers/learning-tools.js
src/pages/eth2/index.js
src/pages/eth2/staking.js
src/pages/eth2/get-involved/index.js
src/pages/wallets/find-wallet.js
src/pages-conditional/dapps.js
src/pages-conditional/eth.js

We could refactor these to have a `titleKey` and a `descriptionKey`, and use with the imported `Translation` component within `CalloutBanner` instead. @mradziwon Hope this helps clarify, let us know if you have issues =)

**Comment by mradziwon** [comment]
@wackerow @minimalsm everything is clear now thanks.

**Comment by samajammin** [comment]
Ya this looks to be caused by #4768

**Comment by samajammin** [comment]
Agree with @wackerow, might as well refactor this as well to receive keys.

**Comment by minimalsm** [comment]
Closed by #5115
