### ISSUE TITLE
Better support for RTL languages

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5087]
**Is your feature request related to a problem? Please describe.**

Until now we haven't had significant amounts of RTL ([right-to-left-script](https://en.wikipedia.org/wiki/Right-to-left_script)) content on ethereum.org. With #5080 we translate our [Use Ethereum bucket](https://ethereum.org/en/contributing/translation-program/content-versions/#use-ethereum-pages) for Arabic and we'll soon have this bucket translated for Farsi (Persian). 

**Describe the solution you'd like**

For a better UX for those reading a RTL language we should make refactors to better support RTL.

**Additional context**

[Right-to-left script](https://en.wikipedia.org/wiki/Right-to-left_script)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SNikhill** [comment]
@minimalsm 
Sir, is there any way in which I could be of assistance with this?

**Comment by samajammin** [comment]
Thanks for volunteering @SNikhill!

I suspect the best next step is to outline specific changes we could make & align on approaches to implement those changes. @SNikhill feel free to make suggestions!

**Comment by minimalsm** [comment]
Hey @SNikhill, thanks for offering to help 😀

This is a pretty significant refactor. I think the highest value would be to follow the order of our [content-buckets](https://ethereum.org/en/contributing/translation-program/content-versions/). A very impactful first step would be having proper RTL support for our homepage (bucket one) As far as implementation goes we already [have some RTL support](https://github.com/ethereum/ethereum-org-website/search?q=rtl) but unsure if the approach we have taken is optimal, feel free to suggest alternative approaches if you come up with any—we're definitely open to ideas!

**Comment by SNikhill** [comment]
Okay, sure, sir. I shall see what a content bucket is and start with that.
Yes, I remember seeing that `isLangRightToLeft()` function. I shall let you know as I explore further and have any questions. :)

**Comment by SNikhill** [comment]
Things I noticed:
(NB: I shall be updating this list)

Language: Arabic (I don't understand it but, do know that it is RTL)
- [ ] If I am on the home page and select a code example, the same tends to be rendered in an incorrect way
![image](https://user-images.githubusercontent.com/51415616/150630738-e7674054-b8ab-40c6-b6c5-9e8bf867d173.png)

**Comment by SNikhill** [comment]
@minimalsm 

Sir, above are some things from the Home Page. Not all of them are a priority.

For Graphs are stuff, I shall like to suggest that on hover, the position of `origin` like 0,0 is shown. The same helps in identifying the direction the trend is progressing in.

**Comment by minimalsm** [comment]
@SNikhill ahh nice catch on the graph. Never even thought of that... could definitely be confusing 🤔

Any reason we wouldn't have this on by default (instead of just on hover)? Worth noting the ~40% of people on mobile wouldn't be able to use it if it was just available on hover. Also, we're making the assumption that people will hover over it with their mouse whilst viewing it.

Curious if anyone else has any input here.

**Comment by SNikhill** [comment]
Sure, we can have it on by default too. If the chart supports it and we can position it the right.

What about the other things? Is the stuff okay to proceed with?

**Comment by SNikhill** [comment]
@minimalsm 

Shall I proceed with other things?

**Comment by minimalsm** [comment]
Yes, @SNikhill, all of these seem in the scope of this issue to me. Do you have particular concerns?

**Comment by SNikhill** [comment]
Oh, I need to look at this.

**Comment by SNikhill** [comment]
@minimalsm 

Do you have any tips to optimise the build process? The local build seems to be taking quite long to proceed (and yes, I have increased the heap size to 8192).

**Comment by SNikhill** [comment]
(NB: I saw the single language tip later)

**Comment by SNikhill** [comment]
(NB: I shall be updating this list)
# Essential Page
--- [What is Ether(ETH)?](https://ethereum.org/ar/eth/)

- [ ]  Icons/Question Mark positions

  ![image](https://user-images.githubusercontent.com/51415616/179369628-b5b9e766-03e8-4e3e-a15c-8ee6dce93774.png)
  ![image](https://user-images.githubusercontent.com/51415616/179369658-715a0370-dd9e-451e-949f-9f6953d2a1b6.png)

**Comment by minimalsm** [comment]
Closing this out as we're handling this as part of Chakra migration.
