### ISSUE TITLE
Add more testnet faucets to Networks developer doc

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5090]
**Is your feature request related to a problem? Please describe.**

People are often frustrated by broken testnet faucets. The best immediate solution to this is to provide more choices on this page. In the case that one faucet goes down, they have other options.

**Describe the solution you'd like**

Add the following faucets (and any other reliable faucets) to the [Networks developer doc](https://ethereum.org/en/developers/docs/networks/#testnet-faucets):

- https://fauceth.komputing.org/
- https://faucets.chain.link/
- https://faucet.paradigm.xyz/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SarveshLimaye** [comment]
@minimalsm can I work on this issue?

**Comment by samajammin** [comment]
Thanks @SarveshLimaye, go for it! Just assigned you.
