### ISSUE TITLE
Add kovan testnet to /build page

### ISSUE THREAD

**Issue by evabeylin** [ethereum/ethereum-org-website#51]

**Comment by maurelian** [comment]
I heard somewhere that kovan might be deprecated or no longer supported by Parity and the initial kovan support group... 

but looking at the latest blocks in: 

- https://ropsten.etherscan.io: ~15 tx per block
- https://kovan.etherscan.io: ~25 tx per block
- https://rinkeby.etherscan.io: ~7 tx per block
- https://goerli.etherscan.io: ~0 tx per block

@jjmstark should we be reflecting or directing reality in this case?

**Comment by maurelian** [comment]
Oh, I found this: https://medium.com/paritytech/announcing-the-end-of-parity-support-for-kovan-9bdf815c807

Even parity seems to be directing people towards goerli, and I think it's the right way to go. 

So, I'd just list goerli (POA option), and ropsten (POW option), assuming ropsten is up to date with the mainnet (ie. supports create2), which I'm checking.
