### ISSUE TITLE
Fix typo on Block explorers page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5101]
**Describe the bug**

There is a typo in the following sentence: ''Blockscout – focusses on the following networks:''
'Focusses' is not the standard spelling.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/#block-explorers
2. Check the description for Blockscout
3. See error

**Expected behavior**

'Focusses' should be written an 'Focuses'

**Screenshots**

![Block explorers typo](https://user-images.githubusercontent.com/37338979/149528751-c5518cb2-ea9f-439b-bc48-a301ec27cd3c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: V1.34.80

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by guevaraf** [comment]
@lukassim please see the PR associated with this typo
