### ISSUE TITLE
Ethereum is not a state machine, but a Turing machine

### ISSUE THREAD

**Issue by garrivjo** [ethereum/ethereum-org-website#5104]
**Describe the bug**

In https://ethereum.org/en/developers/docs/evm/#from-ledger-to-state-machine, there is a sentence stating that
`For this more complex feature, a more sophisticated analogy is required. Instead of a distributed ledger, Ethereum is a distributed [state machine](https://en.wikipedia.org/wiki/Finite-state_machine)`. However, if you follow the link, it says that a state machine "can be in exactly one of a finite number of states at any given time". Besides, a state machine has no stack or memory.

The accurate term would be [Turing machine](https://en.wikipedia.org/wiki/Turing_machine).

Could you change https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/evm/index.md#from-ledger-to-state-machine-from-ledger-to-state-machine?

The title would be `From ledger to Turing machine {#from-ledger-to-turing-machine}`

The text would be `For this more complex feature, a more sophisticated analogy is required. Instead of a distributed ledger, Ethereum is a distributed [Turing machine](https://en.wikipedia.org/wiki/Turing_machine)`

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/evm/#from-ledger-to-state-machine
2. Scroll down to the second paragraph

**Expected behavior**

The title would be `From ledger to Turing machine {#from-ledger-to-turing-machine}`

The text would be `For this more complex feature, a more sophisticated analogy is required. Instead of a distributed ledger, Ethereum is a distributed [Turing machine](https://en.wikipedia.org/wiki/Turing_machine)`

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: Versión 97.0.4692.71 (Build oficial) (x86_64)

**Comment by garrivjo** [comment]
Could you assign this issue to me, please?

**Comment by minimalsm** [comment]
@all-contributors please add @garrivjo for ideas
