### ISSUE TITLE
DApp for ride sharing

### ISSUE THREAD

**Issue by joyboy114** [ethereum/ethereum-org-website#5106]
As time is growing, market competition becomes more fierce. So less skilled get paid lesser. 
Ride sharing has become one such example. Where there should be actually no dependence on third party as central authority.
Similar to this many handloom businesses pay very less and earn very high margin profit on the cost of development of working people.
We can create a unified solution for such problems 
And I think with the power of decentralised power of blockchain we can attain this goal.

**Comment by wackerow** [comment]
Hey @joyboy114, agree, but this is the repo for issue regarding the ethereum.org website. If you have ideas for apps I'd encourage you to get involved in the community to find others who may be interested in this. Gonna close this for now since it's off topic for this repo.
