### ISSUE TITLE
Added term to glossary: SNARK

### ISSUE THREAD

**Issue by mmilenkovic** [ethereum/ethereum-org-website#5119]
**Checklist**

- [x] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [x] This term/definition is not a product advertisement or contain other promotional content
- [x] This term/definition is directly relevant to Ethereum

**Term Name:**

SNARK

**Term Definition:**

Succinct Non-interactive ARgument of Knowledge a type of a zero-knowledge proof.

**Sources, if any (please do not submit copywrited content without appropriate approval):**

[From extractable collision resistance to succinct non-interactive arguments of knowledge, and back again](https://dl.acm.org/doi/10.1145/2090236.2090263)
Vitalik Buterin’s introduction to SNARKs:
- [part 1](https://medium.com/@VitalikButerin/quadratic-arithmetic-programs-from-zero-to-hero-f6d558cea649),
- [part 2](https://medium.com/@VitalikButerin/exploring-elliptic-curve-pairings-c73c1864e627), and 
- [part 3](https://medium.com/@VitalikButerin/zk-snarks-under-the-hood-b33151a013f6)

**Ethereum.org links?**

[Layer 2 rollups](https://ethereum.org/en/developers/docs/scaling/layer-2-rollups/)

**Additional context**

**Comment by minimalsm** [comment]
Thanks @mmilenkovic and agreed! We should add this to the glossary. Would you like to make a PR for this?

**Comment by mmilenkovic** [comment]
PR created https://github.com/ethereum/ethereum-org-website/pull/5208

**Comment by minimalsm** [comment]
Closed by #5208
