### ISSUE TITLE
Added term to glossary: STARK

### ISSUE THREAD

**Issue by mmilenkovic** [ethereum/ethereum-org-website#5120]
**Checklist**

- [x] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [x] This term/definition is not a product advertisement or contain other promotional content
- [x] This term/definition is directly relevant to Ethereum

**Term Name:**

STARK

**Term Definition:**

Scalable Transparent ARgument of Knowledge a type of a zero-knowledge proof.

**Sources, if any (please do not submit copywrited content without appropriate approval):**

[Scalable, transparent, and post-quantum secure computational
integrity](https://eprint.iacr.org/2018/046.pdf)
Vitalik Buterin’s introduction to STARKs:
- [part 1](https://vitalik.ca/general/2017/11/09/starks_part_1.html),
- [part 2](https://vitalik.ca/general/2017/11/22/starks_part_2.html), and 
- [part 3](https://vitalik.ca/general/2018/07/21/starks_part_3.html)

**Ethereum.org links?**

[Layer 2 rollups](https://ethereum.org/en/developers/docs/scaling/layer-2-rollups/)

**Additional context**

**Comment by minimalsm** [comment]
Thanks @mmilenkovic and agreed! We should add this to the glossary. Would you like to make a PR for this?

**Comment by mmilenkovic** [comment]
PR created https://github.com/ethereum/ethereum-org-website/pull/5208

**Comment by minimalsm** [comment]
Closed by #5208
