### ISSUE TITLE
Added term to glossary: Zero-knowledge proof

### ISSUE THREAD

**Issue by mmilenkovic** [ethereum/ethereum-org-website#5121]
**Checklist**

- [x] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [x] This term/definition is not a product advertisement or contain other promotional content
- [x] This term/definition is directly relevant to Ethereum

**Term Name:**

Zero-knowledge proof

**Term Definition:**

Zero-knowledge proof is a cryptographic method by which one party (the prover) can prove to another party (the verifier) that a given statement is true while the prover avoids conveying any additional information.

**Sources, if any (please do not submit copywrited content without appropriate approval):**

[ZKP science](https://zkp.science/)

**Ethereum.org links?**

[Layer 2 rollups](https://ethereum.org/en/developers/docs/scaling/layer-2-rollups/)

**Additional context**

**Comment by minimalsm** [comment]
Thanks @mmilenkovic and agreed! We should add this to the glossary. Would you like to make a PR for this?

**Comment by mmilenkovic** [comment]
PR created https://github.com/ethereum/ethereum-org-website/pull/5208

**Comment by minimalsm** [comment]
Closed by #5208
