### ISSUE TITLE
BigComicArt 

### ISSUE THREAD

**Issue by bigcomicart** [ethereum/ethereum-org-website#5122]
**Is your feature request related to a problem? Please describe.**
Adding my product to Ethereum Dapps page

www.BigComicArt.com has been live and producing NFTs with major established NFT platforms for going on 4 years.
Also see Cryptoarts.org
**Describe the solution you'd like**
Add Ethereum Product

Contributing to Ethereum.org 
**Describe alternatives you've considered**
Been contributing to the Ethereum network and community for over 4+ years

Established community, providing content and becoming a world-wide known NFT artist.
**Additional context**
Working with: Makersplace, SuperRare, WIthFoundation, Portion.io, Opensea, Rarible

<img width="794" alt="Screen Shot 2022-01-16 at 3 58 04 PM" src="https://user-images.githubusercontent.com/97853480/149677806-7fb59092-bf85-4c61-84aa-32df686ba8b5.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @bigcomicart thanks for raising this issue. 

Maybe I'm missing something but this doesn't appear to be a dapp?

**Comment by minimalsm** [comment]
Closing this out as per my comment above, feel free to comment and reopen if I've misunderstood here :-) thanks again.
