### ISSUE TITLE
Add Spanish "Introduction to Ethereum Development" course from Computer Society ITBA and Martin Triay 

### ISSUE THREAD

**Issue by mdedeu** [ethereum/ethereum-org-website#5124]
**Introducción a Ethereum Development**

**En este tutorial en español de 4 clases, un developer de web2 puede obtener los conocimientos básicos sobre web3, qué es Ethereum y qué son los Smart Contracts. Durante las clases vamos a ver aplicada esta tecnología, un ejemplo práctico de un smart contract en Solidity, las bases del lenguaje, cómo funciona el testing con Hardhat y cómo setear un entorno de desarrollo. Para finalizar, vamos a ver cómo deployar a una red local o pública y algunas cuestiones como Tokens o contratos inteligentes migrables.**

**Smart Contracts, Hardhat, Solidity, Deployment, EtherJS,  Testing, ERC-20, OpenZeppelin**

**Publicado el 25 de julio de 2021 por Youtube**

**Begginer**

**Youtube**

**https://youtube.com/playlist?list=PLTqiwJDd_R8y9pfUBjhkVa1IDMwyQz-fU**

**Comment by mdedeu** [comment]
@gilbertginsberg

**Comment by minimalsm** [comment]
Thanks @mdedeu, [see my comment in your other issue](https://github.com/ethereum/ethereum-org-website/issues/5128#issuecomment-1015337935) for next steps here ☺️

**Comment by minimalsm** [comment]
Closed by #5142
