### ISSUE TITLE
BOLTX

### ISSUE THREAD

**Issue by tehseen94** [ethereum/ethereum-org-website#5125]
Hello,

My name is Tehseen Waheed and I work as a Blockchain Partnership Manager at BOLT Global. We have our own crypto wallet which has been live for over 6 months. I have had a look at the requirements to list on ethereum.org and I believe our wallet (BOLTX) does fulfil all the various points mentioned on there. 

I would like to take this opportunity further and would like to supply with any more additional information needed from my end. Would you be able to help on how the process works and I will be able to share more information from our end.

Thank You

Kind regards,

Tehseen

**Comment by minimalsm** [comment]
Hi @tehseen94, thanks for suggesting this.

Could you please open a new issue with [the wallet template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2C+content+%3Afountain_pen%3A&template=suggest_wallet.md&title=) and fill out all of the relevant information for our team to review 😬?

**Comment by minimalsm** [comment]
Closing this out, please create an issue with the wallet template as instructed above. 😀
