### ISSUE TITLE
Add  Spanish"Introduction to Security and Hacking in Ethereum" course by Computer Society ITBA and Martín Abbatemarco

### ISSUE THREAD

**Issue by mdedeu** [ethereum/ethereum-org-website#5126]
**Introducción  a Seguridad y Hacking en Ethereum**

**El objetivo es que una vez terminado el curso, los participantes conozcan las técnicas utilizadas por auditores para detectar, probar y remediar las vulnerabilidades de seguridad más comunes en Smart Contracts.**

**Security, DeFi**

**17 de agosto de 2021 por Youtube**

**Intermediate**

**Youtube**

**https://youtube.com/playlist?list=PLTqiwJDd_R8yHOvteko_DmUxUTMHnlfci**

**Comment by mdedeu** [comment]
@gilbertginsberg

**Comment by minimalsm** [comment]
Thanks @mdedeu, [see my comment in your other issue](https://github.com/ethereum/ethereum-org-website/issues/5128#issuecomment-1015337935) for next steps here ☺️

**Comment by minimalsm** [comment]
Closed by #5142
