### ISSUE TITLE
Add  Spanish "Intoduction to DeFi Development" Course by Computer Society ITBA and Martín Triay

### ISSUE THREAD

**Issue by mdedeu** [ethereum/ethereum-org-website#5128]
**Introducción a DeFi Development**

**En este  crash course vamos a realizar una introducción a lo que es el mundo DeFi y vamos a dar un breve ejemplo de Defi en Solidity, el lenguaje de programación por excelencia de los smart contracts. El objetivo es que una vez terminado el curso, los participantes conozcan los términos más comunes en el ámbito DeFi, conozcan un pantallazo de los protocolos que existen y que tengan finalmente un acercamiento práctico al tema , a nivel de desarrollo.**

**DeFi , Testing**

**29 de noviembre de 2021**

**Intermediate**

**Youtube**

**https://youtube.com/playlist?list=PLTqiwJDd_R8zZiP9_jNdaPqA3HqoW2lrS**

**Comment by mdedeu** [comment]
@gilbertginsberg

**Comment by minimalsm** [comment]
Thanks for this @mdedeu 😀 excited to get more development resources in Spanish.

I think a good start would be adding this to our [language resources page](https://ethereum.org/en/community/language-resources/#es). [Here is the canonical page](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/community/language-resources/index.md) that needs editing. Would you like to open a PR for this?

To add it as a tutorial we'll need to do a small refactor (I've created a ticket) to support external tutorials in non-English languages. 

For context: on the English version of the website we have [both internal and external tutorials](https://ethereum.org/en/developers/tutorials/) but as we can't translate the external tutorials we hide them on [non-English versions of ethereum.org](https://ethereum.org/zh/developers/tutorials/). The refactor seems simple enough, once we get this functionality added we should make sure to add this video series there also.

**Comment by mdedeu** [comment]
> Thanks for this @mdedeu 😀 excited to get more development resources in Spanish.
> 
> I think a good start would be adding this to our [language resources page](https://ethereum.org/en/community/language-resources/#es). [Here is the canonical page](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/community/language-resources/index.md) that needs editing. Would you like to open a PR for this?
> 
> To add it as a tutorial we'll need to do a small refactor (I've created a ticket) to support external tutorials in non-English languages.
> 
> For context: on the English version of the website we have [both internal and external tutorials](https://ethereum.org/en/developers/tutorials/) but as we can't translate the external tutorials we hide them on [non-English versions of ethereum.org](https://ethereum.org/zh/developers/tutorials/). The refactor seems simple enough, once we get this functionality added we should make sure to add this video series there also.

Done! https://github.com/ethereum/ethereum-org-website/pull/5142

**Comment by minimalsm** [comment]
Closed by #5142
