### ISSUE TITLE
Update translation guide with up-to-date screenshots

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5139]
**Is your feature request related to a problem? Please describe.**

The translation guide has a [few outdated screenshots](https://ethereum.org/en/contributing/translation-program/translation-guide/#strings) that refer to 'Docking' (now known as the merge). It would be nice if we could update these images to a current equivalent. 

**Additional context**

![image](https://user-images.githubusercontent.com/62268199/149939559-99a933cc-a907-4ed3-beaa-d00f39024d7d.png)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@minimalsm I can look into it 🙂

**Comment by minimalsm** [comment]
Hey @vluna, thanks! I've assigned you 🙏
