### ISSUE TITLE
Update Readme.md to reflect new site organization & sub-pages

### ISSUE THREAD

**Issue by jjmstark** [ethereum/ethereum-org-website#515]
**Is your feature request related to a problem? Please describe.**

The site recently changed its high-level organization into 3 categories: Individuals, Developers, and Enterprise. However, the ReadMe still reflects the old organization.

**Describe the solution you'd like**
Update the readme.md to reflect new organization, providing contributors with useful information about how to think about each sub-page.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by samajammin** [comment]
@jjmstark some good feedback here from an experienced developer in the space when I asked what he thought of our [documented governance process:](https://github.com/ethereum/ethereum-org-website#-how-are-decisions-about-the-site-made)

> I think it's fine. I'd highlight the Check out our open issues and see if there are any you can help with! item, and add a "help-wanted" or "good-first-issue" label to those that would be nice for an external contributor to tackle. Otherwise, the list of current issues can be intimidating. Similarly, I feel the Notes on individual subpages can be a bit too much, and it wasn't clear to me how to map the subpages listed there to the ones in the actual site. It may help moving these notes to a different file, or making them shorter.
