### ISSUE TITLE
Add Pointer to the list of developer learning tools

### ISSUE THREAD

**Issue by kennethcassel** [ethereum/ethereum-org-website#5167]
Would love to have [Pointer](https://www.pointer.gg/) listed as one of the developer learning tools (under bootcamps). 

Pointer is a web3 dev education company that gives crypto rewards for devs who complete our interactive tutorials.

Over 100 developers have deployed a full-stack solidity app through our Solid Solidity tutorial. 

We've had some great [testimonials ](https://testimonial.to/pointer/all)and we would love to build more solidity/ethereum content! 

Happy to put in the PR if this is approved :)

**Comment by minimalsm** [comment]
Closed by #5216
