### ISSUE TITLE
BOLTX Wallet 

### ISSUE THREAD

**Issue by tehseen94** [ethereum/ethereum-org-website#5173]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**
-  Proper mechanism has been implemented to store and fetch user's cryptographic identities in a secured manner.  

**When did your wallet go live to users?**
- In the fourth quarter of 2019

**Does your wallet have an active development team?**
- yes

- yes

**Is your wallet open-source?**
- Not right now, but will soon be.

**Is your wallet globally accessible?**
- yes

**Is your wallet custodial, non-custodial, or a hardware wallet?**
- non-custodial

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
Local storage
User assumes security of own wallet. Not stored on any backend
Random 32 byte salt
Strengthen user's password by generating a randomised password based on salt and user's password
Random IV
Reduce chances of replay attacks and produce randomised cipher output
Browser secret
Randomised key generated by extension which serves as the browser unique id. 
"Authenticate the user's browser"
AES-GCM
AES encryption mode which provides in-built authentication
PBKDF2
Key derivation algorithm. Made to be computationally expensive to minimise brute-force based attacks
Random nonce
Additional security to add random strings into the plaintext so that no two data will encrypt to the same ciphertext (Prevent info leakage)
Re-encryption of data
Data is re-encrypted on every login.
Limited password retries
Password retries are limited to 10 tries with 1 minute of timeout in between. (Good to have an exponential increment in retry timeout)

**Does the wallet support layer 2 networks?**
Not right now. It will be implemented soon, and will be implemented by using the 1inch API.

**Can the wallet be used with arbitrary Ethereum RPC endpoint?**
- Nope. Endpoints are fixed

**Does the wallet have fiat on-ramps?**
- We are integrating Moonpay shortly

**Does the wallet allow users to explore dapps?**
- No

**Does the wallet have integrated defi/financial tools?**
- Not right now, but it will be. Right now it has a staking feature.

**Can a user withdraw to their card?**
- No

**Does the wallet offer limits protection?**
-No

**Does the wallet allow high-volume purchases?**
- No

**Does the wallet have an integrated token swap?**
- Not right now, will be using 1inch API 

**Is the wallet a multi-signature wallet?**
- No

**Wallet title**
- BOLTX

**Wallet description**
- BoltX is a crypto wallet with an user friendly UI to enable them to send, receive, and store Bitcoin and other cryptocurrencies including Ethereum and NFTs.It also provides staking feature to enable users to stake their BOLT tokens in order to earn rewards.Soon, it will be supporting NFTs: both ERC721 and Zilliqa NFTs, and the swaping feature to swap the tokens.

**Wallet logo**
https://faq.bolt.vision/resources/bolt-logos.

**Background colour for brand logo**
BOLT blue- #454AEA - #61C2ED, White- #FFFFFF

**URL**
https://www.boltx.app/wallet

**Comment by tehseen94** [comment]
Hi, Just wanted to find out if this ticket is still to be reviewed or have I missed something:)

**Comment by Clashinm** [comment]
I'm trying to get all my money back idk what I quit did
