### ISSUE TITLE
Fix typo on Ethereum Support page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5176]
**Describe the bug**

'Ergion' is a typo.

**To Reproduce**

1. Go to https://ethereum.org/en/community/support/
2. Go to Execution clients
3. Check item 4

**Expected behavior**

The correct spelling is 'Erigon'

**Screenshots**

![Erigon typo](https://user-images.githubusercontent.com/37338979/150659108-bbd6e377-37be-473b-8eb8-3619ebe4d822.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: V1.34.81

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by RishiKumarRay** [comment]
I am Interested to raise PR

**Comment by Aman-Mandal** [comment]
Am Interested! :)

**Comment by Clashinm** [comment]
I am interested!

**Comment by Ej1seven** [comment]
I already sent a pull request resolving this issue! Thanks!

**Comment by minimalsm** [comment]
@RishiKumarRay @Aman-Mandal @Clashinm 

Hey folks, thanks for the interest here. Looks like @Ej1seven already put up a PR to solve this. We'll be putting out a bunch of new issues for contributors soon :-) if you'd like to get pinged when we do this please be sure to [join the discord](https://discord.gg/CetY6Y4)
