### ISSUE TITLE
Add term to glossary: Execution Layer

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#5190]
**Checklist**

- [ x ] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [ x ] This term/definition is not a product advertisement or contain other promotional content
- [ x ] This term/definition is directly relevant to Ethereum

**Term Name:**
Execution Layer

**Term Definition:**

After the merge to proof-of-stake, existing Ethereum mainnet clients will continue to host the Ethereum Virtual Machine (EVM), validate transactions and execute state transitions but will not participate in consensus. These clients will therefore be referred to as "execution clients" and form Ethereum's "execution layer".

**Sources, if any (please do not submit copywrited content without appropriate approval):**

https://hackmd.io/@n0ble/the-merge-terminology

**Ethereum.org links?**

The execution layer is included in the FAQs at the bottom of this page: https://ethereum.org/en/upgrades/#eth2

**Additional context**

It will be useful to have the execution/consensus layer terms in the glossary for future articles that discuss post-merge Ethereum architecture.

**Comment by minimalsm** [comment]
Hey @jmcook1186 :-) agreed that we should add this. Would you like to take care of a PR for it?

I also think we should add 'execution client' and 'consensus client' (separately). Not sure how we should change this to avoid duplication but keep context 🤔

**Comment by jmcook1186** [comment]
ok, so maybe I can just add all four terms (ex client, ex layer, cons client, cons layer) in a single PR and close issues #5190 and #5191?
