### ISSUE TITLE
Add term to glossary: Consensus Layer

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#5191]
**Checklist**

- [ x ] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [ x ] This term/definition is not a product advertisement or contain other promotional content
- [ x ] This term/definition is directly relevant to Ethereum

**Term Name:**
Consensus Layer

**Term Definition:**

After the merge to proof-of-stake, consensus about the "true" head of the blockchain will be governed by a new set of clients running on the Beacon Chain. These are "consensus clients" and they form Ethereum's "consensus layer". These clients do not participate in validating transactions or executing state transitions, they request this to be done by execution clients.

**Sources, if any (please do not submit copywrited content without appropriate approval):**

https://hackmd.io/@n0ble/the-merge-terminology

**Ethereum.org links?**

The consensus layer is mentioned in the box at the bottom of this page: https://ethereum.org/en/upgrades/

**Additional context**

It will be useful to have the execution/consensus layer terms in the glossary for future articles that discuss post-merge Ethereum architecture.

**Comment by minimalsm** [comment]
Hey @jmcook1186 :-) agreed that we should add this. Would you like to take care of a PR for it?

**Comment by jmcook1186** [comment]
yep, on it.
