### ISSUE TITLE
Broken link to ETH staking on the Beacon Chain upgrade page

### ISSUE THREAD

**Issue by lingzhong** [ethereum/ethereum-org-website#5198]
**Describe the bug**

The link to information about ETH staking is broken (Resource Not Found) on the Beacon Chain upgrade page.

**To Reproduce**

1. Go to https://ethereum.org/en/upgrades/beacon-chain/
2. Click on 'stake your ETH' under the 'WHEN'S IT SHIPPING?' section
3. See 'Resource Not Found' error after being navigated to the https://ethereum.org/en/upgrades/staking/

**Expected behavior**

Expected to be navigated to a valid page relevant to staking ETH, perhaps the ETH staking landing page such as https://ethereum.org/en/staking/

**Screenshots**
![beacon_chain_upgrade_page](https://user-images.githubusercontent.com/4011137/150802267-d26a2a8b-e712-44e0-9882-848d16499dac.png)

![resource_not_found](https://user-images.githubusercontent.com/4011137/150801612-230f42ec-0480-4565-9076-3894719e8b31.png)

**Desktop (please complete the following information):**

- OS: MacOS 12.1
- Browser: Safari
- Version: 15.2 (17612.3.6.1.6)

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro
- OS: iOS 15.2.1
- Browser: Safari
- Version: 15

**Additional context**

N/A

**Want to contribute?**

Yes! Would love to help fix and test this bug with a PR :)

**Comment by minimalsm** [comment]
@lingzhong thanks for spotting this! && Appreciate your offering to create PR to fix this 😀 I've assigned you.

**Comment by minimalsm** [comment]
@lingzhong looks like there are 29 occurrences of this. Let's squash them all 😠🐛

<img width="478" alt="Screenshot 2022-01-24 at 15 14 00" src="https://user-images.githubusercontent.com/62268199/150809887-57186eb0-9224-492f-a8d7-3d91f20f2d42.png">

**Comment by lingzhong** [comment]
@minimalsm OOF! Sounds good, will combine all the link fixes into a single PR. Thanks for doing the sweep!

**Comment by minimalsm** [comment]
Hey @lingzhong, we're going to try to get this out in the next few hours. Do you have the capacity to get this done soon 😀?

**Comment by lingzhong** [comment]
@minimalsm Yes! I do have the capacity to get this out the door quickly. I'm ironing out the last bit of dev set up, and I already know where the code fixes would be. Thanks for the check!
