### ISSUE TITLE
Site Translation: Yoruba

### ISSUE THREAD

**Issue by amoweolubusayo** [ethereum/ethereum-org-website#522]
I have a task on the bounties network that involves me translating to my local language but my language Yoruba is not available.

Volunteers needed to complete this translation!
https://crowdin.com/project/ethereumfoundation/cs#

**Comment by samajammin** [comment]
Thanks for raising this issue @amoweolubusayo! Excited to get you up & running.

@sorumfactory please add this language to CrowdIn!

**Comment by sorumfactory** [comment]
@amoweolubusayo Thank you for the request! Now it's available on Crowdin :)
@samajammin Thank you for the reminder!
