### ISSUE TITLE
Add 2022 Ethereum events

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5221]
**Is your feature request related to a problem? Please describe.**

More events have been added to this sheet:
https://docs.google.com/spreadsheets/d/1NEu_FCc1hnGAuRgPmbXXpf0h2lCrCOlMKbbFEqgkVDQ/htmlview

**Describe the solution you'd like**

Add them to https://ethereum.org/en/community/events/

**Describe alternatives you've considered**

Should we also add a link to this spreadsheet? Seems like it's updated fairly reguarly.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
I can take care of this one.

**Comment by minimalsm** [comment]
Thanks @vluna, assigned! 😀💪
