### ISSUE TITLE
Add space to 'TheGraph' on the grants page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5246]
**Describe the bug**

The Graph is the name of an indexing protocol. On the grants page, there is a space missing between these two words.

**To Reproduce**

1. Go to ['...'](https://ethereum.org/en/community/grants/#project-specific)
2. Check the first item in the list
3. See error

**Expected behavior**

The correct spelling is 'The Graph'

**Screenshots**

![The Graph typo](https://user-images.githubusercontent.com/37338979/151376666-15f92b29-2056-4b36-9310-4b899216274b.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: V1.34.81

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ilkererkek** [comment]
I can take care of this issue.

**Comment by HursitTarcan** [comment]
I'll work on this.

**Comment by minimalsm** [comment]
Hey @ilkererkek :-) you can work on this. I've assigned you. Please ping if you need any help getting started.

**Comment by minimalsm** [comment]
@HursitTarcan thanks for offering but @ilkererkek replied first! We're uploading a bunch more good first issues so please keep your eyes open 😬
