### ISSUE TITLE
Add end punctuation to Ethereum Governance sentence

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5248]
**Describe the bug**

The following sentence should end with a period:
'Since so many people depend on Ethereum's stability, there is a very high coordination threshold for core changes, including social and technical processes, to ensure any changes to Ethereum are secure and widely supported by the community'

**To Reproduce**

1. Go to https://ethereum.org/en/governance/#ethereum-governance
2. Read the final sentence
3. See error

**Expected behavior**

The sentence should include end punctuation.

**Screenshots**

![Missing full stop](https://user-images.githubusercontent.com/37338979/151387717-053bbc55-5ab4-44eb-8cfa-c64c740771fd.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: V1.34.81

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by minimalsm** [comment]
Thanks for offering @adi611! 

Looks like @ihebu had already opened a PR (note: please comment if you've started work, to avoid duplicate PRs)

We've [opened a bunch more good first issues](https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) if you're interested in helping out!
