### ISSUE TITLE
Uncentered content on upgrades banner

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5260]
**Describe the bug**

In #5235 we implemented a banner on [all of our upgrades pages](https://ethereum.org/en/upgrades/). The banner isn't centered vertically.

**To Reproduce**

1. Go to 'https://ethereum.org/en/upgrades/'
2. See error

**Expected behavior**

The banner should be centered.

**Screenshots**

<img width="1273" alt="Screenshot 2022-01-28 at 10 58 40" src="https://user-images.githubusercontent.com/62268199/151536200-3e18ebf4-5b6d-426f-add1-36ce1c98ee3c.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@minimalsm I could potentially look at this one while working on #5261  as well if thats ok.

**Comment by minimalsm** [comment]
@vluna all yours 💪

**Comment by minimalsm** [comment]
Closed in #5283
