### ISSUE TITLE
Bad labelling on on upgrade banner link

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5261]
**Is your feature request related to a problem? Please describe.**

In #5235 we implemented a banner on [all of our upgrades pages](https://ethereum.org/en/upgrades/). The banner includes a link to the blog post announcement with the text 'More Info'. This is [poor UX and bad for accessibility](https://www.nngroup.com/articles/learn-more-links/).  

**Describe the solution you'd like**

We need to use a more descriptive link label. I would replace 'More info.' with 'Read the full announcement.'

**Describe alternatives you've considered**

Not being a word and grammar nerd.

**Additional context**

Feeling ambitious anon? We likely have more of these on the site, if you find them you can get a cookie 🍪

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
@minimalsm  I can take a look at this one.

**Comment by minimalsm** [comment]
Thanks @vluna ❤️  assigned.

**Comment by minimalsm** [comment]
Any update on this @vluna?

**Comment by vluna** [comment]
@minimalsm My apologies, I could not work on it over the weekend. I have submitted the PR now including the text update and alignment. Let me know if you want any changes done 🙂
