### ISSUE TITLE
Add Foundry as a developer framework

### ISSUE THREAD

**Issue by crisgarner** [ethereum/ethereum-org-website#5263]
**Product name:**

Foundry

**Product description:**

Foundry is a blazing fast, portable and modular toolkit for Ethereum application development written in Rust.

**How long has it been around?**

~6 months.

**Where do you think it should go?**

Frameworks: https://ethereum.org/en/developers/docs/frameworks/

**GitHub URL**

https://github.com/gakonst/foundry

**Docs URL**

Docs: https://onbjerg.github.io/foundry-book/index.html
List of tools for foundry:  https://github.com/crisgarner/awesome-foundry

**Is the product open source?**

yes

**Additional context**
Foundry is a fork of Dapptools faster with tons of new features that help to speed development.
Foundry consists of:

Forge: Ethereum testing framework (like Truffle, Hardhat, and Dapptools).
Cast: Swiss army knife for interacting with EVM smart contracts, sending transactions, and getting chain data.

**Comment by wackerow** [comment]
Hey @crisgarner! Thanks for the suggestion. I put up a PR (#5376) to add this to the developer frameworks listed.
