### ISSUE TITLE
Remove redundant closing bracket on the consensus-mechanisms page

### ISSUE THREAD

**Issue by haydenfowler** [ethereum/ethereum-org-website#5270]
**Describe the bug**

An additional closing bracket has been included on a hyperlink in the consensus-mechanisms page and should be removed.

**To Reproduce**

1. Go to the [consensus-mechanisms](https://ethereum.org/en/developers/docs/consensus-mechanisms/) page
2. Scroll down to `Sybil resistance & chain selection`
3. Note that a stand-alone closing bracket exists

**Expected behavior**

The redundant closing bracket has been removed.

**Screenshots**

![image](https://user-images.githubusercontent.com/9940216/151678901-0a03244d-b70c-447d-b3e5-ca87ec77523b.png)

**Desktop (please complete the following information):**

- OS: OSX 11.6
- Browser: Chrome
- Version: 97.0.4692.99

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by noahfigueras** [comment]
Just commited a fixed for this issue!

**Comment by haydenfowler** [comment]
@noahfigueras I should have mentioned, I've already put up a pull request which you can find [here](https://github.com/ethereum/ethereum-org-website/pull/5271).
