### ISSUE TITLE
Client-diversity developer doc not included in developer docs sidebar navigation

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5275]
**Describe the bug**

We added a [new page to our docs on client diversity](https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/) but forgot to add it to the developer docs sidebar 🤪!

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/'
2. Look between under 'Nodes and clients' in sidebar
3. See error

**Expected behavior**

Client-diversity should be displayed between 'Run a node' and 'Client-diversity'

**Additional context**

Adding the link to the [developer-docs-links.yaml](https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/developer-docs-links.yaml) should solve this issue.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by krvaibhaw** [comment]
I guess I can take care of that.

**Comment by minimalsm** [comment]
Thanks @krvaibhaw, all yours :-) feel free to ping if you need anything.

**Comment by minimalsm** [comment]
Closed by #5281
