### ISSUE TITLE
Broken header-ID on client diversity developer docs

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5276]
**Describe the bug**

We recently added [a new page on client-diveristy](https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/). The header ID for 'Use a minority client' is broken.

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/'
2. Scroll down to 'Use a minority client'
3. See error

**Expected behavior**

- The header-id should work correctly. 
- Curly brackets should not be visible after the heading.

**Screenshots**

<img width="767" alt="Screenshot 2022-01-31 at 09 55 02" src="https://user-images.githubusercontent.com/62268199/151772949-d77db3fa-8789-41cc-80dc-3e1a0d1e04ea.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ihebu** [comment]
Can I work on this one ?

**Comment by minimalsm** [comment]
@ihebu would like to get this patched in the next few hours. if that is ok, please do :-) ❤️
