### ISSUE TITLE
Treat 'the Merge' as a proper noun

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5278]
**Is your feature request related to a problem? Please describe.**

The Merge should be treated as a proper noun as it refers to a specific, non-generic event. 

> _A proper noun is a specific (i.e., not generic) name for a particular person, place, or thing._ 

**Describe the solution you'd like**

We currently treat it as a common noun (i.e. '_Once the merge happens_'). We should search the codebase for all instances of 'the merge' and change them to use the proper noun (the Merge or The Merge if at the beginning of a sentence).

**Describe alternatives you've considered**

Leaving the Merge as a common noun.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by minimalsm** [comment]
Hey @adi611, thanks for offering to help. 

This is temporarily blocked whilst we decide if this should always be 'The Merge' or if 'the Merge' is correct in the middle of a sentence 😬 

Will ping you (probably tomorrow) after we decide.

**Comment by minimalsm** [comment]
Hey @adi611, looks like we're going with 'The Merge' (always uppercase 'The'). Feel free to open a PR for this :-)
