### ISSUE TITLE
Smart contracts for testing description should be italicize to match with the overall aesthetic

### ISSUE THREAD

**Issue by krvaibhaw** [ethereum/ethereum-org-website#5295]
**Describe the bug**

Smart contracts for testing description should be italicize to match with the overall aesthetic

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/programming-languages/python/
2. Scroll down to PYTHON PROJECTS AND TOOLS
3. See the last entry "Smart contracts for testing" under Active section.

**Expected behavior**

Smart contracts for testing description should match with the overall aesthetic by italicize its description.

**Additional context**

Updating this index.md file `src/content/developers/docs/programming-languages/python/index.md` will solve the issue

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by krvaibhaw** [comment]
@minimalsm I have fixed this issue.
Related PR : Update Smart contracts for testing description to match with the overall aesthetic #5296

**Comment by minimalsm** [comment]
Closed in #5296, thanks @krvaibhaw 💪
