### ISSUE TITLE
Add date formats to the style guide

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5299]
**Is your feature request related to a problem? Please describe.**

Noticed on https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/#current-client-diversity

"The execution layer data were obtained from Ethernodes on 23/01/22"

**Describe the solution you'd like**

We should outline a consistent date format (at least for English) in the style guide:
https://ethereum.org/en/contributing/style-guide/

**Comment by chiholiu10** [comment]
May I solve this issue?

**Comment by Epict33tus** [comment]
Changed to format on the source site, edit to reduce confusion
<img width="310" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/32387143/5f6c6b93-f4b2-488d-aefc-7f83be89acf4">

**Comment by Epict33tus** [comment]
https://github.com/ethereum/ethereum-org-website/pull/10784

**Comment by wackerow** [comment]
Resurfacing this...

For React components, we can use `Intl.DateTimeFormat` and pass the locale so it's formatted according to locale, but for markdown content, this is up to the author. As such, I agree we should add a note to our style guide to set up a consistent way to address dates so they are consistent and un-ambiguous.

Given the use of both D/M/Y and M/D/Y in English speaking places, I would recommend we use D-Mon-YYYY format (ie, 2-Nov-2023, or 11-Feb-2023) which removes any ambiguity between month and day. Just my opinion though, open to thoughts from others, cc: @minimalsm @corwintines 

I would target this file for the explanation: `src/content/contributing/style-guide/content-standardization/index.md`

@Epict33tus Any chance you'd like to work on this? Or anyone else?
