### ISSUE TITLE
Change “Fork this page” / GitHub icon

### ISSUE THREAD

**Issue by bmann** [ethereum/ethereum-org-website#53]
The “fork this page” is confusing to many. 

On mobile, the GitHub icon is always present, and just links to the GitHub for the website without any context. 

Suggestion: change wording to “Get Involved” and make a Get Involved page that has links to the GitHub and explains how the website is managed.

Thinking about this more, having this on every page is overkill. Maybe in the footer - “See an error, have a suggestion, or want to make an improvement to this page or site? Get involved”

On mobile, probably remove the icon altogether and people can navigate to the “Get Involved” page via the menu.

**Comment by jjmstark** [comment]
@alancwoo what do you think?

Personally:

- I'm OK removing the GH icon on mobile, where I agree it isn't useful
- I don't think we need a separate "Get involved" page right now - the readme.md on Github serves that purpose
- I'd prefer to keep a "fork me" button of some kind on every page, for now. The fact that ethereum.org is now a website that is being actively updated and evolving is a very important thing to communicate to the user, and to the community in general. Even if not everyone wants to contribute, having this on the page is important information about what ethereum.org is.

**Comment by bmann** [comment]
I’m saying that if you want bring people down the funnel of interaction, that “fork me” (which isn’t what you want — you actually want update me or PR me) only speaks to developers (at best). 

I absolutely think in the footer (or somewhere) signally “Get Involved” is important as a global call to action. 

The README solves (some) of the info — but is only for developers. Can we use Ethereum.org to recruit non technical people? If so a page that we can all link to like ethereumDotOrg/getinvolved helps with that. 

I’ll see if I have time to PR a first draft this week.

**Comment by jjmstark** [comment]
What do you mean by "[the README] is only for developers"? Do you mean that you think the content of the Readme is too technical? Or that because it is on Github, only developers would read / interact with it?

**Comment by bmann** [comment]
Yes, because it's on GitHub, it by default speaks to developers. Basically, I want to advocate that the website has a message of "get involved" -- and that that is the broadest group of people.

**Comment by EvanVanNessEth** [comment]
Changing away from "fork this page" might make sense, but only if we're going to move away from requiring Github PRs and to a separate process.   

Until we have a separate process that has consensus, I don't think it makes sense to change "fork this page"

**Comment by bmann** [comment]
@EvanVanNessEth I’m not super worried about messaging to people with the technical skills to do PRs. My suggestion is that we can make a broader invitation to participate. 

Anyway. I will see about a PR for the icon to start.

**Comment by EvanVanNessEth** [comment]
why would we issue a broader invitation when you need the skills to do a github PR in order to participate?

**Comment by bmann** [comment]
Because there are ways to contribute to the community beyond updating the website, and as I have written above, a general call of “Get Involved” is a great message to send. 

If the home page for the Ethereum ecosystem doesn’t want to send a message of Get Involved other than PRs to the website — that’s fine.

**Comment by jjmstark** [comment]
Yeah, I think there are two things being discussed here:

1. Phrasing of the text that links people to this Github repo, where community members can contribute to the site.

2. Whether ethereum.org should contain a **more general** call to action to "Get involved in the community", which includes contributing to this website repo, but might also include other things that are approachable for non-developers

I think @EvanVanNessEth is making good points re: (1), and that (I think) what @bmann cares more about is (2). One thing that I know has been discussed is adding a "Community" sub-page to the site, which would have information about local meetups, hackathons, various community organizations, various online forums/groups, etc. 

@bmann if that is what you're interested in seeing here, maybe we could open up a separate issue to work out what kind of content would be on such a page?

**Comment by bmann** [comment]
I would call the page “Get Involved” but yes sure I can do that ;)

**Comment by jjmstark** [comment]
To close the loop on this:

@alancwoo unless you have any objections, could you submit a PR which removes the Github icon in the mobile version of the site? 

I'm going to close this, anticipating that we can continue the discussion in a separate issue about adding a page which aims to help users "get involved" in the Ethereum community.
