### ISSUE TITLE
Add Encode Club to developer learning tools

### ISSUE THREAD

**Issue by Vienio99** [ethereum/ethereum-org-website#5343]
**Is your feature request related to a problem? Please describe.**

Add [Encode Club](https://www.encode.club/) to [developer learning tools page](https://ethereum.org/en/developers/learning-tools/) under the bootcamp section.

**Describe alternatives you've considered**

Remove Vyper.fun because the website is no longer available, add dots at the end of descriptions for consistency

**Additional context**

[This is a similar PR ](https://github.com/ethereum/ethereum-org-website/pull/3966)to use as a reference

**Want to contribute?**

Yes, please assign the issue to me

**Comment by minimalsm** [comment]
Closed in #5344
