### ISSUE TITLE
Missing copy on /get-eth/ banner

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5352]
**Describe the bug**

**To Reproduce**

1. Go to https://ethereum.org/en/get-eth/
2. Scroll down to bottom banner
3. See error

![Image 2022-02-03 at 9 47 34 AM](https://user-images.githubusercontent.com/8097623/152818000-312ca4b5-09b9-447a-a514-fa930350629f.jpg)

**Expected behavior**

Should be text above the button.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Fixed in #5356 🎉
