### ISSUE TITLE
Add to glossary: "Sync Committee"

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#5365]
**Checklist**

- [x ] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [x ] This term/definition is not a product advertisement or contain other promotional content
- [x ] This term/definition is directly relevant to Ethereum

**Term Name:**

Sync Committee

**Term Definition:**
a subset of 512 validators on Ethereum's consensus layer that sign off blocks so that light clients can validate the chain without having to access the full chain history. Sync committees are randomly chosen from the full validator set and refreshed about every 27 hours. 

**Sources, if any (please do not submit copywrited content without appropriate approval):**
https://notes.ethereum.org/@vbuterin/HF1_proposal

p.s. please assign me to this issue if you agree and I will raise a PR

**Comment by wackerow** [comment]
This looks great @jmcook1186, agree this would make a nice addition to the glossary. 

We can fine-tune details in the PR, but I did not that Vitalik's post notes that sync committees consist of 1024 validators... I didn't see 512 noted anywhere, let's just double-check this. 

Just assigned you, thanks!

**Comment by jmcook1186** [comment]
I think 1024 was the original intention but it was updated to 512 by the time of the altair update. It is 512 in the altair specs (https://github.com/ethereum/annotated-spec/blob/master/altair/sync-protocol.md#introduction).
