### ISSUE TITLE
Add to glossary: "Supermajority"

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#5366]
**Checklist**

- [x ] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [x ] This term/definition is not a product advertisement or contain other promotional content
- [x ] This term/definition is directly relevant to Ethereum

**Term Name:**

Supermajority

**Term Definition:**
Supermajority is the term given to validators who control more than 2/3 of the total staked ether on PoS Ethereum. This is important because a supermajority is required for the chain to finalize.

**Sources**
https://ethos.dev/beacon-chain/

p.s. please assign me to this issue if you agree and I will raise a PR

**Comment by wackerow** [comment]
This looks good... again, we can fine tune the copy in the PR, but not against adding this to the glossary. Curious thoughts on maybe even adding another entry for "supermajority client" where we can touch on the problem of one client having a potential supermajority to finalize on its own. Sheds more light on the client diversity topic.
