### ISSUE TITLE
Solidity version conflict in tutorial

### ISSUE THREAD

**Issue by kurumbus** [ethereum/ethereum-org-website#5389]
I was following this tutorial:
https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/

And got this error:
Error HH606: The project cannot be compiled, see reasons below.
The Solidity version pragma statement in these files doesn't match any of the configured compilers in your config. Change the pragma or configure additional compiler versions in your hardhat config.
  * @openzeppelin/contracts/utils/Address.sol (^0.8.1)

But when I changed solidity version in hardhat.config.js 

module.exports = {
  solidity: "0.8.1",
///
}

and MyNFT.sol:
pragma solidity ^0.8.1;

The bug disappeared. Should I create a PR with changing tutorial's text?

Sorry if I broke the protocol, I'm new here.

**Comment by IamAmitK** [comment]
I think it should be fine, since you have changed the pragma version in hardhat, it won't be necessary. Just make sure if you are creating a new sol file, keep the same pragma version.

**Comment by stephenhuh** [comment]
same issue here, used resolution mentioned above - would be great to get a PR in to reflect the solution.

**Comment by lingzhong** [comment]
Created PR #5530 to fix this compilation error in NFT tutorial. @minimalsm Seeking review 🏗

**Comment by lingzhong** [comment]
Friendly bump on the PR reviews :) Should be quick; Thanks in advance!
