### ISSUE TITLE
Add to glossary: "LMD_GHOST"

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#5392]
**Checklist**

- [ x ] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [ x ] This term/definition is not a product advertisement or contain other promotional content
- [ x ] This term/definition is directly relevant to Ethereum

**Term Name:**

LMD-GHOST

**Term Definition:**

LMD_GHOST is the fork choice mechanism used by Ethereum's consensus clients to identify the head of the blockchain. They do this by observing which has the greatest accumulation of attestations in their history.

**Sources**

https://arxiv.org/abs/2003.03052

**Additional context**
Definition above is a bit of a placeholder - will refine in PR if assigned

**Comment by victorlrz** [comment]
Hello I would like to take this feature please :)

**Comment by jmcook1186** [comment]
i already opened PR #5396 - feel free to suggest edits

**Comment by minimalsm** [comment]
Solved in #5396
