### ISSUE TITLE
Site Translation: Add Arabic

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#541]
### Prize Bounty
100 DAI

### Challenge Description
Arabic translations are completed, reviewed & ready to to be added to the website!

### Submission Requirements
[This previous PR](https://github.com/ethereum/ethereum-org-website/pull/282/files) may be a useful reference. Below are the steps required to add a new language:
1. Download the [markdown files from CrowdIn](https://crowdin.com/project/ethereumfoundation/ar#). You may need to sign up for CrowdIn & join our project in order to download the files - here's the [invite link](https://crowdin.com/project/ethereumfoundation/invite).
2. Add markdown files in a new /docs/ar/ directory
3. Add nav to config.js (`locales` key)
4. Update the homepage markdown file (the root index.md) to use the `HomePage.vue` component
  - Move that content into translations.js (again, it helps to follow [this previous PR](https://github.com/ethereum/ethereum-org-website/pull/282/files))
  - Add `layout: home` in page [front matter](https://vuepress.vuejs.org/guide/frontmatter.html)
5. In each newly added markdown file...
- [Front matter](https://vuepress.vuejs.org/guide/frontmatter.html)
  - Add `meta` property (i.e. `og:title`) - check out other translation markdown files for reference
  - Confirm it has (correct) `lang` property
  - Remove `date` fields (if they exist)
  - Add `sidebar: auto` for /learn & /developers pages
- Add [explicit heading IDs](https://www.markdownguide.org/extended-syntax/#heading-ids) to each primary header (`#`) & secondary header (`##`) to match the English file versions. For more context on why we do this, [see here](https://github.com/ethereum/ethereum-org-website/issues/272)
  - e.g. `## Začíname {#getting-started}` from /docs/sk/developers/index.md
- Update relative links (i.e. add language path)
  - e.g. a link to the /use page within the /docs/ar/beginners/index.md file should link to ethereum.org/ar/use, not ethereum.org/use

### Judging Criteria
The prize will be awarded to the first valid submission.

### Winner Announcement Date
We will review work within a week of submission. Payouts will occur within a week of submission acceptance.

**Comment by EmanHerawy** [comment]
Happy to translate the content in CrowdIn and the website :D 
#583 
I would love to hear your feedback.

BTW I have noticed that the content in CrowdIn is not updated. Is there any way to sync ?

**Comment by samajammin** [comment]
Thanks for completing this @EmanHerawy! This [has been deployed](https://ethereum.org/ar/) so I'm closing this out.

> BTW I have noticed that the content in CrowdIn is not updated. Is there any way to sync ?

Great question! It's on our list to set this up. You can see more & discuss here: #589
