### ISSUE TITLE
Site Translation: Add Igbo

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#542]
### Prize Bounty
100 DAI

### Challenge Description
Igbo translations are completed, reviewed & ready to to be added to the website!

### Submission Requirements
[This previous PR](https://github.com/ethereum/ethereum-org-website/pull/282/files) may be a useful reference. Below are the steps required to add a new language:
1. Download the [markdown files from CrowdIn](https://crowdin.com/project/ethereumfoundation/ig#). You may need to sign up for CrowdIn & join our project in order to download the files - here's the [invite link](https://crowdin.com/project/ethereumfoundation/invite).
2. Add markdown files in a new /docs/ig/ directory
3. Add nav to config.js (`locales` key)
4. Update the homepage markdown file (the root index.md) to use the `HomePage.vue` component
  - Move that content into translations.js (again, it helps to follow [this previous PR](https://github.com/ethereum/ethereum-org-website/pull/282/files))
  - Add `layout: home` in page [front matter](https://vuepress.vuejs.org/guide/frontmatter.html)
5. In each newly added markdown file...
- [Front matter](https://vuepress.vuejs.org/guide/frontmatter.html)
  - Add `meta` property (i.e. `og:title`) - check out other translation markdown files for reference
  - Confirm it has (correct) `lang` property
  - Remove `date` fields (if they exist)
  - Add `sidebar: auto` for /learn & /developers pages
- Add [explicit heading IDs](https://www.markdownguide.org/extended-syntax/#heading-ids) to each primary header (`#`) & secondary header (`##`) to match the English file versions. For more context on why we do this, [see here](https://github.com/ethereum/ethereum-org-website/issues/272)
  - e.g. `## Začíname {#getting-started}` from /docs/sk/developers/index.md
- Update relative links (i.e. add language path)
  - e.g. a link to the /use page within the /docs/ig/beginners/index.md file should link to ethereum.org/ig/use, not ethereum.org/use

### Judging Criteria
The prize will be awarded to the first valid submission.

### Winner Announcement Date
We will review work within a week of submission. Payouts will occur within a week of submission acceptance.

**Comment by EnochMbaebie** [comment]
ready to be reviewed

**Comment by samajammin** [comment]
Hey @EnochMbaebie - someone just pointed out to me [your work in your fork](https://github.com/EnochMbaebie/ethereum-org-website/commit/c14b5b9d9a4a746498889e95641756657dec94b2). To submit work for a bounty, please make sure you submit a PR to this repo! You can learn how to do that [here](https://github.com/ethereum/ethereum-org-website#deployment-lifecycle). Sorry if there was confusion around how to contribute. If there's ways you think we could improve communication, please let me know.

Unfortunately someone already solved this bounty last week (https://github.com/ethereum/ethereum-org-website/pull/580) but please keep an eye out for future bounties!

**Comment by samajammin** [comment]
Hey @karansinghgit - please submit to the bounty here so we can pay you out: https://ethscholars.bounties.network/bounty/3748

Thanks!
