### ISSUE TITLE
Ethereum 2.0 Learning Guide for Absolute Beginners

### ISSUE THREAD

**Issue by arinddas** [ethereum/ethereum-org-website#5433]
##  **New learners can follow the document and learn the basic concepts around ETH 2.0**

# OVERVIEW

ETH 2.0 is going through major updates each day, many teams are working to create eth2.0 clients for next gen ethereum platform upgradation. ETH 2.0 comes with some major changes in architecture and functionality. 
 

1. POS (proof of stake consensus) mechanism 
2. Validators, Shard chain & Beacon chain ( the main chain after POS - consensus layer) 
3. Phases of launch 
4. How to participate as validators  
5. Eth 2.0 client with existing eth1.0 client 
6. Sharding in details - advanced 
7. Various nodes to support consensus with sharding like supernode, single shard node, light node etc. 
8. What’s new. 
9. Teams working 

Above mentioned topics are very basic to understand about eth2.0. 

**1. POS (Proof of Stake):** 

It is assumed that we all know about current POW protocol and pitfalls about the same. Which triggers the inception of POS on ethereum chain. 

Initial understanding of consensus mechanisms: (POW & POS) 
 
[Consensus mechanisms | ethereum.org](https://ethereum.org/en/developers/docs/consensus-mechanisms/)

 
Then we need to understand about , how ethereum is building the POS in high level  
 
[Proof-of-stake (PoS) | ethereum.org](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/)

**2. Validators, Shard Chain and Beacon Chain:**

**Validators:**
Validators will have to stake a minimum amount of eth (aka stake) to validate and create a block for POS consensus.Proof-of-stake is the underlying mechanism that activates validators upon receipt of enough stake. For Ethereum, users will need to stake 32 ETH to become a validator. Validators are chosen at random to create blocks and are responsible for checking and confirming blocks they don't create. 

**Beacon chain:**
Beacon chain will act as consensus layer chain for proof of stake. Beacon chain will also get the information from shard chain for coordination between them and act as master. Validators aka super nodes can join Beacon-chain as POS block creators. \
 
**Shard chain:**
Sharding is the process of splitting a database horizontally to spread the load – it’s a common concept in computer science. In an Ethereum context, sharding will reduce network congestion and increase transactions per second by creating new chains, known as “shards”. 
 
Shard chains are separate blockchains that will need validators to process transactions and create new blocks. The plan is to have 64 shard chains, with each having a shared understanding of the state of the network. As a result, extra coordination is necessary and will be done by the beacon chain. 
 
When the first shard chains are shipped they will just provide extra data to the network. They won’t handle transactions or smart contracts. But they’ll still offer incredible improvements to transactions per second when combined with rollups.

Rollups are a "layer 2" technology that exists today. They allow dapps to bundle or “roll up” transactions into a single transaction off-chain, generate a cryptographic proof and then submit it to the chain. This reduces the data needed for a transaction. Combine this with all the extra data availability provided by shards and you get 100,000 transactions per second.

**No account Execution (EOA or contract):** 
The Beacon Chain will conduct or coordinate the expanded network of shards and stakers. But it won't be like the Ethereum Mainnet of today. It can't handle accounts or smart contracts.

The Beacon Chain’s role will change over time but it’s a foundational component for the secure, sustainable and scalable Ethereum. 

**Shard chain - contract execution:**
It is planned in future to execute smart contracts on shard chains.

Read in brief here:  
[https://ethereum.org/en/upgrades/beacon-chain/](https://ethereum.org/en/upgrades/beacon-chain/) 

[https://ethereum.org/en/upgrades/shard-chains/](https://ethereum.org/en/upgrades/shard-chains/) 
 
**3. Phases:** 
 
**• Phase 0:** the beacon chain. Launched on 1 December 2020. This is the core chain that makes sure the shards across the network are kept in sync. It achieves this using validators.

**• Phase 1:** the shard chains. Expected 2022. Ethereum’s data and transactions will be run on shard chains. These are proof-of-stake blockchains that use validators to confirm transactions, create blocks and communicate with the beacon chain.  It is expected that Ethereum 2 will begin with 64 shards. At this point, they will not be supporting smart contracts or accounts.

**• Phase 1.5:** the legacy Ethereum chain becomes a shard on the new Ethereum blockchain. Expected 2022. In this phase, the legacy Ethereum network will transition to a proof-of-stake network and be connected to the main Ethereum 2 chain.

**• Phase 2:** shards fully functioning. Expected 2022. The shard chains will be fully functioning and able to communicate with each other and run smart contracts.

**Read in details:** 
[What is Ethereum 2.0? | ConsenSys](https://consensys.net/blog/blockchain-explained/what-is-ethereum-2/) 

[Validated: Staking on eth2 #0 | Ethereum Foundation Blog](https://blog.ethereum.org/2019/11/27/validated-staking-on-eth2-0/)

**4. How to participate as validators:**

To be a validator you need a validator node as well as a validator client. Various teams are building this validator client alongside the main protocol development. 
 
If we relate with eth1.0 , we had geth client(go-client) to establish a full node, in the same way we have many validator clients written in different programming languages. 

![image1](https://user-images.githubusercontent.com/25406823/154212938-fa649139-dbba-4218-a697-c60ddbb3ca1e.PNG)

_Read more at:_
[Ethereum 2.0 and the Seven Clients | by Somer Esat](https://someresat.medium.com/ethereum-and-the-seven-clients-648815c4ac71)

[My Journey to Becoming a Validator on Ethereum 2.0 | ConsenSys](https://consensys.net/blog/blockchain-explained/my-journey-to-becoming-a-validator-on-ethereum-2-0/)

**Testnet validators on Gorilla testnet:**  

[https://prater.launchpad.ethereum.org/en/overview](https://prater.launchpad.ethereum.org/en/overview) 
[How to Set Up an ETH 2.0 Validator (on Goerli Testnet) | Alexandria](https://coinmarketcap.com/alexandria/article/how-to-set-up-an-eth-2-0-validator-on-goerli-testnet) 

**5. Eth 2.0 client with existing eth1.0 client:**

Transactions and applications will still continue as normal on Ethereum, maintained by the same software clients we use today. In this sense, the terms Eth1 and Eth2 actually represent different layers of the stack: execution and consensus.  

Execution clients (Eth1 clients). Responsible for transaction bundling, execution, and state management. This layer is already represented by clients that Ethereum uses daily, such as Geth, OpenEthereum, Hyperledger Besu, and Nethermind. 

Consensus clients (Eth2 clients). Responsible for the validating blocks, also known as the Beacon Chain. This consensus-layer has been running smoothly for more than 6 months, with 155,663 validators collectively staking 4,981,046 ETH. Client teams include Teku, Lighthouse, Nimbus, and Prysm.

![image2](https://user-images.githubusercontent.com/25406823/154239537-04d0ec49-7dfe-4b72-b88c-94a0ceb155cf.PNG)

Read more: (must)

[Charting The Path To Proof of Stake Ethereum | ConsenSys](https://consensys.net/blog/blockchain-explained/charting-the-path-to-proof-of-stake-ethereum/)

[Ethereum 2.0 FAQ | ConsenSys](https://consensys.net/knowledge-base/ethereum-2/faq/)  

**6. Sharding in details - advanced:**

One basic question must have triggered your mine, can we shard our existing chain with POW consensus. The answer is ‘NO’. But why? 
_Read this great article explaining the same:_ 
[Why PoS was Necessary for Ethereum's Sharding - Mango Research](https://www.mangoresearch.co/why-pos-was-necessary-for-ethereums-sharding/#:~:text=PoS%20allows%20for%20easy%20sampling,theoretically%20breaking%20the%20blockchain%20trilemma.https://eth.wiki/sharding/Sharding-FAQs)

_If you are interested in learning the shard in more details, here is the good link of the same:_

[Sharding-FAQs | Ethereum Wiki](https://eth.wiki/sharding/Sharding-FAQs)

**7. Node types in 2.0:**

<span style="text-decoration:underline;">Super-full node</span> - fully downloads every collation of every shard, as well as the main chain, fully verifying everything.

<span style="text-decoration:underline;">Top-level node</span> - processes all main chain blocks, giving them “light client” access to all shards.

<span style="text-decoration:underline;">Single-shard node</span> - acts as a top-level node, but also fully downloads and verifies every collation on some specific shard that it cares more about.

<span style="text-decoration:underline;">Light node</span> - downloads and verifies the block headers of main chain blocks only; does not process any collation headers or transactions unless it needs to read some specific entry in the state of some specific shard, in which case it downloads the Merkle branch to the most recent collation header for that shard and from there downloads the Merkle proof of the desired value in the state."

A good discussion: [Node types in Ethereum 2.0 - Sharding](https://ethresear.ch/t/node-types-in-ethereum-2-0/3668) 

**8. What’s going on eth2.0:** 

First eth2.0 merge testnet is there, various teams faced problems like ‘Geth Panic’ etc. Be updated with latest dev / network updates.

[What's New in Eth2 - 14 January 2022](https://hackmd.io/@benjaminion/eth2_news/)

[Announcing the Kintsugi Merge Testnet | Ethereum Foundation Blog](https://blog.ethereum.org/2021/12/20/kintsugi-merge-testnet/)

**9. Teams working for ETH 2.0:**

Hundreds of people! The work is largely led and coordinated by the Ethereum Foundation research team, but many other research and implementation teams are making substantial contributions. The main work is to collaborate on defining the specification for Ethereum 2.0, which is maintained on the Ethereum Foundation GitHub pages. Five independent teams are building Ethereum 2.0 clients in a variety of different programming languages for different use cases and are constantly feeding back into the design and specifications. ConsenSys Quorum is building Teku, which is written in Java and maintained by the same team behind Hyperledger Besu.

Link: [Teams building on Eth 2.0 - EthHub](https://docs.ethhub.io/ethereum-roadmap/ethereum-2.0/eth2.0-teams/teams-building-eth2.0/)

**More useful resources:**

[ETH2 for Dummies. By Grant Hummer | by Chromatic Capital | Medium](https://medium.com/@chromaticcapital/eth2-for-dummies-11ff9b11509f)

[Ethereum 2.0 Devs Handbook and FAQs - HackMD](https://notes.ethereum.org/@serenity/handbook)

[Ethereum 2.0 Info - HackMD](https://hackmd.io/@benjaminion/eth2_info)

[ETH2 sharding - 思維導圖](https://www.mindomo.com/zh/mindmap/eth2-sharding-4408ec348bee4501aa125c3e3cd251d3) 

_“Trust is our product. We’re okay being the tortoise in the race.” — Kristen Mirabella_

**Comment by minimalsm** [comment]
Hey @arinddas 

I'm not quite sure what this issue is for but if you're suggesting adding this to the site we already cover these changes in great detail across the relevant pages. Sounds like a good blog post though, thanks for writing it up!

FYI [the ecosystem is moving away from Eth2.0 terminology](https://blog.ethereum.org/2022/01/24/the-great-eth2-renaming/).

Closing this issue out, thanks again 🙏

**Comment by arinddas** [comment]
Thank you for your response. @minimalsm. If you can suggest where can I put my thought process as a blog to official ethereum community. 

Thanks for the link.
