### ISSUE TITLE
Ropsten faucet doesn't seem to work, maybe recommend metamask facuet instead??

### ISSUE THREAD

**Issue by php4fan** [ethereum/ethereum-org-website#5450]
At https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/

At step 4 "Add ETH from a faucet" you recommend using Ropsten faucet.
By following the steps, it simply doesn't work.
It looks like it's abandoned and/or broken.

I don't remember how, I found out there's this one: https://faucet.metamask.io/
which works seamlessly, and seems to be provided by Metamask, the very same who provide the browser extension you recommend using as a wallet.

**Comment by corwintines** [comment]
Im having issues using this faucet personally, but if others are having success feel free to add this faucet to the faucet lists on https://ethereum.org/en/developers/docs/networks/#top. Might be worth just changing all faucet references to this page for users to choose from in tutorials.

**Comment by lingzhong** [comment]
It seems there are multiple places on the site that references the [de facto Ropsten faucet](https://faucet.ropsten.be) that reached end of life.

Happy to take this bug on :)

**Comment by lingzhong** [comment]
Created PR #5516 to fix this bug. Seeking review :) @corwintines
