### ISSUE TITLE
Hardhat Tutorial 

### ISSUE THREAD

**Issue by rodrigoherrerai** [ethereum/ethereum-org-website#5462]
We'll consider [our content resources policy](https://ethereum.org/en/contributing/content-resources/) when reviewing the tutorial, so please take a look there first.

**The Complete Hands-On Hardhat Tutorial**

**Hands-On tutorial to learn the basics of Harhdat. We will create 3 projects to understand how Hardhat works in action.**

**Hardhat**

**Medium**

**Beginner**

**Medium**

****

**https://medium.com/better-programming/the-complete-hands-on-hardhat-tutorial-9e23728fc8a4**

**Comment by adi44** [comment]
Hi, I would like to pick up this issue. @rodrigoherrerai
