### ISSUE TITLE
Plugin gatsby-remark-image-urls parsing bugs

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#5501]
**Describe the bug**
Recently a plugin was added to avoid having to modify the image paths for translated markdown pages.

1. Noticing this is causing problems with any images being used within markdown files that are _stored in the root assets folder_. Images stored within the same folder as the english markdown file work fine, but if it's stored in the assets folder it breaks. 
Example is the `poap.png` file in the `assets` folder, which does not render correctly on the translated NFT page.

2. Also noting the frontmatter paths are not responding to this plugin. Attempted to leave `../../assets/use-cases/dao-2.png` in for the translated `dao` pages, but this prevented the images from rendering. Changing these back to `../../../../assets/use-cases/dao-2.png` (for example) did the trick.

3. Local image paths without a leading `./` are not rendering appropriately.

**To Reproduce**

1. Go to https://ethereumorgwebsitedev01-frusecases.gtsb.io/fr/nft and scroll down to "POAP on ethereum.org" alt text where the image should be

2. Difficult to replicate the frontmatter bug without altering path locally and building.

3. Also difficult to replicate without testing locally, but this was noted on the `pt-br` `energy-consumption` page where we had to update the path to include `./` before the file name to get this working.

**Expected behavior**
1. Image paths within the frontmatter field should also default to grabbing the file from the english path

2. Referencing assets within the root `assets` folder should load these image. -- Perhaps we can add something to the plugin to look for `~` at the beginning to indicate a root level path?

3. We should update the style-guide to ensure we always have a `./` leading local filenames, and/or we should update the plugin logic to account for this in the future.

**Screenshots**
<img width="502" alt="image" src="https://user-images.githubusercontent.com/54227730/155600017-5fefcd2e-1814-4dd5-84cf-76d5a37af5d2.png">
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/54227730/155606924-d7f8ee8a-3c86-45f2-8d03-64ef3c83d1e7.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
I believe @pettinarip did a bunch to address this, but since we are migrating to NextJS this quarter I don't see the need to keep this around either. Going to close this out.
