### ISSUE TITLE
Improving POAP to give more fun to Ethereum network users

### ISSUE THREAD

**Issue by amin-yutori** [ethereum/ethereum-org-website#5524]
**Does your functional requirement relate to the problem? Please describe.
Increased POAP usage (markets, transactions)

<! -- A clear and concise description of what the problem is. Example I am always [...]. I'm frustrated when -->.
Currently, the POAP only serves as a badge as a memorial, but there are few places where people can show off even that badge!

**Please describe your preferred solution.
Differentiation from NFT

<! -- A clear and concise description of what you want to happen. -->
・Differentiate between NFT and POAP. And how to make people want to collect more easily.
・There are currently many services that offer benefits to those who own a particular NFT, but I would like to see as many of these as possible become POAPs.

**Please tell us about the alternatives you have considered.--> 
・A simple display function of POAPs owned on etherscan.
・A simple album to show the POAPs you own easily on SNS.

<! -- Please provide a clear and concise description of the alternatives and features you have considered. -->
POAP is simple to display and still easy to collect, and its advantages should be further developed.
POAP collections have a different appeal from NFTs, which are often resold and are easily influenced by the market.
POAPs will encourage users of the Ethereum network to use the network for more than just monetary purposes.

**Comment by minimalsm** [comment]
Hey @amin-yutori, thanks for the thoughts here. Perhaps it would be better if you directed this feedback directly to the team working on POAP. [This is their discord server.](https://discord.gg/jJ7pMz3f)

Closing this out as it is not relevant to ethereum.org specifically ❤️
