### ISSUE TITLE
ethereum.org webpage consistently performing poorly per Lighthouse diagnostics

### ISSUE THREAD

**Issue by lingzhong** [ethereum/ethereum-org-website#5527]
**Describe the bug**

ethereum.org webpage loading performance is consistently poor (scoring 20s out of 100) as diagnosed by Lighthouse Reports in every build over the past 6 months.

**To Reproduce**

1. Go to any recent PR, e.g. #5516 
2. Scroll down to the 'Gatsby Cloud Build Report' by @gatsby-cloud bot
3. Locate the Lighthouse Report subsection and click on 'View full report'
4. See poor 'Performance' metrics of 20s out of a total of 100

**Expected behavior**

The 'Performance' metrics, which measures webpage loading, should be much higher.

**Screenshots**

![light_house_poor_performance](https://user-images.githubusercontent.com/4011137/155998520-7dd24232-f1e1-4d3b-a7de-ba4bf121ef64.png)

**Additional context**

Sample [Lighthouse Report](https://build-73020270-ed07-44d1-8d3b-10ac40c4f5f1.gtsb.io/reports/lighthouse/index.html).

**Want to contribute?**

Happy to help! This performance issue likely has multiple culprits, as indicated in the 'Opportunities' and 'Diagnostics' sections of the Lighthouse Report.

**Comment by wackerow** [comment]
Hey @lingzhong! Thanks for posting the issue. Wanted to let you know the accessibility and performance are definitely issues on the roadmap. The Lighthouse scores can vary quite a bit between desktop and mobile, and agree we need to take a closer look here eventually. 

This report is broad but doesn't help so much with defining specific actionable issues. I'm going to close this specific issue out, but if you find any specific issues that could be worked on to improve these scores it would be helpful to have that filed instead. Maybe with narrower scope we could get someone to hope in and help out here.

Thanks again =)
