### ISSUE TITLE
Add "Show NFT" to wallet option

### ISSUE THREAD

**Issue by ratstraper** [ethereum/ethereum-org-website#5556]
**Is your feature request related to a problem? Please describe.**
I searched for a wallet at https://ethereum.org/en/wallets/find-wallet/ There is nothing in the filters that displays the NFT in the wallet

**Describe the solution you'd like**
Add "Show NFT" to wallet options and filter search

**Comment by corwintines** [comment]
@ratstraper thanks for the suggestion! We are currently working on updating our wallets page, and improving filters is apart of that. We have NFT support as one of these features that we are looking to include :)
