### ISSUE TITLE
Update list of stablecoins

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5558]
**Is your feature request related to a problem? Please describe.**

Noticed the "Top stablecoins by market capitalisation" we list is a bit outdated:
https://ethereum.org/en/stablecoins/

![Image 2022-03-01 at 11 26 34 AM](https://user-images.githubusercontent.com/8097623/156235234-d4611557-8ce8-4268-93dc-7131fc80d9b5.jpg)

**Describe the solution you'd like**

Add more Ethereum-based stablecoin, e.g. the top 10 on https://www.coingecko.com/en/categories/stablecoins

**Describe alternatives you've considered**

None.

**Additional context**

We currently fetch this data via a Coingecko API:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/stablecoins.js#L316

BUT only if the stablecoin is included in this list:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/stablecoins.js#L293

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by joeurassa** [comment]
add me please!

**Comment by minimalsm** [comment]
Hey @JayGreck, thanks for offering to help. I've assigned you ❤️ please confirm you've seen this and let us know if you need any help on this 👍

Thanks @joeurassa too, I've give you a ping if @JayGreck isn't able to work on this.

**Comment by JayGreck** [comment]
Hey @minimalsm, I will begin working on this issue now! 

I have got two questions,
1. Do you want me to replace the old top 10 with the new top 10 and remove the stablecoins that have fallen down from the the first 10 positions? Or do you want me to add the stablecoins that are currently in the top 10 that aren't already in the list? 
2. I have noticed that the Frax stablecoin collateral type is both algorithmic and asset, how should I go about setting the type in the stablecoin list for Frax? 
Thanks.

**Comment by shanajhwhy** [comment]
- - [ ] @joeurassa [[]()]()

**Comment by joeurassa** [comment]
> * [ ]  @joeurassa []()

what does that mean @shanajhwhy am new to github!

**Comment by minimalsm** [comment]
Closed by #5575
