### ISSUE TITLE
Bug in buy function of ERC20 simple DEX tutorial

### ISSUE THREAD

**Issue by samiulllah** [ethereum/ethereum-org-website#5569]
Tutorial at this link has code logical error --> https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md

The buy function transfer amount of token to the buyer but it never transfers ether to the contract.

**Comment by samiulllah** [comment]
Oh sorry I didn't payed attention that buy function is payable and hence value number of eth will be transferred. Close issue.

**Comment by corwintines** [comment]
No worries, thanks @samiulllah :)
