### ISSUE TITLE
[developers/learning-tools/] Vyper.fun site is no longer active

### ISSUE THREAD

**Issue by kpister** [ethereum/ethereum-org-website#5580]
The docs for learning include a card for [Vyper.fun](https://vyper.fun) which is not accessible. The [gitter](https://gitter.im/vyper-fun/lobby) and discord for the project are also dead as far as I can tell.

**To Reproduce**

1. Go to [https://ethereum.org/en/developers/learning-tools/](https://ethereum.org/en/developers/learning-tools/)
2. Click on Open Vyper Fun

**Expected behavior**

There should only be active links on this page for developers to use.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: FF, Chrome...

I am happy to submit the patch removing this card, or leaving it to the team.

**Comment by minimalsm** [comment]
[Checking in with the creator.](https://twitter.com/daoshuaa/status/1491768879491735552) They already stated that they intended to keep it up so hopefully just a temporary outage.

**Comment by minimalsm** [comment]
No answer on Twitter, [followed up with Vyper team on Discord.](https://discord.com/channels/809793915578089484/809794150550732830/959088198095605870)

**Comment by charles-cooper** [comment]
migrated to https://learn.vyperlang.org

**Comment by charles-cooper** [comment]
bumping because as mentioned, the site is still up, it just has been migrated to https://learn.vyperlang.org
