### ISSUE TITLE
Add additional grant programs to the grants page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5581]
**Is your feature request related to a problem? Please describe.**

https://ethereum.org/en/community/grants/

**Describe the solution you'd like**

Lots of Ethereum-related grant programs out there that we should add!
https://twitter.com/WhiteFlamingo88/status/1497907214828376066?s=20&t=Wn4rya0oQdDPtWc6C3td0w
https://docs.google.com/spreadsheets/d/1XHc-p_MHNRdjacc8uOEjtPoWL86olP4GyxAJOFO0zxY/edit#gid=0

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by sancodes** [comment]
I'm willing to help, if this is still open.

**Comment by samajammin** [comment]
Let's keep this open - @corwintines added the Google Sheet link in https://github.com/ethereum/ethereum-org-website/pull/5568 but I think we should add individual grant links vs. relying on this 3rd party resource. Reasoning being:
- Not sure if all those projects are legit or not. We should vet them individually.
- We shouldn't rely on a Google spreadsheet we don’t control, e.g. the website for `Ethereum Foundation` is `https://github.com/aragon/nest` which is incorrect.

**Comment by minimalsm** [comment]
@lingzhong added a bunch in #5664. 

There might still be a few to add (At a glance: DYDX, Lido)

**Comment by vj-codes** [comment]
@minimalsm hey I would like to work on this!

**Comment by lingzhong** [comment]
@minimalsm Added DYDX and Lido in #5755, ready for review 👍 

There are definitely more though.

**Comment by WhiteFlamingo** [comment]
think permission settings on the doc I created were changed for a couple hours last week, so have updated. thanks for adding this, too!
