### ISSUE TITLE
Missing the Hardhat logo 

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#5582]
**Describe the bug**

Missing the Hardhat logo from the "set up local environment" page.
The image src is 404; they might have changed the image location.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/local-environment/
2. Scroll down to the card section
4. See an error image not displaying 

**Expected behavior**

should have the logo

**Screenshots**

![Screen Shot 2022-03-04 02 43 50 PM](https://user-images.githubusercontent.com/1120748/156784143-6ab8b44e-6df2-4dd8-851e-0c2cf469923e.png)

**Desktop (please complete the following information):**

- OS: macOS 12.01
- Browser: brave
- Version: 1.34.81

**Comment by minimalsm** [comment]
Thanks for catching @nloureiro 🎉

Looks like [we were using an external image here](https://github.com/ethereum/ethereum-org-website/blob/e4709c2e7df561411da6059154d364bf22c58d36/src/pages/developers/local-environment.js#L298) that Hardhat removed from their site. I've fixed this in #5593.
