### ISSUE TITLE
OCaml is not supported

### ISSUE THREAD

**Issue by mimoo** [ethereum/ethereum-org-website#5601]
Registering for ETH Amsterdam it tells me to choose which programming language I have experience with, but OCaml is not in there. So they redirected to this page https://ethereum.org/en/developers/docs/programming-languages/ which redirected me to this

**Comment by minimalsm** [comment]
Hey @mimoo, this isn't something we're involved with. Best to reach out to the ETHGlobal team about this. [Here is their Discord](https://discord.gg/ethglobal)
