### ISSUE TITLE
Potentially incorrect statement in the Transactions description

### ISSUE THREAD

**Issue by adeleke-akinade** [ethereum/ethereum-org-website#5604]
The Transactions description on the https://ethereum.org/en/developers/docs/intro-to-ethereum/ page states that "Execution of any code causes a state change in the EVM" and I am unsure if this is correct. What about code execution that simply returns a value but does not change the state?

**Comment by minimalsm** [comment]
Hey @adeleke-akinade thanks for raising this. In the context set by the page, this is definitely correct.
