### ISSUE TITLE
Hero CTA button layout bug

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#5616]
**Describe the bug**
Hero buttons missing buffer spacing

**To Reproduce**

1. Go to https://ethereum.org/en/upgrades/get-involved/bug-bounty/ on desktop
2. See the two hero buttons next to each other without any spacing

**Expected behavior**
A gap between the two buttons horizontally when laying side-by-sde.

**Screenshots**
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/54227730/157116434-9aa5cbe5-e888-40d9-a109-801d26782314.png">

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Browser: Brave
- Version: latest, up-to-date

**Additional context**

Haven't investigated which other pages this bug may affect, if any. 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vluna** [comment]
I can work on this.
