### ISSUE TITLE
TokensFarm

### ISSUE THREAD

**Issue by mktdce** [ethereum/ethereum-org-website#5636]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**
We have 3 stages that program goes through before deployment on production, every stage has its own kind of testing that includes security testing. We also have modifiers that don't allow hackers to execute functions on our contracts because it needs approval of congress member. Also lots of libraries are used, which serve for security.
https://www.certik.com/projects/tokensfarm

**Is your dapp open source?**
No

**Can a user access the dapp without creating an account?**
Yes

**Are dapp funds non-custodial?**
Yes

**Do you offer community support?**
Yes. Live human support chat on the website.
 

**Describe any geographical restrictions on usage of your dapp**
Globally accessible

**Dapp title**
TokensFarm
 

**Dapp description**
Multichain Farm-As-A-Service provider offering off-the-shelf farms for projects and a yield farming one-stop shop for crypto holders.

 

**Dapp logo**
![TokensFram-dark-bg (1)](https://user-images.githubusercontent.com/101288578/157519883-fee3699d-f35e-4be8-8500-316ed14907a9.png)

**Brand color**
#FFFFFF

**Comment by minimalsm** [comment]
Thanks for raising this mktdce
