### ISSUE TITLE
Fix inconsistent spellings of JavaScript

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5642]
**Describe the bug**

At the moment we inconsistently spell JavaScript throughout our site. Searching the codebase there are 683 results for '**JavaScript**' (the correct spelling) but also 120 results for Javascript (the incorrect spelling).

**To Reproduce**

1. Search codebase for 'JavaScript' and 'Javascript' (case sensitive)
1. See error

**Expected behavior**

In-text, the spelling should always be JavaScript.

**Screenshots**

<img width="427" alt="Screenshot 2022-03-10 at 14 02 35" src="https://user-images.githubusercontent.com/62268199/157686363-d00e43cc-f4ee-45f2-ae04-90195c1c19c1.png">

**Additional context**

- A simple unreviewed replace all might break other things (code, links, javascript libraries, etc)
- I will update [our style guide](https://ethereum.org/en/contributing/style-guide/) to reflect this.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by KaranKaira** [comment]
@minimalsm, I would like to take up this issue.
So, I have to individually edit the incorrect spelling(Javascript) into correct spelling( JavaScript).
Thats all , right..

**Comment by minimalsm** [comment]
Hey @KaranKaira, thanks for offering to help. I've assigned you.

Yes, that is correct. Butt be careful not to change any that are used within code/urls/etc :-)

Feel free to ping if you need any guidance.

**Comment by KaranKaira** [comment]
@minimalsm Sure, I will be changing only those which are occurring in text only.

**Comment by KaranKaira** [comment]
Hi @minimalsm , I have edited every markdown file.
There are json files which have incorrect spelling. Do I need to edit them also.
![image](https://user-images.githubusercontent.com/46125192/157921813-39f85e3a-8614-4f1c-8960-9cbdfc35b34b.png)

**Comment by KaranKaira** [comment]
@minimalsm , seeing the changes made in pull request #5654 , I am editing the spellings the json files too..

**Comment by KaranKaira** [comment]
hi @minimalsm , opened pull request #5659.

**Comment by minimalsm** [comment]
Solved in #5659
