### ISSUE TITLE
Fix inconsistent spellings of MetaMask

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5643]
**Describe the bug**

Similar to #5642 — at the moment we inconsistently spell MetaMask throughout our site. Searching the codebase there are 144 results for '**MetaMask**' (the correct spelling) but also 151 results for Metamask (the incorrect spelling).

**To Reproduce**

1. Search codebase for 'MetaMask' and 'Metamask' (case sensitive)
1. See error

**Expected behavior**

In-text, the spelling should always be MetaMask.

**Additional context**

- A simple unreviewed replace all might break other things (code, links, libraries, etc)
- I will update [our style guide](https://ethereum.org/en/contributing/style-guide/) to reflect this.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Re-Drawn** [comment]
Hi, @minimalsm, I would like to work on this issue!

**Comment by ObieMunoz** [comment]
Hi, I can get this done quickly & will be careful to only update the spellings that are in text and outside of code or url's.

**Comment by minimalsm** [comment]
Hey @Re-Drawn, thanks for offering to help. I've assigned you.

Please let us know if you need a hand on this :-)

**Comment by minimalsm** [comment]
@ObieMunoz thanks for offering, I'll ping you if @Re-Drawn isn't able to work on this.
