### ISSUE TITLE
Revamp the Staking page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5647]
**Is your feature request related to a problem? Please describe.**

As mentioned in our Q1 roadmap (#5105), improving the UX of staking is a key goal of our team. Part of this effort should be to revamp the [Staking page](https://ethereum.org/en/staking/).

Two clear areas of improvement we've identified are to expand our resources for both 1) pooled staking & 2) solo staking to make both processes easier to understand & easier to accomplish for visitors.

**Describe the solution you'd like**

Content & design solutions are being actively developed so input is welcome here but the high-level improvements we're thinking is:
- Redesign/restructure the existing [Staking page](https://ethereum.org/en/staking/)
  - Less framing on running your own validator as the primary way to stake (move some of this info to a subpage)
  - Greater focus on the decision to run your own hardware or not vs. how much ETH your willing to stake (given there are now options to run a validator with less than 32 ETH)
- Create a new Staking Pools subpage (e.g. ethereum.org/en/staking/pools/)
  - Provide more education on how pools work & the considerations involved
  - List available staking services (using a clear listing policy #5646) similar to how we list [Ethereum wallets](https://ethereum.org/en/wallets/)
- Create a new Solo Staking subpage (e.g. ethereum.org/en/staking/solo/) 
  - Provide more education on how to solo stake & the considerations involved
  - List available tools/projects that assist with this
- Create a documentation section dedicated to staking (e.g. ethereum.org/en/staking/docs/) 
  - Build out technical & non-technical resources for stakers
  - Integrate content from the community (e.g. #2277)

**Describe alternatives you've considered**

Many 😅 - feel free to comment with feedback or alternatives of your own. We always appreciate input!

**Additional context**

Some discussion & input around this can be found in #5633

**Comment by lingzhong** [comment]
+100 on this!

As a staking participant, it was non-obvious to identify all the trade-off's between the various types of staking mechanisms on the website.

It'd be great if the we can incorporate a way to clearly compare and contrast the trade-off's in the new page design, including but not limited to:

- Staking reward
- Risks
- Financial/asset requirement
- Technical requirement
- Maintenance difficulty (after initial staking)
- Liquidity before the Merge
- Implications to ecosystem decentralization
- Privacy of participation

Would love to help with this 🏗 what's the best way for me to learn about the latest development status? This seems like a large overhaul, not sure where I can break off a piece and chew :)

**Comment by nloureiro** [comment]
We've created a [Figma prototype](https://www.figma.com/proto/p1rEqloJKtdCpr42YdbLpJ/Staking-EPIC?page-id=360%3A532&node-id=475%3A1881&viewport=264%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=475%3A1881) to get more detailed feedback on this.
The Goal is to the most feedback we can on a wireframe type of pages to set the content and flow right.

Please add your contribution using the comments in [Figma ](https://www.figma.com/proto/p1rEqloJKtdCpr42YdbLpJ/Staking-EPIC?page-id=360%3A532&node-id=475%3A1881&viewport=264%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=475%3A1881)

Any other ideas or questions just get them here. 🙂

**Comment by samajammin** [comment]
Thanks for the input @lingzhong! I think that's a great list of considerations to include 😍 

> Would love to help with this 🏗 what's the best way for me to learn about the latest development status? This seems like a large overhaul, not sure where I can break off a piece and chew :)

Amazing! @nloureiro just posted a design protoype (see comment above). I encourage you to check that out & add your feedback. We also have a public Discord - feel free to join the discussion in the `🥩｜staking` channel: https://discord.gg/aQEq7GQsgE
