### ISSUE TITLE
(Add exchange) Xanpool

### ISSUE THREAD

**Issue by johnsgeorgecet** [ethereum/ethereum-org-website#5649]
Before suggesting an exchange, make sure you've read [our exchange listing policy](https://ethereum.org/en/contributing/adding-exchanges/). If it's a decentralized exchange (DEX) you'd like to list, please take a look at our [policy for listing dapps](https://ethereum.org/en/contributing/adding-products/).

Please fill out this short form if you'd like an exchange added to ethereum.org:

**What geographical restrictions apply to this exchange?**
Available in 11 countries in APAC like Singpaore, India, HK, Australia etc. 

**Which currencies are accepted by this exchange?**
AUD, SGD, HKD, THB, PHP, INR, IDR, VND, MYR, NZD, KRW

**Do you have any proof that they're a legitimate company?**
https://xanpool.com/en/about 

**Do you have any extra information?**
They are a non-custodial fiat to crypto exchange, they route the money and crypto directly without touching. Established in 2019. Backed by investors like Valar, OK group etc.

**Comment by minimalsm** [comment]
Hey @johnsgeorgecet,

I tried searching Google/xanpool.com but was unable to find anything on the exact geographical restrictions. We require this to list on ethereum.org. Could you tell us/point us to a resource that explains exactly where Xanpool is and is not available?
