### ISSUE TITLE
Update Cookie Policy page

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/ethereum-org-website#566]
**Is your feature request related to a problem? Please describe.**

Matomo is being used for analytics, and that information should be disclosed in the Cookie Policy page.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Christofon** [comment]
Hi, first time contributor here. Looks like a great issue to start with. 
Have added Matomo `_pk_ses` and `_pk_id`. Could not locate the Google Analytics cookies on my machine tho, are they still in use? 
If not we could delete corresponding disclosures.

**Comment by evertonfraga** [comment]
That’s safe to delete!

thanks

**Comment by evertonfraga** [comment]
Hi @Christofon I see you made the changes, but I didn't see any PR. I'd be happy to review it! 

Thanks

**Comment by Christofon** [comment]
Hi, #581 is the one. :)
Thanks for reviewing.
