### ISSUE TITLE
Update gas docs to post-London/EIP-1559 info only

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5660]
**Is your feature request related to a problem? Please describe.**

Last year we created a bunch of updates around the London upgrade / EIP-1559: #3022 #3521

I'm wondering how long we should frame the content on the [gas page](https://ethereum.org/en/developers/docs/gas/) as "[Prior to the London upgrade](https://ethereum.org/en/developers/docs/gas/#pre-london)" & "[After the London upgrade](https://ethereum.org/en/developers/docs/gas/#post-london)". 

- Should we update that page to reflect the current state of Ethereum (i.e. post-London)? If so, when?
- Should we continue to provide info on the historical structure of the gas market? Should ethereum.org provide an archive of sorts for this information, or can other places (e.g. https://ethdocs.org/) serve this purpose? Is providing historical references even valuable, or does it risk creating confusion in the ecosystem?

**Describe the solution you'd like**

For now I lean towards the stance that ethereum.org should focus on keeping content up to date with the current state of Ethereum. That means updating this gas page (& all content) to explain how Ethereum works now vs. how Ethereum has worked in the past.

**Describe alternatives you've considered**

As mentioned above, I'm open to input on how we may also provide an archive of how Ethereum once worked.

**Additional context**

This also relates to https://github.com/ethereum/ethereum-org-website/issues/3908

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you have input on the proposed updates or if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
I think we should update the gas page to just portray the current state of Ethereum now that London has been out for quite a few months, and move some of the historical gas information to the [/history/](https://ethereum.org/en/history/) page. We could probably overhaul the history page to accommodate for that change if we are going to add this information though. I do think there is some value showing the history of big changes like this though, and we have that page already. Seems like a good fit to me.

**Comment by wackerow** [comment]
Agree... this has been sitting for a while, and all the more reason I don't think we need that historical context directly in the dev docs anymore. I would recommend updating this page to describe the current state of Ethereum, and remove superfluous comments about the London upgrade.

**Comment by corwintines** [comment]
For who wants to pick this up

We should remove the **What was the London Upgrade / EIP-1559?** section from https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/gas/index.md#what-was-the-london-upgrade--eip-1559-what-was-the-london-upgrade-eip-1559 

This can be added to the London upgrade section on the history page https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/gas/index.md#what-was-the-london-upgrade--eip-1559-what-was-the-london-upgrade-eip-1559

I think we can use an expandable card for this information (can reference use of this in that upgrade).

**Comment by Crosstons** [comment]
![image](https://github.com/ethereum/ethereum-org-website/assets/110349596/0716893a-87e7-446c-a5a6-226785d12239)
@corwintines 
Just to confirm the **What was the London Upgrade /EIP-1559?** expandable card is to be added just below the London EIPS expandable card? am I right?
