### ISSUE TITLE
Add Galician language

### ISSUE THREAD

**Issue by NewHouses** [ethereum/ethereum-org-website#5662]
Hello, I would like to star to translate the website to Galician

**Comment by lukassim** [comment]
Hey, thanks for the suggestion.
Added, you can find Galician translations here: https://crowdin.com/project/ethereum-org/gl

Some more information about the ethereum.org Translation Program: https://ethereum.org/en/contributing/translation-program/
You can also join our Discord to reach out to the team or other translators, find other ways of getting involved, claim your POAPs for translation, etc: https://discord.gg/5Bc7jMhxuz
