### ISSUE TITLE
(add-wallet) - Bridge Wallet

### ISSUE THREAD

**Issue by yannggg** [ethereum/ethereum-org-website#5671]
**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**

Yes, each new app version is security tested internally before release.

**When did your wallet go live to users?**

April 2020

**Does your wallet have an active development team?**

Yes

**Is your wallet open-source?**

No

**Is your wallet globally accessible?**

Yes, with the fiat on/off ramp excluding the following countries: Afghanistan, Belarus, Burundi, Central African Republic, Democratic Republic of the Congo, Guinea, Guinea-Bissau, Iran, Iraq, Lebanon, Libya, Mainland China (Hong Kong and Taiwan accepted), Mali, Myanmar, Nicaragua, North Korea, Somalia, Sudan, South Sudan, Syria, USA, Venezuela, Yemen, Zimbabwe.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial. Seed phrase backup is forced upon wallet creation. Also supports private key export.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Ongoing bug bounty program since February 2021 on https://immunefi.com/bounty/mtpelerin/

**Does the wallet support layer 2 networks?**

Yes, Arbitrum and Optimism.

**Can the wallet be used with arbitrary Ethereum RPC endpoint?**

Yes (Settings > Network settings > Advanced settings)

**Does the wallet have fiat on-ramps?**

Yes, with fees being fully subsidized on the first $500 bought per user and per year. Fees are fully subsidized up to $100k per year and per user for jFiat stablecoins. Ramp network fees are subsidized on all networks except Ethereum L1.

**Does the wallet allow users to explore dapps?**

Yes, through WalletConnect

**Does the wallet have integrated defi/financial tools?**

No

**Can a user withdraw to their card?**

Yes, to a bank account. Cash outs on cards are planned.

**Does the wallet offer limits protection?**

No

**Does the wallet allow high-volume purchases?**

Yes, up to $100,000.

**Does the wallet have an integrated token swap?**

Yes, through WalletConnect.

**Is the wallet a multi-signature wallet?**

No

**Wallet title**

Bridge Wallet

**Wallet description**

The ultimate app to invest in Ethereum assets the easy way. Buy and sell crypto from your bank account with the lowest fees on the market, exchange them on the go, and explore the world of DeFi from your phone.

**Wallet logo**

https://www.mtpelerin.com/images/bridge-logo.svg

**Background colour for brand logo**

#001E32

**URL**

https://www.mtpelerin.com/bridge-wallet

**Comment by minimalsm** [comment]
Hey @yannggg thanks for raising this issue.

A few things on the description:

> The ultimate app to invest in Ethereum assets the easy way.

I'm not really comfortable with this first sentence as to a user it might read like ethereum.org is endorsing this product. I think cutting it entirely keeps the descriptiveness intact. Thoughts?

> with the lowest fees on the market

Can you substantiate this claim?

Thanks 😀

**Comment by minimalsm** [comment]
Hey @yannggg 

Just a small update here: as part of [our Q1 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/5105), we are refining our wallets page to improve the user experience of picking a wallet for our users. This will include refining the listing criteria for our wallets page. Until we have researched, established, and published refined listing criteria, we will not be actively adding new wallets to the website. We hope to resolve this soon :-)

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by minimalsm** [comment]
Hey @yannggg 

Sorry for the delay on this. If you'd still like to be listed on ethereum.org, please [fill out our new issue template with the necessary information](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet). Thank you! :-)
