### ISSUE TITLE
On-hover effect missing on 'Go' button (dapps page)

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#5676]
**Describe the bug**

Under the 'Get started' section of [the dapps page](https://ethereum.org/en/dapps/) the 'Go' button does not have an on-hover effect.

**To Reproduce**

1. Go to 'https://ethereum.org/en/dapps/'
1. Scroll down to 'Get started'
1. Hover over the 'Go' button
1. See error

**Expected behavior**

The button should have an appropriate on-hover effect.

**Screenshots**

![image](https://user-images.githubusercontent.com/62268199/158363966-289c6b8c-d019-4767-be17-7156bf8f3511.png)

**Additional context**

There are other, properly styled orange on-hover buttons on the page that can be used to ascertain the correct style.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @KaranKaira, all yours 😀❤️

**Comment by tomaspasie** [comment]
Hi @KaranKaira. I tried looking into this problem you are facing, but I was not able to recreate your issue. However, I was able to get the dapps page running locally on my end and fix the on-hover effect. If you are still facing issues and no longer want to work on this, I'll be happy to take over! 😄

**Comment by KaranKaira** [comment]
@tomaspasie,Sure you can take over , I am kinda busy these days.

**Comment by tomaspasie** [comment]
Hello @minimalsm! Could you assign me this issue? This is actually my first time contributing to an open-source project and I'd love to help out. Thanks!
