### ISSUE TITLE
Sitemap is broken

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5681]
**Describe the bug**

https://ethereum.org/sitemap.xml no longer resolves correctly

**To Reproduce**

1. Go to https://ethereum.org/sitemap.xml

**Expected behavior**

This URL should render our sitemap file.

Looks like this was last read on 12/8/21:
![Image 2022-03-15 at 2 24 33 PM](https://user-images.githubusercontent.com/8097623/158475168-32ec6ef6-ed62-4401-974f-9c7195241ce2.jpg)

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

I suspect this broke when we upgraded to Gatsby v4 (#4324) given that was merged the day before Google Search Console reports our sitemap being last read. That was also when we migrated to Gatsby Cloud for deploys.

On a potentially related note, we have noticed strange 404 behaviors: #5682

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by pettinarip** [comment]
In the newer version of `gatsby-plugin-sitemap` the sitemap is placed here: `/sitemap/sitemap-index.xml`. I've updated the Google Search Console to use that path 👍🏼

**Comment by samajammin** [comment]
Nice @pettinarip! Can you also add a redirect from the old sitemap (https://ethereum.org/sitemap.xml)?
