### ISSUE TITLE
Incorrect response codes

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5682]
**Describe the bug**

Seeing odd behaviour in our site response codes. Seems the site is not always returning 404 response code when it should.

**To Reproduce**

All of these I'd expect a 404 response:
- Go to https://ethereum.org/derp (404 response)
- Go to https://ethereum.org/en/upgrades/asdfasdf/ (200 response if 1st request, 304 on subsequent request)
- Go to https://ethereum.org/en/derp (200 response if 1st request, 304 on subsequent request)

**Expected behavior**

URLs should return a 404 response if no page exists.

**Screenshots**

![Image 2022-03-15 at 2 36 24 PM](https://user-images.githubusercontent.com/8097623/158476840-73e2ff03-490a-4ffa-8d99-d72f49871436.jpg)

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

May be related to #5681 but I'm not sure.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by HursitTarcan** [comment]
Can I try to fix this?

**Comment by okdonga** [comment]
Hi @samajammin, It seems to be a gatsby issue. Someone made an [issue](https://github.com/gatsbyjs/gatsby/issues/28977) on this on gatsby github, but sadly didn't get any response from the team...

**Comment by samajammin** [comment]
Removing stale status & assigning to @corwintines.
