### ISSUE TITLE
Add Atila as a crypto scholarships and Grants Platform

### ISSUE THREAD

**Issue by ademidun** [ethereum/ethereum-org-website#5684]
[Atila](https://atila.ca) is a platform that allows people to start and get scholarships and grants using fiat and [crypto](https://atila.ca/crypto). Here is a [video demo](https://www.youtube.com/watch?v=rsE-PFz5vTE).

The current fiat-based scholarships are not easily accessible by students across the world. For example, if someone starts a scholarship in Canada, it's quite difficult to give that scholarship award to a winning student in Nigeria or India.

Atila allows people to start a scholarship using cryptocurrencies, allows other people to contribute to those scholarships and allows students to receive their scholarship award deposited to a crypto-wallet.

## Criteria for inclusion: the must-haves

I have carefully read the [Adding Products guide](https://ethereum.org/en/contributing/adding-products/) and reviewed each criterion:

**A security-tested product:**
- The Atila team conducts frequent unit tests on our code and security reviews by our internal security team
- Plans to perform a third party audit when we are able to generate more revenue
- The code we use to accept payments is open-sourced: https://github.com/atilatech/atila-web-components-library

**Live for  6 months**
- The Atila scholarship platform for fiat has been live for over 2 years, however, we recently add crypto scholarships in February 2022, so depending on how product is defined we've been live for either 2 years or 2 months
- We also don't currently use smart contracts so the risk of a smart contract hack is reduced

**Worked on by an active team**
- https://atila.ca/team
- https://www.linkedin.com/company/28145296/

**Honest and accurate listing information**
- Vision Essay: [Crypto Scholarships: Funding Education With Crypto](https://atila.ca/blog/tomiwa/crypto-scholarships/)
- Some of our code is closed-source some of it is open-source: https://github.com/atilatech/atila-web-components-library

## Criteria for ranking: the nice-to-haves

**Users can try it out themselves**
- We offer a demo version of the site which users can practice with using testnets and practice money (e.g. using funds retrieved from a faucet): https://demo.atila.ca/crypto

**Non-custodial**
- Scholarship funds are sent to the applicant's non-custodial crypto wallet
- Scholarship funds are currently held by Atila until distributed to student, we are working on adding both Multisig functionality and potentially escrow support for these funds

**Globally accessible**
- Atila is available to anyone in the world, here is a [fun video we made to showcase that fact ](https://www.youtube.com/shorts/e0XprSTXOJc)

**Open source**
- Some of our code is closed-source some of it is open-source: 
- The code we use for our crypto payment form to fund the scholarship is open-source: https://github.com/atilatech/atila-web-components-library

**Community**

- We have multiple platforms that users use to communicate with us: [Instagram](https://www.instagram.com/atilatech/), [Reddit](https://www.reddit.com/r/atila/), [Twitter](https://twitter.com/atilatech), [TikTok](https://www.tiktok.com/@atila.tech) and [Discord](https://www.google.com/url?q=https://discord.gg/Dz7XpzbYy9&sa=D&source=editors&ust=1647431405141399&usg=AOvVaw3lpSfQMRwMoNOl5NkGfjx6) page

**Comment by minimalsm** [comment]
Hey @ademidu, thanks for suggesting this and sorry for the delay in reviewing it.

First off, I wanted to say I really appreciate the awesome work you're doing in making education more accessible. However, as far as ethereum.org goes, we wouldn't be able to list this product at this time due to the product's age and lack of battle-testedness.

Feel free to reapply in the future once the project is a more established and keep up the good work ❤️

**Comment by ademidun** [comment]
Thank you so much for the kind words @minimalsm and no worries about the delay I know that you're very busy.

I completely understand where you're coming from and I will reapply in the future when we're more established as you suggested.

I'm glad we have people like you as part of the Ethereum community. ❤️
