### ISSUE TITLE
New tutorual: How Getting Ethereum Account Balance and Transactions

### ISSUE THREAD

**Issue by pizdecpizdec** [ethereum/ethereum-org-website#5699]
We'll consider [our content resources policy](https://ethereum.org/en/contributing/content-resources/) when reviewing the tutorial, so please take a look there first.

**Tutorial title**

How Getting Ethereum Account Balance and Transactions

**Tutorial description**

We’re going to take apart two sets of data used in creating an Ethereum wallet.
Current Balance — The last Eth amount for the account.
Address transactions — Historical Eth transactions for the account.

**Tag your tutorial**

Transactions, Nodes

**Publication**

Hosted in our Medium Blog

**Skill level**

Beginner

**Hosted on Ethereum.org or hosted elsewhere?**

Hosted in our Medium Blog

**For tutorials hosted elsewhere: URL to tutorial**

https://watchdata.medium.com/how-getting-ethereum-account-balance-and-transactions-c4b43acb8457

**Comment by corwintines** [comment]
Given how tied this is to a product, instead of raw fetching data, I don't think this tutorial is necessary.
