### ISSUE TITLE
New tutorial: How to connect to the Ethereum network using Web3.js

### ISSUE THREAD

**Issue by pizdecpizdec** [ethereum/ethereum-org-website#5700]
We'll consider [our content resources policy](https://ethereum.org/en/contributing/content-resources/) when reviewing the tutorial, so please take a look there first.

**Tutorial title**

How to connect to the Ethereum network using Web3.js

**Tutorial description**

In this tutorial, we will learn how to use Web3.js to connect to the Ethereum blockchain using HTTP. We will write code to get the last block number.

**Tag your tutorial**

Web3.js

**Publication**

Hosted in our Medium Blog

**Skill level**

Beginner

**Hosted on Ethereum.org or hosted elsewhere?**

Hosted in our Medium Blog

**For tutorials hosted elsewhere: URL to tutorial**

https://watchdata.medium.com/how-to-connect-to-the-ethereum-network-using-web3-js-b76ed55efdea

**Comment by mohammadobaid1** [comment]
Let me work on this. @pizdecpizdec

**Comment by corwintines** [comment]
Thanks @pizdecpizdec 

Going to close this out as stale. If you still think this is relevant, feel free to open up a new issue for this.
