### ISSUE TITLE
New tutorial: How to connect to the Ethereum network using Web3.py

### ISSUE THREAD

**Issue by pizdecpizdec** [ethereum/ethereum-org-website#5701]
We'll consider [our content resources policy](https://ethereum.org/en/contributing/content-resources/) when reviewing the tutorial, so please take a look there first.

**Tutorial title**

How to connect to the Ethereum network using Web3.py

**Tutorial description**

In this tutorial, we will learn how to use Web3.py to connect to the Ethereum blockchain using HTTP. We will write code to get the last block number.

**Tag your tutorial**

Web3.py, Python

**Publication**

Hosted in our Medium Blog

**Skill level**

Beginner

**Hosted on Ethereum.org or hosted elsewhere?**

Hosted in our Medium Blog

**For tutorials hosted elsewhere: URL to tutorial**

https://watchdata.medium.com/how-to-connect-to-the-ethereum-network-using-web3-py-7fe451464ad0

**Comment by corwintines** [comment]
Thanks @pizdecpizdec 

Going to close this out as stale, but if you think it is still relevant feel free to create another issue.
