### ISSUE TITLE
Error retrieving TVL in DeFi (DeFiPulse endpoint)

### ISSUE THREAD

**Issue by michael-spengler** [ethereum/ethereum-org-website#5715]
symptom: "Error, please refresh - see screenshot below"

context:  https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/StatsBoxGrid.js#L366-L392

![Screenshot 2022-03-21 at 12 30 39](https://user-images.githubusercontent.com/43786652/159252845-9009b5c5-fcb9-4bfb-8ec1-da37832307d7.png)

**Comment by michael-spengler** [comment]
Potential solution approaches:
1. Update DeFi Pulse API Key via https://data-beta.defipulse.com/dashboard/defipulse 
2. Consider Whitelisting https://ethereum.org - see screenshot to simplify things (no need for GATSBY_FUNCTIONS_PATH ... here)

![Screenshot 2022-03-21 at 13 13 41](https://user-images.githubusercontent.com/43786652/159258889-1b4320fa-86db-4459-8aea-48c28c22cde6.png)

Feel free to ping me via https://t.me/danceplanner if you fix this. I'd like to support ethereum.org.

**Comment by michael-spengler** [comment]
I just found out the issue might also be caused by the defipulse api itself --> https://discord.com/channels/344842193019863040/656905049598984202/955441962603921448

in this case you might consider this issue as a minor potential improvement proposal to whitelist https://ethereum.org - see screenshot above to avoid the dependency on ...GATSBY_FUNCTIONS_PATH ... on the own backend...

**Comment by minimalsm** [comment]
Hey @michael-spengler, thanks for flagging this.

We've been having intermittent issues with the DefiPulse endpoint for a while (it would mostly work but break every few refreshes). Seems to be down altogether right now ☹️

I _think_ @wackerow was reaching out to them regarding this?
