### ISSUE TITLE
Typo on intro to ether page

### ISSUE THREAD

**Issue by nebulahh** [ethereum/ethereum-org-website#5717]
**Describe the bug**

A sentence does not flow well. this sentence under "what is ether" section is talking about ether but then it seems The merge is the one needed to validate blocks. 
**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/'
2. Click on 'intro to ether'
3. Scroll down to 'what is ether'

**Expected behavior**

there should be a comma after "The Merge" link within "what is ether" section to demonstrate a pause, followed by the word "it" to reference ether and not the merge. 
**Screenshots**

**Desktop (please complete the following information):**

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Smartphone (please complete the following information):**

- Browser: [e.g. stock browser, safari]
- Version: [e.g. 22]

**Additional context**

**Want to contribute?**
i would like to help with the problem, if am permitted
We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @nebulahh, thanks for offering to help. I've assigned you 😀

**Comment by nebulahh** [comment]
please am new to this. After running yarn start, i made the required changes on my local machine, but my git bash on windows does not open a new terminal session. it just says success doing something and am unable to type any other thing into git bash, should i edit and make PR on github or commit and push via vscode. what should i do?

**Comment by nebulahh** [comment]
please am new to this. After running yarn start, i made the required changes on my local machine, but my git bash on windows does not open a new terminal session. it just says success doing something and am unable to type any other thing into git bash. it is taking too long and i cant see anything that shows it is loading. should i edit and make PR on github or commit and push via vscode. what should i do?

**Comment by minimalsm** [comment]
Just noting @nebulahh that this is still an issue (see comments in #5742)
