### ISSUE TITLE
Proposal: IPFS for decentralized user interfaces

### ISSUE THREAD

**Issue by qbzzt** [ethereum/ethereum-org-website#5746]
**Tutorial title**

IPFS for decentralized user interfaces

**Tutorial description**

This tutorial teaches the reader how to use IPFS to store the user interface for a decentralized app. This is important because while the application's data and business logic are decentralized, without a censorship resistant user interface users might lose access to it anyway.

**Tag your tutorial**

- IPFS
- User Interface
- JavaScript

**Publication**

Not even written yet.

**Skill level**

Intermediate 

**Hosted on Ethereum.org or hosted elsewhere?**

ethereum.org, once it is written.

**Comment by SkywalkingZulu** [comment]
I'd like to take a dab at this, should I use local daemon or am I allowed to use the cloud stuff? Also timelines?

**Comment by wackerow** [comment]
Hey @qbzzt! Circling back... any chance you would still be interested in writing about this topic? Apologies that it ended up overlooked for a while, but I think this would still be an important topic that could use a better explanation.

I'm going to remove the stale tag for now. Ori, I'm going to just go ahead and assign you to this issue for now, but if you get a moment feel free to just reply here weather or not you think this is something you may have bandwidth for coming up. If not no worries, we could potentially open this up for someone else to contribute on.

**Comment by wackerow** [comment]
@qbzzt Hey Ori! I know some time has passed here, curious if you're still interested in writing this content? Personally think it would be a valuable topic

**Comment by qbzzt** [comment]
I'd like to write it, but it will need to wait until after we push through https://github.com/ethereum/ethereum-org-website/pull/11682 (waiting since November) and probably after I write https://github.com/ethereum/ethereum-org-website/issues/6491.

**Comment by qbzzt** [comment]
Thank you. I look forward to actually getting that one published.

**Comment by wackerow** [comment]
> I'd like to write it, but it will need to wait until after we push through #11682 (waiting since November) and probably after I write #6491.

Hey @qbzzt! Was curious if you were still interested in writing this one. #11682 has been merged, but I see you noted on #6491 that you were going to start work on that one. Were you still interested in this issue after the other is complete?

**Comment by qbzzt** [comment]
Yes. I'm sorry everything is taking me so long; life's hectic. I still want to write this, but it will take some time until I get there so if anybody else wants to take it they're welcome to.
