### ISSUE TITLE
Ethereum security and scam prevention fixes

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5759]
**Describe the bug**

1) Remove exclamation mark from 'Common scams' section
2) Fix wording in 'Giveaway scam' section
3) Add end punctuation to 'Social media hacks' section

**To Reproduce**

1. Go to https://ethereum.org/en/security/
2. Scroll down to 'Common scams', 'Giveaway scam', and 'Social media hacks' sections
3. See errors

**Expected behavior**

1) All items in the list in the 'Common scams' section should have no end punctuation
2) ''create a sense of false urgency'' in the 'Giveaway scam' section should be rephrased as ''create a false sense of urgency''
3) The last sentence in the 'Social media hacks' section should end with a period

**Screenshots**

1)
<img width="799" alt="Screenshot 2022-03-25 at 14 25 56" src="https://user-images.githubusercontent.com/37338979/160130558-ee7ff32c-dd94-4d76-8723-db0077c85489.png">

2)
<img width="798" alt="Screenshot 2022-03-25 at 14 26 08" src="https://user-images.githubusercontent.com/37338979/160130585-5e4661b0-5cb7-41b9-8aeb-ac84b461f05b.png">

3)
<img width="783" alt="Screenshot 2022-03-25 at 14 26 16" src="https://user-images.githubusercontent.com/37338979/160130643-72e9912e-5b7c-4d20-857f-eeddc53c11b2.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Closed in #5777
