### ISSUE TITLE
Fix typo in the Ethereum glossary

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5762]
**Describe the bug**

Under the entry for 'decentralized exchange', the button linking to the /get-eth/dex page contains a typo. Specifically the incorrect spelling is 'Decentalized exchanges'

**To Reproduce**

1. Go to https://ethereum.org/en/glossary/
2. Click on 'decentralized exchange' in the right sidebar or scroll down to the 'decentralized exchange' entry
3. Read text on the button, linking to the /get-eth/dex page

**Expected behavior**

Change the spelling from 'Decentalized exchanges' to 'Decentralized exchanges'

**Screenshots**

<img width="799" alt="Screenshot 2022-03-25 at 14 54 45" src="https://user-images.githubusercontent.com/37338979/160135279-cef9279e-5e25-490a-b8e2-647268d473cb.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by rakeshhotker** [comment]
@lukassim i am willing to work on it
