### ISSUE TITLE
Remove redundant 'are' from contributing page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5763]
**Describe the bug**

In the 'A note on plagiarism' section on the Contributing to ethereum.org page, one of the sentences contains a redundant 'are', which should be removed

**To Reproduce**

1. Go to https://ethereum.org/en/contributing/
2. Scroll down to the 'A note on plagiarism' section
3. Read the second-to-last sentence

**Expected behavior**

The word 'are' should be removed from the following sentence: _However, if you are cannot find this information, do not attempt to add it to ethereum.org._

**Screenshots**

<img width="807" alt="Screenshot 2022-03-25 at 15 03 14" src="https://user-images.githubusercontent.com/37338979/160136195-85b47abb-71c6-4fbc-90dd-b3b84d479a57.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Steph-crown** [comment]
I would like to help out with a PR

**Comment by oma131** [comment]
I would like to be assigned to this issue

**Comment by nitin094-hub** [comment]
Already made a PR !
