### ISSUE TITLE
Is these a misstake in ETH Whitepaper? or I misunderstand?

### ISSUE THREAD

**Issue by Junfromc** [ethereum/ethereum-org-website#5776]
abstracked from ETH whitepaper--Miscellanea And Concerns--Fees

"A miner would be willing to process a transaction if the expected reward is greater than the cost. Thus, the expected reward is kR/N since the miner has a 1/N chance of processing the next block, and the processing cost for the miner is simply kC. Hence, miners will include transactions where kR/N > kC, or R > NC. Note that R is the per-operation fee provided by the sender, and is thus a lower bound on the benefit that **_the sender_** derives from the transaction, and NC is the cost to the entire network together of processing an operation. Hence, miners have the incentive to include only those transactions for which the total utilitarian benefit exceeds the cost."

Is the 
"and is thus a lower bound on the benefit that **_the sender_** derives from the transaction" 
should be 
"and is thus a lower bound on the benefit that **_the miner_** derives from the transaction"?

not the sender but the miner should get the benefit, right? or I misunderstand?

**Comment by minimalsm** [comment]
Hey @Junfromc, we aren't updating the whitepaper anymore but a good place to discuss this would be [the Eth R&D discord](https://discord.gg/2BEKHUqHSA).

Thanks for raising.
