### ISSUE TITLE
Repeated ids on the stats charts

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#5790]
**To Reproduce**
Steps to see the bug:

1. Go to the home page https://ethereum.org/
2. Scroll down to the stats charts
3. Each chart has the following repeated ids in its implementation: `colorUv` and `colorPv`
![image](https://user-images.githubusercontent.com/468158/160425215-8158ec2a-d40a-4dd7-8b32-cbc36e92b586.png)

**Expected behavior**

Modify the way we set these ids (`colorUv` and `colorPv`) to have a unique id per chart created.

We could define them as `colorUv-${chartType}`.

**Additional context**

The ids are defined in the `GridItem` component that lives inside the `StatsBoxGrid` file.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by HursitTarcan** [comment]
Can you assign me for this?

**Comment by Steph-crown** [comment]
Hi, can I hop on this?
