### ISSUE TITLE
Make anchor links accessible

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#5795]
**Description**
On the developer docs, we have an anchor icon that appears when you hover over the titles or headings. These anchor or link icons don't have anything that describes what they do or what they are. They appear as empty links since the icon is aria hidden.

**Where are these anchor icons?**
1. Go to https://ethereum.org/en/developers/docs/
2. See the anchor icons on the left side of the headings
![image](https://user-images.githubusercontent.com/468158/160450971-22e4a8f6-572b-4125-a712-75bedf3d612a.png)

**Solution**
We are using the following Gatsby plugin: https://www.gatsbyjs.com/plugins/gatsby-remark-autolink-headers/
In the source code they are adding [`aria-labels`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-autolink-headers/src/index.js#L75) to the links but in our case, it is not working. Explore/open an issue on the plugin repo to check why this is not working for us.

**Additional context**

Check for reference of a better implementation.
- https://kittygiraudel.com/2020/12/10/accessible-icon-links/
- https://amberwilson.co.uk/blog/are-your-anchor-links-accessible

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by pettinarip** [comment]
Thanks @lingzhong assigned to you!

**Comment by lingzhong** [comment]
Quick note, I'll have a working prototype soon. Will send out a PR after testing.

**Comment by corwintines** [comment]
Going to close this as it has gone quite stale. @pettinarip if you think this should still be addressed do you mind reviving this in a new issue.
