### ISSUE TITLE
Reword contradictory sentences on 'Adding developer tools' page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5802]
**Describe the bug**

The sentences in the 'Product ordering' section of the 'Adding developer tools' page are contradictory.
_Unless products are specifically ordered otherwise, such as alphabetically, products will be displayed from most to least recently added to the page._ - This sentence implies that the most recently added tools are listed on top of the list.
_In other words, the newest products get added to the bottom of the list._ - This sentence implies that the most recently added tools are listed at the bottom of the list.

**To Reproduce**

1. Go to https://ethereum.org/en/contributing/adding-developer-tools/
2. Scroll down to the 'Product ordering' section
3. See error

**Expected behavior**

The most recently added products are listed at the bottom of the list. Therefore, the first sentence should be: 
_Unless products are specifically ordered otherwise, such as alphabetically, products will be displayed from least to most recently added to the page._

**Screenshots**
<img width="800" alt="Screenshot 2022-03-29 at 12 24 06" src="https://user-images.githubusercontent.com/37338979/160591882-b4115fb5-9da1-4f06-9d17-b4f296f6959f.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by nitin094-hub** [comment]
I will do it!

**Comment by nitin094-hub** [comment]
I have made a merge request. Plz, Check!

**Comment by minimalsm** [comment]
Thanks @nitin094-hub, closed by #5806
