### ISSUE TITLE
Fix spelling of 'Cloudflare'

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5851]
**Describe the bug**

On the 'Set up Web3.js to use the Ethereum blockchain in JavaScript' page, _Cloudflare_ is misspelled as _Cloudfare_.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/set-up-web3js-to-use-ethereum-in-javascript/
2. Use the search function or scroll down to the following sentence: _If you’d like to directly access a hosted node you can use Infura or the free ones provided by Cloudfare_
3. See error

**Expected behavior**

_Cloudfare should be changed to Cloudflare_

**Screenshots**
<img width="907" alt="Screenshot 2022-03-31 at 13 09 52" src="https://user-images.githubusercontent.com/37338979/161042592-0d00f7c3-0685-4122-a22d-f77a9b7721d6.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by HursitTarcan** [comment]
Will fix this too :)
