### ISSUE TITLE
Fix spelling of 'execution layer'

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5852]
**Describe the bug**

On the 'How to turn your Raspberry Pi into a node by flashing the MicroSD card', _execution layer_ is misspelled as _execution later_.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/
2. Use the right sidebar or scroll down to the 'Switching clients' section
3. Read the 3rd sentence

**Expected behavior**

_Execution later_ should be changed to _execution layer_.

**Screenshots**
<img width="897" alt="Screenshot 2022-03-31 at 13 15 17" src="https://user-images.githubusercontent.com/37338979/161043480-afe427fc-97c1-4ef3-b7ea-6f8f0e39a804.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by HursitTarcan** [comment]
Can I fix this one?
