### ISSUE TITLE
Fix spelling of 'constraint'

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5853]
**Describe the bug**

On the 'How to use Manticore to find bugs in smart contracts' page, _constraint_ is misspelled as _cosntraint_.
 
**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/
2. Use the right sidebar or scroll down to the 'Constraints' section
3. Read the first sentence in the 'Global constraint'

**Expected behavior**

_Cosntraint_ should be changed to _constraint_.

**Screenshots**
<img width="878" alt="Screenshot 2022-03-31 at 13 23 47" src="https://user-images.githubusercontent.com/37338979/161044796-475733fa-c50f-4f47-b123-61bdef55616c.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by HursitTarcan** [comment]
I will fix this too
