### ISSUE TITLE
Fix errors on the Uniswap-v2 contract walkthrough page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5855]
**Describe the bug**

There are two errors on the 'Uniswap-v2 contract walkthrough' page:
1 - 'Skim' is misspelled as 'Skip'
2 - 'Definition' is misspelled as  'Defintion'

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/uniswap-v2-annotated-code/
2. Search for 'Sync or Skip'
3. Search for 'defintion'
4. See errors

**Expected behavior**

'Skip' should be reworded to 'Skim', as this is the name of the function
'Defintion' should be reworded to 'definition'

**Screenshots**

1)
<img width="903" alt="Screenshot 2022-03-31 at 13 42 38" src="https://user-images.githubusercontent.com/37338979/161047849-aaea63c9-d204-4e7e-a0ec-aa73d6133bc6.png">

2)
<img width="902" alt="Screenshot 2022-03-31 at 13 43 06" src="https://user-images.githubusercontent.com/37338979/161047870-34232e7f-ee01-48ed-8f2b-a7207d1c2cf3.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by HursitTarcan** [comment]
I will fix this one too
