### ISSUE TITLE
Potentially inaccurate documentation in example code

### ISSUE THREAD

**Issue by StrongerXi** [ethereum/ethereum-org-website#5862]
**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/smart-contracts/anatomy/#unique-digital-asset
2. Click on `Show all` (if not already enabled)
3. Scroll down to the function `_createPizza`
4. See comment above `assert(pizzaToOwner[id] == address(0));`

**Expected behavior**
A correct explanation on the purpose of the assert statement (e.g., `id` of Pizza should be unoccupied).

**Screenshots**
<img width="754" alt="Screen Shot 2022-03-31 at 1 59 27 PM" src="https://user-images.githubusercontent.com/26714592/161129633-f221384c-5ab8-42dc-a492-2200d81f0363.png">

**Comment by jmcook1186** [comment]
This assert statement just checks the pizza with ID `id` is not already assigned to a user. `address(0)` is the zero address, indicating that specific pizza has not yet been allocated. In the next line, the mapping is updated to the address of `msg.sender` (the address sending the transaction).

So this isn't a bug. I've added a comment to explain in PR #5905.

**Comment by minimalsm** [comment]
Thanks @jmcook1186, closed in #5905

**Comment by minimalsm** [comment]
@all-contributors please add @StrongerXi for bug reports

**Comment by Dariinkaa** [comment]
#5774 
Duplicate of #

**Comment by corwintines** [comment]
This looks like it should be closed based on past discussion.
