### ISSUE TITLE
Transaction count chart encounters error while loading

### ISSUE THREAD

**Issue by lingzhong** [ethereum/ethereum-org-website#5883]
**Describe the bug**

The `TRANSACTIONS TODAY` and `NODES` charts in the front page fail to load.

**To Reproduce**

1. Go to [ethereum.org](https://ethereum.org/)
2. Scroll down to `Ethereum Today` section with charts
3. See error

**Expected behavior**

Both charts should load without error

**Screenshots**

![chart_error](https://user-images.githubusercontent.com/4011137/161386771-ac6052c7-6478-4715-ac49-c5148ab893e9.png)

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

N/A

**Want to contribute?**

Yes :) I'm digging into this bug right now.

**Comment by lingzhong** [comment]
Both charts are backed by etherscan.io APIs, see https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/StatsBoxGrid.js#L459-L478

**Comment by lingzhong** [comment]
Fetching from the API endpoint failed. The error is suggesting the existing API token does not have the right permissions/limits to access Etherscan API Pro endpoints.

![tx_count](https://user-images.githubusercontent.com/4011137/161389563-9b09748e-cef1-440c-81e5-c209fc6c59fc.png)

**Comment by lingzhong** [comment]
The `NODES` chart sometimes loads, but the `TRANSACTIONS TODAY` chart is failing consistently.

The `TRANSACTIONS TODAY` lambda lives here: https://github.com/ethereum/ethereum-org-website/blob/dev/src/lambda/txs.js

**Comment by lingzhong** [comment]
Looks like we're rate limited: `"NOTOK-Missing/Invalid API Key, rate limit of 1/5sec applied"`

**Comment by lingzhong** [comment]
Potential solutions:

- Let's verify what subscription tier do we have with Etherscan and check if we need to upgrade
- Switch to a different API provider
- Check all the places we're calling this API, maybe we don't need to call it as often, or we should use a cache

**Comment by lingzhong** [comment]
The `NODES` chart is loading without error consistently now.

The `TRANSACTIONS TODAY` chart is backed by a paid API, (which I'm not sure if we have upgraded to API PRO), see https://docs.etherscan.io/api-endpoints/stats-1#get-daily-transaction-count

**Comment by lingzhong** [comment]
Hey @pettinarip @minimalsm @wackerow, while I was digging through the error, I saw your discussion and solution in a similar fix #5751 . Can you provide some guidance on how we should proceed in this issue?

I found some potential alternative API provider for `TRANSACTIONS TODAY` data if we decide to move away from Etherscan. Let me know, thanks!

> Potential solutions:
> 
> * Let's verify what subscription tier do we have with Etherscan and check if we need to upgrade
> * Switch to a different API provider
> * Check all the places we're calling this API, maybe we don't need to call it as often, or we should use a cache

---

> The `NODES` chart is loading without error consistently now.
> 
> The `TRANSACTIONS TODAY` chart is backed by a paid API, (which I'm not sure if we have upgraded to API PRO), see https://docs.etherscan.io/api-endpoints/stats-1#get-daily-transaction-count

**Comment by pettinarip** [comment]
Thanks @lingzhong for taking the time to investigate on this.

It seems that the `module=stats&action=dailytx` endpoint (being used by the `TRANSACTIONS TODAY` chart) is [under the PRO plan](https://docs.etherscan.io/api-pro/api-pro#get-daily-transaction-count), which we don't have. I'm wondering if this is something that has changed recently on the Etherscan API (I couldn't find anything on their social networks) because it was working before 🤔

**Comment by pettinarip** [comment]
Fixed.

This was not a problem with the Etherscan API, the api key was removed from the env by mistake.

**Comment by samajammin** [comment]
Thanks for digging into this @lingzhong & fixing @pettinarip!

For reference, we do have a pro API key - Etherscan was kind enough to provide us one for free 😎

**Comment by samajammin** [comment]
@all-contributors please add @lingzhong for bugs.
