### ISSUE TITLE
Sync English pages with CrowdIn for translations

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#589]
**Is your feature request related to a problem? Please describe.**

Our [translated site content](https://ethereum.org/languages/) lags behind the English content. Currently we manually upload files into [our CrowdIn project](https://crowdin.com/project/ethereumfoundation) for translation.

**Describe the solution you'd like**

- Explore [CrowdIn's Github integration](https://support.crowdin.com/github-integration/) as a way to keep CrowdIn files synced with our Github source files.
- If possible, use a [configuration file](https://support.crowdin.com/configuration-file/)

**Describe alternatives you've considered**

We've explored ditching CrowdIn & only using Github to manage translations ([similar to how React & Vue manage their documentation translations](https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html#backstory)) but for now we've decided to stick with CrowdIn given many of our translators are unfamiliar with Git.

**Additional context**

**Comment by yavorysynka** [comment]
Hello Sam!

Let's set up a sync together this week 🙂
sending you details in the email!

**Comment by faraggi** [comment]
Hi @yavorysynka , you might have meant *my* email...  :)
In any case, adding @samajammin  to the loop is obviously useful and .

**Comment by yavorysynka** [comment]
got it!
already sent you guys an email 🙂

**Comment by samajammin** [comment]
See for config example: https://github.com/Andrulko/ethereum-org-website/blob/dev/crowdin.yml

Thanks @Andrulko!

**Comment by samajammin** [comment]
FYI, I'm hoping I'll have time to knock this out next week.

Regarding the config file, I think we can mostly follow that example above, although instead of specifying every single .md file to translate, I think we should default to adding all files, e.g.:
```
  - source: /docs/**/*.md
    ignore:
      - /docs/%two_letters_code%/
    translation: /docs/%two_letters_code%/**/%original_file_name%
```
Then explicitly adding "ignore" cases.

I think that will give us a more flexible approach vs. having to explicitly add every file. We want the default behavior to be to add any new file into CrowdIn.

**Comment by Andrulko** [comment]
I don't remember exactly why but I've made a decision to specify folder by folder o_O Probably, because I'm not a big fan of `ignore` :D

Your configuration should work fine too and whenever you add new folder to GitHub repo, it will be auto-synced with Crowdin.

**Comment by minimalsm** [comment]
During several discovery calls we noticed that GitHub to Crowdin automation via API does not allow us to review minor changes to source content and decide if translations should be kept. This means that small changes/typos in English (many of which have no effect on other languages) will erase the current translation for that string in ~40 other languages. Until we find a workaround to resolve this (or Crowdin releases a way to do this) I believe this is a non-starter.

We should close this issue and capture it internally on Notion.

**Comment by Andrulko** [comment]
Are you aware of `update_option` parameter available for Update File endpoint?
https://support.crowdin.com/api/v2/#operation/api.projects.files.put

The same parameter is available in API v1 (it's considered as deprecated, usage of API v2 is preferrable):
https://support.crowdin.com/api/api-integration-setup/#titles-update-file

The `update_option: update_as_unapproved` will allow to keep translations but remove approvals. Mainly it's designed for key/value based files though but may work with MD 🤔

The usage of Advanced Workflows might be also helpful, it allows to auto-apply 100% TM matches every time you push the new content to the project:
https://support.crowdin.com/advanced-workflows

**Comment by minimalsm** [comment]
Going to close this out and capture it internally as per [the comments on the Q4 roadmap update](https://github.com/ethereum/ethereum-org-website/issues/4215#issuecomment-1007882026). Unfortunately, due to the edge cases outlined above this isn't something we can solve for now.
