### ISSUE TITLE
Article: Understanding the Yellow Paper

### ISSUE THREAD

**Issue by qbzzt** [ethereum/ethereum-org-website#5890]
**Tutorial title**

Understanding the Yellow Paper

**Tutorial description**

As we get more developers into web3, we get more people who are confused by the mathematical notation in the [Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf). It would be useful, IMAO, to have an article that explains to developers who lack mathematical education how to understand the yellow paper.

**Tag your tutorial**

yellow-paper

**Publication**

Not written yet

**Skill level**

beginner 

**Hosted on Ethereum.org or hosted elsewhere?**

ethereum.org

**For tutorials to be hosted on Ethereum.org: Tutorial Content**

I need to write it first.

**Comment by minimalsm** [comment]
I agree this is a valuable resource to have @qbzzt. One thing that I'm not clear on: how often does the yellow paper get updated? Do we have EIP-1559 in here now? Or more recent changes?

**Comment by minimalsm** [comment]
Also the yellow paper is 41 pages long. How long do you forsee this being? Is it like a SparksNotes version? Or did you want to go through everything line by line similar to your other tutorials?

**Comment by qbzzt** [comment]
> One thing that I'm not clear on: how often does the yellow paper get updated?

AFAIK, the last version right now is Berlin. 

> Also the yellow paper is 41 pages long. How long do you forsee this being? Is it like a SparksNotes version? Or did you want to go through everything line by line similar to your other tutorials?

Good question - I'm not sure. The whole point of looking at the yellow paper is to find tiny details that aren't documented authoritatively elsewhere, so just the highlights isn't useful. 

I think it would be best to go through it, not line by line but equation by equation. There are 358 equations, so while long it won't be too unwieldy.

**Comment by qbzzt** [comment]
Should I get started on this?

**Comment by samajammin** [comment]
Hmmmm I like this idea @qbzzt! Similar question to @minimalsm, I'm curious how you see this being broken up e.g. are there a particular topics within the yellow paper that you could write "chapters" (individual articles) for?

I see this being valuable but I don't want to make this an enormous project. It'd be great to understand how might we attack this in pieces vs. committing to this project that may require many hours of work from you.

**Comment by qbzzt** [comment]
How about we start with the EVM? That's the part I know best, and the one least likely to be changed by the merge. This means sections 9.4, 9.5 and the related appendices.
