### ISSUE TITLE
Fix typo on ERC-20 Contract Walkthrough page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5892]
**Describe the bug**

On the 'ERC-20 Contract Walkthrough' page, _but_ is misspelled as _buf_.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/erc20-annotated-code/#hooks
2. Read the sentence under the code block
3. See error

**Expected behavior**

_Buf_ should be changed to _but_

**Screenshots**
<img width="895" alt="Screenshot 2022-04-04 at 13 32 51" src="https://user-images.githubusercontent.com/37338979/161535603-2e9dc664-5ce3-462f-964d-892192613524.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by KaranKaira** [comment]
@lukassim , Hey I would like to take this up.
