### ISSUE TITLE
KyberSwap

### ISSUE THREAD

**Issue by tramtrinh14** [ethereum/ethereum-org-website#5903]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

<https://chainsecurity.com/wp-content/uploads/2021/04/ChainSecurity_KyberNetwork_DMM_Dynamic-Market-Making_Final.pdf>

**Is your dapp open source?**

<Yes.>

**Can a user access the dapp without creating an account?**

<Yes.>

**Are dapp funds non-custodial?**

<Yes.>

**Do you offer community support?**

<https://t.me/kybernetwork>

**Describe any geographical restrictions on usage of your dapp**

<No.>

**Dapp title**

KyberSwap

**Dapp description**

<KyberSwap is the best place to trade and earn on networks such as Ethereum, Polygon, Binance Smart Chain (BSC), Avalanche, and Fantom; you can get the best rates for your token swaps and earn more with your token assets.>

**Dapp logo**

<https://drive.google.com/drive/folders/1gd6PkS3YL6LguiY7FPKwZkAWViPauzVo>

**Brand color**

<HEX #31cb9e>

**Comment by corwintines** [comment]
Closing in favor of https://github.com/ethereum/ethereum-org-website/issues/9147
