### ISSUE TITLE
Clarify what should live on deprecated software page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5921]
**Is your feature request related to a problem? Please describe.**

It'd be useful to outline what should & should not be listed on the deprecated software page:
https://ethereum.org/en/deprecated-software/

It may be a tough policy/criteria to create but some rough guide may help to inform decisions moving forward.

**Describe the solution you'd like**

Not sure what the best solution is - I welcome input!

Perhaps as something as simple as criteria outlined on the page (below the intro)? Maybe there's some threshold of usage, like downloads, we could use to determine this? I'd say if in doubt we should be lenient & include projects given that there's likely more potential benefit from someone searching for a project & discovering it's deprecated vs. the downside of us listing a bunch of old projects (maybe lower UX for people to have to sift through?). I believe the primary user-journey we originally wanted to solve for was the large number of site searches for "mist" that we didn't previously return any results for.

**Describe alternatives you've considered**

We could create a "listing policy" with a corresponding GH issue template (like we do for products, dev tools, exchanges, etc.) but that feels a bit overkill to me.

**Additional context**

As part of our wiki/documentation consolidation work, many pages exist that reference deprecated projects: https://github.com/ethereum/ethereum-org-website/issues/5731
It's unclear which of these are "worthy" of being added to this list.

Some Discord discussion on what should be included on this page came out of this PR: https://github.com/ethereum/ethereum-org-website/pull/4573

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
In my opinion I think we could deprecate this page at this point. Im not sure how we properly maintain this with the scale of projects that sunset.

Either that, or we add a disclaimer saying this page is deprecated as we have not been maintaining this, and don't think we will have intentions of doing it either.

**Comment by wackerow** [comment]
I think this page is extremely challenging to maintain. As time has gone on, many projects have come and gone, and this page is not currently linked out anywhere (that I can see) from other pages in the repo.

Peaking at Matomo this appears to have around 8 page views for the month, with long load time and 100% bounce rate. I would recommend we kill this page with a redirect back to the homepage.

**Comment by wackerow** [comment]
Opened #12193 to initialize the deprecation of this page. Open for community contribution; going to close this issue out.
