### ISSUE TITLE
Warning! Error encountered during contract execution [out of gas] 

### ISSUE THREAD

**Issue by alexisdavidson** [ethereum/ethereum-org-website#5970]
Hi, I'm following this tutorial https://ethereum.org/en/developers/tutorials/how-to-mint-an-nft/ and I'm getting the error: Warning! Error encountered during contract execution [out of gas]  on Ropsten etherscan.
Any idea how to set the gas limit or fix this?

**Comment by corwintines** [comment]
Going to close this out as its gone stale. If this issue still persists, do you mind reviving @alexisdavidson :)

The tutorial has been updated to use Sepolia as well, so hopefully that issue was fixed with the new testnet.
