### ISSUE TITLE
[Scaling] Adding a Validium: Arbitrum AnyTrust

### ISSUE THREAD

**Issue by jaybuidl** [ethereum/ethereum-org-website#5972]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

Arbitrum AnyTrust

**Product description:**

An Arbitrum mode for ultra low-cost transactions with strong security guarantees. AnyTrust Chains allow for much lower cost and faster withdrawals, in exchange for a minimal extra trust assumption. The key advantage of AnyTrust, compared to sidechains, is that because it’s built on top of Ethereum, AnyTrust requires much less trust.

**How long has it been around?**

Announced but not launched yet.

**Where do you think it should go?**

`src/content/developers/docs/scaling/validium/index.md`

**GitHub URL**

Not sure about the exact repo, it may not be open-source yet: https://github.com/OffchainLabs

**Docs URL**

https://medium.com/offchainlabs/introducing-anytrust-chains-cheaper-faster-l2-chains-with-minimal-trust-assumptions-31def59eb8d7

**Is the product open source?**

Not sure.

**Additional context**

I am not affiliated with Arbitrum but was looking into their recent blog posts about Nitro and AnyTrust. It looks like AnyTrust will launch after Nitro makes it to mainnet.

**Comment by minimalsm** [comment]
[Closing as per this comment.](https://github.com/ethereum/ethereum-org-website/pull/5973#issuecomment-1094976532)
