### ISSUE TITLE
Request to add Foundry

### ISSUE THREAD

**Issue by devtooligan** [ethereum/ethereum-org-website#5984]
Previously, a [pr was merged](https://github.com/ethereum/ethereum-org-website/pull/5376) that added Foundry as a dev framework.  But it was never added as a developer tool and does not currently show up on the [setup local environment](https://ethereum.org/en/developers/local-environment/) page.  Foundry should also be added as a dev tool and that is the reason for submitting this ticket. 

**Product name:**

Foundry

**Product description:**

A blazing fast, portable and modular toolkit for Ethereum application development written in Rust.

**How long has it been around?**

September 2021

**Where do you think it should go?**

[Local Environment](https://ethereum.org/en/developers/local-environment/)

**GitHub URL**

https://github.com/gakonst/foundry

**Docs URL**

https://book.getfoundry.sh

**Is the product open source?**

hell yes

**Additional context**

based

**Comment by samajammin** [comment]
Agreed! Just came here to create a GH issue for this 😄

**Comment by devtooligan** [comment]
Can reference [this pr](https://github.com/ethereum/ethereum-org-website/pull/6000) for this ticket.  

Many of the places DappTools was removed, Foundry sb added

**Comment by devtooligan** [comment]
lemme know if there's any way i can help w this one
