### ISSUE TITLE
Suggest removing DappTools

### ISSUE THREAD

**Issue by devtooligan** [ethereum/ethereum-org-website#5985]
> `dapptools` is currently in a stage of clandestine development where support for the casual user may be deprived. The software can now be considered free as in free puppy. Users seeking guidance can explore using foundry as an alternative - [dapptools README](https://github.com/dapphub/dapptools/pull/927/files)

Anyone who would use the ethereum.org site to choose a development tool or framework is most likely a new or inexperienced user.  Because DappTools is [no longer supported](https://github.com/dapphub/dapptools/pull/927/files), it could be difficult or even frustrating if a new dev chose DappTools based on its presence on the ethereum.org site, and then subsequently ran into a bug and couldn't get any support on the dapp.tools.chat after investing some time with it.

In reviewing the ethereum-org-website [Add a developer tool](https://ethereum.org/en/contributing/adding-developer-tools/) guidelines:
> Has it been recently updated?

Aside from the "free as a puppy" update to the README, there have not been any significant updates in months.

> Is the tool actively maintained?

There are [135 open issues](https://github.com/dapphub/dapptools/issues) (not that that number is really that meaningful tbh) including bug fix requests like [this one.](https://github.com/dapphub/dapptools/issues/899)

As a former (and current) DappTools user I can sincerely say that the Ethereum ecosystem owes a deep debt of gratitude to the core DappTools team for all they have done.  And so, it is with heavy heart that I propose removing DappTools as a suggested developer tool and framework from ethereum.org

**Comment by minimalsm** [comment]
Hey @devtooligan, thanks for raising this.

I support removing dapptools. Would you be interested in putting up a PR for this? If not, I can get to it this week.

**Comment by minimalsm** [comment]
Yup just deleting the call-outs to dappnode. They'll be in a few non-English languages too but you should be able to search the codebase for them pretty easily.

**Comment by minimalsm** [comment]
Closed by #6000
