### ISSUE TITLE
Please add Avado to the Solostaker options

### ISSUE THREAD

**Issue by JosPoulakis** [ethereum/ethereum-org-website#5992]
[ava.do](https://ava.do/)
Opensource: Yes
Audited: No
Bug Bounty: No
Battle-tested: No
Trustless: Yes
Permissionless: Yes
Multi-Client: Yes
Economical: Yes
Avado is a Switzerland based Crypto hardware company providing a Plug&Play Ethereum staking solution with an option to run the minority client Teku (Also adding Nimbus at the moment) 
CEO is Bernd Lapp former Ethereum advisor and CTO Stefaan Ponnet

**Comment by JosPoulakis** [comment]
Great, thank you for that. We will fill it out and come back to you.

**Comment by corwintines** [comment]
Closing: https://github.com/ethereum/ethereum-org-website/pull/7636
