### ISSUE TITLE
Filter out preview deploy traffic from Matomo production data

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#5998]
**Describe the bug**

Not 100% sure this is a bug but noticed cases in Matomo of data reported from our staging environments (i.e. preview deploys), e.g. https://matomo.ethereum.org/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday#?idSite=4&period=range&date=2022-03-21,2022-04-05&segment=&category=CustomReports_CustomReports&subcategory=13

**To Reproduce**

1. Go to https://matomo.ethereum.org/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday#?idSite=4&period=range&date=2022-03-21,2022-04-05&segment=&category=CustomReports_CustomReports&subcategory=13
2. See `ethereumorgwebsitedev...` preview deploy entry

**Expected behavior**

Matomo should only collect data from production traffic (i.e. https://ethereum.org/)

We should
1. confirm if we are indeed collecting preview deploy traffic
2. if so, sort out how to filter that traffic out

**Screenshots**

![Image 2022-04-11 at 11 17 22 AM](https://user-images.githubusercontent.com/8097623/162804486-5e1e04c0-42e6-4ea1-a2df-1a7e256194f3.jpg)

**Additional context**

This is the plugin we use:
https://github.com/kremalicious/gatsby-plugin-matomo

We may want to configure options to solve for this:
https://github.com/kremalicious/gatsby-plugin-matomo#options

**Comment by pettinarip** [comment]
In GC `NODE_ENV` is `production` for Production Builds and Pull Request Builds. https://support.gatsbyjs.com/hc/en-us/articles/360052322954-Environment-Variables-Specific-to-Gatsby-Cloud

What I'm planning to do is to basically avoid loading the plugin if `GATSBY_IS_PREVIEW` is true. Basically because we done have control over that on the plugin.

**Comment by wackerow** [comment]
Fixed with #6366
