### ISSUE TITLE
missing OGP tags in HEAD

### ISSUE THREAD

**Issue by sneg55** [ethereum/ethereum-org-website#6]
Please add http://ogp.me/ tags so when links shared at social media they will show with a proper cover image and title/description

**Comment by bmann** [comment]
I'm new to Vuepress, so just digging through this. Here's an article with some tips https://alligator.io/vuejs/vue-seo-tips/

There is currently one meta header in the config.js file.

**Comment by bmann** [comment]
OK, found some examples I can get started with https://github.com/vuejs/vuepress/issues/777

**Comment by bmann** [comment]
Looks like this plugin is specifically for Vuepress and can help https://github.com/lorisleiva/vuepress-plugin-seo

**Comment by bmann** [comment]
Merged for now
