### ISSUE TITLE
Search is indexing 404 pages

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#6014]
**Describe the bug**

Our search is currently indexing our 404 page. Worse still, it is indexing it multiple times for different languages with the same content.

**To Reproduce**

1. Go to 'ethereum.org'
2. Focus on the searchbar
3. Type 'we could'

**Expected behavior**

- The 404 page should not index
- We should not have duplicate content

**Screenshots**

![image](https://user-images.githubusercontent.com/62268199/162991030-5133900d-968a-4e78-a23e-e71bce8bcde1.png)

**Want to contribute?**

~~We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.~~

Unfortunately, this is likely an issue that requires the use of internal accounts (Algolia). External contributors should not spend much time investigating this issue.

**Comment by samajammin** [comment]
@corwintines might be an easy one for you to pick up, given your previous work with Algolia?

**Comment by samajammin** [comment]
Assigning to you for now 😄

**Comment by samajammin** [comment]
Interesting - I'm unable to reproduce this issue - @minimalsm do you still see this?

**Comment by minimalsm** [comment]
We changed the 404 H1 after this screenshot was taken from 'Resource not found' to 'We couldn't find that page' 😬 though I did put that in the 'how to reproduce' section, I probably should've taken a new screenshot 🤪

**Comment by corwintines** [comment]
Tested this out, seems to be resolved now
