### ISSUE TITLE
Create a listing policy for online communities

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6017]
**Is your feature request related to a problem? Please describe.**

Our listing policies aim to provide transparent criteria on how to suggest products/resources/services to be added ethereum.org & to give insight on how we evaluate proposals. While we already do have a listing policy for "[Ethereum products](https://ethereum.org/en/contributing/adding-products/)", we've learned that dedicated listing policies can add greater clarity on the information we require (e.g. like we have for [adding exchanges](https://ethereum.org/en/contributing/adding-exchanges/)). 

**Describe the solution you'd like**

Create a dedicated listing policy for online communities, which we display here:
https://ethereum.org/en/community/online/

This policy should outline the criteria we use to evaluate communities & decide if we will list them. Potential criteria might be:
- Is it related to Ethereum, the underlying technologies Ethereum uses, or to crypto broadly?
- Is the community open to all? Is it free or paid?
- Is the community legitimate (we'd need a way to define this)? Is there risk of new members being scammed or mislead?
- Is the community active? Does the community have consistent moderation?

**Additional context**

Similar idea/initiative to #5767

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
Closing in lieu of resurfaced issue #10790
