### ISSUE TITLE
Add BeFi Wallet request

### ISSUE THREAD

**Issue by IvanMacaron** [ethereum/ethereum-org-website#6027]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**When did your wallet go live to users?**

July 2021

**Does your wallet have an active development team?**

Yes,always

**Is your wallet open-source?**

Not yet. We are preparing to open part of the core code.

**Is your wallet globally accessible?**

Yes

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial, the private key is controlled by the user and stored in the user’s device, like Metamask.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

BeFi Wallet protects and safeguards user's digital assets using AES-256 Encryption, Key Offset Correction, Personal Password Verification, and Device Fingerprint Key.
BeFi Wallet has been successfully running for more than 15months and with zero hack record.

**Does the wallet have fiat on-ramps?**

Not yet.

**Does the wallet allow users to explore dapps?**

Yes

**Does the wallet have integrated defi/financial tools?**

No

**Can a user withdraw to their card?**

No

**Does the wallet offer limits protection?**

Have a max amount limited.

**Does the wallet allow high-volume purchases?**

Yes

**Does the wallet have an integrated token swap?**

No

**Is the wallet a multi-signature wallet?**

Not yet.

**Wallet title**

BeFi Wallet

**Wallet description**

BeFi Wallet is the global leading decentralized, multi-chain wallet and NFT gateway aimed to safely connect users to the crypto world in the most convenient way.

**Wallet logo**

https://github.com/befiwalletdao/befi_assets/blob/main/logox512.png

**Background colour for brand logo**

<span>#15181C</span>

**URL**

https://befiwalletdao.com/

**Comment by minimalsm** [comment]
Hey @IvanMacaron, thanks for raising the issue. Just wanted to note as per [our listing policy](https://ethereum.org/en/contributing/adding-products/) we aren't currently adding new wallets to the site while we evaluate our criteria.

> A note on adding wallets: as part of [our Q1 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/5105), we are refining our wallets page. This will include refining the listing criteria for our wallets page. Until we have researched, established, and published refined listing criteria, we will not be actively adding new wallets to the website.

As such, a new application will need to make at this point after we determine our updated criteria. Closing this out for now because this could radically change but please do reapply if eligible when we release this.
