### ISSUE TITLE
Rephrase the description of Ethereum upgrades on the homepage

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#6030]
**Describe the bug**

The phrasing on the 'Level up your upgrade knowledge' card on the homepage is not ideal.
The sentence reads _Ethereum consists of interconnected upgrades designed to make the network more scalable, secure, and sustainable_.

**To Reproduce**

1. Go to https://ethereum.org/en/
2. Scroll down to the 'Explore Ethereum.org' section
3. Read the first card, titled 'Level up your upgrade knowledge'

**Expected behavior**

The sentence should be rephrased to something like _The Ethereum roadmap consists of interconnected upgrades designed to make the network more scalable, secure, and sustainable_.

**Screenshots**
<img width="429" alt="Screenshot 2022-04-14 at 13 53 00" src="https://user-images.githubusercontent.com/37338979/163386148-8376e9cb-68d8-485b-a068-c15cdbdae1f8.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by shivam-sharma7** [comment]
could i fix it?
