### ISSUE TITLE
Fix typo on the Introduction to Web3 page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#6031]
**Describe the bug**

In the 'Further reading' section on the Introduction to Web3 page, the first article contains a typo:
_What is Web3? The Decentralized Interent of the Future Explained_

**To Reproduce**

1. Go to https://ethereum.org/en/web3/#further-reading
2. Read the first article title
3. See error

**Expected behavior**

'Interent' should be changed to 'Internet'

**Screenshots**
<img width="774" alt="Screenshot 2022-04-14 at 14 00 01" src="https://user-images.githubusercontent.com/37338979/163386722-a1c9367a-e0d5-4848-b745-970fc4ba4c11.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Closed by #6033
