### ISSUE TITLE
Change position of quotation marks on MEV page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#6032]
**Describe the bug**

The first sentence in the 'Miner extractable value' section of the 'Maximal extractable value' page contains quotation marks that include the end punctuation, when they should only contain the term _miner extractable value_.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/mev/#miner-extractable-value
2. Read the first sentence
3. See error

**Expected behavior**

The closing quotation mark should be moved before the period.
The sentence should be _This concept was first applied under the context of proof-of-work, and was initially referred to as "miner extractable value"._

**Screenshots**
<img width="662" alt="Screenshot 2022-04-14 at 14 04 00" src="https://user-images.githubusercontent.com/37338979/163387398-6f95c5f7-c241-48f0-b470-5ab7a839838a.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by manuperalta** [comment]
Hey, could I fix this one? I'll get on it right away

**Comment by minimalsm** [comment]
Thanks for offering @manuperalta, all yours!
