### ISSUE TITLE
How to Survive in The Ethereum Dark Forest

### ISSUE THREAD

**Issue by rodrigoherrerai** [ethereum/ethereum-org-website#6059]
We'll consider [our content resources policy](https://ethereum.org/en/contributing/content-resources/) when reviewing the tutorial, so please take a look there first.

**How to Survive in The Ethereum Dark Forest**

**Understand how front-running bots operate from first principles and how to avoid them by using FlashBots**

**#MEV #FlashBots #bots**

**https://medium.com/better-programming/how-to-survive-in-the-ethereum-dark-forest-f21c9eca4bfe**

**intermediate**

**https://medium.com/better-programming/how-to-survive-in-the-ethereum-dark-forest-f21c9eca4bfe**

**For tutorials to be hosted on Ethereum.org: Tutorial Content**

**https://medium.com/better-programming/how-to-survive-in-the-ethereum-dark-forest-f21c9eca4bfe**

**Comment by mohammadobaid1** [comment]
So what we are looking here ? @rodrigoherrerai  . Are we looking to modify that tutorial and publish it on ethereum site?

**Comment by rodrigoherrerai** [comment]
Yep or publish it directly from medium

**Comment by corwintines** [comment]
@rodrigoherrerai sorry for letting this go stale. 

Im going to close this out for now, but if you would like to revive this in a new issue feel free. I could see this being good as an external tutorial, or potentially on the MEV page as well.
