### ISSUE TITLE
Period should be outside of quote

### ISSUE THREAD

**Issue by hezhao** [ethereum/ethereum-org-website#6072]
Multiple places in https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/, period should be outside of quote

- `"committee."` -> `"committee".`
- `"slot."` -> `"slot".`
- `"epoch."` -> `"epoch".`

> At least 128 validators are required to attest to each shard block – this is known as a "committee."

> The committee has a time-frame in which to propose and validate a shard block. This is known as a "slot." Only one valid block is created per slot, and there are 32 slots in an "epoch." After each epoch, the committee is disbanded and reformed with different, random participants. This helps keep shards safe from committees of bad actors.

**Comment by minimalsm** [comment]
Closed in #6073
