### ISSUE TITLE
The theme-toggler icon on navbar (UX)

### ISSUE THREAD

**Issue by 1337-ishaan** [ethereum/ethereum-org-website#6078]
The theme-toggler icon on navbar shows *moon* icon when dark mode, for a better UX flow, it should be the opposite.

<img width="448" alt="Screenshot 2022-04-21 at 2 58 39 AM" src="https://user-images.githubusercontent.com/64636222/164325973-c029ef68-eeac-4d3f-af9d-19f237095e90.png">

<img width="428" alt="Screenshot 2022-04-21 at 2 58 48 AM" src="https://user-images.githubusercontent.com/64636222/164326007-2f7d1e2d-2a53-44b0-8d0e-ffe5229e1a57.png">

**Comment by 1337-ishaan** [comment]
I would like to work on this issue, kindly assign me :)

**Comment by nloureiro** [comment]
Yes, the icons should be the other way around. Can you create a PR to fix it?

**Comment by minimalsm** [comment]
Closed by #6079
