### ISSUE TITLE
Instructions to Edit Documentation does not redirects to correct GitHub Markdown file

### ISSUE THREAD

**Issue by consentsam** [ethereum/ethereum-org-website#6092]
### Issue
On [Ethereum documentation](https://ethereum.org/en/developers/docs/) homepage's second paragraph, there is a hyperlink which says 
> All documentation can be edited via GitHub – if you're unsure how, follow these instructions.

In this line the text 

> **follow these instructions**

is hyperlinked and it is supposed to take us to this GitHub file/link https://github.com/ethereum/ethereum-org-website/blob/dev/docs/contributing/editing-markdown.md, instead it routes us to the link https://github.com/ethereum/ethereum-org-website/tree/dev/docs/contributing/EDITING_MARKDOWN.md and since this latter file does not exists, the error **Page Not Found** is thrown.

### To Reproduce

1. Go to [Ethereum documentation](https://ethereum.org/en/developers/docs/)
2. Find the hyperlinked text **follow these instructions** on the second paragraph
3. It will redirect you to the GitHub file https://github.com/ethereum/ethereum-org-website/tree/dev/docs/contributing/EDITING_MARKDOWN.md
5. This happens because there is no such file as `EDITING_MARKDOWN.md` instead the file is `editing-markdown.md` in the same location.

### Expected behavior

It should redirect us to this page https://github.com/ethereum/ethereum-org-website/blob/dev/docs/contributing/editing-markdown.md

The expected behaviour can be noted by the following procedure
1. Go to [Ethereum documentation](https://ethereum.org/en/developers/docs/)
2. Find the button **Edit Page** on the right.
3. Click on it 
4. It will redirect you to the GitHub file https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/index.md
5. Now find the hyperlinked text [follow these instructions](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/contributing/editing-markdown.md).
6. Click on it
7. This will take you to correct page where you can see how to edit the documentation.

**Screen Recording of the issue**

You can find the issue recorded here. When I click on the **follow these instructions**, It shows me the error. After error when I click on the button **Edit on GitHub**, then it redirects me to the correct GitHub Markdown.

https://user-images.githubusercontent.com/16432541/164650652-8e334134-c7ee-4cd8-b6da-325d162eb503.mp4

**Desktop (please complete the following information):**

This issue can be replicated on mobile device as well as on a computer system.

**Want to contribute?**

I would love to fix this issue.

**Comment by samajammin** [comment]
Hey @consentsam - thanks for opening this issue!

I'm not able to reproduce this bug.

When a navigate to:
https://ethereum.org/en/developers/docs/

That link takes me to:
https://github.com/ethereum/ethereum-org-website/blob/dev/docs/contributing/editing-markdown.md

Which loads fine (i.e. it doesn't 404).

Are you still having this issue? If not please close this out.

**Comment by Alibalala** [comment]
好的，已收到

**Comment by consentsam** [comment]
Hello @samajammin, 
I put the issue on Discord as well and it seems like someone fixed it. So, I think this issue can be closed off. Thank you for your response!
