### ISSUE TITLE
Website translators needed!

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#610]
### We're constantly in need of volunteers to help translate ethereum.org!
Given that Ethereum is a global project, we believe it's critical that Ethereum.org is accessible to everyone, regardless of their nationality or language. Our community has been working hard to make this vision a reality but we could use your help!

### How to get involved
Check out [ethereum.org/languages](https://ethereum.org/languages/) for instructions on how to get started as a translator & to monitor the progress of each language. Don't see your language listed? Please comment here & we'll help get you set up.

- [ethereum.org/languages](https://ethereum.org/languages/)
- [Invite link to translate in CrowdIn](https://crowdin.com/project/ethereumfoundation/invite)
- [Join our Slack workspace for collaboration & support](https://join.slack.com/t/ethtranslation/shared_invite/enQtOTc2MTA3OTE4NjMwLTc0OWFhYmY2ZjY4MWYzODdiMTBjOGMyNWU0MDJkNWRkNDFlNzg0NjZlNTUwMWQxM2E5MTFjMWJhMDU2Y2M3OWI)

**Comment by JefteCosta** [comment]
ola!
gotaria de ajudar a traduzir para o pt-BR
