### ISSUE TITLE
Content translators needed!

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#611]
### We're constantly in need of volunteers to help translate Ethereum content!
In addition to translating ethereum.org (#610), we're also undertaking an initiative to translate Ethereum content from the community. Our amazing group of volunteers have been working hard to make this vision a reality but we could use your help!

### How to get involved
Check out [ethereum.org/languages](https://ethereum.org/languages/) for instructions on how to get started as a translator.

- [ethereum.org/languages](https://ethereum.org/languages/)
- [Invite link to translate in CrowdIn](https://crowdin.com/project/contents-translation)
- [Join our Slack workspace for collaboration & support](https://join.slack.com/t/ethtranslation/shared_invite/enQtOTc2MTA3OTE4NjMwLTc0OWFhYmY2ZjY4MWYzODdiMTBjOGMyNWU0MDJkNWRkNDFlNzg0NjZlNTUwMWQxM2E5MTFjMWJhMDU2Y2M3OWI)

**Comment by molecula451** [comment]
@samajammin I am ready for all spanish translation needed.

**Comment by samajammin** [comment]
Thanks @molecula451! Let us know if any instructions aren't clear. Here's the specific project links for Spanish:
https://crowdin.com/project/ethereumfoundation/es-EM#
https://crowdin.com/project/contents-translation/es-ES#

We encourage you to join the #spanish channel in our [Slack](https://join.slack.com/t/ethtranslation/shared_invite/enQtODQzNTM0ODEzMjUzLTM3ZTg1ZjkxNDFjY2ZiOGNlM2M0ZmNhZmVmMjI3NGM5OWE4YjhhZTdkYmVkZThiNzVmM2JlYzM3NTA5NjVmNTE) as well

**Comment by molecula451** [comment]
@samajammin There is an issue I've been seeing in the Spanish slang crypto-space where people still mention 'Blockchain' but instead they talk about as 'La Blockchain' which is Ok but instead if we would like the appropiate transalation we better use it's correct meaning which is 'La Cadena de Bloques' .

**Comment by molecula451** [comment]
> Thanks @molecula451! Let us know if any instructions aren't clear. Here's the specific project links for Spanish:
> https://crowdin.com/project/ethereumfoundation/es-EM#
> https://crowdin.com/project/contents-translation/es-ES#
> 
> We encourage you to join the #spanish channel in our [Slack](https://join.slack.com/t/ethtranslation/shared_invite/enQtODQzNTM0ODEzMjUzLTM3ZTg1ZjkxNDFjY2ZiOGNlM2M0ZmNhZmVmMjI3NGM5OWE4YjhhZTdkYmVkZThiNzVmM2JlYzM3NTA5NjVmNTE) as well

I am there! no bounties out for the whole transalation ?

**Comment by laxman954** [comment]
@samajammin i am ready for translating English - Tamil (india) (en-ta) already contributing for _[ethereumfoundation tamil](https://crowdin.com/translate/ethereumfoundation/451/en-ta)_ . Please add the same language for https://crowdin.com/project/contents-translation (tamil) also. Thanks !!!

**Comment by JefteCosta** [comment]
Olá!
Estou pronto para ajudar na tradução para pt-BR

**Comment by samajammin** [comment]
@sorumfactory please see @laxman954's comment above & add Tamil as a language translation for https://crowdin.com/project/contents-translation - thanks!

**Comment by samajammin** [comment]
Thanks for volunteering @JefteCosta! Please see the instructions in the description to get involved & let us know if you have any questions.

**Comment by laxman954** [comment]
@sorumfactory  @samajammin  can you please update on adding tamil as language translation.

**Comment by L-KH** [comment]
I would like to work in Arabic translation if its still available. thx

**Comment by samajammin** [comment]
Thanks @L-KH! You can find Arabic translations for ethereum.org & our community content here:
https://crowdin.com/project/ethereumfoundation/ar#
https://crowdin.com/project/contents-translation/ar#

Check out [ethereum.org/languages](https://ethereum.org/languages/) for instructions on how to get started as a translator.
- [ethereum.org/languages](https://ethereum.org/languages/)
- [Invite link to translate in CrowdIn](https://crowdin.com/project/contents-translation)
- [Join our Slack workspace for collaboration & support](https://join.slack.com/t/ethtranslation/shared_invite/enQtOTc2MTA3OTE4NjMwLTc0OWFhYmY2ZjY4MWYzODdiMTBjOGMyNWU0MDJkNWRkNDFlNzg0NjZlNTUwMWQxM2E5MTFjMWJhMDU2Y2M3OWI)
