### ISSUE TITLE
Link in setting up a light GETH node has expired and needs to be replaced

### ISSUE THREAD

**Issue by byhow** [ethereum/ethereum-org-website#6148]
**Describe the bug**

In this [article](https://ethereum.org/en/developers/tutorials/run-light-node-geth/#mainnet-and-testnets) where it stated: [public test networks](https://ethereum.org/en/networks/#testnets/) is no longer the path to the testnet introduction url and needs to be updated

**To Reproduce**

1. Go to [article](https://ethereum.org/en/developers/tutorials/run-light-node-geth/#mainnet-and-testnets) 
1. Click on [public test networks](https://ethereum.org/en/networks/#testnets/)
1. Shows `We couldn't find that page`

**Expected behavior**

1. Should've gone to this page: https://ethereum.org/en/developers/docs/networks/#testnets, or:
2. Should redirect this github markdown file: https://github.com/ethereum/ethereum-org-website/blob/dev/networks/#testnets that reside [here](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/tutorials/run-light-node-geth/index.md#mainnet-and-testnets-mainnet-and-testnets) to this file: https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/networks/index.md#testnets-testnets

**Screenshots**

**Desktop (please complete the following information):**

- Browser: Google Chrome
<img width="727" alt="image" src="https://user-images.githubusercontent.com/25713361/165005810-f69419b9-1359-4ba9-8360-062440cb58d0.png">

**Want to contribute?**

Yes, I will be happy to make the updates needed

**Comment by noahliechti** [comment]
@byhow are you still working on this?

**Comment by byhow** [comment]
Hi @noahliechti, thanks for confirming! I will create a PR shortly. You are more than welcome to review the PR if you would like to

**Comment by byhow** [comment]
@noahliechti In case if you want to work on a similar issue, when I check the other occurances for the `networks/#testnets` path in the document, all of the `/developers/docs/networks/#testnets` need to be updated to the `/developers/docs/networks/#ethereum-testnets` to reflect changes here: https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/networks/index.md#ethereum-mainnet-ethereum-mainnet

**Comment by noahliechti** [comment]
@byhow Thanks for the opportunity. I think I'll go for another open issue, since there many others to choose from :)
