### ISSUE TITLE
Add wallet: Crypto.com DeFi Wallet on ethereum.org

### ISSUE THREAD

**Issue by dansoncheng** [ethereum/ethereum-org-website#6155]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**
We have an internal security team auditing every feature, and we’ve also hired an external security audit team to audit the security status of the app.

In feature-wise, we have passcode/biometric as security measures

**When did your wallet go live to users?**
2020 mid-May

**Does your wallet have an active development team?**
Yes

**Is your wallet open-source?**
Not yet, we are still working on it. Part of the wallet will be open-sourced in the future.

**Is your wallet globally accessible?**
Not for all, we only provide services in accordance with local policy requirements.

Crypto.com DeFi Wallet Geo-Restrictions
The following locations are restricted from downloading Crypto.com DeFi Wallet App:
Afghanistan
Andorra
Bangladesh
Bolivia
Burma (Myanmar)
Burundi
Central African Republic
China
Congo, Dem. Rep.
Cook Islands
Cote d'Ivoire
Crimea Region
Cuba
East Timor (Timor-Leste)
Ecuador
Equatorial Guinea
Eritrea
Ethiopia
Gaza Strip
Greenland
Guinea-Bissau
Guinea, Republic of
Iran
Iraq
Kiribati
Korea, North
Kosovo
Kyrgyzstan (Kyrgyz Republic)
Lebanon
Lesotho
Liberia
Libya
Mali
Marshall Islands
Martinique
Mayotte
Namibia
Nepal
Netherlands Antilles
Palestine
Reunion
Saint Helena
Saint Martin
Sint Maarten
Somalia
South Sudan
St Pierre & Miquelon
Sudan
Swaziland
Syria
Tuvalu
Venezuela
Wallis and Futuna
West Bank
Western Sahara
Yemen
Zimbabwe
Donetsk
Luhansk 

**Is your wallet custodial, non-custodial, or a hardware wallet?**
Crypto.com DeFi Wallet is a decentralized/non-custodial wallet, which means you own your private keys. During wallet creation, you will have to [write down your recovery phrase](https://docs.google.com/document/d/1Kuv_LfvQaX9RKc1dmLTopMDQfTuKpXmn2Ea-yvB9gGk/edit#heading=h.ax8di334zm4v) which when needed, you will be able to restore your funds. Having private keys means that you have full control over your funds, and you are the only one responsible for your funds.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
Two-Factor Authentication (2FA) security layer:
https://help.crypto.com/en/articles/3824773-all-about-2fa-on-crypto-com-defi-wallet

Protocol audited:
https://help.crypto.com/en/articles/4430086-are-there-risks-involved-with-using-the-protocol

**Does the wallet support layer 2 networks?**
Not yet, but supporting Arbitrum is in our roadmap.

**Can the wallet be used with arbitrary Ethereum RPC endpoint?**
No, we don’t support custom RPC for now.

**Does the wallet have fiat on-ramps?**
No

**Does the wallet allow users to explore dapps?**
Yes

**Does the wallet have integrated defi/financial tools?**
Yes

**Can a user withdraw to their card?**
No

**Does the wallet offer limits protection?**
Yes

**Does the wallet allow high-volume purchases?**
No

**Does the wallet have an integrated token swap?**
Yes

**Is the wallet a multi-signature wallet?**
No

**Wallet title**
Crypto.com DeFi Wallet

**Wallet description**
It is a non-custodial Defi wallet developed by Crypto.com where you own your crypto and your private keys. 
Crypto.com Wallet is designed to give you full control and secured custody of your crypto. 

**Wallet logo**
https://user-images.githubusercontent.com/102002620/163433411-d667f300-81fe-44b2-b385-ef5503116219.png

**Background colour for brand logo**
#FFFFFF

**URL**
https://defi.onelink.me/MFZQ/weo8mk2v

**Comment by dansoncheng** [comment]
@minimalsm Hi, may I have any updates from your team?

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification
