### ISSUE TITLE
Publish certificate and logo to the ethereum.org website

### ISSUE THREAD

**Issue by Aldekein** [ethereum/ethereum-org-website#6165]
**Describe the solution you'd like**

We've got the certificate and logo for the https://github.com/ethereum/devops/issues/784 and now to put it live we need to publish them somewhere on the ethereum.org website. Then I'll add required DNS records. 
[bimi.zip](https://github.com/ethereum/ethereum-org-website/files/8576923/bimi.zip) contains `logo.svg` and `bimi.pem`.
Please publish them in any convenient folder on  ethereum.org and share the URLs with me.

**Additional context**

Here's a description of what's it and how it looks like - https://www.dmarcanalyzer.com/bimi/how-to-create-a-bimi-record/

**Comment by samajammin** [comment]
Re-opening, noticed this looks strange in emails:

<img width="65" alt="Screen Shot 2022-05-12 at 12 56 30 PM" src="https://user-images.githubusercontent.com/8097623/168055523-de27c23f-4cb6-4e0d-b64e-2740df48da76.png">

I believe it's because we should have a square SVG. Currently looking at https://ethereum.org/logo.svg the dimensions are 886 x 668. At least in Gmail client, they use a 40 x 40 square for this image.

**Comment by nloureiro** [comment]
> Re-opening, noticed this looks strange in emails:
> 
> <img alt="Screen Shot 2022-05-12 at 12 56 30 PM" width="65" src="https://user-images.githubusercontent.com/8097623/168055523-de27c23f-4cb6-4e0d-b64e-2740df48da76.png">
> 
> I believe it's because we should have a square SVG. Currently looking at https://ethereum.org/logo.svg the dimensions are 886 x 668. At least in Gmail client, they use a 40 x 40 square for this image.

Can you try with this 40x40 svg logo?

![sq_logo](https://user-images.githubusercontent.com/1120748/168057614-c2b14ca0-6f1f-49dc-880c-1921eafbe6d8.svg)

**Comment by samajammin** [comment]
Confirming it should be a square: https://www.dmarcanalyzer.com/bimi/how-to-create-a-bimi-record/

> BIMI works with [SVG images](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics). The SVG image has to be squared logo, without any additional text.

**Comment by Aldekein** [comment]
I'm trying to find a solution with Google support, since every other tool displays logo correctly - https://github.com/ethereum/devops/issues/784#issuecomment-1122692259 

Otherwise we'll need to re-generate the certificate through DigiCert with the new SVG file after they review it.

**Comment by Aldekein** [comment]
Here are the updated cert and logo: [bimi_certificate_and_logo.zip](https://github.com/ethereum/ethereum-org-website/files/8833443/bimi_certificate_and_logo.zip)
