### ISSUE TITLE
Feature request: Include statement about slashed funds before Shanghai

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#6193]
**Is your feature request related to a problem? Please describe.**
Current explainers do not explicitly mention that slashed funds are effectively locked until Shanghai, and cannot be re-staked until that time. 
We do explain that withdraws are not enabled, and that slashing results in your funds being exited, but does not mentioned this small fact that you cannot re-stake yet. This was brought up by a user on Discord who provided feedback that this was not clear. 

**Describe the solution you'd like**
Expand one of the slashing warnings and one of the withdraw warnings to include a snippet about slashed funds being locked without ability to re-stake until withdrawals are enabled with Shanghai. 

**Describe alternatives you've considered**
Leave copy as-is, and let issue resolve itself in time when Shanghai is implemented (👎🏻 )

**Additional context**
Same issue filed for Staking Launchpad: https://github.com/ethereum/staking-launchpad/issues/479

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
@wackerow do you still think adding this content is worthwhile given how close we are to Shanghai?
