### ISSUE TITLE
Create new documentation page introducing formal verification

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6194]
**Is your feature request related to a problem? Please describe.**

We have a couple resources on formal verification, mostly as it relates to smart contract security:
https://ethereum.org/en/developers/docs/smart-contracts/security/#formal-verification

Formal verification is a broader field than just the Ethereum context but I feel like for many developers (including myself), Ethereum is their first exposure to the concept of formal verification. Currently we don't offer much of an introduction to what it is & why it's valuable, or how to get involved with various projects within the Ethereum ecosystem.

**Describe the solution you'd like**

I think it'd be useful to create an "Introduction to Formal Verification" page within our documentation to:
- explain formal verification at a high level (maybe formal methods as well)
- how it applies to Ethereum (e.g. both for optimization & security)
- list resources & tools to learn more or use
- list projects to potentially get involved with

**Additional context**

Some resources we may want to reference:
- https://github.com/leonardoalt/ethereum_formal_verification_overview by @leonardoalt
- https://github.com/pirapira/ethereum-formal-verification-overview by @pirapira
- https://fv.ethereum.org/ blog of the Formal Verification team at the EF
- https://gitter.im/ethereum/formal-methods formal methods Gitter

If those folks are ok with us using (with attribution) some of the content in those posts, I think that could provide most of the content we'd want for this page. From there, we could easily translate this into multiple languages.

People who may be able to help write this page :)
https://runtimeverification.com/events/formalverificationeth/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by leonardoalt** [comment]
That's a great idea!

**Comment by emmanuel-awosika** [comment]
Hi @samajammin. I opened a new PR for this issue. Let me know what you think!
