### ISSUE TITLE
Minor code revision in contract interaction tutorial

### ISSUE THREAD

**Issue by CryptoKiddies** [ethereum/ethereum-org-website#6197]
**Describe the bug**

Not a bug but inefficiency: 
In [Interact with other contracts in solidity tutorial,](https://ethereum.org/en/developers/tutorials/interact-with-other-contracts-from-solidity/), `Counter(_counters[msg.sender]).increment(msg.sender);` is a redundant typecasting of the Counter value returned by the `_counters` mapping inside the factory's `increment` implementation.

**Expected behavior**

Replace with `_counters[msg.sender].increment(msg.sender);` 

**Additional context**

Gives new coders a better understanding of the internal contract type.

**Comment by CryptoKiddies** [comment]
Should also mention that the approach in this tutorial blurs the controller and factory patterns, which for gas and deployment management may be ok for simple contract designs, but still mixes the two concepts in the context of a tutorial.

**Comment by corwintines** [comment]
Thanks @CryptoKiddies!

Going to close this out as stale, but if you think it is still relevant please feel free to open another issu!
