### ISSUE TITLE
StakeWise listing is outdated and wrong

### ISSUE THREAD

**Issue by cryptochrome** [ethereum/ethereum-org-website#6213]
Hello,

I am writing about the already existing StakeWise listing. It's outdated and wrong. For example, the listing at https://ethereum.org/en/staking/pools/ claims that StakeWise is not audited, which is wrong. It has been audited multiple times (see [here](https://github.com/stakewise/contracts/tree/master/audits)). 

What do we need to do to get this updated?

Thanks

**Comment by minimalsm** [comment]
Hey @cryptochrome, thanks for flagging this. We'll get this fixed.

Is the audit information the only thing that is incorrect?

**Comment by cryptochrome** [comment]
@minimalsm thank you. I am not 100% certain about the other information, I think the trustless might also be wrong. But the StakeWise team will be reaching out to get the rest fixed. I just flagged this to them. The audit information is definitely wrong, though, so if you could fix that, that would be great and much appreciated :)

**Comment by minimalsm** [comment]
@all-contributors please add @cryptochrome for ideas, bugs
