### ISSUE TITLE
All CardList components now have bottom margin

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6228]
**Describe the bug**

All CardLists now have a bottom margin, which I don't believe is intended. The background color is the same despite the borders:

e.g. on https://ethereum.org/en/get-eth/#country-picker
<img width="958" alt="Screen Shot 2022-05-05 at 3 55 15 PM" src="https://user-images.githubusercontent.com/8097623/166938763-7cd5d244-f658-4224-a4f3-da1291dd2bfa.png">

**To Reproduce**

See example link above.

**Expected behavior**

I don't think we should have a margin here...

This is what those CardLists use to look like:
<img width="1019" alt="Screen Shot 2022-05-05 at 3 59 26 PM" src="https://user-images.githubusercontent.com/8097623/166939638-5686f96d-44ae-47b9-8f1e-7f59a84b4cb6.png">

**Screenshots**

See above.

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

Looks like it came from this commit?
https://github.com/ethereum/ethereum-org-website/pull/5748/commits/746f3e10a67804e9aa000b9a9e0d537d3c76b467

I suspect @corwintines was only trying to apply this to the staking resource links:
<img width="906" alt="Screen Shot 2022-05-05 at 3 56 45 PM" src="https://user-images.githubusercontent.com/8097623/166939086-4269a54e-9a67-4683-8fb8-87ca42f21fd1.png">
Which I do think look better separated by margins but we should apply to only that instance vs. across the app.

**Comment by GrimmHue** [comment]
I can try to fix this issue.

**Comment by corwintines** [comment]
😬
