### ISSUE TITLE
/:splat/ redirects don't work on Gatsby Cloud deploys

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6229]
**Describe the bug**

It appears certain redirect rules in our [redirects.json](https://github.com/ethereum/ethereum-org-website/blob/dev/redirects.json) file break in Gatsby Cloud (but work in Netlify for production deploys)

**To Reproduce**

1. Go to https://ethereumorgwebsitedev01-fredriksvantesethereumorg77039.gtsb.io/en/layer2/
2. See 404 error

**Expected behavior**

1. Go to https://ethereumorgwebsitedev01-fredriksvantesethereumorg77039.gtsb.io/en/layer2/
2. 301 redirect to https://ethereumorgwebsitedev01-fredriksvantesethereumorg77039.gtsb.io/en/layer-2/

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

This appears to be an issue for any `*` --> `/:splat/` redirect.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
Talked to @pettinarip, this wasn't able to be resolved in Gatsby, and he thinks that since we are doing the migration to NextJS that this is ok to close at the moment.
