### ISSUE TITLE
Add wallet: Minke

### ISSUE THREAD

**Issue by joshreyes93** [ethereum/ethereum-org-website#6242]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**

Internal security team

**When did your wallet go live to users?**

April 27, 2022

**Does your wallet have an active development team?**

Yes, we're a team of 8. With 3 current developers.

**Is your wallet open-source?**

https://github.com/Minke-Labs/minke-wallet

**Is your wallet globally accessible?**

Yes! Minke is accessible globally with no KYC. Onramps require level 1 KYC and are available in 30+ countries.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

We've been building wallet products in the space since 2017 and have an experienced dev team. It's a non-custodial wallet.

**Does the wallet support layer 2 networks?**

Polygon POS

**Can the wallet be used with arbitrary Ethereum RPC endpoint?**

No

**Does the wallet have fiat on-ramps?**

Yes we have fiat on-ramps with Apple Pay as well as local payment networks including Pix, SEPA, Faster Payments, PayID and Interac. We're adding South East Asian Payment networks within the next few months.

**Does the wallet allow users to explore dapps?**

No, we're a native saving experience for mStable and Aave

**Does the wallet have integrated defi/financial tools?**

Users can save and earn yield in mStable and Aave

**Can a user withdraw to their card?**

No, but coming in Q3!

**Does the wallet offer limits protection?**

No

**Does the wallet allow high-volume purchases?**

We limit to $1000 per week to keep the experience at KYC level 1 and free of identity checks.

**Does the wallet have an integrated token swap?**

Yes, powered by 0x and it's gasless on Polygon!

**Is the wallet a multi-signature wallet?**

No

**Wallet title**

Minke

**Wallet description**

The easiest way to save and earn in DeFi with rates up to 5% p.a - and zero gas fees!

**Wallet logo**

https://www.minke.app/assets/images/logo.png

**Background colour for brand logo**

#FFFFFF

**URL**

https://www.minke.app/

**Comment by minimalsm** [comment]
Hey @joshreyes93, as noted in our wallet listing criteria, we have currently paused adding new wallets:

> _A note on adding wallets: as part of [our Q1 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/5105), we are refining our wallets page. This will include refining the listing criteria for our wallets page. Until we have researched, established, and published refined listing criteria, we will not be actively adding new wallets to the website._

We'll loop back around to this when we've established the criteria. Please note the criteria are likely to expand and you may be asked to submit a new (updated) request.

**Comment by joshreyes93** [comment]
all g @minimalsm if you could just comment here when the new criteria is up that would be awesome.

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by minimalsm** [comment]
Hey @joshreyes93  

Sorry for the delay on this. Our new criteria us live! If you'd still like to be listed on ethereum.org, please [fill out our new issue template with the necessary information](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet). Thank you! :-)
