### ISSUE TITLE
Add wallet: Sequence Wallet, the smart wallet for web3

### ISSUE THREAD

**Issue by arielman87** [ethereum/ethereum-org-website#6254]
Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**

Our multi-signature key architecture means you don’t have to worry about losing your crypto to a key logger or seed phrase snatcher. Tr
With Sequence, however, multiple independent keys are required to sign in or send a transaction. You can modify or remove these keys, and assign varying signing power to each — giving you an added layer of security and peace of mind. 
Our multi-key design also means you can recover your account, if you happen to lose one of your keys. Simply combine your remaining keys to auto-generate a replacement for your lost key. This is especially helpful if you want to remove a previously signed-in device from your account, which you may have lost in a taxi

Sequence Wallet created with social logins are currently secured using three private keys: Session keys, a Guard key and a Torus key. The Session key and Torus key are both generated for the first time when a user creates their Sequence Wallet via social login or email authentication. 
At least two of the three keys are needed to unlock an account. This means that if one of the three keys is lost or compromised, a user can use the two remaining keys to replace the lost/compromised key. 
For example, if a user lost their device containing their Session Key, they can unlock their Sequence Wallet account by email or social login for the Torus key combined with the Guard key. Once done, another session key is auto-generated and the user is back in their account with all 3 keys accessible again.
From https://docs.sequence.build/private-keys/social-login-wallets/ 

**When did your wallet go live to users?**

November 4th, 2021

**Does your wallet have an active development team?**

Yes, they can see the regular updates we are making to the SDK https://github.com/0xsequence/sequence.js 

**Is your wallet open-source?**

The SDK and the smart contracts are open sourced: 
 - SDK :https://github.com/0xsequence/sequence.js
 - Contracts : https://github.com/0xsequence/wallet-contracts

**Is your wallet globally accessible?**

In order to comply with regulations and policies mandated by Canada, USA and other global jurisdictions, Sequence will not be fully available in the following regions. 
Sequence is currently restricted in the following countries: 
Afghanistan, Belarus Burma Burundi  Central African Republic Cuba Democratic Republic of CongoHong Kong (China) Iran Iraq Lebanon Libya Macao Mali Nicaragua North Korea People’s Republic of China  Republic of Congo Russia Somalia South Sudan Sudan Syria Ukraine Venezuela Yemen Zimbabwe
https://support.sequence.info/hc/en-us/articles/4414030797207-What-countries-is-the-Sequence-Wallet-NOT-be-available-in-

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Non-custodial each Sequence wallet is a smart contract-based wallet that we can't take funds from or censor users

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Sequence wallets is a non-custodial smart contract wallets. We performed 3 separate audits (https://docs.sequence.build/wallet-contracts/contract-audits) for the contracts and they are open-sourced. Users are also able to remove and add more keys to their wallet to better manage which device has access to their wallet.

**Does the wallet support layer 2 networks?**

L2s and sidechains yes, including Polygon, BSC, (Optimism and Arbitrum will be supported Q2 2022)

**Can the wallet be used with arbitrary Ethereum RPC endpoint?**

No, Sequence rounds-robin between 4 different node providers to ensure availability

**Does the wallet have fiat on-ramps?**

Yes, there is fiat on-ramp and yes the wallet subsidizes some transaction fees, including gas fees for in-wallet swaps. Applications can also pay the gas fees for their users, such as is the case for Skyweaver where all tx fees are paid by Horizon.

**Does the wallet allow users to explore dapps?**

No dapp browser within Sequence, but walletconnect is integrated and users can connect to any dapp with it.

**Does the wallet have integrated defi/financial tools?**

Swaps and cross EVM chain bridging are natively integrated within the wallet.

**Can a user withdraw to their card?**

No

**Does the wallet offer limits protection?**

No

**Does the wallet allow high-volume purchases?**

Yes

**Does the wallet have an integrated token swap?**

Swaps and cross EVM chain bridging are natively integrated within the wallet.

**Is the wallet a multi-signature wallet?**

Yes, Each Sequence wallet can be controlled by multiple private keys, acting like a multisignature wallet. Users can either create a Sequence wallet using one of the supported social login options or create a wallet with a private key stored only on that device.
**Wallet title**

Sequence Wallet 
**Wallet description**

[Sequence](https://sequence.info/) is a self-custodial smart contract wallet built for a network of Ethereum chains. Already supporting Ethereum, Polygon, BNB Chain, and with integrations for Arbitrum, Optimism, Fantom, Avalanche and other EVM-compatible networks coming soon, Sequence brings these multiple chains together, so that they function like the cohesive ecosystem we’ve always dreamed of. In the same way that Web browsers let you surf countless different websites and apps, Sequence is your gateway to all the dapps of EVM-compatible Web3.
**Wallet logo**

![SequenceIconSquare](https://user-images.githubusercontent.com/97196974/167196538-fb2aa5cc-659b-4a16-bfd5-a2c1f6c98dd4.png)
<img width="1890" alt="SequenceHorizontalWhite" src="https://user-images.githubusercontent.com/97196974/167196637-9a8c513d-5f69-48d3-b5a5-41b285c0d2ad.png">

**Background colour for brand logo**

#000000
**URL**

https://www.sequence.app

**Comment by minimalsm** [comment]
Hey @arielman87, as noted in our wallet listing criteria, we have currently paused adding new wallets:

> _A note on adding wallets: as part of [our Q1 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/5105), we are refining our wallets page. This will include refining the listing criteria for our wallets page. Until we have researched, established, and published refined listing criteria, we will not be actively adding new wallets to the website._

We'll loop back around to this when we've established the criteria. Please note the criteria are likely to expand and you may be asked to submit a new (updated) request.

**Comment by arielman87** [comment]
Thanks, @minimalsm Joshua, I thought that was not updated as Q1 has already passed.
**Do you know by chance when is the new estimated time that the team will look into this again?** I have no problem in resubmitting including more or diff info.

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by minimalsm** [comment]
Hey @arielman87 

Sorry for the delay on this, our new criteria is up! :-) If you'd still like to be listed on ethereum.org, please [fill out our new issue template with the necessary information](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet). Thank you! :-)
