### ISSUE TITLE
Change Starkware to Starkware StarkEx (validium mode)

### ISSUE THREAD

**Issue by Riely007** [ethereum/ethereum-org-website#6259]
At the VALIDIUM page - Use Validium part, can it be more specific? 

For Matter Labs, you pointed zkSync, and for Starkware, it should be Starkware StarkEx (validium mode), rather than just Starkware. 

Starkware’s StarkEx rollup mode is a zk rollup L2. StarkNet is a volition.

Link: https://ethereum.org/en/developers/docs/scaling/validium/

**Comment by minimalsm** [comment]
Thanks, @Riely007, I agree we should be specific here.

**Comment by TMirrorT** [comment]
Can I claim this amendment?

**Comment by MahendraBishnoi29** [comment]
hey 👋🏻 @minimalsm can you refer me the file where i have to make changes?

**Comment by azpwnz** [comment]
I wanted to help with this issue but discovered that it is already done here https://github.com/ethereum/ethereum-org-website/commit/f6c36d81300db4c650b139edd4d5ca0daada8629


cc @corwintines

**Comment by corwintines** [comment]
Hmm good catch @azpwnz! Thank you!
