### ISSUE TITLE
Adding the GRID+ LATTICE¹ to the Wallets page.

### ISSUE THREAD

**Issue by Logic-Beach** [ethereum/ethereum-org-website#6270]
**Is your wallet globally accessible?**
Yes, although shipping to certain countries must be done via reshipping services (most countries worldwide do not require this). A list of available shipping regions can be found [here](https://docs.gridplus.io/order-and-delivery/shipping-and-delivery).

**Is your wallet custodial, non-custodial, or a hardware wallet?**
Hardware wallet. The user has access to their private keys. If GridPlus disappears, the Lattice1 will still work. The hardware can be used either with our own app, the GridPlus Web Wallet (similar to e.g. Ledger Live) or can be directly connected to MetaMask, Frame, and other wallets and used as an additional layer of security.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**
The wallet has two completely separate compute environments - one connects to the internet and is assumed to be compromised at all times and the other one has access to private keys and signs transactions. They communicate via a hardware "mailbox" and can never get in touch with each other directly. More on this topic can be found [here](https://docs.gridplus.io/lattice1/security-features).

**Does the wallet have fiat on-ramps?**
No.

**Does the wallet allow users to explore dapps?**
The hardware is integrated with MetaMask, Frame and will support other wallet apps in the future too. Anything that can be done with these wallets now has hardware security tied to it. 
WalletConnect can be used when the Lattice1 is used with MetaMask or any other 3rd party wallet that supports WC.

**Does the wallet have integrated defi/financial tools?**
No.

**Can a user withdraw to their card?**
No.

**Does the wallet offer limits protection?**
Not at this time, although this is a feature that could be added to add some mobile functionality to the Lattice1

**Does the wallet allow high-volume purchases?**
Crypto cannot be bought directly from the wallet or its app. It can, however, be bought using a 3rd party integration such as MetaMask or Frame or Wallet Connect.

**Does the wallet have an integrated token swap?**
No. Unless it's used with MetaMask.

**Is the wallet a multi-signature wallet?**
No, but it can be used with Gnosis safe to achieve this feature.

**Wallet title**
GridPlus Lattice¹

**Wallet description**
The GridPlus Lattice¹ is a new generation hardware wallet designed to offer the best security available on the market today. Created by ex-ConsenSys engineers as the only hardware wallet that gives you a readable view of your transactions.

**Wallet logo**
![grid-plus-logo-black+blue-removebg-preview](https://user-images.githubusercontent.com/33695749/128784955-06b0308b-170b-48f2-b7f4-84b7454419a3.png)

**Background colour for brand logo**

#FFFFFF

**URL**
https://gridplus.io/

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by corwintines** [comment]
Hey @Logic-Beach!

Thanks for opening this issue :) The issue template for suggesting a wallet changed recently (https://github.com/ethereum/ethereum-org-website/pull/6622) with the release of the new find wallets page. I'm going to close this issue out, but would appreciate if you filled out a new issue with the updated form :)
