### ISSUE TITLE
Documentation is inconsistent when talking about the "types of transactions"

### ISSUE THREAD

**Issue by 01231** [ethereum/ethereum-org-website#6279]
**Describe the bug**

[This](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/transactions/index.md) page mentions three types of transactions:

> ## Types of transactions
> On Ethereum there are a few different types of transactions:
> - Regular transactions: a transaction from one wallet to another.
> - Contract deployment transactions: a transaction without a 'to' address, where the data field is used for the contract code.
> - Execution of a contract: a transaction that interacts with a deployed smart contract. In this case, 'to' address is the smart contract address

Whereas [this](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/evm/index.md) page mentions only two different types:

> ## Transactions
> ... There are two types of transactions: those which result in  message calls and those which result in contract creation.

The way I understand it is, that both `regular transactions` and `execution of contracts` belong to the type `message calls`. So both definitions would be technically correct. Nevertheless it could be misleading if you don't fully understand it.

**Expected behavior**

In my opinion it would be helpful to have a unified definition that can be used in both files. Here is my approach:

> ## Types of transactions
> On Ethereum there are a two main types of transactions:
> - Transactions which result in message calls
>   - Regular transactions: a transaction from one wallet to another.
>   - Execution of a contract: a transaction that interacts with a deployed smart contract. In this case, 'to' address is the smart 
> - Contract deployment transactions: a transaction without a 'to' address, where the data field is used for the contract code.
contract address

**Comment by noahliechti** [comment]
I would work on this, if you think this is an improvement.

Question: How do you handle documentation that gets reused on multiple pages?

**Comment by samajammin** [comment]
Thanks for surfacing this @nabetse00! I agree with your assessment & proposal.

Assigning to you - thanks for volunteering to help out!

**Comment by nabetse00** [comment]
@samajammin I'm not the one that spotted this improvement. I think that you should change '@nabetes00' 'to '@noahliechti'.
Thank you!

**Comment by samajammin** [comment]
Whoops, sorry! At least I assigned it correct 😅

Please go ahead with your proposal @noahliechti 😄

**Comment by corwintines** [comment]
Thanks @01231 

This page has gone through a few revisions since this was opened so going to close this out as stale. But, if you still think there are more revisions that should be made for this, please feel free to open another issue and we can get on that quick. Thanks!
