### ISSUE TITLE
Epic: Redesign the Learn section

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#6285]
There is a lot to learn in the Ethereum ecosystem. Currently, ethereum.org provides an ever-growing list of disconnected pages that users must piece together independently. Our long-lived "Learn" page https://ethereum.org/en/learn/ provides a scattered list of topics without much rhyme or reason behind the sequence or importance of these topics.

We'll redesign this page and the "Learn" site navigation to improve our content hierarchy for users and create more structured pathways to learning Ethereum that folks can navigate based on their areas of interest and current level of knowledge. 

**Additional context**
This relates to the "🎓 Redesign the Learn page" epic outlined in our Q2 roadmap (https://github.com/ethereum/ethereum-org-website/issues/6161)

related older issue: https://github.com/ethereum/ethereum-org-website/issues/3984 

**Work in progress deisgns**
https://www.figma.com/file/MhSQ4kFr2ykibsCoIx35In/Learn-Revamp?node-id=0%3A1

**Comment by samajammin** [comment]
This has been solved! Closing this out 🎉 

Primary PRs:
- https://github.com/ethereum/ethereum-org-website/pull/6708
- https://github.com/ethereum/ethereum-org-website/pull/6797
- https://github.com/ethereum/ethereum-org-website/pull/6778
