### ISSUE TITLE
Add ETHSeoul to events

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#6304]
**Is your feature request related to a problem? Please describe.**

We should add ETHSeoul to our events page

**Additional context**

https://2022.ethseoul.org/
5 August—7 August
Seoul, Korea 🇰🇷

Add it here: https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.json

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by prahladjshenoy** [comment]
Hi Minimalsm,

I love to contribute, this is my first contribution to the open-source.

If you don't mind shall I work on this issue?

Please correct me if I am wrong.
```
 {
    "title": "ETHSeoul",
    "to": "https://2022.ethseoul.org/",
    "sponsor": null,
    "location": "Seoul, Korea",
    "description": "",
    "startDate": "2022-09-05",
    "endDate": "2022-09-09"
  },
```

I think the description is missing.

**Comment by minimalsm** [comment]
All yours @prahladjshenoy, yes this looks good to me.

**Comment by minimalsm** [comment]
Can't find a public description anywhere. Let's just make something up like "ETHSeoul is a 4-day hackathon for builders based in Seoul, Korea."

**Comment by minimalsm** [comment]
Hey @prahladjshenoy :-) looks like you've done the work here but forgot to push it back to origin. You need to merge your fork into our repo. You can see some information on [how to do this in our README](https://github.com/ethereum/ethereum-org-website#6-submit-your-pr).

**Comment by prahladjshenoy** [comment]
Hi @minimalsm  thanks for the assistance, If I want to do anything let me know, and I will do it.
