### ISSUE TITLE
Create new documentation page on smart contract source code verification

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6308]
**Is your feature request related to a problem? Please describe.**

I feel this is not currently a well documented aspect of smart contracts - the importance of & ability to verify smart contract source code.

**Describe the solution you'd like**

- Create a new documentation page: "Verifying smart contracts" page
  - Right after the "[Deploying smart contracts](https://ethereum.org/en/developers/docs/smart-contracts/deploying/)" page
  - Provide general intro to source code verification as a concept (what is it, why it matters, how it's done)
  - List projects/tools that help devs (& smart contract users) accomplish this
    - e.g. [Sourcify](https://sourcify.dev/), [Etherscan](https://etherscan.io/verifyContract), [Tenderly](https://docs.tenderly.co/monitoring/verifying-a-smart-contract)
    - Pros, cons, features of the various tools

**Describe alternatives you've considered**

- Considered this as a section within compiling or deploying smart contract pages but this topic seems worthy of its own page...
- Naming it “Source code verification” may be more descriptive (also to not confuse it with formal verification of smart contracts - #6194) but it seems to make sense as "Verifying smart contracts" to fit in with the smart contract section ("Compiling", "Deploying" etc.)

**Additional context**

Chatted with @kuzdogan on this who is willing to help write it 😄 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
Since https://github.com/ethereum/ethereum-org-website/pull/6575 was merged I think we can close this @samajammin.
