### ISSUE TITLE
Translate RandomAppList component

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#632]
**Is your feature request related to a problem? Please describe.**

Currently this always displays in English, even on translate pages. E.g.
<img width="297" alt="random-list-translations" src="https://user-images.githubusercontent.com/8097623/70457705-77136400-1a65-11ea-89e5-dbc1af34c22b.png">

**Describe the solution you'd like**

Update this component (`RandomAppList.vue`). Move the `description` strings to pull from strings.json so they can be translated in CrowdIn & display content based on the $lang application property.

**Describe alternatives you've considered**

None

**Additional context**

See the `BuildPage.vue` component for an example of how to translate strings within components based on the current language.

**Comment by luuquocviet379** [comment]
I love
