### ISSUE TITLE
Create new documentation page on interacting with smart contracts

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6327]
**Is your feature request related to a problem? Please describe.**

In our [smart contract docs](https://ethereum.org/en/developers/docs/smart-contracts/) we explain how to write, compile & deploy smart contracts but often developers don't want/need to deploy their own smart contracts, they simply want to interact with existing contracts that are already deployed.

**Describe the solution you'd like**

Create a new "Interacting with smart contracts" documentation page: (within /smart-contracts/)
- Explain the different ways to interact with smart contracts (i.e. CRUD)
  - querying data (which doesn't create a transaction)
  - mutating data, by triggering a tx from an EOA (or from another contract)
- Explain contract ABIs & how they are consumed by other developer tools/libraries to understand the interface of a smart contract & how to interact with the contract
- List different approaches/tools/projects that allow developer to write programs that interact with contracts
  - e.g. https://ethereum.org/en/developers/docs/apis/javascript/
  - e.g. https://ethereum.org/en/developers/docs/apis/backend/
- Link to tutorials that demonstrate different approaches?
  - e.g. https://ethereum.org/en/developers/tutorials/calling-a-smart-contract-from-javascript/
- ...anything else? 

**Describe alternatives you've considered**

Considered adding a section on ABIs in the "[Compiling smart contracts](https://ethereum.org/en/developers/docs/smart-contracts/compiling/)" page but this topic seems to warrant a dedicated page. Often people who want to interact with a smart contract won't be the person compiling/deploying the contract.

**Additional context**

This came up in discussions on #6308 & the value of having greater explanation of contract ABI & metadata.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you'd like to give any input or if you're interested in helping out with a PR.

**Comment by wackerow** [comment]
Re-surfaced with #12195, closing this one out
