### ISSUE TITLE
Bug bounty main leaderboard doesn't sum EL + CL

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6328]
**Describe the bug**

Points in the top leaderboard are not summed across EL + CL (e.g. Martin has bugs on both sides but just shows his EL total):
![telegram-cloud-photo-size-1-5179298451362523728-y](https://user-images.githubusercontent.com/8097623/168306940-61f61508-a312-4a11-9fa6-5aa0d0b4085d.jpg)

**To Reproduce**

1. Go to https://ethereum.org/en/bug-bounty/
2. See error

**Expected behavior**

Top leaderboard should combine EL + CL scores.

**Screenshots**

See above

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All 

**Additional context**

Stems from recent updates to merge bounty programs: #6021

We query this data from 2 separate data files using GraphQL:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/bug-bounty.js#L825
So I imagine we'd have to write some logic to merge those data sources together in the component

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Thanks @andyGallagher, I've assigned you ❤️  Please feel free to ping here or on Discord if you need anything here.

**Comment by samajammin** [comment]
Closing this out - solved in https://github.com/ethereum/ethereum-org-website/pull/6739. Thanks @andyGallagher!
