### ISSUE TITLE
Typo in variable name in utils/calculateStakingRewards.js

### ISSUE THREAD

**Issue by GustavoRSSilva** [ethereum/ethereum-org-website#6338]
**Describe the bug**

This is a minor mistake (I bet it is just a typo), but in the utils/calculateStakingRewards.js (https://github.com/ethereum/ethereum-org-website/blob/dev/src/utils/calculateStakingRewards.js) there is mention of the variable **offlineEpochGweiPentalty**, I think it means **offlineEpochGweiPenalty**.

the same thing happens to **vaildatorUptime**, I think its meant to be **validatorUptime**

**Additional context**

It is related to https://ethereum.org/en/staking/

<img width="1286" alt="Screenshot 2022-05-15 at 20 32 14" src="https://user-images.githubusercontent.com/8384988/168490881-fd311480-8dc5-4615-9817-6e8cc39543ba.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

This is a good first Issue, maybe someone wants to do it :).

**Comment by minimalsm** [comment]
Thanks for reporting @GustavoRSSilva, fixed in #6339 <3

**Comment by minimalsm** [comment]
@all-contributors please add @GustavoRSSilva for bugs
