### ISSUE TITLE
Request to add AVADO to the Ehtereum Solo-Staking page

### ISSUE THREAD

**Issue by JosPoulakis** [ethereum/ethereum-org-website#6340]
Before suggesting a staking product or service, make sure you've read [our listing policy](/contributing/adding-staking-product/).

Only continue with the issue if the staking product meets the criteria listed there.

If it does, complete the following information which we need to accurately list the product/service.

**Product type**

- [x] Node/client tooling
- [ ] Key management
- [ ] Staking as a service
- [ ] Staking pool
- [ ] Other: (describe)

**Name**

Avado

**Logo**

![](https://i.imgur.com/2divm9Z.png)

**Description**

Most convenient Plug&Play staking solution

**Website**

Ava.do

**If software is involved, is everything open source?**

- [x] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ ] No, code is closed source
- [ ] N/A, no custom software is involved
https://github.com/AvadoDServer
**Is the project a fork? If yes, which project was forked?**

Dappnode

**Is the product out of _beta_ development?**

Yes

**What wallets support the product or service?**
Metamask

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**

16 as we offer a Rocketpool package. 32 for regular staking

**If a service, what are the fees associated with using the service?**
No fee, Users buy the device at a one time cost, the software is maintained by AVADO for free.

**If the product or service involved a liquidity token, what are the tokens involved?**
NA

**What date did the project or service go live?**

December 2018

**Has the project undergone an external security audit?**

Not yet, this is on our Roadmap

**Has the project undergone any security bug bounties?**

No

**Is the project being actively maintained?**

Yes

**Is the product or service free of trusted/human intermediaries?**

No, Avado uses the existing processes given to stake and adds a wizard where needed to eliminate any use of CLI

**If a pooled staking service, can users participate as a node operator without permission?**
We integrate Rocket Pool as a DApp and users can participate without permission

**If listing a staking-as-a-service, are users required to sign-up for an account?**
NA

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**
NA - Users always are responsible and holding their own keys

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**
NA

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**

Prysm and Teku, Nimbus yet to be added

**What platforms are supported?**
We use a Linux based platform

**What user interfaces are supported?**
Browser Application

**Social media links**

[]
https://twitter.com/avadocloud
https://www.linkedin.com/company/12978994/admin/
https://www.instagram.com/avadocloud/
https://t.me/joinchat/F_LlkBLEoDrFioPNviEpsQ

**Comment by corwintines** [comment]
Closing as this was done in the above PR
