### ISSUE TITLE
Nav bar horizontal scroll on some languages

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#6357]
**Describe the bug**
On certain language versions of the site, the longer text strings in the nav bar result in crowding of the nav bar contents, causing horizontal overflow and scrolling at certain screen widths.

**To Reproduce**

1. Go to https://ethereum.org/ru/ on desktop
2. Resize window to a width between 1024 and ~1100
3. See larger nav strings (compared to English) causing congested nav bar with horizontal scrolling

**Expected behavior**

Menu items should be responsive for languages with larger strings without causing the nav bar to overflow and horizontally scroll.

**Screenshots**
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/54227730/168725927-f6dfe56b-f870-4322-bd6f-04c5bdd6b8f9.png">

**Comment by nloureiro** [comment]
> cc @nloureiro to check

going over this issue here > https://www.figma.com/file/0UCoVxMeJVCIebTX7FIBHs/header-media-queries-bug?node-id=0%3A1&t=VeoumcIxOGzA4j6m-1

**Comment by pettinarip** [comment]
@TylerAPfledderer not sure if you have already started the migration of the Nav component to Chakra. I was thinking that perhaps it was a good opportunity to also include the new design proposal by @nloureiro in the previous comment.

Feel free to disagree. We could add those new things in a different PR.

**Comment by nloureiro** [comment]
> @pettinarip if this is the issue you are trying to assign to me. Go ahead! We can get rolling with the migration and solution.

I'm working a solution that might scale better and will use CSS and Javascript
the WIP figma file is here > https://www.figma.com/file/0UCoVxMeJVCIebTX7FIBHs/header-media-queries-bug?node-id=31%3A1464&t=I7cd6aNzd4CDMaiK-1
