### ISSUE TITLE
Add new Node Service

### ISSUE THREAD

**Issue by lupascualex** [ethereum/ethereum-org-website#6362]
In the [Popular Node Service](https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/#popular-node-services) section, I would like to add [OMNIA](omniatech.io) with the following features:

- Privacy is enabled by default (and by design - no tracking)
- The first service to cover off-chain privacy
- Front-running protection 
- Decentralized RPC resource pool 
- Freemium subscriptions with 100k Requests Per Day and 25 Requests Per Second (RPS) throughput
- 5+ Blockchains Supported, all testnets included
- Anyone can join with a full node and earn
- No Single Point of Failure
- Zero Downtime
- Build-in load-balancing (including geo location steering for low latency)
- Compliance & blockchain access 2-in-1

**Comment by corwintines** [comment]
This has gone stale, going to close it out. @lupascualex if you still feel this is relevant, please revive this in a new issue.
