### ISSUE TITLE
Epic: Revamp Tutorials section

### ISSUE THREAD

**Issue by nhsz** [ethereum/ethereum-org-website#6365]
_This is an epic that makes up part of [the ethereum.org Q2 Roadmap](https://github.com/ethereum/ethereum-org-website/issues/6161)_.

### Description

Our developer tutorials section continues to grow as we receive submissions from the community.

Currently we have nearly 50 tutorials that collectively make up 5% of all pageviews on the website. Traffic continues to grow as we roll out translations for these pages as well.

This growth is exciting but brings growing pains. it’s harder for users to sort through all the tutorials & to find the type of tutorial they’re searching. The tutorials landing page now has an unwieldy list of tags.

We see opportunity to create better structure on this part of the site, such as categorizing different learning paths (e.g. frontend dapp development vs. smart contract development). This may take the form of tutorial “playlists”, landing pages for tags, or a combination of features.

The maintenance of tutorials is also key to ensure they stay relevant (e.g. ensuring Solidity & library versions stay up to date). We think there’s opportunity to find creative ways to collaborate with the community on this.

### Todo

- [ ] Flesh out this issue

**Comment by minimalsm** [comment]
Closing in favour of #8491
