### ISSUE TITLE
Fix spelling of Optimisic Kovan on Networks page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#6404]
**Describe the bug**

On the Networks page, 'Optimistic Kovan' is spelled as 'Optimisic Kovan'.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/networks/#optimistic-kovan
2. Read the title
3. See error

**Expected behavior**

'Optimisic Kovan' should be changed to 'Optimistic Kovan'

**Screenshots**
<img width="556" alt="Screenshot 2022-05-20 at 13 38 43" src="https://user-images.githubusercontent.com/37338979/169521142-422f8f04-cd02-405d-bcbc-4b17da10e048.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by andyosei12** [comment]
I can work on this

**Comment by mr-harshtyagi** [comment]
Please close this issue

**Comment by Nash0509** [comment]
I can't find the issue. If it's done please close it...

**Comment by wackerow** [comment]
Closing, thanks folks!
