### ISSUE TITLE
KeeCoin Dashboard - DAPP Wallet Eth Managment

### ISSUE THREAD

**Issue by Keecointoken** [ethereum/ethereum-org-website#6416]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

Keecoin is a free DAPP for manage your Ethereum Wallet and interact with Blockchain ETH 

**Is your dapp open source?**

No

**Can a user access the dapp without creating an account?**

Yes, It is only necessary to enter your Ethereum Wallet

**Are dapp funds non-custodial?**

Yes

**Do you offer community support?**

Yes, we support community on : Discord, Telegram, Twitter.

**Describe any geographical restrictions on usage of your dapp**

Nothing

**Dapp title**

KeeCoin Dashboard

**Dapp description**

Keecoin is a free DAPP for manage your Ethereum Wallet and interact with Blockchain ETH 

**Dapp logo**

https://keecoin.io/assets/image/keecointoken-200.png

**Website**

https://keecoin.io

**Comment by corwintines** [comment]
I think this should be open sourced before consideration IMO.

**Comment by minimalsm** [comment]
Hi @Keecointoken, thanks for raising this issue.

As your tool appears to be primarily designed for Binance Smart Chain and closed source, it doesn't align with our current listings. If there's a straightforward way to apply it to Ethereum, we could reconsider this but we don't want to promote a potentially complex user experience. Feel free to reach out if the circumstances change.

Thanks again ❤️

**Comment by minimalsm** [comment]
@all-contributors please add @Keecointoken for ideas
