### ISSUE TITLE
Possible Phishing Website

### ISSUE THREAD

**Issue by WGUcoder22** [ethereum/ethereum-org-website#6421]
Possible phishing website = https://ethstake.exchange/en/about/

Description:

This website mimics ethereum.org to just about every link. The URL listed above represents one page of the website that clearly shows signs of phishing, with hyperlinks under the Work in progress section and the following sections below that are not taking the user to GitHub, instead they are linked to the current page. The suspicious website contains the date of December 1, 2020 located at the bottom of all pages under the TLD, which says it was last updated then.

**Expected behavior**

I expected the website to allow me to safely secure funds for staking, which it has so far with a minimal investment. If this website is apart of ethereum.org, then please reply back to this issue stating that it is legit.

**Screenshots**

![ethstake exchange phishing](https://user-images.githubusercontent.com/76754722/169741295-ae50fdb7-9106-4bd4-a881-500e5ed10c81.png)
![Webiste last updated](https://user-images.githubusercontent.com/76754722/169741396-05bfa27f-1b08-4880-a4ae-961140504b53.png)
![Staking Launchpad Home](https://user-images.githubusercontent.com/76754722/169741780-1f895a6c-fb2d-4822-9b4d-67a765575763.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Chrome
- Version: 101

**Additional context**

I didn't know where else to report this, maybe add a form or email address under the phishing webpage on the official Staking Launchpad website.

**Want to contribute?**

I would like to contribute, but I work full-time and go to school full-time as a computer science student.

**Comment by minimalsm** [comment]
Hey @WGUcoder22, thanks for reporting. **This is a scam website.**

I've reported it to Google using [this phising reporting link](https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en). Please do the same and do not engage with this website!
