### ISSUE TITLE
Wrong i18n link for `page-find-wallet-new-to-wallets-link` in  `/wallets/find-wallet/`

### ISSUE THREAD

**Issue by rwv** [ethereum/ethereum-org-website#6423]
**Describe the bug**

In `/wallets/find-wallet/` there's a link `page-find-wallet-new-to-wallets-link` navigate to `/wallets`. However, it use raw `<a>` tag instead of `components/Link` which cause i18n navigate fails: 

`/zh/wallets/find-wallet/` navigate to `/wallets/` instead of `/zh/wallets/`

**To Reproduce**

1. Go to https://ethereum.org/zh/wallets/find-wallet/
2. Click on [以太坊钱包](https://ethereum.org/wallets/)

**Expected behavior**

Navigate to https://ethereum.org/zh/wallets/

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 100

**Want to contribute?**

I am working on a PR.

**Comment by minimalsm** [comment]
Awesome catch @rwv, thanks!
