### ISSUE TITLE
Create a new use case page for Decentralized Science (DeSci)

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6432]
**Is your feature request related to a problem? Please describe.**

An emerging use case of Ethereum & blockchain technology is "DeSci" or Decentralized Science.

This isn't a topic we currently cover on the site. I think there's opportunity to expose newcomers to this use case.

**Describe the solution you'd like**

Create new use case page (e.g. like [DeFi](https://ethereum.org/en/defi/), [NFTs](https://ethereum.org/en/nft/) & [DAOs](https://ethereum.org/en/dao/)) that introduces DeSci. This page should cover:
- What is DeSci?
- Why is it important? What are problems with existing industry practices?
- How does it work? How is Ethereum/blockchain technology used?
- What are specific industry applications? e.g. publishing, funding, IP ownership, data storage...
- Example projects in the space?
- Further reading to learn more
- ...anything else?

**Additional context**

Some resources that could be helpful...
- https://www.vincentweisser.com/decentralized-science - definitions, links, projects
- https://future.a16z.com/what-is-decentralized-science-aka-desci/ - intro explainer
- https://www.vincentweisser.com/uploads/decentralized-science-landscape.jpg - ecosystem landscape
![image](https://user-images.githubusercontent.com/8097623/169821422-ea690d09-5dc7-4e16-b1ee-ab1b1d4aacfb.png)

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Hey @jmcook1186 - assigning to you for now 😄

**Comment by vincentweisser** [comment]
Hi Sam and Joseph, this is awesome, happy to colab and jam! Let me know how it usually works, do you commit a draft version and have others commit proposed improvements/additions?

**Comment by samajammin** [comment]
Amazing, thanks for volunteering @vincentweisser. Would love to collaborate on this. I think your article linked above already covers a good chunk of the content we'd imagine having on this page. 

I just created a `desci` branch (https://github.com/ethereum/ethereum-org-website/pull/6442) with a new page template to work off. Figure that might be a useful foundation to work off. Potential options here:
1. If you're comfortable with GitHub workflows, feel free to branch off that & open a PR into back into that branch.
2. If you'd prefer to just work on a draft in markdown file, feel free to edit this directly: https://notes.ethereum.org/@sam/desci

Happy to discuss in more detail 😄
