### ISSUE TITLE
Add Ownbit wallet

### ISSUE THREAD

**Issue by jtomtan** [ethereum/ethereum-org-website#6435]
_Please note as part of [our Q2 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/6161) we paused adding new wallets until we establish new, expanded criteria._

Before suggesting a wallet, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your wallet meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.**

Ownbit wallet has been widely tested and code-reviewed inside the team. And part of the source code is open-sourced for years, and has gotten dozens of likes in the github. github: https://github.com/bitbill

**When did your wallet go live to users?**

Around Feb 2018.

**Does your wallet have an active development team?**

Yes, still developing new features, release updates weekly.

**Is your wallet open-source?**

Partially. MultiSig contracts are total open-sourced at: https://github.com/bitbill/bitbill-multisig-contracts

**Is your wallet globally accessible?**

Yes.

**Is your wallet custodial, non-custodial, or a hardware wallet?**

Mnemonic phrase stored in front-end(mobile phone), and owned by the user. Assets can be restored anytime anywhere in any other popular wallets. Follows BIP39, BIP44.

**Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible**

Ownbit MultiSig wallet has not been audited by a third party. But it has been used widely more than 4 years, and no security problems until now. And some critical part of the source code is open-source.

**Does the wallet support layer 2 networks?**

Yes, currently supports zkSync. 

**Can the wallet be used with arbitrary Ethereum RPC endpoint?**

No. New layer 2 networks are added separately.

**Does the wallet have fiat on-ramps?**

No, users pay the fee.

**Does the wallet allow users to explore dapps?**

Some. Ownbit integrated some popular dapps, like: uniswap, aave, comp. But not all.

**Does the wallet have integrated defi/financial tools?**

Yes, some. Like Compound.

**Can a user withdraw to their card?**

No.

**Does the wallet offer limits protection?**

Yes, there's threshold reminder function.

**Does the wallet allow high-volume purchases?**

No. 

**Does the wallet have an integrated token swap?**

No. But users can use uniswap inside Ownbit.

**Is the wallet a multi-signature wallet?**

Yes. Ownbit is famous for its ethereum multisig feature.

**Wallet title**

Ownbit

**Wallet description**

Ownbit is a multi-coin wallet. It implements Cold wallet function (by turning your old phone into a hardware wallet) and MultiSig wallet function for many popular coins, including Bitcoin, Ethereum and more.

**Wallet logo**

https://ownbit.io/resource/brand-assets/images/origin/ownbit_logo_6.40c9017334.svg

**Background colour for brand logo**

0xffffff

**URL**

https://ownbit.io

**Comment by minimalsm** [comment]
Hey @jtomtan 

Sorry for the delay on this. If you'd still like to be listed on ethereum.org, please [fill out our new issue template with the necessary information](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet). Thank you! :-)
