### ISSUE TITLE
Zero Knowledge page

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#6451]
**Is your feature request related to a problem? Please describe.**
- Right now on ethereum.org there aren't any resources on zero-knowledge technology (other than a small amount of information on zk-rollups). Since zero-knowledge proofs are being used for a variety of use cases (rollups, gaming, proof of location, etc), a general learn page on zero-knowledge would be great. 

**Describe the solution you'd like**
- A learn page on zero knowledge

**Additional context**
Some resources:
https://0xparc.notion.site/Pre-program-Topic-Sampler-46456f891dc541a7a780c79f8ced463c
https://ethresear.ch/t/zero-knowledge-proofs-starter-pack/4519
https://learn.0xparc.org/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by COLONAYUSH** [comment]
I want to work on this issue @corwintines

**Comment by COLONAYUSH** [comment]
Sure, I will keep that in mind. Need to a little more research on ZK as to make it more accessible for non technical users.I will share a proposal regarding the same just after that

**Comment by milvinae** [comment]
I would love to help out if you need any help with content reviews, suggestions etc.

**Comment by minimalsm** [comment]
@COLONAYUSH I know it's only been a few days but just wanted to see where you were at with this. We were discussing it at a weekly call we have and we have talked about a rough outline we could provide for you if that helps get you unblocked here 🙂 ?

**Comment by corwintines** [comment]
I think this can be closed out with the merge of https://github.com/ethereum/ethereum-org-website/pull/6890.
