### ISSUE TITLE
Re: Guest Post On Why Penetration Testing Is Required For Blockchain

### ISSUE THREAD

**Issue by amitkumar76** [ethereum/ethereum-org-website#6459]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

[Guest post - penetration testing.docx](https://github.com/ethereum/ethereum-org-website/files/8768727/Guest.post.-.penetration.testing.docx)

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @amitkumar76 :-) thanks opening this. I don't think this content really makes sense for ethereum.org. Hope you find a more impactful place to post this content! Thanks ❤️
