### ISSUE TITLE
ruby docs in /en/ language path showing Romanian instead of English

### ISSUE THREAD

**Issue by ianrandmckenzie** [ethereum/ethereum-org-website#6471]
**Describe the bug**

The following English page is incorrectly displaying some Romanian texts on the production site of this page:
https://ethereum.org/en/developers/docs/programming-languages/ruby/

**To Reproduce**

1. Go to [https://ethereum.org/en/developers/docs/programming-languages/ruby/](https://ethereum.org/en/developers/docs/programming-languages/ruby/)
2. Look for Romanian words in place of what should be English words

**Expected behavior**

The entire page is in English

**Screenshots**

<img width="784" alt="Screen Shot 2022-05-25 at 7 08 50 PM" src="https://user-images.githubusercontent.com/19812697/170402876-59744827-5765-41d2-8e9a-d21433151354.png">

**Desktop (please complete the following information):**

- OS: macOS 11.6
- Browser: brave 1.38.119

**Additional context**

I verified that VPN is turned off and (as far as I know) am not being routed through servers in non-English speaking countries.

**Want to contribute?**

I could possibly fix this, but if it's an issue that's come up before, maybe someone more experienced is ideal. I checked the `/src` section of this repo and the `.md` page itself is properly written in English, so I'm not sure what the deal is. Maybe I've been pwned, but I had a friend largely unassociated with me see the same thing.

**Comment by demonicirfan** [comment]
Hey @ianrandmckenzie I'm new here can i take this issue 😊

**Comment by minimalsm** [comment]
Nice catch @ianrandmckenzie 💪

Whenever this happens, it is usually because a stray translated file has an `en` for the `lang` in the front matter. As English is built first, then translated files after, any translated files with an `en` path will overwrite the actual English file.

Looks like the Romanian version of this page mistakenly has `en` instead of `ro` as the path: https://github.com/ethereum/ethereum-org-website/bclob/dev/src/content/translations/ro/developers/docs/programming-languages/ruby/index.md

Feel free to open a PR @ianrandmckenzie to fix 😎

**Comment by minimalsm** [comment]
@demonicirfan thanks for offering to help 🙏 issue creators generally have the first go at solving issues if they want to take a pop at it (it looks like he'd like to work on it). 

But, if Ian can't take up this issue today, feel free to take over 😎.

**Comment by corwintines** [comment]
Just want to note there are 3 files that have this bug and should get captured under this too:

- https://github.com/ethereum/ethereum-org-website/bclob/dev/src/content/translations/ro/developers/docs/programming-languages/ruby/index.md
- https://github.com/ethereum/ethereum-org-website/bclob/dev/src/content/translations/ro/developers/tutorials/nft-minter/index.md
- https://github.com/ethereum/ethereum-org-website/bclob/dev/src/content/translations/ro/developers/tutorials/optimism-std-bridge-annotated-code/index.md

**Comment by corwintines** [comment]
Woops, didn't mean to click close with comment 😅

**Comment by demonicirfan** [comment]
@minimalsm thanks for your reply i will search fro some other issues 🙂

**Comment by minimalsm** [comment]
Hey @ianrandmckenzie, thanks again for flagging this. I merged a commit to fix this as we were doing a deploy anyway. 

Be sure to [claim your POAP](https://ethereum.org/en/contributing/#poap) for this 🥳!

**Comment by ianrandmckenzie** [comment]
Heya, sorry I disappeared after reporting. Things have been pretty hectic with projects I'm already working on. Would have been nice to contribute, but now that I know how things work around here I'll be sure to jump on the next one I see.

Thanks :)
