### ISSUE TITLE
Article: Blockchain data storage strategies

### ISSUE THREAD

**Issue by qbzzt** [ethereum/ethereum-org-website#6491]
.

**Tutorial title**

Blockchain data storage strategies

**Tutorial description**

There are several ways in which data from external sources can be stored using the Blockchain. Here they are in order of increasing cost.

1. Calldata
2. Contract code
3. Events
4. EVM storage

This article will compare the different strategies, their costs and tradeoffs, and demonstrate the necessary code to use each one, as well as the requirements to use it safely.

**Tag your tutorial**

Storage, Data availability

**Publication**

Not written yet

**Skill level**

Beginner

**Hosted on Ethereum.org or hosted elsewhere?**

I hope to host it on ethereum.org when written.

**Comment by meow-y** [comment]
I want to work on this issue. 
Kindly tell me about the word limit and the length of article. 
Also if you want to add any reference article please do that.

I will write the article and tag the link here. Please assign the task to me.

**Comment by qbzzt** [comment]
Articles are typically written in markdown, and submitted as a PR to this repository (under https://github.com/ethereum/ethereum-org-website/tree/dev/src/content/developers/tutorials).

**Comment by wackerow** [comment]
Hey folks! Disappointed that this fell through the crack, as I do believe this topic would be great to have. Especially with blob data entering the mix soon, I think this would be nice to have. 

@qbzzt I know you've contributed several well-written articles to the site in the past, and as the original poster I'd like to offer this to you to first, but @meowyx I don't want to ignore your gracious offering to help on this as well. Much time has passed, so if either of you are still interested please reply (do me a favor and @ me here if you do).

Thanks!

**Comment by qbzzt** [comment]
@meowyx, are you interested in doing this article? If so, please tell me by end of the January. If not, I'll do it.

@wackerow, FYI.

**Comment by meowyx** [comment]
@meowyx I am presently unable to allocate time for this task, so please feel free to take it.

**Comment by qbzzt** [comment]
It's mine! Mine! I'll probably do it in February, though. Life's busy.

**Comment by qbzzt** [comment]
I'll start writing this article, but I don't think it should be published before Dencun because Dencun adds EIP-4844, which is very relevant to this topic - and I can't give an example cost until it's actually out.

**Comment by qbzzt** [comment]
[PR written](https://github.com/ethereum/ethereum-org-website/pull/12899), and while it need to be reviewed, I can't be the one to review it ;-) .
