### ISSUE TITLE
Turkmen language added

### ISSUE THREAD

**Issue by DayanchMuhammetgeldiyev** [ethereum/ethereum-org-website#6493]
Can Turkmen language be added to the languages? Because the Turkmen language was not there. Could you please add the Turkmen language?

**Comment by lukassim** [comment]
Hey, thanks for the suggestion.
We've just added Turkmen to the project, here is the direct link: https://crowdin.com/project/ethereum-org/tk

**Comment by DayanchMuhammetgeldiyev** [comment]
Thank you for everything

**Comment by DayanchMuhammetgeldiyev** [comment]
Thanks for everything. I have even started
I will invite Turkmens to the project.
I have a question. Is the translation published after it is completely finished or is the language in the site?
