### ISSUE TITLE
Add "The Hitchhikers Guide To Ethereum"

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#6523]
**Describe the solution you'd like**

[Jon Charbonneau](https://mobile.twitter.com/jon_charb) from Delphi Digital put out an incredible summary of the Ethereum roadmap called ["The Hitchhikers Guide To Ethereum"](https://members.delphidigital.io/reports/the-hitchhikers-guide-to-ethereum).

We should add some links to this guide on ethereum.org. 

Some places that might make sense:

- [Upgrades](https://ethereum.org/en/upgrades/)
- [Sharding](https://ethereum.org/en/upgrades/shard-chains/#read-more)
- [The Merge](https://ethereum.org/en/upgrades/merge/#read-more)
- [MEV](https://ethereum.org/en/developers/docs/mev/)

**Additional context**

Unfortunately, it looks like we cannot link to specific sections/headings in the guide 😞, this might limit where we can/should include this. 

- Article: https://members.delphidigital.io/reports/the-hitchhikers-guide-to-ethereum
- Bankless interview discussing the article: https://www.youtube.com/watch?v=xuLyZaty9iI

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MukulKolpe** [comment]
Hey @minimalsm, can I work on this issue?

**Comment by minimalsm** [comment]
Hey @MukulKolpe 👋 by all means! I've assigned you. 

Feel free to ping me here if you need anything 💪. I've included a list of pages but I encourage you to look for other places where it might make sense to add this as a resource.

**Comment by minimalsm** [comment]
Hey @MukulKolpe, any update on this 😀?

**Comment by MukulKolpe** [comment]
Really sorry to inform that I might not be available for few more days, It'll be great if someone else works on this issue.

**Comment by pushkar2112** [comment]
Hey @minimalsm, I would like to give this a go!
