### ISSUE TITLE
generate-heading-ids script is a bit broken

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6529]
**Describe the bug**

The generate-heading-ids script appears to be broken. It works for certain cases but not all.

**To Reproduce**

See #6527 as an example.

**Expected behavior**

The script should slugify all headers & create IDs. As you can see in the example PR, things start to break.

**Additional context**

Not sure what the exact issue is - looking at #6527, I wonder if the script is just not built to handle h4s?

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Mousticke** [comment]
Hi there, can I check this out ?
Assuming that, I will create a branch from [open-research-header-ids](https://github.com/ethereum/ethereum-org-website/tree/open-research-header-ids)

I'll see what the script is doing and fix as needed

**Comment by samajammin** [comment]
Thanks @Mousticke ! I've assigned you.
