### ISSUE TITLE
Update non-dev links to L2 resources

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#6588]
**Describe the bug**
We have several links that are attempting to help people understand more about layer 2 pages. Many of these originate from pages outside of the developer docs, but for a while were forced to link to the `/developers/docs/scaling/`.

These should be updated to point to the new `/layer-2/` page when outside of the developer docs, where appropriate.

**To Reproduce**

1. Go to https://ethereum.org/en/upgrades/merge/#docking-and-shard-chains
2. Click on [layer 2 scaling solutions](https://ethereum.org/en/developers/docs/scaling/#layer-2-scaling) and see how it takes you from a beginner page to a dev docs page.

**Expected behavior**
Link to `/layer-2/` instead on non-dev pages, for references to learn more about layer 2.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MahendraBishnoi29** [comment]
can i take this issue?

**Comment by minimalsm** [comment]
Closed in #6650
