### ISSUE TITLE
Update Sharding page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6590]
**Is your feature request related to a problem? Please describe.**

Our sharding page is outdated - we should revamp this to reflect the latest roadmap.

**Describe the solution you'd like**

  - Explain iterative approach (danksharding / protodanksharding)

Potential resources to link out to
  - [https://www.eip4844.com/](https://www.eip4844.com/)
  - [https://members.delphidigital.io/reports/the-hitchhikers-guide-to-ethereum](https://members.delphidigital.io/reports/the-hitchhikers-guide-to-ethereum)

**Describe alternatives you've considered**

For a quick fix (if we don't have bandwidth for a full rehaul of the page), we could keep the page content the same & just add a banner/disclaimer at the top, e.g. 

> "Execution Sharding has been deprioritized from the Ethereum roadmap in favour of Rollups [link to rollups page]. An update which refocuses this page on data sharding is expected in Q3" 

Hat tip to @timbeiko for the suggestion 😄 

**Additional context**

Somewhat related to #6523

**Comment by samajammin** [comment]
@wackerow assigning to you for now but anyone: feel free to comment if you'd like to help out with this!

**Comment by minimalsm** [comment]
Just gotta link to EIP-4488 now?

**Comment by samajammin** [comment]
Removing stale label.

> Just gotta link to EIP-4488 now?

This would definitely be a great short-term fix but I do think the content of this page needs a overhaul. It's significantly outdated & doesn't reflect the latest roadmap.

**Comment by Rnamita** [comment]
I would like to help with this issue can you please assign it to me?

**Comment by ossayed** [comment]
Hi there I'd love to work on this issue!

**Comment by corwintines** [comment]
I think we can close this issue out after the roadmap work done by @jmcook1186
