### ISSUE TITLE
Suggest a wallet : Ledger Nano X

### ISSUE THREAD

**Issue by Mousticke** [ethereum/ethereum-org-website#6598]
### Wallet name

Ledger Nano X

### Wallet description

Secure, grow your crypto and manage your NFTs with a new Bluetooth-enabled hardware wallet. When you own crypto, what you really own is a private key that gives you access to your coins. You need to keep this key completely safe. Ledger wallets are the best way to own and secure this key. Secure your valuable assets with the Nano X hardware wallet, then manage and grow them with the Ledger Live app.

### Wallet logo

![ledger-logo-long](https://user-images.githubusercontent.com/16734238/172459464-b4edc5f5-f2e9-41f1-bb1f-bbf0a7fad5cb.svg)

### Background color for brand logo

#ffffff

### URL to the project

https://shop.ledger.com/pages/ledger-nano-x

### When did the wallet go live to users?

2019

### Does the wallet have an active development team?

Active team : https://github.com/LedgerHQ

### Is the wallet globally accessible?

Globally accessible from the ship country list

### Is the wallet available in multiple languages?

English; French; Spanish; Russian

### What social links are there for the project?

[Twitter](https://twitter.com/ledger)
[Discord](https://discord.com/channels/885256081289379850/885256081964691557)
[Facebook](https://www.facebook.com/Ledger)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

[App Store](https://apps.apple.com/app/ledger-live/id1361671700)
[Play Store](https://play.google.com/store/apps/developer?id=Ledger)

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Ledger Live one : 
- Windows
- Linux
- MaxOS

[Download page](https://www.ledger.com/fr/ledger-live/ledger-live-download#download-device-1)

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Ledger has been removed from extensions and replaced by Ledger Live mentionned above

### Is it a hardware wallet?

It is a hadware wallet
Sign transaction with : 
- USB
- Bluetooth

SDK available on Github

### Is the source code for the wallet fully open-source?

Only SDK available : https://developers.ledger.com/

### Who holds the private keys?

The user own the private key

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

[Manage your private Key](https://support.ledger.com/hc/en-us/articles/360000380313-Manage-your-private-keys-own-your-crypto?docs=true)

### Has the wallet's smart contract code been audited?

[Bounty ](https://blog.ledger.com/bounty/)
[Security Bulletins](https://blog.ledger.com/lsb/)

### Does the wallet have an internal security team?

Yes. The currrent CTO was the head of security team of Ledger. It's a yes

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes : [Repo]( https://github.com/LedgerHQ/ledger-live)

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support staking directly?

From Ledger live : [Ledger live stack ETH](https://www.ledger.com/staking-ethereum)

### Does the wallet support swaps directly?

Yes :  [Swap](https://www.ledger.com/swap)

### Does the wallet support multi-chain networks?

Yes

### Does the wallet allow the user to customize gas fees?

Yes : [Ledger doc](https://support.ledger.com/hc/en-us/articles/4406211657233-Send-a-custom-Ethereum-transaction-in-Ledger-Live?docs=true)

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes : [Ledger doc](https://support.ledger.com/hc/en-us/articles/4404389645329-Manage-ERC20-tokens?docs=true) 

### Does the wallet support EIP-1559 (type 2) transactions?

Not yet. There is an opened issue [here ](https://github.com/LedgerHQ/ledger-live-desktop/issues/4368)

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes they have. Mostly via credit card, paypal, bitpay and crypto.com : [Support Ledger](https://support.ledger.com/hc/en-us/articles/360006658493-What-payment-methods-do-you-accept-?support=true)

### Does the wallet support withdrawals to fiat?

Yes via Ledger live

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Current CTO of Ledger : [Charles Guillemet](https://www.ledger.com/people/charles-guillemet)

### Does the wallet have a dedicated support team?

Yes

### What educational resources/documentation do you provide to users?

Different docs / tuto from the doc : [Ledger Doc](https://support.ledger.com/hc/en-us/categories/4404376139409?docs=true)

Epic : #6536

**Comment by minimalsm** [comment]
Closing this out as discussed.
