### ISSUE TITLE
Suggest a wallet: Frame

### ISSUE THREAD

**Issue by floating** [ethereum/ethereum-org-website#6601]
### Wallet name

Frame

### Wallet description

A privacy focused Ethereum wallet that runs natively on macOS, Windows and Linux

### Wallet logo

![Frame Logo](https://frame.nyc3.cdn.digitaloceanspaces.com/frameGhost.svg)

### Background color for brand logo

rgb(34, 32, 33)

### URL to the project

https://frame.sh

### When did the wallet go live to users?

April 1, 2019

### Does the wallet have an active development team?

Yes: https://github.com/floating/frame

### Is the wallet globally accessible?

Yes, no limitations

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

[Twitter](https://twitter.com/0xFrame) & [Discord](https://discord.gg/rr4Yr3JkPq)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes: Windows, Mac, Linux

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes: Chromium, Firefox, Safari

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

Yes: https://github.com/floating/frame

### What license is the wallet software released under?

GPL-3.0

### Who holds the private keys?

Only user hold their private keys

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We have completed four independent audits by both Cure53 and Doyensec

### Has the wallet's smart contract code been audited?

No smart contract

### Does the wallet have an internal security team?

It is a main focus of our engineering team

### Any other security testing that should be noted?

[Socket](https://socket.dev)
[LavaMoat](https://github.com/LavaMoat/LavaMoat)

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

Yes: https://framelabs.notion.site/Getting-Started-Guide-775a95edec3244ce80e118ead8ea6516

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes!

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

Yes!

### Does the wallet allow the user to customize gas fees?

Yes!

### Does the wallet support sending transactions to ENS addresses?

Yes!

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes! (both): https://framelabs.notion.site/Getting-Started-Guide-775a95edec3244ce80e118ead8ea6516

### Does the wallet support EIP-1559 (type 2) transactions?

Yes!

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

jordan@frame.sh

### Does the wallet have a dedicated support team?

Yes via Discord

### What educational resources/documentation do you provide to users?

[Getting Started Guide](https://framelabs.notion.site/Getting-Started-Guide-775a95edec3244ce80e118ead8ea6516)
[Our Blog](https://blog.frame.sh)

### Does the wallet have any integrated tools not mentioned above?

Smart Accounts: smart contract backed accounts like Aragon DAOs

**Comment by minimalsm** [comment]
> Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible
We have completed four independent audits by both Cure53 and Doyensec

Hey @floating, are these audits available for us to link to?
