### ISSUE TITLE
Suggest a wallet: Tally Ho

### ISSUE THREAD

**Issue by chlolands** [ethereum/ethereum-org-website#6615]
### Wallet name

Tally Ho!

### Wallet description

Tally Ho is the first community-owned and operated web3 wallet. Our premise is to reconfigure the web3 wallet into something that benefits users and the whole open-source/public goods ecosystem in Ethereum. 

### Wallet logo

![Property 1=Gold](https://user-images.githubusercontent.com/95715502/172689832-d8ca4d3e-e5e7-4371-80d9-b45e952e2e54.png)

### Background color for brand logo

0D2321

### URL to the project

https://tally.cash/

### When did the wallet go live to users?

12/20/21

### Does the wallet have an active development team?

https://github.com/tallycash/extension

### Is the wallet globally accessible?

Yes, there are no KYC requirements. 

### Is the wallet available in multiple languages?

Currently, it's only available in English, but translations are in progress!

### What social links are there for the project?

Discord: [chat.tally.cash](https://discord.com/invite/f5G36jeKb2)
Twitter: [@TallyCash](https://twitter.com/TallyCash)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

We do not have a mobile app at this current time. 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

We do not have a desktop app at this current time. 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

[Download for Chrome](https://chrome.google.com/webstore/detail/tally-ho/eajafomhmkipbjmfmhebemolkcicgfmd)
Download for Firefox: Click on "Download for Firefox [here.](https://tally.cash/) Then, head to the [instructions](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) for download. 
[Download for Brave, Edge & Opera](https://developer.chrome.com/docs/extensions/mv3/getstarted/#manifest) ** note: these instructions are for Chrome, but substituting brave://extensions or edge://extensions or opera://extensions for chrome://extensions depending on browser should get you to the same buttons.

### Is it a hardware wallet?

We enabled full Ledger hardware wallet support. 

### Is the source code for the wallet fully open-source?

Yes, https://github.com/tallycash/extension. 

### What license is the wallet software released under?

GPLv3, https://github.com/tallycash/extension/blob/main/LICENSE

### Who holds the private keys?

Only users hold their private keys. If the project were to disappear, users could plug their keys into another wallet. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We had a [Least Authority Audit](https://leastauthority.com/blog/audit-of-tally-browser-extension-wallet-key-handling-for-ylvis-llc/) conducted on 4/13/22. The audit was a limited scope review of Tally’s [hd-keyring](https://github.com/tallycash/hd-keyring) repository, which contains the code responsible for generating and managing users’ private keys.

### Has the wallet's smart contract code been audited?

Our smart contract code has been audited 4 times, but we haven't yet one public with our smart contracts.

### Does the wallet have an internal security team?

We do not at the moment. 

### Any other security testing that should be noted?

Our Swaps contract has been [audited.](https://code4rena.com/reports/2021-10-tally 
) We’ve had 2 additional audits on our token contracts that will be published soon.

### Spam protection?

We don't collect personal data, so there isn't a need for spam protection.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

 Not yet but it's in the roadmap; we currently use Alchemy and will be adding POKT later this year.

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

https://docs.tally.cash/tally/the-wallet/wallet-features

### Does the wallet support staking directly?

Not at the moment, but it's coming soon.

### Does the wallet support swaps directly?

Yes! https://github.com/tallycash/extension/tree/swapstick-qa-build

### Does the wallet support multi-chain networks?

Not at the moment, but it's coming soon. 

### Does the wallet allow the user to customize gas fees?

Not at the moment. 

### Does the wallet support sending transactions to ENS addresses?

Yes! https://docs.tally.cash/tally/the-wallet/wallet-features

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Not yet but in roadmap; we do have a community-maintained token list. https://github.com/tallycash/token-list

### Does the wallet support EIP-1559 (type 2) transactions?

Yes. 

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No.

### Does the wallet support withdrawals to fiat?

No.

### Is the wallet a multi-signature wallet?

Connect to Gnosis Safe.

### Does the wallet support social recovery?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

Matt Luongo: Twitter- [@mhluongo](https://twitter.com/mhluongo TG- @mhluongo Discord- Matt Luongo#4163
Michael Haley: Twitter- [@rhizo_michael](https://twitter.com/rhizo_michael) TG- @rhizo_michael Discord- Michael Haley#7821
Henry Boldizar: Twitter- [@henryboldi](https://twitter.com/henryboldi) TG- @henryboldi Discord- henryboldi#1220

### Does the wallet have a dedicated support team?

Users can head to the #bug-reports channel in our [Discord. ](https://discord.com/invite/f5G36jeKb2)
Our support is relatively fast, as not only are our developers extremely active in the server, other community members that are well-versed with the product are available to answer questions as well. 

### What educational resources/documentation do you provide to users?

[Documentation](https://docs.tally.cash/tally/)
[Governance](https://gov.tally.cash/) 
[Blog](https://blog.tally.cash/)

### Does the wallet have any integrated tools not mentioned above?

Native Sign In with Ethereum support, view balances across all accounts & WebUSB Ledger integration on Chrome.

**Comment by chlolands** [comment]
@corwintines Hello! We've added some new features to the wallet (the main two being NFT & multichain support.) I just edited the issue. Can we please have this updated on the site? Thank you!

**Comment by chlolands** [comment]
@corwintines Hello! We have since changed our name to Taho. I added a new issue [here](https://github.com/ethereum/ethereum-org-website/issues/9561) Can we please have our profile updated to reflect the info in the new issue?

**Comment by corwintines** [comment]
For sure @chlolands. Thanks for opening this. Sorry, I just closed this because I saw a few opened. I will review that new issue soon!

**Comment by chlolands** [comment]
Hi @corwintines! Just following up to see if you had a chance to review the new issue :)

**Comment by chlolands** [comment]
Hi @corwintines, I am still seeing us listed with our old name on the site, is there a chance you could review this issue as soon as you can? Thank you!
