### ISSUE TITLE
Choose a new typeface for ethereum.org - Design system foundation component

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#6616]
The baseline for this issue is to have a place to discuss a new typeface for ethereum.org as a foundation component of the design system.

To all websites/design systems choosing the right font is a core decision that will influence all subsequence work, from typography to spacing to look to readability.

### I

Today, ethereum.org do not push a specific font family; it uses the system default from the user browser.
The upside is to have a lighter website that will adapt more quickly to all languages.
The downside is the lack of consistency and unified user experience. This can affect spacing, line height, component behavior, etc.

**The first question does open the discussion: Should the new design system keep this option? or choose a font to be the base on all screens and languages?**

### II

We will have to choose if we go for a new typeface for ethereum.org. This is where a good discussion can help narrow down the options.

The new font must be:
- Open-source.
- Multi-language (we now have 46 different languages, some of which have their characters).
- Readability.
- As light as possible in size, not to be hard to load in low-speed connections.
- San serif font (preferable, but open to discussion)

Please add your take on this issue. 
**Should ethereum.org have a specific font family?** 
**If yes, do you have any recommendations that fit the criteria?**

The quest for a new font is in this Figma file > https://www.figma.com/file/Za0dExeooR5vBxcHvcCYWE/ethereum.org-Design-System?node-id=12%3A29.

**Comment by minimalsm** [comment]
> Open-source

Ignorant question: why is open-source important for a typeface?

**Comment by nloureiro** [comment]
> > Open-source
> 
> Ignorant question: why is open-source important for a typeface?

It's more a question of licensing and being aligned with our values.

I know other licenses can be used with no limitations as a web font, and if we cannot find a suitable option within these "must-haves," we can drop this one. 

To start, I would love to keep open source as a principle.  😀

**Comment by isneuu** [comment]
Hi there! 

You all are much wiser than me. I just wanted to share my recommendations. I don't think the ones below fully meet the requirements still here it is.

1. Atkinson Hyperlegible
2. Epilogue
3. Inter
All of them are available on Google Fonts.

4. https://public-sans.digital.gov/
5. http://karrik.phantom-foundry.com/
6. https://github.com/marcologous/Open-Sauce-Fonts

Thanks for welcoming my input!

**Comment by eduairet** [comment]
Hey, a type designer here, how about a new open source typeface?

**Comment by nloureiro** [comment]
> Hi there!
> 
> You all are much wiser than me. I just wanted to share my recommendations. I don't think the ones below fully meet the requirements still here it is.
> 
> 1. Atkinson Hyperlegible
> 2. Epilogue
> 3. Inter
>    All of them are available on Google Fonts.
> 4. https://public-sans.digital.gov/
> 5. http://karrik.phantom-foundry.com/
> 6. https://github.com/marcologous/Open-Sauce-Fonts
> 
> Thanks for welcoming my input!

Great recommendations! Thank you.

**Comment by nloureiro** [comment]
> Hey, a type designer here, how about a new open source typeface?

I would love to have a ethereum.org open source typeface! It's a huge endeavour that we can talk about having. 

I'm not a type designer, but it's on my design bucket list to collaborate in one, for sure. Would you be up to be a part of it?

To be clear: This is an awesome idea that I can add to the roadmap. For the Design system now we will chose a ready to  use typeface.

**Comment by SuperDelphi** [comment]
- Public sans has some nice curves (👀) that makes it warmer and more accessible than the others. The roundedness gives it some modernity.
    - Fira sans also is a good one. Has a strong personality, and has the advantage to have a monospaced version with font ligatures (perfect for code snippets)

(This is the comment that I've made on the Discord)

**Comment by SuperDelphi** [comment]
Lastly, I think the best (but hardest?) way to go is to design a completely new font for Ethereum.org.

**Comment by eduairet** [comment]
> > Hey, a type designer here, how about a new open source typeface?
> 
> 
> 
> I would love to have a ethereum.org open source typeface! It's a huge endeavour that we can talk about having. 
> 
> 
> 
> I'm not a type designer, but it's on my design bucket list to collaborate in one, for sure. Would you be up to be a part of it?
> 
> 
> 
> To be clear: This is an awesome idea that I can add to the roadmap. For the Design system now we will chose a ready to  use typeface. 
> 
> 
> 
> 

Great! I would love to be involved, we could, by the moment, create the repo to build the new family, start discussing sketches so we can have a strong idea to build the basic character set, and define the soul of the font.
We can also start looking in the community for more type designers that want to be involved. I ended-up here via Discord, it might be a good place to start looking for the Ethereum's type design team!

**Comment by nloureiro** [comment]
> 

Do you know any community of type designers that might willing to contribute?  

Keep in mind that this would be a community based approach, and not a commissioned assignment. We can coordinate and facilitate but to be aligned with the open source principles I think would have to be a collaborative effort.

I will bring this discussion to the team and try to add to ethereum.org roadmap.

**Comment by eduairet** [comment]
> > 
> 
> 
> 
> Do you know any community of type designers that might willing to contribute?  
> 
> 
> 
> Keep in mind that this would be a community based approach, and not a commissioned assignment. We can coordinate and facilitate but to be aligned with the open source principles I think would have to be a collaborative effort.
> 
> 
> 
> I will bring this discussion to the team and try to add to ethereum.org roadmap.
> 
> 

Yes, it must be a community based team project, it's a lot to do for a few designers, maybe people contributing at Google Fonts Open Source projects, there are designers with knowledge in different scripts and experienced font engineers that could join from there, I have some friends that might be excited with the idea as well, reaching local type design communities from all over the world might be a good idea too

**Comment by samajammin** [comment]
Thanks @nloureiro! Adding my 2 gwei 😄 

> The first question does open the discussion: Should the new design system keep this option? or choose a font to be the base on all screens and languages?

I think it's worth establishing a consistent font for all screens & languages. I believe the benefits you mentioned outweighs the downside.

> Should ethereum.org have a specific font family? If yes, do you have any recommendations that fit the criteria?

Yes but no strong preference here. Of the ones mentioned, I do like the look of Public Sans & Inter.

**Comment by nloureiro** [comment]
After some consideration, we will adopt Inter as the new font for ethereum.org.
This was the outcome-based:

- Checks all the base criteria.
- Light in weight and might be considered to use as variable font, even lighter.
- Open-source.
- Made for digital with readability in mind.
- Works very well on small screens.
- A great character set, not perfect but very good. We will study the best way to fall back on other characters (I hope to have the community help on this one).

The final Design System Figma is on WIP here: https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=0%3A1

Thank you.
For any other discussion please open a new issue or reach out on Discord.
