### ISSUE TITLE
[TS Code Style]Emoji component has a required size props

### ISSUE THREAD

**Issue by Mousticke** [ethereum/ethereum-org-website#6626]
**Describe the bug**

This is purely coding style issue.
The `Emoji` component has a `size` props with a default value
```ts
const Emoji: React.FC<IProps> = ({ size = 1.5, text, ...props }) 
```
with a defined interface `IProps`

```ts
export interface IProps extends MarginProps {
  size: number
  text: string
}
```

Here `size` is required but set with a default value in the functional components. Other components require the `Emoji` component and have to set the `size` because of the interface.
We should replace the required props as an optional props.

**Expected behavior**

We expect this interface in `src/components/Emoji.tsx`
```ts
export interface IProps extends MarginProps {
  size?: number
  text: string
}
```

**Additional context**

Part of the Typescript rollout: #6392 
Emoji PR for the migration: #6540  

**Want to contribute?**

You can assign me this issue if you want.

**Comment by pettinarip** [comment]
Good catch @Mousticke. I've assigned it to you
