### ISSUE TITLE
Starting translation in Bulgarian language.

### ISSUE THREAD

**Issue by Dobrevmotorsport** [ethereum/ethereum-org-website#663]
I'm here after Ethereum Individuals-Developers-Enterprise "Language Support" - "Ethereum.org Translation Program", point 3.
I have the desire to start translating in Bulgarian language.
What next?

**Comment by samajammin** [comment]
Thanks for volunteering your time @Dobrevmotorsport!

We manage translations via a platform called CrowdIn. You can join our project here:
https://crowdin.com/project/ethereumfoundation/invite

Once you join, you can begin translating immediately here:
https://crowdin.com/project/ethereumfoundation/bg#

You can learn more about our Translation Program here:
https://ethereum.org/languages/

Let us know if you have any questions! Looking forward to getting your translations on ethereum.org!

**Comment by samajammin** [comment]
FYI @Dobrevmotorsport - I'm closing this issue out in favor of #314 - please feel free to add any questions or discussion there. Thanks!
