### ISSUE TITLE
Rename Turbo-Geth to Erigon where necessary

### ISSUE THREAD

**Issue by jonasbostoen** [ethereum/ethereum-org-website#6637]
**Is your feature request related to a problem? Please describe.**

In https://ethereum.org/en/developers/docs/programming-languages/golang, Erigon is still named Turbo-Geth and the links are outdated. This should be updated.

**Want to contribute?**
Yes, will open a PR for a fix

**Comment by amilcarnetto** [comment]
yes, I can help

**Comment by minimalsm** [comment]
Closed in #6638
