### ISSUE TITLE
Establish design principles

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#667]
**Is your feature request related to a problem? Please describe.**

While [our README outlines core principles for ethereum.org](https://github.com/ethereum/ethereum-org-website#ethereumorgs-design-and-content-is-guided-by-three-core-principles) it's still difficult for contributors to add new content or propose design changes to the site. We'd like to establish design principles to serve as a set of guidelines we refer to when designing (i.e. creating, maintaining or updating) something. 

These design principles should be the foundation for what we want the website to represent and project to the world. They’re both aspirational and functional. It’s not just how the website looks, but also how it works and even how it makes someone feel. Everything, from the colors to the page layouts to how we talk about Ethereum on the website should be informed by these principles.

**Describe the solution you'd like**

Document a list of design principles that will serve as a guide for code & content contributors as well as an internal reference when making decisions on product & design tradeoffs.

**Describe alternatives you've considered**

**Additional context**

**Comment by samajammin** [comment]
[Here are the currently proposed principles](https://paper.dropbox.com/doc/Proposed-Design-Principles-for-Ethereum.org-Community-Comment--ArT5JucoiESS5E2iZyUhONCiAg-SiLs6D0wTBGPQ93oPT2qa). Input welcome!

**Comment by edsonayllon** [comment]
Design principles should align to Ethereum's philosophy, specified in the Whitepaper: [Ethereum/wiki/whitepaper](https://github.com/ethereum/wiki/wiki/White-Paper#philosophy).

These include:
- Simplicity
- Agility
- Modularity
- Universality
- Non-censorship (or freedom of expression)

**Comment by edsonayllon** [comment]
And for visuals, there are general graphic design principles, [freely available online](https://en.wikibooks.org/wiki/Graphic_Design/Principles_of_Design). Some core principles of graphic design include:
- Balance
- Rhythm
- Unity
- Contrast
- Emphasis

Which may be helpful for new contributors. 

However, branding unique to Ethereum will probably benefit more from the principles included in the Philosophy section of the Whitepaper, as stated in the comment above.
