### ISSUE TITLE
Tutorial tags incorrectly counting/filtering

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#6672]
**Describe the bug**
Tutorial tag filters are not working appropriately. Getting non-english results when filtering, with inaccurate "count", and slightly confusing results with the external tutorial links.

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/
2. Click on any tag... we'll go with "Analytics (1)" here
3. Scroll down, and notice more than one tutorial is being shown, and when I do this the external one is not tagged "Analytics"
4. Try refreshing (or clearing filter) and then filtering "SQL (1)"
5. Here I'm getting 5 results.. 1 external without the "SQL" tag, 4 all of the same tutorial, just translated (en, id, it, ro).

**Expected behavior**
- "External" tutorials should be tagged in the data file, and these tags should be displaying appropriately on each tutorial card
- Non-english tutorials should only be shown when user is on that language locale (English only on English pages, English acceptable on languages that have not yet been translated)
- The filter count should include the proper number of tutorials available for the given language, including the external tutorials, not including translated versions of the same tutorial.

**Screenshots**
<img width="64" alt="image" src="https://user-images.githubusercontent.com/54227730/173458430-247a80fe-bc2c-4257-9a5c-106bc0a9adb9.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/54227730/173458398-d4cca70f-4fe5-4b26-b7bf-d101a8ac2954.png">

**Desktop (please complete the following information):**

- OS: Monterey
- Browser: Brave
- Version: [Version 1.39.122](https://brave.com/latest/)

**Additional context**
#6365 Epic: Revamp Tutorials section -- This issue may be solved separately via these efforts, but wanted to surface.

**Comment by SNikhill** [comment]
@minimalsm 

May I please have a look at this issue?

**Comment by RanchHowards** [comment]
@minimalsm i'm taking a look as well
