### ISSUE TITLE
Add Section for Infura to Available frameworks

### ISSUE THREAD

**Issue by anataliocs** [ethereum/ethereum-org-website#6673]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

Infura

**Product description:**

Blockchain Development Suite consisting of high availability APIs and Developer Tools that provide quick, reliable access to the Ethereum, IPFS, Filecoin, Polygon, Arbitrum, Optimism, NEAR and Aurora networks.  Infura also provides monitoring, analytics ,notifications and other services to blockchain developers to help abstract away the complexity of running node infrastructure.

**How long has it been around?**

Infura was launched in 2016.

**Where do you think it should go?**

https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/frameworks/index.md

Under "Available frameworks"

**GitHub URL**

[Infura Github](https://github.com/INFURA/infura)

**Docs URL**

[Infura docs](https://docs.infura.io/infura/)

**Is the product open source?**

Many repositories owned by the Infura Github org are OSS.

**Additional context**

Please assign this request to me, Chris Anatalio, Platform Advocate @ Infura

**Comment by corwintines** [comment]
This sounds more like nodes as a service which we have Infura listed under. I'm going to close this out for now, but if you want to revive this issue if I misunderstood @anataliocs please do :)
