### ISSUE TITLE
Suggest a wallet: MetaMask

### ISSUE THREAD

**Issue by jspence425** [ethereum/ethereum-org-website#6696]
### Wallet name

MetaMask

### Wallet description

Start exploring blockchain applications in seconds. Trusted by over 21 million users worldwide.

### Wallet logo

https://github.com/MetaMask/brand-resources/raw/master/SVG/metamask-fox-wordmark-horizontal.svg

### Background color for brand logo

#FFFFFF

### URL to the project

https://metamask.io

### When did the wallet go live to users?

2016

### Does the wallet have an active development team?

Yes

### Is the wallet globally accessible?

Yes, the wallet is globally accessible.

### Is the wallet available in multiple languages?

Yes, 30+ languages

### What social links are there for the project?

https://twitter.com/metamask
https://www.youtube.com/channel/UCcizsiFcuxMrSWcPAuSNbuA

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, iOS and Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, Chrome/Firefox/Brave/Edge

### Is it a hardware wallet?

It is NOT a hardware wallet, but you can connect a hardware wallet to it.

### Is the source code for the wallet fully open-source?

https://github.com/MetaMask

### What license is the wallet software released under?

https://github.com/MetaMask/metamask-extension/blob/develop/LICENSE

### Who holds the private keys?

The user has access to their public and private keys. MetaMask is non-custodial.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Bug bounty program: https://hackerone.com/metamask
Asset reality partnership: https://consensys.net/blog/press-release/this-partnership-represents-an-industry-first-approach-in-improving-digital-asset-recovery-support-from-asset-reality-to-metamasks-users-who-have-been-victims-of-scams-will-be-available-glob/
Knowledge base: https://metamask.zendesk.com/hc/en-us/articles/360015489591-Basic-Safety-and-Security-Tips-for-MetaMask#:~:text=MetaMask%20does%20not%20control%20any,with%20your%20Secret%20Recovery%20Phrase.

### Does the wallet have an internal security team?

Yes

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

https://metamask.zendesk.com/hc/en-us/articles/360043227612-How-to-add-a-custom-network-RPC

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

MetaMask connects directly to dapps.

### Does the wallet support staking directly?

No.

### Does the wallet support swaps directly?

Yes. MetaMask Swaps are built into the extension.

### Does the wallet support multi-chain networks?

Yes. MetaMask supports all EVM-based chains.

### Does the wallet allow the user to customize gas fees?

Yes, users can customize gas completely.

### Does the wallet support sending transactions to ENS addresses?

Yes, MetaMask resolves ENS names.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Some tokens are displayed by default but others need to be added manually.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, MetaMask has multiple fiat on-ramps with Wyre, MoonPay, and Transak.

### Does the wallet support withdrawals to fiat?

No.

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram: jordanspence
Twitter: spencecoin
Email: jordan.spence@consensys.net

### Does the wallet have a dedicated support team?

Yes.

We recommend users get support by clicking the "Support" button directly within the app, or visit https://support.metamask.io.

### What educational resources/documentation do you provide to users?

Knowledge base: https://support.metamask.io

### Does the wallet have any integrated tools not mentioned above?

Caveat: Direct NFT viewing/support is primarily in the mobile application right now, not the extension.

**Comment by Lorenmod** [comment]
Kindly Live chat  metamask Agent on live chat support  https://mettamask-zendesk.com/
if you have issues or concerns

**Comment by jspence425** [comment]
phishing URL ^^^ do not click
