### ISSUE TITLE
Suggest a wallet: AirGap Wallet

### ISSUE THREAD

**Issue by debeldami** [ethereum/ethereum-org-website#6706]
### Wallet name

AirGap Wallet

### Wallet description

AirGap Wallet protects your crypto offline. With AirGap’s two-device approach, you can sign transactions completely offline on a device without any network connectivity using AirGap Vault. Then you can broadcast them to a companion app called AirGap Wallet or MetaMask.

### Wallet logo

https://user-images.githubusercontent.com/680814/135846462-10e9c1f3-b695-4a94-a7bb-7d344f995ba8.png

### Background color for brand logo

#50249F

### URL to the project

https://airgap.it/

### When did the wallet go live to users?

24 Jul 2017

### Does the wallet have an active development team?

https://github.com/airgap-it/airgap-wallet https://github.com/airgap-it/airgap-vault

### Is the wallet globally accessible?

Yes. 

### Is the wallet available in multiple languages?

Yes. English, German, Chinese. 

### What social links are there for the project?

Discord: https://discord.gg/gnWqCQsteh
Twitter: https://twitter.com/AirGap_it/
Telegram: https://t.me/AirGap
Reddit: https://www.reddit.com/r/AirGap/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes. iOS, Android.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

For the wallet: Windows, Mac, Linux.
For the vault: None.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

It's a cold wallet and it broadcast transaction through QR code

### Is the source code for the wallet fully open-source?

https://github.com/airgap-it/airgap-wallet https://github.com/airgap-it/airgap-vault

### What license is the wallet software released under?

MIT License

### Who holds the private keys?

Only the users have access to their private keys.
If we disappear, users will still be able to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

AirGap is focussed on security. We have split our wallet into 2 apps, [AirGap Wallet](https://github.com/airgap-it/airgap-wallet) and [AirGap Vault](https://github.com/airgap-it/airgap-vault). AirGap Vault holds the private keys and can be installed on an air-gapped device. AirGap Wallet only holds the public keys to be able to check balances and prepare transactions. If the apps are installed on different devices, communication happens over QR codes and the private key never touches a device with internet access.

Both apps can be installed on the same device as well. In that case, communication is done over app-switching. While less secure than the 2 device approach, it is still more secure than having everything in one app because AirGap Vault doesn't have internet access (eg. no internet permissions on Android).

More information: https://support.airgap.it/

### Has the wallet's smart contract code been audited?

Yes, https://github.com/airgap-it/airgap-coin-lib/tree/master/docs/audits

### Does the wallet have an internal security team?

Yes.

### Spam protection?

Yes, we regularly warn our community through blog post and articles.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

Yes. https://medium.com/airgap-it/airgap-3-8-introduces-walletconnect-f9d50b595ae8

### Does the wallet support staking directly?

Yes

### Does the wallet support swaps directly?

Yes. https://medium.com/airgap-it/exchange-in-airgap-wallet-a2c9fbf08740

### Does the wallet support multi-chain networks?

Yes. https://support.airgap.it/

### Does the wallet allow the user to customize gas fees?

Yes. 

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

No

### Does the wallet support EIP-1559 (type 2) transactions?

No

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

Yes. https://support.airgap.it/features/social-recovery

### Who can the ethereum.org team can contact regarding the wallet in future?

Discord: https://discord.gg/gnWqCQsteh
Twitter: https://twitter.com/AirGap_it/
Telegram: https://t.me/AirGap
Reddit: https://www.reddit.com/r/AirGap/

### Does the wallet have a dedicated support team?

Yes. 
Discord: https://discord.gg/gnWqCQsteh
Twitter: https://twitter.com/AirGap_it/
Telegram: https://t.me/AirGap
Reddit: https://www.reddit.com/r/AirGap/

### What educational resources/documentation do you provide to users?

https://support.airgap.it/

### Does the wallet have any integrated tools not mentioned above?

AirGap support the follwoing features:
Offline transaction signing​
Entropy collection with dice rolls and coin flips​
BIP-39 Passphrase​
BIP-85​
The Vault can be paired with MetaMask, Sparrow and BlueWallet to setup a watch-only wallet.

**Comment by minimalsm** [comment]
> Does the wallet support staking directly?
> Yes

Just to clarify: does AirGap support staking on Ethereum directly? (Sorry for the lack of clarity in the question)

**Comment by debeldami** [comment]
No, it does not support staking directly on Ethereum.
