### ISSUE TITLE
Translation Slack group invite link expired

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#673]
**Describe the bug**

The invite link has expired:
https://join.slack.com/t/ethtranslation/shared_invite/enQtODQzNTM0ODEzMjUzLTM3ZTg1ZjkxNDFjY2ZiOGNlM2M0ZmNhZmVmMjI3NGM5OWE4YjhhZTdkYmVkZThiNzVmM2JlYzM3NTA5NjVmNTE

**Comment by samajammin** [comment]
Hey @sorumfactory - happy new year 🎉 😄 

Could you please create a new invite link & share here? Looks like the current one has expired.

Thanks!

**Comment by sorumfactory** [comment]
Happy New Year @samajammin 
Thank you for raising this issue. 👍 
Here is the new invitation link which will be validated for 30 days. 

[](https://join.slack.com/t/ethtranslation/shared_invite/enQtOTAxMDQzMjEzNzMzLTA0ODMxNzZmN2IzODkwYWQyY2ExMTMxMmIzMDM0ZTBhNDVmZTc4NDhiODYzM2I3OWM3ZTkxNjYzM2JkY2Q0NmY)

Unfortunately for security reasons, Slack doesn't allow us to issue the invitation link without expiration. I will make sure to keep updating this invitation link by setting the monthly alarm on my calendar.

**Comment by samajammin** [comment]
Reopening - the link expired again.
