### ISSUE TITLE
Kromatika Finance PR

### ISSUE THREAD

**Issue by fensa08** [ethereum/ethereum-org-website#6736]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**
Link to documentation: [docs.kromatika.finance](https://docs.kromatika.finance/)

The team behind Kromatika Finance regards security as a core value and values it very highly. As a consequence, the dapp was subject to multiple security audits from different vendors such as CertiK, MythX and OpenZeppelin. 

Link to Certik security audit: https://1474401179-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FoxScRKy1rYzwfDKYX6RP%2Fuploads%2FUNfZdjITt0i45hgvjlSi%2FSecurity_audit-Kromatika.Finance-2022-02-15.pdf?alt=media&token=bc29ad70-3736-4848-b08a-9159ee309b61

**Is your dapp open source?**

Yes, the link to the github organization repo could be found here: https://github.com/Kromatika-Finance (the front end repository is called interface, while the smart contracts can be found in the limit-trade repository)

Yes, the community developers could open PRs for both the front-end and the smart contracts.
Smart contracts could be found on: https://github.com/Kromatika-Finance/limit-trade

**Can a user access the dapp without creating an account?**
Yes. As a true web3 product, the dapp can be accessed without accounts and can be used only with wallet connected.

Yes, the user can simply connect with their Ethereum address

**Are dapp funds non-custodial?**
Yes, the user funds are non-custodial. However, in order to use the limit order feature you should deposit $KROM ( Kromatika's token).

Yes, the smart contracts are still there and accessible.

**Do you offer community support?**
Yes, we have dedicated discord channel for that purpose. Additionaly, we have team that is constantly monitoring all of our social media accounts & groups.

Discord: https://discord.com/invite/Uv2Q2v26JG
Twitter: https://twitter.com/KromatikaFi
Instagram: https://www.instagram.com/kromatika.finance/
Telegram: https://t.me/kromatika_finance
Reddit: https://www.reddit.com/r/KromatikaFinance/
Medium: https://kromatika-finance.medium.com/
Facebook: https://www.facebook.com/kromatika.finance
Linkedin: https://www.linkedin.com/company/kromatika/

**Describe any geographical restrictions on usage of your dapp**
No geographical restrictions exist.

Yes, it is globally accessible.

**Dapp title**
Kromatika Protocol

Kromatika Finance 

**Dapp description**
Kromatika is a MetaDEX which offers aggregated swaps, limit orders and gasless trading.

KROMATIKA is a decentralized crypto trading protocol (MetaDEX) enabling users to trade crypto assets with meta aggregated swaps (which yield best value for the money), gasless trading, automatically executed limit orders which earn LP fees, avoid front running bots and price slippage.

**Dapp logo**
![KROM_Transparent200x200](https://user-images.githubusercontent.com/23368066/174435801-ef54c70d-caf0-4a83-bf96-822df18b355d.png)

![kromatika-logo-color](https://user-images.githubusercontent.com/23368066/174436104-5ef1887f-a483-4fff-9435-b583b86d623d.svg)

**Brand color**
Shade of a mix between purple and sky blue

its a radial gradient with a mix of different colors, #b8e5fe > #aabbf5 > #ebaeef

**Comment by corwintines** [comment]
Hey @fensa08,

Looking into this, I saw that the total volume for a day in Kromatika is ~30k https://defillama.com/protocol/kromatika. This leads me to think this is not used too much, and would not be sufficient to have on Ethereum.org.
