### ISSUE TITLE
Ethereum Classic 2.0

### ISSUE THREAD

**Issue by RencryptedKnight** [ethereum/ethereum-org-website#6741]
With the upcoming merge and Eth 2.0 no longer being mineable in the future there is a demand for mining other alt coins in Ethereum's place. 

With the decline in Ethereum's value due to inflation and lack of consumer confidence I cannot help but feel that there is a void that can be filled. 

Ethereum Classic 2 could potentially fill the void when proof-of-work shifts to proof-of-stake for Ethereum.

I sympathize with the miners all over the world that rely on Ethereum for passive income as this will no longer be an option for them and they will instead have to opt into mining other less valuable less established crypto tokens and coins.

I would love to contribute to the idea of Ethereum Classic 2 if not invest. Feel free to contact my email usofat88@gmail.com as I would love to get the gears grinding on such a project.

**Comment by minimalsm** [comment]
Hey this is the repo for ethereum.org, the website. This isn't the best place for this kind of discussion, sorry :-)
