### ISSUE TITLE
Add JSON RPC API endpoints to the documentation page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#6760]
**Is your feature request related to a problem? Please describe.**

After the recent migration of eth.wiki (#5690) we heard some feedback that folks still relied on a page (e.g. [here](https://twitter.com/kelvinfichter/status/1537831333854052353?s=20&t=1KU3eFz4N2RBF8J8bNYGYg)) to reference API methods.

We used to list the methods but removed them (in #3553) in favor of the [spec](https://github.com/ethereum/execution-apis) & [playground](https://ethereum.github.io/execution-apis/api-documentation/). Spoke to @lightclient & agreed that the playground perhaps isn't yet the best place to serve as the canonical reference, so let's re-add the list of methods back to the ethereum.org docs (on https://ethereum.org/en/developers/docs/apis/json-rpc/)

**Describe the solution you'd like**

Essentially revert #3553 so we provide a list of JSON RPC API methods that folks can reference, link directly to & view curl examples for.

**Describe alternatives you've considered**

- Push people directly to the [spec playground docs](https://ethereum.github.io/execution-apis/api-documentation/) from https://ethereum.org/en/developers/docs/apis/json-rpc/
- Update the eth.wiki redirect from https://eth.wiki/json-rpc/API directly to https://ethereum.github.io/execution-apis/api-documentation/

**Additional context**

Long-term vision is to have the spec repo & [playground](https://ethereum.github.io/execution-apis/api-documentation/) serve as the canonical reference but the app needs a bit of work before we feel good about it 😄 - perhaps a Q3 project.

**Comment by lightclient** [comment]
Still want! :D

**Comment by wackerow** [comment]
Closed with #6770
