### ISSUE TITLE
Missing Translation Types during TypeScript Migration

### ISSUE THREAD

**Issue by byhow** [ethereum/ethereum-org-website#6767]
**Describe the bug**

During the TypeScript migration [epic](https://github.com/ethereum/ethereum-org-website/issues/6392), we migrated `Translation.js` to TS in https://github.com/ethereum/ethereum-org-website/pull/6540, which enforced types to be derived from `src/intl/en.json` as the default translation string. 

While running `yarn type-check`, a lot of the translation keys were missing from the JSON file, which doesn't have the corresponding translation `text`. e.g. 

```
src/components/Footer.tsx:279:11 - error TS2322: Type '"ethereum-bug-bounty"' is not assignable to type '"summary" | "image" | "use" | "search" | "about" | "security" | "yes" | "no" | "glossary" | "copy" | "loading" | "next" | "previous" | "logo" | "wallets" | "merge" | "1inch-logo" | ... 2224 more ... | "template-usecase-dropdown-aria"'.

279           text: "ethereum-bug-bounty",
              ~~~~

  src/components/Footer.tsx:129:5
    129     text: TranslationKey
            ~~~~
    The expected type comes from property 'text' which is declared here on type '{ to: string; text: "summary" | "image" | "use" | "search" | "about" | "security" | "yes" | "no" | "glossary" | "copy" | "loading" | "next" | "previous" | "logo" | "wallets" | "merge" | ... 2225 more ... | "template-usecase-dropdown-aria"; isPartiallyActive?: boolean | undefined; }'
```
Or:
```
src/components/MergeInfographic.tsx:118:9 - error TS2345: Argument of type '"page-upgrades-merge-infographic-alt-text"' is not assignable to parameter of type '"summary" | "image" | "use" | "search" | "about" | "security" | "yes" | "no" | "glossary" | "copy" | "loading" | "next" | "previous" | "logo" | "wallets" | "merge" | "1inch-logo" | ... 2224 more ... | "template-usecase-dropdown-aria"'.

118         "page-upgrades-merge-infographic-alt-text",
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/MergeInfographic.tsx:123:22 - error TS2322: Type '"page-upgrades-merge-infographic-el"' is not assignable to type '"summary" | "image" | "use" | "search" | "about" | "security" | "yes" | "no" | "glossary" | "copy" | "loading" | "next" | "previous" | "logo" | "wallets" | "merge" | "1inch-logo" | ... 2224 more ... | "template-usecase-dropdown-aria"'.

123         <Translation id="page-upgrades-merge-infographic-el" />
```
We will need to add the missing types and their corresponding translation text to the default `en.json` file so when we do:
```ts
export type TranslationKey = keyof typeof defaultStrings
```
the ^ type won't raise any issues.

**To Reproduce**
1. run `yarn type-check`
2. look for error messages related to translation

**Expected behavior**

No TSC errors related to `translation.ts`
**Screenshots**

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/25713361/174943930-00cc4af4-2dc4-4c6b-b400-e4fef811e6b1.png">

**Want to contribute?**
Sure, but we will need to come up with the suitable translation key value pairs or content in `en.json` to catch the missing types, which may need community effort. If not, I can try to infer from the context as much as possible and we can review them in the upcoming PR, either way.

**Comment by pettinarip** [comment]
Thanks for raising this issue. What is happening here is that, as you described, your local `en.json` file is not updated since we have recently added new translations.

That file is in the `.gitignore` and gets updated locally every time you build the site by running `yarn build` or `yarn start`. In order to fix it, you will need to run either of those scripts and you will see in the output something like this:
```bash
success copy gatsby files - 0.113s
success Compiling Gatsby Functions - 0.149s
info Merged translations saved # <==== this line is updating the file
info Contributors copied
success onPreBootstrap - 0.235s
success createSchemaCustomization - 
```

Once you did that, run again `yarn type-check`.
