### ISSUE TITLE
Web3Auth - Suggest a wallet

### ISSUE THREAD

**Issue by yashovardhan** [ethereum/ethereum-org-website#6781]
### Wallet name

Web3Auth

### Wallet description

"Web3Auth is a wallet infrastructure where passwordless auth meets non-custodial key infrastructure for Web3 apps and wallets. By aggregating OAuth (Google, Twitter, Discord) logins, different wallets and innovative Multi Party Computation (MPC) - Web3Auth provides a seamless login experience to every user on your application be it Gaming, DeFi or NFT.

You can integrate Web3Auth into your application with a couple lines of code and allow users to connect to any blockchain, Ethereum, Solana, Polygon and all others. With web mobile, and Unity SDKs, you can customize its look and branding specifically for your application. Alternatively fully whitelabel and take charge of your UI/UX. For Web2 applications, Web3Auth easily extends your existing auth setup to seamlessly onboard your mainstream users into the decentralized ecosystem and connect native users via their wallet of choice (i.e Metamask, Phantom, Coinbase). 

With Web3Auth applications and wallets find:
- Simplified onboarding leading to higher conversion rates by as much as 64%
- Key recoverability and availibity via enhanced non-custodial 2FA resulting in an 80% reduction of support tickets
- Robust infrastructure that currently already supports 15M users, enterprise grade MPC and uptime guarantees

Plug n play Web3Auth and even your grandma can use your dapp."

### Wallet logo

![](https://web3auth.io/images/web3auth-logo.svg)
![](https://web3auth.io/images/web3auth-logo-Dark.svg)
![](https://web3auth.io/images/w3a-L-Favicon-1.svg)
![](https://web3auth.io/images/w3a-D-Favicon-1.svg)

### Background color for brand logo

#0364FF

### URL to the project

https://web3auth.io

### When did the wallet go live to users?

Jan 2022

### Does the wallet have an active development team?

Yes, we have an active development team consisting of platform specific engineers for mobile web and gaming platforms, internal security team, blockchain and protocol engineering team alongside developer relations team for helping people integrate web3auth as easily as possible. https://github.com/web3auth/web3auth

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

Yes, more than 6 languages are natively supported alongside an option to whitelabel according to ones own needs.

### What social links are there for the project?

https://twitter.com/web3auth
https://www.linkedin.com/company/web3auth
https://youtube.com/c/web3auth
https://discord.gg/web3auth
https://t.me/web3authdev

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Web3Auth has SDKs for following platforms
- Web (JavaScript SDK for all web frameworks)
- iOS
- Android
- React Native
- Flutter
- Unity
- Unreal Engine

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Web3Auth has SDKs for following platforms
- Web (JavaScript SDK for all web frameworks)
- iOS
- Android
- React Native
- Flutter
- Unity
- Unreal Engine

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Web3Auth has SDKs for following platforms
- Web (JavaScript SDK for all web frameworks)
- iOS
- Android
- React Native
- Flutter
- Unity
- Unreal Engine

### Is it a hardware wallet?

No, Web3Auth doesn't support hardware wallets

### Is the source code for the wallet fully open-source?

Yes, https://github.com/web3auth/web3auth

### What license is the wallet software released under?

MIT License

### Who holds the private keys?

The user holds the private key.

The Web3Auth SDK enables you to generate a private key for the user to work directly with your blockchain of choice, after the user has logged in with traditional login methods, like Google, Facebook, Twitter, etc. This is done by generating a private key in a self custodial way for the user shared across all applications linked to your social accounts, via Web3Auth's MPC architecture. This enables users to have the same experience they are used to when logging in. Crypto native users can still connect with the wallet provider of their choice. Learn more about how the Web3Auth key infrastructure works [here](https://docs.web3auth.io/overview/how-web3auth-works).

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://web3auth.io/docs/overview/key-management
https://docs.tor.us/key-infrastructure/overview
https://web3auth.io/docs/overview/audits

### Has the wallet's smart contract code been audited?

Yes, we are audited every quarter: https://web3auth.io/docs/overview/audits

### Does the wallet have an internal security team?

Yes, our CTO leads a security team of 3. One focused on backend penetration and systems and the other on front-end domain security and cryptographic guarantees. Our internal security team is baked into the deployment process, such that any pushed code is reviewed.

### Any other security testing that should be noted?

We have :
a) An internal security team that is baked into the deployment process, such that any pushed code is reviewed.
b) Security audits every two quarters with different external parties, public reports can be found here https://github.com/torusresearch/audit
c) An ongoing bug bounty program https://web3auth.io/docs/contribute/bug-bounty

We have steps to secure against both application and network level DDoS. Backends are secured by an internal proxy, that handle IP/individual limits. 

### Spam protection?

We have steps to secure against both application and network level DDoS. Backends are secured by an internal proxy, that handle IP/individual limits. 

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes, https://web3auth.io/docs/api-reference/web/plugnplay#adding-a-custom-chain-configuration

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, it a wallet infrastructure that can be connected to any ethereum application

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

Yes, we support all chains

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

Yes

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

@yashovardhan (`@yashweb3` on Telegram). Also `@Web3AuthTeam` is available on Discord always

### Does the wallet have a dedicated support team?

Yes - https://discord.com/invite/web3auth

### What educational resources/documentation do you provide to users?

Yes - https://web3auth.io/docs/

**Comment by minimalsm** [comment]
> Is the wallet available in multiple languages?
> Yes, more than 6 languages are natively supported alongside an option to whitelabel according to ones own needs.

Hey @yashovardhan, could you provise some info on what languages you support? I couldn't find the info anywhere :]

**Comment by yashovardhan** [comment]
Hey @minimalsm 

You can find details on language changes on our [whitelabeling documentation](https://web3auth.io/docs/whitelabeling#defaultlanguage)
