### ISSUE TITLE
Suggest a wallet: Guarda

### ISSUE THREAD

**Issue by bchrvl** [ethereum/ethereum-org-website#6784]
### Wallet name

Guarda

### Wallet description

Secure, feature-packed, non-custodial crypto wallet with support for over 50 blockchains. Easy and profitable staking, exchange, send, receive and purchase basically any crypto asset.

### Wallet logo

![guarda-shield-logo](https://user-images.githubusercontent.com/28879222/175073822-3bc233bd-cbe4-485b-a6c6-5050ac38a23b.svg)

### Background color for brand logo

#ffffff

### URL to the project

https://guarda.com/

### When did the wallet go live to users?

2017

### Does the wallet have an active development team?

https://github.com/guardaco

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

https://twitter.com/GuardaWallet
https://www.reddit.com/r/GuardaWallet/
https://www.facebook.com/guardawallet
https://www.youtube.com/c/GuardaWallet
https://www.linkedin.com/company/guardawallet/
https://t.me/Guarda_community

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

https://apps.apple.com/app/apple-store/id1442083982
https://play.google.com/store/apps/details?id=com.crypto.multiwallet

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

macOS - https://github.com/guardaco/guarda-desktop-releases/releases/download/v1.0.20/Guarda-1.0.20.dmg
Windows - https://github.com/guardaco/guarda-desktop-releases/releases/download/v1.0.20/Guarda-Setup-1.0.20.exe
Linux (.deb) - https://github.com/guardaco/guarda-desktop-releases/releases/download/v1.0.20/Guarda_1.0.20_amd64.deb
Linux (.AppImage) - https://github.com/guardaco/guarda-desktop-releases/releases/download/v1.0.20/Guarda-1.0.20.AppImage

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

https://chrome.google.com/webstore/detail/guarda/hpglfhgfnhbgpjdenjgmdgoeiappafln

### Who holds the private keys?

Users have full access to their public and private keys. Guarda is a non-custodial wallet. If the company were to disappear, users would still be able to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

There hasn't been any official audit conducted, however as the wallet is fully non-custodial and all the info is stored directly on users' devices, there's no possibility for a threat. Also, the data for public and private keys is fully encrypted and can only be accessed with a combination of a backup file and its password.

### Does the wallet have an internal security team?

We have a full-time DevOps team

### Spam protection?

There's an in-app feature available to check addresses for a potential illicit activity via an integrated [third-party service](https://amlbot.com/).

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

via WalletConnect

### Does the wallet support staking directly?

Yes. https://guarda.com/staking/ethereum-staking/

### Does the wallet support swaps directly?

Swaps are provided via third-party service: https://changenow.io/

### Does the wallet support multi-chain networks?

https://guarda.com/coins/

### Does the wallet allow the user to customize gas fees?

Yes.

### Does the wallet support sending transactions to ENS addresses?

Yes.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Available through third-party services. https://guarda.com/buy/

### Is the wallet a multi-signature wallet?

Yes. Multi-signature for ETH addresses is supprted.

### Who can the ethereum.org team can contact regarding the wallet in future?

https://t.me/belijah - Elijah Boch - Chief Marketing Officer
or you can contact us directly on Twitter - https://twitter.com/GuardaWallet

### Does the wallet have a dedicated support team?

https://support.guarda.com/
The support team usually replies within an hour.

### What educational resources/documentation do you provide to users?

https://guarda.com/academy/

**Comment by minimalsm** [comment]
Hey @bchrvl, could you provide some info on the multisig setup for Ethereum? I can only find guarda implementing multsig functionality on Bitcoin.

**Comment by bchrvl** [comment]
Hey @minimalsm. Sure, you'd need to type ETH in the search field and find an option of creating a multisig in the list. Here's a screenshot. Let me know if you need any further assistance regarding any of the functionality.
<img width="459" alt="Screenshot 2022-06-25 at 00 22 15" src="https://user-images.githubusercontent.com/28879222/175689413-6a46b5f1-1119-4bc7-9d54-4753cb3590a8.png">
