### ISSUE TITLE
Ensure consistent spelling of 'logo' for alts

### ISSUE THREAD

**Issue by hursittarcan** [ethereum/ethereum-org-website#6803]
**Describe the bug**

We currently use different ways of spelling **logo (with and without capital L)**. 
The spelling should be consistent across the website.

**To Reproduce**

1. Go to 'https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en/page-developers-learning-tools.json'.
2. Search for 'logo'. 
3. See that **logo** is spelled in two different ways. 

**Expected behavior**

All instances should have the same spelling ('logo'). 

**Screenshots**

![image](https://user-images.githubusercontent.com/75273616/175172893-a038bbe3-898f-451f-9759-ef78c75a5cb5.png)

**Comment by Auxburger** [comment]
Hey  @hursittarcan, can i take this issue? :)

**Comment by hursittarcan** [comment]
Hey @Auxburger I already fixed this. But thanks for offering to help ✌
