### ISSUE TITLE
Suggest a wallet: ZenGo

### ISSUE THREAD

**Issue by akitov** [ethereum/ethereum-org-website#6805]
### Wallet name

ZenGo: Crypto & Bitcoin Wallet

### Wallet description

ZenGo is the most secure wallet in Web3: The first on-chain wallet with no seed phrase vulnerability, powered by MPC cryptography and encrypted biometrics. Buy, trade, and earn up to 8% interest on your cryptoassets. Securely connect to NFT & DeFi Dapps with ClearSign. Stay zen with our 24/7 in-app customer support.

### Wallet logo

<img width="400" alt="ZenGo logo" src="https://user-images.githubusercontent.com/107115737/174486159-bddceb25-eaab-402f-a80e-b81e27829276.png">

### Background color for brand logo

#35C4BA

### URL to the project

https://zengo.com/

### When did the wallet go live to users?

January 2020

### Does the wallet have an active development team?

Our latest Android version is from Jun 14, 2022 - https://play.google.com/store/apps/details?id=com.zengo.wallet and the latest iOS version is from June 19, 2022 - https://apps.apple.com/us/app/zengo-crypto-bitcoin-wallet/id1440147115

### Is the wallet globally accessible?

Yes, the wallet is globally accessible. ZenGo is a non-custodial, on-chain crypto wallet, not bound to KYC regulations.

### Is the wallet available in multiple languages?

Yes, in English and now in French, with more language support coming soon.

### What social links are there for the project?

🐤 Twitter: https://twitter.com/ZenGo

🌳  Linktree: https://linktr.ee/zengo

💻  Website: https://zengo.com/

🗒️  Blog: https://zengo.com/blog/

💰 Download ZenGo: http://get.zengo.com/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

**Apple App Store** (Rating: 4.7)
https://apps.apple.com/us/app/zengo-crypto-bitcoin-wallet/id1440147115

**Google Play Store** (Rating: 4.3)
https://play.google.com/store/apps/details?id=com.zengo.wallet&hl=en&gl=US

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No desktop app is planned.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No browser extension is planned.

### Is it a hardware wallet?

No, we're not a hardware wallet.

### Is the source code for the wallet fully open-source?

While our app and server code is closed-source, it is routinely audited by external security institutions. In addition, we support a number of open-source development. You can check out our Github account (https://github.com/ZenGo-X) and especially our core cryptography repositories (for example Curv - https://github.com/KZen-networks/curv and Multi-Party-ECDSA - https://github.com/KZen-networks/multi-party-ecdsa).

### Who holds the private keys?

ZenGo is the first on-chain Web3 wallet powered by Multi-Party Computation (MPC) instead of the traditional public/private key architecture. No one entity owns the private keys, they are sharded and distributed between the user and ZenGo.

This provides maximum security and safety from losing the seed phrase, private keys or passwords associated with a wallet. Private keys are automatically constructed using MPC (multi-party computation) only when required to sign transactions and without ever revealing the secret to other party. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

**Our security model is based on multi-party computation (MPC) combined with biometric authentication on the device.**

We’ve replaced the traditional private key with two independently created mathematical secret shares. One share is stored on your mobile device and the other on the ZenGo server. With no single point of failure.

To sign transactions, you initiate a process in which the server and device shares communicate to sign the transaction without ever revealing their secrets to each other

**More on our security model** – https://zengo.com/security-in-depth/ & https://zengo.com/security/

If you delete the app, lose your phone, or want to use ZenGo on a new device, you can restore the wallet simply by scanning your face which will match with the 3D biometric face map you created during setup.

Even if ZenGo, the company, were to stop operating, your funds are still accessible with ChillStorage. 

**More on guaranteed wallet recovery (ChillStorage)** – https://zengo.com/introducing-guaranteed-access-2-0-aka-chill-storage/

### Has the wallet's smart contract code or security modules been audited?

AppSec audit: June 2019, Kudelski audit: March 2019, Kudelski audit: October 2019, Scorpiones audit: February 2020.

### Does the wallet have an internal security team?

We have an internal research team, ZenGo-X, that focuses on internal security as well as general Web3 security-related issues, and have helped many fellow companies and organizations strengthen their own security.  Please check here – https://zengo.com/research/ – there is a full list of the members and the projects.

### Scam protection?

Recently we announced **ClearSign**, a set of features that protect users when interacting with web3 applications and helps prevent the loss of funds, NFTs or other assets.

**ClearSign** does this by doing three things:
1. Enabling signing **without** the private keys being involved (for every transaction)
2. **Enhancing** and **verifying** signature messages
3. **Blocking** unwanted actions from certain supported Dapps (eg approve access to all funds for a ticketing app)

**More resources**:
[Media kit](https://zengoteam.notion.site/ZenGo-ClearSign-Web3-Firewall-Media-kit-2dabf99b9bd3492ca69f5e8fdb9fa995)
[Announcement](https://www.theblock.co/post/153520/crypto-wallet-app-zengo-introduces-web3-firewall-feature-called-clearsign)

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Not yet

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, connecting to Ethereum apps is possible via WalletConnect. More here - https://zengo.com/wallet-connect/#:~:text=WalletConnect%20is%20that%20extra%20security,all%20from%20your%20trusted%20cryptowallet.

### Does the wallet support staking directly?

Yes. More details: https://zengo.com/earn-interest-with-zengo-savings/

### Does the wallet support swaps directly?

Yes, via Changelly. More details: https://zengo.com/trade-swap/

### Does the wallet support multi-chain networks?

Yes. Bitcoin, Ethereum, Tezos, BNB Chain 

### Does the wallet support Ethereum layer 2 networks?

Not yet

### Does the wallet allow the user to customize gas fees?

No

### Does the wallet support sending transactions to ENS addresses?

Not yet

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Not yet

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, we provide fiat on-ramp via Moonpay, Coinmama and Banxa. More here – https://zengo.com/buy/

### Does the wallet support withdrawals to fiat?

Yes, users are able to sell their crypto for fiat and have it sent to their bank account. More here – http://help.zengo.com/en/articles/3183783-how-to-buy-and-sell-crypto-on-zengo

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No, social recovery is not guaranteed so we don't offer it to our users. We believe our MPC-based security model is more secure.

### Who can the ethereum.org team can contact regarding the wallet in future?

You can always reach us with a DM on Twitter at https://twitter.com/ZenGo.

### Does the wallet have a dedicated support team?

Yes, ZenGo is one of the very few wallets offering a **24/7 in-app live support**. 

### What educational resources/documentation do you provide to users?

We believe education is a critical part of helping onboard the next generation of users to crypto and Web3. ZenGo has a [YouTube channel](https://www.youtube.com/channel/UCmkQTLoWB9X3t2eVA5VYZJA), [Podcast](https://thezencryptoshow.transistor.fm/) and a [Blog](https://zengo.com/blog/).

We also provide users with articles from our [help desk](https://help.zengo.com/en/) entirely depending on their context and problem at hand. If needed, they often also ask our 24/7 support team.

This is something that is a true game-changer for users, that they can speak to someone anytime right from the app.

**Comment by akitov** [comment]
Uploading the PDFs from the audits mentioned above.

[Kzen_External_Report_AppSecLabs_June2019.pdf](https://github.com/ethereum/ethereum-org-website/files/8965631/Kzen_External_Report_AppSecLabs_June2019.pdf)
[kzen-curv-audit final 03.01.2019.pdf](https://github.com/ethereum/ethereum-org-website/files/8965632/kzen-curv-audit.final.03.01.2019.pdf)
[REPORT_final_2019-10-22.pdf](https://github.com/ethereum/ethereum-org-website/files/8965634/REPORT_final_2019-10-22.pdf)
[Zengo_MPT_sharable-final.pdf](https://github.com/ethereum/ethereum-org-website/files/8965635/Zengo_MPT_sharable-final.pdf)

**Comment by md-zengo** [comment]
Hi @minimalsm @corwintines some of the information here needs to be updated, can I add the changes directly to this issue so that you can update?

Thanks!

**Comment by Tomwslape5638** [comment]
Yeah

**Comment by F3n4nd0gm** [comment]
https://github.com/ethereum/ethereum-org-website/assets/147960298/6a27bf47-23c5-4947-920b-fc65e9689231

**Comment by F3n4nd0gm** [comment]
![data-plane-propagation.png](https://github.com/ethereum/ethereum-org-website/assets/147960298/de281017-7068-4739-a126-5260d2acb771)

**Comment by md-zengo** [comment]
Can you make the following changes please? Thanks!

# Description
Zengo is the self-custodial wallet with no seed phrase vulnerability.
Protect and manage all of your cryptocurrencies and NFTs with the crypto wallet that’s secure by default.
Buy, sell, trade, and send over 120+ crypto and Web3 assets, all with the power of MPC security, a secure recovery model and unparalleled 24/7 customer support.

Unlock even more security features such as Legacy Transfer - the industry’s 1st self-custodial inheritance-like system, Theft Protection, and an advanced Web3 Firewall with Zengo Pro.

# Logo

![Icon](https://github.com/ethereum/ethereum-org-website/assets/106451840/df41dadc-8c0c-4b89-99eb-ebedb254c083)

# Background color

Transparent

# Does the wallet support EIP-1559 (type 2) transactions?
https://zengo.com/ethereum-london-upgrade/


# Does the wallet have an active development team?

Yes, releasing new versions multiple times each month.

# Does the wallet support Ethereum layer 2 networks?
Yes, Polygon.

# Does the wallet have any integrated tools not mentioned above?
* Legacy Transfer - the industry’s 1st self-custodial inheritance-like system,
* Theft Protection - multi-factor authentication for high value transactions
* ClearSign - an an advanced Web3 Firewall with Zengo Pro.
* 24/7 Support
* Customizable backgrounds
* ... and more

**Comment by md-zengo** [comment]
Hi! Can you please update the resources?

Thanks,

**Comment by md-zengo** [comment]
@minimalsm @corwintines

**Comment by guibor** [comment]
@minimalsm @corwintines ?

**Comment by md-zengo** [comment]
@minimalsm @corwintines ?
