### ISSUE TITLE
Suggest a wallet: MyCrypto

### ISSUE THREAD

**Issue by jspence425** [ethereum/ethereum-org-website#6811]
### Wallet name

MyCrypto

### Wallet description

MyCrypto is an open-source tool that allows you to manage your Ethereum accounts privately and securely. Developed by and for the community since 2015, we’re focused on building awesome products that put the power in people’s hands.

### Wallet logo

![mycrypto logo 2-01](https://user-images.githubusercontent.com/26891718/175367591-aa4b7933-fa8f-43f3-b808-c2644218eaca.png)

### Background color for brand logo

#FFFFFF

### URL to the project

https://mycrypto.com

### When did the wallet go live to users?

February 2018

### Does the wallet have an active development team?

Yes

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

Yes

### What social links are there for the project?

https://twitter.com/mycrypto

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes: Windows, Mac, Linux

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

Yes: https://github.com/MyCryptoHQ

### What license is the wallet software released under?

MIT License

### Who holds the private keys?

Non-custodial: The user holds their private keys.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Open source code, audits, security team

### Has the wallet's smart contract code or security modules been audited?

Yes

### Does the wallet have an internal security team?

Yes

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Yes

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

Yes - supports WalletConnect

### Does the wallet support staking directly?

no

### Does the wallet support swaps directly?

Yes

### Does the wallet support multi-chain networks?

Yes

### Does the wallet support Ethereum layer 2 networks?

Yes, any EVM network can be added

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

support@mycrypto.com

### Does the wallet have a dedicated support team?

Yes

### What educational resources/documentation do you provide to users?

https://blog.mycrypto.com

**Comment by minimalsm** [comment]
> Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

@jspence425 are the audit reports publicly available? we'd love to link to them if possible as it's great for user trust

**Comment by jspence425** [comment]
> > Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible
> 
> @jspence425 are the audit reports publicly available? we'd love to link to them if possible as it's great for user trust

Yeah!! https://github.com/MyCryptoHQ/MyCrypto/wiki/Audit 

I think there may be another more recent one that hasn't been published, but we have those for now ^^
