### ISSUE TITLE
Suggest a wallet: FoxWallet

### ISSUE THREAD

**Issue by Nuts444** [ethereum/ethereum-org-website#6817]
### Wallet name

FoxWallet

### Wallet description

FoxWallet is a safe and easy-to-use decentralized multi-chain wallet, dedicated to creating an entrance and connection to the Web3 world

### Wallet logo

<img width="64" alt="FoxWallet logo transparent" src="https://user-images.githubusercontent.com/102349584/175475248-667415ec-12d9-4435-be4c-1c9a1ca6f2b4.png">

### Background color for brand logo

#FFFFFF

### URL to the project

https://foxwallet.com/en

### When did the wallet go live to users?

November 15, 2021

### Does the wallet have an active development team?

https://github.com/madfoxoO/FoxWallet#foxwallet

### Is the wallet globally accessible?

It is accessible everywhere, excluding China Mainland

### Is the wallet available in multiple languages?

English, Chinese, Ukrainian, Russian, Spanish, Indonesian

### What social links are there for the project?

Discord: https://discord.com/invite/JVjVbe3Zth
Twitter: https://twitter.com/FoxWallet
Telegram: https://t.me/FoxWallet_EN
Medium: https://medium.com/@FoxWallet
Youtube: https://www.youtube.com/channel/UCt9O4HUkuNutXvFoN6NZh-w

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS: https://apps.apple.com/app/foxwallet-crypto-web3/id1590983231
Android: https://apkcombo.com/foxwallet/com.foxwallet.play/
Google Play: https://play.google.com/store/apps/details?id=com.foxwallet.play

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Who holds the private keys?

Only users hold the private keys to FoxWallet accounts. Both the mnemonics and the private keys are stored locally and not uploaded to the server. Account derivation rules follow the standard [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki). Even if the team decided to live in the forest, there would be no risk to users' assets whatsoever. FoxWallet very clearly warns the users not to store their mnemonics and private keys on the phone and not to take screenshot. The app suggests writing them down and not sharing them with anyone. All these are written in the guidelines, service agreement as well as pop up as the users get to see the mnemonics and private keys. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Audit report: https://www.certik.com/projects/fox-wallet

### Does the wallet have an internal security team?

Yes, FoxWallet indeed has a security team. Apart from the technicians fully-devoted to FoxWallet, we are also backed by a mining company. Hence, FoxWallet has the mining company's security team enhancing the work as well. 

### Scam protection?

While adding custom RPC, FoxWallet warns the users. Also, it is stated in the Privacy Policy and Service Agreement. 
![IMG_5817](https://user-images.githubusercontent.com/102349584/175491265-a3f78427-a186-414b-87f9-1321b6f0aa7d.PNG)
![IMG_5818](https://user-images.githubusercontent.com/102349584/175491489-3c770c20-5234-4e78-94d7-af9ce9ee9f7a.jpg)
 

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

https://hc.foxwallet.com/docs/ethereum-advance/

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

https://hc.foxwallet.com/docs/ethereum-advance/add-custom-rpc

### Does the wallet support staking directly?

It is an upcoming feature. 

### Does the wallet support swaps directly?

No 

### Does the wallet support multi-chain networks?

FoxWallet itself is a multi-chain wallet. Here is a list of chains supported at the moment: https://hc.foxwallet.com/docs/ethereum-advance/.  At the time of writing two more chain are being added. 

### Does the wallet support Ethereum layer 2 networks?

https://hc.foxwallet.com/docs/dapp/zksync-v2-testnet; https://hc.foxwallet.com/docs/ethereum-advance/arbitrum; https://hc.foxwallet.com/docs/ethereum-advance/boba; https://hc.foxwallet.com/docs/ethereum-advance/optimism

### Does the wallet allow the user to customize gas fees?

https://hc.foxwallet.com/docs/speed-up-or-cancel-tx

### Does the wallet support sending transactions to ENS addresses?

https://hc.foxwallet.com/docs/manage-funds

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

https://hc.foxwallet.com/docs/erc20-usage

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, FoxWallet supports both types.  EIP1559 consists of gasLimit, baseFee and priorityFee, in which baseFee + priorityFee is equivalent to previous gasPrice. But baseFee * gasLimit will be destroyed and only priorityFee * gasLimit will be owned by the miners, which makes it a preferable choice for the users, hence, for FoxWallet too. 

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

This feature is on the way, and is meant to be available in mid July. 

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Natalie, BD executive 
Email: nataliey@foxwallet.com
Telegram: @nataliia_444

### Does the wallet have a dedicated support team?

FoxWallet has both a 24/7 support channel on Discord:  https://discord.com/channels/913691408047685653/956143346622013470, 
and a contact email for any enquiries: contact@foxwallet.com. The first one is available 24/7 considering we have a global team that is ready to assist the users at any point of time. Issues are fixed as they come without waiting. 

### What educational resources/documentation do you provide to users?

Tutorials/related documents: https://hc.foxwallet.com/docs/
Tutorials - Youtube: https://www.youtube.com/channel/UCt9O4HUkuNutXvFoN6NZh-w
Discord: #foxfacts server - https://discord.com/channels/913691408047685653/988706690490847273; #learntoearn server -  https://discord.com/channels/913691408047685653/973199577714925589
FAQ: https://hc.foxwallet.com/docs/faq

### Does the wallet have any integrated tools not mentioned above?

1. FoxWallet provides mining-related services (data on miners, registering miners, etc.) through the app and the FilFox explorer that was also developed by the team. Respective links can be found below: 
https://hc.foxwallet.com/docs/filecoin-advance/
https://filfox.info/en
2. Another important characteristic of FoxWallet is an extremely user-friendly interface. Thus, FoxWallet is easy for Web3 beginners and makes their experience smooth while providing more complex experience (f.e. mining services) for those long-term blockchain enthusiasts. 
3. FoxWallet is not only a multi-chain wallet, but also a multi-address wallet. One seed phrase can derive multiple isolated accounts(addresses) in FoxWallet. These accounts have different private keys, which helps improve asset security and reduce risks.
4. Bookmarks: users can use the page collection feature to manage their favourite pages.
5. Last but not the least, FoxWallet has an Address Book feature. With this, users can save other people’s cryptocurrency wallet addresses and keep them on the Address Book page of the app.

**Comment by minimalsm** [comment]
> Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?
> This feature is on the way, and is meant to be available in mid July.

You can update this when it goes live. I'll provide instructions soon.

**Comment by Nuts444** [comment]
> Hey @Nuts444, thanks for raising this. Could you clarify about ENS? The doc you linked to isn't clear.
> 
> Are users able to send funds directly to another user using their ENS address?

yes, the users are able to send funds directly to another user using their ENS address.
