### ISSUE TITLE
Update Difficulty bomb and Ice age definition in glossary

### ISSUE THREAD

**Issue by Eni-G** [ethereum/ethereum-org-website#6841]
**Is your feature request related to a problem? Please describe.**

The *Difficulty bomb* and *Ice age* seem to be only described in the glossary, and I think their explanation could be a little more descriptive and linked to each other. This would also help to better understand why it had to be pushed back in several network upgrades (it’s briefly explained by Muir Glacier on the history page).

**Describe the solution you'd like**

*Difficulty bomb
Planned exponential increase in proof-of-work difficulty setting designed to motivate the transition to proof-of-stake, and reducing the chances of a fork.*

I would add:
The difficulty bomb is a mechanism that increases the rate of time needed to mine a new block on the Ethereum blockchain by increasingly adding to the difficulty level of puzzles in the proof-of-work mining algorithm, eventually leading to what is referred to as the “Ice Age”. It discourages miners from opting to continue the energy-intensive proof-of-work mechanism after the transition to proof-of-stake (The Merge) by making mining exponentially difficult and removing the incentive.

*Ice Age
A hard fork of Ethereum at block 200,000 to introduce an exponential difficulty increase (aka difficulty bomb), motivating a transition to proof-of-stake.*

I would add:
The difficulty bomb increasingly adds to the difficulty over time. At first, its effect is barely noticeable in block times, but it increases the value of how much difficulty it adds until the point where the increase is suddenly exponential, and it becomes so difficult to mine on the Ethereum blockchain, that block production stops (freezes) completely.

**Describe alternatives you've considered**

They difficulty bomb could be linked to the Merge page.

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Ajay-singh1** [comment]
Consice Description.Loved It!

**Comment by corwintines** [comment]
If you disagree, feel free to revive in a new issue :)
