### ISSUE TITLE
Broken Links on <https://ethereum.org/en/upgrades/merge/>

### ISSUE THREAD

**Issue by raj-shekhar1** [ethereum/ethereum-org-website#6857]
**Describe the bug**
The below links are broken on the [The Merge homepage](https://ethereum.org/en/upgrades/merge/) in the `Further Reading` section.
1. [Execution layer Specs](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/merge.md)
2. [Consensus layer Specs](https://github.com/ethereum/consensus-specs/tree/dev/specs/bellatrix)

**To Reproduce**

1. Go to '[link](https://ethereum.org/en/upgrades/merge/)'
4. Scroll down to 'Further Reading'
5. Click on `Execution layer Specs` or `Consensus layer Specs`

**Expected behavior**
* It should take me to correct URI

**Want to contribute?**
Yes

**Comment by minimalsm** [comment]
Hey @raj-shekhar1, I see you'd like to contribute to this? 

Thanks for offering to help ❤️  I've assigned you.

**Comment by raj-shekhar1** [comment]
Thanks @minimalsm :)

**Comment by raj-shekhar1** [comment]
Hi @minimalsm I checked for the possible solutions and found below for - 

Existing ---> [Execution layer Specs](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/merge.md)

Suggested --> [Execution layer Specs](https://github.com/ethereum/execution-specs/) 

But for Consensus layer specs hyperlink can you please suggest more suitable resource then below if available.

Existing --> [Consensus layer Specs](https://github.com/ethereum/consensus-specs/tree/dev/specs/bellatrix)

Suggested --> ??

**Comment by jmcook1186** [comment]
The existing link is already the most appropriate for the consensus specs afaik. Another option is to link out to an annotated spec (e.g. Vitalik's), but IMO it is fine as it is.

**Comment by raj-shekhar1** [comment]
@jmcook1186 makes sense. Thanks
I guess this can be marked as closed then, @minimalsm ?

**Comment by minimalsm** [comment]
Thanks again! 

@all-contributors please add @raj-shekhar1 for ideas
