### ISSUE TITLE
Link on client page is recursive

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#6861]
URL on client page links to itself: https://ethereum.org/en/developers/docs/nodes-and-clients/#clients

![image](https://user-images.githubusercontent.com/27454964/176478141-c2dc7ff8-5e77-417a-85ff-dc6fcb1c5739.png)

**Comment by sharbel97** [comment]
status update on this issue?

**Comment by A-ndy-git** [comment]
This is resolved by #6872. Can we close this issue down now?
