### ISSUE TITLE
Suggest a wallet: Status

### ISSUE THREAD

**Issue by hesterbruikman** [ethereum/ethereum-org-website#6862]
### Wallet name

Status

### Wallet description

Cryptocurrency wallet, decentralized private messenger and Ethereum dApp Browser all in one

### Wallet logo

![Status-logo](https://user-images.githubusercontent.com/35233054/176489936-a24f0755-a879-4def-ae57-f44a14ba1f1c.png)

### Background color for brand logo

#4360DF

### URL to the project

https://status.im/

### When did the wallet go live to users?

Status Mobile has been available in beta since 2017, with the 1.0 version released in Feb 2020.

### Does the wallet have an active development team?

Status has 50+ designers and developers working on it’s wallet and related consumer products. https://github.com/status-im/  Status has ranked in the top 3 of developer activity in Ethereum for the last 5 years in a row. (according to @santimentfeed)

### Is the wallet globally accessible?

Status is a self-custodial wallet. It doesn’t require users to enter any personal identifiable information, and has no KYC requirements or geographical limitations. The app is available for download as an APK file and through F-droid (so it is still available in regions where Google Play Store regional restrictions apply).

### Is the wallet available in multiple languages?

Status is available in: Arabic (left to right), Bengali, German, Greek, English, Spanish, Spanish (Latin America), Spanish (Argentina), Filipino, French, Hindi, Indonesian, Italian, Japanese, Korean, Malay, Dutch, Polish, Portuguese, Portuguese (Brazil), Russian, Turkish, Vietnamese, Chinese (Simplified), Chinese (Traditional, Taiwan) We run a community translation program. More on how to contribute here: https://translate.status.im/

### What social links are there for the project?

https://twitter.com/ethstatus
https://discord.gg/HGSAcAHGMA
https://www.reddit.com/r/statusim/
https://www.instagram.com/status.im/
https://dribbble.com/statusnetwork

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, Status is available for iOS and Android.

iOS 
- App store https://apps.apple.com/us/app/status-private-communication/id1178893006

Android 
- Play Store https://play.google.com/store/apps/details?id=im.status.ethereum
- F-Droid https://f-droid.org/packages/im.status.ethereum/
- APK download https://status.im/get/

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes, but it is currently in Alpha and not ready for usage yet. 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

Status Mobile has integrated Keycard hardware wallet https://keycard.tech/. Keycard signs transactions via NFC; In case of Status Mobile by tapping the card to the phone.

### Is the source code for the wallet fully open-source?

Yes, relevant repos: https://github.com/status-im/, https://github.com/status-im/status-react, https://github.com/status-im/status-go/, https://github.com/status-im/status-keycard/, https://github.com/status-im/go-waku

### What license is the wallet software released under?

The Status app is released under Mozilla Public License Version 2.0. For more information please see the license file: https://github.com/status-im/status-react/blob/develop/LICENSE.md

### Who holds the private keys?

Your life, your keys. The user who installs Status has sole control over access to their keys. Keys are stored locally on their device, or can optionally be stored on a Keycard instead. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Status wallet has been audited by Trail of Bits. Reports can be found here https://github.com/status-im/status-security#audits

Status recurringly runs a bounty program on https://hackerone.com/status_im 

Status has an in-house security team to ensure ongoing development meets security best practices and who proactively work to identify any possible threats.

### Has the wallet's smart contract code or security modules been audited?

Status supports externally owned accounts. Integrated smart contract, i.e. ENS subdomain stateofus.eth has been audited.

### Does the wallet have an internal security team?

Status’s internal security team runs threat modelling sessions with the dev teams, conducts audits, is responsible for internal security and keeps a proactive watch on any emerging possible threats.

### Any other security testing that should be noted?

Status has engaged with Certora for a 3rd party review of any smart contracts currently in development or recently deployed.

Additionally, Status conforms to security best practices and uses available security tooling (slither, echidna, mythx, etc) during its development. If risk is deemed appropriately high, then external reviews are engaged in commensurate to the associated risk. More info on this process can be read in this article: https://our.status.im/what-is-a-security-audit-when-you-should-get-one-and-how-to-prepare/

### Scam protection?

The wallet includes a signing phrase to protect users against phishing attacks. The app does not verify contracts.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Users can specify a RPC URL when adding a network by going to `Profile` > `Settings` > `Advanced` > `Network`

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Status has both a built-in dApp browser and the upcoming release of Status Mobile will add support for WalletConnect. Users can browse to any dApp entering the address (including ENS names if they resolve to a domainname) in the browser, or by searching the dap.ps dApp directory.  All relevant Ethereum standards have been implemented including EIP1193, EIP712, EIP1102, EIP1577, EIP191.

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

Not currently, but this is in development

### Does the wallet support multi-chain networks?

Not currently, but this is in development

### Does the wallet support Ethereum layer 2 networks?

Status Wallets supports basic functionality for L2 networks via manually changing an endpoint to point to an Ethereum compatible L2.  Full support for Ethereum layer 2 networks is under development and will be available in the future.

### Does the wallet allow the user to customize gas fees?

Users can customize gas fees. Gas amount limit, Per-gas tip limit and per-gas price limit can be edited before signing any transaction.

### Does the wallet support sending transactions to ENS addresses?

Yes. Status supports sending transactions to ENS names. This also includes stateofus.eth ENS subdomain names.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Status supports adding custom tokens and auto-scans for a predefined tokenlist.

### Does the wallet support EIP-1559 (type 2) transactions?

All Status wallet transactions are native type-2 EIP-1559 transactions. The wallet also supports message signing following EIP191.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, Status offers a way to buy crypto through several providers that Status has chosen to integrate. These providers accept Apple Pay, Google Pay, bank transfer, credit/debit card and several regional payment solutions.

### Does the wallet support withdrawals to fiat?

Status currently does not have any integrated ‘offramps’. dApps that offer withdrawal can be used through the dApp browser.

### Is the wallet a multi-signature wallet?

No, Status wallet does not yet allow for creating and adding multi-signature accounts.  However Gnosis Safe can be used in the dApp browser.

### Does the wallet support social recovery?

No, Status wallet does not yet support social recovery.

### Who can the ethereum.org team can contact regarding the wallet in future?

John_#7788

### Does the wallet have a dedicated support team?

Status does not have a dedicated support team. All externally reported GitHub issues are reviewed by our QA team and allocated to the respective teams.

### What educational resources/documentation do you provide to users?

Status provides an FAQ, https://status.im/faq/, as well as an in-app glossary. In addition we regularly post educational articles on our blog https://our.status.im/

### Does the wallet have any integrated tools not mentioned above?

Status combines a Wallet, Browser and Chat into a Web3 community experience. When you create a wallet, you also create an account to send end-to-end encrypted messages over Waku, the communication layer for Web3.

Other features include:
- Adding accounts as ‘watch-only’
- Scan transaction requests with QR code (EIP681)
- Manual edit of nonce (optionally enabled)
- Opt-in to viewing content provided by 3rd parties, such as NFT images
- Option to enable biometrics to unlock the application
- Option to block screenshots
- Ability to manage dApp permissions
- Opt-in to local notifications for transactions (Android only), avoiding (FCM) centralized servers https://our.status.im/status-app-notifications-on-android/
- Warning when attempting to send funds to a contract
- ‘Securely move your keys to Status Keycard (hardware wallet)’ 
- Mnemonic is removed from local database after backup seed phrase has been completed

**Comment by minimalsm** [comment]
Thanks @hesterbruikman.

Added here: https://github.com/ethereum/ethereum-org-website/pull/6457/commits/e534782b9ccee15762f6d4de78a03651a9072ddb

We will be working on a ranking algorithm that and having more features will mean higher list ranking, so please be sure to let us know of any changes (like swaps or the desktop browser) and we'll get those added too 👌
