### ISSUE TITLE
Suggest a wallet: Rainbow

### ISSUE THREAD

**Issue by christianbaroni** [ethereum/ethereum-org-website#6868]
### Wallet name

Rainbow

### Wallet description

Rainbow is a fun, simple, and secure way to get started with crypto and explore the new world of Ethereum. You can use Rainbow to purchase, manage, and display Ethereum-based assets and NFTs.

### Wallet logo

![rainbow](https://user-images.githubusercontent.com/7061887/176614795-c2a60fcb-3739-4cf2-ae6d-3f8fbdefa50e.svg)

### Background color for brand logo

#001A4D

### URL to the project

https://rainbow.me

### When did the wallet go live to users?

June 2019

### Does the wallet have an active development team?

Yes: https://github.com/rainbow-me/rainbow

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

Only English currently—more languages soon.

### What social links are there for the project?

https://twitter.com/rainbowdotme
https://www.youtube.com/channel/UCUHX5LBXXX-i46ibBf2Kx8Q

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, iOS and Android:

https://apps.apple.com/us/app/rainbow-ethereum-wallet/id1457119021
https://play.google.com/store/apps/details?id=me.rainbow

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

Yes: https://github.com/rainbow-me/rainbow

### What license is the wallet software released under?

GPL-3.0

### Who holds the private keys?

Rainbow is a non-custodial wallet—users have complete ownership of their private keys. If Rainbow were to disappear, users could take their keys and regain access to their funds using another Ethereum wallet.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Rainbow stores keys securely in the device keychain, requiring biometrics or the device passcode to access.

Rainbow's codebase has forever been open source and can be reviewed by anyone: https://github.com/rainbow-me/rainbow

We've taken several measures to harden the app against dependency attacks, including using [metro-plugin-anisotropic-transform](https://github.com/rainbow-me/metro-plugin-anisotropic-transform), a plugin we built for Metro Bundler, and [@lavamoat/allow-scripts](https://github.com/LavaMoat/LavaMoat/tree/main/packages/allow-scripts), built by MetaMask.

### Has the wallet's smart contract code or security modules been audited?

Rainbow's upcoming swap aggregator contract was audited by OpenZeppelin. We'll be publishing that audit alongside the launch of the feature.

### Does the wallet have an internal security team?

Yes

### Scam protection?

Most spam tokens are hidden by default via a curated list. Users can also hide tokens manually.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, via WalletConnect: https://learn.rainbow.me/connect-your-wallet-to-a-website-or-app

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

Yes: https://learn.rainbow.me/swaptrade-tokens-and-cryptocurrencies

### Does the wallet support multi-chain networks?

Yes, Ethereum and Polygon.

### Does the wallet support Ethereum layer 2 networks?

Yes, currently Arbitrum and Optimism: https://learn.rainbow.me/a-beginners-guide-to-layer-2-networks

### Does the wallet allow the user to customize gas fees?

Yes: https://learn.rainbow.me/what-are-ethereum-gastransaction-fees

### Does the wallet support sending transactions to ENS addresses?

Yes, Rainbow allows sending to ENS addresses and displays the ENS name associated with your wallet.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Tokens are automatically discovered, and Ethereum mainnet tokens can be searched for by name or contract address.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, Rainbow allows purchasing ETH and DAI via Apple Pay: https://learn.rainbow.me/get-some-ether-eth-to-spend-and-cover-gas-costs

### Does the wallet support withdrawals to fiat?

Not currently

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

https://twitter.com/rainbowdotme
https://twitter.com/mikedemarais

### Does the wallet have a dedicated support team?

Yes, users can email support@rainbow.me or DM Rainbow's Twitter account: https://twitter.com/rainbowdotme.

Response times of approximately one hour during US business hours.

### What educational resources/documentation do you provide to users?

Rainbow's Knowledge Base can be found here: https://learn.rainbow.me/

**Comment by minimalsm** [comment]
Thanks @christianbaroni,

Added here: https://github.com/ethereum/ethereum-org-website/pull/6457/commits/74c2351d34799d08514ba331c4e32c7d79a85102
