### ISSUE TITLE
Quoted Netflix energy use might be incorrect

### ISSUE THREAD

**Issue by seadowg** [ethereum/ethereum-org-website#6904]
It seems like the Netflix energy use figure quoted at https://ethereum.org/en/energy-consumption/ might be incorrect. Reading the linked article (https://www.carbonbrief.org/factcheck-what-is-the-carbon-footprint-of-streaming-video-on-netflix/), although it is a little unclear, it seems that the "94 TWh/yr" value referenced is referred to as "misleading" and "too high" as opposed to being used as an accurate measurement. 

I could of course have misread, but this quote appears to be misused to me.

**Comment by jmcook1186** [comment]
Hi, thanks for catching this - I have raised a PR to clarify the uncertainty as explained in that article more clearly. 
Cheers

**Comment by seadowg** [comment]
Closed by PR.
