### ISSUE TITLE
Add Tutorial: Hands on Web3

### ISSUE THREAD

**Issue by sixhobbits** [ethereum/ethereum-org-website#6907]
We'll consider [our content resources policy](https://ethereum.org/en/contributing/content-resources/) when reviewing the tutorial, so please take a look there first.

**Title**
Hands on Web3

**Tutorial description**

Online tutorials / an ebook that shows how to get started with solidity development on Replit.

**Tag your tutorial**

Solidity, Replit, Oracle, NFT, Escrow

**Publication**

https://handonweb3.com and https://docs.replit.com

**Skill level**

Beginner

**Hosted on Ethereum.org or hosted elsewhere?**

Elsewhere

**For tutorials to be hosted on Ethereum.org: Tutorial Content**

N/A

**For tutorials hosted elsewhere: URL to tutorial**

https://handsonweb3.com

**Comment by samajammin** [comment]
Hey, thanks for the PR!

At first glance, it seems like it'd be better/easier to directly link to the replit tutorials:
- https://docs.replit.com/tutorials/escrow-contract-with-solidity
- https://docs.replit.com/tutorials/build-a-robot-nft
- https://docs.replit.com/tutorials/build-a-robot-nft-p2
- https://docs.replit.com/tutorials/build-smart-contract-oracle

What do you think? Those seem to be the same content as PDF you link to.

**Comment by sixhobbits** [comment]
Yes that is fine. The ones on the landing page offer more options (pdf, epub, mobi, links to the versions we have on docs.replit.com) but we maintain both so up to you!

**Comment by wackerow** [comment]
Hey @sixhobbits Sorry this ran dry... 

> * https://docs.replit.com/tutorials/escrow-contract-with-solidity
> * https://docs.replit.com/tutorials/build-a-robot-nft
> * https://docs.replit.com/tutorials/build-a-robot-nft-p2
> * https://docs.replit.com/tutorials/build-smart-contract-oracle

Looks like these are still viable tutorials which I think would be a nice addition. I'll assign myself and get a PR up adding these. 

@all-contributors please add @sixhobbits for ideas
