### ISSUE TITLE
Aktionariat

### ISSUE THREAD

**Issue by MKEAktionariat** [ethereum/ethereum-org-website#6934]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

 Our wallet is already listed, we would also like to be listed as enterprise application live on mainnet in the category finance. The private keys are never transmitted outside the app. Standard web3 libraries are used to ensure security & integrity of the wallet file. On iOS the access to the wallet is protected by bio-metrics like face-ID. The keys are stored encrypted in the app and not stored in external storage.

**Is your dapp open source?**

 Yes, our smart contract is live to use by other developers on Github: https://github.com/aktionariat

**Can a user access the dapp without creating an account?**

 It is very easy to connect to the "broker-bot" with an ethereum wallet - see example: https://dillysocks.com/de-ch/share-sale/#Installation

**Are dapp funds non-custodial?**

 Yes, our wallet solution is self-custodial and a seed phrase needs to be memorized/saved by the user.

**Do you offer community support?**

 We offer a Telegram channel: https://t.me/+GWiWCIcIlVcyNmY0

**Describe any geographical restrictions on usage of your dapp**

 There are now restrictions at the moment.

**Dapp title**

Aktionariat

**Dapp description**

We provide Swiss companies with digital tools to create a market for their shares on their website.

**Dapp logo**

![Aktionariat Social Black](https://user-images.githubusercontent.com/102974634/177348494-99d5bdaf-d644-4854-8240-e388c0629aaa.png)

**Brand color**

#000000

**Comment by MKEAktionariat** [comment]
Hi @minimalsm , yes exactly. If there is anything else that I can help with, happy to do so.

**Comment by MKEAktionariat** [comment]
Hi Joshua,

Thanks for the message. Yes, exactly - if possible, we would like to be
listed in the category "finance".

Freundliche Grüsse / Kind regards

--

Michael Kenneally

Strategic Partnerships Manager





Aktionariat AG

CHE-453.438.437

Mobile: +41 79 526 95 08

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com/>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=0694579a-86e3-4a16-eeba-9b1e471f6ebb>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=0694579a-86e3-4a16-eeba-9b1e471f6ebb>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=0694579a-86e3-4a16-eeba-9b1e471f6ebb>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=0694579a-86e3-4a16-eeba-9b1e471f6ebb>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer.*

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=0694579a-86e3-4a16-eeba-9b1e471f6ebb>

**Comment by minimalsm** [comment]
>  Describe any geographical restrictions on usage of your dapp
> 
> There are now restrictions at the moment.

Given this is only available to Swiss companies, and we don't have any way of filtering this/providing a good experience to users (99%+ who aren't in Switzerland), we decided not to list this for now. Do let us know if this changes! Thanks again
