### ISSUE TITLE
Have all test ETH show as TETHxxxxx

### ISSUE THREAD

**Issue by Linda-OC** [ethereum/ethereum-org-website#6938]
**Is your feature request related to a problem? Please describe.**

One of the issues that I have seen in my work as a help desk agent involves people getting "paid" in Rinkeby or Ropsten ETH, or being sold ETH not knowing that they are receiving test ETH that have no value.  

**Describe the solution you'd like**
What I'd like to see is all test ETH be named TETHxxx.  So Ropsten ETH would be TETHropsten, Goerli would be TETHgoerli, etc. I've seen a few cases in Turkey where people are getting away with using test ETH for payment or selling test ETH.

**Describe alternatives you've considered**
Can't think of alternatives at the moment.

**Additional context**
n/a

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by sourabhagr** [comment]
Hi @Linda-OC, I am interested to help with this issue. Can you guide me on how can I get started - specifically which files should I look at?

**Comment by Linda-OC** [comment]
Hi @sourabhagr!  Thank you for responding!  To be honest, I'm not sure where to start either but I was hoping that some brilliant minds would gather around this feature request and help to make this happen.

**Comment by corwintines** [comment]
While I think the idea is nice, this isn't anything we can do on ethereum.org. Going to close this.
