### ISSUE TITLE
Requesting addition of 'Odia language'.

### ISSUE THREAD

**Issue by CBIKRAM** [ethereum/ethereum-org-website#699]
Odia language is a language of 4crore Indians. I wish it should be added to the translation project.

**Comment by samajammin** [comment]
@CBIKRAM thanks for the suggestion!

@sorumfactory please add Odia to CrowdIn so translators can get up & running. Thanks!

**Comment by sorumfactory** [comment]
Hello @CBIKRAM ! Thank you for your valuable suggestion. I just added the Odia language on Crowdin and created the Odia channel in our Slack workgroup as below. Please let me know if you have more suggestion :))

- Crowdin

https://crowdin.com/project/ethereumfoundation/or#

- Slack

https://join.slack.com/t/ethtranslation/shared_invite/enQtOTAxMDQzMjEzNzMzLTA0ODMxNzZmN2IzODkwYWQyY2ExMTMxMmIzMDM0ZTBhNDVmZTc4NDhiODYzM2I3OWM3ZTkxNjYzM2JkY2Q0NmY

**Comment by samajammin** [comment]
Thanks @sorumfactory! Closing this issue out. Please feel to free re-open if you have any questions @CBIKRAM.
