### ISSUE TITLE
Suggest a wallet - Infinity Wallet

### ISSUE THREAD

**Issue by InfinityWallet** [ethereum/ethereum-org-website#6991]
### Wallet name

Infinity Wallet 

### Wallet description

Infinity Wallet is the first desktop all-in-one wallet ecosystem focusing on providing a one-stop solution for seamless usability of DeFi, and access to the world of Web3 and DApps without needing to use an unintuitive browser extension wallet. Providing an enhanced user experience and a wide range of unique features and services as a curated experience, making Infinity Wallet the complete solution for all crypto users' needs.

### Wallet logo

![InfinityWallet-Logo](https://user-images.githubusercontent.com/64919828/178122904-14549ad9-1ab8-4365-a204-e4ca6266bdbb.svg)

### Background color for brand logo

#137dc7

### URL to the project

https://infinitywallet.io/

### When did the wallet go live to users?

November 2019

### Does the wallet have an active development team?

Yes, we are a full time team working 7 days a week.

### Is the wallet globally accessible?

Yes, we are globally accessible.

### Is the wallet available in multiple languages?

Yes, English and Spanish. With several additional languages coming soon.

### What social links are there for the project?

Twitter: https://twitter.com/InfinityWallet
Discord: https://discordapp.com/invite/SgNjKzF

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No, we are a desktop wallet. We plan to launch mobile in Q1 2023 on Android and iOS taking all our unique features and innovation and applying it to mobile to bring a unique premium user experience to mobile.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes, Infinity Wallet supports Windows, Mac and Linux. We are also the first Desktop Web3 wallet to provide access to DApps & Web3 directly within the wallet without needing to use a browser, providing a wide range of unique advantages to DApps & Users.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Who holds the private keys?

**Do users have access to their public and private keys?** Yes, users own and are the only ones that have access to their seed phrase and private keys.

**Does anyone else?** No, only the user their self has their seed phrase which can also be generated offline since its generated and encrypted locally.

 **If the company/project were to disappear, would users still be able to access their funds?** Yes, we follow the standards allowing users to recover their wallet with us or from us to another wallet.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We are not a static wallet and are constantly evolving with new features, this makes external audits unfeasible. We do however thoroughly internally audit/review and test every release, and have an ongoing bug bounty program. The wallet has been in live use by hundreds of thousands of users for years and we operate live support to ensure our users' experience is flawless.

### Has the wallet's smart contract code or security modules been audited?

We are not a smart contract wallet.

### Does the wallet have an internal security team?

Yes

### Scam protection?

Yes, with our feature called Browser-less DApps we have employed blacklisting of scam/phishing projects in attempts to further secure usage of DApps & Web3.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, more information can be found here: https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements/browser-less-dapps-and-web3

### Does the wallet support staking directly?

No, but its on the roadmap.

### Does the wallet support swaps directly?

Yes, swaps and bridging more information can be found here https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements/cross-chain-swaps-and-bridging

### Does the wallet support multi-chain networks?

Yes, we are actively collaborating with multiple chains and supporting their ecosystems https://docs.infinitywallet.io/infinity-wallet/supported-chains

### Does the wallet support Ethereum layer 2 networks?

Yes, we support Optimism with plans to integrate support for Arbitrum. 

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Integrating

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, a guide can be found here https://docs.infinitywallet.io/infinity-wallet/custom-token-importing#importing-a-custom-token

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

Yes

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

You can get in contact with a partner team at partner@infinitywallet.io

### Does the wallet have a dedicated support team?

Yes, we are one of very few wallets that provide live support (https://infinitywallet.io/?support=walletactive) to users. Additionally, users can also contact our support via email at support@infinitywallet.io

### What educational resources/documentation do you provide to users?

You can find some documentation here:
https://docs.infinitywallet.io/

You can also find a information deck here:
https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

Browser-less DApps & Web3:
https://youtu.be/5B2zaw56dEk

**Comment by corwintines** [comment]
This looks good to me to add.

**Comment by InfinityWallet** [comment]
> This looks good to me to add.

Appreciate adding us :) There is just a small issue with the logo used being different from the logo we provided and it is distorted.

Logo used that is wrong: https://raw.githubusercontent.com/ethereum/ethereum-org-website/b9593a5b4c756a9c04aa4b349ac4eb6e4c5e9a6d/src/assets/wallets/infinity_wallet.png

Here is the original in WEBP format if it could be updated https://we.tl/t-qD7hFd7m5r

Thanks
