### ISSUE TITLE
Suggest a wallet: Krystal

### ISSUE THREAD

**Issue by LoganDWH** [ethereum/ethereum-org-website#6999]
### Wallet name

Krystal

### Wallet description

Krystal is a multi-chain wallet to easily access popular DeFi services and manage your assets including NFTs

### Wallet logo

https://user-images.githubusercontent.com/108636782/177260879-ac39d202-0c2e-49c0-b171-1274add496ae.png

### Background color for brand logo

#1DE9B6

### URL to the project

https://krystal.app/

### When did the wallet go live to users?

01/04/2021, April, 2021

### Does the wallet have an active development team?

https://github.com/KYRDTeam

### Is the wallet globally accessible?

Countries that are banned from accessing Krystal services:  Democratic People's Republic of Korea, Iran, Albania, Barbados, Burkina Faso, Cambodia, Cayman Islands, Haiti, Jamaica, Malta, Morocco, Myanmar, Nicaragua, Panama, Senegal, South Sudan, Syria, Uganda, Yemen, Pakistan, Jordan, Mali, Tur

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

Twiiter: https://twitter.com/KrystalDefi
Telegram: https://t.me/KrystalDefi
Linkedin: https://www.linkedin.com/company/krystal-app/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Android: https://play.google.com/store/apps/details?id=com.kyrd.krystal
iOS: https://apps.apple.com/us/app/krystal-one-platform-all-defi/id1558105691

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No we do not have desktop app

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No, not yet

### Is it a hardware wallet?

No. We are a non-custodial software wallet.

### Is the source code for the wallet fully open-source?

Yes https://github.com/KYRDTeam/Krystal-iOS https://github.com/KYRDTeam/krystal-core

### What license is the wallet software released under?

iOS: https://github.com/KYRDTeam/Krystal-iOS/blob/main/LICENSE

### Who holds the private keys?

Krystal is non-custodial wallet. Users are in control of private keys

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We haven't done public audting for the mobile apps. However, we run internal audit carefully and we have been operating for more than 1 year without any security concern from our users

### Has the wallet's smart contract code or security modules been audited?

Yes. https://github.com/KYRDTeam/krystal-core/blob/main/audit/Krystal%20Audit%20-%20v1.1%20-%20Public%20Report.pdf

### Does the wallet have an internal security team?

Yes. We have an SRE team who take care of the security at the infra level

### Any other security testing that should be noted?

No

### Scam protection?

We have token tag to mark if some token is scam

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No. We are maintaining our own nodes for better user experience

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes. https://docs.krystal.app/features/dapp-browser

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

Yes. https://docs.krystal.app/features/swap

### Does the wallet support multi-chain networks?

Yes. https://docs.krystal.app/features/multiple-networks

### Does the wallet support Ethereum layer 2 networks?

Yes. https://docs.krystal.app/features/multiple-networks

### Does the wallet allow the user to customize gas fees?

Yes. https://docs.krystal.app/features/swap/settings 

### Does the wallet support sending transactions to ENS addresses?

 Not yet

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes. https://docs.krystal.app/features/importing-tokens

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, EIP 1559 is the default type of transaction

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes. https://docs.krystal.app/obtain-a-wallet/buying-tokens#buying-tokens-via-fiat-currencies

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

Twiiter: https://twitter.com/KrystalDefi
Telegram: https://t.me/KrystalDefi
jarvis@krystal.app

### Does the wallet have a dedicated support team?

Telegram: https://t.me/KrystalDefi
Support is fast as we have a dedicated Customer Support admin team

### What educational resources/documentation do you provide to users?

https://docs.krystal.app/features/transferring-tokens/multi-send](https://docs.krystal.app/

### Does the wallet have any integrated tools not mentioned above?

https://docs.krystal.app/features/transferring-tokens/multi-send

**Comment by corwintines** [comment]
Thanks for submitting this @LoganDWH! I am getting the sense this is more of a portfolio management and application portal than it is a wallet. It appears this is a project you sign in to with your wallet, rather than it being a wallet. I will continue to look into this a bit more before making a final call, just giving my initial impression.

**Comment by LoganDWH** [comment]
U should try our app on IOS or Android. Krystal is non-custodial wallet. Users are in control of private keys
Currently on the website, Users will need to import their wallet from 3rd parties, but krystal is building an extension for importing Krystal wallet

You can put us in the portfolio management and application portal, that's also our feature, we're ok with that.

**Comment by LoganDWH** [comment]
Hi Corwintines, Are there any new updates?

**Comment by corwintines** [comment]
Hey @LoganDWH. Following up on this, we talked about the best course of action here and settled on listing you on https://ethereum.org/en/dapps/ in the portfolios section. 

I have been trying to use dapps with the wallet and couldnt connect to anything. I should be able to use walletconnect for this right?

**Comment by LoganDWH** [comment]
Yes, i think we should list in the portfolios section, i think it's the best course

Could u do it please?

**Comment by LoganDWH** [comment]
@corwintines i saw the status as failed https://github.com/ethereum/ethereum-org-website/pull/7639
Currently there is no update on the website, do you need any help?

**Comment by corwintines** [comment]
@LoganDWH it was just a build fail from Vercel, but all good it has been merged.

**Comment by LoganDWH** [comment]
@corwintines 
Sorry to bother you
I have seen Krystal list on website, but now Logo is in rectangular format, I see all other projects are in square format

So I post the new logo here: https://drive.google.com/file/d/1FlER5IAsyfi7DuPiqYrqkC43NgJ3uOm-/view?usp=sharing
Please help me change Krystal's Logo

Thank you!

**Comment by LoganDWH** [comment]
@corwintines , Could you help us change the logo?
