### ISSUE TITLE
Aztec Network

### ISSUE THREAD

**Issue by YtzBeno** [ethereum/ethereum-org-website#7008]
Before suggesting a layer 2, make sure you've read [our listing policy](/contributing/adding-layer-2s/).

Only continue with the issue if your layer 2 meets the criteria listed there.

If it does, complete the following information which we need to accurately list the layer 2.

**Name**

Aztec network

**Logo**

https://camo.githubusercontent.com/d4184ccc66ca33e89889ec4becb5c6857b82f5836dc78344340d4ae9f7ca13cb/68747470733a2f2f692e696d6775722e636f6d2f427856487a44342e706e67

**Description**

Aztec Network is the first smart contract platform with privacy by default and secured by Ethereum.

**Website**

https://aztec.network/

**Developer documentation**

https://docs.aztec.network/

**L2Beat page**

https://l2beat.com/projects/aztec/

**Is the project open source?**

Yes, https://github.com/AztecProtocol

**What category of layer 2 is it? (Optimistic, ZK)**

ZK Rollup

**Does the layer 2 use Ethereum Mainnet for data availability?**

Verificatio  happens with zk proofs on Ethereum. Data availability is calldata on Ethereum; https://medium.com/aztec-protocol/aztec-zkrollup-layer-2-privacy-1978e90ee3b6

**Which bridges are used to onboard?**

Aztec shields your funds; https://zk.money/

**Which exchanges offer support for the project?**

none

**Link to dapp ecosystem (if applicable)**

https://zk.money/earn

**Token contract list (if applicable)**

None

**What date did this project go live?**

march 2021, with the launch of zk.money; https://finance.yahoo.com/news/aztec-launches-defi-privacy-bridge-140000040.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKQDrP4hcfk4XUsWPdSfaPBMfJw3c_VXaM5sGXHaQ_G8IZx4wsrfY17F4v_bjjvZfbUl6D63eZZ7Fvu_fLsY-MA6hP6FKgzRx5QgIgrV7_HciubFIQtogtGgJvSBJLytmAKWfc0wTzkYIjZ-UJE2d40z7ABPzUqi8eYTz1YwqQwz

**Is this project a fork? If yes, which project was forked?**

Not a fork

**What wallets support this layer 2?**

Walletconnect (so most major wallets e.g. Metamask)

**How can users and/or developers connect to this layer 2?**

Through the app; https://zk.money/

**Has this project undergone an external security audit and/or bug bounty?**

Yes, next to several internal audits it also has an 2M immunefi bug bounty and it got audited by some external audit firms; https://medium.com/aztec-protocol/aztec-raises-bug-bounty-to-2-million-for-critical-vulnerabilities-8e42df622659

**Has the project sustained its users over time?**

Especially with the recent launch of Aztec connect, Aztec has really grown in multiple aspects such as, but not limited to, TVL and name popularity; https://l2beat.com/projects/aztecconnect/

**Is the project being actively maintained?**

Yes, team is really active working on it.

**Is there a block explorer?**

Block explorer: https://explorer.aztec.network/

**Comment by samajammin** [comment]
Hey, thanks for raising this issue @YtzBeno!

I believe this is a duplicate of #6589 so closing this out in favor of that. Please feel free to add any additional info as a comment in that issue.
