### ISSUE TITLE
Spelling mistake and provided link to Sharding doesn't work.

### ISSUE THREAD

**Issue by naveen106** [ethereum/ethereum-org-website#7020]
**Describe the bug**
While I was reading this page (shown in the screenshot), I found a hyperlink to _sharding_ on the paragraph for **Scalibility**. The link gives 404 Not Found error in response.
Edit : I have created a Pull Request for spelling mistake, this issue here is for only the link not working correctly.

**Expected behavior**
The link should work or the page should tell **WE'RE WORKING ON IT**

**Screenshots**

![0322](https://user-images.githubusercontent.com/61573478/178497306-ae26d2c4-e486-4db6-907f-24ff6b0553e8.jpg)

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**
Android

**Comment by naveen106** [comment]
@minimalsm  I found out why it was happening, the link provided was not corrected, I've created a pull request which provides the correct link, please look into it.

**Comment by wackerow** [comment]
Appears to be resolved, thanks folks! closing out
