### ISSUE TITLE
Suggest a wallet - Exodus

### ISSUE THREAD

**Issue by kewde** [ethereum/ethereum-org-website#7021]
### Wallet name

Exodus

### Wallet description

Send, receive, and exchange Ethereum and 215+ cryptocurrencies with ease on the world's leading Desktop, Mobile and Hardware crypto wallets

### Wallet logo

![Exodus_symbol](https://user-images.githubusercontent.com/13770485/178499990-7943bfeb-025c-47ae-b8f3-c5a6cd6758a3.svg)

### Background color for brand logo

#1F2033

### URL to the project

https://exodus.com

### When did the wallet go live to users?

2015

### Does the wallet have an active development team?

Yes, new release every two weeks - exodus.com/releases/

### Is the wallet globally accessible?

Yes, except for Fiat onboarding and certain exchanges

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

* http://discord.gg/exodus
* https://github.com/ExodusMovement
* https://www.youtube.com/c/exodus
* https://www.reddit.com/r/ExodusWallet
* https://twitter.com/exodus_io
* https://slack-invite.exodus.com/
* https://www.facebook.com/exodus.io

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

* iOS
* Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

* Windows
* Mac
* Linux

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

* Chrome

### Is it a hardware wallet?

Desktop supports the Trezor hardware wallet.

### Who holds the private keys?

Completely self-custodial wallet.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

* Internal red team performs penetration tests on our infrastructure
* Shipped code only contains dependencies that have been audited by at least two security engineers, dev dependencies used to build the code get audited as well. This is performed by our own internal auditing team.
* [Bug bounties through HackerOne, up to $100,000 for stealing funds remotely](https://hackerone.com/exodus?type=team)

These are the items I have clearance to publicly publish, if there's any doubt about our security posture, I can request for a meeting between you and the security team and they can perhaps share the way we operate in a detail and share any non-public audit documents that they may have.

### Does the wallet have an internal security team?

Yes, every npm package is manually audited by two security engineers

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

https://support.exodus.com/article/2038-lido-dapp-on-ethereum https://support.exodus.com/article/2036-dydx-dapp-on-ethereum https://support.exodus.com/article/2037-aave-dapp-on-ethereum https://support.exodus.com/article/2035-yearn-finance-dapp-on-ethereum https://support.exodus.com/article/1663-nft-gallery

### Does the wallet support staking directly?

Not for ethereum.

### Does the wallet support swaps directly?

https://support.exodus.com/article/787-how-do-i-exchange-assets-in-exodus

### Does the wallet support multi-chain networks?

 Looking for this, will update with docs.

### Does the wallet support Ethereum layer 2 networks?

No, recovery isntructions at https://support.exodus.com/article/1709-arbitrum-network-troubleshooting

### Does the wallet allow the user to customize gas fees?

https://support.exodus.com/article/1517-ethereum-faqs-learn-more-about-eth#enable

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

https://support.exodus.com/article/1838-custom-tokens

### Does the wallet support EIP-1559 (type 2) transactions?

https://support.exodus.com/article/1622-ethereum-london-hard-fork-faqs

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

https://support.exodus.com/article/94-can-i-buy-crypto#buy

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

email: support@exodus.com
twitter: https://twitter.com/exodus_io/

We're more than happy to set up a shared slack channel as well with your team for a direct line of contact.

### Does the wallet have a dedicated support team?

You will typically receive a first response within 10 minutes. Exodus has over a hundred customer support engineers.

### What educational resources/documentation do you provide to users?

https://support.exodus.com/

**Comment by corwintines** [comment]
This looks good to me to bring in
