### ISSUE TITLE
Inclusion of ethereumprice.org

### ISSUE THREAD

**Issue by 0xEther** [ethereum/ethereum-org-website#705]
**Is your feature request related to a problem? Please describe.**
While price fluctuations are - for the most part - a distraction from the developments on Ethereum, I feel it's important to have a resource of some kind referenced on the site.

**Describe the solution you'd like**
I'm suggesting the inclusion of ethereumprice.org on the /learn/ page alongside other community resources.

**Additional context**
Full disclosure, I am the owner of ethereumprice.org and have operated the site with no advertising since 2016. Over the years, the website has fallen down Google Search rankings and made way for ad-heavy alternatives like coindesk.com, coinmarketcap.com and recently, https://markets.businessinsider.com/currencies/eth-usd who do not share the same passion for the Ethereum ecosystem.

By including ethereumprice.org we can recommend a clean, Ethereum-advocating data source for all price information. The website also provides educational/guide content for Ethereum more broadly as well as a weekly non-monetised newsletter.

**Comment by samajammin** [comment]
Closing this, please see #706 for context.
