### ISSUE TITLE
Suggest a wallet - Sequence Wallet

### ISSUE THREAD

**Issue by arielman87** [ethereum/ethereum-org-website#7056]
### Wallet name

Sequence

### Wallet description

[Sequence](https://sequence.info/) is a self-custodial smart contract wallet built for a network of Ethereum chains. Already supporting Ethereum, Polygon, BNB Chain, and with integrations for Arbitrum, Optimism, Fantom, Avalanche and other EVM-compatible networks coming soon. 
Due to the smart contract nature of Sequence, transaction fees can be abstracted away from users. This allows users to pay the transaction fees in multiple currencies or even have their fees paid by a third party. In addition, users don't have to worry about gas limits or gas price since our relayer system automatically reprices transactions to ensure prompt execution

### Wallet logo

![SequenceIconSquare](https://user-images.githubusercontent.com/97196974/167196538-fb2aa5cc-659b-4a16-bfd5-a2c1f6c98dd4.png)
<img width="1890" alt="SequenceHorizontalWhite" src="https://user-images.githubusercontent.com/97196974/167196637-9a8c513d-5f69-48d3-b5a5-41b285c0d2ad.png">

### Background color for brand logo

#000000

### URL to the project

https://www.sequence.xyz

### When did the wallet go live to users?

November 4th, 2021

### Does the wallet have an active development team?

Yes, you can see the regular updates we are making to the SDK https://github.com/0xsequence/sequence.js 

### Is the wallet globally accessible?

In order to comply with regulations and policies mandated by Canada, USA and other global jurisdictions, Sequence has limited access in certain US States, and has no access in specific countries. For a complete list, see here https://support.sequence.xyz/en/articles/6220364-sequence-list-of-restricted-regions

### Is the wallet available in multiple languages?

English. You can have it translated with the Chrome translator extension. As Sequence is a browser wallet, the extension will translate as though it were a normal website.

### What social links are there for the project?

**Discord:** https://discord.gg/sequence

**Twitter:** https://twitter.com/0xsequence

**Tiktok:** https://www.tiktok.com/@0xsequence

**Reddit:** https://www.reddit.com/r/0xSequence/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Not at the moment. Sequence is currently a web browser wallet. We will have iOS and Android apps in the future.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No, it's a web browser wallet at the moment.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, Chrome extension.
https://chrome.google.com/webstore/detail/sequence-wallet/ocmccklecaalljlflmclidjeclpcpdim

### Is it a hardware wallet?

No.

### Is the source code for the wallet fully open-source?

The SDK and the smart contracts are open sourced:   - SDK :https://github.com/0xsequence/sequence.js  - Contracts : https://github.com/0xsequence/wallet-contracts

### What license is the wallet software released under?

No License

### Who holds the private keys?

Sequence Wallets created with social logins are currently secured using three private keys: a Session keys, a Guard key and a Torus key. The Session key and Torus key are both generated for the first time when a user creates their Sequence Wallet via social login or email authentication.

At least two of the three keys are needed to unlock an account. This means that if one of the three keys is lost or compromised, a user can use the two remaining keys to replace the lost/compromised key. For example, if a user lost their device containing their Session Key, they can unlock their Sequence Wallet account by email or social login via the Torus key combined with the Guard key. Once done, another session key is auto-generated and the user is back in their account with all 3 keys accessible again.
From https://docs.sequence.build/private-keys/social-login-wallets/

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We performed 3 separate audits (https://docs.sequence.build/wallet-contracts/contract-audits) for the contracts and they are open-sourced. Users are also able to remove and add more keys to their wallet to better manage which devices have access to their wallet.

Our multi-signature key architecture means you don’t have to worry about losing your crypto to a key logger or seed phrase snatcher. 

With Sequence, multiple independent keys are required to sign in or send a transaction. You can modify or remove these keys, and assign varying signing power to each — giving you an added layer of security and peace of mind.
Our multi-key design also means you can recover your account, if you happen to lose one of your keys. Simply combine your remaining keys to auto-generate a replacement for your lost key. This is especially helpful if you want to remove a previously signed-in device from your account, which you may have lost in a taxi. Please see our documentation for more info: https://docs.sequence.xyz/

### Has the wallet's smart contract code or security modules been audited?

Yes. See here https://docs.sequence.build/wallet-contracts/contract-audits

### Does the wallet have an internal security team?

Yes. We have one dedicated security engineer, in addition to multiple other team members who contribute to security. Beyond our internal team, we leverage security audit firms like Quantstamp and ConsenSys Diligence.

### Any other security testing that should be noted?

We have a few thousands of automated tests

### Scam protection?

Yes, it warns when interacting with unknown contracts.

### Does the wallet support connecting to a hardware wallet?

Not at the moment, but we intend to add hardware wallet support.

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No, Sequence round-robins between 4 different node providers to ensure availability

### Does the wallet support viewing and interacting with NFTs?

Yes. Sequence delivers first-class NFT support, complete with artwork/video and metadata. Sequence auto-indexes every token on any EVM-compatible chain, so that NFTs display in user wallets in the way developers would hope for. Sequence has gallery viewing and allows for batching transactions as well.

### Does the wallet support connecting to Ethereum applications?

Yes. Via WalletConnet, and via deeper integrations with many dapps. 
https://docs.sequence.xyz/build-with-sequence/connect-wallet#connecting-via-walletconnect

### Does the wallet support staking directly?

Not at the moment, but we are considering adding this functionality.

### Does the wallet support swaps directly?

Yes, https://support.sequence.xyz/en/articles/6223539-can-i-exchange-my-tokens 

### Does the wallet support multi-chain networks?

Yes https://docs.sequence.xyz/introduction/multi-chain-support

### Does the wallet support Ethereum layer 2 networks?

Arbitrum and Optimism are already indexed https://status.sequence.info/ but enabling the support for users is in development. https://docs.sequence.xyz/introduction/multi-chain-support. 

### Does the wallet allow the user to customize gas fees?

No, gas is automatically priced and repriced by our relayer service and abstracted away from users

### Does the wallet support sending transactions to ENS addresses?

Yes https://support.sequence.xyz/en/articles/6383987-how-to-use-ens-to-transfer-crypto-and-collectibles 

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

It automatically queries and displays all ERC-20, ERC-721 and ERC-1155 tokens.

### Does the wallet support EIP-1559 (type 2) transactions?

Gas-related logic is abstracted away from the users and handled by our server-side relayer.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes https://docs.sequence.xyz/build-with-sequence/connect-wallet#wallet-login-and-connect-options

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

Yes, see https://docs.sequence.xyz/private-keys/key-management

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

twitter.com/PhABCD

### Does the wallet have a dedicated support team?

Yes, the support chat is available to submit tickets
https://support.sequence.xyz/

### What educational resources/documentation do you provide to users?

The knowledge base is constantly being updated and enriched
https://support.sequence.xyz/

### Does the wallet have any integrated tools not mentioned above?

Described in https://docs.sequence.xyz/

1. 👤 Social/email login. Easily sign in via email, Google, Facebook or other socials. No blockchain knowledge required
2. 📱 Browser, app & extension. Users can access their sequence wallet via https://sequence.app/ or the Sequence browser extension. iOS and Android apps are coming soon.
3. 🔑 Non-custodial. With Sequence, users are in full control of their wallet with no third party being able to access these funds other than them.
4. ⛽ Fee Abstraction. Users can pay transaction fees in various currencies, not only the native currency of the network used.
5. 🤖 Transaction Relaying. Users don't need to worry about gas prices, gas limits or stuck transactions. Developers can sponsor transactions so that their users don't need to pay gas at all.
6. 🎁 Batch Transactions. Users can bundle multiple transactions to be sent in a single native transaction. Users can send different types of token standards (e.g. ERC-20, 721, 1155) all in one transaction, saving time, gas, and reducing carbon footprint.
7. 🖥 Sequence can embed on any screen, game, or dapp, which means users don't need to install anything. This enables a seamless onboarding experience to web3.

**Comment by samajammin** [comment]
Hey - thanks for submitting this info!

Looks to be mostly a duplicate of #7055 - which issue would you like us to review?

**Comment by arielman87** [comment]
> Hey - thanks for submitting this info!
> 
> Looks to be mostly a duplicate of #7055 - which issue would you like us to review?

Yeah, you're right. It's my bad... https://github.com/ethereum/ethereum-org-website/issues/7055 it's the old one, it doesn't have all the answers.

For the reviewers: This is the correct one: https://github.com/ethereum/ethereum-org-website/issues/7056

**Comment by corwintines** [comment]
This looks good to me. Ill create a PR to add this information in, and let you know if I have any questions @arielman87 :) Thanks for suggesting the Sequence wallet!

**Comment by arielman87** [comment]
> This looks good to me. Ill create a PR to add this information in, and let you know if I have any questions @arielman87 :) Thanks for suggesting the Sequence wallet!

@corwintines I can't find the PR for this listing. Do you know when it will get listed ?

**Comment by corwintines** [comment]
Hey @arielman87, just making a PR for this now. Sorry for the delay.

**Comment by corwintines** [comment]
Created a PR for this https://github.com/ethereum/ethereum-org-website/pull/7523

**Comment by minimalsm** [comment]
Closed in #7523
