### ISSUE TITLE
Scrollbar on .sidebar on /community

### ISSUE THREAD

**Issue by andrewjcohen** [ethereum/ethereum-org-website#710]
**Describe the bug**
Scrollbar showing on .sidebar on the /community page. This is due to overflow-y: scroll; Should be set to overflow-y: auto;

**To Reproduce**
1. Go to https://ethereum.org/community/

**Expected behavior**
No scrollbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/1210802/73106488-c4824e00-3eb8-11ea-8bf5-54c5b21d05ef.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Brave
 - Version: 1.2.43

**Comment by samajammin** [comment]
Thanks, @andrewjcohen! I wasn't able to reproduce this issue but I made the update in #712. Please re-open this issue if it doesn't appear to be fixed.
