### ISSUE TITLE
Text is being overflow:hidden in the main column of community

### ISSUE THREAD

**Issue by andrewjcohen** [ethereum/ethereum-org-website#711]
**Describe the bug**
Text is being overflow:hidden in the main column of community when the browser is right before the breakpoint.

**To Reproduce**
1. Go to https://ethereum.org/community/
2. Size your browser down a tad
3. Look at a long line of text.

**Expected behavior**
Copy should move down earlier with 24px padding on the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/1210802/73106552-e5e33a00-3eb8-11ea-8ea3-640c6086f6e5.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Brave
 - Version 1.2.43

**Comment by samajammin** [comment]
Thanks for reporting this!

@all-contributors please add @andrewjcohen for bug reports.
