### ISSUE TITLE
Optimization - Reduce built langs in dev builds

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#7124]
In Gatsby Cloud, we have a site that is called `ethereum-org-website-dev` which builds all the PRs that have `dev` as the target branch to merge. We are building those PRs to have Preview Deploys in order to test them before we merge them into `master`.

Currently, in each one of those builds we are building the entire site. That means that we are building 46 languages, which means building ~9k pages **for each PR**. That seems unnecessary.

The idea is to reduce the number of languages that we build in dev to get faster builds so that we can improve our **productivity**. The downside is that we need to find a way to test all the languages before merging the PRs into master.

We must find a solution or define a new process to deal with that problem.

**Proposal 1:**

An optimal solution would be to have different ENV vars per branch but is not supported by Gatsby Cloud at the moment. [https://gatsby.canny.io/gatsby-cloud/p/add-a-third-context-of-environment-variables-for-pr-builds](https://gatsby.canny.io/gatsby-cloud/p/add-a-third-context-of-environment-variables-for-pr-builds) (give it an upvote 👍 pls).

**Proposal 2:**

- Reduce languages built on `ethereum-org-website-dev` to the top 3 or 5 most used langs
- Create a new branch e.g. `all-langs` from `dev`
- Create a new GC site called `ethereum-org-website-all-langs` that:
    - Builds all the languages
    - Builds PRs that target the `all-langs` branch
- Keep the `all-langs` branch updated (not sure how to do this automatically)

Any new proposal is welcomed :)

**Comment by samajammin** [comment]
> We are building those PRs to have Preview Deploys in order to test them before we merge them into master.

You mean before we merge them into `dev`?

**Comment by samajammin** [comment]
> Reduce languages built on ethereum-org-website-dev to the top 3 or 5 most used langs

Which languages should we use? Perhaps a mix of:
- Most popular (e.g. `zh`, `ru`, `es`)
- A RTL language (e.g. `fa` or `ar`)
- ...any other ideas, cc @lukassim?

**Comment by samajammin** [comment]
> Keep the all-langs branch updated (not sure how to do this automatically)

One approach might be to create a GH action that will keep `all-langs` in sync with `dev`, e.g. this `sync-branches` action:
- https://github.com/marketplace/actions/sync-branches
- https://bharathvaj.me/blog/keep-two-branches-in-sync

**Comment by wackerow** [comment]
We have since switched off of Gatsby Cloud, but the root issue still here persists (building 60+ copies of the site for all the languages, for each PR preview).

@pettinarip Still something you're interested in?

Removed the stale tag, going to flag as help wanted since personally I think this would still be helpful to have a way to do quick builds during development. This would also help the current issue we're having with a significant amount of build minutes being used on Netlify.

**Comment by wackerow** [comment]
cc: @pettinarip bump on above! =)

**Comment by corwintines** [comment]
This could still be useful for the translation import process, especially with the automated process we have now. 

For example. We could build en, vi for Vietnamese imports. 

This would help reduce the risk of timeout errors.

**Comment by pettinarip** [comment]
@wackerow thanks for the ping and sorry for the delay on this.

Yes, super interested in the goal behind it, which is to optimize the builds on the preview deploys and/or dev. Most of the time it doesn't make sense to build the whole site.

I'll close & create a new issue with NextJS & Netlify in place since the approach might be pretty different now.
