### ISSUE TITLE
Wrong ERC4626 interface

### ISSUE THREAD

**Issue by bahurum** [ethereum/ethereum-org-website#7132]
The interface for ERC-4626 token standard here 
https://ethereum.org/en/developers/docs/standards/tokens/erc-4626/ 
is different from the description in [EIP-4626](https://eips.ethereum.org/EIPS/eip-4626) or from the [Solmate implementation](https://github.com/transmissions11/solmate/blob/main/src/mixins/ERC4626.sol) (written by the authors of the EIP). Arguments are either missing or in wrong order for several functions.

**Comment by vdusart** [comment]
Can you assign this to me please

**Comment by pettinarip** [comment]
Thanks @bahurum for reporting this issue. Assigned @vdusart, thanks for fixing it!

**Comment by minimalsm** [comment]
Closed by #7204
