### ISSUE TITLE
Add language resources: Polish Web3 tutorials, general blockchain tech articles

### ISSUE THREAD

**Issue by mpalczynski** [ethereum/ethereum-org-website#7140]
We'll consider [our content resources policy](https://ethereum.org/en/contributing/content-resources/) when reviewing the tutorial, so please take a look there first.

**Title**
Blockchain explained in the polish language.

**Tutorial description**
Online tutorials in the form of articles. All coding materials use the Ethereum tech stack.

**Tag your tutorial**
Solidity, React, Hardhat, NFT, Oracle

**Publication**
https://chainkraft.com

Example tutorials:
https://chainkraft.com/pl/kurs-web3-smart-kontrakt
https://chainkraft.com/pl/kurs-web3-frontend-w-react

**Skill level**
Beginner

**Hosted on Ethereum.org or hosted elsewhere?**
Elsewhere

**For tutorials to be hosted on Ethereum.org: Tutorial Content**
N/A

**For tutorials hosted elsewhere: URL to tutorial**
https://chainkraft.com

**Comment by mpalczynski** [comment]
Please assign the issue to me if the content is appropriate.

**Comment by lukassim** [comment]
Closing this issue as none of the tutorials are accessible and all links to the tutorials results in a 404 error

**Comment by rakpawel** [comment]
Sorry guys, we've had a wordpress issue. Articles are available again.
