### ISSUE TITLE
Blockchain developer marketplace Freeflow

### ISSUE THREAD

**Issue by berkserbet** [ethereum/ethereum-org-website#7145]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

Freeflow

**Product description:**

Freeflow is marketplace that helps blockchain developers find freelance work in web3 projects.

**How long has it been around?**

9 months

**Where do you think it should go?**

I think it under the `Developers` section in `How Can I get Involved?`. [Link](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/community/get-involved/index.md#developers--developers)

**GitHub URL**

We don't have a public repo since we operate a marketplace.

**Docs URL**

[Freeflow Website](https://www.freeflow.dev/)

**Is the product open source?**

It is not

**Additional context**

Freeflow has supported over 100 developers contributing to over 300 web3 projects!

Here is some text that can be used for the change:
```- [Freeflow](https://freeflow.dev/) - join the web3 developer marketplace to find freelance work in web3 projects```

**Comment by corwintines** [comment]
Thanks @berkserbet 

This seems like an interesting idea, but I don't think it really has a place on this page.
