### ISSUE TITLE
Source homepage code examples from data files

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7150]
**Is your feature request related to a problem? Please describe.**

Refactor request...

Currently we display code examples on the homepage that are stored as large strings in the component:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/index.tsx#L603

This is pretty gnarly 😅😬 

**Describe the solution you'd like**

We also store these code examples in data files which at least makes them easy to format:
- https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/CreateWallet.js
- https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/SimpleDomainRegistry.sol
- https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/SimpleToken.sol
- https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/SimpleWallet.sol

It'd be great if we could pull the content for these examples directly from these data files 😄 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vdusart** [comment]
Hey @samajammin, can I do this one please ?

**Comment by samajammin** [comment]
Sure thing, thanks for volunteering @vdusart! Assigning to you 👍

**Comment by samajammin** [comment]
Appreciate all your help with the TS migration BTW! ❤️

**Comment by pettinarip** [comment]
Issue solved by @vdusart. Thanks!
