### ISSUE TITLE
Gatsby Cloud env not displaying our custom 404 page

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#7156]
**Describe the bug**

With the fixes of redirects on Netlify added in #7135 and #7137, our preview env (Gatsby Cloud env) is not displaying our custom 404 pages.
![image](https://user-images.githubusercontent.com/468158/180267728-0a28a5d6-04c8-423a-9402-1700a0f1236f.png)

**To Reproduce**

1. Go to https://ethereumorgwebsitedev01.gtsb.io/nonexistingpage
2. You will see the default 404 page from GC server. Not our custom page.

**Expected behavior**

See our custom 404 page as in prod (Netlify server).

**Additional context**

Check the redirect file output under `public/_redirects.json` (which is the one used by Gatsby Cloud), it is setting a bunch of redirects under "rewrites", including the 404 declarations without specifying the status code we want (404).

```
{
  "fromPath": "/en/*",
  "toPath": "/en/404/"
},
{
  "fromPath": "/es/*",
  "toPath": "/es/404/"
}
```
I think we should investigate more on how https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/ is creating that file.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by SNikhill** [comment]
@pettinarip 

Referring to the documentation looks like that, we need to explicitly define and create a redirect with a status code.
![image](https://user-images.githubusercontent.com/51415616/180272765-cf1c3beb-383d-4a35-82f8-124fff1848cd.png)

- `createRedirect` hook: https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/#redirects

**Comment by pettinarip** [comment]
You are correct @SNikhill. We are doing that [here](https://github.com/ethereum/ethereum-org-website/blob/dev/gatsby-node.ts#L431), so for some reason that code is not ending into the `_redirects.json` file.

**Comment by SNikhill** [comment]
Looks fixed now.
![image](https://user-images.githubusercontent.com/51415616/181268103-b499dc01-4ba9-40f9-bb42-cefc44d09f18.png)

**Comment by pettinarip** [comment]
Ohh thats awesome! so...we were doing it fine, it was a GC issue. Cool. Thanks for letting us know about that @SNikhill 💪🏼
