### ISSUE TITLE
Opcode table horizontal scrolling

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#7163]
**Describe the bug**

The Opcode table on this page https://ethereum.org/en/developers/docs/evm/opcodes is hard to use because of the horizontal scroll functionality. The table has a large number of rows that do not fit into a single page view - to view all the rows vertical scrolling is required. There are also more columns than can fit into a single page view. 

To access out-of-view columns it is necessary to scroll right, which currently requires scrolling to the bottom of the table. However, this puts the row/opcode number out of view, so that with the desired column in view, the row identifier is now obscured. 

This makes it very awkward to access information for specific opcodes using the table.

**To Reproduce**

1.Go to https://ethereum.org/en/developers/docs/evm/opcodes
2. Make an arbitrary choice of row, e.g. 44 - the DIFFICULTY Opcode
3. Try to view content in columns currently out of view - this requires scrolling rightwards at the bottom of the page
4. Try to find the 44 DIFFICULTY Opcode with the desired column still in view.

**Expected behavior**

Either enable arrow-key/click-and-drag horizontal scrolling or put all columns in view by default.

**Screenshots**

Screencast of the problem here: https://discordapp.com/channels/714888181740339261/999252773457633290/999634096839983275

**Desktop (please complete the following information):**

- OS: Linux (Ubunto 20.04)
- Browser: Brave
- Version: 1.40.107

**Additional context**

Issue seems to be desktop specific - on Android the issue is fixed by right-swiping without needing to scroll vertically to the scroll-bar.

**Comment by vdusart** [comment]
Hey @jmcook1186,
you can do `[Shift] + scroll` to do an horizontal scroll.

We should perhaps add a small note on the top of the table to explain it.
Something like :

`Note: In order to see all the content, you can do an horizontal scroll by using [Shift] + scroll`.

I'm not sure everything can be in the view by default it's too large.

Tell me what you think about it :smile:

**Comment by SebastianSupreme** [comment]
@vdusart Great idea if you ask me 👍

**Comment by ArianHamdi** [comment]
<img width="1608" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/59548833/df98cc21-cf3e-4a75-953d-6f790677df14">

The horizontal scrollbar breaks the layout.
