### ISSUE TITLE
Veramo - A decentralized Identity Framework

### ISSUE THREAD

**Issue by emmanuellar** [ethereum/ethereum-org-website#7180]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name: Veramo**

**Product description:** 
Veramo is a JavaScript framework that makes it easy for anyone to use cryptographically verifiable data in their applications. It was designed to make it easy for developers who want to use DIDs, verifiable credentials, and data-centric protocols to bring next-generation features to their users. Find out more: veramo.io

**How long has it been around?**
Was previously a part of Uport (2015). Became Veramo in March 2021

**Where do you think it should go?**
https://ethereum.org/en/developers/docs/frameworks/ and https://ethereum.org/en/decentralized-identity/

**GitHub URL**
https://github.com/uport-project/veramo

**Docs URL**
https://veramo.io/docs/basics/introduction

**Is the product open source?**
YES

**Comment by minimalsm** [comment]
Hey @emmanuellar, thanks for raising this issue. 

I agree with adding Veramo into our developer docs. Not sure if frameworks is the right page, as that page is more focused on dapp frameworks. [Javascript](https://ethereum.org/en/developers/docs/programming-languages/javascript/) seems like it might be a good fit?

Personally, I don't think we should add it to [the decentralized identity page](https://ethereum.org/en/decentralized-identity/) as this page should not be targeted toward developer implementations but users who want to learn about and use decentralized identity services (ENS, SIWE).

**Comment by emmanuellar** [comment]
Thank you @minimalsm 
Where do you suggest I add it? I thought about having it on the [decentralised identity page](https://ethereum.org/en/decentralized-identity/) since Veramo is playing in the field and is currently being used by some projects working on DIDs. Perhaps we can list it on the community section?
