### ISSUE TITLE
Can you add the transaction's trace type introduction?

### ISSUE THREAD

**Issue by scqsu** [ethereum/ethereum-org-website#7188]
I found the transaction's trace type like call, create, suicide, reward, genesis, daofork.

I don't konw what's the different of the above type?

Can you add a introduction page for the trace type?

**Comment by jmcook1186** [comment]
You are looking at the EVM opcodes invoked during some transaction. The individual opcodes are already explained on ethereum.org here: https://ethereum.org/en/developers/docs/evm/opcodes. 

The RPC endpoints for various traces are probably a bit low level for ethereum.org for now, but you can find the information in the docs for individual clients.

**Comment by wackerow** [comment]
@scqsu Thanks for this post! Going to close this out per the above reply, but please feel free to reopen if you feel your intent wasn't met.
