### ISSUE TITLE
Replace "Build" with "Developers"

### ISSUE THREAD

**Issue by jjmstark** [ethereum/ethereum-org-website#72]
This issue is based off a conversation with Scott Lewis on twitter, [where he made the following point](https://twitter.com/scott_lew_is/status/1128108479292612608):

>for a developer to realize the developer portal exists they must also know that ethereum nomenclature for a developer is a builder, but IRL a builder is someone who builds houses. given the devs visiting http://ethereum.org  are new to ethereum, this is suboptimal.

My steel man to expand on this is:
- ethereum.org - especially the landing page - should lean towards optimizing for people who are new to Ethereum. Someone who is already part of the community is less likely to rely on the landing page as an index of the site, because they will already know to go to ethereum.org/build for technical resources
- "Build" is Ethereum-community specific language that could be confusing to a developer who is looking for a "Docs" or "Developer" subpage. The websites for Rust, React, Python, Firebase, and Ember.js do not use "Build" as a top level category. 

What do others think? cc @maurelian

**Comment by maurelian** [comment]
+1, the reasoning make sense to me.

I'd also suggest having ethereum.org/build redirect to ethereum.org/developers.

**Comment by sneg55** [comment]
+1, for common terminology

**Comment by Aniket-Engg** [comment]
Agreed!
Just a minor change, by following the consistency, It should be 'Develop' instead of 'Developers'

**Comment by jjmstark** [comment]
@Aniket-Engg I don't think we should be wedded to the "use a verb for the subpage names", since we've already broken it by using "Beginners". I think people will expect to see `Developers` rather than `Develop`.
