### ISSUE TITLE
Amharic (አማርኛ) language support

### ISSUE THREAD

**Issue by mm319** [ethereum/ethereum-org-website#720]
**Is your feature request related to a problem? Please describe.**

Please add a link to Amharic (አማርኛ), Ethiopia's national language,  on the Ethereum.org Translation page.

Ethiopia has the second largest population in Africa, with over 100m people and around 70% the population being under 30.

Let's tap into the potential.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samajammin** [comment]
@mm319 thanks for the suggestion!

@sorumfactory please add Amharic to CrowdIn so translators can get up & running. Thanks!

**Comment by sorumfactory** [comment]
@mm319 Absolutely. I added Amharic (አማርኛ) on Crowdin. Thank you for your suggestion. We're very excited to embrace the Ethiopian community! :)

**Comment by samajammin** [comment]
Thanks @sorumfactory! Closing this issue out. Please feel to free re-open if you have any questions @mm319.
