### ISSUE TITLE
Suggest a wallet - Rabby Wallet

### ISSUE THREAD

**Issue by chenko515** [ethereum/ethereum-org-website#7209]
### Wallet name

Rabby Wallet

### Wallet description

Rabby Wallet is the game-changing wallet for Ethereum and all EVM chains.

### Wallet logo

![avatar](https://user-images.githubusercontent.com/3264861/181232790-afca4d43-0340-40d9-b0e9-03b341600396.png)

# media pack
https://github.com/RabbyHub/logo

### Background color for brand logo

FFFFFF

### URL to the project

https://rabby.io

### When did the wallet go live to users?

2021-July-27

### Does the wallet have an active development team?

https://github.com/RabbyHub/Rabby

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

https://twitter.com/Rabby_io
https://discord.com/invite/seFBCWmUre

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes. 
Chrome.

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

https://github.com/RabbyHub/Rabby

### What license is the wallet software released under?

MIT

### Who holds the private keys?

Rabby Wallet is a non-custodial wallet, users have complete ownership of their private keys.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Rabby Wallet re-uses the same encryption module as MetaMask to protect user's private keys/mnemonic words.
Rabby Wallet will parse each transaction and explictly tell the user what is the transaction exactly about.
Rabby Wallet has a risk-scan engine that scans transactions for security risks.
Rabby Wallet's source code is open sourced and regularly audited by security audit agencies.

More:
https://medium.com/@rabby_io/rabby-release-announcement-564406988e2b

### Has the wallet's smart contract code or security modules been audited?

https://github.com/RabbyHub/Rabby/blob/develop/docs/SlowMist%20Audit%20Report%20-%20Rabby%20browser%20extension%20wallet-2022.03.18.pdf

### Does the wallet have an internal security team?

Yes.

### Any other security testing that should be noted?

No

### Scam protection?

Yes. Alerts when:

The recipient address is a token contract address.
The recipient address does NOT exist on the current chain.
You've NEVER transferred to this address before.
The recipient address is a contract address but NOT multi-signed.
The recipient address is a Gnosis address that exists on ANOTHER chain.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

Yes, Rabby has supported 34 EVM chains so far.

### Does the wallet support Ethereum layer 2 networks?

Yes, Rabby Wallet has supported Arbitrum, Optimism, Boba and Aurora so far.

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

No, because ENS supports zero-width character which is risky to support.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, support both importing and automatically querying ERC-20 tokens for all 34 EVM chains

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No, but user can connect Gnosis Safe with Dapp via Rabby: https://www.youtube.com/watch?v=u9-ooAIPUQI

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

https://t.me/chuck_2140
https://twitter.com/Rabby_io

### Does the wallet have a dedicated support team?

https://discord.com/invite/seFBCWmUre
Reply within 24 hours

### What educational resources/documentation do you provide to users?

https://support.ledger.com/hc/zh-cn/articles/4409801559569-%E8%AE%BE%E7%BD%AE%E5%B9%B6%E4%BD%BF%E7%94%A8-Rabby-%E9%92%B1%E5%8C%85%E8%AE%BF%E9%97%AE%E6%82%A8%E7%9A%84-Ledger-%E4%BB%A5%E5%A4%AA%E5%9D%8A-ETH-%E8%B4%A6%E6%88%B7?docs=true

### Does the wallet have any integrated tools not mentioned above?

NO

**Comment by corwintines** [comment]
@chenko515 I was wondering if you had any documentation you could provide for Rabby (ex. https://docs.sequence.xyz/). Been finding it helpful to read documentation over before making a call.

**Comment by chenko515** [comment]
There's no public doc section yet but you can refer to our release announcement to know more about Rabby:
https://medium.com/@rabby_io/rabby-release-announcement-564406988e2b

**Comment by chenko515** [comment]
@corwintines There's no public doc section yet but you can refer to our release announcement to know more about Rabby:
https://medium.com/@rabby_io/rabby-release-announcement-564406988e2b

**Comment by corwintines** [comment]
@chenko515 are there plans to have documentation in the future?

**Comment by corwintines** [comment]
Created PR for this. Read the linked article and played around with the wallet. If/when the documentation is released let me know, would like to give it a read :)

**Comment by chenko515** [comment]
NP. Actually we have a joint group set up on telegram earlier, I can invite you over there if you wish.
