### ISSUE TITLE
Suggest a wallet - BitKeep

### ISSUE THREAD

**Issue by keepresolve** [ethereum/ethereum-org-website#7237]
### Wallet name

BitKeep

### Wallet description

BitKeep is the best decentralized multi-chain crypto wallet, providing 70+ mainnets and 220,000 crypto assets and 10,000+ DApps to global users.

### Wallet logo

https://raw.githubusercontent.com/bitkeepwallet/download/main/logo-png/BitKeep_logo_circle.png

### Background color for brand logo

#ffffff

### URL to the project

https://bitkeep.com/

### When did the wallet go live to users?

07-2018

### Does the wallet have an active development team?

https://github.com/bitkeepwallet/

### Is the wallet globally accessible?

yes

### Is the wallet available in multiple languages?

yes

### What social links are there for the project?

Twitter：
BitKeep Wallet：https://twitter.com/BitKeepOS
BitKeep Daily：https://twitter.com/BitKeepDaily
FaceBook：https://www.facebook.com/BitKeep
Youtube：https://www.youtube.com/channel/UCD2S03RS-Q08VdJqZpuOCFQ
Telegram: https://t.me/bitkeep
Discord: https://discord.com/invite/qYTatUzNjM
Medium: https://bitkeepblog.medium.com/
Instagram: https://www.instagram.com/bitkeep_global/?igshid=YmMyMTA2M2Y%3D

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS，Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

yes, Chromium.

### Is it a hardware wallet?

no

### Is the source code for the wallet fully open-source?

no

### What license is the wallet software released under?

https://bitkeep.com/resource/privacy  BitKeep Global Inc.-CI.PDF

### Who holds the private keys?

Do users have access to their public and private keys? Self-custodial wallet, users hold on to the private keys.
Does anyone else? No, not unless the user shares this with someone else
If the company/project were to disappear, would users still be able to access their funds? Yes, the user would still be able to access their private key, and import it into a new wallet

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Confirming with BitKeep

### Has the wallet's smart contract code or security modules been audited?

Confirming with BitKeep

### Does the wallet have an internal security team?

Confirming with BitKeep

### Any other security testing that should be noted?

Confirming with BitKeep

### Scam protection?

No response

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No response

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

yes

### Does the wallet support staking directly?

yes, bkb

### Does the wallet support swaps directly?

yes

### Does the wallet support multi-chain networks?

yes

### Does the wallet support Ethereum layer 2 networks?

yes

### Does the wallet allow the user to customize gas fees?

yes

### Does the wallet support sending transactions to ENS addresses?

yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

yes

### Does the wallet support EIP-1559 (type 2) transactions?

No response

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No response

### Does the wallet support withdrawals to fiat?

No response

### Is the wallet a multi-signature wallet?

No response

### Does the wallet support social recovery?

No response

### Who can the ethereum.org team can contact regarding the wallet in future?

No response

### Does the wallet have a dedicated support team?

No response

### What educational resources/documentation do you provide to users?

https://study.bitkeep.com/zh/

### Does the wallet have any integrated tools not mentioned above?

https://docs.bitkeep.com/

**Comment by corwintines** [comment]
@keepresolve putting the blocked label on this since it seems partially filled out and needs some answers from bitkeep. If there isn't any update then I will close this out until the questions are all able to be answered.

**Comment by corwintines** [comment]
@keepresolve any update on this?

**Comment by corwintines** [comment]
Going to close this since it is incomplete. @keepresolve please reopen this when you have the answers that you are waiting to hear back on.

**Comment by keepresolve** [comment]
Sorry, I forgot to reply. Can I reopen it? I need to supplement the information completely

**Comment by keepresolve** [comment]
I resubmitted a copy. If there is any problem, please prompt me to confirm the modification in time.  https://github.com/ethereum/ethereum-org-website/issues/7730.
