### ISSUE TITLE
Add detail on MEV after The Merge

### ISSUE THREAD

**Issue by emmanuel-awosika** [ethereum/ethereum-org-website#7271]
**Is your feature request related to a problem? Please describe.**

The [current page](https://ethereum.org/en/developers/docs/mev/) on Maximal Extractable Value (MEV) doesn't have a lot of information about MEV after The Merge (except that PoS validators will extract MEV, not miners).

**Describe the solution you'd like**

Seeing as MEV is [predicted](https://hackmd.io/@flashbots/mev-in-eth2) to [factor heavily in validator incomes](https://github.com/flashbots/eth2-research/blob/main/notebooks/mev-in-eth2/eth2-mev-calc.ipynb) (a consequence of reduced ether issuance), I think it'd be great to mention how Ethereum is working on mitigating the impact of MEV on consensus-layer security and decentralization. Specifically, explaining how concepts, like [Proposer-Builder Separation](https://ethresear.ch/t/proposer-block-builder-separation-friendly-fee-market-designs/9725), and current solutions (e.g., [MEV Boost](https://ethresear.ch/t/mev-boost-merge-ready-flashbots-architecture/11177)) will help curb MEV's negative effects after the transition to proof-of-stake. 

**Describe alternatives you've considered**

Putting it as an FAQ on The Merge page (e.g., "How does The Merge affect MEV?") is possible, but I think having an actual explainer would be better. 

**Additional context**

If this sounds good, I can volunteer to start things off by creating an "MEV after The Merge" section on the MEV page. 

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by jmcook1186** [comment]
Hi Emmanuel

thanks for this - I personally would support this idea - I simply haven't had time to get to it myself among the other merge updates but acknowledge it is definitely a gap and would appreciate you working on it!

Please go ahead and take ownership of this - I'll look forward to reviewing!

**Comment by samajammin** [comment]
Just noting this open PR: https://github.com/ethereum/ethereum-org-website/pull/7193

Not sure if there's info there worth grabbing/taking into account.

**Comment by samajammin** [comment]
I agree with this issue overall! I think a FAQ on MEV in relation to the merge makes sense. I'd just suggest let's be wary of writing too much content within the FAQ. Let's answer the question but push visitors to the dedicated MEV page (https://ethereum.org/en/developers/docs/mev/) for most of the MEV content.

**Comment by emmanuel-awosika** [comment]
> Just noting this open PR: #7193
> 
> Not sure if there's info there worth grabbing/taking into account.

Sure, I'll check it out.

**Comment by lukassim** [comment]
Closing this issue as it was solved with PR #7333
