### ISSUE TITLE
Stablecoin card buttons need margin

### ISSUE THREAD

**Issue by hursittarcan** [ethereum/ethereum-org-website#7281]
# Description
The buttons inside the stablecoin cards do not have a margin-bottom. This makes both buttons stick to eachother (it doesn't look good imo). 

The problem is present in both desktop and mobile view. I included screenshots below. 

The first screenshot is the current version. The second screenshot is the result of adding a bottom margin of 5px. Only applied to the left card (with chrome's dev tools).  

![ethereum_desktop_margin - kopie](https://user-images.githubusercontent.com/75273616/182434325-59c1c654-fad5-49f8-8516-4d21cc058714.png)
![image](https://user-images.githubusercontent.com/75273616/182435369-c35d66a3-5782-4616-b1bc-52bcb34d794e.png)

**Comment by samajammin** [comment]
Indeed - thanks for surfacing this bug!

**Comment by nloureiro** [comment]
Great Catch, Thank you.

My take: make the Margin bottom 0.5rem (8px) and I would add the same size for both buttons
![Screen Shot 2022-08-03 09 42 15 AM](https://user-images.githubusercontent.com/1120748/182565359-6c3cc778-b57b-451d-8529-6997da244ca2.png)

**Comment by vdusart** [comment]
Does someone work on this ? If not I can do it :slightly_smiling_face:

**Comment by wackerow** [comment]
@vdusart All yours =). If possible would be nice to use a solution like `gap` here to add a gap between the items despite ordering or flow direction (row/column)

**Comment by minimalsm** [comment]
Closed by #7385
