### ISSUE TITLE
Suggest a wallet - enkrypt

### ISSUE THREAD

**Issue by gamalielhere** [ethereum/ethereum-org-website#7293]
### Wallet name

Enkrypt

### Wallet description

Enkrypt is an extension for easy access to the world of web3 on the Ethereum and Polkadot ecosystems directly in your browser. A non-custodial wallet that tracks no data and leaves you in complete control of your assets!

### Wallet logo

![enkrypt-logo-color](https://user-images.githubusercontent.com/16236741/182736859-a68dc38e-c065-4fd7-9fd4-f08e1f47164c.png)

### Background color for brand logo

#ffffff

### URL to the project

https://www.enkrypt.com 

### When did the wallet go live to users?

August 3rd, 2022

### Does the wallet have an active development team?

Yes https://github.com/enkryptcom/enKrypt

### Is the wallet globally accessible?

Yes. Enkrypt does not collect personal data, has no KYC requirements, no geographic limitations.

### Is the wallet available in multiple languages?

No

### What social links are there for the project?

Twitter https://twitter.com/myetherwallet
Facebook https://www.facebook.com/MyEtherWallet
Reddit https://www.reddit.com/r/MyEtherWallet/
Telegram https://t.me/myetherwallet
Medium https://medium.com/myetherwallet
Youtube https://www.youtube.com/channel/UCQU5QbObwmaHNEMsuX3uQKA
Instagram https://www.instagram.com/myetherwallet/
Discord https://discord.com/invite/W8TrqJXS
GitHub https://github.com/enkryptcom/enKrypt
Twitter https://twitter.com/enkryptcom
Instagram https://www.instagram.com/enkryptofficial/
Reddit https://www.reddit.com/r/enkryptcom/
Telegram https://t.me/enkryptcom

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes. Enkrypt currently supports Chromium https://chrome.google.com/webstore/detail/enkrypt-ethereum-and-polk/kkpllkodjeloidieedojogacfhpaihoh

### Is it a hardware wallet?

No.

### Is the source code for the wallet fully open-source?

Yes https://github.com/enkryptcom/enKrypt

### What license is the wallet software released under?

MIT

### Who holds the private keys?

Users hold their own public and private keys. Enkrypt does not have any access to user keys or wallets. Users receive their mnemonic phrase when generating a wallet, and can use that information to import the wallet into any other Ethereum or Polkadot interface of their choice.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

All Enkrypt developers are required to be part of our organization and have 2FA enabled. We are partnered with HackerOne for penetration testing, and are using latest industry standards for hosting our services to ensure high up-time.

https://hackerone.com/myetherwallet

Enkrypt is not audited, however, Enkrypt does not use its own smart contract and is fully client-side and non-custodial. We don't collect or hold personal user information, and don't have custody of user assets.

### Has the wallet's smart contract code or security modules been audited?

No. Enkrypt does not use its own smart contract.

### Does the wallet have an internal security team?

No. Enkrypt works with Phishfort to monitor and take down phishing websites and apps that pretend to be Enkrypt with similar names and visual assets.

### Any other security testing that should be noted?

No response

### Scam protection?

No response

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes.

### Does the wallet support staking directly?

No.

### Does the wallet support swaps directly?

Yes. Users can perform on-chain swaps between the native token and ERC20s, as well as cross-chain swaps to and from tokens on Polkadot, Kusama, Ethereum, Polygon, and BNB Smart Chain.

### Does the wallet support multi-chain networks?

Enkrypt supports all Ethereum-based EVM chains, Polkadot, and Substrate chains with more blockchains on the way.

### Does the wallet support Ethereum layer 2 networks?

Yes.

### Does the wallet allow the user to customize gas fees?

Yes. Users can select one of three settings for gas – normal, higher, and highest priority

### Does the wallet support sending transactions to ENS addresses?

No. 

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, users are able to buy crypto in the wallet with a credit/debit card.

### Does the wallet support withdrawals to fiat?

No.

### Is the wallet a multi-signature wallet?

No.

### Does the wallet support social recovery?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

Twitter DM: https://twitter.com/enkryptcom
Telegram Vince Major: https://t.me/VinceM009
GitHub https://github.com/enkryptcom/enKrypt

### Does the wallet have a dedicated support team?

Yes. Users can write to [support@myetherwallet.com](mailto:support@myetherwallet.com) or join our (discord)[https://discord.com/invite/W8TrqJXS]  for assistance. Response time is from a few hours to a couple of days during network activity spikes.

### What educational resources/documentation do you provide to users?

Help Center (user documentation): https://help.myetherwallet.com/en/
Blog (educational resource): https://www.mewtopia.com/

**Comment by corwintines** [comment]
Hey @gamalielhere!

Thanks for the submission. I was wondering what day you went live. It says August 2022, but this is recent enough that a specific date would be preferred.

**Comment by gamalielhere** [comment]
@corwintines Just updated the date to August 3rd, 2022.

**Comment by corwintines** [comment]
Opened a PR for this
