### ISSUE TITLE
Remove the term "non-technical" from ethereum.org

### ISSUE THREAD

**Issue by jjmstark** [ethereum/ethereum-org-website#73]
This issue is based on a conversation with Scott Lewis on twitter, [where he made the following point:](https://twitter.com/scott_lew_is/status/1128109117619482625):

>“non-technical” is a diminutive term for non-devs by devs. the idea that random ethereum-curious individuals will self-identify as “non-technical” is not reasonable.

What do others think? cc @ethjoe

**Comment by Aniket-Engg** [comment]
I agree, rather than using 'non-technical', 'conceptual' can be right word or something similar.

**Comment by ethjoe** [comment]
Fine w/ either of this or @Aniket-Engg's suggestion, but the highlight of the twitter post for me was that note about beginners benefitting from some non-linked content that solves for this: 

"a user still has absolutely no clue what ethereum is if she does not clickthru something. and the clickthru is only for “beginners”, which is a blocker for many".

**Comment by oovg** [comment]
Hmm ... yea to your point @ethjoe ... sounds like information hierarchy could solve this a bit.

Current => User lands and the HERO presents them with "Beginners" first and then 3 other options and an image. That is FOLLOWED by the 'tagline' ("Ethereum is a global, open-source platform for ...") afterward.

Suggestion => Swap the hierarchy. Start with the 'tagline' and image, maybe a simple 'learn more' or some such. Then go to the 'Beginner', 'Learn', 'Use', 'Build' afterward. Which actually is already there, so maybe just kill the redundant 'Begin, learn, use, build' from the HERO.

**Comment by ethjoe** [comment]
I've got a feeling that interested community groups will take lead on some subpages over time to develop a bit of OC, and to keep links/videos updated and fresh. There are a lot of designs coming in, but if someone wants to submit PRs for content curation, I think most people will be very game.

**Comment by jjmstark** [comment]
Fixed in https://github.com/ethereum/ethereum-org-website/pull/102 and https://github.com/ethereum/ethereum-org-website/pull/103
