### ISSUE TITLE
Add Romanian to supported languages for content

### ISSUE THREAD

**Issue by fluffays** [ethereum/ethereum-org-website#737]

**Comment by sorumfactory** [comment]
@fluffays Adina. Thank you for your suggestion. We added the Romanian language in Crowdin. Please let us know if you have any questions or suggestions.

- Website Translation: https://crowdin.com/project/ethereumfoundation/ro#
- Contents Translation: https://crowdin.com/project/contents-translation/ro#

**Comment by samajammin** [comment]
Thanks @sorumfactory! Closing this issue out.

Are you a volunteer able to translate Romanian? Please get involved by following the links above!

**Comment by fluffays** [comment]
Thanks @sorumfactory & @samajammin for your quick support on this. Indeed I am a volunteer, already working on them translations. Cheerios!

**Comment by samajammin** [comment]
@all-contributors please add @fluffays for translation

**Comment by samajammin** [comment]
Content is ready for the site! Track progress here: #824
