### ISSUE TITLE
Add info on different transaction types

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7372]
**Is your feature request related to a problem? Please describe.**

Noticing in https://github.com/ethereum/ethereum-org-website/pull/7319 we ask for & provide wallet info on transaction types but don't explain what this means anywhere on the site.

**Describe the solution you'd like**

Add info / section on [our transactions page](https://ethereum.org/en/developers/docs/transactions/) that explains legacy, type 1 & type 2 transactions.

**Describe alternatives you've considered**

We could also link out to existing resources, e.g. this page looks to explain it well ("What is an Ethereum Transaction" section):
https://mycelium.xyz/research/the-journey-of-an-ethereum-transaction

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
Going to add a comment on this resource to base it off of as well: https://www.educative.io/answers/type-0-vs-type-2-ethereum-transactions

**Comment by corwintines** [comment]
Adding good first issue to this for anyone that would like to contribute!

**Comment by SeanXLChen** [comment]
Hi, I can help with this one. 

@samajammin However it seems the resource you mentioned is not there. [https://mycelium.xyz/research/the-journey-of-an-ethereum-transaction](https://mycelium.xyz/research/the-journey-of-an-ethereum-transaction)
Anywhere else could you point me to this article?

**Comment by corwintines** [comment]
Thanks @SeanXLChen!

Assigned this to you with the open PR
