### ISSUE TITLE
Configure new /find-wallet page for translations

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7373]
**Is your feature request related to a problem? Please describe.**

As a result of #6274, the page is no longer configured for translations. As part the "wallet upgrades" epic (#7250), we should do this as one of the last steps (i.e. we should make page updates/improvements BEFORE configuring translations).

**Describe the solution you'd like**

Configure the file(s) for translation.

**Comment by samajammin** [comment]
@corwintines calling attention to this file to make sure we don't miss it - we'll want to translate these strings:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/wallets/wallet-filters.ts

**Comment by corwintines** [comment]
Thanks for making this @samajammin! I think we should be able to do this soon. There are a few changes we should look at for copy from user testing feedback, and want to do a bit of refactoring on some smelly code to clean it up first.

**Comment by corwintines** [comment]
This has been completed
