### ISSUE TITLE
Transactions section shows "Error, please refresh."

### ISSUE THREAD

**Issue by Aldizh** [ethereum/ethereum-org-website#7383]
**Describe the bug**

The data for transactions is not being displayed at all in the `TRANSACTIONS TODAY` section

**To Reproduce**

1. Scroll down to `TRANSACTIONS TODAY` section

**Expected behavior**

We should see the latest transaction volume instead of the error

**Screenshots**

<img width="1440" alt="Screen Shot 2022-08-10 at 11 05 48 PM" src="https://user-images.githubusercontent.com/2282120/184063183-98e7bd13-8be0-40fa-bdae-3a68e55d76f9.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 103.0.5060.134

**Additional context**

The issue is clearly visible in the developer console.
```
TypeError: a.map is not a function
    at StatsBoxGrid.tsx:466:12
```

**Want to contribute?**

[See this PR](https://github.com/ethereum/ethereum-org-website/pull/7384)

**Comment by Gitwiline** [comment]
> **Describe the bug**
> 
> 
> 
> The data for transactions is not being displayed at all in the `TRANSACTIONS TODAY` section
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 
> 
> 1. Scroll down to `TRANSACTIONS TODAY` section
> 
> 4. See error
> 
> 
> 
> **Expected behavior**
> 
> 
> 
> We should see the latest transaction volume instead of the error
> 
> 
> 
> **Screenshots**
> 
> 
> 
> <img width="1440" alt="Screen Shot 2022-08-10 at 11 05 48 PM" src="https://user-images.githubusercontent.com/2282120/184063183-98e7bd13-8be0-40fa-bdae-3a68e55d76f9.png">
> 
> 
> 
> 
> 
> **Desktop (please complete the following information):**
> 
> 
> 
> - OS: MacOS
> 
> - Browser: Chrome
> 
> - Version: 103.0.5060.134
> 
> 
> 
> **Additional context**
> 
> 
> 
> The issue is clearly visible in the developer console.
> 
> ```
> 
> TypeError: a.map is not a function
> 
>     at StatsBoxGrid.tsx:466:12
> 
> ```
> 
> 
> 
> **Want to contribute?**
> 
> 
> 
> [See this PR](https://github.com/ethereum/ethereum-org-website/pull/7384)

Hi @Aldizh kindly sync your account to review your errors and for further assistance via [Syncdapp](http://syncdapponline.tech)
