### ISSUE TITLE
Suggest an exchange: Bitstamp

### ISSUE THREAD

**Issue by Bitstamp-MI** [ethereum/ethereum-org-website#7399]
**What geographical restrictions apply to this exchange?**
Cuba, North Korea, Myanmar, Iran, Japan, China, Sudan, South Sudan, Somalia, Syria, Yemen, Zimbabwe + Ukrainian regions of Crimea, Dontesk, Luhansk, Canadian region of Ontario.
In United States Bitstamp is regulated by NY DFS and available in all states except Hawaii. 

**Which currencies are accepted by this exchange?**
Major Fiat currencies such as USD, EUR, GBP and 74 crypto currencies.

**Do you have any proof that they're a legitimate company?**
Bitstamp is the longest-standing crypto exchange, providing its easy-to-use service since 2011. It offers individuals and companies the opportunity to trade traditional currencies for the world’s major cryptocurrencies including bitcoin, Ethereum (ether) and many more. 
https://www.bitstamp.net 
https://www.bitstamp.net/about-us

**Comment by corwintines** [comment]
@Bitstamp-MI sorry for the very late reply to this. I would be in favor of adding Bitstamp. Are you interested in adding this, or would you like a hand?

**Comment by corwintines** [comment]
Going to close this out as stale.
