### ISSUE TITLE
[Node Service] Nodereal.io

### ISSUE THREAD

**Issue by zaeufi** [ethereum/ethereum-org-website#7400]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

NodeReal MegaNode

**Product description:**

We are providing most reliable, fastest and scalable RPC API services and enhanced API for web3 developers.

**How long has it been around?**

Since 2021

**Where do you think it should go?**

https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/

**GitHub URL**

https://github.com/node-real

**Docs URL**

https://docs.nodereal.io/nodereal/meganode/introduction

**Is the product open source?**

No

**Additional context**

We provide EMV RPC service and enhanced APIs for developers to allow developers to focus on the dApp business logic. Through innovative architecture design and deep understanding of API services, we could provide the globally accessible, scalable and high performance service to all developers across the world.

**Comment by minimalsm** [comment]
Hey @zaeufi, thanks for creating this issue.

Just a heads up this might take a while to get to as it isn't high-priority work for our team, but you're welcome on a PR to add Nodereal.io if you'd like this to be done sooner.

**Comment by zaeufi** [comment]
Hey Joshua,

We would like to push every opportunity possible, so let's do this PR for
sure.

How can we start?
Also which other marketing sponsorships do you have to increase our
Ethereum support?

Thanks!

André Costa

Performance Engineer | BizDev
+351911978251
***@***.***
https://www.nodereal.io/
[image: twitter] <https://twitter.com/andreomatic>
[image: linkedin] <https://www.linkedin.com/in/umdandre/>
[image: instagram] <https://www.instagram.com/umdandre/>
Create Your Own Free Signature
