### ISSUE TITLE
Add TTD info to Merge page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7409]
**Is your feature request related to a problem? Please describe.**

https://mobile.twitter.com/BanklessHQ/status/1557753518282473472

**Describe the solution you'd like**

Once verified with additional sources 😄 we should add this info to the Merge page:
https://ethereum.org/en/upgrades/merge/

**Describe alternatives you've considered**

If there's an upcoming [EF blog post](https://blog.ethereum.org/) on this, it would probably make sense to link to that.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ThreeMuskets12** [comment]
EF blog post won’t be until August 23rd, this seems premature imo

**Comment by wackerow** [comment]
🐼🐼🐼
