### ISSUE TITLE
eth-docker as a tool to run a node

### ISSUE THREAD

**Issue by ThreeMuskets12** [ethereum/ethereum-org-website#7411]
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

eth-docker
**Product description:**

Docker automation for Ethereum consensus and execution clients
**How long has it been around?**

June 5th 2021
**Where do you think it should go?**

https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/
https://ethereum.org/en/run-a-node/
**GitHub URL**

https://github.com/eth-educators/eth-docker
**Docs URL**

https://eth-docker.net/docs/About/Overview/
**Is the product open source?**

YES
**Additional context**

This could be a good middle-ground between buying something like a DApp Node and configuring an execution client + consensus client + validator client on the command line. Has a built-in configuration wizard and also supports sending stats to something like beaconcha.in. I believe this tool was used quite a bit to rapidly spin up different execution + consensus pairs for testing over the last few months of merge testing. Lots of external guides exist for using eth-docker for staking as well!

**Comment by corwintines** [comment]
I see this has been added already to the staking pages, so going to close this out :) Thanks @ThreeMuskets12!
