### ISSUE TITLE
Suggest a wallet:1inch wallet -  bug issue

### ISSUE THREAD

**Issue by petrudenko** [ethereum/ethereum-org-website#7420]
### Wallet name

1inch Wallet

### Wallet description

Please change the "self custody" criteria from NO to YES  in current listing  for 1inch wallet on your website   .

 1inch is a self-custodial wallet(https://help.1inch.io/en/articles/5783998-why-is-1inch-non-custodial-and-what-does-that-mean-for-users) where users have complete ownership of their private keys. If 1inch were to disappear, users could take their keys and regain access to their funds using another wallet
 
 Also please update the description.

-----------------------

1inch is the most powerful and secure crypto wallet

### Wallet logo

![1inchlogo](https://user-images.githubusercontent.com/64213848/184393264-ed9773bd-7a7e-4983-a062-2259b8fb6d22.png)

### Background color for brand logo

082D6E

### URL to the project

https://1inch.io/wallet/

### When did the wallet go live to users?

27 April 2021

### Does the wallet have an active development team?

https://blog.1inch.io/the-1inch-wallet-for-android-is-released-21b04b0a450d

### Is the wallet globally accessible?

No KYC requirements or geographic limitations of the wallet.

### Is the wallet available in multiple languages?

13 Languages (ENG, RU, CH,FR,GER,Hindi, IND, JAP,KOR, POR,SPN,TURK,VIE) 

### What social links are there for the project?

https://blog.1inch.io/
https://www.reddit.com/r/1inch/
https://twitter.com/1inch
https://discord.com/invite/1inch
https://www.youtube.com/channel/UCk0nvK4bHpteQXZKv7lkq5w
https://t.me/OneInchNetwork

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Android and IOS
https://apps.apple.com/us/app/1inch-crypto-defi-wallet/id1546049391
https://play.google.com/store/apps/details?id=io.oneinch.android&hl=en&gl=US
https://cdn.1inch.io/mobile/apk/1inchWallet-1.2.2-s-227.apk

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Safari plugin IOS
https://help.1inch.io/en/articles/6182723-how-to-use-the-1inch-ios-wallet-safari-extension

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

No

### Who holds the private keys?

1inch is a self-custodial wallet where users have complete ownership of their private keys. If 1inch were to disappear, users could take their keys and regain access to their funds using another wallet

(https://help.1inch.io/en/articles/5783998-why-is-1inch-non-custodial-and-what-does-that-mean-for-users)

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

1inch wallet works with [Blue Frost Security ](https://www.bluefrostsecurity.de/en/)as a security partner.

### Does the wallet have an internal security team?

No

### Any other security testing that should be noted?

We have an internal security team

### Scam protection?

1inch warns user when giving permission to user not a contract, and when send goes to a contract not an address.
1inch supports flashbot
https://help.1inch.io/en/articles/5300755-what-are-flashbot-transactions-and-how-do-they-work-on-1inch

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, via wallet connect or built-in browser

### Does the wallet support staking directly?

Yes , https://help.1inch.io/en/articles/4767696-how-to-stake-1inch-tokens-and-participate-in-1inch-network-s-instant-dao-governance-models

### Does the wallet support swaps directly?

Yes , https://help.1inch.io/en/articles/5172827-1inch-wallet-how-to-swap-tokens-using-the-1inch-wallet-app

### Does the wallet support multi-chain networks?

Yes, https://help.1inch.io/en/articles/5172973-how-to-switch-the-network-in-1inch-wallet#:~:text=To%20switch%20networks%2C%20tap%20on,of%20the%20main%20wallet%20page).

### Does the wallet support Ethereum layer 2 networks?

Yes, https://help.1inch.io/en/articles/5172973-how-to-switch-the-network-in-1inch-wallet#:~:text=To%20switch%20networks%2C%20tap%20on,of%20the%20main%20wallet%20page).

### Does the wallet allow the user to customize gas fees?

Yes (https://help.1inch.io/en/articles/5604671-how-to-set-basic-and-advanced-gas-settings-in-the-1inch-ios-wallet#:~:text=To%20do%20so%2C%20open%20the,Limit%22%20to%20enable%20the%20feature.)

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes , https://help.1inch.io/en/articles/5599351-how-to-add-or-remove-any-custom-token-within-the-1inch-ios-wallet

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, https://help.1inch.io/en/articles/5496631-how-the-eip-1559-gas-price-setting-works-on-1inch

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, https://help.1inch.io/en/articles/5277851-how-to-buy-crypto-with-fiat-using-the-1inch-wallet

### Does the wallet support withdrawals to fiat?

no

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

p.rudenko@1inch.io

### Does the wallet have a dedicated support team?

yes, https://help.1inch.io/en/

### What educational resources/documentation do you provide to users?

1inch has a dedicated help center, youtube channel with "How To" videos, live and chatbot support.

### Does the wallet have any integrated tools not mentioned above?

Sign transactions with Apple Watch
Cancel transactions
Send raw hex data
EIP-681 support
Content Integration (News)
Seed phrase import via camera
Games

**Comment by corwintines** [comment]
https://github.com/ethereum/ethereum-org-website/pull/7531

Created a PR for this.
