### ISSUE TITLE
Ensure all article titles in Javascript pages are translated

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#7436]
**Is your feature request related to a problem? Please describe.**

I noticed in #7419 that we still have some article titles that are not being translated. 

You can see [The Merge page](https://ethereum.org/zh/upgrades/merge/#read-more) is entirely untranslated

**Describe the solution you'd like**

Ensure all article titles and descriptions are added to and fetched from JSON files so they can be translated.

**Additional context**

Might it make sense to have all articles in their own JSON file? We don't want to duplicate translations and probably don't want to reach into page-specific JSON files for translation strings on other pages.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment]
Example file that needs to be configured for translations: https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/MergeArticleList.tsx

**Comment by hursittarcan** [comment]
I can do MergeArticleList

**Comment by hursittarcan** [comment]
@minimalsm can you assign this to me?

**Comment by Freitag8** [comment]
>  @`
![Uploading 0eb1cebac6f4001d5ad2ea27acac5316.jpg…]()
`

**Comment by Freitag8** [comment]
Like

**Comment by corwintines** [comment]
@hursittarcan not sure if you are still interested. Let me know and I can assign to you

**Comment by hursittarcan** [comment]
@corwintines forsure!

**Comment by corwintines** [comment]
@hursittarcan awesome! Assigned to you!

**Comment by wackerow** [comment]
Looks like the example has at least been fixed. Checking https://ethereum.org/es/roadmap/merge, all the further reading article titles are translated. @minimalsm Did you know of other areas that are affected by this?

@hursittarcan Did you still want to take a look at this and audit for any additional pages that needed to be updated? Otherwise we can probably close this out.

**Comment by hursittarcan** [comment]
@wackerow I would like to review this over the weekend. I'll carefully check for any untranslated titles and, if necessary, submit a PR.

**Comment by hursittarcan** [comment]
@wackerow @corwintines PR created!

**Comment by corwintines** [comment]
Amazing, thank you @hursittarcan!
