### ISSUE TITLE
Can't translate opcodes page in french

### ISSUE THREAD

**Issue by aaaaaaaaaaaz41** [ethereum/ethereum-org-website#7442]
Hello!

I would like to translate this page in french: https://ethereum.org/fr/developers/docs/evm/opcodes 

But "/evm/opcodes/" has no translation in Crowdin, I think you forgot to add it.

**Comment by isabelladebrito** [comment]
Hi @aaaaaaaaaaaz41! Thanks for creating this issue, and my apologies it took us too long to look into this.

The '[Opcodes for the EVM](https://ethereum.org/fr/developers/docs/evm/opcodes)' page seems to have been set up for translations on Crowdin (https://crowdin.com/project/ethereum-org/fr#/11)%20Foundational%20Docs/developers/docs/evm/opcodes) last year - therefore, I'm gonna go ahead and close this issue. Thanks for your help!
