### ISSUE TITLE
Migrate markdown checker to TypeScript

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7454]
**Is your feature request related to a problem? Please describe.**

We recently added a new script in #7088:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/scripts/markdown-checker.js

**Describe the solution you'd like**

This file should be migrated to TypeScript (#6392).

**Additional context**

Here's the migration guide:
https://github.com/ethereum/ethereum-org-website/blob/dev/docs/typescript.md

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vdusart** [comment]
Hey @samajammin, hope you're doing well !
Can I do this one please :smile:
