### ISSUE TITLE
Update TypeScript docs

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7455]
**Is your feature request related to a problem? Please describe.**

I noticed when creating https://github.com/ethereum/ethereum-org-website/issues/7454 that our TypeScript docs are outdated - we describe the situations as if we're the progress of migrating:

> As we are progressively migrating the entire codebase to TS, we will have a mix of .js and .ts files in the process.

But actually the migration is already complete 🎉 

**Describe the solution you'd like**

Let's rework this documentation to:
- Explain why & how we use TypeScript in the codebase
- Any new files should be TS, not JS
- Any general specifics on HOW we use TS (e.g. any custom linting rules)
- Remove the "migration guide" given that's complete

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by nloureiro** [comment]
No longer relevant, our code conventions cover much of this content. [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/code-conventions.md)
