### ISSUE TITLE
Update Non-fungible tokens (NFT) tokens page with new use-cases

### ISSUE THREAD

**Issue by develo-pera** [ethereum/ethereum-org-website#7458]
Thanks to EIP-4907 and few protocols that emerged recently new use case for NFTs is unlocked: Renting. NFTs can generate passive income now for the holders which is powerful and appealing utility.

If you share my opinion, I would like to be assigned to this issue and I would gladly add Renting section to the page under use-cases.

**Comment by minimalsm** [comment]
Hey @develo-pera, sorry for the delay here. Thanks for raising and offering to help, I've assigned you to this issue.

I think adding content around this makes sense. 

A few questions: 

1. Where would you see this living on the page?
2. How much content do you see this being (I'd expect it to be a pretty short section, but feel free to push back if you disagree.)?
3. Are there any good examples of this already being used we can provide to users?

**Comment by develo-pera** [comment]
Hey @minimalsm, thanks for responding and assigning this to me. It will be my first ever contribution to EF :D

1. I think the best place would be under [What are NFTs used for?](https://ethereum.org/en/nft/#nft-use-cases) section under [Investments and collateral](https://ethereum.org/en/nft/#nfts-and-defi) subsection
2. I agree, just few paragraphs to explain it properly (Shouldn't be longer that this for example https://ethereum.org/en/nft/#certificates)
3. Yes, actually. There are few examples like  [reNFT](https://www.renft.io/), [Renfter](https://renfter.com/), [Double](https://double.one/), etc...

**Comment by nloureiro** [comment]
> Hey @minimalsm, thanks for responding and assigning this to me. It will be my first ever contribution to EF :D
> 
> 1. I think the best place would be under [What are NFTs used for?](https://ethereum.org/en/nft/#nft-use-cases) section under [Investments and collateral](https://ethereum.org/en/nft/#nfts-and-defi) subsection
> 2. I agree, just few paragraphs to explain it properly (Shouldn't be longer that this for example https://ethereum.org/en/nft/#certificates)
> 3. Yes, actually. There are few examples like  [reNFT](https://www.renft.io/), [Renfter](https://renfter.com/), [Double](https://double.one/), etc...

Hey @develo-pera, sorry for the long answer here.

Still up. To follow up on this issue?

if yes, I think we can follow your suggestions and I added one more:
-  add as a use case on the list
-  think a paragraph should be good, this page needs an overall update, but for now 
-  add to further reading a link to this page > https://eips.ethereum.org/EIPS/eip-4907

Let me know if you need anything else. Thank you.

**Comment by corwintines** [comment]
Thanks @develo-pera 

I'm going to close this out at the moment as we did a refactor on the content on the NFT page, and should start to think about how we can create subpages for NFT content in the future. I have added a revisit label on this issue so that when we can focus on this in the future we can come back to this. Thank you again for the idea!
