### ISSUE TITLE
Adding DVT as a seperate category

### ISSUE THREAD

**Issue by alonmuroch** [ethereum/ethereum-org-website#7459]
This feature request is a a followup on a call with @wackerow about creating a dedicated category for [DVT (distributed-validator-technology).](https://github.com/ethereum/distributed-validator-specs).

**Describe the solution you'd like**
Add a dedicated DVT category in (one of the following options):
- use-ethereum->stake ETH -> DVT
DVT is it's own animal, serving as an infrastructural component for staking and not necessarily a staking "service". Having a dedicated category for it will help a lot in educating people DVT, how it works, it's benefits and applications.
- use-ethereum -> DVT
Same as the above but instead have a dedicated DVT category under the main drop down menu, similarly to Layer 2 having a place there. DVT, IMO, has a meaningful enough impact on ethereum as L2 so it might as well have a place next to it as a "complementary" tech for L1 (ethereum itself)

**Want to contribute?**

If one of the above suggestions is relevant, I'd love to help with content around and on DVT (we've written significantly on the topic)

**Comment by minimalsm** [comment]
Hey @alonmuroch. Would love to chat on this more. I can definitely see the need and value of adding more information around DVT to ethereum.org.

My gut take: of the potential options you listed, keeping DVT under the staking umbrella seems preferable. This is better for overall information architecture. Whilst DVT is **extremely** important, I don't think having it as it as a main navigation item makes sense as it's far more niche. If a topic has strong dependencies on other content (i.e. fully understand staking as a concept), I'd almost always side with nesting it within that topic.

**Comment by wackerow** [comment]
Thanks for posting @alonmuroch! As I've mentioned on the side, bandwidth to tackle this right now is going to be a bit limited, but it'd be great to try and get some more discussion in here to iron out some details, then we can discuss pulling this into a future sprint.

**Comment by wackerow** [comment]
I also lean towards keeping this nested within staking for similar reasons to @minimalsm. @alonmuroch, remind me, do you have any folks who could potentially help contribute to content for a DVT page?

**Comment by alonmuroch** [comment]
@wackerow we have someone from the community writing content, he can definitely help out with a lot of that. 
I'm thinking a top to bottom approach talking about what DVT can do all the way down to how it works. WYT?

**Comment by alonmuroch** [comment]
@minimalsm @wackerow any action items?

**Comment by wackerow** [comment]
Hey @alonmuroch! Thanks for pinging on this. With our Q4 planning we've been discussing prioritizing circling back to the staking pages and I'm advocating that we include spending some time to build out a `/staking/dvt` subpage for the site.

Given that most (all?) DVT solutions are currently only on testnet, I think the format of this page should be a bit different than the existing subpages (`/staking/solo` `/staking/saas` and `/staking/pools`) which place a focus on providing tools and resources for people to use on mainnet today. 

> I'm thinking a top to bottom approach talking about what DVT can do all the way down to how it works. WYT?

I think this would be a good idea. Distributed validator tech is obviously still quite new so I think placing a focus on education surrounding the topic would be best for now, then we could add a section to the bottom of how users can start trying out this tech. Before we get too deep in the actual content it would be great to create a potential outline of content to start and solicit some feedback before too much in-depth content is actually written.

For this section of the site specifically I think we should focus on keeping things _relatively_ high level (less technical), as these pages attract more people who are new to the space, or simply not looking for an overly complex explanation. Another thing we can discuss is potentially adding a more technical deep dive to our developer docs, where we can be more free to get into the weeds a bit if needed. 

> we have someone from the community writing content, he can definitely help out with a lot of that.

This is great! If you do have some folks who are willing to help with this content, it would be great for you to ping them about this and see if they'd be willing to put together a draft outline and post it here. Let me know what you think about this plan =)

**Comment by corwintines** [comment]
While the page still needs a bunch of editing based on initial comments, we have a page being worked on in this PR: https://github.com/ethereum/ethereum-org-website/pull/9608
