### ISSUE TITLE
Add `robots.txt` file

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#7464]
We have a generated sitemap that is located under `/sitemap/sitemap-index.xml`. Regardless that this location is pretty standard, some search engines might not find it.

**Describe the solution you'd like**

Create and specify the sitemap location in a `robots.txt` file since this file is understood by all the major search engines.

**Additional context**

This seems to be the default plugin for Gatsby: https://www.gatsbyjs.com/plugins/gatsby-plugin-robots-txt/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vdusart** [comment]
Hey @pettinarip, I hope you're fine !
I can do that :smile:

**Comment by pettinarip** [comment]
> Hey @pettinarip, I hope you're fine ! I can do that smile

I'm doing great! thanks for asking. Hope you are doing good as well.

Ok, I'm assigning it to you. Feel free to ping me if you are stuck or blocked with anything.

**Comment by pettinarip** [comment]
Issue fixed in #7477
