### ISSUE TITLE
ERC4626 page incorrectly includes balanceofunderlying()

### ISSUE THREAD

**Issue by devtooligan** [ethereum/ethereum-org-website#7468]
**Describe the bug**

ERC4626 page incorrectly displays a function that didn't make the final cut

**To Reproduce**
go to:
https://ethereum.org/en/developers/docs/standards/tokens/erc-4626/#balanceofunderlying

![Screen Shot 2022-08-16 at 8 17 23 PM](https://user-images.githubusercontent.com/71567643/185027476-8cc7360c-fa62-4aca-8008-c4bdf592542a.png)

**Expected behavior**

Doesn't have that fn

For reference: 
https://eips.ethereum.org/EIPS/eip-4626

**Comment by minimalsm** [comment]
Nice catch! Thanks @devtooligan
