### ISSUE TITLE
Launchnodes (solo staking provider)

### ISSUE THREAD

**Issue by andreilicious23** [ethereum/ethereum-org-website#7483]
Before suggesting a staking product or service, make sure you've read [our listing policy](/contributing/adding-staking-products/).

Only continue with the issue if the staking product meets the criteria listed there.

If it does, complete the following information which we need to accurately list the product/service.

**Product type**

- [*] Node/client tooling
- [ ] Key management
- [ ] Staking as a service
- [ ] Staking pool
- [ ] Other: (describe)

**Launchnodes**

**[Logo](https://logo-public.s3.us-east-2.amazonaws.com/app+icon.png)**
![alt text](https://logo-public.s3.us-east-2.amazonaws.com/app+icon.png)

**Launchnodes provides solo staking services for Ethereum, with validator, beacon and geth nodes
that run on AWS, Azure and your own infrastructure**

**[Website](https://launchnodes.com/)**

**If software is involved, is everything open source?**

- [ ] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ ] No, code is closed source
- [*] N/A, no custom software is involved

**Is the project a fork? If yes, which project was forked?**
No.

**Is the product out of _beta_ development?**
Yes.

**What wallets support the product or service?**
All wallets that are supported by the Ethereum Launchpad.

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**
32 ETH or multiples of 32 ETH.

**If a service, what are the fees associated with using the service?**
License fee that is paid per hour or annually to Launchnodes and AWS/Azure infrastructure fee. If the client uses own infrastructure, only the Launchnodes license fee applies. 

**If the product or service involved a liquidity token, what are the tokens involved?**
Not applicable.

**What date did the project or service go live?**
September 2020. https://aws.amazon.com/marketplace/seller-profile?id=0eee06cf-d077-4219-9d46-642372b9df1b

**Has the project undergone an external security audit?**
Internal AWS marketplace and Azure marketplace audits. Listing on both marketplaces is only allowed after the products have gone through AWS and Azure marketplaces' security audits. These are not shared, but if products fail the audit, they are not listed. 

**Has the project undergone any security bug bounties?**
No.

**Is the project being actively maintained?**
Yes.

**Is the product or service free of trusted/human intermediaries?**
Yes.

**If a pooled staking service, can users participate as a node operator without permission?**
Not a pooled staking service.

**If listing a staking-as-a-service, are users required to sign-up for an account?**
No.

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**
No. Only the client holds signing and withdrawal keys. The user maintains access to all the keys, Launchnodes has no access to any keys. 

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**
Not applicable.

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**
Prysm validator and beacon nodes as well as full geth nodes. Teku and Nimbus will be offered shortly, as will Erigon.

**What platforms are supported?**
Linux, macOS, Windows.

**What user interfaces are supported?**
CLI, AWS console and Azure console.

**Social media links**
Twitter: https://twitter.com/launchnodes
YouTube: https://www.youtube.com/channel/UC5tEUUlx11httS9Y9RvIzJw
LinkedIn: https://www.linkedin.com/company/67972177/
Discord: https://discord.gg/w5pjfWqdyT

**Comment by andreilicious23** [comment]
@minimalsm can you please check this and push forward, if possible? Thank you!

**Comment by wackerow** [comment]
Hey @andreilicious23, was just looking through this in more details and wanted to clarify some things.

Am I correct that this is a service to connect users to a node that is hosted on AWS?

The tools listed on this page are intended to help users would would like to stake from home with their own hardware and node setup. I feel like this would fit more appropriately into the staking-as-a-service category, where various levels of delegation are present in the staking process, such as offloading the management of the hardware itself. We explicitly caution users about centralizing node power on cloud services like AWS on the solo staking page. 

> If listing a staking-as-a-service, are users required to sign-up for an account?
> No.

Am I mistaken or does the user need an AWS account? When I go through the flow on the site above I'm directed to make a purchase that requires an AWS account. The purpose of this question is to determine if someone can permissionlessly utilize this service. Requiring an account that can be rejected or terminated involves additional trust assumptions.

**Comment by andreilicious23** [comment]
Paul,

Thank you for your feedback!

Let me reconfirm, that the pages in question are as follows:
- https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/
- https://ethereum.org/en/staking/solo/

Although the website takes you to AWS by default, Launchnodes helps users
solo stake on AWS, Azure, GCP, other cloud solutions and users' own
hardware. All cloud set ups happen within the user's account.

Below are answers to some of the points you've made:

*>Am I correct that this is a service to connect users to a node that is
hosted on AWS? *

No that is incorrect. This service sets up a node in a user's own AWS
account, not a Launchnodes-owned AWS account. Launchnodes has no access to
the AWS account or the nodes inside the user's account and there is no UI
dependency on Launchnodes. In the event of Launchnodes as a business not
existing and the Launchnodes entire team dying or going rogue the following
facts are true:

1. Our clients can continue to earn staking rewards from their nodes.
2. The client has never shared its mnemonic, it's keys or passwords with
Launchnodes so there is no breach of security
3. The client can continue to manage their nodes without Launchnodes as the
tech stack is transparent and fully owned by the client.
4. They can change their nodes' setup and architecture with no help or
advice from Launchnodes.

Furthermore, if Launchnodes' clients who are solo stakers decide they no
longer wish to use the nodes, we help them to migrate. They can cancel the
contract at any time and run nodes with a different provider or themselves
without our professional services fees.

Our clients use AWS, but we help them stake on any public or private cloud,
or their own data centre infrastructure. Our work with UNICEF that the
Ethereum Foundation was involved in, has seen us bring up nodes on the
cloud. We will move them into a data centre in Rwanda when staking is
legally allowed to happen in country as per the central bank's
instructions.

*> I feel like this would fit more appropriately into the
staking-as-a-service category.*

Paul, Launchnodes is not a staking-as-a-service provider.


*> We explicitly caution users about centralizing node power on cloud
services like AWS on the solo staking page. *
We agree. AWS is one option of many that we help clients stake through. We
run one of the 6 Beacon nodes in Africa on bare metal, in a local data
centre for a client.

*> Am I mistaken or does the user need an AWS account? *

Yes, in case the user wants to run his/her node on AWS. We can do it on
bare metal for you, the self-service option we offer clients is on AWS. It
will be made more pronounced across our website in the next 2 weeks.

*> When I go through the flow on the site above I'm directed to make a
purchase that requires an AWS account. The purpose of this question is to
determine if someone can permissionlessly utilize this service.*

They can, if they have an AWS account. If they don't, they have to send us
an email and we set up the nodes on the infra they choose, with the client
they choose, with the architecture of their choice. No Launchnodes customer
has an account with Launchnodes, ever.

Hope this helps.

I will be on standby if you need anything else. Thanks for your support
Paul.

**Comment by corwintines** [comment]
I strongly agree with @wackerow here. This seems more like a staking-as-a-service option than solo staking. To me, the moment you have to pay someone for a service it becomes staking-as-a-service. Even if I were to run setup my own validator on AWS I would say that's a service and not solo staking.

> Although the website takes you to AWS by default, Launchnodes helps users solo stake on AWS, Azure, GCP, other cloud solutions and users' own hardware. All cloud set ups happen within the user's account.

Regardless of if this is a Launchnode account (which it is established it isn't), or a personal AWS account, there is the risk that @wackerow highlighted above (Requiring an account that can be rejected or terminated involves additional trust assumptions.). It seems no matter what, a user needs an account at some cloud center to use this (GCP, Azure, etc.).

>Maintain hardware that runs both an Ethereum execution client and consensus client while connected to the internet

The above point is discussed on the staking page, which AWS or any other cloud service would not meet.

>Is the product or service free of trusted/human intermediaries? Yes.

This seems wrong if we are using cloud services.

> If a service, what are the fees associated with using the service? License fee that is paid per hour or annually to Launchnodes and AWS/Azure infrastructure fee. If the client uses own infrastructure, only the Launchnodes license fee applies.

We can see here with your answer it is a service as well.


My suggestion here is looking how to move forward with Launchnodes as a staking-as-a-service provider here if you agree @wackerow.

**Comment by wackerow** [comment]
Hey @andreilicious23, circling back to this, appreciate your thorough response to my questions while I try to understand how Launchnodes operates. I think I understand a bit better after your replies...

> Let me reconfirm, that the pages in question are as follows:
> - https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/
> - https://ethereum.org/en/staking/solo/

A note on this first, listing Launchnodes on the `/developers/docs/nodes-and-clients/run-a-node/` page would not necessarily require the same level of scrutiny as the `/staking/` pages (at least in my opinion, as it's in the developer docs compared to the featured staking pages). I would suggest, if you'd like, to open a PR adding Launchnodes to the end of this list:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/54227730/226739097-003bd1cf-1e87-4afe-9d3e-e81e21745f27.png">

> License fee that is paid per hour or annually to Launchnodes and AWS/Azure infrastructure fee. If the client uses own infrastructure, only the Launchnodes license fee applies.

So if I'm understanding this correctly, the user is responsible for either having access to their own infrastructure, or an account with a third-party cloud provider... Then Launchnodes will assist in setting up the client software and validator setup on whichever option the user chooses?

I see your argument of how this is not SaaS, since you don't seem to be running the hardware yourself... would I be more correct to say this is somewhat of a consulting service where you help users get set up?

Just following the flow on the website to try and take the "Solo stake on alternative infrastructure" approach, I progressed as follows:

https://www.launchnodes.com/ -> Run nodes -> Solo stake on alternative infrastructure -> Start staking [or] Schedule in person consultation

If I choose "Schedule in person consultation" I'm prompted with a Calendly invite, which seems to fit the idea I just mentioned of a "consultation service" (which I have nothing against... just thinking how this would fit into our existing structure, or if maybe this introduces another type of staking product that we should consider)

If I choose "Start staking" I'm taken directly to AWS checkout... I'm not sure I understand how to go through this flow without using AWS... would I need to schedule the consultation?

---

Appreciate you bearing with us here. As I mentioned, mainly just trying to properly understand the service being offered so we can make sure we present it to users as accurately as possible for their own protection.

**Comment by andreilicious23** [comment]
Hi Paul ***@***.***),

Apologies for the belated reply. We overhauled our website so that the
message and product offering is much more clear. Hence, wanted to wait for
the updated site to go live before I follow up re your questions. Please
see my feedback below:

A note on this first, listing Launchnodes on the
/developers/docs/nodes-and-clients/run-a-node/ page would not necessarily
require the same level of scrutiny as the /staking/ pages (at least in my
opinion, as it's in the developer docs compared to the featured staking
pages). I would suggest, if you'd like, to open a PR adding Launchnodes to
the end of this list:


*Ok, that seems reasonable. We are as your points below indicate not a
staking as a service provider. However, we are happy to go through any type
of scrutiny in order to appear where it's most applicable, which are the
solo staking pages. *

[image: image]
<https://user-images.githubusercontent.com/54227730/226739097-003bd1cf-1e87-4afe-9d3e-e81e21745f27.png>

License fee that is paid per hour or annually to Launchnodes and AWS/Azure
infrastructure fee. If the client uses own infrastructure, only the
Launchnodes license fee applies.

So if I'm understanding this correctly, the user is responsible for either
having access to their own infrastructure, or an account with a third-party
cloud provider... Then Launchnodes will assist in setting up the client
software and validator setup on whichever option the user chooses?


*That is absolutely correct!*

I see your argument of how this is not SaaS, since you don't seem to be
running the hardware yourself... would I be more correct to say this is
somewhat of a consulting service where you help users get set up?

*Yes, you would be correct. However, we make the nodes available as
container-based images and AMIs for our clients to run on their own
infrastructure, public cloud or bare metal that we never have access to. so
we get paid a fixed fiat fee for the Geth Node License, a Beacon node
license (Teku or Prysm) and a validator node license (teku or prysm). We
make being a solo staker easy through both the products and the
consultancy. *

Just following the flow on the website to try and take the "Solo stake on
alternative infrastructure" approach, I progressed as follows:

https://www.launchnodes.com/ -> Run nodes -> Solo stake on alternative
infrastructure -> Start staking [or] Schedule in person consultation

If I choose "Schedule in person consultation" I'm prompted with a Calendly
invite, which seems to fit the idea I just mentioned of a "consultation
service" (which I have nothing against... just thinking how this would fit
into our existing structure, or if maybe this introduces another type of
staking product that we should consider).

*For bare metal and for AWS we provide self-service instructions or we can
provide a consultancy service to help engineering teams. About to launch on
GCP as well. Dont mind being in a new category but really all we do is make
our clients solo stakers.*

If I choose "Start staking" I'm taken directly to AWS checkout... I'm not
sure I understand how to go through this flow without using AWS... would I
need to schedule the consultation?

*Yes, if you don't use AWS and the self-serve set-up instructions you would
need to book a consultation and we then do it for you or help you do it on
the infrastructure of your choice that you own.*
------------------------------

Appreciate you bearing with us here. As I mentioned, mainly just trying to
properly understand the service being offered so we can make sure we
present it to users as accurately as possible for their own protection.

*Thank you for taking the time to understand how we make clients solo
stakers. We want to protect clients as well, so anything more you need from
us please let us know we are happy to help in any way we can.*

**Comment by corwintines** [comment]
> *Yes, you would be correct. However, we make the nodes available as
container-based images and AMIs for our clients to run on their own
infrastructure, public cloud or bare metal that we never have access to. so
we get paid a fixed fiat fee for the Geth Node License, a Beacon node
license (Teku or Prysm) and a validator node license (teku or prysm). We
make being a solo staker easy through both the products and the
consultancy. *

I'm a little unclear on this answer here. What are the fees in relation to these clients? I don't believe you have to pay a license fee to use this software on your own, so wondering how this appears here.

**Comment by andreilicious23** [comment]
Hi Corwin. As per above, we make nodes available as container based images
and AMIs, so clients could run them on their own infrastructure (public
cloud and bare metal). The license includes all the scripts and automated
cloud tools/devops stuff to make configuration and running the opensource
software clients easier and in their own cloud accounts or on bare metal.
We also provide all the software updates through these images and AMIs
along with full time support in case customers struggle with the nodes,
need to make updates and need a professional assessment as to how to
structure the staking architecture that runs on infrasructure they own and
only they have access to. Think Redhat and Linux.

All configuration scripts and files and cloudformation templates are
available for clients to see and inspect before running them. We are open
source.

**Comment by andreilicious23** [comment]
Hi C. Do you need anything else from us at this stage? Looking forward to
your feedback and thanks for the support.

**Comment by andreilicious23** [comment]
Hey @corwintines. Wanted to check if you guys need any other details form us. Happy to assist further.

**Comment by andreilicious23** [comment]
Paul (@wackerow), this is fantastic news. Thank you for your help. Few remarks on the features:

1. Multi client: we offer Teku and Prysm
2. We are permissionless
3. Apart from AWS and Azure we are also on [GCP](https://console.cloud.google.com/marketplace/product/launchnodesltd-public/pre-synced-beacon-node-with-geth-rpc-solo-staking?hl=it&pli=1), and bare metal. 
4. We are open source as per Teku and Prysm, plus all files GCP and AWS related are on github (examples: https://github.com/yashLN/Beacon_Presync and https://github.com/yashLN/Geth_Presync) 
5. Everything else is correct.

**Comment by wackerow** [comment]
Hey @andreilicious23, with the updates I would suggest opening a new issue to track, and could also open a PR... I'll drop my initial thoughts here though:

1. Multi client: we offer Teku and Prysm
> Software enables users to pick from and switch between at least two or more execution clients, and two or more consensus layer clients

Looks like in the original post these were still to come, but if Teku is now an option, then agree here.

2. We are permissionless
> Users do not require any special permission to operate a validator using the software or service

You previously mentioned: "*Yes, if you don't use AWS and the self-serve set-up instructions you would need to book a consultation and we then do it for you or help you do it on
the infrastructure of your choice that you own.*"

I interpret that as two options: Ask you folks, or ask Amazon. I do not see an option where I can use this service without any permission.

3. Apart from AWS and Azure we are also on GCP, and bare metal.

Sounds good, but assuming you're suggesting adding a seventh tag for "GCP"... from a design/UX perspective, I'd suggest not overwhelming with that many tags... I might just bundle Azure/AWS/GCP to "Cloud" or "VPS"

4. We are open source as per Teku and Prysm, plus all files GCP and AWS related are on github
> Essential code is 100% open source and available to the public to fork and use

Okay, was just looking at the example repos you posted... When opening a new issue, please do us a favor and link out to any the repos that are involved, and disclose if there are any involved that are still closed source.
