### ISSUE TITLE
Tornado.cash old website can't be reached

### ISSUE THREAD

**Issue by Rakeshmonkee** [ethereum/ethereum-org-website#7498]
- When browsing the finance/payments category under the 'Explore Dapps', tornado cash is an option, but upon clicking the "Go" button to visit the site, it can no longer be accessed
- Adding the new tornado cash link would fix this issue

![tornado cash](https://user-images.githubusercontent.com/89455475/185583266-690a750a-2bd2-418d-bd82-aa2cf9fb0aab.png)

_[Edit: note from a maintainer - we welcome discussion on this topic but we are not currently accepting PRs with solutions until we reach a consensus on the best course of action. Please read this comment for context.](https://github.com/ethereum/ethereum-org-website/issues/7498#issuecomment-1237010925)_

**Comment by Rakeshmonkee** [comment]
https://github.com/Rakeshmonkee/ethereum-org-website

**Comment by VictorBerryy** [comment]
@Rakeshmonkee have you reach out to their live chat support

**Comment by Rakeshmonkee** [comment]
> @Rakeshmonkee have you reach out to their live chat support 

No, the tornado cash offical website is down. So I have replaced it with the tornadocash.eth.link website

**Comment by thegamebegins25** [comment]
Tornado Cash has been shut down by the US government, it is now ILLEGAL to use it if you are a citizen of the US. While ipfs links exist, I think we should remove the entire Tornado Cash entry due to it being ILLEGAL.

**Comment by Rakeshmonkee** [comment]
> Tornado Cash has been shut down by the US government, it is now ILLEGAL to use it if you are a citizen of the US. While ipfs links exist, I think we should remove the entire Tornado Cash entry due to it being ILLEGAL. In #7597, I deleted the Tornado Cash entry. 

While it's ILLEGAL to use tornado cash in the US, I don't believe any other countries have sanctioned it. So instead of deleting this from the ethereum website, adding a pop up before entering tornado cash to warn people that it is sanctioned in the countries that have banned it would be a better move.

**Comment by thegamebegins25** [comment]
That would be a good move, but we would have to find the IPFS hash of Tornado Cash. Do you think we should add a popup for all users, or just remove it entirely if your IP is located in the US?

**Comment by Rakeshmonkee** [comment]
> That would be a good move, but we would have to find the IPFS hash of Tornado Cash. Do you think we should add a popup for all users, or just remove it entirely if your IP is located in the US?

If we remove it entirely for all users using an ip located in the US, we wouldn't need to add a popup. But if you want to go the extra mile you could add a popup warning all people outside of the US that it has been sanctioned by the US government.

**Comment by thegamebegins25** [comment]
I think the popup idea is a good idea, but I don't have my computer now so do you think anyone else could program it?

**Comment by Rakeshmonkee** [comment]
> I think the popup idea is a good idea, but I don't have my computer now so do you think anyone else could program it?

I could have a try, or if I can't do it, I'll reference it in their discord

**Comment by thegamebegins25** [comment]
I think that sounds good. If no one does it by next week I will probably be able to program it.

**Comment by minimalsm** [comment]
Hey @thegamebegins25 @Rakeshmonkee @VictorBerryy. Thanks for all of the discussion around this.

The quick update is that we're still discussing the best approach to take here. I believe leaving a broken link on the website temporarily is fine, over making hasty decisions in what is a contentious and sensitive topic.

Personally, I don't believe we should remove TornadoCash from the website entirely, but we should also be wary of sending users falling under certain regulatory juridiscations to a locally sanctioned website without clearly making them aware of the implications of this. 

Unfortunately, this leaves us in limbo land for now. We welcome thoughtful discussion on this.

**Comment by Rakeshmonkee** [comment]
> Hey @thegamebegins25 @Rakeshmonkee @VictorBerryy. Thanks for all of the discussion around this.
> 
> 
> 
> The quick update is that we're still discussing the best approach to take here. I believe leaving a broken link on the website temporarily is fine, over making hasty decisions in what is a contentious and sensitive topic.
> 
> 
> 
> Personally, I don't believe we should remove TornadoCash from the website entirely, but we should also be wary of sending users falling under certain regulatory juridiscations to a locally sanctioned website without clearly making them aware of the implications of this. 
> 
> 
> 
> Unfortunately, this leaves us in limbo land for now. We welcome thoughtful discussion on this. 

Agreed

**Comment by thegamebegins25** [comment]
> > Hey @thegamebegins25 @Rakeshmonkee @VictorBerryy. Thanks for all of the discussion around this.
> > 
> > 
> > 
> > The quick update is that we're still discussing the best approach to take here. I believe leaving a broken link on the website temporarily is fine, over making hasty decisions in what is a contentious and sensitive topic.
> > 
> > 
> > 
> > Personally, I don't believe we should remove TornadoCash from the website entirely, but we should also be wary of sending users falling under certain regulatory juridiscations to a locally sanctioned website without clearly making them aware of the implications of this. 
> > 
> > 
> > 
> > Unfortunately, this leaves us in limbo land for now. We welcome thoughtful discussion on this. 
> 
> Agreed

Same

**Comment by lukassim** [comment]
Closing this issue as Tornado cash has since been removed from the dapps page
