### ISSUE TITLE
Add layerswap.io to "How to get onto a layer 2" section

### ISSUE THREAD

**Issue by arkoc** [ethereum/ethereum-org-website#7504]
Is your feature request related to a problem? Please describe.

On the Layer2 page on ethereum.org, under the "How to get onto a layer 2" section, I noticed that the drop-down menus to select the layer 2 network have limited options, when in fact almost all CEXs can be bridged to almost any L2 Exchange. 

Describe the solution you'd like

With Layerswap.io, all of those layer 2 networks can be reached by nearly any CEX. Layerswap.io is instant and gasless, users only pay a small fee up to 10x cheaper than a traditional transfer. It would be nice to list Layerswap as an option in "Check exchanges that support L2" under the "How to get onto a layer 2" section.

Describe alternatives you've considered

Additional context
<img width="440" alt="image" src="https://user-images.githubusercontent.com/106245135/185391506-18d79078-a7a9-4881-8c21-e1ca1fdf2380.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/106245135/185391569-801dd602-d51a-4421-a6d3-d2b9a1c162a6.png">

**Comment by minimalsm** [comment]
Hey @arkoc, sorry for the delay here. I think adding Layerswap in some capacity makes sense, but it will require some design thinking. 

However, I do think we should differentiate native exchange support via simple transfers from interacting with smart contracts/bridges. Any thoughts @corwintines?
