### ISSUE TITLE
Geth Node

### ISSUE THREAD

**Issue by andreilicious23** [ethereum/ethereum-org-website#7528]
Before suggesting a staking product or service, make sure you've read [our listing policy](/contributing/adding-staking-products/).

Only continue with the issue if the staking product meets the criteria listed there.

If it does, complete the following information which we need to accurately list the product/service.

**Product type**

- [*] Node/client tooling
- [ ] Key management
- [ ] Staking as a service
- [ ] Staking pool
- [ ] Other: (describe)

**Geth Node**

**![Launchnodes](https://logo-public.s3.us-east-2.amazonaws.com/app+icon.png)**

**Description**
Pre-synced Geth Node on AWS for staking ETH and other Layer 2 solutions. A dedicated Geth node makes it easier and cheaper to stake ETH. It is an execution layer client, used for staking ETH connecting to all consensus layer clients. 

**[Website](https://aws.amazon.com/marketplace/pp/prodview-e7dmfikm7s4zs?sr=0-2&ref_=beagle&applicationId=AWSMPContessa)**

**If software is involved, is everything open source?**

- [ ] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ ] No, code is closed source
- [*] N/A, no custom software is involved

**Is the project a fork? If yes, which project was forked?**
No

**Is the product out of _beta_ development?**
Yes

**What wallets support the product or service?**
All Ethereum Launchpad approved wallets

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**
32ETH or multiples of 32ETH

**If a service, what are the fees associated with using the service?**
Annual license fee

**If the product or service involved a liquidity token, what are the tokens involved?**
Not applicable

**What date did the project or service go live?**
July 2022

**Has the project undergone an external security audit?**
Internal AWS marketplace audits. Listing is only allowed after the product has gone through AWS security audits. These are not shared, but if products fail the audit, they are not listed.

**Has the project undergone any security bug bounties?**
No

**Is the project being actively maintained?**
Yes

**Is the product or service free of trusted/human intermediaries?**
Yes

**If a pooled staking service, can users participate as a node operator without permission?**
Not applicable

**If listing a staking-as-a-service, are users required to sign-up for an account?**
Not applicable

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**
No. Only the client holds signing and withdrawal keys. The user maintains access to all the keys

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**
Not applicable

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**
Geth node supports all CL clients

**What platforms are supported?**
Linux, macOS, Windows

**What user interfaces are supported?**
CLI, AWS console 

**Social media links**
Twitter: https://twitter.com/launchnodes
YouTube: https://www.youtube.com/channel/UC5tEUUlx11httS9Y9RvIzJw
LinkedIn: https://www.linkedin.com/company/67972177/
Discord: https://discord.gg/w5pjfWqdyT

**Comment by corwintines** [comment]
Duplicate: https://github.com/ethereum/ethereum-org-website/issues/7483
