### ISSUE TITLE
Adding DAOHQ to list of DAO apps and tools on ethereum.org

### ISSUE THREAD

**Issue by NNDEV1** [ethereum/ethereum-org-website#7529]
Hey Ethereum devs! I'm Nalin, a data analyst at DAOHQ.

I propose an addition to the [https://ethereum.org/en/dao/#join-start-a-dao](https://ethereum.org/en/dao/#join-start-a-dao) page, specifically in "Join a DAO" for [daohq.co](https:daohq.co). DAOHQ is a DAO marketplace and a one-stop-shop to find, invest and vote in extraordinary DAOs. 

Often time when joining a DAO users have to go through the tedious process of first finding the DAO, then deciding to invest in the DAO through available info and on-chain data(on-chain data is hard to find on smaller DAOs), then navigating to an CEX or DEX and swapping for the token, and then lastly finding a website to use their tokens to vote on proposals.

DAOHQ removes the need for all this confusion by providing database of over 1000 DAOs and information on every single DAO which has been manually reviewed by our team, the ability to buy and sell your token with efficient gas fees, and finally voting with your tokens. 

**Why add DAOHQ to ethereum.org?**(The must-haves)

* We currently have support for the biggest Ethereum wallets including Metamask and Coinbase and have support for many L2s including Binance Smart Chain, Avalanche, and Polygon.
* Our product is currently being audited by DeFi Safety & OtterSec
* DAOHQ has been live for over 6 months and had significant user testing, you can try it out yourself too!
* Our team is incredibly active pushing out changes every single day! We have a ton of features that are being rolled out right now including an ERC20 Launchpad for DAOs, DEX tracking, token holders, and even sentiment analysis.
* All of our listing information is always honest. We are not open-source yet but plan to open-source some of our code very very soon. As for any data on the website, all of our data is truthfully fetched either on-chain or from trusted APIs.

**Why DAOHQ is a great fit**(The nice-to-haves)

* Our wallet connecting experience is seamless and we support the major wallets listed on the Ethereum website. 
* Users can try out our app anytime and see the results for themselves!
* Our onboarding experience is extremely easy with resources including DAOHQs own DAO Knowledge Base([daohq.co/learn](https://www.daohq.co/learn)), DAO Dictionary([daohq.co/learn/dictionary](https://www.daohq.co/learn/dictionary)), FAQ ([daohq.co/faq](https://www.daohq.co/faq)), and our very own blog([daohq.co/blog](https://www.daohq.co/blog)).
* DAOHQ is just a website to facilitate trade of the tokens, we hold nothing with us and you can view all your invested tokens through your own wallet or our DAO Dashboard.
* There are absolutely no geographic limitations with DAOHQ! As long as you have a wallet you can participate in any DAO available, even our team works in various timezones across the world
* We have a ([Discord](https://discord.gg/YKYyUVSmzc)) with a rapidly growing community of over 1100 members and amazing hosted events.

**Does DAOHQ paralyze the user with choices on the ethereum website??**

* There is only one external tool provided on the "Join a DAO" section of the website and I believe the user actually lacks choices in this category rather than providing too many. DAOHQ can help saturate this section.
* Our own website provides users with simple way to dive into the world of DAOs. We keep our UI/UX simple & friendly to non-crypto natives. We believe this will be valuable to learning about DAOs from the Ethereum website.

Side note: Our co-founder Emmet Halm met with Vitalik Buterin and he said he was bullish on DAOs!

**Comment by nloureiro** [comment]
It looks like this project is not operating anymore
The website is off, and no social media activity
![Screen Shot 2024-02-22 06 35 59 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/a4a447a8-8fb6-4d7c-91be-b4e46d5b613e)
