### ISSUE TITLE
Add PWN to the list of lending dapps 

### ISSUE THREAD

**Issue by JosefJ** [ethereum/ethereum-org-website#7546]
**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

PWN Protocol smart contracts have been audited by Extropy.io. The audit can be found here: https://audit.pwn.xyz/ 
The contracts are fully documented within the code and readmes: https://github.com/PWNFinance/pwn_contracts
Documentation export can be found here: https://docs.pwn.xyz

**Is your dapp open source?**

Yes, PWN Protocol is fully open-source. You can see [our GitHub repository.](https://github.com/PWNFinance/pwn_contracts) 

**Can a user access the dapp without creating an account?**

Yes.

**Are dapp funds non-custodial?**

Yes. In no way PWN Protocol relies on the PWN Platform and the smart contracts are fully immutable, with no upgradability, nor parametrization. To make it easier for users to use the PWN Protocol we've created comprehensive [documentation of our smart contracts](https://dev-docs.pwn.xyz/). 

**Do you offer community support?**

Yes, on our discord we have a channel dedicated to this purpose. But of course, users can ask us anywhere (for eg. on Twitter) and we're glad to help. 

**Describe any geographical restrictions on usage of your dapp**

To use the PWN Platform (not the protocol) users have to accept [Terms and Conditions](https://pwn.xyz/terms-and-conditions) due to compliance reasons. 

> By using the Service, you inherently agree to use the Service according to the law in all applicable jurisdictions and acknowledge that you yourself bear all legal obligations associated with using the Service.

**Dapp title**

PWN

**Dapp description**

PWN is a hub for peer-to-peer (P2P) loans backed by digital assets. You can use your fungible tokens or NFTs as collateral, or invest in loans and generate returns. Also, there's no risk of liquidation before the loan expires. The contracts don't have any external dependancies like on-chain oracles either. 

**Dapp logo**

https://pwn.xyz/PWN_logo.svg

**Brand colour**

#05CFB9

**Comment by corwintines** [comment]
Hey @JosefJ, sorry taking so long on this. Created a PR now: https://github.com/ethereum/ethereum-org-website/pull/8245

**Comment by corwintines** [comment]
Closed with above PR
