### ISSUE TITLE
4X Multiplier banner for https://bounty.ethereum.org

### ISSUE THREAD

**Issue by fredriksvantes** [ethereum/ethereum-org-website#7547]
With https://blog.ethereum.org/2022/08/24/mainnet-merge-announcement/ going live, we would like to have something visual (such as a a banner) on https://bounty.ethereum.org to make it clear also on the bounty website that there is now a 4x multiplier for rewards (up to $1 mm). Given that this multiplier is only active until the 8th of September it would be highly appreciated if it could be activated this week.

Thank you!

**Comment by minimalsm** [comment]
Suggested copy: `All Merge-related bounties submitted before September 8th receive a 4x bonus multiplier (up to 1 million USD). [Learn more about the bonus](~blog link~).`

**Comment by minimalsm** [comment]
Or: `All Merge-related bounties currently receive a 4x bonus multiplier (up to 1 million USD). [Learn more about the bonus](~blog link~).`
