### ISSUE TITLE
Developer Resource Update - Solidity Crash Course (Video, Free)

### ISSUE THREAD

**Issue by finxter** [ethereum/ethereum-org-website#7548]
**Is your feature request related to a problem? Please describe.**

Many of our 100,000+ coding students are interested in learning Solidity so they can build apps on ETH and create value for themselves and their communities.

**Describe the solution you'd like**

We have created a video tutorial series with free articles that have already helped thousands of our students learn Solidity:
https://blog.finxter.com/solidity-crash-course/

We found that such a concise Crash Course is required because unlike other programming languages (such as Python, JavaScript, C++), Solidity documentation is still very sparse, especially video content.

To help our students, we have created this free video course to get started with ETH development.

**Describe alternatives you've considered**

**Additional context**

The free course is available here:
https://blog.finxter.com/solidity-crash-course/

And we'd love to see it referenced on the Learning Tools page:
https://ethereum.org/en/developers/learning-tools/

This will help us reach more people by educating them in the creation of Solidity apps to the benefit of our community of coders and the overall Ethereum ecosystem.

Thanks for the great work with the site! ❤️ 🦇🔊

**Comment by minimalsm** [comment]
Hey @finxter, thanks for taking the time to open this issue.

I had a chance to explore Finxter and it’s a great general-purpose learning platform.

As far as its integration as a 'learning tool' for Ethereum/Solidity: currently, our focus is on resources that are highly specific to Ethereum and Solidity to provide a more targeted learning experience. While Finxter offers quality tutorials, it might not align precisely with this specific objective.

For now we'll hold off on adding it to the site to avoid any potential overlap with the existing introductory Solidity tutorials we have.

I'm closing this issue for now, but please don't hesitate to reach out with more ideas in the future.  Thanks again, @finxter!

**Comment by minimalsm** [comment]
@all-contributors please add @finxter for ideas

**Comment by finxter** [comment]
Thanks, @minimalsm - appreciate the kind words. Keep up the good work!
