### ISSUE TITLE
Lack of effectiveGasPrice in docs

### ISSUE THREAD

**Issue by kirqz23** [ethereum/ethereum-org-website#7549]
Hey, 

There is no effectiveGasPrice in the result for TransactionReceipt and its explanation.

https://github.com/ethereum/ethereum-org-website/blob/785c473b346df66b8d733ec79b83d60a5411d470/src/content/developers/docs/apis/json-rpc/index.md?plain=1#L1205-L1218

**Comment by corwintines** [comment]
Closed with above PR
