### ISSUE TITLE
Quiz content: NFTs page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#7553]
This is a sub-task of: https://github.com/ethereum/ethereum-org-website/issues/7461

Prepare content for quiz on page:
https://ethereum.org/en/nft/

Each question should be related to the most important aspects of the page. There can be a unique explanation for each correct/incorrect answer.

**Comment by qbzzt** [comment]
Which of these assets is non fungible?

A. A twenty dollar bill
B. A 1 kg package of peanuts
**C. A drawing of a stickman drawn by a five year old in kindergarten**
D. A copy of The Mona Lisa

**Explanation**

An asset is non fungible if there is only one of it. The kid's drawing is unique and more valuable than those of other kids to the kid's parents. But one twenty dollar bill is as good as another, one package of peanuts is as good as another, and while The Mona List itself is unique, a copy of it is not.

**Comment by qbzzt** [comment]
Are NFTs transferrable?

A. No, never
**B. It depends. An NFT representing a certificate of completion of a course of study likely to be transferrable. An NFT representing ownership of artwork is likely won't be transferrable.**
**C. It depends. An NFT representing ownership of artwork is likely to be transferrable. An NFT representing a certificate of completion of a course of study likely won't be transferrable.**
D. Yes, always.

**Explanation**

Like any other asset on Ethereum, NFTs are managed by programs called smart contracts. The smart contract can be written to allow or disallow the transfer of the NFT, depending on what the NFT represents. It makes sense to allow people who buy artwork to sell it later. However, an NFT that represents an individual achievement should not be sellable to people who did not achieve the same.

**Comment by qbzzt** [comment]
Can ownership of an NFT be revoked?

A. No, never
B. Only if the NFT is transferrable
**C. Only if the NFT contract permits revocation**
D. Yes, there is no way to make a non-revokable NFT

**Explanation:**

NFTs are managed by smart contracts. If the smart contract includes provisions that allow for NFTs managed by it to be revoked, they are revocable. If it doesn't (and you can check that before minting or buying NFTs of that account), they aren't.

**Comment by minimalsm** [comment]
Closing this out as part of #8094. I've migrated question suggestions here [to this Notion doc](https://www.notion.so/efdn/Review-Ori-s-learning-quizzes-suggestions-on-issue-79027459ef9f4f0a9b5ef384f3faf941) and will be updating decisions here.
