### ISSUE TITLE
Quiz content: What is Ether?

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#7555]
This is a sub-task of: https://github.com/ethereum/ethereum-org-website/issues/7461

Prepare content for quiz on page:
https://ethereum.org/en/eth/

Each question should be related to the most important aspects of the page. There can be a unique explanation for each correct/incorrect answer.

**Comment by qbzzt** [comment]
Other than yourself, who can transfer ETH out of your account (to which you hold the private key)?

A. Nobody
**B. Anybody who has your private key or recovery phrase**
C. Your bank.
D. A court order.

**Explanations:**

A. We wish this were true, but you identify to the Ethereum network using your private key, which is created from your recovery phrase. As a result, anybody with the private key or recovery phrase can transfer ETH from your account.
C & D. Not without your private key or recovery phrase. There is no way to create a valid transaction to transfer ETH from an account without the private key.

**Comment by qbzzt** [comment]
What are the *technical* restrictions on sending ETH to other countries? Choose the most accurate answer.

A. You have to comply with the law in the destination country (the one where your recipient is located)
B. You have to comply with the law in the source country (where you are located)
C. You have to comply with the laws of both source and destination countries
D. There are no technical restrictions

**Explanations: **

A. You send to an address. You don't need to even know in what country the recipient is located.
B. and C. While it is a good idea to comply with your local law, there is no technical mechanism that restricts your ability to send ETH anywhere. Note that while you *can* send ETH wherever you wish, the transaction is going to live on the blockchain forever, and be available to anybody to see, including the government that might prosecute you for disobeying its laws.
D. This is correct, there are no technical restrictions. Note that while you *can* send ETH wherever you wish, the transaction is going to live on the blockchain forever, and be available to anybody to see, including the government that might prosecute you for disobeying its laws.

**Comment by AlanGit940** [comment]
crypto scams everywhere , be careful who you invest with , I feel peoples pain because I was also in this shoes , got scammed of my savings by an instagram broker who lured me into investing on their website with promise to make times 3 of it in a month and bonuses , time to withdraw funds , I found out it was fake website and the took all the money a lot of other people too , thanks to an amazing genius , a freelance digital expert hacknetcyberprofessor10 at g mail dot com , I got the contact through a Facebook friend and I was happy that he recovered my funds.

**Comment by konopkja** [comment]
@minimalsm  the explanation here should be improved as it is quite confusing i think
![image](https://user-images.githubusercontent.com/100724231/199711485-0f6ad91d-d012-4620-845e-6bd836b22dd4.png)

**suggestion**:
While this is correct, it's only one of the reasons ETH is valuable, and therefore there is a better answer. 

what do you think?

**Comment by minimalsm** [comment]
> While this is correct, it's only one of the reasons ETH is valuable, and therefore there is a better answer.

How about: This answer is partially correct, but it's only one of the reasons ETH is valuable. @konopkja

**Comment by minimalsm** [comment]
@konopkja let's discuss in #8477
