### ISSUE TITLE
Quiz content: What is a wallet?

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#7556]
This is a sub-task of: https://github.com/ethereum/ethereum-org-website/issues/7461

Prepare content for quiz on page:
https://ethereum.org/en/wallets/

Each question should be related to the most important aspects of the page. There can be a unique explanation for each correct/incorrect answer.

**Comment by qbzzt** [comment]
You just got a wallet and created your Ethereum account. Should you write any information down on a piece of paper to put in a secure place? If so, what?

A. You account address
B. Your account public key
C. Your account private key
**D. Your account recovery phrase**

**Explanations**

A. and B. Your address and public key are not secret. You could post them online, you don’t need to keep them secure.
C. While the private key can let you access a single account, the recovery phrase lets you get the private keys for multiple accounts, so if you might need to use multiple accounts at some point it is better to keep the recovery phrase.

**Comment by qbzzt** [comment]
Which kind of wallet, if any, does not require you to keep a safe copy of your recovery phrase?

A. Physical wallet
B. Mobile wallet
C. Desktop wallet
D. There is no such wallet, you should ALWAYS have a backup copy of your recovery phrase.

**Explanation**

A. Physical devices can be lost or damaged.
B and C. Computers (including smartphones) can lose the information on them due to physical damage, accidental erasure, etc.

**Comment by qbzzt** [comment]
Can you use multiple wallets with the same account?

A. No
B. Up to two, but not more than that
C. Yes, as long as they are all the same type (you need one account for desktop and another for mobile, for example)
D. Yes, any number using any type of wallet,

**Explanation (for all)**

All wallets let you import a recovery phrase, so you can use the same recovery phrase, and therefore Ethereum account(s), from whatever wallet combination you want.

**Comment by minimalsm** [comment]
Closing this out as part of #8094. I've migrated question suggestions here [to this Notion doc](https://www.notion.so/efdn/Review-Ori-s-learning-quizzes-suggestions-on-issue-79027459ef9f4f0a9b5ef384f3faf941) and will be updating decisions here.
