### ISSUE TITLE
Quiz content: Layer 2 page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#7558]
This is a sub-task of: https://github.com/ethereum/ethereum-org-website/issues/7461

Prepare content for quiz on page:
https://ethereum.org/en/layer-2/

Each question should be related to the most important aspects of the page. There can be a unique explanation for each correct/incorrect answer.

**Comment by qbzzt** [comment]
What service(s) does Ethereum (Layer 1) give to Layer 2 solutions?

A. Reliable execution
B. Internal storage
**C. Data integrity and data availability**
D. Data integration, data availability, and internal storage.

**Comment by qbzzt** [comment]
What is the major feature provided by Layer 2 solutions that Ethereum, by itself, cannot provide?

A. Security
B. Decentralization
**C. Scalability**
D. Uptime (reliability)

**Explanation:**

Ethereum optimizes for security and decentralization at the base layer, and decentralization gives us uptime automatically. A decentralized system with thousands of nodes will have a large number of nodes running at any point in time. Layer 2 solutions typically provide scalability by relying on Ethereum for security, and being less decentralized (but relying on mechanisms running on Ethereum to ensure the execution and internal storage are correct).

**Comment by qbzzt** [comment]
Which type of layer 2 solution relies on economic incentives to ensure transactions are executed correctly?

A. Zero-knowledge rollups
**B. Optimistic rollups**
C. Sidechains
D. Validiums

**Explanation:**

Optimistic rollups have sequencers that post the transactions' data and their results (in state root form) on Ethereum, and verifiers that challenge them. Sequencers that post incorrect results, and verifiers that dispute correct results, pay a penalty. Sequencers that post correct results, and verifiers that dispute incorrect results, get rewarded. This is using economic incentives to encourage honesty.

**Comment by qbzzt** [comment]
Which type of layer 2 solution relies on mathematics to ensure transactions are executed correctly?

**A. Zero-knowledge rollups**
B. Optimistic rollups
C. Sidechains
D. Validiums

**Explanation:**

Zero-knowledge rollups post zero-knowledge proofs that they processed their transactions correctly. Producing those proofs requires a lot of computation, and is not feasible to do on chain. However, to verify the proof only requires a relatively simple computation that can be done on-chain easily.

**Comment by minimalsm** [comment]
Closing this out as part of #8094. I've migrated question suggestions here [to this Notion doc](https://www.notion.so/efdn/Review-Ori-s-learning-quizzes-suggestions-on-issue-79027459ef9f4f0a9b5ef384f3faf941) and will be updating decisions here.
