### ISSUE TITLE
Suggest a wallet: Zerion

### ISSUE THREAD

**Issue by 101717** [ethereum/ethereum-org-website#7591]
### Wallet name

Zerion Wallet

### Wallet description

Zerion Wallet helps users manage their Ethereum portfolios, including tokens, NFTs and positions across DeFi protocols.

### Wallet logo

![Zerion Logo – Symbol (1)](https://user-images.githubusercontent.com/37593987/186878373-70455639-8361-4503-81da-63e1ffaa9cc2.svg)

### Background color for brand logo

#2962EF

### URL to the project

https://zerion.io/

### When did the wallet go live to users?

26.05.2022

### Does the wallet have an active development team?

Yes, https://github.com/zeriontech

### Is the wallet globally accessible?

No KYC

### Is the wallet available in multiple languages?

English, Russian, Chinese, French, German, Spanish

### What social links are there for the project?

[Twitter](https://twitter.com/zerion_io)
[Discord](https://zerion.io/discord)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, both iOS and Android

[iOS](https://apps.apple.com/us/app/zerion-crypto-defi-wallet/id1456732565?_branch_match_id=1041613680134470197&utm_source=zerion_homepage&utm_campaign=wallet_launch&utm_medium=homepage&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXz8nMy9arSi3KzM%2FTy8zXTzQ0zDfz9DPIKkwCANwiexEiAAAA)
[Android](https://play.google.com/store/apps/details?id=io.zerion.android&_branch_match_id=1041613680134470197&utm_source=zerion_homepage&utm_campaign=wallet_launch&utm_medium=homepage&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXz8nMy9arSi3KzM%2FTy8zXtzQwzDfz9DPIKkwCAIN1xDwiAAAA)

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes

[Mac](https://apps.apple.com/us/app/zerion-crypto-defi-wallet/id1456732565?_branch_match_id=1041613680134470197&utm_source=zerion_homepage&utm_campaign=wallet_launch&utm_medium=homepage&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXz8nMy9arSi3KzM%2FTy8zXTzQ0zDfz9DPIKkwCANwiexEiAAAA)

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Not yet but it is coming for Chrome 

### Is it a hardware wallet?

No, but it has Ledger compatibility

### Is the source code for the wallet fully open-source?

Not yet

### Who holds the private keys?

Zerion is fully self-custodial! Users' private keys are encrypted on their devices and are not broadcast anywhere. Our users would be able to access their funds even if Zerion as a company disappeared

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We've been audited by Cure53 and SecFault security

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, users can connect to dapps https://help.zerion.io/en/articles/6271651-connecting-to-dapps

### Does the wallet support swaps directly?

Yes, https://help.zerion.io/en/articles/4055273-how-do-i-get-started

### Does the wallet support multi-chain networks?

Yes, https://help.zerion.io/en/articles/5083547-how-does-zerion-s-exchange-work

### Does the wallet support Ethereum layer 2 networks?

Yes, https://help.zerion.io/en/articles/5083547-how-does-zerion-s-exchange-work

### Does the wallet allow the user to customize gas fees?

Yes, https://help.zerion.io/en/articles/4057577-what-are-gas-fees

### Does the wallet support sending transactions to ENS addresses?

Yes, there is no documentation but it it possible through the "Send" tab

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, https://help.zerion.io/en/articles/6251818-how-to-purchase-crypto-with-cash

### Does the wallet support withdrawals to fiat?

Not yet

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

inbox@zerion.io, @glebshumakov on telegram or nahuel 🇦🇷#6269 on Discord

### Does the wallet have a dedicated support team?

Yes! You could redirect them to our [help center](https://help.zerion.io/en/)

We usually respond within 30 minutes 

### What educational resources/documentation do you provide to users?

We have got a lot of help center [articles](https://help.zerion.io/en/) 

### Does the wallet have any integrated tools not mentioned above?

We offer advanced NFT features, such as native NFT management and browsing

**Comment by minimalsm** [comment]
Closed by #7638
