### ISSUE TITLE
Figment Inc.

### ISSUE THREAD

**Issue by figmentworld** [ethereum/ethereum-org-website#7604]
Before suggesting a staking product or service, make sure you've read [our listing policy](/contributing/adding-staking-products/).

Only continue with the issue if the staking product meets the criteria listed there.

If it does, complete the following information which we need to accurately list the product/service.
**Product type**

- [ ] Node/client tooling
- [ ] Key management
- [x] Staking as a service
- [ ] Staking pool
- [ ] Other: (describe)

**Name**

 Figment Inc.

**Logo**

 

**Description**
![figment-logo-black (1)](https://user-images.githubusercontent.com/111998391/187054853-b40c4d28-2339-42af-aaff-a05b4e9dd3a8.svg)

 Figment is one of the world’s leading providers of blockchain infrastructure. Our mission is to empower investors and developers to build Web3, the next generation of the Internet.

**Website**

 https://www.figment.io/

**If software is involved, is everything open source?**

- [ ] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ ] No, code is closed source
- [x] N/A, no custom software is involved

**Is the project a fork? If yes, which project was forked?**

**Is the product out of _beta_ development?**

**What wallets support the product or service?**

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**

 minimum is 32 ETH

**If a service, what are the fees associated with using the service?**

**If the product or service involved a liquidity token, what are the tokens involved?**

**What date did the project or service go live?**

**Has the project undergone an external security audit?** yes

**Has the project undergone any security bug bounties?**

 

**Is the project being actively maintained?**

 yes

**Is the product or service free of trusted/human intermediaries?**

 We are non custodial

**If a pooled staking service, can users participate as a node operator without permission?**

 By company

**If listing a staking-as-a-service, are users required to sign-up for an account?** No

 

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?** 

  Figment holds signing keys, customer holds withdrawal keys

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**

 Lighthouse

**What platforms are supported?**

 Linux, macOS, Windows, iOS

**What user interfaces are supported?**

 Browser

**Social media links**

Twitter: https://twitter.com/Figment_io
Discord (Dev community): https://discord.gg/5KPwwWB2
Telegram (Staking Hub): https://t.me/StakingHub
Website: https://www.figment.io/

**Comment by corwintines** [comment]
Sorry for letting this go stale @figmentworld. Adding this to grooming

**Comment by wackerow** [comment]
Hello @figmentworld, my apologies as well for letting this go. Appreciate you submitting, just have a few clarifying questions here then we can get this moving along:

---

> Is the product out of beta development?

I'm assuming yes but would like to confirm.

> If a service, what are the fees associated with using the service?

"Figment's commission for staking ETH is tailored to each customer based on their staking volume." Just confirming this—sounds like the fee is variable, correct?

> What date did the project or service go live?

...to confirm the "battle tested" indicator.

> Has the project undergone an external security audit? yes

Please provide link to a publicly available report 🙏 

> We are non custodial

Could you help clarify, does the user have access to the signing keys? And is Figment using type `0x00` BLS withdrawal credentials (in which case, does the user have access to these keys?), or are we using type `0x01` credentials that point to an execution address?

---

At the moment, seeing this as the breakdown for the SaaS indicators on the site:

OPEN SOURCE: No
AUDITED: Yes (with link 🙏)
BUG BOUNTY: No
BATTLE TESTED: ?
PERMISSIONLESS: No
DIVERSE CLIENTS: No
SELF CUSTODY: Yes?

**Comment by wackerow** [comment]
@figmentworld Hey! Just touching base on this... any update re clarifying questions above?

**Comment by wackerow** [comment]
Hey @figmentworld, haven't heard back in some time so going to close this for now. Please feel free to re-open with some clarification at your convenience.
