### ISSUE TITLE
Added Zero Services GmbH to nodes-as-a-service

### ISSUE THREAD

**Issue by zeroservices** [ethereum/ethereum-org-website#7607]
Before suggesting a staking product or service, make sure you've read [our listing policy](/contributing/adding-staking-products/).

Only continue with the issue if the staking product meets the criteria listed there.

If it does, complete the following information which we need to accurately list the product/service.

**Product type**

- [ ] Node/client tooling
- [ ] Key management
- [x] Staking as a service
- [ ] Staking pool
- [ ] Other: (describe)

**Name**
Zero Services GmbH

**Logo**

**Description**
Zero Services GmbH is a supplier of managed blockchain services.

**Website**
www.zeroservices.eu

**If software is involved, is everything open source?**

- [ ] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ ] No, code is closed source
- [X] N/A, no custom software is involved

**Is the project a fork? If yes, which project was forked?**

**Is the product out of _beta_ development?**

**What wallets support the product or service?**

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**

**If a service, what are the fees associated with using the service?**
variable, based on customer requirements

**If the product or service involved a liquidity token, what are the tokens involved?**

**What date did the project or service go live?**

**Has the project undergone an external security audit?**

**Has the project undergone any security bug bounties?**

**Is the project being actively maintained?**

**Is the product or service free of trusted/human intermediaries?**
yes

**If a pooled staking service, can users participate as a node operator without permission?**

**If listing a staking-as-a-service, are users required to sign-up for an account?**

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**

**What platforms are supported?**

**What user interfaces are supported?**

**Social media links**
https://twitter.com/zeroservices_eu

**Comment by wackerow** [comment]
Hey @zeroservices, apologies for delay here, appreciate the submission. Need some help on this one... all I can gather from your submission answers is that this is a "supplier of managed blockchain services" with variable fees, and is reported to be trustless. Could you please fill out the form for all SaaS related questions?

---

**Logo**

Provide an SVG or hi-res transparent PNG.

**Is the project a fork? If yes, which project was forked?**

Provide information about if the project is a fork.

**Is the product out of _beta_ development?**

Provide information as to where the product is in the development lifecycle

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**

Provide any details related to ETH requirements, any other staking requirements, and any fees related to the service

**If the product or service involved a liquidity token, what are the tokens involved?**

Include token abbreviation and contract address for any tokens involved

**What date did the project or service go live?**

Provide proof to substantiate the date of when the product or service became available to the public

**Has the project undergone an external security audit?**

Provide a link to a report or repo. If none, are there plans to be audited?

**Has the project undergone any security bug bounties?**

Provide a link to a report or repo. If none, are there plans to hold a bug bounty?

**Is the project being actively maintained?**

Is there an active team developing the project?

**Is the product or service free of trusted/human intermediaries?**

Please expand. Disclose any steps in a stakers journey that depend on trusting humans with the keys to their funds or distribution of rewards.

**If a pooled staking service, can users participate as a node operator without permission?**

Is permission to run a node controlled by an individual, company or DAO?

**If listing a staking-as-a-service, are users required to sign-up for an account?**

List any permissions needed for a user to access the service.

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**

What keys does the user maintain access to? What keys does the service gain access to? Are type `0x00` BLS keys being used, or type `0x01` pointing to an execution address? Who chose/controls that address?

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**

This question is being updated to include SaaS... Please provide clarity on breakdown of client software being used by the service for sake of client diversity.

**Comment by zeroservices** [comment]
> **Logo**
https://www.zeroservices.eu/images/ZERO_Services_White_below.svg
> 
> **Is the project a fork? If yes, which project was forked?**
No.

> **Is the product out of _beta_ development?**
Yes.

> **If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**
Minimum 32ETH requirement. 

> **If the product or service involved a liquidity token, what are the tokens involved?**
No

> **What date did the project or service go live?**
Company founded in 2020.

> Provide proof to substantiate the date of when the product or service became available to the public
Self-verifiable in 'Handelsregister'.

> **Has the project undergone an external security audit?**
Not yet for the service relevant to this issue.
 
> Provide a link to a report or repo. If none, are there plans to be audited?
-
 
> **Has the project undergone any security bug bounties?**
No

> Provide a link to a report or repo. If none, are there plans to hold a bug bounty?
-

> **Is the project being actively maintained?**
Yes

> Is there an active team developing the project?
Yes

> **Is the product or service free of trusted/human intermediaries?**
Yes

> Please expand. Disclose any steps in a stakers journey that depend on trusting humans with the keys to their funds or distribution of rewards.
After signup and in case customer wants to operate a validator (and is not just signing up for a dedicated archive node) we guide them through the validator setup / staking process.

> **If a pooled staking service, can users participate as a node operator without permission?**
Not pooled.
 
> Is permission to run a node controlled by an individual, company or DAO?
> 
> **If listing a staking-as-a-service, are users required to sign-up for an account?**
Yes.


> **If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**
User.

> What keys does the user maintain access to? What keys does the service gain access to? Are type `0x00` BLS keys being used, or type `0x01` pointing to an execution address? Who chose/controls that address?
0x01 for all new setups. Customer holds address.

 
> **If a pooled staking service, what percent of node operators are running a supermajority CL client?**
Not pooled.
> 
> This question is being updated to include SaaS... Please provide clarity on breakdown of client software being used by the service for sake of client diversity.

**Comment by corwintines** [comment]
@zeroservices thanks for opening this. Im going to close this out as its gone stale and the issue wasn't filled out properly. If you would like to be considered again, can you properly fill out the form in a new issue. Thanks!
