### ISSUE TITLE
nonce is missing from transaction information in transactions page

### ISSUE THREAD

**Issue by nitbit1309** [ethereum/ethereum-org-website#7609]
**Describe the bug**

The transaction contains nonce field to avoid replay attack. This field is not included in the information section of transaction. https://ethereum.org/en/developers/docs/transactions/

**To Reproduce**

1. Go to ['transaction page'](https://ethereum.org/en/developers/docs/transactions/)
2. See 'submitted transaction includes the following information:' section

**Expected behavior**

nonce field need to be present.

**Comment by minimalsm** [comment]
Closed in #7610, thanks @nitbit1309 :]
