### ISSUE TITLE
Small bug on Ethereum.org DeSci page

### ISSUE THREAD

**Issue by gonzaprotocol** [ethereum/ethereum-org-website#7612]
**Describe the bug**

There is a link that is misplaced. It should lead to another page.

**To Reproduce**

1. Go to https://ethereum.org/en/desci/
2. Click on **Bio.xyz: get funded for your biotech DAO or desci project** (Direct link: https://ethereum.org/en/desci/#:~:text=Bio.xyz%3A%20get%20funded%20for%20your%20biotech%20DAO%20or%20desci%20project)
3. The link takes you to the page of https://www.molecule.to/

**Expected behavior**

The link should take you to the https://biodao.xyz page

**Comment by minimalsm** [comment]
Closed by #7624, thanks @gonzaprotocol <3

**Comment by gonzagramaglia** [comment]
Hey, I just checked this again. I was wrong. The page to which the link should direct is https://bio.xyz
