### ISSUE TITLE
Broken link on https://ethereum.org/en/enterprise/

### ISSUE THREAD

**Issue by omahs** [ethereum/ethereum-org-website#7620]
Broken link on https://ethereum.org/en/enterprise/

this link: https://ethereum.org/en/developers/docs/scaling/layer-2
should be replaced by this: https://ethereum.org/en/developers/docs/scaling/#layer-2-scaling

**Comment by minimalsm** [comment]
Closed in #7622, thanks for reporting @omahs <3
