### ISSUE TITLE
<ExpandableCard> tag seems to be not supported on our t9n tool

### ISSUE THREAD

**Issue by MATsxm** [ethereum/ethereum-org-website#7635]
**Describe the bug**

`<ExpandableCard>` tag seems to be not supported on our t9n tool Crowdin 

**To Reproduce**

1. On our [Crowdin](https://crowdin.com/project/ethereum-org)
2. Go to [fr t9n for the Merge page](https://crowdin.com/translate/ethereum-org/2926/en-fr?filter=basic&value=0) (in fact it is the same for all languages
3. Scroll down to '### Node operators and dapp developers'
4. See the unsual screenplay 
![Capture d’écran 2022-08-31 142720](https://user-images.githubusercontent.com/1972717/187683300-a432d967-82ef-4803-9946-972e3fe4c36a.jpg)

**Expected behavior**

Normal use of the t9n features on Crowdin

**Screenshots**

Crowdin screenshot

**Additional context**

To me it seems that the `<ExpandableCard>` tag used on line 66 on [the original GitHub page]( https://github.com/ethereum/ethereum-org-website/edit/dev/src/content/upgrades/merge/index.md) is not supported on Crowdin and then breaks the t9n features

Thanks for the help for the i18n Ethereum Cummunity

**Comment by MATsxm** [comment]
Also the same for the 'SOLO STAKING' page.
Seems that the `_test_` markdown tags are not supported on Crowdin.

**Comment by minimalsm** [comment]
Thanks @MATsxm, unfortunately this is expected behaviour and can't be solved without migrating to a different platform.
