### ISSUE TITLE
DeSci page is not responsive, breaks on mobile

### ISSUE THREAD

**Issue by vincentweisser** [ethereum/ethereum-org-website#7665]
**Describe the bug**

The  desci page https://ethereum.org/en/desci/ breaks on mobile, prob due to wrong formatting of the table or something, not sure how to easily fix
 
@samajammin  @wackerow @corwintines  @minimalsm @jmcook1186

**Comment by DonMartin3z** [comment]
Did you guys get it done ?

**Comment by Arun9650** [comment]
No , still figuring out how to do it .

**Comment by isabelladebrito** [comment]
gm @vincentweisser! Thanks for creating this issue, and my apologies it took us too long to look into this.

We've been working on improving the website experience for mobile - I've tested the [DeSci](https://ethereum.org/en/desci/ ) page on a couple of devices and it seems the issue has been solved. I'm gonna go ahead and close this issue but if you spot anything odd, don't hesitate to reopen it. Appreciate your help in reporting this!
