### ISSUE TITLE
Active links not being styled

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#7670]
**Describe the bug**

Some links are not being styled correctly when you don't add the trailing slash in the URL.

### Note: this bug is only reproducible in _Gatsby Cloud_. In prod, we have redirects that will not allow you to visit a page without the trailing slash.

**To Reproduce**

1. Go to https://ethereumorgwebsitedev01.gtsb.io/en/web3
2. See the links in the Header nav, the Footer and Breadcrumbs
3. Switch color mode to dark mode
4. The link color do not change

**Expected behavior**

When you visit a page without the trailing slash, and you switch the color modes, the links should have the correct colors.

Lets find a workaround to enable the active style when we don't have a trailing slash.

**Screenshots**

![image](https://user-images.githubusercontent.com/468158/188210684-353a253b-7c7b-4bd2-a10a-af3db71bc1d9.png)

**Additional context**

The main problem is that the flag `partiallyActive` is `false` in these links: Header nav, Footer & Breadcrumbs.

https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#show-active-styles-for-partially-matched-and-parent-links

So, the active styles are applied only when the path is exactly the same as the url. In the example, it is `/web3/` (with the trailing slash).

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MahendraBishnoi29** [comment]
hey @pettinarip i would love to work on this 🚀

**Comment by pettinarip** [comment]
👋🏼 @MahendraBishnoi29 so this issue might involve some investigation on why the Header nav, Footer & Breadcrumbs are passing `partiallyActive` as `false`. I'll assign it to you but I just wanted to be clear that I don't think it is just turning that flag on.

Thanks for helping us with this.

**Comment by nhsz** [comment]
This has already been fixed, closing it
