### ISSUE TITLE
Read address aloud functionality on the staking deposit address reads address incorrectly

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#7690]
**Describe the bug**

The 'read aloud' functinonality on the staking deposit contract page does not work correctly. When following a number the letter 'C' is read as '_degrees Celsius_' and the letter '**F**' as '_degrees Fahrenheit_'.

**To Reproduce**

1. Go to 'https://ethereum.org/en/staking/deposit-contract/'
2. Click on 'Read address aloud'
3. See error

**Expected behavior**

It should read the characters exactly as they appear (characters should not be relational to one another)

**Smartphone (please complete the following information):**

- Device: iMac
- OS: MacOS 12.5.1
- Browser: Brave
- Version: v1.43.89

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by hursittarcan** [comment]
I could not reproduce this issue. It works ok on my device. (Win 10, Google Chrome v.104.0)

**Comment by sadiejay** [comment]
I can recreate the issue on my device:
 
    OS: MacOS 12.5.1
    Browser: Firefox
    Version: v104.0.1

**Comment by sadiejay** [comment]
May I be assigned this issue? I'm not sure how to tackle this but would like to try!

**Comment by minimalsm** [comment]
Closed by #7736

**Comment by sadiejay** [comment]
Oops did I miss something? I thought a comment was necessary before submitting a PR. Has that changed @minimalsm ?
