### ISSUE TITLE
396

### ISSUE THREAD

**Issue by ahmad396** [ethereum/ethereum-org-website#7692]
Hello. I drew a picture, in this picture there is a triangle with a combination of numbers. which is suitable as a logo for a company and is very valuable to me. If all the designers and thinkers get together, they cannot draw anything higher than this design, and they have not been able to achieve this design so far. I want to sell it on nft sites. Can I make sure that no one will copy it and sell it instead of me?**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Hey @ahmad396, this repo is for issues relating to ethereum.org, the website. Closing this as it isn't relevant to that.
