### ISSUE TITLE
Please add instruction to client types on https://ethereum.org/en/developers/docs/nodes-and-clients for the Merge !

### ISSUE THREAD

**Issue by ytrezq** [ethereum/ethereum-org-website#7700]
How to connect execution to consensus client ? Are any consensus client compatible with any execution client ?
Is setting the consensus client to archive mode required for running aa full archive execution client or is it possible to set up an execution full archive node using a light consensus client ?

**Comment by corwintines** [comment]
Thanks @ytrezq 

Since the merge has happened 2 years ago, and documentation on how to run Ethereum clients is now up to date on the site and with respective clients, going to close this out.
