### ISSUE TITLE
Spelling mistake in documentation

### ISSUE THREAD

**Issue by srv-smn** [ethereum/ethereum-org-website#7703]
**Describe the bug**

There is a spelling mistake in the documentation. Once you reach to this article(https://ethereum.org/en/developers/docs/nodes-and-clients/#snap-sync) in the documentation. In the snap-sync section the spelling of "Merkle trie" is wrong.

**To Reproduce**
Go to https://ethereum.org/en/developers/docs/nodes-and-clients/#snap-sync 

**Expected behavior**

The spelling should be "Merkle tree"

**Screenshots**

![image](https://user-images.githubusercontent.com/47235134/188560856-692bc24c-8e36-4287-b337-b973beb787ac.png)

**Comment by srv-smn** [comment]
I love contributions from the Ethereum community!.

**Comment by minimalsm** [comment]
Hey folks, thanks for highlighting this.

This isn't a mistake, a 'trie' is a type of tree. Maybe not the best naming! ([More on that here](https://stackoverflow.com/questions/4737904/difference-between-tries-and-trees)). 

Pretty common occurrence but going to close this out as no bug here :]

**Comment by minimalsm** [comment]
@all-contributors please add @srv-smn for ideas
