### ISSUE TITLE
Bug: further reading on staking page not being translated

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#7711]
**Describe the bug**

The further reading section of our `/staking/` page isn't currently being translated.

**To Reproduce**

1. Go to 'https://ethereum.org/zh/staking/'
2. Scroll down to 'Further reading (延伸阅读)'
3. See error

**Expected behavior**

It should be translated via strings in a JSON file.

**Screenshots**

<img width="1020" alt="Screenshot 2022-09-06 at 13 28 41" src="https://user-images.githubusercontent.com/62268199/188635519-c536ce35-4299-4804-81fe-3c2fc0384bad.png">

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by martinyung** [comment]
Hi @minimalsm, i would like to take this up, thank you
