### ISSUE TITLE
mist.ethereum.org is still online. 

### ISSUE THREAD

**Issue by cobordism** [ethereum/ethereum-org-website#7715]
Apologies if this is not the correct place to report the following:

mist.ethereum.org should have been taken offline a long time ago. I expect it was just forgotten and overlooked.
It is still up offering binaries from June 2018.

**Comment by lukassim** [comment]
Thanks for raising this!
Closing this issue as this has been resolved and the mist.ethereum.org link now redirects to the Mist entry in the 'Deprecated software' section on the site
