### ISSUE TITLE
Improve search functionality on blog

### ISSUE THREAD

**Issue by JoshDavisLight** [ethereum/ethereum-org-website#7726]
**Is your feature request related to a problem? Please describe.**

I find terms that I search through the search function on the EF blog result in "No Posts Found" when they are terms that are included in many of the most recent blog posts. 

**Describe the solution you'd like**

It would be nice to have a fully functioning search tool that will surface posts with search terms like "academic" or "fellowship"

**Comment by corwintines** [comment]
We overhauled the blog with new docsearch  functionality so going to close this out as done
