### ISSUE TITLE
Flashing color mode on hard refresh

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#7727]
**Describe the bug**

When the user is using dark mode and a hard refresh is done, the user will see the site in light mode for a few seconds until the page loads. Once it finishes, dark mode will be applied as expected.

This behavior produces a flashing effect that is not desired.

**To Reproduce**

1. Go to https://ethereum.org/en/
2. Select dark mode
3. Do a hard refresh
4. For a second you will see the site in light mode and quickly after that it turns back to dark mode

**Expected behavior**

If the user is using dark mode, when the user hard refreshes the site, the page loads immediately in dark mode.

**Additional context**

Chakra already provides a [solution for this problem](https://chakra-ui.com/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr). The problem is that that solution is not available in the [Gatsby plugin that we are using](https://www.gatsbyjs.com/plugins/@chakra-ui/gatsby-plugin/). Additionally, I have opened [an issue on Chakra's repo](https://github.com/chakra-ui/chakra-ui/issues/6621) to see if someone can help us with it.

Digging more into the issue, I tried to set up Chakra without using the plugin.

My idea was on using `cookieStorageManagerSSR` inside the `gatsby-ssr.ts` file BUT, as the manager name indicates, it requires you to pass the cookies to it. For some reason, I can not access the cookies inside `gatsby-ssr.ts` which blocks me to solve this issue (and I guess it is the same issue the plugin authors faced).

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
Im noticing this has improved, but still get light mode in areas other than the nav on the refresh (but no flash of blank anymore). 

Im wondering if this issue is still relevant @pettinarip with our migration to NextJS.

**Comment by TylerAPfledderer** [comment]
@corwintines @pettinarip I'm curious about the changeover to Next affecting this as well.

**Comment by pettinarip** [comment]
Correct. We will probably fix this issue with the Next migration but its still unresolved, so still relevant. cc @nhsz
