### ISSUE TITLE
Suggest a wallet: BitKeep

### ISSUE THREAD

**Issue by keepresolve** [ethereum/ethereum-org-website#7730]
### Wallet name

BitKeep

### Wallet description

BitKeep is the best decentralized multi-chain crypto wallet, providing 70+ mainnets and 220,000 crypto assets and 10,000+ DApps to global users.

### Wallet logo

https://raw.githubusercontent.com/bitkeepwallet/download/main/logo-png/BitKeep_logo_circle.png

### Background color for brand logo

#ffffff

### URL to the project

https://bitkeep.com/

### When did the wallet go live to users?

07-2018

### Does the wallet have an active development team?

yes

### Is the wallet globally accessible?

yes

### Is the wallet available in multiple languages?

yes

### What social links are there for the project?

Twitter：
BitKeep Wallet：https://twitter.com/BitKeepOS
BitKeep Daily：https://twitter.com/BitKeepDaily
FaceBook：https://www.facebook.com/BitKeep
Youtube：https://www.youtube.com/channel/UCD2S03RS-Q08VdJqZpuOCFQ
Telegram: https://t.me/bitkeep
Discord: https://discord.com/invite/qYTatUzNjM
Medium: https://bitkeepblog.medium.com/
Instagram: https://www.instagram.com/bitkeep_global/?igshid=YmMyMTA2M2Y%3D

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS and Android

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

no

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

yes, chrome

### Is it a hardware wallet?

no

### What license is the wallet software released under?

https://bitkeep.com/resource/privacy BitKeep Global Inc.-CI.PDF

### Who holds the private keys?

Do users have access to their public and private keys? Self-custodial wallet, users hold on to the private keys.
Does anyone else? No, not unless the user shares this with someone else
If the company/project were to disappear, would users still be able to access their funds? Yes, the user would still be able to access their private key, and import it into a new wallet

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://study.bitkeep.com/en/?ht_kb=what-is-safety-quiz

### Does the wallet have an internal security team?

yes

### Scam protection?

https://study.bitkeep.com/en/?s=Scam&ht-kb-search=1

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

https://docs.bitkeep.com/guide/connect-wallet-for-dapp.html

### Does the wallet support staking directly?

no

### Does the wallet support swaps directly?

yes

### Does the wallet support multi-chain networks?

yes

### Does the wallet support Ethereum layer 2 networks?

yes

### Does the wallet allow the user to customize gas fees?

yes

### Does the wallet support sending transactions to ENS addresses?

yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

yes

### Who can the ethereum.org team can contact regarding the wallet in future?

Twitter：
BitKeep Wallet：https://twitter.com/BitKeepOS
BitKeep Daily：https://twitter.com/BitKeepDaily
FaceBook：https://www.facebook.com/BitKeep
Youtube：https://www.youtube.com/channel/UCD2S03RS-Q08VdJqZpuOCFQ
Telegram: https://t.me/bitkeep
Discord: https://discord.com/invite/qYTatUzNjM
Medium: https://bitkeepblog.medium.com/
Instagram: https://www.instagram.com/bitkeep_global/?igshid=YmMyMTA2M2Y%3D

### Does the wallet have a dedicated support team?

Telegram: https://t.me/bitkeep.
Telegram, 24-hour customer service

### What educational resources/documentation do you provide to users?

https://study.bitkeep.com/en/

### Does the wallet have any integrated tools not mentioned above?

contract detection : https://share.bitkeep.asia/ContractDetection/1/ 
wallet tools:  https://share.bitkeep.asia/walletTools
otc : https://share.bitkeep.asia/otcPage?code=USD
batch send:   https://share.bitkeep.asia/batchSend
authorized tools:   https://share.bitkeep.asia/Authorize?chain=eth&_needChain=eth

**Comment by keepresolve** [comment]
Hello, do you have any other problems? Can this next version be updated?

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
