### ISSUE TITLE
Suggest a wallet: Ballet

### ISSUE THREAD

**Issue by BalletGlobal** [ethereum/ethereum-org-website#7738]
### Wallet name

Ballet REAL Series Wallet

### Wallet description

The Ballet REAL Series wallet is a physical cryptocurrency wallet that gives you full and exclusive control of your digital assets. A two-factor cryptographic private key is securely concealed on the physical wallet itself, which allows the wallet to function as a bearer asset like cash or gold. REAL Series wallets never need updates or maintenance. Since the private key is in physical form, not digital, there is no risk of accidental data deletion or corruption. REAL Series wallets are designed to be simple and intuitive so that Self-inflicted user error is nearly impossible.

The Ballet Crypto app is a digital asset management companion app to your Ballet REAL Series wallet. When using the app, your assets are kept completely offline on your wallet. The app does not store the credentials of your wallet and cannot access your private key.

### Wallet logo

![Ballet Logo (Black)](https://user-images.githubusercontent.com/112846169/189023283-9026f482-8814-4f50-b432-5fe2f01ab3c1.png)

### Background color for brand logo

#ffffff

### URL to the project

https://www.ballet.com

### When did the wallet go live to users?

September 12, 2019

### Does the wallet have an active development team?

Yes. We have an active development team. Our app is being constantly updated with new features and functions. 

### Is the wallet globally accessible?

Yes, the Ballet REAL Series wallet is globally accessible to purchase. Our Ballet Crypto app is also accessible to download from the App Store, Google Play, and as an Android APK.

### Is the wallet available in multiple languages?

English, German, Spanish, French, Italian, Japanese, Korean, Chinese (Simplified & Traditional), Russian, and Hungarian.

### What social links are there for the project?

Twitter: https://twitter.com/BalletCrypto/

Facebook: https://www.facebook.com/balletcrypto.global/

Instagram: https://www.instagram.com/balletcrypto/

Telegram: https://t.me/BalletCrypto/

Reddit: https://www.reddit.com/r/BalletCrypto/

LinkedIn: https://www.linkedin.com/company/balletcrypto/

Youtube: https://www.youtube.com/channel/UCi2y_uFMqgdst7xe7FolG3w/

Weibo: https://www.weibo.com/BalletCrypto?from=myfollow_all/

Discord: https://discord.gg/e58FqyDA

Anchor: https://anchor.fm/ballet-crypto

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Our companion app for the physical Ballet wallet is our Ballet Crypto App. This app is downloadable from the Apple Store, Google Play, and as an Android APK. 

Apple App Store: https://apps.apple.com/us/app/id1474912942
Google Play: https://play.google.com/store/apps/details?id=com.balletcrypto
Android APK is available on our page here: https://www.ballet.com/app

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Yes we have a desktop app for macOS, Windows, and Linux. All of these can be downloaded at our Ballet Crypto app page here: https://www.ballet.com/app

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

n/a

### Is it a hardware wallet?

Yes the Ballet REAL Series wallet is a physical, non-electronic, offline device. Our Ballet Crypto app supports airgapped offline signing via QR codes. 

### Is the source code for the wallet fully open-source?

The physical Ballet REAL Series wallet utilizes the open-source BIP38 standard. Our Ballet Crypto app is not open-sourced though.

### What license is the wallet software released under?

n/a

### Who holds the private keys?

The users hold the private key and public keys. If the team at Ballet and the Ballet Crypto app were to disappear, users would still be able to access their funds since the physical wallet utilizes the open-source BIP38 standard. REAL Series wallets are made in accordance with BIP38 open industry standards. These tried-and-tested encryption and decryption algorithms further ensure the security of your funds, and assure you that you can still access your funds even if Ballet ceases operations. The encryption and decryption algorithms are non-proprietary, and we have open-sourced our software to ensure full access to the underlying decryption standards.

A full explanation on how users can recover their funds in the event of such situation can be found here: https://medium.com/ballet-crypto/how-to-recover-your-crypto-from-your-ballet-wallet-during-an-apocalypse-80b35f428f6a 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

[Ballet Crypto Mobile Wallet Pentest v3.pdf](https://github.com/ethereum/ethereum-org-website/files/9523428/Ballet.Crypto.Mobile.Wallet.Pentest.v3.pdf)

- A comprehensive audit done by Certik was completed last year. Information on that audit can be found in the attached pdf.

- A complete explanation of the security process taken during our manufacturing process of the physical Ballet REAL Series can be found here: https://www.ballet.com/2FKG

- An open hacking challenge, by our founder & CEO Bobby Lee, is currently ongoing allowing anyone to try and hack the physical Ballet REAL Series wallet. More information can be found here: https://www.takebobbysbitcoin.com/

### Has the wallet's smart contract code or security modules been audited?

Yes, the complete audit report can be found in the attached pdf by Certik.

### Does the wallet have an internal security team?

Yes, we have certain personnel in place to maintain the integrity of our manufacturing process and of the development of our Ballet Crypto app.

### Any other security testing that should be noted?

- A complete explanation of the security process taken during our manufacturing process of the physical Ballet REAL Series can be found here: https://www.ballet.com/2FKG

- An open hacking challenge, by our founder & CEO Bobby Lee, is currently ongoing allowing anyone to try and hack the physical Ballet REAL Series wallet. More information can be found here: https://www.takebobbysbitcoin.com/

### Scam protection?

Ongoing reminders and education to our users in being vigilant about scams and fraudsters is an everyday practice we employ. 

The REAL Series wallets are also protected by tamper-evident QR code stickers and wallet passphrase scratch-offs. As long as the sticker and scratch-off are intact, then you can be assured that your encrypted private key and wallet passphrase are safe and have never been exposed to an unauthorized third party. This feature also makes it safe and reliable to give (or receive) Ballet wallets as gifts, loaded with cryptocurrency.

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, users can use WalletConnect in the Ballet Crypto app.

### Does the wallet support staking directly?

No.

### Does the wallet support swaps directly?

We have integrated 3rd party exchanges to allow swapping directly via the app.

### Does the wallet support multi-chain networks?

Yes, the full list of supported networks can be found here: https://www.ballet.com/coins

### Does the wallet support Ethereum layer 2 networks?

Yes, the full list of supported networks can be found here: https://www.ballet.com/coins

### Does the wallet allow the user to customize gas fees?

Yes, users can customize gas fees during the transaction creation process. 

### Does the wallet support sending transactions to ENS addresses?

No.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

No

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, these steps can be found here: https://support.ballet.com/hc/en-us/articles/900005501826-How-to-buy-crypto-assets-with-the-Ballet-Crypto-app

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

The ethereum.org team can contact us via the email: marketing@ballet.com

### Does the wallet have a dedicated support team?

Yes, users can email us at support@ballet.com

The response time is within 24 hours.

### What educational resources/documentation do you provide to users?

Our community can read up on updates, education, demonstrations, and other resources at our blog here: https://medium.com/ballet-crypto

More can also be found on our official support center page: https://support.ballet.com/hc/en-us

**Comment by BalletGlobal** [comment]
@minimalsm Is there any update or next steps for this application so that we can push it forward? Thank you.

**Comment by BalletGlobal** [comment]
@minimalsm Hi Joshua, is there an update as to how we can push forth our wallet listing application? Let us know if there is anything else you may want to review from us. Thanks.

**Comment by corwintines** [comment]
im pretty uncomfortable recommending a wallet that generates and prints your private key for you instead of the user having the ability to do this. At the moment im going to reject this, but feel free to reopen and push back.

**Comment by corwintines** [comment]
Edit: ill leave open for others opinion first as well.

**Comment by corwintines** [comment]
Closing after discussion: https://discord.com/channels/714888181740339261/938069929205329980/1067549858602434630
