### ISSUE TITLE
Help needed badge renders poorly, giving broken and low quality impression

### ISSUE THREAD

**Issue by miohtama** [ethereum/ethereum-org-website#7743]
**Describe the bug**

"Help needed" badge on certain pages renders poorly, giving an impression of low quality on Ethereum.org website.

[This badge is found on Python page](https://ethereum.org/en/developers/docs/programming-languages/python/) but might be on other pages as well.

**Expected behavior**

The badge looks good regardless of a web browser.

**Screenshots**

<img width="656" alt="image" src="https://user-images.githubusercontent.com/49922/189080026-1e95ab35-d11a-49ac-bf4d-eda5a018ac17.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox

**Additional context**

- I suggest the badge is hidden until a replacement image is found
- The replacement image should be SVG or high-quality PNG

**Comment by corwintines** [comment]
Agree @miohtama, this is pretty ugly.

@nloureiro I think we should still have a callout component, but this should be redesigned to something a little more appealing 😅 Do you mind helping with a design here so that we could change this up.
