### ISSUE TITLE
Suggest a wallet: NOW Wallet 

### ISSUE THREAD

**Issue by alenaign** [ethereum/ethereum-org-website#7777]
### Wallet name

NOW Wallet

### Wallet description

[NOW Wallet](https://walletnow.app/) is a non-custodial mobile cryptocurrency wallet. It allows users to store and exchange crypto assets, choosing from more than 50,000+ trading pairs natively available in the app, including fiat-to-crypto exchanges. NOW Wallet supports 28 blockchains, including the storage of any existing tokens on 7 networks: Ethereum, Binance Smart Chain, Polygon, Avax C-Chain, TRON, Klaytn, and Solana. Our users can also securely store NFTs, connect to dApps with WalletConnect and stake BNB, TRX and NOW Token.

### Wallet logo

![NOWWallet](https://user-images.githubusercontent.com/108939215/189354076-da43d714-cb6b-494b-b31c-98431ac08611.svg)

### Background color for brand logo

#2B2B36

### URL to the project

https://walletnow.app/

### When did the wallet go live to users?

11/29/2021

### Does the wallet have an active development team?

Yes, new versions of the app are launched ~once a week

### Is the wallet globally accessible?

Worldwide

### Is the wallet available in multiple languages?

-

### What social links are there for the project?

https://twitter.com/ChangeNOW_io
https://t.me/changeNOW_chat
https://changenow-io.medium.com/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS: https://apps.apple.com/app/now-wallet-bitcoin-crypto/id1591216386
Android: https://play.google.com/store/apps/details?id=com.nowwallet

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

The desktop version is to be launched by the end of September - available for Windows, Mac, Linux

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

-

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

No

### Who holds the private keys?

NOW Wallet is non-custodial, and we do not collect any personal data, our users have sole control of their private keys.
If the project were to disappear, users would still be able to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

NOW Wallet is non-custodial, we don't collect and store any personal data of users. Our users can connect to dApps only via Wallet Connect, using secure protocols. Our exchange - ChangeNOW is a decentralized exchange.

### Has the wallet's smart contract code or security modules been audited?

-

### Does the wallet have an internal security team?

-

### Any other security testing that should be noted?

-

### Scam protection?

In-app reminders, communication via blog and Social Media

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

-

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Users can connect to dApps by scanning QR or pasting the link

### Does the wallet support staking directly?

-

### Does the wallet support swaps directly?

Yes, more that 50000+ trading pairs are available

### Does the wallet support multi-chain networks?

-

### Does the wallet support Ethereum layer 2 networks?

-

### Does the wallet allow the user to customize gas fees?

Yes, users can regulate the speed of transactions and the fee

### Does the wallet support sending transactions to ENS addresses?

-

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, any tokens on Ethereum are natively seen in the interface

### Does the wallet support EIP-1559 (type 2) transactions?

-

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

Yes, users can sell crypto using bank accounts and Visa/MasterCard

### Is the wallet a multi-signature wallet?

-

### Does the wallet support social recovery?

-

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram - al_ign (Alena, Marketing Manager at NOW Wallet)
Mail - partners@walletnow.app

### Does the wallet have a dedicated support team?

Users can access our 24/7 support team right in the app or by support@changenow.io
The support answers in ±2 minutes

### What educational resources/documentation do you provide to users?

https://changenow.io/blog

**Comment by mikeeflower** [comment]
I recommend you seek professional help while trying to fix your credit to avoid further complications and ruin your credit. I talked to Hack West Credit Repair who listened to me and was happy to help solve my credit issues. My score was raised to 810 in just about 7 days and all collections, charge offs, eviction and IRS were removed from my profile. Hack West also helped to recover my lost crypto currencies that were stolen from my wallet months ago without taking any upfront payment. He did all of these without any red flag or whatsoever. Contact H A C K W E S T @ W R I T E M E . C O M or Whatsapp +1 424.307.2638. You can tell him Mike Flower referred you.

**Comment by alenaign** [comment]
@minimalsm Hello! Is there any update so that we can push it forward, please? Thank you.

**Comment by corwintines** [comment]
Theres a lot of missing data in this. Lots are left with a empty bullet. Going to close, but please reopen with that info filled out and ill look at it right away.
