### ISSUE TITLE
Update Beacon Chain terminology after The Merge?

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#7828]
This issue aims to determine the right way to refer to the Beacon Chain after The Merge. It will be helpful to define a correct naming convention to be used across ethereum.org after the merge.

The Beacon Chain (TBC) went live in November 2020 and ran in parallel to Ethereum Mainnet (EM) right up to the moment of The Merge in September 2022. Having independent terms to describe the two independent chains made a lot of sense because TBC and EM were developed separately and fulfilled different functions - they were different blockchains. However, since The Merge, there is only one Ethereum blockchain formed by combining pre-merge EM and pre-merge TBC. 

Does it makes sense to persist the "Beacon Chain" terminology or to deprecate it in favour of "Ethereum Mainnet". 

**Arguments for persisting TBC terminology are:**
- Since it is a chain of `beacon_blocks` it makes sense to refer to the Beacon Chain.
- there is Beacon terminology baked into clients and tooling, such as `beacon_state`, `beacon_block`, `beacon_node` etc which doesn't make much sense if we deprecate the term Beacon Chain
- It makes a useful distinction between pre- and post-merge Ethereum and EL/CL.

**Arguments against TBC terminology are:**
- The Beacon Chain was a development artefact that did not handle real transactions. It is better for the term to keep this specific definition and leave it behind in the pre-merge world. Let EM refer to the "live" chain for continuity with pre-merge world.
- it will be confusing to have multiple terms for the same chain (Ethereum blockchain, Ethereum Mainnet, Beacon Chain). We have already seen that the ETH2 terminology confused people and was surprisingly sticky. To non-experts multiple terms suggests multiple chains and this misconception will be reinforced by the abundant pre-merge documentation that will persist online.

It would be great to hear people's opinions on this issue

**Comment by samajammin** [comment]
My 2 gwei: given that there's now only one "Ethereum blockchain", I think it makes sense to keep terminology consistent with that, particularly to avoid confusion for newcomers. So I'd vote to deprecate use of "Beacon Chain" across the site.

I suspect it may be useful to keep the [Beacon Chain page](https://ethereum.org/en/upgrades/beacon-chain/) intact as a place to explain this history (i.e. that it used to be a standalone blockchain that was merged with Ethereum Mainnet) but in the rest of e.org site content & documentation, my hunch is that it'd be best to avoid "Beacon Chain" references.

I'm no expert here, so definitely would appreciate input from researchers & client devs who may have technical arguments for keeping "Beacon Chain" around.

**Comment by nloureiro** [comment]
I agree with @samajammin on this and I would add that we need to rethink the upgrade page with the roadmap, like @wackerow have been talking about.
one exemple: the CTA on the upgrade page [explore upgrades] >>> links to the Beacon Chain page - we need to change this
![Screen Shot 2022-09-21 02 42 51 PM](https://user-images.githubusercontent.com/1120748/191520123-f98b6af7-f64e-4423-bb09-e6dfaaef5a1f.png)

**Comment by emmanuel-awosika** [comment]
> It makes a useful distinction between pre- and post-merge Ethereum and EL/CL.

This is probably the best reason for keeping Beacon Chain language on the website. I've always thought of the Beacon Chain as the "consensus engine" and Ethereum Mainnet as the "execution engine." No doubt we'll have to reference this difference in different places (e.g., talking about external block builders and validators). 

> It will be confusing to have multiple terms for the same chain.

Not if we explain that the Beacon Chain *is* a part of the Ethereum chain. That's why having a page on the Beacon Chain and explaining how it fits into Ethereum's infrastructure, like @samajammin suggested, may be ideal.

**Comment by lukassim** [comment]
Closing this issue as it was fixed with PR #9589
