### ISSUE TITLE
Add HairDAO to the DeSci Page

### ISSUE THREAD

**Issue by averbinnen** [ethereum/ethereum-org-website#7867]
### Name

HairDAO 

### Description

HairDAO is a DeSci DAO dedicated to funding early stage R&D for androgenetic alopecia. Check out our website hairdao.xyz

### Logo

<img width="173" alt="HairDAOLogoNew" src="https://user-images.githubusercontent.com/109697460/190487432-ab473e25-7549-47d0-b2f8-044a39d220af.png">

### Brand color

2596be

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/HairDAO/hair-database

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

We have not deployed any code yet. When we do, we'll be deploying our contracts with Molecule as a member of bio.xyz

### Can a user access the dapp without creating an account?

That is the plan. 

### Are dapp funds non-custodial?

That is the plan

### Do you offer community support?

https://t.co/7U50If8sY4

invite to our discord server above

### Describe any geographical restrictions on usage of your dapp

we don't anticipate any. we're based in New York City

**Comment by jmcook1186** [comment]
Hi I also commented on the PR for this - we will happily reconsider when the project develops further but right now this doesn't meet the listing criteria.
