### ISSUE TITLE
Update ETH issuance page for post-Merge

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7873]
### Is your feature request related to a problem? Please describe.

Someone [raised some questions on the ETH issuance page](https://ethereum.org/en/upgrades/merge/issuance/):
https://ethresear.ch/t/some-questions-on-new-burning-and-issuance-mechanism/13695

### Describe the solution you'd like

Review & address questions in the page content.

### Describe alternatives you've considered

None... 😄 

### Additional context

This page content will already be audited as part of #7075, so can perhaps be solved there.

**Comment by veridelisi** [comment]
Anybody explain?

**Comment by veridelisi** [comment]
anaybody?

**Comment by samajammin** [comment]
Hey @veridelisi - looks like this is being addressed in #7921

**Comment by samajammin** [comment]
I tried to explain the issue description but let me know if you have any specific questions.
