### ISSUE TITLE
Add EIP-3074 info

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/ethereum-org-website#7875]
### Is your feature request related to a problem? Please describe.

EIP-3074 seems to be pretty misunderstood/controversial. Ethereum users should be able to find information about EIP-3074 without having to pick a side.

### Describe the solution you'd like

I would like there to be a page that provides a summary of EIP-3074 that is understandable to the layperson and that discusses some of the potential benefits and pitfalls.

### Describe alternatives you've considered

N.A.

### Additional context

One content tag, please :)

**Comment by Pandapip1** [comment]
Would really like to see this, still.

**Comment by Pandapip1** [comment]
Still would like to see this.

**Comment by Pandapip1** [comment]
Still would like to see this.

**Comment by corwintines** [comment]
@Pandapip1 we are adding some information here: https://github.com/ethereum/ethereum-org-website/pull/9648

Any suggestions on content you would like to see for this, and where this could live if created?

**Comment by corwintines** [comment]
Sounds good! Based on your above comment ill close this out as it was addressed in the PR I linked. Thanks!
