### ISSUE TITLE
Empty buttons on the Feedback card - light mode

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#7876]
### Describe the bug

In light mode, the Feedback card buttons are empty or text is not visible.

### To reproduce

1. Go to the home page
2. Select light color mode
3. Click on the feedback button at the button-right corner of the screen
4. The "Yes/No" buttons are empty

### Expected behavior

Fix the Yes and No text colors on the buttons in light mode.

### Screenshots

![image](https://user-images.githubusercontent.com/468158/190640956-c049517d-caec-40a2-aff6-e2b4d96f14b0.png)

**Comment by samajammin** [comment]
Yikes, nice catch! Tagging as a good first issue 😄

**Comment by pettinarip** [comment]
> Can I take this one?

Sure, go for it @hursittarcan. Assigned. Thanks!

**Comment by kavy-the-dev** [comment]
it's still open can i contribute it?
