### ISSUE TITLE
Links to "client diversity" are broken

### ISSUE THREAD

**Issue by barro32** [ethereum/ethereum-org-website#7896]
### Describe the bug

On the "[Spin up your own Ethereum node](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/)" page there are three links to "client diversity" which do not work.

### To reproduce

1. go to https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/
2. click on [client diversity](https://ethereum.org/en/developers/docs/client-diversity)
3. it shows a 404 page

### Expected behavior

It should link to this page:
https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity

**Comment by minimalsm** [comment]
Nice catch @barro32 💪
