### ISSUE TITLE
Suggest a staking product or service

### ISSUE THREAD

**Issue by sambacha** [ethereum/ethereum-org-website#7902]
### Project name

Manifold Finance

### Product type

Other: (describe)

### If other product type, please describe

MEV Boost Relay operator

### Logo

![256_256](https://user-images.githubusercontent.com/32783916/190890603-99081182-a49f-4859-bec4-47b077f0163a.png)

### Description

Manifold Finance operates its own RPC infrastructure platform called SecureRpc

SecureRpc is a bare-metal, fully conformant JSON-RPC/gRPC Infrastructure plane that aims to perform well and meet the following requirements:

-   censorship resistance
-   latency
-   optimizations
-   support for bespoke RPC Calls
-   seamless usage
-   privacy focused
-   improve trade execution
-   improve trade settlement
-   resistant against coercions from state-level actors

It provides MEV Boost Relay at mainnet-relay.securerpc.com and a JSON RPC endpoint at api.securerpc.com/v1 

These services are for the public benefit of Ethereum users, no API key needed. No registration needed, just use the endpoint  and connect to the world of opportunities available on Ethereum. 

### Website

https://securerpc.com

### If software is involved, is everything open source?

Portions of code are open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Production

### What date did the project or service go live?

01/01/2022

### Has the project undergone an external security audit?

https://github.com/manifoldfinance/pki#security-bug-handling-process

### Has the project undergone any security bug bounties?

https://github.com/manifoldfinance/pki#security-bug-handling-process

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

We do not hold any keys for any validators, searchers or builders. 

### If listing a staking-as-a-service, are users required to sign-up for an account?

No

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

All  CL clients support MEV Boost Relay currently. 

### What user interfaces are supported?

RPC

**Comment by wackerow** [comment]
Hey @sambacha! Thank you for filing this, and apologies for delays getting back to you.

This raises a good point about what we should do regarding MEV boost relayers. Currently we do not actually have a place to list relayers in the context of the ethereum.org staking pages. The staking pages are more designed for ways to either run a node, or stake with a service or pool, whereas this gets into another level to the staking journey. 

@minimalsm @jmcook1186 or others, curious what you think about potentially adding a section somewhere for MEV relayers. We should discuss where this could live and how this could be maintained if we want to pursue this.

**Comment by wackerow** [comment]
Is there a list somewhere of different MEV relayers we could list in the MEV portion of the dev docs to give people a starting point?

**Comment by minimalsm** [comment]
Closing as abandoned, feel free to reopen with answers to the above.
