### ISSUE TITLE
Tutorials linking to broken routes

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7904]
### Describe the bug

Seems we're appending language routes incorrectly on some tutorials

### To reproduce

1. Go to https://ethereum.org/en/developers/tutorials/
2. Filter by 'UI'
3. View results - same tutorial listed multiple times, some linking to pages that don't exist (e.g. https://ethereum.org/en/id/developers/tutorials/nft-minter/)

### Expected behavior

Should show results only for pages that exist 😄 - should display tutorials of the current language (in this case, only /en/ routes).

### Screenshots

![Uploading Image 2022-09-18 at 12.18.05 PM.jpg…]()

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by minhoryang** [comment]
I'll handle this.
