### ISSUE TITLE
InfoBanner issues on Mining page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7905]
### Describe the bug

1) broken markdown links in the callout
2) lack of spacing above the callout

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/mining/
2. See InfoBanner component at top

### Expected behavior

1) markdown links should work
2) add spacing above the callout

### Screenshots

![Uploading Image 2022-09-18 at 1.36.30 PM.jpg…]()

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by hursittarcan** [comment]
I can try to fix this one
