### ISSUE TITLE
Ensure consistent spelling of 'zk-rollup' across the site

### ISSUE THREAD

**Issue by hursittarcan** [ethereum/ethereum-org-website#7908]
### Describe the bug

We currently use different ways of spelling 'zk-rollup' on the website - specifically 'ZK-rollup' & 'zk-rollup'. The spelling should be consistent across the website.

### To reproduce

* Example 'ZK-rollup': 

![image](https://user-images.githubusercontent.com/75273616/190922301-65126e0e-5b18-4509-a42a-57d460b37cae.png)

* Example 'zk-rollup': 

![image](https://user-images.githubusercontent.com/75273616/190922322-ee4a0d2a-b7ed-4402-85ae-53733f3c9695.png)

### Expected behavior

I'm not sure about the preferred spelling, I believe 'zk-rollup' - all lowercase looks best (unless it's used in the beginning of a sentence).

**Comment by yadunandanbhat** [comment]
AFAIK, it's ZK-rollups right? I could find and replace all of those

**Comment by hursittarcan** [comment]
> 

I'm not sure. It's best if we wait for a reply from the core team.

**Comment by samajammin** [comment]
Thanks for raising this! Agree would be great to land on a consistent approach.

No strong opinion here. I just ask that we add this to the style guide once we decide 😄:
https://ethereum.org/en/contributing/style-guide/

**Comment by julian-st** [comment]
I can't actually find the example for zk-rollup and I would suggest to leave it with ZK-rollup

**Comment by corwintines** [comment]
Closing as PR has been merged
