### ISSUE TITLE
Errors from the speed of a website connected to Ethereum

### ISSUE THREAD

**Issue by padrone1225** [ethereum/ethereum-org-website#7927]
### Describe the bug

Hi. I am developing the NFT staking platform on Ethereum network. But I got the error from the speed of the network.
I am not sure why this error comes.

As far as I know, EVM will execute a smart contract when someone makes a message call to the smart contract, right? But message call is a transaction and in order to be executed it has to be verified, however the verification time of an Ethereum block is about 14s so it's gonna take a while for the website to change after we interact with its element, isn't it? 
And 14s is too slow in my opinion so I don't know if there is anything wrong with my understanding.

How can i fix this error?

### To reproduce

1. I connect wallet to the website (Metamask)
2. I click `stake all` button.
3. Then the loading ... is not stopped and after 15s it was failed.
* in my wallet, there are only 12 NFTs

### Expected behavior

In fact, all NFTs should be sent to the staked NFT paragraph, but it doesn't happen.

### Additional context

I think this error comes from the merge of Ethereum.
After merge, is there any change on blockchain operation?

**Comment by corwintines** [comment]
This issue isn't related to work we can do on ethereum.org. Going to close.
