### ISSUE TITLE
[Stale] - Add Tenderly Sandbox to  "Code sandboxes" section

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7932]
### Is your feature request related to a problem? Please describe.

We just added Tenderly Sandbox to the IDEs dev docs page: 
https://github.com/ethereum/ethereum-org-website/pull/7930

I could also see it on this page https://ethereum.org/en/developers/learning-tools/ in the "Code sandboxes" section.

### Describe the solution you'd like

Add Tenderly Sandbox to  "Code sandboxes" section

### Describe alternatives you've considered

None :)

### Additional context

Discord discussion:
https://discord.com/channels/714888181740339261/938069929205329980/1020366950301454416

**Comment by minimalsm** [comment]
Closing as duplicate to 10672
