### ISSUE TITLE
Broken link in Particia Merkle Trie page

### ISSUE THREAD

**Issue by f3d0ss** [ethereum/ethereum-org-website#7944]
### Describe the bug

The RLP link in 
https://github.com/ethereum/ethereum-org-website/blob/59de7ddebde3d7866f507e123ce7e9dbe6a06d32/src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md?plain=1#L182
and
https://github.com/ethereum/ethereum-org-website/blob/59de7ddebde3d7866f507e123ce7e9dbe6a06d32/src/content/translations/it/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md?plain=1#L182
and
https://github.com/ethereum/ethereum-org-website/blob/59de7ddebde3d7866f507e123ce7e9dbe6a06d32/src/content/translations/zh/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md?plain=1#L182

are broken.
The page explaining RLP is in /developers/docs/data-structures-and-encoding/rlp

### To reproduce

1. Go to /developers/docs/data-structures-and-encoding/patricia-merkle-trie
2. Open RLP link

### Expected behavior

Go to the page explaining RLP.

**Comment by f-cazzola** [comment]
I would like to make a PR for this
