### ISSUE TITLE
Adding Crypthunt to list of beginner resources

### ISSUE THREAD

**Issue by lakers38** [ethereum/ethereum-org-website#7954]
I was wondering if we could add [Cryptohunt](https://www.cryptohunt.it) to a list of resources for people to learn about crypto and web3 in a beginner friendly manner. Any guidance on where we might link it would be appreciated

I would like to take responsibility for this feature.

**Comment by isabelladebrito** [comment]
Hi there! Thanks for creating this issue, and my apologies it took us too long to look into this.

The resource suggested seem to have pivoted to a broader topic, so I would say that it is no longer pertinent to ethereum.org. 

I will close this issue for now - however, if you come across any other resources that could be added to the website, let us know!
