### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by afsflory** [ethereum/ethereum-org-website#7971]
### Dev tool name

VMware Blockchain for Ethereum 

### Dev tool description

VMware Blockchain for Ethereum enables enterprise organizations to build, run and deploy EVM compatible chains at scale with privacy, governance, world-class support and popular Ethereum integrations. 

### When did the dev tool go live?

VMware Blockchain was introduced in 2021. The platform supported Daml smart contracting language and execution engine. We added support for EVM in August 2022. 

### Where do you think this page should be shown?

https://ethereum.org/en/enterprise/private-ethereum/

### Is the product open source?

No

### Documentation URL

https://github.com/vmware-samples/vmware-blockchain-samples/tree/master/vmware-blockchain-ethereum-developer-kit

### Additional context

VMware Blockchain for Ethereum is available now in beta. VMware Blockchain uses Project Concord which is an open source SBFT protocol for consensus. SBFT was developed by VMware to support mission critical dApps and business networks.  https://github.com/vmware/concord-bft

**Comment by corwintines** [comment]
Since this is end of life based on the repo, going to close this out.
