### ISSUE TITLE
Suggest a tutorial

### ISSUE THREAD

**Issue by anataliocs** [ethereum/ethereum-org-website#7976]
### Tutorial title

First Steps in your Developer Journey with Ethereum using Infura

### Tutorial description

This article details the developer journey getting started with Ethereum development leveraging Infura. We will walk through sending a transaction to your Metamask wallet, IPFS Operations, deploying a NFT smart contract and minting an NFT

### Tutorial tags

"getting started", "typescript", "web3.js", "nodes",  "infura"

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

This article details the developer journey getting started with Ethereum development leveraging Infura. We will walk through sending a transaction to your Metamask wallet, IPFS Operations, deploying a NFT smart contract and minting an NFT

### For tutorials hosted elsewhere: URL to tutorial

https://blog.infura.io/post/getting-started-with-infura-28e41844cc89

**Comment by lukassim** [comment]
Closing this issue as the tutorial already exists on the Infura blog and doesn't need to be duplicated on ethereum.org
