### ISSUE TITLE
Suggest a wallet: Assure

### ISSUE THREAD

**Issue by Emmmawo** [ethereum/ethereum-org-website#7984]
### Wallet name

Assure

### Wallet description

Assure is a digital Wallet, a web3.0 aggregator for crypto assets, and aims to be a portal for tons of users flowing from Web2.0 to Web3.0. With the advanced security protection, Assure offers batches of functions: dual-ended trading, Dapps Collection, Aspace(social media function), NFT, Aswap, OTC and CPL, etc. As a digital wallet, Assure pays great attention to Wallet Security and has got the [Certik Audit report](https://www.assure.pro/Assure/Audit_Report.pdf), the Top blockchain security Audit. 

The Assured community is a group of active and creative people. Since Assure joined Twitter in December, we have generated nearly 60k+ followers in total. Assure community is full of diversity with several regional TG groups because it is a global project. For the details, please check our Official Twitter: [Assure_pro](https://twitter.com/Assure_pro) and Official TG group: [AssurePro](https://t.me/Assurepro) and [Discord server](https://discord.gg/8cZRnM82nC).

Assure is a wallet with great potential which is also positively searching for cooperation with others. 
So far, Assure has joined WalletConnect. https://walletconnect.com/registry?search=Assure
Besides, Assure has been listed on TRON listed page: https://tron.network/wallet?lng=en

### Wallet logo

![logo (2)](https://user-images.githubusercontent.com/113981024/191221679-5d8b9fd7-0815-4be5-97f1-5fbe4b8fb54b.png)

### Background color for brand logo

FFFFFF

### URL to the project

http://assure.pro/

### When did the wallet go live to users?

Assure Wallet went live both in Google Play store and Apple Store on Jan 28th, 2022. 

### Does the wallet have an active development team?

Yes, there are 80+ developers are actively working on the wallet. The proof is 

### Is the wallet globally accessible?

NO KYC requirement for Wallet function. 

### Is the wallet available in multiple languages?

English, and Chinese for now

### What social links are there for the project?

We have a 100k+ community so far. For the details, please check our Official Twitter: [Assure_pro](https://twitter.com/Assure_pro) and Official TG group: [AssurePro](https://t.me/Assurepro) and [Discord server](https://discord.gg/8cZRnM82nC).

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, we have a mobile app, and we support both IOS and Android versions.  

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No, we do not have the desktop app for now. 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No, Assure did not have a browser extension for now as well. 

### Is it a hardware wallet?

No, Assure is not a hardware wallet. Cuz it is a software wallet. 

### Is the source code for the wallet fully open-source?

No, Assure is not open-source

### What license is the wallet software released under?

No.

### Who holds the private keys?

As Assure users, they will hold their own private keys themselves and should be responsible for the private key storage security. Cuz Assure is a decentralized Wallet, we will not have access to the private information of our users. Assure is a decentralized Wallet, for the most function, it is a non-custodial wallet as long as you put the money in the Wallet, not in some products, for example, the cloud wallet, the Binance trading account, your assets are on-chain and will not lose without the project. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Assure has many measures taken to ensure our users' asset security. 
For the technology aspect we have the following measures:
1/ Payment password encryption method (irreversible): bcrypt, encrypted with random salt as salt value.
2/ Mnemonics /private key encryption (reversible): plaintext password + salt value (Mnemonics)/("private key + corresponding chain address + corresponding chain in lowercase") for aes256 encryption (for login key generation)
3/ Forgetting the password (irreversible)
(1) private key: sha256 encryption (private key + address + chain) -> bcrypt encryption with salt value after forgetting the password 
   (2) Mnemonics: through the generation of eth0 address to forget the password operation (if forget the password, please use Mnemonics within this program)
4/
(1) CoinSecretKey: eth public key encryption, eth private key decryption
(2) Coinan account information obtained from the background decryption (reversible): aes256 encryption by salt fixed string

For product design aspect, Assure Wallet is a decentralized wallet that super points on the Security issue. Assure not only pay attention to the technical development, but also the professional institute auditing. For details, please check our [Certik Audit Report](https://www.assure.pro/Assure/Audit_Report.pdf).

### Has the wallet's smart contract code or security modules been audited?

https://www.assure.pro/Assure/Audit_Report.pdf

### Does the wallet have an internal security team?

No

### Any other security testing that should be noted?

the platform will make a test package every time on the shelves, to prevent the abnormal transmission of sensitive local information.

### Scam protection?

The platform will use the information marked on the chain to obtain whether the wallet receiving address is the address that has been frozen by the project, so as to prevent other users from losing their assets.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

No, not for now. 

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

Yes, Assure supports Ethereum applications. For details, please check: https://assuresupport.zendesk.com/hc/en-001/articles/5181349225487

### Does the wallet support staking directly?

No, Assure does not. 

### Does the wallet support swaps directly?

Yes, we support swaps directly. For tutorial, please check: https://assuresupport.zendesk.com/hc/en-001/articles/5550626562959

### Does the wallet support multi-chain networks?

Yes, Assure supports multi-chain networks. For now, we supports 12 chains: BTC, ETH, BSC, Solana, HECO, OKX, TRON, Polkadot, Cardano, Filecoin, Arbitrum, Optimistic. For detail, please check: https://assuresupport.zendesk.com/hc/en-001/categories/5180421126031-Wallet-Functions

### Does the wallet support Ethereum layer 2 networks?

Yes, Assure supports Optimistic and Arbitrum, which are the hot layer 2 networks. And Assure will work on more networks in the future. For details, please check https://assuresupport.zendesk.com/hc/en-001/categories/5180421126031-Wallet-Functions

### Does the wallet allow the user to customize gas fees?

Yes, Assure allows the user to customize gas fees. For the detail, please check: https://assuresupport.zendesk.com/hc/en-001/articles/5181392547855  

### Does the wallet support sending transactions to ENS addresses?

No, Assure does not support transaction to ENS addresses for now. 

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

No, not for now. 

### Does the wallet support EIP-1559 (type 2) transactions?

No, not for now. 

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Assure will support fiat exchange on the new version in October, it has been within testing. 

### Does the wallet support withdrawals to fiat?

Assure will support fiat exchange on the new version in October, it has been within testing. 

### Is the wallet a multi-signature wallet?

No, not for now. 

### Does the wallet support social recovery?

No, not for now. 

### Who can the ethereum.org team can contact regarding the wallet in future?

Please contact [Emma](https://t.me/Emmmawo) on TG

### Does the wallet have a dedicated support team?

Yes, we have a dedicated support team. And if you have issues, please contact our Dev team manager on TG with @yuk1239090

### What educational resources/documentation do you provide to users?

Yes, we have a tutorial and user guide in our [Help Center](https://assuresupport.zendesk.com/hc/en-001), which can be found on the App. 

### Does the wallet have any integrated tools not mentioned above?

Yes, Assure has integrated with Binance with Binance API, which can help our wallet users to trade within the wallet. Aswap has integrated with several Swap Dapp, for example, Sushiswap, uniswap, pancake, Apeswap, MDEX, Cherryswap, etc for now. And we will have more in the future.

**Comment by corwintines** [comment]
The docs are missing a lot of information, and the support link on the site doesnt work. Going to close this out. If you disagree, or this gets fixed, please do create another issue :)
