### ISSUE TITLE
Outdated content on Developer Resources page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#799]
**Is your feature request related to a problem? Please describe.**

"If you actually go to Ethereum.org and click on developers, the first resources you get are out of date. " - https://twitter.com/DennisonBertram/status/1235889745877774341

https://ethereum.org/developers/

**Describe the solution you'd like**

"I would say remove everything before 2019, maybe it can stay in an “archive” but enough of the material/links/projects that these resources reference no longer exist or are not actively maintained that we shouldn’t show them."
https://twitter.com/DennisonBertram/status/1235940513318043648

**Describe alternatives you've considered**

**Additional context**

**Comment by samajammin** [comment]
I think this concern is valid. Providing resources from 2017 on the top of this page goes against our [design principles](https://github.com/ethereum/ethereum-org-website/blob/dev/design-principles.md) to be credible & fresh.

Regularly auditing the content to ensure it's still relevant & up to date is critical. We always welcome eyes from the community on this!

**Comment by ethers** [comment]
General rule sounds fitting for most cases.

Keeping fresh is hard and we probably need a wiki like https://eth.wiki  Unfortunately that one is not modifiable on Github any longer.

**Comment by ethers** [comment]
How about a design principle that generally content must be permissively licensed:
https://creativecommons.org/use-remix/cc-licenses/#by
https://creativecommons.org/use-remix/cc-licenses/#by-sa
https://creativecommons.org/use-remix/cc-licenses/#by-nc-sa
Apache 2, MIT...

That way when the content gets old, there's a possibility of being able to copy it and host the updated content on ethereum.org or a wiki...

The top links on the Developers page are majority before 2019 and would get lost unless archived. Ideally some of those authors are still around and can update?  Or give permission for the content to be copied and updated?

**Comment by samajammin** [comment]
> How about a design principle that generally content must be permissively licensed

@ethers you're referring to content that we link out to? I do think that's an ideal case but not sure we want to create a hard rule that we will ONLY link out to content that is licensed under CC or similar. I'm curious if @jjmstark or anyone else has thoughts on this.

**Comment by ethers** [comment]
> you're referring to content that we link out to?

Yes.  Seems this is resolved with the current leaning that ethereum.org should have some content directly on it than just linking out.
