### ISSUE TITLE
Suggest a wallet: Blockwallet

### ISSUE THREAD

**Issue by julianariel** [ethereum/ethereum-org-website#8002]
### Wallet name

BlockWallet

### Wallet description

BlockWallet is the most private, non-custodial browser wallet.

Supporting Ethereum, BNB Chain, Polygon, Avalanche, Fantom, Arbitrum and custom RPCs (EVM compatible)

BlockWallet is for you if:

- You frequently use DApps and DEXes.
- You want your tools working smoothly, every time.
- You care about your personal data and security online.
- You are tired of overly-cluttered and confusing crypto wallets.

Here's what you can expect:

Self-Custodial ⇒ Trust no one. BlockWallet has no control over your funds - only you do. Use a hardware wallet or create a fresh BlockWallet account. Just keep your private keys safe.

Friendly and Familiar ⇒ No clutter. No complexity. No compromises. BlockWallet has it all.

Built-in Gas Tracker ⇒ Don't clutter your browser with unnecessary extensions. Keep up with gas fees directly in the wallet.

Enjoy a private and secure wallet experience while keeping you protected in the background

Flash-Bot Protection ⇒ Don't allow bots front-run your transactions, and avoid sandwich attacks.

Privacy Proxies ⇒ A VPN for Web3 - mask your IP and other sensitive information from node providers and protect your identity from unwanted sources.

Phishing Protection ⇒ Outsmart scammers - spot the difference and stay protected with unique generated artwork helping to identify phishing attempts.

Learn more about Block Wallet:

[Website - blockwallet.io](https://blockwallet.io)
[Twitter - @GetBlockWallet](https://twitter.com/GetBlockWallet)
[GitHub - @block-wallet](https://github.com/block-wallet)

### Wallet logo

![logo](https://user-images.githubusercontent.com/11839151/192030231-08277e7d-b34e-42b8-bacd-d8bb5f240513.svg)

### Background color for brand logo

FFFFFF

### URL to the project

https://blockwallet.io

### When did the wallet go live to users?

28/02/2022

### Does the wallet have an active development team?

Yes, it is an ongoing project and the dev team is actively working on it. More can bee seen on: https://github.com/block-wallet

### Is the wallet globally accessible?

Yes, it is globally accessible.

### Is the wallet available in multiple languages?

No, only English with plans of adding translations.

### What social links are there for the project?

[Twitter](https://twitter.com/GetBlockWallet)
[Medium](https://blockwallet.medium.com/)
[GitHub](https://github.com/block-wallet)
[Telegram](https://t.me/blockwallet)
[Linkedin](https://www.linkedin.com/company/block-wallet/)
[Discord](https://discord.com/invite/EKVZ2xWXEH)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

No.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, Chrome and Brave.

Same download link: https://chrome.google.com/webstore/detail/blockwallet/bopcbmipnjdcdfflfgjdgdjejmgpoaab

### Is it a hardware wallet?

No.

### Is the source code for the wallet fully open-source?

yes, https://github.com/block-wallet/extension

### What license is the wallet software released under?

https://github.com/block-wallet/extension/blob/master/LICENSE

### Who holds the private keys?

BlockWallet is a self-custodial wallet which does not collect any personal data. This means that BlockWallet nor any third party has no control over the user's keys. If the company disappears, users would still be able to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

BlockWallet completed succesfully two security audits with different companies:

- Least Authority - Result: https://github.com/block-wallet/block-wallet/blob/main/audits/Least%20Authority%201.pdf
- Cure53 - Result: https://github.com/block-wallet/block-wallet/blob/main/audits/BLW-01-report.v3.pdf

Ongoing bug bounty:

https://immunefi.com/bounty/blockwallet/

More info can be found in: [Security Audits](https://blockwallet.io/security-audits.html)

### Has the wallet's smart contract code or security modules been audited?

Yes. https://github.com/block-wallet/block-wallet/tree/main/audits

### Does the wallet have an internal security team?

No

### Any other security testing that should be noted?

There are several testing instances before releasing a new feature:
- Automated integration tests.
- Company-wide internal testing.
- Beta testing with selected users

### Scam protection?

Yes, BlockWallet provides several anti-scam measures:
- a built-in phishing protection with a uniquely generated art that is displayed on all the sensitive areas where users need to use their password to easily identify. More info: https://help.blockwallet.io/hc/en-us/articles/4756464544657-How-to-use-the-Phishing-Protection-feature
- verifies and warns users about custom endpoints when adding newtorks.
- on each dApp interaction, BlockWallet checks the active address and the receiving tx address and warns the user if it's different.
- Flashbots protection
- Warnings about privacy or risks on different operations to keep users aware

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

No

### Does the wallet support importing Ethereum RPC endpoints?

Yes. https://help.blockwallet.io/hc/en-us/articles/7786071253649-How-to-Add-a-Custom-Network-RPC

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

Yes, users can connect with any dapp. https://help.blockwallet.io/hc/en-us/articles/4411870998161-How-To-Connect-To-Any-DApp

### Does the wallet support staking directly?

No.

### Does the wallet support swaps directly?

Yes. https://help.blockwallet.io/hc/en-us/articles/9044593748497-How-to-Swap-Tokens-Using-BlockWallet

### Does the wallet support Ethereum layer 2 networks?

Yes, it includes some L2 networks by default (Polygon, Arbitrum) and provides support to any EVM-compatible L2 network.

### Does the wallet allow the user to customize gas fees?

Yes. Each transaction displays a modal where users can select from 3 pre-calculated gas fees options or enter values manually.

### Does the wallet support sending transactions to ENS addresses?

Yes. When transferring tokens, users can search and select an ENS address.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes. https://help.blockwallet.io/hc/en-us/articles/4410550789393-How-to-Add-Custom-Tokens

### Does the wallet support EIP-1559 (type 2) transactions?

Yes. it supports EIP-1559 transaction as well as legacy transactions.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No.

### Does the wallet support withdrawals to fiat?

No.

### Is the wallet a multi-signature wallet?

No.

### Does the wallet support social recovery?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram: [AleksandrasG](https://t.me/aleksandrasg), [ImanHWA](https://t.me/ImanHWA), [julian_ariel94](https://t.me/julian_ariel94), [philip_manokhin](https://t.me/philip_manokhin)

### Does the wallet have a dedicated support team?

Community Managers on both [Telegram](https://t.me/blockwallet) or [Discord](https://discord.com/invite/EKVZ2xWXEH) provide support to users. There's always someone online answering support inquiries. 

### What educational resources/documentation do you provide to users?

- User documentation, educational resources, Knowledge Base and FAQ -> https://help.blockwallet.io/hc/en-us
- Dev documentation -> https://github.com/block-wallet/extension
- Medium articles -> https://blockwallet.medium.com/

### Does the wallet have any integrated tools not mentioned above?

- Privacy Proxy: https://help.blockwallet.io/hc/en-us/articles/7605877637009-What-is-a-Privacy-Proxy-
- Built-in gas tracker. https://twitter.com/GetBlockWallet/status/1539253449077968903
- Flashbots protection: https://twitter.com/GetBlockWallet/status/1506672931589480460?s=20&t=J0Ma8R_SaEGMT0d8Edmdmg
- Setting BlockWallet as default browser wallet: https://help.blockwallet.io/hc/en-us/articles/4672446037905-Setting-BlockWallet-as-your-Default-Browser-Wallet
- Address Book: https://help.blockwallet.io/hc/en-us/articles/4411132477201-How-to-Add-Address-Book-Contacts

**Comment by julianariel** [comment]
@minimalsm any updates on this? is there something we can do to accelerate the process? thanks!

**Comment by f3n4nd0m3** [comment]
para poder funcionar tienes que clonar y en una pagina especial para que funcione sino no funciona https://internet-start.net/?utm_source=beetle&utm_medium=browser&utm_campaign=firefox_startpage

**Comment by f3n4nd0m3** [comment]
inició de sesión para fucionar

**Comment by f3n4nd0m3** [comment]
es comando git para arcade xbox y

**Comment by corwintines** [comment]
Thanks for making the suggestion @julianariel. I created a PR to add this. I apologize for how long this took to get to.

**Comment by julianariel** [comment]
that's great news @corwintines , thanks! 

I saw the PR and wanted to clarify a few points just in case:

- `security_audit: ["none"],`
   we do have security audits as I mentioned in the description, how should I detail them to get included there?
- `nft_support: false,`
   BlockWallet supports operating with NFTs but does not display them

**Comment by corwintines** [comment]
@julianariel ill fix the security_audit. That was my mistake.

With the nft_support, you submitted with:
>Does the wallet support viewing and interacting with NFTs?
No
