### ISSUE TITLE
Link to blog is broken on https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/

### ISSUE THREAD

**Issue by MacMorgan** [ethereum/ethereum-org-website#8010]
### Describe the bug

Link to blog is broken on https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/

### To reproduce

Go to https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#updating-clients
Click "blog" link
Observe 404

### Expected behavior

"blog" should navigate to https://blog.ethereum.org

**Comment by hursittarcan** [comment]
Cannot reproduce this bug, works fine on my machine.

**Comment by MacMorgan** [comment]
Try Safari

**Comment by MacMorgan** [comment]
Here is a screen recording...

https://user-images.githubusercontent.com/17681/192153799-60a9df70-7e89-4fc9-9e8b-f13076d720ad.mov
