### ISSUE TITLE
Link to challenges.ethereum.org

### ISSUE THREAD

**Issue by tasdienes** [ethereum/ethereum-org-website#802]
**Is your feature request related to a problem? Please describe.**
I could not find a link to challenges.ethereum.org from the ethereum.org site

**Describe the solution you'd like**
Make it easier for researchers to look for interesting problems to work on.
Additional info on this topic can be found at https://ecosystem.support/wishlist/
and https://vitalik.ca/general/2019/11/22/progress.html 

**Describe alternatives you've considered**

**Additional context**

**Comment by samajammin** [comment]
Hey @tasdienes - thanks for raising this issue!

We actually do link to challenges.ethereum.org, though not prominently. It's currently on these pages:
https://ethereum.org/community/#how-can-i-get-involved
https://ethereum.org/learn/#improving-ethereums-scalability

Do you have suggestions on where else we should display it?

**Comment by tasdienes** [comment]
You are so right!  I typed "challenges" into the search box and it didn't find anything, so I gave up.  My bad.

Btw, it might be good to add a link to https://ecosystem.support/wishlist/ (which is pretty new) in the "How can I get involved?" section.

**Comment by samajammin** [comment]
Mmmmya, the current site search is fairly limited - right now it only includes results by page title or sub-headers. It'd a good idea to add more advanced search functionality.

Agree re: adding https://ecosystem.support/wishlist/ ! I'll add that now.
