### ISSUE TITLE
Replace placeholder text with template text in bug issue template

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#8029]
### Is your feature request related to a problem? Please describe.

Before we migrated our issues to [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), we had template text that you could edit to describe a bug. It has been replaced with placeholder text, that disappears when you type. (i.e. now I have to type manually all of the steps, instead of editing the existing text)

Default state:

<img width="974" alt="Screenshot 2022-09-26 at 11 30 08" src="https://user-images.githubusercontent.com/62268199/192254910-38050c9b-e7d3-4616-b8d4-3ad01fc0a984.png">

When I type:

<img width="976" alt="Screenshot 2022-09-26 at 11 33 43" src="https://user-images.githubusercontent.com/62268199/192255490-b62983b7-9e8d-48b4-934a-b9b8df2ddfee.png">

### Describe the solution you'd like

If possible, replace the placeholder text with template text that can be edited.

**Comment by Aksa12** [comment]
Can I work on this issue? I have submitted the PR above. Please let me know if any other changes are required? Thanks.

**Comment by minimalsm** [comment]
Thanks @Aksa12, closed in #8036
