### ISSUE TITLE
Visual regression in markdown lists

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#8031]
### Describe the bug

The lists are no longer displaying as intended.

- Spacing between list items is not correct

You can [see how they displayed before in this preview](https://ethereumorgwebsitedev01-networkupgradescomponent.gtsb.io/en/nft) versus [how they display now.](https://ethereum.org/en/nft/)

### To reproduce

1. Go to https://ethereum.org/en/nft/
2. Scroll down to [the NFT examples section](https://ethereum.org/en/nft/#nft-comparison)
3. See visual regression

### Expected behavior

The list should be correctly formatted ([as per the previous visual style](https://ethereumorgwebsitedev01-networkupgradescomponent.gtsb.io/en/nft)) with adequate space between list items.

### Screenshots

Current:

<img width="963" alt="Screenshot 2022-09-26 at 11 44 53" src="https://user-images.githubusercontent.com/62268199/192258002-59bccc2b-316e-48fd-97e4-5afe436ba17a.png">

Before (expected):

<img width="933" alt="Screenshot 2022-09-26 at 11 45 01" src="https://user-images.githubusercontent.com/62268199/192258009-49e140d1-c672-43c1-91b4-cb74b86a9999.png">

### Additional context

I suspect this happened as part of [the migration to Chakra.](https://github.com/ethereum/ethereum-org-website/issues/6374)

**Comment by AidanPine** [comment]
Hello, I would like to take on the responsibility for this issue if possible.

**Comment by Pro-Coder04** [comment]
@minimalsm could you help me to out to find the location where the source code for this file would be?

**Comment by minimalsm** [comment]
@AidanPine @Pro-Coder04 

Hey folks. As noted [in this comment](https://github.com/ethereum/ethereum-org-website/issues/8030#issuecomment-1257998371), it looks like this was caused by us not pulling over some global styles in our migration to emotion/Chakra from styled-components.

@pettinarip are you working on this already, or is it something we can allocate?

**Comment by NoireBlanc** [comment]
@minimalsm I've already done work moving over the global list item styles, and it seems to have fixed the visual regression issue. However, in the expected look of the webpage you've linked, the first list featured on the nft page does not have the same list item spacing as the rest of the page. Is this expected, or is a consistent spacing for all lists with no exceptions preferred?

**Comment by pettinarip** [comment]
Thanks folks for the help with this. We are trying to fix it under #8139 by just using Chakra components.
