### ISSUE TITLE
Safari does not load fav icon on some pages

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#8044]
### Describe the bug

when I follow a link without going to the homepage on safari the favicon is missing.

If I navigate from the homepage it's ok.

### To reproduce

1. open safari desktop
2. https://ethereum.org/en/energy-consumption/#introduction
3. see if you have the favicon on the browser window

### Expected behavior

The fav icon should appear all the time.

### Screenshots

![Screen Shot 2022-09-27 11 11 33 AM](https://user-images.githubusercontent.com/1120748/192499755-bf40b277-cef1-4eb4-ae79-9fe7a9cb6144.png)
compare with and without the favicon

![Screen Shot 2022-09-27 11 08 45 AM](https://user-images.githubusercontent.com/1120748/192499821-d6dbbc3e-bf2d-4c21-b8d3-e8d5205466be.png)
this is how brave shows the favicon

### Desktop (please complete the following information)

macOS 12.5.1
safari 15.6.1

**Comment by brandonmcconnell** [comment]
@nloureiro This actually appears to work for me, running Safari v16.0 (17614.1.25.9.10, 17614).

**Comment by nagabhiru** [comment]
Same as @brandonmcconnell, I'm able to see the favicon on Safari desktop and on Safari mobile (Version 16.0 (17614.1.25.9.10, 17614))
