### ISSUE TITLE
update the color for the buttons

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#8048]
### Describe the bug

We had to make a small revision on how the colours were used in the buttons, and we updated the Design system.

link to the design system
https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=545%3A16075

It needs to be updated in the code.

### To reproduce

1. see the hover behaviour on the CTA buttons on ethereum.org

### Expected behavior

Remove the transparency and add new color design tokens
![Screen Shot 2022-09-27 12 36 10 AM](https://user-images.githubusercontent.com/1120748/192516252-9d288088-0880-472f-a279-fb29b026fe16.png)
this image can help to see the differences.

### Desktop (please complete the following information)

all OS

**Comment by Mustafa-Azad025** [comment]
hey @nloureiro ,
I am willing to contribute to this and will i have to change button.tsx only ? 
and Please assign this task to me

**Comment by nloureiro** [comment]
> hey @nloureiro ,
> I am willing to contribute to this and will i have to change button.tsx only ?
> and Please assign this task to me

Hey, Thank you for showing interest in this.
I assume it's only button.tsx but I'm not sure. 
probably you just need to be sure the colors variables are set. Should be easy.

**Comment by Nishant891** [comment]
Hey! This is my first time participating in hacktoberfest .
I have been working previously on buttons in CSS.
I would love to contribute.

**Comment by Mustafa-Azad025** [comment]
Hey @nloureiro ,
Very Sorry To Say That I Am Unable To Do This Task As I Am Unable To Open The Theme File My Code Editor Is Not Respond 😥 To File So If You Can Give It To @Nishant891 Your Work Will Not Be Delayed.

**Comment by ernestosperanza** [comment]
Hey may I work on this issue?

**Comment by corwintines** [comment]
Thanks @ernestosperanza! Will assign to you now :)

**Comment by corwintines** [comment]
@nloureiro wondering if you know the state of this issue at the moment? 

@TylerAPfledderer maybe this is something you have handled in your design system implementation work for Buttons as well.

**Comment by TylerAPfledderer** [comment]
@corwintines hmm it might have been updated in #10315 at this point.

**Comment by nloureiro** [comment]
> @corwintines hmm it might have been updated in #10315 at this point.

yes, Ias far as I understand this is the way ;)
