### ISSUE TITLE
Migrate `GitStars` component to Chakra UI

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8049]
This is part of our [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.

## Description

Migrate `src/components/GitStars.tsx` from `emotion` styled components to `chakra`.

This components is used in https://ethereum.org/en/developers/local-environment/
![image](https://user-images.githubusercontent.com/468158/192538878-a20965f7-2720-46cd-9f32-d9c9909cc469.png)

## Additional resources
Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) for more information & check our [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md).

**Comment by curiousyuvi** [comment]
I would like to work on this issue, please assign it to me.

**Comment by pettinarip** [comment]
Thanks @curiousyuvi!

**Comment by curiousyuvi** [comment]
Hey @pettinarip, I think [this](https://github.com/ethereum/ethereum-org-website/pull/8142) PR already fixes this issue, so I'll find some other issue to contribute.
