### ISSUE TITLE
Migrate `Slider` component to Chakra UI

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8051]
This is part of our [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.

## Description
Migrate `src/components/Slider.tsx` from `emotion` styled components to `chakra`.

This component is used in https://ethereum.org/en/what-is-ethereum/
![image](https://user-images.githubusercontent.com/468158/192540772-0f55bcff-4fb5-4b30-9420-70e69afb3d97.png)

## Additional resources
Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) for more information & check our [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md).

**Comment by lawlesx** [comment]
I will start with this

**Comment by lawlesx** [comment]
I would like to work on this.

**Comment by lawlesx** [comment]
@pettinarip Created a PR resolving this
Sorry for the delay, last week was hectic.

**Comment by pettinarip** [comment]
Done! thanks t o @lawlesx
