### ISSUE TITLE
Suggest an exchange

### ISSUE THREAD

**Issue by mdewji-shakepay** [ethereum/ethereum-org-website#8058]
### Exchange name

Shakepay

### Exchange description

Shakepay is a Canadian Exchange that supports Ethereum and Bitcoin. The are registered with FINTRAC in Canada. They also cover all gas fees for transactions to move ETH off platform.

### What geographical restrictions apply to this exchange?

Canada only

### Which currencies are accepted by this exchange?

CAD, BTC, ETH

### Do you have any proof that they're a legitimate company?

http://shakepay.com/

https://www10.fintrac-canafe.gc.ca/msb-esm/public/detailed-information/msb-details/7b226d73624f72674e756d626572223a3134393737362c227072696d617279536561726368223a7b226f72674e616d65223a225368616b65706179222c2273656172636854797065223a317d7d/

### Do you have any extra information?

Shakepay has been around since 2017. They are also active on Social media:

https://twitter.com/shakepay
https://reddit.com/r/shakepay

**Comment by corwintines** [comment]
Closing as PR has been merged.
