### ISSUE TITLE
align to the bottom the card content

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#8062]
### Describe the bug

On the developers page, the content of the cards should alight to the bottom.

### To reproduce

1. got to https://ethereum.org/en/developers/
2. scroll down to the "How would you like to get started?" section
3. the interior of the third card should be align to the bottom

### Expected behavior

Align the buttons to the bottom, and the interior text should start at the same point 

### Screenshots

This is how it is:
![Screen Shot 2022-09-28 11 59 19 AM](https://user-images.githubusercontent.com/1120748/192783906-173659e1-e533-48ac-9bf5-5f8548aded29.png)

This is how it should be:
![Screen Shot 2022-09-28 01 58 25 PM](https://user-images.githubusercontent.com/1120748/192784524-8ed9641d-ab4c-4243-9dfe-a23e3e5d3f25.png)

### Desktop (please complete the following information)

all OS

**Comment by najeebkp** [comment]
Hi, I would like to take care of this. can you please assign this to me? @nloureiro

**Comment by nloureiro** [comment]
> Hi, I would like to take care of this. can you please assign this to me? @nloureiro

It's yours :) Thank you!
