### ISSUE TITLE
Reward and Penalty Documenation outdated

### ISSUE THREAD

**Issue by wenlanbo** [ethereum/ethereum-org-website#8074]
### Describe the bug

In Rewards {#rewards}

The base reward calculation is outdated.

### To reproduce

1. Go to (https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/#rewards)

### Expected behavior

After Altair fork
The base reward calculation should be:

base_reward = effective_balance * (base_reward_factor /  sqrt(sum(active_balance)))

**Comment by julian-st** [comment]
do you have a source for that? Because if I look here https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/ for get_base_reward the base_rewards_per_epoch is still in there

**Comment by wenbo-alkimiya** [comment]
This is the source for this change

https://github.com/ethereum/consensus-specs/blob/4370f30b99142d92bf676f0ee6a0aa74f688f891/specs/altair/beacon-chain.md#get_base_reward

**Comment by heeckhau** [comment]
This issue is already fixed. It can be closed.
