### ISSUE TITLE
code block have wrong font size

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#8076]
### Describe the bug

When displaying code block, like code , pre , etc, the font is bigger than it's supposed to be.

This how we have it now:
`pre, code, kbd, samp {
    font-family: SFMono-Regular,Menlo,Monaco,Consolas,monospace;
    font-size: 1em;`

This is how it is supposed to be:
`pre, code, kbd, samp {
    font-family: SFMono-Regular,Menlo,Monaco,Consolas,monospace;
    font-size: 0.8em;
    line-height: 1.1rem;`

### To reproduce

1. go to this page https://ethereum.org/en/developers/docs/smart-contracts/
2. see the code blocks
3. inspect the css and confirm that the font size is at 1rem

### Expected behavior

The font size is supposed to be smaller.

### Screenshots
This how we have it now:
![Screen Shot 2022-09-29 08 59 10 AM](https://user-images.githubusercontent.com/1120748/192977438-eb44edff-a62b-4085-8a17-e1d417aa49c0.png)

This is how it is supposed to be:
![Screen Shot 2022-09-29 09 13 08 AM](https://user-images.githubusercontent.com/1120748/192977547-bac338c8-4298-4b20-aedc-19c6d0d9faf1.png)

**Comment by amit-ksh** [comment]
I like to work on this, can you assign this to me?

**Comment by VaibhavArora19** [comment]
Can I take this up?
