### ISSUE TITLE
SSR - Hydration bugs

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8083]
### Describe the bug

We have different hydration mismatches across the site. We are server-side rendering something different than what the client-side is.

### To reproduce

1. On your local setup run `yarn start`
2. Visit http://localhost:8000/en/layer-2/
3. See hydration popup error

### Expected behavior

We don't have any hydration mismatches.

### Screenshots

![image](https://user-images.githubusercontent.com/468158/193035898-b4e95529-f344-42e8-aca2-f2f32e9a9588.png)

### Additional context

One potential place where we might have the problem is in `gatsby-browser.tsx` where we are rendering something different based on the `IS_DEV` flag.

**Comment by corwintines** [comment]
https://github.com/ethereum/ethereum-org-website/pull/8247 closing as this has been merged in
