### ISSUE TITLE
Content Update - Rework on Backend API Page

### ISSUE THREAD

**Issue by nmoreau** [ethereum/ethereum-org-website#8102]
### Dev tool name

Proposal to reoganize the page

### Dev tool description

This page is very very confusing.
https://ethereum.org/en/developers/docs/apis/backend/

I suggest to reschuffle the page to make a clear distinction between Nodes and Libraries.

- Nodes
- - Either your run your node and connect your Dapp to that node. This can work in a local developement environnement, but can hardly scale (need upgrades, up time and loadbalancing, ...)
- - Or you use an infrastructure provider to run the Node for you and provide an endpoint to connect to.
- Libraries / Helpers to connect to nodes. This is an alternative to crafting the JSON-RPC requests.

I am proposing tio breakdown the page as follows 
1. Why use a Node Provider
2. Why use a Library
3. Available Node Providers - With some of them providing their own SDK/Libraries
4. Available Libraries

### When did the dev tool go live?

Now

### Where do you think this page should be shown?

Update this page https://ethereum.org/en/developers/docs/apis/backend/

### Is the product open source?

No

### Documentation URL

https://ethereum.org/en/developers/docs/apis/backend/

### Additional context

Before working on this, I want to have a green light and then can spend some time on this to make a proposal.

**Comment by corwintines** [comment]
Going to close this out as stale @nmoreau, if this still interests you @nmoreau feel free to reopen a new issue. Can ping me on discord (corwintines) so this doesn't get lost again.
