### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jcvernaleo** [ethereum/ethereum-org-website#8116]
### Describe the bug

The links:
https://ethereum.org/en/developers/docs/apis/json-rpc/#net_peercount
and
https://ethereum.org/en/developers/docs/apis/json-rpc/#net_listening
are swapped.

### To reproduce

Go to the links above.

### Expected behavior

Links should point to the correct sections.

**Comment by corwintines** [comment]
Closing as PR has been merged
