### ISSUE TITLE
Invalid link for OpenZeppelin proxy patterns in smart contract doc

### ISSUE THREAD

**Issue by 0x7a68** [ethereum/ethereum-org-website#8134]
### Describe the bug

'Link for [More on proxy patterns](https://ethereum.org/enblog.openzeppelin.com/proxy-patterns/)' in ethereum stack doc directs to a missing page

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/smart-contracts/upgrading/#proxy-patterns
2. Click on '[More on proxy patterns](https://ethereum.org/enblog.openzeppelin.com/proxy-patterns/)'
3. See error: https://ethereum.org/enblog.openzeppelin.com/proxy-patterns/ was open and `We couldn't find that page` was shown

### Expected behavior

It should open https://blog.openzeppelin.com/proxy-patterns/

### Desktop (please complete the following information)

- MacOSX
- Chrome

**Comment by julian-st** [comment]
I try to fix this

**Comment by minimalsm** [comment]
Closed in #8135 and #8137 :-)
