### ISSUE TITLE
Wrong merge date on upgrade FAQ

### ISSUE THREAD

**Issue by bizzyvinci** [ethereum/ethereum-org-website#8141]
### Describe the bug

When will the upgrades ship? is one of the FAQ on upgrades page and it states:

> [The Beacon Chain](https://ethereum.org/en/upgrades/beacon-chain/)
> The Beacon Chain went live on December 1, 2020.
> 
> [The Merge](https://ethereum.org/en/upgrades/merge/)
> The Merge is when Mainnet begins using the Beacon Chain for consensus, and proof-of-work is turned off, coming soon.

But the merge has occurred on September 15, 2022

### To reproduce

1. Go to [upgrades page](https://ethereum.org/en/upgrades/)
2. Scroll down to 'Frequently asked questions'
3. Click on 'More' for 'When will the upgrades ship?'

### Expected behavior

You'll see the outdated information

### Screenshots

<img width="1467" alt="Screenshot 2022-10-02 at 19 02 31" src="https://user-images.githubusercontent.com/22333930/193468983-0576c0e7-6aba-4b52-acff-7ca53c6393a2.png">

**Comment by issa-me-sush** [comment]
hey! I would love to work on this, could I please be assigned this  issue?

**Comment by minimalsm** [comment]
Hey @issa-me-sush 👋 Sure, assigned! Thanks for offering to help :-) 

LMK if you need any help here 🙂

**Comment by issa-me-sush** [comment]
thank you for the opportunity, I think the text was modified partially  in one of the merges few hrs prior to me being assigned, but on the deployed official page it still isnt visible, have made some appropriate changes for the faq text and opened pull request, hope its fine, thank you
