### ISSUE TITLE
Update existing glossary term

### ISSUE THREAD

**Issue by LucasMartinCalderon** [ethereum/ethereum-org-website#8163]
### Checklist

- [X] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [X] This term/definition is not a product advertisement or contain other promotional content
- [X] This term/definition is directly relevant to Ethereum

### Term name

DAG

### Term definition

DAG stands for Directed Acyclic Graph. It is a data structure composed of nodes and links between them. Previous to The Merge, Ethereum used a DAG in its [proof-of-work](https://ethereum.org/en/glossary/#pow) algorithm, [Ethash](https://ethereum.org/en/glossary/#ethash).

### Additional context

As it stands today, it might cause confusion for new and existing users, given that it states in present form that Etherum "uses a DAG in its proof-of-work algorithm", which is no longer the case.

**Comment by corwintines** [comment]
Closing as this was updated in above release
