### ISSUE TITLE
Tap outside wallet filter panel to close on mobile

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#8170]
### Describe the bug

Right now a user can only tap on the X to close the filter panel. But, if a user taps outside the panel this should also close the filter panel

https://user-images.githubusercontent.com/15589226/193881389-d8eb608c-53b8-4e4f-9d44-ecedf5499e82.mov

### To reproduce

1. Go to [find wallets](https://ethereum.org/en/wallets/find-wallet/) on a mobile device, or in mobile view in the browser
2. Open the filters panel
3. Try to close the filters panel by tapping outside of it
4. Filter panel doesn't close

### Expected behavior

1. Go to [find wallets](https://ethereum.org/en/wallets/find-wallet/) on a mobile device, or in mobile view in the browser
2. Open the filters panel
3. Tap outside filter panel
4. Filter panel should close

### Screenshots

Uploading Screen Recording 2022-10-04 at 10.55.40 AM.mov…

### Desktop (please complete the following information)

Can simulate in mobile view on desktop browsers

### Smartphone (please complete the following information)

On all mobile devices

**Comment by corwintines** [comment]
Hey @Aksa12!

Thanks for taking this on. If possible would like any area outside of the filter panel to close the panel. 

Ill assign this to you.

**Comment by Aksa12** [comment]
@corwintines done in the linked PR.
