### ISSUE TITLE
Find wallet reset filters not resetting device toggle

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#8171]
### Describe the bug

When resetting filters, all filters are reset, but the UI has a but where the device toggles stay selected

https://user-images.githubusercontent.com/15589226/193894175-480c4f40-f12a-4354-b31a-8a3bfb1e4ca1.mov

### To reproduce

1. Go to [find wallets](https://ethereum.org/en/wallets/find-wallet/)
2. Toggle a device filter and any other filters you want
3. Click reset filters
4. All filters are reset, but the toggles for device remain active

### Expected behavior

1. Go to [find wallets](https://ethereum.org/en/wallets/find-wallet/)
2. Toggle a device filter and any other filters you want
3. Click reset filters
4. All filters are reset, and device toggles are reset

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by ankitzm** [comment]
hey, would love to take up this issue and will be raising a PR soon !!

**Comment by corwintines** [comment]
Thanks @ankitzm! Will assign to you :)

**Comment by Aksa12** [comment]
@ankitzm are you working on this issue or can I take it up?

**Comment by ankitzm** [comment]
Yes working on it currently, will be raising a PR soon !!

**Comment by ankitzm** [comment]
Just made a PR with the required changes. #8291

**Comment by corwintines** [comment]
Closed with above PR
