### ISSUE TITLE
Find wallet filter panel animation

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#8172]
### Is your feature request related to a problem? Please describe.

On mobile, when a user opens the filter panel, right now it appears instantly. And when the user closes the panel disappears instantly. This makes for a weird user experience.

### Describe the solution you'd like

When a user opens the filter panel in mobile view, the filter panel should animate in from the left.

When a user closes the filter panel in mobile view, the filter panel should animate out to the left.

### Describe alternatives you've considered

None

**Comment by curiousyuvi** [comment]
I would like to work on this issue, please assign it to me.

**Comment by curiousyuvi** [comment]
I have opened a [PR](https://github.com/ethereum/ethereum-org-website/pull/8193) that resolves this issue.

**Comment by corwintines** [comment]
@curiousyuvi thanks! Ill try and get to reviewing this week :)

**Comment by vishal590** [comment]
@corwintines assign this task to me🙏🙏

**Comment by vishal590** [comment]
@Corwintines Issue resolve, I made branch vishal-dev from dev and made changes in branch.
I want to commit the issue.
what should I put in commit ? Fixes ?
and which branch to push dev or my vishal-dev branch which I created

**Comment by vishal590** [comment]
@wackerow could you check this, I fixed this issue. I think 20 to 25 days left, no one check this

**Comment by corwintines** [comment]
Going to close this out as the find wallets table in general needs a larger refactor.
