### ISSUE TITLE
Add TECHFUND as new auditing service to smart contract testing page 

### ISSUE THREAD

**Issue by nautical** [ethereum/ethereum-org-website#8213]
Adding TECHFUND to the list of auditing services in docs. TECHFUND ( https://techfund.jp ) is a security auditing firm based out of Tokyo, Japan. 

PR Coming soon.

**Comment by corwintines** [comment]
Hey @nautical.
 
Was looking into this, and wondering if https://hiaudit.io/ is what you are referring to for the audit service?

**Comment by corwintines** [comment]
See comment in https://github.com/ethereum/ethereum-org-website/pull/8535
