### ISSUE TITLE
Description for Lighthouse has been replaced by snap sync description

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/ethereum-org-website#8227]
### Describe the bug

The description for Lighthouse is currently about Snap Sync. It looks like there was a valid description for Lighthouse that was accidentally replaced with some text about Snap Sync: https://ethereum.org/en/developers/docs/nodes-and-clients/#lighthouse

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/nodes-and-clients/#lighthouse
2. See this text:

> - Fastest sync strategy developed by Geth, currently its default.
> - Nethermind only implemented the consuming part until now. They are working on enabling serving other nodes soon.
> - Saves a lot of disk usage and network bandwidth without sacrificing security.
> 
> [More on Snap](https://github.com/ethereum/devp2p/blob/master/caps/snap.md)

### Expected behavior

There should be a description of Lighthouse. One can probably be resurrected from the history.

### Screenshots

![lighthouse_snap](https://user-images.githubusercontent.com/4452260/194999281-7a59db9a-5cf7-4675-b3bc-6bfa23bad075.png)

### Desktop (please complete the following information)

Firefox on Linux

**Comment by amit-ksh** [comment]
I would like to take this issue.

**Comment by jmcook1186** [comment]
thanks for fixing this!
