### ISSUE TITLE
Add a "back to top" button 

### ISSUE THREAD

**Issue by giftade** [ethereum/ethereum-org-website#8237]
some web pages on the Ethereum site are long, so adding this would make it easier to go back to the start.

**Comment by corwintines** [comment]
I think this is a good idea, and something I have heard requested many times. Will bring to grooming to advocate for.

**Comment by corwintines** [comment]
I have refreshed this issue here https://github.com/ethereum/ethereum-org-website/issues/12194

Going to close this out
