### ISSUE TITLE
Stack Exchange ETH & Peeranha

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/ethereum-org-website#8241]
### Dev tool name

Stack Exchange ETH & Peeranha

### Dev tool description

Q&A forums for web3

### When did the dev tool go live?

A few years ago

### Where do you think this page should be shown?

Online communities

### Is the product open source?

Yes

### GitHub URL

https://github.com/peeranha

### Documentation URL

https://github.com/peeranha

**Comment by corwintines** [comment]
Closed with above PR
