### ISSUE TITLE
## :white_check_mark: ethereum-org-website-dev deploy preview ready

### ISSUE THREAD

**Issue by Abu2rkyi** [ethereum/ethereum-org-website#8255]
## :white_check_mark: ethereum-org-website-dev deploy preview ready
* [Deploy preview](https://ethereumorgwebsitedev01-rctokengating.gtsb.io)
* [Build logs](https://gatsbyjs.com/dashboard/5e02f963-3fe5-4e37-a1e7-ac05f7753a86/sites/dc7c4340-a8e9-44ed-b7be-883c70d2f02d/builds/661d40ab-6128-4ca9-9cde-d75b8fafe1b6/details) · **33m** build time

_Originally posted by @gatsby-cloud[bot] in https://github.com/ethereum/ethereum-org-website/issues/8254#issuecomment-1279270886_

**Comment by corwintines** [comment]
Please stop @Abu2rkyi
