### ISSUE TITLE
Migrated Slider.tsx component to Chakra UI

### ISSUE THREAD

**Issue by hoanglamcoin** [ethereum/ethereum-org-website#8277]
## Description
Migrated `Slider.tsx` component to Chakra UI

### Screenshots
**Dark Mode**
Before
<img width="891" alt="Screenshot 2022-10-16 at 12 02 45 AM" src="https://user-images.githubusercontent.com/52166437/196002706-5f52d743-7880-44c1-b079-2adfb0f4ce2e.png">
After
<img width="883" alt="Screenshot 2022-10-16 at 12 02 34 AM" src="https://user-images.githubusercontent.com/52166437/196002713-e296a463-3863-4ada-8546-fbddd7f7962a.png">

**Light Mode**
Before
<img width="878" alt="Screenshot 2022-10-16 at 12 03 01 AM" src="https://user-images.githubusercontent.com/52166437/196002745-742d7fbe-9345-4bf2-b3fb-5bba72ef405c.png">
After
<img width="883" alt="Screenshot 2022-10-16 at 12 02 55 AM" src="https://user-images.githubusercontent.com/52166437/196002749-330c474a-64fe-4413-a236-b4b9b3d61315.png">

## Related Issue

 Resolves Issue #8051 

__Originally posted by @lawlesx in https://github.com/ethereum/ethereum-org-website/pull/8266__

__Originally posted by @hoanglamcoin in https://github.com/hoanglamcoin/Ether/issues/1__

**Comment by amit-ksh** [comment]
Can I work on this?

**Comment by pettinarip** [comment]
Sorry @amit-ksh there is already a PR open for this migration #8266 

Closing as this issue is duplicated.
