### ISSUE TITLE
Upcoming Events are not current

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#828]
Events list located [here](https://ethereum.org/community/#online-communities) are not current due to COVID-19 issues.

- EDCON is [cancelled](https://twitter.com/EDCON_Official/status/1231158547779473410?s=20) this year
- Ethereal Summit is [now completely virtual](https://twitter.com/EtherealSummit/status/1238427310409252864?s=20)
- ETHNYC has been [postponed](https://twitter.com/ETHGlobal/status/1238212524438441986?s=20)

**Comment by samajammin** [comment]
@all-contributors please add @tvanepps for bug reports
