### ISSUE TITLE
Add information on how withdrawals will work

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#8288]
### Is your feature request related to a problem? Please describe.

There was a recent discussion in [Discord](https://discord.com/channels/714888181740339261/776139785550168084/1031726901221412864) around how withdrawals will work when implemented, and the lack of information around this. Too clear this up for the community, we should add some more information to clarify how withdrawals will work when implemented.

### Describe the solution you'd like

Add an FAQ onto the upgrades page on how withdrawals will work

### Describe alternatives you've considered

N/A

### Additional context

Discord discussion: https://discord.com/channels/714888181740339261/776139785550168084/1031726901221412864

**Comment by mail4metablocks** [comment]
Can you assign this to me? i can contribute

**Comment by corwintines** [comment]
Closing in favor of https://github.com/ethereum/ethereum-org-website/issues/9101
