### ISSUE TITLE
Altair Penalties Description Error

### ISSUE THREAD

**Issue by timbeiko** [ethereum/ethereum-org-website#8297]
### Describe the bug

h/t to @eliasimos @ariskk for flagging 

--- 

On [this page](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/#penalties), we can read: 

> The penalties for missing the head, target and source votes are equal to the rewards the attestor would have received had they submitted them. This means that instead of having the reward added to their balance, they have an equal value removed from their balance. There is no penalty associated with the inclusion_delay - the reward will simply not be added to the validator's balance. There is no penalty for failing to propose a block.

According to spec though it seems that there is no penalty for missing the head vote post-Altair

See:
* here: https://eth2book.info/bellatrix/part3/helper/accessors#def_get_flag_index_deltas
* here: (Altair spec - `get_flag_index_deltas`): 
https://github.com/ethereum/annotated-spec/blob/master/altair/beacon-chain.md#get_flag_index_deltas
* here (Bellatrix spec, no changes were made to the rewarding and penalty-giving function - `get_flag_index_deltas`): https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/beacon-chain.md#modified-get_inactivity_penalty_deltas

It would be good for someone involved in the CL specs to sanity check, though. 

### To reproduce

N/A

### Expected behavior

Text should reflect the spec

**Comment by jmcook1186** [comment]
Thanks for pointing this out - fixed in PR #8302
