### ISSUE TITLE
Feature request: Modify feedback widget behavior

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#8298]
### Is your feature request related to a problem? Please describe.

We want to modify the behavior of our feedback widget so its more prominent on desktop devices as right now we do not get enough desktop user feedback (most responses are coming from mobile devices).
<img width="216" alt="Screenshot 2022-10-19 at 12 10 55" src="https://user-images.githubusercontent.com/100724231/196758871-ee6976b9-5ce6-4bee-a7d7-860798661946.png">

### Describe the solution you'd like

**Add new behavior:**
<img width="206" alt="Untitled" src="https://user-images.githubusercontent.com/100724231/196759364-0ac17209-8021-4016-8470-76bdbcd135b1.png">

- Add new animation after 30 sec spent on page: change the default state to this new expanded state (there should be an animation of this expanding to the left 500MS)
- Once user clicks into it and closes the component, it should return to the small bubble
- This should happen once per session max.
- Animation is only for desktop devices.

### Describe alternatives you've considered

NA

**Comment by marcellamalune** [comment]
Hey there, I'd like to help with this! @konopkja @pettinarip

**Comment by pettinarip** [comment]
Assigned @marcellamalune thanks again!

**Comment by corwintines** [comment]
@konopkja I think we can close this now

**Comment by corwintines** [comment]
Go ahead and reopen if you disagree
