### ISSUE TITLE
Getting Transaction History for an Ethereum Address

### ISSUE THREAD

**Issue by 0xolishell** [ethereum/ethereum-org-website#8299]
Hi there, 

I'd like to submit the below beginner tutorial. I think it's an important thing to know and wanted to add it. In full transparency, I'm from Alchemy :) I use Ethereum.org all the time, the content is so helpful! 

https://docs.alchemy.com/docs/how-to-get-transaction-history-for-an-address-on-ethereum

Tutorial tags include: Alchemy, Ethers Js, SDK

**Comment by mail4metablocks** [comment]
Thanks @shelleyolivia for sharing this,

Can some one please assign this to me? i can add it to the {{https://ethereum.org/en/developers/docs/}}

**Comment by shelleyolivia** [comment]
Thank you @mail4metablocks, so appreciate your help!
