### ISSUE TITLE
Bug report - Wrong information in the tutorial page: Understanding the Yellow Paper's EVM Specifications 

### ISSUE THREAD

**Issue by ali-bahjati** [ethereum/ethereum-org-website#8307]
### Describe the bug

In [the section 9.1: Basics](https://ethereum.org/en/developers/tutorials/yellow-paper-evm/#91-basics) the article mentions:

> The EVM also has a separate non-volatile storage model that is maintained as part of the system state - this memory is organized into word arrays (as opposed to word-addressable byte arrays in the stack). The stack is referred to as "memory" while the non-volatile storage is referred to as "storage".

1. To the best of my knowledge it is wrong, stack vs memory vs storage are all three different things.

### To reproduce

Go to [the article](https://ethereum.org/en/developers/tutorials/yellow-paper-evm/#91-basics)

### Expected behavior

It should state that memory is a separate thing and explain it. Ideally it should also explain call-data too.

**Comment by corwintines** [comment]
Closed with above PR
