### ISSUE TITLE
Suggest a wallet: Atomic Wallet

### ISSUE THREAD

**Issue by MichaelAkkerman** [ethereum/ethereum-org-website#8309]
### Wallet name

Atomic Wallet

### Wallet description

Decentralized multi-currency wallet with built-in exchange, staking, and buy crypto options.

### Wallet logo

![atomic_wallet_logo_white_vert_2 (3) 1 (1)](https://user-images.githubusercontent.com/44265428/198365928-8b91929a-a583-479e-a94f-5794e744602a.svg)

### Background color for brand logo

#FFFFFF

### URL to the project

https://atomicwallet.io/

### When did the wallet go live to users?

2018

### Does the wallet have an active development team?

https://github.com/Atomicwallet + Releases history https://atomicwallet.io/downloads

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

https://twitter.com/atomicwallet
https://www.facebook.com/AtomicWallet/
https://www.youtube.com/channel/UCLMnUt6BBtA67eic1vRGF3g
https://www.reddit.com/r/atomicwallet/
https://t.me/AtomicWalletNews

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

https://play.google.com/store/apps/details?id=io.atomicwallet&hl=en&gl=US

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Atomic Wallet is available for Windows, macOS, Debian, Fedora, and Ubuntu https://atomicwallet.io/downloads

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No browser extension

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

No

### Who holds the private keys?

Private keys are stored only on users' devices.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

[Atomic_security_audit_final.pdf](https://github.com/ethereum/ethereum-org-website/files/9832309/Atomic_security_audit_final.pdf)

### Has the wallet's smart contract code or security modules been audited?

Please check the link above

### Scam protection?

We're monitoring copycats daily and warning every user of Atomic wallet about security basics.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No, we use our own ETH nodes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes, we support WalletConnect

### Does the wallet support staking directly?

https://support.atomicwallet.io/article/140-staking-options-in-atomic-wallet

### Does the wallet support swaps directly?

https://support.atomicwallet.io/article/90-the-process-of-exchange

### Does the wallet support multi-chain networks?

No

### Does the wallet support Ethereum layer 2 networks?

No

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

We support Unstoppable Domains

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

https://support.atomicwallet.io/article/42-how-to-add-a-custom-erc20-eth-token

### Does the wallet support EIP-1559 (type 2) transactions?

No

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, Buy crypto with credit/debit card is available through 3rd-party (Simplex)

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No, only 12-words mnemonic

### Who can the ethereum.org team can contact regarding the wallet in future?

mick@atomicwallet.io
Telegram: michael_akkerman

### Does the wallet have a dedicated support team?

https://atomicwallet.io/support

### What educational resources/documentation do you provide to users?

We have a knowledge base at https://support.atomicwallet.io/
And Academy https://atomicwallet.io/academy

**Comment by corwintines** [comment]
@MichaelAkkerman do you have any documentation anywhere on this wallet? I can't find anything easily on the website.

**Comment by MichaelAkkerman** [comment]
@corwintines Most of the processes and features are explained [here](https://support.atomicwallet.io/)
If anything specific is needed besides that, kindly let me know.

**Comment by corwintines** [comment]
Hey @MichaelAkkerman. Were the security issues in the audit addressed? I know this is closed source, so not sure how to verify this.

**Comment by MichaelAkkerman** [comment]
Hey @corwintines , please check a clarification on Security issues:

>A user’s password should meet the minimum security requirements.
Users can set any password for the wallet. It’s not a critical vulnerability - all data that requires a password is located only on the user’s device. We plan to add a password complexity indicator within a month.

> No authentication attempts limit.
That will only confuse the user. If a scammer has an access to the device, the limit will not stop him.

> No verification of certificate host.
This is not a critical issue since we never share private keys, passwords, or mnemonics over the network. At the moment this feature is not needed and will be disabled in the wallet’ next versions.

> Mobile application execution on Jailbroken and Root devices
We would add it along with the password indicator.
