### ISSUE TITLE
Create an Introduction to EIPs page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#831]
**Is your feature request related to a problem? Please describe.**

Recently we made updates to the site footer (#782), which added a link to eips.ethereum.org.

We believe it's helpful to make EIPs more discoverable but for folks new to Ethereum, this could be a confusing landscape to navigate. We realized there's not much content out there that provides a beginner-level introduction to EIPs - what they are, how the process works, how to follow along / get involved, etc. Perhaps we should include examples (like ERC token standards) that help demonstrate how EIPs improve Ethereum & help establish standards across the community.

**Describe the solution you'd like**

Let's create a new page (e.g. ethereum.org/eips) that explains EIPs at a high level & links out to resources (e.g. [EIP 1](https://eips.ethereum.org/EIPS/eip-1)) for users to that want to dig deeper. Ideally this also helps demonstrate the vibrancy of the Ethereum ecosystem, which could build credibility & motivate newcomers to get involved with the community.

In terms of approach, we recommend for anyone who wants to tackle this to either 1) submit a PR with the new page or 2) share a draft document on this issue where community members can add comments & suggest edits.

**Describe alternatives you've considered**

Wait for someone from the community to build this page

**Additional context**

Some community resources I found that could serve as inspiration (though I don't believe these are perfect solutions - some are too in-depth, some too sparse):
- https://eips.ethereum.org/
- https://coinrivet.com/how-ethereum-improvement-proposals-eips-work/
- https://docs.ethhub.io/built-on-ethereum/erc-token-standards/what-are-erc-tokens/

**Comment by samajammin** [comment]
@anettrolikova mentioned interest in helping out with this 😄

**Comment by anettrolikova** [comment]
Introduction [doc](https://docs.google.com/document/d/1__W80NNbfggTeyUqZwrtzV4rsbnT8UxL94udphlawng/editrl)
feel free to add feedback :)
Thanks @timbeiko and @samajammin for contributions to the doc :)

**Comment by samajammin** [comment]
@all-contributors please add @anettrolikova @timbeiko @edsonayllon @poojaranjan for content

**Comment by samajammin** [comment]
@all-contributors please add @timbeiko for content

**Comment by samajammin** [comment]
@all-contributors please add @edsonayllon for content

**Comment by samajammin** [comment]
@all-contributors please add @poojaranjan for content
