### ISSUE TITLE
Advanced / Networking Layer Suggests nodes use discv5

### ISSUE THREAD

**Issue by ryandotsmith** [ethereum/ethereum-org-website#8310]
### Describe the bug

Firstly, I'm not sure this is the right category to report this issues. It has to do with content not the technical implementation. Happy to post this elsewhere.

The docs [here](https://ethereum.org/en/developers/docs/networking-layer/#execution-discovery) indicate that discv5 is used to discover nodes on the ethereum network. However, nodes such as geth don't use discv5 as of today. They use discv4 while exploratory development happens on discv5.

I would like to suggest that we update this section of the docs to explicitly indicate that discv4 is used today and that discv5 is being developed and may be used in the future.

### To reproduce

1. Click https://ethereum.org/en/developers/docs/networking-layer/#execution-discovery

### Expected behavior

I expect to see that discv4 is currently being used

**Comment by ryandotsmith** [comment]
I'd be happy to make these changes if / when we get to the bottom of this issue.

**Comment by jmcook1186** [comment]
yes, you are right - the execution clients still use discv4 by default - but discv5 can be toggled on via CLI. 
Thanks for poiting this out - please lmk if you want to raise a PR, otherwise I can fix.

**Comment by ryandotsmith** [comment]
> please lmk if you want to raise a PR, otherwise I can fix.

Thanks for the quick reply! I will open a PR.

**Comment by ryandotsmith** [comment]
@jmcook1186 PR opened!

**Comment by corwintines** [comment]
Hey @ryandotsmith, thanks for opening this. 

Just wanted to let you know I edited the description links from https://ethereum.org/en/developers/docs/networking-layer/#consensus-discovery to https://ethereum.org/en/developers/docs/networking-layer/#execution-discovery based on your PR.

**Comment by ryandotsmith** [comment]
@corwintines brilliant!
