### ISSUE TITLE
Table out of size

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#8320]
### Describe the bug

The table on this page is way out of the grid

https://ethereum.org/en/developers/docs/evm/opcodes/

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/evm/opcodes/
2. See the page content

### Expected behavior

The table should be within the page grid with overflow scroll

### Screenshots

![Screen Shot 2022-10-21 03 01 09 PM](https://user-images.githubusercontent.com/1120748/197221314-14c7c232-c763-4908-a361-2fc89f3365de.png)

### Desktop (please complete the following information)

Mac OS

**Comment by samajammin** [comment]
Yikes! Thanks for pointing out.

Think this is a result of the Chakra migration (#6374) @pettinarip? I see the markdown table was migrated in #8061 by @ImMiguelP.

**Comment by samajammin** [comment]
@nloureiro can you fix the image in the description? Looks like it never uploaded.

**Comment by pettinarip** [comment]
Yea, seems to be a regression form the Chakra migration PR.

**Comment by Aksa12** [comment]
Hey, I would like to work on this issue

**Comment by nloureiro** [comment]
> Hey, I would like to work on this issue

I assigned it to you. Go for it!
