### ISSUE TITLE
Incorrect href in Korean

### ISSUE THREAD

**Issue by dbadoy** [ethereum/ethereum-org-website#8321]
### Describe the bug

Incorrect href

### To reproduce

 1. Select korean
 2. Move any tab (example - https://ethereum.org/ko/community/events/)
<img width="745" alt="스크린샷 2022-10-21 오후 11 49 15" src="https://user-images.githubusercontent.com/72970043/197224535-2d71f330-ee19-4c85-8657-f0b18d20ff71.png"> 
 3. Click below button. (I don't know what to call this)
<img width="203" alt="스크린샷 2022-10-22 오전 12 00 23" src="https://user-images.githubusercontent.com/72970043/197227025-92650c8d-7489-4bc2-8317-467a72b8d767.png">

### Expected behavior

as-is : `/ko/en/*`
to-be: `/ko/*`

### Screenshots

<img width="1391" alt="스크린샷 2022-10-21 오후 11 42 29" src="https://user-images.githubusercontent.com/72970043/197223097-abc94c63-46f5-4aec-b5da-82f6b361030c.png">

### Desktop (please complete the following information)

mac OS, Chrome

**Comment by ritanshoo** [comment]
Hello @dbadoy , Thanks for pointing the issue,
I would love to work on it, can you please assign it to me

**Comment by dbadoy** [comment]
Thanks for respond, @ritanshoo!
I couldn't set the assign. Maybe the permissions are set.
IMO if you want, you can leave a comment that you will work on it, and then tag the issue to PR when you are done.

**Comment by dbadoy** [comment]
Ping?
