### ISSUE TITLE
Fix Gatsby i18n issue

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#8344]
_This is part of our [Change i18n plugin epic](https://github.com/ethereum/ethereum-org-website/issues/8345)._

### Describe the bug

There are currently some issues with the internationalization library that is being used. 

1 - High memory usage during build time
2 - A large app.js bundle is being created, making the user experience suffer when this is downloaded

After some initial fixes for code splitting which was contributing to the large app.js bundle, it was uncovered that more needs to be done to fix this.

Currently this is an analysis of these bundles:
![Untitled](https://user-images.githubusercontent.com/15589226/197610199-d346f47d-69f1-4fa7-b517-e27b4fe69032.png)

Ideally, we can split out translation bundles:
![Untitled (1)](https://user-images.githubusercontent.com/15589226/197610364-453ed1fe-a730-41c2-9763-08eda59d20e8.png)

### To reproduce

Build the app and analyze the bundles

### Expected behavior

![Untitled (1)](https://user-images.githubusercontent.com/15589226/197610430-88d9501a-df57-44ca-b27c-11d710a435be.png)

Get to a point where languages are being broken out into their own bundles, and we no longer have them in one app.js bundle.

**Comment by pettinarip** [comment]
Bundles after changing the lib:
![image](https://user-images.githubusercontent.com/468158/204316548-23c9982d-94fa-4090-bfad-385fa832c0ad.png)

Closing.
