### ISSUE TITLE
Extra padding on the right in the docs pages

### ISSUE THREAD

**Issue by amit-ksh** [ethereum/ethereum-org-website#8373]
### Describe the bug

There is some extra padding on the right side of the page when the screen width is close to `1025px`.

### To reproduce

1. Go to any docs page like https://ethereum.org/en/developers/docs/dapps/
2. Open the dev tool and change the screen width near to `1025px`  just before the `l` breakpoint.
3. Slide the right side of the page to see the extra padding.

### Expected behavior

Should not have extra padding on the right side.

### Screenshots

https://user-images.githubusercontent.com/91947037/197945208-a372e5bc-c9a0-4a08-ac4c-70bb5172e793.mp4

![image](https://user-images.githubusercontent.com/91947037/197946406-65e03210-dbc9-405e-bab6-c4a2f71a2dba.png)

### Desktop (please complete the following information)

OS: Windows 10
Browser: Brave

**Comment by TylerAPfledderer** [comment]
Hmmm might be related to #8364

**Comment by TylerAPfledderer** [comment]
Not stale

**Comment by nloureiro** [comment]
@TylerAPfledderer @pettinarip 

is this the same bug with the table on dev docs? like this [issue](https://github.com/ethereum/ethereum-org-website/issues/12119)

example of the bug
[https://ethereum.org/developers/docs/evm/opcodes](https://ethereum.org/developers/docs/evm/opcodes)

**Comment by nloureiro** [comment]
@TylerAPfledderer @pettinarip

is this the same bug with the table on dev docs? like this https://github.com/ethereum/ethereum-org-website/issues/12119

Should we close this issue?

example of the bug
https://ethereum.org/developers/docs/evm/opcodes

**Comment by pettinarip** [comment]
> @TylerAPfledderer @pettinarip
> 
> is this the same bug with the table on dev docs? like this #12119
> 
> Should we close this issue?
> 
> example of the bug https://ethereum.org/developers/docs/evm/opcodes

No, this is a different issue. I see this in most of the docs pages, i.e. https://dev--ethereumorg.netlify.app/developers/docs/transactions

FYI atm prod doesn't have the fix you mentioned bc has been reverted. However, you can test it in the [dev env](https://dev--ethereumorg.netlify.app).

**Comment by TylerAPfledderer** [comment]
@pettinarip there is a mention of PR #8415

**Comment by corwintines** [comment]
This should have been resolved in https://github.com/ethereum/ethereum-org-website/pull/12460 so going to close this issue out. I think we still have an issue with consistent width of the right TOC, but that is a separate issue to this. Going to close this out, thanks @amit-ksh!
