### ISSUE TITLE
UI Bug report: deposit contract page (missing padding)

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#8391]
### Describe the bug

- missing padding for the button "copy address" + "reveal address" and info text bellow

### To reproduce

1. go to https://ethereum.org/en/staking/deposit-contract/
2. look at the button "reveal address"

### Expected behavior

- add padding to the button

### Screenshots

<img width="550" alt="Screenshot 2022-10-28 at 13 02 31" src="https://user-images.githubusercontent.com/100724231/198539655-6a9c5eb7-b220-4da8-bf9b-e007a8374cc5.png">

**Comment by minimalsm** [comment]
Closed by #8396
