### ISSUE TITLE
Fix typo on The Merge page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#8392]
### Describe the bug

There is a typo in the following sentence: _with all it's accounts, balances, smart contracts, and blockchain state_
'it's' means 'it is', and is incorrect in this context

### To reproduce

1. Go to https://ethereum.org/en/upgrades/merge/#what-is-the-merge
2. Scroll down past the infographic
3. Read the 1st sentence

### Expected behavior

'it's' should be changed to 'its'

### Screenshots

<img width="920" alt="Screenshot 2022-10-28 at 13 22 12" src="https://user-images.githubusercontent.com/37338979/198576498-db8a6ef0-2f20-45f6-852c-0096a772c8fe.png">

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by minimalsm** [comment]
Closed by #8404
