### ISSUE TITLE
Fix inconsistent spelling of YouTube

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#8393]
### Describe the bug

The spelling of YouTube is inconsistent, as there are two instances of 'Youtube' on the website
- The Ethereum energy consumption page
- The Client diversity page

### To reproduce

1. Go to https://ethereum.org/en/energy-consumption/
2. Search for 'compared to youtube'
3. See error

1. Go to https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/#further-reading
2. Read the second to last item
3. See error

### Expected behavior

The consistent spelling throughout the site should be 'YouTube'

### Screenshots

<img width="779" alt="Screenshot 2022-10-28 at 13 34 11" src="https://user-images.githubusercontent.com/37338979/198578308-2110837a-b5cb-49ce-8f5e-7cd8ddc31c85.png">
<img width="659" alt="Screenshot 2022-10-28 at 13 34 28" src="https://user-images.githubusercontent.com/37338979/198578313-f663e410-1858-469b-af57-f3c01400cc3b.png">

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by minimalsm** [comment]
Closed by #8396
