### ISSUE TITLE
Unresponsive Table

### ISSUE THREAD

**Issue by SavPhill** [ethereum/ethereum-org-website#8407]
### Describe the bug

On page https://ethereum.org/en/nft/ The comparison table under the heading ‘A comparison’ is not symmetrical on all device types. 

See screenshot below taken from a mobile device:
![10F2CDC4-A4AB-412D-98A3-B20D3056CBD9](https://user-images.githubusercontent.com/38789408/198820682-7cf9b814-8515-45a0-8ea1-779fc79daf36.jpeg)

### To reproduce

1. Go to 'https://ethereum.org/en/nft/'
2. Scroll down to 'A comparison'
4. See alignment issues.

### Expected behavior

I believe we can easily adjust this table to be more aligned for all device types.

**Comment by tinniaru3005** [comment]
I would like to work on this. Can you please assign it to me?
