### ISSUE TITLE
General ether issuance page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#8444]
### Is your feature request related to a problem? Please describe.

Currently there is a page titled [How The Merge impacted ETH supply](https://ethereum.org/en/upgrades/merge/issuance/) which was originally created to focus on the changes taking place with the issuance of ether via the transition to proof-of-stake via The Merge. With a successful Merge behind us, this page has been updated with post-merge figured, but is still primarily focused on how ether issuance changed as a result of this network upgrade.

### Describe the solution you'd like

A new generalized page on the issuance of ether. This page would likely live at `/eth/issuance` instead of nested within the upgrade section of the site, and should more broadly educate on how ETH is issued for people who are newer to the ecosystem, without complicating the topic with comparisons to proof-of-work days. 

The existing page will not last forever as the pages related to network upgrades continue to evolve and progress, leaving the need for a long term resource that clearly lays out the factors that influence ether supply.

Content from the existing page could be rolled forward and updated to remove unnecessary copy, along with work that has already been prepped and tabled in PR #7921.

### Describe alternatives you've considered

- Leave the existing page `/upgrades/merge/issuance` as the primary resource to direct people to regarding ether supply. 
- Link to external resources for this information

Would prefer neither of these myself.

**Comment by corwintines** [comment]
Would still like to see this done, would be a good living resource for the site.

**Comment by wackerow** [comment]
Re-surfacing in new issue, #12664... closing in lieu of
