### ISSUE TITLE
Add project to desci/#get-involved

### ISSUE THREAD

**Issue by os-dlake** [ethereum/ethereum-org-website#8447]
### Is your feature request related to a problem? Please describe.

Hey! I'm Oliver, a Lead Developer at Data Lake.

I propose an addition to the https://ethereum.org/en/desci specifically in "Get Involved" for [data-lake.co]. 
Data Lake is building a Global Medical Data Donation System and serves the purpose of data access layer for both Decentralized and Centralized Science Projects.

We believe that Data Lake has built enough traction and proven its model to be featured on the DeSci Page of Ethereum Website, also, since Data Lake is building on Ethereum. 

### Describe the solution you'd like

Add Data Lake (https://data-lake.co) onto the DeSci page on Get Involved section.

### Describe alternatives you've considered

N/A

### Additional context

Since Data Lake is a swiftly arising project in the DeSci space, I'm attaching some links in order to add context to what Data Lake does and what traction it has already gotten, furthermore why it should be listed amongst important DeSci projects on the Ethereum Website.

Website: https://data-lake.co/
Data Lake in BeInCrypto: https://beincrypto.com/blockchain-may-be-poised-to-help-revolutionize-medical-science/
Sept Project Update: https://datalaketoken.medium.com/project-update-7-september-2022-df68627114b2
Sillicon Republic (Startup of the Week): https://www.siliconrepublic.com/start-ups/data-lake-medical-data-system-privacy-healthcare

**Comment by corwintines** [comment]
See comment in PR
