### ISSUE TITLE
Quiz: Web3 allows users to own digital assets directly through:

### ISSUE THREAD

**Issue by ligi** [ethereum/ethereum-org-website#8460]
ENS is also a NFT - so B and C are correct. But also these are not the only types of digital assets. I would completely remove this question.

![image](https://user-images.githubusercontent.com/111600/199573578-52bb2cbb-8235-45e3-a6c6-b772cc72cc92.png)

**Comment by wackerow** [comment]
Agree... I think this adds confusion without really providing a clear teaching point. Will assign myself to remove.
