### ISSUE TITLE
Quiz Bug report: You can have a single, censorship-resistant login across all of the web through the use of

### ISSUE THREAD

**Issue by mds1** [ethereum/ethereum-org-website#8465]
### Describe the bug

It expects the wrong answer as shown in the images below

<img width="661" alt="image" src="https://user-images.githubusercontent.com/17163988/199625634-2ac32fb1-fd95-4156-a2a2-3b46468cba37.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/17163988/199625649-2f4cda16-0a08-4da5-868e-aefcb4d89d64.png">

### To reproduce

See above

### Expected behavior

See above

**Comment by corwintines** [comment]
Thanks, @mds1!

This got fixed in: https://github.com/ethereum/ethereum-org-website/pull/8453

Will be fixed in next deploy
