### ISSUE TITLE
adding a resource

### ISSUE THREAD

**Issue by valerierosario** [ethereum/ethereum-org-website#8466]
I saw your links pages related to Cryptocurrency/ Binance. It is found here -http://ethereum.org/en/nft/

Do you mind adding a Binance article as part of your resource link - (https://www.binance.com/en/blog/fiat/how-to-invest-in-nfts-421499824684903763?utm_source=Spiralytics&utm_medium=Binance+Blog&utm_campaign=Blog5

**Comment by minimalsm** [comment]
Hey @valerierosario, thanks for the suggestion. 

I'd personally not like to include any links that are speculative (how to invest, how to make money from selling 'x', how to defi degen, etc).

**Comment by corwintines** [comment]
I also dont think this is an appropriate link for the NFT page, but appreciate the suggestion @valerierosario

**Comment by corwintines** [comment]
Following up on this, going to close the issue. I dont think a link giving investment advice like this is appropriate for the NFT page. 

Thank you for the suggestion, @valerierosario! If you have any others please do open more issues in the future :)
