### ISSUE TITLE
Testnets page directs dapp developers to use Goerli

### ISSUE THREAD

**Issue by dcposch** [ethereum/ethereum-org-website#8467]
### Describe the bug

This page makes it sound like Goerli is the right testnet for testing dapps, while Sepolia is going away soon: https://ethereum.org/en/developers/docs/networks/#ethereum-testnets

Apparently Sepolia is actually preferred?  https://twitter.com/lightclients/status/1587914219214999552

### To reproduce

1. Go go https://ethereum.org/en/developers/docs/networks/#ethereum-testnets

### Expected behavior

See summary

**Comment by corwintines** [comment]
Thanks, @dcposch! Opened something up to be reflect information in this blog post: https://blog.ethereum.org/2022/06/21/testnet-deprecation.

**Comment by corwintines** [comment]
Closed in https://github.com/ethereum/ethereum-org-website/pull/8481
