### ISSUE TITLE
ETH Logo asset is inlined (base64 encoded) and a duplicate

### ISSUE THREAD

**Issue by carlfairclough** [ethereum/ethereum-org-website#847]
**Describe the bug**
https://ethereum.org/assets/#eth-logo is inlined in the HTML, and so the links are broken.
https://ethereum.org/assets/#black-on-transparent-background is the same image, and is working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://ethereum.org/assets/#eth-logo
2. Click on the image or link

**Expected behavior**
The link should be to a file

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version:  80.0.3987.132

**Comment by samajammin** [comment]
Nice catch, thanks for reporting!

**Comment by samajammin** [comment]
@all-contributors please add @carlfairclough for bug reports
