### ISSUE TITLE
Change "Ethereum meetups" flag position [design proposal]

### ISSUE THREAD

**Issue by hursittarcan** [ethereum/ethereum-org-website#8479]
## Descirption 
* The flags in the "Ethereum meetups" list are displayed a little above the text (I don't know if this is a bug or if this is supposed to be like this). 
* I think it would look better if we would lower the position of the flag, to match the position of the text. (see screenshots, before & after). 

### To reproduce

1. Go to https://ethereum.org/en/community/events/
2. Scroll down to 'Ethereum meetups'
4. See 'bug'

### Expected behavior

/

### Screenshots

![image](https://user-images.githubusercontent.com/75273616/199761106-70b2d12d-2f26-410e-99f0-042b9c933282.png)
![image](https://user-images.githubusercontent.com/75273616/199761307-843b2c9a-6e53-42b6-bdb4-01cbfa1311c5.png)

**Comment by jmcook1186** [comment]
also see #8478 for broken flags
