### ISSUE TITLE
Sepolia long-term Support unclear

### ISSUE THREAD

**Issue by Michael-A-Heuer** [ethereum/ethereum-org-website#8495]
In the [networks section about sepolia](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/networks/index.md#sepolia-sepolia) the docs state that 
> Although Sepolia is still running, it is not currently planned to be maintained long-term.

This seems to contradict the announcement https://blog.ethereum.org/2022/06/21/testnet-deprecation 
> Two testnets, Goerli and Sepolia, will be maintained going forward. Goerli is recommended for stakers to test protocol upgrades and developers who want to interact with a large existing state. Sepolia is recommended for users and developers who want a lighter weight chain to sync to and interact with.

and discussion https://ethereum-magicians.org/t/og-council-post-merge-testnets/9034
> only Goerli and Sepolia will be supported long-term after the merge

On Twitter, client devs from [geth](
https://twitter.com/lightclients/status/1587914219214999552) and [prysm](
https://twitter.com/terencechain/status/1588191530589704193?s=20&t=V46N7Fw7-xAmUiu1CiAybw) started suggesting using sepolia. 

Can you clarify this issue?

**Comment by jmcook1186** [comment]
Hello - yes that text was out of date - it got updated yesterday in this PR #8481.
Sepolia is supported long term and is the preferred testnet for dapp developers.

**Comment by q9f** [comment]
We should incorporate the release and lifecycle schedule maybe? I don't know who said that Sepolia will not be maintained long term. The opposite is true. Sepolia is currently the best bet long term

* https://youtu.be/1UtcvVve32A?t=708
* https://ethereum-magicians.org/t/proposal-predictable-ethereum-testnet-lifecycle/11575/5
