### ISSUE TITLE
Update Spinner colors to be consistent

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#8516]
[In this PR](https://github.com/ethereum/ethereum-org-website/pull/8483/files#r1013781740), I noted we should change the spinner colour implemented on the staking page. For this to happen, we must:

1. Decide colour
2. Implement colour consistently across spinners

**Comment by wackerow** [comment]
@nloureiro Do we have plans to standardize our loading indicators? Going to assign you here, but feel free to close out if this is being tracked separately in the DS rollout.

**Comment by nloureiro** [comment]
> @nloureiro Do we have plans to standardize our loading indicators? Going to assign you here, but feel free to close out if this is being tracked separately in the DS rollout.

Thank you for mentioning it. I self assign it and will take it from here

**Comment by nloureiro** [comment]
I closed this issue for now. 
The spinners will be worked on the design system level and then will open an new issue to be implemented
