### ISSUE TITLE
Request to add MetaMask Grants DAO to Ethereum grants list 

### ISSUE THREAD

**Issue by ritave** [ethereum/ethereum-org-website#8522]
MetaMask has recently opened a grants programme with a yearly $2.4M budget.

On behalf of MetaMask, I'm requesting it to be added to the [Ethereum grants](https://ethereum.org/en/community/grants/) list.

* [Link to the grants programme that we request to add](https://metamaskgrants.org/)
* [Official announcement](https://consensys.net/blog/press-release/consensys-launches-metamask-grants-dao/)

Additionally Consensys Grants is finished and inactive. I also request it to be removed from the website

**Comment by minimalsm** [comment]
Hey @ritave, thanks for raising this 💪 

Agree we should add this to the grants page. I'd encourage you to open a PR if you'd like to move this along quickly. If not, I've added a few tags that should get some community attention on this issue ☺️

Thanks again

**Comment by samajammin** [comment]
I assume this would make the most sense under "project specific" grants?
https://ethereum.org/en/community/grants/#project-specific

@ritave let us know if you disagree.

**Comment by ritave** [comment]
@samajammin 
I think that's reasonable.

For some context:

While MetaMask grants have a requirement to have some positive impact on MetaMask, we're also sponsoring broad public good type projects as well.

The first [approved proposal](https://metamaskgrants.org/Agoric-f6febc801a5142069e175bb177ba0ea3) concerns building [Secure EcmaScript sandboxes](https://github.com/endojs/endo/tree/master/packages/ses), with more in the pipeline.
