### ISSUE TITLE
Add dapp explanation on /dapps page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#853]
**Is your feature request related to a problem? Please describe.**

We've gotten feedback from users that it'd be valuable to add a brief explanation on the "what" & "why" of the /dapps page. Currently we just list some example dapps to use.

**Describe the solution you'd like**

Add a brief intro paragraph explaining what dapps are & how they're different.

**Describe alternatives you've considered**

**Additional context**

**Comment by VoltronDeveloper1** [comment]
You all are so far away from the true power its unbelievable. Its elementary my dear Watson

**Comment by samajammin** [comment]
Solved in #854
