### ISSUE TITLE
Rethink "Roadmap" section of About page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#8532]
### Is your feature request related to a problem? Please describe.

We currently have a "Roadmap" section of About page:
https://ethereum.org/en/about/#roadmap

It outlines a process of how we approach work on the website:

> We organize our tasks in 3 categories:
> - in progress
> - planned
> - implemented

Then it pulls in various GH issues (via GH API) with the associated labels:
- planned: `Status: Up Next`
- in progress `Status: In Progress`

Then for "implemented" I believe it just pulls in PRs that have been merged.

Overall this is ok but I don't think it accurately reflects our roadmap. e.g. I don't think the `Status: Up Next` or `Status: In Progress` issue labels are frequently used.

### Describe the solution you'd like

It might be easier & clearer to just:
1. explain we set our product roadmap on a quarterly basis
2. link to the most recent product roadmap GH issue (currently #8399), which gives a clear outline of what our priorities are & we're working on
3. Delete the various `Status` labels from GH

### Describe alternatives you've considered

- remove the "Roadmap" section from the page entirely
- start using status GH labels on issues/PRs with more discipline

**Comment by samajammin** [comment]
@minimalsm seems like a good candidate for you to knock out fairly easily?

Looks like the current section is now broken:
![Image 2023-01-12 at 11 02 48 AM](https://user-images.githubusercontent.com/8097623/212157811-ce826a17-8095-4446-a949-53965f47022f.jpg)

So perhaps a good reason to prioritize this update.

**Comment by nhsz** [comment]
Related issue: https://github.com/ethereum/ethereum-org-website/issues/9158
