### ISSUE TITLE
Add Design System info to About page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#8533]
### Is your feature request related to a problem? Please describe.

Currently we list information about our "design principles" on this page:
https://ethereum.org/en/about/#design-principles

But there's no mention of the design system that's in progress (#6284).

### Describe the solution you'd like

Now that the design system (#6284) is in progress & we have [Figma files we can reference](https://github.com/ethereum/ethereum-org-website/issues/8533#issue-1440449502), I suspect it may be worth publicly linking to this information from the website.

We could:
1. Update the "design principles" to "design"
2. Include information on both the "design principles" & "design system" within this section

### Describe alternatives you've considered

We could instead (or additionally) reference this information within the Contributing section of the website:
https://ethereum.org/en/contributing/

**Comment by wackerow** [comment]
@nloureiro Pulling this back for now and assigning you... I think a few updates in this section could be helpful. Let me know if you disagree, or if you'd like a hand updating some of the copy here.

**Comment by nloureiro** [comment]
It was added this section to the about page, I think it covers this requests
[https://ethereum.org/en/about#design-system](https://ethereum.org/en/about#design-system)
