### ISSUE TITLE
Add new product to Digital collectibles list. NFT collectors social network

### ISSUE THREAD

**Issue by goncharov-vlad** [ethereum/ethereum-org-website#8538]
I wanna add my project to the list. 
This is it https://indigos.app

This platform ensures that you won't be alone as a web3 user. It also can be used as an effective marketing tool for advertising NFTs, because of its blockchain community you interact with directly

You can read more about it on https://indigos.app/about page

**Comment by corwintines** [comment]
Looking into this, there are no users and this app is pretty low quality. Going to close this out.

**Comment by goncharov-vlad** [comment]
> Looking into this, there are no users and this app is pretty low quality. Going to close this out.

Hello! Why do you think so? You aren't right, but in any way thank you for the feedback!
