### ISSUE TITLE
Incorrect styles on `Pill` component

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8550]
### Describe the bug

Do to recent the recent Chakra migration on the `Pill` component #8501 the styles on light mode are not the correct ones. Check the screenshots below.

### To reproduce

1. Go to https://ethereumorgwebsitedev01.gtsb.io/en/layer-2/
2. Scroll down to the "Application specific layer 2s" section
3. See the incorrect styles

### Expected behavior

We should apply the correct styles on the `Pill` component when using light mode. Check the screenshot.

### Screenshots

Wrong styles (in `dev`):
![image](https://user-images.githubusercontent.com/468158/200933145-56dfc1b7-ddbe-400d-941a-ca7c22d4324f.png)

Correct ones (in prod):
![image](https://user-images.githubusercontent.com/468158/200933626-54bf9bd7-457b-4837-9173-75691ad12c41.png)

**Comment by corwintines** [comment]
Closing as above PR has been merged
