### ISSUE TITLE
Replace `Pill` component with the Chakra `Badge` component

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8551]
### Is your feature request related to a problem? Please describe.

Currently we are using [a custom component (`Pill`)](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Pill.tsx) to display a badge like component.

Since we are migrating over using Chakra components, we need to replace this custom component with the Chakra one.

### Describe the solution you'd like

`Badge` component https://chakra-ui.com/docs/components/badge/usage

1. Identify all the different variants we have across the site
2. Create custom theme for the `Badge` component under https://github.com/ethereum/ethereum-org-website/tree/dev/src/%40chakra-ui/gatsby-plugin/components
3. Remove the custom `Pill` component
4. Replace all the uses of `Pill` with the `Badge` component

### Describe alternatives you've considered

None.

**Comment by pettinarip** [comment]
Nice @TylerAPfledderer assigning it to you. Please take into account this bug that is related #8550 to this (in order to implement the correct color scheme in the badge theming).

**Comment by TylerAPfledderer** [comment]
@pettinarip, correct. You got it! 👍

**Comment by TylerAPfledderer** [comment]
@pettinarip I notice that there are two styled pill components that do not use the `Pill` component, but are created in the [ProductCard component](https://github.com/ethereum/ethereum-org-website/blob/94dfbce15a319e11a7ecce20bc645b6573695ea9/src/components/ProductCard.tsx#L74-L111) and the [StakingProductsCardGrid component](https://github.com/ethereum/ethereum-org-website/blob/94dfbce15a319e11a7ecce20bc645b6573695ea9/src/components/Staking/StakingProductsCardGrid.tsx#L103-L122). 

Should I look to replace those or update them as well, even though the components they reside in have not been migrated yet?

**Comment by pettinarip** [comment]
Good catch @TylerAPfledderer.

If its possible yes, I would replace them since there is not going to be any conflict in using a Chakra component inside those components.

**Comment by TylerAPfledderer** [comment]
@pettinarip this will impact `TutorialTags`, which is incomplete under the first wave migration (#6374) and currently assigned. Can either...
- Complete most of this issue and wait until the component has been migrated, or...
- Finish this issue with a PR that is merged and does not include this component, and create another PR after merge. This will require leaving the `Pill` component in the project for now.

**Comment by pettinarip** [comment]
Got it @TylerAPfledderer. I'm assigning `TutorialTags` to you since there is not much migration to do there apart from the `Pill` component & the assignee hasn't shown any activity yet.

**Comment by TylerAPfledderer** [comment]
@pettinarip understood. Thank you!

**Comment by TylerAPfledderer** [comment]
@pettinarip Created a PR #8774 for this component.
