### ISSUE TITLE
Bug report: outdated link to non-existing wallet filter

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#8558]
### Describe the bug

This filter is no longer existing after find wallet revamp.

### To reproduce

1. Go to https://ethereum.org/en/security/#spend-limits
2. Click on [Explore wallets with limits protection](https://ethereum.org/en/wallets/find-wallet/?filters=has_limits_protection)

### Expected behavior

 remove the link 

### Screenshots

<img width="908" alt="Screenshot 2022-11-10 at 15 50 59" src="https://user-images.githubusercontent.com/100724231/201072022-9798570c-204b-455e-b9fb-7cf22e809c8f.png">

**Comment by yash251** [comment]
could you please assign me this issue?

**Comment by yash251** [comment]
also I don't understand, I can see a wallet filter

**Comment by konopkja** [comment]
> also I don't understand, I can see a wallet filter

what do you mean?

**Comment by konopkja** [comment]
oh sorry, remove the link and the text. "Explore wallets with limits protection"
