### ISSUE TITLE
Bug report: broken link on what is a wallet page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#8559]
### Describe the bug

The link redirects to blog homepage, not specific article. Should be removed or replaced.

### To reproduce

1. Go to https://ethereum.org/en/wallets/
2. Click on "the keys to keeping your crypto safe" link

### Expected behavior

working link

### Screenshots

<img width="763" alt="Screenshot 2022-11-08 at 18 38 01" src="https://user-images.githubusercontent.com/100724231/201074705-f762ffc2-551d-4357-b7bc-6d661c5a3cbb.png">

**Comment by Saksham010** [comment]
Can I work on this issue?

**Comment by konopkja** [comment]
absolutely

**Comment by pontushenriksson** [comment]
I am able to contribute to this too if @Saksham010 needs help or doesn't finish :D
