### ISSUE TITLE
Get ETH page incorrect "last updated" date

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#8562]
### Describe the bug

I believe this page is giving the wrong date on when it was last updated.

### To reproduce

1. Go to https://ethereum.org/en/get-eth/#country-picker
2. Select a country in the dropdown
3. Scroll down below the exchange/wallet results
4. See text (screenshot below): "We collected this information manually. If you spot something wrong, let us know at website@ethereum.org. Last updated November 7, 2022"

### Expected behavior

The date should reflect the last commit date of this file:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/exchanges-by-country.csv
Which appears to have been on April 4th 2022.

Even the file where this logic is implemented:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/EthExchanges.tsx#L599
Last commit was September 6th 2022, so it's not showing that...

Not sure what file date it's currently pulling from 🤔 - perhaps this is when the entire website was last updated?

### Screenshots

![Image 2022-11-10 at 11 22 24 AM](https://user-images.githubusercontent.com/8097623/201150771-7fd30989-43f0-4938-9695-38432e59ced8.jpg)

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by jryanhaber** [comment]
I am interested in fixing bugs like this.  
Is there an existing mechanism for rewarding devs who are addressing bugs?

**Comment by armgp** [comment]
Hey, I can work on this. Can I get assigned to this issue?

**Comment by armgp** [comment]
When I built the code, Its showing the last commited time of https://github.com/ethereum/ethereum-org website/blob/dev/src/data/exchanges-by-country.csv.
![image](https://user-images.githubusercontent.com/49094298/201680080-bd98d6db-c7fa-4eb6-83c2-d9b515859554.png)

**Comment by corwintines** [comment]
We have addressed this during out NextJS migration. 

https://github.com/ethereum/ethereum-org-website/blob/ebf5f8682dadbba69f83d9c1c470a9fafe048528/src/pages/get-eth.tsx#L114

You can see on this line that we are now checking the git log for the date.

Going to close this out.
