### ISSUE TITLE
Scroll arrows show up next to 'Enterprise'

### ISSUE THREAD

**Issue by abhranildas** [ethereum/ethereum-org-website#857]
**Describe the bug**
On at least the homepage, Windows system-style scroll arrows show up next to the Enterprise link on top.

**Screenshot**
![image](https://user-images.githubusercontent.com/1142007/77238741-0837c200-6ba1-11ea-804f-7a56727d51d3.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 80

**Comment by samajammin** [comment]
Thanks for reporting this! Screenshots would be helpful to troubleshoot this if you're able to add any.

**Comment by samajammin** [comment]
@all-contributors please add @abhranildas for bug reports.

**Comment by abhranildas** [comment]
Hi guys, I added a screenshot.
