### ISSUE TITLE
Link colission in Ethereum's Rust developer page

### ISSUE THREAD

**Issue by gzanitti** [ethereum/ethereum-org-website#8577]
### Describe the bug

In the Ethereum's Rust developer page, two projects point in the same direction due to redirections: SputnikVM and evm_rs.

### To reproduce

1) Go to Ethereum's Rust developer page [here](https://ethereum.org/en/developers/docs/programming-languages/rust/)
2) Go to the section "Rust projects and tools".
3) Open both links: [SputnikVM](https://github.com/sorpaas/rust-evm) and [evm_rs](https://github.com/rust-blockchain/evm)

### Expected behavior

Only one of the links should exist, since they both point to the same project.

**Comment by vishal590** [comment]
hi team, can I work on this issue

**Comment by corwintines** [comment]
Closing as this was fixed in the above PR
