### ISSUE TITLE
Add an exchange - Moonpay.com

### ISSUE THREAD

**Issue by danierod** [ethereum/ethereum-org-website#8583]
### Exchange name

Moonpay

### Exchange description

MoonPay is a financial technology company that builds payments infrastructure for crypto. Our on-and-off-ramp suite of products provides a seamless experience for converting between fiat currencies and cryptocurrencies using all major payment methods including debit and credit card, local bank transfers, Apple Pay and Google Pay. MoonPay is active in more than 160 countries and is trusted by 250+ leading wallets, websites, and applications to accept payments and defeat fraud.

### What geographical restrictions apply to this exchange?

Anyone with a supported card can use MoonPay services except for residents in the following countries:

- Afghanistan
- Albania
- American Samoa (USA)
- Anguilla (UK)
- Bahamas
- Bangladesh
- Barbados
- Belarus
- Bolivia
- Botswana
- Burkina Faso
- Cambodia
- Cayman Islands (UK)
- China
- Congo, Democratic Republic of the
- Cote d'Ivoire
- Crimea
- Cuba
- Ecuador
- Ghana
- Guam (USA)
- Haiti
- Iceland
- Iran
- Iraq
- Jamaica
- Japan
- Kosovo
- Liberia
- Malta
- Mauritius
- Mongolia
- Morocco
- Myanmar (formerly Burma)
- Nicaragua
- North Korea
- Northern Mariana Islands (USA)
- Pakistan
- Panama
- Russia
- Senegal
- South Sudan
- Sudan
- Syria
- Trinidad and Tobago
- Uganda
- Ukraine
- US Virgin Islands (USA)
- Vanuatu
- Venezuela
- Yemen
- Zimbabwe

US states that are not supported yet:

- US Virgin Islands

### Which currencies are accepted by this exchange?

Moonpay supports the following fiat currencies:

AUD - Australian Dollar
BGN - Bulgarian Lev
BRL - Brazilian Real
CAD - Canadian Dollar
CHF - Swiss Franc
CNY - Chinese Yuan
COP - Colombia Peso
CZK - Czech Koruna
DKK - Danish Krone
DOP - Dominican Peso
EGP - Egyptian Pound
EUR - Euro
GBP - Pound Sterling
HKD - Hong Kong Dollar
HRK - Croatian Kuna
IDR - Indonesian Rupiah
ILS - Israeli New Shekel
JPY - Japanese Yen
JOD - Jordanian Dollar
KES - Kenyan Shilling
KRW - South Korean Won 
KWD - Kuwaiti Dinar
LKR - Sri Lankan Rupee
MAD - Moroccan Dirham
MXN - Mexican Peso
MYR - Malaysian Ringgit
NGN - Nigerian Naira
NOK - Norwegian Krone
NZD - New Zealand Dollar
OMR - Omani Rial
PEN - Peruvian Sol
PKR - Pakistani Rupee
PLN - Polish Złoty
RON - Romanian Leu
SEK - Swedish Krona
SGD - Singapore Dollar
THB - Thai Baht
TRY - Turkish Lira
TWD - Taiwan Dollar
USD - US Dollar
VND - Vietnamese Dong
ZAR - South African Rand

### Do you have any proof that they're a legitimate company?

Website: https://www.moonpay.com/

News:
https://www.cnbc.com/2022/06/21/crypto-start-up-moonpay-in-nft-deal-with-universal-fox.html
https://boardroom.tv/moonpay-crypto-payments-explained/

### Do you have any extra information?

All information can be found in the About us page:
https://www.moonpay.com/about-us

**Comment by Dev-Liz** [comment]
Hello @danierod where am I supposed to add this, please??. I'm interested in working on it.

**Comment by danierod** [comment]
Hello @Dev-Liz , Moonpay is to be added as an exchange

**Comment by armgp** [comment]
@danierod 
https://www.moonpay.com/legal/licenses
Here moonpay is licensed for Louisiana. Following the issue I have added Louisiana to usaExceptions. Should I remove it or keep it that way.

**Comment by armgp** [comment]
@danierod Thanks for the immediate response. I have removed it. I also think the data in exchanges-by-country.csv for moonpay is wrong. For example moonpay has support in Albania, but the csv file shows false. Should I also correct these data?

**Comment by danierod** [comment]
Hey @armgp let me double check that list again and make sure it is updated. Will give you an answer in a few minutes

**Comment by danierod** [comment]
@armgp updated the list of countries in the original issue request, but I will also add the updated list here:

- Afghanistan
- Albania
- Bahamas
- Bangladesh
- Belarus
- Barbados
- Bolivia
- Botswana
- Burkina Faso
- Cambodia
- Cayman islands
- China
- Congo
- Côte d'Ivoire
- Cuba
- Ecuador
- Ghana
- Haiti
- Iceland
- Iran
- Iraq
- Jamaica
- Japan
- Kosovo
- Korea
- Liberia
- Libya
- Malta
- Mauritius
- Mongolia
- Morocco
- Myanmar
- Nicaragua
- Pakistan
- Panama
- Philippines
- Senegal
- South Sudan
- Sudan
- Syrian arab republic
- Trinidad and tobago
- Uganda
- Vanuatu
- Venezuela
- Yemen
- Zimbabwe

**Comment by armgp** [comment]
okay thanks :)

**Comment by epicfox87** [comment]
+1 on this many of my clients use it because it covers many geos!

**Comment by danierod** [comment]
Since PR from @armgp was abandoned, I'll work on this issue.

**Comment by armgp** [comment]
sorry i am new to contributing and I accidentally reset all my commits🥲

**Comment by corwintines** [comment]
Will review this week.

**Comment by corwintines** [comment]
@danierod want to get this over the finish line. I was wondering where you got the list of supported countries. Was looking here myself, but not sure if its up to date: https://support.moonpay.com/hc/en-gb/articles/360009279877-What-are-our-non-supported-countries-states-and-territories-for-off-ramp-

**Comment by danierod** [comment]
> @danierod want to get this over the finish line. I was wondering where you got the list of supported countries. Was looking here myself, but not sure if its up to date: https://support.moonpay.com/hc/en-gb/articles/360009279877-What-are-our-non-supported-countries-states-and-territories-for-off-ramp-

Hello @corwintines, tbh not sure if I updated the list here in the issue. But in the implementation the list was validated with the Moonpay's developers.
I can make sure to update here as well, first thing tomorrow morning.

**Comment by danierod** [comment]
@corwintines updated the list of countries and states that are not accepted by Moonpay. Anything else that you need from me?

**Comment by corwintines** [comment]
This is great @danierod. Will rereview and try to get in.
