### ISSUE TITLE
Upgrade Gatsby to v5

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8586]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Upgrade Gatsby to v5 using the [official migration guide](https://v5.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/).

### Describe alternatives you've considered

None.

### Additional context

More official resources:
- https://www.gatsbyjs.com/blog/gatsby-5-upgrade-say-no-to-yolo/
- Release notes https://www.gatsbyjs.com/docs/reference/release-notes/v5.0/

**Comment by TylerAPfledderer** [comment]
FYI Chakra's Gatsby plugin in the current version might not support the upgrade. Currently checking if this has been addressed/investigated yet.

**Comment by TylerAPfledderer** [comment]
Issue with Chakra's Gatsby Plugin has been fixed, and should be released by the time this project transitions to Gatsby 5

**Comment by pettinarip** [comment]
Cool! great to hear that. Thanks for bringing that up.
