### ISSUE TITLE
Remove FTX and FTX US

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#8587]
We should remove FTX from the get-eth page as they are no longer a functional exchange, and anyone interacting with that exchange is at risk of losing their assets.

Paused withdrawals
- https://ftx.com/

Bankrupt filing
- https://twitter.com/FTX_Official/status/1591071832823959552

**Comment by minimalsm** [comment]
To clarify, we should remove FTX and FTX US, they are two different organisations, but both have filed for bankruptcy and are not accepting withdrawals or deposits (i.e. not acting as an exchange, and not helpful to users who are trying to get ETH).
