### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dgcoffman** [ethereum/ethereum-org-website#8599]
### Describe the bug

The Coinbase Wallet data on https://ethereum.org/en/wallets/find-wallet/ is incorrect.

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on "Coinbase wallet"
3. See the incorrect data

### Expected behavior

Coinbase Wallet
  - Is non-custodial
  - Supports multiple L2s including Optimism, Arbitrum, Polygon, BNB, and Fantom
  - Has native support for ENS
  - Sends 1559 transactions
  - Supports ERC-20s on mainnet and L2s
  - Allows buying crypto with fiat
  - Supports staking via the in-app browser

**Comment by armgp** [comment]
can i work on this?

**Comment by minimalsm** [comment]
Closed by #8600
