### ISSUE TITLE
Decentralized Identity documentation: Using the expression "PKI" is misleading

### ISSUE THREAD

**Issue by pdelagrave** [ethereum/ethereum-org-website#8608]
Hello,

Referring to this section in particular: https://ethereum.org/en/decentralized-identity/#public-key-infrastructure

[PKI](https://en.wikipedia.org/wiki/Public_key_infrastructure) is centralized, all the control is held by the root CAs and the organizations packaging the "trusted" CAs certs in their popular products (browsers, OSes).

While the expression "Public-Key Infrastructure" alone doesn't imply centralization or decentralization, the ubiquitous PKI type known and used traditionally is the one described on Wikipedia and is centralized. A given system (Ethereum in this case) making use of public-key cryptography doesn't make it a PKI as we know it, re-using the expression as such is misleading; PKI is not a generic expression for a system using public-key cryptography.

It seems like the documentation meant to explain [Public-key cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography) instead.

Hoping this can help, assuming I'm not all wrong, let me know :)

Thanks

**Comment by corwintines** [comment]
This makes sense, good call out @pdelagrave. Will make that update.
