### ISSUE TITLE
Add "Proof of Reserves" to exchange listing policy

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#8611]
### Is your feature request related to a problem? Please describe.

We have a listing policy to determine which exchanges we link to from the site:
https://ethereum.org/en/contributing/adding-exchanges/

We currently list them on:
https://ethereum.org/en/get-eth/

Given recent events, I think it's worth adding proof of reserves as a criteria to our listing policy in order to:
- protect users
- encourage more exchanges to adopt practices that improve transparency & ability for users to verify activity

### Describe the solution you'd like

Range of approaches we could take here... would love input from the community on this!

For instance, implementation could vary from adding it as a hard requirement for exchanges to be listed or could soft-start by elevating those who do (e.g. ranking hire, or some badge of sorts).

It could also vary on how we define "proof of reserves", e.g. 
- Assets (by listing cold storage addresses, for instance)
- Both assets & liabilities ([as defined by Nic Carter](https://niccarter.info/proof-of-reserves/))

I would lean towards the latter (given assets info doesn’t inform much without knowing liabilities) but something is better than nothing.

### Describe alternatives you've considered

Mentioned above.

### Additional context

Some discussion on this here:
https://twitter.com/samonchain/status/1591681929870737408

I think another major consideration is what responsibility we're willing to put on our shoulders. We don't have the accounting expertise or bandwidth to necessarily validate what exchanges publish as proof of reserves is legitimate. Ideally we'd have a resource that we could rely on, e.g.
- https://niccarter.info/proof-of-reserves/
- https://chain.link/proof-of-reserve

**Comment by corwintines** [comment]
While I think this is a good idea, we won't have the capacity to implement and maintain this. I can't think of a clear maintenance plan that wouldn't be time consuming. There is a need for something like this in the space, but I don't think we will have the capacity to provide up to date information on proof of reserves. If there is a resource that comes up around this I would glady link out to them here. We would be better off pushing users to wallets I think.

Going to close this out as we won't be working on this.
