### ISSUE TITLE
Migrate `DeveloperDocsLinks.tsx` to Chakra

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8633]
*This is part of our [2nd wave of migration](https://github.com/ethereum/ethereum-org-website/issues/8632) of the [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

**Things to consider**

- Use [Chakra’s List component](https://chakra-ui.com/docs/components/list/usage) instead of `<ul>`.

Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) & the [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for more information.

**Comment by metadiver** [comment]
HI @pettinarip, I'm new here, I would like to work on this one to start with. Can you assign it to me please?

**Comment by pettinarip** [comment]
Sorry for the delay on this. Assigned @metadiver thanks for the help.
