### ISSUE TITLE
Migrate Search `Input.tsx` & `index.tsx` component to Chakra

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8635]
*This is part of our [2nd wave of migration](https://github.com/ethereum/ethereum-org-website/issues/8632) of the [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

**Things to consider**

- Start migrating the `Input.tsx` since `index.tsx` depends on it
- Use [Input](https://chakra-ui.com/docs/components/input/usage) & [FormControl](https://chakra-ui.com/docs/components/form-control) from Chakra as much as possible

Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) & the [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for more information.

**Comment by adi29raj** [comment]
Hi @pettinarip , Hope this helps in assigning this issue to me.

**Comment by amit-ksh** [comment]
Hey @pettinarip! I like to work on this one.

**Comment by pettinarip** [comment]
Assigned @amit-ksh

**Comment by amit-ksh** [comment]
Hey @pettinarip! I have to migrate both `Index.tsx` and `index.tsx` to Chakra or only `Index.tsx`

**Comment by amit-ksh** [comment]
Hey @pettinarip! There is any guide for setting up the **Algolia**?

**Comment by wackerow** [comment]
@pettinarip As far as I know, none of the required variables are particularly sensitive, unless you need to use the admin/write key to actually write to the index.
```sh
GATSBY_ALGOLIA_APP_ID
GATSBY_ALGOLIA_SEARCH_KEY
GATSBY_ALGOLIA_BASE_SEARCH_INDEX_NAME
GATSBY_GITHUB_TOKEN_READ_ONLY
GATSBY_FUNCTIONS_PATH
```

These are all already exposed to the Gatsby frontend... Any reason you can think of why we couldn't just provide these (perhaps just through a DM)?

**Comment by corwintines** [comment]
Hmm, yeah these should all be read keys so I wonder if we have a way to have a dev set we can share on a case-by-case basis.

**Comment by pettinarip** [comment]
Done in #9480
