### ISSUE TITLE
Migrate `FileContributors.tsx` to Chakra

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8636]
*This is part of our [2nd wave of migration](https://github.com/ethereum/ethereum-org-website/issues/8632) of the [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

**Things to consider**

- Replace the custom Modal with the [Chakra’s Modal](https://chakra-ui.com/docs/components/modal/usage)

Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) & the [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for more information.

**Comment by armgp** [comment]
Hey can I work on this?

**Comment by pettinarip** [comment]
Assigned @armgp 👍🏼

**Comment by armgp** [comment]
Should I only replace the custom modal?.. or should i also migrate rest of the components also?

**Comment by abheektripathy** [comment]
@armgp are you still working on this? if not, would like to take it up.

**Comment by armgp** [comment]
if you are interested you can take it up😊

**Comment by abheektripathy** [comment]
@pettinarip would like to work on this.

**Comment by abheektripathy** [comment]
hi @pettinarip is this issue still open for contribution?

**Comment by pettinarip** [comment]
Oopss! sorry, missed this message. Assigning it to you @abheektripathy! thanks for the help 💪🏼

**Comment by pettinarip** [comment]
> Should I only replace the custom modal?.. or should i also migrate rest of the components also?

To answer this question. Yes, we should migrate the entire component, which means the modal that it is using internally + the other components it uses, like `Container`, `Skeletons`, etc.

Sorry for the late response.

**Comment by amit-ksh** [comment]
Hey @abheektripathy! Are you still working on this, if not I'd like to work on this one?

**Comment by abheektripathy** [comment]
Hi @amit-ksh currently working on this.

**Comment by SyedAhkam** [comment]
Hey @abheektripathy, are you still working on this? If not, I'd like to take this up.

**Comment by abheektripathy** [comment]
nope you can take it up if you want.

**Comment by SyedAhkam** [comment]
Okay! 

@pettinarip do you mind assigning the issue to me?

**Comment by pettinarip** [comment]
Done! thanks @SyedAhkam
