### ISSUE TITLE
Migrate `Roadmap.tsx` to Chakra

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8637]
*This is part of our [2nd wave of migration](https://github.com/ethereum/ethereum-org-website/issues/8632) of the [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

**Things to consider**

- Use the [Link Overlay](https://chakra-ui.com/docs/components/link-overlay/usage) to replace the `CardItem` imported component from `SharedStyledComponents`

Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) & the [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for more information.

**Comment by amit-ksh** [comment]
Hey @pettinarip! Can I work on this one?

**Comment by pettinarip** [comment]
Done @amit-ksh 🙏🏼
