### ISSUE TITLE
Migrate `SimpleTable.tsx` to Chakra

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8638]
*This is part of our [2nd wave of migration](https://github.com/ethereum/ethereum-org-website/issues/8632) of the [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

**Things to consider**

- Check if we can use the [Chakra’s Table component](https://chakra-ui.com/docs/components/table/usage) for this

Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) & the [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for more information.

**Comment by amit-ksh** [comment]
Hey @pettinarip! Can I work on this?

**Comment by pettinarip** [comment]
Thanks @amit-ksh

**Comment by amit-ksh** [comment]
Hey @pettinarip!, I was facing issues migrating the `SimpleTable.tsx` using Chakra `Table`. I was not able to make the Table row a link. Can you help me, please?? 
Here is the current code-

![tablerow](https://user-images.githubusercontent.com/91947037/204087789-6aa5ddbf-e4d6-4746-83a7-8f78e507b63d.png)
