### ISSUE TITLE
Migrate `Tabs.tsx` to Chakra

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8639]
*This is part of our [2nd wave of migration](https://github.com/ethereum/ethereum-org-website/issues/8632) of the [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

**Things to consider**

- Delete the current `Tabs.tsx` file
- Replace it with the native [Chakra Tabs component](https://chakra-ui.com/docs/components/tabs/usage)
- Probably we will need to create a new `Tabs` file under https://github.com/ethereum/ethereum-org-website/tree/dev/src/%40chakra-ui/gatsby-plugin/components to apply the current styles to it

Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) & the [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for more information.

**Comment by amit-ksh** [comment]
Hey @pettinarip! can I work on this issue?

**Comment by pettinarip** [comment]
Sure! Thanks for helping on this @amit-ksh.
