### ISSUE TITLE
XL screen layout regression

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#864]
**Describe the bug**

We've had a regression of #207. Currently the site navigation stretches the width of the screen, regardless of width.

**To Reproduce**
1. Visit ethereum.org using an XL screen (i.e. width greater than 1440px)

**Expected behavior**

See #207 for context - site content (including the nav & footer) should not exceed a width of `$contentWidthXL` (1440px), no matter how wide the user's screen is. We should have a container that restricts this width.

**Screenshots**

![Image 2020-03-21 at 2 48 26 PM](https://user-images.githubusercontent.com/8097623/77237246-a74dc100-6b83-11ea-9e8b-b39d216d315c.png)

**Comment by carlfairclough** [comment]
Huh. The offset there is surprising.

The footer is currently using the updated breakpoints, which are fluid with no currently defined max-width (see: https://www.figma.com/file/rQK2dt9eaLOMmvTOf5ifdr/Ethereum.org-Style-Guide-RC1?node-id=3%3A0).

The offset here, however, is wrong. I believe this fix should be part of #762

**Comment by samajammin** [comment]
Sounds good to me @carlfairclough. You game with setting a max width container? I don't know if that was ever discussed in the style guide.
