### ISSUE TITLE
Add "use bridges" section to the bridge page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#8653]
### Is your feature request related to a problem? Please describe.

We have a page on bridges:
https://ethereum.org/en/bridges/

Currently it describes bridges but doesn't explain how or where to use any.

### Describe the solution you'd like

Add a "use bridges" section to the page.

Simple solution might be to just link to some resources that list out bridges, e.g.
- Risk analysis: https://l2beat.com/bridges/risk
- Bridge assets: https://transferto.xyz/swap

### Describe alternatives you've considered

We could build our own widget similar to https://transferto.xyz/swap but I suspect that might be more effort than it's worth to build & maintain.

### Additional context

Somewhat related improvement to the page, I think L2BEAT has useful definitions on the types of bridges:
- token bridges
- liquidity networks

I suspect that will be more helpful vs. what we have:
- trusted bridges
- trustless bridges

Or perhaps those types we could add in addition to "trusted" & "trustless".

Here's a Devcon talk with more info on the different bridge types:
https://www.youtube.com/watch?v=10welw1d_Bc

**Comment by nloureiro** [comment]
This issue is still very relevant,  any takers to follow up?

**Comment by minimalsm** [comment]
Reposted here ##12450

Closing this one out
