### ISSUE TITLE
Feature Request - Add Staking Survey as a Banner to the Staking page

### ISSUE THREAD

**Issue by Rodrigolvc** [ethereum/ethereum-org-website#8654]
### Is your feature request related to a problem? Please describe.

- The current distribution of Ethereum validators is becoming increasingly centralized amongst a few large entities. 
- To remedy the situation, we need a better understanding of how and why users choose where and when to stake their ETH. 

### Describe the solution you'd like

- We would like ethereum.org to link an anonymous survey asking users if they are staking, how and when, and why they chose the staking method. 
- The survey is at (https://stakingsurvey.paperform.co/)
- To obtain a larger sample size and reduce bias, we need to disseminate the survey through as many avenues as possible. 
- Ethereum.org is used by a larger cross-section of the Ethereum community than other specialized staking resources. 

### Describe alternatives you've considered

- We are already looking at on-chain data, but it doesn't explicitly tell us why people chose to stake via a SaaS or as a solo validator. 
- We are disseminating the survey through other avenues, but few of them will have the reach that ethereum.org does. 
- We could use a different survey provider if paperform doesn't follow the guidelines and practices of ethereum.org

**Comment by minimalsm** [comment]
Hey @Rodrigolvc, thanks for raising this.

For the proposed survey, could you confirm:

- How do you anticipate the data being used?
- Will the results be made public?

**Comment by minimalsm** [comment]
Also, when would this survey run? Does it have a start and end date?

**Comment by Rodrigolvc** [comment]
- The data will be used to determine the causes of centralization, create visual data, and inform our strategy to mitigate centralization. The survey is anonymous unless participants want a POAP; we will issue POAPs and delete the email list. 
- Results will be publicized. 
- We anticipate running it for two weeks.

**Comment by Rodrigolvc** [comment]
- Starting the 2022/11/29

**Comment by nloureiro** [comment]
@Rodrigolvc, is there a reason for the survey to be "anonymous"? In the sense that it does not have a brand/name/organized by and no link to who's behind the survey? Is it on purpose?

At the top is: "We are interested in creating informative and educational ...."
Who are "we"?

The idea is to give some credibility and assurance of who is behind this; it helps to trust and, therefore, to fill it.

In this case, it might help to be clear that it's not an ethereum.org survey, even if it's linked from there.

**Comment by Rodrigolvc** [comment]
@nloureiro @minimalsm 
I think it's a good point. We've updated the survey; it now explains that it is a collaboration between ETHStaker and the EF. Should we make it more explicit? I agree it is better to define who is running the survey.

**Comment by samajammin** [comment]
Overall I support this initiative but I am a bit wary on creating a slippery slope when it comes to community members requesting to add surveys on ethereum.org. e.g. I could see many researchers across the ecosystem wanting to create surveys on the website. We should have some sort of criteria for why or why not we decide to add a particular survey.

Criteria that comes to mind:
- making it clear "who" is running any given survey (who controls the questions) & clarifying when it's distinct from the ethereum.org core team
- requiring that raw data from surveys will be public to the community (not sure how this could be guaranteed?)
- ...anything else?

Again I support adding this survey, I just think we need to outline a clear framework on how to manage these type of requests moving forward as this sets a new precedent.

**Comment by minimalsm** [comment]
Agree with Sam's sentiments here. 

> Criteria that comes to mind:
> 
> * no surveys should capture PII
> * surveys should not be promoting/advertising any particular product or organization
> * make it clear "who" is running any given survey (who controls the questions) & clarifying when it's distinct from the ethereum.org core team
> * require that raw data from surveys will be public to the community (not sure how this could be guaranteed?)
> * require that once a survey is live on ethereum.org, it cannot be edited (not sure how this could be guaranteed?)
> * ...anything else?
> 
> Again I support adding this survey, I just think we need to outline a clear framework on how to manage these type of requests moving forward as this sets a new precedent.

I'd also like to add: "provides significant value to the Ethereum ecosystem". This is a little vague and we can work on that. In the case of this specific survey, I think it would tick that box because the aim is to learn more about how people decided to stake in order to improve overall decentralisation of stakers and therefore the security and integrity of Ethereum.

Let's consider this as working criteria for now. I don't think we need block this until we get a listing policy live on the site, but for the record, this is the framework we're working from.

@Rodrigolvc could you confirm you don't intend to/won't make changes to the survey in the time it is live on ethereum.org?

The current survey, for purposes of future reference:

<img width="735" alt="Screenshot 2022-12-01 at 14 24 23" src="https://user-images.githubusercontent.com/62268199/205077579-368fb814-0b29-4a5d-9491-2afd967ac318.png">

**Comment by Rodrigolvc** [comment]
@minimalsm We won't make any changes to the survey while it's displayed on the Ethereum.org website! Let me know when we can get it live.
