### ISSUE TITLE
Add Nansen's 'Proof of Reserves' of all Exchanges

### ISSUE THREAD

**Issue by epicfox87** [ethereum/ethereum-org-website#8683]
### Exchange name

All Exchanges Proof of Reserves

### Exchange description

After the recent events that led to the bankruptcy of FTX, it is very important for everyone to have quick way to view all exchanges reserves, please add this resource as a note:

https://portfolio.nansen.ai/entities?utm_source=twitter&utm_medium=social&utm_campaign=portfolio_exchanges_12nov22

It includes all major exchanges reserves from the most known wallets that belong to them.

### What geographical restrictions apply to this exchange?

No restrictions

### Which currencies are accepted by this exchange?

N/A

### Do you have any proof that they're a legitimate company?

Nansen is widely adopted analytics company

### Do you have any extra information?

N/A

**Comment by samajammin** [comment]
Related to #8611

**Comment by corwintines** [comment]
Going to close this in favor of #8611 @epicfox87, but would appreciate your input over there! :)
