### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by nsexer** [ethereum/ethereum-org-website#8704]
### Describe the bug

Broken link on https://ethereum.org/en/learn/#what-is-ethereum-used-for: 
 More on Ethereum use cases > 📃Blockchain in developing countries > http://governance40.com/wp-content/uploads/2019/06/Blockchain-in-Developing-Countries.pdf

### To reproduce

1. Visit 'https://ethereum.org/en/learn/#what-is-ethereum-used-for'
2. Click on 'Blockchain in developing countries'

### Expected behavior

Link to report

### Screenshots

![image](https://user-images.githubusercontent.com/30265113/203275487-85315e0a-6a20-462c-8c68-0b4a85d7b334.png)

### Desktop (please complete the following information)

Mac

**Comment by corwintines** [comment]
Thanks @nsexer!

I found a working wayback link that we can replace this with for now: https://web.archive.org/web/20220708092831/http://governance40.com/wp-content/uploads/2019/06/Blockchain-in-Developing-Countries.pdf

Will open up a PR to update.

**Comment by corwintines** [comment]
PR created
