### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by 1kko-ahnlabio** [ethereum/ethereum-org-website#8742]
### Wallet name

ABC Wallet

### Wallet description

Secure and convinient Multichain wallet by security company.

### Wallet logo

![favicon_400](https://raw.githubusercontent.com/ahnlabio/abcwallet-extension-provider-api/93841ec6e990c654c933cddffab6fa00783b0372/icon/favicon_400.png)

### Background color for brand logo

#000000 or #ffffff

### URL to the project

https://myabcwallet.io/

### When did the wallet go live to users?

2. Sep. 2022

### Does the wallet have an active development team?

Yes, https://github.com/ahnlabio/abcwallet-extension-provider-api

### Is the wallet globally accessible?

Yes

### Is the wallet available in multiple languages?

English, Korean, Japanese

### What social links are there for the project?

https://twitter.com/AhnLab_ABC
https://www.youtube.com/@ABC_Wallet
https://medium.com/@AhnLabBlockchainCompany

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes. Here are links
- Android: https://play.google.com/store/apps/details?id=io.myabcwallet.mpc&hl=en&gl=US
- iOS: under screening by Apple.

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, it supports Chromium

### Is it a hardware wallet?

no

### Is the source code for the wallet fully open-source?

No, but we will probably open source it within this year.

### What license is the wallet software released under?

Currently not available.

### Who holds the private keys?

We use MPC (multi-party computation) for signing and recovering private key. We divide key into thee shares and stored one to user, another to AhnLab Blockchain Company's server (co-sign server), and last one to Atomrigs Lab server (recovery server), our partner. These shares are a private key itself, instead using Shamir's secret share algorithm and ECDSA makes private key recoverable whenever user needs to sign the contract, requiring using two out of three key shares. 
Through this architecture we archive decentralized, distributed private key recovery system. 
When user decides to leave wallet, we will provide private key. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

As AhnLab Blockchain Company is a subsidary company of AhnLab, one of the biggest cyber security company in Korea, security is our main concern. To achieve highest security in infrastructures, polict and software.

## Infrastructure security:
- [AhnLab MSS](https://global.ahnlab.com/site/product/productSubDetail.do?prodSeq=1000) monitors 24/7 on our servers and infrastructures. 
- Our developers' PC and equipments are proactively scanned on both OS level and network level.

## App security:
- All of our communication between servers and wallets are encrypted end-to-end.
- With [AhnLab's ASTx ](https://www.ahnlab.com/kr/site/product/productView.do?prodSeq=109) (propietary security modules), App shuts down whenever irregular event(such as memory modification, rooting, debugging) is detected.

## Transaction security:
- Anytime wallet user tries to interact with suspicious dApp, smart contracts, transactions, ABC Wallet warns user for it's risk.

### Has the wallet's smart contract code or security modules been audited?

App Security modules are CC certified and used most of banks in Korea.

### Does the wallet have an internal security team?

Although security team is legally external, we are tightly coupled with AhnLab, and have weekly security report from MSS, realtime resopnse for any incidents.

### Scam protection?

Yes. combining our internal and external malware and scam data sources, we are able to detect any suspicious interaction including dApp, smart contract and EOA.

### Does the wallet support connecting to a hardware wallet?

Yes. We support Ledger hardware through "Ledger Live", "WebHID" and "U2F".

### Does the wallet support WalletConnect?

Yes. We are now included since [WalletConnect V2 beta 9](https://github.com/WalletConnect/web3modal/pull/755)

### Does the wallet support importing Ethereum RPC endpoints?

Yes. You may add Custom Network in "Settings > Networks > Add Custom Network".

### Does the wallet support viewing and interacting with NFTs?

Not currently but is planned to be included with in 1Q.2023.

### Does the wallet support connecting to Ethereum applications?

Yes. 

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

Yes. ABC Wallet supports all EVM networks out of the box.

### Does the wallet support Ethereum layer 2 networks?

Yes. all networks that use EVM transactions are supported.

### Does the wallet allow the user to customize gas fees?

Yes. During the transaction, user can easliy select gas fee for faster transaction or customize gas fee.

### Does the wallet support sending transactions to ENS addresses?

No

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No

### Does the wallet support withdrawals to fiat?

No

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No, but the key is only recovered when user is authroize oneself for recovery.

### Who can the ethereum.org team can contact regarding the wallet in future?

our [company twitter](https://twitter.com/AhnLab_ABC), or directly email to [Ikko](1kko@ahnlab.com)

### Does the wallet have a dedicated support team?

No, but our response to email is very quick within an hour during working hours (9-18 KST). If live support is needed, we create telegram group and involve responsible individuals to resolve the issue.

### What educational resources/documentation do you provide to users?

We have some guide and tutorials at our youtube channel: https://www.youtube.com/@ABC_Wallet

### Does the wallet have any integrated tools not mentioned above?

No

**Comment by corwintines** [comment]
Hey @1kko-ahnlabio. Thanks for the submission.

As part of our must haves, we require a project to be live for over 6 months. You can see our policy [here](https://github.com/ethereum/ethereum-org-website/issues/8781).

Feel free to reopen in a few months again if you'd like to be considered.
