### ISSUE TITLE
Suggest a tutorial

### ISSUE THREAD

**Issue by mushketyk** [ethereum/ethereum-org-website#8748]
### Tutorial title

Developing Applications on Ethereum Blockchain

### Tutorial description

In-depth course about developing DApps on Ethereum

An in-depth course about developing full-stack applications on the Ethereum blockchain. The course starts with the basics of the Ethereum protocol and its infrastructure. Then it goes into the Solidity programming language, setting up a development environment using Truffle, testing smart contracts, reusing Solidity code, writing frontends for Ethereum applications, and much more.

### Tutorial tags

Solidity, web3

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials to be hosted on Ethereum.org: Tutorial Content

Table of Content of the course:

- Course Overview 
- Ethereum Protocol
- Getting Started with Smart Contracts 
- Solidity Programming Language
- Ethereum API  
- Blocks and Fees
- Truffle Framework 
- Developing Advanced Smart Contracts
- Reusing Code in Smart Contracts
- Web Applications with Ethereum

### For tutorials hosted elsewhere: URL to tutorial

https://www.pluralsight.com/courses/blockchain-ethereum-developing-applications

**Comment by corwintines** [comment]
Adding this to grooming session to discuss

**Comment by mushketyk** [comment]
@corwintines Did you have a chance to discuss it?

**Comment by corwintines** [comment]
Thanks @mushketyk 

We do have some tutorials from Patrick for example which covers this. It seems pretty broad for a single tutorial. Going to close this out for now as we have some tutorials covering these topics.
