### ISSUE TITLE
Social icons in footer not displaying

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#876]
**Describe the bug**

**To Reproduce**
1. Visit any page

Appears it's an issue with the fill/color of the icons

**Expected behavior**

Icons should display.

**Screenshots**

![Image 2020-03-25 at 3 49 50 PM](https://user-images.githubusercontent.com/8097623/77593035-b351bf80-6eb0-11ea-9942-a95397bd01bd.png)

**Comment by samajammin** [comment]
FYI @carlfairclough

**Comment by samajammin** [comment]
Confirmed, they ARE there, it's an SVG fill/color issue:
![Image 2020-03-25 at 3 56 23 PM](https://user-images.githubusercontent.com/8097623/77593276-396e0600-6eb1-11ea-9d15-bf4d8268037b.png)

**Comment by carlfairclough** [comment]
Ahhhhh this must've been lost when dealing with nav icons. Will open a PR in the next few minutes to address this.
