### ISSUE TITLE
Remove mentions of specific node provider projects from developer docs

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#8767]
### Is your feature request related to a problem? Please describe.

Currently, we get PRs every few weeks from node providers to be added as a suggestion directly in the copy of the page.

- [Example 1](https://github.com/ethereum/ethereum-org-website/pull/8554/files#r1025642625)
- [Example 2](https://github.com/ethereum/ethereum-org-website/pull/8666/files)
- [Example 3](https://github.com/ethereum/ethereum-org-website/pull/8664/files)

We obviously cannot add every node provider to this page. If we want to remain credibly neutral, we should remove all mention of specific products and, instead, link to our nodes as a service page.

### Describe the solution you'd like

- Remove all mention of specific providers 
- Link to our nodes as a service page
- Improve copy of these sections to support the removal of specific mentions

### Describe alternatives you've considered

- Do nothing.
- Add whoever opens a PR to this section.

**Comment by corwintines** [comment]
Added this to GH grooming
