### ISSUE TITLE
Fix wrong unit in chart energy consumption

### ISSUE THREAD

**Issue by UliGall** [ethereum/ethereum-org-website#8769]
### Describe the bug

The `<EnergyConsumptionChart />` element in [src/content/energy-consumption/index.md](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/energy-consumption/index.md) has a wrong caption.

It says _Annual Energy Consumption in TW/yr_, but it needs to be _Annual Energy Consumption in TW**h**/yr_. Note the missing **h**.  Everywhere else it's correct.

### To reproduce

1. Go to [website](https://ethereum.org/en/energy-consumption/)
2. Scroll down to Chart
4. Notice wrong unit

### Expected behavior

TWh instead of TW

**Comment by UliGall** [comment]
@jmcook1186 tagging for visibility; I'd submit a PR, but couldnt find the file that I needed to change.

**Comment by jmcook1186** [comment]
ok - thanks for the catch!
