### ISSUE TITLE
Implement Chakra's Breadcrumbs component

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8772]
### Is your feature request related to a problem? Please describe.

Currently we have [a custom implementation](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Breadcrumbs.tsx) of the Breadcrumbs component.

### Describe the solution you'd like

Replace the current implementation using the [Chakra's Breadcrumbs component](https://chakra-ui.com/docs/components/breadcrumb/usage).

### Describe alternatives you've considered

None.

**Comment by TylerAPfledderer** [comment]
@pettinarip I can take this!

**Comment by pettinarip** [comment]
Thanks for the help @TylerAPfledderer assigned to you 💪🏼
