### ISSUE TITLE
Remove Ropsten and Rinkeby from nodes-and-clients page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#8773]
### Describe the bug

Ropsten and Rinkeby testnets are in the process of being deprecated.

According to a previous [blog post](https://blog.ethereum.org/2022/06/21/testnet-deprecation), Ropsten is due to be deprecated by the end of this year (Q4 2022), and Rinkeby (which never underwent a merge upgrade) is due to be deprecated by mid next year (Q2/Q3 2023).

Given Ropsten deprecation is essentially going on right now, and Rinkeby is still in a pre-merge environment with waning support, wanted to raise the idea of removing these as supported networks from the `nodes-and-clients` page.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/nodes-and-clients/#execution-clients
2. See 'Networks' column

### Expected behavior

Should we still be listing these is they are in the process of being deprecated, while we have Goerli and Sepolia to use? Rinkeby is not an appropriate staging area for dapp developers as it is still in a pre-merge environment.

### Screenshots

<img width="667" alt="image" src="https://user-images.githubusercontent.com/54227730/204368217-3f8e9939-2372-40c7-97e6-c5086013e50e.png">

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/54227730/204368310-7969009c-0c74-46da-b3ec-c44ad381ef0e.png">

### Additional context

If we agree, would be great if a community member could hop in to remove these =)

**Comment by yash251** [comment]
Please assign me this

**Comment by wackerow** [comment]
@yash251 Thanks! Assigned =)

**Comment by yash251** [comment]
So should I remove "Ropsten" and "Rinkeby" from the Networks column? Also, should I change Görli to Goerli? @wackerow

**Comment by yash251** [comment]
@wackerow please check and let me know

**Comment by corwintines** [comment]
@wackerow I believe this can be closed now with the above PRs.

**Comment by yash251** [comment]
> @wackerow I believe this can be closed now with the above PRs.

Yes it has been merged
