### ISSUE TITLE
Request for a Simple Introduction to Ethereum (Idiot's Guide)

### ISSUE THREAD

**Issue by AdebolaEgunjobi** [ethereum/ethereum-org-website#8776]
Someone please create a simple introduction to Ethereum - like an Idiot's Guide. The whole thing is quite confusing and getting more so!! People like me are scared away by the seeming complexity and deep amount of detail. I'm finding it hard to know where to start learning!

**Comment by corwintines** [comment]
@AdebolaEgunjobi going to close this. If you have any suggestions on our content or specific areas that are confusing feel free to open an issue for those :)
