### ISSUE TITLE
Suggest a staking product or service

### ISSUE THREAD

**Issue by totoCZ** [ethereum/ethereum-org-website#8797]
### Project name

Squid

### Product type

Staking as a service

### Logo

![squid Logo - Black with Transparent Background](https://user-images.githubusercontent.com/5316250/204906808-79539a06-37fe-4fb7-be99-bbebb58049d9.svg)

### Description

Squid specializes in building and operating infrastructure for Ethereum users and also offers a hosted staking service.

### Website

https://www.ohsquid.com

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes

### If a service, what are the fees associated with using the service?

12 USD per validator per month.

### What date did the project or service go live?

Nov 2022

### Has the project undergone an external security audit?

No

### Has the project undergone any security bug bounties?

No

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

No, the service administrator has access to staking keys.

### If listing a staking-as-a-service, are users required to sign-up for an account?

Yes, at a minimum sign up with email is required. No other information is needed.

### If listing as staking-as-a-service, who holds the signing keys, and withdrawal keys?

Signing keys: User & Service
Withdrawal keys: User

**Comment by corwintines** [comment]
@wackerow could you review when you have a moment

**Comment by wackerow** [comment]
Thanks for filing this @totoCZ! Appreciate the thoroughness with the form. 

From your post, this seems fitting for an SaaS listing with the following indicators:

OPEN SOURCE: No
AUDITED: No
BUG BOUNTY: No
BATTLE TESTED: Nov 2022 - <6mo, newly released (will soon switch to >6mos)
PERMISSIONLESS: No
DIVERSE CLIENTS: No?
SELF CUSTODY: No

If this sounds correct, would welcome a PR to add it to the `staking-products.json` file, or let me know if you need a hand and I can help get this added.

**Comment by wackerow** [comment]
Noticing here that I had labeled "SELF CUSTODY: No" in my comment above, but per your post:

> If listing as staking-as-a-service, who holds the signing keys, and withdrawal keys?
> Signing keys: User & Service
> Withdrawal keys: User

...it looks like this would meet the current definition. I see you already labeled this `true` in the PR 👍, just wanted to make note.

**Comment by totoCZ** [comment]
Excellent, thank you.
