### ISSUE TITLE
ankr staking info issues

### ISSUE THREAD

**Issue by PolozovT** [ethereum/ethereum-org-website#8801]
### Describe the bug

there is incorrect data about ankr liquid staking here: [https://ethereum.org/en/staking/pools/#explore-staking-pools](https://ethereum.org/en/staking/pools/#explore-staking-pools)
we have audits and it can be found here: [https://www.ankr.com/docs/staking/liquid-staking/eth/overview/#audit-details](https://www.ankr.com/docs/staking/liquid-staking/eth/overview/#audit-details)
also we have a bug bounty for our eth liquid staking: [https://immunefi.com/bounty/ankr/](https://immunefi.com/bounty/ankr/)

### To reproduce

open page https://ethereum.org/en/staking/pools/#explore-staking-pools and you can see red circles near "AUDITS" and "BUG BOUNTY". it's wrong

### Expected behavior

circles near "AUDITS" and "BUG BOUNTY" are green

### Screenshots

![image](https://user-images.githubusercontent.com/39823227/205059842-6f7d1e98-60c3-42b1-bd32-8e3ccd1a2c69.png)

**Comment by romelsantosgalvan010** [comment]
Por q me Jaqueo mi cel puto de perra pero ni ni sabe comole va air
