### ISSUE TITLE
[BUG] BannerNotification text should be centered

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#8806]
### Describe the bug

Text should be center aligned in BannerNotification instead of left aligned

### To reproduce

1. Go to [staking page](https://ethereum.org/en/staking)
2. Notice banner at the top
3. See text left aligned

![Screen Shot 2022-12-01 at 5 16 10 PM](https://user-images.githubusercontent.com/15589226/205186593-43e2bc44-44c2-4be7-bf09-1c625f62f80d.png)

### Expected behavior

Text should be centered. BannerNotification could just be Stack instead of Flex

![Screen Shot 2022-12-01 at 5 21 35 PM](https://user-images.githubusercontent.com/15589226/205186761-654a8049-ff03-4594-8886-447739a945b4.png)

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by ai-slave** [comment]
can't reproduce

**Comment by TylerAPfledderer** [comment]
Banner not showing in prod, but showing in dev.

The wrapping flex element will need the `justifyContent="center"` here.

**Comment by pettinarip** [comment]
TODO: once we fix this issue, remove the `Center` component from `PostMergeBanner` as it is not going to be needed anymore.
