### ISSUE TITLE
Add SmartContracts Tools to Dapp list

### ISSUE THREAD

**Issue by vittominacori** [ethereum/ethereum-org-website#8819]
SmartContracts Tools offers a set of decentralized products and services running on different blockchain networks.
No login. No setup. No coding required.

[Token Generator](https://www.smartcontracts.tools/token-generator/): Create a Token in less than a minute with the most used Smart Contract Generator.

![Screenshot 2022-12-03 alle 16 40 20](https://user-images.githubusercontent.com/8151143/205449273-fb68f899-ebc2-4cdf-b9f6-7582a0c09a23.png)

[Token Watcher](https://www.smartcontracts.tools/token-watcher/): Create a dedicated page for your ERC20 or BEP20 Token to share.

![image](https://user-images.githubusercontent.com/8151143/205449256-70ffab14-79cf-4828-a77a-ea6400513f0e.png)

**Comment by corwintines** [comment]
Ill add this to grooming. 

Do you mind providing a rationale for why you feel this should be added?

**Comment by corwintines** [comment]
@vittominacori could you fill out our [Suggest a dapp issue template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&template=suggest_dapp.yaml&title=Suggest+a+dapp). Ill close this out so you can reopen an issue with that.
