### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Ayushhgupta39** [ethereum/ethereum-org-website#8842]
### Is your feature request related to a problem? Please describe.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/96309609/205957881-8ff0b60a-6539-42f9-b138-0fa546a634df.png">

Here, in the above Image, the word 'Trustless' can be a bit misguiding for the readers. Although it means that Web3 doesn't rely on third-parties and operates using incentives, a word like Trustless is a bit inappropriate.

### Describe the solution you'd like

The word 'trustless' can be replaced by a word like 'independent' or 'self-reliant' to better describe the documentation.

### Describe alternatives you've considered

The word 'trustless' can be replaced by a word like 'independent' or 'self-reliant' to better describe the documentation.

### Additional context

I would love to make this contribution.

**Comment by corwintines** [comment]
Trustless is a very prominent term in Ethereum, and the broader ecosystem. I don't think we should be changing this.
