### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by trevorsc19** [ethereum/ethereum-org-website#8855]
### Dev tool name

Kaleido

### Dev tool description

Kaleido is an infrastructure provider for web3 developers looking to easily create their own blockchain networks.  Right now, we offer users the option to create a blockchain network using multiple different Ethereum clients (Geth, Besu, Quorum, and Polygon Edge) as well as Hyperledger Fabric and R3 Corda.

### When did the dev tool go live?

November 2017

### Where do you think this page should be shown?

On the Enterprise Ethereum page and on the storage page (for our IPFS solution)

### Is the product open source?

No

### Documentation URL

https://docs.kaleido.io

### Additional context

We're already listed on the private Ethereum page, but just looking to make sure we're represented in all of the correct places on the Ethereum.org website.

**Comment by trevorsc19** [comment]
I'd like to be assigned to this issue - I will be providing a PR shortly with some updated documentation

**Comment by corwintines** [comment]
Closing as above PR has been merged
