### ISSUE TITLE
Format and Lint Import Order with `eslint-plugin-simple-import-sort` and `prettier`

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#8865]
> **I consider this low priority in implementing**

Exploring the option of applying `eslint-plugin-simple-import-sort` and `prettier` for improved formatting and lint checking with file and package import order in components.

Not necessarily a problem; but to keep in line with project best practice, it is suggested to keep imports in a certain order.

Using `eslint-plugin-simple-import-sort` could give improved lint checking to ensure that the ordering preferences are met when adding or updating components, and be able to fail that check during PR to help reviewers catch undesirable formatting.

In addition with `prettier` formatting could happen on save or `eslint --fix` as most of the suggested configurations from this eslint package are auto-fixable.

See the docs for this [Eslint Plugin](https://github.com/lydell/eslint-plugin-simple-import-sort#readme)

In short, this setup would look for the following:
1. Installation of `eslint-plugin-simple-import-sort` as it does not exist in the project (`prettier` does exist!)
2. Go through setup with `eslintrc.js` file per [Gatsby Eslint Config Docs](https://www.gatsbyjs.com/docs/how-to/custom-configuration/eslint/#configuring-eslint). This adds installation of `eslint-config-react-app` to retain default config.
3. Applying suggested setup or similar shown in the [plugin README docs](https://github.com/lydell/eslint-plugin-simple-import-sort#usage)
4. Append or alter the config as needed
5. Ensure a Github workflow is established for PRs that includes lint and `eslint --fix` or similar.

This GH issue is to pose the question and to investigate whether or not this will be helpful and doable in the contributing workflow. Alternatively, the `eslint-plugin-import` dep with the [import/order](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) rule is also possible, but might not have the needed options provided in the proposed package. (See ["How is this  rule different from import/order"](https://github.com/lydell/eslint-plugin-simple-import-sort#how-is-this-rule-different-from-importorder))

## Alternatives

In conjunction with Husky, use [prettier-plugin-organize-imports](https://github.com/simonhaenisch/prettier-plugin-organize-imports#readme) via `lint-staged` to automatically organize the imports during commit.

However, based on current projects I'm in that use this, the import order might not be desirable.

**Comment by TylerAPfledderer** [comment]
Should there be the exploration in using `` can consider this setup in the custom `.eslintrc.js` file:
```js
module.exports = {
  globals: {
    __PATH_PREFIX__: true,
  },
  extends: "react-app",
  plugins: ["simple-import-sort"],
  rules: {
    "import/no-webpack-loader-syntax": [0],
    "simple-import-sort/imports": [
      "error",
      {
        groups: [
          // Node.js builtins.
          [
            "^(assert|buffer|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)",
          ],
          // Packages. `react` related packages come first.
          // Also, put `react-icons` in sorting order not with `react`
          ["^react(?!-.)$", "^\\w", "^@\\w"],
          // Internal packages.
          // ["^(@|@company|@ui|components|utils|config|vendored-lib)(/.*|$)"],
          ["^(\\.\\./)+@chakra-ui/gatsby-plugin/theme"],
          // From the `types` directory.
          ["^(\\.\\./)+types"],
          // From the `components` directory.
          ["^(\\.\\./)+components"],
          // From the `utils` directory.
          ["^(\\.\\./)+utils"],
          // From the `data` directory.
          ["^(\\.\\./)+data"],
          // Parent imports. Put `..` last.
          ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
          // Other relative imports. Put same-folder imports and `.` last.
          ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
          // Style imports.
          ["^.+\\.s?css$"],
          // Side effect imports.
          ["^\\u0000"],
        ],
      },
    ],
    "simple-import-sort/exports": "error",
  },
}
```

**Comment by TylerAPfledderer** [comment]
Side note: When setting up the custom ESLint config this will also trigger warnings that have been hidden, which is helpful for any additional code cleanup.

**Comment by TylerAPfledderer** [comment]
@pettinarip should this issue be considered closed?

**Comment by pettinarip** [comment]
@TylerAPfledderer yes! thanks again
