### ISSUE TITLE
Suggest a dapp: forgivenet® 

### ISSUE THREAD

**Issue by kailash-manasarovar** [ethereum/ethereum-org-website#8873]
### Name

forgivenet

### Description

https://1frgvn.com/

There is only one true currency between human beings. forgivenet® is the start of something new. The first whispers of a global currency of love based on forgiveness. Request forgiveness from those you’ve wronged and receive an FRGVN token in return.

### Logo

![frgvn-symbol](https://user-images.githubusercontent.com/50398315/206910906-c92221e7-8cd8-46b3-9ef6-9eae155cc0c7.png)

### Brand color

#FFFFF

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/kailash-manasarovar/forgivenet-frontend -> in constant development
https://github.com/kailash-manasarovar/forgivenet -> live and not in development
https://github.com/kailash-manasarovar/forgivenet-suite -> in development, full dev environment with docs for frontend dev

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

* https://github.com/kailash-manasarovar/forgivenet
* Solidity app live on Ethereum main net.
* Built in security with SafeMath, Owned interface, ERC20 implementation, ReentrancyGuard.
* No security issues in 3 years of being live.

### Can a user access the dapp without creating an account?

Yes.

### Are dapp funds non-custodial?

Yes, funds and forgiveness requests are live on mainnet. Funds accessible with ERC20 wallets. Request accessible on Etherscan but we are working towards a visualisation of the database.

### Do you offer community support?

We are working towards this.

### Describe any geographical restrictions on usage of your dapp

None I'm aware of.

**Comment by corwintines** [comment]
There's not really any information on this project, and the description doesn't match what the app looks to do.
