### ISSUE TITLE
Include External Link Icon in a Child Element Instead of `:after` Pseudo

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#8877]
### Describe the bug

For some screen readers, they have the potential to read out any content that can be read within the pseudo elements. The external link character in the `Link` component is one of them (Checked with NVDA).

Allowing this character to be conditionally rendered in a child element instead of a pseudo will allow the ability to apply `aria-hidden` on said element to ensure it is visible, but can not be read by a screen reader.

```tsx
{ !hideArrow && (
  <Box as="span" ms={0.5} aria-hidden>↗</Box>
)}
```

### To reproduce

1. Go to any page that renders `Link` or `ButtonLink` with external. (i.e. https://ethereum.org/en/layer-2/)
2. Use screen reader (`NVDA`, in particular) and navigate to a given link.
3. Reader will read out the text and end with "upright arrow"

### Expected behavior

Screen reader should not read out this repetitive icon

**Comment by TylerAPfledderer** [comment]
Eh, this actually shouldn't be a bug, but an A11y improvement! 😅 ♿

**Comment by corwintines** [comment]
Updated the tags to match your comment :)

Let me know if you're interested in working on this and ill assign this

**Comment by TylerAPfledderer** [comment]
@corwintines assign away! 🤘
