### ISSUE TITLE
A11y Refactor: ProductList Component

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#8878]
## Objective
Improving accessibility and UI markup for the [ProductList](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/ProductList.tsx) component, including UX with screen readers.

## Description
Now that this component has been migrated to ChakraUI for the UI Epic, there might be further improvements that can be made.
- Apply the Chakra `List` component wrapping the mapped components.
- Apply the `ListItem` component to parent component in the map
- Use `aria-labelledby` to connect the list with the heading content (ensuring that if the user simply navigated to the list via screen reader shortcut, they know what type of list this is.
- Add visually hidden text in button link to extend the meaning of the link
  - It currently just renders the text "Go"
  - Add dynamic text with title prop, like `"to { title } website (opens a new window)"` (all links in all instances of this component are external)

**Comment by corwintines** [comment]
Appreciate the suggestion :)

Is this something you would also be interested in taking on @TylerAPfledderer?

**Comment by TylerAPfledderer** [comment]
@corwintines sign me up!

**Comment by corwintines** [comment]
Done :) sorry, thought I had gotten to this already
