### ISSUE TITLE
[DESIGN FEEDBACK] New markdown pages in the Design system

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#8880]
We are building a new [Design system](https://github.com/ethereum/ethereum-org-website/issues/6284) for ethereum.org

We are at a stage where some of the components are already in Figma, and we are building page templates. 
With this in mind, we want to improve the experience of navigating our mark-down-based pages.

This template is the most used on ethereum.org, and you can find them in some use cases pages, documentation pages, and tutorials.

![Screen Shot 2022-12-12 10 47 45 AM](https://user-images.githubusercontent.com/1120748/207026771-29f8a1ab-2d84-40db-ab11-f7fc043be40c.png)

We've finalized a [proposal](https://www.figma.com/file/vMfyq3UaTUxttMGIf5nxrH/Markdown-pages-feedback?node-id=6%3A13937&t=c2y450lZmb8MyzE3-1) for these pages that involves several components.
![Screen Shot 2022-12-12 10 48 01 AM](https://user-images.githubusercontent.com/1120748/207026815-d2fa1cf3-4284-4863-9ccb-c8ebef4e7d06.png)

Please use this [Figma](https://www.figma.com/file/vMfyq3UaTUxttMGIf5nxrH/Markdown-pages-feedback?node-id=1%3A7027&t=c2y450lZmb8MyzE3-1) to leave feedback or to use comments on this issue.

![Screen Shot 2022-12-12 10 52 20 AM](https://user-images.githubusercontent.com/1120748/207027437-f134b61b-b335-466e-a222-b0fbde6fee21.png)

**Comment by Dev-Liz** [comment]
I Just dropped some comments @nloureiro

**Comment by Victorybrown** [comment]
[nloureiro](https://github.com/nloureiro) is this issue still open ?

**Comment by nloureiro** [comment]
> [nloureiro](https://github.com/nloureiro) is this issue still open ?

Good question, the third-level navigation is going to be solved with the recent proposal for the navigation (you can check the work [here](https://www.figma.com/file/VFKy8nGjdd4PuSdogBUJGA/Redesign-menu-navigation?type=design&node-id=1097%3A87428&mode=design&t=HpYz57UVGpoXuNrp-1) and give some feedback  )

for the MD pages, do have anything in mind?

**Comment by nloureiro** [comment]
You can find the final design proposal here: https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=1215%3A20190&mode=design&t=CpYxGFSRAbtCBcSH-1
