### ISSUE TITLE
CoinGecko

### ISSUE THREAD

**Issue by Whiskey992** [ethereum/ethereum-org-website#8882]
### Wallet name

Crypto/Bitcoin_ethereum_bitcoincash_sweat_any Crypto on market

### Wallet description

Provides everything true and correct and super easy to use for beginners and allows fast trades for fast transactions up to date security and trust is reliable .

### Wallet logo

Coin Gecko

### Background color for brand logo

Green with colors of the rainbows plus indigo for indigenous people

### URL to the project

Www.coingecko.com

### When did the wallet go live to users?

Unknown

### Does the wallet have an active development team?

Yes I'm a developer working on it

### Is the wallet globally accessible?

Yes. names/birthdays/sin number or country based id for verification

### Is the wallet available in multiple languages?

Yes

### What social links are there for the project?

Twitter discord and Facebook

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Android smart phone or ios apple products and Windows but make a mobile use easy for users

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

Windows PC , mobile app

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Chrome and safari google and Yahoo

### Is it a hardware wallet?

All of the above

### Is the source code for the wallet fully open-source?

No

### What license is the wallet software released under?

Google

### Who holds the private keys?

Yes and data banks that open up around any country but for now google and internet and bitcoin code blockchain

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Binance bcuz i tried to audit but no good please review binance and integrate coingecko to trade with binance if they want to stay in business

### Does the wallet have an internal security team?

Yrs. Most secure bitcoin code

### Scam protection?

Protects and shows you when and where your transactions went and ip address if agreed to take payments from wallet to wallet unless done p2p and trusted p2p

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

Connecting wallets from any site crypto is used

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

All networks that deal legit crypto

### Does the wallet support staking directly?

Every crypto can now receive and earn crypto staking goes up the longer you stake for more%and you could add more for more earnings

### Does the wallet support swaps directly?

Buy/sell/trade/stake/gift

### Does the wallet support multi-chain networks?

Yes

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

No

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Unknown

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Buy through other main sites and trade

### Does the wallet support withdrawals to fiat?

Yes

### Is the wallet a multi-signature wallet?

S.i.n # or Countrys number also health care number if needed

### Does the wallet support social recovery?

Yes

### Who can the ethereum.org team can contact regarding the wallet in future?

Twitter ,Google ,binance and data banks 

### Does the wallet have a dedicated support team?

Block chain with way too find their own transaction and simply approve with two party's involved and a network monitor to see and approve

### What educational resources/documentation do you provide to users?

Simple use and very understanding

### Does the wallet have any integrated tools not mentioned above?

Indicator of being hacked and ability to disapprove transaction to prevent fraud and keep funds safe and secure under your own personal watch.

**Comment by corwintines** [comment]
No links. This doesnt seem like a genuine issue. Going to close.
