### ISSUE TITLE
Bug report: wrong color combination for tags on stablecoins page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#8923]
### Describe the bug

Stablecoins page contains a section where tags are used.

The color combinations have very low contrast and the text inside the tag is unreadable.

### To reproduce

1. Go to (https://ethereum.org/en/stablecoins/)
3. Scroll down to the "How to get stablecoins" section
4. See the color combination

### Expected behavior

Contrasting colors so that text is readable. 

<img width="247" alt="Screenshot 2022-12-15 at 20 37 47" src="https://user-images.githubusercontent.com/100724231/207903042-84d761a2-7464-4218-8bb1-b7f7e00b30f2.png">
<img width="322" alt="Screenshot 2022-12-15 at 20 38 00" src="https://user-images.githubusercontent.com/100724231/207903044-ddf99fc9-5e03-474b-9b0b-59adb10e4df7.png">

### Screenshots of current situation

<img width="458" alt="Screenshot 2022-12-15 at 20 24 13" src="https://user-images.githubusercontent.com/100724231/207901516-fae8645d-b137-4044-9a6a-121b83651f27.png">
<img width="397" alt="Screenshot 2022-12-15 at 20 24 28" src="https://user-images.githubusercontent.com/100724231/207901520-74e00bc2-7c02-46b4-9225-3d7e417f0b85.png">

### Desktop (please complete the following information)

latest chrome, macbook

**Comment by TylerAPfledderer** [comment]
@konopkja bug was introduced in #8774 (my mistake). I'll take this to make the correction!

**Comment by uday03meh** [comment]
Hi, Can I start working on it?

**Comment by TylerAPfledderer** [comment]
> Hi, Can I start working on it?

Hey @uday03meh! I have already addressed this with the referenced PR above. 😄

**Comment by pettinarip** [comment]
Nice, thanks @uday03meh & @TylerAPfledderer (I've assigned this to you)

**Comment by pettinarip** [comment]
This is issue is fixed in #8601
