### ISSUE TITLE
Launchnodes.com to be added as a solo staking provider

### ISSUE THREAD

**Issue by andreilicious23** [ethereum/ethereum-org-website#8924]
Hi @minimalsm @corwintines @pettinarip. Would appreciate if you could help with this!

Adding Launchnodes applies to the following pages:
- https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/
- https://ethereum.org/en/staking/solo/

**Product type**

- [*] Node/client tooling
- [ ] Key management
- [ ] Staking as a service
- [ ] Staking pool
- [ ] Other: (describe)

**Launchnodes**

**[Logo](https://logo-public.s3.us-east-2.amazonaws.com/app+icon.png)**
![alt text](https://logo-public.s3.us-east-2.amazonaws.com/app+icon.png)

**Launchnodes provides solo staking services for Ethereum, with validator, beacon and geth nodes
that run on AWS, Azure and your own infrastructure**

**[Website](https://launchnodes.com/)**

**If software is involved, is everything open source?**

- [ ] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ ] No, code is closed source
- [*] N/A, no custom software is involved

**Is the project a fork? If yes, which project was forked?**
No.

**Is the product out of _beta_ development?**
Yes.

**What wallets support the product or service?**
All wallets that are supported by the Ethereum Launchpad.

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**
32 ETH or multiples of 32 ETH.

**If a service, what are the fees associated with using the service?**
License fee that is paid per hour or annually to Launchnodes and AWS/Azure infrastructure fee. If the client uses own infrastructure, only the Launchnodes license fee applies. 

**If the product or service involved a liquidity token, what are the tokens involved?**
Not applicable.

**What date did the project or service go live?**
September 2020. https://aws.amazon.com/marketplace/seller-profile?id=0eee06cf-d077-4219-9d46-642372b9df1b

**Has the project undergone an external security audit?**
Internal AWS marketplace and Azure marketplace audits. Listing on both marketplaces is only allowed after the products have gone through AWS and Azure marketplaces' security audits. These are not shared, but if products fail the audit, they are not listed. 

**Has the project undergone any security bug bounties?**
No.

**Is the project being actively maintained?**
Yes.

**Is the product or service free of trusted/human intermediaries?**
Yes.

**If a pooled staking service, can users participate as a node operator without permission?**
Not a pooled staking service.

**If listing a staking-as-a-service, are users required to sign-up for an account?**
No.

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**
No. Only the client holds signing and withdrawal keys. The user maintains access to all the keys, Launchnodes has no access to any keys. 

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**
Not applicable.

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**
Prysm validator and beacon nodes as well as full geth nodes. Teku and Nimbus will be offered shortly, as will Erigon.

**What platforms are supported?**
Linux, macOS, Windows.

**What user interfaces are supported?**
CLI, AWS console and Azure console.

**Social media links**
Twitter: https://twitter.com/launchnodes
YouTube: https://www.youtube.com/channel/UC5tEUUlx11httS9Y9RvIzJw
LinkedIn: https://www.linkedin.com/company/67972177/
Discord: https://discord.gg/w5pjfWqdyT

**Comment by corwintines** [comment]
Duplicate: https://github.com/ethereum/ethereum-org-website/issues/7483
