### ISSUE TITLE
Add Farcaster.xyz to the decentralized social networks list

### ISSUE THREAD

**Issue by ShawkiS** [ethereum/ethereum-org-website#8941]
### Name

farcaster.xyz

### Description

Farcaster is a sufficiently decentralized social network. It is an open protocol that can support many clients, just like email.

Users will always have the freedom to move their social identity between applications, and developers will always have the freedom to build applications with new features on the network.

Also, this would be awesome to add in the **Further reading** section: 
https://www.varunsrinivasan.com/2022/01/11/sufficient-decentralization-for-social-networks

### Logo

![logo_128](https://user-images.githubusercontent.com/57439827/208300729-4604f7cb-8da5-4189-921a-8b9ea2131553.png)

### Brand color

#825dc7

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/farcasterxyz/hub

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Farcaster uses signing wallets to not risk the assets wallet of the user.

### Can a user access the dapp without creating an account?

The app that's developed by Merkle Manufactory is invite-only but there have been multiple permissionlessly built apps:
https://twitter.com/dwr/status/1594741328390553600

### Are dapp funds non-custodial?

N/A

### Do you offer community support?

A Telegram group chat.

### Describe any geographical restrictions on usage of your dapp

N/A

**Comment by corwintines** [comment]
Closing as above PR has been merged
