### ISSUE TITLE
Include markdownlint in github actions 

### ISSUE THREAD

**Issue by Amit0617** [ethereum/ethereum-org-website#8949]
### Is your feature request related to a problem? Please describe.

Since there is a large number of markdown files. This can fasten the process.

### Describe the solution you'd like

Include a GitHub action for Markdownlint.

### Describe alternatives you've considered

There are other tools too like write-good which can help with grammatical mistakes and spelling errors too.

### Additional context

Creating an example action in pull request too.

**Comment by corwintines** [comment]
We have a markdown linting script in the repo already. Have you considered using this instead of adding another package?

**Comment by corwintines** [comment]
Thanks for the idea @Amit0617.

This library won't be necessary for our use case. Any linting that the proposed library would provide is handled in prettier which we have configured for the repo. We also have a script `markdown-checker` which looks for custom things in the markdown for our project. 

I do think getting this in a GitHub action would be a benefit, I will make an issue for this work. But, this library isn't needed for the above reasons.

Let me know if you want to work on that new issue :)
