### ISSUE TITLE
EscrowDapp

### ISSUE THREAD

**Issue by escrowdapp** [ethereum/ethereum-org-website#8951]
Multichain Escrow Service

An open source escrow dapp acts as a neutral third party between buyer and seller to protect both parties from potential fraudulent actions of the other.

-------------

🔹Secure & Trustfull

[Open source](http://github.com/escrowdapp) code, on-chain transactions with [verified](https://tinyurl.com/escrowdapp-contracts) smart contract; safely store funds

🔹Multichain

Thanks to EVM compatible blockchains; we run on TomoChain, Ethereum, BSC and Avalanche.

🔹Don't Trust, Verify

A decentralized escrow would be an independent mechanism that would remove the need for human interaction, or at least cut it down to a minimum. That is main reason why decentralized escrow will be the core part of the future.

🔹You Are In Control

Advantage of decentralization and smart contract; no governing entity controls your funds, no one can prevent you from withdrawing your funds.

-------------

🌐 LINKS

✅ Web: https://www.escrowdapp.com/
✅ App: https://app.escrowdapp.com/
✅ Marketplace: https://market.escrowdapp.com/
✅ Twitter: https://twitter.com/escrowdapp_com
✅ Telegram: https://t.me/escrowdapp_com
✅ Medium: https://medium.com/@escrowdapp_com
✅ Github: http://github.com/escrowdapp
✅ Audit: https://tinyurl.com/EscrowDappAudit
✅ Whitepaper: https://tinyurl.com/escrow-dapp-wp

**Comment by corwintines** [comment]
Hey @escrowdapp 

We currently don't accept projects that haven't been live 6 months. Looking at the audit and GitHub, this project doesn't meet that. Going to close this.
