### ISSUE TITLE
Suggest an exchange

### ISSUE THREAD

**Issue by paybis-admin** [ethereum/ethereum-org-website#8952]
### Exchange name

Paybis

### Exchange description

Paybis is a cryptocurrency exchange that operates on a counterparty business model - meaning that we are the counterparty to each transaction and buy or sell crypto to clients from our own reserves. We do not have an order matching platform like traditional exchanges do (i.e. Binance, Coinbase etc.). Paybis allows users to buy and sell crypto assets fast and hassle-free with a variety of payment methods, and the services are available in 180+ countries with close to 2 million registered customers. 
Paybis does not hold custody over customers’ fiat funds (i.e., there is no fiat deposit option on the platform). But, we provide custodial wallet services where our users have the option to use Paybis’ hosted wallets to store their cryptocurrencies.

### What geographical restrictions apply to this exchange?

The list of Restricted jurisdictions for the provision of the Paybis’ services includes: Afghanistan, Belarus, Cuba, Hawaii (state of the US), Iran, Iraq, Myanmar, New York (state of the US), North Korea, Russia, Somalia, South Sudan, Sudan, Syria, and geographies with unrecognized or disputed status.
Point 10 of the Terms and Conditions describe the geographical restrictions in more detail https://paybis.com/policies/terms-of-service/

### Which currencies are accepted by this exchange?

Supported Fiat currencies: AED, ARS, AUD, AZD, AZN, BDT, BRL, CAD, CHF, CLP, COP, CRC, CZK, DKK, DOP, DZD, EGP, EUR, GBP, GEL, HKD, HRK, HUF, ILS, INR, JPY, KRW, KWD, MAD, MXN, MYR, NGN, NOK, PEN, PHP, PLN, RON, SAR, SEK, SGD, THB, TND, TRY, UAH, USD, XAF, ZAR.

### Do you have any proof that they're a legitimate company?

- Paybis’ “About us” page can be found here: https://paybis.com/about-us/

- Paybis has 18K reviews on trustpilot, rated Excellent:  https://uk.trustpilot.com/review/paybis.com

- The legal entity is PAYBIS LTD - a UK private company limited by shares incorporated on 28 April 2016 (company number [SC533961](https://find-and-update.company-information.service.gov.uk/company/SC533961)) whose registered office is at 1 West Regent Street, Glasgow, Scotland, G2 1RW.

- Paybis posses several registrations in different jurisdictions:
United States:
In the US, the regulations vary from state to state. In most states, Paybis’ business model does not require Money Transmitter Licences (MTLs). This has been confirmed by the regulators directly, from whom we have received no-action letters. PAYBIS LTD is also registered as a Money Service Business with FinCEN of the US. The registration number is 31000175037491.
Other licenses:
Even though in most jurisdictions Paybis is out of scope for being licensed (based on the fact we do not have a physical presence there, and we do not target customers residing in these countries), Paybis has voluntarily applied for several licenses and registrations, including AMF crypto asset registration (France), and FINTRAC registration (Canada). The Canadian regulator has already registered as a money service business, registration number is M22061209.

### Do you have any extra information?

- Paybis has been operating in the crypto market since 2014, providing services in 180+ countries, with close to 2M registered users.
- Paybis employs 100+ employees in 10+ countries

**Comment by corwintines** [comment]
Hey @paybis-admin, would you be interested in opening the PR for this?

**Comment by corwintines** [comment]
There hasn't been a response to this, so going to close.
