### ISSUE TITLE
Design Developers docs - The fire starter 

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#8955]
Usually, the title "Developers docs" refers to technical documentation to developers to follow and learn new technologies or guide them on building new applications.

At etheteum.org, this documentation is a reference to the Ethereum community, targeting beginners and intermediate users who want to learn more about Ethereum.

All new technologies bring new design challenges, and it's clear that design documentation on web3 is fundamental and lacking in the ecosystem.

This issue aims to start the discussion around what this content should be like. 

The fire starter was the contribution from [Elizabeth Bassey](https://github.com/Dev-Liz) made on a comment in the [Design system epic](https://github.com/ethereum/ethereum-org-website/issues/6284) that couldn't be more aligned with the internal roadmap discussion for Q1 2023.

A clear action item to this issue will be an EPIC dedicated to this subject, but for now, this issue will be the starting point of the discussion with the community.

The original comment is [here](https://github.com/ethereum/ethereum-org-website/issues/6284#issuecomment-1358302715), and this is a copy of the text to make it easy to have the discussion on the same page.

-----------

```
Getting started in web3 as a designer, can be very daunting because there are little to no resources available for designers (unlike developers)

ethereum.org could cover topics that would easily onboard designers from web2 into web3. Such as:

Introduction to web3 Design

Difference between web1, web2 and web3 Designs (what makes web3 different)
Web3 Fundamentals

Web3 Terminologies
Web3 tokens (and why we need them) ?
Web3 wallets
Dapps
DAOs (How they work)
Web3 Design principles
Analyzing web3 products

Ui Elements and components design
Interaction and flow
Web3 Design Basics

Wallet interaction
Interaction with blockchain protocols
Defi Product Design
NFT Product Design
Designing for web3 Governance
User Research and Usability testing in web3

Glossary

Resources

Contributing to web3 Design projects

_We could further break each topic down into subtopics._
```

**Comment by Dev-Liz** [comment]
Thank you for this! @nloureiro 

I suggest we include a navigation link - **Designers** on Ethereum.org landing page (like there is for Developers).

This section would be a documentation for web3 designers which would include:

- Tutorials
- How-to-guides
- Explanation &
- References

(Using [diataxis](https://diataxis.fr/) as a framework for proper documentation).

All content topics can be grouped under each of the framework's categories (Tutorials, How-to-guides, Explanations & References).


In the meantime, we could start by:
- Creating a timeline for the project
- Suggesting more topics for web3 design content (probably creating a dedicated issue for this)
- Once we've had enough topics, we group them into each of the above-mentioned categories
- List them as tasks in an open issue, and anyone interested could pick a topic to contribute to.

We could use a writing style guide so all content stay consistent.

Next, we
- Create a repo for the project, which would include a contribution guide for onboarding new contributors
- Contributors can contribute using Markdown, or just sharing a google docs link ( what do you think?)

*Suggesting google docs because markdown can be a problem for designers who never got to use it.


I'd love to know your thoughts on this.

**Comment by konopkja** [comment]
**Thank you for the comment @Dev-Liz , I love your excitement :)**

**I like the overall vision and direction. My suggestion:**

- lets start small and practically build toward what you suggested 
- we can monitor the impact and interest in the community
- Start with one category and build it up, this can then be published as the basis and we can move forward to the next
- is there a category or collection of topics you feel closest too?

- this should be on e.org so im not sure we need a different repo

**Currently the process I see could be like this:** 

1. ideate on design topics that you think should be covered
2. Propose those topics and the structure of the articles on GH for review
3. Wait for the design team to comment and approve
4. Once approved, write the content
5. Submit it in the corresponding in GH issue or send the link to google docs 

Once we have a few articles (around 5?) we can make the new section visible on the site

**Comment by Dev-Liz** [comment]
Thank you @konopkja!...I love your process!

I'd suggested some topics earlier though
https://github.com/ethereum/ethereum-org-website/issues/6284#issuecomment-1358302715

I guess I'll take some time to categorize and structure them properly. Once done, I'll share it here for review.

**About the topics I'm closest to?**
I'm still a newbie in web3 but have been in the ecosystem for a while now to understand a few things, I have used a few defi products too.

I believe with proper research and review from the team, I'd be able to take some introductory topics.

**Comment by samajammin** [comment]
Love the thinking here! Thanks @Dev-Liz for getting involved 😄 

I think it'd also be worth doing a bit of research around what content already exists online in the ecosystem. e.g. I came across this, which looks decent: https://www.web3designprinciples.com/

A reasonable starting point might just be to create a single page of resources for designers & to list them / link out to them from there (that's how the developers portal originally started & we iterated many times over it: e.g. see https://web.archive.org/web/20190710161625/https://ethereum.org/developers/). Not saying that was a high quality page at the time lol but more saying it's ok to get something out the door that is valuable & to iteratively improve it over time.

One the content topic front, I think you list some solid potential topics (e.g. components & user interactions unique to web3) but overall I will say **I'm skeptical about how web3 design is actually much different than web2 design**. When designing any product, you need to account for nuances (e.g. if actions are irreversible, or accounting for pending/error states) & you need to provide appropriate levels of information to the user of the product. I agree it's a different paradigm & worth building resources for but I'm not yet sold it requires fully fledged portal full with documentation, tutorials, how to guides, etc. I'm happy to be proven wrong here... but again, I think we can start iteratively. Many of the topics we also already cover across the site, so maybe it's in part about aggregating that information in one place for designers vs. building a bunch of new pages... e.g. Web3 Fundamentals, Web3 Terminologies, Web3 wallets, Dapps, DAOs - do we really need explainer pages on these topics specifically for designers? What would be different about those pages for designers vs. pages explaining those concepts to an average user?

**Comment by Dev-Liz** [comment]
> > Thank you @konopkja!...I love your process!
> > I'd suggested some topics earlier though [#6284 (comment)](https://github.com/ethereum/ethereum-org-website/issues/6284#issuecomment-1358302715)
> > I guess I'll take some time to categorize and structure them properly. Once done, I'll share it here for review.
> > **About the topics I'm closest to?** I'm still a newbie in web3 but have been in the ecosystem for a while now to understand a few things, I have used a few defi products too.
> > I believe with proper research and review from the team, I'd be able to take some introductory topics.
> 
> I am more than happy to provide feedback and review. Maybe others in the community will join as well :)
> 
> Yes those topics mostly look good, the next step should really be to:
> 
> 1. select one category
> 2. select a few of those subtopics proposed there or new ones as the articles to be written
> 3. propose for each article a high-level structure so that we know what you would like to touch upon per article.
> 
> This is important so that you dont spend significant amount of time writing about something we would not approve and to align our expectations. While the titles can look good, it still leaves a lot of ambiguity as to what would the content be.
> 
> For example in that proposed list I can see items such as "DAOs (How they work)" which we already have an explanatory [DAO page](https://ethereum.org/en/dao/), so we would need to see further details to decide how that differs from the content on the website already.



> Love the thinking here! Thanks @Dev-Liz for getting involved 😄
> 
> I think it'd also be worth doing a bit of research around what content already exists online in the ecosystem. e.g. I came across this, which looks decent: https://www.web3designprinciples.com/
> 
> A reasonable starting point might just be to create a single page of resources for designers & to list them / link out to them from there (that's how the developers portal originally started & we iterated many times over it: e.g. see https://web.archive.org/web/20190710161625/https://ethereum.org/developers/). Not saying that was a high quality page at the time lol but more saying it's ok to get something out the door that is valuable & to iteratively improve it over time.
> 
> One the content topic front, I think you list some solid potential topics (e.g. components & user interactions unique to web3) but overall I will say **I'm skeptical about how web3 design is actually much different than web2 design**. When designing any product, you need to account for nuances (e.g. if actions are irreversible, or accounting for pending/error states) & you need to provide appropriate levels of information to the user of the product. I agree it's a different paradigm & worth building resources for but I'm not yet sold it requires fully fledged portal full with documentation, tutorials, how to guides, etc. I'm happy to be proven wrong here... but again, I think we can start iteratively. Many of the topics we also already cover across the site, so maybe it's in part about aggregating that information in one place for designers vs. building a bunch of new pages... e.g. Web3 Fundamentals, Web3 Terminologies, Web3 wallets, Dapps, DAOs - do we really need explainer pages on these topics specifically for designers? What would be different about those pages for designers vs. pages explaining those concepts to an average user?

Thank you! @samajammin...you've made some really solid points here!

I agree there'd be no need to create different content for topics that have been written already (especially on e.org).

I think having a resource page like the one you've mentioned, would be a great start.

Curating those resources could give us an idea of what topics exist, and what needs to be written.


I'd get right in and curate the resources under each topic and category, referencing resources already available on ethereum.org.

Will submit it here for review when done, and we can create a page like this (https://web.archive.org/web/20190710161625/https://ethereum.org/developers/) for designers.


Once that is ready, we could then create a structure for contents that do not exist (if need be) @konopkja 

 @samajammin @nloureiro

**Comment by Dev-Liz** [comment]
Hello @nloureiro @samajammin @konopkja 

Here's a link to the resources I've curated. Please let me to your thoughts on it.
https://docs.google.com/document/d/1iionRNz_pEjOLr3gs6T8Ww1KDah6uhUekwIC4Yv2Od0/edit?usp=sharing

**Comment by konopkja** [comment]
Hello, just letting you know I will review this in the upcoming days.

**Comment by dcardines-design** [comment]
Just want to add to the convo! Really passionate about this hahaha, I vibe with the topic a lot.

In my experience designing for web3 and also building out a few products in the space (an nft wallet tracker, web3 design pattern library), and being a power user in a lot of these apps I found that there are a few key differences and unique experiences in web3 and web2 that this dedicated design page can go into, explore, and explain to other designers on how to design for:

Such as:
  1. Connecting a wallet to enter an app (simple to design for but ubiquitous experience, might be worth getting right or improving)
  2. Signing a transaction
  3. Signing a multisig wallet
  4. Having a transaction get cancelled but still lose money _(no web2 equivalent)_
  5. Locking or staking flows _(there's no web2 equivalent of staking I think, unless you include ETFs or timeshare platforms)_
  6. Switching networks _(I mean what even is an equivalent for this in web2 haha switching carriers or switching from Android to iOS OS?)_ _(what's the design approach to telling a user that "oh hey btw this feature is only available if you **switch your wallet to a different network**" there's no standard for this and it would be nice if there was.)_

Most of these are just different and (one would argue trickier to design for) because the tech is a bit too front-facing, that's why the experience isn't intuitive for those outside of the space but want to try to get into it. Which in my opinion makes the web3 experience a bit diff from web2, where designers would need to be aware of how these work and work towards designing properly for them.

An example would be buying NFTs on Opensea versus buying Reddit NFTs. These have two fundamentally different flows but one abstracts away the jargon and technicalities from the user (and if I remember from a podcast, reddit intentionally didn't want to include the term NFTs due to the baggage).

All this is to say that these examples of web3 experiences are arguably and noticeably different from web2. 😅

Also to maybe suggest adding W3Design.io to the list of resources as a design pattern library @Dev-Liz? 😊

**Comment by dcardines-design** [comment]
Oh also on this note:

https://ethereum.org/en/community/get-involved/#ethereum-jobs/

There's no "Designer" help on how to join the Ethereum community and related projects, which is a bit sad tbh. haha

cc: @konopkja @nloureiro

**Comment by Dev-Liz** [comment]
> Just want to add to the convo! Really passionate about this hahaha, I vibe with the topic a lot.
> 
> In my experience designing for web3 and also building out a few products in the space (an nft wallet tracker, web3 design pattern library), and being a power user in a lot of these apps I found that there are a few key differences and unique experiences in web3 and web2 that this dedicated design page can go into, explore, and explain to other designers on how to design for:
> 
> Such as:
> 
> 1. Connecting a wallet to enter an app (simple to design for but ubiquitous experience, might be worth getting right or improving)
> 2. Signing a transaction
> 3. Signing a multisig wallet
> 4. Having a transaction get cancelled but still lose money _(no web2 equivalent)_
> 5. Locking or staking flows _(there's no web2 equivalent of staking I think, unless you include ETFs or timeshare platforms)_
> 6. Switching networks _(I mean what even is an equivalent for this in web2 haha switching carriers or switching from Android to iOS OS?)_ _(what's the design approach to telling a user that "oh hey btw this feature is only available if you **switch your wallet to a different network**" there's no standard for this and it would be nice if there was.)_
> 
> Most of these are just different and (one would argue trickier to design for) because the tech is a bit too front-facing, that's why the experience isn't intuitive for those outside of the space but want to try to get into it. Which in my opinion makes the web3 experience a bit diff from web2, where designers would need to be aware of how these work and work towards designing properly for them.
> 
> An example would be buying NFTs on Opensea versus buying Reddit NFTs. These have two fundamentally different flows but one abstracts away the jargon and technicalities from the user (and if I remember from a podcast, reddit intentionally didn't want to include the term NFTs due to the baggage).
> 
> All this is to say that these examples of web3 experiences, might be worth talking about, improving via design, and standardizing with EF acting as the stewards. ✨🌈😅 Think Google material design guys! 😄
> 
> Also to maybe suggest adding W3Design.io to the list of resources as a design pattern library @Dev-Liz? 😊

Happy to have you join us! @dcardines-design

I think your list would make for a great How-to-guides. I also agree with us sharing some examples of web3 experiences..maybe we can share them as case studies or make them part of the **Explanations** section of the documentation.

And yes! I'd love to add **w3Design.io** to the curated list as a resource for web3 Design patterns. Thank you for taking time to create that! @dcardines-design

**Comment by Dev-Liz** [comment]
> Oh also on this note:
> 
> https://ethereum.org/en/community/get-involved/#ethereum-jobs/
> 
> There's no "Designer" help on how to join the Ethereum community and related projects, which is a bit sad tbh. haha
> 
> cc: @konopkja @nloureiro

Right!

Can we also have open-source internships inclusive of designers, please?? This would expose more designers to open-source projects as it is a common misconception that open-source projects are for developers only.

Programs like [OUTREACHY ](https://www.outreachy.org/)can be considered, alongside Google season of Docs (for Technical writers).

**Comment by nloureiro** [comment]
Hey, how are we on this? It looks like we stopped. 
Should we restart the conversation? 
I believe there is a huge potential here, and I would love to push this forward.


LMK what do you think?

**Comment by konopkja** [comment]
> Hey, how are we on this? It looks like we stopped. Should we restart the conversation? I believe there is a huge potential here, and I would love to push this forward.
> 
> LMK what do you think?

@nloureiro  I have been reviewing the quality of design sources proposed by @Dev-Liz  here: https://github.com/ethereum/ethereum-org-website/issues/8955#:~:text=https%3A//docs.google.com/document/d/1iionRNz_pEjOLr3gs6T8Ww1KDah6uhUekwIC4Yv2Od0/edit%3Fusp%3Dsharing

havent gotten through the full list yet, but welcome anyone else to review, add, comment on the proposed list

**Comment by Dev-Liz** [comment]
> Hey, how are we on this? It looks like we stopped. Should we restart the conversation? I believe there is a huge potential here, and I would love to push this forward.
> 
> LMK what do you think?

Yes, please...I'm still interested in working on it

**Comment by konopkja** [comment]
@Dev-Liz i think we will be able to move this discussion to a pull request and push the first version live soon, are you able to create a new markdown page in developer docs (foundational topics)? if not i can create it.

**Comment by konopkja** [comment]
Started draft PR: https://github.com/ethereum/ethereum-org-website/pull/9858

**Comment by konopkja** [comment]
Merged here https://github.com/ethereum/ethereum-org-website/pull/9858

Page here: https://ethereum.org/en/developers/docs/design-and-ux/
