### ISSUE TITLE
Bug report: ExpandableCard component text alignment on upgrades FAQ

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#8960]
### Describe the bug

Seeing an odd mixture of aligning text center vs left (in English) within expandable cards, FAQ section of Upgrades page.

### To reproduce

1. Go to https://ethereum.org/en/upgrades/
2. Scroll down to Frequently Asked Questions section near the bottom
3. See alignment of text, and how some are centered and some are left aligned.

### Expected behavior

All of these should consistently aligned as start (left) or center, but not both.

### Screenshots

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/54227730/208769419-314e02ea-f95a-400b-9a2b-fd9fe402a564.png">

### Additional context

I'm guessing this bug might have arisen via the Chakra-UI migration. In the past I believe these were all start-aligned, not centered. @nloureiro Can you confirm if centering text was intended here?

**Comment by TylerAPfledderer** [comment]
@wackerow Chakra's `Accordion` component applies `textAlign: center` in the default theme to `AccordionButton`.

Can at the very least apply the value `unset` which also reverts the value of this property back to `left`. 

Better for future consideration with the new DS is to apply this to the base styles in the Chakra theme config.

**Comment by TylerAPfledderer** [comment]
@wackerow This is coming from Chakra's `AccordionButton`, which serves as the toggle-able header. Because it renders a `button` wrapping all of that content, it is also applying `textAlign: center` from the user agent styles for `button`.

Can at the very least apply `textAlign: left` or `unset` to `AccordionButton`

For future consideration if content like this in all components that will use the `Accordion` components in the new DS, would look to apply this change as a base style in the Chakra theme config.

**Comment by wackerow** [comment]
@TylerAPfledderer Thanks for looking into this... `text-align: start` could be one approach this, alternatively if we actually do want this to be centered, we could likely find a way to just force the width of both texts to fill the accordion, so the centered text is actually centered, rather than dependent on the length of the text.

@nloureiro Thoughts on this? In the past these were left-aligned, but not necessarily against reconsidering this. As mentioned, I'm more looking for consistency in how it appears.. the above screenshot is lookin a bit messy as-is.

**Comment by nloureiro** [comment]
Yes, this is an alignment bug.

All should be to the left.
![Screen Shot 2022-12-26 09 20 08 AM](https://user-images.githubusercontent.com/1120748/209531066-7ba80220-d2f6-4bb5-872f-96b32a3af6a5.png)

**Comment by MahendraBishnoi29** [comment]
> Yes, this is an alignment bug.
> 
> All should be to the left.
> ![Screen Shot 2022-12-26 09 20 08 AM](https://user-images.githubusercontent.com/1120748/209531066-7ba80220-d2f6-4bb5-872f-96b32a3af6a5.png)
> 

Can i work on this? @wackerow @TylerAPfledderer @nloureiro

**Comment by corwintines** [comment]
Closing as above PR fixed this
