### ISSUE TITLE
Add Zenland to Dapps list of Ethereum.org

### ISSUE THREAD

**Issue by zenland-dao** [ethereum/ethereum-org-website#8966]
Hello. Please add Zenland as a dapp to ethereum.org 

Name: Zenland
URL: https://zen.land/
Image: https://zen.land/square-logo.jpg
Description: Escrow Smart Contract Platform & Marketplace

**Comment by albertg361** [comment]
Ok we will add him

**Comment by albertg361** [comment]
Ok we can use that

**Comment by corwintines** [comment]
Hey @zenland-dao. Could you fill out our issue template for dapps? https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&template=suggest_dapp.yaml&title=Suggest+a+dapp
