### ISSUE TITLE
Preview deploys display all external links

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#897]
**Describe the bug**

**To Reproduce**
1. Go to any PR preview deploy (e.g. [this one](https://deploy-preview-896--ethereumorg.netlify.com/assets/))
2. View sidebar links or other internal links

**Expected behavior**

They shouldn't have the external link arrows

**Screenshots**

![Image 2020-03-27 at 9 21 27 AM](https://user-images.githubusercontent.com/8097623/77777585-017bd580-700d-11ea-8a98-df72412119fa.png)

**Comment by samajammin** [comment]
Hey @carlfairclough - very small issue here but perhaps there's a quick fix to update this logic?

Looks like we exclude certain domains:
```
a:not([href^="https://ethereum.org"]):not([href^="http://ethereum.org"]):not([href^="/"]):not([href^="#"]):not(.hide-icon)
```

Can we also exclude all netlify.com subdomains?

**Comment by carlfairclough** [comment]
Looking at this now
