### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by Dadaz5** [ethereum/ethereum-org-website#8970]
### Wallet name

SafePal

### Wallet description

SafePal is a comprehensive crypto management platform that provides hardware wallet, software wallet, and browser extension wallet solutions. With powerful web3 solutions, allowing users to store, manage, swap, and trade their crypto assets. Till now SafePal has supported 15 languages, 54 blockchains and is serving close to 7M+ users global-wide.

### Wallet logo

![Vertical Logo Color](https://user-images.githubusercontent.com/120176423/208847000-d4531632-aff3-4d61-89f2-f586398bdcb3.svg)

### Background color for brand logo

#4A21EF

### URL to the project

safepal.com

### When did the wallet go live to users?

May 15th, 2019

### Does the wallet have an active development team?

https://github.com/SafePalWallet

### Is the wallet globally accessible?

SafePal is a decentralized wallet that doesn't require KYC from users. SafePal is serving 7m+ users from 196 countries and regions.

### Is the wallet available in multiple languages?

English, Japanese, Korean, German, French, Spanish, Italian, Vietnamese, Portuguese, Russian, Thai, Indonesian, Turkish, Traditional Chinese

### What social links are there for the project?

Twitter: https://twitter.com/iSafePal
Support Twitter: https://twitter.com/safepal_support
Discord: https://discord.com/invite/BuKynZqRNj
Telegram:https://t.me/SafePalwallet
Instagram: https://www.instagram.com/isafepal/
Facebook: https://www.facebook.com/iSafePal
Youtube: https://www.youtube.com/channel/UCfqztNiZWV62Eu9kiqKf6WQ

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

https://apps.apple.com/app/apple-store/id1548297139
https://play.google.com/store/apps/details?id=io.safepal.wallet

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

SafePal doesn't have a desktop app yet.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

https://chrome.google.com/webstore/detail/safepal-extension-wallet/lgmpcpglpngdoalbgeoldeajfclnhafa
https://addons.mozilla.org/en-US/firefox/addon/safepal-extension-wallet/
https://microsoftedge.microsoft.com/addons/detail/safepal-extension-wallet/apenkfbbpmhihehmihndmmcdanacolnh

### Is it a hardware wallet?

SafePal S1 Hardware Wallet adopts an air-gapped signing mechanism for better security. During a transfer, the S1 hardware wallet communicates with the SafePal App via encrypted QR codes. No radio frequencies, antenna, or USB are involved, which keeps the S1 device 100% offline and safely protected against remote attacks or online attacks. 

### Is the source code for the wallet fully open-source?

 SafePal is not open-sourced yet. The SafePal team is preparing its open-source wallet program that will open the SafePal mobile app, browser extension, and communication protocol on the hardware wallet to third party developers.

### Who holds the private keys?

As SafePal is a decentralized wallet, it means that SafePal is not storing users' security passwords. Users can take complete control over their crypto assets by holding the seed phrase (also called the mnemonic phrase). If SafePal were to disappear, users could still access their funds using their seed phrase.
The seed phrase is the only proof of users' decentralized assets on the blockchain. Once it's lost or forgotten, users cannot recover the wallet elsewhere, and people who get the seed phrase will have direct access and control of your funds. If you are using a SafePal wallet, in this case, try to create a new empty wallet and manually transfer all the funds to the new wallet as soon as possible. After doing that, make sure that you have a backup of the new seed phrase and store it in a secure manner (such as using SafePal [Cypher](https://store.safepal.com/safepal-cypher-seed-board.html) to store the seed words and put it in a safe place).

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

SafePal S1 adopts the world-leading security hardware architect, with an EAL 5+ secure element(to keep the private key in a safe and isolated environment), true random number generator(to make sure the private key is uniquely generated), and multiple layers of security sensors(to detect malicious attack and trigger self-erasing mechanism).

It is implemented with an air-gapped signing mechanism. All transaction data is transferred via encrypted QR codes between the hardware device and the SafePal App. There is no Bluetooth, no WiFi, no NFC or any other radio-frequencies, and thus keeping the private key in a 100% offline environment.

On software level, SafePal is implemented with device authentication, Passphrase and self-erasing mechanism, protecting your crypto from supply chain attacks, radio-frequency attacks and other attacks. More security details can be found from our Knowledge Base (https://safepalsupport.zendesk.com/hc/en-us/categories/4406445170843-Security)

### Has the wallet's smart contract code or security modules been audited?

No critical vulnerabilities were found. 

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

**Comment by corwintines** [comment]
There are a lot of unanswered questions in this issue. Going to close, but feel free to reopen after they have been answered.
