### ISSUE TITLE
Suggest a tutorial: Connect Metamask With A Local Hardhat Network

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#8972]
### Tutorial title

Connect Metamask With A Local Hardhat Network

### Tutorial description

A quick guide on connecting Metamask to a local Hardhat network:

- Hardhat Setup
- Running a Local Hardhat Network
-  Add Local Network to Metamask
- Importing Test Accounts
- Testing The Network (via transferring test ETH)

### Tutorial tags

metamask, hardhat

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

Will link draft PR in comments after creation of issue

**Comment by corwintines** [comment]
Thanks for the suggestion @0xKai27.

My main concern here is being able to maintain a tutorial like this. I imagine hardhat will do a better job maintaining this than we will: https://hardhat.org/tutorial

We already link out to this on the tutorials page, and I imagine this is going to be the best user experience for using specific tools. My preference is to leave it as is, but will look for feedback from others.

**Comment by corwintines** [comment]
Talked with the rest of the team, we align on just linking out to hardhat for this.
