### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by Dadaz5** [ethereum/ethereum-org-website#8973]
### Wallet name

SafePal

### Wallet description

SafePal is a comprehensive crypto management platform that provides hardware wallet, software wallet, and browser extension wallet solutions. With powerful web3 solutions, allowing users to store, manage, swap, and trade their crypto assets. Till now SafePal has supported 15 languages, 54 blockchains and is serving close to 7M+ users global-wide.

### Wallet logo

![Vertical Logo Color](https://user-images.githubusercontent.com/120176423/208847000-d4531632-aff3-4d61-89f2-f586398bdcb3.svg)

### Background color for brand logo

#4A21EF

### URL to the project

safepal.com

### When did the wallet go live to users?

May 15th, 2019

### Does the wallet have an active development team?

https://github.com/SafePalWallet

### Is the wallet globally accessible?

SafePal is a decentralized wallet that doesn't require KYC from users. SafePal is serving 7m+ users from 196 countries and regions.

### Is the wallet available in multiple languages?

English, Japanese, Korean, German, French, Spanish, Italian, Vietnamese, Portuguese, Russian, Thai, Indonesian, Turkish, Traditional Chinese

### What social links are there for the project?

Twitter: https://twitter.com/iSafePal
Support Twitter: https://twitter.com/safepal_support
Discord: https://discord.com/invite/BuKynZqRNj
Telegram:https://t.me/SafePalwallet
Instagram: https://www.instagram.com/isafepal/
Facebook: https://www.facebook.com/iSafePal
Youtube: https://www.youtube.com/channel/UCfqztNiZWV62Eu9kiqKf6WQ

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

https://apps.apple.com/app/apple-store/id1548297139
https://play.google.com/store/apps/details?id=io.safepal.wallet

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

SafePal doesn't have a desktop app yet.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

https://chrome.google.com/webstore/detail/safepal-extension-wallet/lgmpcpglpngdoalbgeoldeajfclnhafa
https://addons.mozilla.org/en-US/firefox/addon/safepal-extension-wallet/
https://microsoftedge.microsoft.com/addons/detail/safepal-extension-wallet/apenkfbbpmhihehmihndmmcdanacolnh

### Is it a hardware wallet?

SafePal S1 Hardware Wallet adopts an air-gapped signing mechanism for better security. During a transfer, the S1 hardware wallet communicates with the SafePal App via encrypted QR codes. No radio frequencies, antenna, or USB are involved, which keeps the S1 device 100% offline and safely protected against remote attacks or online attacks. 

### Is the source code for the wallet fully open-source?

 SafePal is not open-sourced yet. The SafePal team is preparing its open-source wallet program that will open the SafePal mobile app, browser extension, and communication protocol on the hardware wallet to third party developers.

### Who holds the private keys?

As SafePal is a decentralized wallet, it means that SafePal is not storing users' security passwords. Users can take complete control over their crypto assets by holding the seed phrase (also called the mnemonic phrase). If SafePal were to disappear, users could still access their funds using their seed phrase.
The seed phrase is the only proof of users' decentralized assets on the blockchain. Once it's lost or forgotten, users cannot recover the wallet elsewhere, and people who get the seed phrase will have direct access and control of your funds. If you are using a SafePal wallet, in this case, try to create a new empty wallet and manually transfer all the funds to the new wallet as soon as possible. After doing that, make sure that you have a backup of the new seed phrase and store it in a secure manner (such as using SafePal [Cypher](https://store.safepal.com/safepal-cypher-seed-board.html) to store the seed words and put it in a safe place).

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

SafePal S1 adopts the world-leading security hardware architect, with an EAL 5+ secure element(to keep the private key in a safe and isolated environment), true random number generator(to make sure the private key is uniquely generated), and multiple layers of security sensors(to detect malicious attack and trigger self-erasing mechanism).

It is implemented with an air-gapped signing mechanism. All transaction data is transferred via encrypted QR codes between the hardware device and the SafePal App. There is no Bluetooth, no WiFi, no NFC or any other radio-frequencies, and thus keeping the private key in a 100% offline environment.

On software level, SafePal is implemented with device authentication, Passphrase and self-erasing mechanism, protecting your crypto from supply chain attacks, radio-frequency attacks and other attacks. More security details can be found from our Knowledge Base (https://safepalsupport.zendesk.com/hc/en-us/categories/4406445170843-Security)

### Has the wallet's smart contract code or security modules been audited?

No critical vulnerabilities were found.  https://blog.kraken.com/post/7874/kraken-security-labs-finds-flaws-in-safepal-s1-hardware-wallet/

### Does the wallet have an internal security team?

Yes the CTO of SafePal is leading a 5-man security team for supply chain, hardware design and development, software design and development and financial risk management. 

### Any other security testing that should be noted?

No

### Scam protection?

SafePal has developed tools such as Revoke Manager for users to manage the access of third-party DApps in SafePal wallet. Revoke Manager is a useful tool developed by SafePal to check all the DApps that you have authorized and revoke any of them in a few clicks.

Meanwhile, SafePal Academy has been producing educational content such as blog posts, infographics, and live streams to warn and educate users of potential scams. Here are some examples: 

- Zero Transfer Scam
https://twitter.com/V_SafePal/status/1602871714555121664?s=20&t=zVPAVpHinoN-ZA6_PhufaA

- How to use DApps Safely
https://twitter.com/safepal_support/status/1598206800594993152?s=20&t=zVPAVpHinoN-ZA6_PhufaA

- How To Identify High-Risk DApps
https://twitter.com/safepal_support/status/1605753337478934529?s=20&t=zVPAVpHinoN-ZA6_PhufaA

- How to avoid Phishing Scams
https://twitter.com/safepal_support/status/1583314442791817216?s=20&t=zVPAVpHinoN-ZA6_PhufaA

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

SafePal Extension wallet support importing Ethereum RPC endpoints. Users can add custom network in “Setting” by themselves.

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Please provide documentation for how users connect to applications. List examples (ie. connect wallet to dapp, in wallet browser, etc.) How to connect with DApps in the SafePal Extension Wallet https://safepalsupport.zendesk.com/hc/en-us/articles/7107203059611-How-to-connect-with-DApps-in-the-SafePal-Extension-Wallet

### Does the wallet support staking directly?

Yes How to stake crypto into SafePal Earn https://safepalsupport.zendesk.com/hc/en-us/articles/4408616360347-How-to-stake-crypto-into-SafePal-Earn

### Does the wallet support swaps directly?

Yes How to Use SafePal Swap https://safepalsupport.zendesk.com/hc/en-us/articles/360061266551-How-to-Use-SafePal-Swap  SafePal Swap now supports switching provider https://safepalsupport.zendesk.com/hc/en-us/articles/9600859674651-SafePal-Swap-now-supports-switching-provider-V3-7-0-and-above-

### Does the wallet support multi-chain networks?

SafePal has supported 54 blockchains including Bitcoin, Arbitrum, Aurora, TON, Boba, Ethereum, Optimism, BNB Beacon Chain, BNB Smart Chain, Doge, Cardano, Solana, Polygon, Polkadot, Tron, Avalanche, Litecoin, Cosmos, Ethereum Classic, Stellar, Crono, Near, Bitcoin cash, VeChain, Terra Classic, Theta, HECO, Kucoin Cummunity Chain, Aptos, Zcash, ETHW, Neo, Fantom, Dash, Terra 2.0, Celo, Gnosis, Kusama, Qtum, Harmony, Moonbeam, Injective, SongBird, DigiByte, Metis,Godwoken, Nervos, Godwoken V1, Syscoin, RSK, Fuse, Flare, Ripple, XDC. https://www.safepal.com/coin/lists

### Does the wallet support Ethereum layer 2 networks?

Yes, we support a lot of Ethereum layer 2 networks, sidechain and other EVM compatible chains. Here are some details:  L2: Arbitrum One, Optimism, Metis, Boba;  Sidechains & other EVM compatible chains: BSC, Polygon, Gnosis, Aurora, Avalanche C Chain, Celo, Crono, Fantom, Fuse, Godwoken, HECO, KCC, Moonbeam, RSK, Syscoin, SongBird, Flare, ETHW, XinFin;  More details you can check on our changelog below. SafePal App Upgrade History https://safepalsupport.zendesk.com/hc/en-us/articles/360047721832-SafePal-App-Upgrade-History  Firmware Upgrade History https://safepalsupport.zendesk.com/hc/en-us/articles/360047263792-Firmware-Upgrade-History  SafePal Extension Wallet Upgrade History https://safepalsupport.zendesk.com/hc/en-us/articles/10081198445467-SafePal-Extension-Wallet-Upgrade-History

### Does the wallet allow the user to customize gas fees?

Yes, please see the sceenshot of app in the google slide page1 https://docs.google.com/presentation/d/1BFOSj30KOB6q5ZLBkuZBhU3rQcG7JxKmVXSt2TCBxgY/edit?usp=sharing

### Does the wallet support sending transactions to ENS addresses?

SafePal has not supported sending transactions to ENS address yet, but we are preparing to support them in the future.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes; How to Import a MetaMask Wallet into SafePal App (via Private Key) https://safepalsupport.zendesk.com/hc/en-us/articles/8823024878235-How-to-Import-a-MetaMask-Wallet-into-SafePal-App-via-Private-Key-  How to import all the EVM chains with one set of private key in a SafePal wallet https://safepalsupport.zendesk.com/hc/en-us/articles/9601422838555-How-to-import-all-the-EVM-chains-with-one-set-of-private-key-in-a-SafePal-wallet

### Does the wallet support EIP-1559 (type 2) transactions?

Yes, SafePal Hardware wallet, Mobile App wallet and Extension wallets all support EIP-1559 (type 2) transactions.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes, we provide fiat on-ramps solutions in SafePal wallet such as Simplex, Moonpay and Binance Connect.  Please see the sceenshot of app in the google slide page 2 https://docs.google.com/presentation/d/1BFOSj30KOB6q5ZLBkuZBhU3rQcG7JxKmVXSt2TCBxgY/edit?usp=sharing Here is the guide of “How to use the Buy Crypto DApp in SafePal App” https://safepalsupport.zendesk.com/hc/en-us/articles/6808893659291-How-to-use-the-Buy-Crypto-DApp-in-SafePal-App-

### Does the wallet support withdrawals to fiat?

SafePal don’t provide off-ramp solutions yet but will support soon.

### Is the wallet a multi-signature wallet?

SafePal don’t support multi-signature yet. It’s on our 2023 Q1 roadmap.

### Does the wallet support social recovery?

SafePal hasn't supported social recovery yet. It’s on our 2023 Q2 roadmap.

### Who can the ethereum.org team can contact regarding the wallet in future?

Telegram: @veronica520
Twitter: @iSafePal

### Does the wallet have a dedicated support team?

Yes, we have a full-time dedicated support team to help users 24/7. To seek help, users can visit our official website (https://www.safepal.com/) and scroll to the bottom of safepal.com. Then, select "Submit a Request" to contact a member of the SafePal support team. A SafePal support team member will contact you shortly (within 48 hours of the workday)after logging a support ticket.

### What educational resources/documentation do you provide to users?

1) SafePal Academy 
https://blog.safepal.com/
2) Infographic posts examples:
a) How to use DApps Safely
https://twitter.com/safepal_support/status/1598206800594993152?s=20&t=zVPAVpHinoN-ZA6_PhufaA
            b) How To Identify High-Risk DApps
https://twitter.com/safepal_support/status/1605753337478934529?s=20&t=zVPAVpHinoN-ZA6_PhufaA
c) How to avoid Phishing Scams
https://twitter.com/safepal_support/status/1583314442791817216?s=20&t=zVPAVpHinoN-ZA6_PhufaA
3) Youtube tutorial/livestreams
           a) SafePal Software Wallet Tutorials
https://www.youtube.com/playlist?list=PLFGC6K0dA6l1K_JBJskf4a6Rq76TbXJr1 
           b) SafePal Extension Wallet Tutorials
           https://www.youtube.com/playlist?list=PLFGC6K0dA6l2KOorbQmeoCCIUvWgvY8PZ
           c) SafePal S1 Hardware Wallet Tutorials
           https://www.youtube.com/playlist?list=PLFGC6K0dA6l05oxW7w1t5mUr4k3VGe8yc
           d) SafePal LiveStreams
           https://www.youtube.com/playlist?list=PLFGC6K0dA6l1XGYpcxQMeqJGZ7gn5o4qQ

**Comment by corwintines** [comment]
This seems like a duplicate. Going to close and use first one.
