### ISSUE TITLE
Suggest a tutorial: Securing off-chain data via on-chain NFTs

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#8977]
### Tutorial title

Creating Truly Decentralised NFTs — A Comprehensive Guide to ERC721 & IPFS

### Tutorial description

Blockchain memory is expensive but IPFS enables data to be economically stored off-chain while its provenance is still secured on-chain. The tutorial guides the user through the following steps:

- Hardhat & IPFS Environment Setup & Configuration
- Extending OpenZeppelin’s ERC721 Contract & Helper Contracts
- Deploying Token Contract to Goerli Testnet (getting test ETH, connecting to node, private key exporting)
- Uploading Data to IPFS and Writing Response to the Blockchain
- Interacting Programatically with a Local Contract Instance
- Sending Created ERC721 Tokens on Goerli Testnet via Metamask

### Tutorial tags

ipfs, erc-721, hardhat

### Skill level

Intermediate

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

Will link draft PR in comments after creation of issue

**Comment by corwintines** [comment]
Would be open to this @0xKai27. My suggestion would be to use the Sepolia testnet instead though

**Comment by nloureiro** [comment]
Closing this issue because the [PR](https://github.com/ethereum/ethereum-org-website/pull/8978) is closed too
