### ISSUE TITLE
Intro To Ethereum (What are smart contracts?) - Minor readability improvements

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#8984]
Minor language changes to make the "What are smart contracts?" section easier to follow.

Draft pull request screenshot below:

![image](https://user-images.githubusercontent.com/104422522/209248722-ee452294-f71b-4fa4-aac6-7e4c7391fad8.png)

**Comment by corwintines** [comment]
Closing based on comment in PR
