### ISSUE TITLE
Suggest a tutorial: Signing In With Ethereum via Metamask

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#8993]
### Tutorial title

Signing In With Ethereum via Metamask

### Tutorial description

Quick guide focusing on the core sign-in flow using Metamask:

- SIWE Authentication on Client vs Server
- Constructing the sign-in message for users to approve
- Avoiding replay attacks through nonce synchonisation
- Interacting with SIWE via the Metamask UI

### Tutorial tags

metamask, ethers.js, siwe

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

Will link draft PR in comments after creation of issue

**Comment by corwintines** [comment]
Left a comment in the PR about this. Strongly encourage you to workshop the tutorial you created a bit more and open this again. Feel free to reach out on discord if you want to jam on it a bit
