### ISSUE TITLE
broken link at /build/ page

### ISSUE THREAD

**Issue by sneg55** [ethereum/ethereum-org-website#9]
https://ethereum.org/build/%5Bhttps://github.com/ConsenSys/ethereum-developer-tools-list#ethereum-clients%5D(https://github.com/ConsenSys/ethereum-developer-tools-list#ethereum-clients) 

![image](https://user-images.githubusercontent.com/7769371/56984036-f341e280-6b39-11e9-95f7-ae8bb16f1028.png)

**Comment by alancwoo** [comment]
Good catch, thanks!
