### ISSUE TITLE
Feature request: Add information on censorship resistant relays

### ISSUE THREAD

**Issue by enehizy** [ethereum/ethereum-org-website#9010]
### Is your feature request related to a problem? Please describe.

To fight censorship resistance the community has come up with the ultra sound relay ,a credibly neutral relay..But it currently only has 2.8% of validators..

### Describe the solution you'd like

Since relays are important  Ethereum there should be a section dedicated to relays..while advertising any credibly neutral relays

### Describe alternatives you've considered

There is no other alternative 

### Additional context

![Screenshot_2022-12-27-10-58-23-995_com brave browser](https://user-images.githubusercontent.com/39803122/209649339-f523edbe-048b-47f1-a696-fa6761d8ce42.jpg)

**Comment by corwintines** [comment]
@wackerow wondering if you have any thoughts on this topic as we have discussed censorship resistance in the past.

@jmcook1186 also wondering if you have any ideas here as well given some of the roadmap stuff you recently worked on.

**Comment by corwintines** [comment]
I think there has been some information added for this with our roadmap content, and this issue has gone stale. Going to close this out , but if you still think this is important and want to contribute for it @enehizy please open another issue for this :)
