### ISSUE TITLE
KyberSwap

### ISSUE THREAD

**Issue by tramtrinh14** [ethereum/ethereum-org-website#9015]
Propose to feature KyberSwap - A multichain AMM DEX and DEX aggregator, native to Ethereum, in Token Swap and Investment tab:

[](https://kyberswap.com/swap/)

![logomark](https://user-images.githubusercontent.com/101160249/209782401-9c529b8d-f111-45be-a2be-8aa5fbff9039.png)

**Comment by corwintines** [comment]
Closing in favor of https://github.com/ethereum/ethereum-org-website/issues/9147
