### ISSUE TITLE
EcsrowDapp

### ISSUE THREAD

**Issue by escrowdapp** [ethereum/ethereum-org-website#9016]
#listing request on ethereum.org/en/dapps/?category=finance

Name: EscrowDapp
Contract: https://etherscan.io/address/0x09a712106B287CEFf717dA86da51CA66696427D2#code
Audit: https://github.com/verichains/public-audit-reports/blob/main/Verichains%20Public%20Audit%20Report%20-%20EscrowDapp%20Smartcontracts%20-%20v1.1.pdf
Web: [www.escrowdapp.com](http://www.escrowdapp.com/)
App: https://app.escrowdap.com/
Telegram: https://t.me/escrowdapp_com
Twitter: https://twitter.com/escrowdapp_com
Medium: https://medium.com/@escrowdapp_com

**Comment by corwintines** [comment]
Duplicate PR, left comment in original
