### ISSUE TITLE
Suggest a glossary term

### ISSUE THREAD

**Issue by coldu42** [ethereum/ethereum-org-website#9026]
### Checklist

- [X] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [X] This term/definition is not a product advertisement or contain other promotional content
- [X] This term/definition is directly relevant to Ethereum

### Term name

Proto-Danksharding

### Term definition

A scaling solution that reduces the cost of [layer 2](https://ethereum.org/en/layer-2/) call data through the introduction of blob carrying [transactions](https://ethereum.org/en/glossary/#transaction).

### Sources, if any (please do not submit copywrited content without appropriate approval)

[Bankless: Dive into Danksharding with Vitalik, Dankrad, Protolambda, Tim Beiko](https://www.youtube.com/watch?v=N5p0TB77flM)

### Ethereum.org links

[Sharding](https://ethereum.org/en/upgrades/sharding/)

[Proto-Danksharding FAQ](https://notes.ethereum.org/@vbuterin/proto_danksharding_faq#What-is-proto-danksharding-aka-EIP-4844)

**Comment by coldu42** [comment]
Request for self assignment

**Comment by corwintines** [comment]
@jmcook1186 do you think this would be worthwhile adding with your roadmap work?

**Comment by corwintines** [comment]
@coldu42 now that we have content on the site around proto danksharding I think this would be appropriate. Is this something you are still interested in contributing?
