### ISSUE TITLE
Typo in Consensus-mechanisms/Block creation {#pow-block-creation} Line no 39.

### ISSUE THREAD

**Issue by 1xAhmed** [ethereum/ethereum-org-website#9030]
There were 2 " The the " on line 39 in the documentation section of Consensus-mechanisms/Block creation {#pow-block-creation}. 
I can fix this typo. I would like you to assign me this issue. Thank you!

**Comment by RanaAhmed-Ali** [comment]
I can fix this typo. I want you to assign me this issue. Thank you!

**Comment by corwintines** [comment]
Closing as this was addressed in above PR :)
