### ISSUE TITLE
Typo in the MEV Proposer-Builder Separation section Line 151.

### ISSUE THREAD

**Issue by 1xAhmed** [ethereum/ethereum-org-website#9032]
There were 2 " receive receive " on line 151 in the documentation section of last paragraph of Proposer-Builder Separation.
I can fix this typo. I would like you to assign me this issue. Thank you!

**Comment by RanaAhmed-Ali** [comment]
I can fix this typo. I want you to assign me this issue. Thank you!

**Comment by corwintines** [comment]
Closing as this was completed in above PR's
