### ISSUE TITLE
Suggest a tutorial: Issuing And Verifying Ethereum DIDs with Metamask

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9060]
### Tutorial title

Issuing And Verifying Ethereum DIDs with Metamask

### Tutorial description

Signing, Issuing, and Verifying DIDs as JWTs on a browser UI using Metamask

- Key concepts and data objects (DID, DID Documents, Registries, Key Pair, JWT)
- End-to-end process in the shoes of the Issuer and Audience (i.e. validator)
- Issuance of a JWT with a private claim that is signed by the Issuer
- Creation of a Issuer delegate signer
- Validation of Subject DID Document and JWT payload by the Audience

### Tutorial tags

signing, ethers.js, metamask, identity

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

Will link draft PR in comments after creation of issue

**Comment by corwintines** [comment]
Thanks for the suggestion @0xKai27. Going to add to GH grooming to see what the team thinks about adding this tutorial. 

I wanted to check, I see you link out to your medium post for this. Would you consider just having this as an external tutorial instead of something maintained on ethereum.org? We support external tutorials as well.

**Comment by 0xKai27** [comment]
Honestly, I'm indifferent with regards to where the tutorial is hosted. The external links are more so because it already exists on Medium. I was thinking more so in terms of not requiring the user to navigate out from ethreum.org

**Comment by wackerow** [comment]
- Hey @0xKai27! I see #9061 was closed out, assuming this was because we're diverting to posting this as an external tutorial? Did you want to place a PR to list this as an external tutorial, or would you like a hand with this?

**Comment by wackerow** [comment]
Posting the Medium link here for reference: https://medium.com/@kaishinaw/issuing-and-verifying-ethereum-dids-with-metamask-a42070c0a04d

**Comment by 0xKai27** [comment]
@wackerow Sure, I can post this as an external link :)

**Comment by wackerow** [comment]
Hey @0xKai27, were you still interested in posting a PR for this?

**Comment by corwintines** [comment]
Threw a PR up for this
