### ISSUE TITLE
Add Art Blocks to the "Explore dapp" page, under "Art and Fashion" or "Digital Collectables"

### ISSUE THREAD

**Issue by ABDruid** [ethereum/ethereum-org-website#9066]
Artblocks.io would be a great platform to surface on the "explore dapp" page.

**Comment by corwintines** [comment]
@ABDruid could you resubmit this using the `suggest a dapp` issue template: https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&template=suggest_dapp.yaml&title=Suggest+a+dapp
