### ISSUE TITLE
Bad redirect from /upgrades/shard-chains/

### ISSUE THREAD

**Issue by seishun** [ethereum/ethereum-org-website#9067]
### Describe the bug

Requesting this path redirects to //upgrades/sharding/.

### To reproduce

1. Go to https://ethereum.org/upgrades/shard-chains/

### Expected behavior

Landing on a page related to sharding or an error page.

**Comment by corwintines** [comment]
Thanks for reporting this @seishun! Definitely not the intended experience. Ill open a PR to add this redirect in.
