### ISSUE TITLE
The text is centered on the expandable cards 

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9069]
### Describe the bug

This [PR](https://github.com/ethereum/ethereum-org-website/pull/8572) introduced a bug.

the text is centered and should be to the left.

![Screen Shot 2023-01-05 04 58 04 PM](https://user-images.githubusercontent.com/1120748/210837309-ea2804c1-4ddf-4893-af8c-7b4b05251d6a.png)

https://ethereum.org/en/history/

![Screen Shot 2023-01-05 05 02 54 PM](https://user-images.githubusercontent.com/1120748/210838441-49fd9c7a-8381-4f6b-bf24-2c9b98321e2c.png)
https://ethereum.org/en/run-a-node/
in this case some are center and others are left.

### To reproduce

1. [Go to](https://ethereum.org/en/history/)'

2. See error

### Expected behavior

the carde should be left alight
![Screen Shot 2023-01-05 05 05 51 PM](https://user-images.githubusercontent.com/1120748/210838959-376ca2c5-2c46-408c-ad01-ee5c1b3b9c94.png)
![Screen Shot 2023-01-05 05 04 51 PM](https://user-images.githubusercontent.com/1120748/210838965-ca9f5364-d40f-4af8-a2bd-fdf5ed036c09.png)

**Comment by 0xKai27** [comment]
Tagging related issue #8960 for easier reference. This behaviour is happening across all expandable card components on ethereum.org. Some examples include:

### History of Ethereum
[Link](https://ethereum.org/en/history/)
![image](https://user-images.githubusercontent.com/104422522/211478019-a105ac35-41d1-45a8-87f8-8f06d4493b88.png)

### Academic Grants Round
[Link](https://ethereum.org/en/community/grants/academic-grants-round/#accordion-button-:R17klalajkau:)
![image](https://user-images.githubusercontent.com/104422522/211477723-746a9a2c-8caa-471c-bab7-88692ab9d970.png)

**Comment by MahendraBishnoi29** [comment]
@nloureiro @wackerow I would love to work on this 🚀

**Comment by MahendraBishnoi29** [comment]
also what about this @nloureiro @wackerow? shouldn't it be also centered like in the first card

<img width="907" alt="Screenshot 2023-02-04 134818" src="https://user-images.githubusercontent.com/74294202/216756908-9f71769c-a2ea-44d3-9050-e619d3fba2be.png">

**Comment by corwintines** [comment]
Closing this out as this has been resolved
