### ISSUE TITLE
Learn Page: Change stablecoins card description

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9079]
## Description

Current stablecoin card description only refers to dollar denominated stablecoins. There are currently other stablecoins, such as the EUROC, which do not use the "dollar terminology". With increased adoption of DeFi, it is [likely](https://medium.com/@kaishinaw/the-future-of-stablecoins-a-macro-lens-3f09dc05339e) that many stablecoin variants will continue to be created organically based on non-dollar currencies: yuen/yen, rupee, ruble, franc, won, etc. 

![image](https://user-images.githubusercontent.com/104422522/210920477-de1f4f20-23d1-4481-80c8-47b9c6281c91.png)

## Suggested

Stablecoins are cryptocurrencies **_whose valuations_** are designed to **_track widely accepted forms of money_**.

**Comment by corwintines** [comment]
Thanks for bringing this up. I agree this description should change (like many things on that page 😅).

I would suggest something more along the lines of:

```
Stablecoins are cryptocurrencies that attempt to peg their value to a currency, commodity, or some other financial instrument.
```

Let me know what you think! If this is something you would like to work on let me know too, I can assign this to you :)

**Comment by 0xKai27** [comment]
Sure, I could create a PR for this
