### ISSUE TITLE
Improve navigation menu usability

### ISSUE THREAD

**Issue by shazow** [ethereum/ethereum-org-website#908]
Right now, the navigation bar is using on-hover menus, this has common usability pitfalls and is generally discouraged. (Lots of content about the topic under the query `usability hover menus`)

Here's a brief recording reproducing a problem that I legitimately ran into twice immediately upon opening the page for the first time, it's super frustrating: https://imgur.com/a/UPtxlVR

Suggestions:
- Switch away from on-hover menus altogether if possible (the mobile hierarchical side nav is really nicely done, could use that for desktop too?)
- If we're committed to on-hover menus, then add a timeout before the menu is closed which will give the cursor a chance to make it over a gap (200-500ms should do it), and increase the hover box margin (a 10-20px margin of forgiveness of going outside of an element helps).

**Comment by carlfairclough** [comment]
Thanks! This is related to #868 and is a priority

**Comment by samajammin** [comment]
Thanks for the thoughtful feedback @shazow! 

I do agree moving away from hover menus is worth considering but as a quick fix I think adding a timeout like you mentioned is a great solution. @carlfairclough could you please add that in when tackling #868?

**Comment by samajammin** [comment]
@all-contributors please add @shazow for ideas & accessibility

**Comment by shazow** [comment]
Thank you. :)
