### ISSUE TITLE
What Is Ethereum Page: Standardise "middleman" terminology

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9080]
## Description

Under the "What is a cryptocurrency?" section, there are multiple variations of the middleman concept (middle man, middle-man):

![image](https://user-images.githubusercontent.com/104422522/210924884-83cc9540-5102-45ae-8869-918c6f8e6ec1.png)

## Suggested

To standardise to "middleman" as per dictionary definition

**Comment by gretellzz** [comment]
After falling victim to fraud twice trying to recover my stolen USDT, I gave up on the possibilities of ever being able to have it recovered until Gear Head Cyber Panacea was recommended on Quora and I was very grateful to have come across the article as they recovered 85% of my stolen USDT and so I decided to share this for anyone else that might be in need of their services..you can reach them on Gearheadcyberpanacea AT gmail DOT com or check out their website GEARHEADPANACEA dot COM
