### ISSUE TITLE
Add Hebrew Resource

### ISSUE THREAD

**Issue by bensam282** [ethereum/ethereum-org-website#9087]
Hi, 

I'm Ben Samocha, founder & CEO of CryptoJungle.co.il the largest crypto news, academy and education platform in Israel, operating in Hebrew. I've also founded CryptoTalks - the largest crypto community with more than 40,000 members, and the largest youtube channel - CryptoJungle.

I'd like to add http://www.cryptojungle.co.il/  as a Hebrew resource on the language resource page as we are featuring ethereum guides and news constantly.

https://ethereum.org/en/community/language-resources/

Thanks,
Ben

**Comment by corwintines** [comment]
Hey @bensam282. 

I was wondering if you could give a little more info on the content that you have on CryptoJungle. I was seeing a lot of investment type of content, which I don't think we would want. But, if there are more resources on the technology that I am missing please let me know!

**Comment by bensam282** [comment]
Of course - CryptoJungle is essentially the center of the Israeli blockchain and crypto ecosystem.
We have 3 major pillars to our work:
1. Content - Largest & leading website that includes news, guides, opinion pieces and analysis // Largest & leading podcast (we hosted for example an Ethereum 2.0 week in September w 5 different interviews) // Largest & leading YouTube channel w weekly videos // and operating across all social platforms. Content is led by myself, Ben Samocha - the founder.
2. Community - Largest & leading community with 43K members - CryptoTalks on Facebook ("מדברים קריפטו") and physical events for beginners, B2B, investors and more. 
3. Education - We have an academy facing B2C customers w beginner & professional courses (Blockchain Expert with a certification by the Israeli Chamber of Information Technologies), and we provide professional education within businesses - both crypto companies (some of them are among largest in the Ethereum ecosystem), and traditional companies, government authorities, etc.

We have in depth content not solely on investments but on the underlying technology itself.

**Comment by corwintines** [comment]
I think what would be best here is linking out to these specific episodes rather than this site itself. There is too much not focused on Ethereum here that would be confusing for a user. Let me know what episodes and links you have and we can look to add them on https://ethereum.org/en/community/language-resources/

**Comment by bensam282** [comment]
Of course, here are the relevant episodes and links, from the last one to the first one:

1. Udi Wertheimer - What bitcoiners can learn from Ethereum 
https://www.cryptojungle.co.il/udi-wertheimer-what-bitcoiners-can-learn-from-ethereum/
2. Omer Greismen (OpenZeppelin) - How We Prevented a 15 Billion Dollars Smart Contract Hack
https://www.cryptojungle.co.il/omer-greisman-openzeppelin/
3. Shy Datika (INX) - Tokenization and the future of securities, including is Ethereum a security
https://www.cryptojungle.co.il/shy-datika-tokenization/
4. Roy Confino (Lemonade) - Insurance @ Ethereum
https://www.cryptojungle.co.il/roy-confino-insurance/
5. Idan Ofrat (Fireblocks) - Instutional Adoption 
https://www.cryptojungle.co.il/idan-ofrat-fireblocks/
6. Gal Weizman (MetaMask) - What is MetaMask
https://www.cryptojungle.co.il/gal-weizman-metamask/
7. Dror Aviely (Consensys) - The center of ethereum
https://www.cryptojungle.co.il/dror-aviely-ethereum-center/
8. Nir Rozin - Being a cryptopunk
https://www.cryptojungle.co.il/nir-rozin-cryptopunk/
9. Adan Kedem - Gaming & Metaverse
https://www.cryptojungle.co.il/adan-kedem-web3-gaming/
10. Uri Kolodny (Starkware) - Ethereum and blockchain layers
https://www.cryptojungle.co.il/uri-kolodny-starkware/
11. Udi Wertheimer - Ethereum 2.0 vs competition
https://www.cryptojungle.co.il/udi-on-eth2/
12. Ben Samocha (myself) - Ethereum 2.0 - an opportunity?
https://www.cryptojungle.co.il/etherurm2-week-summary/
13. Alon Muroch (Bloxstaking) - What is Ethereum 2.0?
https://www.cryptojungle.co.il/alon-moroch-eth2/
14. Eilon Aviv (Collider Ventures) - What can go wrong with Ethereum 2.0
https://www.cryptojungle.co.il/eilon-aviv-eth2-0/
15. Eilon Aviv (Collider Ventures) - Why do we need Ethereum 2.0
https://www.cryptojungle.co.il/eilon-aviv-ethereum-2-0/


Also a guide on ethereum (will be updated soon too):
https://www.cryptojungle.co.il/coins/what-is-ethereum/

**Comment by corwintines** [comment]
Im in favor of adding these, will create a PR. Apologies for bad turn around @bensam282.
