### ISSUE TITLE
Add "improve this page" link to markdown pages of the repo

### ISSUE THREAD

**Issue by shazow** [ethereum/ethereum-org-website#909]
I couldn't find a link anywhere on https://ethereum.org/ where to go to open issues or contribute back. (Is there one? Did I miss it?)

Would be nice if there was a link somewhere. At minimum, in the footer nav. Bonus points if the "Website last updated: Mar 30, 2020" string was linked to the commit maybe?

Also a "Help improve this website" link or badge somewhere would be great too.

**Comment by samajammin** [comment]
Another excellent idea! I think the only link we provide currently is the Github icon in the footer (& that links to [the ethereum org](https://github.com/ethereum), not this website repo.

Providing a link to the last commit may be tough but I think a link to the corresponding page in the Github repo would be a quick win. Looks like [Vuepress provides this functionality in their default theme](https://vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links), which I bet we could mimic.

Thanks @shazow

**Comment by samajammin** [comment]
FYI @shazow - we've added this page to our footer: https://ethereum.org/about/

I still think a "improve this page" link is a worthy addition so I'll keep this issue open.
