### ISSUE TITLE
Content Idea: Top 3 best and worst web3 experiences — rated by natives and newbies

### ISSUE THREAD

**Issue by dcardines-design** [ethereum/ethereum-org-website#9091]
I think it would be interesting if we rate web3 experiences from the perspectives of crypto natives (buildoors, 1-4+ years in the space) and newbies (optional, 1-4 months in the space). We can use certain criteria to standardize this as well, and maybe have some additional standards on who can rate or give their opinion and who can't.

I think this can open the conversation up as to what makes a really good web3 experience and set the bar for others to emulate, non of the super complex onboarding that introduces 10+ concepts to grandma. 

One of the best that comes to mind is Reddit and their Vault feature. Super seamless!

**Comment by corwintines** [comment]
Unsure what the ask is here. Feel free to open again with more info.
