### ISSUE TITLE
Suggest a dapp: Synthetix

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9130]
### Name

Synthetix

### Description

Synthetix is a protocol for issuing and trading synthetic assets on [Ethereum](https://www.ethereum.org/). Each synthetic asset (or [Synth](https://docs.synthetix.io/tokens#synthetic-assets-synths)) is an [ERC20 token](https://theethereum.wiki/w/index.php/ERC20_Token_Standard) which tracks the price of an external asset.

Proposed one-liner for dapp preview: Synthetix is a protocol for issuing and trading synthetic assets

### Logo

![Synthetix-glyph-blue](https://user-images.githubusercontent.com/104422522/211483567-125a8963-1c9b-4c72-8aa2-03f66f054f2e.svg)

Please refer [here](https://drive.google.com/drive/u/0/folders/1lYReAAGwzb39isEID1n-dDwvFwzKAGDj) for brand assets

### Brand color

#00D1FF

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/synthetixio

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Yes, audits are done for every release and linked to [Github](https://github.com/Synthetixio/synthetix/releases)

### Can a user access the dapp without creating an account?

Yes, access is via standardised wallets. Please see screenshot of current [app](https://staking.synthetix.io/)

![image](https://user-images.githubusercontent.com/104422522/211485716-758df72c-c236-4439-b660-366a585269d4.png)

### Are dapp funds non-custodial?

Yes, please refer to [Addresses](https://docs.synthetix.io/addresses/) for the full list of Synthetix contracts. Users are able ot call the contract directly using the [`_close`](https://github.com/Synthetixio/synthetix/blob/v2.80.3/contracts/Collateral.sol) function.

### Do you offer community support?

Discord: https://discord.com/invite/Synthetix

### Describe any geographical restrictions on usage of your dapp

Globally accessible

**Comment by 0xKai27** [comment]
Relates to #9129

**Comment by corwintines** [comment]
@0xKai27 is your idea to have this under the trading and predictions market category?

Also, would you like to lead adding Synthetix?

I think this project is fine to add.

**Comment by 0xKai27** [comment]
That would be the most accurate category based on the existing groupings.

To be more specific, I believe a "Derivatives" section would better suit an app like Synthetix. This would be related to the dapp framework suggested under #9146. What does the team think with regards to expanding the dapp categories?
