### ISSUE TITLE
Suggest a dapp: DYDX

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9131]
### Name

dYdX

### Description

dYdX is a leading decentralized exchange that currently supports perpetual trading. dYdX runs on smart contracts on the Ethereum blockchain and allows users to trade with no intermediaries.

### Logo

![logo](https://user-images.githubusercontent.com/104422522/211494338-941da213-f206-49a4-952b-04d8ae8de031.svg)

Please refer [here](https://dydx.exchange/brand) fro brand assets

### Brand color

5b63f7

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/dydxprotocol

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

The Starkware Perpetual smart contracts were audited independently by [PeckShield](https://peckshield.com/).

Please refer to [docs](https://dydxprotocol.github.io/v3-teacher/#vulnerability-disclosure-policy) for latest reports

### Can a user access the dapp without creating an account?

Yes, access is via standard web3 wallets

![image](https://user-images.githubusercontent.com/104422522/211496611-933a4836-5ace-4aa3-bb04-6f25b9d8736d.png)

![image](https://user-images.githubusercontent.com/104422522/211496675-fd3b7bc2-fac3-4ee5-9dc3-5d3ed085ac84.png)

### Are dapp funds non-custodial?

Yes, contract addresses can be found on the official [Github](https://github.com/dydxprotocol/perpetual/blob/master/migrations/deployed.json)

[`P1Margin.sol`](https://github.com/dydxprotocol/perpetual/blob/master/contracts/protocol/v1/impl/P1Margin.sol) defines a `withdraw()` function which enables the withdrawal of the margins previously deposited

### Do you offer community support?

Discord: https://discord.gg/Tuze6tY

### Describe any geographical restrictions on usage of your dapp

dYdX contracts are not offered to persons or entities who reside in, are citizens of, are located in, are incorporated in, or have a registered office in the United States of America.

**Comment by 0xKai27** [comment]
Relates to #9129

**Comment by corwintines** [comment]
@0xKai27 do you recall if DYDX is still on Ethereum? Last I recall they were abandoning it for Cosmos.

**Comment by corwintines** [comment]
https://github.com/ethereum/ethereum-org-website/pull/7585 I recall us removing DYDX for this reason already. Im going to close this issue out, but feel free to reopen if you disagree.
