### ISSUE TITLE
Add Blotic Discord invite to Online Community page.

### ISSUE THREAD

**Issue by PavanTamrakar** [ethereum/ethereum-org-website#9132]
This PR adds an invite link to the Blotic community discord to the online community page. 

Blotic is a web3 college community that helps the coming generation educate what blockchain is and what it can do. We want to give our students every single resource and help them land their first web3 job. We take a student from Zero to One in blockchain and give them everything they need in the future like - Connections, Startup idea execution if they have any, and help them start their career in Blockchain.

**Comment by PavanTamrakar** [comment]
The community have received grants from PolygonDAO, Aave Grant, UniswapGrantProgram and StarkCon.

**Comment by corwintines** [comment]
This feels pretty unfinished and hard to make a call on. Is the site https://blotic.org/?

**Comment by PavanTamrakar** [comment]
Yes.
It is in the development phase it will be up and working in couple of days

**Comment by corwintines** [comment]
I would say reopen this when it is done. If that's the site and its not done then we shouldn't list it on ethereum.org imo. Thanks for the suggestion though :)
