### ISSUE TITLE
Suggest a dapp: Yearn

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9133]
### Name

Yearn Finance

### Description

Yearn Finance is DeFi’s premier yield aggregator. Giving individuals, DAOs and other protocols a way to deposit digital assets and receive yield.

### Logo

![YEARN_SYMBOL_BLUE_RGB](https://user-images.githubusercontent.com/104422522/211507325-c7140069-9569-4004-b3e3-4462d686412f.png)

Please see [Yearn press kit](https://github.com/yearn/yearn-press-kit) for brand assets

### Brand color

1554f2

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/yearn/yearn-vaults

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

The core contracts found in [yearn-vaults](https://github.com/yearn/yearn-vaults/) repository have been audited by multiple independent third-party firms

Please refer to [Security docs](https://docs.yearn.finance/security/) for more information regarding audits and testing process.

### Can a user access the dapp without creating an account?

Yes, access is via standardised wallets. Please see screenshot of current [app](https://yearn.finance/vaults)

![image](https://user-images.githubusercontent.com/104422522/211504707-81c612c8-cc80-4bee-9045-a6a65a498715.png)

### Are dapp funds non-custodial?

Smart contract addresses can be found [here](https://docs.yearn.finance/getting-started/products/addresses)

[`Vault.vy`](https://github.com/yearn/yearn-vaults/blob/master/contracts/Vault.vy) defines a `withdraw()` function which can be externally called

### Do you offer community support?

Discord: https://discord.gg/yearn

### Describe any geographical restrictions on usage of your dapp

N/A

**Comment by 0xKai27** [comment]
Relates to #9129

**Comment by corwintines** [comment]
I think this is ok to add, will create PR for this now.
