### ISSUE TITLE
Suggest a dapp: Convex

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9134]
### Name

Convex

### Description

Convex allows Curve.fi liquidity providers to earn trading fees and claim boosted CRV without locking CRV themselves. Liquidity providers can receive boosted CRV and liquidity mining rewards with minimal effort.

### Logo

![convex-finance-cvx-logo](https://user-images.githubusercontent.com/104422522/211511695-1fd7405a-7ad4-4bd2-8ba2-41f1efb2b3da.png)

### Brand color

333333

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/convex-eth

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Please see [Audit docs](https://docs.convexfinance.com/convexfinance/faq/audits) for list of formal audits performed on contracts for Convex Finance.

[Github](https://github.com/convex-eth/platform/tree/main/audit) of audit reports

### Can a user access the dapp without creating an account?

Yes, access is via standardised wallets. Please see screenshot of current [app](https://www.convexfinance.com/stake)

![image](https://user-images.githubusercontent.com/104422522/211508288-3e9c538a-5a42-474c-8ba4-c84c0f3190ee.png)

### Are dapp funds non-custodial?

Smart contract addresses can be found [here](https://docs.convexfinance.com/convexfinance/faq/contract-addresses)

[`Booster.sol`](https://github.com/convex-eth/platform/blob/main/contracts/contracts/Booster.sol) defines a `withdraw()` function which is publicly callable

### Do you offer community support?

Discord: https://discord.com/invite/TTEVTqY488

### Describe any geographical restrictions on usage of your dapp

N/A

**Comment by 0xKai27** [comment]
Relates to #9129

**Comment by corwintines** [comment]
@0xKai27 what category do you see this under?

Also, would you like to lead adding Convex?

I think this project is fine to add.
