### ISSUE TITLE
Bug report: Twemoji images not loading correctly

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9135]
### Describe the bug

Twemoji images which are used through ethereum.org asicons are not being rendered correctly. The image takes a very long time to load and eventually when it loads, it is always displayed with a broken image icon. Behaviour is inconsistent as some of the images are able to be loaded immediately on page refresh and without any issues.

See screenshots below.

### To reproduce

1. Go to the links in the 'screenshot' section below
2. Scroll down to a section which uses the Twemoji icons
3. For icons which are not shown, wait for icon to load
4. View the broken image icon upon load

### Expected behavior

Icons should be loaded on page load and without the accompanying broken icon 

### Screenshots

[Dapps](https://ethereum.org/en/dapps/)
![image](https://user-images.githubusercontent.com/104422522/211524476-e799d318-5859-41e1-8f69-7ad84aabbbeb.png)

[Layer 2](https://ethereum.org/en/layer-2/)
![image](https://user-images.githubusercontent.com/104422522/211524968-a15a8da3-8002-435d-b358-8b1cc0fb7822.png)

[Stablecoins](https://ethereum.org/en/stablecoins/)
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/104422522/211525516-7530f705-3976-4c88-ac6e-a00ea132ed9b.png">

### Desktop (please complete the following information)

Browser: Tested on Chromium (Brave and Chrome)

**Comment by utkarshk384** [comment]
It seems that the CDN(Max CDN) used by twemoji is down, therefore try following the steps provided [here](https://github.com/twitter/twemoji/issues/580#issue-1525852899).

**Comment by minimalsm** [comment]
Thanks for the report @utkarshk384 ❤️
