### ISSUE TITLE
Dapp Categorisation: A Use Case Driven Framework

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9146]
## Description
This issue is meant to drive the conversation around the categorisation of Ethereum dapps. While many dapps do not fit nicely into a single category (due to Web3 composability), having defined categories is a crucial starting point for users wanting to make sense of the possible use cases that can be built on Ethereum. 

To this end, the sections below is a proposal of dapp categories based on key concepts in the dapp space. It builds upon the existing [dapps page](https://ethereum.org/en/dapps/), and proposes language changes as well as new categories so as to clearly delineate between dapp core use cases. Example dapps have been categorised based on their core use case and will be included pending a review against ethereum.org dapp [listing policy](https://ethereum.org/en/contributing/adding-products/).

Critically, to arrive at a list that is comprehensive but not overwhelmingly long, community feedback will be much appreciated. If implemented, it is envisioned that these categorical standards will be extended across the relevant dapp pages on ethereum.org. This includes the creation of new pages which provides an overview of the categories (i.e. social, gaming). I will be happy to drive this initiative once the categories have been defined.

For further background:
- [The Web3 Stack: Web3 Primitives](https://medium.com/@kaishinaw/the-web3-stack-web3-primitives-f5695e0d8740)
- [DeFi Ecosystem: Primitives and Technology Stack](https://medium.com/@kaishinaw/defi-ecosystem-primitives-and-technology-stack-85401fdd62ad)

Related issues:
- #9063 
- #9129 
- #9130 
- #9131 
- #9133 
- #9134 
- #9147 

Excluded categories:
- Decentralised Science: Still a very niche use case that is developing. Believe the current [DeSci page](https://ethereum.org/en/desci/) will suffice.
- DAOs: DAOs build on top of dapps as a governance layer and hence is a topic which is better suited after users are familiar with a specific dapp.

### Finance

Decentralised finance dapps that encompasses all non-custodial financial services on the Ethereum chain.

| Current | Suggested | Examples | Remarks |
| :---: | :---: | :---: | :---: |
| Lending and borrowing | Loans | AAVE, Compound, Oasis, PWN | tradFi uses "loans" as a noun describing the action of lending/borrowing | 
| Trading and prediction markets | Prediction Markets | Polymarket, Augur | Remove trading to avoid confusion with token swaps |
| Payments | - | Tornado Cash, Sablier | No changes |
| Insurance | - | Nexus Mutual, Etherisc | No changes |
| Token swaps | Exchanges | Uniswap, Curve, Balancer, Loopring | More specific naming to refer to both AMM and orderbook DEXes |
| Investments | Supply Aggregator/ Investment Funds | Token Sets, Index Coop, Yearn, Convex | Specific to supply side aggregators which optimise yield through implementing smart contract strategies  |
| Crowdfunding | - | GItcoin Grants | No changes |
| Portfolios |  Portfolio Management | Zapper, Zerion, Rotki, Krystal | Specific to dapps which implement a user friendly UI for users to manage all their DeFi needs|
| - | Demand Aggregator | Matcha, 1inch, Kyber | Refers to dapps which optimise trade routes for the best rates |
| - | Marketplaces | OpenSea, Rarible | Refers to platforms which offer listing services to match NFT demand/supply |
| - | Derivatives | dYdX, Synthetix | Dapps which facilitate the trading of tokens which derive their value from an underlying asset |
| - | Liquid Staking | Lido, Ankr | Protocols which adds flexibility to cash flows by enabling users to utilise the value locked in staked funds on a Proof-of-Stake blockchain |
| - | Bridges | Multichain, Rubic | Protocols that enable assets to be securely moved across various independent chains. This can be L1<->L1 or L1 <->L2 |

### Arts and collectibles

Unique digital assets (i.e. NFTs) which have significant cultural value

| Current | Suggested | Examples | Remarks |
| :---: | :---: | :---: | :---: |
| Art and fashion | Digital Art | Foundation, SuperRare, Async Art, Nifty Gateway | Focused on the tokenisation of visual art pieces and their collections |
| Music | - | Audius | No changes |
| Digital collectibles | Digital Collectibles | marble.cards, CryptoPunks | Category for exclusive collections of tokenised assets. These collections usually have other functionalities which are built on top of provable ownership |
| - | Shared Experiences | POAP | Commemorative NFTs which are usually minted to a user based on their participation in a particular event |
| - | Marketplaces | OpenSea, Rarible | Refers to platforms with product listing pages where users can buy/sell the above |

### Gaming

Structured virtual environments with clearly defined goals and gamified play-to-earn economic incentives.

| Current | Suggested | Examples | Remarks |
| :---: | :---: | :---: | :---: |
| Virtual Worlds | _(Move to Metaverse)_ | - | More suited to metaverse as this are unstructured worlds with no defined goals |
| Competition | Web3 Games | Axie Infinity, Gods Unchaines, Dark Forest | The "competition" terminology is less helpful as a category as all Web3 games consist of some form of social comparison (i.e. there is no non-competitive games) |
| - | Yield Guilds | Merit Circle, Yield Guild Games | Dapps that are able to generate yield through optimising certain aspects of the play-to-earn gaming experience |

### Metaverse

Virtual worlds where users have the freedom to form personal networks and take ownership of digital assets

| Current | Suggested | Examples | Remarks |
| :---: | :---: | :---: | :---: |
| - | Avatars | OSUVOX, Spatial | A digital identity twin that represents a user in a particular metaverse and is capable of being manipulated by said user |
| - | Virtual Worlds | Decentraland, Voxels | Virtual worlds where users have the freedom to form personal networks and take ownership of digital assets |

### Social

Decentralised social networks and related identity technologies where digital identities and social graphs are user owned.

| Current | Suggested | Examples | Remarks |
| :---: | :---: | :---: | :---: |
| - | Social Media | gm.xyz, CyberConnect | Protocols which specialise in the sharing of social media across social graphs |
| - | Creator Economy | Mirror, Rally | Protocols that focus on the publishing of user created content (articles, videos, etc.) |
| - | Messaging | Status, XMTP, Skiff | Communication focused protocols that built on top of decentralised identity to enable direct messaging between peers on the network |
| - | Identity | ENS, Spruce,  Ontology |  Base identity infrastructure which enables decentralised proof of identity (i.e. you are who you say you are) and the verification of peer-to-peer claims (i.e. who said what about me) |

### Technology

Generic category to catch all remaining use cases which support or are related to the proper functioning of Web3 dapps.

| Current | Suggested | Examples | Remarks |
| :---: | :---: | :---: | :---: |
| Utilities | - | Golem, Graph, Arweave | Dapps which optimise compute or storage requirements of dapps |
| Developer Tools | - | radicle.xyz, API3, push | Tools which improves the dapp developer experience |
| Marketplaces | Code Marketplaces | Gitcoin | Dapps which allow developers to earn crypto for working on open-source software |
| Browsers | - | Brave, Opera | Web3 native web browsers with in-built walllets/web3 integrations |

**Comment by corwintines** [comment]
Hey @0xKai27!

Really like the suggestions here, and glad to hear you are eager to work on this. 

Looking at the your dapp categories, my initial thoughts are

---
## Finance
**Lending and borrowing -> Loans** - I understand the idea behind this, but I think Lending and borrwing probably speaks to a more global audience a bit easier
**Trading and prediction markets -> prediction markets** - Makes sense
**Payments** - Makes sense
**Insurance** - Makes sense
**Token swaps -> exchanges** - only concern is potential confusion with centralized exchanges. Understand the change here, just noting.
**Investments -> Supply Aggregator/ Investment Funds** - Lean towards investment funds here
**Crowdfunding** - Makes sense. We should add clr.fund here as well just noting
**Portfolios -> Portfolio management** - Makes sense
**Demand Aggregators** - I think most of these dapps would fall under other categories easily, might be unnecessary. Loosly held opinion here.
**Marketplaces** - Might be worth doing NFT marketplaces, but overall agree. I see this below though in Art and collectables suggestion. I think this suits that section a bit more.
**Derivatives**  - Probably makes sense, but little out of my depth on this
**Liquid staking** - I think this makes sense. @wackerow curious your thoughts too given staking page content.
**Bridges** - YES!

## Arts and collectibles
**Art and fashion -> Digital Art** - Makes sense to me
**Music** - Makes sense
**Digital collectibles** - so main difference here from Digital Art is use case largely?
**Shared experiences** - Like the idea, I think otterspace and gitpoap fit in here too. I think there probably a better name for this, but I need to think a bit more. Overall yes though.
**Marketplaces** - Agree, but this should only exist here and not Finance I think. 

## Gaming
I think this space is still a bit new to get categories. My opinion is play to earn is not a genre, but a mechanic, and likely genres are how we want to separate this out in the future. For now I think we can get away with just a gaming section without the categories still. Open to pushback here though.

## Meteverse
Curious what this landscape looks like broadly. Still feels like a lot of these would fit under Gaming at the moment. 

## Social
**Social media** - makes sense
**Creator economy** - I think this could just be Content personally
**Messaging** - Makes sense
**Identity** - Makes sense

## Technology
I think most of this is covered in developer tools, and likley more appropriate there as well. But, open to pushback on this thinking

---

Ill add this to GH grooming as well, but curious what you think of this feedback @0xKai27.

**Comment by 0xKai27** [comment]
Hey there, no major concerns with the suggestions as it was more for a draft to kickstart the discussion.

## Further comments:

### Finance
- Lending and borrowing -> Loans - We can stick to the former
- Token swaps -> exchanges - Technically "Decentralized Exchanges" covers both AMMs and orderbook models. Just cautious that DEXs tend to lean towards the former for most but with ecosystem maturity, this shouldn't be a problem.
- Demand Aggregators - I think it's important to differentiate between DEX and aggregators (even though a lot of aggregator teams also have their own DEXs). With reference to tradFi, aggregators are almost like OTC markets whereby DEXs are more similar to exchanges. Their mode of operations (i.e. router/factory contracts, API hosting, etc.) are different which results in different business models.

### Arts and collectibles
- Digital collectibles - Yes, almost a catchall for NFTs that doesn't fall into the general categories as there will be new use cases emerging.
- Marketplaces - Wasn't too sure whether to duplicate under finance as the core function of marketplaces are still trades. While the marketplace suits the current NFT use cases which largely falls under "Arts and collectibles", I'm just wary future use cases might fall outside this category but still need a platform for price and data discovery. Agree that in the current environment, leaving it here would be more in line with general expectations.

### Gaming
Agree with the genre, only callout is that yield guilds externalise the play-to-earn mechanics which might be an important conceptual difference for users (i.e. a gamer who earns through playing the game vs an investor who does not want to game but generate yield). Up for debate whether this nuance is required given the maturity of the space.

### Metaverse
The main reason for differentiating is that Metaverse provides unstructured interactions as opposed to games. In other words, games have clearly defined goals and incentives whereas Metaverse provides the user freedom to build their own experiences. This is especially crucial when starting to think about extended reality spaces whereby more of real world businesses are being merged with Metaverse NFT ownership concepts. Could be argued that life is all a game though ;)

**Comment by corwintines** [comment]
Thanks for all the thought into this @0xKai27. I'm wondering if you are wanting to work on this now :) I think we are more or less ready to start work on this idea, and any changes that might come up can be handled in a PR.

**Comment by 0xKai27** [comment]
Hey @corwintines, been meaning to get around to this but been caught up with some other things. I'll update in the next few weeks time an update here again when done

**Comment by 0xKai27** [comment]
@corwintines created a PR with the new categories and apps. Can use this as a base to tidy up the dapps page.

Specifically, there are a number of dapps which have been added that might require the team's views. 

Let me know what are the next steps. Thanks!

**Comment by 0xKai27** [comment]
@corwintines Any updates on this PR? I'm guessing I'll have to add in the new dapps which were added since the PR was created

**Comment by corwintines** [comment]
Hey @0xKai27,

On my list of things to review this sprint, thanks for checking in. Will update on what may be needed to add, but I can try to catch any of the apps that need to me added to categories.
