### ISSUE TITLE
Upgrade mdx to v2

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#9160]
### Is your feature request related to a problem? Please describe.

Upgrade the mdx version to v2.

### Describe the solution you'd like

Upgrade `next-mdx-remote` to v4 #11938. This upgrade will force us to move to [the v2 of mdx](https://mdxjs.com/blog/v2/).

Resources:
- https://mdxjs.com/migrating/v2/

### Describe alternatives you've considered

None.

**Comment by corwintines** [comment]
Do you think this is something you'll want to lead next sprint @pettinarip?

**Comment by pettinarip** [comment]
@corwintines is possible. This is an important upgrade but not urgent I'd say. So, it all depends on priorities and time/capacity we have next sprint. I'd call this as a nice to have.

**Comment by pettinarip** [comment]
Closing as we are not going to implement it on Gatsby. Its gonna be covered in the Next migration.

**Comment by pettinarip** [comment]
Reopening this issue since this is not going to be covered in the NextJS migration. More details on [this issue](https://github.com/ethereum/ethereum-org-fork/issues/9.

We are planning on tackling this issue once we finish with the NextJS migration.

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting for assignment, per private discussion.

**Comment by pettinarip** [comment]
Thanks @TylerAPfledderer, assigned.

FYI I've updated the issue description. To upgrade mdx to v2 we will need to upgrade `next-mdx-remote` to v4 (which is what #11938 is all about). Will keep both issues open but both should be fixed in the same PR.

**Comment by pettinarip** [comment]
Closing this issue for now, as we will not be upgrading this lib for now. Once we find a clear benefit or a strict limitation, we may reopen this.
