### ISSUE TITLE
Suggest a wallet: Update Gnosis Safe to Safe following rebrand

### ISSUE THREAD

**Issue by jorgeselva** [ethereum/ethereum-org-website#9171]
### Wallet name

Safe (prev. Gnosis Safe) 

### Wallet description

Safe is the most trusted decentralized custody protocol and collective asset management platform, with over $30B in assets stored across Ethereum and multiple other networks.

At the most basic, Safe is a multi-signature account standard that allows users to define a list of owner/signer accounts and a quorum of signers required to confirm a transaction. The Safe Protocol also serves as a foundation for a growing ecosystem of Dapps.

### Wallet logo

![Safe_Logos_Symbol_Green](https://user-images.githubusercontent.com/3975770/212338977-5968eae5-bb1b-4e71-8f82-af5282564c66.png)

### Background color for brand logo

#12ff80

### URL to the project

https://safe.global/

### When did the wallet go live to users?

2017

### Does the wallet have an active development team?

Yes: https://github.com/5afe

### Is the wallet globally accessible?

Yes

### What social links are there for the project?

Twitter: https://twitter.com/safe
Discord: https://chat.safe.global/
Mirror: https://safe.mirror.xyz/

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

iOS:
https://apps.apple.com/app/id1515759131
Android: 
https://play.google.com/store/apps/details?id=io.gnosis.safe

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

app.safe.global

### Is the source code for the wallet fully open-source?

https://github.com/5afe

### Who holds the private keys?

Full self-custodial

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes through the Safe App Store

### Does the wallet support staking directly?

Yes

### Does the wallet support swaps directly?

Yes

### Does the wallet support multi-chain networks?

Yes

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

Yes

### Is the wallet a multi-signature wallet?

Yes

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

https://twitter.com/JorgeSelva

### Does the wallet have a dedicated support team?

Yes

### What educational resources/documentation do you provide to users?

https://docs.safe.global/

**Comment by corwintines** [comment]
Thanks, @jorgeselva. I've updated this info and any mentions of Gnosis Safe as well.
