### ISSUE TITLE
Suggest a dapp: DexGuru 

### ISSUE THREAD

**Issue by sneg55** [ethereum/ethereum-org-website#9172]
### Name

DexGuru

### Description

DexGuru is a non-custodial trading terminal made for traders in DeFi era, leveraging on-chain analytics combined with token swap execution capabilities. 
We've built an interface that provides access to easy-to-understand on-chain data analysis across decentralized protocols on Ethereum, BSC, Polygon, Avalanche, Fantom, Arbitrum, Optimism, Gnosis, and CELO to enable traders to make best the best possible trade decisions in real-time! 

Give it a try: [dex.guru](https://dex.guru)

### Logo

![white](https://user-images.githubusercontent.com/7769371/212347747-c75f58b6-ba41-4df8-9b84-c5479479b4a9.svg)

### Brand color

6046FF

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/dex-guru/

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

DexGuru does not have a smart contract; instead, we use [meta-aggregation](https://docs.dex.guru/general/features/trading-tools/meta-aggregation). We use multiple decentralized exchange aggregators, like 1inch or 0x protocols and their smart contracts that had been audited and battle-tested. 

### Can a user access the dapp without creating an account?

Yes

### Are dapp funds non-custodial?

Yes

### Do you offer community support?

https://discord.com/invite/dPW8fzwzz9

### Describe any geographical restrictions on usage of your dapp

None

**Comment by corwintines** [comment]
@sneg55 would you be interested in making a PR for this?

**Comment by sneg55** [comment]
> @sneg55 would you be interested in making a PR for this?

Sure thing, here you go: https://github.com/ethereum/ethereum-org-website/pull/9552

**Comment by sneg55** [comment]
> @sneg55 would you be interested in making a PR for this?

Hi, can you please review this PR: #9552

**Comment by sneg55** [comment]
bump
