### ISSUE TITLE
DeFi Pulse is no longer a resource to learn about DeFi apps or get DeFi data

### ISSUE THREAD

**Issue by teuchert** [ethereum/ethereum-org-website#9178]
### Describe the bug

Hello,

on the pages https://ethereum.org/en/defi/#defi-data and https://ethereum.org/en/community/get-involved/#financial-professionals, DeFi Pulse is referenced as a resource to learn about DeFi apps or get DeFi data. 

The DeFi Pulse website no longer contains such information.

Attached you can find a screen shot of today's content of the DeFi Pulse website (there's more content of the same type if you scroll down, which is not shown in the screen shot).

Best regards,

Andreas

### To reproduce

1. Go to https://ethereum.org/en/defi/#defi-data or https://ethereum.org/en/community/get-involved/#financial-professionals
2. Click on the links to DeFi Pulse
3. Scroll down (if you want)
4. See that there's no information about Ethereum DeFi apps or data provided.

### Expected behavior

I expect sites that are referenced as a resource to learn about DeFi apps or get DeFi data, to actually provide such information.

Consequently, references to DeFi Pulse in such contexts should be removed or replaced by websites actually providing information about DeFi apps and data, like DeFi Llama.

### Screenshots

![Screenshot_2023-01-14_16-30-50](https://user-images.githubusercontent.com/3678497/212480177-11ef3329-f0f0-4839-ae7c-8150a9f6509e.png)

### Desktop (please complete the following information)

I don't believe my OS or browser matters here.

**Comment by teuchert** [comment]
I would like to create a PR fixing this issue.

**Comment by minimalsm** [comment]
Thanks for raising @teuchert 

Some more context:

- https://twitter.com/defipulse/status/1583531851305480193
- https://www.reddit.com/r/ethdev/comments/yf3na3/what_happened_to_defipulse/
