### ISSUE TITLE
Tutorial: Beginner's Guide To Yul

### ISSUE THREAD

**Issue by marjon-call** [ethereum/ethereum-org-website#9181]
Tutorial title

Beginner's Guide To Yul

Tutorial description

This guide goes over the basics of using Yul for smart contract development

Tag your tutorial

yul, memory, storage, evm

Publication

Github

Skill level

Advanced

Hosted on Ethereum.org or hosted elsewhere?

Hosted on Github
https://github.com/marjon-call/Begginer-s-Guide-to-Yul/blob/main/README.md

For tutorials to be hosted on Ethereum.org: Tutorial Content

https://github.com/marjon-call/Begginer-s-Guide-to-Yul/blob/main/README.md

**Comment by corwintines** [comment]
Id be in favor of adding this as an further reading resource here https://ethereum.org/en/developers/docs/smart-contracts/languages/#yul

Let me know what you think @marjon-call :) 

Would you like to make a PR for this as well?

**Comment by corwintines** [comment]
Closing as stale. Feel free to reopen @marjon-call if you wish and we can discuss the above comment.
