### ISSUE TITLE
Link is broken for the Engine API

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#9192]
### Describe the bug

The Engine API link gives a 404.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/networking-layer/#connecting-clients
2. Click on Engine API
3. The link gives a 404

### Expected behavior

I think we should link to this [URL](https://github.com/ethereum/execution-apis/blob/main/src/engine/common.md) now.

**Comment by pettinarip** [comment]
cc @jmcook1186 @wackerow @minimalsm

Perhaps you guys know this.

**Comment by jmcook1186** [comment]
Hi @pettinarip, the suggested replacement URL (https://github.com/ethereum/execution-apis/blob/main/src/engine/common.md) is correct!
