### ISSUE TITLE
Styling for markdown `<details>` pattern 

### ISSUE THREAD

**Issue by taxmeifyoucan** [ethereum/ethereum-org-website#9203]
### Is your feature request related to a problem? Please describe.

Some parts of docs require to list many nested options with details, e.g. [here](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#running-an-execution-client) or [here](https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/#popular-node-services) . This generally happens when there are various options and user can choose one, like different clients. 

Field which expands upon user interaction would allow to rollup unnecessary details and make docs more readable. 

### Describe the solution you'd like

Create styling which fits ethereum.org doc style and enables to nicely use spoilers in text. In markdown files this is achieved using `<details>` and `<summary>` tags. 

Here is an example: 

<details>
<summary> Title </summary>
More info
</details>

### Describe alternatives you've considered

In places where this would be beneficial, docs just use titles which creates a long and harder to navigate page. With a spoiler which expands on click, user reveals only those details he needs and page is more clear.

**Comment by corwintines** [comment]
@nloureiro @pettinarip I know we have the Accordion for the design system https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=1220%3A19589&t=hmTZYsJFYGzKvnwu-1

Do you think this would cover this issue raised here? We could always let people use <details> or <summary> and just use the Accordion component like we do for other components in markdown templates

### Reference
https://github.com/ethereum/ethereum-org-website/blob/b0d03f9b5ffe80b325d9d34aa3c0ae1d8131c6a9/src/templates/static.tsx#L121

**Comment by taxmeifyoucan** [comment]
@corwintines yes that sounds good to me! Where can I find more info on how to use this component?

**Comment by corwintines** [comment]
Was chatting with @minimalsm and @wackerow and we agree we arent going to add support for `<details>` and `<summary>` in markdown due to how Crowdin parses html elements in markdown. 

For the `ExpandableCard` example, we would do the following:

```
<ExpandableCard title="Example title" eventCategory="/route/of/page" eventName="clicked title">

Your content here

</ExpandableCard>
```

Going to close this out for now, but if you disagree and want to discuss this more @taxmeifyoucan let us know! Sorry for the slow turn around on this issue.
