### ISSUE TITLE
Support URL parameters for pre-applied filters on find wallets page

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#9209]
### Is your feature request related to a problem? Please describe.

It would be helpful for the find wallet page to support URL parameters and apply filters based on these parameters. This would allow us to link out to the find wallets page with a set of query parameters and see wallets with that filter applied.

For example, the NFT page links out to find wallets with a query parameter and this gets applied filtering down the wallets to ones that support NFTs.

### Describe the solution you'd like

Support URL parameters being passed and applying a filter on page load. 

Ex url: /wallets/find-wallet?device=mobile&buy_crypto=true

This would then apply filters for mobile and buy_crypto on page load.

### Describe alternatives you've considered

No other alternative at the moment.

**Comment by Rnamita** [comment]
I would like to take this up if it's not yet closed

**Comment by Rnamita** [comment]
thanks @corwintines for assigning it! I would be interested to know where I could find all the url parameters that have to be supported

**Comment by corwintines** [comment]
@Rnamita good starting point to see them would be `useWalletFilterSidebar.tsx`

**Comment by wackerow** [comment]
#12646 is a duplicate. Will close this one to keep more recent issue tracking.
