### ISSUE TITLE
Replace hero image on /wallets page

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#9210]
### Is your feature request related to a problem? Please describe.

The current robot hero image on the [wallets](https://ethereum.org/en/wallets) page doesn't really fit. When making the [find wallets](https://ethereum.org/en/wallets/find-wallet) page we came up with a new hero image that could be used in place of this robot.

### Describe the solution you'd like

Replace the robot hero image on the [wallets page](https://ethereum.org/en/wallets) with a new image. The image on the [find wallet page](https://ethereum.org/en/wallets/find-wallet) will work for now.

### Describe alternatives you've considered

N/A

**Comment by MukulKolpe** [comment]
Hey, @corwintines. Can I work on this issue?

**Comment by minimalsm** [comment]
Hey @MukulKolpe, you got it! 💪

**Comment by MukulKolpe** [comment]
Thank you, @minimalsm, @corwintines !!

I have raised a PR, Please let me know if any changes are required 😄
