### ISSUE TITLE
Add Multichain user persona on find wallets and multichain filter

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#9211]
### Is your feature request related to a problem? Please describe.

Given the multichain nature of the ecosystem, users may want a wallet that supports networks outside of the Ethereum ecosystem as well. Many wallets listed also already support other networks such as Bitcoin, so adding a persona around this makes sense.

### Describe the solution you'd like

Add data for multichain support to wallet data

Add filter for multichain support to find wallets

Create user persona and filter preset for multichain user

### Describe alternatives you've considered

N/A

**Comment by kevinghim** [comment]
It'd be great to show wallets that support multichain balances as well as multichain dapp connections.
