### ISSUE TITLE
Epic: hire a community lead

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#9223]
## Summary

Our current community lead (hey, that's me 😀) is transitioning to another role on the team, leaving a gap in our capacity to interact with and grow our incredible community.

As part of our Q1 roadmap (#9090), we'll be looking for a new community lead to help us engage, maintain, and grow our community. We'll release a job listing for this role in the coming weeks.

Think you are right for the role? [Apply on Lever](https://jobs.lever.co/ethereumfoundation/89ff5705-3351-422d-a5d1-b0805e95edec?lever-origin=applied&lever-source%5B%5D=GitHub).

**Comment by MrJithil** [comment]
Are we looking for a full time position?

**Comment by CamoCatX** [comment]
Would this job be permit or are they regularly planning to switch this position out?

**Comment by CamoCatX** [comment]
@MrJithil I am not part of the Ethereum team but I read the link that @minimalsm put...It says it is full time.

**Comment by minimalsm** [comment]
@MrJithil yes, it is a full-time role. Though, for exceptional candidates we may consider more flexibility.

**Comment by minimalsm** [comment]
@CamoCatX it's a permanent position 😊

**Comment by MrJithil** [comment]
> @MrJithil yes, it is a full-time role. Though, for exceptional candidates we may consider more flexibility.

Thank You.

**Comment by CamoCatX** [comment]
@minimalsm How many hours each day would this job consist of? If you don't mind me asking.

**Comment by corwintines** [comment]
Hours are pretty flexible. We have meetings that have some sync time with the team members, but outside of that whatever works best for you to get your hours in for the week.

**Comment by sleonp-dev** [comment]
Has the position been filled, the link to apply has been disabled? Thanks!

**Comment by corwintines** [comment]
@sleonp-dev we aren't accepting any more applications :)

**Comment by minimalsm** [comment]
Closing out ☺️
