### ISSUE TITLE
Ethereum forks / network upgrades timeline page

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/ethereum-org-website#923]
**Describe the solution you'd like**
Given the number of forks we had to date and that there's not a simple/straightforward way to find these informations without going into the weeds of `ethereum/pm`, AllCoreDevs chat or the crypto media, I propose the creation of a timeline of forks.

Even my (already biased) Google search does not show ethereum.org website in the first page for the "ethereum forks" term.

**Describe alternatives you've considered**

The first thing that comes to my mind was a visual timeline with:

- fork name
- fork date
- fork block
- a short description, highlighting the main reasons for it
- relevant links (meta-EIP for that HF, EF blog posts, etc…)

An initial information architecture for such page:
![Artboard](https://user-images.githubusercontent.com/47108/78722688-063b6600-78f8-11ea-8ebd-4ec113d5fce5.png)

**Additional context**

Related:
- https://www.visualcapitalist.com/mapping-major-ethereum-forks/
-

**Comment by evertonfraga** [comment]
An analogous page for the ETH 2.0 roadmap, describing the planned phases could be of great value for those coming in to learn.

**Comment by samajammin** [comment]
Thank you for this suggestion @evertonfraga! Overall, I love this idea. 

Looking quickly at search volume, there's clearly some interest in this topic. Collectively, these terms show  ~1-6K impressions per month:

![Image 2020-04-08 at 8 42 39 AM](https://user-images.githubusercontent.com/8097623/78804663-47259000-7975-11ea-8258-c8f7ab55e3c7.png)

My hunch is also that this subject is a large source of FUD that education could help address, e.g. explaining the basics of "What is a fork?", how they work & that forks aren't necessarily a bad thing but are in fact required for many software upgrades. I think a timeline that shows the history of Ethereum forks is also a valuable resource to provide.

**Comment by samajammin** [comment]
@all-contributors please add @evertonfraga for ideas

**Comment by samajammin** [comment]
A few of current top results for this topic
- https://www.etherchain.org/hardForks
- https://medium.com/xena-exchange/history-of-ethereum-hard-forks-will-istanbul-support-eth-prices-fe475c48873e
- https://consensys.net/blog/blockchain-explained/a-short-history-of-ethereum/
- https://blockchain.news/news/ethereum-the-whole-forking-history
- https://finance.yahoo.com/news/history-ethereum-forks-140004446.html

**Comment by samajammin** [comment]
@evertonfraga do you have any interest & capacity to contribute to this page? I just created an collaborative document here: https://docs.google.com/document/d/1cSKLDT3BfOzqeeIgWBJ2C4MseRe4HSerYgB1NqTJQ-o/edit

Anyone should feel free to hop in & contribute 😄

**Comment by evertonfraga** [comment]
@samajammin I don't have capacity to fully engage here at least til the end of Q2. I already have a stack of web projects under my watch, plus my EthereumJS assignments.

**Comment by samajammin** [comment]
@evertonfraga totally understandable! Thanks for the update. I'll look into getting resources on this.

**Comment by marcgarreau** [comment]
Just went googling for these names; an updated list is surprisingly hard to find, e.g., most of the links @samajammin posted haven't been updated to include Muir Glacier. Ended up getting what I needed from a [geth test file](https://github.com/ethereum/go-ethereum/blob/master/core/forkid/forkid_test.go). 😅

+1 for even a simple list of this history on the official website.

**Comment by samajammin** [comment]
Another useful page for fork status: https://forkmon.ethdevops.io/

**Comment by samajammin** [comment]
Solved in #2078 🎉

**Comment by samajammin** [comment]
@evertonfraga better late than never: https://ethereum.org/en/history/

Thanks to @ryancreatescopy for pulling this together.
