### ISSUE TITLE
Polygon Hermez no longer exists and link is non-functional, should be renamed to Polygon zkEVM

### ISSUE THREAD

**Issue by mangoquarterzip** [ethereum/ethereum-org-website#9263]
### Describe the bug

https://ethereum.org/en/developers/docs/scaling/zk-rollups/

links to https://docs.hermez.io/zkEVM/architecture/introduction/

which no longer exists

### To reproduce

1.Go to https://ethereum.org/en/developers/docs/scaling/zk-rollups/
2.Scroll to the bottom at "who is working on a zkEVM"

### Expected behavior

Should be linked to https://polygon.technology/solutions/polygon-zkevm

Description should be changed to :

Polygon zkEVM is a decentralized ZK Rollup on the Ethereum mainnet working on a zero-knowledge Ethereum Virtual Machine (zkEVM) that executes Ethereum transactions in a transparent way, including smart contracts with zero-knowledge-proof validations.

### Screenshots

<img width="729" alt="Screenshot 2023-01-23 at 00 50 12" src="https://user-images.githubusercontent.com/108644014/213949810-b0722a90-c9c4-414d-8232-17f7140596f8.png">

**Comment by mesquitaoliveira** [comment]
@mangoquarterzip The bug is solved:

[Deploy preview](https://ethereumorgwebsitedev01-mesquitaoliveiraethereumorgweb.gatsbyjs.io/en/developers/docs/scaling/zk-rollups)
## Screenshots:
![image](https://i.imgur.com/L1Kx7oh.png)
