### ISSUE TITLE
Navbar close button visible when opening the Search bar in smaller screen.

### ISSUE THREAD

**Issue by amit-ksh** [ethereum/ethereum-org-website#9275]
### Describe the bug

A non-working navbar close button is visible when the Search bar opened on a smaller screen.

### To reproduce

1. Open any page of **ethereum.org** with a screen width of less than 1000px 
2. Click on the Search bar
3. Click the close button on the top-left of the page
4. See the error

### Expected behavior

Navbar close button should not be visible.

### Screenshots

[Home _ ethereum.org.webm](https://user-images.githubusercontent.com/91947037/214236004-c47f409d-4d1c-4c0f-8776-1aa1d25489b4.webm)

### Desktop (please complete the following information)

OS: Windows 10
Browser: Brave

**Comment by rohitguptaa22** [comment]
Hi team ,
Please assign this issue to me I resolve this issue.

**Comment by rohitguptaa22** [comment]
@corwintines merged a PR for this issue, kindly check.

**Comment by corwintines** [comment]
Closing this as it was merged
