### ISSUE TITLE
Preparing UI for the Launch of StakeWise V3 

### ISSUE THREAD

**Issue by Jstar101** [ethereum/ethereum-org-website#9277]
### Is your feature request related to a problem? Please describe.

This request is not related to a problem but is instead aimed at highlighting several areas where the website UI could be updated to accommodate for StakeWise V3. For context, StakeWise V3 will introduce a brand-new model for liquid staking with the goal of maximising the health of the Beacon Chain through the decentralisation of staked ETH. It will be a highly flexible protocol offering benefits to many users, but most notably solo stakers, who will be able to access a liquid staking token whilst staking on their own node. 

StakeWise V3 development was [announced in September 2022](https://stakewise.medium.com/stakewise-v3-announcement-9e4fe73abdf2), the testnet is expected to go live in the coming weeks with the aim for a full Mainnet launch late Q1/early Q2. More information about V3 can be found in the [litepaper](https://stakewise.io/stakewise-v3.pdf).

Given the strong alignment of values between V3, Ethereum.org and the ecosystem as a whole, I hope to discuss the below suggested UI updates with the aim strike the balance between highlighting an important new protocol for the network whilst ensuring Ethereum.org remains a neutral party.

### Describe the solution you'd like

**Suggestion 1:**
_Page ref: https://ethereum.org/en/staking/_

Update the wording to highlight the ability to solo stake with less than 32 ETH, but mention the need to receive delegations from others. It is important to keep this section concise, however, explicitly requiring 32 ETH risks deterring would-be solo stakers. V3, Rocket Pool, and the introduction of technologies such as DVT, will reduce the 32 ETH hurdle for people to start solo staking.

![image](https://user-images.githubusercontent.com/106162669/214276318-8581fd92-f737-4e91-886a-2752c904be39.png)

** **
**Suggestion 2:**
_Page ref: https://ethereum.org/en/staking/_

Update the comparisons to highlight that liquidity tokens can be available to solo stakers, not only those of pooled staking services.

![image](https://user-images.githubusercontent.com/106162669/214280910-26375068-6714-4298-9bad-1437213a1635.png)

** **
**Suggestion 3:**
_Page ref: https://ethereum.org/en/staking/solo/_

Highlight the ability to liquid stake under the header "Why Solo?" and link to the StakeWise Liquid Solo Staking Guide. Liquid staking is evidently very popular, however, currently, there is a trade-off between decentralisation and liquid staking. V3 will solve this and it is important to show those who want to liquid stake that they can actually do so on their own node. 

![image](https://user-images.githubusercontent.com/106162669/214278808-1499030c-3070-44e6-9f8c-c2f2615cf75a.png)

** **
**Suggestion 4:**
_Page ref: https://ethereum.org/en/staking/solo/_

Add the StakeWise Operator software to the Node Tools section:

![image](https://user-images.githubusercontent.com/106162669/214279537-0ac333ed-c840-4a48-93e1-e62b5f92db32.png)

** **
**Suggestion 5:**
_Page ref: https://ethereum.org/en/staking/solo/_

Add the StakeWise "Liquid Staking for Solo Stakers Guide" to the guides section:

![image](https://user-images.githubusercontent.com/106162669/214279596-d6aa936d-115e-4774-b6c5-40922637130a.png)

** **
**Suggestion 6:**
_Page ref: https://ethereum.org/en/staking/pools/_

Update the wording on the "Why stake with a pool?" section to highlight that pooled staking is not the only way to liquid stake. If users find liquid staking attractive, they should explore whether they can do so as a solo staker first, then revert to pooled staking if that best suits their needs. 

![image](https://user-images.githubusercontent.com/106162669/214279926-f4b57178-5c1c-491c-8482-b3ebcc609236.png)

** **
**Suggestion 7:**
_Page ref: https://ethereum.org/en/staking/pools/_

Update the StakeWise permissionless checkmark to a green tick.

![image](https://user-images.githubusercontent.com/106162669/214280670-03e8b417-03b9-4d97-a654-35bbe02594bb.png)

### Describe alternatives you've considered

**Suggestion 8:**

There is scope for solo stakers to get involved with StakeWise V3 during the upcoming testnet. Is there an appetite to add the above suggestions to the Solo Staking page and highlight the ability to participate in the network's testnet ahead of the Mainnet launch?

### Additional context

The StakeWise team will submit the necessary PR requests once there has been sufficient time for the Ethereum.org community to discuss the above suggestions.

**Comment by wackerow** [comment]
Hey @Jstar101! Sorry for the delay getting back to you on this... Appreciate you laying all of your suggestions out and your reasoning. Let's unpack...

**Suggestion 1: <32 options for "solo"**
I tend to agree with the sentiment here that we don't want to push away folks who may otherwise run nodes because they don't have 32 ETH.

This makes me wonder if this would warrant a slightly larger rebrand, perhaps converting "solo staking" to "home staking". 

In either case, given we do list Rocket Pool as an option under "solo" even though it is obviously designed to accommodate <32 ETH, I think it's reasonable to update this section to note that there are alternative ways to "stake from home" (or however we want to phrase this to imply running a node) that have lower ETH requirements. 

**Suggestion 2: LSDs for solo as well**
How many other examples are there of users being able to "mint their own LSD"? I know with Rocket Pool you end up minting rETH, and StakeWise V3 aims to provide this, but V3 is also quite new and not yet to Mainnet.

Just trying to get an idea of what's out there, but overall I think this is still reasonable. We already have Rocket Pool listed under the solo page, and I think this can help remind people that this is an option if you're staking from home.

And yeah, similar to above, I feel like this is pushing the bounds of the "solo" meme, and perhaps warrants us renaming that. "Home stakers" is probably more appropriate.

**Suggestion 3: Update Why section and link to StakeWise guide**
I don't think I'm in favor of linking out to a StakeWise guide at this section of the page, but we could certainly drop it below.

As for updating the sections, **curious what others think**... I'm hesitant to change what is there, especially given the nascency of this technology still. 

**Suggestion 4: Add StakeWise Operator to Node Tool**
💯... once it's live on Mainnet =)

**Suggestion 5: Add guide**
This works with me!

**Suggestion 6: Suggest solo for LSDs on pools page**
I think this shines more light of the challenges with categorizing all of these things. Again I think if we update the "solo" section to be something like "home staking" much of this ends up making more sense. 

If we go through with something like that, then yeah I think this update would make more sense, to remind users to check out "home staking" LSD options first... either here, or maybe in the Comparison table.

**Suggestion 7: Permissionless nodes**
💯! Again, once live on Mainnet.

**Suggestion 8: Testnet involvement**
As you've probably notice we're not really set up currently for testnet tooling. There was similar discussion surrounding distributed validator tech, where we currently do not have a place to list tools only available on the testnet.  Also making sure the platform stays objective and as neutral as possible... this could open the doors for a lot of others who want their testnet projects listed in the same way. 

---

Curious what others think about potentially rebranding "solo" to "home" to make room for what is described here? I'm in the camp that we want to encourage more people to run nodes and participate in the actual infrastructure of Ethereum. Trustless and permissionless mechanisms to achieve this I think we should make room for, and I think using the term "home staking" helps us move past the 32 ETH hurdle a bit and encourage more people to stake from home.

**Comment by corwintines** [comment]
Hey @Jstar101! Apologies for the late response here. Appreciate the thoughtful issue that you have opened. Lots of good suggestions here, so ill leave my thoughts as well

---

**Suggestion 1: <32 ETH staking**
Agree with the change to not explicitly say you need 32 ETH here. Given changes to the staking landscape that allows for pooled staking and DVT, it makes sense to discuss these options here as well. 

@wackerow I agree, we could drop the "solo" portion here and change it to "Home staking". 

It does make me wonder if we want to add a badge or something to highlight the difference between these different options. 

**Suggestion 2: LSD**
Same questions as @wackerow, but seems like an overall improvement and something that should be included.

**Suggestion 3: LSD in why solo stake**
For me, I don't think this is necessary. It's a tool that solo stakers can have now, but I don't think it is a reason why someone should solo stake. 

**Suggestion 4: StakeWise in Node Tools**
Agree, but once live :)

**Suggestion 5: solo staking guides**
Support this.

**Suggestion 6: why stake with a pool**
Given the other suggestions this makes sense. Share @wackerow concerns. I am curious what you think could replace this as well.

**Suggestion 7**
Agree, once live :)

**Suggestion 8: highlight testnet participation**
I like the idea overall, but I do wonder if this conflicts with the UX of the page. @konopkja do you have any insight on this suggestion?

---

Overall, agree with most changes on this. 

Appreciate the StakeWise team looking to contribute to this as well. I'll get action items for this sorted out by next week, and then what would be the best way of moving forward with this for you @Jstar101?

Thanks again!

**Comment by Jstar101** [comment]
@wackerow , @corwintines - many thanks for your responses! 

**Suggestion 1: <32 ETH staking**
Great to see agreement on this point! I wonder if the best way to go about this would be to tweak the wording slightly to remove the "should have at least 32 ETH" and then have a specific subsection on the [Solo staking page](https://ethereum.org/en/staking/solo/) where it tackles the topic of <32 ETH staking? This way anyone who doesn't have 32 ETH is not instantly deterred from the Solo staking option and they can specifically learn about <32 ETH staking on the next page. 

I do agree that this could warrant a re-brand away from 'Solo' staking towards 'Home' staking.

**Suggestion 2: LSD**
Yeah so this one is interesting because whilst RPL is a liquid staking protocol, it is not liquid staking for the node operators (i.e. they cannot mint rETH as their capital is purely used as collateral). This will be something unique to V3 where an operator can stake on their own node and mint an LSD against their own staked capital. The rationale for this change it to again try to encourage solo/home staking and show that even if you want to 'liquid stake', you will be able to do that on your own node.

**Suggestion 3: LSD in why solo stake**
I hear you here. It is closely related to the above suggestion where it would be unique to StakeWise and I fully appreciate it is not ideal to single out one protocol here. I do think though that liquid staking is an important narrative right now and that the ability to do so on your own node could really make the difference between someone home staking vs not. How about not linking to anything specific on StakeWise here? I still think mentioning the ability to liquid stake solo would be a worthwhile benefit to include - that might be a good middle ground. 

**Suggestions 4, 5 and 7**
Awesome, the ball is very much in our court here and I will let you know when we have the material/software ready to display on these pages. 

**Suggestion 6: why stake with a pool**
Yeah, this one is interesting. I think the main issue is with the wording of "staking with a pool comes with a number of **distinct** benefits". Once V3 is live, this will not be strictly true. Having said that, if the other changes are made, then this section is not too problematic as a user would have likely already seen that you can liquid solo stake if they want to. And not to mention that liquid staking is still a key benefit of using a pooled solution. In hindsight, I think this could stay as is.

**Suggestion 8: highlight testnet participation**
Fully agree with your comments and it is certainly a change I wouldn't expect for just StakeWise V3 alone. Maybe there is a rationale to have a testnets section which includes key upcoming tech like DVTs. This would help the site remain more neutral as it highlights a wider range of testnets. Agree this would be a much larger scope of work though than all the above suggestions and isn't necessarily a high priority. Food for thought though :)

---

@corwintines - that sounds great re next steps. Just let us know how we can assist with anything here. I believe the majority of the changes are technically simple, it is just important that everyone is happy with the change of narrative that comes with these changes :)

**Comment by wackerow** [comment]
> Suggestion 1: <32 ETH staking

Seems like we're forming consensus.

- Update to "Home staking"
- Add section about <32 ETH options
- Continue to emphasize node operation from home

- Add indicator to products that support liquid staking options

> Suggestion 2: LSD
> Yeah so this one is interesting because whilst RPL is a liquid staking protocol, it is not liquid staking for the node operators (i.e. they cannot mint rETH as their capital is purely used as collateral). 

Forgive my ignorance, do Rocket Pool node operators who deposit 16 ETH not get rETH in return?

In either case, sounds like with the above changes, we could add an indicator that signals which projects enable minting a token representative of the ETH staked.

> Suggestion 3: "Why stake solo?"

I think given the above discussion, would consider looking at this one from the lens of an updated "Why stake from home?" section. I see this as a section that should be about the direct benefits of home/solo staking. I'm not sure I'm sold that "the ability to liquid stake" is a direct reason why someone should run a home setup... you can also liquid stake without operating any hardware.

> Suggestion 6: Suggest solo for LSDs on pools page
> In hindsight, I think this could stay as is.

I think if we switch to "Home staking", we could potentially tweak the wording on the `/pools` "Why" copy to just suggest that this is possible from home as well.

> Suggestion 8: Testnet tool listing

@konopkja Would be curious your input. Overall given the challenges in maintaining these product listings, and the overall direction so far to avoid beta/pre-production products, I'm not sure a page like this would be the most appropriate for these tools. I think personally I'd be more in favor of waiting until products are in production / on Mainnet.

But as always, welcome thoughts from others. Should we try to provide space for people to learn about what is coming, and to be directed to ways to test things out?

> Suggestion 4, 5, 7: 💯

**Comment by Jstar101** [comment]
Awesome guys, I think we're pretty much aligned on everything! 

What is important is that we try to remove the current distinction between 'home staking' and 'liquid staking' as they will no longer be separate things. We want to mitigate the situation where someone decides not to stake from home because they think they can't access a liquid staking token. Both suggestions 2, 3 and 6 are aiming to achieve this, although for suggestion 3 specifically, I do agree that it would not be a 'direct benefit' of solo staking and so it might not be suitable to mention liquid staking here.

> > 
> Forgive my ignorance, do Rocket Pool node operators who deposit 16 ETH not get rETH in return?

No, node operator's capital is not made liquid/tokenised.

**Comment by Jstar101** [comment]
Hey hey - looking to bring this thread back to life following the launch of StakeWise V3! Conscious that I raised a lot of suggestions in my initial post, but it feels like we found consensus on most points in the above discussions. 

To recap:

**Suggestion 1: <32 ETH staking**
- Re-brand away from 'Solo' staking towards 'Home' staking.
- Add section about <32 ETH options
- Continue to emphasize node operation from home
- Add indicator to products that support liquid staking options

**Suggestion 2: LSD**
Highlight that liquid staking IS available for solo/home stakers. You no longer have to go down the pooled staking route in order to access DeFi with staked capital. For example, on StakeWise V3 you can set up a private staking pool where you are the only operator, stake onto your node and be able to mint osETH against it to access/farm DeFi.

**Suggestion 3: LSD in why solo stake**
The idea behind this change was to make sure that if someone wanted to liquid stake, they would not be turned away from solo/home staking. I do agree that this is not an explicit reason to solo stake though so it might be difficult to add a liquid token section here. Maybe suggestion 2 is enough to tackle this.

**Suggestion 4: Add StakeWise Operator Service to Node Tools**
This one is pretty straightforward. I would appreciate some guidance on the individual flags here though - are they related to the staking protocol itself or the node tool? If it is the staking protocol, then I believe all flags should be ticked green as per the Rocket Pool section. Regarding the min stake amount, it should be "No minimum" for StakeWise Operator. Regarding the "Get Started" button, it should link to [this page](https://docs.stakewise.io/guides/running-a-vault).

**Suggestion 5: solo staking guides**
Please link to [this page](https://docs.stakewise.io/guides/running-a-vault) with the guide titled "Liquid Solo Staking". We are planning to create more liquid solo staker-specific guides, but this documentation would be great to start with.

**Suggestion 6: why stake with a pool**
This one is a little tricky I agree. Might be worth just dropping this for now. I would just hate for someone to assume that staking with a pool is the only way to liquid stake. Maybe remove the word 'distinct' from the short summary to try to stop this from happening.

**Suggestion 7: Permissionless nodes**
It's been a long time coming, but we can now turn the Permissionless Nodes section on the StakeWise section under staking pools to green!

**Comment by wackerow** [comment]
I've opened a new issue, #13134, summarizing the key items from this discussion. Going to close this thread out to try and re-center latest discussion in the new thread. If I've missed anything with that issue please feel free to surface with a new issue.
