### ISSUE TITLE
Typo in Bug Bounty Program

### ISSUE THREAD

**Issue by hursittarcan** [ethereum/ethereum-org-website#9286]
### Description

"Earn up to $250,000 USD and a place on the leaderboard by finding protocol, client and Solidity bugs affecting the Ethereum network.". 

Link: https://ethereum.org/en/bug-bounty/

I might be wrong, but why do we use both $ and USD? Isn't it enough to use just one of them? 

### To reproduce

/ 

### Expected behavior

/

### Screenshots

![image](https://user-images.githubusercontent.com/75273616/214391118-81fad67d-9e7b-4295-a9bf-8a986169c790.png)

**Comment by raynemang** [comment]
I suspect it's for congruency. And to prevent misinterpretation of the prize amount. 

For example, people could assume it's CAD, NZD or AUD because they share the $ symbol.

**Comment by hursittarcan** [comment]
> I suspect it's for congruency. And to prevent misinterpretation of the prize amount.
> 
> For example, people could assume it's CAD, NZD or AUD because they share the $ symbol.

Wouldn't it then be better to use USD only? Me, being from Europe got confused by this, I thought it was a mistake.

**Comment by raynemang** [comment]
That's a fair view for sure.

I'm guessing the primary reason is to avoid confusion by stating it's a dollar amount and not a token amount and it's valued in USD.

**Comment by rohitguptaa22** [comment]
Hi team,
Please assign this issue to me. I want to start contributing to openSource but there is no good beginner-friendly issue.
I will remove the USD from the text.?

**Comment by vishal590** [comment]
hi team, assign this task to me. I will fix it.

**Comment by corwintines** [comment]
@konopkja any opinion on this?

I think it's fine as it is, but wanted to check from your UX perspective.

**Comment by konopkja** [comment]
> @konopkja any opinion on this?
> 
> I think it's fine as it is, but wanted to check from your UX perspective.

"USD" is clearer than "$"  so i would keep "USD" and remove the dollar sign, but overall agree both are not needed.
