### ISSUE TITLE
Listing policy links to GH issue templates are broken

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#9291]
### Describe the bug

Looks like since we updated our GH issue templates to yml files, we broke all the links on our listing policy page.

e.g. see https://github.com/ethereum/ethereum-org-website/pull/9289

I spot checked a couple others that are also broken. We should check all listing policies & update them if needed.

### To reproduce

1. Go to https://ethereum.org/en/contributing/
2. Click on a listing policy, e.g. https://ethereum.org/en/contributing/adding-developer-tools/
3. Click on "create issue" button
4. See error - it should open an issue template vs. a blank issue

### Expected behavior

Links should lead to our custom issue templates, no a blank issue

### Screenshots

See https://github.com/ethereum/ethereum-org-website/pull/9289

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by MukulKolpe** [comment]
Hey @samajammin, can I work on this issue?

**Comment by MukulKolpe** [comment]
@corwintines Yess!!

**Comment by corwintines** [comment]
@MukulKolpe sounds good. Let me know if you have any questions :) Assigning to you.
