### ISSUE TITLE
adding a expressive hover effect to the footer icons of the home page

### ISSUE THREAD

**Issue by Jayaditya-Contributor** [ethereum/ethereum-org-website#9293]
### Is your feature request related to a problem? Please describe.

The footer icons of the home page felt more like an image instead an expressive link

### Describe the solution you'd like

by adding expressive hover effect to the icons makes the user understand , it's more than a ordinary icon.

### Describe alternatives you've considered

I do not have any alternatives.

**Comment by Imimi111** [comment]
Leave a comment

**Comment by corwintines** [comment]
Hey @Jayaditya-Contributor. Do you mind expanding on this a bit?

**Comment by MahendraBishnoi29** [comment]
> Hey @Jayaditya-Contributor. Do you mind expanding on this a bit?

@corwintines he's talking about these footer links. I think there should be a hover effect on these logos 

![Screenshot 2023-01-26 170212_LI](https://user-images.githubusercontent.com/74294202/214826043-2f12d926-7f6d-4a66-95ea-0676e3803449.jpg)

**Comment by rohitguptaa22** [comment]
Hi team ,
Please assign this issue to me. I will work on it
