### ISSUE TITLE
New glossary terms for better data comparison: DAA, DTC, DNA, TUA

### ISSUE THREAD

**Issue by MSeidl-Analytics** [ethereum/ethereum-org-website#9314]
Glossary term proposals

Blockchains have a number of main metrics that can be analyzed. Daily Transaction Count, Daily Active Addresses, New Addresses Per Day, Total unique addresses.

For the sake of making the comparison between EVM blockchains easier, I propose to include the following terms in the glossary:

**Daily Active Addresses (DAA):** Number of distinct Ethereum addresses (https://ethereum.org/en/glossary/#address) that sent a transaction on a given date. Note that this only includes sender addresses, not receivers, since receiver addresses are considered passive addresses.

**Daily Transaction Count (DTC):** Number of daily transactions (https://ethereum.org/en/glossary/#transaction). Can also be defined as the number of unique transaction ids per day.

**Daily New Addresses (DNA):** Number of distinct Ethereum addresses (https://ethereum.org/en/glossary/#address) that recorded their first-ever transaction (https://ethereum.org/en/glossary/#transaction) on a given date. The first-ever transaction is usually a transaction where an address receives funds as a receiver in a transaction.

**Total Unique Addresses (TUA)**: The total number of distinct Ethereum addresses (https://ethereum.org/en/glossary/#address) that ever appeared in a transaction (https://ethereum.org/en/glossary/#transaction). This can also be expressed as the cumulative value of "Daily New Addresses" (link to the term above).

**Comment by MukulKolpe** [comment]
Hey @corwintines, can I work on this issue?

**Comment by corwintines** [comment]
Thanks for the suggestions @MSeidl-Analytics, and thank you offering to pick this up @MukulKolpe. 

These terms are pretty self explanatory, quite niche to investing or articles that are covering topics on them, and we don't use these terms anywhere on ethereum.org. For these reasons, I don't think we need to add these terms, and going to close the issue. Feel free to reopen if you disagree, and let us know why.

Thanks again!
