### ISSUE TITLE
Suggest a dapp: CoinBrain

### ISSUE THREAD

**Issue by michallangmajer** [ethereum/ethereum-org-website#9316]
**Name**
CoinBrain

**Website**
https://coinbrain.com

**Description**
CoinBrain is a crypto analytics platform that combines on-chain and off-chain data to provide traders with the insights they need to make informed decisions.

**Logo**
<img width="300" alt="Slack Profile Picture" src="https://user-images.githubusercontent.com/74111834/214864209-ed12ce76-172b-4981-8619-4669fbf8d7ba.png">

**Comment by corwintines** [comment]
Hey @michallangmajer,

Can you reopen this issue using this template: https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&template=suggest_dapp.yaml&title=Suggest+a+dapp

Thanks
