### ISSUE TITLE
Suggest a developer tool: Substreams

### ISSUE THREAD

**Issue by alex-pakalniskis** [ethereum/ethereum-org-website#9318]
### Dev tool name

Substreams

### Dev tool description

parallelized blockchain data indexing technology

### When did the dev tool go live?

June 2022

### Where do you think this page should be shown?

https://ethereum.org/en/developers/docs/programming-languages/rust/#rust-projects-and-tools

### Is the product open source?

Yes

### GitHub URL

https://github.com/streamingfast/substreams

### Documentation URL

https://substreams.streamingfast.io/

### Additional context

Built by StreamingFast, a core developer working on The Graph protocol

**Comment by alex-pakalniskis** [comment]
Happy to help out and update the docs with this info.

**Comment by corwintines** [comment]
Hey @alex-pakalniskis

Sounds good to me! Would you like me to assign this to you?

**Comment by alex-pakalniskis** [comment]
@corwintines yes please. Thanks :smile:

**Comment by corwintines** [comment]
Great, assigned to you @alex-pakalniskis :)
