### ISSUE TITLE
Upgrade Storybook to v7 and Component Story Format to v3

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-website#9323]
_The following description and details is related to these upgrades as of `v7.0.0-beta.35` of Storybook and subject to updates and changes post preliminary findings._

## Overview
This issue is to track discussion in upgrading Storybook to v7 and the Story Component formatting to v3. This may be to resolve with a PR immediately, or to be kept as record for implementation at a later time.

## Setup

The following steps can be taken (in order):
1. Run `npx storybook@next upgrade --prerelease`, and select `yes` to all prompts
    - Run `storybook-binary` migration which adds `storybook` as a dev dependency. (Different than `@storybook/*`)
    - Run `sb-scripts` to update the build and dev scripts for Storybook
    - Run `newFrameworks` to replace storybook webpack deps
    - Run `autodocsTrue` to opt in on having autodocs generated for every story.
    - Run `missing-babelrc` to add a babel config as the settings in SB are no longer out of the box, and now looks at a project's config.
2. The final request to add babel config has its own prompts which can be given a yes to each along with installation of `@babel/preset-env`
    - Installation of `@babel/preset-typescript`
    - Installation of `@babel/preset-react`
3. With No. 1, the `main.js` file in `.storybook` will be updated. Additional changes need to happen manually.
    - The `webpack` option will need to be removed as it breaks compiling and also does not appear to be needed.
    - Under the `features` option, `emotionAlias` is no longer needed
4. Run `npx storybook@next migrate csf-2-to-3 --glob="**/*.stories.tsx"` to update the current story files to CSF3

## Component Story Format 3
In essence, this new version allows for each story to be an object.

For example, a story from [Button.stories.tsx](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Button/Button.stories.tsx) will go from this:
```tsx
const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />

export const Solid = Template.bind({})
Solid.args = {
  children: "What is Ethereum?",
}
```
to this:
```tsx
// No Template!
export const Solid: StoryObj<typeof Button> = {
  args: {
    children: "What is Ethereum?",
  },
}
```
Or with [Card.stories.tsx](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Card/Card.stories.tsx):
```tsx
const defaultProps: IProps = {
  emoji: ":woman_student:",
  title: "Learn Ethereum development",
  description: "Read up on core concepts and the Ethereum stack with our docs",
}

export const Default: ComponentStory<typeof Card> = (args) => (
  <Card {...defaultProps} {...args}>
    <Button>Read the docs</Button>
  </Card >
)
```
to this:
```tsx
const defaultProps: IProps = {
  emoji: ":woman_student:",
  title: "Learn Ethereum development",
  description: "Read up on core concepts and the Ethereum stack with our docs",
}

export const Default: StoryObj<typeof Card> = {
  render: (args) => (
    <Card {...defaultProps} {...args}>
      <Button>Read the docs</Button>
    </Card>
  ),
}
```
> NOTE: the `.tsx` file extension is still needed for these files to be rendered.

## Any Caveats/Blockers?
- There are currently no known blockers. However Storybook v7 is still currently in beta.
- Chakra UI's plugin looks to be working as expected.
- With the addition of a `.babelrc.json`, the spin-up of the Gatsby dev server looks to be working as expected, but warning stacks do appear in the terminal. Additional configuration may be needed?

## Resources
- See this notion docs to [Storybook 7 migration guide](https://chromatic-ui.notion.site/Storybook-7-migration-guide-dbf41fa347304eb2a5e9c69b34503937)
- See the blog on [Component Story Format 3](https://storybook.js.org/blog/storybook-csf3-is-here/)
- There is a comprehensive [Migration docs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#start-storybook--build-storybook-binaries-removed)

**Comment by MrJithil** [comment]
Working on it.

**Comment by MrJithil** [comment]
PR Ready. #9324 

@TylerAPfledderer

**Comment by TylerAPfledderer** [comment]
Dependency bump available to [improve type safety](https://storybook.js.org/blog/improved-type-safety-in-storybook-7/) with CSF3

**Comment by pettinarip** [comment]
Thanks @TylerAPfledderer for all the details you put here.

I agree! lets bump it.

**Comment by pettinarip** [comment]
Completed on #9324
