### ISSUE TITLE
Suggestion: add p2p.org Ethereum staking as a service

### ISSUE THREAD

**Issue by rgb2hsl** [ethereum/ethereum-org-website#9326]
## Pull-request https://github.com/ethereum/ethereum-org-website/pull/9329

[P2P](https://p2p.org/) provides secure non-custodial [staking service](https://p2p.org/faq/en/articles/5280324-what-is-staking), allowing token holders to participate in staking without running necessary tech infrastructure by themselves.

Since Merge we providing non-custodial native Ethereum staking as a service. All the details and info can be found [at the corresponding landing page](https://p2p.org/networks/ethereum-staking-service)

The Ethereum staking service is currently running in semi-manual mode on our end. We plan to upgrade it to a Shanghai upgrade with a fully automated flow.

We're looking forward to be listed as a staking provider on ["Staking as a service" page](https://ethereum.org/en/staking/saas/)

We provided all the necessary info below.

## Summary

Our smart contracts are **open source** ([link 1](https://github.com/p2p-org/p2p-eth2-depositor) and [link 2](https://github.com/p2p-org/eth-staking-fee-distributor-contracts)). Other software are not.

Here you can see the [smart contract external audit report](https://p2p.org/networks/ethereum/staking/audit.pdf).

We do not have a bug bounty.

[We are actively accepting stake](https://www.rated.network/o/P2P.ORG%20-%20P2P%20Validator%20-%20Lido?network=mainnet&view=poolShare).

We do not require KYC. If a user works with our Ethereum Staking Service, they do not need to go through KYC because their assets do not get to our account and are sent directly to the Ethereum network.

As for the client diversity, we have 3 CL types: Prysm, Lighthouse and Teku.

Self custody. User withdraws and receives rewards [in their personal wallet](https://p2p.org/networks/ethereum/staking-application). We do not have access to it and do not know the seed phrase.

### First, which category of product or service is it?

Staking as a service (SaaS).

### When was the project or service launched?

P2P stake in mainnet and runs validators since the middle of December 2020.

Since September 2022 P2P accepts staking requests from [p2p.org](http://p2p.org/) website. [The first stake](https://beaconcha.in/validator/9097e1d6fa353f89beaf930d55cbde06bf832375643f0c94c3ad275a06932f7997f458e336e812624e9555192b97aa05#deposits) from the website took place in November 1, 2022.

### Is the project being actively maintained?

Yes, the project is actively supported. We add a new stake almost every day. Here is [a link](https://beaconcha.in/validator/502687) to the latest stake.

### Is the product or service free of trusted/human intermediaries?

Yes, it’s free from trusted/human intermediaries. We are non-custodial and don’t have access to withdrawal credential. And from perspective of signing keys no one in [P2P](http://p2p.org/) have access to whole key. Each key is split 2-of-3 Threshold schema, and each part is completely isolated from each other (no one in our team has access to the whole key and keys are stored separately in infrastructure repositories)

Regarding the fee distribution we also don’t have any trusted/human intermediaries. We use immutable [audited smart contract](https://p2p.org/networks/ethereum/staking/audit.pdf), which collects execution rewards and sends to client after charging P2P service fee.

### What platforms are supported?

Web. Any desktop platform that has a Browser app compatible with certain wallets. Chrome on any Desktop OS is ideal prior to both MetaMask extension and Ledger WEB HID/USB connectivity.

### Is everything open source?

Our smart contracts involved in staking service is open source.

- P2pEth2Depositor: [Etherscan](https://etherscan.io/address/0x4ca21e4d3a86e7399698f88686f5596dbe74adeb#code), [GitHub](https://github.com/p2p-org/p2p-eth2-depositor)
- FeeDistributorFactory [on Etherscan](https://etherscan.io/address/0xd875e7e690dcb00997b0247022f87dedb40176e4#code), FeeDistributor (template) [on Etherscan](https://etherscan.io/address/0xf4e8ac9a2f2c563e8e3729ee5aa5f1d7e5d02c6a#code), [both on GitHub](https://github.com/p2p-org/eth-staking-fee-distributor-contracts)

The frontend and the backend of the service are not open source.

### Is the product out of *beta* development?

We are not in beta - we are in *general availability* i.e. we are actively [accepting](https://www.rated.network/o/P2P.ORG%20-%20P2P%20Validator%20-%20Lido?network=mainnet&view=poolShare) stake and fully [responsible](https://p2p.org/terms-of-use) for it (In our offer we offer the client slashing protection and slashing insurance from [RELM](https://www.relminsurance.com/) and [Nexus Mutual](https://nexusmutual.io/))

### Has the software undergone an external security audit?

Our smart contracts have been independently audited externally. [Here's link to the report](https://p2p.org/networks/ethereum/staking/audit.pdf).

Our frontend and backend have not.

### Does the project have a bug bounty program?

We do not have Bug Bounty.

### What are the fees associated with using the service?

[P2P](http://p2p.org/) charges service fee in according with [term of services](https://p2p.org/networks/ethereum/staking-application/terms) as % of execution layer rewards generated by client’s validators. We use immutable audited smart contract, which collects execution rewards and sends to client after charging P2P service fee.

### Are users required to sign-up for an account?

No, if a user works with our Ethereum Staking Service, they do not need to go through KYC because their assets do not get to our account and are sent directly to the Ethereum network.

### Who holds the signing keys, and withdrawal keys?

Withdrawal keys are controlled by the client and only by them. They don't transfer them to us, only ETH address for generating deposit data with this address as a withdrawal address.
Signing keys are generated by our side, we control them and we use them for running validator.

### What is the client diversity of the nodes being operated?

We use vouch as a validator client, so it supports different CLs at the same time. Currently, we use simultaneously 3 CL types: Prysm, Lighthouse and Teku. One validator is connected to two of them (mixed: Lighthouse + Teku or Prysm + Teku) simultaneously. Prysm is the majority client and we run overall 25% of our validators with it.

### What user interfaces are supported?

As we mentioned above — any Web Browsers, compatible with corresponding wallets.

### For SaaS, how many validators are currently being operated by the service?

Currently it is [7391 validators](https://www.rated.network/o/P2P.ORG%20-%20P2P%20Validator%20-%20Lido?network=mainnet&view=poolShare).

**Comment by rgb2hsl** [comment]
We will soon provide the PR with related changes

**Comment by rgb2hsl** [comment]
We are still a bit concerned about he launch date. P2P runs mainnet validators continuously since December 2020 and validators infrastructure is battle-tested since then. But today we are offers to our clients to stake via freshly deployed (with audit) contracts. Can we mark December 2020 as our launch date, or it must be September 2022?

**Comment by corwintines** [comment]
@wackerow do you mind taking a look at this?

**Comment by wackerow** [comment]
(Left reply in [PR 9329 here](https://github.com/ethereum/ethereum-org-website/pull/9329#pullrequestreview-1341661134))

**Comment by minimalsm** [comment]
Closing as per #9329
