### ISSUE TITLE
Bug report: inconsistent UI color 

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9327]
### Describe the bug

The website active state for toggle uses primary color plus black in dark mode.

active state for checkbox uses primary color + white in dark mode.

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on "feature filters"
2. Click on "mobile device"

### Expected behavior

The expected result is for the checkbox to use black color for ticked checkbox.

### Screenshots

<img width="92" alt="Screenshot_2023-01-26_at_18 51 10" src="https://user-images.githubusercontent.com/100724231/215081355-6dedea0a-e35a-4229-ba8e-a7a7126e8efb.png">

**Comment by MrJithil** [comment]
Fixing on #9357
