### ISSUE TITLE
Suggest a wallet: Bitizen Wallet

### ISSUE THREAD

**Issue by ermakovventures** [ethereum/ethereum-org-website#9338]
### Wallet name

Bitizen Wallet

### Wallet description

Bitizen is an MPC-based, non-custodial, privacy-safe and censorship-resistant multichain wallet with no private keys and no seed phrases. It is perfectly designed for new and experienced users who are discovering Web3 space, providing them with an excellent security and enjoyable experience. Bitizen has its own built-in Web3 Touch Browser, a large Dapp library, Use-to-Earn platform, NFT DIDs, and many other features. Start your safe Web3 journey with Bitizen Wallet today!

### Wallet logo

![COLOR_V](https://user-images.githubusercontent.com/109569113/215300021-5df110c2-91c3-401c-9e7f-32e36d4f24f3.svg)

### Background color for brand logo

#0dad86

### URL to the project

https://bitizen.org

### When did the wallet go live to users?

September 2021

### Does the wallet have an active development team?

Yes, please check our monthly updates:
https://medium.com/@bitizenwallet/bitizen-monthly-report-december-f751c273f69c
https://medium.com/@bitizenwallet/bitizen-monthly-report-november-35d3dc9030d8

### Is the wallet globally accessible?

No KYC, no geographic limitations

### Is the wallet available in multiple languages?

English, Simplified Chinese (currently localizing to Vietnamese, Korean, Japanese, Turkish, Russian, Spanish)

### What social links are there for the project?

https://twitter.com/BitizenWallet
https://discord.com/invite/6bpZkzZBDP
https://t.me/bitizenwallet
https://medium.com/@bitizenwallet
https://www.youtube.com/channel/UCrmFuyS5xgXPGb_MbBTljpQ

https://link3.to/bitizen

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, fully working on iOS, Android + APK

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No, Bitizen is an MPC-based wallet with no private keys and no seed phrases.

### Is the source code for the wallet fully open-source?

No

### Who holds the private keys?

Bitizen is an MPC-based wallet with no private keys and no seed phrases. User stores his encrypted key share on his or her mobile phone, and another key share is stored on Bitizen server. Third key share can be added on the second user's device, such as a second phone, iPad, laptop etc. Bitizen is a semi/non-custodial wallet, meaning that a user can sign his transactions with or without Bitizen server, by connecting his two devices via Bluetooth.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Security Audit report by SlowMist:
https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/blockchain-application/SlowMist%20Audit%20Report%20-%20Bitizen%20Wallet(iOS)_en-us.pdf

https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/blockchain-application/SlowMist%20Audit%20Report%20-%20Bitizen%20Wallet(Android)_en-us.pdf

BugRap White Hat Bug Bounty:
https://bugrap.io/projects/Bitizen

### Has the wallet's smart contract code or security modules been audited?

Please check SlowMist Security Audit Reports by the link above.

### Does the wallet have an internal security team?

No

### Any other security testing that should be noted?

- MPC Distributed Key Shares Generation Protocol
- MPC Signature Computation Protocol
- 2-of-3 TSS (two signing devices with key shares jointly compute a signature)
- MPC Key Share Rotation protocol (making hacking impossible) 
- 3FA backup and recovery, including biometry (encrypted face scan)
- Encrypted Face scan transaction signature approval
- Social recovery (family member's face)
- Extra security measures as limits set by the user himself

### Scam protection?

Yes. Bitizen wallet alerts and blocks an access for a Dapp if a third-party provider may potentially try to access funds or make any changes.

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes. Connect Wallet to a Dapp, built-in Web3 Touch Browser, DApps Discovery with recommended Dapps, GameFi, NFT, SocialFi, DeFi and other sections, Use-to-Earn (in development)

### Does the wallet support staking directly?

Not yet

### Does the wallet support swaps directly?

Not yet

### Does the wallet support multi-chain networks?

Yes

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

No

### Does the wallet support sending transactions to ENS addresses?

Yes, via TwitterScan 

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Not yet

### Does the wallet support withdrawals to fiat?

Not yet

### Is the wallet a multi-signature wallet?

No, Bitizen is an MPC-wallet

### Does the wallet support social recovery?

Yes, by family member's encrypted face scan

### Who can the ethereum.org team can contact regarding the wallet in future?

Bitizen Wallet CMO:

TG: @Nikitawins
Twitter: NikitaShengli
DC: Nikita Ermakov#3472
web3@bitizen.org

### Does the wallet have a dedicated support team?

Yes
Nikita @ Bitizen (TG: @Nikitawins)
Tia (TG: @TiaaQT)
Harlan (TG: @HarlanMix)
Steven (TG: @cophiaw)

24/7, reply within ~10 mins

### What educational resources/documentation do you provide to users?

Documentation:
https://docs.bitizen.org

YouTube Tutorials:
https://www.youtube.com/@bitizenwallet

Blog with educational articles:
https://medium.com/@bitizenwallet

### Does the wallet have any integrated tools not mentioned above?

- No KYC
- Privacy-safe: Zero-knowledge about users
- All personal data is encrypted, team has no decryption keys.

**Comment by ameeetgaikwad** [comment]
I would like to help!

**Comment by ermakovventures** [comment]
> I would like to help!

Can you add information about Bitizen to the Find Wallet list?

**Comment by ameeetgaikwad** [comment]
Yes I can, can you provide the link of the page where to add?

**Comment by ermakovventures** [comment]
> Yes I can, can you provide the link of the page where to add?

https://ethereum.org/en/wallets/find-wallet/

**Comment by ermakovventures** [comment]
> Yes I can, can you provide the link of the page where to add?
https://ethereum.org/en/wallets/find-wallet/
@ameeetgaikwad let me know when you add, many thanks!

**Comment by corwintines** [comment]
@ameeetgaikwad just one question I had here to clarify. 

If Bitizen disappeared, is a user still able to access their funds? It sounds like it is possible with 2/3 keys for the MPC controlled by the user, but wanted clarification on this.

**Comment by ameeetgaikwad** [comment]
> @ameeetgaikwad just one question I had here to clarify.
> 
> If Bitizen disappeared, is a user still able to access their funds? It sounds like it is possible with 2/3 keys for the MPC controlled by the user, but wanted clarification on this.

@corwintines hey I'm just here to help, I don't know anything about Bitizen wallet. @ermakovventures can help you with this.

**Comment by corwintines** [comment]
Still unanswered questions here. Going to close this out. @ermakovventures if you can provide more info on what happens if Bitizen disappears for the MPC side of this wallet feel free to reopen.
