### ISSUE TITLE
Suggest a developer tool - Percy

### ISSUE THREAD

**Issue by MrJithil** [ethereum/ethereum-org-website#9361]
### Dev tool name

Percy

### Dev tool description

URL: https://www.browserstack.com/percy

Percy helps teams automate visual testing. It captures screenshots, compares them against the baseline, and highlights visual changes. With increased visual coverage, teams can deploy code changes with confidence with every commit.

### When did the dev tool go live?

Mid of 2023

### Where do you think this page should be shown?

* https://ethereum.org/en/
* https://ethereum.org/en/learn/
* expanded nav menu
* https://ethereum.org/en/staking/
* and all other critical pages and components

### Is the product open source?

No

### Documentation URL

https://www.browserstack.com/docs/

### Additional context

Percy is a paid software but for the basic setup and most wanted features could be used Free (5000 screenshot comparisons)

**Comment by corwintines** [comment]
I don't see this as a developer tool for Ethereum developers, and not sure where this would live on the site. This would largely be related to frontend development to me. I'm going to close this for now, but if you disagree feel free to reopen and provide a bit more of a rationale for this tool specifically :)
