### ISSUE TITLE
Suggest a dapp - Lirn.io

### ISSUE THREAD

**Issue by tinteth** [ethereum/ethereum-org-website#9372]
### Name

Lirn.io

### Description

Verifying education onchain through a proof of education protocol.

### Logo

![LirnLogo(BLK)](https://user-images.githubusercontent.com/121214172/216236833-55c422b4-7b7c-4a4c-b589-9e9468c1cab2.png)

### Brand color

#000000 

### Is your dapp open source?

No

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

We have an internal security team and have gotten third parties to vet our smart contract for vulnerabilities. We do not facilitate any financial transactions so our Dapp never integrates with user funds.

### Can a user access the dapp without creating an account?

Yes

### Are dapp funds non-custodial?

Yes (we are none financial)

### Do you offer community support?

Yes, we are active on Twitter.

### Describe any geographical restrictions on usage of your dapp

N/A

**Comment by tinteth** [comment]
Url is https://lirn.io

**Comment by corwintines** [comment]
Hey @tinteth.

This seems like an interesting idea. It does seem like this is a product <6 months if I look at the age of the quizzes to take. IF you see our listing policy, this is a requirement: https://ethereum.org/en/contributing/adding-products/#criteria-for-inclusion-the-must-haves

I'm going to close this out for that reason, but encourage you to open this in the future. How often are quizzes being added out of curiosity?

**Comment by tinteth** [comment]
Sorry I missed the timeline requirement @corwintines!

We're adding a new quiz per week and opening the platform up to more subject matter experts. We expect to have more quizzes coming out weekly.
