### ISSUE TITLE
EIP Quiz

### ISSUE THREAD

**Issue by tinteth** [ethereum/ethereum-org-website#9373]
We have created an EIP quiz for Ethereum users.
The information has been directly sourced from EIP-1 which covers the instructional information. This is beneficial to test users' knowledge and possibly even token gate future EIP and requires they pass the quiz. This would imply they have proof of knowledge.

You can find the quiz here: https://lirn.io 
The quiz title is EIP Quiz.

**Comment by corwintines** [comment]
Hey @tinteth. Thanks for the suggestion. 

I'm going to close this out as it's unclear what the ask here is, but if you would like to open an issue expanding on this my suggestions around this would be.

1 - For our learn quizzes, we look to make the questions around the content on the relevant page (https://ethereum.org/en/eips in this case). Take a look at this page first. 
2 - After that, come up with 4-8 questions to ask around this content, and open an issue with these questions

Hope to hear from you with that :) Thanks again!

**Comment by tinteth** [comment]
Hey @corwintines thank you for the clarity.

The ask would be to become a platform for a more in-depth quiz for EIP and for Ethereum to direct users to take it on our site. The information is directly from EIP-1.

I'll come back to this when we get more brand recognition and metrics on our platform.

Thanks again for your support :)
