### ISSUE TITLE
Suggest a dapp: Request Finance

### ISSUE THREAD

**Issue by owlcity001** [ethereum/ethereum-org-website#9381]
### Name

Request Finance

### Description

The all-in-one finance solution for Web3 teams - Crypto invoices, billing, payroll & expenses

### Logo

![image](https://user-images.githubusercontent.com/101855038/216504377-eeca9635-0797-49c6-acfa-84c9d0ebf045.png)

Press kit [here](https://www.request.finance/press)

### Brand color

#2b6ff4

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/RequestNetwork/

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Audits by Cure53 [here](https://request.network/en/2020/07/07/request-encryption-audit-completed-by-cure53/)

### Can a user access the dapp without creating an account?

No

### Are dapp funds non-custodial?

Yes

### Do you offer community support?

https://discord.gg/mknydCf2Nu

### Describe any geographical restrictions on usage of your dapp

Not applicable

**Comment by corwintines** [comment]
Hey @owlcity001. Thanks for opening this. 

Where do you see this fitting on the dapps page? Do you think there needs to be a new category?

Are you wanting to submit the PR to add this?

**Comment by konopkja** [comment]
@owlcity001 Hello, where would you see your project to be added on this page? https://ethereumorgwebsitedev01-0xkai27ethereumorgwebsitedapps.gatsbyjs.io/en/dapps/

Can you make a PR with the change?

**Comment by corwintines** [comment]
This has gone stale. Going to close.
