### ISSUE TITLE
Bug report: all links lead to gemini on safari - stablecoins page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9386]
### Describe the bug

There is a bug that redirects the user wherever one clicks to gemini, affected browser: safari

### To reproduce

1. Open Safari browser
2. Go to https://ethereum.org/en/stablecoins/
2. Click on table of stablecoins

see error

### Expected behavior

not to link out to gemini

**Comment by minimalsm** [comment]
I could replicate this on both my iPhone (Safari && Brave) and my desktop Safari browser.

Looks like anywhere you hover on the table, it treats it as a hover on the last item of the table. When I delete Gemini, the next bottom item is the only one clickable.

<img width="1527" alt="Screenshot 2023-02-03 at 13 23 27" src="https://user-images.githubusercontent.com/62268199/216614765-3e338e9c-30fa-48b2-99d1-3c295c6a1090.png">

**Comment by samajammin** [comment]
I'm able to reproduce on desktop Safari. Basically anywhere I click on the page, that link opens 😱

**Comment by minimalsm** [comment]
Related: https://github.com/chakra-ui/chakra-ui/issues/3832
