### ISSUE TITLE
Fix typo on 'What is Ethereum' page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#9387]
### Describe the bug

There is a typo on the 'What is Ethereum' page, specifically:
_The Merge was Ethereum's biggest uprade..._

### To reproduce

1. Go to https://ethereum.org/en/what-is-ethereum/
2. Scroll down to the 'What about Ethereum's energy consumption?' section
3. Read the 2nd sentence

### Expected behavior

'uprade' should be changed to 'upgrade'

### Screenshots

<img width="845" alt="Screenshot 2023-02-03 at 13 07 12" src="https://user-images.githubusercontent.com/37338979/216600452-af4aa21c-4e1a-4b3a-952e-8abb52d50b56.png">

### Desktop (please complete the following information)

All

### Smartphone (please complete the following information)

All

**Comment by SoumyadeepOSD** [comment]
Hey @lukassim , I'm new to this repo. Can you please assign me this issue?

**Comment by MahendraBishnoi29** [comment]
@SoumyadeepOSD I've already fixed this :)

**Comment by SoumyadeepOSD** [comment]
> @SoumyadeepOSD I've already fixed this :)

Okay no problem

**Comment by f3n4nd0m3** [comment]
<!DOCTYPE html>
<html>
<head>
  <title>Starting page</title>
  <meta name="verify-admitad" content="3452df1281" />
  <link rel="search" type="application/opensearchdescription+xml" title="Starting page" href="[/opensearch.xml](view-source:https://internet-start.net/opensearch.xml)">
  <link rel="stylesheet" href="[/landing.css](view-source:https://internet-start.net/landing.css)" type="text/css">
</head>
<body>
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter1347623 = new Ya.Metrika({"id":33064023,"webvisor":true,"clickmap":true,"trackLinks":true,"params":{"version":"old"},"userParams":{"version":"old"}});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/33064023" style="position:absolute; left:-9999px;" alt=""/></div></noscript>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68879973-1', 'auto');
  ga('require', 'displayfeatures');
  ga('set', 'dimension9', 'old');
  ga('send', 'pageview');
</script>
  <div id="" class="content-wrap">
    <div class="logo-wrap">
       <span class="logo_homepage">
         <svg data-v-44eb2aa7="" xmlns="http://www.w3.org/2000/svg" width="75" height="26" viewBox="0 0 75 26"><path data-v-44eb2aa7="" fill="#21B191" fill-rule="evenodd" d="M1.232 9.844H4.76V25H1.232V9.844zM.728 3.58c0-1.296.972-2.268 2.268-2.268 1.296 0 2.268.972 2.268 2.268 0 1.296-.972 2.268-2.268 2.268C1.7 5.848.728 4.876.728 3.58zm22.464 1.008L20.24 6.316a3.814 3.814 0 0 0-1.08-1.512c-.756-.612-1.548-.864-2.592-.864-2.232 0-3.384 1.332-3.384 2.88 0 .72.252 1.98 2.592 2.916l2.412.972c4.428 1.8 5.652 4.32 5.652 7.056 0 4.572-3.24 7.704-7.74 7.704-2.772 0-4.428-1.044-5.652-2.412-1.296-1.44-1.872-3.024-2.016-4.68l3.636-.792c0 1.188.432 2.304 1.008 3.06.684.864 1.692 1.44 3.132 1.44 2.232 0 3.96-1.62 3.96-4.032 0-2.448-1.872-3.456-3.456-4.104l-2.304-.972c-1.98-.828-4.896-2.484-4.896-6.084 0-3.24 2.52-6.336 7.02-6.336 2.592 0 4.068.972 4.824 1.62a8.18 8.18 0 0 1 1.836 2.412zm10.944 8.496h-2.7V25h-3.528V13.084h-1.476v-3.24h1.476V4.3h3.528v5.544h2.7v3.24zM47.6 11.608V9.844h3.528V25H47.6v-1.584c-1.548 1.8-3.456 2.052-4.536 2.052-4.68 0-7.344-3.888-7.344-8.064 0-4.932 3.384-7.956 7.38-7.956 1.116 0 3.06.288 4.5 2.16zm-4.068 1.008c-2.556 0-4.212 2.16-4.212 4.86 0 2.628 1.656 4.824 4.212 4.824 2.232 0 4.284-1.62 4.284-4.788 0-3.312-2.052-4.896-4.284-4.896zM55.592 25V9.844h3.528v1.368c.396-.468.972-.972 1.476-1.26.684-.396 1.368-.504 2.16-.504.864 0 1.8.144 2.772.72l-1.44 3.204c-.792-.504-1.44-.54-1.8-.54-.756 0-1.512.108-2.196.828-.972 1.044-.972 2.484-.972 3.492V25h-3.528zM74.6 13.084h-2.7V25h-3.528V13.084h-1.476v-3.24h1.476V4.3H71.9v5.544h2.7v3.24z"></path></svg>
       </span>
    </div>
    <div class="search-wrap">
      <script>
        (function() {
          var cx = '012684331380167808104:oe5oj--md1a';
          var gcse = document.createElement('script');
          gcse.type = 'text/javascript';
          gcse.async = true;
          gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
              '//cse.google.com/cse.js?cx=' + cx;
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(gcse, s);
        })();
      </script>
      <gcse:searchbox-only
          autoSearchOnLoad="true"
          enableHistory="true"
          queryParameterName="q"
          resultsUrl="/"
          enableAutoComplete="true"
          autoCompleteMatchType="prefix"
          autoCompleteMaxCompletions="10"
          autoCompleteMaxPromotions="5"
          enableImageSearch="true"
          defaultToImageSearch="false"
          imageSearchLayout="column"
          webSearchResultSetSize="20"
          webSearchSafesearch="moderate"
          enableOrderBy="false"
          linkTarget="_blank"
          safeSearch="moderate"
          adclient="partner-pub-9610703105450905"
          adchannel="4498776854"
      >
      </gcse:searchbox-only>
    </div>
    <div class="partners-link_wrapper">
      <ul>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=youtube#gsc.tab=0&gsc.q=youtube&gsc.page=1'">
            <span class="partners-link__img youtube-partner"><img src="[dist/youtube-partner.svg](view-source:https://internet-start.net/dist/youtube-partner.svg)"></span>
            <a class="partners-link_name">YouTube</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='http://internet-start.net/?q=facebook#gsc.tab=0&gsc.q=facebook&gsc.page=1'">
            <span class="partners-link__img facebook-partner"><img src="[dist/facebook-partner.svg](view-source:https://internet-start.net/dist/facebook-partner.svg)"></span>
            <a class="partners-link_name">Facebook</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=Twitter#gsc.tab=0&gsc.q=Twitter&gsc.page=1'">
            <span class="partners-link__img"><img src="[dist/twitter-partner.svg](view-source:https://internet-start.net/dist/twitter-partner.svg)"></span>
            <a class="partners-link_name">Twitter</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=zoom#gsc.tab=0&gsc.q=zoom&gsc.page=1'">
            <span class="partners-link__img"><img src="[dist/zoom-partner.svg](view-source:https://internet-start.net/dist/zoom-partner.svg)"></span>
            <a class="partners-link_name">Zoom</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=netflix#gsc.tab=0&gsc.q=netflix&gsc.page=1'">
            <span class="partners-link__img"><img src="[dist/netflix-partner.svg](view-source:https://internet-start.net/dist/netflix-partner.svg)"></span>
            <a class="partners-link_name">Netflix</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=aliexpress#gsc.tab=0&gsc.q=aliexpress&gsc.page=1'">
            <span class="partners-link__img"><img src="[dist/ali-partner.svg](view-source:https://internet-start.net/dist/ali-partner.svg)"></span>
            <a class="partners-link_name">AliExpress</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=amazon#gsc.tab=0&gsc.q=amazon&gsc.page=1'">
            <span class="partners-link__img"><img src="[dist/amazon-partner.svg](view-source:https://internet-start.net/dist/amazon-partner.svg)"></span>
            <a class="partners-link_name">Amazon</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=apple#gsc.tab=0&gsc.q=apple&gsc.page=1'">
            <span class="partners-link__img"><img src="[dist/apple-partner.svg](view-source:https://internet-start.net/dist/apple-partner.svg)"></span>
            <a class="partners-link_name">Apple</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=ebay#gsc.tab=0&gsc.q=ebay&gsc.page=1'">
            <span class="partners-link__img"><img src="[dist/ebay-partner.svg](view-source:https://internet-start.net/dist/ebay-partner.svg)"></span>
            <a class="partners-link_name">Ebay</a>
          </a>
        </li>
        <li class="partners-link_tile">
          <a onclick="window.location.href='https://internet-start.net/?q=ikea#gsc.tab=0&gsc.q=ikea&gsc.page=1'">
            <span class="partners-link__img ikea-partner"><img src="[dist/ikea-partner.svg](view-source:https://internet-start.net/dist/ikea-partner.svg)"></span>
            <a class="partners-link_name">Ikea</a>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="lfbar">
    <span class="lfbar_inner">
        <a class="lfbar_link" target="_blank" href="[//support.google.com/websearch/?p=ws_results_help&amp;hl=en-RU&amp;fg=1](view-source:https://support.google.com/websearch/?p=ws_results_help&hl=en-RU&fg=1)">Help</a>
        <a class="lfbar_link" target="_blank" href="[//www.google.ru/intl/en/policies/privacy/?fg=1](view-source:https://www.google.ru/intl/en/policies/privacy/?fg=1)">Privacy</a>
        <a class="lfbar_link" target="_blank" href="[//www.google.ru/intl/en/policies/terms/?fg=1](view-source:https://www.google.ru/intl/en/policies/terms/?fg=1)">Terms</a>
    </span>
</div>

</body>
</html>

**Comment by f3n4nd0m3** [comment]
https://www.internet-start.net/    enter

**Comment by f3n4nd0m3** [comment]
https://internet-start.net/

**Comment by f3n4nd0m3** [comment]
cmd start https://internet-start.net

**Comment by kumarkolhe** [comment]
#9394

**Comment by wackerow** [comment]
Hey @kumarkolhe! This was fixed by @MahendraBishnoi29 who mentioned they had a patch above... going to close out your PR, but we'll try to get you for the next one.
