### ISSUE TITLE
Suggest an exchange: Korbit

### ISSUE THREAD

**Issue by brian-korbit** [ethereum/ethereum-org-website#9396]
### Exchange name

Korbit (Korbit Inc.)

### Exchange description

Established in 2013, Korbit is the pioneer of the crypto exchange industry in Korea. Fostering its service beyond simple trading to Crypto Research, NFT Marketplace, Metaverse Community and various B2B services, the company is constantly expanding its borders to grow into a global exchange.

### What geographical restrictions apply to this exchange?

Located in Seoul, the financial hub in South Korea, Korbit is under KoFIU(Korea Financial Intelligence Unit) authority. Acquiring official VASP(Virtual Asset Service Provider) from the government in Oct 2021, Korbit is one of five government-approved crypto exchanges in Korea.

### Which currencies are accepted by this exchange?

Korbit supports KRW-Crypto trading service. 
   As of 02 Feb 2023, over 118 crypto currencies are listed and being actively traded.

### Do you have any proof that they're a legitimate company?

You may find more information on Korbit from the following official website : https://www.korbit.co.kr/about

Following documents are available for the proof of business legitimacy : 
Company Information (eng Ver.) 
[(Eng)Korbit_intro_2023-02-02.pptx.pdf](https://github.com/ethereum/ethereum-org-website/files/10636586/Eng.Korbit_intro_2023-02-02.pptx.pdf)

Korbit took the lead in proving the transparency of fund management among crypto exchanges in Korea, and acquired certified Financial Reserves Disclosure mark on CoinMarketCap.
https://coinmarketcap.com/exchanges/korbit/

(and more if needed)

### Do you have any extra information?

With nearly 10 years of Crypto exchange business operation since 2013, Korbit has been leading the future of crypto-and-blockchain-based technologies in South Korea.

Officially approved VASP-licensed crypto exchange, over 130 Korbit crews are interactively upscaling the service quality standard in service, compliance and expansion of crypto-based businesses. 

With its highly valued credits and know-how, Global conglomerates such as Samsung, LG, SK, NXC are partnering with Korbit for various B2B collaborations.

**Comment by corwintines** [comment]
Hey @brian-korbit, would you like to open the PR to add Korbit?

**Comment by tomatowax** [comment]
@corwintines Thank you for the comment. We'll prepare the PR to add the Korbit website.

**Comment by tomatowax** [comment]
@corwintines Is it OK if we add it on the 'dev' branch? (I checked the dev branch is the default branch for this repo.)

**Comment by tomatowax** [comment]
@corwintines Hi. I made the PR and requested it to merge onto 'dev' branch. Please check and merge. Thank you.

https://github.com/ethereum/ethereum-org-website/pull/10334

**Comment by ted-korbit** [comment]
@corwintines Hi, could you check this pull request to add Korbit exchange? Thank you cc @wackerow
https://github.com/ethereum/ethereum-org-website/pull/10334
