### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Sagarsc07** [ethereum/ethereum-org-website#9411]
### Describe the bug

External links or sites can't be reached!

### To reproduce

1. Go to 'https://ethereum.org/en/what-is-ethereum/'
2. Click on 'Projects built on Ethereum ℹ'
3. Scroll down to 'Ethereum in numbers'
4. See error 'https://www.stateofthedapps.com/stats/platform/ethereum#new' this site can't be reached!

### Expected behavior

Show us project built on Ethereum. 

### Screenshots

![Ethereum in numbers](https://user-images.githubusercontent.com/106554264/217057825-d9de683d-2f43-4821-acc9-f96213d888ce.jpg)
![Can't reach](https://user-images.githubusercontent.com/106554264/217057822-089c0fe7-8357-49cb-8a60-43c646113ded.jpg)

### Desktop (please complete the following information)

OS: - Windows 10
Browser: - Chrome
Version: - Version 109.0.5414.120 (Official Build) (64-bit)

### Additional context

Just update the external link.

**Comment by MahendraBishnoi29** [comment]
I think it's deprecated. @pettinarip @wackerow 
I want to work on this so should I remove this link or add a new link here?

**Comment by pettinarip** [comment]
Thanks for reporting this bug @Sagarsc07.

It seems that the entire site is down https://www.stateofthedapps.com/ and on twitter as well.

@konopkja do you know if we have a replacement for this link? maybe in the meanwhile we can remove this link 🤔 

@MahendraBishnoi29 thanks for trying to help us here. Let's wait a moment and see what options we have here.

**Comment by konopkja** [comment]
> 

not really, lets ask the community what would be the best resource

**Comment by MahendraBishnoi29** [comment]
> 

I have a few suggestions if I may offer them

what about: https://dappradar.com/

**Comment by konopkja** [comment]
i see josh stark link is also broken in that component

**Comment by pettinarip** [comment]
For a short term solution, lets remove those links @MahendraBishnoi29
- the one reported (stateoftheapps.com)
- and the josh stark's links which are also broken

We can keep investigating what resource we could use and later make a decision.

Thanks, assigning it to you :)

**Comment by MahendraBishnoi29** [comment]
@konopkja josh stark link is good i think

**Comment by pettinarip** [comment]
> @konopkja @pettinarip josh stark link is good I think, also should I use https://dappradar.com/ or not?

Do you know if this same data is provided by dappradar? could you build a query or permalink to that resource?

**Comment by konopkja** [comment]
> > @konopkja @pettinarip josh stark link is good I think, also should I use https://dappradar.com/ or not?
> 
> Do you know if this same data is provided by dappradar? could you build a query or permalink to that resource?

https://dappradar.com/rankings/protocol/ethereum

Discussed with dappradar team, its a community-based project indexing, but they have a review process in place - I am okay with changing the link to them.

**Comment by pettinarip** [comment]
Ok cool!

We could take this opportunity and update the metric as well @konopkja. Currently we are displaying `2970` dapps. Now it should be `3882`. Is that correct?

![image](https://user-images.githubusercontent.com/468158/218497361-e1e7609e-6d20-4673-8cec-9f5b6038c8bb.png)

**Comment by konopkja** [comment]
yep, agree. Somebody from their team will also comment on this issue I think.

**Comment by dragosdydy** [comment]
@konopkja Dragos here, co-founder of DappRadar. As you have already said, we are getting the submissions from the community or dapp developers and we are making sure they have filled all the relevant information (logo, title, description, social media, smart contracts, etc.).

We're also keeping an eye on the market and keeping the dapps listed updated. Let us know if we can offer more information or help with anything.

**Comment by konopkja** [comment]
> @konopkja Dragos here, co-founder of DappRadar. As you have already said, we are getting the submissions from the community or dapp developers and we are making sure they have filled all the relevant information (logo, title, description, social media, smart contracts, etc.).
> 
> We're also keeping an eye on the market and keeping the dapps listed updated. Let us know if we can offer more information or help with anything.

Hello! do you want any UTM parameters in the link or without is ok too?

**Comment by dragosdydy** [comment]
@konopkja If it is allowed, it would be great to have UTM params: https://dappradar.com/rankings/protocol/ethereum?utm_source=ethereum&utm_medium=website&utm_campaign=ethereum-dapps - but it is up to you. Thanks.

**Comment by konopkja** [comment]
> https://dappradar.com/rankings/protocol/ethereum?utm_source=ethereum&utm_medium=website&utm_campaign=ethereum-dapps

after syncing with the core team, we decided not to include the utm parameters as we generally do not allow these, sorry for the miscommunication.

**Comment by vishal590** [comment]
@konopkja I want to participate in writing code, how can I participate ?
please reply 🙏🙏

**Comment by konopkja** [comment]
> @konopkja I want to participate in writing code, how can I participate ? please reply 🙏🙏

check our open issues and post a comment on the one you would like to take on https://github.com/ethereum/ethereum-org-website/issues

**Comment by konopkja** [comment]
@vishal590 do you want to make the changes in this issue? if not @pettinarip  or @corwintines  please, have a look here. Update the number of apps and link to the source.

**Comment by vishal590** [comment]
@konopkja  currently working on one issue

**Comment by corwintines** [comment]
Will assign to you @vishal590

**Comment by MahendraBishnoi29** [comment]
> I see this is already assigned to @MahendraBishnoi29 who has opened a PR @vishal590. If you want to help review that to contribute to this that would be great. 

yes I've already made suggested changes but still waiting for someone's review 😃

**Comment by konopkja** [comment]
fixed
