### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by pr0toshi** [ethereum/ethereum-org-website#9418]
### Dev tool name

Scry

### Dev tool description

Scrys a platform for arbitrary oracles and scalable onchain data feeds to be created using our custom oracle framework. You can have 100s-1000+ data feeds using any API you may want with high scale design, historical lookup, developer self deployment and more. The oracles were designed when we were trying to create a permissionless synthetic assets platform and we wanted to demo by creating a banana synth, but the oracle solutions out there were all low quality or not easy to get new feeds up. So we made our own.

Oracles key features
- Autonomous oracle system where devs can self deploy own feeds/oracles and use custom signers for permissionless, decentralized and secure deployment with self-controllable feed creation using custom APIs for rapid development. The nodes are able to be deployed in <15m on any EVM by devs with 0 code needed and update feeds supported in realtime as needed.
- 200+ different feed updates with 1 tx (high scale data). Scaled with Layer 2s.
- Use any API with a highly robust parse engine, controlled by a simple spreadsheet, just put the URL, the parse for the json to be expected and basic info and the feed will be ready to use and submitted on chain by all signers.
- Data lookup for historical data for all feeds natively, allows for both immutable data access, TWAP construction and onchain analytics.
- Allows for various monetization structures at a feed level, oracle providers can charge for certain feeds to earn revenue as well as provide others for public use, subscription models for data requests at the feed level and oracle level.
- Largest data provider for goerli, sepolia, optimism, canto, polygon and providing 3x the data Link are able to, with the ability to scale to 100x by simply updating the APIs pulled from. Stress tested with up to 500 feeds with just 1 tx, which is 10x Links entire oracle network for any Layer 2, and more than matches all oracle feeds for mainnet they offer, in 1 tx.
- Fully decentralized and open source, the Front End, Node and Contracts are all open source and can be self hosted by teams and networks

Front end (beta)
[https://goerli.dapp.scry.finance](https://t.co/7jPQPTvRS2)

Workshop demo
https://youtube.com/playlist?list=PLk1tMbSRqESqXp5u0oHwVLL43e7dfV5LB

### When did the dev tool go live?

Been used in prod in other projects since Jan 2022 before being opened up

### Where do you think this page should be shown?

https://ethereum.org/en/developers/docs/oracles/

### Is the product open source?

Yes

### GitHub URL

https://github.com/ScryProtocol

### Documentation URL

https://docs.scry.finance

### Additional context

The only tools that allows developers fulyl self sovereign oracle deployment with custom signers. No token BS or requirements. Fully open source from contracts to node to FE.

**Comment by corwintines** [comment]
Closing based on comment in PR
