### ISSUE TITLE
[Design system V2] New doc search component.

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9429]
This issue is a part of the https://github.com/ethereum/ethereum-org-website/issues/9431

The goal is to adopt doc search from Algolia to be the search component for ethereum.org

The component is a pre-built one we only get to change some styles to blend better into the Design system.

We have a Design proposal ready to be implemented by @wackerow, but open to getting feedback.

Here is the [Figma file](https://www.figma.com/file/wkPuZW7kbXuEiawA4A2isT/V2%2Fdoc-search-component?node-id=0%3A1&t=hK4RRlKeld9Lef2e-1) with the design.

The header with the new search input
![Screen Shot 2023-02-08 08 30 00 PM](https://user-images.githubusercontent.com/1120748/217644108-04226625-5ee4-40f1-859c-58ea3425f525.png)

The search modal
![Screen Shot 2023-02-08 08 29 47 PM](https://user-images.githubusercontent.com/1120748/217644181-95f4ea62-d499-4740-9cb2-2f069619416c.png)

**Comment by corwintines** [comment]
I'm very excited by this
