### ISSUE TITLE
[Design system V2] Callouts component

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9430]
## Intro
This issue is a part of the [Design System V2 Epic](https://github.com/ethereum/ethereum-org-website/issues/9431) and can be assigned to anyone who wants to collaborate. 
You can use the comments to sign that you want to work on this, and this issue can be assigned to you.
If you have any questions about it, please don't hesitate to reach out on the comments or on our discord

<br>
<br>

## Description
Creating all the possible variations of callouts in the DS is an important way to bring attention to specific pieces of information or to draw the user's focus to a specific part of the content. It can be a great way to draw attention to smaller parts of the content that may otherwise be overlooked.

 Additionally, callouts can help make the content more visually appealing and organized, which can make it easier for the user to navigate and understand the information presented.

- Type: unification design
- Difficulty: 3 out of 10

[Link to the Figma file](https://www.figma.com/file/RFV10aXTzNQ1Nt41uGvBJp/V2%2FCallouts?node-id=0%3A1&t=KIsLtR6zUGqwMDgQ-1) to be worked on 

<br>
<br>

## workflow
These are the main steps for each task.

1. #### Use a separate [Figma file](https://www.figma.com/file/RFV10aXTzNQ1Nt41uGvBJp/V2%2FCallouts?node-id=0%3A1&t=KIsLtR6zUGqwMDgQ-1).
    - made by the team and liked here should be
2. #### Identify on which pages the component is used.
    - This can be made collaboratively and consists of screenshots/links to the pages where these components are already in use. Note that we can propose the unification of similar components in one if we find that the UX/UI justifies that’s the core unification goal of the Design system V2.
3. #### Identify the chakra component to be used as a base (if any)
    - We use chakra UI as a base framework, and if we can match the new design with an existing UI component in chakra, it’s a good call. If not, we can build one, but this should be something to identify now that will ease the implementation.
4. #### Work on the design.
    - This is where we build the new proposal that will be a new component in the design system, never forgetting the different screen sizes, behavior states, and themes.
5. #### Test and validate the new component on Figma.
    - Before closing the design, we need to test some real use cases. I suggested having some production screenshot as the base and building it on a Figma page with real content to test the live application of the new design.
6. #### Validation and feedback.
    - At this point, we are ready to validate and collect feedback. We should act upon this and have the best proposal possible.
7. #### Spec to handover to code.
    - This will be the final step, where we review the file from the perspective of a handover to the design system master file and to the code or storybook for code development.
8. #### Merge with the master Figma file of the Design system.
    - This step will be made by someone from the core team because there are some things that could be improved in how we can onboard external contributors to the Figma team. It’s a Figma thing that we can’t change for now.
9. #### Close the issue and publish the Design system update on the Figma community**.
    - For the last action, we need to close the issue and update the Design system on the Figam community file. At this point, another issue might need to be created to update the storybook and the code to reflect this new design.

<br>
<br>

**Comment by nloureiro** [comment]
For 2024, we will create a new set of PRs for the Design Community to work on. Keeping this on does not make sense anymore.

**Comment by ReactOnChain** [comment]
Hey @nloureiro can you assign this task to me? I've almost completed it.

**Comment by nloureiro** [comment]
> Hey @nloureiro can you assign this task to me? I've almost completed it.

yes, it's yours!

let me know if you need anything. Thank you!

**Comment by ReactOnChain** [comment]
Ideal, thanks!
Once I finish with the Figma, what do I do next? Paste the public link in here?

**Comment by ReactOnChain** [comment]
Hey @nloureiro I have finished the design of the component. Do I need to create a new branch of this repo, and change the link to the figma to my own one?
Thanks for your help!

**Comment by nloureiro** [comment]
> Hey @nloureiro I have finished the design of the component. Do I need to create a new branch of this repo, and change the link to the figma to my own one? Thanks for your help!

hey. great.
yes, can you link your Figma file here for a review.

Thank you!

**Comment by ReactOnChain** [comment]
Sounds good, let me know if anything else needs adding:

https://www.figma.com/file/GwW36tUeGaaCl5x7NAhdIi/V2%2FCallouts---Harvey-Amend?type=design&node-id=0%3A1&mode=design&t=kAWtGH4kYms35u6C-1

**Comment by nloureiro** [comment]
They look great, I will review them in detail soon!
Thank you for your contribution!!

**Comment by wackerow** [comment]
cc: @nloureiro bump

**Comment by ReactOnChain** [comment]
Hey, I see it's been pushed to stale, but the design has been completed?

**Comment by ReactOnChain** [comment]
Hey, is there anything else you need me to do for this task?

**Comment by nloureiro** [comment]
hey @ReactOnChain great work!!!

I'm so sorry, I missed the review for this... my bad.

The base design is great! I like it

May I ask you to expand it to edge cases?

- how does it behave with more text? 2 lines? 3 lines?
- mobile version, just to be sure if all the content stays in the same place
- question: will this call out be for warning and success, too? should we use the green, yellow and red from the design system?

Thank you for your contribution!! 🙌

**Comment by nloureiro** [comment]
Thank you, @ReactOnChain, for this!

I haven´t reviewed the Figma in detail, but I will close the issue based on your great contribution!

Thank you!
