### ISSUE TITLE
[Design system V2] Rich tables component

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9433]
## Intro
This issue is a part of the [Design System V2 Epic](https://github.com/ethereum/ethereum-org-website/issues/9431) and can be assigned to anyone who wants to collaborate. 
You can use the comments to sign that you want to work on this, and this issue can be assigned to you.
If you have any questions about it, please don't hesitate to reach out on the comments or on our discord

<br>
<br>

## Description
When creating a content page that includes a table, it is important to take into consideration the size of the user's screen and the potentially varying needs for filters, sorting, and other expected behaviors for tables.

This involves making sure that the table is easily readable on a variety of devices and that the filters, sorting, and other expected behaviors are easy to access and use.

 Additionally, it is important to make sure that the design of the table is simple and intuitive, and that the layout is well organized.

- Type: unification design
- Difficulty: 3 out of 10

[Link to the Figma file](https://www.figma.com/file/ho2kPFynPguZaYbQRk1scO/V2%2Frich-table?node-id=1%3A48&t=dgfKJ7Uv1RJ2Jkxb-1) to be worked on 

<br>
<br>

## workflow
These are the main steps for each task.

1. #### Use a separate [Figma file](https://www.figma.com/file/ho2kPFynPguZaYbQRk1scO/V2%2Frich-table?node-id=1%3A48&t=dgfKJ7Uv1RJ2Jkxb-1).
    - made by the team and liked here should be
2. #### Identify on which pages the component is used.
    - This can be made collaboratively and consists of screenshots/links to the pages where these components are already in use. Note that we can propose the unification of similar components in one if we find that the UX/UI justifies that’s the core unification goal of the Design system V2.
3. #### Identify the chakra component to be used as a base (if any)
    - We use chakra UI as a base framework, and if we can match the new design with an existing UI component in chakra, it’s a good call. If not, we can build one, but this should be something to identify now that will ease the implementation.
4. #### Work on the design.
    - This is where we build the new proposal that will be a new component in the design system, never forgetting the different screen sizes, behavior states, and themes.
5. #### Test and validate the new component on Figma.
    - Before closing the design, we need to test some real use cases. I suggested having some production screenshot as the base and building it on a Figma page with real content to test the live application of the new design.
6. #### Validation and feedback.
    - At this point, we are ready to validate and collect feedback. We should act upon this and have the best proposal possible.
7. #### Spec to handover to code.
    - This will be the final step, where we review the file from the perspective of a handover to the design system master file and to the code or storybook for code development.
8. #### Merge with the master Figma file of the Design system.
    - This step will be made by someone from the core team because there are some things that could be improved in how we can onboard external contributors to the Figma team. It’s a Figma thing that we can’t change for now.
9. #### Close the issue and publish the Design system update on the Figma community**.
    - For the last action, we need to close the issue and update the Design system on the Figam community file. At this point, another issue might need to be created to update the storybook and the code to reflect this new design.

<br>
<br>

**Comment by nloureiro** [comment]
this issue was worked  here
https://github.com/ethereum/ethereum-org-website/pull/9932

https://www.chromatic.com/component?appId=63b7ea99632763723c7f4d6b&csfId=molecules-display-content-tables--tables&buildNumber=681&k=6491e56b49064d50ffdbeeb1-1200-interactive-true&h=8&b=-8

https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=2460%3A46192&mode=design&t=DGWxSDIF1kj1FM6m-1

**Comment by Dotcom0x** [comment]
Would like to work on this :)

**Comment by nloureiro** [comment]
> Would like to work on this :)

this one is already done, forgot to close it, sorry... thank you

**Comment by Dotcom0x** [comment]
No Worries!
