### ISSUE TITLE
[Design system V2] FAQ component

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9434]
## Intro
This issue is a part of the [Design System V2 Epic](https://github.com/ethereum/ethereum-org-website/issues/9431) and can be assigned to anyone who wants to collaborate. 
You can use the comments to sign that you want to work on this, and this issue can be assigned to you.
If you have any questions about it, please don't hesitate to reach out on the comments or on our discord

<br>
<br>

## Description
It’s one of the most used stand-alone components, and it needs to be unified in all its variations, including the implementation of best practices. 

This component needs to be ready to be used in Markdown (MD) pages, as well as in other document types and formats.

- Type: unification design
- Difficulty: 3 out of 10

[Link to the Figma file](https://www.figma.com/file/KrWFu90ZtTiY58rhnmErHS/V2%2FFAQ-components?node-id=0%3A1&t=FgqXbVgYJZT4l45H-1) to be worked on 

<br>
<br>

## workflow
These are the main steps for each task.

1. #### Use a separate [Figma file](https://www.figma.com/file/KrWFu90ZtTiY58rhnmErHS/V2%2FFAQ-components?node-id=0%3A1&t=FgqXbVgYJZT4l45H-1).
    - made by the team and liked here should be
2. #### Identify on which pages the component is used.
    - This can be made collaboratively and consists of screenshots/links to the pages where these components are already in use. Note that we can propose the unification of similar components in one if we find that the UX/UI justifies that’s the core unification goal of the Design system V2.
3. #### Identify the chakra component to be used as a base (if any)
    - We use chakra UI as a base framework, and if we can match the new design with an existing UI component in chakra, it’s a good call. If not, we can build one, but this should be something to identify now that will ease the implementation.
4. #### Work on the design.
    - This is where we build the new proposal that will be a new component in the design system, never forgetting the different screen sizes, behavior states, and themes.
5. #### Test and validate the new component on Figma.
    - Before closing the design, we need to test some real use cases. I suggested having some production screenshot as the base and building it on a Figma page with real content to test the live application of the new design.
6. #### Validation and feedback.
    - At this point, we are ready to validate and collect feedback. We should act upon this and have the best proposal possible.
7. #### Spec to handover to code.
    - This will be the final step, where we review the file from the perspective of a handover to the design system master file and to the code or storybook for code development.
8. #### Merge with the master Figma file of the Design system.
    - This step will be made by someone from the core team because there are some things that could be improved in how we can onboard external contributors to the Figma team. It’s a Figma thing that we can’t change for now.
9. #### Close the issue and publish the Design system update on the Figma community**.
    - For the last action, we need to close the issue and update the Design system on the Figam community file. At this point, another issue might need to be created to update the storybook and the code to reflect this new design.

<br>
<br>

**Comment by aacalanto** [comment]
hello! leaving a comment here to claim this task :)

**Comment by nloureiro** [comment]
> 

Hi @aacalanto, any developments on this issue?
DO you need any help?

**Comment by elcristiancamilo** [comment]
Hello @nloureiro, Camilo here, we talked by discord.

**Comment by nloureiro** [comment]
> Hello @nloureiro, Camilo here. We talked by discord.

Hello!
Thank you for reaching out. I've assigned you to this issue

@aacalanto started to do some variations, and I think he made really good progress.
@elcristiancamilo do you think you can jump in this Figma file and try to navigate on his work and help get a final design?
It might be just picking one of his ideas or redesign/interate to make something different. You can use Figma comments or just create components in Figma, whatever you feel like.

Reach out if you need any help. It can be a bit overwhelming to start, so don´t feel shy to ask questions, it can be a learning journey for you while you are collaborating

https://www.figma.com/file/KrWFu90ZtTiY58rhnmErHS/V2%2FFAQ-components?type=design&node-id=1%3A134&mode=design&t=m2i1EDkyLGVU1LeX-1

**Comment by elcristiancamilo** [comment]
> > Hello @nloureiro, Camilo here. We talked by discord.
> 
> Hello! Thank you for reaching out. I've assigned you to this issue
> 
> @aacalanto started to do some variations, and I think he made really good progress. @elcristiancamilo do you think you can jump in this Figma file and try to navigate on his work and help get a final design? It might be just picking one of his ideas or redesign/interate to make something different. You can use Figma comments or just create components in Figma, whatever you feel like.
> 
> Reach out if you need any help. It can be a bit overwhelming to start, so don´t feel shy to ask questions, it can be a learning journey for you while you are collaborating
> 
> https://www.figma.com/file/KrWFu90ZtTiY58rhnmErHS/V2%2FFAQ-components?type=design&node-id=1%3A134&mode=design&t=m2i1EDkyLGVU1LeX-1

Hola @nloureiro, thanks for explaining how to start because I was a little confused. 
I started to work in the Figma file. I am not sure if I am doing good but I made some proposals of design.

Thanks

**Comment by nloureiro** [comment]
This issue was mergen on the main Design system figma file here
https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=6797%3A28838&mode=design&t=JbqlHKfbpdWgzyfC-1
