### ISSUE TITLE
[Design system V2] Slider component

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9437]
## Intro
This issue is a part of the [Design System V2 Epic](https://github.com/ethereum/ethereum-org-website/issues/9431) and can be assigned to anyone who wants to collaborate. 
You can use the comments to sign that you want to work on this, and this issue can be assigned to you.
If you have any questions about it, please don't hesitate to reach out on the comments or on our discord

<br>
<br>

## Description
This is a straightforward element of the design system featuring varied content cards which have been arranged in the style of a carousel, showing only one card at a time. 

This component is a great addition to the design system and can be used to display a range of information in a visually appealing way.

- Type: unification design
- Difficulty: 4 out of 10

[Link to the Figma file](https://www.figma.com/file/uozCnbWF9WqLVQX7rnIyYB/V2%2FSlider?node-id=0%3A1&t=9kcM9en9MAyM5aGv-1) to be worked on 

<br>
<br>

## workflow
These are the main steps for each task.

1. #### Use a separate [Figma file](https://www.figma.com/file/uozCnbWF9WqLVQX7rnIyYB/V2%2FSlider?node-id=0%3A1&t=9kcM9en9MAyM5aGv-1).
    - made by the team and liked here should be
2. #### Identify on which pages the component is used.
    - This can be made collaboratively and consists of screenshots/links to the pages where these components are already in use. Note that we can propose the unification of similar components in one if we find that the UX/UI justifies that’s the core unification goal of the Design system V2.
3. #### Identify the chakra component to be used as a base (if any)
    - We use chakra UI as a base framework, and if we can match the new design with an existing UI component in chakra, it’s a good call. If not, we can build one, but this should be something to identify now that will ease the implementation.
4. #### Work on the design.
    - This is where we build the new proposal that will be a new component in the design system, never forgetting the different screen sizes, behavior states, and themes.
5. #### Test and validate the new component on Figma.
    - Before closing the design, we need to test some real use cases. I suggested having some production screenshot as the base and building it on a Figma page with real content to test the live application of the new design.
6. #### Validation and feedback.
    - At this point, we are ready to validate and collect feedback. We should act upon this and have the best proposal possible.
7. #### Spec to handover to code.
    - This will be the final step, where we review the file from the perspective of a handover to the design system master file and to the code or storybook for code development.
8. #### Merge with the master Figma file of the Design system.
    - This step will be made by someone from the core team because there are some things that could be improved in how we can onboard external contributors to the Figma team. It’s a Figma thing that we can’t change for now.
9. #### Close the issue and publish the Design system update on the Figma community**.
    - For the last action, we need to close the issue and update the Design system on the Figam community file. At this point, another issue might need to be created to update the storybook and the code to reflect this new design.

<br>
<br>

**Comment by HamishMcDougall** [comment]
I will pick this up.

**Comment by HamishMcDougall** [comment]
I am having trouble identifying which pages use the component on https://ethereum.org/en/ 

Can anyone point me in the right direction ?

**Comment by nloureiro** [comment]
> I am having trouble identifying which pages use the component on https://ethereum.org/en/
> 
> Can anyone point me in the right direction?


Hi, @HamishMcDougall Thank you for reaching out!

the slider is a simple component that it's not used too much, but you can find an example here
https://ethereum.org/en/what-is-ethereum/

(Just notice that the arrow buttons have a bug, damn! They should be)

The goal is to build this component in this figma file.
https://www.figma.com/file/uozCnbWF9WqLVQX7rnIyYB/V2%2FSlider?type=design&node-id=0%3A1&mode=design&t=zrnh0zp9ls6JgCxR-1

You can improve a little bit if you want to, using the Design system color and typography.

I can help if you need it. Let me know if this is enough for you to start working on it



it can

**Comment by HamishMcDougall** [comment]
@nloureiro  Thank you

**Comment by HamishMcDougall** [comment]
Design [Slider V2]  for review and community feedback  

https://www.figma.com/file/uozCnbWF9WqLVQX7rnIyYB/V2%2FSlider?type=design&node-id=1%3A142&mode=design&t=GSTxYX3Fp8lAvKpv-1

**Comment by nloureiro** [comment]
This PR is done and merged into the main figma file [here](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=8649%3A3175&mode=design&t=Ub5G2toJSslqUJWa-1)
