### ISSUE TITLE
Suggest a dapp: Art Blocks

### ISSUE THREAD

**Issue by ABDruid** [ethereum/ethereum-org-website#9446]
### Name

Art Blocks

### Description

Art Blocks is dedicated to bringing compelling works of contemporary generative art to life. We unite artists, collectors, and blockchain technology in service of groundbreaking artwork and remarkable experiences. Art Blocks is a platform on which artists publish editions of unique generative artworks using creative code. Chosen through a highly-selective application process, these projects represent new directions in this emergent art form.

### Logo

![lil squig 1200px](https://user-images.githubusercontent.com/105388299/217681909-4d3d6aad-d658-4c83-a10c-2a2c468fe241.png)

### Brand color

#FF00FF

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/ArtBlocks/artblocks-contracts

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

We develop our smart contracts out in the open (https://github.com/ArtBlocks/artblocks-contracts) and while we do not complete audits for all of our contracts due to a quickly actively evolving and developing suite of modular smart contracts, we do make extensive use of code reviews, automated tests, and end-to-end testnet verifications before releasing updated contracts into the wild.

### Can a user access the dapp without creating an account?

Yes! Art Blocks is fully accessible for viewing/interacting with anyone with access to the internet and accessible for collecting for anyone with an Ethereum wallet. There is no need to create a separate user account to use Art Blocks other than having an Ethereum wallet itself.

### Are dapp funds non-custodial?

Yes! Art Blocks contracts manage funds in a non-custodial way–when a user makes a purchase via Art Blocks, those funds are split in an automated way using smart contract logic. Additionally, the ERC721 Non-Fungible Tokens that are issued via Art Blocks are tokens that can be owned non-custodially in any Ethereum wallet, and given that the artwork itself for Art Blocks is stored on the Ethereum blockchain itself when an artist uploads their creative-coding script to on-chain storage, we believe that the Art Blocks art that we sell to be describe-able as a truly non-custodial bearer-asset type of digital artwork.

### Do you offer community support?

We do not offer customer support in the traditional sense of having a customer support team, but our community or we can answer most questions on our Discord server. Otherwise, here are our official channels:

Discord: discord.gg/artblocks
Website: Artblocks.io
Twitter: https://twitter.com/artblocks_io
Instagram: https://www.instagram.com/artblocks_io
YouTube: https://www.youtube.com/@ArtBlocksOfficialour community or us

### Describe any geographical restrictions on usage of your dapp

We do not have any in-contract geographical restrictions to this effect. However, our frontend and all backend services that we run and maintain are OFAC compliant based on using the Chainalysis API to screen for sanctioned addresses. Our frontend and backend services also do IP verification against sanctioned OFAC country lists.

**Comment by corwintines** [comment]
Thanks @ABDruid. Is this something you would like to open a PR for?

**Comment by ABDruid** [comment]
I completely lost track of this ticket! Very sorry for the delayed response. 

To be honest, I'm not the most technical and have no clue how to open a PR. 

With my current experience in GH, I either edit our docs directly on GH, or pull the entire repo, navigate to the specific page, edit that, and submit the PR. However, I have no clue where to find the page to edit in this repo.

If you (or someone) could provide some guidance on this, I'd be more than happy to do it (and learn how!)

Please let me know if I can help or add further context

**Comment by nloureiro** [comment]
> I completely lost track of this ticket! Very sorry for the delayed response.
> 
> To be honest, I'm not the most technical and have no clue how to open a PR.
> 
> With my current experience in GH, I either edit our docs directly on GH, or pull the entire repo, navigate to the specific page, edit that, and submit the PR. However, I have no clue where to find the page to edit in this repo.
> 
> If you (or someone) could provide some guidance on this, I'd be more than happy to do it (and learn how!)
> 
> Please let me know if I can help or add further context

hey. we lost track of this too, sorry for the late response.

We will open the PR and add it to the website very soon. Thank you for opening this issue.

**Comment by ABDruid** [comment]
Thanks so much for following up. Looking forward to seeing it live 😃
