### ISSUE TITLE
Library of Ethereum - Curated Collection of Ethereum Ecosystem Resources   

### ISSUE THREAD

**Issue by arpitingle** [ethereum/ethereum-org-website#9452]
https://github.com/ArpitIngle/Library-of-Ethereum 

"Library of Ethereum", a GitHub repo with a curated collection of Ethereum ecosystem resources. It includes resources on Smart Contracts (Solidity, Vyper, Cairo), DeFi, Security, Layer 2, EVM, MEV, Cryptography, and ZKPs.

**Comment by corwintines** [comment]
Hey @ArpitIngle, looks like an interesting resource. Wondering where you had envisioned this being?

**Comment by ArpitIngle** [comment]
> Hey @ArpitIngle, looks like an interesting resource. Wondering where you had envisioned this being?

Not so sure. Just wanted to contribute :)

**Comment by corwintines** [comment]
Going to close this out as its gone stale. @arpitingle Feel free to reopen if you want, but would suggest having an idea where to have this resource.
