### ISSUE TITLE
Horizontal scroll on Withdrawals page

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#9456]
### Describe the bug

On mobile, the withdrawals page has a horizontal scroll

### To reproduce

1. Go to https://ethereum.org/en/staking/withdrawals
2. go to mobile view if not on a mobile device
3. See the horizontal scroll

### Expected behavior

There should be no horizontal scroll when on this page

### Screenshots

![withdrawals](https://user-images.githubusercontent.com/15589226/217862113-73e41d73-58ec-473f-84f4-60585785c36c.png)

**Comment by TylerAPfledderer** [comment]
Wondering if this is a browser-specific issue to pinpoint. This bug does not appear in Chrome, Firefox, or Opera.

**Comment by rohitguptaa22** [comment]
it is working fine in chrome and edge as well, might be browser specific

**Comment by corwintines** [comment]
Hmm thanks for investigating @TylerAPfledderer @rohitguptaa22. Sounds like @wackerow will pick it up.

I am able to reproduce in brave on mobile. I think it might be something to do with the hero.

**Comment by wackerow** [comment]
Ended up being text that wasn't wrapping within the table at the bottom, and within the ButtonLink in the ShanghaiCapella component. Patched in #9482
