### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by OffcierCia** [ethereum/ethereum-org-website#9468]
### Dev tool name

pessimistic.io

### Dev tool description

The team behind Pessimistic helps blockchain startups meet modern security challenges since 2017

### When did the dev tool go live?

2016

### Where do you think this page should be shown?

High tempo and risks of contemporary DeFi-development make security expensive and clumsy. We solve this problem by helping blockchain startups to keep their code and development processes consistent and secure.

### Is the product open source?

No

### GitHub URL

https://github.com/pessimistic-io/audits

### Documentation URL

https://github.com/pessimistic-io/audits

**Comment by corwintines** [comment]
Hey @OffcierCia. Thanks for opening this. 

Is your suggestion here to be listed with other audit services [here](https://ethereum.org/en/developers/docs/smart-contracts/testing/#smart-contract-auditing-services)

Once I understand what you are looking for I will review. Thanks.

**Comment by OffcierCia** [comment]
Hello! Yes, that is true.


D8E452ED 8213DDF3 863DDD96 1F8DCEB2 9617D53A


Sent with Proton Mail secure email.

------- Original Message -------

**Comment by OffcierCia** [comment]
Up 🙂
