### ISSUE TITLE
Suggest a Layer 2 - Metis

### ISSUE THREAD

**Issue by 0x000hx** [ethereum/ethereum-org-website#9472]
### Name

Metis

### Logo

![image](https://user-images.githubusercontent.com/118819912/216794563-905b17ae-d811-44b4-be4f-4fc057384f2f.png)

### Description

Metis is an Ethereum Layer 2 solution building a framework for open, decentralized and trustless collaboration.

### Website

metis.io

### Developer documentation

https://docs.metis.io/dev

### L2BEAT page

https://l2beat.com/scaling/projects/metis

### Is the project open source?

Yes, it is open source, link:
https://github.com/MetisProtocol

### What category of layer 2 is it?

Optimistic Chain

### Does the layer 2 use Ethereum Mainnet for data availability?

The Merkle Tree Roots derived from transaction data are stored on Ethereum Mainnet, the transaction data is stored on decentralized storage Memolabs.

### Which bridges are used to onboard users?

Here is the list:
1. Official bridge -- https://bridge.metis.io/home
2. Synapse -- https://synapseprotocol.com/landing
3. Poly Network -- https://bridge.poly.network/
4. Celer -- https://cbridge.celer.network/#/transfer
5. BoringDAO -- https://oportal.boringdao.com/
6. Relay Chain -- https://app.relaychain.com/#/cross-chain-bridge-transfer
7. O3 Swap -- https://o3swap.com/bridge
8. Multichain -- https://app.multichain.org/#/router
9. Stargate -- https://stargate.finance/transfer

### Which exchanges offer support for the project?

The Metis Andromeda network is currently supported on:

1. OKX -- https://www.okx.com/trade-spot/metis-usdt
2. Kucoin -- https://www.kucoin.com/trade/METIS-USDT?spm=kcWeb.B1homepage.Header4.1
3. Gate_io -- https://www.gate.io/trade/METIS_USDT
4. Bitget -- https://www.bitget.com/en/spot/METISUSDT_SPBL
5. MEXC -- https://www.mexc.com/exchange/METIS_USDT

ERC20 Supported
1. Coinbase -- https://pro.coinbase.com/trade/METIS-USDT
2. Crypto.com -- https://crypto.com/price/metisdao
3. Lbank -- https://www.lbank.com/en-US/trade/metis_usdt/

Layer 2 Decentralized Exchanges
1. NetSwap DEX - https://netswap.io/
2. Tethys - https://tethys.finance/
3. Hummus --https://www.hummus.exchange/
4. Hermes -- https://hermes.maiadao.xyz/#/swap
5. Hera.finance -- https://app.hera.finance/#/swap
6. Uniswap -- https://coinmarketcap.com/dexscan/ethereum/0x1c98562a2fab5af19d8fb3291a36ac3c618835d9 
7. Pancakeswap - https://coinmarketcap.com/dexscan/bsc/0x69afe59e88614501c3fdeb7480f12dba0a414032

### Link to dapp ecosystem (if applicable)

https://metis.io/ecosystem

### What date did the project go live?

November 19 2021

### Is this project a fork? If yes, which project was forked?

Yes, it is a fork of Optimism's L2 solution

### What wallets support this layer 2?

Most of multichain web3 wallets such as MetaMask/Trust wallet and hardwallets like Ledger.

### How can users and/or developers connect too this layer 2 network?

RPC URL: https://andromeda.metis.io/?owner=1088
Chain ID: 1088
Currency Symbol: METIS

### Has this project undergone an external security audit and/or a bug bounty?

Audits:
1. Hacken - [Smart Contract Code Review and Security Analysis Report](https://drive.google.com/file/d/1AHDVzVUcRh8ghmfLR8qRfaHpgML7v9vW/view)
2. Slowmist - [Metis Network Security Audit Report](https://drive.google.com/file/d/1d6tjopE25mN50ByLacX8IpoIuWSGKwQ8/view)
3. Armor Labs - [Metis Portal Contract Audit](https://drive.google.com/file/d/1yv_PBW-hanMoB50gan4zB2QKsEKNxyOO/view
)

Bug bounty: 
1. Immunefi -- https://immunefi.com/bounty/metis

### Has the project sustained its users over time?

TVL:
Current -- $154,000,000+
Peak -- $740,000,000+

Total Transactions: 4,600,000+
Total wallets: 105,000+

### Is there an active team developing the project?

Yes

### Is there a block explorer?

https://andromeda-explorer.metis.io/

**Comment by samajammin** [comment]
> What category of layer 2 is it?
> Optimistic Chain

We currently currently list any "Optimistic Chain"s on our Layer 2 page. You can view what categories we list here: https://ethereum.org/en/contributing/adding-layer-2s/

From my understanding Metis still doesn't use Ethereum for data availability - see discussion here: #6190

How would you define an Optimistic Chain? Are you suggesting we add Optimistic Chains to the site? If so, maybe that should be an independent issue/discussion.

**Comment by corwintines** [comment]
Given that Metis isn't using Ethereum for data availability, I still think this shouldn't be listed on the layer 2 page. This is something required in the listing policy and the same reason we don't list any Validiums on there. However, I think we should make an Optimistic Chain's page for the scaling section where this would be appropriate. Would this be something you would be open to contributing to @xcvoierg?

**Comment by xcvoierg** [comment]
@samajammin @corwintines Hello! Yes, I would like to try and contribute to the Optimistic Chain page. Could you please provide the steps for it?

**Comment by corwintines** [comment]
Apologies for letting this go stale @0x000hx. 

I have created an issue for this https://github.com/ethereum/ethereum-org-website/issues/11105 in regards to creating a page on Opimium (I see this is the new term used by L2BEAT). Im going to close this issue out for now in favor of getting this page written first. If you are still interested, let me know in that other issue :)

**Comment by 0x000hx** [comment]
> Apologies for letting this go stale @0x000hx.
> 
> I have created an issue for this #11105 in regards to creating a page on Opimium (I see this is the new term used by L2BEAT). Im going to close this issue out for now in favor of getting this page written first. If you are still interested, let me know in that other issue :)

Hello, 
Our roadmap has changed -- we will come back to native OPR this year (will post the tx data on L1),
