### ISSUE TITLE
Suggest a tutorial

### ISSUE THREAD

**Issue by dcbuild3r** [ethereum/ethereum-org-website#9476]
### Tutorial title

devpill.me

### Tutorial description

[devpill.me](https://devpill.me/) is a public good blockchain development guide built by me ([dcbuilder](https://twitter.com/DCbuild3r)) and a few contributor friends. It contains short guides on different topics which in turn aggregate resources to learn more about the given topics. These are the currently available sections.
<img width="330" alt="Screenshot 2023-02-11 at 18 01 49" src="https://user-images.githubusercontent.com/19372745/218270869-27f6d5d4-17eb-42e3-9ff2-55fdeef646b9.png">
The repo for the website which contains all of the content is open-source and can be found [here](https://github.com/dcbuild3r/devpill.me). I plan on updating the guide here and there with new things I learn, but I'd love for it to be updated with resources gathered by different members of the Ethereum community.

### Tutorial tags

ethereum, front-end, back-end, smart contracts, solidity, Cairo, Starknet, cryptography, soft skills in the blockchain space

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://devpill.me/

**Comment by corwintines** [comment]
This seems like a good addition. Will open up a PR for this to be an external tutorial resource. Thanks @dcbuild3r!
