### ISSUE TITLE
Add `rust-web3` to depricated software list

### ISSUE THREAD

**Issue by jakehemmerle** [ethereum/ethereum-org-website#9484]
### Is your feature request related to a problem? Please describe.

Author has said they aren't going to maintain it: https://github.com/tomusdrw/rust-web3/issues/664

This hasn't had a merged PR in almost a year, and there are tons of issues open. I encountered this when I realized it doesn't support serializing/deserializing RLP encoding, while ethers does.

### Describe the solution you'd like

Add `rust-web3` to deprecated list

### Describe alternatives you've considered

use `ethers`: https://docs.rs/ethers/latest/ethers/index.html

**Comment by corwintines** [comment]
Thanks @jakehemmerle! I think for now we can just remove the mentions of this project from the repo. Ill open a PR up for that now.
