### ISSUE TITLE
Bug report small typo in Alchemy URL learning tool

### ISSUE THREAD

**Issue by 0xSilkweave** [ethereum/ethereum-org-website#9504]
### Describe the bug

The Alchemy learning tool URL is missing a "." causing the link to not work properly.

Easy fix by changing [learning-tools.tsx](https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/developers/learning-tools.tsx).

### To reproduce

/

### Expected behavior

/

### Screenshots

<img width="348" alt="image" src="https://user-images.githubusercontent.com/123412102/219461634-7e081627-cbb7-4590-ac97-bc076d0d5a5e.png">

**Comment by corwintines** [comment]
Closing as this was resolved in above PR :)
