### ISSUE TITLE
Prioritization of search results needs improvements 

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9529]
### Describe the bug

Some of the search results are suboptimal and the order of results should be modified. Examples:

- [ ] translation guide links should not be before “How to” guides
- [x] “eth” search should not suggest the assets page as the first result

**BUG**

- [x] - a quotation mark symbol is not allowed in search? shows like a code in UI (see screenshot)

### To reproduce

1. Go to ethereum.org
2. Click on search 
3. Start typing eg. "eth"

### Expected behavior

Top results should reflect the most common user needs.

### Screenshots

<img width="496" alt="Screenshot 2023-02-20 at 15 49 42" src="https://user-images.githubusercontent.com/100724231/220130989-94165234-30b2-4789-bc77-d64a26277ab9.png">
<img width="558" alt="Screenshot 2023-02-20 at 15 49 48" src="https://user-images.githubusercontent.com/100724231/220131004-c8840453-3c42-46fe-b4eb-b8c0eeea91c2.png">
<img width="517" alt="Screenshot 2023-02-20 at 15 49 53" src="https://user-images.githubusercontent.com/100724231/220131018-d031b8ef-1b65-4e6d-b3e6-2735f0039644.png">

**Comment by vishal590** [comment]
Hi @konopkja, can I work on this issue ?

**Comment by konopkja** [comment]
> 
actually this intro to ethereum is problematic as it sends user to "EVM", i suspect the anchor works wrongly because "ETH" term is above it but its hidden, instead i see EVM description as seen on the screenshot.

That being said i dont think ideally this developer docs page should be the first result anyway.

<img width="733" alt="Screenshot 2023-08-04 at 12 00 44" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/69624f77-192f-4eeb-b5fd-5e1874b07dc2">
<img width="809" alt="Screenshot 2023-08-04 at 12 01 18" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/82c63b35-3b3a-4fec-a226-5f738f5401d6">

**Comment by konopkja** [comment]
<img width="703" alt="Screenshot 2023-08-04 at 12 03 01" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/33aa26f2-ee81-4311-a564-4b30617e1745">

searching for "ethereum" also shows results that are probably more technical than should be

**Comment by konopkja** [comment]
<img width="651" alt="Screenshot 2023-08-04 at 12 05 17" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/ee2fb6ee-7674-4763-a8c2-dae3067cdcdc">
 
this ideally should show how to guide first

**Comment by corwintines** [comment]
This seems like we have made improvements from the migration to DocSearch, so going to close this out. If there are any more specific issues that you see Jakub, maybe we can open up a new issue to address those there given we have changed how we do search since this opened.
