### ISSUE TITLE
Uniswap dead links

### ISSUE THREAD

**Issue by Dom-Mac** [ethereum/ethereum-org-website#9533]
### Describe the bug

Dead links to Uniswap documentation

### To reproduce

Example:
1. Go to [Oracle](https://ethereum.org/en/developers/docs/oracles/)
2. Click on [TWAP](https://docs.uniswap.org/protocol/V2/concepts/core-concepts/oracles)
3. See error

### Expected behavior

Functional link

**Comment by vishal590** [comment]
@konopkja can I work on this issue ?

**Comment by Dom-Mac** [comment]
There is already a PR opened. Fixed #9532
