### ISSUE TITLE
Suggest a page: Distributed Validator Technology

### ISSUE THREAD

**Issue by plotnikov-blox** [ethereum/ethereum-org-website#9536]
This is an all encompassing page that describes Distributed Validator Technology (DVT). The page covers what DVT is, why we need it, components & how they distribute a validator's operation, as well as its use cases. Since the first DVT implementation is nearing completion (as per Vitalik's roadmap) I suggest that the page be added to explain this critically important technology.

**Comment by plotnikov-blox** [comment]
The page is completed so please assign it to me

**Comment by jmcook1186** [comment]
Hi - you are very welcome to raise a PR - we might be interested in a page on DVT, but it will have to be reviewed by the team and be a good fit for the site. We generally work with collaborators to craft pages specifically for the site rather than incorporating pre-written material as-is.
