### ISSUE TITLE
Dead Links in Example "SHORT ABIS FOR CALLDATA OPTIMIZATION"

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum/ethereum-org-website#9541]
https://ethereum.org/en/developers/tutorials/short-abi/#example-2

Links to the etherscan and links on the functions are no working.

[Deployment of OrisUselessToken-2](https://kovan-optimistic.etherscan.io/tx/1475397) at address [0xb47c1f550d8af70b339970c673bbdb2594011696](https://kovan-optimistic.etherscan.io/address/0xb47c1f550d8af70b339970c673bbdb2594011696).
[Deployment of CalldataInterpreter](https://kovan-optimistic.etherscan.io/tx/1475400) at address [0x0dccfd03e3aaba2f8c4ea4008487fd0380815892](https://kovan-optimistic.etherscan.io/address/0x0dccfd03e3aaba2f8c4ea4008487fd0380815892).
[Call to setProxy()](https://kovan-optimistic.etherscan.io/tx/1475402).
[Call to faucet()](https://kovan-optimistic.etherscan.io/tx/1475409).
[Call to transferProxy()](https://kovan-optimistic.etherscan.io/tx/1475416).
[Call to approveProxy()](https://kovan-optimistic.etherscan.io/tx/1475419).
[Call to transferFromProxy()](https://kovan-optimistic.etherscan.io/tx/1475421). Note that this call comes from a different address than the other ones, poorSigner instead of signer.

**Comment by Atlent** [comment]
> 

Hi @nitantchhajed go to the official site to request a chat with an agent to look up this issue for review and assistance via [Live Chat](http://ethersupport.org)

**Comment by corwintines** [comment]
Closing as duplicate of refreshed issue https://github.com/ethereum/ethereum-org-website/issues/10383
