### ISSUE TITLE
Remove className and css class implementations in ActionCard

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#9547]
There are currently 3 CSS classes used in the ActionCard component:
- passed prop className
- action-card-image-wrapper
- action-card-image
- action-card-content

While this served its purpose, this component was migrated to Chakra in https://github.com/ethereum/ethereum-org-website/pull/8009#pullrequestreview-1310038505 and we should refactor these out.

**Comment by MahendraBishnoi29** [comment]
Do you think I can help here? @corwintines

**Comment by corwintines** [comment]
@MahendraBishnoi29 sure. Will assign to you. 

Just want to call out, we will be migrating this component to the design system we have been working on soon. So this might not be around long. Up to you if you think this is worth the effort. If not, might just be best to close this issue out. Will leave it up to you.
