### ISSUE TITLE
Suggest a wallet: Taho

### ISSUE THREAD

**Issue by chlolands** [ethereum/ethereum-org-website#9560]
### Wallet name

Taho

### Wallet description

Imagine a community-owned wallet that actually embodies and protects Web3 values—a wallet that’s available to anyone, anywhere on Earth, that can finance itself, that’s governed by a DAO, and that’s accountable to you, not some faceless corporation. Meet Taho: the world’s first community-owned wallet that makes it safe and easy to connect to the decentralized web. 

### Wallet logo

![Avatar](https://user-images.githubusercontent.com/95715502/221033622-fb606b37-93f1-485b-9ce5-59b92f756033.png)

### Background color for brand logo

FDAE49

### URL to the project

https://taho.xyz

### When did the wallet go live to users?

12/20/21

### Does the wallet have an active development team?

https://github.com/tallycash/extension

### Is the wallet globally accessible?

Yes, there are no KYC requirements. 

### Is the wallet available in multiple languages?

Currently, it's only available in English, but translations are in progress!

### What social links are there for the project?

[Discord](chat.taho.xyz)
[Twitter](twitter.com/taho.xyz)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

We do not have a mobile app at this time. 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

We do not have a desktop app at this time. 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

The Taho browser extension can be downloaded for Chrome + Brave [here.](https://chrome.google.com/webstore/detail/taho/eajafomhmkipbjmfmhebemolkcicgfmd)

### Is it a hardware wallet?

Taho itself is not a hardware wallet, but we do offer [full Ledger hardware support.](https://blog.taho.xyz/a-ledger-integration-you-can-love/)

### Is the source code for the wallet fully open-source?

Yes, https://github.com/tallycash/extension. 

### What license is the wallet software released under?

GPLv3, https://github.com/tallycash/extension/blob/main/LICENSE

### Who holds the private keys?

Only users hold their private keys. If the project were to disappear, users could plug their keys into another wallet.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We had a [Least Authority Audit](https://leastauthority.com/blog/audit-of-tally-browser-extension-wallet-key-handling-for-ylvis-llc/) conducted on 4/13/22. The audit was a limited scope review of Tally’s [hd-keyring](https://github.com/tallycash/hd-keyring) repository, which contains the code responsible for generating and managing users’ private keys.

### Has the wallet's smart contract code or security modules been audited?

Our smart contract code has been audited 4 times, but we haven't yet one public with our smart contracts.

### Does the wallet have an internal security team?

We do not at the moment. 

### Any other security testing that should be noted?

Our Swaps contract has been [audited.](https://code4rena.com/reports/2021-10-tally) We’ve had 2 additional audits on our token contracts that will be published soon.

### Scam protection?

Please refer to our [Privacy Policy](https://taho.xyz/privacy/#ThirdPartyLinks), updated as of February 2023. 

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

 Not yet but it's in the roadmap; we currently use Alchemy and will be adding POKT later this year.

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes. Users can connect to dapps via:https://tahowallet.notion.site/Taho-Knowledge-Base-4d95ed5439c64d6db3d3d27abf1fdae5

### Does the wallet support staking directly?

No.

### Does the wallet support swaps directly?

Yes!

### Does the wallet support multi-chain networks?

Yes!

### Does the wallet support Ethereum layer 2 networks?

Yes! We support Arbitrum, Polygon, and Optimism. 

### Does the wallet allow the user to customize gas fees?

No.

### Does the wallet support sending transactions to ENS addresses?

Yes!

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes! Add a token [here.](https://github.com/tahowallet/token-list/issues?ref=blog.taho.xyz)

### Does the wallet support EIP-1559 (type 2) transactions?

No.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No.

### Does the wallet support withdrawals to fiat?

No.

### Is the wallet a multi-signature wallet?

No.

### Does the wallet support social recovery?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

[Nax, GTM Lead](https://twitter.com/naxsun3301)
[Chloe, Content + Social ](https://twitter.com/regenbruja)
[Alex, Tech Lead](https://twitter.com/0xDaedalus)
[Michael Haley, Head of Product ](https://twitter.com/rhizo_michael)

### Does the wallet have a dedicated support team?

Head to #bug-reports in our [Discord.](chat.taho.xyz)

### What educational resources/documentation do you provide to users?

https://tahowallet.notion.site/Taho-Knowledge-Base-4d95ed5439c64d6db3d3d27abf1fdae5

### Does the wallet have any integrated tools not mentioned above?

Tabbed Onboarding, Daylight notifications of in-wallet "abilities"

**Comment by corwintines** [comment]
Will review in https://github.com/ethereum/ethereum-org-website/issues/9561 as it looks more up to date with links.
