### ISSUE TITLE
Suggest a wallet: Taho

### ISSUE THREAD

**Issue by chlolands** [ethereum/ethereum-org-website#9561]
### Wallet name

Taho

### Wallet description

Imagine a community-owned wallet that actually embodies and protects Web3 values—a wallet that’s available to anyone, anywhere on Earth, that can finance itself, that’s governed by a DAO, and that’s accountable to you, not some faceless corporation. Meet Taho: the world’s first community-owned wallet that makes it safe and easy to connect to the decentralized web. 

### Wallet logo

![Avatar](https://user-images.githubusercontent.com/95715502/221033622-fb606b37-93f1-485b-9ce5-59b92f756033.png)

### Background color for brand logo

FDAE49

### URL to the project

https://taho.xyz

### When did the wallet go live to users?

12/20/21

### Does the wallet have an active development team?

https://github.com/tahowallet/extension

### Is the wallet globally accessible?

Yes, there are no KYC requirements. 

### Is the wallet available in multiple languages?

Currently, it's only available in English, but translations are in progress!

### What social links are there for the project?

[Discord](chat.taho.xyz)
[Twitter](twitter.com/taho.xyz)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

We do not have a mobile app at this time. 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

We do not have a desktop app at this time. 

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

The Taho browser extension can be downloaded for Chrome + Brave [here.](https://chrome.google.com/webstore/detail/taho/eajafomhmkipbjmfmhebemolkcicgfmd)

### Is it a hardware wallet?

Taho itself is not a hardware wallet, but we do offer [full Ledger hardware support.](https://blog.taho.xyz/a-ledger-integration-you-can-love/)

### Is the source code for the wallet fully open-source?

Yes, https://github.com/tahowallet/extension

### What license is the wallet software released under?

GPLv3, https://github.com/tahowallet/extension/blob/main/LICENSE

### Who holds the private keys?

Only users hold their private keys. If the project were to disappear, users could plug their keys into another wallet.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We had a [Least Authority Audit](https://leastauthority.com/blog/audit-of-tally-browser-extension-wallet-key-handling-for-ylvis-llc/) conducted on 4/13/22. The audit was a limited-scope review of Tally’s [hd-keyring](https://github.com/tallycash/hd-keyring) repository, which contains the code responsible for generating and managing users’ private keys.

### Has the wallet's smart contract code or security modules been audited?

Our smart contract code has been audited 4 times, but we haven't yet gone public with our smart contracts.

### Does the wallet have an internal security team?

We do not at the moment. 

### Any other security testing that should be noted?

Our Swaps contract has been [audited.](https://code4rena.com/reports/2021-10-tally) We’ve had 2 additional audits on our token contracts that will be published soon.

### Scam protection?

Please refer to our [Privacy Policy](https://taho.xyz/privacy/#ThirdPartyLinks), updated as of February 2023. 

### Does the wallet support connecting to a hardware wallet?

Yes, Ledger.

### Does the wallet support WalletConnect?

Not at the moment, but adding support very soon.

### Does the wallet support importing Ethereum RPC endpoints?

 Not yet but it's in the roadmap; we currently use Alchemy. 

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

Yes. Users can connect to dapps by selecting Taho as the option to connect(when available) or via the Metamask, Injected or Web3 Wallet option if Taho is set to default.tps://tahowallet.notion.site/Taho-Knowledge-Base-4d95ed5439c64d6db3d3d27abf1fdae5

### Does the wallet support staking directly?

Not at the moment.

### Does the wallet support swaps directly?

Yes! https://github.com/tahowallet/extension/tree/swapstick-qa-build

### Does the wallet support multi-chain networks?

We currently support BNB Chain, Avalanche and Rootstock.

### Does the wallet support Ethereum layer 2 networks?

We currently support Polygon, Optimism, and Arbitrum. 

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes, Taho has full ENS and UNS domain support.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Not yet but its in the roadmap; we do have a[ community-maintained token list. ](https://github.com/tahowallet/token-list)

### Does the wallet support EIP-1559 (type 2) transactions?

Yes. 

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

No.

### Does the wallet support withdrawals to fiat?

No.

### Is the wallet a multi-signature wallet?

Connect to Gnosis Safe.

### Does the wallet support social recovery?

No.

### Who can the ethereum.org team can contact regarding the wallet in future?

Head of Product: [Michael Haley ](https://twitter.com/rhizo_michael)
Lead Engineer: [Alex Bazenhov](https://twitter.com/0xDaedalus)
Marketing: [LJ Jackson](https://twitter.com/alsoknownasLJ), [Chloe Anderson](twitter.com/regenbruja), [Naxsun](https://twitter.com/naxsun3301)

### Does the wallet have a dedicated support team?

Users should report bugs in the #bug-reports room on our [Discord.](chat.taho.xyz)

Members of our core team, as well as mods, are available to help users troubleshoot any issues.

### What educational resources/documentation do you provide to users?

[Taho Knowledge Base](https://tahowallet.notion.site/Taho-Knowledge-Base-4d95ed5439c64d6db3d3d27abf1fdae5)

### Does the wallet have any integrated tools not mentioned above?

Get notified of in-wallet abilities via [Daylight](https://blog.taho.xyz/daylight-integration-announcement/) ☀️
View account balances across all networks via the _Portfolio_ tab. 
View accounts in [_Read-Only_](https://blog.taho.xyz/web3-through-the-looking-glass-tally-hos-read-only-mode/) mode without entering a recovery phrase. 
[Easily change account names, add + remove addresses linked to recovery phrases, and track account balances.](https://blog.taho.xyz/sections-for-accounts/)
[Import multiple recovery phrases](https://blog.taho.xyz/importing-multiple-recovery-phrases/)
View all assets across networks via the [_Portfolio_ ](View All Your Assets with Tally Ho’s Portfolio) tab

**Comment by corwintines** [comment]
Sorry for delay @chlolands. I have made a PR for this. Should be in next release (Tuesday).
