### ISSUE TITLE
Earth Wallet

### ISSUE THREAD

**Issue by everhusk** [ethereum/ethereum-org-website#9564]
### Wallet name

Earth Wallet

### Wallet description

Earth Wallet is the self-custody Ethereum staking wallet for those who want to earn rewards while keeping full control over their assets. Safely stake, manage, and grow your Ethereum holdings anywhere on Earth with ease.

### Wallet logo

![Mark](https://user-images.githubusercontent.com/4977840/221052742-52531a2f-11db-44f7-9c1b-1e7d14aac121.png)

### Background color for brand logo

#0F1726

### URL to the project

earthwallet.io

### When did the wallet go live to users?

July 2021

### Does the wallet have an active development team?

Yes [github.com/earthwallet](github.com/earthwallet)

### Is the wallet globally accessible?

Available everywhere on Earth

### Is the wallet available in multiple languages?

Yes, (AR, BN, EN, ES, FE, HI, MR, RU, SW, TA, TE, TH, UR, VI, and ZH)

### What social links are there for the project?

[twitter.com/earthwallet](twitter.com/earthwallet)
[instagram.com/earthwallet.io](instagram.com/earthwallet.io)
[t.me/earth_wallet](t.me/earth_wallet)

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes we support [iOS](https://apps.apple.com/us/app/earth-wallet/id1638414929) and [Android](https://play.google.com/store/apps/details?id=earth.wallet.app).

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No.

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

Yes, we support Chromium and Firefox.

### Is it a hardware wallet?

No.

### Is the source code for the wallet fully open-source?

Yes [github.com/earthwallet/wallet](github.com/earthwallet/wallet)

### What license is the wallet software released under?

GNU General Public License v3.0.

### Who holds the private keys?

Users are in full control of their public keys (creation/import/export) on their own devices, and the company/project has no access whatsoever. If the company were to disappear, users would still be able to access their funds.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

We just completed our code freeze of version 1, and will be conducting full security audits with Trail of Bits in April.

### Has the wallet's smart contract code or security modules been audited?

We do not have any smart contract code or security modules in the wallet.

### Does the wallet have an internal security team?

Yes, our team has over a decade of experience building and securing over $1B in digital assets (TradFi, CEXs, and DeFi).

### Any other security testing that should be noted?

We have applied best practices from our experience working as senior software engineers at TD Bank, LedgerX, and several DeFi protocols securing over $1B in TVL.

### Scam protection?

When a user connects their wallet to a dApp, the Earth Wallet user interface will present clear information about:
a) the contract address
b) the data/signature being requested
c) uses wallet connect v2 best practices

### Does the wallet support connecting to a hardware wallet?

It is on the roadmap.

### Does the wallet support WalletConnect?

Yes, both WalletConnect v1 and v2.

### Does the wallet support importing Ethereum RPC endpoints?

It is on the roadmap.

### Does the wallet support viewing and interacting with NFTs?

Yes, both viewing and sending/receiving with auto-discovery.

### Does the wallet support connecting to Ethereum applications?

Yes, users can connect using wallet connect v2 on all platforms (iOS, Android, and Chrome) via QR code or browser.

### Does the wallet support staking directly?

Yes Earth Wallet will support Earth Ether, a new decentralized ethereum staking protocol natively in April 2022.

### Does the wallet support swaps directly?

It is planned in a future release.

### Does the wallet support multi-chain networks?

Yes, Earth Wallet support Bitcoin, Dogecoin, Polygon, and ICP. With Optimism support coming soon.

### Does the wallet support Ethereum layer 2 networks?

Yes. Polygon, and optimism soon.

### Does the wallet allow the user to customize gas fees?

Yes. Users can select from 3 options or customize.

### Does the wallet support sending transactions to ENS addresses?

Yes, Earth Wallet supports ENS and unstoppable domain address resolution and reverse resolution.

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes, it supports automatically displaying ERC20 tokens.

### Does the wallet support EIP-1559 (type 2) transactions?

Yes.

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Not directly, but users can connect to dapps that do this.

### Does the wallet support withdrawals to fiat?

Not directly, but users can connect to dapps that do this..

### Is the wallet a multi-signature wallet?

It is a planned release later this year.

### Does the wallet support social recovery?

It is a planned release later this year.

### Who can the ethereum.org team can contact regarding the wallet in future?

You can reach our team at t.me/earthwallet, in our support channel for real time support, or twitter.com/sukhveer for any more private questions. Or via email at support@earthwallet.io.

### Does the wallet have a dedicated support team?

Yes, we are always providing support via the telegram support channel, t.me/earthwallet. Or via email at support@earthwallet.io.

### What educational resources/documentation do you provide to users?

We provide full documentation of all features and how-tos [here](https://docs.earthwallet.io).

### Does the wallet have any integrated tools not mentioned above?

We support push notifications for new transactions, and plant a tree for every new account that is created!

**Comment by corwintines** [comment]
@everhusk just wanted to follow up on this. I saw you were getting a security audit in April, I wanted to follow up on this. These are very important  for being able to review a listing as it lets us see if there has been followup addressing any security vulnerabilities.

**Comment by everhusk** [comment]
Hi @corwintines thanks for following up! We are just wrapping up our audit with Halborn this month, I'll drop it here for your consideration as soon as possible.

**Comment by corwintines** [comment]
Thanks @everhusk

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by corwintines** [comment]
Haven't gotten follow up on security audit. Going to close.

**Comment by everhusk** [comment]
Hi @corwintines,

Apologies on the delay, took a bit longer than originally expected to complete everything. The security audit for Earth Wallet is now completed, and all issues fully resolved and deployed to production.

Please see below for the full report.

[Earth_Wallet_Android_iOS_Mobile_App_Pentest_Report_Halborn_Final.pdf](https://github.com/ethereum/ethereum-org-website/files/13497580/Earth_Wallet_Android_iOS_Mobile_App_Pentest_Report_Halborn_Final.pdf)
