### ISSUE TITLE
Add to DeSci Further Reading

### ISSUE THREAD

**Issue by PaigeDAO** [ethereum/ethereum-org-website#9593]
### Is your feature request related to a problem? Please describe.

I'd like to add this explanation of DeSci to the further reading section of the DeSci page. It is written for general audiences rather than specialized blockchain-literate or science audiences. As DeSci (and Open Science) gain traction, I feel it's important to be inclusive in our language and messageing, too. 

### Describe the solution you'd like

Please add this link to Further Reading Section on DeSci: 
[​https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/](https://usadailytimes.com/2022/09/12/what-is-desci-decentralized-science/)   by Paige Donner

### Describe alternatives you've considered

I suppose the alternative is to continue to leave out this more inclusive messaging about DeSci.

**Comment by PaigeDAO** [comment]
Hi, as the first female co-founder of a DeSci DAO, I'd like to contribute to this discussion, too. (FrontierDAO). Thank you

**Comment by corwintines** [comment]
Thanks @PaigeDAO 

I read through the article, and I am not really seeing how this is more inclusive than what is currently there. A lot of the content in the article is already covered on this page as well in regards to IP NFT's which is mainly what this article hits on. I don't think this really adds or supplements the content on the page as it currently stands. Im going to close this out, but feel free to reopen if you disagree and we can discuss further.

**Comment by PaigeDAO** [comment]
Yes re-opening.  The central focus of this article is on blockchain use case for publishing scientific research.  It is also primarily an audio piece. So if you @corwintines didn't get the chance to listen to the audio, you may have missed the core content of the piece?
