### ISSUE TITLE
Navbar items are not visible

### ISSUE THREAD

**Issue by amit-ksh** [ethereum/ethereum-org-website#9606]
### Describe the bug

Navbar items are not visible for a small range of screen widths (`995px` - `1020px`).

### To reproduce

1. Go to [ethereum website](https://ethereum.org/en/)
2. Change the screen width to `1000px`
3. See error

### Expected behavior

**Navbar items should be visible**

### Screenshots

![image](https://user-images.githubusercontent.com/91947037/222060009-2cf672c3-234f-4148-bfbc-4af0cee3fa4c.png)

### Desktop (please complete the following information)

- OS: Windows 10
- Browser: Brave

**Comment by vishal590** [comment]
@corwintines could you assign this task to me ?

**Comment by corwintines** [comment]
Sorry @vishal590, I see @rohitt-gupta opened a PR for this

**Comment by vishal590** [comment]
@corwintines don't worry, I got one PR. Your already assigned me 👍
