### ISSUE TITLE
Suggest content: Ethereum use case for cross-border donations

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/ethereum-org-website#9607]
Recently Turkey and Syria were hit by two large earthquakes of magnitude 7.8 and 7.6. Over 50,000 people were killed and millions were left without shelter and basic needs. 

The crypto community quickly came together to globally collect funding for relief efforts. Different donation campaigns were launched by [Refik Anadol](https://twitter.com/refikanadol/status/1622623521104089090), [Anka Relief DAO](https://ankarelief.org/), [Bankless DAO & Giveth](https://twitter.com/Givethio/status/1623493672149843969), and [Pak](https://cause.quest/). Vitalik Buterin also donated to [different campaigns](https://cointelegraph.com/news/vitalik-buterin-donates-227k-to-help-earthquake-victims-in-turkey-syria). Although [crypto is not allowed as a payment](https://www.reuters.com/technology/no-more-kebabs-bitcoins-turkeys-crypto-payment-ban-looms-2021-04-28/) in Turkey, [an okay was given](https://twitter.com/haluklevent/status/1622913175409623041) for some organizations to collect donations. At least 6M $ was collected per [this Dune dashboard](https://dune.com/davy42/turkiye-earthquake-donations) following some of the addresses.

More info can be found here: https://turkiyereliefdao.org

Recalling the similar campaigns for [Ukraine](https://www.elliptic.co/blog/live-updates-millions-in-crypto-crowdfunded-for-the-ukrainian-military) and [India](https://cryptorelief.in/), I think this highlights an important use case for Ethereum: To be able to quickly raise donations against emergencies globally, which otherwise would require converting foreign currencies, sending them through SWIFT (if your bank supports it) which takes days to reach, and potentially paying really high transactions fees.

We can add some content about this on ethereum.org. I've found this section for Ethereum use cases but appreciate any suggestions where this fits better.

https://ethereum.org/en/learn/#what-is-ethereum-used-for

**Comment by corwintines** [comment]
Thanks @kuzdogan! Sorry for such a late response here.

@minimalsm @konopkja wondering if you have any input here. I know we mention cross border payments already on the ["What is Ethereum?" page](https://ethereum.org/en/what-is-ethereum/). 

@kuzdogan knowing this content exists here, would you also say this is addressed by that, or see a need for this content on other pages in addition?

**Comment by kuzdogan** [comment]
What I was referring to is actually the "The Quickest Help in Times of Crisis" part. I haven't seen that at the time, or it's added later. Maybe we can add Turkey earthquakes there? 

https://decrypt.co/120770/turkey-syria-earthquake-relief-cryptocurrency-fundraising

Otherwise we can close this.

**Comment by konopkja** [comment]
i think its worth adding a sentence around relief funds for earth quake crisis in turkey as its timely

**Comment by kuzdogan** [comment]
This went under the radar... Do you think it's still relevant and do you want to add this? I am not too strongly opinioned and don't have the peak motivation than a year ago honestly but it's still a very legit use case IMO. 

What I understood was to add it in this section, no?

<img width="487" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/13069972/2f32815b-5a65-4570-b954-56b07b4762b5">

**Comment by konopkja** [comment]
> This went under the radar... Do you think it's still relevant and do you want to add this? I am not too strongly opinioned and don't have the peak motivation than a year ago honestly but it's still a very legit use case IMO.
> 
> What I understood was to add it in this section, no?
> 
> <img alt="image" width="487" src="https://private-user-images.githubusercontent.com/13069972/329188020-2f32815b-5a65-4570-b954-56b07b4762b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTAyMjEsIm5iZiI6MTcxNTI0OTkyMSwicGF0aCI6Ii8xMzA2OTk3Mi8zMjkxODgwMjAtMmYzMjgxNWItNWE2NS00NTcwLWI5NTQtNTZiMDdiNDc2MmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEwMTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmODQ2YjI5YzNhNDNiYTJmYzU3ZmY0ZDI1MTE0ZDY4OWQyNTIwYmNiZGI5ZGU0M2ZlMGE4OGExNWRjYWUyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLScUxiBdSxxKgJCA0WKBD9C8eQR-lbHRjaUeNMafKY">

We have this section on what is ethereum that covers it i believe. Now adding it to the /learn page is a consideration too, but will need a link to some good overview article talking about crypto being used for relief donations.

![Screenshot 2024-05-10 at 12 00 58](https://github.com/ethereum/ethereum-org-website/assets/100724231/a0c659d0-52f9-412c-96e2-bdd096dfa4f7)

**Comment by corwintines** [comment]
In general this leads me to think we need a page on a very basic use case for Ethereum. Payments. This seems like a topic that could be covered on that page.

**Comment by konopkja** [comment]
i will close this issue and create a new one based on corwin's proposal

> Reference in new issue
