### ISSUE TITLE
Remove localcryptos from DEX page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#9619]
Unfortunately, localcryptos is winding down.

<img width="1246" alt="Screenshot 2023-03-02 at 11 51 01" src="https://user-images.githubusercontent.com/62268199/222420875-1d514027-77f0-4eb0-9ce3-cc34bad7122a.png">

We should remove localcryptos from this page. Ideally, we should replace it with something else if there is a reputable alternative (note: the alternative they suggest, localbitcoins, is also winding down).

**Comment by vishal590** [comment]
Please assign this task to me🙏🙏

**Comment by Nazeeh21** [comment]
I'd like to work on this.

**Comment by corwintines** [comment]
For now, I think we just remove it to call this done. I'm not sure of an alternative right now. 

@vishal590 assigning to you

**Comment by Pandapip1** [comment]
I think that Bisq is probably the best alternative.

**Comment by vishal590** [comment]
@corwintines please could you checkt this 
 I made changes but still no one checks it

**Comment by corwintines** [comment]
@vishal590 I don't see a PR for this, was it merged already?

**Comment by vishal590** [comment]
I did changes please check

**Comment by corwintines** [comment]
@vishal590 care to share the PR?
