### ISSUE TITLE
Broken Link on "What is Ethereum?"

### ISSUE THREAD

**Issue by Drblessing** [ethereum/ethereum-org-website#9645]
### Describe the bug

On the "[What is Ethereum?](https://ethereum.org/en/what-is-ethereum/)" page, there is a link to a broken website in the "Ethereum in numbers" section. The information bubble next to projects built on Ethereum has a Data Source link that is broken.

Broken Link:
Data Source: [State of the dapps](https://www.stateofthedapps.com/stats/platform/ethereum#new)

### To reproduce

1. Go to https://ethereum.org/en/what-is-ethereum/
2. Click on the information bubble next to "Projects built on Ethereum"
3. Click on the state of the dapps link

### Expected behavior

The link should link to a website that shows the number of dapps, or projects, running on Ethereum.

### Screenshots

Picture of broken link

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/52829488/223203664-501a9b1e-f35d-4cc7-bd5e-dd3749c4b1f7.png">

### Desktop (please complete the following information)

- OS: MacOS
- Browser: Brave
- Version: 1.48.171

**Comment by Drblessing** [comment]
I'd like to fix this issue and work with the community to find a new trusted, decentralized data source for "Projects built on Ethereum".

**Comment by MahendraBishnoi29** [comment]
@Drblessing I've already fixed this issue. here's PR #9474
