### ISSUE TITLE
Suggest a developer tool

### ISSUE THREAD

**Issue by 0x1992** [ethereum/ethereum-org-website#9665]
### Dev tool name

NFTScan

### Dev tool description

NFTScan is the world's largest NFT data infrastructure. NFTScan supports the full amount of NFT data of 12 blockchains including Ethereum, BNBChain, Polygon, Arbitrum, Optimism, Fantom, Avalanche, Solana, Moonbeam, Gnosis, Cronos and PlatON. NFTScan provides professional NFT data services for Web3 developers.

### When did the dev tool go live?

July 2021

### Where do you think this page should be shown?

[https://ethereum.org/en/enterprise/](https://ethereum.org/en/enterprise/private-ethereum/)

### Is the product open source?

No

### GitHub URL

https://github.com/nftscan-official

### Documentation URL

https://docs.nftscan.com/

### Additional context

NFTScan is the world's largest NFT data infrastructure. NFTScan supports the full amount of NFT data of 12 blockchains including Ethereum, Solana, BNBChain, Moonbeam, Polygon, Arbitrum, Optimism, Fantom, Avalanche, Gnosis, Cronos and PlatON. NFTScan currently serves over 200 Web3 projects, including CoinMarketCap、imToken, Safepal, BitKeep, Cyberconnect, Bybit, Mask Network, OneKey, DefiYield, Kucoin, Cobo, RSS3, and more.

NFTScan: https://nftscan.com/
Developer: https://developer.nftscan.com/
API Docs: https://docs.nftscan.com/
Twitter: https://twitter.com/nftscan_com

**Comment by corwintines** [comment]
Thanks @0x1992!

I don't think this belongs on the Enterprise page, that section of the site really needs to be reworked 😅 

But, I do see this as a resource on the /nft page for explorers. What do you think?
