### ISSUE TITLE
[roadmap content]: Tweak LH menu for readability

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#9673]
Two options:

a) tweak the component to have smaller fontsize or update the width
b) reduce the number of words in the subtitles

Either way, it's just an interim fix to improve the page aesthetic until the v2 design gets implemented

**Comment by seunbayo** [comment]
@jmcook1186  Any update? what is LH page so I can check for the perfect fix?

**Comment by jmcook1186** [comment]
Hi @seunbayo - the menu being referred to is the links on the left hand side of `ethereum.org/roadmap` directly underneath the **Ethereum Roadmap** title. I think the links look too big and we should either reduce the font size or the number of words in each title. @konopkja is ideating on a redesign of the page at the moment, so let's get his opinion before implementing a change.

**Comment by seunbayo** [comment]
I think reducing the number of words in each title would work. Awaiting @konopkja comment on it tho

**Comment by nloureiro** [comment]
Various observations to apply this quick fix before the Design System final changes:

1 - this needs to be fixed on all pages that use this layout, don't only on the roadmap
2- from the content side, it's crucial to keep title as shorter as possible. Not only for the layout but for accessability and easier readability.
3 - Let's keep the font size the same and adjust the content if possible. Changing the font size to accommodate the content is not a good practice. It needs to be the other way around.

With this in mind, my proposal for the quick fix is to align is to make all left aligned and 100% width. We can steal some pixels on the <ul> padding and make the navigation dropdown button 100% too.

I did it on the dev tools to check, and would look like this.
![Screen Shot 2023-04-06 08 57 03 AM](https://user-images.githubusercontent.com/1120748/230314977-14b98399-6bca-4258-b7ef-0223e591899f.png)
![Screen Shot 2023-04-06 08 56 48 AM](https://user-images.githubusercontent.com/1120748/230315012-c6893f79-9d13-449b-a40d-b8db1d01110f.png)
![Screen Shot 2023-04-06 08 56 38 AM](https://user-images.githubusercontent.com/1120748/230315018-9a6ec22a-d569-4552-82c8-b7adfc05c209.png)
![Screen Shot 2023-04-06 08 56 26 AM](https://user-images.githubusercontent.com/1120748/230315031-819afb12-feb9-47dc-a0f9-b9a846407a98.png)


for other pages would be like this

![Screen Shot 2023-04-06 08 57 45 AM](https://user-images.githubusercontent.com/1120748/230315249-5e393a65-bfba-41f7-88fc-e51ecea0a2c9.png)
![Screen Shot 2023-04-06 08 57 33 AM](https://user-images.githubusercontent.com/1120748/230315291-d8a1d18e-7419-45c3-992d-049be9794673.png)


@konopkja what do you think?

Question for @wackerow @minimalsm : the right alignment was a deliberate decision in the past? Am I missing anything here?

**Comment by konopkja** [comment]
agree with @nloureiro here, left alignment for the text will improve readability before we change the design in design system.

**Comment by seunbayo** [comment]
Thank you @konopkja  @nloureiro 

1. Left alignment for the text for all the concerned pages is noted


@jmcook1186 I think only the roadmap home text needs to be reduced as other pages are short enough,

**What I am proposing**
What changes are coming to Ethereum? <> Changes coming ETH
Why does Ethereum need a roadmap? <> Why ETH need a Roadmap
Will Ethereum's roadmap change over time? Will ETH roadmap change?
When will the roadmap be finished? <> Finished roadmap
Do I have to do anything when there is an upgrade? <> After the upgrade, what next
What about The Verge, The Splurge, etc? <> Verge|Spurge|Purge

What are your suggestions and opinions?

**Comment by seunbayo** [comment]
i think @jmcook1186  feedback is needed

**Comment by jmcook1186** [comment]
Hi, sorry I didn't realize I was blocking this.

I don't like swapping "Ethereum" for "ETH" because we are talking about Ethereum the network, not ETH the asset.
Also, the meaning changes when you replace "Do I have to do anything when there is an upgrade?" with "After the upgrade, what next".

I think left-aligning the text as suggested by @nloureiro and @konopkja above solves the majority of the issue.

**Comment by corwintines** [comment]
@nloureiro with the new design in production, do you think this is done?

**Comment by nloureiro** [comment]
@corwintines yes, it's done
