### ISSUE TITLE
Use `extendBaseTheme` instead of `extendTheme`

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#9679]
With this approach, we apply the theme for just the components we need or those that we have defined in our custom theme. The main benefit is that this will reduce the amount of JS we bundle, resulting in improved performance.

As a consequence of this change, we’ll need to check and update all the existing component theme configs to ensure that they maintain the same styles and avoid any unexpected visual changes.

**Comment by TylerAPfledderer** [comment]
@pettinarip have it assigned to me, please!
