### ISSUE TITLE
Markdown checkbox support

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#9680]
### Is your feature request related to a problem? Please describe.

Currently our markdown parser has limited support for checkboxes. Using the syntax `- [ ] ` at the start of a line results in rendering both a bullet point and an unchecked box, but this box is non-interactive. Removing the `-` breaks the syntax and `[ ]` is rendered instead of a checkbox.

### Describe the solution you'd like

Using `- [ ] ` syntax within markdown will default to an un-bulleted list of checkboxes that can be clicked/tapped to check and uncheck.

This was brought up in the context of the [style-guide discussion here](https://github.com/ethereum/ethereum-org-website/pull/9618#discussion_r1128805748), where we wanted to have boxes users could check off when reviewing their own content submissions.

### Describe alternatives you've considered

- Build a React component that is imported into the templates and used instead of the markdown syntax
- Opt to not have interactive checkboxes as an option

**Comment by corwintines** [comment]
Removing the stale tag to revive this issue
