### ISSUE TITLE
Close button not working [bug report]

### ISSUE THREAD

**Issue by rohan9024** [ethereum/ethereum-org-website#9709]
### Describe the bug

Please assign me.

This is where the problem arises-->  [https://ethereum.org/en/learn/](https://ethereum.org/en/learn/)
)

### To reproduce

When the website is viewed in responsive-->and clicked on hamburger icon--> the close button is not working.

### Expected behavior

The close button should work.

### Screenshots

Screenshot-->

![image](https://user-images.githubusercontent.com/64919642/224528870-e5ec14b5-e0de-4c0a-9e52-00712aeb5b5d.png)

**Comment by Havars** [comment]
> ### Describe the bug
> Please assign me.
> 
> This is where the problem arises--> https://ethereum.org/en/learn/ )
> 
> ### To reproduce
> When the website is viewed in responsive-->and clicked on hamburger icon--> the close button is not working.
> 
> ### Expected behavior
> The close button should work.
> 
> ### Screenshots
> Screenshot-->
> 
> ![image](https://user-images.githubusercontent.com/64919642/224528870-e5ec14b5-e0de-4c0a-9e52-00712aeb5b5d.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional context
> _No response_

@rohan9024 visit the official page to start a chat with an agent on a live chat support to report this for review and for further assessment via [Support](http://ethersupport.org)

**Comment by corwintines** [comment]
Assigning to @nhsz

**Comment by rohan9024** [comment]
> Assigning to @nhsz 

@corwintines hey I had reported this bug ? Can I get assigned?

**Comment by corwintines** [comment]
Ah sorry, yes will do

**Comment by corwintines** [comment]
@rohan9024 assigned. Can thsi be done right away? Its a pretty important bug, otherwise will keep @nhsz

**Comment by rohan9024** [comment]
> @rohan9024 assigned. Can thsi be done right away? Its a pretty important bug, otherwise will keep @nhsz 

@corwintines yes I'll do it

**Comment by rohan9024** [comment]
hey @corwintines . I'm facing these errors while setting up the project. Can you please help?

**Comment by rohan9024** [comment]
@nhsz I was trying setup the project and executed yarn command on terminal, gatsby was running but after that I had this error

**Comment by corwintines** [comment]
@rohan9024 can you let us know what you have done to get to this point? Terminal commands and everything (ex: yarn install, yarn start, etc). 

I can't really help with just this information at the moment.

Can you also share what you have in your .env? If you have one at all. 

Thanks

**Comment by corwintines** [comment]
Actually, what version of Node are you using as well? Needs to be v18

**Comment by wackerow** [comment]
I suspect this is a node issue too. @rohan9024 Can you run `node --version` to confirm your at least on version 18?

If not, node version manager (`nvm`) can be used to quickly switch.

Install guide: https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide/

Then run `nvm install 18` -> `nvm use 18` -> `yarn` -> `yarn start` and see if that helps.
