### ISSUE TITLE
Add content to ethereum.org/enterprise

### ISSUE THREAD

**Issue by tasdienes** [ethereum/ethereum-org-website#971]
Under Enterprise Focused Services
•	provide.services – Infrastructure and APIs for Enterprise Web3 applications 
(or maybe this should be under Protocol and Infrastructure since it’s adjacent to Infura?)

Under Protocol and Infrastructure
•	Baseline Protocol - an open source initiative that combines advances in cryptography, messaging, and blockchain to deliver secure and private business processes at low cost via the public Ethereum Mainnet.
https://www.baseline-protocol.org/ 

Should we consider adding a section or page listing enterprise applications that are live on Mainnet?  I have my own list that I’ve been keeping, but this could be challenging to keep up to date.

**Comment by samajammin** [comment]
> Should we consider adding a section or page listing enterprise applications that are live on Mainnet? I have my own list that I’ve been keeping, but this could be challenging to keep up to date.

Yes, I think we should! Any interest in taking a swing at drafting up this content @tasdienes?

**Comment by samajammin** [comment]
@all-contributors please add @tasdienes for ideas

**Comment by tasdienes** [comment]
Submitted PR #981 with the new content.
Ideally, I think we should separate the enterprise on mainnet stuff from the private chain enterprise stuff (and put more emphasis on the former).
