### ISSUE TITLE
Unwanted spacing [Minor Design Issue]

### ISSUE THREAD

**Issue by rohan9024** [ethereum/ethereum-org-website#9710]
### Describe the bug

Has unwanted space

Even the language cards are not taking up the whole space 

Please assign me this issue

### To reproduce

(https://ethereum.org/en/languages/?from=/learn/)](https://ethereum.org/en/languages/?from=/learn/)

### Expected behavior

Should have less spacing

### Screenshots

![image](https://user-images.githubusercontent.com/64919642/224529050-71698e11-5b54-472a-ac55-d05ff9e855fe.png)

![image](https://user-images.githubusercontent.com/64919642/224529211-a36502a3-f415-4f35-b620-bd401e8e44a3.png)

### Additional context

I'm using brave

**Comment by seunbayo** [comment]
@corwintines can i be assigned this?

**Comment by rohan9024** [comment]
@seunbayo already working on it

**Comment by seunbayo** [comment]
Alright @rohan9024

**Comment by corwintines** [comment]
@nloureiro will be looking into this for the design system, and will be handled in that body of work if any changes need to be made. Going to close this out.
