### ISSUE TITLE
Update new logo for Nexus Mutual dapp

### ISSUE THREAD

**Issue by clmnxm** [ethereum/ethereum-org-website#9726]
Please update the logo for Nexus Mutual dapp under Insurance at
https://ethereum.org/en/dapps/?category=finance

Nexus Mutual www.nexusmutual.io recently rebranded and has now a new logo that can be seen as well in github at https://github.com/NexusMutual

![Nexus_Mutual_logo_mark](https://user-images.githubusercontent.com/115262340/225263534-66d0e7f6-428d-4130-a5d4-3d159fd4bd67.png)

**Comment by vishal590** [comment]
Assign this issue to me 🙏🙏

**Comment by ketan3108** [comment]
Hi @clmnxm , i would like to contribute in this . Could you please assign me . 
Thanks

**Comment by clmnxm** [comment]
hi @corwintines can you help with this?

Thanks!
