### ISSUE TITLE
Suggest a wallet: ShapeShift Wallet

### ISSUE THREAD

**Issue by thesmithdao** [ethereum/ethereum-org-website#9728]
### Wallet name

ShapeShift Wallet

### Wallet description

ShapeShift Wallet is a free, community-owned open-source cryptocurrency wallet. You can import a Secret Recovery phrase, or create a new wallet. The wallet supports 10 chains without the need to switch networks, and aggregates DEXs, Fiat Ramps, and DeFi protocols to make it easy to buy, sell, trade, and earn without any added fees. You can also connect ShapeShift wallet to any dapp that supports WalletConnect.

### Wallet logo

https://assets.website-files.com/5cec55545d0f47cfe2a39a8e/61895a7ef8500fada381641f_FOX_token.svg

### Background color for brand logo

Borealis (#386FF9), Light #FFFFFF, or Midnight (#0D182D) 

### URL to the project

https://app.shapeshift.com 

### When did the wallet go live to users?

July/2020

### Does the wallet have an active development team?

Yes, ShapeShift DAO

### Is the wallet globally accessible?

Yes, no KYC

### Is the wallet available in multiple languages?

Yes

### What social links are there for the project?

https://twitter.com/ShapeShift
https://discord.gg/shapeshift
https://forum.shapeshift.com
https://medium.com/@ShapeShift.com
https://github.com/shapeshift
https://t.me/shapeshiftofficial

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

AppStore (iOS): https://apps.apple.com/us/app/shapeshift-crypto-platform/id996569075 
Playstore (Android): https://play.google.com/store/apps/details?id=com.shapeshift.droid_shapeshift 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

https://app.shapeshift.com

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

ShapeShift is fully open-source including the wallet: https://github.com/shapeshift/hdwallet  https://github.com/shapeshift/web 

### What license is the wallet software released under?

MIT license

### Who holds the private keys?

The user. ShapeShift is non-custodial.

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

https://www.defisafety.com/app/pqrs/108

### Has the wallet's smart contract code or security modules been audited?

N/A

### Does the wallet have an internal security team?

Yes

### Any other security testing that should be noted?

N/A

### Scam protection?

No

### Does the wallet support connecting to a hardware wallet?

Yes

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

Yes

### Does the wallet support staking directly?

Yes. 

### Does the wallet support swaps directly?

Yes

### Does the wallet support multi-chain networks?

Yes

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

Yes

### Does the wallet support sending transactions to ENS addresses?

Yes

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes

### Does the wallet support EIP-1559 (type 2) transactions?

Yes

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes

### Does the wallet support withdrawals to fiat?

Yes

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

https://discord.gg/shapeshift https://twitter.com/shapeshift 
Also @willyfox#1178 or https://twitter.com/willyogo

### Does the wallet have a dedicated support team?

Y, discord.gg/shapeshift 

### What educational resources/documentation do you provide to users?

https://docs.shapeshift.com/ 
https://shapeshift.zendesk.com/hc/en-us/

### Does the wallet have any integrated tools not mentioned above?

DEX integrations: 0x, CowSwap, and THORChain with no added fees
Send to y.at or unstoppable domains
Ability to add/derive multiple Ethereum accounts from a single seed phrase
Wallet notifications powered by PUSH Protocol and Wherever; Additionally, ability to view all of your PUSH notifications in ShapeShift

**Comment by corwintines** [comment]
Closing as above has been merged
