### ISSUE TITLE
Update the favicon of Storybook Setup with Ethereum favicon

### ISSUE THREAD

**Issue by MukulKolpe** [ethereum/ethereum-org-website#9754]
Hey, I noticed the storybook setup does not have any favicon. Maybe we can use the same favicon we use on the ethereum.org website for the storybook setup as well. Let me know If this seems relevant, I can make a quick PR to fix this.

**Comment by MukulKolpe** [comment]
@corwintines, @minimalsm 👀

**Comment by TylerAPfledderer** [comment]
@MukulKolpe I did not even consider that when updating the styling of the dashboard! 😅 

I don't see why not. @corwintines provided approval for the theming update. 

Adding custom theming for the dashboard was not only intended to match with the project, but also in the event of sharing the storybook via the [showcase page](https://storybook.js.org/showcase) for public viewing once completed. So I would say this is relevant. :)

**Comment by corwintines** [comment]
Thanks for the input @TylerAPfledderer :) I agree, I say go for it @MukulKolpe. Will assign to you. 

I think you should use the Ethereum diamond (color filled) for this. Its the same as the one we use on the nav bar.

![Screen Shot 2023-03-31 at 1 54 35 PM](https://user-images.githubusercontent.com/15589226/229217175-c0d6502c-ecb8-4894-ad9f-fd78818d28f3.png)

In the repo you can find it in `/src/assets/eth-home-icon.png`. Let me know if you need anything :)

**Comment by MukulKolpe** [comment]
Thank you @TylerAPfledderer, @corwintines. I've raised the PR.
