### ISSUE TITLE
StaticQuery component deprecated

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#9758]
## Description

```sh
The <StaticQuery /> component is deprecated and will be removed in Gatsby v6. Use useStaticQuery instead. Refer to the migration guide for more information: https://gatsby.dev/migrating-4-to-5/#staticquery--is-deprecated
```

Our `Footer` component uses the `StaticQuery` component, which is deprecated and will lose support in Gatsby v6. We should update this to use the `useStaticQuery` hook instead.

**Comment by MahendraBishnoi29** [comment]
@wackerow I would love to work on this😀

**Comment by corwintines** [comment]
Closed with above PR
