### ISSUE TITLE
Inappropriate translation banners on bug-bounty page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#9759]
## Issue

The following banner is being displayed on the English `/en/bug-bounty/` page:

> You’re viewing this page in English because we haven’t translated it yet. Help us translate this content.

And this is being displayed on a fully translated version:

> Está viendo esta página en inglés porque aún no la hemos traducido. Ayúdenos a traducir este contenido.

(Same message but in Spanish)

## To reproduce

1. Go to https://ethereum.org/en/bug-bounty or https://ethereum.org/es/bug-bounty
2. See banner notification

## Expected behavior

This message should only be displayed for non-English versions of the page that have not yet been translated.

## Screenshot

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/54227730/226387713-e7b212d3-37cd-4a87-9a77-c75676da28a4.png">

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/54227730/226388491-e0065225-9317-424e-b407-976f6f72c06a.png">

## Additional context

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MahendraBishnoi29** [comment]
can you please tell me the steps to fix this 🤔 @wackerow

**Comment by wackerow** [comment]
@MahendraBishnoi29 Not sure honestly, would have to do a little digging.

I would first check out the [`Layout` component](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Layout.tsx) as that is where the `TranslationBanner` is being rendered from. May be related to the `pageContext` that is generated during build, which affects the booleans being used in this component.

Let us know if you'd like to be assigned to take a stab at it... if you're hitting issues we can certainly try to help out!

**Comment by MahendraBishnoi29** [comment]
sure @wackerow 🚀

**Comment by wackerow** [comment]
@MahendraBishnoi29 Let us know if you'd like to be assigned!

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29 Let us know if you'd like to be assigned!

sure assign it to me 😀 @wackerow

**Comment by corwintines** [comment]
I've assigned this to you @MahendraBishnoi29. Thanks!

**Comment by corwintines** [comment]
Tested this out, I think this has been resolved but couldn't find the PR that fixed this. Going to close it out as its been fixed.
