### ISSUE TITLE
Sharding page could not be found.

### ISSUE THREAD

**Issue by yunesco** [ethereum/ethereum-org-website#9762]
The sharding URL on this page https://ethereum.org/en/upgrades/, needs to be updated from https://ethereum.org/en/upgrades/sharding/ to https://ethereum.org/en/roadmap/danksharding/, i can fix it if you assign it to me.

**Comment by corwintines** [comment]
Thanks for reporting @yunesco 

And thanks for offering both @yunesco and @vishal590 

We have a PR https://github.com/ethereum/ethereum-org-website/pull/9815/files where we are working on some cleanup work for the roadmap work we did. This is addressed in there, so im going to link this issue to that and it will be closed from that PR. If you take a look, redirects are being addressed there :)
