### ISSUE TITLE
Design regression: button text color on L2 page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#9766]
## Issue
Regression noted on the button contained within the `InfoBanner` on the L2 page, where text color is not properly responding to color mode.

## To replicate
1. Go to https://ethereum.org/en/layer-2/
2. Scroll about half-way down, to "Do your own research: risks of layer 2"
3. Make sure you're in "light mode"
4. See black text on blue button

## Screenshot
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/54227730/226612889-24c3bf1e-1d85-4478-917b-a8f1674869b2.png">

## Additional context
Likely related to recent updates surroudding design system

cc: @nloureiro @pettinarip @TylerAPfledderer

**Comment by MahendraBishnoi29** [comment]
I would love to fix this @wackerow

**Comment by MahendraBishnoi29** [comment]
@wackerow @TylerAPfledderer why is the text showing white on localhost?
<img width="221" alt="Screenshot 2023-03-23 094326" src="https://user-images.githubusercontent.com/74294202/227101327-26c606cf-3c8d-4c7b-a5a1-e924d91132d9.png">

**Comment by TylerAPfledderer** [comment]
@MahendraBishnoi29 did you apply any changes yet?

Checking updated dev on my local still shows the issue.

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29 did you apply any changes yet?
> 
> Checking updated dev on my local still shows the issue.

I've first pulled from the main branch for the updated codebase using `git pull origin dev` but the button color is still white on my localhost?

**Comment by wackerow** [comment]
Looks like this has been fixed... closing
