### ISSUE TITLE
footer bottom space bug in mobile view

### ISSUE THREAD

**Issue by MahendraBishnoi29** [ethereum/ethereum-org-website#9770]
go to mobile view and scroll after footer

[4b307656-b3c7-4bb8-a136-3da981ec9498.webm](https://user-images.githubusercontent.com/74294202/226785409-26695121-5dcf-4da1-89d3-1d372675ded2.webm)

**Comment by MahendraBishnoi29** [comment]
@wackerow assign it to me I'm working on it 👍🏻

**Comment by wackerow** [comment]
Noticing this too, using Brave or Safari on macOS... thanks for reporting @MahendraBishnoi29, will assign you

**Comment by MahendraBishnoi29** [comment]
> Noticing this too, using Brave or Safari on macOS... thanks for reporting @MahendraBishnoi29, will assign you

I think it's showing on all browsers 🤔

**Comment by TylerAPfledderer** [comment]
@MahendraBishnoi29 @wackerow this issue should now be closed as completed. 👍🏼 🎉
