### ISSUE TITLE
Dapps page: duplicatory category selection on mobile 

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9772]
There is a bug showing 2x the same dapss category menu on mobile

**Steps to reproduce:**
1. Go to: https://ethereum.org/en/dapps on mobile devoce
2. Scroll through the page to see
- First appearance: after "explore dapps" headline (as expected)
- Second appearance: after three boxes with benefits bellow dapps listing (should be removed)

**Images**
![Screenshot 2023-03-22 at 18 04 03](https://user-images.githubusercontent.com/100724231/226913111-9954eacf-1e7f-4413-84b4-f54745edfa9f.png)
![Screenshot 2023-03-22 at 18 04 11](https://user-images.githubusercontent.com/100724231/226913122-2346f7c0-9b52-4e72-8a56-0d558433f4b2.png)

**Expected behaviopr**
- do not duplicate the menu for dapps

**Comment by MahendraBishnoi29** [comment]
@konopkja on the same page the background color of this section's first card should be white, right?
<img width="935" alt="Screenshot 2023-03-22 202438" src="https://user-images.githubusercontent.com/74294202/226944729-350c50e5-2a7a-4758-8d14-552f8a372c5f.png">

or this?
![Screenshot 2023-03-22 202740_LI](https://user-images.githubusercontent.com/74294202/226946020-16201526-6fbf-40ed-a6a4-0fd2dc31cc73.jpg)

**Comment by konopkja** [comment]
> @konopkja on the same page the background color of this section's first card should be white, right? <img alt="Screenshot 2023-03-22 202438" width="935" src="https://user-images.githubusercontent.com/74294202/226944729-350c50e5-2a7a-4758-8d14-552f8a372c5f.png">
> 
> or this? ![Screenshot 2023-03-22 202740_LI](https://user-images.githubusercontent.com/74294202/226946020-16201526-6fbf-40ed-a6a4-0fd2dc31cc73.jpg)

should probably be one consistent color different from white (the light orange), but please create a separate issue to discuss that and lets keep this issue specific to the initially reported bug.

**Comment by MahendraBishnoi29** [comment]
@konopkja so either we can comment the mobile menu or we can remove it because we don't need the same menu 🤔

**Comment by konopkja** [comment]
> @konopkja so either we can comment the mobile menu or we can remove it because we don't need the same menu 🤔

yes the fix should be removing the second appearance of the menu.

**Comment by MahendraBishnoi29** [comment]
yes assign it to me I've made a PR for another issue and accidentally fixed this issue in the same PR because I've got a single branch for all my changes so what would you suggest should I ask reviewers to cancel the last commit or should close the PR and raise 2 new PR's for both issues

**Comment by konopkja** [comment]
> 

@corwintines  ping to decide

**Comment by MahendraBishnoi29** [comment]
> > 
> 
> @corwintines ping to decide

I think closing it and making 2 PR's would be better because both issues should've separate PR's

**Comment by corwintines** [comment]
@MahendraBishnoi29 ive commented in the PR, but I closed it so that you can open two separate PRs. 

With the one you will open in regards to this issue, make sure you remove the code and not just comment it out. 

Thanks!
