### ISSUE TITLE
inconsistent background color on Dapps Page

### ISSUE THREAD

**Issue by MahendraBishnoi29** [ethereum/ethereum-org-website#9782]
this is the background color of the first card in The magic behind dapps section:

<img width="935" alt="Screenshot 2023-03-22 202438" src="https://user-images.githubusercontent.com/74294202/227082315-74490833-5ced-4124-8b87-b66eba83c740.png">

but it doesn't match, it should be the same light orange color like the below picture
![Screenshot 2023-03-22 202740_LI](https://user-images.githubusercontent.com/74294202/227083208-7d970570-a768-42d6-a478-b79acfaa99eb.jpg)

**Comment by MahendraBishnoi29** [comment]
assign it to me I'll take care of it 👍🏻

**Comment by shreyjay0** [comment]
I see that no one has been assigned to this issue, can I take up this one? Looking to start contributing to ETH ecosystem.

**Comment by corwintines** [comment]
Ah I see some conversation around this in another PR. @MahendraBishnoi29 will assign to you. Lets go with the lighter color from your second image. Will assign to you.

**Comment by MahendraBishnoi29** [comment]
@corwintines I'm already on it but if you you're taking care of it then I'm out 😄

**Comment by corwintines** [comment]
Nah feel free to keep on it @MahendraBishnoi29, I'm just testing out assigning issues to myself to try and keep track of stuff in progress.

**Comment by corwintines** [comment]
Closing with above PR
