### ISSUE TITLE
Bug report: overflowing button text in stablecoins page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9784]
### Describe the bug

1. the text of the button is overflowing
2. the colored background is too small, could be much wider so there is more space for the content inside

### To reproduce

1. Go to (https://ethereum.org/en/stablecoins/)
2. Scroll down to "Use your stablecoins
3. See error

### Expected behavior

increase width of the components on mobile

### Screenshots

![Screenshot 2023-03-23 at 17 11 36](https://user-images.githubusercontent.com/100724231/227204448-fd7221e4-0fea-480b-878f-bae27d88f8d7.png)

**Comment by MukulKolpe** [comment]
Hey @konopkja, can I work on this issue?

**Comment by konopkja** [comment]
> Hey @konopkja, can I work on this issue?

absolutely! assigned you the issue

**Comment by sanibalakrishna** [comment]
Hey @konopkja , If this issue is not resolved yet could you assign this issue to me?

**Comment by konopkja** [comment]
> Hey @konopkja , If this issue is not resolved yet could you assign this issue to me?

Hi @sanibalakrishna, let's give @MukulKolpe a few days to look at this since he asked first. Then I can reassign.

**Comment by pettinarip** [comment]
This needs to be fixed on the Button theme configuration. We have a design for this case in the Design System. I had made a new task under the DS implementation epic to keep track of it #10020

**Comment by minimalsm** [comment]
Confirming I see this under 324px wide

**Comment by akhilesh-w** [comment]
![image](https://user-images.githubusercontent.com/77394282/236956875-d7db73f8-212d-4186-ad90-8c9efc149ec0.png)

As you can see, this problem isn't solved yet. Can you please assign it to me.

**Comment by konopkja** [comment]
seems like this is fixed, so closing this
