### ISSUE TITLE
Pooled NFT

### ISSUE THREAD

**Issue by gomezjo-jedi** [ethereum/ethereum-org-website#9785]
### Name

Pooled NFT

### Description

As the name implies, Pooled NFTs are simply NFTs pooled together inside a smart contract. For each NFT added to the pool, users recieve an equal number of Pool Tokens that represents their ownership of the pool. These Pool Tokens are standard ERC-20 tokens you see being used throughout Ethereum and DeFi today. Pool Tokens are always backed one to one by the NFTs in the pool. To get NFTs out of the pool, users exchange one Pool Token for each NFT they want to remove from the pool.

NFT Pools are collection-specific, meaning each NFT collection has a dedicated NFT Pool and only NFTs from that collection can be added to its pool. Anyone can create new NFT Pools.

Currently, Pooled NFTs support ERC-721 NFTs. Pooled NFT smart contracts do not contain any admin permissions and are free to use with no added fees. Users just pay gas for transactions.

### Logo

<img width="714" alt="PooledNFTblacktext 1 11af04e8" src="https://user-images.githubusercontent.com/62118490/227267555-593ce905-6bff-4ba3-8f11-f280831ccb6a.png">
![Icon256-Black](https://user-images.githubusercontent.com/62118490/227267834-3dcdcabc-8356-4def-a2cf-2458f3358223.png)
![PooledNFT-black](https://user-images.githubusercontent.com/62118490/227267888-af450fd0-5c4e-41b0-aa92-490342a51bcf.png)

### Brand color

#FFA500

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/hifi-finance/pooled-nft

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

https://github.com/hifi-finance/pooled-nft

### Can a user access the dapp without creating an account?

Yes. 

### Are dapp funds non-custodial?

Yes

### Do you offer community support?

Yes. 
Discord https://discord.com/invite/mhtSRz6
Website: https://poolednft.com/#/welcome

### Describe any geographical restrictions on usage of your dapp

No geographical restrictions.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @gomezjo-jedi 

We don't accept projects that have been live for less than 6 months. Based on what I can find this is around 3 months old. Going to close for that reason.
