### ISSUE TITLE
Hifi Finance

### ISSUE THREAD

**Issue by gomezjo-jedi** [ethereum/ethereum-org-website#9787]
### Name

Hifi Lending Protocol

### Description

Users can borrow against their crypto without any surprises. Our success is measured by the volume of debt the lending protocol services. Buying and selling tokenized debt enables fixed-rate lending and borrowing — advancing the decentralized finance landscape to include novel collateral types and use cases. New ecosystem projects and partnerships will expand the supported collateral types users can leverage.

### Logo

![1_HifiLogo](https://user-images.githubusercontent.com/62118490/227271208-d5cfe255-90d9-4c53-932c-ebe6597eaaa8.png)
![1_HifiLogo](https://user-images.githubusercontent.com/62118490/227271220-e5a9691b-02b9-453f-b487-473b1e2ac4f1.svg)
![2_HifiSubmark](https://user-images.githubusercontent.com/62118490/227271300-456d2b9c-9fc1-4e7a-991a-ca37e6da1e0d.png)
![2_HifiSubmark](https://user-images.githubusercontent.com/62118490/227271315-d2cc6184-981a-493c-bd15-c1e69f587724.svg)
![1_HifiLogo](https://user-images.githubusercontent.com/62118490/227271386-13f648b0-cfed-474c-b93b-aaa50b9ac1fb.png)

### Brand color

#6E2EF4

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/hifi-finance

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

https://github.com/hifi-finance/hifi/tree/main/audits

### Can a user access the dapp without creating an account?

Yes. 

### Are dapp funds non-custodial?

Yes.

### Do you offer community support?

Yes. Discord https://discord.com/invite/mhtSRz6

### Describe any geographical restrictions on usage of your dapp

No geographical restrictions.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @gomezjo-jedi 

Looking at the roadmap section on your site it appears HIFI is under 6 months live on mainnet, which we require.

The liquidity pools also seem very shallow (under 500k). I would say this is too early to list on ethereum.org from me. 

If I have misunderstood anything let me know, but I will also leave this open for others to comment first.

**Comment by corwintines** [comment]
Going to close this out with above comment.
