### ISSUE TITLE
Suggest a staking product or service

### ISSUE THREAD

**Issue by Gandalf-Dust-Wizard** [ethereum/ethereum-org-website#9792]
### Project name

Bedrock Liquid Staking & Staking Pool

### Product type

Staking Pool

### If other product type, please describe

-

### Logo

![rockx_logo-white text@2x](https://user-images.githubusercontent.com/51398526/227436998-280c2c71-b9a9-47ee-9aac-6ef944175afd.png)
![rockx_logo-dark text@2x](https://user-images.githubusercontent.com/51398526/227437025-200aed04-9975-4627-a39b-537f564e654d.png)

### Description

Bedrock is a non-custodial solution that fits the needs of institutions looking for a foundation for liquid staking at scale through cutting-edge technology and regulatory compliance. By bringing a whole new level of transparency and security to liquid staking, Bedrock allows institutions to unlock liquidity safely while leveraging a true crypto-native solution.

### Website

https://bedrock.rockx.com/

### If software is involved, is everything open source?

Yes, everything is open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

The product is out of beta development and has been launched on Ethereum mainnet. It has been online for ~ 6 months. https://etherscan.io/tx/0x725b15afd741bef44fef37e612204150d451dc514af2bab133273121107a5fb3

Project GitHub: https://github.com/RockX-SG/stake

LP: https://app.balancer.fi/#/ethereum/pool/0xbfce47224b4a938865e3e2727dc34e0faa5b1d82000000000000000000000527

### What wallets support the product or service?

All wallets that support ERC20 tokens

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

No minimum, however we recommend staking more than 0.01 ETH,

### If a service, what are the fees associated with using the service?

10% of staking rewards

### If the product or service involved a liquidity token, what are the tokens involved?

UniETH is the liquidity token

Verification of total uniETH supply on-chain: https://etherscan.io/token/0xF1376bceF0f78459C0Ed0ba5ddce976F1ddF51F4
Verification of all deposits into uniETH on-chain: https://etherscan.io/address/0x4beFa2aA9c305238AA3E0b5D17eB20C045269E9d

### What date did the project or service go live?

29 Sep 2022 (https://etherscan.io/tx/0x725b15afd741bef44fef37e612204150d451dc514af2bab133273121107a5fb3)

### Has the project undergone an external security audit?

Yes

Smart contract audit report: https://github.com/RockX-SG/stake/blob/main/PeckShield-Audit-Report-RockXStaking-v1.0.pdf

### Has the project undergone any security bug bounties?

None yet, however, we plan to launch a bug bounty in the near future.

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Yes, it is all managed by smart contracts

### If a pooled staking service, can users participate as a node operator without permission?

Yes

### If listing a staking-as-a-service, are users required to sign-up for an account?

-

### If listing as staking-as-a-service, who holds the signing keys, and withdrawal keys?

-

### If a pooled staking service, what percent of node operators are running a super-majority consensus layer client?

Currently at 100%, however, we will be implementing DVT to decentralize the validators in addition to setting up the Bedrock DAO.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

-

### What platforms are supported?

Most platforms supported including Linux, macOS, Windows, iOS, Android

### What user interfaces are supported?

Browser app for now

### Social media links

Twitter: https://twitter.com/rockx_official
LinkedIn: https://www.linkedin.com/company/rockx-official
Discord: https://discord.gg/YJzs4UwsTp
YouTube: https://www.youtube.com/channel/UCur9s16EemOPuY_YAXhtG9A

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @Gandalf-Dust-Wizard! Thanks for posting... I see you're suggesting this as a "Liquid Staking Protocol". Trying to figure out the best way to fit this in given the existing structure of the staking pages on ethereum.org/staking.

From the website, it looks like both SaaS and pooled staking pages could be appropriate:

**Pooled: https://bedrock.rockx.com/unieth/stake**

> Not a pooled staking service at the moment, but is on our development roadmap

The link above presents an option to convert arbitrary amounts of ETH into uniETH. Would this not be best categorized in the pooled staking options?

**SaaS: https://www.rockx.com/staking/validators/ethereum**

<img width="853" alt="image" src="https://user-images.githubusercontent.com/54227730/228993180-0393d0eb-9874-4957-be9d-e9dcc7f476ff.png">

This appears to be a 32 ETH min staking-as-a-service setup, which requires users to contact you via email, is that correct?


If so, we should break this out and consider each product separately for the two different pages, and fill out the items needed in the form for each.

**Comment by wackerow** [comment]
@Gandalf-Dust-Wizard Recapping here after our chat:
- SaaS product is available now. @Gandalf-Dust-Wizard to update this issue to be centered around SaaS product => Review and PR to follow
- Pooled product currently lacking liquidity, which is in the works. Pooled product to come as a new/separate issue

**Comment by Gandalf-Dust-Wizard** [comment]
@wackerow an update in relation to our last comments/discussion. The SaaS product will be undergoing a major upgrade including the implementation of a full self-service portal, and once launched, we will create the SaaS issue. Scheduled to occur later this month.

Since our liquidity has increased to a sufficient amount now, we have adjusted this issue to focus on the Staking Pool product. This is now ready for review.
