### ISSUE TITLE
Add Bisq to DEX list

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/ethereum-org-website#9794]
### Exchange name

Bisq

### Exchange description

Bisq is a decentralized exchange similar to localcryptos, except the listings themselves are stored and executed in a decentralized manner, and it isn't currently shutting down. 

### What geographical restrictions apply to this exchange?

None, AFAIK 

### Which currencies are accepted by this exchange?

Bitcoin (primarily), Ethereum, a few others.

In terms of fiat, USD is supported. I think that EUR and GBP are also supported, but I'm not sure. 

### Do you have any proof that they're a legitimate company?

N.A. (It's peer to peer).

The source code is here: https://github.com/bisq-network/bisq

The website is here: https://bisq.network/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks, @Pandapip1 

It would be nice to add more p2p options like this. My main reservation right now with this is it is mainly a BTC exchange, as opposed to ETH. You would need to go fiat -> BTC -> ETH which seems pretty unintuitive for us trying to onboard a user to Ethrereum. I understand it's potentially good for that but seems a bit off putting that on ethereum.org in my opinion if it's centered on buying and selling BTCc.

The other issue I'm having is even trying to use Bisq. The documentation is pretty rough and seems like it's for a different version of the app. Is there something I'm missing here from the docs?

**Comment by Pandapip1** [comment]
> Is there something I'm missing here from the docs?

I have not used Bisq either, since the payment options are limited, and I'm currently not able to buy any amount of crypto (even for testing). It seems pretty simple to use, though. For now, feel free to mark this as very low priority and/or waiting for more information.

**Comment by Pandapip1** [comment]
Bump

**Comment by Pandapip1** [comment]
Bump

**Comment by minimalsm** [comment]
> -> BTC -> ETH which seems pretty unintuitive for us trying to onboard a user to Ethrereum.

Agree, this is too obscure for us to list for the reasons @corwintines stated. Closing this out.

**Comment by minimalsm** [comment]
@all-contributors please add @Pandapip1 for ideas
