### ISSUE TITLE
Roadmap pages: UI bugs on mobile

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9804]
### Describe the bug

There are a few UI bugs that should be fixed:
1. There is no empty space between the header buttons and header dropdown
2. There is no empty space between the header background and the first line of text below it.

### To reproduce

1. Use mobile device
2. Go to [roadmap pages](https://ethereum.org/en/roadmap/)
3. See error

### Expected behavior

add empty space to improve aesthetics and readability 

### Screenshots

![Screenshot 2023-03-26 at 14 06 54](https://user-images.githubusercontent.com/100724231/227967431-2344afe1-e937-463a-8bb4-136d21704ef4.png)

![Screenshot 2023-03-26 at 14 07 27](https://user-images.githubusercontent.com/100724231/227967457-65a18f3c-513f-4af9-ba3f-5f9e15cbe2b6.png)

**Comment by shreyjay0** [comment]
Hello @konopkja, I can fix this issue. Can you assign it to me?

**Comment by OmkarK97** [comment]
Assign me the task @konopkja
