### ISSUE TITLE
Mobile breadcrumb navigation wrong spacing 

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9805]
### Describe the bug

There is buggy spacing in the mobile breadcrumb navigation, see screenshot.

### To reproduce

1. Use mobile
2. Go to https://ethereum.org/en/roadmap/user-experience/
3. See the error

### Expected behavior

1. Remove the gap and maintain same padding as between "Home / ethereum roadmap"
2. If breadcrumb text is too long, the whole breadcrumb navigation should be divided into two lines instead of each text inside the navigation having two lines

### Screenshots

![Screenshot 2023-03-26 at 14 07 51](https://user-images.githubusercontent.com/100724231/228023280-b08120e6-dd71-411a-852f-94319c9ee397.png)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by shreyjay0** [comment]
Can I take this up?

**Comment by shreyjay0** [comment]
Just to confirm, are you expecting something like 

<img src="https://user-images.githubusercontent.com/42074753/228399222-4fce0738-426b-4db8-9c29-c9f4e8b83fde.png" alt="2 lined" width="180" height="275"/>   OR    <img src="https://user-images.githubusercontent.com/42074753/228399292-b5b69ee5-bb91-4d69-b1c0-dac39c2e8dfa.png" alt="2 lined" width="180" height="275"/>

?

**Comment by konopkja** [comment]
> Just to confirm, are you expecting something like
> 
> <img alt="2 lined" width="180" height="275" src="https://user-images.githubusercontent.com/42074753/228399222-4fce0738-426b-4db8-9c29-c9f4e8b83fde.png"> OR <img alt="2 lined" width="180" height="275" src="https://user-images.githubusercontent.com/42074753/228399292-b5b69ee5-bb91-4d69-b1c0-dac39c2e8dfa.png">
> 
> ?

the first one, but could you add little bit more space between the two lines?

**Comment by shreyjay0** [comment]
ok, I'll add some more space between them

**Comment by corwintines** [comment]
Closing as above PR addressed. Thanks again @shreyjay0

**Comment by shreyjay0** [comment]
sure, thanks
