### ISSUE TITLE
Add Infura Sepolia Testnet Faucet

### ISSUE THREAD

**Issue by anataliocs** [ethereum/ethereum-org-website#9820]
### Dev tool name

Infura Sepolia Testnet Faucet

### Dev tool description

Infura just released a Sepolia Testnet Faucet that lets you claim 0.5 Sepolia ETH per day, for free. It's super easy to use, just visit http://infura.io/faucet, sign in to your Infura account, enter your wallet address, and claim.

Sepolia Testnet is an important tool for testing your smart contracts before deploying them on mainnet environments. With our Testnet Faucet, you can easily catch bugs and reduce the cost of deploying tests on mainnet.

At Infura, we're all about making Web3 development easy and reliable. That's why we're excited to offer this important tool to help you achieve your goals.

### When did the dev tool go live?

3/28/2023

### Where do you think this page should be shown?

https://ethereum.org/en/developers/docs/networks/#sepolia

Under Faucets.

![image](https://user-images.githubusercontent.com/4750426/228355324-db80db91-b7dc-43d0-b13c-186a4efffdc5.png)

### Is the product open source?

No

### Documentation URL

http://infura.io/faucet

### Additional context

![image](https://user-images.githubusercontent.com/4750426/228355523-272dd466-0ebd-4437-bf0c-1adf08935192.png)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Closing as above PR has been merged in
