### ISSUE TITLE
Inconsistency with theme switch button on small screen sizes

### ISSUE THREAD

**Issue by shreyjay0** [ethereum/ethereum-org-website#9822]
### Describe the bug

On screen sizes including mobile devices and tablets, when the theme is set to light mode, the theme switch button in the sidebar displays the label "Light" and respective icon instead of the expected label "Dark" and vice versa. This issue can confuse users who are trying to switch themes.

### To reproduce

1. Go to any page on ethereum.org on a mobile device or a tablet.
2. Click on the menu icon in the top-right corner to open the sidebar
3. Look at the bottom panel to see the theme switch button
4. Observe the label and icon displayed on the theme switch button

### Expected behavior

1. When the theme is set to light mode, the theme switch button in the sidebar should show the label "Dark" and a moon icon. This indicates that clicking the button will switch the theme to dark mode.

2. When the theme is set to dark mode, the theme switch button in the sidebar should show the label "Light" and a sun icon. This indicates that clicking the button will switch the theme to light mode.

### Screenshots

<img src="https://user-images.githubusercontent.com/42074753/228359936-65c3c4c8-8f77-4f5a-8ceb-00a1bc5b9383.png" alt="in light mode" width="250" height="450"/>

<img src="https://user-images.githubusercontent.com/42074753/228360353-7fa3eb9e-dcd1-45ad-9f0d-ab75dddd4440.png" alt="in dark mode" width="250" height="450"/>

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
@nloureiro @konopkja would like your input on this before reviewing the PR.

**Comment by nloureiro** [comment]
@corwintines all good from my side, good catch

**Comment by shreyjay0** [comment]
Good to know, thank you
