### ISSUE TITLE
Show execution layer client diversity of staking services

### ISSUE THREAD

**Issue by one-three-three-seven** [ethereum/ethereum-org-website#9840]
### Is your feature request related to a problem? Please describe.

I'm currently looking for a staking service which does not use Geth.

I have noticed that some of the staking services at https://ethereum.org/en/staking/saas/ have a check mark on the "DIVERSE CLIENTS" field. I have asked the support from one these services about this topic and the support responded with the info, that they **only** use Geth for the execution layer.

The "DIVERSE CLIENTS" field seems currently only used for the consensus layer. But the execution layer is actually also very important. The shown information is misleading.

### Describe the solution you'd like

I would suggest to add a new metric "DIVERSE EXECUTION CLIENTS" and rename "DIVERSE CLIENTS" to "DIVERSE CONSENSUS CLIENTS".

### Describe alternatives you've considered

We could also remove the "DIVERSE CLIENTS" check mark from services which do not have diversified the execution layer clients.

### Additional context

I think I could make a Pull Request for this. **But I would like to know which solution is preferred first.**

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Thanks @one-three-three-seven. I agree, this seems like an important distinction that is missing.

Before assigning and looking at next steps, id like to see what @wackerow thinks about this suggestion. 

Just to check, I see that you checked off being interested in working on this issue. Are you open to researching and updating the data for this?

**Comment by one-three-three-seven** [comment]
Hello @corwintines,

Thanks for your reply. I have already started to make a very basic website about this topic: https://execution-diversity.info
But I think ethereum.org is a better location to rise awareness.

It's not possible to verify the information which the services are providing, but I still believe it's better to have an official statement from the services about their (execution layer) diversity.

We may need a threshold at which we consider a service as diversified. (For example: Do we show Lido as diversified with 90% Geth usage?) In my opinion, <2/3 Geth usage would be a good threshold.

So, we would show a service/pool with **<2/3 Geth usage** as **diversified** and the other ones (with **>2/3 Geth usage**) as **not diversified**. (Depending on their official statement.)

**Comment by Buttaa** [comment]
@one-three-three-seven, I completely agree that the current labeling of "Diverse Clients" is misleading and should be expanded to include "EL client diversity" and "CL client diversity, imo.

Initially, I was hesitant to advocate for diversity in execution clients, but over the past few months, most EL clients have made significant progress and are now suitable for staking.

**Comment by wackerow** [comment]
I'm favor of this.

For SaaS, the definition used on the site for Diverse Clients is currently:

> Service should not run more than 50% of their aggregate validators with a majority validator client

"Majority validator" essentially means whichever client is being used the most at any moment, but doesn't add emphasis if there is a supermajority client (which has the most serious potential consequences). Geth, according to clientdiversity.org, is currently just around 60%... so currently not holding a supermajority.

Any opposition to just repeating the definition currently being used, tweaked slightly?

> DIVERSE CONSENSUS CLIENTS: Service should not run more than 50% of their aggregate validators with a majority consensus client

> DIVERSE EXECUTION CLIENTS: Service should not run more than 50% of their aggregate validators with a majority execution client

**Comment by wackerow** [comment]
Also, love the [new page](https://execution-diversity.info/)! We should also find a place to list this on the site. Any reason we should wait? (ie, the site is labeled as "work in progress")

**Comment by one-three-three-seven** [comment]
> Any opposition to just repeating the definition currently being used, tweaked slightly?
> 
> > DIVERSE CONSENSUS CLIENTS: Service should not run more than 50% of their aggregate validators with a majority consensus client
> 
> > DIVERSE EXECUTION CLIENTS: Service should not run more than 50% of their aggregate validators with a majority execution client

I'm generally fine with that. Some people might not know the difference between consensus and execution; however, I think it doesn't really make a difference in practice. If we use the exact same sentence and thresholds anyway, we could simplify it:

> DIVERSE CLIENTS: Service should not run more than 50% of their aggregate validators with a majority client

(It's almost the same as the already used sentence, I only removed the word "validator".)

> "Majority validator" essentially means whichever client is being used the most at any moment

I would suggest considering only clients with >=50% as the majority client. Prysm and Lighthouse have almost the same share right now, so it would be odd to consider Prysm as the majority client but not Lighthouse, just because of a few percentage points difference. The majority client might also switch quite often, as Lighthouse could soon have a higher share than Prysm.

> Geth, according to clientdiversity.org, is currently just around 60%... so currently not holding a supermajority.

This information is very likely wrong. (JFYI, I have also contributed a little bit to clientdiversity.org)
The website uses ethernodes.org as data source for the execution layer. It's only counting the number of nodes detected in the p2p network. There can be a huge difference between the number of nodes and validators using a specific client.

The large services, such as Lido, Coinbase, and Kraken, run only a small number of nodes but have a very high number of validators. Using the number of detected P2P nodes skews the metric in favor of Geth. The goal of my project, execution-diversity.info, is to improve the available data sources. I'm doing this by inquiring the support about the services' actual execution client usage. This approach is much more reliable but requires more time.

To my best knowledge, Geth is a supermajority client.

> Also, love the [new page](https://execution-diversity.info/)! We should also find a place to list this on the site. Any reason we should wait? (ie, the site is labeled as "work in progress")

That would be great! I'm still in the process of asking services and improving the FAQ. I also have pending chats with other people which want to contribute to this project. So there is still a lot of stuff changing, I would prefer to wait a little bit before merging this.

**Suggestion**
1.) We do the easy approach and show `DIVERSE CLIENTS: Service should not run more than 50% of their aggregate validators with a majority client`, This applies to both, execution and consensus layer.
2.) I will ask all the services currently shown on the ethereum.org page about the distribution. We will show the check mark accordingly. They can also contribute this information by pull request / issue.
3.) We will handle the "merge" of execution-diversity.info into ethereum.org in a separate issue, as soon as I feel ready.

**Comment by wackerow** [comment]
re: @one-three-three-seven 

> I would suggest considering only clients with >=50% as the majority client. Prysm and Lighthouse have almost the same share right now, so it would be odd to consider Prysm as the majority client but not Lighthouse, just because of a few percentage points difference. The majority client might also switch quite often, as Lighthouse could soon have a higher share than Prysm.

I do agree that the current definition is faulty. Although, I might suggest an alternative direction... Any client over 33% could prevent finalization—is there a way we could phrase this to dissuade operators from using these clients? Personally would like to encourage operators to choose clients that are below this, to prevent any bugs from halting finalization. Perhaps something like:

> Service should not run more than 50% of their aggregate validators with client software comprising >33% network share

(50% is arbitrary... not sure where else to draw this line... perhaps 33%? If all operators kept all clients below 33% of their aggregate we'd never end up here)

---

> The website uses ethernodes.org as data source for the execution layer. It's only counting the number of nodes detected in the p2p network. There can be a huge difference between the number of nodes and validators using a specific client.

Okay, I was curious about this. So is this counting "nodes", vs "number of validators running X client"? Having a resource to reference for some numbers would certainly help from our end...

Beyond that, could also ask a similar question from above—should we update the definition to catch any client that could potentially halt finality?

---

> I would prefer to wait a little bit before merging this.

Sounds great!

---

> 1.) We do the easy approach and show DIVERSE CLIENTS: Service should not run more than 50% of their aggregate validators with a majority client, This applies to both, execution and consensus layer.

I'm down... can also consider iterating per above comments, but personally okay with starting here

> 2.) I will ask all the services currently shown on the ethereum.org page about the distribution. We will show the check mark accordingly. They can also contribute this information by pull request / issue.

🙏 This would be super helpful! Raising issues then PRs with public discourse/data reporting would be ideal just for documentation and transparency sake. 

> 3.) We will handle the "merge" of execution-diversity.info into ethereum.org in a separate issue, as soon as I feel ready.

Thanks again... As I think about this more, this issue here could actually act as the hub to organize this if you'd like... or if you'd prefer, feel free to open a clean new issue to track the products that are already listed... I'll leave it up to you.

**Comment by one-three-three-seven** [comment]
Thanks for your comprehensive feedback.

I think we should differentiate between the mid-term goal of having no more supermajority clients and the long-term goal of keeping finalizing even if any client has an issue. A short period of non-finality is just a "minor incident" compared to the catastrophic result of a supermajority consensus bug. My focus is currently on resolving the issue of supermajority clients.

> Service should not run more than 50% of their aggregate validators with client software comprising more than 33% of the network share.

Not even a well-diversified service with 30% Prysm, 30% Lighthouse, 30% Teku, and 10% Nimbus would fulfill this requirement. I fear that setting the threshold at 33.3% is too aggressive. The operators may not even try to reach it. I would go with 50% / 50%.

> Okay, I was curious about this. So, is this counting "nodes" versus "number of validators running X client"? Having a resource to reference for some numbers would certainly help from our end...

There is no source, that's the problem. There can be 1,000 Besu nodes running 1 validator each and 1 Geth node with 1,000 validators. The number of nodes does not tell us anything about the usage for validator duties; it's totally misleading.

**Summary**
1.) We both agree on the 50% / 50% threshold, so we should do it.
2.) I would suggest enforcing new enlisting to provide that information. This improves transparency and documentation.
3.) Show a question mark (?) for existing services. This way, we can handle each rating in a transparent way as a pull request.

(I will let you know as soon as I have an update about the "merge" of execution-diversity.info. I'm still waiting for a lot of answers.)

**Comment by jmcook1186** [comment]
Hi @corwintines - scanning back through the comments, I don't love the idea of an arbitrary target of 50%. 

The reason is that if that arbitrary target is actually achieved there are only two possible outcomes: 

1) tacit approval of a suboptimal client distribution (i.e. "well done for reaching 50% - kick back, your work is done")
2) moving the goalposts in a way that would be frustrating to operators ("well done for reaching 50% - we told you that was a good target but actually it isn't - back to work")

Neither are particularly desirable.

I don't think ethereum.org should be trying to make a judgment about this - we should either report an empirical value that has clear reasoning behind it (i.e. 33% due to liveness) or not report a value at all.

Couldn't you just report the % share for each operator without making a value judgment about it? Then explain clearly the risks associated with different thresholds: 33%, 50%, 66%, and let the readers infer from there?

**Comment by one-three-three-seven** [comment]
Hello,

I'm at this point happy with any progress, regardless of the used thresholds or kind of visualization.
