### ISSUE TITLE
in mobile devices, footer occupies more height than expected

### ISSUE THREAD

**Issue by amit-ksh** [ethereum/ethereum-org-website#9862]
### Describe the bug

The footer has the `min-height` of `100vh`

### To reproduce

1. Go to https://ethereum.org/en/
2. Scroll down to the bottom of the page
4. See the error

### Expected behavior

Should not have extra height

### Screenshots

![screenshot-ethereum org-2023 04 01-14_55_53](https://user-images.githubusercontent.com/91947037/229277920-dc92e54b-bcca-47cd-a496-5db807437e78.png)

### Desktop (please complete the following information)

Browser: Brave
OS: Windows 10

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by MahendraBishnoi29** [comment]
@amit-ksh  #9863
