### ISSUE TITLE
Invalid link 'incentive layer' and 'LMD-GHOST'

### ISSUE THREAD

**Issue by Yc-Chen** [ethereum/ethereum-org-website#9866]
### Describe the bug

When reading 'ETHEREUM PROOF-OF-STAKE ATTACK AND DEFENSE', I noticed the 2 invalid links 'incentive layer' and 'LMD-GHOST'.

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attack-and-defense/#prerequisites
2. Click on 'incentive layer' or 'LMD-GHOST'
3. See error 'We couldn't find that page'

### Expected behavior

See the correct pages.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by MahendraBishnoi29** [comment]
@Yc-Chen are you working on it? if not then  I would love to work on this

**Comment by Yc-Chen** [comment]
@MahendraBishnoi29 Please go ahead. I cannot work on it as I do not know where the link 'incentive layer' should go...

**Comment by jmcook1186** [comment]
Looks like the url linked to from LMD-GHOST is missing the `developers` slug - the correct link is: https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/gasper/#fork-choice.

"incentive layer" is supposed to link here: `https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/

Please go ahead and raise a PR if you want to!

**Comment by MahendraBishnoi29** [comment]
@jmcook1186 let someone from the team verify these links and then I'll raise a PR. appreciate your help :)
