### ISSUE TITLE
Diversify Links with Kernel Additions

### ISSUE THREAD

**Issue by andytudhope** [ethereum/ethereum-org-website#9869]
### Is your feature request related to a problem? Please describe.

After talking through some ideas with @minimalsm I'd like to add links to Kernel and some of the educational resources we have gathered in order to diversify what is already offered on e.org.

### Describe the solution you'd like

This will entail me going through the site page by page, thinking about user journeys, thinking about which specific Kernel links work well at which specific times, and adding them.

While doing this, I will also update any copy that I can and fix any bugs that come up.

### Describe alternatives you've considered

I do not plan to add copious amounts of new information. If anything, I will edit and remove whatever I can to make people's experience cleaner, clearer and less overwhelming.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by minimalsm** [comment]
Merged both PRs @andytudhope, sorry for the delay. 

I'll leave this issue for now, feel free to close whenever you'd call this done.

**Comment by andytudhope** [comment]
Ah, sorry friendly bot. I am still planning on working on this: it's just that travels and hackathons have taken priority for the time being. Still a long way to go.

**Comment by wackerow** [comment]
Hey @andytudhope! Circling back... looks like this has run quiet over the past year. I'm going to go ahead and close this out, but primarily for organizational/clean-up purposes. If you'd like to continue these efforts please do us a favor and open a new issue and we can go from there, thanks!
