### ISSUE TITLE
Suggest a staking product or service

### ISSUE THREAD

**Issue by Buttaa** [ethereum/ethereum-org-website#9882]
### Project name

Ethpool

### Product type

Staking pool

### Logo

![20230123_Ethpool_Logo](https://user-images.githubusercontent.com/26490734/229705604-0e3d132c-67d2-4e8d-989b-dba31551f3bb.png)
![20230123_Ethpool_Logo_500](https://user-images.githubusercontent.com/26490734/229705610-9eb04a53-8c3b-4d2c-92ff-4cee01b1afad.png)

### Description

Ethpool is a non-custodial staking service. Users upload their validator key(s), and Ethpool will perform the validator duties for the user.

### Website

https://ethpool.org/

### If software is involved, is everything open source?

No, code is closed source

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes, Ethpool launched in [October, 2021](https://twitter.com/ethermine_org/status/1450852809616801799). 

### What wallets support the product or service?

Walletconnect, Metamask

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

/

### If a service, what are the fees associated with using the service?

8-15% of transaction rewards or roughly 2% of a validator's total earnings.

### If the product or service involved a liquidity token, what are the tokens involved?

/

### What date did the project or service go live?

October, 2021.

### Has the project undergone an external security audit?

No

### Has the project undergone any security bug bounties?

No

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Ethpool is a non custodial service. 
Only the validator keys must be shared with Ethpool so that the service can perform the validator duties.

### If a pooled staking service, can users participate as a node operator without permission?

/

### If listing a staking-as-a-service, are users required to sign-up for an account?

Yes, only an e-mail account is required.

### If listing as staking-as-a-service, who has access to the signing keys?

The service only needs access to the validator keys.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

/

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

Ethpool uses Lighthouse and Nethermind.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

/

### What platforms are supported?

Linux, macOS, Windows, iOS, Android

### What user interfaces are supported?

Browser app

### Social media links

https://twitter.com/ethermine_org
https://discord.io/ethermine

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Buttaa** [comment]
https://github.com/ethereum/ethereum-org-website/pull/9871

**Comment by wackerow** [comment]
@Buttaa Hey just checking, is the `feeRecipient` a contract address? Or does it go to Ethpool where the fee is taken and manually distributed?

And I assume the user simply designates their own execution withdrawal address or holds onto their own mnemonic/BLS keys?

Lastly, so we happen to have any reference for the validator breakdown? I see `15%` entered in the PR for "percent majority client"... 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/54227730/230414749-9233bd62-510b-46af-9850-1affd2f12785.png">
This definition admittedly is getting hazy as we now have two clients that are neck-and-neck to be most used... Is Ethpool running 100% Lighthouse?

Also shines light on the potential need to update/clarify this definition to continue to encourage users to keep the client usage distributed.

**Comment by Buttaa** [comment]
> @Buttaa Hey just checking, is the `feeRecipient` a contract address? Or does it go to Ethpool where the fee is taken and manually distributed?
> 
> And I assume the user simply designates their own execution withdrawal address or holds onto their own mnemonic/BLS keys?
> 
> Lastly, so we happen to have any reference for the validator breakdown? I see `15%` entered in the PR for "percent majority client"... <img alt="image" width="507" src="https://user-images.githubusercontent.com/54227730/230414749-9233bd62-510b-46af-9850-1affd2f12785.png"> This definition admittedly is getting hazy as we now have two clients that are neck-and-neck to be most used... Is Ethpool running 100% Lighthouse?
> 
> Also shines light on the potential need to update/clarify this definition to continue to encourage users to keep the client usage distributed.

@wackerow , the feeRecipient is `ethpool.eth` which an EOA address manually distributes the reward, as you described.

Correct, the user can choose an address to which the transaction rewards will be sent to (after the pool fee).
Only the user has access to the withdrawal credentials. And the validator keys need to be uploaded by the user.

The 15% were referring to the EL client (nethermind). As for the CL client, Ethpool operates 100% lighthouse right now.
