### ISSUE TITLE
What is a Smart Contract Audit

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/ethereum-org-website#9900]
### Tutorial title

What is a Smart Contract Audit

### Tutorial description

We explain:
1. What a smart contract audit is
2. What to expect from an audit
3. What to expect after an audit

And we list a few smart contract auditors. 

### Tutorial tags

security 

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://www.cyfrin.io/blog/what-is-a-smart-contract-audit

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by nhsz** [comment]
Fixed by #9901
