### ISSUE TITLE
Add Kurtosis as a developer tool

### ISSUE THREAD

**Issue by leeederek** [ethereum/ethereum-org-website#9910]
### Dev tool name

Kurtosis ([kurtosis.com](https://www.kurtosis.com/))

### Dev tool description

Kurtosis is a composable build system for multi-container test environments. Kurtosis is well suited for engineers who need: to instantiate test environments that require dynamic set up logic, programmatic data injection, and/or completely reusable and portable environment definitions for their multi-container application tests.

### When did the dev tool go live?

Mid/Late 2020

### Where do you think this page should be shown?

We'd like to add Kurtosis to two different locations on Ethereum.org:

1. [The "Set up local environment" page](https://ethereum.org/en/developers/local-environment/)
2. [The Development Networks page](https://ethereum.org/en/developers/docs/development-networks/#available-projects)

### Is the product open source?

Yes

### GitHub URL

https://github.com/kurtosis-tech/kurtosis

### Documentation URL

https://docs.kurtosis.com/

### Additional context

The Ethereum Foundation uses Kurtosis for end-to-end testing in CI ([most recently with The Merge](https://www.kurtosis.com/blog/testing-the-ethereum-merge) and for replicating failing tests locally for debugging. 

Go here to see the [Kurtosis package](https://github.com/kurtosis-tech/eth2-package) that can be used to spin up a configurable local Ethereum testnet that supports 9 different CL and EL clients, along with some services optionally attached on top (Grafana, Forkmon, Prometheus, transaction spammer).

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by DimaLex9** [comment]
Yes

**Comment by egypjoy** [comment]
Ok
