### ISSUE TITLE
Suggest Taiko as a layer 2

### ISSUE THREAD

**Issue by d1onys1us** [ethereum/ethereum-org-website#9919]
### Name

Taiko

### Logo

![Taiko_Logo_Fluo](https://user-images.githubusercontent.com/13951458/230506906-474e42f7-00e8-478b-9edc-c127ed97f83e.svg)

### Description

Taiko is a fully decentralized, Ethereum-equivalent ZK Rollup (a Type 1 ZK-EVM).

### Website

https://taiko.xyz

### Developer documentation

https://taiko.xyz/docs

### L2BEAT page

https://l2beat.com/scaling/projects/taiko

### Is the project open source?

https://github.com/taikoxyz

### What category of layer 2 is it?

ZK Rollup.

### Does the layer 2 use Ethereum Mainnet for data availability?

The layer 2 is in the testnet phase, but will use Ethereum for data availability. Right now we are using the Sepolia testnet. 

### Which bridges are used to onboard users?

Here is the documentation to use our bridge: https://taiko.xyz/docs/guides/use-the-bridge

Anybody can build their own bridge on Taiko, or do bridging totally by themself via cross chain merkle proof verification.

### Link to dapp ecosystem (if applicable)

https://taiko.xyz/showcase

### Token contract list (if applicable)

https://taiko.xyz/docs/reference/contract-addresses

### What date did the project go live?

Our first testnet was released in Q4 2022: https://taiko.mirror.xyz/-lahy4KbGkeAcqhs0ETG3Up3oTVzZ0wLoE1eK_ao5h4

### Is this project a fork? If yes, which project was forked?

We fork Geth for our client implementation: 

### What wallets support this layer 2?

Any wallet that supports Ethereum, we have also been added to ethereum/chains: https://github.com/ethereum-lists/chains/pull/2442

### How can users and/or developers connect too this layer 2 network?

https://taiko.xyz/docs/reference/rpc-configuration

### Has this project undergone an external security audit and/or a bug bounty?

The layer 2 is a serious project but in testnet phase, similar to the other layer 2's which have been listed here. So we are not in the audit stage yet but will definitely get there. We are totally open source and MIT licensed and the community helps us to find bugs and fix security issues at this stage but our approach to this will just continue to get more robust over time.

### Has the project sustained its users over time?

Yes much of the statistics can be seen in these explorers: https://explorer.a2.taiko.xyz/ and https://status.a2.taiko.xyz/ and https://data.zkpool.io/public/dashboards/JHDtVb3J6E2v1crgDAMkcE0xKqAzDSluJXUufWqe?p_w59_time_range=Last%204%20Hours&p_w60_time_range=Last%204%20Hours&p_w61_time_range=Last%207%20Days

### Is there an active team developing the project?

Yes

### Is there a block explorer?

https://explorer.a2.taiko.xyz/
https://sepolia.etherscan.io/
https://status.a2.taiko.xyz/

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
Hey @d1onys1us, thanks for opening this. 

Since this project is still in testnet phase ill have to close this at the moment. 

I need to update https://ethereum.org/en/contributing/adding-layer-2s/ to be more explicit about the project being live, but this should be consistent with how we treat other products https://ethereum.org/en/contributing/adding-products/#criteria-for-inclusion-the-must-haves

After this has been live, please do reopen for listing!

**Comment by d1onys1us** [comment]
hello @corwintines I was trying to add Taiko here for the original PR (which led to making this issue):

<img width="741" alt="image" src="https://user-images.githubusercontent.com/13951458/234746356-c5e332cd-f490-46ee-aa33-bf636e53ac67.png">

is this section okay for testnet phase? because it says "who is working on", I thought this implied that a testnet phase is fine. also, also Scroll for example is in a testnet phase, and the others are in a mainnet beta.

**Comment by corwintines** [comment]
Ah good point @d1onys1us. I think this is ok to go on https://ethereum.org/en/developers/docs/scaling/zk-rollups/. My mistake. We can hold off from adding to layer-2 data file and add it to this section.

**Comment by d1onys1us** [comment]
> Ah good point @d1onys1us. I think this is ok to go on https://ethereum.org/en/developers/docs/scaling/zk-rollups/. My mistake. We can hold off from adding to layer-2 data file and add it to this section. I'll assign to you to add this :)

thanks @corwintines ! I opened a PR here: https://github.com/ethereum/ethereum-org-website/pull/10136 :)
