### ISSUE TITLE
Change the hero image to a new illustration on the wallet page

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9940]
### Is your feature request related to a problem? Please describe.

On the [Ai Illustration EPIC](https://github.com/ethereum/ethereum-org-website/issues/9090), we agree that some pages can be updated with Ai-generated images to create a more dynamic experience and not overuse the same illustrations.

### Describe the solution you'd like

For the first illustration, we will replace the one on the wallet page with this one.
https://ethereum.org/en/wallets/

![wallet_illustration](https://user-images.githubusercontent.com/1120748/230907401-734e1dc5-8eb3-43eb-8137-556bb80618b5.png)

Figma mockup
![Screen Shot 2023-04-10 02 11 32 PM](https://user-images.githubusercontent.com/1120748/230907572-1573ad32-a852-4a31-8304-2345d53f82f7.png)

### Describe alternatives you've considered

none

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by daredevil3435** [comment]
I want to start contributing with this issue. Can you explain me in detail?

**Comment by nloureiro** [comment]
> @nloureiro I would like to contribute to this issue. How do I get started with?

oh nice!

The basic idea on this is to replace the image on this page, can you do a PR with the image change?

**Comment by daredevil3435** [comment]
> > @nloureiro I would like to contribute to this issue. How do I get started with?
> 
> 
> 
> oh nice!
> 
> 
> 
> The basic idea on this is to replace the image on this page, can you do a PR with the image change?
> 
> 

Yes. Happy to contribute. But how do I find the files in large codebase. I checked but it's kinda overwhelming!! Guide me through this. Thank you!!

**Comment by corwintines** [comment]
@daredevil3435 you'll need to:

- Add this new image asset into the assets folder
- In /src/page-conditionals/wallets.tsx youll need to update the graphql query for the hero image to this new image

Ill assign this to you. Thanks!

**Comment by daredevil3435** [comment]
> @daredevil3435 you'll need to:
> 
> * Add this new image asset into the assets folder
> * In /src/page-conditionals/wallets.tsx youll need to update the graphql query for the hero image to this new image
> 
> Thanks!

thanks for the help!! I'll submit PR soon

**Comment by daredevil3435** [comment]
I did the changes as you said but I'm getting error on testing about Query.
