### ISSUE TITLE
Unick NFT Aggregator

### ISSUE THREAD

**Issue by Unick-io** [ethereum/ethereum-org-website#9946]
### Name

Unick

### Description

Unick.io is a platform for NFTs that operates across multiple blockchains, including Ethereum, Polygon, Arbitrum, Optimism, and more. It offers users a secure and seamless way to buy, sell, trade, and collect NFTs.

### Logo

![Unick-logo-512](https://user-images.githubusercontent.com/125575926/231158979-dcf9d19e-8b15-4854-acbc-2941cc2f2a04.png)

### Brand color

#6E56CB

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/Unick-io

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

Build with trusted web3 technology providers including wagmi, alchemy, thirdweb and reservoir. All of the smart contracts have been audited by the 3rd party providers.

### Can a user access the dapp without creating an account?

Yes, wagmi wallet connect.

### Are dapp funds non-custodial?

No funds stored in the app. All transactions are performed within the wallet only.

### Do you offer community support?

Web: Chat bubble on the website unick.io,
Discord: https://discord.com/invite/gpnzJXBG8m
Twitter:  https://twitter.com/unick_io

### Describe any geographical restrictions on usage of your dapp

N/A

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Unick-io** [comment]
Looking forward to a new, exciting venture :)

**Comment by corwintines** [comment]
Looks like this was just started in February at the earliest. We require 6 months being live. Going to close this out.
