### ISSUE TITLE
[Improvement] As a non Desktop user (tablet and mobile), when I scroll fully down I see a huge white space that could be limited

### ISSUE THREAD

**Issue by trisgerra** [ethereum/ethereum-org-website#9954]
### Describe the bug

The issue is actually in all pages, It's not really a bug but I think it's a good improvement.
When the user open the home page (but also other pages) the .css-13eivrm is creating a huge vertical.

I think we can just change the style for margin-top, I'm happy to work on it as a first issue.

### To reproduce

1. Go to 'any page'
2. Resize the screen to achieve the round button for feedback (.css-13eivrm)
3. Scroll down until the end
4. The page will be completely white because of the button style

### Expected behavior

1. Go to 'any page'
2. Resize the screen to achieve the round button for feedback (.css-13eivrm)
3. Scroll down until the end
4. A small padding should be there, but not an entire white page

### Screenshots

Actual state:
<img width="886" alt="Screenshot 2023-04-12 at 21 47 49" src="https://user-images.githubusercontent.com/3984060/231568562-3c5b3752-63ac-42b8-8dd0-784445d27ae6.png">

Desired: 
<img width="885" alt="Screenshot 2023-04-12 at 21 48 47" src="https://user-images.githubusercontent.com/3984060/231568781-20b2d986-40d0-4013-a3f7-d60e223a4cf1.png">

### Desktop (please complete the following information)

- OS: OSX Monterey 12.5
- Browser:  Chrome / Safari 
- Version: 112.0.5615.49 / 16.0

I tried only these 2 browser, but it's probably in all browser.

### Smartphone (please complete the following information)

- Device: iPhone XR
- OS: iOS 16.3.1
- Browser: Safari

I tried only my personal phone, but it's in all smartphones.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by TylerAPfledderer** [comment]
Hey @trisgerra!

I'm not seeing this issue, and was addressed in #9863. I've checked this out Chrome and Firefox on desktop and mobile.

Have you cleared browser cache?

**Comment by trisgerra** [comment]
Hey @TylerAPfledderer, I had this issue in production but when i tried dev branch in local it was fixed.

I just doubl checked again the page, and it is working as expected in prod. 

Sorry for the duplicate.
