### ISSUE TITLE
Suggest a tutorial

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/ethereum-org-website#9960]
### Tutorial title

Fuzzing introduction

### Tutorial description

fuzz testing vs invariant testing and why they are important

### Tutorial tags

security

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://patrickalphac.medium.com/fuzz-invariant-tests-the-new-bare-minimum-for-smart-contract-security-87ebe150e88c

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment]
I see this has been merged, so im going to close this out. Thanks @PatrickAlphaC!
