### ISSUE TITLE
Bug report: header buttons on L2 dont work

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9972]
### Describe the bug

when clicking on the header buttons on L2 page, nothing happens. Same buttons on other pages work properly.

### To reproduce

1. Go to https://ethereum.org/en/layer-2/
2. Click onheader buttons
3. See error

### Expected behavior

working anchors

### Screenshots

<img width="751" alt="Screenshot 2023-04-17 at 15 52 53" src="https://user-images.githubusercontent.com/100724231/232485941-370e4f3d-6361-4c7e-b0ce-6cea46601137.png">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Noothan-am** [comment]
hey @konopkja, is this issue still open? i wanted to take up this one

**Comment by konopkja** [comment]
@corwintines what is the status here?
