### ISSUE TITLE
Bug report: overflowing text in a button on DAPPs page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9973]
### Describe the bug

text is overflowing on smaller browser sizes (tablet / mobile)

### To reproduce

1. Go to https://ethereum.org/en/dapps/
2. Scroll down to 'Add dapp'
3. See error (mobile / tablet)

### Expected behavior

button text not overflowing, if necessary move button bellow on a new line (on mobile)

### Screenshots

<img width="469" alt="Screenshot 2023-04-17 at 17 38 37" src="https://user-images.githubusercontent.com/100724231/232487055-eda03f2b-da72-45fd-9007-b3e81d885bf3.png">

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MukulKolpe** [comment]
Hey @konopkja, can I work on this issue?

**Comment by konopkja** [comment]
sure, thank you!

**Comment by vaibhavtevatia** [comment]
Hi @konopkja, because of the inactivity on this issue. I've found the bug and fixed it. Can you assign it to me so I can make a PR?

**Comment by konopkja** [comment]
ping @corwintines

**Comment by ItIsOHM** [comment]
Hey @konopkja is this issue still open? I'd like to give it a try :D

**Comment by konopkja** [comment]
> Hey @konopkja is this issue still open? I'd like to give it a try :D

Hello, there is a PR already to fix this. Just waiting for the review: https://github.com/ethereum/ethereum-org-website/pull/10141

This issue will be then closed. I suggest checking other open issues without linked PR firx.

ping @corwintines

**Comment by ItIsOHM** [comment]
@konopkja Can you please suggest where I should look for some good first issues related to Ethereum? I can't find any new ones.

**Comment by minimalsm** [comment]
This was solved as part of https://github.com/ethereum/ethereum-org-website/issues/10020. Closing this out :)
