### ISSUE TITLE
Bug report: L2 numbered list doesnt have aligned numbers

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9974]
### Describe the bug

Aspect ratio has no effect in CSS anymore, see screenshot (the numbers are not aligned to the centre of the circle)

### To reproduce

1. Go to https://ethereum.org/en/layer-2/
2. Scroll down to Layer 1 paragraph
3. See error

### Expected behavior

numbers in the centre of the circle

### Screenshots

![Screen Shot 2023-04-17 07 58 09 PM 1](https://user-images.githubusercontent.com/100724231/232487599-e4fefb5e-c62d-4feb-96c7-b3f81da80fdc.png)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MahendraBishnoi29** [comment]
assign it to me @konopkja

**Comment by konopkja** [comment]
reassigned to @SimardeepSingh1450 , thank you

**Comment by SimardeepSingh1450** [comment]
@konopkja , I am facing this **JAVASCRIPT HEAP OUT OF MEMORY** issue when running yarn start on my local dev environment, can you help me out ?
![heap-out-of-memory](https://github.com/ethereum/ethereum-org-website/assets/92221517/5d02b414-40aa-4c7c-8347-09624c967ef4)

**Comment by MahendraBishnoi29** [comment]
@konopkja I've already fixed it but for some reasons, I'm not able to update my forked repo or can't even push the changes from my local machine otherwise I would've raised a PR so please give me a few hours for it, thanks

**Comment by SimardeepSingh1450** [comment]
![ethereum-count-fix](https://github.com/ethereum/ethereum-org-website/assets/92221517/21392907-0688-496b-ad61-b78f30ef9f5e)
@konopkja Here is a preview of the fix and I have created PR as well at #10158, please review these changes and merge.

**Comment by nhsz** [comment]
Fixed by #10158
