### ISSUE TITLE
Feature request: change links to list

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9975]
### Is your feature request related to a problem? Please describe.

these two links should be list format on https://ethereum.org/en/layer-2/ (see screenshot)

### Describe the solution you'd like

these two links should be list format on https://ethereum.org/en/layer-2/ (see screenshot)

![Screenshot 2023-04-17 at 17 45 51](https://user-images.githubusercontent.com/100724231/232488422-ff82823d-7845-4c37-8e05-52b6b7cb5a0f.png)

### Describe alternatives you've considered

NA

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MahendraBishnoi29** [comment]
@konopkja I'll take care of it 👍🏻

**Comment by tarunsamanta2k20** [comment]
> @konopkja I'll take care of it 👍🏻

@konopkja I have completed this issue. Please don't create any PRs. FCFS basis.

**Comment by MahendraBishnoi29** [comment]
> > @konopkja I'll take care of it 👍🏻
> 
> @konopkja I have completed this issue. Please don't create any PRs. FCFS basis. 

Alright @tarunsamanta2k20 👍🏻

**Comment by konopkja** [comment]
can you link the PR?
