### ISSUE TITLE
Bug report: wrong highlight style on header buttons

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9976]
### Describe the bug

Overflow hidden

### To reproduce

1. Go to any custom template (for example https://ethereum.org/en/layer-2/)
2. use dark theme
3. mouse over header buttons

### Expected behavior

proper styling shown according to the design system

### Screenshots

![Screenshot 2023-04-17 at 17 51 17](https://user-images.githubusercontent.com/100724231/232489327-e3f3b956-8a74-4e94-85fa-80b6da02a77f.png)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Vayras** [comment]
Hi @konopkja can you assign this issue to me?

**Comment by Noothan-am** [comment]
hey @konopkja  is this issue still open?

**Comment by konopkja** [comment]
> hey @konopkja is this issue still open?

I think so. @Vayras  still interested to work on this? If not I can reassign it to @Noothan-am

**Comment by Noothan-am** [comment]
hey @konopkja i have fixed this bug can i send pr?

**Comment by Noothan-am** [comment]
hey @konopkja I think I figured it out 

## After removing css-i6bazn class it is working fine 
![image](https://user-images.githubusercontent.com/100135382/235451649-fb2c4d6b-acbb-4d90-87f7-37f9fb76d432.png)

![image](https://user-images.githubusercontent.com/100135382/235451741-3c563dcd-62ae-4368-b09b-14f0bbed9e38.png)

so as I am new to open source and Chakra UI I am unable to reach this code can you please help me?

**Comment by konopkja** [comment]
@corwintines @pabloped  ping

**Comment by pabloped** [comment]
Hi!
@Noothan-am you can follow the instructions in the readme page in "How to contribute" section.
You need to fork this repo and when you make the changes you can submit a PR, be careful to follow the instructions in [https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword](url) to link to this issue.

In this case the page that are referring this issue are located in: src/pages/layer-2.tsx, there you can see the component that render the buttons, by default chacra puts "overflow:hidden" to any wrap component, to solve this issue I think that an approach could be to override this style with overflow:visible .
