### ISSUE TITLE
Suggest a wallet: Dawn Wallet

### ISSUE THREAD

**Issue by thomas-waite** [ethereum/ethereum-org-website#9977]
### Wallet name

Dawn

### Wallet description

Dawn is a mobile Ethereum wallet for iOS that is focused on allowing you to use Ethereum apps in the fewest taps, straight from Safari.

### Wallet logo

![Icon-App-iTunes](https://user-images.githubusercontent.com/20632187/232484943-9a77e79b-b905-4194-ba59-01e47e08c7aa.png)

### Background color for brand logo

#000000

### URL to the project

https://www.dawnwallet.xyz/

### When did the wallet go live to users?

App store: 14/04/2023, Public beta: 01/03/2023

### Does the wallet have an active development team?

Yes, two co-founders working full time. Open source wallet SDK: https://github.com/dawnwallet/dawn-key-management

### Is the wallet globally accessible?

Globally accessible, no KYC

### Is the wallet available in multiple languages?

English

### What social links are there for the project?

https://twitter.com/dawn_wallet
https://discord.com/invite/W9TwvXGn8Y
https://t.me/+MoyzFlJOVsBkNDI0

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes. iOS is supported: https://apps.apple.com/us/app/dawn-ethereum-wallet/id1673143782 

### Does the wallet have a desktop app? If yes, which operating systems are supported (Windows, Mac, Linux)?

No

### Does the wallet have a browser extension? If yes, which browsers are supported (Chromium, Firefox, Safari)?

No

### Is it a hardware wallet?

No

### Is the source code for the wallet fully open-source?

All code which touches the private key, our wallet SDK is open sourced: https://github.com/dawnwallet/dawn-key-management . UI code is not open sourced

### What license is the wallet software released under?

Wallet SDK is under: GPL-3.0 license

### Who holds the private keys?

The wallet is fully self-custodial, users have access to their private keys.

Our company never has access to private keys. 

If our company was to disappear, users would still be able to access their funds. 

### Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

All code which touches a private key in the wallet (our wallet SDK) has been open sourced here: https://github.com/dawnwallet/dawn-key-management 

Members of the community have reviewed the open source code. 

We have implemented industry leading security practices, including:
- Using the iPhone secure enclave to encrypt the users private key
- Storing the encrypted private key in the iPhone keychain
- Using FaceID to authenticate access to decrypting the private key in order to sign a transaction
- Scanning transactions that a user is prompted to sign by a dapp with Blowfish (https://blowfish.xyz/) and blocking malicious transactions

### Has the wallet's smart contract code or security modules been audited?

NA - we don't have smart contract code

### Does the wallet have an internal security team?

The co-founders (both Ethereum and mobile engineers) are the security team

### Any other security testing that should be noted?

We have implemented industry leading security practices, including:
- Using the iPhone secure enclave to encrypt the users private key
- Storing the encrypted private key in the iPhone keychain
- Using FaceID to authenticate access to decrypting the private key in order to sign a transaction
- Scanning transactions that a user is prompted to sign by a dapp with Blowfish (https://blowfish.xyz/) and blocking malicious transactions

### Scam protection?

Yes. We have integrated with the security tool Blowfish (https://blowfish.xyz/). We block any domains that Blowfish identifies as fraudulent. 

We also use Blowfish to scan all transactions that a user is prompted to sign on Mainnet and Polygon. The results are:
- If the transaction is identified as malicious, we block it
- If the transaction is suspicious, we show a warning to the user 
- We show the simulated state changes that will occur if a user were to sign the transaction

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support importing Ethereum RPC endpoints?

No - support will be added in a future version

### Does the wallet support viewing and interacting with NFTs?

No

### Does the wallet support connecting to Ethereum applications?

Yes. Dawn features a native Safari extension, which allows a user to connect to and interact with any Dapp direct from the Safari browser.

### Does the wallet support staking directly?

No

### Does the wallet support swaps directly?

No

### Does the wallet support multi-chain networks?

No

### Does the wallet support Ethereum layer 2 networks?

Yes - Polygon, Arbitrum, Optimism

### Does the wallet allow the user to customize gas fees?

Yes - when a user sends a transaction they can choose from a "Fast" or "Standard" gas fee

### Does the wallet support sending transactions to ENS addresses?

Yes - natively integrated into ENS

### Does the wallet support importing or automatically querying and displaying ERC-20 tokens?

Yes - user ERC20 balances are automatically shown in the wallet

### Does the wallet support EIP-1559 (type 2) transactions?

No - supported will be added in a couple weeks

### Does the wallet have fiat on-ramps through credit/debit cards, wire transfers, or bank transfers (ACH)?

Yes - Ramp on/off ramp

### Does the wallet support withdrawals to fiat?

Yes - Ramp on/off ramp

### Is the wallet a multi-signature wallet?

No

### Does the wallet support social recovery?

No

### Who can the ethereum.org team can contact regarding the wallet in future?

The two co-founders are best to contact:

Tom Waite
--------------
Twitter: https://twitter.com/tom_waite_ 
Telegram: @tomwaite

Isaac Rodriguez
-----------------
Twitter: https://twitter.com/koide_dev
Telegram: @isaacro

### Does the wallet have a dedicated support team?

Yes. The co-founders are the support team, we are responding to any support issues in our dedicated Telegram support channel (https://t.me/+MoyzFlJOVsBkNDI0) and through our Discord. 

We highly value providing a first class support experience and are responding at least within a couple of hours. 

We are rolling out Intercom, so users can talk to us immediately within the wallet if they have any issues.

### What educational resources/documentation do you provide to users?

Website: https://www.dawnwallet.xyz/ 

There is also onboarding within the wallet itself.

### Does the wallet have any integrated tools not mentioned above?

The Safari extension and in-browser native popup are the main stand out features of Dawn

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by corwintines** [comment]
Hey @thomas-waite

Overall think this wallet has potential. But wanted to comment on the fact that I think some documentation would be necessary here for both us to review, and the users would benefit from this. 

Other reason for closing this at this time is the wallet went live ~2 months ago. We do state we expect a wallet to be live for 6 months before consideration: https://ethereum.org/en/contributing/adding-wallets/
