### ISSUE TITLE
Feature request: switch button style 

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#9978]
### Is your feature request related to a problem? Please describe.

This is the first button users see on the homepage. As such it should be in primary button style instead of secondary.

### Describe the solution you'd like

Change the style to primary button style.

### Describe alternatives you've considered

NA

### Additional context

![Screenshot 2023-04-17 at 17 55 22](https://user-images.githubusercontent.com/100724231/232490547-c62f8734-abcc-40e4-969c-063844f292bf.png)

homepage, bellow the header

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Saiteja-Basam** [comment]
Hi @konopkja  Can you assign this to me?

**Comment by Vayras** [comment]
Hello @konopkja can I contribute towards this ?

**Comment by konopkja** [comment]
> Hello @konopkja can I contribute towards this ?

hello, this has been already assigned to someone else, please feel free to check other issues that have not been assigned to anyone yet.

**Comment by Vayras** [comment]
Okay, Thank you
